### ISSUE TITLE
wrong units for diivoo water timer 

### ISSUE THREAD

**Issue by nelbs** [make-all/tuya-local#1007]
I found a little bug...

The homeassistant number entity(number.dual_water_timer_irrigation_time_2) of the diivoo water timer does not have the right units. The entity is showing minutes instead of hours. 

![Screenshot_2023-08-19-15-01-37-13_c3a231c25ed346e59462e84656a70e50](https://github.com/make-all/tuya-local/assets/6464671/1c4e6bc6-375a-4d0e-bc48-53e7d6792262)

![Screenshot_2023-08-19-15-02-10-07_a3b3f7ff182fbca1933b088238f0f0da](https://github.com/make-all/tuya-local/assets/6464671/3e26906a-7e5d-4e76-96d2-d2631a308244)

**Comment by make-all** [comment]
This would suggest the max 86400 is also incorrect.

Are you able to gather the result of Query Things Data Model API function for the device?  It was originally submitted by PR, so I don't have any details like that.  The submitter may have simply copied from other devices without checking things like units and ranges.

**Comment by nelbs** [comment]
Yeah sure...

{
    "result": {
        "model": "{\"modelId\":\"000004dppk\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\","
                 "\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":11,\"accessMode\":\"ro\","
                 "\"code\":\"battery_percentage\",\"description\":\"\",\"extensions\":{"
                 "\"iconName\":\"icon-dp_battery\",\"attribute\":\"1024\"},\"name\":\"主电池电量\",\"typeSpec\":{"
                 "\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,"
                 "\"unit\":\"%\"}},{\"abilityId\":19,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"\","
                 "\"extensions\":{\"iconName\":\"icon-baojing\",\"scope\":\"fault\",\"attribute\":\"1024\"},"
                 "\"name\":\"故障告警\",\"typeSpec\":{\"label\":[\"1\",\"2\"],\"maxlen\":2,\"type\":\"bitmap\","
                 "\"typeDefaultValue\":0}},{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"normal_timer\","
                 "\"description\":\"\",\"name\":\"普通定时\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},"
                 "{\"abilityId\":102,\"accessMode\":\"rw\",\"code\":\"cycle_timer\",\"description\":\"\","
                 "\"name\":\"循环定时\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},{\"abilityId\":103,"
                 "\"accessMode\":\"rw\",\"code\":\"countdown_2\",\"description\":\"\",\"extensions\":{"
                 "\"iconName\":\"icon-dp_time2\",\"attribute\":\"4096\"},\"name\":\"开关2倒计时\",\"typeSpec\":{"
                 "\"max\":1440,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,"
                 "\"unit\":\"min\"}},{\"abilityId\":104,\"accessMode\":\"rw\",\"code\":\"switch_2\","
                 "\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"4096\"},"
                 "\"name\":\"开关2\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":105,"
                 "\"accessMode\":\"rw\",\"code\":\"switch_1\",\"description\":\"\",\"extensions\":{"
                 "\"iconName\":\"icon-dp_power2\",\"attribute\":\"4096\"},\"name\":\"开关1\",\"typeSpec\":{"
                 "\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":106,\"accessMode\":\"rw\","
                 "\"code\":\"countdown_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\","
                 "\"attribute\":\"4096\"},\"name\":\"开关1倒计时\",\"typeSpec\":{\"max\":1440,\"min\":0,\"scale\":0,"
                 "\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"min\"}},{\"abilityId\":110,"
                 "\"accessMode\":\"ro\",\"code\":\"use_time_2\",\"description\":\"\",\"extensions\":{"
                 "\"iconName\":\"icon-dp_time3\",\"attribute\":\"4096\",\"trigger\":\"direct\"},\"name\":\"使用时间2\","
                 "\"typeSpec\":{\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\","
                 "\"typeDefaultValue\":0,\"unit\":\"s\"}},{\"abilityId\":111,\"accessMode\":\"ro\","
                 "\"code\":\"use_time_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time3\","
                 "\"attribute\":\"4096\",\"trigger\":\"direct\"},\"name\":\"使用时间1\",\"typeSpec\":{\"max\":86400,"
                 "\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"s\"}},"
                 "{\"abilityId\":112,\"accessMode\":\"ro\",\"code\":\"status_1\",\"description\":\"\","
                 "\"name\":\"状态1\",\"typeSpec\":{\"range\":[\"manual\",\"auto\",\"idle\"],\"type\":\"enum\","
                 "\"typeDefaultValue\":\"manual\"}},{\"abilityId\":113,\"accessMode\":\"ro\",\"code\":\"status_2\","
                 "\"description\":\"\",\"name\":\"状态2\",\"typeSpec\":{\"range\":[\"manual\",\"auto\",\"idle\"],"
                 "\"type\":\"enum\",\"typeDefaultValue\":\"manual\"}},{\"abilityId\":114,\"accessMode\":\"rw\","
                 "\"code\":\"weather_delay2\",\"description\":\"\",\"name\":\"天气延时2\",\"typeSpec\":{\"range\":["
                 "\"OFF\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\"],\"type\":\"enum\","
                 "\"typeDefaultValue\":\"OFF\"}},{\"abilityId\":117,\"accessMode\":\"rw\",\"code\":\"weather_delay\","
                 "\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_light2\",\"attribute\":\"4096\"},"
                 "\"name\":\"天气延时\",\"typeSpec\":{\"range\":[\"OFF\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\"],"
                 "\"type\":\"enum\",\"typeDefaultValue\":\"OFF\"}}]}]}"
    },

**Comment by nelbs** [comment]
The "Get the specifications and properties of the device" tool shows a better overview....

{
  "result": {
    "category": "ggq",
    "functions": [
      {
        "code": "normal_timer",
        "desc": "{\"maxlen\":255}",
        "name": "普通定时",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "countdown_2",
        "desc": "{\"unit\":\"min\",\"min\":0,\"max\":1440,\"scale\":0,\"step\":1}",
        "name": "灌溉时间2",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":1440,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_2",
        "desc": "{}",
        "name": "阀门控制2",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_1",
        "desc": "{}",
        "name": "阀门控制1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "desc": "{\"unit\":\"min\",\"min\":0,\"max\":1440,\"scale\":0,\"step\":1}",
        "name": "灌溉时间1",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":1440,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "battery_percentage",
        "name": "主电池电量",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "normal_timer",
        "name": "普通定时",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "countdown_2",
        "name": "灌溉时间2",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":1440,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_2",
        "name": "阀门控制2",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_1",
        "name": "阀门控制1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "name": "灌溉时间1",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":1440,\"scale\":0,\"step\":1}"
      },
      {
        "code": "use_time_2",
        "name": "单次使用时间2",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "use_time_1",
        "name": "单次使用时间1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ]

**Comment by nelbs** [comment]
Thanks!
