### ISSUE TITLE
Turn on/off not working

### ISSUE THREAD

**Issue by aizquierdoc** [make-all/tuya-local#1008]
Hello everyone,

I am testing the integration and everything is perfect until I press the button. Nothing happens on the switch.

If I turn on/off from the Tuya or Local Tuya integration, the indicator changes in Tuya Local. If I do it from the Tuya Local integration, the indicator shows the change but the switch does not turn on/off.

Any idea why it happens?

Greetings!

**Comment by make-all** [comment]
Either your device_id or your local_key is incorrect.  There are several existing issues reporting the same thing, and eventually they always turn out to be one of these.

**Comment by aizquierdoc** [comment]
Thank you,

I've reviewed the information and it seems to be fine, although I can't get to the instructions in the repository and I'm not sure.

This is the information on the Tuya website and in core.config_entries. I don't get it.

![Image](https://github.com/make-all/tuya-local/assets/35219189/2e32991d-a27a-40ff-9ffd-9e161c2d367d)

**Comment by aizquierdoc** [comment]
Ok, I found it. It is not the uuid but the Device Id.

When adding a new device it asks you for the uuid and hence the error.

All perfect thanks!
