### ISSUE TITLE
New thermostat support

### ISSUE THREAD

**Issue by WildeRNS** [make-all/tuya-local#101]
Hello, have this thermostat: https://a.aliexpress.com/_mLsYT7w
If you can, please add it to your integration. Thanks

Debug info:
`{
  "result": {
    "active_time": 1639047183,
    "biz_type": 18,
    "category": "wk",
    "create_time": 1639047183,
    "icon": "smart/icon/bay15868568226346hzr/f6951bd4dbe53137a47e3cb07077c42b.png",
    "id": "Edited",
    "ip": "193.19.253.93",
    "lat": "Edited",
    "local_key": "Edited",
    "lon": "Edited",
    "model": "",
    "name": "Панель у кухні",
    "online": true,
    "owner_id": "12366373",
    "product_id": "csp3rfvhj6ppmaps",
    "product_name": "MTS700WB",
    "status": [
      {
        "code": "switch",
        "value": true
      },
      {
        "code": "mode",
        "value": "hot"
      },
      {
        "code": "work_state",
        "value": "normal_temp_set"
      },
      {
        "code": "temp_set",
        "value": 21
      },
      {
        "code": "temp_set_f",
        "value": 70
      },
      {
        "code": "temp_unit_convert",
        "value": "c"
      },
      {
        "code": "temp_current",
        "value": 21
      },
      {
        "code": "temp_correction",
        "value": -1
      },
      {
        "code": "temp_current_f",
        "value": 70
      },
      {
        "code": "factory_reset",
        "value": false
      },
      {
        "code": "countdown",
        "value": "cancel"
      },
      {
        "code": "countdown_left",
        "value": 0
      }
    ],
    "sub": false,
    "time_zone": "+02:00",
    "uid": "Edited",
    "update_time": 1639382371,
    "uuid": "Edited"
  },
  "success": true,
  "t": 1640716595546
}`

**Comment by make-all** [comment]
The above debug info is missing the dp ids.  If you can look in the HA log after trying to add the device to this integration, the list of ids and values should be able to be matched up with the values above.  And if you have set up a Tuya developer account for getting the local key, or adding to the default cloud Tuya integration, then you can browse the API Explorer there, which somewhere will contain the ranges and possible values for some of the items.

**Comment by WildeRNS** [comment]
> The above debug info is missing the dp ids. If you can look in the HA log after trying to add the device to this integration, the list of ids and values should be able to be matched up with the values above. And if you have set up a Tuya developer account for getting the local key, or adding to the default cloud Tuya integration, then you can browse the API Explorer there, which somewhere will contain the ranges and possible values for some of the items.

Where I can find DPs in API Explorer?

**Comment by make-all** [comment]
Under "Smart Home Management System" / "Device Control" / "Get Device Specification Attribute", you can get the full information including ids.

**Comment by make-all** [comment]
But there are often additional local ids that are not available through the cloud API, so to improve device recognition, it is also useful to have the log message from HA when you first attempt to connect the device, or a local capture of full device state from tuya-cli or tinytuya etc.

**Comment by WildeRNS** [comment]
> Under "Smart Home Management System" / "Device Control" / "Get Device Specification Attribute", you can get the full information including ids.

thanks!
`{
  "result": {
    "category": "wk",
    "functions": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "dp_id": 2,
        "type": "Enum",
        "values": "{\"range\":[\"cold\",\"hot\"]}"
      },
      {
        "code": "temp_set",
        "dp_id": 16,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-20,\"max\":105,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_set_f",
        "dp_id": 17,
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":-4,\"max\":221,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_unit_convert",
        "dp_id": 23,
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "temp_correction",
        "dp_id": 27,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":-5,\"max\":5,\"scale\":0,\"step\":1}"
      },
      {
        "code": "factory_reset",
        "dp_id": 39,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown",
        "dp_id": 41,
        "type": "Enum",
        "values": "{\"range\":[\"cancel\",\"1h\"]}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "dp_id": 2,
        "type": "Enum",
        "values": "{\"range\":[\"cold\",\"hot\"]}"
      },
      {
        "code": "work_state",
        "dp_id": 3,
        "type": "Enum",
        "values": "{\"range\":[\"manual\"]}"
      },
      {
        "code": "temp_set",
        "dp_id": 16,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-20,\"max\":105,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_set_f",
        "dp_id": 17,
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":-4,\"max\":221,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_unit_convert",
        "dp_id": 23,
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "temp_current",
        "dp_id": 24,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-20,\"max\":105,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_correction",
        "dp_id": 27,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":-5,\"max\":5,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_current_f",
        "dp_id": 29,
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":-4,\"max\":221,\"scale\":0,\"step\":1}"
      },
      {
        "code": "factory_reset",
        "dp_id": 39,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown",
        "dp_id": 41,
        "type": "Enum",
        "values": "{\"range\":[\"cancel\",\"1h\"]}"
      },
      {
        "code": "countdown_left",
        "dp_id": 42,
        "type": "Integer",
        "values": "{\"unit\":\"sec\",\"min\":0,\"max\":3600,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1641547882739
}`

**Comment by WildeRNS** [comment]
Can confirm, thermostat working. Thanks
