### ISSUE TITLE
Since the new HA update again "migration errors" 

### ISSUE THREAD

**Issue by PeterDemuynck** [make-all/tuya-local#1015]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior including the device the issue was observed with:

**Expected behavior**

**Additional context**

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

**Comment by make-all** [comment]
Did you forget something?
