### ISSUE TITLE
Request support for Proscenic A9 Air Purifier

### ISSUE THREAD

**Issue by RobusX** [make-all/tuya-local#1019]
I am wondering why is Proscenic A9 Air Purifier still not supported:
https://www.amazon.de/-/en/Proscenic-A9-Purifier-Performance-Sufferers/dp/B096M3Z8VV/ref=sr_1_1?crid=R5KVQACQ6S40&keywords=Proscenic+A9&qid=1692793759&sprefix=proscenic+a9%2Caps%2C120&sr=8-1

But I found among Tuya local devices Proscenic A8, which IS supported.
Possibly is much more users with A9, than with A8 ( I have 2x A9 in my house). 

Is possible to implement also support for A9 ?
I have A9 in HA linked via the official Tuya integration, but I cannot set fan (vent) speed...always only one.
This is, why I found Tuya Local and open a new req.

All info i found about A9 issues in HA is here:
https://github.com/tuya/tuya-home-assistant/issues/727

and here:
https://community.home-assistant.io/t/proscenic-purifier-a8/315680

I will really appreciate if you manage to include A9 via Tuya Local (and many others too).
If you need any additional (json) data, please let me know what exactly is needed (link on the official tuya page).
Thank you very much.
Rob

**Comment by make-all** [comment]
There is no local protocol info in any of the links.
I already put a lot of effort into explaining the information needed in the issue template, as I do not want to spend time explaining it personally to every reporter.  If you cannot put the effort in yourself, then I can only close the issue if there is not sufficient info.
