### ISSUE TITLE
Timer value label is "min", should be "sec"

### ISSUE THREAD

**Issue by jdavidr17** [make-all/tuya-local#102]
I have several tuya compatible smart plugs with energy monitoring... all connected working great with the integration.  I decided for one of the plugs to enable and use the timer entity that is included in the integration.  In testing it, I set it to 2 minutes, but it timed out almost immediately.  It took a while but I figured out that the native units of the timer value entered is seconds, whereas the units are labeled min in the integration.  Confirmed by changing value to 120, and it now turns off in 2 minutes.  Should be an easy fix!
thanks for your work on this integration -- viva la local!

d

**Comment by make-all** [comment]
Yes, there isn't enough documentation to know what all the various units are for timers, so they are currently just a guess.
Which device is this, so I can change it, and do you know the range?  Most devices seem to be up to 24 hours, but some are 6 or 12 hours.

**Comment by jdavidr17** [comment]
Hi, thanks for the quick reply, the switch is 
Manufacturer: ‎BN-LINK
‎Part Number: BNC-60/U133TJ
https://help.bn-link.com/hc/en-us/articles/360042269832-BNC-60-U133TJ
Unfortunately was not Tasmota flashable:  https://templates.blakadder.com/bn-link_BNC-60_U133TJ.html
Purchased here:  https://www.amazon.com/BN-LINK-Monitoring-Function-Compatible-Assistant/dp/B07CVPKD8Z
Manual:  https://cdn.shopify.com/s/files/1/0018/2521/0421/files/U133T.pdf?v=14915309573559959467

I read through the manual, BN-Link support pages, and all amazon questions+reviews having to do with "timer" and I'm not able to find the official timer range listed.  On the tuya-smart android app, the countdown timer is in hours:minutes (no seconds) and the minimum is 0 hours 1 minute and the max is 24 hours 0 minutes.  

hope this helps,
thanks,
d

**Comment by nicoolaro** [comment]
@make-all i have similar issue but 24 hour period counting as 24 minutes. Example i set 1h heater is shut off after 1 minute. My Heater (Although not Kogan brand) is recognized as "Kogan KAWFHTP" .

Everything else works!

**Comment by make-all** [comment]
I tested here on my Kogan KAHTP heater and it is the same.  I don't use the timer on the heater myself, and initially guessed the scale based on the manual and the Tuya app only allowing to set whole hours, but never got around to testing, as it was part of a bulk change adding secondary entities across a large number of devices.

**Comment by make-all** [comment]
Was this meant for issue #115?

**Comment by nicoolaro** [comment]
> Was this meant for issue #115?

yes! wrong issue :)
