### ISSUE TITLE
Detected blocking call to sleep inside the event loop.

### ISSUE THREAD

**Issue by Tikosso** [make-all/tuya-local#1021]
Logger: homeassistant.util.async_
Source: util/async_.py:166
First occurred: 23 sierpnia 2023 22:39:34 (8 occurrences)
Last logged: 23 sierpnia 2023 22:55:20

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 76: self._api = tinytuya.Device(dev_id, address, local_key)

**Comment by make-all** [comment]
Duplicate of #482
