### ISSUE TITLE
Request support for PEARL Xystec NX-4986-919 WLAN-USB-3.0-Hub

### ISSUE THREAD

**Issue by pdecat** [make-all/tuya-local#1031]
# Log Message

```
2023-08-26 14:09:49.611 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches simple_triple_switch_timer with quality of 75%. DPS: {"updated_at": 1693051788.6278589, "1": true, "2": false, "3": false, "4": false, "9": 0, "10": 0, "11": 0, "12": 0}
2023-08-26 14:09:49.613 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/
```

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"000002ikla\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"16\"},\"name\":\"USB 1\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"switch_2\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"16\"},\"name\":\"USB 2\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":3,\"accessMode\":\"rw\",\"code\":\"switch_3\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"16\"},\"name\":\"USB 3\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":4,\"accessMode\":\"rw\",\"code\":\"switch_4\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"16\"},\"name\":\"USB 4\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":9,\"accessMode\":\"rw\",\"code\":\"countdown_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\"},\"name\":\"USB1倒计时\",\"typeSpec\":{\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"s\"}},
{\"abilityId\":10,\"accessMode\":\"rw\",\"code\":\"countdown_2\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\"},\"name\":\"USB2倒计时\",\"typeSpec\":{\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"s\"}},
{\"abilityId\":11,\"accessMode\":\"rw\",\"code\":\"countdown_3\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\"},\"name\":\"USB3倒计时\",\"typeSpec\":{\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"s\"}},
{\"abilityId\":12,\"accessMode\":\"rw\",\"code\":\"countdown_4\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\"},\"name\":\"USB4倒计时\",\"typeSpec\":{\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"s\"}}]}]}"
  },
  "success": true,
  "t": 1693051899072,
  "tid": "b5b3f6f5440911eeb3f09e6a0abc163a"
}
```

# Product ID

`ckg60n4x6qakegxo`

Edit: fixed the product id, the ~`key5nck4tavy43jp`~ was the product key from my previous Local Tuya integration I'm migrating from, and it does not match anything from the Tuya API now that I re-checked.

# Information about how the device functions

Manufacturer link: http://www.xystec.info/WiFi-USB-3-0-Hub-mit-4-einzeln-steuerbaren-Ports-p-NX-4986-919.shtml

Purchased from PEARL at: https://www.pearl.fr/article/NX4986/hub-4-ports-usb-3-0-connecte-compatible-avec-commandes-vocales

**Comment by make-all** [comment]
This may be able to work with the quad_powerstrip config.
If not, a new config will be needed without the optional sensors included.

**Comment by pdecat** [comment]
I've tried adding the product_id of my device to `quad_powerstrip.yaml` but Tuya Local still does not propose to select it:

```
2023-08-30 07:26:49.565 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches simple_triple_switch_timer with quality of 75%. DPS: {"updated_at": 1693373208.779516, "1": true, "2": false, "3": false, "4": false, "9": 0, "10": 0, "11": 0, "12": 0}
```

![image](https://github.com/make-all/tuya-local/assets/318490/2526b556-8f4a-4bc9-aea9-0ded8fa61cb8)

**Comment by make-all** [comment]
You would need to use the latest version of quad_powerstrip.yaml from git,
as I made some changes yesterday that should make this compatible with your
device.

**Comment by pdecat** [comment]
Updated `quad_powerstrip.yaml`, no better :confused: (even restarted Home Assistant in case it was cached).

```
2023-08-30 08:16:02.880 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches simple_triple_switch_timer with quality of 75%. DPS: {"updated_at": 1693376162.0194623, "1": true, "2": false, "3": false, "4": false, "9": 0, "10": 0, "11": 0, "12": 0}
```
![image](https://github.com/make-all/tuya-local/assets/318490/9b69884b-0e6c-4535-9eb6-ea5258268333)

**Comment by make-all** [comment]
Sorry, I was being blocked from pushing the changes since there were new merged pull requests I did not have locally.  Now the change to quad_powerstrip.yaml has been pushed it should work.

**Comment by pdecat** [comment]
Got the update

Please note that I fixed the product id earlier this morning, the correct one is `ckg60n4x6qakegxo`.

The ~`key5nck4tavy43jp`~ was the product *key* from my previous Local Tuya integration I'm migrating from, and it does not match anything from the Tuya API now that I re-checked.

**Comment by pdecat** [comment]
It is ok now, thanks again!

I applied this change locally:
```
diff quad_powerstrip.yaml.orig quad_powerstrip.yaml
5c5
<   - id: key5nck4tavy43jp
---
>   - id: ckg60n4x6qakegxo
```

![image](https://github.com/make-all/tuya-local/assets/318490/94778f7d-e373-4c51-9b0a-96644fd3bbeb)

![image](https://github.com/make-all/tuya-local/assets/318490/aea70011-48d4-48d6-a541-a922fb02efba)

**Comment by make-all** [comment]
Possibly a wrong device_id (device_id differs from uuid for some devices, so if you took it from uuid it may be wrong)

**Comment by make-all** [comment]
This seems to be due to the forced polling for energy monitoring sensors, which this device does not have, failing.
Probably it will need a separate config to avoid these errors.

**Comment by pdecat** [comment]
Working great with the latest changes, no error so far :crossed_fingers:

![image](https://github.com/make-all/tuya-local/assets/318490/4b50c1a5-9d3b-42b0-8afc-1e5b4be6f1eb)
![image](https://github.com/make-all/tuya-local/assets/318490/97f3b255-a340-4d07-b940-689e80a7470f)
