### ISSUE TITLE
MJZM GL-3000-WiFi Thermostat

### ISSUE THREAD

**Issue by Lesboy72** [make-all/tuya-local#1048]
I found a tool called moes_bht002_thermostat_c that works under HA, which can be used for the object thermostat type after integration. One thing is missing from this, namely that there is no feedback when the heating is switched on, a tongue of flame or similar that indicates that the heating is currently working.

![thermostat](https://github.com/make-all/tuya-local/assets/101478461/906875a7-7482-4ec5-b628-b2c231a60564)

**Comment by Lesboy72** [comment]
Hello Jason!
Why did you close my request for support?

**Comment by make-all** [comment]
It isn't clear what you are asking for from this integration. It just seems like a complaint about a missing feature on the device display to me.

**Comment by Lesboy72** [comment]
Could I request support specifically for this device (MJZM GL-3000)?
