### ISSUE TITLE
Unable to connect to the device

### ISSUE THREAD

**Issue by antoweb** [make-all/tuya-local#1050]
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**
Adding BHT-6000 Thermostat integrartion report an error like image attached
![image](https://github.com/make-all/tuya-local/assets/32364871/4c54da30-4176-47fd-8aba-07b2841b31c3)

**To Reproduce**
Steps to reproduce the behavior including the device the issue was observed with:

**Expected behavior**

**Additional context**

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

**Comment by antoweb** [comment]
Also tried with protocol auto nothing else

**Comment by make-all** [comment]
See discussion #522 for possible causes and solutions.  Without further evidence this cannot be considered a bug, as there are too many external variables that can affect the ability to make a connection to the device, and the integration is only reporting the underlying network connectivity issue.
