### ISSUE TITLE
local key location

### ISSUE THREAD

**Issue by toofewacres** [make-all/tuya-local#1053]
In the read.me, the location that you give to find the local key in the Tuya Developer App is now in "Cloud / API Explorer
Smart Home Device System / Device Management / Get device details"

**Comment by make-all** [comment]
For some reason you seem to still have the old layout on iot.tuya.com.  For most users the layout of Cloud / API Explorer changed a couple of months ago to a new layout.  The instructions in README.md are for the new layout.

**Comment by toofewacres** [comment]
Strange... I logged in again this morning and it's still the same...
Oh well, I found the local key and all is well.

Nice work.
Thanks

⁣Get TypeApp for Android ​
