### ISSUE TITLE
Request support for [device description]

### ISSUE THREAD

**Issue by iindigoo** [make-all/tuya-local#1058]
# Log Message

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:296
Integration: Tuya Local (documentation, issues)
First occurred: 02:08:47 (1 occurrences)
Last logged: 02:08:47

Simple switch receive loop error <class 'UnboundLocalError'>:cannot access local variable 'err' where it is not associated with a value
Traceback (most recent call last):
  File "/config/custom_components/tuya_local/device.py", line 296, in async_receive
    poll = await self._hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tinytuya/core.py", line 1488, in receive
    return self._send_receive(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tinytuya/core.py", line 1085, in _send_receive
    sock_result = self._get_socket(False)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tinytuya/core.py", line 948, in _get_socket
    return err
           ^^^
UnboundLocalError: cannot access local variable 'err' where it is not associated with a value

# Information about DPS mappings

{
  "result": {
    "model": "{\"modelId\":\"000003eglo\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"ro\",\"code\":\"doorcontact_state\",\"description\":\"\",\"extensions\{\"attribute\":\"768\"},\"name\":\"门磁状态\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":2,\"accessMode\":\"ro\",\"code\":\"battery_percentage\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"电池电量\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%\"}}]}]}"
  },
  "success": true,
  "t": 1693699204709,
  "tid": "d536347049ec11ee9a70760d0d3c40d3"
}

doorcontact_state : 1
battery_percentage : 2

# Product ID
"product_id": "5etnzhfidcmm0ang",

# Information about how the device functions
https://nl.aliexpress.com/item/1005004931427707.html?spm=a2g0o.order_list.order_list_main.59.21ef79d2P7U0xQ&gatewayAdapt=glo2nld

You can only add the device when activating it by opening and closing the door. 
the device turns off after a few seconds to safe battery.
it shows up as a simple_switch.

**Comment by make-all** [comment]
In general battery powered tuya devices are not suitable for local use, as the battery management is designed specifically to work with the cloud, not local connections.

The errors you are getting in the log should be fixed by the version of tinytuya released yesterday, which will be in the next version of tuya-local.

**Comment by iindigoo** [comment]
Thanks for your reaction.
I will buy one that uses a hub
