### ISSUE TITLE
Request support for Sierra Modern Home Smart WiFi Wireless Diffuser

### ISSUE THREAD

**Issue by admn-monkey** [make-all/tuya-local#1063]
**Product Information:**
    "model": "",
    "name": "Smart diffuser",
    "product_id": "venoaj75waptukdf",
    "product_name": "Smart diffuser",

**Notes:**
On AMZ: https://www.amazon.com/dp/B0799D1TDH?ref=ppx_yo2ov_dt_b_product_details&th=1

The core functionality probably covers a number of different brands of this same "shaped" Essential Oil Diffuser. Just looking at the "Compare with similar items" on Amazon shows at least three others. Could be one of the already supported ASAKUKI models, but the Supported Devices doesn't distinguish which ASAKUKI diffuser is currently supported. 

If any additional information from the device is needed, I just need instructions on how to get it. Probably obvious that I have the device in the Tuya IoT portal, I'm just not a developer by trade so instructions are always appreciated. 

**Functionality:**
The Diffuser has Off, Weak, and Strong modes.

Spray Timer has On, 1 Hour, 3 Hours, and 6 Hours (one of those modes then correlates to the Diffuser mode - On and Weak for example just runs on low until the diffuser runs out of water and automatically shuts off). 

Lights have gradient (automatic rotating colors), fixed (pick a color on a color wheel), Nightlight (no color select - sort of just yellow with brightness 0% to 100%).   

**DPS Mappings**
{
  "result": {
    "category": "jsq",
    "functions": [
      {
        "code": "switch",
        "desc": "{}",
        "name": "总开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_led",
        "desc": "{}",
        "name": "灯光开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_set",
        "desc": "{\"range\":[\"cancel\",\"1h\",\"3h\",\"6h\"]}",
        "name": "喷雾倒计时设置",
        "type": "Enum",
        "values": "{\"range\":[\"cancel\",\"1h\",\"3h\",\"6h\"]}"
      },
      {
        "code": "mode",
        "desc": "{\"range\":[\"small\",\"large\"]}",
        "name": "喷雾模式(雾量)",
        "type": "Enum",
        "values": "{\"range\":[\"small\",\"large\"]}"
      },
      {
        "code": "work_mode",
        "desc": "{\"range\":[\"white\",\"colour\"]}",
        "name": "灯光模式",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\"]}"
      },
      {
        "code": "bright_value",
        "desc": "{\"unit\":\"\",\"min\":0,\"max\":255,\"scale\":0,\"step\":1}",
        "name": "亮度值",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":255,\"scale\":0,\"step\":1}"
      },
      {
        "code": "colour_data",
        "desc": "{\"min\":0,\"unit\":\"\",\"scale\":0,\"max\":255,\"step\":1}",
        "name": "彩光值",
        "type": "Integer",
        "values": "{\"min\":0,\"unit\":\"\",\"scale\":0,\"max\":255,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "name": "总开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_led",
        "name": "灯光开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fault",
        "name": "故障告警",
        "type": "Bitmap",
        "values": "{\"label\":[\"1\"]}"
      },
      {
        "code": "countdown_set",
        "name": "喷雾倒计时设置",
        "type": "Enum",
        "values": "{\"range\":[\"cancel\",\"1h\",\"3h\",\"6h\"]}"
      },
      {
        "code": "countdown_left",
        "name": "喷雾倒计时剩余时间",
        "type": "Integer",
        "values": "{\"unit\":\"分钟\",\"min\":0,\"max\":360,\"scale\":0,\"step\":1}"
      },
      {
        "code": "mode",
        "name": "喷雾模式(雾量)",
        "type": "Enum",
        "values": "{\"range\":[\"small\",\"large\"]}"
      },
      {
        "code": "work_mode",
        "name": "灯光模式",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\"]}"
      },
      {
        "code": "bright_value",
        "name": "亮度值",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":255,\"scale\":0,\"step\":1}"
      },
      {
        "code": "colour_data",
        "name": "彩光值",
        "type": "Integer",
        "values": "{\"min\":0,\"unit\":\"\",\"scale\":0,\"max\":255,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1693857206074,
  "tid": "b62a6ba74b5c11ee8711ea6e14ba735f"
}

**Comment by make-all** [comment]
You have only provided cloud documentation, so it will not be possible to add the device unless more info is provided from logs and the Query Things Data Model function in Tuya's API Explorer.

**Comment by admn-monkey** [comment]
Hopefully I did better with the info this time. 



# Log Message


```
Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:49
Integration: Tuya Local (documentation, issues)
First occurred: 2:02:19 PM (4 occurrences)
Last logged: 3:07:21 PM

Device matches simple_switch with quality of 14%. DPS: {"updated_at": 1693850538.3640082, "1": true, "11": true, "12": 151, "13": "0", "14": 0, "108": "", "111": 255}
Report this to https://github.com/make-all/tuya-local/issues/
Device matches simple_switch with quality of 11%. DPS: {"updated_at": 1693854440.5782225, "1": true, "11": true, "12": 0, "13": "0", "14": 0, "103": "small", "108": "", "110": "1", "111": 255}

```

# Information about DPS mappings


```
# This is from "Query Things Data Model"
{
  "result": {
    "model": "{\"modelId\":\"000002hv9m\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"Power\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power\",\"attribute\":\"1\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":11,\"accessMode\":\"rw\",\"code\":\"Light\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_light\",\"attribute\":\"16\"},\"name\":\"灯光\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":12,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"缺水故障\",\"extensions\":{\"iconName\":\"icon-dp_warming\",\"scope\":\"fault\"},\"name\":\"故障告警\",\"typeSpec\":{\"label\":[\"1\"],\"maxlen\":1,\"type\":\"bitmap\",\"typeDefaultValue\":0}},{\"abilityId\":13,\"accessMode\":\"rw\",\"code\":\"countdown\",\"description\":\"0:ON；1：1小时；2：3小时；3：6小时。可根据产品实际功能进行设置。\",\"extensions\":{\"iconName\":\"icon-dp_time2\"},\"name\":\"倒计时\",\"typeSpec\":{\"range\":[\"0\",\"1\",\"2\",\"3\"],\"type\":\"enum\",\"typeDefaultValue\":\"0\"}},{\"abilityId\":14,\"accessMode\":\"ro\",\"code\":\"countdown_left\",\"description\":\"mcu每分钟上报\",\"extensions\":{\"iconName\":\"icon-dp_time\"},\"name\":\"倒计时剩余时间\",\"typeSpec\":{\"max\":360,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"分钟\"}},{\"abilityId\":103,\"accessMode\":\"rw\",\"code\":\"dp_mist_grade\",\"description\":\"小喷雾，大喷雾,关闭\",\"name\":\"雾量\",\"typeSpec\":{\"range\":[\"small\",\"big\",\"off\"],\"type\":\"enum\",\"typeDefaultValue\":\"small\"}},{\"abilityId\":108,\"accessMode\":\"rw\",\"code\":\"colour_data\",\"description\":\"Value: ”00112233334455”（长度为 14 的字符串） 00: R 11: G 22: B 3333: H(色调 Hue) 44: S(饱和度 Saturation) 55: V(明度 Value) 示例： {\\\"2700000000ff27\\\"}\",\"name\":\"彩光值\",\"typeSpec\":{\"maxlen\":255,\"type\":\"string\",\"typeDefaultValue\":\"\"}},{\"abilityId\":109,\"accessMode\":\"rw\",\"code\":\"work_mode\",\"description\":\"white：白光模式；colour：彩光模式；scene：场景模式；scene1-4:不同场景模式切换；可根据产品实际功能更改。\",\"name\":\"灯光模式\",\"typeSpec\":{\"range\":[\"white\",\"colour\",\"scene\",\"scene1\",\"scene2\",\"scene3\",\"scene4\"],\"type\":\"enum\",\"typeDefaultValue\":\"white\"}},{\"abilityId\":110,\"accessMode\":\"rw\",\"code\":\"lightmode\",\"description\":\"1：七彩循环；2：定色；3：夜灯\",\"name\":\"灯光模式\",\"typeSpec\":{\"range\":[\"1\",\"2\",\"3\"],\"type\":\"enum\",\"typeDefaultValue\":\"1\"}},{\"abilityId\":111,\"accessMode\":\"rw\",\"code\":\"setlight\",\"description\":\"\",\"name\":\"亮度\",\"typeSpec\":{\"max\":255,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"\"}}]}]}"
  },
  "success": true,
  "t": 1693870579132,
  "tid": "d907ad4e4b7b11ee8179fa3ecb648a44"
}

# And this is the result of the instructions @ www.zigbee2mqtt.io
{"1":"Power","11":"Light","12":"Fault","13":"Countdown","14":"Left Time","103":" Fog ","108":"Color","109":"Led Mode","110":"Light Mode","111":"Brightness"}

```






# "category": "jsq"
# "name": "Smart diffuser"
# "product_id": "venoaj75waptukdf"
# "product_name": "Smart diffuser"

}





# Information about how the device functions
# All the notes below are related to the "value" values. 
{
  "result": {
    "properties": [
      {
# Device has power but it's in a software Off state: false
# Device has power and is in a software On state: true
        "code": "Power",
        "custom_name": "",
        "dp_id": 1,
        "time": 1693859326535,
        "value": false 
      },
      {
# Turn light on: true
# Turn light off: false
        "code": "Light",
        "custom_name": "",
        "dp_id": 11,
        "time": 1693858374567,
        "value": false
      },
      {
        "code": "fault",
        "custom_name": "",
        "dp_id": 12,
        "time": 1693854381612,
        "value": 0
      },
      {
# Value is "0" when Spray Timer is ON (No timer set; ON means run with no timer); "1" when spray time is set to '1 Hour'; "2" when set to '3 Hours' ; "3" when set to '6 Hours'.	  
        "code": "countdown",
        "custom_name": "",
        "dp_id": 13,
        "time": 1693852225821,
        "value": "0"
      },
      {
# This looks like a data slot (not set but auto-populates); Value goes to "0" when Spray Timer is in the "ON" position (no timer) ; "60" when '1 Hour' is selected and then counts down from there in 1 minute increments. 
        "code": "countdown_left",
        "custom_name": "",
        "dp_id": 14,
        "time": 1693852226033,
        "value": 0
      },
      {
# Value is "off" when not misting ; "small" when in Weak mode in the app ; "big" when in Strong mode in the app. 	  
        "code": "dp_mist_grade",
        "custom_name": "",
        "dp_id": 103,
        "time": 1693858138505,
        "value": "off"
      },
      {
# Not used when in Nightlight mode or Gradient mode
# In "fixed" mode it's a color value across a color wheel range. Just sliding the wheel around and pulled these.  
# "ff96000023ffff" is yellow ; "ff002f015c6464" Red ; "5100ff01036464" Purple ; "004dff00de6464" Blue ; Green "00ff2f00836464"
# What this looks like is the first 6 digits is a HEX color code. Then the next 6 digits are also a HEX color code. 
# Seems like it then blends the two to make the actual color. Maybe primary color and then secondary color like Blue + Yellow = Green? Honestly, I'm not fully sure on how software color generation is usually done. 
# The last two digits are brightness control while in Fixed mode ranging from 0% to 100% with values ranging 00 to 64 (so HEX). 
        "code": "colour_data",
        "custom_name": "",
        "dp_id": 108,
        "time": 1693858314054,
        "value": "ff9c000024ffff"
      },
      {
# I have no clue what this one does - changed every setting and this value never changed.
        "code": "work_mode",
        "custom_name": "",
        "dp_id": 109,
        "time": 1692216675662,
        "value": "white"
      },
      {
# gradient: 1 ; fixed: 2 ; Nightlight: 3
        "code": "lightmode",
        "custom_name": "",
        "dp_id": 110,
        "time": 1693858314024,
        "value": "3"
      },
      {
# Brightness control value is 0 to 255 used with "Nightlight"  (lightmode set to 3)
        "code": "setlight",
        "custom_name": "",
        "dp_id": 111,
        "time": 1693858319002,
        "value": 31
      }
    ]
  },
  "success": true,
  "t": 1693873344976,
  "tid": "49ae1bcc4b8211ee9db51e8ad7cd6da8"
}

**Comment by make-all** [comment]
Device seems to be compatible with Ditua aroma diffuser, but from the log, some dps are not being sent, so need to be marked as optional.

**Comment by admn-monkey** [comment]
[home-assistant_tuya_local_2023-09-08T22-11-51.090Z.log](https://github.com/make-all/tuya-local/files/12563990/home-assistant_tuya_local_2023-09-08T22-11-51.090Z.log)

Debug log attached. The automation options aren't the same between the two devices and they don't match the options on the actual device entity in HA. While the manual controls on the device itself look right for the diffuser function, the automation tasks not only don't match up, also the on, off, and toggle throw errors and just won't work. It's not possible to automate the diffuser at all. 

The LED lighting automation is hit or miss too. The options aren't named and brightness controls don't exist on all of them. 

Error state works well for out of water. Apparently that's what the error id slot is for. 

Is it possible this device needs its own configuration?

**Comment by make-all** [comment]
I don't really understand what you mean by "the automation options", and there are no relevant errors in that log.
I only see changes to the Timer, which seem to be taking effect.

**Comment by admn-monkey** [comment]
None of the automation to operate the diffuser work. The diffuser cannot be
turned on or off with a scheduled automation.

Turn on, Turn off, and Toggle all result in the following when trying to
schedule the device actions. The timer actions don't work either.

Error running action
not a valid value for dictionary value @ data['entity_id']. Got None

**Comment by make-all** [comment]
You have not provided an entity id to the automation, according to that message.

**Comment by admn-monkey** [comment]
This may be a bug in HA. entity_id IS populated automatically. Here's the yaml for the Action "Turn on" that I assume comes built into Tuya Local's device support. 

type: turn_on
device_id: b79771f7d3e6dacc4f4c48cafed6bebf
entity_id: 367eadf753e6024c5c48376ef3e99de9
domain: fan

So, no, I haven't made a mistake here and likely no, there's not a true issue with support for the device with Tuya Local. I do appreciate the addition of the device support; now to figure out how to make HA work with it without using the console tool.
