### ISSUE TITLE
emylo_energy_meter sigle phase wrong readings

### ISSUE THREAD

**Issue by lukrs** [make-all/tuya-local#1066]
Hi,
emylo_energy_meter has wrong readings. All the details in attachment. Maybe there are more Emylo meter types?
![11](https://github.com/make-all/tuya-local/assets/3304582/3dbae6db-96b4-4692-ab33-19e908f32d82)
![12](https://github.com/make-all/tuya-local/assets/3304582/47896d87-9f3e-4476-a2b5-01f3b440bf4e)

**Comment by make-all** [comment]
Can you download the device diagnostics so I can see the raw data?

**Comment by make-all** [comment]
Also, the actual current, power and voltage readings from the cloud at the time you take the diagnostics (if it is a steady load the timing will not need to be perfect, as they will only be ballpark figures for checking different decoding possibilities against)

**Comment by make-all** [comment]
i found the original commit bb4f0fd7cbd0 and from the comment, I think it is just that the format has never been verified for emylo meters.

**Comment by lukrs** [comment]
Hi,
Sorry for late response, here are the diagnostics
[tuya_local-Rova Pool Electricity Meter.json.txt](https://github.com/make-all/tuya-local/files/12546312/tuya_local-Rova.Pool.Electricity.Meter.json.txt)

**Comment by make-all** [comment]
This seems to break down into (2345, 3410, 539) judging from the 00 byte positions.
I would guess the voltage is the first one, at 234.5V, but I'm not sure about the next two.

**Comment by lukrs** [comment]
![meter](https://github.com/make-all/tuya-local/assets/3304582/bf4390b8-033d-42dc-b181-b04bd4f479cd)

**Comment by lukrs** [comment]
second one is current(A)

**Comment by lukrs** [comment]
great :) ... I can confirm that it works
![b](https://github.com/make-all/tuya-local/assets/3304582/a10f1306-d942-46c4-b3f9-e5102124d24c)
