### ISSUE TITLE
New device: POIEMA ONE

### ISSUE THREAD

**Issue by edwinyoo44** [make-all/tuya-local#107]
This device is Air Purifiers

https://poiema.com.tw/product/poiema-one-2021

product_id: 2q2jgeegaziyugdg

DPS id: code ; type ; values
1: switch ; Bollean ; {}
2: pm25 ; Integer ; {"min": 0, "max": 999, "scale": 0, "step": 1}
3: mode ; Enum ; {"range": ["manual", "auto", "sleep"]}
4: fan_speed_enum ; Enum ; {"range": ["low", "mid", "high", "strong"]}
7: lock ; Bollean ; {}
11: filter_reset ; Bollean ; {}
18: countdown_set ; Enum ; {"range": ["cancel", "1h", "2h", "3h", "4h", "5h"]}
19: countdown_left ; Integer ; {"unit": "min", "min": 0, "max": 360, "scale": 0, "step": 1}

**Comment by make-all** [comment]
Assuming the support added 3 months ago is OK.
