### ISSUE TITLE
New device: Breaker (single phase) with energy monitoring

### ISSUE THREAD

**Issue by WildeRNS** [make-all/tuya-local#110]
Hello, if you can, please add new device (only phase_a is used):
https://aliexpress.com/item/1005002505542131.html

Device info:
{
  "result": {
    "active_time": 1634563440,
    "biz_type": 18,
    "category": "dlq",
    "create_time": 1634563424,
    "icon": "smart/icon/bay1591839287906taVN/267162108e2f97cf9ddf39067b4eae7a.png",
    "id": "edited",
    "ip": "edited",
    "lat": "edited",
    "local_key": "edited",
    "lon": "edited",
    "model": "",
    "name": "Kitchen Breaker",
    "online": true,
    "owner_id": "12366373",
    "product_id": "ntwmuj82anq1l92i",
    "product_name": "Breaker",
    "status": [
      {
        "code": "total_forward_energy",
        "value": 139470
      },
      {
        "code": "phase_a",
        "value": "CHoAQgQADlwAAA=="
      },
      {
        "code": "phase_b",
        "value": "AAAAAAAAAAAAAA=="
      },
      {
        "code": "phase_c",
        "value": "AAAAAAAAAAAAAA=="
      },
      {
        "code": "fault",
        "value": 0
      },
      {
        "code": "switch_prepayment",
        "value": false
      },
      {
        "code": "energy_reset",
        "value": ""
      },
      {
        "code": "balance_energy",
        "value": 0
      },
      {
        "code": "charge_energy",
        "value": 0
      },
      {
        "code": "switch",
        "value": true
      },
      {
        "code": "breaker_number",
        "value": "FSE-F723C46A04FC6C"
      }
    ],
    "sub": false,
    "time_zone": "+03:00",
    "uid": "edited",
    "update_time": 1640764653,
    "uuid": "edited"
  },
  "success": true,
  "t": 1641634444054
}

DP's list:
{
  "result": {
    "category": "dlq",
    "functions": [
      {
        "code": "switch_prepayment",
        "dp_id": 11,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "energy_reset",
        "dp_id": 12,
        "type": "Enum",
        "values": "{\"range\":[\"empty\"]}"
      },
      {
        "code": "charge_energy",
        "dp_id": 14,
        "type": "Integer",
        "values": "{\"unit\":\"kW·h\",\"min\":0,\"max\":999999,\"scale\":2,\"step\":1}"
      },
      {
        "code": "switch",
        "dp_id": 16,
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "total_forward_energy",
        "dp_id": 1,
        "type": "Integer",
        "values": "{\"unit\":\"kW·h\",\"min\":0,\"max\":99999999,\"scale\":2,\"step\":1}"
      },
      {
        "code": "phase_a",
        "dp_id": 6,
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "phase_b",
        "dp_id": 7,
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "phase_c",
        "dp_id": 8,
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "fault",
        "dp_id": 9,
        "type": "Bitmap",
        "values": "{\"label\":[\"short_circuit_alarm\",\"surge_alarm\",\"overload_alarm\",\"leakagecurr_alarm\",\"temp_dif_fault\",\"fire_alarm\",\"high_power_alarm\",\"self_test_alarm\",\"ov_cr\",\"unbalance_alarm\",\"ov_vol\",\"undervoltage_alarm\",\"miss_phase_alarm\",\"outage_alarm\",\"magnetism_alarm\",\"credit_alarm\",\"no_balance_alarm\"]}"
      },
      {
        "code": "switch_prepayment",
        "dp_id": 11,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "energy_reset",
        "dp_id": 12,
        "type": "Enum",
        "values": "{\"range\":[\"empty\"]}"
      },
      {
        "code": "balance_energy",
        "dp_id": 13,
        "type": "Integer",
        "values": "{\"unit\":\"kW·h\",\"min\":0,\"max\":99999999,\"scale\":2,\"step\":1}"
      },
      {
        "code": "charge_energy",
        "dp_id": 14,
        "type": "Integer",
        "values": "{\"unit\":\"kW·h\",\"min\":0,\"max\":999999,\"scale\":2,\"step\":1}"
      },
      {
        "code": "switch",
        "dp_id": 16,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "breaker_number",
        "dp_id": 19,
        "type": "String",
        "values": "{\"maxlen\":255}"
      }
    ]
  },
  "success": true,
  "t": 1641634234387
}

**Comment by WildeRNS** [comment]
Forgot to mention: this device was already integrated in Tuya V2 component (if it help).

**Comment by WildeRNS** [comment]
I receive message from integration that device is not supported

**Comment by make-all** [comment]
Please show the full error message from the Home Assistant log, the one that lists the DPS values.

**Comment by WildeRNS** [comment]
> Please show the full error message from the Home Assistant log, the one that lists the DPS values.

Do I need enable debug for component?

**Comment by make-all** [comment]
The important info comes out as Warning messages, which should be enabled by default.

**Comment by WildeRNS** [comment]
custom_components.tuya_local.config_flow] Device matches None with quality of 0%. DPS: {'1': 141630, '9': 0, '11': False, '12': False, '13': 0, '16': True, '19': 'FSE-F723C46A04FC6C', '101': 275, '102': 170, '103': 40, '104': 30, '105': False, '106': False, 'updated_at': 1641719713.4769526}
2022-01-09 11:15:16 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/

**Comment by make-all** [comment]
It looks like the phase_x attributes are only available through the cloud API.  Instead, it looks like the voltage, current and power for phase_a may be being broken out into dps 101,102,103,104 but I am not sure as 275 seems too high for voltage, but others are too low (in the cloud data, voltage was 217).  There are also two additional boolean flags on 105 and 106.  Also, it seems charge_energy is not available, this may be because prepayment is disabled, or it may also be cloud only.

**Comment by WildeRNS** [comment]
> Also, it seems charge_energy is not available, this may be because prepayment is disabled, or it may also be cloud only or write only.

i think it is true, prepayment is disabled.

**Comment by make-all** [comment]
I have updated the config to leave out the missing attributes.

**Comment by WildeRNS** [comment]
> I have updated the config to leave out the missing attributes.

Will try it tomorrow and write you back.

**Comment by WildeRNS** [comment]
Updated to latest, and device added successful, but no voltage, power  and current.

**Comment by make-all** [comment]
That's expected, since the phase_x fields are what hold that data, and it was anyway encoded, making it difficult to extract.  If the "unknown_XXX" attributes fit though, we can pull the data from there.

The other thing to check will be the fault codes. The credit alarm and no balance alarm might be easily triggered by enabling prepay mode and uploading 0.01kWh of credit (which is no longer accessible from the integration since that dp was not appearing), allowing the order to be checked (I assumed the order listed in the docs above was LSB first, but if it is MSB first, it will need changing).

**Comment by WildeRNS** [comment]
> That's expected, since the phase_x fields are what hold that data, and it was anyway encoded, making it difficult to extract. If the "unknown_XXX" attributes fit though, we can pull the data from there.

I know, one user was successfully decided it make PR in Tuya V2 integration, I can find this PR and post here?

**Comment by make-all** [comment]
I saw the commit in the default tuya integration, and that is how I know what information is encoded in phaseA attribute in the initial data you sent, but that is not useful if the attribute is not available in the local data.

**Comment by WildeRNS** [comment]
> I saw the commit in the default tuya integration, and that is how I know what information is encoded in phaseA attribute in the initial data you sent, but that is not useful if the attribute is not available in the local data.

I understand you, I was thinking that is local value's ;)
Thanks for you work!

**Comment by WildeRNS** [comment]
One more question, can you make  Energy reset as button, not switch?

**Comment by make-all** [comment]
Buttons are not currently supported, as they are new.

**Comment by WildeRNS** [comment]
Ok
