### ISSUE TITLE
Request support for Atorch (S1WP) device Smart Plug Energy meter

### ISSUE THREAD

**Issue by jnasserifar** [make-all/tuya-local#1103]
Could you please add Atorch (S1WP) to the support device list please.

I tried to add it myself but when I add yaml file in adding device I receive Unknown error. when I remove the file the suggested devices to choose are not energy meters!

Thank you in advance!

From Tuya iot API explorer:

    "model": "S1WP",
    "name": "Smart Energy Meter",
    "product_id": "sqrf2g1amfutn4co",
    "product_name": "炬为电能宝-计控型(S1WP)",

{
  "result": {
    "properties": [
      {
        "code": "switch_1",
        "custom_name": "",
        "dp_id": 1,
        "time": 1691582860910,
        "value": true
      },
      {
        "code": "countdown_1",
        "custom_name": "",
        "dp_id": 9,
        "time": 1695000549682,
        "value": 0
      },
      {
        "code": "add_ele",
        "custom_name": "",
        "dp_id": 17,
        "time": 1695003267591,
        "value": 5
      },
      {
        "code": "cur_current",
        "custom_name": "",
        "dp_id": 18,
        "time": 1695005887553,
        "value": 830
      },
      {
        "code": "cur_power",
        "custom_name": "",
        "dp_id": 19,
        "time": 1695005887568,
        "value": 6613
      },
      {
        "code": "cur_voltage",
        "custom_name": "",
        "dp_id": 20,
        "time": 1695005887514,
        "value": 12385
      },
      {
        "code": "price",
        "custom_name": "",
        "dp_id": 101,
        "time": 1695000549682,
        "value": 73
      },
      {
        "code": "cost",
        "custom_name": "",
        "dp_id": 102,
        "time": 1695005872416,
        "value": 51192
      },
      {
        "code": "add_cost",
        "custom_name": "",
        "dp_id": 103,
        "time": 1695004926491,
        "value": 5
      },
      {
        "code": "ovp",
        "custom_name": "",
        "dp_id": 104,
        "time": 1695000549682,
        "value": 2650
      },
      {
        "code": "ocp",
        "custom_name": "",
        "dp_id": 105,
        "time": 1695000549682,
        "value": 1000
      },
      {
        "code": "opp",
        "custom_name": "",
        "dp_id": 106,
        "time": 1695000549682,
        "value": 3000
      },
      {
        "code": "language",
        "custom_name": "",
        "dp_id": 107,
        "time": 1695000549682,
        "value": "english"
      },
      {
        "code": "work_value",
        "custom_name": "",
        "dp_id": 108,
        "time": 1695000549682,
        "value": 9
      },
      {
        "code": "standby_value",
        "custom_name": "",
        "dp_id": 109,
        "time": 1695000549682,
        "value": 3
      },
      {
        "code": "standby_time",
        "custom_name": "",
        "dp_id": 110,
        "time": 1695000549682,
        "value": 60
      },
      {
        "code": "beep",
        "custom_name": "",
        "dp_id": 111,
        "time": 1695000549682,
        "value": true
      },
      {
        "code": "sw_mode",
        "custom_name": "",
        "dp_id": 112,
        "time": 1695000549682,
        "value": "normally_open"
      },
      {
        "code": "data_reset",
        "custom_name": "",
        "dp_id": 113,
        "time": 1689902912733,
        "value": false
      },
      {
        "code": "wifi_reset",
        "custom_name": "",
        "dp_id": 114,
        "time": 1695000475501,
        "value": true
      },
      {
        "code": "factor_reset",
        "custom_name": "",
        "dp_id": 115,
        "time": 1690317870702,
        "value": true
      },
      {
        "code": "screen_rotation",
        "custom_name": "",
        "dp_id": 116,
        "time": 1690317641569,
        "value": true
      },
      {
        "code": "standby_screen",
        "custom_name": "",
        "dp_id": 117,
        "time": 1695000549682,
        "value": "measurement"
      },
      {
        "code": "menu",
        "custom_name": "",
        "dp_id": 118,
        "time": 1695000549682,
        "value": "safety_protection"
      },
      {
        "code": "plow",
        "custom_name": "",
        "dp_id": 119,
        "time": 1695000549682,
        "value": 5
      },
      {
        "code": "time_a",
        "custom_name": "",
        "dp_id": 120,
        "time": 1695000549682,
        "value": 10
      },
      {
        "code": "phigh",
        "custom_name": "",
        "dp_id": 121,
        "time": 1695000549682,
        "value": 500
      },
      {
        "code": "time_b",
        "custom_name": "",
        "dp_id": 122,
        "time": 1695000549682,
        "value": 1
      },
      {
        "code": "ele",
        "custom_name": "",
        "dp_id": 123,
        "time": 1695005872423,
        "value": 70126
      },
      {
        "code": "run_countdown",
        "custom_name": "",
        "dp_id": 124,
        "time": 1695000475516,
        "value": 0
      },
      {
        "code": "timing_close",
        "custom_name": "",
        "dp_id": 125,
        "time": 1695000549682,
        "value": 10800
      },
      {
        "code": "timing_open",
        "custom_name": "",
        "dp_id": 126,
        "time": 1695000549682,
        "value": 60
      },
      {
        "code": "loop_open",
        "custom_name": "",
        "dp_id": 127,
        "time": 1695000549682,
        "value": 60
      },
      {
        "code": "loop_close",
        "custom_name": "",
        "dp_id": 128,
        "time": 1695000549682,
        "value": 60
      },
      {
        "code": "countdown_open",
        "custom_name": "",
        "dp_id": 129,
        "time": 1695000551639,
        "value": 60
      },
      {
        "code": "countdown_close",
        "custom_name": "",
        "dp_id": 130,
        "time": 1695000551639,
        "value": 60
      },
      {
        "code": "r_mode",
        "custom_name": "",
        "dp_id": 131,
        "time": 1695000551639,
        "value": "open"
      },
      {
        "code": "warning",
        "custom_name": "",
        "dp_id": 132,
        "time": 1695000551639,
        "value": "off"
      },
      {
        "code": "cur_frequency",
        "custom_name": "",
        "dp_id": 133,
        "time": 1695005882593,
        "value": 6012
      },
      {
        "code": "power_factor",
        "custom_name": "",
        "dp_id": 134,
        "time": 1695005887574,
        "value": 64
      },
      {
        "code": "cpu_temp",
        "custom_name": "",
        "dp_id": 135,
        "time": 1695005882605,
        "value": 34
      },
      {
        "code": "price_mode",
        "custom_name": "",
        "dp_id": 136,
        "time": 1695000551639,
        "value": "single_rate"
      },
      {
        "code": "over_time",
        "custom_name": "",
        "dp_id": 137,
        "time": 1695000551639,
        "value": 0
      },
      {
        "code": "ttl",
        "custom_name": "",
        "dp_id": 138,
        "time": 1695000551639,
        "value": "memory"
      }
    ]
  },
  "success": true,
  "t": 1695005892345,
  "tid": "3489316d55cf11eeacc91e124c4e4d14"
}

**Comment by jnasserifar** [comment]
This is the Yaml file I created and not working!



name: Atroch energy monitoring smartplug
legacy_type: energy monitoring smartplug
products:
  - id: sqrf2g1amfutn4co
    name: Smart Energy Meter S1WP
  
primary_entity:
  entity: switch
  class: outlet
  dps:
    - id: 1
      name: switch
      type: boolean
      
secondary_entities:
  - entity: sensor
    dps:
    - id: 18
        name: sensor
        type: integer
        class: measurement
        unit: mA

    - id: 19
        name: sensor
        type: integer
        class: measurement
        unit: Watt
    - id: 20
        name: sensor
        class: measurement
        unit: V

  - entity: sensor
    category: diagnostic
    class: config
    dps:
      - id: 135
        name: sensor
        type: integer
        class: measurement
        unit: C

**Comment by blakadder** [comment]
I have that one just need to make a PR

**Comment by jnasserifar** [comment]
@blakadder could you please let me know how we can make PR?

**Comment by jnasserifar** [comment]
Hi after some investigation I was able to build a yaml file that does not show unknown error message(do some correction on spaces in yaml file).
I pushed the file in the devices folder after entering the value of device form in suggested device list I am not able to see it as support device.
what can be the issue?
 
After replacing the file in the devices directory, I restated the home assitant and also rebbot the machine! nothing changed!

I am attaching the file got your review

[zix_final.txt](https://github.com/make-all/tuya-local/files/12704039/zix_final.txt)

**Comment by jnasserifar** [comment]
Thanks for creating the support device.
I have updated tuya_local and retired to add the device, but when I add the attributes such as ip, local key and id i received a message it is not able to connect to device! I did check the lig but nothing pop up in the home assistant log file!  I pinged the device and its reacheable via home assistant. What can be the issue?

**Comment by blakadder** [comment]
Did you set protocol to 3.4?

**Comment by jnasserifar** [comment]
@blakadder I tested all the protocols especially 3.5 and 3.4. I will retry again.

I rebooted the machine several times also

**Comment by jnasserifar** [comment]
@blakadder  I did couple of tries with protocols 3.4
Only on one of the devices Tuya_Local can connect but with 5 devices that are not the target device!

![image](https://github.com/make-all/tuya-local/assets/29044416/ff45a5ab-e198-4f49-a636-b5ca4e8d7388)

Log message
2023-10-18 11:44:53.587 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches qoto_03_sprinkler with quality of 13%. DPS: {"updated_at": 1697643892.5306752, "9": 0, "17": 5, "18": 51, "19": 250, "20": 12246, "101": 100, "102": 5510, "103": 7, "104": 2650, "105": 1000, "106": 3000, "107": "english", "108": 9, "109": 3, "110": 60, "111": true, "112": "controlled", "117": "measurement", "118": "wifi1", "119": 5, "120": 10, "121": 500, "122": 1, "123": 5510, "124": 0, "125": 10800, "126": 60, "127": 60, "128": 60, "129": 60, "130": 60, "131": "open", "132": "off", "133": 6001, "134": 39, "135": 35, "136": "single_rate", "137": 0, "138": "memory"}

**Comment by make-all** [comment]
A couple of the dps are missing from that log, so needed to be made optional in the config.

**Comment by blakadder** [comment]
works now, dp 1 wasn't reported from the plug after a factory reset

**Comment by jnasserifar** [comment]
So I just need to do a reset the plug?

**Comment by blakadder** [comment]
no, you need the updated configuration where those dp's are marked as optional

**Comment by jnasserifar** [comment]
@blakadder @make-all  Thank you guys for all the efforts. you rock!
Now I confirm the plug is connected as expected.
I replace the config file and everything looks great!

**Comment by pirate** [comment]
I have the Atorch S1WP smart outlet and just set it up on HASS using both Tuya and Tuya Local to test it out.

It seems like Tuya autodetects and adds the 3 main sensors correctly (A, W, V), but it tries to use DP `1` as the default `Socket 1` `switch` control, but AFAIK these devices actually use DP `131` `r_mode` to change the switch state.

<img width="500" alt="Screenshot 2023-12-20 at 8 15 13 PM" src="https://github.com/make-all/tuya-local/assets/511499/63d649d9-5c54-46e8-ac85-bad1f0c9d91d">
<br/><br/>

According to Tuya Cloud, DP `131` is an Enum select field that accepts `open` or `close` as its values, and turns the outlet on or off accordingly.
<img width="500" alt="image" src="https://github.com/make-all/tuya-local/assets/511499/ebb2faf6-ab53-4b8d-9347-92afe6bd4334" align="top"><img width="500" alt="image" src="https://github.com/make-all/tuya-local/assets/511499/14016a17-88be-40d2-a02f-9f4845169cf7" align="top">



I was able to set up DP `131` manually using Tuya Local, but it's annoying that the devices are now duplicated (one Tuya device for the Voltage, Current, Power readings, and one LocalTuya device for just the `r_mode` select control).

<img width="800" alt="image" src="https://github.com/make-all/tuya-local/assets/511499/a8fbd863-1e8c-4566-957c-9fa3d7274bfe">

I tried to set up automations to sync the broken Tuya DP `1` `switch` control to the equivalent LocalTuya device's DP `131` `r_mode` `select` control, but it's clunky and annoying to set up because I have many of these devices.

<img width="500" alt="Screenshot 2023-12-20 at 8 09 19 PM" src="https://github.com/make-all/tuya-local/assets/511499/f48dd4b1-ea07-4caf-8a07-a07b5e83af16">
<img width="500" alt="Screenshot 2023-12-20 at 8 08 59 PM" src="https://github.com/make-all/tuya-local/assets/511499/4597012a-111a-41d2-ac1f-330459293170">


Is there any way to get DP `131` to show up correctly by default as the main control for this device in Home Assistant (and also have it appear as a `switch` instead of `select`)?

Or does anyone have advice on how to synchronize the controls between Tuya and LocalTuya devices in a programmatic way e.g. `<tuya device>.switch[DP 1]=on/off` <-> `<localtuya device>.select[DP 131]=open/close`?

**Comment by make-all** [comment]
DP 131 is exposed already, but it is a tri-state, so cannot be fully represented as a switch.  What is the actual behaviour of dp 1 (read-only?, operational only in auto mode?).

**Comment by pirate** [comment]
DP1 is not functional in any mode, neither via Tuya Cloud explorer nor home assistant.

131 is technically tri-state but only displays 2 options on the physical screen. The auto function doesn't seem worth exposing to home assistant as it requires programming the device physically to set up the auto timers/limits.

**Comment by blakadder** [comment]
DP1 is functional on my device and turns the relay on or off

**Comment by pirate** [comment]
Strange, I've tried every settings combo I could find and couldn't get dp1 working. I'll keep trying

**Comment by pivanet** [comment]
> I have the Atorch S1WP smart outlet and just set it up on HASS using both Tuya and Tuya Local to test it out.
> 
> It seems like Tuya autodetects and adds the 3 main sensors correctly (A, W, V), but it tries to use DP `1` as the default `Socket 1` `switch` control, but AFAIK these devices actually use DP `131` `r_mode` to change the switch state.
> 
> <img alt="Screenshot 2023-12-20 at 8 15 13 PM" width="500" src="https://private-user-images.githubusercontent.com/511499/292084650-63d649d9-5c54-46e8-ac85-bad1f0c9d91d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMjk0MTgsIm5iZiI6MTcyMTMyOTExOCwicGF0aCI6Ii81MTE0OTkvMjkyMDg0NjUwLTYzZDY0OWQ5LTVjNTQtNDZlOC1hYzg1LWJhZDFmMGM5ZDkxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQxODU4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjI2MjIzMDMzZDgwZThmOTQ4ZWU4Zjc1MDFmNjQ1MmViMzA4NDc5MGU3Y2UzZmY0YTkzMTYwZjAxYTgyYTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QPCee00FO6w6E0BchKpjraonYGKnI2PxH0-T7k-9r2I">
> 
> According to Tuya Cloud, DP `131` is an Enum select field that accepts `open` or `close` as its values, and turns the outlet on or off accordingly. <img alt="image" width="500" src="https://private-user-images.githubusercontent.com/511499/292083466-ebb2faf6-ab53-4b8d-9347-92afe6bd4334.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMjk0MTgsIm5iZiI6MTcyMTMyOTExOCwicGF0aCI6Ii81MTE0OTkvMjkyMDgzNDY2LWViYjJmYWY2LWFiNTMtNGI4ZC05MzQ3LTkyYWZlNmJkNDMzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQxODU4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmRlNzFiZWM5ZTNhYWU5MGRmNGZiODNlOTc5Mzk4YWM2NjhjZmQxNDA5M2MzMjkxNDViMDM5NDMwZjEwNzk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QM6xgurasGnfgCP4bhSBjNXW1poefel9LiCEv_loRlY"><img alt="image" width="500" src="https://private-user-images.githubusercontent.com/511499/292085351-14016a17-88be-40d2-a02f-9f4845169cf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMjk0MTgsIm5iZiI6MTcyMTMyOTExOCwicGF0aCI6Ii81MTE0OTkvMjkyMDg1MzUxLTE0MDE2YTE3LTg4YmUtNDBkMi1hMDJmLTlmNDg0NTE2OWNmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQxODU4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDNlYjUyN2Y0NmM1YTMxMjJmMzRlYjE0NTJhN2IyYTE0YzNlNjE4YTA2ZjUzNDg0Mjk3MzI0ZjI2Yzk4ZjlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1NZgaS_LOwP7dALSgmXLc6pFKwJsrTtrzau-9jfbL7I">
> 
> I was able to set up DP `131` manually using Tuya Local, but it's annoying that the devices are now duplicated (one Tuya device for the Voltage, Current, Power readings, and one LocalTuya device for just the `r_mode` select control).
> 
> <img alt="image" width="800" src="https://private-user-images.githubusercontent.com/511499/292084308-a8fbd863-1e8c-4566-957c-9fa3d7274bfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMjk0MTgsIm5iZiI6MTcyMTMyOTExOCwicGF0aCI6Ii81MTE0OTkvMjkyMDg0MzA4LWE4ZmJkODYzLTFlOGMtNDU2Ni05NTdjLTlmYTNkNzI3NGJmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQxODU4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmU4MzMyYWU5NzgzOWQwYWY3ZTg3NzNhY2ZhZjRjNTg5MzhkZWQ5Y2ZlMzFhMTkwOGY2NjM4ZGE5MjIyYTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W2NKC3KtoAS38WTXB9PjbILk6JitZKD_Xf4hHT18Nvk">
> I tried to set up automations to sync the broken Tuya DP `1` `switch` control to the equivalent LocalTuya device's DP `131` `r_mode` `select` control, but it's clunky and annoying to set up because I have many of these devices.
> 
> <img alt="Screenshot 2023-12-20 at 8 09 19 PM" width="500" src="https://private-user-images.githubusercontent.com/511499/292083742-f48dd4b1-ea07-4caf-8a07-a07b5e83af16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMjk0MTgsIm5iZiI6MTcyMTMyOTExOCwicGF0aCI6Ii81MTE0OTkvMjkyMDgzNzQyLWY0OGRkNGIxLWVhMDctNGNhZi04YTA3LWEwN2I1ZTgzYWYxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQxODU4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDA5ZDE4MjdlZjU4NjY4M2Y0ZTQwZDhkZWUwMWU1ODQ3NzBlMWE4M2M2ZWY2NjhmYmJiMGFiNTUxNDg0ZDFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ulf7nVpYZx-Ancg25ezG9W10Yc46u20IwqFmIsgWTlQ"> <img alt="Screenshot 2023-12-20 at 8 08 59 PM" width="500" src="https://private-user-images.githubusercontent.com/511499/292083837-4597012a-111a-41d2-ac1f-330459293170.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMjk0MTgsIm5iZiI6MTcyMTMyOTExOCwicGF0aCI6Ii81MTE0OTkvMjkyMDgzODM3LTQ1OTcwMTJhLTExMWEtNDFkMi1hYzFmLTMzMDQ1OTI5MzE3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQxODU4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzQwYjdhMDQ0NGIyNTA2YTVmZmIxNzhmZDViNjNlOWMzMGI0ZGYwYjA4ODkzMTU5YTM1ZTMyZTU0MjYzNzM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p6eg6JHQUlDXpvl7SVgIiI5nItaT6Yw0f89Kd_0sDsA">
> Is there any way to get DP `131` to show up correctly by default as the main control for this device in Home Assistant (and also have it appear as a `switch` instead of `select`)?
> 
> Or does anyone have advice on how to synchronize the controls between Tuya and LocalTuya devices in a programmatic way e.g. `<tuya device>.switch[DP 1]=on/off` <-> `<localtuya device>.select[DP 131]=open/close`?

it's an old post, but I have the same issue - i've managed to get the values from smart socket but was unable to do on/off.
So i create a select entity as you described and a "conversion to switch"

`      smart_energy_mode_switch:
        friendly_name: Smart Energy Meter Switch Ex
        unique_id: "smart_energy_meter_switch_ex"
        value_template: "{{ is_state('select.smart_energy_meter_switch_select', 'on') }}"
        turn_on:
          service: select.select_option
          target:
            entity_id: select.smart_energy_meter_switch_select
          data:
            option: 'on'
        turn_off:
          service: select.select_option
          target:
            entity_id: select.smart_energy_meter_switch_select
          data:
            option: 'off'`

**Comment by make-all** [comment]
Check your protocol version and device id are correct.
