### ISSUE TITLE
New device: Smart Wifi Plug - Blitzwolf BW-SHP6

### ISSUE THREAD

**Issue by WildeRNS** [make-all/tuya-local#111]
Device info:
{
  "result": {
    "active_time": 1619426870,
    "biz_type": 18,
    "category": "cz",
    "create_time": 1571822840,
    "icon": "smart/icon/ay1506337792739cXrIR/839190793a883bd3cfe4204089dae5f6.jpg",
    "id": "edited",
    "ip": "edited",
    "lat": "edited",
    "local_key": "edited",
    "lon": "edited",
    "model": "SP111/欧规10A/带计量/(BG定制)变更PID-CUCO固件",
    "name": "BW-SHP6",
    "online": true,
    "owner_id": "edited",
    "product_id": "EYfNTuTPZln9e4cn",
    "product_name": "BW-SHP6",
    "status": [
      {
        "code": "switch",
        "value": true
      },
      {
        "code": "countdown_1",
        "value": 0
      },
      {
        "code": "cur_current",
        "value": 6904
      },
      {
        "code": "cur_power",
        "value": 15466
      },
      {
        "code": "cur_voltage",
        "value": 2321
      }
    ],
    "sub": false,
    "time_zone": "+02:00",
    "uid": "edited",
    "update_time": 1639512613,
    "uuid": "edited"
  },
  "success": true,
  "t": 1641634909777
}

Device dp's:
{
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "cur_current",
        "dp_id": 4,
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_power",
        "dp_id": 5,
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":0,\"max\":50000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "cur_voltage",
        "dp_id": 6,
        "type": "Integer",
        "values": "{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "countdown_1",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1641634902851
}

**Comment by make-all** [comment]
This should be already supported by the smartplugv1.yaml config.

**Comment by WildeRNS** [comment]
> This should be already supported by the smartplugv1.yaml config.

Thanks, working
