### ISSUE TITLE
Cannot connect device

### ISSUE THREAD

**Issue by garry0garry** [make-all/tuya-local#1111]
To change the Wi-Fi network, I reset the device. I received a new local key from the iot.tuya, but the key is not accepted. Why?

Request:
`curl --request GET "https://openapi.tuyaeu.com/v2.0/cloud/thing/batch?device_ids= ... `
Answer:
`... "local_key":"ts\u003c+N?_PN(_EDu+m" ...`

Non-standard key format?

**Comment by garry0garry** [comment]
[tinytuya](https://github.com/jasonacox/tinytuya) gives the same key.

**Comment by make-all** [comment]
Q&A belongs in Discussions, see #522
