### ISSUE TITLE
Neo Ir Controller Can't add child device

### ISSUE THREAD

**Issue by MiloRoNu** [make-all/tuya-local#1115]
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior including the device the issue was observed with:

**Expected behavior**

**Additional context**

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

When adding the device with a sub device, it says it's unable to add or there's intermittent attempts and all cancels.

Adding the device alone works. It even controls it right, although the fan only and auto modes don't work. Configuring the sub device after 
adding the device alone does not work either. It says the same error.

This is the error that appears in the log. Although i don't think it is the correct one.

Logger: homeassistant.bootstrap
Source: bootstrap.py:508
First occurred: 08:33:26 (1 occurrences)
Last logged: 08:33:26

Waiting on integrations to complete setup: tuya_local

![image](https://github.com/make-all/tuya-local/assets/17202076/b4afeb24-feae-4098-9e7b-0eddf3ae3cd5)

**Comment by make-all** [comment]
The Neo device is designed to provide the interface to a climate device on the main device without using sub devices.

There is a general problem with detection of IR sub devices, as they do not return any data to Home Assistant, they are command only.  Currently the detection logic relies on data coming back from the device, but in this case it does not matter because the sub-device is not needed.
