### ISSUE TITLE
New device: BlitzWolf®BW-IS6 Security Alarm System Kit

### ISSUE THREAD

**Issue by WildeRNS** [make-all/tuya-local#112]
device info:
{
  "result": {
    "active_time": 1641233768,
    "biz_type": 18,
    "category": "mal",
    "create_time": 1641233768,
    "icon": "smart/icon/ay1506337792739cXrIR/4371489cfd222464e82ebfe327129225.jpg",
    "id": "edited",
    "ip": "edited",
    "lat": "edited",
    "local_key": "edited",
    "lon": "edited",
    "model": "BW-IS6",
    "name": "BW-IS6",
    "online": true,
    "owner_id": "edited",
    "product_id": "gcymopbbssihh6h2",
    "product_name": "BW-IS6",
    "status": [
      {
        "code": "master_mode",
        "value": "disarmed"
      },
      {
        "code": "delay_set",
        "value": 30
      },
      {
        "code": "alarm_time",
        "value": 1
      },
      {
        "code": "switch_alarm_sound",
        "value": true
      },
      {
        "code": "temper_alarm",
        "value": false
      },
      {
        "code": "switch_mode_sound",
        "value": false
      },
      {
        "code": "charge_state",
        "value": true
      },
      {
        "code": "battery_percentage",
        "value": 100
      },
      {
        "code": "switch_low_battery",
        "value": true
      },
      {
        "code": "alarm_call_number",
        "value": ""
      },
      {
        "code": "alarm_sms_number",
        "value": ""
      },
      {
        "code": "switch_alarm_call",
        "value": false
      },
      {
        "code": "switch_alarm_sms",
        "value": false
      },
      {
        "code": "call_looptimes",
        "value": 1
      },
      {
        "code": "muffling",
        "value": false
      },
      {
        "code": "alarm_msg",
        "value": "BCEEOARBBEIENQQ8BDAAIARBBD0ETwRCBDAAIARBACAEPgRFBEAEMAQ9BEs="
      },
      {
        "code": "switch_alarm_propel",
        "value": true
      },
      {
        "code": "alarm_delay_time",
        "value": 30
      },
      {
        "code": "switch_mode_dl_sound",
        "value": true
      },
      {
        "code": "master_state",
        "value": "normal"
      },
      {
        "code": "master_information",
        "value": ""
      },
      {
        "code": "factory_reset",
        "value": false
      },
      {
        "code": "sub_admin",
        "value": "AgADAAEC////IAQUBDIENQRABFYAIARDACAEQQQ1BEAEMgQ1BEAEPQRDAQEA////HAQUBDIENQRABFYAIAQyACAEMwQwBEAEMAQ2BFYCAQD///8gBBQEMgQ1BEAEVgAgBEMAIAQzBDAEQAQ0BDUEQAQ+BDE="
      }
    ],
    "sub": false,
    "time_zone": "+02:00",
    "uid": "eu1589556857161CVwFG",
    "update_time": 1641233772,
    "uuid": "edited"
  },
  "success": true,
  "t": 1641642172215
}

device dp's:
{
  "result": {
    "category": "mal",
    "functions": [
      {
        "code": "master_mode",
        "dp_id": 1,
        "type": "Enum",
        "values": "{\"range\":[\"disarmed\",\"arm\",\"home\",\"sos\"]}"
      },
      {
        "code": "delay_set",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"秒\",\"min\":0,\"max\":300,\"scale\":0,\"step\":1}"
      },
      {
        "code": "alarm_time",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"unit\":\"分钟\",\"min\":1,\"max\":60,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_alarm_sound",
        "dp_id": 4,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_mode_sound",
        "dp_id": 10,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_low_battery",
        "dp_id": 17,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "alarm_call_number",
        "dp_id": 18,
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "alarm_sms_number",
        "dp_id": 19,
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "switch_alarm_call",
        "dp_id": 20,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_alarm_sms",
        "dp_id": 21,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "call_looptimes",
        "dp_id": 22,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":1,\"max\":10,\"scale\":0,\"step\":1}"
      },
      {
        "code": "muffling",
        "dp_id": 25,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_alarm_propel",
        "dp_id": 27,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "alarm_delay_time",
        "dp_id": 28,
        "type": "Integer",
        "values": "{\"unit\":\"秒\",\"min\":0,\"max\":300,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_mode_dl_sound",
        "dp_id": 29,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "master_state",
        "dp_id": 32,
        "type": "Enum",
        "values": "{\"range\":[\"normal\",\"alarm\"]}"
      },
      {
        "code": "factory_reset",
        "dp_id": 34,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "sub_admin",
        "dp_id": 38,
        "type": "Raw",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "master_mode",
        "dp_id": 1,
        "type": "Enum",
        "values": "{\"range\":[\"disarmed\",\"arm\",\"home\",\"sos\"]}"
      },
      {
        "code": "delay_set",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"秒\",\"min\":0,\"max\":300,\"scale\":0,\"step\":1}"
      },
      {
        "code": "alarm_time",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"unit\":\"分钟\",\"min\":1,\"max\":60,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_alarm_sound",
        "dp_id": 4,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temper_alarm",
        "dp_id": 9,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_mode_sound",
        "dp_id": 10,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "charge_state",
        "dp_id": 15,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "battery_percentage",
        "dp_id": 16,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_low_battery",
        "dp_id": 17,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "alarm_call_number",
        "dp_id": 18,
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "alarm_sms_number",
        "dp_id": 19,
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "switch_alarm_call",
        "dp_id": 20,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_alarm_sms",
        "dp_id": 21,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "call_looptimes",
        "dp_id": 22,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":1,\"max\":10,\"scale\":0,\"step\":1}"
      },
      {
        "code": "muffling",
        "dp_id": 25,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "alarm_msg",
        "dp_id": 26,
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "switch_alarm_propel",
        "dp_id": 27,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "alarm_delay_time",
        "dp_id": 28,
        "type": "Integer",
        "values": "{\"unit\":\"秒\",\"min\":0,\"max\":300,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_mode_dl_sound",
        "dp_id": 29,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "master_state",
        "dp_id": 32,
        "type": "Enum",
        "values": "{\"range\":[\"normal\",\"alarm\"]}"
      },
      {
        "code": "master_information",
        "dp_id": 33,
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "factory_reset",
        "dp_id": 34,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "sub_admin",
        "dp_id": 38,
        "type": "Raw",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1641642277856
}

**Comment by make-all** [comment]
Alarm panels are not yet supported, so this will require enhancement to support a new platform.

**Comment by make-all** [comment]
Support for alarm control panels was finally added, and I made a config based on the above information.  But as there are no logs, there is a high probability that something does not match with reality, so please send logs if you test it and find it does not work.
