### ISSUE TITLE
Thermostat working except temperature changes

### ISSUE THREAD

**Issue by stalakerob** [make-all/tuya-local#1120]
**Describe the bug**
I have a ME81H thermostat that is recognized as a Beok TGR81 device (it also looks identical). Everything works as expected but when I change the temperature in HA it is not reported back properly. That means that the temperature does change in the device (and in the Tuya App) but in HA is does not. The current temperature is correct. I've tried various protocol versions and polling on/off but no success,

**To Reproduce**
Steps to reproduce the behavior including the device the issue was observed with:

**Expected behavior**

**Additional context**

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"
```
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.9.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "6.1.45",
    "supervisor": "2023.09.2",
    "host_os": "Home Assistant OS 10.5",
    "docker_version": "23.0.6",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "watchman": {
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    },
    "myenergi": {
      "version": "0.0.23",
      "requirements": [
        "pymyenergi==0.0.27"
      ]
    },
    "cover_rf_time_based": {
      "version": "1.1.3",
      "requirements": []
    },
    "tuya_local": {
      "version": "2023.9.1",
      "requirements": [
        "pycryptodome~=3.18",
        "tinytuya==1.12.11"
      ]
    },
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "miele": {
      "version": "0.1.15",
      "requirements": [
        "flatdict==4.0.1",
        "pymiele==0.1.6"
      ]
    },
    "blitzortung": {
      "version": "1.0.1",
      "requirements": [
        "paho-mqtt>=1.5.0"
      ]
    },
    "scheduler": {
      "version": "v0.0.0",
      "requirements": []
    },
    "alexa_media": {
      "version": "4.6.5",
      "requirements": [
        "alexapy==1.26.8",
        "packaging>=20.3",
        "wrapt>=1.12.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya_local",
    "name": "Tuya Local",
    "codeowners": [
      "@make-all"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/make-all/tuya-local",
    "integration_type": "device",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/make-all/tuya-local/issues",
    "requirements": [
      "pycryptodome~=3.18",
      "tinytuya==1.12.11"
    ],
    "version": "2023.9.1",
    "is_built_in": false
  },
  "data": {
    "name": "WZ Thermostat",
    "type": "beok_tgr81_thermostat_c",
    "device_id": "**REDACTED**",
    "device_cid": "",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": "auto",
    "tinytuya_version": "1.12.11",
    "api_version_set": 3.3,
    "api_version_used": 3.3,
    "api_working": true,
    "status": {},
    "cached_state": {
      "updated_at": 0,
      "1": true,
      "2": "manual",
      "10": true,
      "16": 27,
      "19": 40,
      "24": 235,
      "27": -2,
      "36": "open",
      "39": true,
      "40": false,
      "43": "in",
      "45": 0,
      "101": 1,
      "102": "52"
    },
    "pending_state": {
      "16": {
        "value": 20,
        "updated_at": 1695834584.693981,
        "sent": true
      }
    },
    "connected": true,
    "force_dps": [],
    "home_assistant": {
      "name": "WZ Thermostat",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": "\u00b0C",
          "state": {
            "entity_id": "number.wz_thermostat_calibration_offset",
            "state": "-2",
            "attributes": {
              "min": -9,
              "max": 9,
              "step": 1.0,
              "mode": "auto",
              "unit_of_measurement": "\u00b0C",
              "icon": "mdi:thermometer",
              "friendly_name": "WZ Thermostat Calibration offset"
            },
            "last_changed": "2023-09-27T17:06:31.228113+00:00",
            "last_updated": "2023-09-27T17:06:31.228113+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": "temperature",
          "icon": null,
          "unit_of_measurement": "\u00b0C",
          "state": {
            "entity_id": "number.wz_thermostat_high_temperature_limit",
            "state": "40",
            "attributes": {
              "min": 30,
              "max": 90,
              "step": 1.0,
              "mode": "auto",
              "unit_of_measurement": "\u00b0C",
              "device_class": "temperature",
              "icon": "mdi:thermometer-chevron-up",
              "friendly_name": "WZ Thermostat High temperature limit"
            },
            "last_changed": "2023-09-27T17:06:31.228343+00:00",
            "last_updated": "2023-09-27T17:06:31.228343+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": "temperature",
          "icon": null,
          "unit_of_measurement": "\u00b0C",
          "state": {
            "entity_id": "number.wz_thermostat_low_temperature_limit",
            "state": "unknown",
            "attributes": {
              "min": 5,
              "max": 20,
              "step": 1.0,
              "mode": "auto",
              "unit_of_measurement": "\u00b0C",
              "device_class": "temperature",
              "icon": "mdi:thermometer-chevron-down",
              "friendly_name": "WZ Thermostat Low temperature limit"
            },
            "last_changed": "2023-09-27T17:06:31.228490+00:00",
            "last_updated": "2023-09-27T17:06:31.228490+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": "\u00b0C",
          "state": {
            "entity_id": "number.wz_thermostat_hysteresis",
            "state": "1",
            "attributes": {
              "min": 1,
              "max": 5,
              "step": 1.0,
              "mode": "auto",
              "unit_of_measurement": "\u00b0C",
              "icon": "mdi:arrow-expand-vertical",
              "friendly_name": "WZ Thermostat Hysteresis"
            },
            "last_changed": "2023-09-27T17:06:31.228625+00:00",
            "last_updated": "2023-09-27T17:06:31.228625+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": "switch",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.wz_thermostat_anti_frost",
            "state": "on",
            "attributes": {
              "device_class": "switch",
              "icon": "mdi:snowflake-melt",
              "friendly_name": "WZ Thermostat Anti-frost"
            },
            "last_changed": "2023-09-27T17:06:31.228742+00:00",
            "last_updated": "2023-09-27T17:06:31.228742+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "lock.wz_thermostat_child_lock",
            "state": "unlocked",
            "attributes": {
              "icon": "mdi:hand-back-right",
              "friendly_name": "WZ Thermostat Child lock",
              "supported_features": 0
            },
            "last_changed": "2023-09-27T17:06:31.228880+00:00",
            "last_updated": "2023-09-27T17:06:31.228880+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": "restart",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "button.wz_thermostat_reset",
            "state": "2023-09-27T16:58:58.362531+00:00",
            "attributes": {
              "device_class": "restart",
              "friendly_name": "WZ Thermostat Reset"
            },
            "last_changed": "2023-09-27T17:06:31.228991+00:00",
            "last_updated": "2023-09-27T17:06:31.228991+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "problem",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "binary_sensor.wz_thermostat_error",
            "state": "off",
            "attributes": {
              "device_class": "problem",
              "friendly_name": "WZ Thermostat Error"
            },
            "last_changed": "2023-09-27T17:06:31.229166+00:00",
            "last_updated": "2023-09-27T17:06:31.229166+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "climate.wz_thermostat",
            "state": "heat",
            "attributes": {
              "hvac_modes": [
                "heat",
                "off"
              ],
              "min_temp": null,
              "max_temp": 40,
              "target_temp_step": 1.0,
              "preset_modes": [
                "program",
                "manual"
              ],
              "current_temperature": 23.5,
              "temperature": 27,
              "hvac_action": "heating",
              "preset_mode": "manual",
              "fault_code": 0,
              "icon": "mdi:radiator",
              "friendly_name": "WZ Thermostat",
              "supported_features": 17
            },
            "last_changed": "2023-09-27T17:06:31.229597+00:00",
            "last_updated": "2023-09-27T17:06:31.229597+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "select.wz_thermostat_sensor_selection",
            "state": "Internal",
            "attributes": {
              "options": [
                "Internal",
                "External",
                "Both"
              ],
              "icon": "mdi:gauge",
              "friendly_name": "WZ Thermostat Sensor selection"
            },
            "last_changed": "2023-09-27T17:06:31.229746+00:00",
            "last_updated": "2023-09-27T17:06:31.229746+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "select.wz_thermostat_working_week",
            "state": "unavailable",
            "attributes": {
              "options": [
                "Off",
                "5 days",
                "6 days",
                "7 days"
              ],
              "icon": "mdi:calendar-clock",
              "friendly_name": "WZ Thermostat Working week"
            },
            "last_changed": "2023-09-27T17:06:31.199143+00:00",
            "last_updated": "2023-09-27T17:06:31.199143+00:00"
          }
        }
      ]
    }
  }
}
```

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

![thermostat](https://github.com/make-all/tuya-local/assets/44496615/a9e48384-b80e-4a10-a928-4e8d90e0d2b1)

![Screenshot_20230927_191845_Tuya Smart](https://github.com/make-all/tuya-local/assets/44496615/d150577f-054f-402d-9737-ed8c9aa78c09)

**Comment by make-all** [comment]
This is a strange problem.  The fact that the control of the device works shows that the configuration is correct and the communication is working, but HA does not seem to be receiving anything from the device (status is empty, and timestamp on cached_state is 0).  Possibly the protocol version needs to be 3.2, but I am not sure.

**Comment by make-all** [comment]
A debug log might show more information about what is happening.

**Comment by stalakerob** [comment]
Thank you for helping with this. Here's the debug log:
`Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/helpers/device_config.py:682
Integration: Tuya Local (documentation, issues)
First occurred: 09:10:11 (1 occurrences)
Last logged: 09:10:11

WZ Thermostat receive loop terminated by exception 'NoneType' object has no attribute 'get_value'
Traceback (most recent call last):
  File "/config/custom_components/tuya_local/device.py", line 215, in receive_loop
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 730, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 771, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 147, in state
    current_option = self.current_option
                     ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/select.py", line 52, in current_option
    return self._option_dps.get_value(self._device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 402, in get_value
    bytevalue = self.decoded_value(device)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 411, in decoded_value
    v = self._map_from_dps(device.get_property(self.id), device)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 682, in _map_from_dps
    return r_dps.get_value(device)
           ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_value'
`

**Comment by stalakerob** [comment]
Thanks for helping. Here are  few debug log entries:
`Logger: homeassistant.components.select
Source: custom_components/tuya_local/helpers/device_config.py:682
Integration: Auswählen (documentation, issues)
First occurred: 09:15:51 (2 occurrences)
Last logged: 09:15:51

Error adding entities for domain select with platform tuya_local
Error while setting up tuya_local platform for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1001, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/tuya_local/helpers/mixin.py", line 98, in async_added_to_hass
    self._device.register_entity(self)
  File "/config/custom_components/tuya_local/device.py", line 185, in register_entity
    entity.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 901, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 730, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 771, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 147, in state
    current_option = self.current_option
                     ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/select.py", line 52, in current_option
    return self._option_dps.get_value(self._device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 402, in get_value
    bytevalue = self.decoded_value(device)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 411, in decoded_value
    v = self._map_from_dps(device.get_property(self.id), device)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 682, in _map_from_dps
    return r_dps.get_value(device)
           ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_value'
`
`Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/helpers/device_config.py:682
Integration: Tuya Local (documentation, issues)
First occurred: 09:16:14 (1 occurrences)
Last logged: 09:16:14

WZ Thermostat receive loop terminated by exception 'NoneType' object has no attribute 'get_value'
Traceback (most recent call last):
  File "/config/custom_components/tuya_local/device.py", line 215, in receive_loop
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 730, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 771, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 147, in state
    current_option = self.current_option
                     ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/select.py", line 52, in current_option
    return self._option_dps.get_value(self._device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 402, in get_value
    bytevalue = self.decoded_value(device)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 411, in decoded_value
    v = self._map_from_dps(device.get_property(self.id), device)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 682, in _map_from_dps
    return r_dps.get_value(device)
           ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_value'
`

**Comment by make-all** [comment]
There is a problem in that config, the "Working week" select entity tries to handle two slightly different dp layouts, but it was doing so incorrectly, causing those errors during initialisation which are preventing the communication from working.

**Comment by stalakerob** [comment]
OK, so what can I do now?

**Comment by stalakerob** [comment]
Using Protocol 3.1, 3.4 and 3.5 it says unable to connect. Using 3.2 it does not list the correct device type. Only 3.3 works (kind of)

**Comment by make-all** [comment]
If you are using HACS, you can test the change by going to the tuya-local page within HACS, and selecting Redownload from the top right menu.  After the dialog appears, you should get a list of available versions to choose from, select "main".  Wait for the list to become active again after selecting, then press Download.

If it is successful, you will get two notifications, one telling you tuya-local 2023.9.1 is available, which you can ignore for now, and another telling you to reboot to finish the install.  After rebooting, you should have the fix.

**Comment by stalakerob** [comment]
Thank you very much! This now works. I'm getting the following log message though:
`Logger: homeassistant.util.async_
Source: util/async_.py:164
First occurred: 10:06:44 (1 occurrences)
Last logged: 10:06:44

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 76: self._api = tinytuya.Device(dev_id, address, local_key)`

Then a realized that number.wz_thermostat_low_temperature_limit is not available. That was already the case before your recent changes. It's not a big deal for me. I just wanted to let you know. And finally will this fix be included in future version so that I can update without breaking things again?

**Comment by stalakerob** [comment]
Update: number.wz_thermostat_low_temperature_limit now works. I don't know why. The log entry is still there.

**Comment by make-all** [comment]
That log entry is caused by using "Auto" for the IP address.

The Low temperature limit not being available would have been due to the device not sending the current value for whatever reason.  I think in that case the temperature range will fall back to a minimum of 5

**Comment by stalakerob** [comment]
Entered IP address. Log entry gone. Everything works now. You rock !
