### ISSUE TITLE
Issue with the Garden Solar Lights

### ISSUE THREAD

**Issue by Krispkiwi** [make-all/tuya-local#1125]
Hey Mate,

I'm running into an issue with two of the garden solar lights after resetting my HA, they're both not getting the correct option when it comes to the device selection screen instead the only light option is the rgbww_lightbulb, 

Any ideas what's causing this? the first two paired fine.

**Comment by make-all** [comment]
With a log message, I might be able to see.

**Comment by Krispkiwi** [comment]
> With a log message, I might be able to see.

Sweet, I've just completely reset my HA so I'll get this to you when I get back to the integrations. Will probably be around Tuesday.

**Comment by Krispkiwi** [comment]
Alright mate, first 3 lights are connecting fine, last light is getting "Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect." 

I obtained everything from Tiny Tuya which is working for all other devices, which section contains the logs that you're after?

**Comment by make-all** [comment]
Are these all WiFi devices, or through a hub?  If through a hub it may be that the hub is limited to 3 local connections on the WiFi side.

**Comment by Krispkiwi** [comment]
> Are these all WiFi devices, or through a hub? If through a hub it may be that the hub is limited to 3 local connections on the WiFi side.

They're the bluetooth solar lights

**Comment by Krispkiwi** [comment]
Made another attempt today, can confirm the limit to adding solar lights though Tuya local appears to be 3 although the default tuya cloud integration can get all 4.
