### ISSUE TITLE
Heater goes unavailable continuously

### ISSUE THREAD

**Issue by nicoolaro** [make-all/tuya-local#115]
I set heater as Kogan KAWFHTP everything is working perfectly for some time then seems HA drops contact to device, it's shown as unavailable and i keep seeing a bunch of these errors.

`2022-01-10 00:51:52 ERROR (SyncWorker_0) [custom_components.tuya_local.device] Failed to refresh device state for Heater.`

Keep in mind that i haven't block internet access to API.

My heater is often recognized if i restart Home Assistant again.

Anything i can do to keep state up or it's just limitation to my heater?

**Comment by make-all** [comment]
Do you use the official app as well?  The Tuya devices seem to only handle one local connection at a time, so if the app is using the connection, it can block Home Assistant from using it. If this continues long enough, HA seems to mark devices as offline and stop polling them until a reboot.  This integration only provides the API for polling, it does not control when to poll (apart from defining a poll interval) so there isn't much I can do about the fact that it cannot recover until a HA restart when this happens.

**Comment by nicoolaro** [comment]
> Do you use the official app as well? The Tuya devices seem to only handle one local connection at a time, so if the app is using the connection, it can block Home Assistant from using it. If this continues long enough, HA seems to mark devices as offline and stop polling them until a reboot. This integration only provides the API for polling, it does not control when to poll (apart from defining a poll interval) so there isn't much I can do about the fact that it cannot recover until a HA restart when this happens.

I removed all apps and link to google home .
Behavior is strange: it will go to unavailable then occasionally it will respond to commands like on/off , then call will fail but eventually it will come as available and go in circles :-D.  I guess those are limitations of my device, anyways thanks

**Comment by make-all** [comment]
If your heater is not actually KAWFHTP, there may be some small difference in config that causes this, so a custom configuration specifically for your heater may help.

**Comment by nicoolaro** [comment]
> If your heater is not actually KAWFHTP, there may be some small difference in config that causes this, so a custom configuration specifically for your heater may help.

It's recognized as KAWFHTP and it looks like Kogan just not the same brand, i guess they are using the same chip for diff manufacturers.

If you have an idea i am happy to get to the bottom of this but otherwise i don't want to take too much of your time.

**Comment by make-all** [comment]
Maybe the firmware is the same, but sometimes it differs slightly, such as the strings used for Enum type settings (eg "high", "low" vs "1", "3" or "1", "2").  If there is a message in the HA log when it goes offline, it may give a clue as to what is wrong.

**Comment by make-all** [comment]
The dps returned in your comment on #102 does seem to be an exact match.

**Comment by nicoolaro** [comment]
> The dps returned in your comment on #102 does seem to be an exact match.

Just so you know that my heater goes offline even within the Tuya app, so it's probably not be related to this integration. 
you can close this issue as to not the clog the backlog.

Thanks
