### ISSUE TITLE
Cant control AUBESS smart plug

### ISSUE THREAD

**Issue by guffy1234** [make-all/tuya-local#1158]
Hi

Basically I want to switch from localtuya to tyua-local, but unfortunately my devices don't work properly

**Describe the bug**
I have a few AUBESS WiFi smart plugs. I trying to add one of them to Tuya-Local. 

**To Reproduce**
Try to switch off the socket. Actually the device doesn't react to the command at all, on-screen switch turning off for a few seconds and then returns to original state.

**Expected behavior**
Entity controls the device. Socket switching of and on.

**Additional context**
In Localtuya the same device works fine. And Tuya-Local immediately reflects all changes properly.

[tuya_local-5d69f755f0c81f0b65945a4c0fadc8ea-Test4-6b25de2e4b88adf7d46e8b63b8722051.json.txt](https://github.com/make-all/tuya-local/files/12848545/tuya_local-5d69f755f0c81f0b65945a4c0fadc8ea-Test4-6b25de2e4b88adf7d46e8b63b8722051.json.txt)

[home-assistant_tuya_local_2023-10-09T16-38-03.403Z.log](https://github.com/make-all/tuya-local/files/12848555/home-assistant_tuya_local_2023-10-09T16-38-03.403Z.log)

Thanks!

PS. 
It would be nice to make a couple enhancements. What is the best way to ask them - make separate tickets?
1. Support Tuya cloud connection to detect devices (ip/localkey) like localtuya does
2. It would be nice if an entity will have somewhere attribute which device template it uses. And it would be nice to have ability to change the template without entity delete/create cycle.

PPS.
I have the same device as in this ticket and it works well from localtuya. So I'm waiting for it will be available in tyualocal
https://github.com/make-all/tuya-local/issues/1038

**Comment by make-all** [comment]
In the past others have found this to be caused by using the wrong device id for their devices.  In particular, for many devices, the iot.tuya.com lists "id" and "uuid", as the same values, so a lot of advice equated these, but it turns out some devices have a different "uuid" and "id", and in those cases the "id" must be used to function correctly.
