### ISSUE TITLE
Request support for Kennedy Fireplace

### ISSUE THREAD

**Issue by wrmacj** [make-all/tuya-local#1165]
Looking for help trying to add my Kennedy Fireplace model Data included 
Let me know if there is anything else that will help.
Thanks for the assistance.
    • Query Device Details 
    • Query Properties
    • Get the specifications and properties of the device 
    • Get the instruction set of the device
    • Get the status of a single device 
    • Tuya_local Log
    • Choose the type of device  - Selected kogan_glass_1_7l_kettle
    • I do not know how to create a new device and have it be offered as a device type.

# Log Message

```
Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:97
Integration: Tuya Local (documentation, issues)
First occurred: 5:39:28 PM (1 occurrences)
Last logged: 5:39:28 PM

Device matches rgbww_lightbulb with quality of 20%. DPS: {"updated_at": 1697146768.3605497, "1": true, "3": 21, "5": "5", "13": "f", "15": 69, "19": "0", "20": 0, "101": true, "102": "1", "103": "0", "104": "1", "106": "0", "107": "0", "108": "1", "109": "0"}
```

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"0000029m7w\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":3,\"accessMode\":\"ro\",\"code\":\"temp_current\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"当前温度_C\",\"typeSpec\":{\"max\":40,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"℃\"}},
{\"abilityId\":5,\"accessMode\":\"rw\",\"code\":\"level\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"设定温度\",\"typeSpec\":{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\"],\"type\":\"enum\",\"typeDefaultValue\":\"1\"}},
{\"abilityId\":13,\"accessMode\":\"rw\",\"code\":\"temp_unit_convert\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"温标切换\",\"typeSpec\":{\"range\":[\"c\",\"f\"],\"type\":\"enum\",\"typeDefaultValue\":\"c\"}},
{\"abilityId\":15,\"accessMode\":\"ro\",\"code\":\"temp_current_f\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"当前温度_F\",\"typeSpec\":{\"max\":104,\"min\":32,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":32,\"unit\":\"℉\"}},
{\"abilityId\":19,\"accessMode\":\"rw\",\"code\":\"countdown_set\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"倒计时\",\"typeSpec\":{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\"],\"type\":\"enum\",\"typeDefaultValue\":\"0\"}},
{\"abilityId\":20,\"accessMode\":\"ro\",\"code\":\"countdown_left\",\"description\":\"1、已设置倒计时开/关机，倒计时执⾏期间，倒计时剩余时间应每分钟更新⼀次（ n=n-1 ）;2、倒计时剩余时间为0时，取暖器应执⾏相应的逻辑，并关联上报倒计时为0；3、倒计时执⾏期间，如⼈为提前开启/关闭取暖器，倒计时应⾃动结束，关联上报倒计时、倒计时剩余时间为0；4、可配置为只倒计时关机。\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"倒计时剩余时间\",\"typeSpec\":{\"max\":480,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"min\"}},
{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"FLAME_ON_OFF\",\"description\":\"\",\"name\":\"火焰开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":102,\"accessMode\":\"rw\",\"code\":\"FLAME_RED\",\"description\":\"\",\"name\":\"红色\",\"typeSpec\":{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\"],\"type\":\"enum\",\"typeDefaultValue\":\"0\"}},
{\"abilityId\":103,\"accessMode\":\"rw\",\"code\":\"FLAME_BLUE\",\"description\":\"\",\"name\":\"蓝色\",\"typeSpec\":{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\"],\"type\":\"enum\",\"typeDefaultValue\":\"0\"}},
{\"abilityId\":104,\"accessMode\":\"rw\",\"code\":\"FLAME_YELLOW\",\"description\":\"\",\"name\":\"黄色\",\"typeSpec\":{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\"],\"type\":\"enum\",\"typeDefaultValue\":\"0\"}},
{\"abilityId\":106,\"accessMode\":\"rw\",\"code\":\"EMBER_LIGHT\",\"description\":\"\",\"name\":\"炭床灯\",\"typeSpec\":{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\"],\"type\":\"enum\",\"typeDefaultValue\":\"0\"}},
{\"abilityId\":107,\"accessMode\":\"rw\",\"code\":\"HEAT\",\"description\":\"\",\"name\":\"加热\",\"typeSpec\":{\"range\":[\"0\",\"1\",\"2\"],\"type\":\"enum\",\"typeDefaultValue\":\"0\"}},
{\"abilityId\":108,\"accessMode\":\"rw\",\"code\":\"save_flame\",\"description\":\"\",\"name\":\"保存火焰状态\",\"typeSpec\":{\"range\":[\"0\",\"1\"],\"type\":\"enum\",\"typeDefaultValue\":\"0\"}},
{\"abilityId\":109,\"accessMode\":\"rw\",\"code\":\"restore_flame\",\"description\":\"\",\"name\":\"恢复火焰状态\",\"typeSpec\":{\"range\":[\"0\",\"1\",\"2\"],\"type\":\"enum\",\"typeDefaultValue\":\"0\"}}]}]}"
  },
  "success": true,
  "t": 1697149273142,
  "tid": "a6fac2da694d11ee8b62ea7d43a7f458"
}
```

# Product ID

      "category": "qn",
      "custom_name": "Fireplace",
      "icon": "smart/icon/bay1596551773231nZOy/656d5de80df9d518dd93a35f44fcbc7b.jpg",
      "id": "--Mask--",
      "ip": "--Mask--",
      "is_online": true,
      "lat": "--Mask--",
      "local_key": "--Mask--",
      "lon": "--Mask--",
      "model": "JR - 082020",
      "name": "JR W/O TOP LIGHT",
      "product_id": "x6yepotm52a8pfbv",
      "product_name": "JR W/O TOP LIGHT",
      "sub": false,
      "time_zone": "-05:00",
      "update_time": 1682201053,
      "uuid": "--Mask--"

# Information about how the device functions

    • The device has the following capabilities in the app.
        ◦ On Off
        ◦ Two speed fan
        ◦ Current temperature
        ◦ Target Temp
        ◦ On Timer
        ◦ Flame lights in Three colours with 4 levels plus off
        ◦ Ember lights in 8 colours plus on and off 
        ◦ Choice of F or C

![Kennedy_Fierplace](https://github.com/make-all/tuya-local/assets/109797056/0851c9b0-0d0b-435e-92ea-ba95e4b6713d)

Looking for help trying to add my Kennedy Fireplace model Data included 

    • Query Device Details 
    • Query Properties
    • Get the specifications and properties of the device 
    • Get the instruction set of the device
    • Get the status of a single device 
    • Tuya_local Log
    • Choose the type of device  - Selected kogan_glass_1_7l_kettle
    • I do not know how to create a new device and have it be offered as a device type.
    • The device has the following capabilities in the app.
        ◦ On Off
        ◦ Two speed fan
        ◦ Current temperature
        ◦ Target Temp
        ◦ On Timer
        ◦ Flame lights in Three colours with 4 levels plus off
        ◦ Ember lights in 8 colours plus on and off 
        ◦ Choice of F or C

**Choose the type of device**
Choose the type that matches your device
Device type
garage_door_opener
**kogan_glass_1_7l_kettle**
rgbww_lightbulb
simple_switch

___________________________________________________________________________
    • Query Device Details
      
      "category": "qn",
      "custom_name": "Fireplace",
      "icon": "smart/icon/bay1596551773231nZOy/656d5de80df9d518dd93a35f44fcbc7b.jpg",
      "id": "--Mask--",
      "ip": "--Mask--",
      "is_online": true,
      "lat": "--Mask--",
      "local_key": "--Mask--",
      "lon": "--Mask--",
      "model": "JR - 082020",
      "name": "JR W/O TOP LIGHT",
      "product_id": "x6yepotm52a8pfbv",
      "product_name": "JR W/O TOP LIGHT",
      "sub": false,
      "time_zone": "-05:00",
      "update_time": 1682201053,
      "uuid": "--Mask--"
______________________________________________________________________

    • Query Properties 

{
  "result": {
    "properties": [
      {
        "code": "switch",
        "custom_name": "",
        "dp_id": 1,
        "time": 1697099530180,
        "value": false
      },
      {
        "code": "temp_current",
        "custom_name": "",
        "dp_id": 3,
        "time": 1697137181974,
        "value": 20
      },
      {
        "code": "level",
        "custom_name": "",
        "dp_id": 5,
        "time": 1697099530056,
        "value": "5"
      },
      {
        "code": "temp_unit_convert",
        "custom_name": "",
        "dp_id": 13,
        "time": 1697074352815,
        "value": "f"
      },
      {
        "code": "temp_current_f",
        "custom_name": "",
        "dp_id": 15,
        "time": 1697137182094,
        "value": 68
      },
      {
        "code": "countdown_set",
        "custom_name": "",
        "dp_id": 19,
        "time": 1697078047703,
        "value": "0"
      },
      {
        "code": "countdown_left",
        "custom_name": "",
        "dp_id": 20,
        "time": 1697078047802,
        "value": 0
      },
      {
        "code": "FLAME_ON_OFF",
        "custom_name": "",
        "dp_id": 101,
        "time": 1697099530284,
        "value": false
      },
      {
        "code": "FLAME_RED",
        "custom_name": "",
        "dp_id": 102,
        "time": 1697074353005,
        "value": "1"
      },
      {
        "code": "FLAME_BLUE",
        "custom_name": "",
        "dp_id": 103,
        "time": 1697074353109,
        "value": "0"
      },
      {
        "code": "FLAME_YELLOW",
        "custom_name": "",
        "dp_id": 104,
        "time": 1697074353206,
        "value": "1"
      },
      {
        "code": "EMBER_LIGHT",
        "custom_name": "",
        "dp_id": 106,
        "time": 1697078546058,
        "value": "0"
      },
      {
        "code": "HEAT",
        "custom_name": "",
        "dp_id": 107,
        "time": 1697079280827,
        "value": "0"
      },
      {
        "code": "save_flame",
        "custom_name": "",
        "dp_id": 108,
        "time": 1697074420946,
        "value": "1"
      },
      {
        "code": "restore_flame",
        "custom_name": "",
        "dp_id": 109,
        "time": 1696983087804,
        "value": "0"
      }
    ]
  },
  "success": true,
  "t": 1697137521074,
  "tid": "4a45d241693211ee847b16e7c18db4ee

­___________________________________________________________________________________

    • Get the specifications and properties of the device 

 "result": {
    "category": "qn",
    "functions": [
      {
        "code": "switch",
        "desc": "{}",
        "name": "开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "level",
        "desc": "{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\"]}",
        "name": "设定温度",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\"]}"
      },
      {
        "code": "temp_unit_convert",
        "desc": "{\"range\":[\"c\",\"f\"]}",
        "name": "温标切换",
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "countdown_set",
        "desc": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\"]}",
        "name": "倒计时",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\"]}"
      },
      {
        "code": "FLAME_ON_OFF",
        "desc": "{}",
        "name": "火焰开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "FLAME_RED",
        "desc": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\"]}",
        "name": "红色",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\"]}"
      },
      {
        "code": "FLAME_BLUE",
        "desc": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\"]}",
        "name": "蓝色",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\"]}"
      },
      {
        "code": "FLAME_YELLOW",
        "desc": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\"]}",
        "name": "黄色",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\"]}"
      },
      {
        "code": "EMBER_LIGHT",
        "desc": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\"]}",
        "name": "炭床灯",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\"]}"
      },
      {
        "code": "HEAT",
        "desc": "{\"range\":[\"0\",\"1\",\"2\"]}",
        "name": "加热",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\"]}"
      },
      {
        "code": "save_flame",
        "desc": "{\"range\":[\"0\",\"1\"]}",
        "name": "保存火焰状态",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\"]}"
      },
      {
        "code": "restore_flame",
        "desc": "{\"range\":[\"0\",\"1\",\"2\"]}",
        "name": "恢复火焰状态",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\"]}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "name": "开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_current",
        "name": "当前温度_C",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":40,\"scale\":0,\"step\":1}"
      },
      {
        "code": "level",
        "name": "设定温度",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\"]}"
      },
      {
        "code": "temp_unit_convert",
        "name": "温标切换",
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "temp_current_f",
        "name": "当前温度_F",
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":32,\"max\":104,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_set",
        "name": "倒计时",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\"]}"
      },
      {
        "code": "countdown_left",
        "name": "倒计时剩余时间",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":480,\"scale\":0,\"step\":1}"
      },
      {
        "code": "FLAME_ON_OFF",
        "name": "火焰开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "FLAME_RED",
        "name": "红色",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\"]}"
      },
      {
        "code": "FLAME_BLUE",
        "name": "蓝色",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\"]}"
      },
      {
        "code": "FLAME_YELLOW",
        "name": "黄色",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\"]}"
      },
      {
        "code": "EMBER_LIGHT",
        "name": "炭床灯",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\"]}"
      },
      {
        "code": "HEAT",
        "name": "加热",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\"]}"
      },
      {
        "code": "save_flame",
        "name": "保存火焰状态",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\"]}"
      },
      {
        "code": "restore_flame",
        "name": "恢复火焰状态",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\"]}"
      }
    ]
  },
  "success": true,

___________________________________________________________________________________

    • Get the instruction set of the device 

{
  "result": {
    "category": "qn",
    "functions": [
      {
        "code": "switch",
        "desc": "switch",
        "name": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "level",
        "desc": "level",
        "name": "level",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\"]}"
      },
      {
        "code": "temp_unit_convert",
        "desc": "temp unit convert",
        "name": "temp unit convert",
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "countdown_set",
        "desc": "countdown set",
        "name": "countdown set",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\"]}"
      },
      {
        "code": "FLAME_ON_OFF",
        "desc": "FLAME ON OFF",
        "name": "FLAME ON OFF",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "FLAME_RED",
        "desc": "FLAME RED",
        "name": "FLAME RED",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\"]}"
      },
      {
        "code": "FLAME_BLUE",
        "desc": "FLAME BLUE",
        "name": "FLAME BLUE",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\"]}"
      },
      {
        "code": "FLAME_YELLOW",
        "desc": "FLAME YELLOW",
        "name": "FLAME YELLOW",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\"]}"
      },
      {
        "code": "EMBER_LIGHT",
        "desc": "EMBER LIGHT",
        "name": "EMBER LIGHT",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\"]}"
      },
      {
        "code": "HEAT",
        "desc": "HEAT",
        "name": "HEAT",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\"]}"
      },
      {
        "code": "save_flame",
        "desc": "save flame",
        "name": "save flame",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\"]}"
      },
      {
        "code": "restore_flame",
        "desc": "restore flame",
        "name": "restore flame",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\"]}"
      }
    ]
  },
  "success": true,
  "t": 1697142666209,
  "tid": "45014b11693e11ee847b16e7c18db4ee"
}
______________________________________________________________________________

    • Get the status of a single device 

  "result": [
    {
      "code": "switch",
      "value": true
    },
    {
      "code": "temp_current",
      "value": 21
    },
    {
      "code": "level",
      "value": "5"
    },
    {
      "code": "temp_unit_convert",
      "value": "f"
    },
    {
      "code": "temp_current_f",
      "value": 69
    },
    {
      "code": "countdown_set",
      "value": "0"
    },
    {
      "code": "countdown_left",
      "value": 0
    },
    {
      "code": "FLAME_ON_OFF",
      "value": true
    },
    {
      "code": "FLAME_RED",
      "value": "1"
    },
    {
      "code": "FLAME_BLUE",
      "value": "0"
    },
    {
      "code": "FLAME_YELLOW",
      "value": "1"
    },
    {
      "code": "EMBER_LIGHT",
      "value": "0"
    },
    {
      "code": "HEAT",
      "value": "0"
    },
    {
      "code": "save_flame",
      "value": "1"
    },
    {
      "code": "restore_flame",
      "value": "0"
    }
  ],
  "success": true,
______________________________________________________________________

-Tuya Local Log

  "integration_manifest": {
    "domain": "tuya_local",
    "name": "Tuya Local",
    "codeowners": [
      "@make-all"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/make-all/tuya-local",
    "integration_type": "device",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/make-all/tuya-local/issues",
    "requirements": [
      "pycryptodome~=3.18",
      "tinytuya==1.12.11"
    ],
    "version": "2023.9.1",
    "is_built_in": false
  },
 "data": {
    "name": "Kogan smart kettle",
    "type": "kogan_glass_1_7l_kettle",
    "device_id": "**REDACTED**",
    "device_cid": "",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": 3.3,
    "tinytuya_version": "1.12.11",
    "api_version_set": 3.3,
    "api_version_used": 3.3,
    "api_working": true,
    "status": {},
    "cached_state": {
      "updated_at": 1697137724.1015198,
      "1": true,
      "3": 20,
      "5": "5",
      "13": "f",
      "15": 68,
      "19": "0",
      "20": 0,
      "101": true,
      "102": "1",
      "103": "0",
      "104": "1",
      "106": "0",
      "107": "0",
      "108": "1",
      "109": "0"
    },
    "pending_state": {},
    "connected": true,
    "force_dps": [],
    "home_assistant": {
      "name": "Kogan smart kettle",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "climate.kogan_smart_kettle",
            "state": "heat",
            "attributes": {
              "hvac_modes": [
                "off",
                "heat"
              ],
              "min_temp": null,
              "max_temp": null,
              "target_temp_step": 1,
              "current_temperature": 41,
              "icon": "mdi:kettle",
              "friendly_name": "Kogan smart kettle",
              "supported_features": 0
            },

**Comment by wrmacj** [comment]
Not sure if this helps
When it is done how do I add it and use it.
Thank you.

![Image](https://github.com/make-all/tuya-local/assets/109797056/d1e9944c-ecfe-4aa8-85d4-64cb5a9d8c6d)

**Comment by wrmacj** [comment]
The interphace now has the appropriate options look and feel but they do not controll the device.

**Comment by make-all** [comment]
This can happen if you used the wrong value for device id.
