### ISSUE TITLE
Request support for Avatto Underfloor Heating Thermostat WT200W-EH

### ISSUE THREAD

**Issue by Knellius** [make-all/tuya-local#1166]
# Log Message

Device matches simple_switch_timerv2 with quality of 50%. DPS: {"updated_at": 1697031776.2913554, "1": false, "9": 0, "38": "off", "42": "", "43": "", "44": ""}
Device matches simple_switch_timerv2 with quality of 50%. DPS: {"updated_at": 1697032807.4679646, "1": false, "9": 0, "38": "off", "42": "", "43": "", "44": ""}
Device matches garage_door_opener with quality of 12%. DPS: {"updated_at": 1697043115.6020806, "1": false, "3": 274, "4": "cold", "5": "0", "8": false, "13": true, "16": 0, "20": 0, "21": 40, "25": "3", "26": false, "31": false, "41": "1", "101": false, "105": 10, "107": 50}
Device matches garage_door_opener with quality of 12%. DPS: {"updated_at": 1697043283.652968, "1": false, "3": 274, "4": "cold", "5": "0", "8": false, "13": true, "16": 0, "20": 0, "21": 40, "25": "3", "26": false, "31": false, "41": "1", "101": false, "105": 10, "107": 50}
Device matches hydrotherm_dynamic_x8_water_heater with quality of 29%. DPS: {"updated_at": 1697044457.944128, "1": true, "2": 350, "3": 248, "4": "cold", "5": "1", "8": false, "13": true, "16": 0, "20": 0, "21": 40, "25": "3", "26": false, "31": false, "41": "1", "101": false, "105": 10, "107": 50}

# Information about DPS mappings

{
"result": {
"model": "{\"modelId\":\"00000035fb\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":
[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"temp_set\",\"description\":\"int 型数据传输 如 250 则表示温度为25.0°\",\"extensions\":{\"iconName\":\"icon-dp_temp\"},\"name\":\"设置温度\",\"typeSpec\":{\"max\":950,\"min\":50,\"scale\":1,\"step\":5,\"type\":\"value\",\"typeDefaultValue\":50,\"unit\":\"℃\"}},
{\"abilityId\":3,\"accessMode\":\"ro\",\"code\":\"temp_current\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_sun\"},\"name\":\"室内温度\",\"typeSpec\":{\"max\":999,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"℃\"}},
{\"abilityId\":4,\"accessMode\":\"rw\",\"code\":\"mode\",\"description\":\"制冷，制热，送风，根据实际情况自由配置\",\"extensions\":{\"iconName\":\"icon-dp_mode\"},\"name\":\"工作模式\",\"typeSpec\":{\"range\":[\"cold\",\"hot\",\"wind\"],\"type\":\"enum\",\"typeDefaultValue\":\"cold\"}},
{\"abilityId\":5,\"accessMode\":\"ro\",\"code\":\"work_state\",\"description\":\"继电器输出状态 指示 \",\"extensions\":{\"iconName\":\"icon-eco\"},\"name\":\"工作状态\",\"typeSpec\":{\"range\":[\"0\",\"1\"],\"type\":\"enum\",\"typeDefaultValue\":\"0\"}},
{\"abilityId\":8,\"accessMode\":\"rw\",\"code\":\"child_lock\",\"description\":\"童锁开关\",\"extensions\":{\"iconName\":\"icon-dp_fresh\"},\"name\":\"童锁\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":13,\"accessMode\":\"rw\",\"code\":\"sound\",\"description\":\"\",\"name\":\"声音\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":16,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"根据实际情况设置\",\"extensions\":{\"scope\":\"fault\"},\"name\":\"故障告警\",\"typeSpec\":{\"label\":[\"1\",\"2\",\"3\"],\"maxlen\":3,\"type\":\"bitmap\",\"typeDefaultValue\":0}},
{\"abilityId\":20,\"accessMode\":\"rw\",\"code\":\"temp_correction\",\"description\":\"\",\"name\":\"温度校准\",\"typeSpec\":{\"max\":99,\"min\":-99,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-99,\"unit\":\"\"}},
{\"abilityId\":21,\"accessMode\":\"rw\",\"code\":\"upper_temp\",\"description\":\"\",\"name\":\"设置温度上限\",\"typeSpec\":{\"max\":95,\"min\":15,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":15,\"unit\":\"℃\"}},
{\"abilityId\":25,\"accessMode\":\"rw\",\"code\":\"sensor_choose\",\"description\":\"内置、外置 双温\",\"name\":\"传感器选择\",\"typeSpec\":{\"range\":[\"1\",\"2\",\"3\"],\"type\":\"enum\",\"typeDefaultValue\":\"1\"}},
{\"abilityId\":26,\"accessMode\":\"rw\",\"code\":\"frost\",\"description\":\"\",\"name\":\"防霜冻功能\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":31,\"accessMode\":\"rw\",\"code\":\"reset\",\"description\":\"\",\"name\":\"恢复出厂设置\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":41,\"accessMode\":\"rw\",\"code\":\"backlight\",\"description\":\"背光亮度3挡位\",\"name\":\"背光亮度\",\"typeSpec\":{\"range\":[\"0\",\"1\",\"2\",\"3\"],\"type\":\"enum\",\"typeDefaultValue\":\"0\"}},
{\"abilityId\":42,\"accessMode\":\"rw\",\"code\":\"work_days\",\"description\":\"1：5+2\\n2:  6+1\\n3:  7\",\"name\":\"工作日设置\",\"typeSpec\":{\"range\":[\"1\",\"2\",\"3\"],\"type\":\"enum\",\"typeDefaultValue\":\"1\"}},
{\"abilityId\":43,\"accessMode\":\"rw\",\"code\":\"week_program3\",\"description\":\"\",\"name\":\"周程序3（工作日休息日）\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"zhufan\",\"description\":\"常闭型 正逻辑  常开型 反逻辑\",\"name\":\"常闭型_常开型\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":105,\"accessMode\":\"rw\",\"code\":\"qidongwencha\",\"description\":\"继电器 启动或者关闭 温差值\",\"name\":\"输出启动温差\",\"typeSpec\":{\"max\":95,\"min\":5,\"scale\":1,\"step\":5,\"type\":\"value\",\"typeDefaultValue\":5,\"unit\":\"\"}},
{\"abilityId\":107,\"accessMode\":\"rw\",\"code\":\"xianwen\",\"description\":\"双温双控时 外置传感器限温值 默认45\",\"name\":\"传感器限温值\",\"typeSpec\":{\"max\":60,\"min\":5,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":5,\"unit\":\"\"}}
]
}]}"
},
"success": true,
"t": 1697237775798,
"tid": "b6b4ef416a1b11eebdf0a64fb2ede3b1"
}

Data points finding script result (from "Find Tuya Data Points" article):
{"1":"Switch","2":"Set Temperature","3":"Current Temperature","4":"Mode","5":"Working status","8":"Child lock","41":"Backlight brightness","101":"常闭型_常开型","105":"Temperature control switch difference"}

# Product ID

"product_id": "gw173aldekvpzalg"

# Information about how the device functions

User manual:
https://thermostat.guide/avatto/avatto-wt200-smart-wifi-thermostat-user-manual/

Screenshots from SmartLife app
![01](https://github.com/make-all/tuya-local/assets/139018351/b73ddc64-84a1-4466-b44d-0815b564a9cb)
![02](https://github.com/make-all/tuya-local/assets/139018351/c22b0226-b112-4845-8310-ed195f0c6bb0)
![03](https://github.com/make-all/tuya-local/assets/139018351/7964e49b-3ab1-4258-b35e-87d3074d34f0)
![04](https://github.com/make-all/tuya-local/assets/139018351/4ba184f2-901b-401c-b0a7-d579a99644c3)
![05](https://github.com/make-all/tuya-local/assets/139018351/1002dfee-0322-4b71-abcb-00aeb89c5040)
![06](https://github.com/make-all/tuya-local/assets/139018351/d64468f7-e71c-4bdc-ac70-8ca258c34849)
![07](https://github.com/make-all/tuya-local/assets/139018351/0160a289-ba51-4974-8de3-2fd8ee1a438d)
![08](https://github.com/make-all/tuya-local/assets/139018351/470fc4bc-5890-4db8-84da-181749d7bf8d)
![09](https://github.com/make-all/tuya-local/assets/139018351/3f17f713-33d4-4174-8dd1-6e2ff4df85cb)
![10](https://github.com/make-all/tuya-local/assets/139018351/b84bc5b0-deba-4e20-8062-3950b215d236)
![11](https://github.com/make-all/tuya-local/assets/139018351/00f5c69b-8594-426c-b67d-a52f61c427d2)
![12](https://github.com/make-all/tuya-local/assets/139018351/3411f6d4-2eb5-475d-9ee6-0e3046c54f51)
![13](https://github.com/make-all/tuya-local/assets/139018351/cac2c4dc-f352-4572-bc84-318a286c535e)

**Comment by Knellius** [comment]
Also, i've just received the excel file with DPS from seller. There is the list of same DPS, with same codes but with different IDs. I don't know if you need it, but just in case i'll attach it here)
[Temp-2(jaovfquhkmbydxyp)_10_06.xlsx](https://github.com/make-all/tuya-local/files/12905826/Temp-2.jaovfquhkmbydxyp._10_06.xlsx)

**Comment by Knellius** [comment]
I took the yaml file for WT100 as a prototype and made this file. Actually, they are almost identical, i've just made few changes, and now it works perfectly with my WT200.
I think, WT100 file just have too many dps that lack attribute "optional: true", otherwise it could serve.
[avatto_wt200_thermostat.zip](https://github.com/make-all/tuya-local/files/13170384/avatto_wt200_thermostat.zip)

**Comment by Knellius** [comment]
Should I make a pull request?

**Comment by make-all** [comment]
I'll compare with the WT100 file again. I previously had a quick look, and they seemed different, but maybe you are right and making some dps optional will be enough.

**Comment by make-all** [comment]
The temperature ranges are a little different.  I don't know whether the WT100 ones are correct, as there was a long list of modes in the original info the user reported, but only the ones in the config worked (which matches the modes listed here), so that info was suspect.
