### ISSUE TITLE
Support BlitzHome® BH-AF2 Air Fryer

### ISSUE THREAD

**Issue by axcs** [make-all/tuya-local#117]
Hello, can it support the BlitzHome® BH-AF2 Air Fryer?
I managed to use some resources with "rospogrigio/localtuya"
but having the options as switch some functions are changed or impossible to use.

**Comment by make-all** [comment]
I would need more information about the device.  If you try to add it, using the device name, IP address and local key, you should see a message in the Home Assistant log saying it is not an exact match for any device and listing the dps that the device returns. You can cancel adding the device at the point where it asks you to select the device type (probably it will offer "Simple Switch", or maybe say no matching device).

Also, if you registered to iot.tuya.com to get your device key, there might be further information in "Cloud" / "API Explorer" / "Smart Home Management System" / "Device Control" / "Get Device Specification Attribute" (you'll need to select your Region's Data Center also)

**Comment by make-all** [comment]
This issue will be closed soon, as without further information about the device, no further progress can be made.

**Comment by make-all** [comment]
This information is now being closed, as there is insufficient information to do anything.
