### ISSUE TITLE
missing device_class and state_class in energy

### ISSUE THREAD

**Issue by mywp** [make-all/tuya-local#1175]
can't use Energy in Dashboards of Home Assistant
missing device_class and state_class in energy of yaml file
Like:
  - entity: sensor
    category: diagnostic
    class: energy
    name: Energy
    dps:
      - id: 17
        name: sensor
        type: integer
        class: total_increasing
        unit: Wh
        optional: true

**Comment by make-all** [comment]
This is not a bug.  Almost all Tuya smartplugs reset the energy count too frequently for it to be useful for the Energy dashboard, so it is not marked for that to prevent misleading users into trying to use it.
