### ISSUE TITLE
EV charger recoqnized as Dooya_Curtain or ioratap_zigbee

### ISSUE THREAD

**Issue by Striiter** [make-all/tuya-local#1176]
**Describe the bug**
EV charger recoqnized as Dooya_Curtain or ioratap_zigbee
https://github.com/make-all/tuya-local/issues/1149

When added thinks its "dooya_curtain" or "loratap_zigbee_six_switch"
https://i.imgur.com/E2xdcAt.png

**To Reproduce**
Add device

**Expected behavior**
Well, add the DP's from issue #1149

**Additional context**

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

`
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.10.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Copenhagen",
    "os_name": "Linux",
    "os_version": "6.1.56",
    "supervisor": "2023.10.0",
    "host_os": "Home Assistant OS 11.0",
    "docker_version": "24.0.6",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "sonoff": {
      "version": "3.5.2",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "ecoflow": {
      "version": "3.0.0",
      "requirements": [
        "reactivex"
      ]
    },
    "ecoflow_cloud": {
      "version": "0.12.4",
      "requirements": [
        "paho-mqtt==1.6.1",
        "reactivex==4.0.4",
        "protobuf>=4.23.0"
      ]
    },
    "meross_cloud": {
      "version": "1.2.8",
      "requirements": [
        "meross_iot==0.4.5.7"
      ]
    },
    "tuya_local": {
      "version": "2023.9.2",
      "requirements": [
        "pycryptodome~=3.18",
        "tinytuya==1.12.11"
      ]
    },
    "energidataservice": {
      "version": "1.4.1",
      "requirements": [
        "async-retrying-ng==0.1.3",
        "CurrencyConverter==0.17.11"
      ]
    },
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "xiaomi_miot": {
      "version": "0.7.13",
      "requirements": [
        "construct>=2.10.56",
        "python-miio>=0.5.6",
        "micloud>=0.3"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya_local",
    "name": "Tuya Local",
    "codeowners": [
      "@make-all"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/make-all/tuya-local",
    "integration_type": "device",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/make-all/tuya-local/issues",
    "requirements": [
      "pycryptodome~=3.18",
      "tinytuya==1.12.11"
    ],
    "version": "2023.9.2",
    "is_built_in": false
  },
  "data": {
    "name": "Dooya curtain",
    "type": "dooya_curtain",
    "device_id": "**REDACTED**",
    "device_cid": "",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": 3.3,
    "tinytuya_version": "1.12.11",
    "api_version_set": 3.3,
    "api_version_used": 3.3,
    "api_working": true,
    "status": {},
    "cached_state": {
      "updated_at": 1697470920.9762964,
      "10": 0,
      "101": "charing",
      "102": 8,
      "103": true,
      "104": 0,
      "106": 14,
      "107": 213,
      "108": 68,
      "109": 14,
      "110": 253,
      "111": 8,
      "112": true,
      "113": 9,
      "114": 0
    },
    "pending_state": {},
    "connected": true,
    "force_dps": [],
    "home_assistant": {
      "name": "Dooya curtain",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "curtain",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "cover.dooya_curtain",
            "state": "unknown",
            "attributes": {
              "current_position": 8,
              "device_class": "curtain",
              "friendly_name": "Dooya curtain",
              "supported_features": 15
            },
            "last_changed": "2023-10-16T15:42:00.976711+00:00",
            "last_updated": "2023-10-16T15:42:00.976711+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "select.dooya_curtain_direction",
            "state": "Reverse",
            "attributes": {
              "options": [
                "Forward",
                "Reverse"
              ],
              "icon": "mdi:swap-horizontal",
              "friendly_name": "Dooya curtain Direction"
            },
            "last_changed": "2023-10-16T15:42:00.976984+00:00",
            "last_updated": "2023-10-16T15:42:00.976984+00:00"
          }
        }
      ]
    }
  }
}`

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

Log: 

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:97
Integration: Tuya Local ([documentation](https://github.com/make-all/tuya-local), [issues](https://github.com/make-all/tuya-local/issues))
First occurred: 17.34.08 (3 occurrences)
Last logged: 17.36.22

    Device matches dooya_curtain with quality of 29%. DPS: {"updated_at": 1697470447.8732698, "10": 0, "101": "charing", "102": 8, "103": true, "104": 0, "106": 12, "107": 207, "108": 67, "109": 13, "110": 255, "111": 8, "112": true, "113": 8, "114": 0}
    Device matches dooya_curtain with quality of 29%. DPS: {"updated_at": 1697470517.910808, "10": 0, "101": "charing", "102": 8, "103": true, "104": 0, "106": 12, "107": 209, "108": 69, "109": 14, "110": 255, "111": 8, "112": true, "113": 8, "114": 0}
    Device matches dooya_curtain with quality of 29%. DPS: {"updated_at": 1697470581.260348, "10": 0, "101": "charing", "102": 8, "103": true, "104": 0, "106": 12, "107": 210, "108": 68, "109": 14, "110": 255, "111": 8, "112": true, "113": 8, "114": 0}

**Comment by Striiter** [comment]
Temperature needs to be devided by 10

**Comment by ve1koz111** [comment]
Same with 2023.10.0

First occurred: 17:40:02 (4 occurrences)
Last logged: 17:40:38

Device matches loratap_zigbee_six_switch with quality of 8%. DPS: {"updated_at": 1697611200.6483939, "10": 0, "101": "no_connect", "102": 32, "104": 0, "106": 0, "107": 245, "108": 0, "109": 0, "110": 258, "112": false, "113": 0, "114": 0}
Report this to https://github.com/make-all/tuya-local/issues/
Device matches loratap_zigbee_six_switch with quality of 8%. DPS: {"updated_at": 1697611236.7577858, "10": 0, "101": "no_connect", "102": 32, "104": 0, "106": 0, "107": 244, "108": 0, "109": 0, "110": 261, "112": false, "113": 0, "114": 0}

**Comment by moldav20** [comment]
Hi guys!
I have the same issue. I bought this version: https://www.aliexpress.com/item/1005005509894969.html?spm=a2g0o.order_list.order_list_main.23.12b51802zyX1ZW
But it's not working fine. When I try to add to Tuya Local, thinks it "dooya_curtain" or "loratap_zigbee_six_switch".
What can I do with it?

**Comment by Striiter** [comment]
@moldav20 you can trick it by adding it as "dooya_curtain" - then replace "dooya_curtain.yaml" with the content of the ev charger yaml file

i can at least see data, but its read only. cant toggle or change anything - only see voltage, current amps, set amps, current kw, and kwh, as well as charge time

**Comment by moldav20** [comment]
Thank you, but I need device control too, so I hope, it will supported soon.

> @moldav20 you can trick it by adding it as "dooya_curtain" - then replace "dooya_curtain.yaml" with the content of the ev charger yaml file
> 
> i can at least see data, but its read only. cant toggle or change anything - only see voltage, current amps, set amps, current kw, and kwh, as well as charge time

**Comment by make-all** [comment]
A better fix is to mark dp 16 (Clear energy button) as optional, as was just done in the development version.
