### ISSUE TITLE
New Device: Ecostrad Radiator

### ISSUE THREAD

**Issue by Paul-C-S** [make-all/tuya-local#118]
I've bought a few of Ecostrad Radiators (https://www.electricradiatorsdirect.co.uk/ecostrad-iq-ceramic-wifi-controlled-electric-radiators/) and need a little help with the YAML file.

This is the output from tuya-cli:
{
  '1': true,
  '2': 'hot',
  '16': 180,
  '24': 90,
  '27': 0,
  '40': false,
  '104': '15',
  '107': '1',
  '108': '0',
  '109': '0'
}

This is my attempt at the YAML:
[Ecostrad-Radiator.yaml.txt](https://github.com/make-all/tuya-local/files/7877934/Ecostrad-Radiator.yaml.txt)

Note: ID 109 is not used.  This is shown in the app but does nothing

I have full functionality but there are a few issues.

1. The descriptions do not show when adding the device
![Entities with missing names](https://user-images.githubusercontent.com/67597584/149677421-e6988c92-fce7-4d7a-b846-6e5c1cfe713e.PNG)

But it looks and works fine in the Entity Info:
![Entity Info](https://user-images.githubusercontent.com/67597584/149677449-b2d5619b-9b96-4bfc-b761-0a34d87fa125.PNG)

And in the Lovelace page too:
![Lovelace Display](https://user-images.githubusercontent.com/67597584/149677464-1314e721-38f2-4d07-a93e-8c3bb1473df7.PNG)

2. Is it possible to have control of the operation type (sensor, eco, comfort, etc.) in the primary entity display circled in yellow?
![Lovelace Display - Plan](https://user-images.githubusercontent.com/67597584/149677513-8b787e2c-fb72-4ab5-9541-bb97981075bc.PNG)

Any help would be appreciated :)

**Comment by make-all** [comment]
1. The config page requires strings defined in translations/en.json.
    Where possible, tweak the names to match existing names in there, to keep the translations required as small as possible if someone wants to contribute support for another language.  Suggest: Open Window Detection -> Open Window Detector, Operating Mode -> remove this entity, as it is already covered by the preset mode of the climate entity, Sensor Mode -> maybe Timer or Schedule?, Temperature Correction -> Calibration Offset.
2. The area marked in yellow is for the hvac_modes defined in the Home Assistant climate platform: cool, heat, heat_cool, auto, fan_only and off.  What you are calling operation type seems to be preset_mode, which is only available under the ... menu in the top right of that card in the default Home Assistant climate card.

**Comment by make-all** [comment]
I think the "person_infrared_ray" preset does seem to match the "auto" hvac_mode defined by Home Assistant as "The device is set to a schedule, learned behavior, AI.", but splitting just that out makes the configuration very complex.

**Comment by Paul-C-S** [comment]
Thanks for tidying that up.

Some names are still not showing when adding the device:
![Some Missing Names](https://user-images.githubusercontent.com/67597584/149761514-34af2763-02b2-440c-91b5-fbb333a46bcf.PNG)

But the Lovelace display is much better (with preset mode moved to the device details now):
![No Preset Mode](https://user-images.githubusercontent.com/67597584/149761648-01095c5f-ea29-4484-bd0e-006db1995482.PNG)

![Preset Mode in Details](https://user-images.githubusercontent.com/67597584/149761668-06a57473-c8da-4744-9f6b-26cd384bfebd.PNG)

**Comment by make-all** [comment]
Sometimes you need to Shift-Refresh in the browser to pick up new strings.  In the end, only Calibration Offset was reusable from existing strings, as the Open Window Detector that was there already was a switch, not a select (and this one has 3 options, so cannot be a switch) and the others don't really fit with any existing function.

**Comment by make-all** [comment]
If you want the presets surfaced to the main page, the favoured solution seems to be to add a row of buttons, configured with the service call to change to the desired preset.

**Comment by Paul-C-S** [comment]
That all makes sense.

Thank you.  It works great :)
