### ISSUE TITLE
Request support for YRHAND K7 Wi-Fi Smart Door Lock

### ISSUE THREAD

**Issue by felipecrs** [make-all/tuya-local#1182]
# Log Message

```
Sorry, I have not attempted to add the lock to HA yet. Let me know if I should. But according to the product id it is not supported anyway.
```

# Information about DPS mappings

Note that I translated the Chinese names and descriptions to English.

```json
{
  "modelId": "000004eppn",
  "services": [
    {
      "actions": [],
      "code": "",
      "description": "",
      "events": [],
      "name": "Default Service",
      "properties": [
        {
          "abilityId": 1,
          "accessMode": "ro",
          "code": "unlock_fingerprint",
          "description": "Optional. Fingerprint data is recorded on the door lock, and after recording is complete, the hardware assigns an ID. When fingerprint unlocking occurs, the door lock will report this data. Please use recorded data for reporting.",
          "extensions": { "iconName": "icon-dp_lock", "attribute": "1344" },
          "name": "Fingerprint Unlock",
          "typeSpec": {
            "max": 999,
            "min": 0,
            "scale": 0,
            "step": 1,
            "type": "value",
            "typeDefaultValue": 0
          }
        },
        {
          "abilityId": 2,
          "accessMode": "ro",
          "code": "unlock_password",
          "description": "Optional. Regular passwords (non-temporary) are recorded on the door lock, and after recording is complete, the hardware assigns an ID. When regular password unlocking occurs, the door lock will report this data. Regular passwords refer to passwords created on the door lock hardware, excluding temporary passwords created through the app. Please use recorded data for reporting.",
          "extensions": { "iconName": "icon-dp_lock", "attribute": "1344" },
          "name": "Regular Password Unlock",
          "typeSpec": {
            "max": 999,
            "min": 0,
            "scale": 0,
            "step": 1,
            "type": "value",
            "typeDefaultValue": 0
          }
        },
        {
          "abilityId": 3,
          "accessMode": "ro",
          "code": "unlock_temporary",
          "description": "Optional. Distinguishes between temporary and regular passwords. Temporary passwords are created through the app and can have an exact expiration date. They can also send SMS notifications to the recipients during creation. Please use recorded data for reporting.",
          "extensions": { "iconName": "icon-shoushimima", "attribute": "1344" },
          "name": "Temporary Password Unlock",
          "typeSpec": {
            "max": 999,
            "min": 0,
            "scale": 0,
            "step": 1,
            "type": "value",
            "typeDefaultValue": 0
          }
        },
        {
          "abilityId": 5,
          "accessMode": "ro",
          "code": "unlock_card",
          "description": "Optional. Card data is recorded on the door lock, and after recording is complete, the hardware assigns an ID. When card unlocking occurs, the door lock will report this data. Please use recorded data for reporting.",
          "extensions": { "iconName": "icon-dp_lock", "attribute": "1344" },
          "name": "Card Unlock",
          "typeSpec": {
            "max": 999,
            "min": 0,
            "scale": 0,
            "step": 1,
            "type": "value",
            "typeDefaultValue": 0
          }
        },
        {
          "abilityId": 6,
          "accessMode": "ro",
          "code": "unlock_face",
          "description": "Optional. Face data is recorded on the door lock, and after recording is complete, the hardware assigns an ID. When face unlocking occurs, the door lock will report this data. Please use recorded data for reporting.",
          "extensions": { "iconName": "icon-dp_smile", "attribute": "1344" },
          "name": "Face Recognition Unlock",
          "typeSpec": {
            "max": 999,
            "min": 0,
            "scale": 0,
            "step": 1,
            "type": "value",
            "typeDefaultValue": 0
          }
        },
        {
          "abilityId": 7,
          "accessMode": "ro",
          "code": "unlock_key",
          "description": "Optional. If the hardware can detect mechanical key unlocking, it will report a fixed DP value of 1, indicating that mechanical key unlocking has occurred. This unlocking record should be reported in the data type for records.",
          "extensions": { "iconName": "icon-dp_lock", "attribute": "1344" },
          "name": "Key Unlock",
          "typeSpec": {
            "max": 999,
            "min": 0,
            "scale": 0,
            "step": 1,
            "type": "value",
            "typeDefaultValue": 0
          }
        },
        {
          "abilityId": 8,
          "accessMode": "ro",
          "code": "alarm_lock",
          "description": "Required. Alarm types: 0=wrong fingerprint, 1=wrong password, 2=wrong card, 3=wrong face, 4=tongue stuck, 5=too hot, 6=unclosed door timeout, 7=electronic lock tongue not ejected, 8=anti-pry, 9=key inserted, 10=low battery, 11=battery exhausted, 12=shock, 13=defense, 14=stay alarm, 15=doorbell call.",
          "extensions": { "iconName": "icon-dp_warming", "attribute": "1344" },
          "name": "Alarm",
          "typeSpec": {
            "range": [
              "wrong_finger",
              "wrong_password",
              "wrong_card",
              "wrong_face",
              "tongue_bad",
              "too_hot",
              "unclosed_time",
              "tongue_not_out",
              "pry",
              "key_in",
              "low_battery",
              "power_off",
              "shock",
              "defense",
              "stay_alarm",
              "doorbell"
            ],
            "type": "enum",
            "typeDefaultValue": "wrong_finger"
          }
        },
        {
          "abilityId": 9,
          "accessMode": "ro",
          "code": "unlock_request",
          "description": "Optional. To use the remote door opening function, this DP is required. The door lock reports a remote door opening request, which needs to be triggered by the hardware. When the door lock locally reports a remote door opening request, it carries a countdown in seconds. Only a response can be made within those seconds. Clicking 'Allow' will unlock the door. The countdown can be less than or equal to 90 seconds. When the door lock either agrees or rejects the remote door opening, change the value of this field to 0, and the panel will stop blinking.",
          "extensions": { "attribute": "1344" },
          "name": "Remote Door Opening Request Countdown",
          "typeSpec": {
            "max": 999,
            "min": 0,
            "scale": 0,
            "step": 1,
            "type": "value",
            "typeDefaultValue": 0
          }
        },
        {
          "abilityId": 10,
          "accessMode": "rw",
          "code": "arming_switch",
          "description": "Note: This feature is not currently developed.",
          "extensions": { "attribute": "1344" },
          "name": "Arming Switch",
          "typeSpec": { "type": "bool", "typeDefaultValue": false }
        },
        {
          "abilityId": 12,
          "accessMode": "ro",
          "code": "residual_electricity",
          "description": "Optional. Either the battery level or battery status, choose one. Report the battery level.",
          "extensions": { "attribute": "1344" },
          "name": "Remaining Battery Level",
          "typeSpec": {
            "max": 100,
            "min": 0,
            "scale": 1,
            "step": 1,
            "type": "value",
            "typeDefaultValue": 0,
            "unit": ""
          }
        },
        {
          "abilityId": 15,
          "accessMode": "ro",
          "code": "unlock_app",
          "description": "Optional. After a remote door opening event occurs in the app, the door lock reports a record of the remote door opening. Use recorded data for reporting.",
          "extensions": { "iconName": "icon-shouji", "attribute": "1344" },
          "name": "App Remote Unlock (Wi-Fi Door Lock)",
          "typeSpec": {
            "max": 999,
            "min": 0,
            "scale": 0,
            "step": 1,
            "type": "value",
            "typeDefaultValue": 0
          }
        },
        {
          "abilityId": 16,
          "accessMode": "ro",
          "code": "hijack",
          "description": "Optional. This function does not require hardware implementation. The door lock does not need to make hijack judgments; marking the unlock ID in the app is sufficient.",
          "extensions": { "iconName": "icon-baojing", "attribute": "1344" },
          "name": "Hijack Alarm",
          "typeSpec": { "type": "bool", "typeDefaultValue": false }
        },
        {
          "abilityId": 19,
          "accessMode": "ro",
          "code": "doorbell",
          "description": "Optional. If the door lock hardware has a doorbell function, clicking this data point will trigger a doorbell call notification to the cloud. It is recommended to trigger only one doorbell call notification for continuous doorbell calls. After reporting, the app will retain a record, and it can trigger push notifications.",
          "extensions": { "iconName": "icon-a_power", "attribute": "1344" },
          "name": "Doorbell Call",
          "typeSpec": { "type": "bool", "typeDefaultValue": false }
        },
        {
          "abilityId": 25,
          "accessMode": "ro",
          "code": "update_all_finger",
          "description": "Optional. When all fingerprint data on the door lock changes locally, whether added or deleted, trigger the synchronization of all fingerprint IDs from the door lock to the cloud. Note: Each time synchronization is performed, use a full synchronization to upload all the locally available IDs to the cloud.",
          "extensions": { "iconName": "icon-dp_fly", "attribute": "1376" },
          "name": "Sync All Fingerprint IDs",
          "typeSpec": { "maxlen": 128, "type": "raw" }
        },
        {
          "abilityId": 26,
          "accessMode": "ro",
          "code": "update_all_password",
          "description": "Optional. When all password data on the door lock changes locally, whether added or deleted, trigger the synchronization of all password IDs from the door lock to the cloud. Note: Each time synchronization is performed, use a full synchronization to upload all the locally available IDs to the cloud.",
          "extensions": { "iconName": "icon-dp_fly", "attribute": "1376" },
          "name": "Sync All Password IDs",
          "typeSpec": { "maxlen": 128, "type": "raw" }
        },
        {
          "abilityId": 27,
          "accessMode": "ro",
          "code": "update_all_card",
          "description": "Optional. When all card data on the door lock changes locally, whether added or deleted, trigger the synchronization of all card IDs from the door lock to the cloud. Note: Each time synchronization is performed, use a full synchronization to upload all the locally available IDs to the cloud.",
          "extensions": { "iconName": "icon-dp_fly", "attribute": "1376" },
          "name": "Sync All Card IDs",
          "typeSpec": { "maxlen": 128, "type": "raw" }
        },
        {
          "abilityId": 28,
          "accessMode": "ro",
          "code": "update_all_face",
          "description": "Optional. When all face data on the door lock changes locally, whether added or deleted, trigger the synchronization of all face IDs from the door lock to the cloud. Note: Each time synchronization is performed, use a full synchronization to upload all the locally available IDs to the cloud.",
          "extensions": { "iconName": "icon-dp_fly", "attribute": "1376" },
          "name": "Sync All Face IDs",
          "typeSpec": { "maxlen": 128, "type": "raw" }
        },
        {
          "abilityId": 31,
          "accessMode": "ro",
          "code": "update_all_fin_vein",
          "description": "Optional. When all finger vein data on the door lock changes locally, whether added or deleted, trigger the synchronization of all finger vein IDs from the door lock to the cloud.",
          "extensions": { "iconName": "icon-dp_fly", "attribute": "1376" },
          "name": "Sync All Finger Vein IDs",
          "typeSpec": { "maxlen": 128, "type": "raw" }
        },
        {
          "abilityId": 32,
          "accessMode": "ro",
          "code": "unlock_offline_pd",
          "description": "Optional. This algorithm is implemented by TuYa. It reports a successful offline password unlock event, displaying the password and unlock time in the unlock record.",
          "extensions": { "iconName": "icon-dp_upload", "attribute": "1344" },
          "name": "Offline Password Unlock Report",
          "typeSpec": { "maxlen": 128, "type": "raw" }
        },
        {
          "abilityId": 33,
          "accessMode": "ro",
          "code": "unlock_offline_clear",
          "description": "Optional. This algorithm is implemented by TuYa. After inputting the offline clear code on the door lock, the corresponding password is cleared, and the clearing event is reported.",
          "extensions": { "iconName": "icon-dp_upload", "attribute": "1344" },
          "name": "Offline Password Clear Report",
          "typeSpec": { "maxlen": 128, "type": "raw" }
        },
        {
          "abilityId": 49,
          "accessMode": "rw",
          "code": "remote_no_pd_setkey",
          "description": "Optional. A new encryption mechanism for remote door opening. This DP needs to be sent during network configuration.",
          "extensions": { "iconName": "icon-setting", "attribute": "1376" },
          "name": "Set No-Password Remote Door Opening Key",
          "typeSpec": { "maxlen": 128, "type": "raw" }
        },
        {
          "abilityId": 50,
          "accessMode": "rw",
          "code": "remote_no_dp_key",
          "description": "Optional. A new encryption mechanism for remote door opening. This DP should be sent when replying to a remote door opening.",
          "extensions": { "iconName": "icon-dp_lock", "attribute": "1376" },
          "name": "New No-Password Remote Door Opening with Key",
          "typeSpec": { "maxlen": 128, "type": "raw" }
        },
        {
          "abilityId": 57,
          "accessMode": "rw",
          "code": "lock_record",
          "description": "Optional. If this DP is selected, the device will report a lock record after locking the door.",
          "extensions": { "iconName": "icon-dp_lock", "attribute": "1344" },
          "name": "Lock Record",
          "typeSpec": { "maxlen": 128, "type": "raw" }
        },
        {
          "abilityId": 60,
          "accessMode": "rw",
          "code": "local_capacity_link",
          "description": "Optional. Check this feature when hardware has a local capacity that needs to be associated with the door opening method. For example, if taking photos or videos needs to be associated with the door opening method, this DP will be sent: Association function + door opening method type + door opening method ID.",
          "extensions": { "iconName": "icon-dp_mode", "attribute": "1344" },
          "name": "Link Local Capacity",
          "typeSpec": { "maxlen": 128, "type": "raw" }
        },
        {
          "abilityId": 70,
          "accessMode": "rw",
          "code": "lock_local_record",
          "description": "Optional. Report any operation record on the local door lock to the cloud. The cloud record will be displayed in the app and can be used for authentication and other scenarios.",
          "extensions": { "iconName": "icon-dp_book", "attribute": "96" },
          "name": "Local Door Lock Record",
          "typeSpec": { "maxlen": 128, "type": "raw" }
      ]
    }
  ]
}

```

# Product ID

umca8uiv2203ua3k

# Information about how the device functions

https://aliexpress.com/item/1005004495398206.html

**Comment by phid78** [comment]
Hi, I've been using home assistant for 1 week, and this is my first post here. I'm completely new to home automation and know nothing about scripting.
I was looking to integrate my Smartlock K7 from Tediton (functional on the Tuya android app, but not supported in home assistant) and I think it's the same model.
Here's what I found (if it helps): 

https://www.alibaba.com/product-detail/Tediton-Tuya-WIFI-APP-Fingerprint-Smart_10000013113540.html

 {
      "active_time": 1695739562,
      "category": "jtmspro",
      "create_time": 1695739562,
      "custom_name": "",
      "icon": "smart/program_category_icon/jtmspro.png",
      "id": "XXXX",
      "ip": "XX.XX.XX.XX",
      "is_online": true,
      "lat": "48.7XXX",
      "local_key": "XXXXXXXXXX",
      "lon": "2.0XXX",
      "model": "",
      "name": "WifiSmartLock",
      "product_id": "umca8uiv2203ua3k",
      "product_name": "WBR3(TX全)智能门锁",
      "sub": false,
      "time_zone": "+02:00",
      "update_time": 1696698853,
      "uuid": "XXXXXXXXX"
    },

    "documentation": "https://www.home-assistant.io/integrations/tuya",
    "integration_type": "hub",
    "iot_class": "cloud_push",
    "loggers": [
      "tuya_iot"
    ],
    "requirements": [
      "tuya-iot-py-sdk==0.6.6"
    ],
    "is_built_in": true
  },
  "data": {
    "endpoint": "https://openapi.tuyaeu.com",
    "auth_type": 0,
    "country_code": "33",
    "app_type": "tuyaSmart",
    "mqtt_connected": true,
    "disabled_by": null,
    "disabled_polling": false,
    "name": "WifiSmartLock",
    "model": "",
    "category": "jtmspro",
    "product_id": "umca8uiv2203ua3k",
    "product_name": "WifiSmartLock",
    "online": true,
    "sub": false,
    "time_zone": "+02:00",
    "active_time": "2023-09-26T14:46:02+00:00",
    "create_time": "2023-09-26T14:46:02+00:00",
    "update_time": "2023-10-22T12:21:52+00:00",
    "function": {
      "arming_switch": {
        "type": "Boolean",
        "value": {}
      },
      "remote_no_pd_setkey": {
        "type": "Raw",
        "value": {}
      },
      "remote_no_dp_key": {
        "type": "Raw",
        "value": {}
      },
      "lock_record": {
        "type": "Raw",
        "value": {}
      },
      "local_capacity_link": {
        "type": "Raw",
        "value": {}
      }
    },
    "status_range": {
      "unlock_fingerprint": {
        "type": "Integer",
        "value": {
          "min": 0,
          "max": 999,
          "scale": 0,
          "step": 1
        }
      },
      "unlock_password": {
        "type": "Integer",
        "value": {
          "min": 0,
          "max": 999,
          "scale": 0,
          "step": 1
        }
      },
      "unlock_temporary": {
        "type": "Integer",
        "value": {
          "min": 0,
          "max": 999,
          "scale": 0,
          "step": 1
        }
      },
      "unlock_card": {
        "type": "Integer",
        "value": {
          "min": 0,
          "max": 999,
          "scale": 0,
          "step": 1
        }
      },
      "unlock_face": {
        "type": "Integer",
        "value": {
          "min": 0,
          "max": 999,
          "scale": 0,
          "step": 1
        }
      },
      "unlock_key": {
        "type": "Integer",
        "value": {
          "min": 0,
          "max": 999,
          "scale": 0,
          "step": 1
        }
      },
      "alarm_lock": {
        "type": "Enum",
        "value": {
          "range": [
            "wrong_finger",
            "wrong_password",
            "wrong_card",
            "wrong_face",
            "tongue_bad",
            "too_hot",
            "unclosed_time",
            "tongue_not_out",
            "pry",
            "key_in",
            "low_battery",
            "power_off",
            "shock",
            "defense"
          ]
        }
      },
      "unlock_request": {
        "type": "Integer",
        "value": {
          "min": 0,
          "max": 999,
          "scale": 0,
          "step": 1
        }
      },
      "arming_switch": {
        "type": "Boolean",
        "value": {}
      },
      "residual_electricity": {
        "type": "Integer",
        "value": {
          "unit": `"%",`
          "min": 0,
          "max": 100,
          "scale": 1,
          "step": 1
        }
      },
      "unlock_app": {
        "type": "Integer",
        "value": {
          "min": 0,
          "max": 999,
          "scale": 0,
          "step": 1
        }
      },
      "hijack": {
        "type": "Boolean",
        "value": {}
      },
      "doorbell": {
        "type": "Boolean",
        "value": {}
      },
      "update_all_finger": {
        "type": "List",
        "value": {}
      },
      "update_all_password": {
        "type": "List",
        "value": {}
      },
      "update_all_card": {
        "type": "List",
        "value": {}
      },
      "update_all_face": {
        "type": "List",
        "value": {}
      },
      "update_all_fin_vein": {
        "type": "Raw",
        "value": {}
      },
      "unlock_offline_pd": {
        "type": "Raw",
        "value": {}
      },
      "unlock_offline_clear": {
        "type": "Raw",
        "value": {}
      },
      "remote_no_pd_setkey": {
        "type": "Raw",
        "value": {}
      },
      "remote_no_dp_key": {
        "type": "Raw",
        "value": {}
      },
      "lock_record": {
        "type": "Raw",
        "value": {}
      },
      "local_capacity_link": {
        "type": "Raw",
        "value": {}
      }
    },
    "status": {
      "unlock_fingerprint": 1,
      "unlock_password": 0,
      "unlock_temporary": 909,
      "unlock_card": 2,
      "unlock_face": 0,
      "unlock_key": 0,
      "alarm_lock": "wrong_password",
      "unlock_request": 0,
      "arming_switch": false,
      "residual_electricity": 50,
      "unlock_app": 0,
      "hijack": false,
      "doorbell": false,
      "update_all_finger": [
        1
      ],
      "update_all_password": [],
      "update_all_card": [
        2
      ],
      "update_all_face": [],
      "update_all_fin_vein": "",
      "unlock_offline_pd": "",
      "unlock_offline_clear": "",
      "remote_no_pd_setkey": "AAAB",
      "remote_no_dp_key": "",
      "lock_record": "",
      "local_capacity_link": ""
    },
    "home_assistant": {
      "name": "WifiSmartLock",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": []
    }
  }

DPS : 
Unlock with Fingerprint
1.	code: "1"

Unlock with code
1.	code: "2"

Unlock with tempory code
1.	code: "3"

Unlock with card
1.	code: "5"

Unlock with face reognition
1.	code: "6"

Door lock local operation record
1.	code: "70"

Unlock with mechanical key
1.	code: "7"

Alert
1.	code: "8"

Remote unlocking countdown
1.	code: "9"

Arm mode
1.	code: "10"

Remaining battery
1.	code: "12"

Remote unlocking in app
1.	code: "15"

Duress alarm
1.	code: "16"

Door bell
1.	code: "19"

Synchronize all fingerprints
1.	code: "25"

Synchronize all codes
1.	code: "26"

Synchronize all cartes
1.	code: "27"

Synchronize all faces
1.	code: "28"

Synchronize all finger veins
1.	code: "31"

Offline code unlocking
1.	code: "32"

Clearing offline codes
1.	code: "33"

Set key for no-code unlock
1.	code: "49"

No-code unlock
1.	code: "50"

Lock records
1.	code: "57"

Associate local lock capability
1.	code: "60"

**Comment by phid78** [comment]
looking at what has already been done for the smartlocks in the devices rep, I tried to create a file, but it does not work, how can i help you or you help me to move the integration forward?

`name: WifiSmartLock
icon: mdi:lock-smart
products:
  - id: umca8uiv2203ua3k
    name: WBR3 
    category : jtmspro
primary_entity:
  entity: lock
  dps:
    - id: 1
      name: unlock_fingerprint
      icon: mdi:fingerprint
      type: integer
      optional: true
      persist: false
    - id: 2
      name: unlock_password
      icon: mdi:keyboard
      type: integer
      optional: true
      persist: false
    - id: 3
      name: unlock_temp_pwd
      icon: mdi:keyboard-off
      type: integer
      optional: true
      persist: false
    - id: 5
      name: unlock_card
      icon: mdi:SmartCard
      type: integer
      optional: true
      persist: false
    - #id: 6
      #name: unlock_face
      #icon: mdi:FaceRecognition 
      #type: integer
      #optional: true
      #persist: false
    - id: 7 
      name: unlock_key
      icon: mdi:key_chain
      type: integer
      optional: true
      persist: false
    - id: 15 
      name: unlock_app
      icon: mdi:application
      type: integer
      optional: true
      persist: false
    - id: 9 
      name: request_unlock
      icon: mdi:LockQuestion
      type: integer
      optional: true
      persist: false
    - id: 32 
      name: unlock_offline_pd
      icon: mdi:LockOpenOutline
      type: integer
      optional: true
      persist: false
#   - id: 33 
  #   name: unlock_offline_clear
  #   icon: mdi:LockOffOutline
   #  type: integer
   #  optional: true
   #  persist: false
    - id: 57
      name: lock_record
      icon: mdi:clipboard-list
      type: string
      optional: true
    #- id: 70
      # name: lock_local_record
      # type: string
      # optional: true
secondary_entities:
  - entity: sensor
    class: battery
    category: diagnostic
    icon: mdi:BatteryHigh
    dps:
      - id: 12
        type: integer
        name: sensor
        unit: "%"
        class: measurement
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
          - dps_val: wrong_finger
            icon: mdi:FingerprintOff
            value: true
          - dps_val: "0"
            value: true
          - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: wrong_password
          icon: mdi:NumericOff  
          value: true
        - dps_val: "1"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: wrong_card
          icon: mdi:CardBulletedOff          
          value: true
        - dps_val: "2"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: wrong_face
          icon: mdi:EmoticonPoopOutline
          value: true
        - dps_val: "3"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: tongue_bad
          icon: mdi:EmoticonTongue
          value: true
        - dps_val: "4"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: too_hot
          icon: mdi:FireCircle
          value: true
        - dps_val: "5"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: unclosed_time
          icon: mdi:TimerLockOpenOutline
          value: true
        - dps_val: "6"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: tongue_not_out
          icon: mdi:EmoticonTongueOutline
          value: true
        - dps_val: "7"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: pry
          icon: mdi:HammerScrewdriver
          value: true
        - dps_val: "8"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: key_in
          icon: mdi:ShieldKey
          value: true
        - dps_val: "9"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: low_battery
          icon: mdi:BatteryLow
          value: true
        - dps_val: "10"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: power_off
          icon: mdi:BatteryAlertVariantOutline
          value: true
        - dps_val: "11"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: shock
          icon: mdi:Hammer
          value: true
        - dps_val: "12"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: defense
          icon: mdi:ShieldAlert
          value: true
        - dps_val: "13"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: stay_alarm
          icon: mdi:MotionSensor
          value: true
        - dps_val: "14"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: doorbell
          icon: mdi:Bell-alert
          value: true
        - dps_val: "15"
          value: true
        - value: false
  - entity: binary_sensor
    name: Duress
    class: safety
    category: diagnostic
    dps:
      - id: 16 
        type: boolean
        name: sensor
        optional: true
        persist: false
        mapping:
          - dps_val: null
            value: false
  - entity: binary_sensor
    name: Doorbell
    class: sound
    icon: mdi:Bell
    category: diagnostic
    dps:
      - id: 19
        type: boolean
        name: sensor
        optional: true
        persist: false
        mapping:
          - dps_val: null
            value: false
`

**Comment by felipecrs** [comment]
@make-all, do you mind sharing why this was closed?

**Comment by make-all** [comment]
With no local log information, there is zero chance that this will ever be worked on.
It does not help anybody to leave issues that won't be worked on in an open state indefinitely.

**Comment by felipecrs** [comment]
Oh. I didn't know. I will try to get the logs then.

**Comment by phid78** [comment]
it's not as if I asked the question of how to move the project forward...

**Comment by make-all** [comment]
I am sorry you feel frustrated after the work you put in, but my time is limited, and I cannot help debug your config with the information available on this issue.

Locks are complicated to support, they usually have a long list of dps in the iot.tuya.com API Explorer information, but the dps they actually report in the local protocol is very limited.  They can also have undocumented quirks in how they can be opened remotely.

**Comment by felipecrs** [comment]
Oh, sorry. Actually the door lock isn't mine and it isn't in my home, so it's a little more difficult for me to get such logs.

And I supposed it would be the Tuya Local Home Assistant integration logs for when I attempt to connect to the door lock and it fails, as the README mentions:

> 1. When attempting to add the device, if it is not supported, you will either get a message saying the device cannot be recognised at all, or you will be offered a list of devices (maybe a list of length 1) that are partial matches, often simple switch is among them. **You can cancel the process at this point, and look in the Home Assistant log - there should be a message there containing the current data points (dps) returned by the device.**

**Comment by make-all** [comment]
Battery powered devices won't work reliably even if you can get them connected in the few seconds after manually waking them.  A connection needs to be maintained for monitoring, and it won't be possible to send commands to the lock when it is asleep (no remote unlock).

**Comment by phid78** [comment]
do you need something else @make-all  ?

**Comment by WoodenLoony** [comment]
https://github.com/azerty9971/xtend_tuya
