### ISSUE TITLE
The alarm unit GauTone PG-103 security alarm system doesn't recognize correctly in configure process

### ISSUE THREAD

**Issue by apmsys-br** [make-all/tuya-local#1194]
I'm attempting to add this alarm unit model PG103. The option to choose doesn't make sense:

![image](https://github.com/make-all/tuya-local/assets/67117732/93b37ab8-1fd0-424d-a976-12a0704fcd9d)

Follow below the JSON query device details:

{
  "result": {
    "active_time": 1652995129,
    "category": "mal",
    "create_time": 1652995129,
    "custom_name": "Central Alarme",
    "icon": "smart/icon/ay15500268672065IQ53/228d374afbb9c201e98a29fce3779733.jpg",
    "id": "eb82df558866273154nbvn",
    "ip": "x.x.x.x",
    "is_online": true,
    "lat": "-19.9106",
    "local_key": "4d4b4e92b6dca056",
    "lon": "-44.1127",
    "model": "PG103",
    "name": "Alarm Host",
    "product_id": "z75vinnyhtgxhaxw",
    "product_name": "报警主机V2.2",
    "sub": false,
    "time_zone": "-03:00",
    "update_time": 1652995182,
    "uuid": "41c8846d23820591"
  },
  "success": true,
  "t": 1697739193213,
  "tid": "2acb53e96eab11ee847b16e7c18db4ee"
}

In Device readme this device should have support.
![image](https://github.com/make-all/tuya-local/assets/67117732/845618bb-67d1-4bc9-a6ef-f6f1de2bc2b4)

I attempted to make changes in the .yaml file but had no success. Can someone help me?

**Comment by make-all** [comment]
The important thing when reporting a bug is the Home Assistant log messages.

**Comment by apmsys-br** [comment]
Hello @make-all!
So sorry, lol...I forgot about it. Follow the log:
[Log tuya.txt](https://github.com/make-all/tuya-local/files/13055388/Log.tuya.txt)

I don't know but it seems like the tuya found something in the first line...Does it make sense? Will you need more information from my side? Thank you for your return!

**Comment by make-all** [comment]
The relevant lines would be this one:

```
2023-10-20 11:25:28.665 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config gautone_pg103_alarm.yaml
2023-10-20 11:25:28.666 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Not match for Alarm security system, missing required DPs: [{'10': 'bool'}]
```

**Comment by apmsys-br** [comment]
Hello @make-all!
I changed the YAML manually here according to your commit above. It works for me! Thanks 

![image](https://github.com/make-all/tuya-local/assets/67117732/a2d5df78-423b-43bd-8057-ac3f9676184e)

![image](https://github.com/make-all/tuya-local/assets/67117732/cc567831-a5b7-46cc-b9f6-511358c39ae2)
