### ISSUE TITLE
Failed to fetch device status

### ISSUE THREAD

**Issue by Anj-0110** [make-all/tuya-local#1197]
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**

--I am getting the following messages in the log...

This error originated from a custom integration.

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:546
Integration: Tuya Local (documentation, issues)
First occurred: October 18, 2023 at 11:03:39 (18833 occurrences)
Last logged: 10:51:41

Failed to fetch device status for Galley 10
Failed to fetch device status for Living room 1
Failed to fetch device status for Pendant 2
Failed to fetch device status for Galley 14
Failed to fetch device status for Galley 09

This error originated from a custom integration.

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:303
Integration: Tuya Local (documentation, issues)
First occurred: October 18, 2023 at 14:36:51 (6 occurrences)
Last logged: 08:00:53

**Coat closet error reading: Unexpected Payload from Device
Galley 14 error reading: Unexpected Payload from Device
Hall 1 error reading: Unexpected Payload from Device
Galley 10 error reading: Unexpected Payload from Device
UCL 4 error reading: Unexpected Payload from Device**

**To Reproduce**
Steps to reproduce the behavior including the device the issue was observed with:  

--I have restarted, updated and done all the things I am aware of.  New to HA so not sure what all to try??

**Expected behavior**

--Eliminate the errors

**Additional context**

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

**Comment by make-all** [comment]
Possibly the WiFi connection to the devices is not strong causing corruption of local messages, the protocol version is not quite right (only 3.2 and 3.3 are close enough to get misdetected and not quite work properly like this), or this device is using some part of the protocol not supported by the underlying tinytuya library.

None of these possible causes are a bug in this integration though, and the way this report is written it is maybe more suited to Discussions than Issues.
