### ISSUE TITLE
DETA Fan Contoller

### ISSUE THREAD

**Issue by meremortals70** [make-all/tuya-local#12]
I have a global keys file which has a lot of DP's listed in them.

How do I align them with the DP's that appear when I add a device to local Tuya.

Am I missing something or is it trial and error?

**Comment by make-all** [comment]
You need to figure out what (most of) the DPs mean by adjusting settings on the fan while observing them in the debug log or with tuya-cli.

If you have access to the schema file (which used to be accessible on some older versions of apps, and may still be on rooted devices), you can also look there (probably the description will be in Chinese, but Google Translate can narrow it down).

**Comment by make-all** [comment]
If you have more information on the DPS output of the device and meanings of each dps, which you can get by controlling the device from its control panel while querying it with tuya-cli, then I am ready to add it now.

If I do not get a response, I will have to close this request, as there is not enough information to go on. Unfortunately there is not a public repository with information about Tuya devices' dps assignments, so I have to rely on users to provide this information.  If you are able to get your local key, you should be able to query the device also.

**Comment by make-all** [comment]
Some info seems to be here: https://github.com/AMoo-Miki/homebridge-tuya-lan/pull/148#issuecomment-752759458

**Comment by make-all** [comment]
If the device is the same as that in the homebridge-tuya-lan issue linked above, then it should now be supported in 0.8.2.

**Comment by make-all** [comment]
As it is almost 3 months since support was added, and no feedback has been received, I am closing this now. Please open a new issue if the support is not working for you.
