### ISSUE TITLE
SmartIR 

### ISSUE THREAD

**Issue by rdaguerre** [make-all/tuya-local#120]
i have 2 devices in a SmartIR connected. i have  local key and Device ID but i dont have a ip host because is a SubDevice from SmartIR (smartlife IR hub). Excuse for my english
example

  { name: 'Smart IR',
    id: '6103724ab324',
    key: 'a89adfe461d',
    subDevices:
     [ { name: 'Denon',
         id: 'eb00856614vphy',
         cid: '6b25f6a95a' },
       { name: 'TV',
         id: 'eb1aa289vkau',
         cid: '1b0a59faebf' } ] } ]

**Comment by make-all** [comment]
Subdevices are not connected. I'm not sure what you can do with such devices anyway, as they do not expose any dps.
I think IR blaster support is so different than other devices, it should probably be its own integration.
