### ISSUE TITLE
Request support for Atorch (AT2PL) 2P AC110/220V 100A WIFI Din Rail Meter Leakage Security Protection Breaker Switch Remote Control By Tuya app

### ISSUE THREAD

**Issue by mykm203** [make-all/tuya-local#1200]
# Log Message

```
Please paste logs here
```

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"dw42x8\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"1024\"},\"name\":\"开关状态\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":9,\"accessMode\":\"rw\",\"code\":\"countdown_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"attribute\":\"1120\"},\"name\":\"开关倒计时\",\"typeSpec\":{\"max\":360000,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"s\"}},
{\"abilityId\":17,\"accessMode\":\"rw\",\"code\":\"add_ele\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-battery\",\"attribute\":\"1120\",\"trigger\":\"direct\"},\"name\":\"增加电量\",\"typeSpec\":{\"max\":5000000,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"kwh\"}},
{\"abilityId\":18,\"accessMode\":\"ro\",\"code\":\"cur_current\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-Ele\",\"attribute\":\"1088\"},\"name\":\"当前电流\",\"typeSpec\":{\"max\":120000,\"min\":0,\"scale\":3,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"A\"}},
{\"abilityId\":19,\"accessMode\":\"ro\",\"code\":\"cur_power\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_tool\",\"attribute\":\"1088\"},\"name\":\"当前功率\",\"typeSpec\":{\"max\":2700000,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"W\"}},
{\"abilityId\":20,\"accessMode\":\"ro\",\"code\":\"cur_voltage\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-a_function_turbo\",\"attribute\":\"1088\"},\"name\":\"当前电压\",\"typeSpec\":{\"max\":30000,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"V\"}},
{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"price\",\"description\":\"\",\"name\":\"电费单价\",\"typeSpec\":{\"max\":99999,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"\"}},
{\"abilityId\":102,\"accessMode\":\"ro\",\"code\":\"cost\",\"description\":\"\",\"name\":\"总电费\",\"typeSpec\":{\"max\":50000000,\"min\":0,\"scale\":3,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"\"}},
{\"abilityId\":103,\"accessMode\":\"ro\",\"code\":\"add_cost\",\"description\":\"\",\"extensions\":{\"trigger\":\"direct\"},\"name\":\"电费\",\"typeSpec\":{\"max\":5000000,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"\"}},
{\"abilityId\":104,\"accessMode\":\"rw\",\"code\":\"ovp\",\"description\":\"\",\"name\":\"过压值\",\"typeSpec\":{\"max\":2650,\"min\":1,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":1,\"unit\":\"V\"}},
{\"abilityId\":105,\"accessMode\":\"rw\",\"code\":\"ocp\",\"description\":\"\",\"name\":\"过流值\",\"typeSpec\":{\"max\":1000,\"min\":1,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":1,\"unit\":\"A\"}},
{\"abilityId\":106,\"accessMode\":\"rw\",\"code\":\"opp\",\"description\":\"\",\"name\":\"过功率值\",\"typeSpec\":{\"max\":27500,\"min\":1,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":1,\"unit\":\"W\"}},
{\"abilityId\":107,\"accessMode\":\"rw\",\"code\":\"language\",\"description\":\"\",\"name\":\"设备语言\",\"typeSpec\":{\"range\":[\"chinese\",\"english\"],\"type\":\"enum\",\"typeDefaultValue\":\"chinese\"}},
{\"abilityId\":108,\"accessMode\":\"rw\",\"code\":\"work_value\",\"description\":\"\",\"name\":\"工作屏幕亮度\",\"typeSpec\":{\"max\":9,\"min\":1,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":1,\"unit\":\"\"}},
{\"abilityId\":109,\"accessMode\":\"rw\",\"code\":\"standby_value\",\"description\":\"\",\"name\":\"待机屏幕亮度\",\"typeSpec\":{\"max\":9,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"\"}},
{\"abilityId\":110,\"accessMode\":\"rw\",\"code\":\"standby_time\",\"description\":\"\",\"name\":\"进入待机时间\",\"typeSpec\":{\"max\":99,\"min\":3,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":3,\"unit\":\"s\"}},
{\"abilityId\":111,\"accessMode\":\"rw\",\"code\":\"beep\",\"description\":\"\",\"name\":\"系统声音\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":112,\"accessMode\":\"rw\",\"code\":\"sw_mode\",\"description\":\"\",\"name\":\"开关模式\",\"typeSpec\":{\"range\":[\"controlled\",\"normally_open\"],\"type\":\"enum\",\"typeDefaultValue\":\"controlled\"}},
{\"abilityId\":113,\"accessMode\":\"rw\",\"code\":\"data_reset\",\"description\":\"\",\"name\":\"累计数据清零\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":114,\"accessMode\":\"rw\",\"code\":\"wifi_reset\",\"description\":\"\",\"name\":\"wifi设备重置\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":115,\"accessMode\":\"rw\",\"code\":\"factor_reset\",\"description\":\"\",\"name\":\"恢复出厂设置\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":116,\"accessMode\":\"rw\",\"code\":\"screen_rotation\",\"description\":\"\",\"name\":\"屏幕旋转\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":117,\"accessMode\":\"rw\",\"code\":\"standby_screen\",\"description\":\"\",\"name\":\"待机画面\",\"typeSpec\":{\"range\":[\"original\",\"measurement\"],\"type\":\"enum\",\"typeDefaultValue\":\"original\"}},
{\"abilityId\":118,\"accessMode\":\"rw\",\"code\":\"menu\",\"description\":\"\",\"name\":\"设备显示风格：\",\"typeSpec\":{\"range\":[\"front\",\"back\",\"display_off\"],\"type\":\"enum\",\"typeDefaultValue\":\"front\"}},
{\"abilityId\":119,\"accessMode\":\"rw\",\"code\":\"lvp\",\"description\":\"\",\"name\":\"欠压值\",\"typeSpec\":{\"max\":2750,\"min\":1,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":1,\"unit\":\"V\"}},
{\"abilityId\":120,\"accessMode\":\"rw\",\"code\":\"control\",\"description\":\"\",\"name\":\"超限控制使能\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":121,\"accessMode\":\"rw\",\"code\":\"olcp\",\"description\":\"\",\"name\":\"漏电阀值：\",\"typeSpec\":{\"max\":100,\"min\":10,\"scale\":3,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":10,\"unit\":\"A\"}},
{\"abilityId\":122,\"accessMode\":\"ro\",\"code\":\"leakage_ele\",\"description\":\"\",\"name\":\"漏电总电量\",\"typeSpec\":{\"max\":999999999,\"min\":0,\"scale\":3,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"kw.h\"}},
{\"abilityId\":123,\"accessMode\":\"ro\",\"code\":\"ele\",\"description\":\"\",\"name\":\"总电量\",\"typeSpec\":{\"max\":999999999,\"min\":0,\"scale\":3,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"kw.h\"}},
{\"abilityId\":124,\"accessMode\":\"rw\",\"code\":\"leakage_current\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-power1\",\"attribute\":\"4096\"},\"name\":\"漏电电流\",\"typeSpec\":{\"max\":120000,\"min\":0,\"scale\":3,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"A\"}},
{\"abilityId\":132,\"accessMode\":\"rw\",\"code\":\"warning\",\"description\":\"\",\"name\":\"告警标志\",\"typeSpec\":{\"range\":[\"off\",\"ovp\",\"ocp\",\"opp\",\"lvp\",\"le\",\"olcp\"],\"type\":\"enum\",\"typeDefaultValue\":\"off\"}},
{\"abilityId\":133,\"accessMode\":\"ro\",\"code\":\"cur_frequency\",\"description\":\"\",\"name\":\"当前频率\",\"typeSpec\":{\"max\":100000,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"Hz\"}},
{\"abilityId\":134,\"accessMode\":\"ro\",\"code\":\"power_factor\",\"description\":\"\",\"name\":\"功率因数\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"PF\"}},
{\"abilityId\":135,\"accessMode\":\"ro\",\"code\":\"cpu_temp\",\"description\":\"\",\"name\":\"仪表CPU温度\",\"typeSpec\":{\"max\":150,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"℃\"}},
{\"abilityId\":136,\"accessMode\":\"rw\",\"code\":\"price_mode\",\"description\":\"\",\"name\":\"电费模式选择：\",\"typeSpec\":{\"range\":[\"single_rate\",\"stair\",\"peak_valley_stair\"],\"type\":\"enum\",\"typeDefaultValue\":\"single_rate\"}},
{\"abilityId\":137,\"accessMode\":\"rw\",\"code\":\"over_time\",\"description\":\"\",\"name\":\"超限电压恢复延时：\",\"typeSpec\":{\"max\":99,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"min\"}},
{\"abilityId\":138,\"accessMode\":\"rw\",\"code\":\"ttl\",\"description\":\"\",\"name\":\"设备上电开关状态：\",\"typeSpec\":{\"range\":[\"open\",\"colse\"],\"type\":\"enum\",\"typeDefaultValue\":\"open\"}},
{\"abilityId\":139,\"accessMode\":\"rw\",\"code\":\"prepayment_switch\",\"description\":\"\",\"name\":\"预付费开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":140,\"accessMode\":\"ro\",\"code\":\"balance_energy\",\"description\":\"\",\"name\":\"剩余可用电量显示\",\"typeSpec\":{\"max\":500000,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"kW·h\"}},
{\"abilityId\":141,\"accessMode\":\"rw\",\"code\":\"clear_energy\",\"description\":\"\",\"name\":\"剩余可用电量清零\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":142,\"accessMode\":\"rw\",\"code\":\"energy_charge\",\"description\":\"\",\"name\":\"电量充值\",\"typeSpec\":{\"max\":500000,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"kW·h\"}},
{\"abilityId\":143,\"accessMode\":\"rw\",\"code\":\"credit\",\"description\":\"\",\"name\":\"电量不足报警值\",\"typeSpec\":{\"max\":500,\"min\":10,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":10,\"unit\":\"kW·h\"}}]}]}"
  },
  "success": true,
  "t": 1697797212604,
  "tid": "410822f76f3211ee8665fe445e07f2df"
}
```

# Product ID

# Information about how the device functions

**Comment by mykm203** [comment]
DIN version of #1103

**Comment by mykm203** [comment]
Looks like yaml file dhould looks like:
------------------------------------------
atorch_at2pl.yaml
------------------------------------------
name: Energy monitoring plug with display Atorch AT2PL
products:
  - id: seqzqh45b0ggn9so
    name: Atorch AT2PL
primary_entity:
  entity: switch
  class: outlet
  dps:
    - id: 1
      type: boolean
      name: switch
      optional: true
secondary_entities:
  - entity: number
    category: config
    name: Countdown
    icon: "mdi:timer"
    dps:
      - id: 9
        type: integer
        name: value
        mapping:
          - scale: 1
            step: 1
        range:
          min: 0
          max: 360000
        unit: s
  - entity: sensor
    class: current
    name: add_ele
    dps:
      - id: 17
        type: integer
        name: sensor
        mapping:
          - scale: 100
            step: 1
        range:
          min: 0
          max: 5000000
        unit: kWh
        class: measurement
  - entity: sensor
    class: current
    name: Current
    dps:
      - id: 18
        type: integer
        name: sensor
        readonly: true
        mapping:
          - scale: 1000
            step: 1
        range:
          min: 0
          max: 120000
        unit: A
        class: measurement
  - entity: sensor
    class: power
    name: Power
    dps:
      - id: 19
        type: integer
        name: sensor
        readonly: true
        mapping:
          - scale: 100
            step: 1
        range:
          min: 0
          max: 2700000
        unit: W
        class: measurement
  - entity: sensor
    class: voltage
    name: Voltage
    dps:
      - id: 20
        type: integer
        name: sensor
        readonly: true
        mapping:
          - scale: 100
        step: 1
        range:
          min: 0
          max: 30000
        unit: V
        class: measurement
  - entity: number
    category: config
    name: Electricity price
    icon: "mdi:cash-multiple"
    dps:
      - id: 101
        type: integer
        name: value
        mapping:
          - scale: 100
        step: 1
        range:
          min: 0
          max: 99999
  - entity: sensor
    name: Total Cost
    dps:
      - id: 102
        type: integer
        name: sensor
        readonly: true
        mapping:
          - scale: 1000
        step: 1
        range:
          min: 0
          max: 50000000
  - entity: sensor
    name: Add Cost
    dps:
      - id: 103
        type: integer
        name: sensor
        readonly: true
        mapping:
          - scale: 100
            step: 1
        range:
          min: 0
          max: 5000000
  - entity: number
    category: config
    name: Overvoltage value
    icon: "mdi:flash-triangle"
    dps:
      - id: 104
        type: integer
        name: value
        mapping:
          - scale: 10
            step: 1
        range:
          min: 0
          max: 2650
        unit: V
  - entity: number
    category: config
    name: Overcurrent value
    icon: "mdi:flash-triangle"
    dps:
      - id: 105
        type: integer
        name: value
        mapping:
          - scale: 10
            step: 1
        range:
          min: 0
          max: 1000
        unit: A
  - entity: number
    category: config
    name: Overpower value
    icon: "mdi:flash-triangle"
    dps:
      - id: 106
        type: integer
        name: value
        mapping:
          - scale: 1
            step: 1
        range:
          min: 0
          max: 27500
        unit: W
  - entity: select
    category: config
    icon: "mdi:web-box"
    name: Language
    dps:
      - id: 107
        type: string
        name: option
        mapping:
          - dps_val: chinese
            value: Chinese
          - dps_val: english
            value: English
  - entity: number
    category: config
    name: Screen brightness
    icon: "mdi:brightness-7"
    dps:
      - id: 108
        type: integer
        name: value
        range:
          min: 1
          max: 9
  - entity: number
    category: config
    name: Standby brightness
    icon: "mdi:brightness-4"
    dps:
      - id: 109
        type: integer
        name: value
        range:
          min: 1
          max: 9
  - entity: number
    category: config
    name: Standby time
    icon: "mdi:sun-clock"
    dps:
      - id: 110
        type: integer
        name: value
        range:
          min: 3
          max: 99
        unit: s
  - entity: switch
    name: Beep
    category: config
    dps:
      - id: 111
        type: boolean
        name: switch
  - entity: select
    name: Switch mode
    category: config
    dps:
      - id: 112
        type: string
        name: option
        mapping:
          - dps_val: controlled
            value: Controlled
          - dps_val: normally_open
            value: Normally Open
  - entity: button
    name: Reset data
    category: diagnostic
    icon: "mdi:autorenew"
    dps:
      - id: 113
        type: boolean
        name: button
        optional: true
  - entity: button
    name: Reset Wi-Fi
    category: diagnostic
    icon: "mdi:autorenew"
    dps:
      - id: 114
        type: boolean
        name: button
        optional: true
  - entity: button
    name: Factory reset
    category: diagnostic
    icon: "mdi:autorenew"
    dps:
      - id: 115
        type: boolean
        name: button
        optional: true
  - entity: button
    name: Screen rotate
    category: config
    icon: "mdi:screen-rotation"
    dps:
      - id: 116
        type: boolean
        name: button
        optional: true
  - entity: select
    category: config
    name: Standby screen
    dps:
      - id: 117
        type: string
        name: option
        mapping:
          - dps_val: original
            value: Original
          - dps_val: measurement
            value: Measurement
  - entity: select
    category: config
    name: Display style
    dps:
      - id: 118
        type: string
        name: option
        mapping:
          - dps_val: front
            value: Front
          - dps_val: back
            value: Back
          - dps_val: display_off
            value: Display Off
  - entity: number
    category: config
    name: LVP
    icon: "mdi:flash-triangle"
    dps:
      - id: 119
        type: integer
        name: value
        mapping:
          - scale: 10
            step: 1
        range:
          min: 0
          max: 2750
        unit: V    
  - entity: switch
    name: Control
    category: config
    dps:
      - id: 120
        type: boolean
        name: switch
  - entity: number
    category: config
    name: OLCP
    icon: "mdi:flash-triangle"
    dps:
      - id: 121
        type: integer
        name: value
        mapping:
          - scale: 1000
            step: 1
        range:
          min: 10
          max: 100
        unit: A
  - entity: number
    category: config
    name: Total Leakage Power
    dps:
      - id: 122
        type: integer
        name: value
        readonly: true
        mapping:
          - scale: 1000
            step: 1
        range:
          min: 1
          max: 999999999
        unit: kWh
        class: total_increasing
  - entity: sensor
    name: Total Power
    class: energy
    dps:
      - id: 123
        name: sensor
        type: integer
        readonly: true
        mapping:
          - scale: 1000
            step: 1
        range:
          min: 1
          max: 999999999
        unit: kWh
        class: total_increasing        
  - entity: sensor
    name: leakage_current
    category: diagnostic
    class: energy
    dps:
      - id: 124
        name: sensor
        type: integer
        mapping:
          - scale: 1000
        step: 1
        range:
          min: 1
          max: 120000
        unit: kWh
        class: measurement         
  - entity: sensor
    name: Warning
    class: enum
    category: diagnostic
    icon: "mdi:eye-circle-outline"
    dps:
      - id: 132
        name: sensor
        type: string
        mapping:
          - dps_val: off
            value: Off
          - dps_val: ovp
            value: Overvoltage protection
          - dps_val: ocp
            value: Overcurrent protection
          - dps_val: opp
            value: Overpower protection
          - dps_val: lvp
            value: Lower voltage protection
          - dps_val: le
            value: protection
          - dps_val: olcp
            value: protection
  - entity: sensor
    class: frequency
    name: Frequency
    dps:
      - id: 133
        name: sensor
        type: integer
        readonly: true
        mapping:
          - scale: 100
            step: 1
        range:
          min: 1
          max: 100000
        unit: Hz
        class: measurement        
  - entity: sensor
    name: Power factor
    class: power_factor
    dps:
      - id: 134
        name: sensor
        type: integer
        readonly: true
        mapping:
          - scale: 100
            step: 1
        range:
          min: 1
          max: 100
        unit: PF
        class: measurement
  - entity: sensor
    name: CPU Temperature
    category: diagnostic
    class: temperature
    dps:
      - id: 135
        name: sensor
        type: integer
        readonly: true
        mapping:
          - scale: 1
            step: 1
        range:
          min: 1
          max: 150
        unit: ℃
        class: measurement
  - entity: select
    category: config
    name: Energy tariff
    dps:
      - id: 136
        type: string
        name: option
        mapping:
          - dps_val: single_rate
            value: Single rate
          - dps_val: stair
            value: Stair
          - dps_val: peak_valley_stair
            value: Peak-valley
  - entity: number
    category: config
    name: Overvoltage recovery delay
    icon: "mdi:timer"
    dps:
      - id: 137
        type: integer
        name: value
        mode: box
        range:
          min: 0
          max: 99
        unit: min
  - entity: select
    category: config
    name: Poweron switch status
    dps:
      - id: 138
        type: string
        name: option
        mapping:
          - dps_val: open
            value: "On"
          - dps_val: colse
            value: "Off"
  - entity: switch
    category: config
    name: Prepaid Switch
    dps:
      - id: 139
        type: boolean
        name: switch
  - entity: select
    category: config
    name: Balance Energy
    dps:
      - id: 140
        type: integer
        name: value
        readonly: true
        mapping:
          - scale: 100
            step: 1
        range:
          min: 0
          max: 500000
        unit: kWh
        class: measurement
  - entity: switch
    category: config
    name: Clear Eenergy
    dps:
      - id: 141
        type: boolean
        name: switch
        optional: true
  - entity: select
    category: config
    name: Energy Charge
    dps:
      - id: 142
        type: integer
        name: value
        readonly: true
        optional: true
        mapping:
          - scale: 100
            step: 1
        range:
          min: 0
          max: 500000
        unit: kWh
        class: measurement
  - entity: select
    category: config
    name: Credit
    dps:
      - id: 143
        type: integer
        name: value
        readonly: true
        mapping:
          - scale: 1
            step: 1
        range:
          min: 10
          max: 500
        unit: kWh
        class: measurement
-----------------------------
But when I put this file in device sirectory, and go to configuration, its not showing in chose devise dropdown list. What I should do?

Debug list:
--------------
"integration_manifest": {
    "domain": "tuya_local",
    "name": "Tuya Local",
    "codeowners": [
      "@make-all"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/make-all/tuya-local",
    "integration_type": "device",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/make-all/tuya-local/issues",
    "requirements": [
      "pycryptodome~=3.18",
      "tinytuya==1.12.11"
    ],
    "version": "2023.11.0",
    "is_built_in": false
  },
  "data": {
    "name": "Advanced energy monitoring smartplug",
    "type": "smartplugv2_energy",
    "device_id": "",
    "device_cid": "",
    "local_key": "I",
    "host": "",
    "protocol_version": 3.4,
    "tinytuya_version": "1.12.11",
    "api_version_set": 3.4,
    "api_version_used": 3.4,
    "api_working": true,
    "status": {},
    "cached_state": {
      "updated_at": 1701186613.3351827,
      "1": true,
      "9": 0,
      "18": 5421,
      "19": 88106,
      "20": 22456,
      "101": 10100,
      "102": 427954,
      "103": 7,
      "104": 2450,
      "105": 500,
      "106": 10000,
      "107": "english",
      "108": 9,
      "109": 3,
      "110": 60,
      "111": true,
      "112": "controlled",
      "117": "measurement",
      "118": "front",
      "119": 1800,
      "120": true,
      "121": 100,
      "122": 0,
      "123": 4237,
      "124": 0,
      "132": "off",
      "133": 4998,
      "134": 72,
      "135": 43,
      "136": "single_rate",
      "137": 2,
      "138": "open",
      "139": false,
      "140": 50000,
      "143": 30,
      "17": 5
    },
    "pending_state": {},
    "connected": true,
    "force_dps": [],
    "home_assistant": {
      "name": "Advanced energy monitoring smartplug",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": "min",
          "state": {
            "entity_id": "number.advanced_energy_monitoring_smartplug_timer",
            "state": "0.0",
            "attributes": {
              "min": 0.0,
              "max": 1440.0,
              "step": 1.0,
              "mode": "auto",
              "unit_of_measurement": "min",
              "icon": "mdi:timer",
              "friendly_name": "Advanced energy monitoring smartplug Timer"
            },
            "last_changed": "2023-11-28T15:45:50.126569+00:00",
            "last_updated": "2023-11-28T15:45:50.126569+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "outlet",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.advanced_energy_monitoring_smartplug",
            "state": "on",
            "attributes": {
              "device_class": "outlet",
              "friendly_name": "Advanced energy monitoring smartplug"
            },
            "last_changed": "2023-11-28T15:45:50.126003+00:00",
            "last_updated": "2023-11-28T15:45:50.126003+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": "switch",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.advanced_energy_monitoring_smartplug_overcharge_cutoff",
            "state": "unknown",
            "attributes": {
              "device_class": "switch",
              "icon": "mdi:battery-charging",
              "friendly_name": "Advanced energy monitoring smartplug Overcharge cutoff"
            },
            "last_changed": "2023-11-28T15:45:50.126215+00:00",
            "last_updated": "2023-11-28T15:45:50.126215+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "lock.advanced_energy_monitoring_smartplug_child_lock",
            "state": "unknown",
            "attributes": {
              "icon": "mdi:hand-back-right-off",
              "friendly_name": "Advanced energy monitoring smartplug Child lock",
              "supported_features": 0
            },
            "last_changed": "2023-11-28T15:45:50.126975+00:00",
            "last_updated": "2023-11-28T15:45:50.126975+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "select.advanced_energy_monitoring_smartplug_initial_state",
            "state": "unknown",
            "attributes": {
              "options": [
                "On",
                "Off",
                "Last State"
              ],
              "icon": "mdi:toggle-switch",
              "friendly_name": "Advanced energy monitoring smartplug Initial state"
            },
            "last_changed": "2023-11-28T15:45:50.125407+00:00",
            "last_updated": "2023-11-28T15:45:50.125407+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "select.advanced_energy_monitoring_smartplug_light",
            "state": "unknown",
            "attributes": {
              "options": [
                "State",
                "Position",
                "Off",
                "On"
              ],
              "icon": "mdi:circle-double",
              "friendly_name": "Advanced energy monitoring smartplug Light"
            },
            "last_changed": "2023-11-28T15:45:50.125638+00:00",
            "last_updated": "2023-11-28T15:45:50.125638+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": "Wh",
          "state": {
            "entity_id": "sensor.advanced_energy_monitoring_smartplug_energy",
            "state": "5",
            "attributes": {
              "unit_of_measurement": "Wh",
              "friendly_name": "Advanced energy monitoring smartplug Energy"
            },
            "last_changed": "2023-11-28T15:49:59.995550+00:00",
            "last_updated": "2023-11-28T15:49:59.995550+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "current",
          "icon": null,
          "unit_of_measurement": "mA",
          "state": {
            "entity_id": "sensor.advanced_energy_monitoring_smartplug_current",
            "state": "5421",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "mA",
              "device_class": "current",
              "friendly_name": "Advanced energy monitoring smartplug Current"
            },
            "last_changed": "2023-11-28T15:50:11.514981+00:00",
            "last_updated": "2023-11-28T15:50:11.514981+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "power",
          "icon": null,
          "unit_of_measurement": "W",
          "state": {
            "entity_id": "sensor.advanced_energy_monitoring_smartplug_power",
            "state": "8810.6",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "W",
              "device_class": "power",
              "friendly_name": "Advanced energy monitoring smartplug Power"
            },
            "last_changed": "2023-11-28T15:50:11.658083+00:00",
            "last_updated": "2023-11-28T15:50:11.658083+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "voltage",
          "icon": null,
          "unit_of_measurement": "V",
          "state": {
            "entity_id": "sensor.advanced_energy_monitoring_smartplug_voltage",
            "state": "2245.6",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "V",
              "device_class": "voltage",
              "friendly_name": "Advanced energy monitoring smartplug Voltage"
            },
            "last_changed": "2023-11-28T15:50:10.895574+00:00",
            "last_updated": "2023-11-28T15:50:10.895574+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "problem",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "binary_sensor.advanced_energy_monitoring_smartplug_error",
            "state": "off",
            "attributes": {
              "device_class": "problem",
              "friendly_name": "Advanced energy monitoring smartplug Error"
            },
            "last_changed": "2023-11-28T15:45:50.123940+00:00",
            "last_updated": "2023-11-28T15:45:50.123940+00:00"
          }
        }
      ]
    }
  }
}

**Comment by make-all** [comment]
Yes, when you make a config from only the cloud documentation, it very likely won7t work. This is why I must insist on local logs. The device diagnostics above should be enough to figure things out.
