### ISSUE TITLE
Request support for WIFI Aire Acondicionado Inteligente Vivion

### ISSUE THREAD

**Issue by magomao** [make-all/tuya-local#1203]
Tuya-Local didnt givme the Climate option when try to add it

Air Conditioner Vivion

id1 switch | Boolean | "{true,false}"
id2 temp_set | Integer | {   "unit": "℃",   "min": 16,   "max": 32,   "scale": 0,   "step": 1 }
id3 temp_current | Integer | {   "unit": "℃",   "min": -50,   "max": 50,   "scale": 0,   "step": 1 }
id4 mode | Enum | {   "range": [     "auto",     "cold",     "hot",     "wet",     "wind"   ] }
id5 fan_speed_enum | Enum | {   "range": [     "strong",     "auto",     "low",     "middle",     "high",     "mute"   ] }
id11 anion | Boolean | "{true,false}"
id12 heat | Boolean | "{true,false}"
id22 fault | Bitmap | "label": [     "E0",     "E1",     "E2",     "E3",     "E4",     "E5",     "E6",     "E7",     "P8",     "P9",     "P10",     "P11",     "P12",     "P13",     "P14",     "P15"   ]
id25 sleep | Boolean | "{true,false}"
id31 gear_vertical | Enum | "range": [     "off",     "same",     "vane_1",     "vane_2",     "vane_3",     "vane_4",     "vane_5"   ] 
id33switch_horizontal | Boolean | "{true,false}"
id36 display | Boolean | "{true,false}"
id101 timer on
id102 timer off

{
  "result": {
    "active_time": 1678893134,
    "category": "kt",
    "create_time": 1678893134,
    "custom_name": "Aire Living",
    "icon": "smart/icon/bay1587470497289eqWq/832ef9e5f6985294fdbdbfcd4dd50d75.jpg",
    "id": "***********************",
    "ip": "**************",
    "is_online": true,
    "lat": "********",
    "local_key": "**********************",
    "lon": "**********",
    "model": "300123 300124 300125",
    "name": "Aire Acondicionado Inteligente Vivion",
    "product_id": "orgvakh0qub0hjx8",
    "product_name": "Aire Acondicionado Inteligente Vivion",
    "sub": false,
    "time_zone": "-03:00",
    "update_time": 1697756304,
    "uuid": "79bcb1e968780010"
  },
  "success": true,
  "t": 1697756905887,
  "tid": "68618aa86ed411ee88d87e68e426c0a4"

I wrote this YAML file into DEVICES but when try to add the device didnt show me the Climate option.

name: "Aire Acondicionado Inteligente Vivion"
products:
  - id: "orgvakh0qub0hjx8"
    model: "300123 300124 300125"
    primary_entity:
      entity: climate
      icon: "mdi:air-conditioner"
    dps:
      - id: 1
        name: "switch"
        type: "boolean"
      - id: 2
        name: "temp_set"
        type: "integer"
        min: 16
        max: 32
        scale: 0
        step: 1
        unit: "℃"
      - id: 3
        name: "temp_current"
        type: "integer"
        min: -50
        max: 50
        scale: 0
        step: 1
        unit: "℃"
      - id: 4
        name: "mode"
        type: "enum"
        range:
          - "auto"
          - "cold"
          - "hot"
          - "wet"
          - "wind"
      - id: 5
        name: "fan_speed_enum"
        type: "enum"
        range:
          - "strong"
          - "auto"
          - "low"
          - "middle"
          - "high"
          - "mute"
      - id: 11
        name: "anion"
        type: "boolean"
        map: "anion"
      - id: 12
        name: "heat"
        type: "boolean"
      - id: 31
        name: "gear_vertical"
        type: "enum"
        range:
          - "off"
          - "same"
          - "vane_1"
          - "vane_2"
          - "vane_3"
          - "vane_4"
          - "vane_5"
      - id: 33
        name: "switch_horizontal"
        type: "boolean"
      - id: 36
        name: "display"
        type: "boolean"
      - id: 101
        name: "timer_on"
        type: "boolean"
      - id: 102
        name: "timer_off"
        type: "boolean"

---------------------------------------------------

Standard status set

switch | Boolean | "{true,false}"
temp_set | Integer | {   "unit": "℃",   "min": 16,   "max": 32,   "scale": 0,   "step": 1 }
temp_current | Integer | {   "unit": "℃",   "min": -50,   "max": 50,   "scale": 0,   "step": 1 }
mode | Enum | {   "range": [     "auto",     "cold",     "hot",     "wet",     "wind"   ] }
fan_speed_enum | Enum | {   "range": [     "strong",     "auto",     "low",     "middle",     "high",     "mute"   ] }
anion | Boolean | "{true,false}"
heat | Boolean | "{true,false}"
gear_vertical | Enum | {   "range": [     "off",     "same",     "vane_1",     "vane_2",     "vane_3",     "vane_4",     "vane_5"   ] }
switch_horizontal | Boolean | "{true,false}"

**Comment by magomao** [comment]
ERROR LOGS

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:103 
Integration: Tuya Local (documentation, issues) 
First occurred: 19:02:42 (1 occurrences) 
Last logged: 19:02:42

Report this to https://github.com/make-all/tuya-local/issues/


Logger: custom_components.tuya_local.helpers.device_config
Source: custom_components/tuya_local/helpers/device_config.py:981 
Integration: Tuya Local (documentation, issues) 
First occurred: 19:02:42 (1 occurrences) 
Last logged: 19:02:42

Parse error in vivion_air_conditioner.yaml


Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:97 
Integration: Tuya Local (documentation, issues) 
First occurred: 19:02:42 (1 occurrences) 
Last logged: 19:02:42

Device matches feit_dimmer with quality of 21%. DPS: {"updated_at": 1699653755.476912, "1": true, "2": 23, "3": 25, "4": "hot", "5": "auto", "11": false, "12": true, "25": false, "31": "vane_3", "33": false, "36": true, "101": false, "102": false, "103": "0000", "104": "0000", "105": false, "106": true, "107": false, "108": 0}

**Comment by magomao** [comment]
<img width="814" alt="Captura de pantalla 2023-11-10 a la(s) 7 51 11 p  m" src="https://github.com/make-all/tuya-local/assets/83680228/38c83be7-2d8c-4d10-a37d-614b1d7a4899">

didnt show climate option

**Comment by magomao** [comment]
Hi @make-all , there's anything else I should/could  do for help or just wait for this to be added?

**Comment by make-all** [comment]
This is in the queue, the full_info tag and the Ready status mean it is not waiting on anything but volunteers' time.
