### ISSUE TITLE
Request support for PJ2101A 1P WiFi Smart Meter-Bidirectional

### ISSUE THREAD

**Issue by jnasserifar** [make-all/tuya-local#1204]
Could you please provide a support for power meter single phase  PJ2101A 1P WiFi Smart Meter-Bidirectional.

      "model": "PJ2101A",
      "name": "PJ2101A 1P WiFi Smart Meter ",
      "product_id": "ze8faryrxr0glqnn",
      "product_name": "PJ2101A 1P WiFi Smart Meter "

	  {
  "result": {
    "properties": [
      {
        "code": "forward_energy_total",
        "custom_name": "",
        "dp_id": 1,
        "time": 1697918972757,
        "value": 0
      },
      {
        "code": "reverse_energy_total",
        "custom_name": "",
        "dp_id": 2,
        "time": 1697918972769,
        "value": 0
      },
      {
        "code": "month_energy",
        "custom_name": "",
        "dp_id": 3,
        "time": 1697918742302
      },
      {
        "code": "daily_energy",
        "custom_name": "",
        "dp_id": 4,
        "time": 1697918742302
      },
      {
        "code": "phase_a",
        "custom_name": "",
        "dp_id": 6,
        "time": 1697919534732,
        "value": "BMgACtIAARo="
      },
      {
        "code": "power",
        "custom_name": "",
        "dp_id": 101,
        "time": 1697919534851,
        "value": 282
      },
      {
        "code": "current_direction",
        "custom_name": "",
        "dp_id": 102,
        "time": 1697918954147,
        "value": "FORWARD"
      }
    ]
  },
  "success": true,
  "t": 1697919537175,
  "tid": "102cd97a704f11ee88d87e68e426c0a4"

**Comment by jnasserifar** [comment]
Currently when I add with protocol 3.5 the following devices proposed.
![image](https://github.com/make-all/tuya-local/assets/29044416/fca48c03-6726-4263-8797-8046b4b37c2d)

**Comment by openshwprojects** [comment]
This one seems to work OK with OpenBeken: https://www.elektroda.com/rtvforum/viewtopic.php?p=21092624#21092624
