### ISSUE TITLE
Request support for ZM-wi-Fi Smart Meter

### ISSUE THREAD

**Issue by mellow8** [make-all/tuya-local#1208]
Could you please provide a support for power meter single phase ZM-wi-Fi Smart Meter.

"model": "ZM-wi-Fi -电表",
      "name": "WiFi Smart Meter",
      "product_id": "nzexeqam9qulajbf",
      "product_name": "WiFi Smart Meter",

{
  "result": {
    "properties": [
      {
        "code": "total_forward_energy",
        "custom_name": "",
        "dp_id": 1,
        "time": 1697991145657,
        "value": 452860
      },
      {
        "code": "phase_a",
        "custom_name": "",
        "dp_id": 6,
        "time": 1697991179989,
        "value": "CR8ADjAAAtw="
      },
      {
        "code": "fault",
        "custom_name": "",
        "dp_id": 10,
        "time": 1697976210955,
        "value": 0
      },
      {
        "code": "switch",
        "custom_name": "",
        "dp_id": 16,
        "time": 1697976210955,
        "value": true
      },
      {
        "code": "alarm_set_2",
        "custom_name": "",
        "dp_id": 17,
        "time": 1697975758236,
        "value": "AQAAPAMAAO4EAADI"
      },
      {
        "code": "meter_id",
        "custom_name": "",
        "dp_id": 18,
        "time": 1697976210955,
        "value": "111111111111"
      }
    ]
  },
  "success": true,
  "t": 1697991182108,
  "tid": "dfe3d93d70f511ee88d87e68e426c0a4"
}

**result from the Query Things Data Model function**

{
  "result": {
    "model": "{\"modelId\":\"000002ksab\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"ro\",\"code\":\"total_forward_energy\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"正向总有功电量\",\"typeSpec\":{\"max\":99999999,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"kW·h\"}},{\"abilityId\":6,\"accessMode\":\"ro\",\"code\":\"phase_a\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"A相电压，电流及功率\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},{\"abilityId\":10,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"告警事件\",\"typeSpec\":{\"label\":[\"ov_cr\",\"unbalance_alarm\",\"ov_vol\",\"undervoltage_alarm\",\"miss_phase_alarm\",\"outage_alarm\",\"magnetism_alarm\",\"terminal_alarm\",\"cover_alarm\",\"credit_alarm\",\"battery_alarm\",\"meter_hardware_alarm\",\"no_balance_alarm\"],\"maxlen\":13,\"type\":\"bitmap\",\"typeDefaultValue\":0}},{\"abilityId\":16,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"电表拉合闸\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":17,\"accessMode\":\"rw\",\"code\":\"alarm_set_2\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"告警设置\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},{\"abilityId\":18,\"accessMode\":\"ro\",\"code\":\"meter_id\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"设备号显示 \",\"typeSpec\":{\"maxlen\":255,\"type\":\"string\",\"typeDefaultValue\":\"\"}}]}]}"
  },
  "success": true,
  "t": 1698230477606,
  "tid": "0702c42a732311ee8b62ea7d43a7f458"
}

**Comment by golfsupamit** [comment]
I same issue any update about device.

**Comment by mellow8** [comment]
result from the Query Things Data Model function

{
  "result": {
    "model": "{\"modelId\":\"000002ksab\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"ro\",\"code\":\"total_forward_energy\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"正向总有功电量\",\"typeSpec\":{\"max\":99999999,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"kW·h\"}},{\"abilityId\":6,\"accessMode\":\"ro\",\"code\":\"phase_a\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"A相电压，电流及功率\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},{\"abilityId\":10,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"告警事件\",\"typeSpec\":{\"label\":[\"ov_cr\",\"unbalance_alarm\",\"ov_vol\",\"undervoltage_alarm\",\"miss_phase_alarm\",\"outage_alarm\",\"magnetism_alarm\",\"terminal_alarm\",\"cover_alarm\",\"credit_alarm\",\"battery_alarm\",\"meter_hardware_alarm\",\"no_balance_alarm\"],\"maxlen\":13,\"type\":\"bitmap\",\"typeDefaultValue\":0}},{\"abilityId\":16,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"电表拉合闸\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":17,\"accessMode\":\"rw\",\"code\":\"alarm_set_2\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"告警设置\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},{\"abilityId\":18,\"accessMode\":\"ro\",\"code\":\"meter_id\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"设备号显示 \",\"typeSpec\":{\"maxlen\":255,\"type\":\"string\",\"typeDefaultValue\":\"\"}}]}]}"
  },
  "success": true,
  "t": 1698230477606,
  "tid": "0702c42a732311ee8b62ea7d43a7f458"
}

**Comment by mellow8** [comment]
**### log form hass**

This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:49
Integration: Tuya Local (documentation, issues)
First occurred: 18:21:03 (8 occurrences)
Last logged: 18:51:11

Device matches None with quality of 0%. DPS: {"updated_at": 1698232863.0311344, "1": 456323, "10": 0, "16": true, "18": "111111111111"}
Report this to https://github.com/make-all/tuya-local/issues/
Device matches None with quality of 0%. DPS: {"updated_at": 1698233285.0382235, "1": 456338, "10": 0, "16": true, "18": "111111111111"}
Device matches None with quality of 0%. DPS: {"updated_at": 1698233570.824418, "6": "CMoAF3oABOo="}
Device matches None with quality of 0%. DPS: {"updated_at": 1698234670.5094569, "1": 456369, "10": 0, "16": true, "18": "111111111111"}

Logger: homeassistant.util.async_
Source: util/async_.py:164
First occurred: October 24, 2023 at 21:54:11 (24 occurrences)
Last logged: 18:51:09

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 77: self._api = tinytuya.Device(dev_id, address, local_key)
