### ISSUE TITLE
Detected blocking call to sleep inside the event loop

### ISSUE THREAD

**Issue by larronni** [make-all/tuya-local#1209]
**Describe the bug**

Logger: homeassistant.util.async_
Source: util/async_.py:137
First occurred: 05:30:43 (1 occurrences)
Last logged: 05:30:43

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 77: self._api = tinytuya.Device(dev_id, address, local_key)

**To Reproduce**

Reboot HA

**Comment by make-all** [comment]
Duplicate of #482
