### ISSUE TITLE
IR remote control - HIRCIR

### ISSUE THREAD

**Issue by rodolfomachado** [make-all/tuya-local#1215]
Hi.

If possible, I'd like to add the IR below. Thanks

"model": "HIRCIR"
"product_name": "HIRCIR - Central de Controle IR TW"

Btw, when I try to add this devide Tuya Local detects as "loratap_curtain_switch"

# Log Message
Could not find any log related to it. How can I do it?

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"000001msiu\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"control\",\"description\":\"send_ir:码库红外码发送\\nstudy:进入学习状态\\nstudy_exit:退出学习状态\\nstudy_key:学习获取到的红外码发送\",\"extensions\":{\"iconName\":\"icon-dp_puzzle\",\"attribute\":\"4\"},\"name\":\"控制命令\",\"typeSpec\":{\"range\":[\"send_ir\",\"study\",\"study_exit\",\"study_key\"],\"type\":\"enum\",\"typeDefaultValue\":\"send_ir\"}},
{\"abilityId\":2,\"accessMode\":\"ro\",\"code\":\"study_code\",\"description\":\"用于学习功能数据上报\",\"name\":\"学习上报参数\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":3,\"accessMode\":\"wr\",\"code\":\"ir_code\",\"description\":\"用于搭配按键参数解码使用\",\"extensions\":{\"iconName\":\"icon-dp_puzzle\"},\"name\":\"遥控器解码参数\",\"typeSpec\":{\"maxlen\":255,\"type\":\"string\",\"typeDefaultValue\":\"\"}},
{\"abilityId\":4,\"accessMode\":\"wr\",\"code\":\"key_code\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_puzzle\"},\"name\":\"码库按键参数\",\"typeSpec\":{\"maxlen\":255,\"type\":\"string\",\"typeDefaultValue\":\"\"}},
{\"abilityId\":5,\"accessMode\":\"wr\",\"code\":\"key_code2\",\"description\":\"仅用于机顶盒多个按键下发\",\"extensions\":{\"iconName\":\"icon-dp_puzzle\"},\"name\":\"码库按键参数2\",\"typeSpec\":{\"maxlen\":255,\"type\":\"string\",\"typeDefaultValue\":\"\"}},
{\"abilityId\":6,\"accessMode\":\"wr\",\"code\":\"key_code3\",\"description\":\"仅用于机顶盒多个按键下发\",\"extensions\":{\"iconName\":\"icon-dp_puzzle\"},\"name\":\"码库按键参数3\",\"typeSpec\":{\"maxlen\":255,\"type\":\"string\",\"typeDefaultValue\":\"\"}},
{\"abilityId\":7,\"accessMode\":\"wr\",\"code\":\"key_study\",\"description\":\"\",\"name\":\"学习参数下发\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":8,\"accessMode\":\"wr\",\"code\":\"key_study2\",\"description\":\"仅用于机顶盒多个按键同时下发\",\"name\":\"学习参数下发2\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":9,\"accessMode\":\"wr\",\"code\":\"key_study3\",\"description\":\"仅用于机顶盒多个按键下发\",\"name\":\"学习参数下发3\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":10,\"accessMode\":\"wr\",\"code\":\"delay_time\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_puzzle\",\"attribute\":\"4\"},\"name\":\"红外码发送延时\",\"typeSpec\":{\"max\":65535,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"ms\"}},
{\"abilityId\":11,\"accessMode\":\"wr\",\"code\":\"key_code4\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_puzzle\"},\"name\":\"码库按键参数4\",\"typeSpec\":{\"maxlen\":255,\"type\":\"string\",\"typeDefaultValue\":\"\"}},
{\"abilityId\":12,\"accessMode\":\"wr\",\"code\":\"key_study4\",\"description\":\"\",\"name\":\"学习参数下发4\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":13,\"accessMode\":\"rw\",\"code\":\"type\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_puzzle\",\"attribute\":\"4\"},\"name\":\"码库标识\",\"typeSpec\":{\"max\":255,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"\"}}]}]}"
  },
  "success": true,
  "t": 1698164978371,
  "tid": "867db902728a11ee8b62ea7d43a7f458"
}
```
# Product ID

DP ID | Description
-- | --
1 | Control commands
2 | Learning code report parameter
3 | Decoding parameter
4 | Code library parameter
5 | Code library parameter2
6 | Code library parameter3
7 | Learning code parameter
8 | Learning code parameter2
9 | Learning code parameter3
10 | Send delay
11 | Code library parameter4

# Information about how the device functions

https://www.geonav.com.br/produtos/central-de-controle-infravermelho-universal-wi-fi/

It's a IR control. So it can copy IR remote control and simulate any remote control. 
In tuya app there are also several model that you can use and there is no need to copy the IR signal.

**Comment by make-all** [comment]
There is currently no support for general remote controls in this integration.

**Comment by make-all** [comment]
remote control support is being added, but there is a limitation in device detection that requires devices to be always sending at least one dps that can be read.  I am not sure whether this device will be detectable, as there is no log provided.

**Comment by rodolfomachado** [comment]
Which log do you need and how can I get it?

Em sáb., 30 de dez. de 2023, 13:10, Jason Rumney ***@***.***>
escreveu:

**Comment by make-all** [comment]
When you try to add the device, and are offered "loratap_curtain_switch" as a possible match, there should be a message in Home Assistant logs listing the dps on which that guess was made.  In earlier versions it may not output the message if the loratap_curtain_switch appears to be a "perfect" match (in 2023.12.3 it will output it, as with over 500 many device configs now supported false matches start to become more likely.

**Comment by rodolfomachado** [comment]
[home-assistant_2024-01-03T13-12-31.255Z.log](https://github.com/make-all/tuya-local/files/13819295/home-assistant_2024-01-03T13-12-31.255Z.log)

Here is the full log. I could not find where is shows the match.

If it is the wrong log or if you need anything else, please ask me

**Comment by make-all** [comment]
Is "Tomada da TV" the correct device?  It looks like a standard smartplug dps layout, so probably not.  But a message like the below is what I am looking for (when trying to add a new device, you should get one with WARNING log level, so you do not need to set the logging to debug level for new devices).

2024-01-03 10:07:14.102 DEBUG (MainThread) [custom_components.tuya_local.device] Tomada da TV received {"1": false, "9": 0, "17": 1, "18": 0, "19": 0, "20": 2215, "21": 1, "22": 582, "23": 13466, "24": 7587, "25": 5490, "26": 0, "full_poll": true}

**Comment by make-all** [comment]
Actually, I think I found it:
2024-01-03 10:07:34.730 DEBUG (SyncWorker_36) [custom_components.tuya_local.device] Test refreshed device state: {"devId": "12126860d8bfc016b8f6", "dps": {"1": "send_ir"}}

The log ends within 3.5 seconds of the above message, so I think the WARNING level message was cropped off, but this message has the same info.
