### ISSUE TITLE
Treatlife DS03 fan with dimmable light - fan automation action not working

### ISSUE THREAD

**Issue by kramttocs** [make-all/tuya-local#1216]
All functions appear to work fine when using the device controls.
When trying to turn on, turn off, or toggle the fan via an automation action with the Device directly it fails with:

Error running action
not a valid value for dictionary value @ data['entity_id']. Got None

I am able to accomplish the same end result with the Fan services from what I am seeing.

**Comment by make-all** [comment]
It seems you have not specified the entity to act on in your automation.
The log message is not coming from this integration but from the general automation framework.

**Comment by kramttocs** [comment]
No, I chose the device (you don't get the actions if you don't). :)

![image](https://github.com/make-all/tuya-local/assets/11565750/8d967f17-5370-4ac1-92e8-d50303e55394)

Here is if I choose the action to turn the light on (which works):

action:
  - type: turn_on
    device_id: 61fc80eff3d42a9220b449d201a39a82
    entity_id: b8a74181a0063455eed8d2a5c571a285
    domain: light
mode: single

Here is to turn the fan on (which doesn't work):

action:
  - type: turn_on
    device_id: 61fc80eff3d42a9220b449d201a39a82
    entity_id: 5ca8f7d976dbffb49a955220ea415ad6
    domain: fan
mode: single


While I am not sure how to really verify the entity_id here, the fact that it's changing based on the domain makes me assume the 5ca8f7... is correct for the fan

**Comment by kramttocs** [comment]
Additionally, it would be nice to have Increase/Decrease for the fan speed as an action (like the light brightness)

**Comment by make-all** [comment]
In that case, please send the complete message from the full logs.  There should be a stack trace there showing where the error is coming from.

**Comment by kramttocs** [comment]
Hmm, doesn't look like I am getting much of a stack.

```
2023-10-24 17:13:10.070 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Invalid data for device at pos 1: not a valid value for dictionary value @ data['entity_id']
2023-10-24 17:13:10.070 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140136270496960] Error handling message: not a valid value for dictionary value @ data['entity_id']. Got None (invalid_format) Scott from 192.168.2.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.61)
```

**Comment by kramttocs** [comment]
```
Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:1783
First occurred: 2:30:57 PM (10 occurrences)
Last logged: 5:17:06 PM

websocket_api script: Error executing script. Invalid data for device at pos 1: not a valid value for dictionary value @ data['entity_id']
websocket_api script: Error executing script. Invalid data for call_service at pos 1: must contain at least one of entity_id, device_id, area_id.
```

**Comment by make-all** [comment]
The error seems to be in the UI frontend. The entity id is used to determine which integration to send the request to, so it has not even reached this integration yet.  I do not think this is a bug with this integration.

**Comment by make-all** [comment]
It seems to be the same issue as https://github.com/home-assistant/core/issues/99728 (also with the fan operations on a combined fan/light device).  The original reporter closed the issue because they found a workaround of using a Call Service action, but I am not sure why the reason for latest "Closed as completed" after someone else reopened it two weeks ago, as there is no linked change or comment from the user that closed it.

**Comment by kramttocs** [comment]
Thank you for looking at this and finding that. I'll pursue it on that ticket.
