### ISSUE TITLE
Sunbeam Bed Warmer

### ISSUE THREAD

**Issue by Jab2870** [make-all/tuya-local#1218]
**Describe the bug**

Sunbeam Bed Warmer not working.

![image](https://github.com/make-all/tuya-local/assets/1909202/efaf7c85-05f2-440b-b8d4-5841a514b9d5)

**To Reproduce**
Steps to reproduce the behavior including the device the issue was observed with:

Connected blanket to local network, set up using Tuya Smart app. ID and key extracted using tuya-cli

![image](https://github.com/make-all/tuya-local/assets/1909202/13cb282f-18f7-4719-b1d3-a9a098a24ae3)

Device added using tuya local extension.

**Expected behavior**

Due to the sunbeam bed warmer being included in devices, I hoped I'd be able to add it

<https://github.com/make-all/tuya-local/blob/main/custom_components/tuya_local/devices/sunbeam_dual_bedwarmer.yaml>

**Additional context**

This is the second tuya device I've attempted to use with tuya local. The first worked flawlessly first time so I believe all my API keys etc are working

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

I am experiencing the bug whilst trying to add the device, so can't provide this

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

```
This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:103
Integration: Tuya Local (documentation, issues)
First occurred: 17:51:40 (3 occurrences)
Last logged: 18:11:28

Report this to https://github.com/make-all/tuya-local/issues/
```

**Comment by make-all** [comment]
The log message is missing.  It is all very well having the "This error originated from..." part,  but the important info is in the message itsef.

**Comment by Jab2870** [comment]
Thanks for your quick reply.

I am not sure what has changed since yesterday, but tuya local now thinks it is a simple switch:

![image](https://github.com/make-all/tuya-local/assets/1909202/f434f49a-e837-442c-bba2-16a53658b7b6)

This is what I get in the logs now:

```
This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:97
Integration: Tuya Local (documentation, issues)
First occurred: 13:11:24 (1 occurrences)
Last logged: 13:11:24

Device matches simple_switch with quality of 14%. DPS: {"updated_at": 1698408682.745719, "1": false, "8": false, "14": false, "15": false, "24": true, "25": false, "105": "ZONE_B"}
```

I'm not sure if it's related, but the device appears to work when set up with local tuya rather than tuya local when following these instructions: https://community.home-assistant.io/t/integration-with-sunbean-wifi-heated-mattress-pad/362588/5
