### ISSUE TITLE
Need help to integration - Awow TH213 thermostat

### ISSUE THREAD

**Issue by dlosito** [make-all/tuya-local#122]
I need help! 
I've been trying for days to integrate an AWOW TH213 thermostat but I'm going crazy! :-)
After entering the intial configuration data, this list of type of device comes out:

![image](https://user-images.githubusercontent.com/97706849/150603509-81fa2a2c-eb56-475f-9fa3-bd6e2407d30f.png)

How can I bind the entity of the thermostat to the right device template?
Maybe the question is a bit "elementary" but I'm new to HA and this device is the basis of the project I have in mind!

Thanks for your help!
Domenico.

**Comment by make-all** [comment]
It's possible that there are different variants of this thermostat, or it returns different data depending on what mode it is in.

If you choose one of those options, then cancel at the next step, there should be some Warning messages in the Home Assistant log that will help diagnose the issue.

After that, maybe you can try changing the mode of the thermostat from the control panel, then try again to see if that works.

**Comment by dlosito** [comment]
Below the logs:

Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:76
Integration: Tuya Local (documentation, issues)
First occurred: 23:22:11 (1 occurrences)
Last logged: 23:22:11

Report this to https://github.com/make-all/tuya-local/issues/

Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:73
Integration: Tuya Local (documentation, issues)
First occurred: 23:22:11 (1 occurrences)
Last logged: 23:22:11

Device matches andersson_gsh_heater with quality of 42%. DPS: {'1': True, '2': 16, '3': 21, '4': '3', '6': False, '12': 0, '101': 23, '102': '2', '103': 1, '104': 1, '105': False, '116': '1', 'updated_at': 1642803719.9702704}

Ask for any other information :-)
Thanks!

**Comment by make-all** [comment]
It seems to be a minor variant. The other one had dps 107, 108, 110 the function of which had not been identified which are missing from this one, and this one has dps 116, which is missing from the other.  So functionally, there is no difference, just a difference in the mysterious other data that is being returned which we don't know the purpose of.

**Comment by dlosito** [comment]
now it's work!!! thanks a lot!
