### ISSUE TITLE
Request support for YRHAND H4

### ISSUE THREAD

**Issue by gabyhaos** [make-all/tuya-local#1223]
# Log Message

```
Please paste logs here
Device matches None with quality of 0%. DPS: {"updated_at": 1698530885.1550186, "3": 910, "11": "medium"}
Report this to https://github.com/make-all/tuya-local/issues/
```

# Information about DPS mappings

```
Please paste the output here.
{
    "result": {
      "model": "{\"modelId\":\"000001mt7t\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"ro\",\"code\":\"unlock_fingerprint\",\"description\":\"【可选】指纹在门锁上录入，录入完成后由硬件分配id，发生指纹解锁后，门锁将上报该dp点。请用记录型上报\",\"extensions\":{\"trigger\":\"direct\"},\"name\":\"指纹解锁\",\"typeSpec\":{\"max\":999,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"\"}},
{\"abilityId\":2,\"accessMode\":\"ro\",\"code\":\"unlock_password\",\"description\":\"【可选】普通密码（非临时密码）在门锁上录入，录入完成后由硬件分配id，发生普通密码解锁后，门锁将上报该dp点。普通密码指在门锁硬件上创建的密码，不包含通过app创建的临时密码。请用记录型上报\",\"extensions\":{\"trigger\":\"direct\"},\"name\":\"普通密码解锁\",\"typeSpec\":{\"max\":999,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},
{\"abilityId\":3,\"accessMode\":\"ro\",\"code\":\"unlock_temporary\",\"description\":\"【可选】临时密码与普通密码进行区分，临时密码指由app创建的密码，临时密码可以具备准确的效期，进行创建时可以同步发短信给接收人。请用记录型上报\",\"extensions\":{\"trigger\":\"direct\"},\"name\":\"临时密码解锁\",\"typeSpec\":{\"max\":999,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},
{\"abilityId\":4,\"accessMode\":\"ro\",\"code\":\"unlock_dynamic\",\"description\":\"【可选】该算法由涂鸦实现。使用动态密码开门成功后，进行上报，只要报指定数字1。app显示的时候，只要有动态密码记录，不显示具体编号只显示类型\",\"extensions\":{\"trigger\":\"direct\"},\"name\":\"动态密码解锁\",\"typeSpec\":{\"max\":999,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},
{\"abilityId\":5,\"accessMode\":\"ro\",\"code\":\"unlock_card\",\"description\":\"【可选】卡片在门锁上录入，录入完成后由硬件分配id，发生卡片解锁后，门锁将上报该dp点。请用记录型上报\",\"extensions\":{\"trigger\":\"direct\"},\"name\":\"卡片解锁\",\"typeSpec\":{\"max\":999,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},
{\"abilityId\":6,\"accessMode\":\"ro\",\"code\":\"unlock_face\",\"description\":\"【可选】人脸在门锁上录入，录入完成后由硬件分配id，发生人脸解锁后，门锁将上报该dp点。请用记录型上报\",\"extensions\":{\"iconName\":\"icon-dp_smile\",\"attribute\":\"1024\"},\"name\":\"人脸识别解锁\",\"typeSpec\":{\"max\":999,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},
{\"abilityId\":8,\"accessMode\":\"ro\",\"code\":\"alarm_lock\",\"description\":\"【必选】0=指纹试错告警、1=密码试错告警、2=卡片试错告警、3=人脸试错告警、4=假锁（锁舌卡住）、5=高温告警、6=超时未关门、7=电子锁舌未弹出、8=防撬告警 、9=钥匙插入、10=低电告警、11=电量耗尽告警、12=震动告警\",\"extensions\":{\"trigger\":\"direct\"},\"name\":\"告警\",\"typeSpec\":{\"range\":[\"wrong_finger\",\"wrong_password\",\"wrong_card\",\"wrong_face\",\"tongue_bad\",\"too_hot\",\"unclosed_time\",\"tongue_not_out\",\"pry\",\"key_in\",\"low_battery\",\"power_off\",\"shock\"],\"type\":\"enum\",\"typeDefaultValue\":\"wrong_finger\"}},
{\"abilityId\":9,\"accessMode\":\"ro\",\"code\":\"unlock_request\",\"description\":\"【可选】如要使用远处开门功能，该dp点必选。门锁上报远程开门请求，需要硬件主动触发。\\n门锁本地上报远程开门请求时，携带x秒倒计时，只有在x秒内才能做出响应，点击允许，门锁将会解锁。可以x小于等于90。；当门锁被远程开门同意，或者拒绝了，将该字段的值改为0，面板将不会闪烁\",\"name\":\"远程开门请求倒计时\",\"typeSpec\":{\"max\":90,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},
{\"abilityId\":10,\"accessMode\":\"wr\",\"code\":\"reply_unlock_request\",\"description\":\"【可选】与远程开门请求配合使用，回复是否同意远程开门，同意/拒绝\",\"name\":\"远程开门请求回复\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":11,\"accessMode\":\"ro\",\"code\":\"battery_state\",\"description\":\"【可选，但必须二选一】电量状态与电量值，二选一。high=高、medium=中、low=低、poweroff=电量即将耗尽\",\"extensions\":{\"iconName\":\"icon-dp_battery\"},\"name\":\"电池电量状态\",\"typeSpec\":{\"range\":[\"high\",\"medium\",\"low\",\"poweroff\"],\"type\":\"enum\",\"typeDefaultValue\":\"high\"}},
{\"abilityId\":15,\"accessMode\":\"ro\",\"code\":\"unlock_app\",\"description\":\"【可选】当发生app远程开门的事件后，门锁上报远程开门的记录。使用记录型数据上报\",\"extensions\":{\"iconName\":\"icon-dp_upload\",\"trigger\":\"direct\"},\"name\":\"App远程解锁wifi门锁 \",\"typeSpec\":{\"max\":999,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},
{\"abilityId\":16,\"accessMode\":\"ro\",\"code\":\"hijack\",\"description\":\"【可选】该功能默认不需要硬件实现，门锁不用做劫持判断，只要在app上标记解锁id即可\",\"extensions\":{\"trigger\":\"direct\"},\"name\":\"劫持告警\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":19,\"accessMode\":\"ro\",\"code\":\"doorbell\",\"description\":\"【可选】门锁硬件上如带有门铃功能，点击后，将会触发一次门铃呼叫通知到云端。建议，连续的门铃呼叫，只触发一次门铃呼叫上报。上报后，将在app保留记录，并可以触发push\",\"extensions\":{\"iconName\":\"icon-a_power\",\"attribute\":\"1024\"},\"name\":\"门铃呼叫\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":23,\"accessMode\":\"ro\",\"code\":\"unlock_hand\",\"description\":\"【可选】掌纹在门锁上录入，录入完成后由硬件分配id，发生掌纹解锁后，门锁将上报该dp点。请用记录型上报\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"attribute\":\"1024\"},\"name\":\"掌纹解锁\",\"typeSpec\":{\"max\":999,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},
{\"abilityId\":24,\"accessMode\":\"ro\",\"code\":\"unlock_finger_vein\",\"description\":\"【可选】指静脉在门锁上录入，录入完成后由硬件分配id，发生指静脉解锁后，门锁将上报该dp点。请用记录型上报\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"attribute\":\"1024\"},\"name\":\"指静脉解锁\",\"typeSpec\":{\"max\":999,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}}]}]}"
    },
    "success": true,
    "t": 1698532605037,
    "tid": "790062a475e211ee95454a52bad04d54"
  }
```

{"1":"Finger Unlock","2":"Password Unlock","3":"Temporary Password Unlock","4":"Dynamic Password Unlock","5":"Card Unlock","6":"Face Recognition Unlock","8":"Lock Alarm","9":"Remote Unlock Request","10":"Remote Unlock Reply","11":"Battery State","15":"Remote Unlock via App","16":"Hijack Alarm","19":"Door Bell","23":"Palm Unlock","24":"Finger Vein Unlock"}

# Product ID
"product_id": "bxq2o60gxhh2ben6"

"mapping": {
            "1": {
                "code": "unlock_fingerprint",
                "type": "Integer",
                "values": {
                    "unit": "",
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "2": {
                "code": "unlock_password",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "3": {
                "code": "unlock_temporary",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "4": {
                "code": "unlock_dynamic",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "5": {
                "code": "unlock_card",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "6": {
                "code": "unlock_face",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "8": {
                "code": "alarm_lock",
                "type": "Enum",
                "values": {
                    "range": [
                        "wrong_finger",
                        "wrong_password",
                        "wrong_card",
                        "wrong_face",
                        "tongue_bad",
                        "too_hot",
                        "unclosed_time",
                        "tongue_not_out",
                        "pry",
                        "key_in",
                        "low_battery",
                        "power_off",
                        "shock"
                    ]
                }
            },
            "9": {
                "code": "unlock_request",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 90,
                    "scale": 0,
                    "step": 1
                }
            },
            "11": {
                "code": "battery_state",
                "type": "Enum",
                "values": {
                    "range": [
                        "high",
                        "medium",
                        "low",
                        "poweroff"
                    ]
                }
            },
            "15": {
                "code": "unlock_app",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "16": {
                "code": "hijack",
                "type": "Boolean",
                "values": {}
            },
            "19": {
                "code": "doorbell",
                "type": "Boolean",
                "values": {}
            },
            "23": {
                "code": "unlock_hand",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "24": {
                "code": "unlock_finger_vein",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "10": {
                "code": "reply_unlock_request",
                "type": "Boolean",
                "values": {}
            }
        },

# Information about how the device functions

https://es.aliexpress.com/item/1005004280612909.html?spm=a2g0o.order_list.order_list_main.5.3129194dHXv5Jm&gatewayAdapt=glo2esp
Manual online pdf:
https://docdro.id/yAKF5Ld
![App screenshots (1)](https://github.com/make-all/tuya-local/assets/122612706/64808b22-7ffc-40ea-950d-13f52e93fec3)
![App screenshots (2)](https://github.com/make-all/tuya-local/assets/122612706/c090bb0a-670f-4be3-852f-0928769ef1c4)
![App screenshots (3)](https://github.com/make-all/tuya-local/assets/122612706/4a838339-363c-43e2-856b-28d24ebcf857)
![App screenshots (4)](https://github.com/make-all/tuya-local/assets/122612706/a0ff4d62-cf54-44e4-bc1e-cb146ac9ea39)
![App screenshots (5)](https://github.com/make-all/tuya-local/assets/122612706/0dc6479f-e9c7-4fb9-becd-03215d09d161)

**Comment by gabyhaos** [comment]
I've been researching how it works. To save battery, it only connects to Wi-Fi when you enter a code. At that moment the lock must verify if it is registered in the app and allows it to open. Two seconds after opening or denying access it disconnects from Wi-Fi.

**Comment by make-all** [comment]
Based on your research, this is unlikely to work reliably using the local protocol, as a connection cannot be maintained while it is sleeping, and there is no way of knowing locally when it has woken, as it is only waking to connect to the cloud.
