### ISSUE TITLE
Help i cant add my licht bulb

### ISSUE THREAD

**Issue by pascal2313** [make-all/tuya-local#1228]
### Discussed in https://github.com/make-all/tuya-local/discussions/1225

<div type='discussions-op-text'>

<sup>Originally posted by **pascal2313** October 29, 2023</sup>
hi i Resendly bouth some new light bulbs and i cant add them i know for sure that i am putting the correct information in becouse i have done it a few times but recently there where special characters in my local key and then it wont work. 

i get this error 
Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect.

the log
![image](https://github.com/make-all/tuya-local/assets/69986711/4f82441d-a8b9-4e3d-be8d-f9ff3e6b31c5)

can anybody help me with this issue?</div>

**Comment by make-all** [comment]
Because this is not a bug report, it is a request for assistance which is a duplicate of an already ongoing discussion.
