### ISSUE TITLE
New Device: Lefant M213 Robot Vacuum Cleaner 

### ISSUE THREAD

**Issue by dlosito** [make-all/tuya-local#123]
Hi @make-all 
Can you help me to integrate this device?

**Logs:**

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:73
Integration: Tuya Local (documentation, issues)
First occurred: 23:55:50 (1 occurrences)
Last logged: 23:55:50

Device matches simple_switch with quality of 6%. DPS: {'1': True, '2': False, '3': 'standby', '4': 'foward', '5': '0', '6': 91, '13': False, '16': 0, '17': 0, '18': 0, '101': 'nar', '102': -23, '103': 27, '104': 0, '106': 'ChargeStage:DETSWITCH ', '108': 'BatVol:13159', 'updated_at': 1642892130.3030555}

**Get Device Specification**
{
  "result": {
    "category": "sd",
    "functions": [
      {
        "code": "power",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "power_go",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Cleaning switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "lang_config": {
          "chargego": "Charging Base",
          "random": "Random",
          "smart": "Smart",
          "spiral": "Spiral",
          "standby": "Standby",
          "wall_follow": "Wall Follow"
        },
        "name": "Mode",
        "type": "Enum",
        "values": "{\"range\":[\"standby\",\"smart\",\"chargego\",\"random\",\"wall_follow\",\"spiral\"]}"
      },
      {
        "code": "direction_control",
        "lang_config": {
          "backward": "Backward",
          "stop": "Stop",
          "turn_left": "Left",
          "turn_right": "Right"
        },
        "name": "Direction",
        "type": "Enum",
        "values": "{\"range\":[\"backward\",\"turn_left\",\"turn_right\",\"stop\"]}"
      },
      {
        "code": "seek",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Seek Robot",
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "power",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "power_go",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Cleaning switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "lang_config": {
          "chargego": "Charging Base",
          "random": "Random",
          "smart": "Smart",
          "spiral": "Spiral",
          "standby": "Standby",
          "wall_follow": "Wall Follow"
        },
        "name": "Mode",
        "type": "Enum",
        "values": "{\"range\":[\"standby\",\"smart\",\"chargego\",\"random\",\"wall_follow\",\"spiral\"]}"
      },
      {
        "code": "direction_control",
        "lang_config": {
          "backward": "Backward",
          "stop": "Stop",
          "turn_left": "Left",
          "turn_right": "Right"
        },
        "name": "Direction",
        "type": "Enum",
        "values": "{\"range\":[\"backward\",\"turn_left\",\"turn_right\",\"stop\"]}"
      },
      {
        "code": "electricity_left",
        "lang_config": {
          "unit": "%"
        },
        "name": "Battery",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "seek",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Seek Robot",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "clean_record",
        "lang_config": {
          "unit": "Cleaning Record"
        },
        "name": "Cleaning Record",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "clean_area",
        "lang_config": {
          "unit": "㎡"
        },
        "name": "Cleaning Area",
        "type": "Integer",
        "values": "{\"unit\":\"㎡\",\"min\":0,\"max\":9999,\"scale\":0,\"step\":1}"
      },
      {
        "code": "clean_time",
        "lang_config": {
          "unit": "min"
        },
        "name": "Cleaning Time",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":9999,\"scale\":0,\"step\":1}"
      },
      {
        "code": "fault",
        "lang_config": {
          "collision": "Collision",
          "edge_sweep": "Side Cleaning Fault",
          "garbage_box": "Dust box failure",
          "land_check": "Ground Check Fault",
          "left_wheel": "Left Wheel Fault",
          "middle_sweep": "Middle Cleaning Fault",
          "right_wheel": "Right Wheel Fault"
        },
        "name": "Fault Alarm",
        "type": "Bitmap",
        "values": "{\"label\":[\"edge_sweep\",\"middle_sweep\",\"left_wheel\",\"right_wheel\",\"garbage_box\",\"land_check\",\"collision\"]}"
      }
    ]
  },
  "success": true,
  "t": 1642894674898
}

**Comment by make-all** [comment]
This will require additional support for the vacuum platform. In the meantime, if you can check back in the Tuya API Explorer, right near the bottom there is another method to get a list the Device Attributes which also returns dps ids, so they can be linked without guessing (I think it's under Smart Home Management, last option under second to last subcategory, I have no idea why they need so many methods to get almost the same information but all subtly different)

**Comment by dlosito** [comment]
this one?

{
  "result": {
    "category": "sd",
    "functions": [
      {
        "code": "power",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "power_go",
        "dp_id": 2,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "dp_id": 3,
        "type": "Enum",
        "values": "{\"range\":[\"standby\",\"smart\",\"chargego\",\"random\",\"wall_follow\",\"spiral\"]}"
      },
      {
        "code": "direction_control",
        "dp_id": 4,
        "type": "Enum",
        "values": "{\"range\":[\"backward\",\"turn_left\",\"turn_right\",\"stop\"]}"
      },
      {
        "code": "seek",
        "dp_id": 13,
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "power",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "power_go",
        "dp_id": 2,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "dp_id": 3,
        "type": "Enum",
        "values": "{\"range\":[\"standby\",\"smart\",\"chargego\",\"random\",\"wall_follow\",\"spiral\"]}"
      },
      {
        "code": "direction_control",
        "dp_id": 4,
        "type": "Enum",
        "values": "{\"range\":[\"backward\",\"turn_left\",\"turn_right\",\"stop\"]}"
      },
      {
        "code": "electricity_left",
        "dp_id": 6,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "seek",
        "dp_id": 13,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "clean_record",
        "dp_id": 15,
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "clean_area",
        "dp_id": 16,
        "type": "Integer",
        "values": "{\"unit\":\"㎡\",\"min\":0,\"max\":9999,\"scale\":0,\"step\":1}"
      },
      {
        "code": "clean_time",
        "dp_id": 17,
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":9999,\"scale\":0,\"step\":1}"
      },
      {
        "code": "fault",
        "dp_id": 18,
        "type": "Bitmap",
        "values": "{\"label\":[\"edge_sweep\",\"middle_sweep\",\"left_wheel\",\"right_wheel\",\"garbage_box\",\"land_check\",\"collision\"]}"
      }
    ]
  },
  "success": true,
  "t": 1642897780958
}

**Comment by make-all** [comment]
Thanks, that's the one, with the dp_id listed.

**Comment by make-all** [comment]
One question - the "Seek Robot" feature, what does it do?  My best guess would be turning on a beep so you can find the robot?

**Comment by dlosito** [comment]
yes it's correct!

**Comment by philou669** [comment]
> This will require additional support for the vacuum platform. In the meantime, if you can check back in the Tuya API Explorer, right near the bottom there is another method to get a list the Device Attributes which also returns dps ids, so they can be linked without guessing (I think it's under Smart Home Management, last option under second to last subcategory, I have no idea why they need so many methods to get almost the same information but all subtly different)

when I try to get device attrbutes I have this message.

{
  "code": 1106,
  "msg": "permission deny",
  "success": false,
  "t": 1644152607666
}

I have Lefant M210 Robot Vacuum Cleaner it's probably similar to the m213

**Comment by make-all** [comment]
Is your device paired to the same account, and did you select the closest server (the default of China is only for customers in China, most others are on Western America or Western Europe server I think.

**Comment by make-all** [comment]
It seems the M210 is not compatible with the M213, in order to add support for that, I will need a new issue to be filed with all the relevant information (DPS logs, information from iot.tuya.com developer portal).  Closing this, as M213 support was provided, and no further issue has been raised for that model.
