### ISSUE TITLE
New Device: Kyvol E30 Vacuum

### ISSUE THREAD

**Issue by kramttocs** [make-all/tuya-local#124]
Currently showing as a simple_switch.

    "functions": [
      {
        "code": "power",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "power_go",
        "dp_id": 2,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "direction_control",
        "dp_id": 4,
        "type": "Enum",
        "values": "{\"range\":[\"forward\",\"backward\",\"turn_left\",\"turn_right\",\"stop\"]}"
      },
      {
        "code": "suction",
        "dp_id": 14,
        "type": "Enum",
        "values": "{\"range\":[\"strong\",\"normal\",\"quiet\",\"gentle\",\"closed\"]}"
      },
      {
        "code": "seek",
        "dp_id": 13,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "reset_roll_brush",
        "dp_id": 11,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "reset_edge_brush",
        "dp_id": 10,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "reset_filter",
        "dp_id": 12,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "dp_id": 3,
        "type": "Enum",
        "values": "{\"range\":[\"standby\",\"random\",\"smart\",\"wall_follow\",\"mop\",\"spiral\",\"left_spiral\",\"right_spiral\",\"bow\",\"left_bow\",\"right_bow\",\"partial_bow\",\"chargego\",\"single\",\"zone\",\"pose\",\"point\",\"part\",\"pick_zone\"]}"
      }
    ],
    "status": [
      {
        "code": "power",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "power_go",
        "dp_id": 2,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "direction_control",
        "dp_id": 4,
        "type": "Enum",
        "values": "{\"range\":[\"forward\",\"backward\",\"turn_left\",\"turn_right\",\"stop\"]}"
      },
      {
        "code": "suction",
        "dp_id": 14,
        "type": "Enum",
        "values": "{\"range\":[\"strong\",\"normal\",\"quiet\",\"gentle\",\"closed\"]}"
      },
      {
        "code": "seek",
        "dp_id": 13,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "status",
        "dp_id": 5,
        "type": "Enum",
        "values": "{\"range\":[\"standby\",\"smart_clean\",\"wall_clean\",\"spot_clean\",\"mop_clean\",\"goto_charge\",\"charging\",\"charge_done\",\"paused\",\"cleaning\",\"zone_clean\",\"part_clean\",\"pick_zone_clean\",\"goto_pos\",\"pos_arrived\",\"pos_unarrive\",\"sleep\"]}"
      },
      {
        "code": "electricity_left",
        "dp_id": 6,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "clean_record",
        "dp_id": 15,
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "clean_time",
        "dp_id": 17,
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":9999,\"scale\":0,\"step\":1}"
      },
      {
        "code": "edge_brush",
        "dp_id": 7,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "roll_brush",
        "dp_id": 8,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "filter",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "reset_roll_brush",
        "dp_id": 11,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "reset_edge_brush",
        "dp_id": 10,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "reset_filter",
        "dp_id": 12,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "clean_area",
        "dp_id": 16,
        "type": "Integer",
        "values": "{\"unit\":\"㎡\",\"min\":0,\"max\":9999,\"scale\":0,\"step\":1}"
      },
      {
        "code": "mode",
        "dp_id": 3,
        "type": "Enum",
        "values": "{\"range\":[\"standby\",\"random\",\"smart\",\"wall_follow\",\"mop\",\"spiral\",\"left_spiral\",\"right_spiral\",\"bow\",\"left_bow\",\"right_bow\",\"partial_bow\",\"chargego\",\"single\",\"zone\",\"pose\",\"point\",\"part\",\"pick_zone\"]}"
      }
    ]
  },

**Comment by make-all** [comment]
As with #123, this requires implementation of the vacuum platform to proceed, so is not as simple as some other requests for new devices.  However, I have already started that, so it should not be too far in the future.

**Comment by kramttocs** [comment]
Much appreciated. I am downright impressed with the Inkbird support.

**Comment by make-all** [comment]
Can you please capture the local dps from the device.  Sometimes there are some differences between the local and cloud API or errors/omissions in the documentation on the portal.

**Comment by kramttocs** [comment]
And that would be using the command line option? 

Can you elaborate on your last sentence? I guess I don't know the difference in how what you are doing is validating the features vs what shows in the cloud api.

**Comment by kramttocs** [comment]
And that command line option is only available on a linux environment, right? If so, afraid that's out of reach at this time. I wonder if the submitter of #123 can provide that?

**Comment by make-all** [comment]
Local dps can be captured by starting to add the device into tuya-local, you can abort after selecting the device type.  Then check in the Home Assistant log. There should be some WARNING level messages from tuya-local, about the imperfect match of the device to any configuration.

The submitter of #123 has a different brand and model of vacuum, so it will not be the same.

**Comment by kramttocs** [comment]
Can definitely get that!

Device matches simple_switch with quality of 5%. DPS: {'1': True, '2': False, '3': 'standby', '4': 'stop', '5': 'Charging_Base', '6': 2, '7': 20, '8': 60, '9': 20, '10': False, '11': False, '12': False, '13': False, '14': '3', '17': 0, '18': 0, '101': '2', '102': '900234', '104': 'standby', '107': 1, 'updated_at': 1643837343.0291703}

Happy to provide anything else.

**Comment by make-all** [comment]
Thanks.  This confirms that a number of the Enum types are replaced by numeric values in the local protocol, which is one of the things that quite commonly happens.

I'll make the config assuming that the order listed in the docs is the order of the numeric properties, once the config is made, you'll have to go through and check they all match.

**Comment by kramttocs** [comment]
I can see that 5 doesn't match the values they provided in the cloud api

**Comment by make-all** [comment]
That too. I'd only noticed 14, which is numeric

**Comment by kramttocs** [comment]
Oh you are right. And it's a string as well?

**Comment by kramttocs** [comment]
Excellent work. Just pulled down main and tried it.
Only issue I have found is changing the fan setting. 
The only time it doesn't throw and error is setting it to 'gentle'.
Let me know what I can do to help.

![image](https://user-images.githubusercontent.com/11565750/152913622-9e3cd5d6-7f38-4f4e-8c99-534eb730cdf7.png)

**Comment by kramttocs** [comment]
Also, not sure if these mean anything worthwhile:
![image](https://user-images.githubusercontent.com/11565750/152914898-5275f955-cb54-45fa-9cdf-5a814de491cb.png)

**Comment by make-all** [comment]
The attributes with actual names are mostly set-only in the vacuum API, so they are added as attributes for convenience so the current value can be read as well or in the case of Error, is returned as "fault" in state for any non-zero value, but you may be able to tell more information about the error from the actual value.

The "unknown" ones, probably have a meaning which if you can figure it out can be added into the config, but these weren't listed in the API explorer documentation above.  In particular, unknown 104 looks like it might be something usable (it may be a reflection of the mode, but maybe reporting whether it is really in that mode, even though you set it, so could be useful for separating commands from status.

**Comment by make-all** [comment]
Released in 0.15.0
