### ISSUE TITLE
Heatstorm wall heating Fahrenheit Celsius not correct

### ISSUE THREAD

**Issue by kramttocs** [make-all/tuya-local#1241]
It's treating the Fahrenheit value from the device as the Celsius value so the F value.

For example, The device is in F now and the Tuya app shows 66 set point. The device in HA has Fahrenheit selected but shows 151 degress. If I change HA to Celsius then it shows 66.
Changing the app to Celsius makes HA change to 66 C when it should be 66 F

[tuya_local-3a21de9eeaa62c77f9cd226dcd4be410-RecRoom Heater-a2932c897cb38b63e4752600e59b2f75.json.txt](https://github.com/make-all/tuya-local/files/13231375/tuya_local-3a21de9eeaa62c77f9cd226dcd4be410-RecRoom.Heater-a2932c897cb38b63e4752600e59b2f75.json.txt)

**Comment by fireheadman** [comment]
+1 on this issue 
![image](https://github.com/make-all/tuya-local/assets/19847195/8a18e37d-252a-4ed7-a6b1-5ae946f4afb0)

no way my heater is doing 162 degrees F!  If you select Celsius, it will reflect the F temp, but then the heater is now showing C degrees.

![image](https://github.com/make-all/tuya-local/assets/19847195/732fcac1-840c-44d5-888e-e90b0fd374f1)

**Comment by kramttocs** [comment]
Hey @make-all .
Is awaiting confirmation mean somehow needed from me?

**Comment by make-all** [comment]
Awaiting confirmation means the work is done, but since i don't have the device, it is untested.  It doesn't really affect anything, but quite a few issues that get released in that state end up being reopened for minor corrections later.

**Comment by kramttocs** [comment]
Thanks and happy to. I just copied the files over (replaced everything). The Values look good now.
If I toggle the Temp Unit to C though, it changes in the Tuya app but the Thermostat control doesn't change the values. Seems like it is locked into F now. 
[tuya_local-3a21de9eeaa62c77f9cd226dcd4be410-RecRoom Heater-a2932c897cb38b63e4752600e59b2f75.json (1).txt](https://github.com/make-all/tuya-local/files/13328997/tuya_local-3a21de9eeaa62c77f9cd226dcd4be410-RecRoom.Heater-a2932c897cb38b63e4752600e59b2f75.json.1.txt)

Side question: since I replaced everything, will HACS recognize and official release or should I redownload the latest?

**Comment by make-all** [comment]
The display in Home Assistant is converted to the user display values.  If you look in Developer / States, it should show the raw values I think, or definitely if you download the diagnostics from Settings / Devices & Settings / Devices / <heatstorm device>

**Comment by kramttocs** [comment]
That makes sense. Thanks
