### ISSUE TITLE
Heatstorm Presets Not Working

### ISSUE THREAD

**Issue by kramttocs** [make-all/tuya-local#1242]
The options in the App are Low/Auto/High
In HA they are Eco/Comfort/Boost

Changing via HA sets the device to Low no matter what option is chosen in HA.

Right after changing the Control display in HA shows the Preset chosen in HA but eventually it will refresh and changes to Low
Eco/Comfort/Boost labels are great. Just need them to make the appropriate change and the display to map the Tuya value to them.

![image](https://github.com/make-all/tuya-local/assets/11565750/be689ced-9be5-496e-82f5-aebe5a41c47a)

[tuya_local-3a21de9eeaa62c77f9cd226dcd4be410-RecRoom Heater-a2932c897cb38b63e4752600e59b2f75.json.txt](https://github.com/make-all/tuya-local/files/13231410/tuya_local-3a21de9eeaa62c77f9cd226dcd4be410-RecRoom.Heater-a2932c897cb38b63e4752600e59b2f75.json.txt)

**Comment by fireheadman** [comment]
+1 on this issue and I see in the OP screenshot he has the same issue with temp.
no way his heater is  doing 151 degrees F!   Mine is doing that too.   If you select Celsius, it will reflect the F temp, but then the heater is now showing C degrees.

**Comment by kramttocs** [comment]
This looks good! Tested it (for all of 5 minutes) but values are changing, reflecting in the Tuya app, and persisting.
