### ISSUE TITLE
Migration error - HCT-611 Water timer

### ISSUE THREAD

**Issue by spanzetta** [make-all/tuya-local#1244]
After the latest update I see the following error
Pls note that it was working perfectly until this latest update
Can you pls help me to understand how to fix?
Thanks

![image](https://github.com/make-all/tuya-local/assets/49818743/6c45965a-a826-46e2-b67c-2e857a9d438e)

**Comment by make-all** [comment]
Can you check the Home Assistant log for log messages?  I can't tell much from a screenshot.

**Comment by spanzetta** [comment]
I did update few days ago...  and until then it was always working.

I will provide any you log you want.. just tell me which one..

![image](https://github.com/make-all/tuya-local/assets/49818743/0f5def8b-40b9-4679-9f85-9c4ebc03d20a)

**Comment by make-all** [comment]
The log messages will be in the Home Assistant Core log, at the time you did the update or last restarted HA

**Comment by spanzetta** [comment]
hmm... so I lost those logs (restarted many times already - last was this morning after update to 2023.11) .. or is there a way to recover them?

**Comment by spanzetta** [comment]
I verified that the update was installed yesterday.. it was from 2023.9.1 to 2023.10.0 (even if you release it 2 weeks ago - it was prompted to update to it only yesterday.. don't ask me why)
I redownloaded 2023.9.1 and I still have this migration error.. (%£$%"!).. but until yesterday it was working...
If I reconfigure my device (config button) by confirming all the parameters... when I click "submit" it says "Success!" but the device still doesn't work!
In the Assistant Core logs I see nothing relevant.. and also in the device Logbook
Any idea about the possible cause of the problem?
How can I provide you some usefull logs for you to identify the problem?
Thanks in advance

**Comment by spanzetta** [comment]
Is it possible that it's the same problem of https://github.com/make-all/tuya-local/issues/984?

Maybe the update the caused the problem in my case was the HA 2023.11 of today?

**Comment by spanzetta** [comment]
dear @make-all 
can you pls help me to solve the issue?
Thanks

**Comment by spanzetta** [comment]
Solved myself by removing all device and configuring them again ...
It remains strange why did this problem happen

**Comment by make-all** [comment]
It is certainly not the same issue as #984, as that issue was fixed and an immediate update issued one day after the release that caused it. But there have been no migrations added since then, so it is indeed a mystery why you would get these errors updating from 2023.9.1 to 2023.11.0.  Without logs it is impossible to debug, so while it seems to be a workaround to remove and re-add the devices, the bug will remain for other users to find.
