### ISSUE TITLE
Request support for Tuya Human Presence Sensor (Wifi Version)

### ISSUE THREAD

**Issue by r17019** [make-all/tuya-local#1248]
# Log Message

```
2023-11-04 12:21:13.598 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches ir_remote_sensors with quality of 50%. DPS: {"updated_at": 1699062672.755938, "1": "none", "101": 0, "102": 14, "103": false}
2023-11-04 12:21:13.598 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/
```

# Information about DPS mappings

```
{
  "result": {
    "properties": [
      {
        "code": "presence_state",
        "custom_name": "",
        "dp_id": 1,
        "time": 1699061803844,
        "value": "none"
      },
      {
        "code": "have",
        "custom_name": "",
        "dp_id": 101,
        "time": 1699061807363,
        "value": 0
      },
      {
        "code": "none",
        "custom_name": "",
        "dp_id": 102,
        "time": 1699062345443,
        "value": 9
      },
      {
        "code": "led",
        "custom_name": "",
        "dp_id": 103,
        "time": 1699062384135,
        "value": false
      },
      {
        "code": "th1",
        "custom_name": "",
        "dp_id": 104,
        "time": 1663659433226,
        "value": 120
      },
      {
        "code": "th2",
        "custom_name": "",
        "dp_id": 105,
        "time": 1663659433226,
        "value": 250
      }
    ]
  },
  "success": true,
  "t": 1699062384531,
  "tid": "f648f9287ab311ee837e2261b7a5ced3"
}

```

# Product ID

"name": "Human Presence Sensor WiFi Version",
"product_id": "jfmnvyhd63yuuchn",
"product_name": "人体存在WIFI版",

# Information about how the device functions
Using Localtuya, I have control of the microwave binary sensor, and the LED (only as a switch on/off, not color). 
 - DPI 1: Microwave binary sensor
 - DPI 103: LED on/off
Using the Tuya integration it only exposes the microwave binary sensor.

24g mm wave sensor
LED changes color depending on state - Red detected, Green clear, Blue no wifi connection.

https://www.aliexpress.com/item/1005004552185948.html

**Comment by r17019** [comment]
This is what shows currently when trying to add
![image](https://github.com/make-all/tuya-local/assets/110243292/3235ab7a-f9bf-43c5-9a00-349f3c65c9ee)

**Comment by make-all** [comment]
This requires more info on the dps: possible values that dp 1 can take, range and meaning of dps 101, 102, 104, 105, and whether dp 103 is a switch for controlling whether the LED is on, or a binary_sensor indicating the LED state.
