### ISSUE TITLE
Request support for Litroux_M7S_pro_vacuum

### ISSUE THREAD

**Issue by jrhessels** [make-all/tuya-local#1249]
could you add the Litroux_M7S_pro_vacuum. i att. the code

[Litroux_M7S_pro_vacuum.txt](https://github.com/make-all/tuya-local/files/13256313/Litroux_M7S_pro_vacuum.txt)

**Comment by jrhessels** [comment]
what is the new name of the config i cannot find te file ? in de custom devices

**Comment by make-all** [comment]
This has not been added, and will likely never be added, since it is difficult to review with no information about the device and the config as an attachment where it needs to be downloaded and separately viewed offline.
