### ISSUE TITLE
Arlec Fan Ceiling Fan DCF4002WHA does not create entity for light.

### ISSUE THREAD

**Issue by UrZdcw9** [make-all/tuya-local#127]
Hi there,

First of all, thanks for all your work on this integration.

I have installed a ceiling fan with a light DCF4002WHA .  The integration loads the fan controls but does not create an entity for the light.

Is it possible for this to be add?

**Comment by make-all** [comment]
I'm confused by this report.  The title says DCF5241HA, but the body says DCF4002WHA.  Also, on one of your edits, you included the log output which showed that the fan was an exact match for the existing Arlec fan configuration, but for some reason was selected as switch.

Are there two fans that you have here?  Was the original report resolved and you are now trying to get a different fan working?

To add light control, I'd need the log messages that appear when you first add the device.  These will show what data the device is exposing (apparently it is at least compatible with the fan-only model, which is what DCF5241HA seems to be).

**Comment by make-all** [comment]
If the option for Deta fan comes up, it may be usable with that (the Deta fan does not have direction control that the standalone Arlec fan has, but it does have a light).

**Comment by UrZdcw9** [comment]
Hey make-all,

Apologies, i had two issues; but resolved one and was reusing original posting.  title updated to reflect issue. 

 i now have DCF5241HA working without problems.

The issue that persists is with DCF4002WHA - upon integration no light entity is created.  I don't think i was able to select the Deta fan (from memory).

I had a workaround - adding a secondary entity to arlec_fan.yaml -->

  - entity: light
    dps:
      - id: 9
        type: boolean
        name: switch
        
      Which kind of worked; however rendered the integration faulty for the DCF5241HA (again now resolved).
      
   Would it be possible to add a yaml file for arlec_fan_with_light or similar?

**Comment by make-all** [comment]
Can you please send the log messages, with full dps set in.  As far as I can tell from the Bunnings site, this fan should have a dimmable light, so more than just the switch that the Deta fan has (and if the deta fan is not appearing as an option, I guess it doesn't have separate timers for fan and light).

**Comment by UrZdcw9** [comment]
@make-all;

i have just re-run integration on DCF4002WHA .  Attached are screen shots + below are logs.
![image](https://user-images.githubusercontent.com/92231563/151769288-8810f42a-4257-479a-ba27-b3fcd36e39ad.png)

------------------
![image](https://user-images.githubusercontent.com/92231563/151769317-35aacd0f-b224-431e-9d92-95b74d16a45d.png)



Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:73
Integration: Tuya Local (documentation, issues)
First occurred: 8:27:44 PM (1 occurrences)
Last logged: 8:27:44 PM

Device matches arlec_fan with quality of 62%. DPS: {'1': True, '3': '6', '4': 'forward', '9': False, '10': 100, '11': 100, '102': 'normal', '103': 'off', 'updated_at': 1643621262.32304}

**Comment by make-all** [comment]
Do you have access to iot.tuya.com?
If you go to Cloud / API Explorer, then Smart Home Management System / Device Control / Get Device Specification Attribute, and enter your Device ID, what does it report?  This info should contain the range for the brightness ('10'?) and whatever value '11' is.

**Comment by UrZdcw9** [comment]
thanks for looking into this @make-all ,

i think this is what you are after.

{
  "result": {
    "category": "fsd",
    "functions": [
      {
        "code": "fan_countdown_set",
        "type": "Enum",
        "values": "{\"range\":[\"cancel\",\"1h\",\"2h\"\"4h\",\"8h\"]}"
      },
      {
        "code": "fan_mode",
        "type": "Enum",
        "values": "{\"range\":[\"nature\",\"sleep\"]}"
      },
      {
        "code": "temp_value",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":100,\"scale\":0,\"step\":2}"
      },
      {
        "code": "bright_value",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":100,\"scale\":0,\"step\":2}"
      },
      {
        "code": "switch_led",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_direction",
        "type": "Enum",
        "values": "{\"range\":[\"forward\",\"reverse\"]}"
      },
      {
        "code": "fan_switch",
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "fan_switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_direction",
        "type": "Enum",
        "values": "{\"range\":[\"forward\",\"reverse\"]}"
      },
      {
        "code": "switch_led",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "bright_value",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":100,\"scale\":0,\"step\":2}"
      },
      {
        "code": "temp_value",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":100,\"scale\":0,\"step\":2}"
      },
      {
        "code": "fan_mode",
        "type": "Enum",
        "values": "{\"range\":[\"sleep\",\"nature\"]}"
      },
      {
        "code": "fan_countdown_set",
        "type": "Enum",
        "values": "{\"range\":[\"cancel\",\"1h\",\"2h\",\"4h\",\"8h\"]}"
      }
    ]
  },
  "success": true,
  "t": 1643627471642
}

**Comment by make-all** [comment]
That is almost the info I'm after. There are many places in the API explorer that return a similar description of the data returned by the cloud API, but only the specific one I mentioned above ties that back to the dp ids used by the local API.

**Comment by UrZdcw9** [comment]
Sorry @make-all; i see that now.  the options in tuya cloud have very similar labels.

---------------

{
  "result": {
    "category": "fsd",
    "functions": [
      {
        "code": "fan_countdown_set",
        "dp_id": 103,
        "type": "Enum",
        "values": "{\"range\":[\"cancel\",\"1h\",\"2h\"\"4h\",\"8h\"]}"
      },
      {
        "code": "fan_mode",
        "dp_id": 102,
        "type": "Enum",
        "values": "{\"range\":[\"nature\",\"sleep\"]}"
      },
      {
        "code": "temp_value",
        "dp_id": 11,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":100,\"scale\":0,\"step\":2}"
      },
      {
        "code": "bright_value",
        "dp_id": 10,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":100,\"scale\":0,\"step\":2}"
      },
      {
        "code": "switch_led",
        "dp_id": 9,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_direction",
        "dp_id": 4,
        "type": "Enum",
        "values": "{\"range\":[\"forward\",\"reverse\"]}"
      },
      {
        "code": "fan_switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "fan_switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_direction",
        "dp_id": 4,
        "type": "Enum",
        "values": "{\"range\":[\"forward\",\"reverse\"]}"
      },
      {
        "code": "switch_led",
        "dp_id": 9,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "bright_value",
        "dp_id": 10,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":100,\"scale\":0,\"step\":2}"
      },
      {
        "code": "temp_value",
        "dp_id": 11,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":100,\"scale\":0,\"step\":2}"
      },
      {
        "code": "fan_mode",
        "dp_id": 102,
        "type": "Enum",
        "values": "{\"range\":[\"sleep\",\"nature\"]}"
      },
      {
        "code": "fan_countdown_set",
        "dp_id": 103,
        "type": "Enum",
        "values": "{\"range\":[\"cancel\",\"1h\",\"2h\",\"4h\",\"8h\"]}"
      }
    ]
  },
  "success": true,
  "t": 1643675339142
}

**Comment by make-all** [comment]
I have added a new config, and support for the color temperature of the light.

To test it out before release, if you used HACS to install, you can select Redownload on the menu for tuya-local, then select "main" as the version to install.  If you manually installed, just copy over the head of the main branch.

**Comment by make-all** [comment]
Things to check, which I am not able to without access to the device:

- that the brightness works as expected across the full range.
- that the color temperature works as expected across the full range.
- that the warm and cold ends of color temperature is at the expected end of the scale.

**Comment by UrZdcw9** [comment]
Testing....

![image](https://user-images.githubusercontent.com/92231563/152126004-b40cd82a-c6cd-4efa-be5f-485f0db4eacd.png)

![image](https://user-images.githubusercontent.com/92231563/152126060-86660c07-cc95-475d-898f-f674c83f64e2.png)
![image](https://user-images.githubusercontent.com/92231563/152127855-4dc713c7-d471-4c0f-ae54-e30a17d87759.png)
---
that the brightness works as expected across the full range. PASS
that the color temperature works as expected across the full range. PASS
that the warm and cold ends of color temperature is at the expected end of the scale. PASS
------
the only niggle that i noticed was there was a lag/no update to Home Assistant when i adjusted the device via the manufacturer supplied remote.

Can do further testing on the niggle if need be.  

Otherwise amazing for this to be turned around in a day or two.

**Comment by make-all** [comment]
The delay getting feedback from the device is a known issue, since some devices become unstable if we poll too frequently.  Polling rather than keeping a permanent connection was a design decision made by the upstream developer of the Goldair Climate integration on which this was originally based, in order to play nicer with the official Tuya apps, but the apps don't really play nicely back, so it may not have been the best choice.

**Comment by UrZdcw9** [comment]
understood, thanks for the prompt action to enable the light entity.

**Comment by make-all** [comment]
Released in 0.15.0
