### ISSUE TITLE
Request support for [SX1 Socket in-line switch with relay & countdown]

### ISSUE THREAD

**Issue by MJW911** [make-all/tuya-local#1277]
# Log Message

```
Please paste logs here
No logs created. error: "unable to connect to your device with those details..." message

(Later got proper logs...)

Device matches SX1_Relay_Simple_Switch with quality of 50%. DPS: {"updated_at": 1700306632.7101316, "1": true, "9": 0, "38": "memory", "40": "relay", "41": false, "42": "", "43": "", "44": ""}
```

# Information about DPS mappings

```
Please paste the output here.
```{
  "result": {
    "model": "{\"modelId\":\"0000039ftm\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"133\"},\"name\":\"开关1\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":9,\"accessMode\":\"rw\",\"code\":\"countdown_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"attribute\":\"128\"},\"name\":\"开关1倒计时\",\"typeSpec\":{\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"s\"}},
{\"abilityId\":38,\"accessMode\":\"rw\",\"code\":\"relay_status\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_battery\",\"attribute\":\"640\"},\"name\":\"上电状态设置\",\"typeSpec\":{\"range\":[\"off\",\"on\",\"memory\"],\"type\":\"enum\",\"typeDefaultValue\":\"off\"}},
{\"abilityId\":40,\"accessMode\":\"rw\",\"code\":\"light_mode\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-deng\",\"attribute\":\"128\"},\"name\":\"指示灯状态设置\",\"typeSpec\":{\"range\":[\"relay\",\"pos\",\"none\"],\"type\":\"enum\",\"typeDefaultValue\":\"relay\"}},
{\"abilityId\":41,\"accessMode\":\"rw\",\"code\":\"child_lock\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power\",\"attribute\":\"128\"},\"name\":\"童锁开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":42,\"accessMode\":\"rw\",\"code\":\"cycle_time\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_loop\",\"attribute\":\"128\"},\"name\":\"循环定时\",\"typeSpec\":{\"maxlen\":255,\"type\":\"string\",\"typeDefaultValue\":\"\"}},
{\"abilityId\":43,\"accessMode\":\"rw\",\"code\":\"random_time\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_circle\",\"attribute\":\"128\"},\"name\":\"随机定时\",\"typeSpec\":{\"maxlen\":255,\"type\":\"string\",\"typeDefaultValue\":\"\"}},
{\"abilityId\":44,\"accessMode\":\"rw\",\"code\":\"switch_inching\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_circle\",\"attribute\":\"128\"},\"name\":\"点动开关\",\"typeSpec\":{\"maxlen\":255,\"type\":\"string\",\"typeDefaultValue\":\"\"}}]}]}"
  },
  "success": true,
  "t": 1699520718102,
  "tid": "1a52aae07edf11eeb1a19a6f3bbb8890"
}
```

{
    "category": "cz",
    "functions": [
        {
            "code": "switch_1",
            "dp_id": 1,
            "type": "Boolean",
            "values": "{}"
        },
        {
            "code": "countdown_1",
            "dp_id": 9,
            "type": "Integer",
            "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
        },
        {
            "code": "relay_status",
            "dp_id": 38,
            "type": "Enum",
            "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
        },
        {
            "code": "light_mode",
            "dp_id": 40,
            "type": "Enum",
            "values": "{\"range\":[\"relay\",\"pos\",\"none\"]}"
        },
        {
            "code": "child_lock",
            "dp_id": 41,
            "type": "Boolean",
            "values": "{}"
        },
        {
            "code": "cycle_time",
            "dp_id": 42,
            "type": "String",
            "values": "{}"
        },
        {
            "code": "random_time",
            "dp_id": 43,
            "type": "String",
            "values": "{}"
        },
        {
            "code": "switch_inching",
            "dp_id": 44,
            "type": "String",
            "values": "{}"
        }
    ],
    "lang_config": {},
    "status": [
        {
            "code": "switch_1",
            "dp_id": 1,
            "type": "Boolean",
            "values": "{}"
        },
        {
            "code": "countdown_1",
            "dp_id": 9,
            "type": "Integer",
            "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
        },
        {
            "code": "relay_status",
            "dp_id": 38,
            "type": "Enum",
            "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
        },
        {
            "code": "light_mode",
            "dp_id": 40,
            "type": "Enum",
            "values": "{\"range\":[\"relay\",\"pos\",\"none\"]}"
        },
        {
            "code": "child_lock",
            "dp_id": 41,
            "type": "Boolean",
            "values": "{}"
        },
        {
            "code": "cycle_time",
            "dp_id": 42,
            "type": "String",
            "values": "{}"
        },
        {
            "code": "random_time",
            "dp_id": 43,
            "type": "String",
            "values": "{}"
        },
        {
            "code": "switch_inching",
            "dp_id": 44,
            "type": "String",
            "values": "{}"
        }
    ]
}

# Product ID

 r9xep1xwyoubglpn

# Information about how the device functions

 an inline switch with relay which confirms device power, indicator light for options, child lock, and countdown timers with inching mode. 20A device.

**Comment by MJW911** [comment]
after some digging around, i see the device type is a "socket" under the "cz" category.

there isnt a corresponding .py file in the custom_components/tuya_local directory. it seems to share parts of the "switch" and "Sensor" command/status sets.

{
  "result": {
    "category": "cz",
    "status_list": [
      {
        "code": "countdown_usb1",
        "name": "USB1倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_usb2",
        "name": "USB2倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch",
        "name": "开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_1",
        "name": "开关1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_2",
        "name": "开关2",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_3",
        "name": "开关3",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_4",
        "name": "开关4",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_5",
        "name": "开关5",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_6",
        "name": "开关6",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "name": "开关1倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_2",
        "name": "开关2倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_3",
        "name": "开关3倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_4",
        "name": "开关4倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_5",
        "name": "开关5倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_6",
        "name": "开关6倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_usb1",
        "name": "USB1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_usb2",
        "name": "USB2",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "add_ele",
        "name": "增加电量",
        "type": "Integer",
        "values": "{\"unit\":\"kwh\",\"min\":0,\"max\":50000,\"scale\":3,\"step\":100}"
      },
      {
        "code": "cur_current",
        "name": "当前电流",
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_power",
        "name": "当前功率",
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":0,\"max\":50000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_voltage",
        "name": "当前电压",
        "type": "Integer",
        "values": "{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "child_lock",
        "name": "童锁",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "relay_status",
        "name": "上电状态",
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "switch_usb3",
        "name": "USB3",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_usb4",
        "name": "USB4",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_usb5",
        "name": "USB5",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_usb6",
        "name": "USB6",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_usb3",
        "name": "USB3倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_usb4",
        "name": "USB4倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_usb5",
        "name": "USB5倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_usb6",
        "name": "USB6倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "random_time",
        "name": "随机定时",
        "type": "Json",
        "values": "{}"
      },
      {
        "code": "cycle_time",
        "name": "循环定时",
        "type": "Json",
        "values": "{}"
      },
      {
        "code": "light_mode",
        "name": "指示灯状态设置",
        "type": "Enum",
        "values": "{\"range\":[\"none\",\"relay\",\"pos\"]}"
      },
      {
        "code": "switch_backlight",
        "name": "背光开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "voltage_coe",
        "name": "电压校准系数",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":1000000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "electric_coe",
        "name": "电流校准系数",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":1000000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "test_bit",
        "name": "产测结果位",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":5,\"scale\":0,\"step\":1}"
      },
      {
        "code": "power_coe",
        "name": "功率校准系数",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":1000000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "electricity_coe",
        "name": "电量校准系数",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":1000000,\"scale\":0,\"step\":1}"
      },
      {
        "name": "故障告警",
        "type": "Bitmap",
        "values": "{\"label\":[\"ov_cr\",\"ov_vol\",\"ov_pwr\",\"ls_cr\",\"ls_vol\",\"ls_pow\"]}"
      }
    ]
  },
  "success": true,
  "t": 1699529551526,
  "tid": "ab8958fe7ef311eeab249a6504bbc951"
}

**Comment by MJW911** [comment]
![Tuya local error](https://github.com/make-all/tuya-local/assets/103822540/0312e5cb-918c-4588-a6b8-8ae07d9170c2)
this is the error message i get when attempting to add the devices. 

happy to assist however i can with getting it added as a device.

**Comment by MJW911** [comment]
So i managed to connect to the devices and load them after many unsuccessful attempts (may have had something to do with parts of the localtuya integration still hanging around in yaml.

I am able to control the devices as simple switches successfully, but have received some log errors.


This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:103
Integration: Tuya Local (documentation, issues)
First occurred: November 18, 2023 at 1:23:55 PM (1 occurrences)
Last logged: November 18, 2023 at 1:23:55 PM

Report this to https://github.com/make-all/tuya-local/issues/

This error originated from a custom integration.

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:223
Integration: Tuya Local (documentation, issues)
First occurred: November 18, 2023 at 1:22:37 PM (1 occurrences)
Last logged: November 18, 2023 at 1:22:37 PM

Top Geyser receive loop has terminated

the devices have been working for 24 hours no with no issues.

**Comment by make-all** [comment]
There should be another log before that first one which lists the dps, that is the one that is needed for a new device request.  The two log messages are only ever output together, so if that one you gave is there, the other should be also.

**Comment by MJW911** [comment]
this is the previous error log:

This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:97
Integration: Tuya Local (documentation, issues)
First occurred: November 18, 2023 at 1:23:55 PM (1 occurrences)
Last logged: November 18, 2023 at 1:23:55 PM

Device matches SX1_Relay_Simple_Switch with quality of 50%. DPS: {"updated_at": 1700306632.7101316, "1": true, "9": 0, "38": "memory", "40": "relay", "41": false, "42": "", "43": "", "44": ""}

I attempted to write a YAML for the device, but think i made some errors...

name: Simple outlet with timer
products:
  - id: r9xep1xwyoubglpn
    name: SX1
primary_entity:
  entity: switch
  dps:
    - id: 1
      name: switch_1
      type: boolean
secondary_entities:
  - entity: number
    category: config
    name: countdown_1
    icon: "mdi:timer"
    dps:
      - id: 9
        name: value
        type: integer
        unit: s
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 0
            step: 1
  - entity: select
    name: relay_status
    class: enum
    icon: "mdi:toggle-switch"
    category: config
    dps:
      - id: 38
        type: string
        name: option
        optional: true
        mapping:
          - dps_val: "range"
            value: "On"
          - dps_val: "power_off"
            value: "Power_Off"
          - dps_val: "power_on"
            value: "power_on"
          - dps_val: last
            value: Last state
  - entity: select
    name: light_mode
    class: enum
    icon: "mdi:toggle-switch"
    category: config
    dps:
      - id: 40
        type: string
        name: option
        optional: true
        mapping:
          - dps_val: "range"
            value: "On"
          - dps_val: "relay"
            value: "relay"
          - dps_val: "pos"
            value: "position"
          - dps_val: none
            value: none

Im also getting this error on one of the devices:

This error originated from a custom integration.

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:546
Integration: Tuya Local (documentation, issues)
First occurred: 5:41:03 AM (746 occurrences)
Last logged: 1:47:47 PM

Failed to fetch device status for [redacted device name]
