### ISSUE TITLE
Ambient light bar [定制旧幻彩面板STWLA1]

### ISSUE THREAD

**Issue by fischrobi** [make-all/tuya-local#1282]
# Log Message

```
Please paste logs here
It can be adding like
- marpou_ceiling_lamp_ledlight
- rgb_led_strip
- rgbcw_lightbulb

but either has fully functions. (only the on-of works, but the scenes or colors dont)

2023-11-10 23:59:14.430 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call to sleep inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/device.py, line 77: self._api = tinytuya.Device(dev_id, address, local_key), please create a bug report at https://github.com/make-all/tuya-local/issues
2023-11-10 23:59:14.531 INFO (MainThread) [custom_components.tuya_local.device] Setting protocol version for Test to 3.3
2023-11-11 00:00:36.823 INFO (MainThread) [custom_components.tuya_local.device] Creating device: bfc01121664cef0894yaaj
2023-11-11 00:00:39.468 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call to sleep inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/device.py, line 77: self._api = tinytuya.Device(dev_id, address, local_key), please create a bug report at https://github.com/make-all/tuya-local/issues
2023-11-11 00:00:39.593 INFO (MainThread) [homeassistant.components.number] Setting up number.tuya_local
2023-11-11 00:00:39.597 INFO (MainThread) [homeassistant.components.select] Setting up select.tuya_local
2023-11-11 00:00:39.600 INFO (MainThread) [homeassistant.components.light] Setting up light.tuya_local
2023-11-11 00:00:39.642 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new number.tuya_local entity: number.fenybar_timer
2023-11-11 00:00:39.644 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new select.tuya_local entity: select.fenybar_scene
2023-11-11 00:00:39.649 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new light.tuya_local entity: light.fenybar
2023-11-11 00:00:39.666 INFO (MainThread) [custom_components.tuya_local.device] Setting protocol version for fenybar to 3.3
```

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"0000033d3p\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":20,\"accessMode\":\"rw\",\"code\":\"switch_led\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power\",\"attribute\":\"3\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":21,\"accessMode\":\"rw\",\"code\":\"work_mode\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_mode\"},\"name\":\"模式\",\"typeSpec\":{\"range\":[\"colour\",\"scene\",\"music\"],\"type\":\"enum\",\"typeDefaultValue\":\"colour\"}},
{\"abilityId\":24,\"accessMode\":\"rw\",\"code\":\"colour_data\",\"description\":\"类型：字符；\\nValue: 000011112222；\\n0000：H（色度：0-360，0X0000-0X0168）；\\n1111：S (饱和：0-1000, 0X0000-0X03E8）；\\n2222：V (明度：0-1000，0X0000-0X03E8)\",\"extensions\":{\"iconName\":\"icon-yanse\"},\"name\":\"彩光\",\"typeSpec\":{\"maxlen\":255,\"type\":\"string\",\"typeDefaultValue\":\"\"}},
{\"abilityId\":26,\"accessMode\":\"rw\",\"code\":\"countdown\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-a_nav_timer\",\"attribute\":\"2\"},\"name\":\"倒计时\",\"typeSpec\":{\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},
{\"abilityId\":27,\"accessMode\":\"wr\",\"code\":\"music_data\",\"description\":\"类型：字符串；\\nValue: 011112222333344445555；\\n0：   变化方式，0表示直接输出，1表示渐变；\\n1111：H（色度：0-360，0X0000-0X0168）；\\n2222：S (饱和：0-1000, 0X0000-0X03E8）；\\n3333：V (明度：0-1000，0X0000-0X03E8）；\\n4444：白光亮度（0-1000）；\\n5555：色温值（0-1000）\",\"extensions\":{\"iconName\":\"icon-dp_mic\"},\"name\":\"音乐律动\",\"typeSpec\":{\"maxlen\":255,\"type\":\"string\",\"typeDefaultValue\":\"\"}},
{\"abilityId\":51,\"accessMode\":\"rw\",\"code\":\"dreamlight_scene_mode\",\"description\":\"专门用于幻彩灯带场景\\nValue：ABCDEFGHIJJKLLM...\\nA：版本号；\\nB：情景模式编号；\\nC：变化方式（0-静态、1-渐变、2跳变、3呼吸、4-闪烁、10-流水、11-彩虹）\\nD：单元切换间隔时间（0-100）;\\nE：单元变化时间（0-100）；\\nFGH：设置项；\\nI：亮度（亮度V：0~100）；\\nJJ：颜色1（色度H：0-360）；\\nK：饱和度1 (饱和度S：0-100)；\\nLL：颜色2（色度H：0-360）；\\nM：饱和度2（饱和度S：0~100）；\\n注：有多少个颜色单元就有多少组，最多支持20组；\\n每个字母代表一个字节\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"幻彩情景\",\"typeSpec\":{\"maxlen\":255,\"type\":\"raw\"}},
{\"abilityId\":52,\"accessMode\":\"rw\",\"code\":\"dreamlightmic_music_data\",\"description\":\"专门用于幻彩灯带本地音乐\\nValue：ABCDEFGHIJKKLMMN...\\nA：版本号；\\nB：本地麦克风开关（0-关、1-开）；\\nC：音乐模式编号；\\nD：变化方式；\\nE：变化速度（1-100）;\\nF：灵敏度(1-100)；\\nGHI：设置项；\\nJ：亮度（亮度V：0~100）；\\nKK：颜色1（色度H：0-360）；\\nL：饱和度1 (饱和度S：0-100)；\\nMM：颜色2（色度H：0-360）；\\nN：饱和度2（饱和度S：0~100）；\\n注：有多少个颜色单元就有多少组，最多支持8组；\\n每个字母代表一个字节\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"炫彩本地音乐律动\",\"typeSpec\":{\"maxlen\":255,\"type\":\"raw\"}},
{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"dreamscene_data\",\"description\":\"专门用于预览幻彩灯带场景 Value：ABCDEFGHIJJKLLM... A：版本号； B：情景模式编号； C：变化方式（0-静态、1-渐变、2跳变、3呼吸、4-闪烁、10-流水、11-彩虹） D：单元切换间隔时间（0-100）; E：单元变化时间（0-100）； FGH：设置项； I：亮度（亮度V：0~100）； JJ：颜色1（色度H：0-360）； K：饱和度1 (饱和度S：0-100)； LL：颜色2（色度H：0-360）； M：饱和度2（饱和度S：0~100）； 注：有多少个颜色单元就有多少组，最多支持20组； 每个字母代表一个字节\",\"name\":\"幻彩场景\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}}]}]}"
  },
  "success": true,
  "t": 1699653576111,
  "tid": "6fe6d4f4801411ee947fc28416bb4602"
}
```

# Product ID

{
  "result": [
    {
      "active_time": 1699549083,
      "category": "dd",
      "create_time": 1699549083,
      "custom_name": "Fénybár",
      "icon": "smart/icon/ay1537253199182WiFyz/0f02ade7b620fe85630e0891f399a4b5.jpg",
      "id": "bfc01121664cef0894yaaj",
      "ip": "*************",
      "is_online": true,
      "lat": "**********",
      "local_key": "***********",
      "lon": "*******",
      "model": "定制旧幻彩面板STWLA1",
      "name": "Ambient Light Bar",
      "product_id": "kteusapswadn9pf5",
      "product_name": "Ambient Light Bar",
      "sub": false,
      "time_zone": "+01:00",
      "update_time": 1699549106,
      "uuid": "ba8535cb4e3000f8"
    }
  ],
  "success": true,
  "t": 1699653920794,
  "tid": "3d5c6048801511eeb1a19a6f3bbb8890"
}

# Information about how the device functions

https://img.kwcdn.com/product-file-public/1e133b36d82/3b69b0a66b46e66871c778417df0f401.pdf?_x_vst_scene=adg&_x_ads_sub_channel=search&_x_ads_channel=google&_x_ads_account=7333502893&_x_ads_set=20436177068&_x_ads_id=153023092220&_x_ads_creative_id=669017720576&_x_ns_source=g&_x_ns_gclid=CjwKCAiAxreqBhAxEiwAfGfndIwLuLOUexVmyaEjnmzgzdo5Agvr-gpXWWZDGrOyJ_ChoHUr_spUihoCWn4QAvD_BwE&_x_ns_placement=&_x_ns_match_type=e&_x_ns_ad_position=&_x_ns_product_id=&_x_ns_target=&_x_ns_devicemodel=&_x_ns_wbraid=CjgKCAiAo7KqBhAvEigAG2VnuDSm2EHr0YcXWhUj9i0PpV0DNFFtQ53ghmg-dLXD8FEzsosNGgJrPQ&_x_ns_gbraid=0AAAAAo4mICEIWCCOlIPQ0QSuPPzSdqJpY&_x_ns_keyword=temu&_x_ns_targetid=kwd-4583699489&_x_ns_extensionid=&_x_sessn_id=nb281tzwxa&refer_page_name=goods&refer_page_id=10032_1699654374013_4gz3p4kszu&refer_page_sn=10032

shop:
https://share.temu.com/5KXWfLR5GaA

**Comment by make-all** [comment]
Since you added it already, the logs are not showing the dps data that is logged when you first add the device.  Can you go to Settings / Devices & Services / Devices / ambient light bar, and download the diagnostics (button in top left box)

**Comment by fischrobi** [comment]
"data": {
    "name": "fenybar",
    "type": "rgbcw_lightbulb",
    "device_id": "**REDACTED**",
    "device_cid": "",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": 3.3,
    "tinytuya_version": "1.12.11",
    "api_version_set": 3.3,
    "api_version_used": 3.3,
    "api_working": true,
    "status": {},
    "cached_state": {
      "updated_at": 1699722228.163602,
      "20": true,
      "21": "scene",
      "24": "00fb03e802bc",
      "26": 0,
      "51": "AQkKMjKgAABkAABkADxkAHhkALRkAPBkASxk"
    },
    "pending_state": {},
    "connected": true,
    "force_dps": [],
    "home_assistant": {
      "name": "fenybar",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": "min",
          "state": {
            "entity_id": "number.fenybar_timer",
            "state": "0.0",
            "attributes": {
              "min": 0.0,
              "max": 1440.0,
              "step": 1.0,
              "mode": "auto",
              "unit_of_measurement": "min",
              "icon": "mdi:timer",
              "friendly_name": "fenybar Timer"
            },
            "last_changed": "2023-11-11T00:11:25.956291+00:00",
            "last_updated": "2023-11-11T00:11:25.956291+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "select.fenybar_scene",
            "state": "unknown",
            "attributes": {
              "options": [
                "Night",
                "Read",
                "Working",
                "Leisure",
                "Soft",
                "Colorful",
                "Dazzling",
                "Gorgeous"
              ],
              "icon": "mdi:palette",
              "friendly_name": "fenybar Scene"
            },
            "last_changed": "2023-11-11T00:11:25.955220+00:00",
            "last_updated": "2023-11-11T00:11:25.955220+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "light.fenybar",
            "state": "on",
            "attributes": {
              "min_color_temp_kelvin": 2700,
              "max_color_temp_kelvin": 6500,
              "min_mireds": 153,
              "max_mireds": 370,
              "effect_list": [
                "Scene",
                "Music"
              ],
              "supported_color_modes": [
                "color_temp",
                "hs"
              ],
              "color_mode": "hs",
              "brightness": 0,
              "color_temp_kelvin": null,
              "color_temp": null,
              "hs_color": [
                251,
                100
              ],
              "rgb_color": [
                46,
                0,
                255
              ],
              "xy_color": [
                0.147,
                0.045
              ],
              "effect": "Scene",
              "friendly_name": "fenybar",
              "supported_features": 4
            },
            "last_changed": "2023-11-11T12:56:39.876215+00:00",
            "last_updated": "2023-11-11T12:56:39.876215+00:00"
          }
        }
      ]
    }
  }
}

**Comment by fischrobi** [comment]
I just put on localtuya to check what dpID-s it says:

![image](https://github.com/make-all/tuya-local/assets/118021596/98236f1c-42be-4822-b5a6-7e9c8e55eba0)

I hope it can helps too
