### ISSUE TITLE
Request support for IoT Curtain 3M

### ISSUE THREAD

**Issue by ops244** [make-all/tuya-local#1291]
Device matches loonas_curtain with quality of 57%. DPS: {"updated_at": 1699828861.3765116, "1": "stop", "2": 0, "3": 0, "5": "forward", "7": "closing", "11": "fully_open", "102": true}

----------------------------------------------------------------------------------------------------------------------------------------------------

{
  "result": {
    "model": "{\"modelId\":\"0000026bet\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"control\",\"description\":\"【必选项】用于控制电机的开启、暂停、关闭。该DP点枚举值参数不允许修改，不允许增减。\",\"extensions\":{\"iconName\":\"icon-dp_power2\"},\"name\":\"控制\",\"typeSpec\":{\"range\":[\"open\",\"stop\",\"close\"],\"type\":\"enum\",\"typeDefaultValue\":\"open\"}},{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"percent_control\",\"description\":\"如果窗帘电机可以监控窗帘目前的所处位置，例如窗帘现在开了一半，也就是50%，那么可以通过该DP点进行窗帘位置的自定义控制。控制使用该DP点，如果选择了该DP点，必选选择“”开启百分比状态显示“”，该DP点数值范围值参数不允许修改，不允许增减。\",\"name\":\"开启百分比控制\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%\"}},{\"abilityId\":3,\"accessMode\":\"ro\",\"code\":\"percent_state\",\"description\":\"该DP点与“”开启百分比状态控制“”配套使用。改DP点用于显示实际窗帘所处位置。该DP点数值范围值参数不允许修改，不允许增减。\",\"name\":\"开启百分比状态\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%\"}},{\"abilityId\":5,\"accessMode\":\"rw\",\"code\":\"control_back\",\"description\":\"用于设置电机转向，顺时针，或者逆时针，forward代表顺时针，back代表逆时针\",\"name\":\"电机反向\",\"typeSpec\":{\"range\":[\"forward\",\"back\"],\"type\":\"enum\",\"typeDefaultValue\":\"forward\"}},{\"abilityId\":7,\"accessMode\":\"ro\",\"code\":\"work_state\",\"description\":\"【必选项】用于显示电机的当前工作状态。该DP点枚举值参数不允许修改，不允许增减。如需要修改在APP面板中显示的内容，可以前往第四步的拓展中心，多语言管理修改代表值，新增的枚举值所代表的的内容也是在多语言中修改代表值。\",\"name\":\"工作状态\",\"typeSpec\":{\"range\":[\"opening\",\"closing\"],\"type\":\"enum\",\"typeDefaultValue\":\"opening\"}},{\"abilityId\":11,\"accessMode\":\"ro\",\"code\":\"situation_set\",\"description\":\"上报该DP点枚举值，以告知APP，该窗帘，100%对应的是全开，还是全关。不上报或者不选择改DP点，则默认100%为全关。\",\"name\":\"百分比含义\",\"typeSpec\":{\"range\":[\"fully_open\",\"fully_close\"],\"type\":\"enum\",\"typeDefaultValue\":\"fully_open\"}},{\"abilityId\":12,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"【必选】设备上报故障值，该DP点枚举值可增减，但不可修改枚举值名称，例如可以删除motor_fault，可以增加其他值，未选则不展示该功能。 如需要修改在APP面板中显示的内容，可以前往第四步的拓展中心，多语言管理修改代表值，新增的枚举值所代表的的内容也是在多语言中修改代表值。\",\"name\":\"故障告警\",\"typeSpec\":{\"label\":[\"motor_fault\"],\"maxlen\":1,\"type\":\"bitmap\",\"typeDefaultValue\":0}},{\"abilityId\":102,\"accessMode\":\"rw\",\"code\":\"Handpulled\",\"description\":\"\",\"name\":\"手拉启动\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}}]}]}"
  },
  "success": true,
  "t": 1699829180624,
  "tid": "4c4a1cd081ad11eea3b2361f03176748"
}

--------------------------------------------------------------------------------------------------------------------------------------------------

https://hiper-power.com/catalog/umnyy-dom/umnaya-tekhnika/umnyy-elektrokarniz-dlya-shtor-curtain-3m/

**Comment by ops244** [comment]
{
"result": [
{
"active_time": 1698723813,
"category": "cl",
"create_time": 1670429602,
"custom_name": "шторы зал",
"icon": "smart/icon/ay1541662398752zwSuU/8f65af3fa065bce2581652506da778b6.jpg",
"id": "",
"ip": "",
"is_online": true,
"lat": "56.3302",
"local_key": "",
"lon": "43.9301",
"model": " IoT Curtain 3M ",
"name": "IoT Curtain 3M",
"product_id": "qxzxmhkdvqexpwqx",
"product_name": " IoT Curtain 3M ",
"sub": false,
"time_zone": "+03:00",
"update_time": 1698723820,
"uuid": "1114010224a16028d6bf"
}
],
"success": true,
"t": 1699829476512,
"tid": "fcbac0e981ad11eeb1a19a6f3bbb8890"
}

**Comment by ops244** [comment]
Do you need any more information? It has been hanging in the issue for 4 months

**Comment by make-all** [comment]
I am unable to find this for sale anywhere outside of Russia.  Currently Russia is engaged in a war of aggression against a neighboring country, so I do not wish to spend my time on work that will exclusively benefit Russia at this time.

**Comment by ops244** [comment]
absolutely all countries have waged wars, it's just that it's so overblown around Russia, the United States only lives in wars, but somehow I haven't heard that they would be condemned... regarding the sale exclusively in Russia, on the contrary, this company left the Russian market and I bought them on the American website... lol
