### ISSUE TITLE
Support sensors - roadmap?

### ISSUE THREAD

**Issue by pironic** [make-all/tuya-local#13]
I understand your current documentation suggests that you are focusing on items that are not well supported by the tuya cloud api... That being said, contact sensors are currently entirely unsupported on the tuya cloud api. Is there any including in the near roadmap for supporting these types of devices in this project?

Thanks very much for your work thus far. <3

**Comment by make-all** [comment]
Tuya sensors are impossible to support by local communication, as they spend most of their time offline to conserve battery, and only come online to report sensor changes to the cloud.  It would have to be the cloud API that adds support for these (or reflash them with Tasmota or ESPHome and get them to report to HA or an MQTT server instead if they are ESP based)

**Comment by pironic** [comment]
hmm... reading through source code i see that we rely on tinytuya to provide connectivity. I tried to see if that library can see my door sensors and it does not. Might be dead in the water before we even set sail. :/
