### ISSUE TITLE
LoraTap Curtain Switch

### ISSUE THREAD

**Issue by majker17** [make-all/tuya-local#1300]
Dears,

I used LoraTap curtain switch in SmartLife and I would like to import the devices to Local Tuya.

I still has got the problem with the functionality because the entities are not visible. Sometimes I saw in logs this kind of errors:

Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 13 listopada 2023 21:42:44 (1 occurrences)
Last logged: 13 listopada 2023 21:42:44

Error setting up entry Roleta sypialnia 2 for cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 206, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!

This is standard instruction for the lora tap:

![commands](https://github.com/make-all/tuya-local/assets/150544029/db8f6d1d-b19c-45e2-9404-fadffdc01b35)

The connection looks fine. Could you support me and tell me what am I doing wrong?

![roleta1](https://github.com/make-all/tuya-local/assets/150544029/538e6cb1-abac-40c0-85a4-187e3f3b89ed)

Let me know if I should check something or provide more data. Thank you in advanced.

**Comment by make-all** [comment]
These errors are not from this integration.
It looks like you have somehow gotten duplicate entities in your registry.  Remove them (including any hidden or disabled ones) and try adding the device again.

**Comment by majker17** [comment]
Hello,

I tried to reload it but there is still the same. Could you tell me how to take a look to app register to check and modify that?

**Comment by make-all** [comment]
Settings / Devices & Services / Entities / Clear (where it says "... entities not shown").  Find your entities related to this curtain and check the box, then "Remove Selected".
Go to the Devices tab, and do the same for the devices related to this curtain.

Restart, then add the device again.

**Comment by majker17** [comment]
Dear make-all,

after steps which you suggest me I saw the same problem. Do you have any idea what is the matter?
![1](https://github.com/make-all/tuya-local/assets/150544029/89fd8a75-a345-48ba-9c34-f75836597327)
![2](https://github.com/make-all/tuya-local/assets/150544029/541c8694-d0b7-40d8-987b-46ba85faf924)
![3](https://github.com/make-all/tuya-local/assets/150544029/f8825ff2-d1f5-4a61-bd4d-234d58d71c3a)

**Comment by make-all** [comment]
Do you mean you are still getting this in the log?

```
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
```

Or your issue is that the state is Unknown (which may be because the device is not returning any info about its current state).

**Comment by majker17** [comment]
Dear make-alll,

I checked the logs and I did not see this kind of problems. I did not know what is the issue but in general on cloud everything works fine. 

I did not see the line which you send to me in logs.

What should I do in this situation?

**Comment by majker17** [comment]
Hi, I create new HAOS but it is still the same.
![Uploading a.PNG…]()

**Comment by majker17** [comment]
Hi I solve the isse used other HACS. But from my observation the LoraTap use the control based on number 1,2,3 - I suppose your hacs use the start pause stop. Please if it is possible add it to your plugin becasuse it is quite good but for me is unusefull becasue of the problem with blinds. Thanks in advance.

**Comment by msaphoto06** [comment]
same problem
it's Ok with 1,2,3 option in local tuya

**Comment by fdreckmann** [comment]
Any Updates ?

**Comment by make-all** [comment]
If you are getting the error reported, then you have somehow managed to get duplicated config entries. The problem is not related to this integration, and the steps to remove the entities and re-add the device are listed above.

According to this comment, the steps worked to solve the original issue:
https://github.com/make-all/tuya-local/issues/1300#issuecomment-1812030043
