### ISSUE TITLE
Electric Dehumidifier CD12PW wrong device type

### ISSUE THREAD

**Issue by sfgrabowski** [make-all/tuya-local#131]
I'm trying to re-add my Electriq Dehumidifier CD12PW. It used to work, then became unavailable, so tried adding it again after deleting the integration.

I am now getting the wrong device types in the selection. I can choose either: garage_door_opener or simple_switch.

It used to work perfectly and create the required humidifier entities, but I can no longer select the correct parameters so am unable to add the device successfully.

Does anyone have a solution? It is added via the official Tuya integration, but that also only shows as a simple on/off, rather than all the different entities this integration used to provide.

I'm seeing a few different errors in my log:

`Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:73 
Integration: Tuya Local ([documentation](https://github.com/make-all/tuya-local), [issues](https://github.com/make-all/tuya-local/issues)) 
First occurred: 6 February 2022, 21:27:53 (6 occurrences) 
Last logged: 21:40:23
Device matches garage_door_opener with quality of 25%. DPS: {'1': False, '2': 'auto', '3': 72, '5': True, '10': False, '101': True, '102': '45', '103': 20, 'updated_at': 1644189642.9686792}
Device matches garage_door_opener with quality of 25%. DPS: {'1': False, '2': 'auto', '3': 74, '5': True, '10': False, '101': True, '102': '45', '103': 20, 'updated_at': 1644190497.3329158}
Device matches garage_door_opener with quality of 25%. DPS: {'1': True, '2': 'auto', '3': 50, '5': True, '10': False, '101': True, '102': '45', '103': 22, 'updated_at': 1644270819.2511923}
Device matches garage_door_opener with quality of 25%. DPS: {'1': True, '2': 'auto', '3': 58, '5': True, '10': False, '101': True, '102': '45', '103': 22, 'updated_at': 1644356079.6559415}
Device matches garage_door_opener with quality of 25%. DPS: {'1': True, '2': 'auto', '3': 57, '5': True, '10': False, '101': True, '102': '45', '103': 23, 'updated_at': 1644356422.64602}`

and

`Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:76 
Integration: Tuya Local ([documentation](https://github.com/make-all/tuya-local), [issues](https://github.com/make-all/tuya-local/issues)) 
First occurred: 6 February 2022, 21:27:53 (6 occurrences) 
Last logged: 21:40:23

Report this to https://github.com/make-all/tuya-local/issues/`

and previously...

`Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:248 
Integration: Tuya Local ([documentation](https://github.com/make-all/tuya-local), [issues](https://github.com/make-all/tuya-local/issues)) 
First occurred: 6 February 2022, 21:24:32 (6 occurrences) 
Last logged: 6 February 2022, 21:26:02

Failed to refresh device state for Electriq Dehumidifier CD12PW.
Failed to refresh device state for Test.`

**Comment by make-all** [comment]
Try adding it after turning the switch on.  It seems it is not reporting the humidity setting, which may be because it is switched off.
Alternatively, the firmware has been upgraded, and the humidity moved to dp 102.

**Comment by make-all** [comment]
I don't think the dp 102 is the humidity setting actually, as it is surrounded by quotes, which normally means one of a limited set of options. It could be an angle for the airflow output.

**Comment by sfgrabowski** [comment]
I've tried power cycling the dehumidifier and am still getting the same issue. I've checked the Tuya Smart Life app and it shows the following regarding firmware versions:

`Main Module: V3.1.4
MCU Module: V1.0.0`

I don't know if that is of any use.

I can't see any other information in the logs related to the dehumidifier. I think this started after I unplugged the machine temporarily whilst cleaning, and haven't intentionally updated the firmware etc.

**Comment by make-all** [comment]
The only advice I have is to cycle through the modes and change the set humidity from the device's control panel, then try to add it in Home Assistant while it is switched on.  Hopefully one of those things will bring the set humidity back into the reported dps values, so it can be recognised.

I'm not familiar with the release history for the device's firmware, so the version numbers on their own don't really say anything, just that might be an explanation for why the device's behaviour has changed (if it has changed permanently, and is not just in this state because the last set humidity was out of range or something like that).

**Comment by sfgrabowski** [comment]
Thanks. Followed the advice of cycling through the modes, setting the humidity via the buttons, then power cycling. Then managed to get the dehumidifier into HA. Unfortunately it came through as unavailable although the entities were generated. Restarting HA and then waiting a few minutes solved it. Thanks for your help.
