### ISSUE TITLE
stuck in integration wizard

### ISSUE THREAD

**Issue by latel** [make-all/tuya-local#1310]
**Describe the bug**
stuck in integration wizard

**To Reproduce**
install with hacs, restart homeassistant, add device using tuya-local integration

**Expected behavior**
show wizard

**Additional context**
stucking in loading wizard dialog
![image](https://github.com/make-all/tuya-local/assets/5621862/3cecfc94-e438-4c7f-a3d8-8ba4e3a40010)

tuya local: 2023.11.0
Homeassistant
Core 2023.11.2
Supervisor 2023.11.3
Frontend 20231030.2

**Comment by latel** [comment]
after a long time of waiting, problems resolved, I saw the wizard dialog

**Comment by Xornop** [comment]
Have the same issue, has not been resolved. Sometimes after a long time (15 minutes) it says
Config flow could not be loaded: Unknown error
