### ISSUE TITLE
Unable to add any devices via the integration now

### ISSUE THREAD

**Issue by aatifk** [make-all/tuya-local#1329]
**Describe the bug**
I'm unable to add any devices via the integration. Had a power outage this morning and when everything came back online, two merkury smart bulbs that were previously connected via Tuya-local never connected back. Power-cycled the bulbs several times with no luck. I removed them from the integration to add them back but now they won't join at all. I keep getting the intermittent connection issue error, but I've been trying this for over 12 hours now. 

**To Reproduce**
Unexpected shutdown of the whole power system.

**Expected behavior**
The integration should have come back online as expected. 

**Additional context**
I've been trying to add a Tuya-based WiFi Bridge as well (AC701) and that won't connect either. However, not sure if that's even supported since trying this for the first time. 

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

**Comment by make-all** [comment]
Requests for help should be posted in discussions, not the issue tracker.
