### ISSUE TITLE
loratap_curtain_switch unknown

### ISSUE THREAD

**Issue by GeekSpirit34** [make-all/tuya-local#1330]
Hello, my loratap_curtain_switch as unknown :
 ![Screenshot_20231121_084543](https://github.com/make-all/tuya-local/assets/151208812/87ce3a36-2119-4023-a141-824ddef7aae8)

Diagnosis : 

`{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.11.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Paris",
    "os_name": "Linux",
    "os_version": "6.1.21-v8",
    "supervisor": "2023.11.3",
    "host_os": "Home Assistant OS 11.1",
    "docker_version": "24.0.6",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "sonoff": {
      "version": "3.5.3",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "tuya_local": {
      "version": "2023.11.0",
      "requirements": [
        "pycryptodome~=3.18",
        "tinytuya==1.12.11"
      ]
    },
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya_local",
    "name": "Tuya Local",
    "codeowners": [
      "@make-all"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/make-all/tuya-local",
    "integration_type": "device",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/make-all/tuya-local/issues",
    "requirements": [
      "pycryptodome~=3.18",
      "tinytuya==1.12.11"
    ],
    "version": "2023.11.0",
    "is_built_in": false
  },
  "data": {
    "name": "Volet 1er",
    "type": "loratap_curtain_switch",
    "device_id": "**REDACTED**",
    "device_cid": "",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": "auto",
    "tinytuya_version": "1.12.11",
    "api_version_set": 3.3,
    "api_version_used": 3.3,
    "api_working": true,
    "status": {},
    "cached_state": {
      "updated_at": 1700552808.8894181,
      "1": "3"
    },
    "pending_state": {},
    "connected": true,
    "force_dps": [],
    "home_assistant": {
      "name": "Volet 1er",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "blind",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "cover.volet_1er",
            "state": "unknown",
            "attributes": {
              "device_class": "blind",
              "friendly_name": "Volet 1er",
              "supported_features": 0
            },
            "last_changed": "2023-11-21T07:39:05.970173+00:00",
            "last_updated": "2023-11-21T07:39:05.970173+00:00"
          }
        }
      ]
    }
  }
}`

The device works fine from tuya developer interface, i can control it normaly.
Log journal said he is become unknown : 
![Screenshot_20231121_084543](https://github.com/make-all/tuya-local/assets/151208812/4a942891-126b-4bb2-a860-99593904583c)
I tried to reload it, remove and add it another once, the same problem appear.

Tell me if you need more information, i'm new to HA and Tuya local but i'm web developer so if i can help you to understand more my problem do not hesitate.

Thanks

**Comment by msaphoto06** [comment]
same problem
it's Ok with 1,2,3 option in localtuya
