### ISSUE TITLE
Geyserwise Target Temperature is Always set to Overnight Temperature (Block 1)

### ISSUE THREAD

**Issue by asifkassam** [make-all/tuya-local#1337]
**Describe the bug**
It appears that the water_heater entity has a target temperature always set to the temperature of DPID103 (number.entityname_overnight_temperature)

**To Reproduce**
see attached screen capture done at 8am (target should be Block 2 - Morning Temperature entity number)
[Recording 2023-11-23 081222.zip](https://github.com/make-all/tuya-local/files/13446905/Recording.2023-11-23.081222.zip)

**Expected behavior**
Geyserwise allows users to set the target temperature of the water heater in 4 blocks (blocks 1-4) with the following configuration - I am wondering if this is something that can be achieved by the integration? 

![image](https://github.com/make-all/tuya-local/assets/67918736/68ff1a26-ce05-493e-8073-6a6677f91dd6)
 as depicted on page 39 of https://www.geyserwise.com/wp-content/uploads/2023/05/GeyserWise-Max-installers-manual-2015.07.01.pdf

**Additional context**
An automation to manually set the target temperature to Block1, Block2, Block3, Block4 at 00:00, 06:00,12:00,18:00 by the user is an acceptable work-around though this resets Block1 to Target Temperature and if  Block1  is adjusted between 06:00 and 23:59 then the target temperature is changed to Block1 again.

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

device diagnostics attached:

[tuya_local-c1ba0c6deab0f4be6b31a055a4c87f84-Geyserwise Main-f6de5a91baeef31bd8063b868afb3a81.json.txt](https://github.com/make-all/tuya-local/files/13446687/tuya_local-c1ba0c6deab0f4be6b31a055a4c87f84-Geyserwise.Main-f6de5a91baeef31bd8063b868afb3a81.json.txt)

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.
no logged error

**Comment by make-all** [comment]
Do any of the dps return information that indicate which "block" is currently active?  If so, it should be possible to support this additional complexity.

**Comment by asifkassam** [comment]
Not that I can determine

Heres the query from "Query Things Data Model"

{
  "result": {
    "model": "{\"modelId\":\"000004r919\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"1664\"},\"name\":\"Power\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"mode\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"attribute\":\"1664\"},\"name\":\"Mode\",\"typeSpec\":{\"range\":[\"Holiday\",\"Timer\"],\"type\":\"enum\",\"typeDefaultValue\":\"Holiday\"}},{\"abilityId\":10,\"accessMode\":\"ro\",\"code\":\"temp_current\",\"description\":\"0-125\",\"extensions\":{\"iconName\":\"icon-dp_c\",\"attribute\":\"1152\"},\"name\":\"Geyser Temp\",\"typeSpec\":{\"max\":125,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"℃\"}},{\"abilityId\":13,\"accessMode\":\"ro\",\"code\":\"work_state\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-zhuangtai\",\"attribute\":\"1152\"},\"name\":\"Element\",\"typeSpec\":{\"range\":[\"Off\",\"On\"],\"type\":\"enum\",\"typeDefaultValue\":\"Off\"}},{\"abilityId\":20,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"e1-e9\",\"extensions\":{\"iconName\":\"icon-baojing\",\"scope\":\"fault\",\"attribute\":\"1152\"},\"name\":\"Fault\",\"typeSpec\":{\"label\":[\"Earth_leakge\",\"Dry_burn\",\"Wt_sensor_fault\",\"Heating_loss\",\"Over_temp\",\"Water_leak\",\"Comm_failure\",\"Ct_probe_fault\",\"Pump_failure\"],\"maxlen\":9,\"type\":\"bitmap\",\"typeDefaultValue\":0}},{\"abilityId\":101,\"accessMode\":\"ro\",\"code\":\"Pump\",\"description\":\"Rotation Pump On/Off State\",\"name\":\"Pump State\",\"typeSpec\":{\"range\":[\"Off\",\"On\"],\"type\":\"enum\",\"typeDefaultValue\":\"Off\"}},{\"abilityId\":102,\"accessMode\":\"rw\",\"code\":\"Solar_Differential\",\"description\":\"solar differential setting 7-15℃\",\"name\":\"Solar Differential\",\"typeSpec\":{\"max\":15,\"min\":7,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":7,\"unit\":\"℃\"}},{\"abilityId\":103,\"accessMode\":\"rw\",\"code\":\"Block1\",\"description\":\"0：00-6：00 设定温度\",\"name\":\"Block1\",\"typeSpec\":{\"max\":75,\"min\":30,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":30,\"unit\":\"℃\"}},{\"abilityId\":104,\"accessMode\":\"rw\",\"code\":\"Block2\",\"description\":\"6：00-12：00 设定温度\",\"name\":\"Block2\",\"typeSpec\":{\"max\":75,\"min\":30,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":30,\"unit\":\"℃\"}},{\"abilityId\":105,\"accessMode\":\"rw\",\"code\":\"Block3\",\"description\":\"12：00-18：00 设定温度\",\"name\":\"Block3\",\"typeSpec\":{\"max\":75,\"min\":30,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":30,\"unit\":\"℃\"}},{\"abilityId\":106,\"accessMode\":\"rw\",\"code\":\"Block4\",\"description\":\"12：00-18：00 设定温度\",\"name\":\"Block4\",\"typeSpec\":{\"max\":75,\"min\":30,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":30,\"unit\":\"℃\"}},{\"abilityId\":107,\"accessMode\":\"rw\",\"code\":\"Anti_Freeze_Temp\",\"description\":\"anti freeze temperature setting 0-10℃\",\"name\":\"Anti Freeze Temp.\",\"typeSpec\":{\"max\":10,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"℃\"}},{\"abilityId\":108,\"accessMode\":\"ro\",\"code\":\"Collector_Temp\",\"description\":\"collector temperature 0-197℃\",\"name\":\"Collector\",\"typeSpec\":{\"max\":197,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"℃\"}},{\"abilityId\":109,\"accessMode\":\"ro\",\"code\":\"Element_Runtime\",\"description\":\"Element runtime calculate 0-999\",\"name\":\"Element Runtime\",\"typeSpec\":{\"max\":999,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"hour\"}}]}]}"
  },
  "success": true,
  "t": 1700728925164,
  "tid": "2dd5534c89dc11ee82d73e55532a4cc5"

**Comment by make-all** [comment]
It is out of scope of this general integration to provide device specific customisations of the UI that go beyond the data the device is returning.  If the device is unable to inform the integration which is the active temperature block, then we are not able to dynamically switch it.

**Comment by asifkassam** [comment]
Just a thought - would it be possible (better?) to create the water_heater entity without a target temperature (if possible?) since it is only valid between 00:00 and 06:00 and you create the individual temperature blocks anyway so no functionality is lost.

It would prevent inadvertent changes to block1 temperature by user trying to adjust the water_heater entity target temperature outside of the block1 time
