### ISSUE TITLE
Thermostat BHT-002GBLW Wrong temperature

### ISSUE THREAD

**Issue by shojkeee** [make-all/tuya-local#134]
Hello. It may have already been in the branches. But I didn't find it. As I understand it, the main tuyalocal integration does not have thermostat support. Your support is available. But it doesn't work without the main tuyalocal integration as I understand it. 

In general, the problem is the following. When adding the BHT-002GBLW thermostat, the temperature is not correct. Is there any way to fix this?

![image](https://user-images.githubusercontent.com/72029085/153766696-1e9669fb-52f0-4463-afcf-46e677d0ec60.png)

**Comment by shojkeee** [comment]
I noticed that the readings are exactly 5 times less than they should be

**Comment by vampywiz17** [comment]
it is a different integration not connect to the local tuya integration. Try this one, wihout other tuya integration.

**Comment by shojkeee** [comment]
> it is a different integration not connect to the local tuya integration. Try this one, wihout other tuya integration.

I do not understand.  Can you explain what to try?  In details

**Comment by vampywiz17** [comment]
@shojkeee 

Your screenshot is show localuya integration. This Integration (tuya-local) is a different one. Not need to install localtuya that it work.

Just add this integration to HACS, Install it and add the tuya device (need ID and key of course)

**Comment by shojkeee** [comment]
> @shojkeee
> 
> Your screenshot is show localtuya integration. This Integration (tuya-local) is a different one. Not need to install localtuya that it work.
> 
> Just add this integration to HACS, Install it and add the tuya device (need ID and key of course)

When I only added your integration.  And going to settings->integrations.  I did not add tuyalocal.  I did not understand how to connect the device in it.

**Comment by shojkeee** [comment]
@vampywiz17
Can you describe to me step by step where to go to add a device? I know the id and key. I don't understand where to add the device.

There is no such thing in settings-> integration. I'm trying to add it to the configuration file.yaml is something like this code:

climate:
   - platform: tuya-local
     host: 192.168.31.165
     local_key: '77f2b30f83422b63434a'
     device_id: '13101012d532628bfc00ab9d8'
     name: 'moes'
     scan_interval: 5
     min_temp: 5
     max_temp: 35
     protocol_version: 3.3

but he also swears and nothing happens.((((

**Comment by make-all** [comment]
After installing tuya-local, through HACS or manually, you should be able to add devices from the Integrations page of your HA config.  Press  the "Add Integration" button at the bottom right, and start typing tuya-local to select this integration,  Then you should get a dialog requesting device id, local key and IP address.  After entering those, you will get a second dialog letting you select your device type from the possible matches. Finally will be a dialog to select which entities you want to make available.

**Comment by shojkeee** [comment]
Thanks. Found. It is called Tuya Local. But I faced another problem. the device is not being added.

![image](https://user-images.githubusercontent.com/72029085/153838894-840b902c-f495-4d68-afe8-87627ec15b73.png)


Although the data is correct. In the usual Localtuya, they were accepted and everything worked.

![image](https://user-images.githubusercontent.com/72029085/153839016-66d1b0c0-90a4-4449-9c7e-df04959b173a.png)

**Comment by vampywiz17** [comment]
First, add this repo to HACS:

![image](https://user-images.githubusercontent.com/14281430/153826565-6eaeca51-3833-4256-a8b3-9035d4d42627.png)

add tuya local integration:

![image](https://user-images.githubusercontent.com/14281430/153839063-2e062afd-e2ea-4a04-9c41-9377969f8dd7.png)

add neccasery data:

![image](https://user-images.githubusercontent.com/14281430/153839164-63be2163-908b-4017-90e6-7d28743c37b5.png)

That is all.

Edit:

Ah, @make-all faster than me :)

**Comment by shojkeee** [comment]
> Спасибо. Нашел. Называется Туя Местная. Но я столкнулся с другой проблемой. устройство не добавляется.
> 
> ![изображение](https://user-images.githubusercontent.com/72029085/153838894-840b902c-f495-4d68-afe8-87627ec15b73.png)
> 
> Хотя данные верны. В обычной Локалтуе их приняли и все заработало.
> 
> ![изображение](https://user-images.githubusercontent.com/72029085/153839016-66d1b0c0-90a4-4449-9c7e-df04959b173a.png)

Could it be because localtuya is installed in parallel?

**Comment by vampywiz17** [comment]
@shojkeee 

Possible. Tuya devices anly accept one local connection.

**Comment by shojkeee** [comment]
> @shojkeee
> 
> Possible. Tuya devices only accept one local connection.

Thanks. After I deleted the device, everything was added to localtuya. And everything started to show correctly. But at the beginning, the values were not available. Everything loaded with a delay. Is this normal?

**Comment by vampywiz17** [comment]
@shojkeee 

If you add a device, after restart the HA.

**Comment by shojkeee** [comment]
When I saw the unavailable values, I did so.

Sorry again, for being so blind and not seeing tua local in and integrations. Because I was looking at the icons, and not reading the letters ((((

**Comment by make-all** [comment]
Delay is normal, this integration is async so it does not block startup waiting for the devices to start communicating.  Also it has automatic recognition of the protocol version, so ca n take a couple of tries before it gets the communication right, and quite a slow polling interval due to some devices requiring it.
