### ISSUE TITLE
Asakuki Aroma Diffuser

### ISSUE THREAD

**Issue by AsztalosZs** [make-all/tuya-local#1343]
Hello

I have an Asakuki Diffuser and managed to add it to HA by Tuya-Local, but the two main entities are switched. What the HA shows as a lamp turns on the diffuser and the diffuser switch turns on the lamp.
Of course, I could change the icon and the frendly name, but the "more info" window still works according to the original function.
I would like to ask for a solution to this.

  "integration_manifest": {
    "domain": "tuya_local",
    "name": "Tuya Local",
    "codeowners": [
      "@make-all"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/make-all/tuya-local",
    "integration_type": "device",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/make-all/tuya-local/issues",
    "requirements": [
      "pycryptodome~=3.18",
      "tinytuya==1.12.11"
    ],
    "version": "2023.11.0",
    "is_built_in": false
  },
  "data": {
    "name": "Asakuki Aroma Diffuser",
    "type": "asakuki_diffuser",
    "device_id": "**REDACTED**",
    "device_cid": "",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": "auto",
    "tinytuya_version": "1.12.11",
    "api_version_set": 3.3,
    "api_version_used": 3.3,
    "api_working": true,
    "status": {},
    "cached_state": {
      "updated_at": 1700861566.2345712,
      "1": false,
      "11": true,
      "12": 0,
      "13": "0",
      "14": 0,
      "103": "off",
      "108": "7e00ff010dffff",
      "109": "white",
      "110": "1",
      "111": 245
    },
    "pending_state": {},
    "connected": true,
    "force_dps": [],
    "home_assistant": {
      "name": "Asakuki Aroma Diffuser",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "fan.asakuki_aroma_diffuser",
            "state": "on",
            "attributes": {
              "preset_modes": [],
              "percentage": 50,
              "percentage_step": 50.0,
              "preset_mode": null,
              "icon": "mdi:scent",
              "friendly_name": "Asakuki Aroma Diffuser",
              "supported_features": 1
            },
            "last_changed": "2023-11-24T21:29:40.740174+00:00",
            "last_updated": "2023-11-24T21:29:40.740174+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "light.asakuki_aroma_diffuser",
            "state": "off",
            "attributes": {
              "effect_list": [
                "Color",
                "Mood"
              ],
              "supported_color_modes": [
                "white"
              ],
              "color_mode": null,
              "brightness": null,
              "effect": null,
              "color_data": "7e00ff010dffff",
              "friendly_name": "Asakuki Aroma Diffuser",
              "supported_features": 4
            },
            "last_changed": "2023-11-24T21:29:37.469697+00:00",
            "last_updated": "2023-11-24T21:29:37.469697+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "select.asakuki_aroma_diffuser_mood",
            "state": "Mood 1",
            "attributes": {
              "options": [
                "Mood 1",
                "Mood 2",
                "Mood 3"
              ],
              "icon": "mdi:palette",
              "friendly_name": "Asakuki Aroma Diffuser Mood"
            },
            "last_changed": "2023-11-24T21:25:58.738556+00:00",
            "last_updated": "2023-11-24T21:25:58.738556+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "select.asakuki_aroma_diffuser_color",
            "state": "unknown",
            "attributes": {
              "options": [
                "Red",
                "Orange",
                "Yellow",
                "Green",
                "Blue",
                "Indigo",
                "Violet",
                "Pink",
                "Cyan"
              ],
              "icon": "mdi:palette",
              "friendly_name": "Asakuki Aroma Diffuser Color"
            },
            "last_changed": "2023-11-24T21:25:58.738900+00:00",
            "last_updated": "2023-11-24T21:25:58.738900+00:00"
          }
        }
      ]

Kind Regards,

Zsolt

**Comment by make-all** [comment]
Based on #1140, there appear to be two versions of this device. One has the switches reversed, and is actually compatible with the Ditua DT-1522-YN config, as noted in DEVICES.md.

If you remove the device and add it again, are you offered the Ditua config as an option?  If so, then you have one of the more recent versions of this device, and should use the Ditua config.

**Comment by make-all** [comment]
Checked based on the data in the supplied diagnostics, and this device is 100% compatible with the Ditua config, and 70% compatible with the Asakuki config, so the issue here seems to be that the wrong config is used.

**Comment by AsztalosZs** [comment]
Thank you very much for your quick reply. The problem is solved with your suggestion.
Thank you.
