### ISSUE TITLE
VORK VK6067AW - Air Purifier Support

### ISSUE THREAD

**Issue by pgistrand** [make-all/tuya-local#135]
Tried to add VORK VK6067  Air Purifier without luck.

Please add to "New Device"

    "name": "Air Purifier",
    "model": "VK-6067AW",
    "category": "kj",
    "product_id": "trpege6ebn8at1el",
    "product_name": "Air Purifier",
    "functions": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_speed_enum",
        "dp_id": 4,
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"mid\",\"high\",\"auto\",\"sleep\"]}"
      },
      {
        "code": "light",
        "dp_id": 8,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "filter_reset",
        "dp_id": 11,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_set",
        "dp_id": 18,
        "type": "Enum",
        "values": "{\"range\":[\"cancel\",\"2h\",\"4h\"]}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_speed_enum",
        "dp_id": 4,
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"mid\",\"high\",\"auto\",\"sleep\"]}"
      },
      {
        "code": "filter",
        "dp_id": 5,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "light",
        "dp_id": 8,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "filter_reset",
        "dp_id": 11,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_set",
        "dp_id": 18,
        "type": "Enum",
        "values": "{\"range\":[\"cancel\",\"2h\",\"4h\"]}"
      },
      {
        "code": "countdown_left",
        "dp_id": 19,
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":480,\"scale\":0,\"step\":1}"
      },
      {
        "code": "air_quality",
        "dp_id": 21,
        "type": "Enum",
        "values": "{\"range\":[\"great\",\"good\",\"medium\",\"severe\"]}"
      },
      {
        "code": "fault",
        "dp_id": 22,
        "type": "Bitmap",
        "values": "{\"label\":[\"e1\",\"e2\"]}"
      }
[vork_vk6067AW_purifier.yaml.txt](https://github.com/make-all/tuya-local/files/8086953/vork_vk6067AW_purifier.yaml.txt)

**Comment by pgistrand** [comment]
After digging in the code and some trial and error I figured this one out.

Some typos in my yaml file and also removing dp_id: 22 (couldn't find the right type) solved my issues.

Attached file works.

[vork_vk6067AW_purifier.yaml.txt](https://github.com/make-all/tuya-local/files/8092225/vork_vk6067AW_purifier.yaml.txt)
.

**Comment by pgistrand** [comment]
After digging in the code and some trial and error I figured this one out.

Some typos in my yaml file and also removing dp_id: 22 (couldn't figure out the right type) solved my issues.

Attached file works
[vork_vk6067AW_purifier.yaml.txt](https://github.com/make-all/tuya-local/files/8092527/vork_vk6067AW_purifier.yaml.txt)
.

**Comment by make-all** [comment]
Tuya API Bitmap should usually map to bitfield in the yaml config (I came up with my type names before discovering the Tuya API documentation).

**Comment by pgistrand** [comment]
Thanks

Updated my yaml file with dpid 22 type bitfield. Tested and works fine
[vork_vk6067AW_purifier.yaml.txt](https://github.com/make-all/tuya-local/files/8117491/vork_vk6067AW_purifier.yaml.txt)

Feel free to make changes and add to your repository.

**Comment by make-all** [comment]
Support for this device is in 0.16.0
