### ISSUE TITLE
Request support for ChronoThermostat PLICK Smart NEVE X RFW

### ISSUE THREAD

**Issue by popokio** [make-all/tuya-local#1350]
Need help with this device yaml.
I've Tried to edit the YAML by myself without success but I think that I have already grabbed all the necessary infos from tinytuya wizard and HA logs.
I only replaced the id and keys with 0000 but all the other details are there.
Let me know if enough.
Thanks

FROM HA LOG
Device matches simple_switch with quality of 10%. DPS: {"updated_at": 1701123272.990376, "1": true, "2": "auto", "3": "off", "16": 50, "24": 200, "27": 0, "33": 0, "39": true, "42": 1, "102": 136}

FROM TINYTUYA WIZARD

{
            "id": "0000000000000",
            "ip": "192.168.1.44",
            "active": 2,
            "encrypt": true,
            "productKey": "0000000000000",
            "name": "Home ChronoThermostat PLICK",
            "key": "0000000000000",
            "mac": "00:00:00:00:00:00",
            "ability": 0,
            "token": "",
            "wf_cfg": "",
            "dev_type": "default",
            "err": "",
            "type": "default",
            "dps": {
                "dps": {
                    "1": true,
                    "2": "temporary",
                    "3": "off",
                    "16": 129,
                    "24": 222,
                    "27": 0,
                    "33": 1,
                    "39": true,
                    "42": 86,
                    "102": 33
                }
            },
            "origin": "broadcast",
            "ver": "3.3"
        }

  "name": “Home ChronoThermostat PLICK",
        "id": “00000000000000000",
        "key": “0000000000000000",
        "mac": “00:00:00:00:00:00",
        "uuid": “000000000000000000",
        "sn": “000000000000000000",
        "category": "wk",
        "product_name": "NEVE X RFW",
        "product_id": “00000000000000000000",
        "biz_type": 18,
        "model": "NEVE X RFW",
        "sub": false,
        "icon": "https://images.tuyaeu.com/smart/icon/ay1541463935213XqnXM/ea71fe7c0e1e171c00670f2c43a77ec1.png",
        "mapping": {
            "1": {
                "code": "switch",
                "type": "Boolean",
                "values": {}
            },
            "2": {
                "code": "mode",
                "type": "Enum",
                "values": {
                    "range": [
                        "auto",
                        "holiday",
                        "manual"
                    ]
                }
            },
            "3": {
                "code": "work_state",
                "type": "Enum",
                "values": {
                    "range": [
                        "cold"
                    ]
                }
            },
            "16": {
                "code": "temp_set",
                "type": "Integer",
                "values": {
                    "unit": "\u00b0C",
                    "min": 50,
                    "max": 350,
                    "scale": 1,
                    "step": 1
                }
            },
            "24": {
                "code": "temp_current",
                "type": "Integer",
                "values": {
                    "unit": "\u00b0C",
                    "min": 0,
                    "max": 400,
                    "scale": 1,
                    "step": 1
                }
            },
            "27": {
                "code": "temp_correction",
                "type": "Integer",
                "values": {
                    "unit": "",
                    "min": -30,
                    "max": 30,
                    "scale": 1,
                    "step": 5
                }
            },
            "32": {
                "code": "holiday_temp_set",
                "type": "Integer",
                "values": {
                    "unit": "\u00b0C",
                    "min": 50,
                    "max": 350,
                    "scale": 1,
                    "step": 1
                }
            },
            "33": {
                "code": "holiday_days_set",
                "type": "Integer",
                "values": {
                    "unit": "day",
                    "min": 0,
                    "max": 99,
                    "scale": 0,
                    "step": 1
                }
            },
            "39": {
                "code": "factory_reset",
                "type": "Boolean",
                "values": {}
            },
            "40": {
                "code": "child_lock",
                "type": "Boolean",
                "values": {}
            },
            "42": {
                "code": "countdown_left",
                "type": "Integer",
                "values": {
                    "unit": "min",
                    "min": 0,
                    "max": 1440,
                    "scale": 0,
                    "step": 1
                }
            },
            "45": {
                "code": "fault",
                "type": "Bitmap",
                "values": {
                    "label": [
                        "e1",
                        "e2",
                        "e3"
                    ]
                }
            }
        },
        "ip": "192.168.1.44",
        "version": "3.3"
    }

**Comment by make-all** [comment]
productid is useful information for this integration, as it is an id that is shared among all devices of this model.
Also, the QueryThingsDataModel result is preferred over other similar dps listings from the cloud API, as that one seems to match more closely the local protocol. Others can have different Enum ranges, and be missing some dps due to differences between the cloud protocol and local protocol that some devices have.

**Comment by popokio** [comment]
Sorry I’m quite new to HA and all this stuff.

I have retrieved infos from Tuya following your guide and this is the result
Hope now is enough
Please let me know.
Thanks


{"1":"Switch","2":"Mode","3":"Working status","16":"Set temperature","24":"Current temperature","27":"temperature calibration","32":"Holiday temperature","33":"holiday mode days setting","37":"week program","39":"Restore factory settings","40":"Child lock","42":"Remaining time","45":"Fault alarm","101":"temporary time","102":"总开机时间","103":"Antifreeze temperature","104":"fine temperature adjustment”}



{"startRowId":"","pageNo":1,"pageSize":10,"code":"32","startTime":1701024524643,"endTime":1701197324644,"projectCode":"p1692029789822ntfw4s","sourceId":"eu1594143644954oug6D","sourceType":"4","deviceId":"bf32091aa374e81887wjik","pageStartRow":"","region":"EU”}


{"startRowId":"","pageNo":1,"pageSize":10,"code":"1","startTime":1701024900779,"endTime":1701197700779,"projectCode":"p1692029789822ntfw4s","sourceId":"eu1594143644954oug6D","sourceType":"4","deviceId":"bf32091aa374e81887wjik","pageStartRow":"","region":"EU”}


{"startRowId":"","pageNo":1,"pageSize":10,"code":"33","startTime":1701024943429,"endTime":1701197743429,"projectCode":"p1692029789822ntfw4s","sourceId":"eu1594143644954oug6D","sourceType":"4","deviceId":"bf32091aa374e81887wjik","pageStartRow":"","region":"EU"}


{"startRowId":"","pageNo":1,"pageSize":10,"code":"2","startTime":1701032136057,"endTime":1701204936058,"projectCode":"p1692029789822ntfw4s","sourceId":"eu1594143644954oug6D","sourceType":"4","deviceId":"bf32091aa374e81887wjik","pageStartRow":"","region":"EU”}

{"startRowId":"","pageNo":1,"pageSize":10,"code":"3","startTime":1701032169157,"endTime":1701204969158,"projectCode":"p1692029789822ntfw4s","sourceId":"eu1594143644954oug6D","sourceType":"4","deviceId":"bf32091aa374e81887wjik","pageStartRow":"","region":"EU”}

{"startRowId":"","pageNo":1,"pageSize":10,"code":"37","startTime":1701032186856,"endTime":1701204986856,"projectCode":"p1692029789822ntfw4s","sourceId":"eu1594143644954oug6D","sourceType":"4","deviceId":"bf32091aa374e81887wjik","pageStartRow":"","region":"EU”}



{"startRowId":"","pageNo":1,"pageSize":10,"code":"101","startTime":1701032249405,"endTime":1701205049406,"projectCode":"p1692029789822ntfw4s","sourceId":"eu1594143644954oug6D","sourceType":"4","deviceId":"bf32091aa374e81887wjik","pageStartRow":"","region":"EU”}

{"startRowId":"","pageNo":1,"pageSize":10,"code":"102","startTime":1701032280104,"endTime":1701205080105,"projectCode":"p1692029789822ntfw4s","sourceId":"eu1594143644954oug6D","sourceType":"4","deviceId":"bf32091aa374e81887wjik","pageStartRow":"","region":"EU”}

{"startRowId":"","pageNo":1,"pageSize":10,"code":"39","startTime":1701032295537,"endTime":1701205095538,"projectCode":"p1692029789822ntfw4s","sourceId":"eu1594143644954oug6D","sourceType":"4","deviceId":"bf32091aa374e81887wjik","pageStartRow":"","region":"EU”}



{"startRowId":"","pageNo":1,"pageSize":10,"code":"103","startTime":1701032317087,"endTime":1701205117087,"projectCode":"p1692029789822ntfw4s","sourceId":"eu1594143644954oug6D","sourceType":"4","deviceId":"bf32091aa374e81887wjik","pageStartRow":"","region":"EU”}


{"startRowId":"","pageNo":1,"pageSize":10,"code":"40","startTime":1701032333820,"endTime":1701205133821,"projectCode":"p1692029789822ntfw4s","sourceId":"eu1594143644954oug6D","sourceType":"4","deviceId":"bf32091aa374e81887wjik","pageStartRow":"","region":"EU”}

{"startRowId":"","pageNo":1,"pageSize":10,"code":"104","startTime":1701032368886,"endTime":1701205168886,"projectCode":"p1692029789822ntfw4s","sourceId":"eu1594143644954oug6D","sourceType":"4","deviceId":"bf32091aa374e81887wjik","pageStartRow":"","region":"EU”}

{"startRowId":"","pageNo":1,"pageSize":10,"code":"42","startTime":1701032396369,"endTime":1701205196369,"projectCode":"p1692029789822ntfw4s","sourceId":"eu1594143644954oug6D","sourceType":"4","deviceId":"bf32091aa374e81887wjik","pageStartRow":"","region":"EU”}

{"startRowId":"","pageNo":1,"pageSize":10,"code":"45","startTime":1701032416236,"endTime":1701205216236,"projectCode":"p1692029789822ntfw4s","sourceId":"eu1594143644954oug6D","sourceType":"4","deviceId":"bf32091aa374e81887wjik","pageStartRow":"","region":"EU”}


"startRowId":"","pageNo":1,"pageSize":10,"code":"16","startTime":1701032571740,"endTime":1701205371740,"projectCode":"p1692029789822ntfw4s","sourceId":"eu1594143644954oug6D","sourceType":"4","deviceId":"bf32091aa374e81887wjik","pageStartRow":"","region":"EU”}

{"startRowId":"","pageNo":1,"pageSize":10,"code":"24","startTime":1701032600499,"endTime":1701205400499,"projectCode":"p1692029789822ntfw4s","sourceId":"eu1594143644954oug6D","sourceType":"4","deviceId":"bf32091aa374e81887wjik","pageStartRow":"","region":"EU”}

{"startRowId":"","pageNo":1,"pageSize":10,"code":"27","startTime":1701032659716,"endTime":1701205459716,"projectCode":"p1692029789822ntfw4s","sourceId":"eu1594143644954oug6D","sourceType":"4","deviceId":"bf32091aa374e81887wjik","pageStartRow":"","region":"EU”}

**Comment by make-all** [comment]
Product ID was in your original post, but replaced with "00000000" like the sensitive values such as device id and local key.  This was what I was wanting.

**Comment by popokio** [comment]
"id": "bf32091aa374e81887wjik",
            "local_key": ")Y'Zj?vB|<Pkwb]Q",
            "model": "NEVE X RFW",
            "product_id": "qgmh0aak7xcmrlf3",
            "product_name": "NEVE X RFW"

Sorry, hope now is fine
