### ISSUE TITLE
New Device: Lidl Smart Charger - Parkside PLGS 2012 A1

### ISSUE THREAD

**Issue by pgistrand** [make-all/tuya-local#136]
All functions and sensors are not reported by Tuya IoPlatform - more DPID's below

        "category": "zncdq",
        "product_id": "h6pglenun37dzsgo",
        "product_name": "Lidl Smart charger", 

    "functions": [
      {
        "code": "charge_switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "charge_current",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":100}"
      },
      {
        "code": "charge_voltage",
        "dp_id": 4,
        "type": "Integer",
        "values": "{\"unit\":\"mV\",\"min\":0,\"max\":25000,\"scale\":1,\"step\":100}"
      },
      {
        "code": "storage_switch",
        "dp_id": 8,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "upper_temp_switch",
        "dp_id": 9,
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "charge_switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "charge_current",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":100}"
      },
      {
        "code": "charge_voltage",
        "dp_id": 4,
        "type": "Integer",
        "values": "{\"unit\":\"mV\",\"min\":0,\"max\":25000,\"scale\":1,\"step\":100}"
      },
      {
        "code": "battery_percentage",
        "dp_id": 5,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_current",
        "dp_id": 6,
        "type": "Integer",
        "values": "{\"unit\":\"?\",\"min\":-25,\"max\":85,\"scale\":0,\"step\":1}"
      },
      {
        "code": "storage_switch",
        "dp_id": 8,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "upper_temp_switch",
        "dp_id": 9,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "maxtemp_times",
        "dp_id": 10,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":65535,\"scale\":0,\"step\":1}"
      }
    ]

ID	Description
1	Charge Start Switch	 - Boolean - Switch
2	Name	- String -	Sensor
3	Charge Current (mA) - Int - Sensor
4	Battery Voltage (/1000) - Int - Sensor
5	Battery percentage (%)	- Int  - Sensor
6	Temperature	- Int  - Sensor
7	Charge Type	ECO, quick (Performance), standard (Balance), individual (Expert)	- Sensor
8	Storage (60%) - Boolean - Switch
9	upper_temp_switch	 - Boolean - Switch
10    maxtemp_times - 	- Int  - Sensor
11    ?
101	Max charge current (mA) - Int - Sensor
102	Time to Full (in minutes) - Int - Sensor
103	10 minutes to full charge notification - Boolean - Switch
104	Fully charged notification- Boolean - Switch

**Comment by make-all** [comment]
Support for this device is in 0.16.0

**Comment by spcqike** [comment]
Does anyone know what error 32 on ID11 is for? 

I tried to build smart solar overproduction charging, with node red. Every now and than I get error 32, toys apps says „Drahtbruchschutz“ and I either need to pull and reinsert the battery or unplug everything and start it again. 

Is there some list or explanation of what errors there are and why they occur?
