### ISSUE TITLE
C16 device state in HA

### ISSUE THREAD

**Issue by SamJongenelen** [make-all/tuya-local#137]
Im using [a C16 device](https://github.com/make-all/tuya-local/blob/main/custom_components/tuya_local/devices/saswell_c16_thermostat.yaml) and it is communicating nicely. 
However, I noticed the device _state_  is incorrect in Homeassistant; Its unavailable. 

Could you help fix this?

When the device is idle:
![image](https://user-images.githubusercontent.com/3382443/154507177-0aef72ac-ef57-428e-b2fb-a2bea1629a83.png)

![image](https://user-images.githubusercontent.com/3382443/154506476-0257d35e-844d-4f8d-aacf-e984241a4636.png)

![image](https://user-images.githubusercontent.com/3382443/154506726-98301556-935a-46ed-80cc-0f2897871c84.png)

**Comment by make-all** [comment]
Are there any errors in the log?  The state should follow dp 9, which is boolean: false for "heat", true for "cool".  But if dp 9 is not a boolean, or not present, it could cause such a problem.

**Comment by SamJongenelen** [comment]
No errors indeed. The `idle\heating` data from the hvac_action looks correct though

**Comment by make-all** [comment]
I think this may be fixed in 0.21.0 (2022.12.0), after the change made to remember old state if the device decides to stop sending it in updates.

**Comment by SamJongenelen** [comment]
Can confirm this is resolved
