### ISSUE TITLE
Unable to add Lytmi Neo 2.0b (Screen sync smart light) as HDMI sync light

### ISSUE THREAD

**Issue by beyondgrave** [make-all/tuya-local#1371]
**Describe the bug**
I'm trying to add a Lytmi Neo 2.0b, but the only options that pop-up in drop down are related to lightbulbs or strip leds. I was expecting it to be similar to adding Lytmi Neo Fantasy 3 (which I also have on a different TV). 

**To Reproduce**
Add Lymi Neo 2.0b using device ID and localkey. Drop down does not include "HDMI sync light"

**Expected behavior**
Drop down should include "HDMI sync light" as device option.

**Additional context**
Works fine with my Lytmi Neo Fantasy 3.0. It's detected as HDMI sync light. With Lytmi Neo 2.0b, the closest device type that works is rgbcw_lightbulb. That allows on/off, brightness. I also tried rgb_led_strip and only on/off worked.  
Thought this would be fixed with #264 but maybe something changed after #790

![image](https://github.com/make-all/tuya-local/assets/59484158/51d0b156-f823-473d-81e5-5344ecc69aae)

**Comment by make-all** [comment]
Tuya devices not following any standard is not a bug with this integration.
