### ISSUE TITLE
New Device (Power Strip) LOGICOM Strippy with 4 Socket+4 USB

### ISSUE THREAD

**Issue by novisys** [make-all/tuya-local#138]
Hi,
I buyed a new device branded under the name of LOGICOM Strippy this one come with with 4 Socket+4 USB (is TUYA/SmartLife compatible)
I added this one using the tuya-local integration and just one socket was detected
can you please help add this one to get the 4 socket + USB one ?
Thanks

**Comment by novisys** [comment]
Device matches simple_switch_timer with quality of 20%. DPS: {'1': False, '2': False, '3': False, '4': False, '5': False, '9': 0, '10': 0, '11': 0, '12': 0, '13': 0, 'updated_at': 1645301202.2416973}

**Comment by make-all** [comment]
It looks like 4 switches for the outlets, and a single switch for all the USBs, is that correct? And independant timers for each of the switches?

**Comment by novisys** [comment]
Yes its  100% correct !

**Comment by novisys** [comment]
i tried with this but now i can't configure my device !
`name: Simple 4x Strip With Timer
primary_entities:
  - entity: switch
    class: outlet
    dps:
      - id: 1
        name: switch01
        type: boolean
  - entity: switch
    class: outlet
    dps:
      - id: 2
        name: switch02
        type: boolean
  - entity: switch
    class: outlet
    dps:
      - id: 3
        name: switch03
        type: boolean
  - entity: switch
    class: outlet
    dps:
      - id: 4
        name: switch04
        type: boolean
  - entity: switch
    class: outlet
    dps:
      - id: 5
        name: switch05
        type: boolean

secondary_entities:
  - entity: number
    category: config
    name: Timer
    icon: "mdi:timer"
    dps:
      - id: 9
        name: value
        type: integer
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: number
    category: config
    name: Timer
    icon: "mdi:timer"
    dps:
      - id: 10
        name: value
        type: integer
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: number
    category: config
    name: Timer
    icon: "mdi:timer"
    dps:
      - id: 11
        name: value
        type: integer
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: number
    category: config
    name: Timer
    icon: "mdi:timer"
    dps:
      - id: 12
        name: value
        type: integer
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: number
    category: config
    name: Timer
    icon: "mdi:timer"
    dps:
      - id: 13
        name: value
        type: integer
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
`

**Comment by novisys** [comment]
Now i get systematically this error !
![Uploading 9AF73D33-9610-482B-B13C-892E3CFC4AEA.jpeg…]()

**Comment by make-all** [comment]
- There can only be one primary_entity.
- Names need to be unique, so you need to give names to your entities (you can have one of each type unnamed)
- Choose names that are already in translations/en.json if possible.  I think Switch 1, Switch 2, Switch 2, Switch 4, Switch USB and Timer 1, ... are already defined.
- watch your indentation.  It may be just github's formatting, but min and max should be indented under range:.

**Comment by novisys** [comment]
Now i get systematically this error !

![](https://zupimages.net/up/22/07/5yu5.jpeg)

**Comment by pgistrand** [comment]
Goto: Configuration  -> Add-ons, Backups & Supervisor -> System tab... Choose Core as logprovider and watch the log to get some indications on what might have gone wrong.

**Comment by make-all** [comment]
Support for this device is in 0.16.0
