### ISSUE TITLE
Request support for BLACK+DECKER BXEH60016GB Smart Dehumidifier

### ISSUE THREAD

**Issue by neilmartin83** [make-all/tuya-local#1384]
# Log Message

```
N/A
```

# Information about DPS mappings

```
{"1":"POWER","2":"Dehumidity","4":"TARGET HUMIDITY","6":"Fan Speed","7":"LOCK","11":"FAULT","12":"TIMER","101":"Timer","102":"SLEEP","103":"temp","104":"humidity","105":"DEFROST"}
```

# Product ID

q8v8m3uiiq9krvwv

# Information about how the device functions

This device is identical in functionality to the breville_lad208_dehumidifier configuration already supported here but the following DPs are not implemented (I currently hide the entities they create). I think the same configuration could be copied but with the new Product ID above and DPs below removed:

7: "LOCK"
102: "SLEEP"

Thank you! :-)

**Comment by make-all** [comment]
There isn't enough info here, and if it works fine with another config and the missing dps are already marked as optional there, I wouldn't make a separate config anyway.
