### ISSUE TITLE
Support Fairland Inver-X heatpump

### ISSUE THREAD

**Issue by jrossey** [make-all/tuya-local#139]
It seems my Fairland Inver-X heatpump is not supported. When adding the device (correct ip, device ID and local key), I can only select simple_switch as type of device. Can I help with adding support for this heatpump?
![image](https://user-images.githubusercontent.com/1841872/154859912-ea6f6f5b-47c4-42d6-84e7-711d2544a4f8.png)

**Comment by make-all** [comment]
Please check the Home Assistant log for messages from tuya-local integration.  There should be a message from when got the above dialog telling the data your heatpump is returning.  Hopefully it is similar enough to another heatpump that we can make educated guesses as to the format.

**Comment by jrossey** [comment]
Below is the output from the logs:

`This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:73
Integration: tuya_local (documentation, issues)
First occurred: 2:56:12 PM (1 occurrences)
Last logged: 2:56:12 PM

Device matches simple_switch with quality of 9%. DPS: {'1': False, '2': 'silence', '102': 11, '103': True, '104': 0, '105': 'warm', '106': 30, '107': 18, '108': 40, '115': 0, '116': 0, 'updated_at': 1645538171.5828362}`

**Comment by make-all** [comment]
This device seems identical to the IPS Inverter pool heatpump, for which a pull request was submitted today (#150)

**Comment by make-all** [comment]
I'll leave this open to track to release, since there isn't an accompanying issue for the pull request above.

**Comment by make-all** [comment]
Support for the IPS Pro pool heatpump, which seems the same as this model is in 0.16.0

**Comment by chris-garbas** [comment]
maybe we should name it more general than ips pro ... 👍

**Comment by make-all** [comment]
It's difficult to come up with a more general name that is not misleadingly too general.  
I documented in the README that IPS Pro config should work also for Fairland Inver-X, which is the same solution used for some other devices that seem very close.  Only when there seems to be a lot of different models using a standard template from Tuya like with smart switches have I renamed configs to be general.

**Comment by chris-garbas** [comment]
👍👍

i would be fine with changing the name to the original manufacturer anyway, it’s up to you.

BTW: it was to cold at my location to test all features. Maybe I come up with another PR later to support the cooling mode and some other stuff

**Comment by jrossey** [comment]
Thank you! I succesfully added my Fairland Inver-X!
