### ISSUE TITLE
Invergo - Inverter Pool Heater not fully compatible

### ISSUE THREAD

**Issue by mikkaat** [make-all/tuya-local#14]
Hi, 
First thanks for great job on this integration. It is easy to setup and for the most part works as required.

I have a pool heat inverter heatpump which is compatible with Tuya (runs on the InverGo app). I have successfully extracted the ID and Key from the https://iot.tuya.com/ site and can also see this information when i interact with the tuya-cli wizard command.

When i configure the inverter on the Tuya Local (Home Assistant) integration, i can set either Auto or gardenpac_heatpump which produces the exact same results. I can see the device status, the current water temperature and the target set temperature, but cannot see a switch so that i can turn the device on or off.
By mostly I mean it does somewhat work with any heater config selected - you see on/off status and you are able to turn on/off the device.

You worked with Xeovar in issue 11 to successfuly resolve the issue for him and produce the gardenpac_heatpump option. I have tuya-cli installed, but just need some guidance on how i can extract the dps, ie what the command line should be, as when i enter it as  follows )where the ######## are the actual numbers provided in the wizard):
tuya-cli get --id ########## --key ########## --ip 10.0.20.170
No response is produced, and no error is produced either.

**Comment by make-all** [comment]
This is what works for me:

```bash
tuya-cli get --id ##### --key ##### -a 
```

tuya-cli is generally able to automatically find the IP address, but if it doesn't you can add the `--ip 10.0.20.170` back. I think your command is just missing the `-a` (fetch all), without which you need to specify a dps id to fetch.

Climate devices do not present a separate switch entity, there is a mode, which is set to HEAT when on, and OFF when off, and which shows up in lovelace in the bottom middle of the temperature dial, with two icons below - a fire icon for HEAT, and a power icon for OFF, which are clickable to set the mode.

**Comment by mikkaat** [comment]
@make-all - Thank you... This ended up being a user issue (my stupidity), I was not aware of the button once added to lovelace, I should have tried that first. I can confirm it is working perfectly. Apologies for wasting your time.

**Comment by mikkaat** [comment]
@make-all just one last question if i could please...

![image](https://user-images.githubusercontent.com/12488156/117376980-9130ca80-af15-11eb-9d06-3cce090b5cb0.png)

Is the power button meant to send an ON/HEAT command as well as an OFF command, as I can only trigger an OFF command from this button. In order for me to activate the unit, i need to use the three dots at the top right of the card to get to the details view and then select HEAT from the Operation dropdown.
![image](https://user-images.githubusercontent.com/12488156/117377123-dbb24700-af15-11eb-84e1-948875e6c781.png)

**Comment by make-all** [comment]
The Power icon only works as an OFF button. The Heat icon to it's left should work as an ON button.

**Comment by mikkaat** [comment]
> The Power icon only works as an OFF button. The Heat icon to it's left should work as an ON button

Thank you
