### ISSUE TITLE
EV charger won't change Current.

### ISSUE THREAD

**Issue by Striiter** [make-all/tuya-local#1402]
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**
The device wont accept change of "set charging current"

**To Reproduce**
Steps to reproduce the behavior including the device the issue was observed with:
Once device is added it wont change the current. It will change according to a change in the Smart Life app, but will not change in Home Assistant.

**Expected behavior**
If the charger is set to 10A, and i want to set it to 8A, it sets it at 8A but changes back to 10A again. It never changes in real life, only when its changed in the Tuya IoT Platform or in the Smart Life app

**Additional context**

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

No messages in log when changing Set Charge Current.
[tuya_local-1d044c51e5b616659a606441dfc9e5df-EV charger-f84d367d8884cea7bff1060a215c832b.json.txt](https://github.com/make-all/tuya-local/files/13637677/tuya_local-1d044c51e5b616659a606441dfc9e5df-EV.charger-f84d367d8884cea7bff1060a215c832b.json.txt)
[Tuya IoT Standard Status Set.txt](https://github.com/make-all/tuya-local/files/13637720/Tuya.IoT.Standard.Status.Set.txt)

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.
![billede](https://github.com/make-all/tuya-local/assets/127613636/acf88ad1-41de-45bf-8453-26822dda19ed)
![billede](https://github.com/make-all/tuya-local/assets/127613636/2ac6bc7d-229e-4225-ba0e-657ce74a06c6)
![billede](https://github.com/make-all/tuya-local/assets/127613636/1830efaa-0511-458b-955e-921bf3ab8a3f)
![billede](https://github.com/make-all/tuya-local/assets/127613636/492f1aaa-83e9-4549-a73f-0c9d7912fff5)

No device logs in Tuya IoT indicating Home Assistant is trying to change charging speed.

Screen recording on phone: https://youtu.be/4VBJ8QNqlUk

**Comment by make-all** [comment]
I think this issue requires debug logs to figure out what is going on.  You can enable debugging in the device settings, when you disable it again, the log will be automatically downloaded.  You may wish to review and filter the log before attaching, as it will be the complete log from when you last restarted HA (I will only need the tuya-local related lines, and only for the period that debugging was enabled).

**Comment by Striiter** [comment]
@make-all Thank you for reviewing. I've included the log here: https://github.com/make-all/tuya-local/files/13637677/tuya_local-1d044c51e5b616659a606441dfc9e5df-EV.charger-f84d367d8884cea7bff1060a215c832b.json.txt

However - there is no entry regarding changing charge current, when debug is enabled, charge current is set (multiple times) debug is disabled and downloaded.

**Comment by make-all** [comment]
This is the diagnostics, which is just a snapshot of the current state of the dps.  I need the debug log, that will show the flow of setting the charge current and then the communication back from the device.
