### ISSUE TITLE
Any chance to merge this project with github.com/rospogrigio/localtuya?

### ISSUE THREAD

**Issue by rafenden** [make-all/tuya-local#141]
Why double the efforts?

Ticket on the `rospogrigio/localtuya` project:
https://github.com/rospogrigio/localtuya/issues/758

**Comment by make-all** [comment]
When I started this, localtuya seemed focused on simple devices like switches, lights and sensors, and this was focused more on climate devices.  They have both grown, but the basic philosophy behind them is also different - localtuya seems to offer a configurable framework on which users can configure their own devices, but that takes some technical knowledge, this one is more aimed at building up a database of devices that can be detected and just work.

Merging them would quite frankly be more effort than just maintaining two separate integrations for people to choose from.
I have considered changing the name of this one to be less confusing however.

**Comment by CloCkWeRX** [comment]
Oh, I just stumbled across this, nice!

A lot of localtuya users aren't certain about configuration; I could certainly see a use case for ingesting the .yaml content from here, and at the very least displaying it when configuration is done.

As a very small improvement; I might propose some links in the other project's README, directing users here for some reference configuration / to contribute?
