### ISSUE TITLE
Request support for [support for Tuya_Web_Stats queries for energy monitor devices]

### ISSUE THREAD

**Issue by Mannokia** [make-all/tuya-local#1417]
Hello.
Is it possible to do something so that this integration can issue WEB Tuya requests?
```
($stats = Tuya_Web_Stats('478803312cf43204ab22', 17);
sg('object.property', $stats["years"][(int) date('Y')][date('m')]);)
```

This is seen in the MAJORDOMO system, in the TUYA integration.

Using this query, you can get the total consumption, daily consumption and monthly consumption values ​​from the cloud.

**Comment by make-all** [comment]
Currently cloud features are out of scope

**Comment by make-all** [comment]
Also, I think this is a duplication of features already available in the Energy dashboard in Home Assistant, so I do not think it is useful to add this feature.

**Comment by Mannokia** [comment]
> Also, I think this is a duplication of features already available in the Energy dashboard in Home Assistant, so I do not think it is useful to add this feature.

The fact of the matter is that I personally would like to use this function to take data for the Energy dashboard. Because I can’t seem to collect data without error. On some days there is no error at all, while on other days the error reaches 40 kWh.

**Comment by make-all** [comment]
Use the power sensor with an integration helper.  The energy sensor on most Tuya smartplugs is useless.
