### ISSUE TITLE
Himox H05 support (see comments further down)

### ISSUE THREAD

**Issue by gschmidl** [make-all/tuya-local#142]
I have a Himox H06 and it's only detected as a simple_switch - anything I can do about this?

(I also have a H05 that is detected correctly in localtuya - does it make any sense to try to set it up in tuya-local?)

I've removed the integration from localtuya before setting it up in tuya-local.

**Comment by gschmidl** [comment]
Additional information - my H06 payload looks like this:
```
    "1": True,
    "4": "high",
    "5": 92,
    "8": True,
    "11": False,
    "18": "cancel",
    "19": 0,
    "22": "severe",
    "101": 2,
```

**Comment by make-all** [comment]
Himox H06 support was added to the source recently. It is not yet in a release.  To try it if using HACS, you need to select "Redownload" from the tuya-local menu inside the HACS Integrations screen, and select "main" as the version to install.

Himox H13 is not yet supported.  As long as you do not have the same device configured in both, localtuya and tuya-local can co-exist side by side.

**Comment by gschmidl** [comment]
I blithely assumed its presence in the documentation meant it was already released. Apologies and thanks for the help!

**Comment by make-all** [comment]
The documentation you see on github is taken from main.  I have not made a release for some time because there are major changes in the next release (vacuum and RGBW lighting support) which still need some debugging. And also I have not had time for the past month due to other life events.

**Comment by gschmidl** [comment]
Understood. If there's anything I can do to help add support for the H13 - if you're interested - please let me know. No hurry, of course.

**Comment by make-all** [comment]
It seems to me like the dps that match have the same meaning.  dp 2 is new, and looks like it is in the right range to be a current temperature sensor.  dp 21 looks like it may have just moved from dp 22 (air quality indicator).  dp 7 is a new switch or indication, or maybe it has also simply moved from dp 8.   I guess figuring out those three (and whether my speculation about them having simply moved is correct) is all that is needed.

**Comment by gschmidl** [comment]
I went back and checked and it's the H05, not H13 - I've updated the comments.

The H05 does not have a light on/off switch but it does have a child lock.
The other buttons are a timer (1/2/4/8h), on/off, reset filter, and speed (night/low/high/auto).

**Comment by make-all** [comment]
Reopening for the H05

**Comment by make-all** [comment]
Support for H05 is in 0.16.0

**Comment by gschmidl** [comment]
Tried this out and it connects and turns on and off, but I think it's not 100% right:

Temperature displays at 108°C
Timer offers 1/2/4/8 hours on the device, but only 4 and 8 in the config.

Thanks for adding it!

**Comment by make-all** [comment]
The timer values were copied straight from H06, which does apparently only support 4 and 8 hours.  As for the temperature, it is strange, as there are no transformations applied to it, and the value you first posted was 21, which looks like a reasonable temperature.  Unless the original was when it was 4 degrees and there is actually a 5x multiplier on that...

**Comment by gschmidl** [comment]
No, it was approximately the same temperature then. But it's also not changed by even 0.1° since I commented:

![image](https://user-images.githubusercontent.com/20334/161445067-c64d5cf4-d7d3-464b-af48-c5968d7bc66e.png)

**Comment by make-all** [comment]
Are you sure the entity is correctly configured in the UI?  As there is no transformation on the temperature value, I cannot see how this could go wrong like this.

**Comment by make-all** [comment]
Closing due to no feedback
