### ISSUE TITLE
Device Support Request: Kogan Garage Door Opener

### ISSUE THREAD

**Issue by markbvdh** [make-all/tuya-local#143]
Hi, this device has 4 DPs (101, 102, 104, 105).  Device type: mc

101 - 'fopen', 'fclose' (open / close)
102 - 'opened', 'openning', 'closing', 'closed' (4 states of its wireless tilt sensor....'openning' is spelt incorrectly!)
104 - 100 (Battery power level of tilt sensor)
105 - True (Timed open warning?)

(Setting DP101 as a 'switch' doesn't work with the Rosprogrigio local Tuya integration).

Cheers

{Also: I can confirm the pool heatpump integration works nicely with the Summerwave Si Series heatpumps sold in Australia with the optional wifi module.  Thanks for your work!}

**Comment by make-all** [comment]
Do you know which config the pool heatpump was detected as?

**Comment by markbvdh** [comment]
This is developer tools report when added as Gardenpac
![Screen Shot 2022-03-09](https://user-images.githubusercontent.com/98468488/157430339-ebeaf3ec-1bd6-4641-8f45-1f3d9ffd0afd.png)

**Comment by markbvdh** [comment]
Thanks Jason, control works as expected.  Only issue s it's slow to report the status (DP102) - seems fine/instant on the tuya cloud.

**Comment by make-all** [comment]
This is now released in 0.16.0
