### ISSUE TITLE
InkBird IBBQ-4T V2

### ISSUE THREAD

**Issue by TurboTronix** [make-all/tuya-local#1434]
So my IBBQ-4T device gets identified as "inkbird_bbq4t_thermometerv2.yaml" but this is what I get in my temps:

![image](https://github.com/rospogrigio/localtuya/assets/7071554/4d02448c-46cc-4ba7-b3c3-7321db2cd5a8)

Actual temps on the device are (in F):
Probe1: 76
Probe2: 77
Probe3: 78
Probe4: 77

In Tuya loT under debug I get the following for DP107: **xB0AAfYdAAFQHgAB9h0AAQ==**

Device Details:
```
{
  "result": [
    {
      "active_time": 1703080310,
      "category": "wk",
      "create_time": 1703080310,
      "custom_name": "",
      "icon": "smart/icon/ay15117410451057cPZi/0dd6cd05c1014f682a4e68fc1ab16.png",
      "id": "##########################",
      "ip": "############",
      "is_online": true,
      "lat": "############",
      "local_key": "#################",
      "lon": "###########",
      "model": "IBBQ-4T  V2.x",
      "name": "IBBQ-4T",
      "product_id": "wavwesi8clrfwx68",
      "product_name": "IBBQ-4T",
      "sub": false,
      "time_zone": "####",
      "update_time": 1703090359,
      "uuid": "######"
    }
  ],
  "success": true,
  "t": #####,
  "tid": "######"
}
```

**Comment by make-all** [comment]
Bug reports need to come with logs or diagnostics.  Simply describing your issue like this does not give enough info and leaves me guessing whether the obvious problem in the base64 encoding is a typo on your part or a bug in your device's firmware.

**Comment by TurboTronix** [comment]
From what I see in the log under Tuya loT:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ronli/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ronli/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


12/20/2023   17:41 | Report | 探头温度1 | 4h0AAeIdAAGWHgAB4h0AAQ== | device itself |  
-- | -- | -- | -- | -- | --
12/20/2023   17:41 | Report | 探头温度1 | 4h0AAOIdAACCHgAA4h0AAA== | device itself |  
12/20/2023   17:40 | Report | 探头温度1 | 4h0AAeIdAAFuHgAB4h0AAQ== | device itself |  
12/20/2023   17:40 | Report | 探头温度1 | 4h0AAOIdAABuHgAA9h0AAA== | device itself |  
12/20/2023   17:38 | Report | 探头温度1 | 4h0AAfYdAAFuHgAB9h0AAQ== | device itself |  
12/20/2023   17:38 | Report | 探头温度1 | 4h0AABQeAABuHgAAFB4AAA== | device itself |  
12/20/2023   17:38 | Report | 探头温度1 | 4h0AAfYdAAFuHgABAB4AAQ== | device itself |  
12/20/2023   17:38 | Report | 探头温度1 | zh0AAPYdAABuHgAAAB4AAA== | device itself |  



</body>

</html>
