### ISSUE TITLE
IBBQ-4T V2

### ISSUE THREAD

**Issue by TurboTronix** [make-all/tuya-local#1439]
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**

- Only probe 1 shows it's temperature. All other probes don't show up

**To Reproduce**
Steps to reproduce the behavior including the device the issue was observed with:

Step 1: use the following device
```
      "model": "IBBQ-4T  V2.x",
      "name": "IBBQ-4T",
      "product_id": "wavwesi8clrfwx68",
```
Step 2: this will use the following yaml: 
inkbird_bbq4t_thermometerv2.yaml

**Expected behavior**
The code in inkbird_bbq4t_thermometerv2.yaml needs to be modified for probe 2-3-4 (change type to **base64**):

```
- entity: sensor
    name: Temperature probe 2
    class: temperature
    dps:
      - id: 107
        type: base64

```

**Additional context**
I also noted that probe 1 and 3 don't give the accurate temps, I can't figure out why. I've tried several things but can't pin point the reason.

The following picture shows that Probe 1 and Probe 3 seem to give the same faulty value of -16.36 (they seem to be the same value as well, not 2 diff values but a duplication of the same value). However these temps should be similar to those given by Probe 1 and Probe 4. 

![image](https://github.com/make-all/tuya-local/assets/7071554/42085049-b76a-48d6-be12-407b970ef370)

Debug log: 
[tuya_local-d64ae89f06e1f8c04fc2f9ccc6c9fb9b-BBQ thermometer-ad5f5d681fb06a690e5c35076defe4da.json.txt](https://github.com/make-all/tuya-local/files/13752888/tuya_local-d64ae89f06e1f8c04fc2f9ccc6c9fb9b-BBQ.thermometer-ad5f5d681fb06a690e5c35076defe4da.json.txt)

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

**Comment by make-all** [comment]
Thanks for pointing out the incorrect types.  The temperatures seem to be encoded as 3 bytes per probe, with another 1 byte of flags.  The previous masks were based on 2 bytes per probe, so the odd numbered probes were actually picking up the leading byte and the flags, and probes 2 and 4 were showing the temperatures of probes 1 and 2 (or maybe 3 and 4).

Do you think you can do some experimenting to check if the probes are ordered correctly?

Also, the "preset temperature" settings are also currently masked to 2 bytes per probe, but that dp seems to have 28 bytes in total.  I am not sure whether it is 7 bytes per probe, or some smaller number per probe, with some more general settings in there as well.  Currently the only capture of that DP is in a comment in the original issue that has all 28 bytes set to 0, so some experimenting with those presets from the app and capturing the base64 values will help try to figure them out.

**Comment by TurboTronix** [comment]
OK will do some testing this coming weekend to see if I can help out.

**Comment by TurboTronix** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ronli/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ronli/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


  | DP | Hassio | IBBQ-4T (in Celcius)
-- | -- | -- | --
  | Base64 from log | P1 | P2 | P3 | P4
Probe 1 in hot water | DP107 | UEYAAKIcAAAqHAAANBwAAA== | 82 | 23 | 22 | 22
Probe 2 in hot   water | DP107 | GiIAAP5CAAAqHAAANBwAAA== | 31 | 78 | 22 | 22
Probe 3 in hot   water | DP107 | PB4AAE4gAAB0QAAA5BsAAA== | 26 | 28 | 74 | 22
Probe 4 in   hot water | DP107 | ehwAAN4cAABKHwAABD0AAA== | 23 | 23 | 27 | 69
  |   |   |   |   |   |  
P1 Temp Preset | DP112 |   |   |   |   |  
P2 Temp Preset | DP113 |   |   |   |   |  
P3 Temp Preset | DP114 |   |   |   |   |  
P4 Temp   Preset | DP115 |   |   |   |   |  



</body>

</html>

**Comment by TurboTronix** [comment]
I can't seem to change the presets, in my Tuya dev these inputs are missing and in Hassio they are not properly connected.

These are the only things I can control from Tuya dev:
![image](https://github.com/make-all/tuya-local/assets/7071554/cf639094-d287-4985-bc93-26e00e9b465e)

**Comment by TurboTronix** [comment]
Another unrelated issue is the temp unit changing from F to C and vise versa does not work. In your code you use DP19 which is Temperature Scale. But in Tuya loT I noticed it uses the following when I send a command:

1
: 
{code: "temp_unit_convert", value: "f"}
code
: 
"temp_unit_convert"
value
: 
"f"

**Comment by TurboTronix** [comment]
I am still trying to decypher this...can't figure it out.

![image](https://github.com/make-all/tuya-local/assets/7071554/0a915ddf-31a2-4f84-9133-2a6f7a580a45)
[probe_debug.xlsx](https://github.com/make-all/tuya-local/files/13779836/probe_debug.xlsx)

**Comment by make-all** [comment]
The readings are in Fahrenheit.  You need to break down the HEX into groups of 4, then because it is little endian reverse the bytes in each (not every hex digit, as two hex digits make up a byte):

- 50460000 becomes 00004650 Which in decimal is 18000 = 180.00 degrees

So the order is correct - left to right in blocks of 4 (not reversing the whole string, which would result in a 4 to 1 probe order).

**Comment by TurboTronix** [comment]
I tried that but the other 3 probes don't match. the first one is indeed 180 F which matches but the rest give all over the place numbers.

**Comment by make-all** [comment]
From the latest config and the values above, I'm getting

**Probe 1 in hot water**

 sensor_temperature_probe_1: 180.0
  sensor_temperature_probe_2: 73.3
  sensor_temperature_probe_3: 72.1
  sensor_temperature_probe_4: 72.2

**Probe 2 in hot water**
  sensor_temperature_probe_1: 87.3
  sensor_temperature_probe_2: 171.5
  sensor_temperature_probe_3: 72.1
  sensor_temperature_probe_4: 72.2

**Probe 3 in hot water**
  sensor_temperature_probe_1: 77.4
  sensor_temperature_probe_2: 82.7
  sensor_temperature_probe_3: 165.0
  sensor_temperature_probe_4: 71.4

**Probe 4 in hot water**
  sensor_temperature_probe_1: 72.9
  sensor_temperature_probe_2: 73.9
  sensor_temperature_probe_3: 80.1
  sensor_temperature_probe_4: 156.2

These seem to have a small offset from the values you quoted, but are not wildly out of the expected range.

**Comment by TurboTronix** [comment]
Ok nevermind, noticed last release was 3 weeks ago. It's no rush, I will keep monitoring for updates. Thanks for your hard work!
