### ISSUE TITLE
Include compatibility with alarm PG107, which allows triggering from home assistant

### ISSUE THREAD

**Issue by reprogerman** [make-all/tuya-local#1440]
Well, as the title says, let's see if it is possible to add compatibility with the pg107 alarm, I currently use the classification of the pg103, I do not know the latter's functions, but I currently use the pg107 and it has the function of triggering a shot through a call service, which is very useful to use as an alarm for anything such as shooting at the presence of a person in frigate cameras

**Comment by make-all** [comment]
There is absolutely nothing in this report to action.
