### ISSUE TITLE
Loratap Cover unknow and bouton hide

### ISSUE THREAD

**Issue by msaphoto06** [make-all/tuya-local#1442]
Good morning,

My loratap shutters appear in unknown without buttons.
the model is tuh2eatk4hsq336s.
It's a 1,2,3 model.
It is not important to me whether the shutter is open or closed. I just want to be able to initiate actions.
These are the only elements out of 14 that I cannot switch from localtuya to tuya local.

THANKS

**Comment by make-all** [comment]
This would seem to be a bug with the cover UI card.  It is valid for the state to be Unknown, that should not be causing the buttons to be disabled.

**Comment by make-all** [comment]
What is the state of the localtuya implementation when the curtain is stopped?

**Comment by msaphoto06** [comment]
![Capture d’écran 2023-12-23 081254](https://github.com/make-all/tuya-local/assets/79517010/cd7f66d5-8f50-44b6-8d88-bf7818022ea5)
I didn't understand your question very well.

**Comment by msaphoto06** [comment]
After another test this morning,
the entity does not appear in the services either and does not follow the movement initiated by the tuya application:
if I go to service / cover.close_cover, my entity created by tuya-local does not appear in the choices, I only see the one created with localtuya.
When I open the pane with the application, it remains unknown in tuya-local

**Comment by msaphoto06** [comment]
Hi,

It's OK for the commands if I modify the yaml such as..
`  dps:
    - id: 1
      name: control
      type: string
      mapping:
        - conditions:
            - dps_val: [ "1", "2", "3" ]
              mapping:
                - dps_val: "1"
                  value: open
                - dps_val: "2"
                  value: close
                - dps_val: "3"
                  value: stop`
-->
  dps:
    - id: 1
      name: control
      type: string
      mapping:
        - dps_val: "1"
          value: open
        - dps_val: "2"
          value: close
        - dps_val: "3"
          value: stop`

On the other hand, still no movement history and reaction time is much longer than localtuya

Sorry for my uncertain English, I'm French
