### ISSUE TITLE
Home thermostat BHT - 8000

### ISSUE THREAD

**Issue by GjelbrimH** [make-all/tuya-local#1443]
Hello to everyone. 
I bought the BHT - 8000 WIFI thermostat 2 years ago, so it is wireless and everything works fine except for the temperature when it should be turned on. 
The problem is that if I set the temperature to 23C or whatever temperature, the moment the temperature in the room drops to 22.5C, the boiler turns on, so only for 0.5C. For me, it is too little, the 1C is perfect, so I'd love to work this way like when I set it to 23C (or whatever temperature) and when it drops to 22C, then the heating can turn on (fire). I have also tried the dead zone temp function, but if I do it then it rises to 1.5C and I can't make it 1C anyway.

Please, who can help me?
![photobank-5](https://github.com/make-all/tuya-local/assets/154633644/57e19e93-3119-4af1-addd-50124fda12cf)

**Comment by make-all** [comment]
This is not a story board.  If you want to request support for a device, please fill out the details requested in the form.

**Comment by GjelbrimH** [comment]
> This is not a story board.  If you want to request support for a device, please fill out the details requested in the form.

Sorry I don't know much about here, I am new. Can you explain in more detail what to do?
Thank you!
