### ISSUE TITLE
Request support for [DTS238-7 Wifi Three Phase Energy Meter]

### ISSUE THREAD

**Issue by samybalasa** [make-all/tuya-local#1449]
# Log Message
Log details (WARNING)
This error originated from a custom integration.
Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:103
Integration: Tuya Local ([documentation](https://github.com/make-all/tuya-local), [issues](https://github.com/make-all/tuya-local/issues))
First occurred: 15:38:09 (2 occurrences)
Last logged: 15:47:04
Report this to https://github.com/make-all/tuya-local/issues/```
This error originated from a custom integration.
Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:223
Integration: Tuya Local (documentation, issues)
First occurred: 15:51:52 (1 occurrences)
Last logged: 15:51:52
Contor Trifazic General receive loop has terminated

# Information about DPS mappings
{
        "name": "Smart Meter",
        "id": "03410103a4e57c0b0eb4",
        "key": "6980b038d420be8c",
        "mac": "a4:e5:7c:0b:0e:b3",
        "uuid": "03410103a4e57c0b0eb3",
        "sn": "1000290280057F",
        "category": "cz",
        "product_name": "meter",
        "product_id": "sw9asyjj8j44frjl",
        "biz_type": 0,
        "model": "DDS238-2 WIFI",
        "sub": false,
        "icon": "https://images.tuyaeu.com/smart/icon/ay1560212249260P1Twc/453ba400152308bc828c7f0dda185587.jpg",
        "mapping": {
            "1": {
                "code": "switch_1",
                "type": "Boolean",
                "values": {}
            },
            "9": {
                "code": "countdown_1",
                "type": "Integer",
                "values": {
                    "unit": "s",
                    "min": 0,
                    "max": 86400,
                    "scale": 0,
                    "step": 1
                }
            },
            "18": {
                "code": "cur_current",
                "type": "Integer",
                "values": {
                    "unit": "mA",
                    "min": 0,
                    "max": 100000,
                    "scale": 0,
                    "step": 1
                }
            },
            "19": {
                "code": "cur_power",
                "type": "Integer",
                "values": {
                    "unit": "W",
                    "min": 0,
                    "max": 500000,
                    "scale": 1,
                    "step": 1
                }
            },
            "20": {
                "code": "cur_voltage",
                "type": "Integer",
                "values": {
                    "unit": "V",
                    "min": 0,
                    "max": 5000,
                    "scale": 1,
                    "step": 1
                }
            }
        },
        "ip": "192.168.x.x",
        "version": "3.3"
    }

# Product ID
sw9asyjj8j44frjl

# Information about how the device functions
I request an update for this device in Tuya Local integration to specifically support the DTS238-7 Wifi Three Phase Energy Meter. While I've successfully discovered and integrated the device, I've noticed a lack of support for measuring energy consumption in standard units such as GJ, kWh, MJ, MWh, Wh. It seems the system has recognized only a similar version of the device, leading to improper configuration. Please consider creating an soecific integration for this device that enables precise energy consumption monitoring in Home Assistant for my specific device model.

I would like to extend my sincere gratitude for the effort and dedication you have shown in supporting the Home Assistant community. Your work greatly enhances the capabilities and usability of Home Assistant for users like myself. The community truly benefits from your contributions, and I am thankful for your continued support in making these valuable integrations available and up-to-date.

**Comment by make-all** [comment]
The information you have given is for a generic smartplug, not an energy meter.  I cannot add something that is not available.

**Comment by samybalasa** [comment]
So... how can I do that?
![IMG_004307485DD1-1](https://github.com/make-all/tuya-local/assets/16115410/a5a60a37-5daa-41b7-995e-84aaa4c84d44)
This is the same device....
Thank you !

**Comment by make-all** [comment]
There is a tutorial here: https://hittheroad.dev/how-to-track-energy-consumption-in-home-assistant-using-a-tuya-wifi-digital-meter-and-riemann-sum-a6214ab2556d

**Comment by samybalasa** [comment]
thank you verry much, it is working
