### ISSUE TITLE
Add a camera mount

### ISSUE THREAD

**Issue by RP92** [make-all/tuya-local#145]
Hi I have this camera, Life365 Italy-Mini8s(安凯V300_8M), and I don't think it's supported, trying to add gives me this error, Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect.

**Comment by make-all** [comment]
Cameras are not supported, and would require a lot more investigation into the details of how they work with the tuya protocol and video streaming.

**Comment by make-all** [comment]
This issue anyway does not have enough information to even start looking at integrating support.
