### ISSUE TITLE
Request support for [Heat Pump Controller]

### ISSUE THREAD

**Issue by samybalasa** [make-all/tuya-local#1455]
# Log Message
Nothing related

# Information about DPS mappings
    {
        "name": "Heat Pump Wifi Zigbee Controller",
        "id": "61568261c45bbeda7d00",
        "key": "*Q@lUz;vS-0EUPEn",
        "mac": "c4:5b:be:da:7d:00",
        "uuid": "61568261c45bbeda7d10",
        "sn": "1000585330021E",
        "category": "znrb",
        "product_name": "\u70ed\u6cf5\u4e09\u8054\u4f9b",
        "product_id": "koylufmd3rozlmax",
        "biz_type": 0,
        "model": "",
        "sub": false,
        "icon": "https://images.tuyaeu.com/smart/icon/ay1568944647187spSKl/b67b176951840ec2759b1b7302bbc52a.png",
        "mapping": {
            "1": {
                "code": "switch",
                "type": "Boolean",
                "values": {}
            },
            "2": {
                "code": "mode",
                "type": "Enum",
                "values": {
                    "range": [
                        "cold",
                        "heating"
                    ]
                }
            },
            "4": {
                "code": "temp_set",
                "type": "Integer",
                "values": {
                    "unit": "",
                    "min": 10,
                    "max": 60,
                    "scale": 0,
                    "step": 1
                }
            },
            "16": {
                "code": "temp_current",
                "type": "Integer",
                "values": {
                    "min": -30,
                    "max": 100,
                    "scale": 0,
                    "step": 1
                }
            }
        },
        "ip": "192.168.75.145",
        "version": "3.3"
    },

# Product ID
61568261c45bbeda7d00

# Information about how the device functions
This is a Heat Pump Controller.

When I have to choose the type of device, i only found this device types:
desk_lamp
mellerware_citymove_vacuum
rgbww_lightbulb
simple_switch

**Comment by make-all** [comment]
As you are unable to collect logs, the device is most likely unable to connect locally.  It would therefore be a waste of time to work on this.

**Comment by samybalasa** [comment]
I found this log when connecting the heating pump (found as Mellerware vacuum Reset HEPA filter):

December 26, 2023

Mellerware vacuum Reset HEPA filter  became unknown
22:25:34 - 9 seconds ago

Mellerware vacuum Reset roller brush  became unknown
22:25:34 - 9 seconds ago

Mellerware vacuum Reset brush  became unknown
22:25:34 - 9 seconds ago

Mellerware vacuum  changed to Idle
22:25:34 - 9 seconds ago

Mellerware vacuum Reset HEPA filter  became unavailable
22:25:29 - 14 seconds ago

Mellerware vacuum Reset roller brush  became unavailable
22:25:29 - 14 seconds ago

Mellerware vacuum Reset brush  became unavailable
22:25:29 - 14 seconds ago

Mellerware vacuum  became unavailable
22:25:29 - 14 seconds ago

RPi Power status  cleared (no problem detected)
22:24:54 - 1 minute ago

Mellerware vacuum Reset HEPA filter  became unknown
22:24:37 - 1 minute ago

Mellerware vacuum Reset roller brush  became unknown
22:24:37 - 1 minute ago

Mellerware vacuum Reset brush  became unknown
22:24:37 - 1 minute ago

Mellerware vacuum  changed to Idle
22:24:37 - 1 minute ago

Mellerware vacuum Reset HEPA filter  became unavailable
22:24:32 - 1 minute ago

Mellerware vacuum Reset roller brush  became unavailable
22:24:32 - 1 minute ago

Mellerware vacuum Reset brush  became unavailable
22:24:32 - 1 minute ago

Mellerware vacuum  became unavailable
22:24:32 - 1 minute ago

**Comment by samybalasa** [comment]
the device can connect, and is a common device

**Comment by samybalasa** [comment]
> As you are unable to collect logs, the device is most likely unable to connect locally. It would therefore be a waste of time to work on this.

the device can connect, and is a common device
