### ISSUE TITLE
[New device] Tesla Aroma Diffuser

### ISSUE THREAD

**Issue by fantnhu** [make-all/tuya-local#1469]
Hello! Thank you for your work so far. Please add the Tesla Aroma Diffuser to the integration.
I hope you can find all the information here:

`[Aroma Diffuser] 192.168.xx.xxx     - [Off] - DPS: {'1': False, '2': '1', '11': False, '12': 0, '13': '1', '14': 0, '101': '2', '102': 'colour', '103': 'ff00400158ffff', '104': False}`

```
"result": {
    "model": "{\"modelId\":\"0000034p26\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"Power\",\"description\":\"开启/关闭，开启进入待机状态\",\"extensions\":{\"iconName\":\"icon-dp_power\",\"attribute\":\"23\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"Mode\",\"description\":\"1：连续喷雾；2：间歇喷雾\",\"extensions\":{\"iconName\":\"icon-dp_mode\"},\"name\":\"工作模式\",\"typeSpec\":{\"range\":[\"1\",\"2\"],\"type\":\"enum\",\"typeDefaultValue\":\"1\"}},
{\"abilityId\":11,\"accessMode\":\"rw\",\"code\":\"Light\",\"description\":\"开启/关闭\",\"extensions\":{\"iconName\":\"icon-dp_light\"},\"name\":\"灯光\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":12,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"缺水保护\",\"extensions\":{\"iconName\":\"icon-dp_warming\",\"scope\":\"fault\"},\"name\":\"故障告警\",\"typeSpec\":{\"label\":[\"1\"],\"maxlen\":1,\"type\":\"bitmap\",\"typeDefaultValue\":0}},
{\"abilityId\":13,\"accessMode\":\"rw\",\"code\":\"countdown\",\"description\":\"0:取消；1：1小时;2：3小时；3：5小时；可根据产品实际功能进行设置。\",\"extensions\":{\"iconName\":\"icon-dp_time2\"},\"name\":\"倒计时\",\"typeSpec\":{\"range\":[\"0\",\"1\",\"2\",\"3\"],\"type\":\"enum\",\"typeDefaultValue\":\"0\"}},
{\"abilityId\":14,\"accessMode\":\"ro\",\"code\":\"countdown_left\",\"description\":\"mcu每分钟上报\",\"extensions\":{\"iconName\":\"icon-dp_time\"},\"name\":\"倒计时剩余时间\",\"typeSpec\":{\"max\":360,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"分钟\"}},
{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"lightmode\",\"description\":\"1：七彩渐变;2:选色\",\"name\":\"灯光模式\",\"typeSpec\":{\"range\":[\"1\",\"2\"],\"type\":\"enum\",\"typeDefaultValue\":\"1\"}},
{\"abilityId\":102,\"accessMode\":\"rw\",\"code\":\"work_mode\",\"description\":\"\",\"name\":\"灯光模式\",\"typeSpec\":{\"range\":[\"white\",\"colour\",\"scene\",\"scene_1\",\"scene_2\",\"scene_3\",\"scene_4\"],\"type\":\"enum\",\"typeDefaultValue\":\"white\"}},
{\"abilityId\":103,\"accessMode\":\"rw\",\"code\":\"colour_data\",\"description\":\"Value: ”00112233334455”（长度为 14 的字符串） 00: R 11: G 22: B 3333: H(色调 Hue) 44: S(饱和度 Saturation) 55: V(明度 Value) 示例： {\\\"2700000000ff27\\\"}    指定16种颜色\",\"name\":\"彩光值\",\"typeSpec\":{\"maxlen\":255,\"type\":\"string\",\"typeDefaultValue\":\"\"}},
{\"abilityId\":104,\"accessMode\":\"rw\",\"code\":\"spray\",\"description\":\"开启/关闭\",\"name\":\"喷雾开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}}]}]}"
  }
```
![image](https://github.com/make-all/tuya-local/assets/73642352/cae8892c-cae9-454e-8f48-0e443595ecfd)

**Comment by make-all** [comment]
The product_id can be found under Device Management / Query Device Details in API Explorer on iot.tuya.com

**Comment by fantnhu** [comment]
> The product_id can be found under Device Management / Query Device Details in API Explorer on iot.tuya.com

`{
  "result": {
    "active_time": 1702415402,
    "category": "jsq",
    "create_time": 1649159575,
    "custom_name": "Aroma Diffuser",
    "icon": "smart/icon/bay1584694222677qRhW/1cccdde566a391e5651856297879ef38.png",
    "id": "xxx",
    "ip": "xxx",
    "is_online": true,
    "lat": "xxx",
    "local_key": "xxx",
    "lon": "18.2200",
    "model": "TSL-AC-JS01W",
    "name": "Tesla Smart Aroma Diffuser",
    "product_id": "izm17rnzcc2akjis",
    "product_name": "Tesla Smart Aroma Diffuser",
    "sub": false,
    "time_zone": "+01:00",
    "update_time": xxx,
    "uuid": "xxx"
  }`

**Comment by fantnhu** [comment]
Hi! Thank you for your work!
I tried to add it, but it doesn't quite work. It only recognizes 3.3 protocol - TuyaLocal 2024.1.0. 
I can choose from the following (image).
Unfortunately I get 1-1 entity, usually a switch:
 - light switch: turns on the light and the device starts (light control works, but I can't turn off the light and the device separately)
or
 - single switch: turns on the light and the device starts

Am I doing it wrong?
![image](https://github.com/make-all/tuya-local/assets/73642352/b8e1e9df-5d36-4125-8a9b-34e6d0753467)

**Comment by make-all** [comment]
You logs at the top are not in the format that this integration uses, so maybe they are not truly based off what the device sends for its initial data request.  Or maybe the result depends on device settings.  Whenever you want to report some issue, I really need the device logs (especially initial connection issues) or diagnostics (if the device is already connected, but not working correctly).

**Comment by make-all** [comment]
Also, you specified "TuyaLocal 2024.1.0", but this change was not in that release.  This issue is tagged "unreleased", which means to use it you will have to install from the main branch, not a release tag (it is possible from the "Redownload" menu of HACS to select "main", but you will have to ignore the prompts to upgrade to release 2024.1.0 until 2024.1.1 is available).

**Comment by fantnhu** [comment]
`Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:97
Integration: Tuya Local ([documentation](https://github.com/make-all/tuya-local), [issues](https://github.com/make-all/tuya-local/issues))
First occurred: 07:41:51 (1 occurrences)
Last logged: 07:41:51

Device matches cc_curtain with quality of 20%. DPS: {"updated_at": 1706164910.3156176, "1": false, "2": "1", "11": false, "12": 0, "13": "1", "14": 0, "101": "2", "102": "colour", "103": "ff00400158ffff", "104": false}`

**Comment by fantnhu** [comment]
Ohhh thanks for the help. It was indeed my mistake. 
I confirm that the device is working properly. 
Only observation is that the "Fault" sensor indicates "Out of water".
Thanks again. I will test the other devices soon. 
![image](https://github.com/make-all/tuya-local/assets/73642352/583a23c3-332e-4acf-9105-91e6d66cc9c5)
