### ISSUE TITLE
[New device] PNI Water feeder (for pets)

### ISSUE THREAD

**Issue by fantnhu** [make-all/tuya-local#1470]
Hello! Thank you for your work so far. Please add the PNI Water Feeder to the integration.
I hope you can find all the information here:

<details>
<summary>"product_id": "ajkayo9kucq6vttv"</summary>

```
        "name": "Water Feeder",
        "id": "xxx",
        "key": ":xxx",
        "mac": "xxx",
        "uuid": "xxx",
        "category": "cwysj",
        "product_name": "PNI Water Feeder",
        "product_id": "ajkayo9kucq6vttv",
        "biz_type": 18,
        "model": "TA-WF-SMART(UV)",
        "sub": false,
        "icon": "https://images.tuyaeu.com/smart/icon/ay1519800722250B425i/b1024a27c41da78382ae032342d5fb0f.jpg",
        "mapping": {
            "10": {
                "code": "uv",
                "type": "Boolean",
                "values": {}
            },
            "1": {
                "code": "switch",
                "type": "Boolean",
                "values": {}
            }
        }`
```

</details>

```
"result": {
    "model": "{\"modelId\":\"0000004dus\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":10,\"accessMode\":\"rw\",\"code\":\"uv\",\"description\":\"\",\"name\":\"UV杀菌\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":13,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"\",\"name\":\"故障告警\",\"typeSpec\":{\"label\":[\"water_lack\"],\"maxlen\":1,\"type\":\"bitmap\",\"typeDefaultValue\":0}}]}]}"
  }
```

![image](https://github.com/make-all/tuya-local/assets/73642352/4d735ff8-3edb-49ca-98bc-843c897f7847)

**Comment by make-all** [comment]
Pleas provide logs also

**Comment by fantnhu** [comment]
> Pleas provide logs also

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:97
Integration: tuya_local ([documentation](https://github.com/make-all/tuya-local), [issues](https://github.com/make-all/tuya-local/issues))
First occurred: 18:42:05 (1 occurrences)
Last logged: 18:42:05

`Device matches mellerware_citymove_vacuum with quality of 33%. DPS: {"updated_at": 1704476523.981763, "1": false, "10": false, "13": 1}`

**Comment by fantnhu** [comment]
`{
    "tokenResponse": {
        "expire_time": 300,
        "region": "EU",
        "secret": "3lWf",
        "token": "aYQqd20I"
    },
    "deviceApi": "http://a.tuyaeu.com/d.json",
    "activeRequest": {
        "token": "aYQqd20I",
        "productKey": "ajkayo9kucq6vttv",
        "softVer": "1.0.0",
        "protocolVer": "2.2",
        "baselineVer": "40.00",
        "cadVer": "1.0.3",
        "cdVer": "1.0.0",
        "options": "{\"isFK\":false}",
        "t": 1704482640
    },
    "activeResponse": {
        "schema": [
            {
                "mode": "rw",
                "property": {
                    "type": "bool"
                },
                "id": 1,
                "type": "obj"
            },
            {
                "mode": "rw",
                "property": {
                    "type": "bool"
                },
                "id": 10,
                "type": "obj"
            },
            {
                "mode": "ro",
                "property": {
                    "type": "bitmap",
                    "maxlen": 1
                },
                "id": 13,
                "type": "obj"
            }
        ],
        "devId": "xxx",
        "resetFactory": false,
        "timeZone": "+01:00",
        "capability": 1,
        "secKey": "xxx",
        "stdTimeZone": "+01:00",
        "schemaId": "0000004dus",
        "dstIntervals": [
            [
                1711846800,
                1729990800
            ],
            [
                1743296400,
                1761440400
            ],
            [
                1774746000,
                1792890000
            ],
            [
                1806195600,
                1824944400
            ],
            [
                1837645200,
                1856394000
            ]
        ],
        "localKey": "xxx"
    },
    "checkResponse": {
        "error_devices": [],
        "success_devices": [
            {
                "id": "bf36870155eccdeb22pdxv",
                "ip": "2a06:98c0:3600::103",
                "lat": "",
                "lon": "",
                "name": "Water Feeder",
                "online": false,
                "product_id": "ajkayo9kucq6vttv",
                "uuid": "xxx"
            }
        ]
    },
    "modelResponse": {
        "model": {
            "modelId": "0000004dus",
            "services": [
                {
                    "actions": [],
                    "code": "",
                    "description": "",
                    "events": [],
                    "name": "\u9ed8\u8ba4\u670d\u52a1",
                    "properties": [
                        {
                            "abilityId": 1,
                            "accessMode": "rw",
                            "code": "switch",
                            "description": "",
                            "name": "\u5f00\u5173",
                            "typeSpec": {
                                "type": "bool",
                                "typeDefaultValue": false
                            }
                        },
                        {
                            "abilityId": 10,
                            "accessMode": "rw",
                            "code": "uv",
                            "description": "",
                            "name": "UV\u6740\u83cc",
                            "typeSpec": {
                                "type": "bool",
                                "typeDefaultValue": false
                            }
                        },
                        **{
                            "abilityId": 13,
                            "accessMode": "ro",
                            "code": "fault",
                            "description": "",
                            "name": "\u6545\u969c\u544a\u8b66",
                            "typeSpec": {
                                "label": [
                                    "water_lack"
                                ],
                                "maxlen": 1,
                                "type": "bitmap",
                                "typeDefaultValue": 0
                            }**
                        }
                    ]
                }
            ]
        }
    },
    "errors": [],
    "detailsResponse": {
        "active_time": 1704482640,
        "asset_id": "165374831",
        "category": "cwysj",
        "category_name": "Pet Water Feeder",
        "gateway_id": "",
        "icon": "smart/icon/ay1519800722250B425i/b1024a27c41da78382ae032342d5fb0f.jpg",
        "id": "bf36870155eccdeb22pdxv",
        "ip": "xxx",
        "lat": "",
        "local_key": "xxx",
        "lon": "",
        "model": "TA-WF-SMART(UV)",
        "name": "Water Feeder",
        "online": false,
        "product_id": "ajkayo9kucq6vttv",
        "product_name": "Water Feeder",
        "sub": false,
        "time_zone": "+01:00",
        "uuid": "xxx"
    },
    "updateResponse": [
        {
            "channel": 0,
            "control_type": 0,
            "current_version": "1.0.0",
            "dev_type": 0,
            "firmware_deploy_time": 1603710650,
            "last_upgrade_time": 0,
            "timeout": 60,
            "type": 0,
            "type_desc": "Main Module",
            "upgrade_status": 0,
            "version": "1.0.4"
        }
    ],
    "deleteResponse": true,
    "cachedAt": 1704482641323,
    "cacheKey": "ajkayo9kucq6vttv"
}`

**Comment by fantnhu** [comment]
I confirm that all functions work flawlessly.
Thank you for your work!
![image](https://github.com/make-all/tuya-local/assets/73642352/76a0d043-05df-4579-a71a-987e5a566c37)
