### ISSUE TITLE
Request support for WeeKett Smart Kettle

### ISSUE THREAD

**Issue by debdalerichard** [make-all/tuya-local#1481]
# Log Message

```
Please paste logs here
```

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"000003swnr\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"start\",\"description\":\"【必选】控制设备启动暂停开关\",\"extensions\":{\"attribute\":\"1\"},\"name\":\"工作开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":2,\"accessMode\":\"ro\",\"code\":\"temp_current\",\"description\":\"【非必选】当前温度显示，该DP点用于温标为摄氏度使用，未选择该DP点则不展示该功能\",\"name\":\"当前温度（℃）\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"℃\"}},
{\"abilityId\":3,\"accessMode\":\"ro\",\"code\":\"temp_current_f\",\"description\":\"【非必选】当前温度显示，该DP点用于温标为华氏度使用，未选择该DP点则不展示该功能\",\"name\":\"当前温度（℉）\",\"typeSpec\":{\"max\":212,\"min\":32,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":32,\"unit\":\"℉\"}},
{\"abilityId\":8,\"accessMode\":\"rw\",\"code\":\"temp_set\",\"description\":\"【非必选】选择沸腾后冷却到目标温度选项，该DP点数值范围可修改，未选则不展示该功能。\",\"name\":\"温度设置（℃）\",\"typeSpec\":{\"max\":100,\"min\":40,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":40,\"unit\":\"℃\"}},
{\"abilityId\":9,\"accessMode\":\"rw\",\"code\":\"temp_set_f\",\"description\":\"【非必选】选择沸腾后冷却到目标温度选项，该DP点数值范围可修改，未选则不展示该功能。\",\"name\":\"温度设置（℉）\",\"typeSpec\":{\"max\":212,\"min\":104,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":104,\"unit\":\"℉\"}},
{\"abilityId\":12,\"accessMode\":\"rw\",\"code\":\"temp_unit_convert\",\"description\":\"【非必选】温标切换开关选择，未选则不展示该功能。如果选这了该功能，必须选择℃和℉的相关搭配DP点\",\"name\":\"温标切换\",\"typeSpec\":{\"range\":[\"c\",\"f\"],\"type\":\"enum\",\"typeDefaultValue\":\"c\"}},
{\"abilityId\":13,\"accessMode\":\"rw\",\"code\":\"warm\",\"description\":\"\",\"name\":\"保温\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":15,\"accessMode\":\"ro\",\"code\":\"status\",\"description\":\"【必选】设备上报工作状态，该DP点枚举值可增减，但不可修改枚举值名称，例如可以删除9，但是不能把9改为其他词，可以增加，仅支持增加数字，未选则不展示该功能。 默认： 1代表：待机中 2代表：加热中 3代表：冷却中 4代表：保温中 5代表：加热到目标温度 6代表：沸腾后冷却到目标温度 7代表：预留1 8代表：预留2 9代表：预留3 如需要修改代表名称，可以前往第四步的拓展中心，多语言管理修改代表值，新增的枚举值所代表的的内容也是在多语言中修改代表值。\",\"name\":\"工作状态\",\"typeSpec\":{\"range\":[\"standby\",\"heating\",\"cooling\",\"warm\",\"heating_temp\",\"boiling_temp\",\"reserve_1\",\"reserve_2\",\"reserve_3\"],\"type\":\"enum\",\"typeDefaultValue\":\"standby\"}},
{\"abilityId\":16,\"accessMode\":\"rw\",\"code\":\"work_type\",\"description\":\"此dp点不需要：【必选】不可修改、删除、增加枚举值。该DP点用于明确当前工作模式是什么，与所使用的温度设置DP点绑定上报。 例如： 用户选择了90℃直接加热快捷键 APP会下发：该DP点的setting_quick和对应温度的DP点； MCU需要上报：该DP点的setting_quick和对应温度的DP点；\",\"name\":\"工作类型\",\"typeSpec\":{\"range\":[\"setting_quick\",\"boiling_quick\",\"temp_setting\",\"temp_boiling\"],\"type\":\"enum\",\"typeDefaultValue\":\"setting_quick\"}},
{\"abilityId\":19,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"\",\"extensions\":{\"scope\":\"fault\"},\"name\":\"故障告警\",\"typeSpec\":{\"label\":[\"waterless\",\"kettle_leave\"],\"maxlen\":2,\"type\":\"bitmap\",\"typeDefaultValue\":0}},
{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"baby_mode\",\"description\":\"\",\"name\":\"婴儿奶粉模式\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}}]}]}"
  },
  "success": true,
  "t": 1704533700692,
  "tid": "dca7d59cac7611eeb4711ef527e2ea42"
}
```

{
  "result": {
    "active_time": 1702136786,
    "category": "bh",
    "create_time": 1702136786,
    "custom_name": "",
    "icon": "smart/icon/ay156518157955398rGB/363a2e8ea6ad2c985b72ca71d4531411.png",
    "id": "",
    "ip": "",
    "is_online": true,
    "lat": "",
    "local_key": "",
    "lon": "",
    "model": "",
    "name": "Kettle ",
    "product_id": "01rtpfyd3amxdsps",
    "product_name": "WeeKett Kettle BLT 二代 KE4071TF 已出货严禁修改",
    "sub": false,
    "time_zone": "+00:00",
    "update_time": 1702140598,
    "uuid": ""
  },
  "success": true,
  "t": 1702317366517,
  "tid": "8eb59795984e11eeba277618d5e79284"
}

{
  "result": {
    "properties": [
      {
        "code": "start",
        "custom_name": "",
        "dp_id": 1,
        "time": 1702458682252,
        "value": false
      },
      {
        "code": "temp_current",
        "custom_name": "",
        "dp_id": 2,
        "time": 1702462489999,
        "value": 16
      },
      {
        "code": "temp_current_f",
        "custom_name": "",
        "dp_id": 3,
        "time": 1702462281221,
        "value": 60
      },
      {
        "code": "temp_set",
        "custom_name": "",
        "dp_id": 8,
        "time": 1702450901261,
        "value": 100
      },
      {
        "code": "temp_set_f",
        "custom_name": "",
        "dp_id": 9,
        "time": 1702325992424,
        "value": 212
      },
      {
        "code": "temp_unit_convert",
        "custom_name": "",
        "dp_id": 12,
        "time": 1702325992452,
        "value": "c"
      },
      {
        "code": "warm",
        "custom_name": "",
        "dp_id": 13,
        "time": 1702325992478,
        "value": false
      },
      {
        "code": "status",
        "custom_name": "",
        "dp_id": 15,
        "time": 1702458682354,
        "value": "standby"
      },
      {
        "code": "work_type",
        "custom_name": "",
        "dp_id": 16,
        "time": 1702326513830,
        "value": "temp_setting"
      },
      {
        "code": "fault",
        "custom_name": "",
        "dp_id": 19,
        "time": 1702459187952,
        "value": 0
      },
      {
        "code": "baby_mode",
        "custom_name": "",
        "dp_id": 101,
        "time": 1702325991858,
        "value": false
      }
    ]
  },
  "success": true,
  "t": 1702463378388,
  "tid": "8492964699a211ee8ae5e673203d0211"
}

**Comment by make-all** [comment]
Logs are required

**Comment by debdalerichard** [comment]
I'm Fairly new to Home Assistant is this what you require?
Great work! 
> ```
> Please paste logs here
> ```
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.1.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "6.1.70-haos",
    "supervisor": "2023.12.1",
    "host_os": "Home Assistant OS 11.3",
    "docker_version": "24.0.7",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "tuya_local": {
      "version": "2023.12.2",
      "requirements": [
        "tinytuya==1.13.1"
      ]
    },
    "retry": {
      "version": "v2.6.1",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "tuya_local",
    "name": "Tuya Local",
    "codeowners": [
      "@make-all"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/make-all/tuya-local",
    "integration_type": "device",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/make-all/tuya-local/issues",
    "requirements": [
      "tinytuya==1.13.1"
    ],
    "version": "2023.12.2",
    "is_built_in": false
  },
  "data": {
    "name": "Kettle",
    "type": "simple_switch",
    "device_id": "**REDACTED**",
    "device_cid": "",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": "auto",
    "tinytuya_version": "1.13.1",
    "api_version_set": 3.3,
    "api_version_used": 3.3,
    "api_working": true,
    "status": {},
    "cached_state": {
      "updated_at": 1704542336.4326048,
      "1": false,
      "2": 46,
      "3": 115,
      "8": 100,
      "9": 212,
      "12": "c",
      "13": false,
      "15": "standby",
      "16": "temp_setting",
      "19": 0,
      "101": false
    },
    "pending_state": {},
    "connected": true,
    "force_dps": [],
    "home_assistant": {
      "name": "Kettle",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "switch",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.kettle_2",
            "state": "off",
            "attributes": {
              "device_class": "switch",
              "friendly_name": "Kettle"
            },
            "last_changed": "2024-01-06T10:17:32.293327+00:00",
            "last_updated": "2024-01-06T10:17:32.293327+00:00"
          }
        }
      ]
    }
  }
}

**Comment by make-all** [comment]
Yes diagnostics will do if you have already set it up (with reduced features).  I was after the dps list that is in there.

**Comment by debdalerichard** [comment]
just an update (steep learning curve)...I think (hopefully) I've got the full DPS list so to pull in the full features of this device??

  {
        "name": "Kettle",
        "id": "REDACTED",
        "key": "REDACTED",
        "mac": "REDACTED",
        "uuid": "a129665a90a20727",
        "sn": "10012072200279",
        "category": "bh",
        "product_name": "Kettle ",
        "product_id": "01rtpfyd3amxdsps",
        "biz_type": 18,
        "model": "",
        "sub": false,
        "icon": "https://images.tuyaeu.com/smart/icon/ay156518157955398rGB/363a2e8ea6ad2c985b72ca71d4531411.png",
        "mapping": {
            "1": {
                "code": "start",
                "type": "Boolean",
                "values": {}
            },
            "2": {
                "code": "temp_current",
                "type": "Integer",
                "values": {
                    "unit": "\u00b0C",
                    "min": 0,
                    "max": 100,
                    "scale": 0,
                    "step": 1
                }
            },
            "3": {
                "code": "temp_current_f",
                "type": "Integer",
                "values": {
                    "unit": "\u00b0F",
                    "min": 32,
                    "max": 212,
                    "scale": 0,
                    "step": 1
                }
            },
            "8": {
                "code": "temp_set",
                "type": "Integer",
                "values": {
                    "unit": "\u00b0C",
                    "min": 40,
                    "max": 100,
                    "scale": 0,
                    "step": 1
                }
            },
            "9": {
                "code": "temp_set_f",
                "type": "Integer",
                "values": {
                    "unit": "\u00b0F",
                    "min": 104,
                    "max": 212,
                    "scale": 0,
                    "step": 1
                }
            },
            "12": {
                "code": "temp_unit_convert",
                "type": "Enum",
                "values": {
                    "range": [
                        "c",
                        "f"
                    ]
                }
            },
            "13": {
                "code": "warm",
                "type": "Boolean",
                "values": {}
            },
            "15": {
                "code": "status",
                "type": "Enum",
                "values": {
                    "range": [
                        "standby",
                        "heating",
                        "cooling",
                        "warm",
                        "heating_temp",
                        "boiling_temp",
                        "reserve_1",
                        "reserve_2",
                        "reserve_3"
                    ]
                }
            },
            "16": {
                "code": "work_type",
                "type": "Enum",
                "values": {
                    "range": [
                        "setting_quick",
                        "boiling_quick",
                        "temp_setting",
                        "temp_boiling"
                    ]
                }
            }
        }
    }
