### ISSUE TITLE
Constant deprecation in HA 2024.1

### ISSUE THREAD

**Issue by elarsson1** [make-all/tuya-local#1484]
**Describe the bug**
Home Assistant 2024.1 has deprecated a number of constants which have been replaced by enum types. Starting in HA 2024.1, this will emit log messages for use of deprecated constants in 2024.1. These constants will be removed completely in 2025.1. 

Reference:
* https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**To Reproduce**
Issue is reproduced on any Home Assistant build > 2024.1

**Expected behavior**
Integration starts with no warnings in log. 

**Sample Log messages**
Entity None (<class 'custom_components.tuya_local.light.TuyaLocalLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 0> and color modes, please create a bug report at https://github.com/make-all/tuya-local/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by make-all** [comment]
It seems only the 0 values are an issue, as there is not any value defined for them in the enums.
