### ISSUE TITLE
support switch with multiple gang

### ISSUE THREAD

**Issue by viKirubanathan** [make-all/tuya-local#149]
Hi,

is it possible to add devices with multiple gangs?

simple switch -> multiple gang switches
![image](https://user-images.githubusercontent.com/28481643/160261762-c5c3eff6-9b4f-4736-8692-111415213345.png)

thanks.

**Comment by make-all** [comment]
As a fallback option, there is no common standard, so no, there is not a possibility for generic support.  There are already several specific multigang switches supported, and any requests for new ones would need to come with technical information about the dps returned by the switches.
