### ISSUE TITLE
I don't know if it's a bug or not

### ISSUE THREAD

**Issue by ops244** [make-all/tuya-local#1491]
hi, I don't know if this is a bug or not, but I'll write here, before that I described the add device to you, in the last update it says that it was added, but now it just gives me a sign saying "the device is not supported" (at the same time, before the update was released, I manually added it from your repository and it worked, except one team. Why is that?

This is the device https://github.com/make-all/tuya-local/issues/1284

![2024-01-08_01-08-55](https://github.com/make-all/tuya-local/assets/19797600/b3edc768-360e-48ad-a62e-5156d7116cfc)

**Comment by ops244** [comment]
but this was when I manually added the file (that is, everything works in principle)
![2024-01-08_01-21-48](https://github.com/make-all/tuya-local/assets/19797600/2a6336fb-48ca-431e-891e-95baf07b74cb)

**Comment by make-all** [comment]
Please include the log messages related to this from Settings/System/Logs/Full Log

**Comment by ops244** [comment]
[home-assistant_2024-01-07T23-43-50.433Z.log](https://github.com/make-all/tuya-local/files/13855288/home-assistant_2024-01-07T23-43-50.433Z.log)

**Comment by make-all** [comment]
The relevant log message is this:

2024-01-08 02:41:23.637 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches None with quality of 0%. DPS: {"updated_at": 1704670868.2671, "4": "chargego", "5": "charge_done", "6": 0, "7": 1, "8": 100, "9": "gentle", "10": "closed", "17": 190, "19": 290, "21": 140, "23": 149, "26": 8, "28": 0}

Which device is this for?

**Comment by ops244** [comment]
This vacuum cleaner https://github.com/make-all/tuya-local/issues/1284

**Comment by ops244** [comment]
can the device IDs be changed in tuya? is it because it's not the same as in yaml right now?
It's worth it now bfcef42f141c15006amqze

![2024-01-08_03-32-12](https://github.com/make-all/tuya-local/assets/19797600/ecd04830-4d7d-4239-b5ca-6e21f9ffea0a)

**Comment by make-all** [comment]
That is not the device id, it is the product id.

Product id is common to all devices of that type.  It can be used in future
to link devices to config files (but not currently, because product id is
only available via the cloud and during local network discovery, but
currently we do not support discovery, only manual config).

Device id is unique to your device.  It is used to configure your specific
device.

**Comment by ops244** [comment]
yes, I understood, so I deleted the comment, everything is fine there)

**Comment by ops244** [comment]
if you restore the backup of the home assistant with an already authorized vacuum cleaner, it works now, if you delete it, you will no longer add it, it says "this device is not supported"

**Comment by ops244** [comment]
hi, everything is connecting normally now, but could you also add a "return to base" button?
![2024-01-11_08-47-29](https://github.com/make-all/tuya-local/assets/19797600/ec35893c-07e3-406b-9f6d-9354e554a754)
