### ISSUE TITLE
TTEC vacuum does not display the return_to_base button

### ISSUE THREAD

**Issue by make-all** [make-all/tuya-local#1509]
### Discussed in https://github.com/make-all/tuya-local/discussions/1508

<div type='discussions-op-text'>

<sup>Originally posted by **ops244** January 11, 2024</sup>
is it possible to add a "return to base" button to this vacuum cleaner? I tried, but it didn't work out.

https://github.com/make-all/tuya-local/issues/1284

![2024-01-11_08-47-29](https://github.com/make-all/tuya-local/assets/19797600/1ec9c3b2-ca8c-4c84-aeb4-46a298dae8f9)

https://github.com/make-all/tuya-local/issues/1284</div>

**Comment by make-all** [comment]
The return_to_base command is available in the list of commands, and should show on the "more info" card pictured.

The reason it is not is due to the way the pause vs other commands logic is handled in the config.  The logic needs to be reversed to make the pause dp the main command dp so nested mappings are not required.  Nested mappings inside a conditional override the mapping rather than append to it, so when the device is paused, the other commands become inaccessible with current config.

**Comment by make-all** [comment]
Other vacuums with a separate boolean pause dp may also have the same bug, which their users are silently putting up with.

**Comment by ops244** [comment]
Everything is ok now, thank you very much!
![2024-01-11_08-47-29](https://github.com/make-all/tuya-local/assets/19797600/ae6abdac-e6e3-41ba-b3c6-4feeb3fa8c47)
