### ISSUE TITLE
Integration not working with 2022.3

### ISSUE THREAD

**Issue by madduci** [make-all/tuya-local#151]
Hi

I'm running a HA 2022.3.8 installation but when I click to "Add Integration", it returns the message that the integration cannot be installed, I need to run a newer version of it, but the 2022.3.8 is the latest stable one.

How can I solve the issue?
![Localtuya](https://user-images.githubusercontent.com/371042/161431074-4d997087-5b18-406d-b48c-055eab672e69.png)

Edit: I am running Home Assistant as a Docker Container

**Comment by make-all** [comment]
That is strange, as this integration does support configuration via the UI, and is working with 2022.3 for me and others. Is there anything related to this in your log files?

**Comment by jddayley** [comment]
I'm having the same issue.

**Comment by make-all** [comment]
I just tried a fresh install of HomeAssistant core in a VM.  The only issue I had was that the newly added integrations did not show up in the UI until I used Ctrl-Refresh in the browser to force a refresh.  It may be a bug in the newer versions of HA (likely something intended to speed up the UI is caching too aggressively)

**Comment by madduci** [comment]
@make-all sorry for the delay in my response. In the logs doesn't appear any error. I've also tested with the 2022.4.1 and the problem persists, getting the error message.

**Comment by madduci** [comment]
After reading better the content of the repository, I've moved the custom_components folder of this repository to the /config folder in my Home Assistant docker volume and after a restart of the container, it showed up.
