### ISSUE TITLE
Request support for - Arlec RF Transmitter Self Learning Controller

### ISSUE THREAD

**Issue by NatMan3000** [make-all/tuya-local#1516]
# Log Message

```
2024-01-13 12:56:25.686 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches None with quality of 0%. DPS: {"updated_at": 1705110980.7241101, "101": "Button1"}
2024-01-13 12:56:25.687 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/
```

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"0000003qya\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"r1_rd\",\"description\":\"\",\"name\":\"Remote 1\",\"typeSpec\":{\"range\":[\"Button1\",\"Button2\",\"Button3\",\"Button4\",\"Button5\",\"Button6\",\"Button7\",\"Button8\"],\"type\":\"enum\",\"typeDefaultValue\":\"Button1\"}},
{\"abilityId\":102,\"accessMode\":\"wr\",\"code\":\"r2_rd\",\"description\":\"\",\"name\":\"Remote 2\",\"typeSpec\":{\"range\":[\"Button1\",\"Button2\",\"Button3\",\"Button4\",\"Button5\",\"Button6\",\"Button7\",\"Button8\"],\"type\":\"enum\",\"typeDefaultValue\":\"Button1\"}},
{\"abilityId\":103,\"accessMode\":\"wr\",\"code\":\"r3_rd\",\"description\":\"\",\"name\":\"Remote 3\",\"typeSpec\":{\"range\":[\"Button1\",\"Button2\",\"Button3\",\"Button4\",\"Button5\",\"Button6\",\"Button7\",\"Button8\"],\"type\":\"enum\",\"typeDefaultValue\":\"Button1\"}},
{\"abilityId\":104,\"accessMode\":\"wr\",\"code\":\"r4_rd\",\"description\":\"\",\"name\":\"Remote 4\",\"typeSpec\":{\"range\":[\"Button1\",\"Button2\",\"Button3\",\"Button4\",\"Button5\",\"Button6\",\"Button7\",\"Button8\"],\"type\":\"enum\",\"typeDefaultValue\":\"Button1\"}},
{\"abilityId\":105,\"accessMode\":\"wr\",\"code\":\"r5_rd\",\"description\":\"\",\"name\":\"Remote 5\",\"typeSpec\":{\"range\":[\"Button1\",\"Button2\",\"Button3\",\"Button4\",\"Button5\",\"Button6\",\"Button7\",\"Button8\"],\"type\":\"enum\",\"typeDefaultValue\":\"Button1\"}},
{\"abilityId\":106,\"accessMode\":\"wr\",\"code\":\"r6_rd\",\"description\":\"\",\"name\":\"Remote 6\",\"typeSpec\":{\"range\":[\"Button1\",\"Button2\",\"Button3\",\"Button4\",\"Button5\",\"Button6\",\"Button7\",\"Button8\"],\"type\":\"enum\",\"typeDefaultValue\":\"Button1\"}},
{\"abilityId\":107,\"accessMode\":\"wr\",\"code\":\"r7_rd\",\"description\":\"\",\"name\":\"Remote 7\",\"typeSpec\":{\"range\":[\"Button1\",\"Button2\",\"Button3\",\"Button4\",\"Button5\",\"Button6\",\"Button7\",\"Button8\"],\"type\":\"enum\",\"typeDefaultValue\":\"Button1\"}},
{\"abilityId\":108,\"accessMode\":\"wr\",\"code\":\"r8_rd\",\"description\":\"\",\"name\":\"Remote 8\",\"typeSpec\":{\"range\":[\"Button1\",\"Button2\",\"Button3\",\"Button4\",\"Button5\",\"Button6\",\"Button7\",\"Button8\"],\"type\":\"enum\",\"typeDefaultValue\":\"Button1\"}},
{\"abilityId\":109,\"accessMode\":\"wr\",\"code\":\"sig_ops\",\"description\":\"0x01 learn 0x02 test 0x03 delete 0x04 save\",\"name\":\"button operations\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":110,\"accessMode\":\"wr\",\"code\":\"btlist_rd\",\"description\":\"\",\"name\":\"remote button list\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":111,\"accessMode\":\"wr\",\"code\":\"rnlist_rd\",\"description\":\"\",\"name\":\"remote name list\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":112,\"accessMode\":\"wr\",\"code\":\"rn_wr\",\"description\":\"\",\"name\":\"remote name store\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":113,\"accessMode\":\"ro\",\"code\":\"sys_err\",\"description\":\"\",\"extensions\":{\"scope\":\"fault\"},\"name\":\"system error\",\"typeSpec\":{\"label\":[\"sys_err_1\",\"sys_err_2\",\"sys_err_3\",\"sys_err_4\"],\"maxlen\":4,\"type\":\"bitmap\",\"typeDefaultValue\":0}}]}]}"
  },
  "success": true,
  "t": 1705049658566,
  "tid": "2bb86463b12811ee847d96852008b4f4"
}
```
{"101":"Remote 1","102":"Remote 2","103":"Remote 3","104":"Remote 4","105":"Remote 5","106":"Remote 6","107":"Remote 7","108":"Remote 8","109":"button operations","110":"remote button list","111":"remote name list","112":"remote name store","113":"system error"}

# Device
Device id: 7178737398f4abf00b21

{
  "result": [
    {
      "active_time": 1660187032,
      "bind_space_id": "61867196",
      "category": "qt",
      "create_time": 1658899888,
      "custom_name": "RF Remote",
      "icon": "smart/icon/ay1558866774161DZ6MV/1563775105d3ba04c81ff.png",
      "id": "7178737398f4abf00b21",
      "ip": "**********",
      "is_online": true,
      "lat": "**********",
      "local_key": "**********",
      "lon": "**********",
      "model": "HUBRF06HA Yidong",
      "name": "HUBRF06HA",
      "product_id": "lclekupkvteemsym",
      "product_name": "HUBRF06HA",
      "sub": false,
      "time_zone": "+10:00",
      "update_time": 1674098582,
      "uuid": "7178737398f4abf00b21"
    }
  ],
  "success": true,
  "t": 1705049402460,
  "tid": "930c4f46b12711ee965f7eb6fd123fbf"
}

# Information about how the device functions

This product is a standalone self-learning RF hub for controlling most of the RF remote controlled products at 433 MHz frequency. It enables the non-smart RF products to be controlled via the Grid Connect app. It should be placed within relatively close proximity to the RF products that are intended to control.

This product does not have any RF code stored initially. The RF code needs to be learnt and stored into the product before it can be used. The procedures are easy to follow and simple to operate. This product can store up to 64 different RF control signals which can be flexibly organised in 8 different groups. The product is tested with a range of brands and can control most ceiling fans, motorised blinds and other RF products using a fixed code at 433Hz frequency.

This product is compatible with the Grid Connect smart home automation system, built to optimise your everyday living. Simply download the free Grid Connect app on your iOS or Android device and use your home Wi-Fi or mobile internet connection to control, customise and automate your product. It takes only minutes to set up, and there’s a wide range of products available that allow you to customise your system any way you like. Use the app to create the perfect light for every moment of the day, set your product to operate on your ideal schedule, and enjoy peace of mind while you’re away. Most Grid Connect products are compatible with Google Assistant and Amazon Alexa (sold separately), so you can operate your system with the ultimate convenience.

# Below is an example of the Tuya logs when a button is pressed on the Tuya ios app for this device.

<img width="1928" alt="Screenshot 2024-01-12 at 8 10 53 pm" src="https://github.com/make-all/tuya-local/assets/110029833/a6304baa-24d5-4294-a3b9-2eb9a0f4b41b">

**Comment by make-all** [comment]
Local logs are needed.

**Comment by NatMan3000** [comment]
Is this what you need?
```
2024-01-13 12:56:25.686 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches None with quality of 0%. DPS: {"updated_at": 1705110980.7241101, "101": "Button1"}
2024-01-13 12:56:25.687 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/
```

**Comment by make-all** [comment]
Yes, thanks. That confirms that the device is detectable, and gives the info on what dps need to be marked optional.

**Comment by NatMan3000** [comment]
Great! Thanks for all your hard work. :)

**Comment by NatMan3000** [comment]
Hi, I cannot get this setup.
I've tried all protocols, double checked device ID, IP address, Local key. But always get the error:
_Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect._

```
2024-01-31 14:37:27.974 DEBUG (SyncWorker_1) [custom_components.tuya_local.device] Test refreshed device state: {"Error": "Check device key or version", "Err": "914", "Payload": null}
2024-01-31 14:37:27.974 DEBUG (SyncWorker_1) [custom_components.tuya_local.device] new state (incl pending): {"updated_at": 1706672247.9740682}
```

**Comment by make-all** [comment]
You don't mention protocol version.  It seems many protocol 3.5 devices are appearing in the market now, and these do not work as well with the auto detection as thee older 3.3 and 3.1 devices.

**Comment by NatMan3000** [comment]
I've tried to add manually using versions 31., 3.2, 3.3, 3.4, 3.5 & auto. I get the same result every time. 
This is not a new device. I have had it for maybe 2 years, and i don't know how long it has been available before that.

**Comment by make-all** [comment]
I see from the original log that the device id matches the uuid, so this is likely to be one of the older protocols, most likely 3.3 I would guess.  Do note that the local key is changed every time you pair the mobile app, so if you captured the local key some time ago, and later re-paired the device, the key may have changed.  It is a bit strange that it was connecting 3 weeks ago when you made the original report, but has since stopped working.  it should work with the settings you used back then.

**Comment by robinhood-code** [comment]
I have the exact same issue with this device. Worked initially during pairing and then suddenly not working on one day while all the settings have not been changed.

Also got the same “check key error” in the log but it was 3.3 that was working and suddenly it’s not accepting.

Confirmed the local key is the same as found on iot.tuya.com.

Confirmed the IP is correct. 

Device is fully working in Tuya app, and sometime after playing a bit in the Tuya app, Tuya Local could connect it again but it usually will only last a day or so, before it became unavailable again and couldn’t connect it anymore. 

Any idea is welcome.
