### ISSUE TITLE
Failed to fetch device status - same or similar to #1197

### ISSUE THREAD

**Issue by Zodiac-69** [make-all/tuya-local#1521]
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**
Device goes "Off Line" in HA but is still working via the Tuya Smart app.

**To Reproduce**
Random, there is no fixed interval where this happens.
Only way to get them back online is to switch the power off and then on again. 

**Expected behaviour**

**Additional context**
The lights are always on.
This is only happening with my lights.
They are all the same type - A60 1800-2700K RGBWW light Brand is BNETA

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

See attached File - tuya_local-LS1.json.txt
[tuya_local-LS1.json.txt](https://github.com/make-all/tuya-local/files/13930620/tuya_local-LS1.json.txt)

Please check if there are messages from Tuya Local in the Home
This error originated from a custom integration.

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:548
Integration: Tuya Local (documentation, issues)
First occurred: 08:42:35 (25 occurrences)
Last logged: 08:44:08

Failed to fetch device status for LS1

![image](https://github.com/make-all/tuya-local/assets/2076401/dee47481-143e-45f0-82a3-5fecefd10805)

After i Cycled the power
![image](https://github.com/make-all/tuya-local/assets/2076401/892a7c89-03e3-4c49-9836-46b10e74be00)

**Comment by make-all** [comment]
Wireless networks are inherently unreliable, and Tuya devices may contain unknown bugs themselves.  If you are going to assert that there is a bug in the integration, then you need to come with evidence that can be acted on, not just speculation.  From the evidence you have presented, the bug is in the device that needs to be power cycled to recover.

**Comment by Zodiac-69** [comment]
So i did some more digging...
Ran TinyTuya on a seperate RPI and when the bulb goes offline in tuya-local(HA), TinyTuya is also not able to connect to the bulb.
I used "Fing" to try and ping the bulb, no response.
Checked for open ports, no open ports reported.

But the bulb is still working via the Tuya app.
So it seems that the Tuya bulbs "crash" and that you can't ping the device thus port 6668 is no longer accessible and that is why the bulb goes offline in HA.

Not sure what port is used by the Tuya app, but even though i am unable to ping the device, it still function via the Tuya app.

**Comment by make-all** [comment]
The Tuya app is able to access via the cloud when the local connection is not working.  The cloud is an outgoing connection, so even when the device is not accepting incoming requests, or responding to pings, it may be still connecting out to the cloud.  Perhaps it has changed its IP address.

**Comment by andystewart999** [comment]
When the bulb is in this state, are you able to do a packet capture on it to see if it's still initiating outbound connections to the Tuya cloud?

**Comment by Anj-0110** [comment]
> So i did some more digging... Ran TinyTuya on a seperate RPI and when the bulb goes offline in tuya-local(HA), TinyTuya is also not able to connect to the bulb. I used "Fing" to try and ping the bulb, no response. Checked for open ports, no open ports reported.
> 
> But the bulb is still working via the Tuya app. So it seems that the Tuya bulbs "crash" and that you can't ping the device thus port 6668 is no longer accessible and that is why the bulb goes offline in HA.
> 
> Not sure what port is used by the Tuya app, but even though i am unable to ping the device, it still function via the Tuya app.

Zodiak-69, I am experiencing the same or similar thing.  I have a couple devices in HA that seem to lose the TL connection but I can still control them through the app.  When I cycle the power all devices come back to the TL integration but randomly lose 1-3 lights devices.

Did you find a solution?

**Comment by Zodiac-69** [comment]
HiAnj-0110

I am still verifying, but initial results are promising.
I use Ubiquity AP's and looking on the forums, it seems that Tuya bulbs do not play well with WiFi.

On my setup, i have 3x Ubiquity AP's all with the same SSID.

This is what i have done so far and my Tuya bulbs are staying online so far.
1. All devices have Static IP's
2. Create a separate SSID for my IoT units, 2.4GHz only.
3. Disable the following:
  a. Band Steering
  b. BSS Transition
  c. Roaming / Fast Roaming
  d.PMF
  e. Uplink connectivity Monitoring
  f. Auto optimize network

So far it has made a huge difference.

I still want to do the following that was recommended as well.
X. Channel bandwidth to VTH20
Y. Set fixed channels to each AP, CH.1 and CH.11 is recommended.

Hope this can assist you

**Comment by HGRT846** [comment]
Hello, I also have this problem, my tuya sockets were randomly gone unavailable, I tried a lot, but the only thing that really helped me was changing the encryption on the WiFi to WPA only, now after several days I have only one socket which still throws "Failed to fetch device status" errors sometimes, I think it might be misunderstanding in protocol version, how do I find the right version to use with my socket? (BTW, they are two different sockets) Thanks in advance!

**Comment by Zodiac-69** [comment]
Just some feedback.
Since implementing the changes listed above - [,](https://github.com/make-all/tuya-local/issues/1521#issuecomment-1944313323) - i have not had any of my Tuya bulbs go off line.

For now i am not making any changes until the end of March.

**Comment by Anj-0110** [comment]
I have recently acquired a Ubiquite UDR and 2 AC lite AP's.  I have gone through and matched all the devices with static IP's on a dedicated 2.4 SSID and took your suggestions on the settings.  I will give it a couple days to see how things react and communicate.  I have a lot of TUYA, they were relatively cheap and were purchased prior to diving into HASS.

Thanks for the suggestions!

**Comment by Zodiac-69** [comment]
Just some feedback (2)
All my Tuya bulbs have now remained online and available in Tuya-local since i implemented the changed listed in my post above. Not once, did i have to power cycle my Tuya bulbs since i made the changes.

I think that i can say that the issues i had were all related to Tuya bulbs and their wifi implementation.
For me it was only my Tuya bulbs, they are all the same type (RGB Color Control + White Temp Control (Warm White 2700K ~ Cool White 6500K) 230V, 9W, 806lm) that was going off line, my other Tuya devices did not and were always available in HA.

So i think i can safely say that changing the settings has resolved my issues.
Next step is to move my devices to a VLAN.

**Comment by Anj-0110** [comment]
So...
It has only been less than 24 hours and I am at a loss with the connectivity!?  I cannot figure out why I am losing connectivity, it is not just tuya lights.  I am not sure if it is the tuya-local integration, my wifi or other issues that I am not aware of.  When I log into the unifi-os web app, and go to the clients I have a range of poor to excellent status for the 60 devices connected through the UDR.  One specific device, a smart plug is 2' from the AP and the status is excellent but in the TL integration is bounces from connected to unavailable, why would this be? Also, the tuya lights, specifically INFIBRITE 6" RGBW, similar to your lights are unavailable randomly through HA but are connected in the UNIFI-OS.  Also to mention, I have connected all the devices through the SMARTLIFE app on my phone, when I check the connection it also shows them as offline.

You mentioned changing the bandwidth, I don't see where to do this in the unifi-os?

The below screenshot are just some of the lights that lose connection. 
![image](https://github.com/make-all/tuya-local/assets/124223141/2b607be2-6b6d-4b6e-adaa-5255c3c93fe0)

This screenshot is a light device that is next to the UDR and the status of its connection through the unifi-os
![image](https://github.com/make-all/tuya-local/assets/124223141/2e8f725d-5e31-42f3-ac9d-5d17dc5aa0d1)

 

I don't know what else to try?  What am I doing wrong?  Any advice?

**Comment by Zodiac-69** [comment]
Hi Anj-0110

Not sure why your Tuya bulbs are going offline.
To set the bandwidth (This is a "Global" setting on your AP and will affect ALL SSID's),
Left hand menu: - Double round circle - Unifi Decices
Select the AP and click on the "Gear" icon.
2.4GHz, you can select: 20 or 40MHz as the bandwidth.
Next to that you can also select the WiFi CH you want to set the AP to use.

I do not run my UniFi software the whole time.
I only run it when i have issues, or want to make changes, else the UniFi network app is not running.

**Comment by Anj-0110** [comment]
Hi Z-

Just sending an update...

I have taken a little different approach and have had success so far.  One critical sequence I didn't perform prior to my previous post was power cycle the devices.  With your setting suggestions HA was seeing all the devices and seemed to hold the connection.  However, after some reading and learning, in my environment, I set the bandwidth to 20 and the power of the channel to low.  I have 3 AP's in my house.  I read it was recommended to narrow the channel and decrease the power, otherwise there is too much noise the clients have to try and decide which AP to connect to.  Since doing so, I have all excellent wifi connections but more importantly, HA is not dropping the device as unavailable.  I will let this ride and fingers crossed this headache is behind me!!

Thanks for your suggestions!
