### ISSUE TITLE
BHT-002GALW - partly working

### ISSUE THREAD

**Issue by maierei** [make-all/tuya-local#154]
Hi,
adding the device works fine.
Termperature values and current state from device show up in HA.
Changing temperature or turning the device off in HA leads to "not available" message. Sometimes message dissapears after longer time and values show up again. 
But still changes are mostly not transferred to device.
Thanks.

**Comment by make-all** [comment]
Which config are you using?  There are currently two different "BHT-002" devices supported.  The designation seems to be commonly used by not quite compatible clones, and I don't know how many more configs will be needed.

**Comment by maierei** [comment]
I need a little more information about what you call "which config" - sorry.

**Comment by make-all** [comment]
When adding the integration, you are prompted to choose which device config to use.  This will also be used for the default name for the entities created, so if you do not remember which device you chose, the entity name may be a clue.

**Comment by Simonz82** [comment]
Hi @make-all 
I have the same problem, I see temperature and 3 buttons (calendar, fire, on/off)
but when I click from calendar to fire (to switch the thermostat in manual) temperature disappears and gives me "NOT AVAILABLE".
is it possible to do something ?
when registering the product in HA I chose BHT-002 is it wrong?
can I give you some product data to help you understand if there are any problems or if you have any ideas ?
thanks

**Comment by make-all** [comment]
Most likely your BHT-002 has different valid values for the mode DPS.

If you can capture the data in different modes (switched from the panel,
captured either using tuya-cli or by enabling debug logging for tuya-local
in configuration.yaml and restarting (there may be a reload option for
logging, I do not have HA running right now as I am away from home for a
few weeks so I cannot check).

**Comment by maierei** [comment]
Okay, I understand  - I have registered the device as BHT-002. 
I will try to enable the debug log and attach it here.

**Comment by maierei** [comment]
I have an update: After I turned off internet access for the device via my router controlling the device via HA seems to work fine and very fast. It will need more tests... will update this topic here.
