### ISSUE TITLE
Request support for Tonepie T1PRO (Automatic Cat Litter Box)

### ISSUE THREAD

**Issue by AprovelPD** [make-all/tuya-local#1541]
# Log Message

```
Device matches tuya_smart_zigbee_door_sensor with quality of 4%. DPS: {"updated_at": 1705566179.3904612, "6": 5549, "7": 1, "8": 25, "17": false, "22": 0, "101": false, "102": false, "104": false, "105": true, "109": true, "111": true, "114": false, "117": 3, "118": 15, "119": false, "120": false, "121": false, "122": false, "123": 1, "124": 4, "125": 3, "126": true, "127": 1500, "128": 0}
Device matches tuya_smart_zigbee_door_sensor with quality of 4%. DPS: {"updated_at": 1705584174.547205, "6": 5367, "7": 1, "8": 39, "17": false, "22": 0, "101": false, "102": false, "104": false, "105": true, "109": true, "111": true, "114": false, "117": 3, "118": 15, "119": false, "120": true, "121": false, "122": false, "123": 1, "124": 4, "125": 3, "126": true, "127": 1500, "128": 0}
```

# Information about DPS mappings

```
{"6":"Cat Weight","7":"excretion times day","8":"Excretion Time","17":"Deodorization","22":"Fault","101":"clean","102":"empty","103":"trash status","104":"monitoring","105":"auto","106":"clean time","107":"clean time switch","108":"版本识别","109":"备用版本识别","110":"not disturb","111":"Infrared Radar Sensor Off","112":"toilet notice","113":"net notice","114":"Kids Lock","115":"calibration","116":"unit","117":"Clumping Time","118":"Cleaning Interval","119":"store full notify","120":"Deordrizer","121":"Smart clean","122":"Non-disturbing","123":"Usage Times","124":"Waste Bin Calibration","125":"Litter Leveling Setting","126":"Auto Deordrizer Setting","127":"Detection Sensitivity","128":"number"}
```

```
        "name": "Selbstreinigende Katzentoilette",
        "id": "bf9eee32eb29e02b82m53q",
        "key": "xxxxxxxxxx",
        "mac": "xxxxxxxxxxxxxx",
        "uuid": "63af5ab405fd9f46",
        "sn": "xxxxxxxxxxxx",
        "category": "msp",
        "product_name": "Automatic Cat Litter Box",
        "product_id": "5t7esmqqh92ssbe5",
        "biz_type": 0,
        "model": "\u5ba0\u7269\u732b\u7802\u76c6",
        "sub": false,
        "icon": "https://images.tuyaeu.com/smart/icon/bay1627386467137Cb6K/c7ac5dd09c3e82ef441604d913b6795d.png",
        "mapping": {
            "6": {
                "code": "cat_weight",
                "type": "Integer",
                "values": {
                    "unit": "g",
                    "min": 600,
                    "max": 10000,
                    "scale": 0,
                    "step": 1
                }
            },
            "7": {
                "code": "excretion_times_day",
                "type": "Integer",
                "values": {
                    "unit": "times",
                    "min": 0,
                    "max": 60,
                    "scale": 0,
                    "step": 1
                }
            },
            "8": {
                "code": "excretion_time_day",
                "type": "Integer",
                "values": {
                    "unit": "s",
                    "min": 0,
                    "max": 1800,
                    "scale": 0,
                    "step": 1
                }
            },
            "17": {
                "code": "deodorization",
                "type": "Boolean",
                "values": {}
            },
            "22": {
                "code": "fault",
                "type": "Bitmap",
                "values": {
                    "label": [
                        "motor_fault",
                        "program_fault",
                        "g_sensor_fault"
                    ],
                    "maxlen": 3
                }
            }
        },
        "ip": "xxx.xx.xx.xx",
        "version": "3.4"
```

or https://github.com/tuya/tuya-home-assistant/issues/935

# Product ID
5t7esmqqh92ssbe5

# Information about how the device functions
A rotating Cat Toilet.
You can start the cleaning manually and automatic, Deodorization manually or automatic,
Weight your cat, Do not Disturb Rules, Time measurement, how often was you cat, alert when bag is full
calibrate full, calibrate clumping time, calobrate litter level, turn on/off infrared sensor...

**Comment by AprovelPD** [comment]
Functions via Tuya Smart App:
Excretion Time in seconds
Excretion Times per day
Cat weight in gramms
Enable/Disable Auto Mode
Clean per Button
Deordrizer per Button
Empty all per Button
Set Clumping Time in minutes
Set cleaning intervall in minutes
Enable/Disable Kids Lock
Enable/Disable Infrared Radar Sensor (Enabled = Off / Dissabled = on)
Set Time-Schedule for "Do Not Disturb"
Set Times for plannend cleaning
Set Times for Deodorizer
Calibration Value for Waste Bin Full (0-15)
Calibration Value for litter level (0-6)

**Comment by make-all** [comment]
It seems like for each function there is a switch to control whether it is automatic, and a button to trigger it manually.  From the details given it is not possible to figure out which is which.  Are you able to give any more details about the function of each dp?

**Comment by AprovelPD** [comment]
I have translated all the Chinese characters into English. 
Furthermore, I have formatted the whole thing a bit nicer and put my comment below each one for explanation. 

abilityId:6,
accessMode:ro,
code:cat_weight,
description:Regularly report the weight of cats, support multiple cats weighing, APP terminal can manually classify different cats with different weights.,
extensions:
	iconName:icon-dp_mode,
	attribute:1024,
name:Cat Weight,
typeSpec:
	max:10000,
	min:600,
	scale:0,
	step:1,
	type:value,
	typeDefaultValue:600,
	unit:g
- This value should reflect the weight of the cat in gramms. 

abilityId:7,
accessMode:ro,
code:excretion_times_day,
description:After the cat defecates, the total number of defecations for the day is reported on the device side and displayed on the APP side,
extensions:
	iconName:icon-dp_0,
	attribute:1024,
name:Number of defecations per day,
typeSpec:
	max:60,
	min:0,
	scale:0,
	step:1,
	type:value,
	typeDefaultValue:0,
	unit:times
- This value indicates the frequency of use per day.

abilityId:8,
accessMode:ro,
code:excretion_time_day,
description:After the cat defecates, the device side reports the duration of the current defecation, and the APP side carries out the display of the trend of the duration at different times,
extensions:
	iconName:icon-dp_time,
	attribute:1024,
name:length of visit to the toilet,
typeSpec:
	max:1800,
	min:0,
	scale:0,
	step:1,
	type:value,
	typeDefaultValue:0,
	unit:seconds
- This value indicates the duration in seconds of use per day.
	
abilityId:17,
accessMode:rw,
code:deodorization,
description:Deodorizing and sterilizing switch,
extensions:
	iconName:icon-dp_filter,
	attribute:1024,
name:deodorize and sterilize,
typeSpec:
	type:bool,
	typeDefaultValue:false
-

abilityId:22,
accessMode:ro,
code:fault,
description:motor_fault：motor failure program_fault：program error g_sensor_fault：Abnormal gravity sensor sensing,
extensions:
	iconName:icon-baojing,
	attribute:1024,
name:Fault Alarms,
typeSpec:
	label:[motor_fault,program_fault,g_sensor_fault],
	maxlen:3,
	type:bitmap,
	typeDefaultValue:0
-
	
abilityId:101,
accessMode:rw,
code:Clean,
description:1 Start 0 Close,
name:One-Click Cleanup,
typeSpec:
	type:bool,
	typeDefaultValue:false
- Switch to start the clean process manually one time

abilityId:102,
accessMode:rw,
code:empty,
description:1 Start 0 Cancel,
name:One click to change sand,
typeSpec:
	type:bool,
	typeDefaultValue:false
- Switch to start the empty process manually one time (let all litter fall in to trash bag)

abilityId:103,
accessMode:ro,
code:trash_status,
description:0 Trash can is empty, cue text disappears 1 Trash can is full, cue text,
name:Trash can status,
typeSpec:
	type:bool,
	typeDefaultValue:false
- i dont exactly know what this switch is for...
	
abilityId:104,
accessMode:ro,
code:monitoring,
description:When the cat enters, a text message appears, and disappears when the cat leaves.,
name:Barrel monitoring
typeSpec:
	type:bool,
	typeDefaultValue:false
- this monitors if the cat enters or leave the toilet ("cat left" or "Cats approach or enter")

abilityId:105,
accessMode:rw,
code:Induction_Clean,
description:,
name:Induction cleaning,
typeSpec:
	type:bool,
	typeDefaultValue:false
- Activates automatic cleaning Independent of ID 107 and 106 i think
	
abilityId:106,
accessMode:rw,
code:clean_time,
description:Each time according to the hour-minute format, each occupies 2 bytes, minutes and hours, decimal to hexadecimal, such as 18:50, converted to hexadecimal for 1232. period for the binary week or a single valid. Supports up to three time settings, unset with 0 supplement. Example: 12320013200000000000,
name:regular cleaning,
typeSpec:
	maxlen:128,
	type:raw
- time shedule for cleaning by time

abilityId:107,
accessMode:rw,
code:clean_time_switch,
description:If activated, the schedule of ID 106 comes into effect.,
name:Timed cleaning switch,
typeSpec:
	type:bool,
	typeDefaultValue:false
- this should be the switch to activate the sheduled cleaning	

abilityId:108,
accessMode:rw,
code:Clean_taste,
description:Each time according to the hour-minute format, each occupies 2 bytes, minutes and hours, decimal to hexadecimal, such as 18:50, converted to hexadecimal for 1232. period for the binary week or a single valid. Supports up to three time settings, unset with 0 supplement. Example: 12320013200000000000,
name:version identification,
typeSpec:
	maxlen:128,
	type:raw
- i dont know exactly...

abilityId:109,
accessMode:rw,
code:Clean_tasteSwitch,
description:,
name:Alternate version identification,
typeSpec:
	type:bool,
	typeDefaultValue:false
- again i dont know
	
abilityId:110,
accessMode:rw,
code:not_disturb,
description:,
name:distraction-free,
typeSpec:
	maxlen:128,
	type:raw
- i think this is the sheduled "do not disturb" time plan like ID 106

abilityId:111,
accessMode:rw,
code:Clean_notice,
description:Infrared function on or off,
name:Turn off infrared to accommodate cat houses,
typeSpec:
	type:bool,
	typeDefaultValue:false
- i dont know exactly, its translated. there is a switch to activate the infrared sensor (switch off = activat, switch on = deactivated)

abilityId:112,
accessMode:rw,
code:toilet_notice,
description:,
name:Toilet notification,
typeSpec:
	type:bool,
	typeDefaultValue:false
- i dont know 

abilityId:113,
accessMode:rw,
code:Net_notice,
description:Can be used for drum bin reset only if a fault is triggered,
name:Barrel bin reset,
typeSpec:
	type:bool,
	typeDefaultValue:false
- dont know

abilityId:114,
accessMode:rw,
code:child_lock,
description:,
name:children's lock,
typeSpec:
	type:bool,
	typeDefaultValue:false
- acivated or deactivates the sensor touch panel on the device itself

abilityId:115,
accessMode:rw,
code:calibration,
description:calibration,
extensions:
	trigger:direct,
name:Scale Calibration,
typeSpec:
	type:bool,
	typeDefaultValue:false
- i saw in debugging its on for me, but i dont know what this is doing...

abilityId:116,
accessMode:rw,
code:unit,
description:,
name:unit (of measure),
typeSpec:
	type:bool,
	typeDefaultValue:false
- dont know - in debugging i have 0 events from this

abilityId:117,
accessMode:rw,
code:induction_delay,
description:,
name:Clearance wait time,
typeSpec:
	max:60,
	min:0,
	scale:0,
	step:1,
	type:value,
	typeDefaultValue:0,
	unit:minutes
- how much time to wait after cat left the toilete to clean 

abilityId:118,
accessMode:rw,
code:induction_interval,
description:,
name:Clearance interval,
typeSpec:
	max:120,
	min:0,
	scale:0,
	step:1,
	type:value,
	typeDefaultValue:0,
	unit:minutes
- time to clean every x minutes

abilityId:119,
accessMode:rw,
code:store_full_notify,
description:,
name:Maneuvering bin full notification,
typeSpec:
	type:bool,
	typeDefaultValue:false
- goes on when trash is full

abilityId:120,
accessMode:rw,
code:odourless,
description:,
name:Instant Odor Cleaning,
typeSpec:
	type:bool,
	typeDefaultValue:false
- goes on when odor cleaning starts

abilityId:121,
accessMode:rw,
code:smart_clean,
description:,
name:Smart Cleanup,
typeSpec:
	type:bool,
	typeDefaultValue:false
- is one when smart clean is activeated (just clean when cat enters and left)

abilityId:122,
accessMode:rw,
code:not_disturb_Switch,
description:,
name:Do Not Disturb switch,
typeSpec:
	type:bool,
	typeDefaultValue:false
- goes on when dnd is active or manually activate

abilityId:123,
accessMode:rw,
code:usage_times,
description:,
extensions:
	trigger:direct,
name:Number of times used,
typeSpec:
	max:100,
	min:1,
	scale:0,
	step:1,
	type:value,
	typeDefaultValue:1,
	unit:times
- in debugging it shows every time cat enters "	1times"

abilityId:124,
accessMode:rw,
code:capacity_calibration,
description:,
extensions:
	trigger:direct,
name:Bins are full and calibrated.,
typeSpec:
	max:15,
	min:0,
	scale:0,
	step:1,
	type:value,
	typeDefaultValue:0,
	unit:
- thats a number to calibrate the trash bag from 0-15 

abilityId:125,
accessMode:rw,
code:sand_surface_calibration,
description:,
extensions:
	trigger:direct,
name:Litter calibration,
typeSpec:
	max:6,
	min:0,
	scale:0,
	step:1,
	type:value,
	typeDefaultValue:0,
	unit:
- thats a number to calibrate the movements to get a sand litter surface... 

abilityId:126,
accessMode:rw,
code:auto_deordrizer,
description:,
name:Automatic odor elimination,
typeSpec:
	type:bool,
	typeDefaultValue:false
- true = activate odor elimantation automatcially after usage_times; false = dont do anything

abilityId:127,
accessMode:rw,
code:detection_sensitivity,
description:,
extensions:
	trigger:direct,
name:detection sensitivity,
typeSpec:
	max:1500,
	min:600,
	scale:0,
	step:100,
	type:value,
	typeDefaultValue:600,
	unit:g
- how much grams should enter the toilete to recognize the cat

abilityId:128,
accessMode:rw,
code:number,
description:,
extensions:
	trigger:direct,
name:number,
typeSpec:
	max:999999,
	min:0,
	scale:0,
	step:1,
	type:value,
	typeDefaultValue:0,
	unit:
- i have no idea, all the time 0

**Comment by Schmandre** [comment]
Hello, I got the same toilet and device got assigned as door sensor. 

Cause I see a lot of work here and status "new device" and "unreleased", how can I learn the device, so that is working atm? Is there a "beta branch" for this?

Br
Schmandre

**Comment by make-all** [comment]
This device is supported in the latest release.

**Comment by Schmandre** [comment]
Whatever I did wrong. Installed the repo thorugh hacs yesterday. Now I changed to "main" branch and I could setup. Thank you for your work
