### ISSUE TITLE
3 phase tuya breaker have an error. Only 1 phase shows.

### ISSUE THREAD

**Issue by vpaulos** [make-all/tuya-local#1543]
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**
Added device tuya 3 phase breaker with power metter, but shows only phase A info 

**To Reproduce**
adding while "next-next" pushing

**Expected behavior**
we need to see all 3 phase info about curr+volt+power

**Additional context**
i can send you add photo

![tuya_original_snapshot](https://github.com/make-all/tuya-local/assets/48480823/8b78c633-0514-4b72-a2a2-4d8c8d2ff433)

DP from api for this device

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

**Comment by vpaulos** [comment]
your integration shows only this:
![tuya_local_snapshot](https://github.com/make-all/tuya-local/assets/48480823/ffaa4379-df7b-4ff0-83f9-0798de900edd)

**Comment by vpaulos** [comment]
DP from iot.tuya
{
  "result": {
    "properties": [
      {
        "code": "total_forward_energy",
        "custom_name": "",
        "dp_id": 1,
        "time": 1705343311369,
        "value": 492756
      },
      {
        "code": "phase_a",
        "custom_name": "",
        "dp_id": 6,
        "time": 1705343361816,
        "value": "CUMAApoAAHI="
      },
      {
        "code": "phase_b",
        "custom_name": "",
        "dp_id": 7,
        "time": 1705343368020,
        "value": "CXMAAKgAABM="
      },
      {
        "code": "phase_c",
        "custom_name": "",
        "dp_id": 8,
        "time": 1705343359714,
        "value": "CT0AAuoAAE0="
      },
      {
        "code": "fault",
        "custom_name": "",
        "dp_id": 9,
        "time": 1705342633409,
        "value": 0
      },
      {
        "code": "switch_prepayment",
        "custom_name": "",
        "dp_id": 11,
        "time": 1705342771453,
        "value": false
      },
      {
        "code": "clear_energy",
        "custom_name": "",
        "dp_id": 12,
        "time": 1675929948398,
        "value": false
      },
      {
        "code": "balance_energy",
        "custom_name": "",
        "dp_id": 13,
        "time": 1705342771973,
        "value": 0
      },
      {
        "code": "charge_energy",
        "custom_name": "",
        "dp_id": 14,
        "time": 1705342631276,
        "value": 100000
      },
      {
        "code": "leakage_current",
        "custom_name": "",
        "dp_id": 15,
        "time": 1705343363806,
        "value": 6
      },
      {
        "code": "switch",
        "custom_name": "",
        "dp_id": 16,
        "time": 1705341986996,
        "value": true
      },
      {
        "code": "alarm_set_1",
        "custom_name": "",
        "dp_id": 17,
        "time": 1705343365929,
        "value": "AwEAGQQBADIFAQA3"
      },
      {
        "code": "alarm_set_2",
        "custom_name": "",
        "dp_id": 18,
        "time": 1705343366927,
        "value": "AQEAKAMBARMEAAC5CAAAAA=="
      },
      {
        "code": "breaker_id",
        "custom_name": "",
        "dp_id": 19,
        "time": 1705341986996,
        "value": "4294967295"
      },
      {
        "code": "leakagecurr_test",
        "custom_name": "",
        "dp_id": 21,
        "time": 1693504326283,
        "value": false
      }
    ]
  },
}

**Comment by make-all** [comment]
The device diagnostics are required to determine which specific device this report is about, and what data is being received from it.

**Comment by vpaulos** [comment]
how can I heklp you in this case?

**Comment by make-all** [comment]
Download the diagnostics and post here.

![image](https://github.com/make-all/tuya-local/assets/9624699/ecfd3058-4706-4bc6-a8f0-50000af8f51d)

**Comment by vpaulos** [comment]
SORRY FOR THIS TIME PAUSE. fILE.

[Uploading tuya_local-9560bb8ef940ae66abe5bc23bc1291fc-a.int.electricity-349c9b41dbbdc0f08c2df9ba7c5cb4ef.json.txt…]()

**Comment by vpaulos** [comment]
AND THIS IS FILE FROM TUYA WEB INTEGRATION

[tuya-c175dca8bc2ad52a66f24e8594c8b289-a.int.electricity.total-5fcfbd40a7783aae02829624391396f1.json.txt](https://github.com/make-all/tuya-local/files/14102983/tuya-c175dca8bc2ad52a66f24e8594c8b289-a.int.electricity.total-5fcfbd40a7783aae02829624391396f1.json.txt)

**Comment by make-all** [comment]
You have configured this as TOMPD 63LW, which is a single phase device.  The behaviour described is expected.
