### ISSUE TITLE
TTEC vacuum

### ISSUE THREAD

**Issue by ops244** [make-all/tuya-local#1545]
I do not know what to do with this vacuum cleaner, it is already boring...  
after the previous fix, the cleaning start button is no longer pressed (while everything works through the voice assistant) and outputs a bunch of errors
previous fix - https://github.com/make-all/tuya-local/issues/1509
-------------------------

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:238
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 11:19:18 (1 occurrences)
Last logged: 11:19:18

[281472147770816] Entity vacuum.pylesos does not support this service.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 864, in entity_service_call
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity vacuum.pylesos does not support this service.

![2024-01-20_11-29-35](https://github.com/make-all/tuya-local/assets/19797600/471c1a30-f8af-4ae2-92fe-550dd83b60aa)

**Comment by ops244** [comment]
if the voice assistant works without errors, maybe there is another command to start cleaning?

**Comment by ops244** [comment]
now there are no errors, but it doesn't start either

**Comment by ops244** [comment]
Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:225
Integration: Tuya Local ([documentation](https://github.com/make-all/tuya-local), [issues](https://github.com/make-all/tuya-local/issues))
First occurred: 17:38:50 (1 occurrences)
Last logged: 17:38:50

Пылесос receive loop has terminated

**Comment by ops244** [comment]
it does not start (the voice assistant does not work either, although it worked before)
the same error when adding
--------------------------------------
Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:225
Integration: Tuya Local ([documentation](https://github.com/make-all/tuya-local), [issues](https://github.com/make-all/tuya-local/issues))
First occurred: 07:48:49 (1 occurrences)
Last logged: 07:48:49

Пылесос receive loop has terminated

**Comment by make-all** [comment]
"the same error when adding"

It seems like you are maybe adding multiple copies of the integration?  You should only need to add each device once.  Even if the config changes, you do not need to add it again.

**Comment by ops244** [comment]
Yes, you're right, the mistake is because of this
maybe you still need some information? it still doesn't start cleaning (other buttons are working)

**Comment by make-all** [comment]
Maybe I misunderstood the function of those first three dps.  I have made another attempt with another combination.  This time, the logic should set switch_go to true when start is pressed, and pause to true when pause is pressed.  These two dps are assumed to work together now.

**Comment by ops244** [comment]
does not work
before this fix, the start worked, but did not return to the base https://github.com/make-all/tuya-local/issues/1491
then he began to return to the base, but the start does not work, but the voice assistant starts cleaning (only the button does not work)
after the last fix does not work at all

**Comment by make-all** [comment]
I don't understand this. There is no start button in the screeenshots in #1491, according to the history of the config, the start button would not have started appearing until the first fix on this issue yesterday.

**Comment by ops244** [comment]
there was a click on the phrase "start cleaning" and it started, it is still there, but it does not work
![2024-01-21_15-06-26](https://github.com/make-all/tuya-local/assets/19797600/981bc2a8-99d5-45c3-8dec-c4c5bdb030b6)

**Comment by ops244** [comment]
if there are no more ideas, then return this yaml, at least the voice assistant works here
[ttec_reobipro_vacuum.zip](https://github.com/make-all/tuya-local/files/14009669/ttec_reobipro_vacuum.zip)

**Comment by make-all** [comment]
I think a comment on #1393 has helped to understand how the switch_go, pause and switch_charge dps operate.

I have separated them out as buttons in case the vacuum is still not working correctly with them.

**Comment by ops244** [comment]
now it says "the device is not supported"
--------------------------------------------------
Device matches None with quality of 0%. DPS: {"updated_at": 1706343412.8754532, "4": "chargego", "5": "charge_done", "6": 0, "7": 0, "8": 100, "9": "strong", "10": "closed", "17": 189, "19": 289, "21": 139, "23": 149, "26": 8, "28": 0}

**Comment by ops244** [comment]
maybe I should run it through the cloud in tuya? is there anything useful to learn there? Everything works there
