### ISSUE TITLE
The use of sensor for Inventor Eva Ion Pro dehumidifier is deprecated and should be replaced by humidifier.

### ISSUE THREAD

**Issue by DariukaB** [make-all/tuya-local#1546]
This error originated from a custom integration.

Logger: custom_components.tuya_local.helpers.config
Source: custom_components/tuya_local/helpers/config.py:46
Integration: Tuya Local (documentation, issues)
First occurred: 21:30:54 (1 occurrences)
Last logged: 21:30:54

The use of sensor for Inventor Eva Ion Pro dehumidifier is deprecated and should be replaced by humidifier.

**Comment by make-all** [comment]
Not a bug. The humidity is available in the humidifier now, so this is a warning to the user that the separate sensor is deprecated and may be removed in future, in case you are relying on it for automations etc.
