### ISSUE TITLE
Request support for smart kettle Proficoock PC-WKS 1167 G

### ISSUE THREAD

**Issue by znack14** [make-all/tuya-local#1552]
Good day.  Please add the device: Profi Cook PC-WKS 1167 G smart kettle. I was able to get 2 sensors and one switch from it through integration.  The sensors show the set temperature that the kettle should maintain in Keep Warm mode, and modes 0.6, 05, 04 - which change if you switch modes in the kettle itself or in the mobile application.  It's also strange that the integration saw the kettle as an IR remote, and there's also one control that gives an error when pressed...calling the remote turn.off function.  I am ready to provide all the necessary data and access to the Tuya account.

**Comment by dingausmwald** [comment]
Hey there. Why this wasn't implementend? Also looking for this

**Comment by dingausmwald** [comment]
{
  "result": {
    "model": "{\"modelId\":\"000004j85x\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"Mode\",\"description\":\"0：奶粉（45℃）\\n1：蜜水 （60℃）\\n2：绿茶 （85℃）\\n3：红茶（除氯3分钟）\\n4：煮沸\\n5：保温\\n6：取消\",\"name\":\"工作模式\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\"]}},{\"abilityId\":102,\"accessMode\":\"rw\",\"code\":\"SetTem\",\"description\":\"默认70℃\",\"name\":\"温度设置\",\"typeSpec\":{\"type\":\"value\",\"max\":95,\"min\":30,\"scale\":0,\"step\":1,\"unit\":\"℃\"}},{\"abilityId\":104,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"0：干烧报警\\n1：水壶故障\\n2：少水报警\\n\",\"extensions\":{\"scope\":\"fault\"},\"name\":\"故障告警\",\"typeSpec\":{\"type\":\"bitmap\",\"label\":[\"0\",\"1\",\"2\"],\"maxlen\":3}},{\"abilityId\":105,\"accessMode\":\"ro\",\"code\":\"Tem\",\"description\":\"\",\"name\":\"当前温度\",\"typeSpec\":{\"type\":\"value\",\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"℃\"}},{\"abilityId\":106,\"accessMode\":\"ro\",\"code\":\"state\",\"description\":\"0：未连接\\n1：壶座分离\\n2：空闲中\\n3：加热中\\n4：冷却中\\n5：保温中\\n\",\"name\":\"当前状态\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\"]}},{\"abilityId\":107,\"accessMode\":\"ro\",\"code\":\"countdown\",\"description\":\"mcu上报\",\"name\":\"倒计时剩余时间\",\"typeSpec\":{\"type\":\"value\",\"max\":240,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"分钟\"}},{\"abilityId\":108,\"accessMode\":\"ro\",\"code\":\"timer\",\"description\":\"\",\"name\":\"倒计时\",\"typeSpec\":{\"type\":\"value\",\"max\":240,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"分钟\"}}]}]}"
  },
  "success": true,
  "t": 1731943528768,
  "tid": "575d3266a5c111efbd65e6107338fc03"
}

**Comment by dingausmwald** [comment]
{
  "result": {
    "model": {
      "modelId": "000004j85x",
      "services": [
        {
          "actions": [],
          "code": "",
          "description": "",
          "events": [],
          "name": "Default Service",
          "properties": [
            {
              "abilityId": 101,
              "accessMode": "rw",
              "code": "Mode",
              "description": "0: Milk Powder (45℃)\n1: Honey Water (60℃)\n2: Green Tea (85℃)\n3: Black Tea (Chlorine removal for 3 minutes)\n4: Boil\n5: Keep Warm\n6: Cancel",
              "name": "Operation Mode",
              "typeSpec": {
                "type": "enum",
                "range": ["0", "1", "2", "3", "4", "5", "6"]
              }
            },
            {
              "abilityId": 102,
              "accessMode": "rw",
              "code": "SetTem",
              "description": "Default 70℃",
              "name": "Set Temperature",
              "typeSpec": {
                "type": "value",
                "max": 95,
                "min": 30,
                "scale": 0,
                "step": 1,
                "unit": "℃"
              }
            },
            {
              "abilityId": 104,
              "accessMode": "ro",
              "code": "fault",
              "description": "0: Overheating Alert\n1: Kettle Malfunction\n2: Low Water Alert",
              "extensions": {
                "scope": "fault"
              },
              "name": "Fault Alert",
              "typeSpec": {
                "type": "bitmap",
                "label": ["0", "1", "2"],
                "maxlen": 3
              }
            },
            {
              "abilityId": 105,
              "accessMode": "ro",
              "code": "Tem",
              "description": "",
              "name": "Current Temperature",
              "typeSpec": {
                "type": "value",
                "max": 100,
                "min": 0,
                "scale": 0,
                "step": 1,
                "unit": "℃"
              }
            },
            {
              "abilityId": 106,
              "accessMode": "ro",
              "code": "state",
              "description": "0: Not Connected\n1: Base Detached\n2: Idle\n3: Heating\n4: Cooling\n5: Keeping Warm",
              "name": "Current Status",
              "typeSpec": {
                "type": "enum",
                "range": ["0", "1", "2", "3", "4", "5"]
              }
            },
            {
              "abilityId": 107,
              "accessMode": "ro",
              "code": "countdown",
              "description": "Reported by MCU",
              "name": "Remaining Countdown Time",
              "typeSpec": {
                "type": "value",
                "max": 240,
                "min": 0,
                "scale": 0,
                "step": 1,
                "unit": "Minutes"
              }
            },
            {
              "abilityId": 108,
              "accessMode": "ro",
              "code": "timer",
              "description": "",
              "name": "Countdown Timer",
              "typeSpec": {
                "type": "value",
                "max": 240,
                "min": 0,
                "scale": 0,
                "step": 1,
                "unit": "Minutes"
              }
            }
          ]
        }
      ]
    }
  },
  "success": true,
  "t": 1731943528768,
  "tid": "575d3266a5c111efbd65e6107338fc03"
}

**Comment by CakesTwix** [comment]
Any progress?
