### ISSUE TITLE
Princess 540 panel heater

### ISSUE THREAD

**Issue by renaudallard** [make-all/tuya-local#1556]
The "Princess 350 panel heater" seems to be supported, but when I add a "Princess 540 panel heater", it's not even recognized as a heater/climate device. There is no difference apart from power (540W instead of 350W) on those 2 heaters.
The product code for the 540W model is bf1c4cc728280d4955h1hq
I am sorry I can't make a pull request as I don't know how the 350 is recognized granted there is no product code in devices/princess_panel_heater.yaml

**Comment by make-all** [comment]
Without logs, there isn't anything I can do with this information. Simply adding the product id is not going to help with detection, as if it was really compatible it would have been detected based on dps matches.

**Comment by renaudallard** [comment]
Does the config I made in localtuya help?
`"data": {
    "device_config": {
      "friendly_name": "Princess Chauffage connect\u00e9 \u00e0 panneau rayonnant infrarouge",
      "host": "ip_address",
      "device_id": "bf1c4cc728280d4955h1hq",
      "local_key": "***************",
      "protocol_version": "3.3",
      "enable_debug": false,
      "model": "Princess Smart Infrared Heater",
      "dps_strings": [
        "1 (value: False)",
        "2 (value: 26)",
        "3 (value: 21)",
        "101 (value: 0)"
      ],
      "entities": [
        {
          "id": 1,
          "friendly_name": "Chauffage Princess IR grenier",
          "temperature_unit": "celsius",
          "target_precision": 1,
          "target_temperature_dp": 2,
          "current_temperature_dp": 3,
          "hvac_mode_dp": 1,
          "hvac_mode_set": "True/False",
          "precision": 1,
          "platform": "climate"
        }
      ],
      "product_key": "akgjihcqbyeaeaxe"
    },`
