### ISSUE TITLE
BLE Lights not functioning correctly

### ISSUE THREAD

**Issue by Krispkiwi** [make-all/tuya-local#1578]
**Describe the bug**
The BLE Solar lights have stopped working,  the toggle button automatically shifts back to what it was before you pressed the toggle although the device itself doesn't go back to that state resulting in the device staying on or staying off depending on the state changed it to.

**To Reproduce**
Adding the BLE device then toggling

**Expected behavior**
The toggle should turn the device on and off correction

**Additional context**
This is a new problem, it seems to pick up the correct state after a reload but then the problem persists.

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"
[config_entry-tuya_local-de3531e93dc2fe7547d7de798da4607d.json.txt](https://github.com/make-all/tuya-local/files/14093479/config_entry-tuya_local-de3531e93dc2fe7547d7de798da4607d.json.txt)

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

A few errors/warning exist in the logs:

Error 1: 

Solar Light 1 receive loop terminated by exception 'dict' object is not callable
Traceback (most recent call last):
  File "/config/custom_components/tuya_local/device.py", line 212, in receive_loop
    entity.on_receive(poll)
  File "/config/custom_components/tuya_local/event.py", line 63, in on_receive
    self.extra_state_attributes(),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'dict' object is not callable

Logger: custom_components.tuya_local.helpers.config
Source: custom_components/tuya_local/helpers/config.py:46
Integration: Tuya Local ([documentation](https://github.com/make-all/tuya-local), [issues](https://github.com/make-all/tuya-local/issues))
First occurred: 5:13:14 PM (4 occurrences)
Last logged: 6:59:51 PM

The use of binary_sensor for Solar garden light is deprecated and should be replaced by event_motion.

https://youtu.be/eBOWIVZSuFU

**Comment by make-all** [comment]
Thanks for the report, it is a bug in the new event entity.
