### ISSUE TITLE
Tuya Smart Fam controll incorrectly comes in as an LED Strip Light.  

### ISSUE THREAD

**Issue by dlk57** [make-all/tuya-local#1583]
The Controller is a Tuya Smart Fan control 3 speeds plus off and on/off for light.

While it comes in as Led it only gives on/ff for the light plus a timer.

The following is the info from IOT.Tuya

Don

"result": {
"active_time": 1706382309,
"bind_space_id": "97888050",
"category": "fsd",
"create_time": 1706372773,
"custom_name": "Garage Ceiling Fan ",
"icon": "smart/icon/ay15259177940092jIQE/730c660d540c2e83fa436e15e420d5b4.jpg",
"id": "REDACTED",
"ip": "172.56.28.93",
"is_online": true,
"lat": "39.4900",
"local_key": "REDACTED",
"lon": "-74.4700",
"model": "JF018-WIFI-SOC",
"name": "Smart Ceiling Fan ",
"product_id": "afcgb439awama7v8",
"product_name": "Smart Ceiling Fan ",
"sub": false,
"time_zone": "-05:00",
"update_time": 1706382309,
"uuid": "774836d1ea4a760e"
},
"success": true,
"t": 1706713202744,
"tid": "6950ded7c04911ee9ba54e7461b93a02"

Diagnostics

"home_assistant": {
"installation_type": "Home Assistant OS",
"version": "2024.1.6",
"dev": false,
"hassio": true,
"virtualenv": false,
"python_version": "3.11.6",
"docker": true,
"arch": "x86_64",
"timezone": "America/New_York",
"os_name": "Linux",
"os_version": "6.1.71-haos",
"supervisor": "2023.12.1",
"host_os": "Home Assistant OS 11.4",
"docker_version": "24.0.7",
"chassis": "embedded",
"run_as_root": true
},
"custom_components": {
"spook": {
"version": "2.1.1",
"requirements": []
},
"switchbotremote": {
"version": "1.0.0",
"requirements": [
"pyhumps"
]
},
"hacs": {
"version": "1.34.0",
"requirements": [
"aiogithubapi>=22.10.1"
]
},
"cielo_home": {
"version": "1.6.8",
"requirements": []
},
"alexa_media": {
"version": "4.9.0",
"requirements": [
"alexapy==1.27.10",
"packaging>=20.3",
"wrapt>=1.14.0"
]
},
"bhyve": {
"version": "3.2.2",
"requirements": []
},
"tuya_local": {
"version": "2024.1.1",
"requirements": [
"tinytuya==1.13.1"
]
},
"localtuya": {
"version": "5.2.1",
"requirements": []
},
"govee": {
"version": "2023.11.1",
"requirements": [
"govee-api-laggat==0.2.2",
"dacite==1.8.0"
]
},
"nodered": {
"version": "3.1.3",
"requirements": []
},
"spook_inverse": {
"version": "2.1.1",
"requirements": []
}
},
"integration_manifest": {
"domain": "tuya_local",
"name": "Tuya Local",
"codeowners": [
"@make-all"
],
"config_flow": true,
"dependencies": [],
"documentation": "https://github.com/make-all/tuya-local",
"integration_type": "device",
"iot_class": "local_push",
"issue_tracker": "https://github.com/make-all/tuya-local/issues",
"requirements": [
"tinytuya==1.13.1"
],
"version": "2024.1.1",
"is_built_in": false
},
"data": {
"name": "Garage Ceiling Fan - local",
"type": "rgb_led_strip",
"device_id": "REDACTED",
"device_cid": "",
"local_key": "REDACTED",
"host": "REDACTED",
"protocol_version": "auto",
"tinytuya_version": "1.13.1",
"api_version_set": 3.3,
"api_version_used": 3.3,
"api_working": true,
"status": {},
"cached_state": {
"updated_at": 1706716420.277616,
"20": false,
"26": 0,
"60": false,
"62": 1,
"64": 0,
"66": true
},
"pending_state": {},
"connected": true,
"force_dps": [],
"home_assistant": {
"name": "Garage Ceiling Fan - local",
"name_by_user": null,
"disabled": false,
"disabled_by": null,
"entities": [
{
"disabled": false,
"disabled_by": null,
"entity_category": "config",
"device_class": null,
"original_device_class": null,
"icon": null,
"unit_of_measurement": "min",
"state": {
"entity_id": "number.garage_ceiling_fan_timer",
"state": "0.0",
"attributes": {
"min": 0.0,
"max": 1440.0,
"step": 1.0,
"mode": "auto",
"unit_of_measurement": "min",
"icon": "mdi:timer",
"friendly_name": "Garage Ceiling Fan - local Timer"
},
"last_changed": "2024-01-31T14:44:25.066530+00:00",
"last_updated": "2024-01-31T14:44:25.066530+00:00"
}
},
{
"disabled": false,
"disabled_by": null,
"entity_category": null,
"device_class": null,
"original_device_class": null,
"icon": null,
"unit_of_measurement": null,
"state": {
"entity_id": "light.garage_ceiling_fan_2",
"state": "off",
"attributes": {
"effect_list": [
"Scene"
],
"supported_color_modes": [
"hs",
"white"
],
"color_mode": null,
"brightness": null,
"hs_color": null,
"rgb_color": null,
"xy_color": null,
"effect": null,
"friendly_name": "Garage Ceiling Fan - local",
"supported_features": 4
},
"last_changed": "2024-01-31T15:49:02.288127+00:00",
"last_updated": "2024-01-31T15:49:02.288127+00:00"
}
}
]
}
}
}

@dlk57

Add a comment
Comment
 
Add your comment here...
 
Remember, contributions to this repository should follow our [GitHub Community Guidelines](https://docs.github.com/articles/github-community-guidelines).
Assignees
No one assigned
Labels
[bug](https://github.com/make-all/tuya-local/labels/bug)
Projects
[ Tuya Local](https://github.com/users/make-all/projects/2)

Status: No status
Milestone
No milestone
Development
No branches or pull requests

Notifications
Customize
You’re receiving notifications because you authored the thread.
1 participant
@dlk57
Footer
© 2024 GitHub, Inc.
Footer navigation
[Terms](https://docs.github.com/site-policy/github-terms/github-terms-of-service)
[Privacy](https://docs.github.com/site-policy/privacy-policies/github-privacy-statement)
[Security](https://github.com/security)
[Status](https://www.githubstatus.com/)
[Docs](https://docs.github.com/)
[Contact](https://support.github.com/?tags=dotcom-footer)
Manage cookies

**Comment by dlk57** [comment]
Sorry hit the return key before finishing the report.
The Controller is a Tuya Smart Fan control 3 speeds plus light.

While it comes in as Led  it only gives on/ff for the light plus a timer.

The following is the info from IOT.Tuya

Don

"result": {
--
"active_time": 1706382309,
"bind_space_id":   "97888050",
"category": "fsd",
"create_time": 1706372773,
"custom_name": "Garage   Ceiling Fan ",
"icon":   "smart/icon/ay15259177940092jIQE/730c660d540c2e83fa436e15e420d5b4.jpg",
"id":   "eb07d8c0a23f446d67qs6r",
"ip": "172.56.28.93",
"is_online": true,
"lat": "39.4900",
"local_key":   "qWB'7gS@a<!Rto(N",
"lon": "-74.4700",
"model":   "JF018-WIFI-SOC",
"name": "Smart Ceiling Fan   ",
"product_id":   "afcgb439awama7v8",
"product_name": "Smart   Ceiling Fan ",
"sub": false,
"time_zone":   "-05:00",
"update_time": 1706382309,
"uuid":   "774836d1ea4a760e"
},
"success": true,
"t": 1706713202744,
"tid":   "6950ded7c04911ee9ba54e7461b93a02"

**Comment by make-all** [comment]
Not a bug.

**Comment by spyder94** [comment]
> Not a bug.

How is this not a bug? I'm experiencing the same issue where I'm trying to add a ceiling fan but the system detects it as an rgb_led_strip. There don't appear to be any options to change or specify the type.

Also, if you're going to close a reported issue, it would be appreciated and helpful to anyone experiencing the issue if you provided some sort of information about why you are closing it.

**Comment by ifeign** [comment]
I am having the exact same issue.
