### ISSUE TITLE
Missing dps for Fairland pool heat pumps

### ISSUE THREAD

**Issue by Utopia69** [make-all/tuya-local#159]
Hi,
Is it possible to add missing DPS values for Fairland inverter pool heat pump (maybe also working with BWT & IPS inverters)

output of my Fairland Full Inverter Plus (IPH45) heat pump
{"devId": "XXX", "dps": {"1": true, "102": 12, "103": true, "104": 100, "105": "warm", "106": 30, "107": 18, "108": 35, "115": 0, "116": 0, "117": true, "118": false, "120": -1, "122": 51, "124": 13, "125": 78, "126": 78, "127": 34, "128": 363, "129": 808, "130": false, "134": false, "135": true, "136": false, "139": false, "140": "LowSpeed"}}

dps values I found:
107 --> Set Value Lower Temp Limit
108 --> Set Value Upper Temp Limit
120 --> Outer Coil Temperature
122 --> Exhaust Temperature
124 --> Ambient Air Temperature
125 --> Compressor Running Speed %	
127 --> Cooling Plate Temperature
128 --> Electronic Expansion Valve Opening
129 --> DC Fan Motor Speed

Greatz

**Comment by make-all** [comment]
This model actually seems closest to Madimack.  Quite likely a lot of these pool heat pumps that share some or most dp ids have a common mapping of dp id to function, so I'll make the change for IPS as well (I did think at the time the 107 and 108 looked like min and max temperature).

**Comment by Utopia69** [comment]
Hi, 
Thanks already for the update.
I also found dp 117
true => smart mode
false => silent mode
Grtz,

**Comment by make-all** [comment]
Thanks, 117 is already covered in the madimack configuration (though true there is labelled Boost rather than Smart), and also in the GardenPAC heatpump where it is labelled as you wrote.  I guess GardenPAC is probably another model that might benefit from your investigations.  IPS does not appear to have dp 117.

**Comment by Utopia69** [comment]
I just found the complete list:
{dpName: "Electronic Expansion Valve Opening", dpId: 128}
{dpName: "Power", dpId: 1}
{dpName: "DC Fan Motor Speed", dpId: 129}
{dpName: "Defrost", dpId: 130}
{dpName: "Compressor AC Contactor", dpId: 134}
{dpName: "Circulating Pump", dpId: 135}
{dpName: "Four-way Valve", dpId: 136}
{dpName: "Current-limiting Charging Relay", dpId: 139}
{dpName: "AC Fan Motor Speed", dpId: 140}
{dpName: "Inlet Water Temperature", dpId: 102}
{dpName: "Temperature Switch", dpId: 103}
{dpName: "Speed Percentage", dpId: 104}
{dpName: "Select Mode ", dpId: 105}
{dpName: "Setting", dpId: 106}
{dpName: "Set Value Lower Limit", dpId: 107}
{dpName: "Set Value Upper Limit", dpId: 108}
{dpName: "Fault", dpId: 115}
{dpName: "Fault 2", dpId: 116}
{dpName: "Silence Mode", dpId: 117}
{dpName: "Heating or Cooling Running", dpId: 118}
{dpName: "Outer Coil Temperature", dpId: 120}
{dpName: "Exhaust Temperature", dpId: 122}
{dpName: "Ambient Temperature", dpId: 124}
{dpName: "Compressor Running Speed", dpId: 125}
{dpName: "Compressor Current", dpId: 126}
{dpName: "Cooling Plate Temperature", dpId: 127}

**Comment by Utopia69** [comment]
tested the adjustments and it looks good
the dp 130 (defrost) would be nice to have
false => normal state (not defrosting)
true => heatpump is defrosting

Also 115 & 116, then we can send a notification when there is an error ( so if 115 or 116 is not 0)
ex. dp 115=4 => Error E3, no water flow

For the fan speed may add rpm as unit?

Grtz,

**Comment by make-all** [comment]
These changes are included in 0.18.0 release.
