### ISSUE TITLE
Moes IR Controller does everything except send the IR Command

### ISSUE THREAD

**Issue by phoenixmarines** [make-all/tuya-local#1599]
**Describe the bug**
The Moes IR Controller is added fine and the Air Conditioning card is added to the dashboard.
All buttons seem to work and update the touchscreen display but the device doesn't send the IR command to the air conditioner

**To Reproduce**
Try to add the Moes IR Air Conditioner controller to devices.
Add the new Thermostat card to the dashboard.
Try to turn on the air conditioner or make and changes and they will show on the touchscreen but not send the signal to the air conditioner.

**Expected behavior**
The touchscreen should update and send the new settings via IR to the air conditioner.

**Additional context**
I have added both the master wifi controller and the sub devices named after the air conditioner in the smartlife app. Both seem to function exactly the same not sure which one I'm supposed to be using but neither sends the IR signal.

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"
{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2024.1.6",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Pacific/Auckland",
    "os_name": "Linux",
    "os_version": "5.10.0-10-amd64",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "tuya_local": {
      "version": "2024.1.1",
      "requirements": [
        "tinytuya==1.13.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya_local",
    "name": "Tuya Local",
    "codeowners": [
      "@make-all"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/make-all/tuya-local",
    "integration_type": "device",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/make-all/tuya-local/issues",
    "requirements": [
      "tinytuya==1.13.1"
    ],
    "version": "2024.1.1",
    "is_built_in": false
  },
  "data": {
    "name": "Air Conditioning",
    "type": "ir_moes_heatpump",
    "device_id": "**REDACTED**",
    "device_cid": "",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": 3.3,
    "tinytuya_version": "1.13.1",
    "api_version_set": 3.3,
    "api_version_used": 3.3,
    "api_working": true,
    "status": {},
    "cached_state": {
      "updated_at": 1707035201.175817,
      "1": false,
      "2": 240,
      "3": 23,
      "4": "cold",
      "5": "auto",
      "8": 364,
      "9": 23,
      "10": 20,
      "11": "c",
      "12": 60,
      "15": "scene_1",
      "16": "done",
      "18": 364,
      "201": "{\"ver\":\"3\",\"control\":\"irlib_download\",\"sub_ctrl\":2,\"dl_percent\":100,\"devid\":\"ebfbf4b15d3f00fa1abc1z\",\"range\":-1542458297}"
    },
    "pending_state": {},
    "connected": true,
    "force_dps": [],
    "home_assistant": {
      "name": "Air Conditioning",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "climate.air_conditioning",
            "state": "off",
            "attributes": {
              "hvac_modes": [
                "off",
                "cool",
                "heat",
                "heatcool",
                "fan_only",
                "dry"
              ],
              "min_temp": 16,
              "max_temp": 32,
              "target_temp_step": 1.0,
              "fan_modes": [
                "auto",
                "low",
                "medium",
                "high"
              ],
              "current_temperature": 24.0,
              "temperature": 23,
              "current_humidity": 60,
              "fan_mode": "auto",
              "unknown_9": 23,
              "unknown_10": 20,
              "display_unit": "c",
              "unknown_15": "scene_1",
              "unknown_16": "done",
              "unknown_18": 364,
              "friendly_name": "Air Conditioning",
              "supported_features": 9
            },
            "last_changed": "2024-02-04T08:21:35.078906+00:00",
            "last_updated": "2024-02-04T08:23:25.833975+00:00"
          }
        }
      ]
    }
  }
}

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.
No Logged messages.

**Comment by make-all** [comment]
If the device display is updating, then the commands are getting through from Home Assistant to the device, so the problem is not in the integration, but in the device itself, or your setup of the device.

**Comment by phoenixmarines** [comment]
I forgot to mention the device works fine from the Smart life App. Is there any other advice for setting this up. I saw in a previous lost that you actually own one of these so I assume by your response yours is working fine.


-------- Original message --------
From: Jason Rumney ***@***.***>
Date: 4/02/24 9:56 pm (GMT+12:00)
To: make-all/tuya-local ***@***.***>
Cc: Brett Smith ***@***.***>, Author ***@***.***>
Subject: Re: [make-all/tuya-local] Moes IR Controller does everything except send the IR Command (Issue #1599)


If the device display is updating, then the commands are getting through from Home Assistant to the device, so the problem is not in the integration, but in the device itself, or your setup of the device.

**Comment by make-all** [comment]
No, I don't own this one, but another universal remote that presents send-only representations of high level devices as subdevices, which are unusable with tuya-local, as they do not report anything. The main device is a universal learning remote which works as a remote entity for learning and sending remote commands.
