### ISSUE TITLE
Nedis air quality monitor wrong unit

### ISSUE THREAD

**Issue by JacobsenKim** [make-all/tuya-local#1601]
![Skærmbillede 2024-02-04 135140](https://github.com/make-all/tuya-local/assets/157890151/052e8dc4-fc2e-4645-9065-389986581bd3)

Line 46 need to change from ppm to "µg/m³" then the error stop in HA.

i had this fixed before but update the complete local tuya pack and got the problem once more.

Please update the file
https://github.com/make-all/tuya-local/blob/main/custom_components/tuya_local/devices/nedis_airquality.yaml

Thx

**Comment by make-all** [comment]
Based on the original report, the device is reporting ppm.  So the correct fix is not to change the unit, but to change the class to the more recently added volatile_organic_compounds_parts class (I'm not sure exactly when this appeared, but it was within the last few months, so it is surprising that HA is throwing errors so soon after introducing the split between these).

**Comment by JacobsenKim** [comment]
The change fixed the problem at my end :-D

Thx
