### ISSUE TITLE
Electric Heater not being detected as a climate device

### ISSUE THREAD

**Issue by lowebb** [make-all/tuya-local#1603]
I'm trying to a Wärme Designer WiFi Electric Wall Heater Panel Heater Radiator - Ultra Slim (8cm) - 2Kw - Programmable Digital Thermostat - Wall Mountable. tuya-local is finding the device and I am able to add it; but it is not detecting it as a climate device and not offering me that in the entity tye drop-down. The closest I can get is a 'feit_dimmer' which allows me to switch on and off the heater, but not control the temperature

HA logs say
```
2024-02-04 13:45:47.460 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches feit_dimmer with quality of 57%. DPS: {"updated_at": 1707054344.1942992, "1": true, "2": 17, "3": 18, "4": "day", "101": false, "102": "Comfort", "103": 0}
2024-02-04 13:45:47.460 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/
```

Using tinytuya, the device info has the following mapping
```
        "mapping": {
            "3": {
                "code": "temp_current",
                "type": "Integer",
                "values": {
                    "unit": "\u00b0C",
                    "min": 0,
                    "max": 50,
                    "scale": 0,
                    "step": 1
                }
            },
            "2": {
                "code": "temp_set",
                "type": "Integer",
                "values": {
                    "unit": "\u00b0C",
                    "min": 12,
                    "max": 45,
                    "scale": 0,
                    "step": 1
                }
            },
            "1": {
                "code": "switch",
                "type": "Boolean",
                "values": {}
            }
        },
```

I'm interested in helping if I can. Would love to understand how I can debug this further. Is defining a yaml under `devices` within the realms of possibility? Such as similar to `andersson_gsh_heater.yaml`

**Comment by make-all** [comment]
This is not a bug but a new device request.  If you'd used the new device template instead of the bug template it would have led you through providing the full information.  As it is, the report only contains partial information about the dps mappings, so it is unlikely to be added soon unless more info is provided.

**Comment by lowebb** [comment]
Understood, have raised https://github.com/make-all/tuya-local/issues/1606 and will close this ticket
