### ISSUE TITLE
Home-Assistant 2022.4.4 does not load tuya-local

### ISSUE THREAD

**Issue by ed-holland** [make-all/tuya-local#161]
Since 2022.3 the integration does not seem to load anymore.
Tried going back to old 14.4 (which it had before the update) and also to main version.
It tries to load the repository but never shows as integration in HACS (1.24.5). It completes the install it seems.
It is possible to add the integration tuya_local but then this error occurs:
![image](https://user-images.githubusercontent.com/53995991/163579017-41a6715d-8429-4648-8e5c-d82c2472f316.png)

Uninstalling and re-installing did not help.

Any idea what is going wrong here?

**Comment by ed-holland** [comment]
After a reboot of the OS, the integration now shows up in HACS. Issue persists when trying to add a tuya device.

**Comment by make-all** [comment]
Duplicate of #151 and if you are using 0.14.4, #144.  As with #151, the issue has been resolved by restarting HA, though your last comment suggests it is not completely solved, but it isn't clear what the remaining problem actually is.

**Comment by ed-holland** [comment]
Indeed is a duplicate. 
After many tries, i was able to get it working again ;-)
I used the redownload menu in HACS and rebooted. Now there was a tuya_local and tuya_local.old in the cutom_components directory. The error was only referring to the old, so i removed it and then rebooted again.

Now i could add the Device without a problem :-)
The error was referring to the
