### ISSUE TITLE
Request support for 1CH Wi-Fi Dimmer Module CB3S

### ISSUE THREAD

**Issue by toposilva** [make-all/tuya-local#1611]
I like you add support for 1CH Wi-Fi Dimmer Module CB3S. I've too a module 2CH but for now I only have connected for 1CH
It detects for multiple options but none (only 2 are dimmers) give options for dimming.

# Log Message

2024-02-05 10:05:01.734 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches eurom_800_heater with quality of 83%. DPS: {"updated_at": 1707127478.6695797, "1": true, "2": 427, "3": 250, "5": 797, "6": 0, "14": "off"}
2024-02-05 10:05:01.734 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"000004abbo\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch_led_1\",\"description\":\"\",\"extensions\":{\"attribute\":\"519\"},\"name\":\"开关1\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"bright_value_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_half\",\"attribute\":\"1158\"},\"name\":\"亮度值1\",\"typeSpec\":{\"max\":1000,\"min\":10,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":10}},
{\"abilityId\":3,\"accessMode\":\"rw\",\"code\":\"brightness_min_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-liangdu1\",\"attribute\":\"1152\"},\"name\":\"最小亮度1\",\"typeSpec\":{\"max\":1000,\"min\":10,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":10}},
{\"abilityId\":4,\"accessMode\":\"rw\",\"code\":\"led_type_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_box2\",\"attribute\":\"1152\"},\"name\":\"开关类型1\",\"typeSpec\":{\"range\":[\"kickback\",\"seesaw_toggle\",\"seesaw_sync\"],\"type\":\"enum\",\"typeDefaultValue\":\"kickback\"}},
{\"abilityId\":5,\"accessMode\":\"rw\",\"code\":\"brightness_max_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_sun\",\"attribute\":\"1152\"},\"name\":\"最大亮度1\",\"typeSpec\":{\"max\":1000,\"min\":10,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":10}},
{\"abilityId\":6,\"accessMode\":\"rw\",\"code\":\"countdown_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"attribute\":\"1155\"},\"name\":\"倒计时1\",\"typeSpec\":{\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"s\"}},
{\"abilityId\":14,\"accessMode\":\"rw\",\"code\":\"relay_status\",\"description\":\"\",\"extensions\":{\"iconName\":\"setting icon-setting\",\"attribute\":\"1152\"},\"name\":\"设备重启状态设置\",\"typeSpec\":{\"range\":[\"off\",\"on\",\"memory\"],\"type\":\"enum\",\"typeDefaultValue\":\"off\"}}]}]}"
  },
  "success": true,
  "t": 1707127408297,
  "tid": "cf09655ac40d11eeae7d5ef5dab112a3"
}
```

# Product ID
5zsarybcltypoeaa

**Comment by make-all** [comment]
CB3S seems to be the name of Tuya's latest WiFi+Bluetooth module.  Do you have any identifying brand or model for the device itself?  Often the dimmer modules will have a model code written on them if they are the type that is designed to be fitted behind the normal switchplate.

**Comment by toposilva** [comment]
1CH Wi-Fi Dimmer Module / 2CH Wi-Fi Dimmer Module is the only thing that appear on device...
I've changed a yaml of one device to detect and auto configure this and it works with every options

[1ch_wifi_dimmer_module.zip](https://github.com/make-all/tuya-local/files/14237382/1ch_wifi_dimmer_module.zip)

If you want you can test verify it and put it on your integration
