### ISSUE TITLE
Request: WiFi Patio Infrared Heater

### ISSUE THREAD

**Issue by Swiftnesses** [make-all/tuya-local#163]
Hello, I've recently purchased a Tuya (Smartlife) enabled infrared patio heater (2.4kw).

Product link - https://www.devola.co.uk/products/devola-2-4kw-wi-fi-patio-radiant-heater-dvph2400b

Note: It appears to be sold under various brands.

**Looking at the Tuya development portal, the instruction set is:**

```
switch | Boolean | "{true,false}"
temp_set | Integer | {   "unit": "°C",   "min": 5,   "max": 45,   "scale": 0,   "step": 1 }
mode | Enum | {   "range": [     "smart"   ] }
level | Enum | {   "range": [     "1",     "2",     "3",     "4"   ] }
mode_eco | Boolean | "{true,false}"
lock | Boolean | "{true,false}"
temp_unit_convert | Enum | {   "range": [     "c",     "f"   ] }
temp_set_f | Integer | {   "unit": "℉",   "min": 44,   "max": 99,   "scale": 0,   "step": 1 }
```

**Status set:**

```
switch | Boolean | "{true,false}"
temp_set | Integer | {   "unit": "°C",   "min": 5,   "max": 45,   "scale": 0,   "step": 1 }
temp_current | Integer | {   "unit": "°C",   "min": -20,   "max": 50,   "scale": 0,   "step": 1 }
mode | Enum | {   "range": [     "smart"   ] }
level | Enum | {   "range": [     "1",     "2",     "3",     "4"   ] }
mode_eco | Boolean | "{true,false}"
lock | Boolean | "{true,false}"
countdown_left | Integer | {   "unit": "分钟",   "min": 0,   "max": 1440,   "scale": 0,   "step": 1 }
work_state | Enum | {   "range": [     "heating",     "warming"   ] }
temp_unit_convert | Enum | {   "range": [     "c",     "f"   ] }
temp_set_f | Integer | {   "unit": "℉",   "min": 44,   "max": 99,   "scale": 0,   "step": 1 }
temp_current_f | Integer | {   "unit": "℉",   "min": -4,   "max": 122,   "scale": 0,   "step": 1 }
```

Can this device please be added? I think it's a great connected device for those that like to be outdoors... :)

**Comment by make-all** [comment]
In the Tuya Developer portal, under the API Explorer, there are a lot of functions returning similar values. Only one gives the local indexes that are needed to communicate directly with the device. That one is under Smart Home Management System, Device Control, the last "Get Device Specification Attribute" function in the list.

**Comment by Swiftnesses** [comment]
@make-all,

My bad, I'm new to this. Below is the output of the function:

`
{
  "result": {
    "category": "qn",
    "functions": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"°C\",\"min\":5,\"max\":45,\"scale\":0,\"step\":1}"
      },
      {
        "code": "mode",
        "dp_id": 4,
        "type": "Enum",
        "values": "{\"range\":[\"smart\"]}"
      },
      {
        "code": "level",
        "dp_id": 5,
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\",\"4\"]}"
      },
      {
        "code": "mode_eco",
        "dp_id": 6,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "lock",
        "dp_id": 7,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_unit_convert",
        "dp_id": 19,
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "temp_set_f",
        "dp_id": 20,
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":44,\"max\":99,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"°C\",\"min\":5,\"max\":45,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_current",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"unit\":\"°C\",\"min\":-20,\"max\":50,\"scale\":0,\"step\":1}"
      },
      {
        "code": "mode",
        "dp_id": 4,
        "type": "Enum",
        "values": "{\"range\":[\"smart\"]}"
      },
      {
        "code": "level",
        "dp_id": 5,
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\",\"4\"]}"
      },
      {
        "code": "mode_eco",
        "dp_id": 6,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "lock",
        "dp_id": 7,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_left",
        "dp_id": 12,
        "type": "Integer",
        "values": "{\"unit\":\"分钟\",\"min\":0,\"max\":1440,\"scale\":0,\"step\":1}"
      },
      {
        "code": "work_state",
        "dp_id": 14,
        "type": "Enum",
        "values": "{\"range\":[\"heating\",\"warming\"]}"
      },
      {
        "code": "temp_unit_convert",
        "dp_id": 19,
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "temp_set_f",
        "dp_id": 20,
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":44,\"max\":99,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_current_f",
        "dp_id": 21,
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":-4,\"max\":122,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1651302411283,
  "tid": "1be034a3c85411ecb1897e9cb5e43094"
}
`

**Comment by Swiftnesses** [comment]
Please let me know if you need anything else...
