### ISSUE TITLE
Request support for Smart Curtain QS-ZIGBEE-C01(LC9+RF)

### ISSUE THREAD

**Issue by peruggini** [make-all/tuya-local#1634]
```
2024-02-09 12:53:23.372 INFO (MainThread) [custom_components.tuya_local.device] Setting protocol version for Test to 3.4
2024-02-09 12:53:57.389 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches None with quality of 0%. DPS: {"updated_at": 1707479603.4451215, "4": false, "32": "normal"}
2024-02-09 12:53:57.389 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/
```
# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"000004wtkm\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"control\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"1536\"},\"name\":\"窗帘开关1\",\"typeSpec\":{\"range\":[\"open\",\"stop\",\"close\",\"continue\"],\"type\":\"enum\",\"typeDefaultValue\":\"open\"}},
{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"percent_control\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-icon-percent\",\"attribute\":\"1536\"},\"name\":\"百分比1\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%\"}},
{\"abilityId\":3,\"accessMode\":\"rw\",\"code\":\"cur_calibration\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_loop\",\"attribute\":\"1536\"},\"name\":\"精准校准1\",\"typeSpec\":{\"range\":[\"start\",\"end\"],\"type\":\"enum\",\"typeDefaultValue\":\"start\"}},
{\"abilityId\":8,\"accessMode\":\"rw\",\"code\":\"control_back\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"attribute\":\"1536\"},\"name\":\"电机转向切换1\",\"typeSpec\":{\"range\":[\"forward\",\"back\"],\"type\":\"enum\",\"typeDefaultValue\":\"forward\"}},
{\"abilityId\":10,\"accessMode\":\"rw\",\"code\":\"quick_calibration_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_loop\",\"attribute\":\"1536\"},\"name\":\"快捷校准1\",\"typeSpec\":{\"max\":180,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"s\"}},
{\"abilityId\":12,\"accessMode\":\"rw\",\"code\":\"elec_machinery_mode\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"attribute\":\"1024\"},\"name\":\"一路开关类型\",\"typeSpec\":{\"range\":[\"button\",\"flip\"],\"type\":\"enum\",\"typeDefaultValue\":\"button\"}}]}]}"
  },
  "success": true,
  "t": 1707482629564,
  "tid": "df5f3926c74811eeaa50e2bf9884e306"
}
```

# Product ID

{
  "result": {
    "active_time": 1703087408,
    "bind_space_id": "79501552",
    "category": "tdq",
    "create_time": 1703087408,
    "custom_name": "Tapparella Camera da Letto",
    "icon": "smart/icon/ay15107356719526e3ps/9403d421c9e59c2160c14418950560c4.png",
    "id": "bf28bfd016696f337ccjb0",
    "ip": "",
    "is_online": true,
    "lat": "45.4700",
    "local_key": "",
    "lon": "9.2500",
    "model": "",
    "name": "QS-ZIGBEE-C01(LC9+RF) 2",
    "product_id": "ol1uhvza",
    "product_name": "QS-ZIGBEE-C01(LC9+RF)",
    "sub": true,
    "time_zone": "+01:00",
    "update_time": 1703087430,
    "uuid": "a4c138d8b498c932"
  },
  "success": true,
  "t": 1707482712935,
  "tid": "11068b8cc74911ee9d7cfe8b4d072f7e"
}

**Comment by make-all** [comment]
The log does not match the dps mapping info.

From the dps mapping, it appears to be similar to the QS-WIFI-C01 that is already supported, but with some extra calibration options (which may also be present on the WiFi model, just not included in the original report for that)

**Comment by peruggini** [comment]
Are you referring at integration log from HA?
Pretty sure it was correct, just tried again:

2024-02-13 11:37:59.726 INFO (MainThread) [custom_components.tuya_local.device] Setting protocol version for Test to 3.4
2024-02-13 11:38:34.992 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches None with quality of 0%. DPS: {"updated_at": 1707820679.938705, "4": false, "32": "normal"}
2024-02-13 11:38:34.993 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/

Happy to help with anything useful

**Comment by make-all** [comment]
This doesn't match at all, there is no DPS 4 or 32 listed, and "normal" doesn't look like a curtain related setting

**Comment by peruggini** [comment]
Got it!
My fault, that was log related to gateway.
I was missing "sub device id" field in configuration.
I put node_id field from IOT Tuya in "sub device id" field and now is successfully recognized
