### ISSUE TITLE
Request support for Eightree Smart Plug ET29 with power consumption

### ISSUE THREAD

**Issue by Th0tti** [make-all/tuya-local#1635]
switch_1 | Boolean | "{true,false}"
-- | -- | --
countdown_1 | Integer | {   "min": 0,   "max": 43200,   "scale": 0,   "step": 1 }
power_production | Integer | {   "unit": "kW·h",   "min": 0,   "max": 5000,   "scale": 3,   "step": 100 }
power_consumption | Integer | {   "unit": "kW·h",   "min": 0,   "max": 5000,   "scale": 3,   "step": 100 }
cur_current | Integer | {   "unit": "mA",   "min": 0,   "max": 30000,   "scale": 0,   "step": 1 }
cur_power | Integer | {   "unit": "W",   "min": 0,   "max": 80000,   "scale": 1,   "step": 1 }
cur_voltage | Integer | {   "unit": "V",   "min": 0,   "max": 5000,   "scale": 1,   "step": 1 }
test_bit | Integer | {   "min": 0,   "max": 5,   "scale": 0,   "step": 1 }
voltage_coe | Integer | {   "min": 0,   "max": 1000000,   "scale": 0,   "step": 1 }
electric_coe | Integer | {   "min": 0,   "max": 1000000,   "scale": 0,   "step": 1 }
power_coe | Integer | {   "min": 0,   "max": 1000000,   "scale": 0,   "step": 1 }
electricity_coe | Integer | {   "min": 0,   "max": 1000000,   "scale": 0,   "step": 1 }
fault | Bitmap | {   "label": [     "ov_cr",     "ov_vol",     "ov_pwr",     "ls_cr",     "ls_vol",     "ls_pow"   ],   "maxlen": 6 }
relay_status | Enum | {   "range": [     "off",     "on",     "memory"   ] }
overcharge_switch | Boolean | "{true,false}"
light_mode | Enum | {   "range": [     "relay",     "pos",     "none",     "on"   ] }
cycle_time | String | {   "maxlen": 255 }
random_time | String | {   "maxlen": 255 }
mode_switch | Enum | {   "range": [     "auto",     "item_1",     "item_2"   ] }
status | Enum | {   "range": [     "production",     "consumption"   ] }

Test protocol error 914: Check device key or version```

# Query Things Data Model
{
  "result": {
    "model": "{\"modelId\":\"000004x7dd\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\"},\"name\":\"开关1\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":9,\"accessMode\":\"rw\",\"code\":\"countdown_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\"},\"name\":\"倒计时1\",\"typeSpec\":{\"max\":43200,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},{\"abilityId\":16,\"accessMode\":\"ro\",\"code\":\"power_production\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_lightning\"},\"name\":\"发电量\",\"typeSpec\":{\"max\":5000,\"min\":0,\"scale\":3,\"step\":100,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"kW·h\"}},{\"abilityId\":17,\"accessMode\":\"ro\",\"code\":\"power_consumption\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_battery\"},\"name\":\"耗电量\",\"typeSpec\":{\"max\":5000,\"min\":0,\"scale\":3,\"step\":100,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"kW·h\"}},{\"abilityId\":18,\"accessMode\":\"ro\",\"code\":\"cur_current\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_0\"},\"name\":\"电流\",\"typeSpec\":{\"max\":30000,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"mA\"}},{\"abilityId\":19,\"accessMode\":\"ro\",\"code\":\"cur_power\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_1\"},\"name\":\"功率\",\"typeSpec\":{\"max\":80000,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"W\"}},{\"abilityId\":20,\"accessMode\":\"ro\",\"code\":\"cur_voltage\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_0\"},\"name\":\"电压\",\"typeSpec\":{\"max\":5000,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"V\"}},{\"abilityId\":21,\"accessMode\":\"ro\",\"code\":\"test_bit\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_2\"},\"name\":\"产测结果位\",\"typeSpec\":{\"max\":5,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},{\"abilityId\":22,\"accessMode\":\"ro\",\"code\":\"voltage_coe\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_1\"},\"name\":\"电压校准系数\",\"typeSpec\":{\"max\":1000000,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},{\"abilityId\":23,\"accessMode\":\"ro\",\"code\":\"electric_coe\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_2\"},\"name\":\"电流校准系数\",\"typeSpec\":{\"max\":1000000,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},{\"abilityId\":24,\"accessMode\":\"ro\",\"code\":\"power_coe\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_3\"},\"name\":\"功率校准系数\",\"typeSpec\":{\"max\":1000000,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},{\"abilityId\":25,\"accessMode\":\"ro\",\"code\":\"electricity_coe\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_3\"},\"name\":\"电量校准系数\",\"typeSpec\":{\"max\":1000000,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},{\"abilityId\":26,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-baojing\"},\"name\":\"故障告警\",\"typeSpec\":{\"label\":[\"ov_cr\",\"ov_vol\",\"ov_pwr\",\"ls_cr\",\"ls_vol\",\"ls_pow\"],\"maxlen\":6,\"type\":\"bitmap\",\"typeDefaultValue\":0}},{\"abilityId\":38,\"accessMode\":\"rw\",\"code\":\"relay_status\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-zhuangtai\",\"attribute\":\"512\"},\"name\":\"上电状态设置\",\"typeSpec\":{\"range\":[\"off\",\"on\",\"memory\"],\"type\":\"enum\",\"typeDefaultValue\":\"off\"}},{\"abilityId\":39,\"accessMode\":\"rw\",\"code\":\"overcharge_switch\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-a_power\",\"attribute\":\"512\"},\"name\":\"过充保护\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":40,\"accessMode\":\"rw\",\"code\":\"light_mode\",\"description\":\"\",\"extensions\":{\"iconName\":\"tcl_function_light\",\"attribute\":\"512\"},\"name\":\"指示灯状态设置\",\"typeSpec\":{\"range\":[\"relay\",\"pos\",\"none\",\"on\"],\"type\":\"enum\",\"typeDefaultValue\":\"relay\"}},{\"abilityId\":42,\"accessMode\":\"rw\",\"code\":\"cycle_time\",\"description\":\"1\",\"extensions\":{\"iconName\":\"icon-dp_time3\",\"attribute\":\"512\"},\"name\":\"循环定时\",\"typeSpec\":{\"maxlen\":255,\"type\":\"string\",\"typeDefaultValue\":\"\"}},{\"abilityId\":43,\"accessMode\":\"rw\",\"code\":\"random_time\",\"description\":\"1\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"attribute\":\"512\"},\"name\":\"随机定时\",\"typeSpec\":{\"maxlen\":255,\"type\":\"string\",\"typeDefaultValue\":\"\"}},{\"abilityId\":44,\"accessMode\":\"rw\",\"code\":\"mode_switch\",\"description\":\"auto：自动检测\\nitem_1:设置为发电\\nitem_2：设置为耗电\\n\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"attribute\":\"512\"},\"name\":\"状态修正\",\"typeSpec\":{\"range\":[\"auto\",\"item_1\",\"item_2\"],\"type\":\"enum\",\"typeDefaultValue\":\"auto\"}},{\"abilityId\":45,\"accessMode\":\"ro\",\"code\":\"status\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-zhuangtai\"},\"name\":\"设备状态\",\"typeSpec\":{\"range\":[\"production\",\"consumption\"],\"type\":\"enum\",\"typeDefaultValue\":\"production\"}}]}]}"
  },
  "success": true,
  "t": 1707517130274,
  "tid": "3368e3dfc79911eea1957edaaa357452"
}

**Comment by make-all** [comment]
These look like fairly standard smartplugs, without a log message I can't even be sure that you have tried adding them.
