### ISSUE TITLE
Issues recognizing Zigbee ZN373186 sensor

### ISSUE THREAD

**Issue by romicaiarca** [make-all/tuya-local#1636]
**Describe the bug**
I have 3 Zigbee THS and it looks like they should be supported by the component but for some reasone they are detected as other sensor and I have wrong data displayed.

**To Reproduce**
Add the sensors in home assistant. see the screen for suggested sensors.
<img width="408" alt="Screenshot 2024-02-10 at 00 52 51" src="https://github.com/make-all/tuya-local/assets/1266110/622e6c88-003f-45da-890f-418341c1a683">

**Expected behavior**
I'd expect to be detected as this sensor. Check the product id = xr3htd96
<img width="478" alt="Screenshot 2024-02-10 at 01 00 07" src="https://github.com/make-all/tuya-local/assets/1266110/d7c94dfb-ecf5-4c84-8dcc-ad8825d712b8">

**Additional context**
Here you have the details that are extracted from tuya iot platform (check the product_id= xr3htd96

<img width="787" alt="Screenshot 2024-02-10 at 00 54 08" src="https://github.com/make-all/tuya-local/assets/1266110/592d397f-2be1-4ea3-aac9-32a37c9d19fc">

**Comment by make-all** [comment]
Without the log messages, whatever problem is there is impossible to diagnose.

**Comment by romicaiarca** [comment]
> Without the log messages, whatever problem is there is impossible to diagnose.

What logs do you need?
After some testing and debugging, it looks like the sensor is not sending all the time DP ID: 4 (battery percent) and that's why the zigbee_zn373186_temphumid_sensor.yaml is omited by the automatic detection. What I had to do is to add optional: true into zigbee_zn373186_temphumid_sensor.yaml file, and the battery percent became available after few hours. Do you think That I should create a PR with this fix or in your opinion this shouldn't be included in the device settings from the official repo?

Best Regards,
Romica

**Comment by make-all** [comment]
That info is basically what I was expecting to see in the logs.
