### ISSUE TITLE
Devices detected by LocalTuya but not by Tuya Local

### ISSUE THREAD

**Issue by duckati** [make-all/tuya-local#1638]
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**
All my devices is detected correctly by LocalTuya but not by Tuya Local with the same DeviceID and Local Key

**To Reproduce**
Add the devices in home assistant. see the screen for error.

![image](https://github.com/make-all/tuya-local/assets/51483537/6f20262b-4cf0-4a2b-988c-79639b2e4b5e)

**Comment by make-all** [comment]
No bug is described, and no evidence of a bug is provided.
