### ISSUE TITLE
Wilfa haze hu400bc humidifier turning off sound issue

### ISSUE THREAD

**Issue by daitj** [make-all/tuya-local#164]
There is some weird issue with this humidifier with this component, when I directly use tinytuya and set dps 8 false, the sound is off, but when I do it via home assistant, it makes a long beep sound, if I try many times from HA, it does work may be 1 in 10 times.

My guess is that when you turn off sound, all other async requests to read the state should wait for sound off request to be completed.

I could look into the code and figure out, but just putting this here if anyone knows what is the issue immediately.

**Comment by make-all** [comment]
In general, tuya devices need some time in between commands.  They seem to be single threaded, and don't have much if any of a buffer in their networking stack.  If this is from an automation, adding a delay of a couple of seconds between commands might help.  From the UI it is a bit harder to control, but generally you just do one thing at a time, so there should be a bit of a gap between commands.

**Comment by make-all** [comment]
Besides the last comment, in case this is due to a protocol incompatibility, 2022.12.1 just released allows to set the protocol_version manually.  If you try different values, you may find that one works better.

**Comment by oywino** [comment]
Does this mean that the Wilfa Haze has a Tuya Firmware?
How did you find that out?

**Comment by magnusgundersen** [comment]
For anyone else wondering; Yes, the Wilfa Haze is Tuya compatible. Just pair it with the Tuya Smart app, and then follow the instructions in this repo to setup local access from Home Assistant.
