### ISSUE TITLE
Wilfa haze hu400bc humidifier humidity step

### ISSUE THREAD

**Issue by daitj** [make-all/tuya-local#165]
When I made a PR for this humidifier, I wrote to you that the humidity can only be changed in the step of 5, 

I tried to add step it in the YAML file in many places but none work. 

So as of now in HA, I can change to any value but humidifier rounds it to nearest value. If anyone could point to me how to do that, it would be great.

**Comment by make-all** [comment]
It seems like HA itself does not support steps for humidifier devices.  The integration will enforce the steps based on the config, which may be what you are seeing with the rounding after setting by the UI, as tuya devices are not always robust in their input handling, some may round, others seem to stop responding if given unexpected input.
