### ISSUE TITLE
Add support for Poolex Q-Line series pool heat pump

### ISSUE THREAD

**Issue by odeBuXTeR** [make-all/tuya-local#166]
Hi all, testing this project to integrate my pool heat pump to HA, I have the ability to do this with the modified config file attached.

This is for Poolex Q-Line series pool heat pump, for me, it's the 7Kw model, but I think that the file works with the others models of the Q-Line series.

Thank you for your work and I hope that you can integrate this config file in future release, because file don't stay after updates :
[poolex_qline_heatpump.yaml.txt](https://github.com/make-all/tuya-local/files/8601919/poolex_qline_heatpump.yaml.txt)

Just rename the file by deleting .txt extension.

Thank you a lot !
Olivier DEGAND (odeBuXTeR)

**Comment by odeBuXTeR** [comment]
Hi, I've tried the files provided and the pool heater is detected with the water flow, but when I try changing heating mode or the temperature set, it come back to the previous set.

I went back to the regular release of tuya local with my files, and ... oh ! It's doing the same ! I lost a thing somewhere... Recently, I 'veupgraded my HA to core 2022.5.5 and 8.1 OS. Would be the link ?

I'll try to downgrade when I'll have time to do.

Thx, I keep you in touch

**Comment by make-all** [comment]
Is it  possible that you got the current temperature and temperature control the wrong way around?  Try swapping the ids for those two.

**Comment by odeBuXTeR** [comment]
As a confirmation of a good way for the two temperatures, when I set the wanted temperature on the panel of the heatpump, I got the desired temperature on the round and the small number of the climate picture on HA and the actual readed temperature on the big number.So the two ids seams not to be swapped. The strange thing is that it's going back to the previous set after 20 or 30 second, when I change on the heatpump it change to the desired temperature in a second...No error on HA log but I haven't view how to set debug mode on tuya local, I check this and say you what I have.ThxOlivierLe 28 mai 2022 03:28, Jason Rumney ***@***.***> a écrit :
Is it  possible that you got the current temperature and temperature control the wrong way around?  Try swapping the ids for those two.

**Comment by odeBuXTeR** [comment]
When requesting the iot platform for the dps, here is what I have :

{ "result": { "category": "znrb", "functions": [ { "code": "switch", "dp_id": 1, "type": "Boolean", "values": "{}" }, { "code": "mode", "dp_id": 2, "type": "Enum", "values": "{\"range\":[\"cold\",\"heating\"]}" }, { "code": "temp_set", "dp_id": 4, "type": "Integer", "values": "{\"unit\":\"℃\",\"min\":8,\"max\":40,\"scale\":0,\"step\":1}" } ], "status": [ { "code": "switch", "dp_id": 1, "type": "Boolean", "values": "{}" }, { "code": "mode", "dp_id": 2, "type": "Enum", "values": "{\"range\":[\"cold\",\"heating\"]}" }, { "code": "temp_set", "dp_id": 4, "type": "Integer", "values": "{\"unit\":\"℃\",\"min\":8,\"max\":40,\"scale\":0,\"step\":1}" }, { "code": "temp_current", "dp_id": 16, "type": "Integer", "values": "{\"unit\":\"℃\",\"min\":-30,\"max\":100,\"scale\":0,\"step\":1}" } ] }, "success": true,

Please note that the dp 15 is not listed but is working properly ...

**Comment by make-all** [comment]
The only differences from the config there are no "mute" mode, and temperature goes down to 8 rather than 15.
The former could be an issue if it was set when the device does not actually recognise it (or maybe does not allow setting temperature or has more restricted range in that mode).

I have changed the config to be in line with what is described in the iot API info, as that is what the cloud API will be restricted to (but I will keep the dps 15 since this is known to be working).

**Comment by odeBuXTeR** [comment]
Hi, sorry for this late reply. Here is what to do to have the device fully operate with your integration:

name: Poolex Q-Line Heatpump
primary_entity:
  entity: climate
  dps:
    - id: 1
      name: hvac_mode
      type: boolean
      mapping:
        - dps_val: false
          value: "off"
          icon: "mdi:hvac-off"
          icon_priority: 1
        - dps_val: true
          constraint: heating_mode
          conditions:
            - dps_val: cold
              value: cool
            - dps_val: heating
              value: heat
            - dps_val: mute
              value: auto
    - id: 2
      name: heating_mode
      hidden: true
      type: string
      icon_priority: 3
      mapping:
        - dps_val: heating
          icon: "mdi:hot-tub"
        - dps_val: cold
          icon: "mdi:snowflake"
        - dps_val: mute
          icon: "mdi:hot-tub"

    - id: 4
      name: temperature
      type: integer
      range:
        min: 8
        max: 40
    - id: 15
      type: bitfield
      name: error
      mapping:
        - dps_val: 0
          value: "OK"
        - dps_val: 1
          value: "Water Flow Protection"
          icon: "mdi:water-pump-off"
          icon_priority: 2
    - id: 16
      name: current_temperature
      type: integer
secondary_entities:
  - entity: binary_sensor
    name: Water Flow
    class: problem
    category: diagnostic
    dps:
      - id: 15
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - dps_val: 1
            value: true

As you can see, I just map the mute mode of the device with the hvac auto mode. Because there's no silent or eco mode existing, that's the only finded solution.
In the hvac_mode section, just map the mute mode with the heating icon. Note that on the ui, the hvac is in green with an icon like a calendar...
Added a missing value of the bitfield at the end of the file.
With this, all is ok, I can interact with the heatpump within HA.

Thanks for your work.
OD

**Comment by make-all** [comment]
I don't think the missing value at the end is an issue. The intention was to trigger that problem indicator when there is any error from the heatpump, rather than just the one error we know the value of.

**Comment by odeBuXTeR** [comment]
OK for the fan_only soft heating ^^ but all are in grey, not so sexy :) heat_cool have a better view I think, but you have the last word.
Just one thing in my logs :
WARNING (MainThread) - [custom_components.tuya_local.generic.climate] Unrecognised HVAC Mode of True ignored

But all working fine

**Comment by make-all** [comment]
It seems there may be another heating_mode value that is not caught in the mapping.  If it is just a glitch during startup, maybe making "heating" or "mute" the default will help.

**Comment by make-all** [comment]
Based on your comment "all are in grey", fan_only might be disabling something, so \i've changed to heat_cool instead.  Also added that as a default fallback to avoid the error message, though unsure whether that error indicates another mode is available which we could support somehow, or it is just a glitch that happens at startup.

**Comment by odeBuXTeR** [comment]
Thank you, that's what I did manualy on the config file, all seems working fine, the only behavior observed is on ha start/restart, the pool is in unknown state, don't have the time for the moment to find how bypass this, I'll keep you in touch.Kind regardsOlivierLe 18 sept. 2022 12:16, Jason Rumney ***@***.***> a écrit :
Based on your comment "all are in grey", fan_only might be disabling something, so \i've changed to heat_cool instead.  Also added that as a default fallback to avoid the error message, though unsure whether that error indicates another mode is available which we could support somehow, or it is just a glitch that happens at startup.

**Comment by make-all** [comment]
It will take some time after startup to establish communication with the device.  There is some autodetection of some Tuya protocol options that has to happen first.
