### ISSUE TITLE
Since last update a few devices do not connect anymore

### ISSUE THREAD

**Issue by vanhoofseppe** [make-all/tuya-local#1661]
They are listed as if they need to be reconfigured:
![image](https://github.com/make-all/tuya-local/assets/6939626/7baaf3be-d4d9-4558-857c-8ad90dfab599)

**LOG:**
	Line 16271: 2024-02-16 11:25:38.837 ERROR (MainThread) [custom_components.tuya_local] Configuration file for rgbcw_lightbulb not found
	Line 16732: 2024-02-16 11:25:47.707 ERROR (MainThread) [custom_components.tuya_local] Configuration file for rgbcw_lightbulb not found
	Line 17177: 2024-02-16 11:25:52.764 ERROR (MainThread) [custom_components.tuya_local] Configuration file for simple_triple_switch_timer not found

If I click configure from the integration interface I get the error 'Sorry, there is no support for this device'.
![image](https://github.com/make-all/tuya-local/assets/6939626/29951894-4ed7-4689-98a6-3d1b6977813a)

But they have worked the past year.

**Comment by make-all** [comment]
Something seems to have gone wrong with your installation. You will probably need to reinstall the integration.
