### ISSUE TITLE
Request support for Tongou Circuit Breaker With Energy Monitoring – TO-Q-ST463JWT 4P

### ISSUE THREAD

**Issue by realdimik** [make-all/tuya-local#1667]
# Log Message

```
2024-02-18 13:30:00.028 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config tompd_63lw_breaker.yaml
2024-02-18 13:30:00.071 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config tongou_qcb2_circuitbreaker.yaml
2024-02-18 13:30:00.072 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Not match for Circuit breaker, missing required DPs: [{'102': 'str'}, {'103': 'str'}, {'104': 'str'}, {'105': 'str'}, {'107': 'str'}, {'109': 'str'}, {'110': 'str'}, {'112': 'bool'}, {'114': 'int'}, {'115': 'int'}, {'116': 'int'}, {'118': 'int'}, {'119': 'int'}, {'125': 'int'}, {'126': 'int'}, {'127': 'int'}, {'131': 'int'}, {'132': 'int'}, {'133': 'int'}, {'134': 'int'}, {'139': 'int'}]

```

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"00000208px\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",
	\"properties\":[
{\"abilityId\":1,\"accessMode\":\"ro\",\"code\":\"total_forward_energy\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"正向总有功电量\",\"typeSpec\":{\"max\":99999999,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"kW·h\"}},
{\"abilityId\":6,\"accessMode\":\"ro\",\"code\":\"phase_a\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"A相电压，电流及功率\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":7,\"accessMode\":\"ro\",\"code\":\"phase_b\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"B相电压，电流及功率\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":8,\"accessMode\":\"ro\",\"code\":\"phase_c\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"C相电压，电流及功率\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":9,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"故障告警\",\"typeSpec\":{\"label\":[\"short_circuit_alarm\",\"surge_alarm\",\"overload_alarm\",\"leakagecurr_alarm\",\"temp_dif_fault\",\"fire_alarm\",\"high_power_alarm\",\"self_test_alarm\",\"ov_cr\",\"unbalance_alarm\",\"ov_vol\",\"undervoltage_alarm\",\"miss_phase_alarm\",\"outage_alarm\",\"magnetism_alarm\",\"credit_alarm\",\"no_balance_alarm\"],\"maxlen\":17,\"type\":\"bitmap\",\"typeDefaultValue\":0}},
{\"abilityId\":11,\"accessMode\":\"rw\",\"code\":\"switch_prepayment\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"预付费功能开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":12,\"accessMode\":\"rw\",\"code\":\"clear_energy\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"剩余可用电量清零\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":13,\"accessMode\":\"ro\",\"code\":\"balance_energy\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"剩余可用电量显示\",\"typeSpec\":{\"max\":99999999,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"kW·h\"}},
{\"abilityId\":14,\"accessMode\":\"rw\",\"code\":\"charge_energy\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"电量充值\",\"typeSpec\":{\"max\":999999,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"kW·h\"}},
{\"abilityId\":15,\"accessMode\":\"ro\",\"code\":\"leakage_current\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"剩余电流显示\",\"typeSpec\":{\"max\":1000,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"mA\"}},
{\"abilityId\":16,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"断路器拉合闸\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":17,\"accessMode\":\"rw\",\"code\":\"alarm_set_1\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"告警设置1\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":18,\"accessMode\":\"rw\",\"code\":\"alarm_set_2\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"告警设置2\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":19,\"accessMode\":\"ro\",\"code\":\"breaker_id\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"设备号显示\",\"typeSpec\":{\"maxlen\":255,\"type\":\"string\",\"typeDefaultValue\":\"\"}},
{\"abilityId\":21,\"accessMode\":\"rw\",\"code\":\"leakagecurr_test\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"剩余电流测试\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}}]}]}"
  },
  "success": true,
  "t": 1708251336840,
  "tid": "a89a3e81ce4611ee9fb272b4dd63a2de"
}
```

# Product ID

      "model": "ZC03W",
      "name": "breaker",
      "product_id": "jexpyxmyl0gubapl",
      "product_name": "智能断路器",

# Information about how the device functions

Device is detected as tompd_63lw_breaker and show only single phase, when it has actually 3 phases
(one phase works correctly)
https://www.aliexpress.com/item/1005003008120962.html
https://elcb.net/product/smart-control-circuit-breaker-three-phase-rcbo/

**Comment by make-all** [comment]
Sorry it isn't clear from the huge debug log dump what device you are trying to add.  There don't even seem to be any `full_poll: true` dps captured in there, just single dp updates for an already configured device.  For a new device request it is better to include only the WARNING level message containing the dps detected during the process of adding the device.

**Comment by realdimik** [comment]
Thank you for the fast reply.
I've deleted the device, switched logs on and add the device again. I can see only warning about termination, but no warnings about adding in Settings/System/Logs and 'cat /homeassistant/home-assistant.log | grep DPS' is also empty.
The device is detected as tompd_63lw_breaker. That it is not correct. tompd_63lw_breaker has only single phase, mine one has three. 
I'm newbie in HA. Please tell me what I can do more to make your job easier.

**Comment by realdimik** [comment]
I've found by tompd in home-assistant.log

2024-02-18 13:30:00.028 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config tompd_63lw_breaker.yaml
2024-02-18 13:30:00.071 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config tongou_qcb2_circuitbreaker.yaml
2024-02-18 13:30:00.072 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Not match for Circuit breaker, missing required DPs: [{'102': 'str'}, {'103': 'str'}, {'104': 'str'}, {'105': 'str'}, {'107': 'str'}, {'109': 'str'}, {'110': 'str'}, {'112': 'bool'}, {'114': 'int'}, {'115': 'int'}, {'116': 'int'}, {'118': 'int'}, {'119': 'int'}, {'125': 'int'}, {'126': 'int'}, {'127': 'int'}, {'131': 'int'}, {'132': 'int'}, {'133': 'int'}, {'134': 'int'}, {'139': 'int'}]

Is it what you need?

**Comment by make-all** [comment]
No this is list of all the expectations for tongou_qcb2_circuitbreaker that are NOT met by your device, but there is no information there of what your device is actually sending.  I am a bit confused as to why you are getting these DEBUG messages during the config matching, but not the WARNING level one at the end of all the matching showing the DPS and the closest matching config with % matched.  This used to be suppressed if the config was 100% matched, but since 2024.2.0 it should be always output (as the number of configs has grown to the point where a false 100% match is quite likely).

**Comment by realdimik** [comment]
The Home Assistant Core is 2024.2.1.
The only warning I have ('cat /homeassistant/home-assistant.log | grep WARN') is:
```
WARNING (MainThread) [custom_components.tuya_local.device] Горячая вода и отопление receive loop has terminated
```
when I deleted the device from HA.
I've tried even change logs level in configuration.yaml to 

```
logger:
  default: debug
  logs:
    custom_components.tuya_local: warning

```

and for

```
logger:
  default: warning

```
same results.

But finally (if debugs logs are on) I always have
```
2024-02-18 14:06:09.442 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config tompd_63lw_breaker.yaml
```
It means for me that tompd_63lw_breaker was chosen.

Could be the reason of missed choice in logs that I was asked to choose between two devices in UI during adding? I'd tried both and found that tompd_63lw_breaker works better for me. And after that I'm always choosing it.

**Comment by make-all** [comment]
It seems I didn't commit the change I thought I had made to the main branch.  So assuming that your device must be a 100% match for tompd_63lw + additional dps for the other phases.  Probably the best way to get the data is to download the device diagnostics from Settings / Devices / Tuya-local (your device) / Download Diagnostics

**Comment by realdimik** [comment]
Here you are
[tuya_local-2a66aa05d87f1ec94f75ccb4a2b27e81-Горячая вода и отопление-c8b33e3bab41cb7040ac5e8018d49ee2.json](https://github.com/make-all/tuya-local/files/14322653/tuya_local-2a66aa05d87f1ec94f75ccb4a2b27e81-.-c8b33e3bab41cb7040ac5e8018d49ee2.json)

**Comment by realdimik** [comment]
It works for me. Thank you!
![image](https://github.com/make-all/tuya-local/assets/29751341/6719b501-d2ca-4626-8dce-1943384db852)
