### ISSUE TITLE
Eightree smart plug e29

### ISSUE THREAD

**Issue by Th0tti** [make-all/tuya-local#1668]
When integrating Tuya, my sockets (Category cz, Eightree e29) are not recognized.  The following error is reported as a log.

Connection test failed with <class 'Exception'> Unable to find device on network (specify IP address)

When I enter the IP address I get the following error

Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect.

'Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:431
Integration: tuya_local (documentation, issues)
First occurred: 21:03:38 (1 occurrences)
Last logged: 21:03:38

Test protocol error 904: Unexpected Payload from Device

The following information is displayed to me in the IOT

{ "result": [ { "active_time": 1708285645, "bind_space_id": "182590374", "category": "cz", "create_time": 1707513699, "custom_name": "eightree", "icon": "smart/icon/ay1544008322541hl9iQ/1afec15631dbe7c0eb36052a43b41a15.png", "id": "bf32e80814726830dbcsev", "ip": "xxxx", "is_online": true, "lat": "53.6112", "local_key": "xxxx", "lon": "7.2764", "model": "SP22S", "name": "WLAN Steckdose 2", "product_id": "b1ifw50hk0mb069f", "product_name": "双向计量", "sub": false, "time_zone": "+01:00", "update_time": 1708285673, "uuid": "f6301ed48cb834d9" } ], "success": true, "t": 1708286469091, "tid": "75172cd0ce9811ee9fb272b4dd63a2de" }

Can u help me? What data is needed?

**Comment by make-all** [comment]
You are not reporting a bug here,you are asking for help. This would be best suited for Discussions. There is already a discussion for connection issues in #522 which likely already has the answer you ar looking for - possibly your device is one of the newer protocol versions that don't seem to  work as well with auto detection.
