### ISSUE TITLE
Bug report for ZX-G30 alarm system

### ISSUE THREAD

**Issue by dmotkan** [make-all/tuya-local#1673]
Hello colleagues.
I have a problem with the ZX-G30 alarm system.
Integration works, with the exception of alarm warning. After connecting, I have 1 device and 14 objects. Arming and disarming works, reports about the low charge of the battery, etc work. They are displayed in the journal of events. However, the most necessary event I need - the alarm is not reflected there. As a result, I cannot configure the scenari I need. I want to note that the integration of Tuya also does not reflect the alarm operation in journal. I received all the possible data from Iot.tuya.com. And found the absence of some dp_id in your device configuration file. 

In the log iot.tuya alarm message  looks like this 
`      {
        "code": "master_state",
        "event_from": "1",
        "event_id": 7,
        "event_time": xxxxxxxxxxxxxxx,
        "status": "1",
        "value": "alarm"
      },
`

dp_id 32 which may be responsible for notification of the alarm trigger:
`Query Things:
{\"abilityId\":32,
\"accessMode\":\"rw\",
\"code\":\"master_state\",
\"description\":\"0 ??(????)\\n1 ??\",
\"extensions\":{\"iconName\":\"icon-dp_shield\"},
\"name\":\"????\",
\"typeSpec\":{\"range\":[\"normal\",\"alarm\"],
\"type\":\"enum\",
\"typeDefaultValue\":\"normal\"}} `

In addition, there may be a typo in dp_id 9 :  temper_alarm
`Query Things:
{\"abilityId\":9,
\"accessMode\":\"ro\",
\"code\":\"temper_alarm\",
\"description\":\"true??\\nfalse??\",
\"extensions\":{\"iconName\":\"icon-dp_tool\"},
\"name\":\"????\",
\"typeSpec\":{\"type\":\"bool\",
\"typeDefaultValue\":false}} `

Best regards, dmotkan .

**Comment by make-all** [comment]
I'm pretty sure the typo is on Tuya's side, as a tamper alarm is standard on security products to alert when someone tries to tamper with it.

**Comment by make-all** [comment]
It might be useful to get the full QueryThingsDataModel output for this device, as there are a lot of "unknown" dps in the config.

**Comment by dmotkan** [comment]
Possibly a typo in Tuya.
However, when I move the slider corresponding to this ID in the web interface, no changes occur in the alarm system.
I am attaching the QueryThingsDataModel file. The original model is displayed in one line. 
[ZX-G30_ThingsDataModel.txt](https://github.com/make-all/tuya-local/files/14364137/ZX-G30_ThingsDataModel.txt)

**Comment by make-all** [comment]
```
{
  "result": {
    "model": "{\"modelId\":\"00000040ox\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"????\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"master_mode\",\"description\":\"disarmed??\\narm??\\nhome??\\nsos??\",\"extensions\":{\"iconName\":\"icon-dp_mode\"},\"name\":\"????\",\"typeSpec\":{\"range\":[\"disarmed\",\"arm\",\"home\",\"sos\"],\"type\":\"enum\",\"typeDefaultValue\":\"disarmed\"}},
{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"delay_set\",\"description\":\"????,??????????????\",\"extensions\":{\"iconName\":\"icon-zanting1\"},\"name\":\"????\",\"typeSpec\":{\"max\":300,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"?\"}},
{\"abilityId\":3,\"accessMode\":\"rw\",\"code\":\"alarm_time\",\"description\":\"????,????\",\"extensions\":{\"iconName\":\"icon-a_nav_timer\"},\"name\":\"????\",\"typeSpec\":{\"max\":60,\"min\":1,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":1,\"unit\":\"??\"}},
{\"abilityId\":4,\"accessMode\":\"rw\",\"code\":\"switch_alarm_sound\",\"description\":\"true??\\nfalse??\",\"extensions\":{\"iconName\":\"icon-power\"},\"name\":\"?????\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":9,\"accessMode\":\"ro\",\"code\":\"temper_alarm\",\"description\":\"true??\\nfalse??\",\"extensions\":{\"iconName\":\"icon-dp_tool\"},\"name\":\"????\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":10,\"accessMode\":\"rw\",\"code\":\"switch_mode_sound\",\"description\":\"true?????\\nfalse?????\",\"extensions\":{\"iconName\":\"icon-power\"},\"name\":\"??????\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":15,\"accessMode\":\"ro\",\"code\":\"charge_state\",\"description\":\"true??????\\nfalse??????\",\"extensions\":{\"iconName\":\"icon-power1\"},\"name\":\"?????\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":16,\"accessMode\":\"ro\",\"code\":\"battery_percentage\",\"description\":\"????????\",\"extensions\":{\"iconName\":\"icon-dp_battery\"},\"name\":\"????\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%\"}},
{\"abilityId\":17,\"accessMode\":\"rw\",\"code\":\"switch_low_battery\",\"description\":\"true?????????\\nfalse???????\",\"extensions\":{\"iconName\":\"icon-dianliang\"},\"name\":\"????????\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":18,\"accessMode\":\"rw\",\"code\":\"alarm_call_number\",\"description\":\"??????,??????\",\"name\":\"??????\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":19,\"accessMode\":\"rw\",\"code\":\"alarm_sms_number\",\"description\":\"??????,??????\",\"name\":\"??????\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":20,\"accessMode\":\"rw\",\"code\":\"switch_alarm_call\",\"description\":\"true??\\nfalse??\",\"extensions\":{\"iconName\":\"icon-guanjia\"},\"name\":\"????\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":21,\"accessMode\":\"rw\",\"code\":\"switch_alarm_sms\",\"description\":\"????????????\\ntrue ??\\nfalse??\",\"extensions\":{\"iconName\":\"icon-dp_doc2\"},\"name\":\"????\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":22,\"accessMode\":\"rw\",\"code\":\"call_looptimes\",\"description\":\"????????????\",\"extensions\":{\"iconName\":\"icon-p12\"},\"name\":\"?????????\",\"typeSpec\":{\"max\":10,\"min\":1,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":1,\"unit\":\"\"}},
{\"abilityId\":23,\"accessMode\":\"ro\",\"code\":\"telnet_state\",\"description\":\"1 ??\\n2 ???\\n3 ?????\\n4 ??????\",\"extensions\":{\"iconName\":\"icon-fengli\"},\"name\":\"??????\",\"typeSpec\":{\"range\":[\"1\",\"2\",\"3\",\"4\"],\"type\":\"enum\",\"typeDefaultValue\":\"1\"}},
{\"abilityId\":24,\"accessMode\":\"rw\",\"code\":\"zone_attribute\",\"description\":\"Normal ??\\n24Hours 24??\\nDelay ??\\nHome  ??\\n24HoursMute 24????\\nHomeDelay ?????\\nOff ??\",\"extensions\":{\"iconName\":\"icon-a_fan_auto\"},\"name\":\"????\",\"typeSpec\":{\"range\":[\"Normal\",\"24Hours\",\"Delay\",\"Home\",\"24HoursMute\",\"HomeDelay\",\"Off\"],\"type\":\"enum\",\"typeDefaultValue\":\"Normal\"}},
{\"abilityId\":25,\"accessMode\":\"rw\",\"code\":\"muffling\",\"description\":\"true????(????)\\nfalse??\",\"extensions\":{\"iconName\":\"icon-Mute\"},\"name\":\"??\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":26,\"accessMode\":\"rw\",\"code\":\"alarm_msg\",\"description\":\"??UTF16(??????)\",\"name\":\"????\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":27,\"accessMode\":\"rw\",\"code\":\"switch_alarm_propel\",\"description\":\"true??\\nfalse??\",\"extensions\":{\"iconName\":\"icon-dp_chat\"},\"name\":\"????\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":28,\"accessMode\":\"rw\",\"code\":\"alarm_delay_time\",\"description\":\"???????????\",\"extensions\":{\"iconName\":\"icon-timer1\"},\"name\":\"????\",\"typeSpec\":{\"max\":300,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"?\"}},
{\"abilityId\":29,\"accessMode\":\"rw\",\"code\":\"switch_mode_dl_sound\",\"description\":\"true??\\nfalse??\",\"extensions\":{\"iconName\":\"icon-dp_time\"},\"name\":\"??????\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":32,\"accessMode\":\"rw\",\"code\":\"master_state\",\"description\":\"0 ??(????)\\n1 ??\",\"extensions\":{\"iconName\":\"icon-dp_shield\"},\"name\":\"????\",\"typeSpec\":{\"range\":[\"normal\",\"alarm\"],\"type\":\"enum\",\"typeDefaultValue\":\"normal\"}},
{\"abilityId\":33,\"accessMode\":\"ro\",\"code\":\"master_information\",\"description\":\"\",\"name\":\"????\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":34,\"accessMode\":\"rw\",\"code\":\"factory_reset\",\"description\":\"true????(????)\\nfalse????\",\"extensions\":{\"iconName\":\"icon-dp_anti-clockwise\"},\"name\":\"??????\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":35,\"accessMode\":\"rw\",\"code\":\"sub_add\",\"description\":\"true ??\\nfalse ????\",\"extensions\":{\"iconName\":\"icon-dp_plus\"},\"name\":\"?????\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":36,\"accessMode\":\"rw\",\"code\":\"sub_class\",\"description\":\"0 ???  1 ??? 2 ????? 3 RFID\",\"extensions\":{\"iconName\":\"icon-dp_direction\"},\"name\":\"?????\",\"typeSpec\":{\"range\":[\"0\",\"1\",\"2\",\"3\"],\"type\":\"enum\",\"typeDefaultValue\":\"0\"}},
{\"abilityId\":37,\"accessMode\":\"rw\",\"code\":\"sub_type\",\"description\":\"0 ???? 1 ??  2 ?? 3 ?? 4 CO  5 ?? 6 ?? 7 ???? 8 ???? 9 ???? 10 ?? 11 ????? 12 ??\",\"extensions\":{\"iconName\":\"icon-dp_list\"},\"name\":\"?????\",\"typeSpec\":{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\"],\"type\":\"enum\",\"typeDefaultValue\":\"0\"}},
{\"abilityId\":38,\"accessMode\":\"rw\",\"code\":\"sub_admin\",\"description\":\"?????,??,????,????,?????,????,??????\",\"name\":\"?????\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":39,\"accessMode\":\"ro\",\"code\":\"sub_state\",\"description\":\"0??\\n1??\\n2??\\n3??\",\"extensions\":{\"iconName\":\"icon-shoucang\"},\"name\":\"?????\",\"typeSpec\":{\"range\":[\"0\",\"1\",\"2\",\"3\"],\"type\":\"enum\",\"typeDefaultValue\":\"0\"}},
{\"abilityId\":40,\"accessMode\":\"rw\",\"code\":\"master_language\",\"description\":\"0\\\\1\\\\2\\\\3\\\\4\\\\5\\\\6\\\\7\\\\8\\\\9\\\\\\n?\\\\??/?\\\\?\\\\?\\\\?\\\\?\\\\?\\\\?\\\\?\\n?  ??????(?????)\",\"extensions\":{\"iconName\":\"icon-dp_doc\"},\"name\":\"????\",\"typeSpec\":{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\"],\"type\":\"enum\",\"typeDefaultValue\":\"0\"}}]}]}"
  },
  "success": true,
  "t": -----------,
  "tid": "----------------------------"
}
```

**Comment by make-all** [comment]
In the QueryThingsDataModel result, temper_alarm is marked as "ro", which indicates it should not be a switch, but a binary_sensor, so it is expected that changing the switch state that is in the UI currently does not do anything. This is why it is useful to have that data, it tells a lot about the expected function of the dps as well as the name to id mappings.

**Comment by make-all** [comment]
It is a shame the Chinese characters got corrupted by the file upload, a lot of info is still missing due to descriptions that can no longer be translated.

**Comment by dmotkan** [comment]
Now I’ll upload it via the GitHub form. Chinese characters should be readable if the appropriate fonts are installed.  In Mozilla Firefox, hieroglyphs are drawn.
`"result": {
    "model": "{\"modelId\":\"00000040ox\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"master_mode\",\"description\":\"disarmed撤防\\narm布防\\nhome在家\\nsos紧急\",\"extensions\":{\"iconName\":\"icon-dp_mode\"},\"name\":\"主机模式\",\"typeSpec\":{\"range\":[\"disarmed\",\"arm\",\"home\",\"sos\"],\"type\":\"enum\",\"typeDefaultValue\":\"disarmed\"}},{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"delay_set\",\"description\":\"设置成功，经延时设定时间后主机模式生效\",\"extensions\":{\"iconName\":\"icon-zanting1\"},\"name\":\"退出延时\",\"typeSpec\":{\"max\":300,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"秒\"}},{\"abilityId\":3,\"accessMode\":\"rw\",\"code\":\"alarm_time\",\"description\":\"单次报警，持续时长\",\"extensions\":{\"iconName\":\"icon-a_nav_timer\"},\"name\":\"报警时长\",\"typeSpec\":{\"max\":60,\"min\":1,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":1,\"unit\":\"分钟\"}},{\"abilityId\":4,\"accessMode\":\"rw\",\"code\":\"switch_alarm_sound\",\"description\":\"true打开\\nfalse关闭\",\"extensions\":{\"iconName\":\"icon-power\"},\"name\":\"报警声开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":9,\"accessMode\":\"ro\",\"code\":\"temper_alarm\",\"description\":\"true打开\\nfalse关闭\",\"extensions\":{\"iconName\":\"icon-dp_tool\"},\"name\":\"防拆报警\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":10,\"accessMode\":\"rw\",\"code\":\"switch_mode_sound\",\"description\":\"true开启提示音\\nfalse关闭提示音\",\"extensions\":{\"iconName\":\"icon-power\"},\"name\":\"布撤防提示音\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":15,\"accessMode\":\"ro\",\"code\":\"charge_state\",\"description\":\"true默认正常供电\\nfalse表示电源断开\",\"extensions\":{\"iconName\":\"icon-power1\"},\"name\":\"主电源状态\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":16,\"accessMode\":\"ro\",\"code\":\"battery_percentage\",\"description\":\"设备当前电量状态\",\"extensions\":{\"iconName\":\"icon-dp_battery\"},\"name\":\"电池电量\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%\"}},{\"abilityId\":17,\"accessMode\":\"rw\",\"code\":\"switch_low_battery\",\"description\":\"true正常开启低电量报警\\nfalse关闭低电量报警\",\"extensions\":{\"iconName\":\"icon-dianliang\"},\"name\":\"探测器低电量报警\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":18,\"accessMode\":\"rw\",\"code\":\"alarm_call_number\",\"description\":\"本地设定电话，网关自动拨打\",\"name\":\"报警电话号码\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},{\"abilityId\":19,\"accessMode\":\"rw\",\"code\":\"alarm_sms_number\",\"description\":\"本地设定短信，网关自动推送\",\"name\":\"报警短信号码\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},{\"abilityId\":20,\"accessMode\":\"rw\",\"code\":\"switch_alarm_call\",\"description\":\"true打开\\nfalse关闭\",\"extensions\":{\"iconName\":\"icon-guanjia\"},\"name\":\"报警电话\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":21,\"accessMode\":\"rw\",\"code\":\"switch_alarm_sms\",\"description\":\"是否开启网关本身推送短信\\ntrue 开启\\nfalse关闭\",\"extensions\":{\"iconName\":\"icon-dp_doc2\"},\"name\":\"报警短信\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":22,\"accessMode\":\"rw\",\"code\":\"call_looptimes\",\"description\":\"电话未接通时持续拨打次数\",\"extensions\":{\"iconName\":\"icon-p12\"},\"name\":\"未接听重复拨打次数\",\"typeSpec\":{\"max\":10,\"min\":1,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":1,\"unit\":\"\"}},{\"abilityId\":23,\"accessMode\":\"ro\",\"code\":\"telnet_state\",\"description\":\"1 正常\\n2 无网络\\n3 无电话模块\\n4 电话卡未插入\",\"extensions\":{\"iconName\":\"icon-fengli\"},\"name\":\"电话网络状态\",\"typeSpec\":{\"range\":[\"1\",\"2\",\"3\",\"4\"],\"type\":\"enum\",\"typeDefaultValue\":\"1\"}},{\"abilityId\":24,\"accessMode\":\"rw\",\"code\":\"zone_attribute\",\"description\":\"Normal 正常\\n24Hours 24小时\\nDelay 延时\\nHome  在家\\n24HoursMute 24小时无声\\nHomeDelay 在家有延时\\nOff 关闭\",\"extensions\":{\"iconName\":\"icon-a_fan_auto\"},\"name\":\"防区属性\",\"typeSpec\":{\"range\":[\"Normal\",\"24Hours\",\"Delay\",\"Home\",\"24HoursMute\",\"HomeDelay\",\"Off\"],\"type\":\"enum\",\"typeDefaultValue\":\"Normal\"}},{\"abilityId\":25,\"accessMode\":\"rw\",\"code\":\"muffling\",\"description\":\"true消音启用（下发消音）\\nfalse默认\",\"extensions\":{\"iconName\":\"icon-Mute\"},\"name\":\"消音\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":26,\"accessMode\":\"rw\",\"code\":\"alarm_msg\",\"description\":\"采用UTF16（原始内容转译）\",\"name\":\"告警信息\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},{\"abilityId\":27,\"accessMode\":\"rw\",\"code\":\"switch_alarm_propel\",\"description\":\"true打开\\nfalse关闭\",\"extensions\":{\"iconName\":\"icon-dp_chat\"},\"name\":\"告警推送\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":28,\"accessMode\":\"rw\",\"code\":\"alarm_delay_time\",\"description\":\"告警后多长时间开始报警\",\"extensions\":{\"iconName\":\"icon-timer1\"},\"name\":\"进入延时\",\"typeSpec\":{\"max\":300,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"秒\"}},{\"abilityId\":29,\"accessMode\":\"rw\",\"code\":\"switch_mode_dl_sound\",\"description\":\"true打开\\nfalse关闭\",\"extensions\":{\"iconName\":\"icon-dp_time\"},\"name\":\"倒计时提示音\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":32,\"accessMode\":\"rw\",\"code\":\"master_state\",\"description\":\"0 正常（解除报警）\\n1 报警\",\"extensions\":{\"iconName\":\"icon-dp_shield\"},\"name\":\"主机状态\",\"typeSpec\":{\"range\":[\"normal\",\"alarm\"],\"type\":\"enum\",\"typeDefaultValue\":\"normal\"}},{\"abilityId\":33,\"accessMode\":\"ro\",\"code\":\"master_information\",\"description\":\"\",\"name\":\"主机信息\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},{\"abilityId\":34,\"accessMode\":\"rw\",\"code\":\"factory_reset\",\"description\":\"true恢复出厂（下发操作）\\nfalse通常状态\",\"extensions\":{\"iconName\":\"icon-dp_anti-clockwise\"},\"name\":\"恢复出厂设置\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":35,\"accessMode\":\"rw\",\"code\":\"sub_add\",\"description\":\"true 添加\\nfalse 添加结束\",\"extensions\":{\"iconName\":\"icon-dp_plus\"},\"name\":\"添加子设备\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":36,\"accessMode\":\"rw\",\"code\":\"sub_class\",\"description\":\"0 探测器  1 遥控器 2 有线探测器 3 RFID\",\"extensions\":{\"iconName\":\"icon-dp_direction\"},\"name\":\"子设备品类\",\"typeSpec\":{\"range\":[\"0\",\"1\",\"2\",\"3\"],\"type\":\"enum\",\"typeDefaultValue\":\"0\"}},{\"abilityId\":37,\"accessMode\":\"rw\",\"code\":\"sub_type\",\"description\":\"0 人体红外 1 门磁  2 烟雾 3 燃气 4 CO  5 振动 6 水浸 7 红外对射 8 玻璃破碎 9 紧急按钮 10 门铃 11 环境探测器 12 其它\",\"extensions\":{\"iconName\":\"icon-dp_list\"},\"name\":\"子设备类别\",\"typeSpec\":{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\"],\"type\":\"enum\",\"typeDefaultValue\":\"0\"}},{\"abilityId\":38,\"accessMode\":\"rw\",\"code\":\"sub_admin\",\"description\":\"子设备序号，类型，防区属性，开启关联，名称字节数，工作状态，电量状态等等\",\"name\":\"子设备管理\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},{\"abilityId\":39,\"accessMode\":\"ro\",\"code\":\"sub_state\",\"description\":\"0正常\\n1报警\\n2故障\\n3其它\",\"extensions\":{\"iconName\":\"icon-shoucang\"},\"name\":\"子设备状态\",\"typeSpec\":{\"range\":[\"0\",\"1\",\"2\",\"3\"],\"type\":\"enum\",\"typeDefaultValue\":\"0\"}},{\"abilityId\":40,\"accessMode\":\"rw\",\"code\":\"master_language\",\"description\":\"0\\\\1\\\\2\\\\3\\\\4\\\\5\\\\6\\\\7\\\\8\\\\9\\\\\\n中\\\\繁体/英\\\\法\\\\意\\\\德\\\\西\\\\葡\\\\俄\\\\日\\n指——本地主机面板（有语言显示）\",\"extensions\":{\"iconName\":\"icon-dp_doc\"},\"name\":\"主机语言\",\"typeSpec\":{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\"],\"type\":\"enum\",\"typeDefaultValue\":\"0\"}}]}]}"
  },
`
