### ISSUE TITLE
Reload service after restart wi-fi

### ISSUE THREAD

**Issue by diemon24** [make-all/tuya-local#1674]
Please add in HA service to reload device or all integration. Some wi-fi devices after disconnected not available in HA. Only change state this device in Smart Life app allows become available in HA. If I can create automation with reload devices that would be perfect.

**Comment by make-all** [comment]
This is not a bug report concerning this integration, but a feature request for Home Assistant itself, for a feature which already exists in the service `homeassistant.reload_config_entry`
