### ISSUE TITLE
Request support for [siguro sgr hd f300w dehumidifier]

### ISSUE THREAD

**Issue by fumantsu** [make-all/tuya-local#1676]
Hello, 
I have create a yaml file dealing with most if not all functions. Only "issue" is this:
```
Platform tuya_local does not generate unique IDs. ID bffd33db0f43a741bdwzuk-switch_ionizer already exists - ignor
ing switch.siguro_dehumidifier_ionizer

```
I'm not sure what is the issue.

[siguro_sgr_hd_f300w_dehumidifier.yaml.txt](https://github.com/make-all/tuya-local/files/14365419/siguro_sgr_hd_f300w_dehumidifier.yaml.txt)

**Comment by make-all** [comment]
The issue will be that you somehow managed to get the device set up twice.

**Comment by fumantsu** [comment]
@make-all I provided the file for supporting the device (maybe some check will be good) and you close it as not planned?

**Comment by make-all** [comment]
I currently lack the time to even get through the queue of high quality reports that follow the simple instructions on the issue templates.  The chances of ever getting to this issue with all the information in an attachment that I have to download and view offline, and which apparently has some issue so requires careful review with no supporting logs or tuya documentation, is zero, so it might as well be closed.

**Comment by fumantsu** [comment]
ok, lack of time is understandable. Just closing like this while I trying to help you a bit with a working configuration (so less research) was little odd.
