### ISSUE TITLE
Request support for BSD33 EU Smart Plug w/ power and energy metering - like smartplugv2_energyv3.yaml but not exactly

### ISSUE THREAD

**Issue by convicte** [make-all/tuya-local#1689]
# Log Message

```
No logs are availble as the plug is incorrectly identified as a bulb and LED strip
```

# Information about DPS mappings

```
"result": {
    "model": "{\"modelId\":\"0000003uz9\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"1\"},\"name\":\"开关1\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":9,\"accessMode\":\"rw\",\"code\":\"countdown_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\"},\"name\":\"开关1倒计时\",\"typeSpec\":{\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"s\"}},
{\"abilityId\":17,\"accessMode\":\"rw\",\"code\":\"add_ele\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-battery\"},\"name\":\"增加电量\",\"typeSpec\":{\"max\":50000,\"min\":0,\"scale\":3,\"step\":100,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"kwh\"}},
{\"abilityId\":18,\"accessMode\":\"ro\",\"code\":\"cur_current\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-Ele\"},\"name\":\"当前电流\",\"typeSpec\":{\"max\":30000,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"mA\"}},
{\"abilityId\":19,\"accessMode\":\"ro\",\"code\":\"cur_power\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_tool\"},\"name\":\"当前功率\",\"typeSpec\":{\"max\":50000,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"W\"}},
{\"abilityId\":20,\"accessMode\":\"ro\",\"code\":\"cur_voltage\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-a_function_turbo\"},\"name\":\"当前电压\",\"typeSpec\":{\"max\":5000,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"V\"}},
{\"abilityId\":21,\"accessMode\":\"ro\",\"code\":\"test_bit\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_direction\"},\"name\":\"产测结果位\",\"typeSpec\":{\"max\":5,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},
{\"abilityId\":22,\"accessMode\":\"ro\",\"code\":\"voltage_coe\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-gaodiyin\"},\"name\":\"电压校准系数\",\"typeSpec\":{\"max\":1000000,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},
{\"abilityId\":23,\"accessMode\":\"ro\",\"code\":\"electric_coe\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-gaodiyin\"},\"name\":\"电流校准系数\",\"typeSpec\":{\"max\":1000000,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},
{\"abilityId\":24,\"accessMode\":\"ro\",\"code\":\"power_coe\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-gaodiyin\"},\"name\":\"功率校准系数\",\"typeSpec\":{\"max\":1000000,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},
{\"abilityId\":25,\"accessMode\":\"ro\",\"code\":\"electricity_coe\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-gaodiyin\"},\"name\":\"电量校准系数\",\"typeSpec\":{\"max\":1000000,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},
{\"abilityId\":26,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-baojing\"},\"name\":\"过流故障上报\",\"typeSpec\":{\"label\":[\"ov_cr\"],\"maxlen\":1,\"type\":\"bitmap\",\"typeDefaultValue\":0}}]}]}"
  },
  "success": true,
  "t": 1709241051203,
```

# Product ID

```
      "name": "Smart Plug 5",
      "product_id": "gvsnpmrhp1ktgawm",
      "product_name": "TC0025_TW02_PLUG_DLTJL1_P1",
      "sub": false,
```

# Information about how the device functions

Product Aliexpress page:
https://www.aliexpress.com/item/1005004761870895.html
Tuya API Standard Status page:
![image](https://github.com/make-all/tuya-local/assets/78666770/9700f506-b4a5-4f69-9843-f1d42fb10c9a)

There is major overlap with `custom_components/tuya_local/devices/smartplugv2_energyv3.yaml`, but when adding the product_id in my local files and rebooting HA it still doesn't get recognized as such.
I've used this process before and always worked for matching devices, but here for some reason it doesn't.
The only major difference I've found is ```DPS: 17 \"unit\":\"kwh\"}}``` while the existing sensor in `energyv3` has:
```    category: diagnostic
    name: Energy
    dps:
      - id: 17
        name: sensor
        type: integer
        unit: Wh
        optional: true
```
        
If someone could point me in the right direction, why the local addition of the product_id doesn't work, I could attempt a pull for this. Without it, I am lost here why it's not like all the others.

**Comment by make-all** [comment]
product_id is not yet used for matching.  If your device is being misdetected as a light, then there must be a log message when that happens.  Without that message it is impossible to tell what is going wrong.

**Comment by convicte** [comment]
Selecting the RGBLED in the config flow doesn't generate a reasonable entry, like the one described above.

![image](https://github.com/make-all/tuya-local/assets/78666770/40deb46d-225f-4e47-b73a-3081e9f583c9)

This error originated from a custom integration.

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:80
Integration: Tuya Local (documentation, issues)
First occurred: 23:42:13 (1 occurrences)
Last logged: 23:42:13

<class 'Exception'>: Unable to find device on network (specify IP address) while initialising device REDACTED

This said, when I provide all the possible information, including the IP address found for the plug on my network, I get a config flow error:

![image](https://github.com/make-all/tuya-local/assets/78666770/cb592191-3e41-4480-aa39-7c4d0545e7d5)

When I remove the device IP, I get the error:

Logger: homeassistant.util.async_
Source: util/async_.py:141
First occurred: February 29, 2024 at 23:52:06 (7 occurrences)
Last logged: 00:10:39

Detected blocking call to sleep inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/device.py, line 77: self._api = tinytuya.Device(dev_id, address, local_key), please create a bug report at https://github.com/make-all/tuya-local/issues

which is discussed in #407, so I seem to be going in circles,though I get a simple switch that works, even regardless of the above error.

**Comment by convicte** [comment]
Correct me if I am wrong, but the log error entire you seek is mostly generated when the device is not recognized, but in my case it gets misclassified.
```
I tried adding it as a simple switch, as a test, and only get the #407 style error:
Logger: homeassistant.util.async_
Source: util/async_.py:141
First occurred: February 29, 2024 at 23:52:06 (9 occurrences)
Last logged: 08:08:10

Detected blocking call to sleep inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/device.py, line 77: self._api = tinytuya.Device(dev_id, address, local_key), please create a bug report at https://github.com/make-all/tuya-local/issues"
```
With logging enabled and after switching the simple switch added (which works BTW) I get a bit more in the log created, but nothing major:
```
2024-03-01 08:10:50.184 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch received {"1": false, "full_poll": true}
2024-03-01 08:11:09.766 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch new pending updates: {"1": {"value": false, "updated_at": 1709277069.766448, "sent": false}}
2024-03-01 08:11:09.767 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch sending dps update: {"1": false}
2024-03-01 08:11:09.885 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch received {"1": false, "full_poll": true}
2024-03-01 08:11:09.999 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch received {"1": false, "full_poll": false}
```
Could you please advise what combination of actions exactly you'd envisage to produce the logs that would be helpful?
Conversely, I can post in https://github.com/make-all/tuya-local/discussions and ask the question there.
I am drawing a blank...

**Comment by make-all** [comment]
Based on the logs provided, this device is only presenting as a simple switch locally:
`2024-03-01 08:11:09.885 DEBUG (MainThread) [custom_components.tuya_local.device] Simple switch received {"1": false, "full_poll": true}`
