### ISSUE TITLE
Request support for tripple wall switch

### ISSUE THREAD

**Issue by jrhessels** [make-all/tuya-local#1705]
Device mapping device is not connecting.  cannot find tripple switch in device. and custom create looks not to work.

"mapping": {
            "1": {
                "code": "switch_1",
                "type": "Boolean",
                "values": {}
            },
            "2": {
                "code": "switch_2",
                "type": "Boolean",
                "values": {}
            },
            "3": {
                "code": "switch_3",
                "type": "Boolean",
                "values": {}
            },
            "7": {
                "code": "countdown_1",
                "type": "Integer",
                "values": {
                    "unit": "s",
                    "min": 0,
                    "max": 86400,
                    "scale": 0,
                    "step": 1
                }
            },
            "8": {
                "code": "countdown_2",
                "type": "Integer",
                "values": {
                    "unit": "s",
                    "min": 0,
                    "max": 86400,
                    "scale": 0,
                    "step": 1
                }
            },
            "9": {
                "code": "countdown_3",
                "type": "Integer",
                "values": {
                    "unit": "s",
                    "min": 0,
                    "max": 86400,
                    "scale": 0,
                    "step": 1
                }
            },
            "14": {
                "code": "relay_status",
                "type": "Enum",
                "values": {
                    "range": [
                        "off",
                        "on",
                        "memory"
                    ]
                }
            },
            "16": {
                "code": "switch_backlight",
                "type": "Boolean",
                "values": {}
            },
            "17": {
                "code": "cycle_time",
                "type": "String",
                "values": "{\"maxlen\":255}"
            },
            "18": {
                "code": "random_time",
                "type": "String",
                "values": "{\"maxlen\":255}"
            },
            "19": {
                "code": "switch_inching",
                "type": "String",
                "values": "{\"maxlen\":255}"
            }
        },
        "version": "3.3"
    },

**Comment by make-all** [comment]
DPS given matches moes_threegang.yaml.  No log was provided to debug why the device isn't matching, so nothing more can be done.

**Comment by jrhessels** [comment]
correct is didnt saw this one, but still iam not able to connect see log below when i try to connected my devices 

Logger: homeassistant.util.async_
Source: util/async_.py:141
First occurred: 13:50:56 (1 occurrences)
Last logged: 13:50:56

Detected blocking call to sleep inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/device.py, line 77: self._api = tinytuya.Device(dev_id, address, local_key), please create a bug report at https://github.com/make-all/tuya-local/issues

****************************************************************************************
This error originated from a custom integration.

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:431
Integration: Tuya Local (documentation, issues)
First occurred: 13:50:59 (1 occurrences)
Last logged: 13:50:59

Test protocol error 901: Network Error: Unable to Connect

![2024-03-04_134324](https://github.com/make-all/tuya-local/assets/114057761/684c9e0b-81e5-4280-9b41-66f23e0d3602)
![2024-03-04_135344](https://github.com/make-all/tuya-local/assets/114057761/f8fd0ed5-bf4f-4e38-99a9-4d8785f76f4f)

**Comment by make-all** [comment]
`Detected blocking call to sleep...`  this is a sign that you did not configure an IP address for your device.  There may be something preventing the auto detection from working (for example if you have localtuya installed, it has already claimed the discovery broadcast ports so tinytuya cannot open them)

**Comment by jrhessels** [comment]
Thank you
to solve it I needed to do following:
- give the switch static ip adress
- reconnected to the app
