### ISSUE TITLE
2024.3.0 resurfacing of Migration Error with ebac DJ4000 and 2023.8.0 #984

### ISSUE THREAD

**Issue by Clam58** [make-all/tuya-local#1710]
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**

On upgrading to 2024.3.0 this [error](https://github.com/make-all/tuya-local/issues/984) resurfaced 

Log:

Error migrating entry EBAC DJ4000 dehumidifier for tuya_local
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 701, in async_migrate
result = await component.async_migrate_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tuya_local/init.py", line 374, in async_migrate_entry
await async_migrate_entries(hass, entry.entry_id, update_unique_id13_2)
File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1389, in async_migrate_entries
updates = entry_callback(entry)
^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tuya_local/init.py", line 359, in update_unique_id13_2
new_suffix is None and new_id.contains(suffix)
^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'contains'

**To Reproduce**
Steps to reproduce the behavior including the device the issue was observed with:

**Expected behavior**

**Additional context**

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

**Comment by make-all** [comment]
Already fixed under #984 and released as 2024.3.1
