### ISSUE TITLE
Incorrect values for wdyk_2p63a_energy_meter (current/power/voltage)

### ISSUE THREAD

**Issue by rbreiff** [make-all/tuya-local#1717]
The displayed values of current and power (B+C) are incorrect or missing voltage (B+C)

![Screenshot 2024-03-06 at 16-45-32 Tuinkamer – Home Assistant](https://github.com/make-all/tuya-local/assets/99100909/197b5546-c60f-459e-bbc2-88949d854e5d)

**Expected behavior**
Value of Current A, B and C in range 0 -20 A,
Value of Power A in Watt,
Value of Power B and C seem to be factor 1000x,
Value of Voltage B and C seem to be missing

**Comment by make-all** [comment]
This is a complaint, not a bug report.

Nothing can be done with this information. I need logs or diagnostics showing the exact data coming from the device.

**Comment by rbreiff** [comment]
[tuya_local-2d999e37f9b27265873f8add4c1ab0f1-WP (SPRSUN) Energiemeter-6a9445f90048bb02a17480b8c16009a3(1).json](https://github.com/make-all/tuya-local/files/14527324/tuya_local-2d999e37f9b27265873f8add4c1ab0f1-WP.SPRSUN.Energiemeter-6a9445f90048bb02a17480b8c16009a3.1.json)
Thank you for the quick reply. I've added the diagnostic log.
Is this OK?
