### ISSUE TITLE
Poolex Silverline - Unknown Preset SilentHeat

### ISSUE THREAD

**Issue by tipofthesowrd** [make-all/tuya-local#172]
My Pool heatpump was automatically discovered as a Poolex Heatpump.
In the Tuya Api it's identified as a  _"model": "Pool-Amitime"_

There is one preset_mode missing in my case which is SilentHeat.
It is recognized by Home Assistant in the developer tools if the heatpump has been manual put in this mode

Adding the additional mapping works fine:

        - dps_val: "SilentHeat"
          value: "SilentHeat"

However, I'm not sure this does not interfere with the other devices recognized as Poolex.

**Comment by make-all** [comment]
Thanks. I think since it is additional, it should be OK to add to the current config.  Possibly the Silverline also has this mode, as other pool heatpumps also have Boost and Silent variations (they all seem to be based on the same firmware with minor variations).
