### ISSUE TITLE
Request support for Spacetronik Smart CO Detector SL-DC01

### ISSUE THREAD

**Issue by karolzamosc** [make-all/tuya-local#1723]
Spacetronik Smart CO Detector SL-DC01

![spacetronic_CO](https://github.com/make-all/tuya-local/assets/61420368/3e0a17aa-9bdd-4c35-b924-0dc27473c393)

```
countdown_1 | Integer | {   "min": 0,   "scale": 0,   "unit": "s",   "max": 86400,   "step": 1 }
-- | -- | --
cur_current | Integer | {   "min": 0,   "scale": 0,   "unit": "mA",   "max": 30000,   "step": 1 }
cur_voltage | Integer | {   "min": 0,   "unit": "V",   "scale": 0,   "max": 2500,   "step": 1 }
cur_power | Integer | {   "min": 0,   "scale": 0,   "unit": "W",   "max": 50000,   "step": 1 }
switch | Boolean | "{true,false}"
```

`{
  "result": {
    "model": "{\"modelId\":\"000004viqa\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"ro\",\"code\":\"co_state\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-jiaquan\",\"attribute\":\"1280\",\"trigger\":\"direct\"},\"name\":\"CO检测状态\",\"typeSpec\":{\"range\":[\"alarm\",\"normal\"],\"type\":\"enum\",\"typeDefaultValue\":\"alarm\"}},{\"abilityId\":8,\"accessMode\":\"rw\",\"code\":\"self_checking\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_half\",\"attribute\":\"1024\"},\"name\":\"设备自检\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":9,\"accessMode\":\"ro\",\"code\":\"checking_result\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_half\",\"attribute\":\"1024\",\"trigger\":\"direct\"},\"name\":\"设备自检结果\",\"typeSpec\":{\"range\":[\"checking\",\"check_success\",\"check_failure\",\"others\"],\"type\":\"enum\",\"typeDefaultValue\":\"checking\"}},{\"abilityId\":11,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_warming\",\"scope\":\"fault\",\"attribute\":\"1280\",\"trigger\":\"direct\"},\"name\":\"故障告警\",\"typeSpec\":{\"label\":[\"fault\"],\"maxlen\":1,\"type\":\"bitmap\",\"typeDefaultValue\":0}}]}]}"
  },
  "success": true,
  "t": 1709931295189,
  "tid": "1dd1f7cadd8e11ee8ffde20134d788d1"
}`

**Comment by make-all** [comment]
Without a log message there is no guarantee this device will work
