### ISSUE TITLE
New Device: APOSEN A550 Vacuum

### ISSUE THREAD

**Issue by 17hoehbr** [make-all/tuya-local#173]
Hello, just picked up this device from a thrift store and would love to have it integrated into my home assistant setup via a local api. I'm not too familiar with this project or robot vacuums in general so I'm not sure how difficult it would be to add support, but I'm happy to provide any device information needed.

**Comment by make-all** [comment]
In theory if it is tuya based it can be supported.  First you'll need the device id and local key (this information should be kept private) to do any local control of the device.  If you try to then configure the device in this integration with this information, and the device is not supported, there will be a warning message in the log with a snapshot of the current device status, which is a big part of what is needed to add support.  But better information can be obtained from the developer portal at iot.tuya.com, if you sign up for an account there (which you need to for the official tuya cloud integration, and also some of the methods of obtaining the local key), then under Cloud there is an API explorer.  It has recently changed, but one of the last categories is called "Device Control" (it used to be Smart Home Management), and the last function under there "Get Device Specification Attribute" gives more detailed information on most of the functions available.  Probably some dps you see reported in the log message will be missing from there so both sets of information are needed, but we can figure those out later, or just leave them as unknown attributes so they are available for observation so someone can figure out their meaning in future.

**Comment by 17hoehbr** [comment]
Thanks for the response. I've already gone through the setup guide and acquired the local api but home assistant just detects it as a simple switch. Navigating to the device specification attribute gave me the following information:
```
{
  "result": {
    "category": "sd",
    "functions": [
      {
        "code": "power",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "power_go",
        "dp_id": 2,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "dp_id": 3,
        "type": "Enum",
        "values": "{\"range\":[\"standby\",\"smart\",\"wall_follow\",\"spiral\",\"chargego\",\"random\"]}"
      },
      {
        "code": "direction_control",
        "dp_id": 4,
        "type": "Enum",
        "values": "{\"range\":[\"backward\",\"turn_left\",\"turn_right\",\"stop\"]}"
      },
      {
        "code": "seek",
        "dp_id": 13,
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "power",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "power_go",
        "dp_id": 2,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "dp_id": 3,
        "type": "Enum",
        "values": "{\"range\":[\"standby\",\"smart\",\"wall_follow\",\"spiral\",\"chargego\",\"random\"]}"
      },
      {
        "code": "direction_control",
        "dp_id": 4,
        "type": "Enum",
        "values": "{\"range\":[\"backward\",\"turn_left\",\"turn_right\",\"stop\"]}"
      },
      {
        "code": "electricity_left",
        "dp_id": 6,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "seek",
        "dp_id": 13,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "clean_record",
        "dp_id": 15,
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "clean_area",
        "dp_id": 16,
        "type": "Integer",
        "values": "{\"unit\":\"㎡\",\"min\":1,\"max\":9999,\"scale\":0,\"step\":1}"
      },
      {
        "code": "clean_time",
        "dp_id": 17,
        "type": "Integer",
        "values": "{\"unit\":\"分\",\"min\":0,\"max\":9999,\"scale\":0,\"step\":1}"
      },
      {
        "code": "fault",
        "dp_id": 18,
        "type": "Bitmap",
        "values": "{\"label\":[\"edge_sweep\",\"middle_sweep\",\"left_wheel\",\"right_wheel\",\"garbage_box\",\"land_check\",\"collision\"]}"
      }
    ]
  },
  "success": true,
  "t": 1654394668611,
  "tid": "d4df3f19e47311ecb42622d60ed3c2d7"
}
```

And here is the error message that shows up in the logs when I try adding the vacuum in home assistant:
```
2022-06-05 02:07:10 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches simple_switch with quality of 7%. DPS: {'1': True, '2': True, '3': 'smart', '4': 'foward', '5': '1', '6': 86, '13': False,>
2022-06-05 02:07:10 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/
```

**Comment by make-all** [comment]
Can you check that log message again?  There seems to be a continuation arrow at the end that is indicating there is more, maybe this is a new feature in 2022.6, but there should be some way to expand that to see the rest, or maybe you need to look in the full log.

**Comment by 17hoehbr** [comment]
Ah I was reading the log through an ssh session, I think the terminal probably cut it off. Here's the full message:

```
2022-06-05 02:07:10 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches simple_switch with quality of 7%. DPS: {'1': True, '2': True, '3': 'smart', '4': 'foward', '5': '1', '6': 86, '13': False, '16': 4, '17': 10, '18': 0, '101': 'nar', '102': 31, '103': 175, '104': 0, 'updated_at': 1654394830.0133498}
2022-06-05 02:07:10 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/
```

**Comment by make-all** [comment]
Since this is almost identical to Lefant M213, I have removed some of the extra unknown attributes from that config to make it compatible.

**Comment by 17hoehbr** [comment]
It does seem to let me add the device to home assistant now, but I'm not really sure what to do with it from here. It shows up as the entity "automation.vacuum", and attempting to add it to the dashboard only shows a simple on / off switch, which doesn't seem to do anything. Clicking the switch does not turn on the vacuum nor does it write anything to the logs.

![image](https://user-images.githubusercontent.com/1351017/175841857-601108e1-93ec-4c9d-bf04-803f98f2f03d.png)

**Comment by 17hoehbr** [comment]
My bad, I accidentally selected the entity for my vacuum automation task instead of the vacuum itself. Selecting the Lefant device during setup then adding the correct entity to the dashboard seems to be working perfectly. It also works well with this custom vacuum card: https://github.com/denysdovhan/vacuum-card
