### ISSUE TITLE
tuya curtain wifi motor

### ISSUE THREAD

**Issue by cherokee13** [make-all/tuya-local#1735]
# Log Message

```
It is written that the device is not supported
```

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"0000026bet\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"control\",\"description\":\"【必选项】用于控制电机的开启、暂停、关闭。该DP点枚举值参数不允许修改，不允许增减。\",\"extensions\":{\"iconName\":\"icon-dp_power2\"},\"name\":\"控制\",\"typeSpec\":{\"range\":[\"open\",\"stop\",\"close\"],\"type\":\"enum\",\"typeDefaultValue\":\"open\"}},
{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"percent_control\",\"description\":\"如果窗帘电机可以监控窗帘目前的所处位置，例如窗帘现在开了一半，也就是50%，那么可以通过该DP点进行窗帘位置的自定义控制。控制使用该DP点，如果选择了该DP点，必选选择“”开启百分比状态显示“”，该DP点数值范围值参数不允许修改，不允许增减。\",\"name\":\"开启百分比控制\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%\"}},
{\"abilityId\":3,\"accessMode\":\"ro\",\"code\":\"percent_state\",\"description\":\"该DP点与“”开启百分比状态控制“”配套使用。改DP点用于显示实际窗帘所处位置。该DP点数值范围值参数不允许修改，不允许增减。\",\"name\":\"开启百分比状态\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%\"}},
{\"abilityId\":5,\"accessMode\":\"rw\",\"code\":\"control_back\",\"description\":\"用于设置电机转向，顺时针，或者逆时针，forward代表顺时针，back代表逆时针\",\"name\":\"电机反向\",\"typeSpec\":{\"range\":[\"forward\",\"back\"],\"type\":\"enum\",\"typeDefaultValue\":\"forward\"}},
{\"abilityId\":7,\"accessMode\":\"ro\",\"code\":\"work_state\",\"description\":\"【必选项】用于显示电机的当前工作状态。该DP点枚举值参数不允许修改，不允许增减。如需要修改在APP面板中显示的内容，可以前往第四步的拓展中心，多语言管理修改代表值，新增的枚举值所代表的的内容也是在多语言中修改代表值。\",\"name\":\"工作状态\",\"typeSpec\":{\"range\":[\"opening\",\"closing\"],\"type\":\"enum\",\"typeDefaultValue\":\"opening\"}},
{\"abilityId\":11,\"accessMode\":\"ro\",\"code\":\"situation_set\",\"description\":\"上报该DP点枚举值，以告知APP，该窗帘，100%对应的是全开，还是全关。不上报或者不选择改DP点，则默认100%为全关。\",\"name\":\"百分比含义\",\"typeSpec\":{\"range\":[\"fully_open\",\"fully_close\"],\"type\":\"enum\",\"typeDefaultValue\":\"fully_open\"}},
{\"abilityId\":12,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"【必选】设备上报故障值，该DP点枚举值可增减，但不可修改枚举值名称，例如可以删除motor_fault，可以增加其他值，未选则不展示该功能。 如需要修改在APP面板中显示的内容，可以前往第四步的拓展中心，多语言管理修改代表值，新增的枚举值所代表的的内容也是在多语言中修改代表值。\",\"name\":\"故障告警\",\"typeSpec\":{\"label\":[\"motor_fault\"],\"maxlen\":1,\"type\":\"bitmap\",\"typeDefaultValue\":0}},
{\"abilityId\":102,\"accessMode\":\"rw\",\"code\":\"Handpulled\",\"description\":\"\",\"name\":\"手拉启动\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}}]}]}"
  },
  "success": true,
  "t": 1710143201269,
  "tid": "7fb5cec5df7b11ee9a28e612834bce39"
}
```

{
  "result": [
    {
      "active_time": 1700853829,
      "bind_space_id": "50605376",
      "category": "cl",
      "create_time": 1670429602,
      "custom_name": "",
      "icon": "smart/icon/ay1541662398752zwSuU/8f65af3fa065bce2581652506da778b6.jpg",
      "id": "1114010224a16028d6bf",
      "ip": "",
      "is_online": true,
      "lat": "56.3300",
      "local_key": "",
      "lon": "43.9300",
      "model": " Wifi motor ",
      "name": "Wifi motor",
      "product_id": "oxzxmhkdvqexpwqo",
      "product_name": " Wifi motor ",
      "sub": false,
      "time_zone": "+03:00",
      "update_time": 1700853847,
      "uuid": "1114010224a16028d6bf"
    }
  ],
  "success": true,
  "t": 1710143369594,
  "tid": "e40eeec0df7b11ee92ae463057fe9a2e"
}
# Information about how the device functions

https://aliexpress.ru/item/1005005064894686.html?sku_id=12000035221212882&spm=a2g2w.productlist.search_results.8.5d12395bW0DC2t

**Comment by make-all** [comment]
I need the actual log message, not a summary of the dialog that pops up.

**Comment by cherokee13** [comment]
Device matches loonas_curtain with quality of 57%. DPS: {"updated_at": 1710161544.5357656, "1": "stop", "2": 48, "3": 100, "5": "forward", "7": "closing", "11": "fully_open", "102": true}

**Comment by cherokee13** [comment]
added, but the buttons don't work
![Uploading 2024-03-21_15-39-35.png…]()

**Comment by cherokee13** [comment]
added, but the buttons don't work

![2024-03-21_15-39-35](https://github.com/make-all/tuya-local/assets/162964691/4d5a2055-e4dc-4278-b355-348fb05240ed)

**Comment by make-all** [comment]
I suspect that dp 11 is not working as the description says, probably it is always indicating "fully_open" even if it is not fully open.

**Comment by cherokee13** [comment]
Device matches eruiklink_curtains with quality of 100%. DPS: {"updated_at": 1711036807.4212956, "1": "stop", "2": 90, "3": 90, "5": "forward", "7": "closing", "11": "fully_open", "102": true}

-----------------------------
only the left button is working now. he closed the curtains, but he can't open them (the right one doesn't work at all)
![2024-03-21_19-07-18](https://github.com/make-all/tuya-local/assets/162964691/35b74b74-3764-4819-a6a1-92168d748979)

**Comment by ops244** [comment]
everything is working now, but in the voice assistant, open and close are mixed up in places for some reason... I say open it - it shows closed and vice versa... is it possible to switch places?

**Comment by cherokee13** [comment]
everything is working now, but in the voice assistant, open and close are mixed up in places for some reason... I say open it - it shows closed and vice versa... is it possible to switch places?

**Comment by ops244** [comment]
you can also sign them as iot_curtain_3m - this is the same thing
https://github.com/make-all/tuya-local/issues/1291

**Comment by cherokee13** [comment]
Everything is ok now, thanks!

**Comment by cherokee13** [comment]
very strange, after the update to 2024.3.2 something completely different finds and does not work, what is the problem?

**Comment by make-all** [comment]
Your device is not returning consistent data.

**Comment by cherokee13** [comment]
what should I do in this case?

**Comment by cherokee13** [comment]
I still don't understand what it means to not return data? it returns some, since now another device is being searched for and why did everything work before that? what is the reason? (if I hadn't returned it, it would have written that the device is not supported)

**Comment by make-all** [comment]
You should post the logs.  I said it doesn't return **consistent** data.  Obviously it is always returning something, but it is not the same every time, or it would match the new config, as the log message above now does.

```
$ python util/best_match.py '{"1": "stop", "2": 93, "3": 100, "5": "back", "7": "closing", "11": "fully_open", "102": true}'
eruiklink_curtains matched 100%
  cover_curtain:
   control: stop
   position: 93
   current_position: 100
   unreliable_action: closing
   situation_set: fully_open
  select_direction:
    option: Anti-clockwise
  binary_sensor_problem:
    sensor: False
    fault_code: None
  binary_sensor_hand_pulled:
    sensor: True
```

**Comment by cherokee13** [comment]
I realized what the error was, my logs in the home assistant are disabled, because of this I did not receive data, it is working now
