### ISSUE TITLE
Request support for EARU WiFi MCB Smart Circuit Breaker

### ISSUE THREAD

**Issue by 79chrisone** [make-all/tuya-local#1739]
# Log Message

```
This device not supported, other EARU circuit breaker custom config not working this item.
```

# Information about DPS mappings

```
{
  "result": {
    "properties": [
      {
        "code": "switch_1",
        "custom_name": "",
        "dp_id": 1,
        "time": 1709368032475,
        "value": true
      },
      {
        "code": "countdown_1",
        "custom_name": "",
        "dp_id": 9,
        "time": 1709368032475,
        "value": 0
      },
      {
        "code": "add_ele",
        "custom_name": "",
        "dp_id": 17,
        "time": 1710229470000,
        "value": 530
      },
      {
        "code": "cur_current",
        "custom_name": "",
        "dp_id": 18,
        "time": 1710228838427,
        "value": 14187
      },
      {
        "code": "cur_power",
        "custom_name": "",
        "dp_id": 19,
        "time": 1710228838427,
        "value": 32616
      },
      {
        "code": "cur_voltage",
        "custom_name": "",
        "dp_id": 20,
        "time": 1710228838427,
        "value": 2303
      },
      {
        "code": "test_bit",
        "custom_name": "",
        "dp_id": 21,
        "time": 1709368032680,
        "value": 2
      },
      {
        "code": "voltage_coe",
        "custom_name": "",
        "dp_id": 22,
        "time": 1709368032680,
        "value": 0
      },
      {
        "code": "electric_coe",
        "custom_name": "",
        "dp_id": 23,
        "time": 1709368032680,
        "value": 0
      },
      {
        "code": "power_coe",
        "custom_name": "",
        "dp_id": 24,
        "time": 1709368032680,
        "value": 0
      },
      {
        "code": "electricity_coe",
        "custom_name": "",
        "dp_id": 25,
        "time": 1709368032680,
        "value": 0
      },
      {
        "code": "fault",
        "custom_name": "",
        "dp_id": 26,
        "time": 1709368032487,
        "value": 0
      },
      {
        "code": "relay_status",
        "custom_name": "",
        "dp_id": 38,
        "time": 1709463057929,
        "value": "memory"
      },
      {
        "code": "light_mode",
        "custom_name": "",
        "dp_id": 40,
        "time": 1709463057936,
        "value": "relay"
      },
      {
        "code": "child_lock",
        "custom_name": "",
        "dp_id": 41,
        "time": 1709368032532,
        "value": false
      },
      {
        "code": "cycle_time",
        "custom_name": "",
        "dp_id": 42,
        "time": 1709368032524,
        "value": ""
      },
      {
        "code": "temp_value",
        "custom_name": "",
        "dp_id": 47,
        "time": 1710225410786,
        "value": 22
      },
      {
        "code": "alarm_set_1",
        "custom_name": "",
        "dp_id": 48,
        "time": 1709985094345,
        "value": "BQEAZAcAAAA="
      },
      {
        "code": "alarm_set_2",
        "custom_name": "",
        "dp_id": 49,
        "time": 1709985094405,
        "value": "AQEAKAMBAQkEAQBa"
      }
    ]
  },
  "success": true,
  "t": 1710229509667,
  "tid": "738f6c92e04411ee9a28e612834bce39"
}


```

# Product ID

{
  "result": [
    {
      "active_time": 1708791912,
      "bind_space_id": "74940800",
      "category": "dlq",
      "create_time": 1708791912,
      "custom_name": "L1",
      "icon": "smart/icon/ay1547266640143rRUIA/bd9693fe6e7941f59845f98648b0a1a0.png",
      "id": "bf6216e329ffa8257cicgt",
      "ip": "x.x.x.x",
      "is_online": true,
      "lat": "xx.xx",
      "local_key": "",
      "lon": "xx.xx",
      "model": "",
      "name": "WiFi-计量DPN断路器 3",
      "product_id": "azpywu5zfg5wyzpn",
      "product_name": "WiFi-计量DPN断路器",
     "status": [
          {
            "code": "switch",
            "value": true
          },
          {
            "code": "countdown_1",
            "value": 0
          },
          {
            "code": "add_ele",
            "value": 100
          },
          {
            "code": "cur_current",
            "value": 14166
          },
          {
            "code": "cur_power",
            "value": 32684
          },
          {
            "code": "cur_voltage",
            "value": 2311
          },
          {
            "code": "test_bit",
            "value": 2
          },
          {
            "code": "voltage_coe",
            "value": 0
          },
          {
            "code": "electric_coe",
            "value": 0
          },
          {
            "code": "power_coe",
            "value": 0
          },
          {
            "code": "electricity_coe",
            "value": 0
          },
          {
            "code": "fault",
            "value": 0
          },
          {
            "code": "relay_status",
            "value": "last"
          },
          {
            "code": "light_mode",
            "value": "relay"
          },
          {
            "code": "child_lock",
            "value": false
          },
          {
            "code": "cycle_time",
            "value": ""
          },
          {
            "code": "temp_value",
            "value": 21
          },
          {
            "code": "alarm_set_1",
            "value": "BQEAZAcAAAA="
          },
          {
            "code": "alarm_set_2",
            "value": "AQEAKAMBAQkEAQBa"
          }
      "sub": false,
      "time_zone": "+01:00",
      "update_time": 1708791925,
      "uuid": "xxxxxxx"
    }
  ],
  "success": true,
  "t": xxxx,
  "tid": "xxxxx"
}

# Information about how the device functions

WiFi MCB Smart Circuit Breaker Over Current Under Voltage Protection Power Metering 1-63A Wireless Remote Control Switch
Features:
-Energy monitor
-Power limit
-Current limit
-Voltage protection
-Temperature protection
-Timer Switch
https://www.aliexpress.com/i/3256805275626901.html?gatewayAdapt=4itemAdapt

**Comment by 79chrisone** [comment]
Hi All!

My first yaml file is here:

` 
name: Circuit breaker
products:
  - id: azpywu5zfg5wyzpn
    name: EARU SW MCB
primary_entity:
  entity: switch
  icon: "mdi:fuse"
  name: Fuse switch
  dps:
    - id: 1
      name: switch
      type: boolean
secondary_entities:
  - entity: switch
    icon: "mdi:account-lock"
    name: Child lock
    dps:
      - id: 41
        name: switch
        type: boolean
  - entity: sensor
    category: diagnostic
    class: voltage
    dps:
      - id: 20
        name: sensor
        type: integer
        unit: V
        class: measurement
        force: true
        mapping:
          - scale: 10
  - entity: sensor
    category: diagnostic
    class: current
    dps:
      - id: 18
        name: sensor
        type: integer
        unit: A
        class: measurement
        force: true
        mapping:
          - scale: 1000
  - entity: sensor
    category: diagnostic
    class: power
    dps:
      - id: 19
        name: sensor
        type: integer
        unit: kW
        class: measurement
        force: true
        mapping:
          - scale: 10
` 

It works just like the original tuya :)
How can I integrate other functions of the device? Eg: current limit, voltage minimum, maximum
I don't see these in the original tuya integration either.
Any ideas?

Original tuya
![official](https://github.com/make-all/tuya-local/assets/104096180/00dcc460-1770-47eb-8b24-100be97f56b0)

tuya-local
![custom](https://github.com/make-all/tuya-local/assets/104096180/6e7ea5e1-5a59-4f5d-be29-d086b2a3bad4)

**Comment by erelke** [comment]
@79chrisone Szia! Ugyanilyen cuccom van, gond nélkül működik ezzel a yaml-el: https://github.com/make-all/tuya-local/blob/main/custom_components/tuya_local/devices/earu_smart_wifi_circuit_breaker_with_energy_monitor.yaml

Ezt én írtam, de régebb, így elsőre nem látom miért ne menne a tied ezzel? Talán neked zigbee-s van, mert a linkelt aliexpress-es oldalon az van.

**Comment by 79chrisone** [comment]
> @79chrisone Szia! Ugyanilyen cuccom van, gond nélkül működik ezzel a yaml-el: https://github.com/make-all/tuya-local/blob/main/custom_components/tuya_local/devices/earu_smart_wifi_circuit_breaker_with_energy_monitor.yaml
> 
> Ezt én írtam, de régebb, így elsőre nem látom miért ne menne a tied ezzel? Talán neked zigbee-s van, mert a linkelt aliexpress-es oldalon az van.

Szia nem zigbee-s, csak a link sikerült rosszul. Most megpróbáltam felvenni egy másik ugyanilyen eszközt, és a választható eszköz típusok között meg sem jelenik a tiéd. Amit látok különbséget így hirtelen az az id. 
- id: ine4hhapkgxonij1. <-- tiéd
- id:  azpywu5zfg5wyzpn <-- enyém
Kreálok egy új fájlt az én id-mmel és a te tartalmaddal. Meglátjuk.
Köszönöm.
