### ISSUE TITLE
Fix support for Poolex Silverline fi heatpump

### ISSUE THREAD

**Issue by MadDoct** [make-all/tuya-local#174]
It appears as simple switch... Same as #139 (Fairland Inver-X heatpump)
Doesn't seem to be rocognized as the correct heat pump

logs:
"Device matches simple_switch with quality of 33%. DPS: {'1': False, '3': 24, '13': 0, 'updated_at': 1654527654.1303046}"

api data:

{
   "result":{
      "category":"qn",
      "functions":[
         {
            "code":"switch",
            "dp_id":1,
            "type":"Boolean",
            "values":"{}"
         },
         {
            "code":"temp_set",
            "dp_id":2,
            "type":"Integer",
            "values":"{\"unit\":\"°C\",\"min\":0,\"max\":40,\"scale\":0,\"step\":1}"
         }
      ],
      "status":[
         {
            "code":"switch",
            "dp_id":1,
            "type":"Boolean",
            "values":"{}"
         },
         {
            "code":"temp_set",
            "dp_id":2,
            "type":"Integer",
            "values":"{\"unit\":\"°C\",\"min\":0,\"max\":40,\"scale\":0,\"step\":1}"
         },
         {
            "code":"temp_current",
            "dp_id":3,
            "type":"Integer",
            "values":"{\"unit\":\"°C\",\"min\":-20,\"max\":50,\"scale\":0,\"step\":1}"
         }
      ]
   },
   "success":true,
   "t":1654531302809,
   "tid":"f5344a60e5b111ec87322aa367714e21"
}

**Comment by make-all** [comment]
Try adding it when it is turned on.  It seems to not be returning all its data.  According to the config previously made for this model, there should be 1: power, 2: set temperature, 3: current temperature, 4: mode, 13: fault code.  But it seems yours is not reporting set temperature and mode when it is off.
