### ISSUE TITLE
Tuyalocal 2024.3.1 breaking HA Yellow

### ISSUE THREAD

**Issue by adamzeis** [make-all/tuya-local#1741]
### Discussed in https://github.com/make-all/tuya-local/discussions/1732

<div type='discussions-op-text'>

<sup>Originally posted by **adamzeis** March 10, 2024</sup>
Not sure where else to ask, but I recently updated to 2024.3.1 and it seems to be breaking my installation. Everything is running fine, I've restarted multiple times to be sure, but once I update to 2024.3.1 then I'm not able to full access HASS. I can get to a main dashboard, but everything is extremely slow to respond. I can't get far enough in to initiate a restore, however, and I've had to reset my HA Yellow and do a full restore from scratch. I'm not sure how to access any logs that would tell me any underlying issues, but curious if anyone has experienced anything similar or can point me in the right direction for diagnosing. Much appreciated. </div>

**Comment by make-all** [comment]
This doesn't really meet the criteria for a bug report, as there is no solid information linking the problems to this integration, and no other users having the same issue.  I think for now it is best left as a discussion in #1732 until there is something actionable found.
