### ISSUE TITLE
Australian Orion Grid Connect Smart Pan And Tilt Security Camera Indoor

### ISSUE THREAD

**Issue by megarch2021** [make-all/tuya-local#1743]
@make-all
I have already created yaml file for these two devices. But i do not know how to get around the pull request.

  - id: uhvuchdkaimx0hfu
    name: Orion SC009HA1
  - id: 2g8r2qybiaxbl9xx
    name: Orion SC009HA2

Please review and add to your devices list.

Issues:
1. camera(actual physical camera)  resets to default settings when home assistant is restarted.
2. camera(actual physical camera)  resets to default settings when first connected to local-tuya.
3. In home assistant settings from camera(actual physical camera) is not transferred to tuya-local device settings. Needs to be adjusted after every restart
4. Led indicator cannot stay on. If turned on from local-tuya, turns off after 15 seconds 
[orion_camera_megas.zip](https://github.com/make-all/tuya-local/files/14579928/orion_camera_megas.zip)

**Comment by megarch2021** [comment]
I have updated the yaml file with some notes & removed defaults/persist/force.
[orion_camera_megas.zip](https://github.com/make-all/tuya-local/files/14580286/orion_camera_megas.zip)

**Comment by make-all** [comment]
Your later attachment is detected as a virus. Please post inline next time, and preferably provide the requested info for a new device so I have something to review against.

**Comment by make-all** [comment]
Config is not usable as-is, and no info was supplied for debugging, so this has been removed to fix the CI issues.
