### ISSUE TITLE
New Device: Lefant M210 Robot Vacuum Cleaner

### ISSUE THREAD

**Issue by chrisrowley14** [make-all/tuya-local#1746]
# Log Message

Logger: custom_components.localtuya.cloud_api
Source: custom_components/localtuya/cloud_api.py:300
integration: LocalTuya (documentation, issues)
First occurred: March 12, 2024 at 11:51:05 PM (1 occurrences)
Last logged: March 12, 2024 at 11:51:05 PM

Cloud API connection failed: Error 1106: permission deny

Device stuck in cleaning as per https://github.com/make-all/tuya-local/issues/123#issuecomment-1030830695

# Information about DPS mappings

{
  "result": {
    "model": "{\"modelId\":\"000003h0we\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"power\",\"description\":\"【非必选】\\n\\\"可选择无开关机功能。\\n开关机控制。\\n下发： 发送控制指令给主机，主机依据指令状态进行开关机操作。\\n上报：\\n当主机使用遥控器关机或者长时间静止进入关机状态后，主机会上报一个关机数据。\\n当主机处于关机状态时，通过遥控器或者触摸主机的按键，主机会进入开机状态，主机会上报一个开机数据。\\\"\\n\",\"extensions\":{\"iconName\":\"icon-dp_power2\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"switch_go\",\"description\":\"【必选】\",\"extensions\":{\"iconName\":\"icon-dp_power\",\"attribute\":\"544\"},\"name\":\"清扫开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":3,\"accessMode\":\"rw\",\"code\":\"mode\",\"description\":\"【必选】枚举值按需选择，不需要的可删除\\nstandby：待机模式，random：随机模式，smart：自动清扫， wall_follow：沿边清扫 ，mop:拖地功能 ， spiral:定点清扫，left_spiral:左螺旋，right_spiral:右螺旋，right_bow：右⼸弓字，left_bow：左⼸弓字，partial_bow：局部弓字, chargego:回充模式\\n\",\"extensions\":{\"iconName\":\"icon-dp_mode\"},\"name\":\"工作模式\",\"typeSpec\":{\"range\":[\"standby\",\"smart\",\"chargego\",\"random\",\"wall_follow\",\"spiral\"],\"type\":\"enum\",\"typeDefaultValue\":\"standby\"}},{\"abilityId\":4,\"accessMode\":\"rw\",\"code\":\"direction_control\",\"description\":\"【必选】\\n\\\"前进，后退，左转，右转，停止。\\n默认逻辑：按住方向键下发 前/后/左转/右转，手指抬起下发停止\\\"\\n\\n\",\"extensions\":{\"iconName\":\"icon-dp_wind\"},\"name\":\"方向\",\"typeSpec\":{\"range\":[\"foward\",\"backward\",\"turn_left\",\"turn_right\",\"stop\"],\"type\":\"enum\",\"typeDefaultValue\":\"foward\"}},{\"abilityId\":5,\"accessMode\":\"ro\",\"code\":\"status\",\"description\":\"状态指示\\n0：待机中\\n1：自动清扫\\n2：拖地\\n3：沿边清扫\\n4：回充中\\n5：充电\\n6：定点清扫\",\"extensions\":{\"iconName\":\"icon-dp_dust\"},\"name\":\"工作状态\",\"typeSpec\":{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\"],\"type\":\"enum\",\"typeDefaultValue\":\"0\"}},{\"abilityId\":6,\"accessMode\":\"ro\",\"code\":\"electricity_left\",\"description\":\"【必选】\",\"extensions\":{\"iconName\":\"icon-dp_up\"},\"name\":\"剩余电量\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%\"}},{\"abilityId\":13,\"accessMode\":\"rw\",\"code\":\"seek\",\"description\":\"【非必选】\\n\",\"extensions\":{\"iconName\":\"icon-dp_curve\"},\"name\":\"寻找机器\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":15,\"accessMode\":\"ro\",\"code\":\"clean_record\",\"description\":\"\\n清扫日期+ YYYYMMDDTTRR 清扫时长 + XXX 清扫面积 xxx 如： \\\"201804110511020080\\\" 代表2018年4月11日05点11分，清扫了20分钟，80平方米 （假如MCU没有RTC，时间可不上报。记录则默认显示为数据上报时间）\",\"extensions\":{\"iconName\":\"icon-dp_direction\"},\"name\":\"清扫记录\",\"typeSpec\":{\"maxlen\":255,\"type\":\"string\",\"typeDefaultValue\":\"\"}},{\"abilityId\":16,\"accessMode\":\"ro\",\"code\":\"clean_area\",\"description\":\"【非必选】默认区间为0min—9999㎡（没有小数点），如果需要显示为小数点，可以修改倍数参数，例如需要支持一位小数点，则倍数参数为1，上报的数值会经过计算，保留一位小数，例如上报589，经过换算后为58.9㎡。\",\"extensions\":{\"iconName\":\"icon-dp_voice\",\"attribute\":\"64\"},\"name\":\"清扫面积\",\"typeSpec\":{\"max\":9999,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"㎡\"}},{\"abilityId\":17,\"accessMode\":\"ro\",\"code\":\"clean_time\",\"description\":\"【非必选】 MCU上报本次清扫时间，实时更新\",\"extensions\":{\"iconName\":\"icon-dp_warming\",\"attribute\":\"64\"},\"name\":\"清扫时间\",\"typeSpec\":{\"max\":9999,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"min\"}},{\"abilityId\":18,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"\\n\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"scope\":\"fault\"},\"name\":\"故障告警\",\"typeSpec\":{\"label\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\"],\"maxlen\":23,\"type\":\"bitmap\",\"typeDefaultValue\":0}},{\"abilityId\":19,\"accessMode\":\"ro\",\"code\":\"map_config\",\"description\":\"【有地图则必选】如果扫地机有地图功能，需要选择此功能点，用于配置地图参数，具体格式如下： 共3个字节,第一个字节为原点（0,0）位置，二三字节为地图最大的长宽 0x00 左上角 0x01 左下角 例：0x0000ff 左上角，最大长宽值为255\",\"extensions\":{\"iconName\":\"icon-dp_time\",\"attribute\":\"96\"},\"name\":\"地图参数\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"water_sction\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-jiare1\"},\"name\":\"风量\\\\水量显示\",\"typeSpec\":{\"range\":[\"low\",\"nar\",\"high\"],\"type\":\"enum\",\"typeDefaultValue\":\"low\"}},{\"abilityId\":102,\"accessMode\":\"ro\",\"code\":\"temp_unseen\",\"description\":\"\",\"name\":\"机箱温度\",\"typeSpec\":{\"max\":30000,\"min\":-30000,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-30000,\"unit\":\"℃\"}},{\"abilityId\":103,\"accessMode\":\"ro\",\"code\":\"Yaw_unseen\",\"description\":\"\",\"name\":\"航向角\",\"typeSpec\":{\"max\":30000,\"min\":-30000,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-30000,\"unit\":\"\"}},{\"abilityId\":104,\"accessMode\":\"rw\",\"code\":\"IIC_ERROR_unseen\",\"description\":\"\",\"name\":\"IIC_ERROR_COUNT\",\"typeSpec\":{\"max\":30000,\"min\":-30000,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-30000,\"unit\":\"\"}},{\"abilityId\":105,\"accessMode\":\"ro\",\"code\":\"WheelState_unseen\",\"description\":\"\",\"name\":\"轮子状态\",\"typeSpec\":{\"maxlen\":255,\"type\":\"string\",\"typeDefaultValue\":\"\"}},{\"abilityId\":106,\"accessMode\":\"ro\",\"code\":\"ChargeState_unseen\",\"description\":\"\",\"name\":\"充电状态\",\"typeSpec\":{\"maxlen\":255,\"type\":\"string\",\"typeDefaultValue\":\"\"}},{\"abilityId\":107,\"accessMode\":\"ro\",\"code\":\"ModeState_unseen\",\"description\":\"\",\"name\":\"模式状态\",\"typeSpec\":{\"maxlen\":255,\"type\":\"string\",\"typeDefaultValue\":\"\"}},{\"abilityId\":108,\"accessMode\":\"ro\",\"code\":\"RobotLog_unseen\",\"description\":\"\",\"name\":\"RobotLog\",\"typeSpec\":{\"maxlen\":255,\"type\":\"string\",\"typeDefaultValue\":\"\"}}]}]}"
  },
  "success": true,
  "t": 1710289934312,
  "tid": "236a036be0d111eeb8e44adb5c011a40"
}

# Product ID

"product_id": "av1mqcrkux82tppu"

# Information about how the device functions

https://www.manualslib.com/products/Lefant-M210-12055833.html

**Comment by make-all** [comment]
You appear to have sent this report to the wrong location. Your logs are from localtuya
