### ISSUE TITLE
Australian Brilliant Smart Wifi Outdoor PIR Sensor

### ISSUE THREAD

**Issue by megarch2021** [make-all/tuya-local#1747]
@make-all
I have already created yaml files for this. But I do not know how to get around the pull request.
products:
  - id: kwkq8icRxCrxXEAC
    name: Brilliant Smart Wifi Outdoor PIR Sensor SKU:21016/09
Please review and add to your devices list.
Minor issue: 
1. DP values are in seconds raging from  10-600 , can they be mapped to minutes?
2. Lux level ranges from 0 to 2000, can they also include additional mapping 0=dark, 1000=dusk, 2000=daylight?
[brilliant_pir_sensor_megas.zip](https://github.com/make-all/tuya-local/files/14580940/brilliant_pir_sensor_megas.zip)

**Comment by make-all** [comment]
Config does not have any non-optional dps to match devices against.

Since there is no information given other than the configs, I don't have any way to fix this.
