### ISSUE TITLE
New Device: ElectriQ Airflex15W (AirCon /w Heatpump and Dehumidifier)

### ISSUE THREAD

**Issue by RichardMawdsley** [make-all/tuya-local#175]
Hi, I have this new device which would be great to get working with this integration.  I've attempted to add it and whilst it does get discovered, I can't seem to match any of the states correctly with exception to current and set temps (although they appear in a value divided by 10).

Below is the output from its device details.  Any help in getting this supported / working would be greatly appreciated. Thanks.

{
   "result":{
      "active_time":1654613312,
      "biz_type":0,
      "category":"kt",
      "create_time":1654613312,
      "icon":"smart/product_icon/kt.png",
      "id":"042678373c6105c3d837",
      "ip":"REDACTED",
      "lat":"REDACTED",
      "local_key":"REDACTED",
      "lon":"REDACTED",
      "model":"A011A.02.010.001",
      "name":"ElectriQ Airflex15W Air Conditioner",
      "online":true,
      "owner_id":"REDACTED",
      "product_id":"4RUISW6Lmtz2u1l8",
      "product_name":"Portable air conditioner",
      "status":[
         {
            "code":"switch",
            "value":false
         },
         {
            "code":"temp_set",
            "value":21
         },
         {
            "code":"temp_current",
            "value":24
         },
         {
            "code":"humidity_set",
            "value":90
         },
         {
            "code":"mode",
            "value":"cold"
         },
         {
            "code":"windspeed",
            "value":"3"
         },
         {
            "code":"c_f",
            "value":"C"
         },
         {
            "code":"temp_set_f",
            "value":62
         },
         {
            "code":"temp_current_f",
            "value":32
         },
         {
            "code":"humidity_current",
            "value":47
         }
      ],
      "sub":false,
      "time_zone":"+00:00",
      "uid":"eu1590676008761EkqMm",
      "update_time":1654613335,
      "uuid":"042678373c6105c3d837"
   },
   "success":true,
   "t":1654681878669,
   "tid":"8b6b9416e71011ecaeb34a08c3e1e6f8"
}

**Comment by make-all** [comment]
Hi, the above is missing the local protocol details.  If you go back to iot.tuya.com, where I presume you found that, in the API Explorer under Device Control (second to last section on the left navigation bar) the last function "Get Device Specification Attribute" will return the same data as above with additional dp_id information that ties it to the local protocol.

Additionally, a copy of the log message containing the DPS list when you attempt to add the device would help to cross check in case of any format differences between local and cloud protocols.

**Comment by RichardMawdsley** [comment]
Hi @make-all, sorry for the delay.. here is the output from 'Get Device Specification Attribute':

{
  "result": {
    "category": "kt",
    "functions": [
      {
        "code": "windspeed",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\" ]}"
      },
      {
        "code": "humidity_set",
        "type": "Integer",
        "values": "{\"min\":0,\"unit\":\"%\",\"scale\":0,\"max\":100,\"type\":\"value\",\"step\":1}"
      },
      {
        "code": "temp_set",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"min\":16,\"unit\":\"℃\",\"scale\":0,\"max\":31,\"type\":\"value\",\"step\":1}"
      },
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "dp_id": 101,
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"cold\",\"hot\",\"wet\",\"wind\",\"eco\"]}"
      },
      {
        "code": "c_f",
        "dp_id": 109,
        "type": "Enum",
        "values": "{\"range\":[\"C\",\"F\"]}"
      },
      {
        "code": "temp_set_f",
        "dp_id": 110,
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":62,\"max\":90,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "humidity_current",
        "dp_id": 112,
        "type": "",
        "values": "{\"min\":0,\"scale\":0,\"unit\":\"%\",\"max\":100,\"step\":1}"
      },
      {
        "code": "windspeed",
        "dp_id": 104,
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\" ]}"
      },
      {
        "code": "humidity_set",
        "dp_id": 17,
        "type": "Integer",
        "values": "{\"min\":0,\"unit\":\"%\",\"scale\":0,\"max\":100,\"type\":\"value\",\"step\":1}"
      },
      {
        "code": "temp_current",
        "dp_id": 3,
        "type": "",
        "values": "{\"min\":-20,\"scale\":0,\"unit\":\"℃\",\"max\":100,\"step\":1}"
      },
      {
        "code": "temp_set",
        "dp_id": 2,
        "type": "",
        "values": "{\"min\":16,\"unit\":\"℃\",\"scale\":0,\"max\":31,\"type\":\"value\",\"step\":1}"
      },
      {
        "code": "switch",
        "dp_id": 1,
        "type": "",
        "values": "{}"
      },
      {
        "code": "mode",
        "dp_id": 101,
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"cold\",\"hot\",\"wet\",\"wind\",\"eco\"]}"
      },
      {
        "code": "temp_current_f",
        "dp_id": 111,
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":32,\"max\":99,\"scale\":0,\"step\":1}"
      },
      {
        "code": "c_f",
        "dp_id": 109,
        "type": "Enum",
        "values": "{\"range\":[\"C\",\"F\"]}"
      },
      {
        "code": "temp_set_f",
        "dp_id": 110,
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":62,\"max\":90,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_current_f",
        "dp_id": 111,
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":32,\"max\":99,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1657539959772,
  "tid": "087e7088010f11ed88929287a6a8350d"
}

**Comment by make-all** [comment]
Support is released in 0.18.0

**Comment by RichardMawdsley** [comment]
Superb thank you @make-all .  I'll get this tested!

**Comment by make-all** [comment]
What Warning messages do you get in the log?

**Comment by RichardMawdsley** [comment]
Hi @make-all , thanks for the recent changes.  I manually copied them into my customconfig and gave it a test..

![image](https://user-images.githubusercontent.com/26411043/179971206-2f5ca54a-7314-4407-90c8-7e878c73cc75.png)

Wahey! It's picked up.  For the most part, the control of it works fine.  The 'Operation' drop down seems to be fairly redundant as it's everything from the 'Preset' one which seems to be responsive.

![image](https://user-images.githubusercontent.com/26411043/179971967-d92fc57a-a356-445e-bac8-e55973b4d1c5.png)

Bugs I've found so far:

- Fan Mode (speed) is reversed.  High is actually low.  Low is High.
- Preset 'Fan' does not change it to this on the unit, nothing happens.  If I change it in Tuya to be 'Fan', then in HA it shows as preset 'Eco'.  In fairness this may not be a bug but differing expectations on wording.

Thanks again!

**Comment by make-all** [comment]
The reason for duplicating the presets in Operation is that the operation buttons are available in the standard Climate card in the UI (for presets you have to open the More Info... window).  Also, Off is only available in Operation, but on the other hand, Eco is not available in Operation, since those are a fixed set of operations defined by Home Assistant.

The reason for the mix up with fan and eco is that the log you posted uses numbers for the preset/operation modes, so I had to make an assumption that the numbers matched the order that they were listed in on the iot.tuya.com API docs.  Obviously that is not true, so you might need to check them all carefully.

**Comment by RichardMawdsley** [comment]
Gotcha, thanks for the explanation.

Created a new pull request where I think I've fixed the Fan Speed and removed\changed the non-existent Eco to Fan.  Also attempted to fix the 'tests'.

[](https://github.com/make-all/tuya-local/pull/205)
