### ISSUE TITLE
HCT-611 Water Timer broken functionality (it was working until I updated the FW)

### ISSUE THREAD

**Issue by spanzetta** [make-all/tuya-local#1775]
@make-all can you pls give some help?
As discussion.. nobody was answering
Thanks in advance

### Discussed in https://github.com/make-all/tuya-local/discussions/1767

<div type='discussions-op-text'>

<sup>Originally posted by **spanzetta** March 22, 2024</sup>
I have 3 of these device (HCT-611 + HCG-001-C BT Gateway) and they was working until I updated today their FW
I would never immagine that a FW update would break the functionality.. but this is what happened..
I have now 2 updated (that doesn't work anymore in HA) and 1 NOT updated which is working..

These are the info about the FW update (maybe you can realize what did they change..)

![image](https://github.com/make-all/tuya-local/assets/49818743/daea6117-3d31-40bc-a76f-a4d46cc9a8f2)
![image](https://github.com/make-all/tuya-local/assets/49818743/d16e1a8a-eba6-4996-a373-79841ce2bc6b)

I noticed in the Tuya IOT console that while the NOT updated one (the one I didn't update the FW) is listed as "Controllable" while the 2 with updated FW that doesn't work in HA are listed as "read"
Maybe this means something?

![image](https://github.com/make-all/tuya-local/assets/49818743/541fe268-c19f-4ba0-9202-b275fa12f856)

Pls let me know how to collect some logs that can be usefull for the author to underand the problem and hopefully find a solution..

Thanks in advance</div>

**Comment by spanzetta** [comment]
Many thanks

**Comment by make-all** [comment]
Sorry, but I have no inside knowledge into device manufacturers, so I cannot explain this.  For accessing Home Assistant logs, perhaps you will find it easier to search for information that you can understand in Italian.

**Comment by spanzetta** [comment]
I am not asking (and cannot pretend) that you know device .. I am asking help on how to debug the sw since you are the developer..
If I now reconfigure the 3 device .. the 2 with new FW fails... while the one with old FW works..
There must something that explain this..
I am at your full disposal to collect anything (logs) that can help you to understand why it doesn't work anymore..
Useless to point out that with SmartLife they all 3 works fine..
I hope you want to collaborate and help me..
Thanks in advance

**Comment by spanzetta** [comment]
for example.. what is error 901?

_2024-03-26 17:07:32.192 DEBUG (SyncWorker_62) [custom_components.tuya_local.device] Test refreshed device state: {"Error": "Network Error: Unable to Connect", "Err": "901", "Payload": null}
2024-03-26 17:07:32.198 WARNING (SyncWorker_62) [custom_components.tuya_local.device] Test protocol error 901: Network Error: Unable to Connect_

**Comment by spanzetta** [comment]
@make-all  ??

**Comment by spanzetta** [comment]
Solved... removed Tuya-local and installed official Tuya integration..
Everything works fine now !
Sorry for having disturbed you
