### ISSUE TITLE
Thermostat Valve (Moes ZigBee TRV)

### ISSUE THREAD

**Issue by Dexter-Lucky** [make-all/tuya-local#1780]
# Log Message

```
2024-03-28 14:19:24.106 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches None with quality of 0%. DPS: {"updated_at": 1711624761.0052001, "4": false, "9": "closed", "14": 30}
```

# Information about DPS mappings

```
"result": {
    "properties": [
      {
        "code": "mode",
        "custom_name": "",
        "dp_id": 1,
        "time": 1706277282020,
        "value": "auto",
        "range": [
          "auto",
          "manual",
          "TempHold",
          "holidays"
        ]

      },
      {
        "code": "temp_set",
        "custom_name": "",
        "dp_id": 2,
        "time": 1711221203551,
        "value": 22,
        "min": 5,
        "max": 45,
        "scale": 0,
        "step": 1
      },
      {
        "code": "temp_current",
        "custom_name": "",
        "dp_id": 3,
        "time": 1711613124213,
        "value": 200,
        "scale": 1
      },
      {
        "code": "switch_rapid",
        "custom_name": "",
        "dp_id": 4,
        "time": 1711618210775,
        "value": false
      },
      {
        "code": "countdown_rapid",
        "custom_name": "",
        "dp_id": 5,
        "time": 1704998846044,
        "value": 0,
        "unit": "min",
        "min": 0,
        "max": 720,
        "scale": 0,
        "step": 15
      },
      {
        "code": "work_state",
        "custom_name": "",
        "dp_id": 7,
        "time": 1711608038291,
        "value": "closed",
        "range": [
          "opened",
          "closed"
        ]

      },
      {
        "code": "window_check",
        "custom_name": "",
        "dp_id": 8,
        "time": 1670587785775,
        "value": false
      },
      {
        "code": "window_state",
        "custom_name": "",
        "dp_id": 9,
        "time": 1711618210666,
        "value": "closed",
        "range": [
          "opened",
          "closed"
        ]
      },
      {
        "code": "child_lock",
        "custom_name": "",
        "dp_id": 13,
        "time": 1704745150702,
        "value": true
      },
      {
        "code": "battery_percentage",
        "custom_name": "",
        "dp_id": 14,
        "time": 1711618209825,
        "value": 30,
        "unit": "%",
        "min": 0,
        "max": 100
      },
      {
        "code": "week_program11",
        "custom_name": "",
        "dp_id": 101,
        "time": 1702382485446,
        "value": "BwAuCR4sER4sFh4qCAAuCwAsER4sFx4qCAAuCwAsER4sFx4q"
      },
      {
        "code": "BoostTime",
        "custom_name": "",
        "dp_id": 103,
        "time": 1670587786375,
        "value": 200
      },
      {
        "code": "Valve_Ratio",
        "custom_name": "",
        "dp_id": 104,
        "time": 1711608038401,
        "value": 0
      },
      {
        "code": "FillTemp",
        "custom_name": "",
        "dp_id": 105,
        "time": 1704572307380,
        "value": 0
      },
      {
        "code": "Eco_Mode",
        "custom_name": "",
        "dp_id": 106,
        "time": 1703916238274,
        "value": false
      },
      {
        "code": "Eco_Temp",
        "custom_name": "",
        "dp_id": 107,
        "time": 1698002818959,
        "value": 14
      },
      {
        "code": "MaxSettemp",
        "custom_name": "",
        "dp_id": 108,
        "time": 1670587786965,
        "value": 30
      },
      {
        "code": "MinSetTEMP",
        "custom_name": "",
        "dp_id": 109,
        "time": 1670587787085,
        "value": 10
      }
    ]
  },
  "success": true,
  "t": 1711626054829,
  "tid": "094c1c23ecf811ee92ae463057fe9a2e"

[CodeTypeValues Valve.txt](https://github.com/make-all/tuya-local/files/14788868/CodeTypeValues.Valve.txt)

```

</details>

# Product ID

b6wax7g0

# Information about how the device functions

https://moeshouse.com/products/moes-zigbee-trv-by100?pr_prod_strat=e5_desc&pr_rec_id=71af205d1&pr_rec_pid=6557597368401&pr_ref_pid=6862492532817&pr_seq=uniform
https://www.zigbee2mqtt.io/devices/BRT-100-TRV.html

**Comment by make-all** [comment]
The log message is missing, seems to be replaced by a file name.

And the dps info is insufficient as it is missing the lists of allowed values or range for each item, and whether they are read-write or readonly.

**Comment by Dexter-Lucky** [comment]
I don't know why, but link in topic doesn't work. I'll leave it here.
Log Message:
[home-assistant_tuya_local_2024-03-28T11-19-29.671Z.log](https://github.com/make-all/tuya-local/files/14788946/home-assistant_tuya_local_2024-03-28T11-19-29.671Z.log)

dps:
[CodeTypeValues Valve.txt](https://github.com/make-all/tuya-local/files/14788868/CodeTypeValues.Valve.txt)

**Comment by Dexter-Lucky** [comment]
Unfortunately, it doesn't work. Does not detect this equipment. I am attaching the log:
2024-04-11 21:10:14.938 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config moes_trv_thermostat.yaml
2024-04-11 21:10:14.938 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Not match for Radiator valve, missing required DPs: [{'108': 'int'}, {'109': 'int'}]

[home-assistant_tuya_local_2024-04-11T18-10-22.999Z_11-04.log](https://github.com/make-all/tuya-local/files/14950350/home-assistant_tuya_local_2024-04-11T18-10-22.999Z_11-04.log)

**Comment by make-all** [comment]
Sorry, I forgot to mark the second copy of these two dps as optional.

**Comment by make-all** [comment]
> Rapid heating (id 4, switch_rapid). The description of this parameter is missing in the code.

It was an oversight.  I initially interpreted this as on/off switch for the thermostat, and combined it with hvac_mode, but realised it was a wrong interpretation, so moved it partially to preset_mode instead, as `boost`, but as you say, the dp was missing so it will not work.

> Filler temp (id 105, FillTemp). This parameter characterizes the adjustment in the temp_current parameter.

This was not obvious from the name, but now that I have the extra dp info, I can see the range (-9 to 9) so it can be broken out into a separate entity now.

> countdown_rapid (id 5). Didn't show this parameter at all.

It is showing in your screenshot as "Boost timer"

> temp_set (id 2) didn't change value in device

From the screenshot, your device is in eco mode, so the temperature will be affecting the eco mode temperature (id 107)

> boost timer (id 103 BoostTime) didn't change value in device

There are two dps with the same meaning (dp 4, range 0 - 12 hours; dp 103 range 100 to 900 seconds).  I am not sure how they interact, and what the expectation is for them, but the boost switch on dp 5 seems to be grouped with the dp 4 timer, so I implemented that, and left this one as a read-only attribute, as anyway I had no range info for it at the time..

> work_state (id 7) is Working status (diagnostic parameret)
This is implemented as hvac_action (heating / idle) on the climate entity.

**Comment by Dexter-Lucky** [comment]
I couldn't add device
log:

```
2024-04-21 18:12:51.054 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config moes_trv_thermostat.yaml
2024-04-21 18:12:51.054 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Not match for Radiator valve, missing required DPs: [{'1': 'str'}, {'105': 'int'}]
```

**Comment by Dexter-Lucky** [comment]
> I couldn't add device log:
> 
> ```
> 2024-04-21 18:12:51.054 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config moes_trv_thermostat.yaml
> 2024-04-21 18:12:51.054 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Not match for Radiator valve, missing required DPs: [{'1': 'str'}, {'105': 'int'}]
> ```
> 
> I added to this parametrs `optional: true` . Start testing

This problem still  actual.
