### ISSUE TITLE
None (<class 'custom_components.tuya_local.light.TuyaLocalLight'>) sets invalid supported color modes {<ColorMode.HS: 'hs'>, <ColorMode.BRIGHTNESS: 'brightness'>}

### ISSUE THREAD

**Issue by robinhood-code** [make-all/tuya-local#1788]
**Describe the bug**

None (<class 'custom_components.tuya_local.light.TuyaLocalLight'>) sets invalid supported color modes {<ColorMode.HS: 'hs'>, <ColorMode.BRIGHTNESS: 'brightness'>}, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/make-all/tuya-local/issues

**To Reproduce**

This error message only appears when HA is restarted. 

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

Logger: homeassistant.components.light
Source: components/light/__init__.py:1165
integration: Light ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 10:48:19 AM (1 occurrences)
Last logged: 10:48:19 AM

None (<class 'custom_components.tuya_local.light.TuyaLocalLight'>) sets invalid supported color modes {<ColorMode.HS: 'hs'>, <ColorMode.BRIGHTNESS: 'brightness'>}, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/make-all/tuya-local/issues

**Comment by make-all** [comment]
You did not include any details about what device this report is about, but from a quick scan, it seems it must be "hdmi_sync_light", as that is the only one that incorrectly uses brightness mode together with other modes.

**Comment by robinhood-code** [comment]
My apology but that was all the info I could gather as there was no other info in the log that told me which device it was related to, but glad that you found the specific device that caused the issue. 

I made your change to my local copy and I confirm the warning message is now gone. Thanks for the quick action on this.
