### ISSUE TITLE
Optional DPS

### ISSUE THREAD

**Issue by myhomeiot** [make-all/tuya-local#179]
When I add support for this device #178 I found that some DPS available only in some conditions, for example in my case the DPS 31, 40 and 41 available only if external sensor connected to channel 1, if it's connected into channel 2 then this DPS's is unavailable but DPS 32, 42, 43 is available, see commented lines in PR.
Because of this, the only way to add this device it's manually edit yaml file and comment/uncomment required lines.

Is it possible to mark some DPS's as optional in the yaml file so it's will pass detection and allow user to add device?

Another problem which I have, it's DPS 22 (I don't add it to the PR), this DPS show if device has a problem, but it's not available if no problems. Tuya definition for this DPS:
```
{
  "code": "fault_type",
  "dp_id": 22,
  "type": "Enum",
  "values": "{\"range\":[\"normal\",\"ch1_offline\",\"ch2_offline\",\"ch3_offline\",\"offline\"]}"
}
```

Example if problem exists: DPS: `{'1': 260, '2': 59, '3': 'high', '9': 'c', '10': 'm_s', '11': 'hpa', '12': 'mm', '13': 'lux', '22': 'ch1_offline', '30': 'high', '31': 'high', '38': 256, '39': 61, '40': 263, '41': 0, '54': 10043, '55': 0, '56': 0, '57': 0, '58': 'north_north_west', '60': 0, '61': 0, '62': 0, '63': 35, '64': 175, '65': 256, '66': 264, '67': 256, '68': 'comfortable', '101': 342, 'updated_at': 1654963344.081381}`

If no: `{'1': 266, '2': 60, '3': 'high', '9': 'c', '10': 'm_s', '11': 'hpa', '12': 'mm', '13': 'lux', '30': 'high', '31': 'high', '38': 262, '39': 63, '40': 271, '41': 0, '54': 10025, '55': 0, '56': 0, '57': 0, '58': 'north', '60': 0, '61': 0, '62': 0, '63': 0, '64': 186, '65': 272, '66': 272, '67': 262, '68': 'comfortable', '101': 6, 'updated_at': 1654888712.565212}`

Extra problem, it's a enum, which somehow need to be converted into binary sensor class: problem.

**Comment by make-all** [comment]
Support has been added for marking dps as optional in 0.18.0

**Comment by myhomeiot** [comment]
Looks good. I tested 0.18.0 version and can confirm that it's works. Will wait until #176 and will try migrate all my Tuya devices from [localtuya](https://github.com/rospogrigio/localtuya) where in v4 the yaml configuration was completely removed :-(.

Thanks for your work!
