### ISSUE TITLE
Add Creative Celling Fan "Wind Cup" with light (similar to added device "Chanfok Smart Ceiling fan")

### ISSUE THREAD

**Issue by fboulange** [make-all/tuya-local#1791]
Hello,

We've got a CREATIVE wood celling fan with dimming ligth
Here are the details : 
- Trade : CREATIVE
- Model : Wind CUP
- Link : [https://www.create-store.com](https://www.create-store.com/fr/acheter-ventilateurs-de-plafond/90898-wind-cup-ventilateur-de-plafond-40w-silencieux-o132-cm.html?id_c=176934)
- Features : 

1. Different speed
2. Forward/reverse
3. Light (switch / temperature / intensity)
4. Sleeping mode timer (1h, 2h, 4h, 8h)

It is really  similar to Chanfok Smart Ceiling fan which as been added in request #546 

# Log Message

```
Please paste logs here
```

# Information about DPS mappings

**Query Device Details**

# Product ID
```
{
  "result": {
    "active_time": 1661342815,
    "bind_space_id": "12360839",
    "category": "fsd",
    "create_time": 1659983399,
    "custom_name": "Ventilo Salon",
    "icon": "smart/icon/ay1564458733639x1LBu/7e84ea311049e256d357d89d74276448.png",
    "id": "bf4c8827149af6cfd8p5z1",
    "ip": "88.174.141.234",
    "is_online": true,
    "lat": "47.2300",
    "local_key": "1d5f7164b3cf4bdf",
    "lon": "-2.1700",
    "model": "101",
    "name": "Light+Fan-new product",
    "product_id": "u5ovvhurbvynvspv",
    "product_name": "Light+Fan-new product",
    "sub": false,
    "time_zone": "+02:00",
    "update_time": 1711904589,
    "uuid": "50356d64f93158e9"
  },
  "success": true,
  "t": 1711987834840,
  "tid": "5f03f1b5f04211ee888c7e5d947927a8"
}
```

**Query Properties**
# DPs
```
{
  "result": {
    "properties": [
      {
        "code": "switch_led",
        "custom_name": "",
        "dp_id": 20,
        "time": 1711966226652,
        "value": false
      },
      {
        "code": "work_mode",
        "custom_name": "",
        "dp_id": 21,
        "time": 1711911235636,
        "value": "white"
      },
      {
        "code": "bright_value",
        "custom_name": "",
        "dp_id": 22,
        "time": 1711246095320,
        "value": 84
      },
      {
        "code": "temp_value",
        "custom_name": "",
        "dp_id": 23,
        "time": 1711911235600,
        "value": 865
      },
      {
        "code": "colour_data",
        "custom_name": "",
        "dp_id": 24,
        "time": 1661342815549,
        "value": ""
      },
      {
        "code": "scene_data",
        "custom_name": "",
        "dp_id": 25,
        "time": 1661342815549,
        "value": ""
      },
      {
        "code": "control_data",
        "custom_name": "",
        "dp_id": 28,
        "time": 1661342815549,
        "value": ""
      },
      {
        "code": "brightness_min_1",
        "custom_name": "",
        "dp_id": 58,
        "time": 1661342815549,
        "value": 10
      },
      {
        "code": "led_type_1",
        "custom_name": "",
        "dp_id": 59,
        "time": 1661342815549,
        "value": "led"
      },
      {
        "code": "fan_switch",
        "custom_name": "",
        "dp_id": 60,
        "time": 1711902990225,
        "value": false
      },
      {
        "code": "fan_speed",
        "custom_name": "",
        "dp_id": 62,
        "time": 1711902626614,
        "value": 1
      },
      {
        "code": "fan_direction",
        "custom_name": "",
        "dp_id": 63,
        "time": 1711157838777,
        "value": "reverse"
      },
      {
        "code": "fan_countdown_left",
        "custom_name": "",
        "dp_id": 64,
        "time": 1711157838807,
        "value": 0
      }
    ]
  },
  "success": true,
  "t": 1711984617120,
  "tid": "e11b6a0ef03a11ee888c7e5d947927a8"
}
```

# Information about how the device functions

**Comment by make-all** [comment]
There is insufficient information here to create a config.

**Comment by andreas-soroko** [comment]
@make-all Just stumbled across this issue - I have the same fan - which information do you need? 
I can select/choose multiple configurations - or so it seems - but I can't configure "fan_beep" in any of them (disabled)

## home-assistant log: 
> Include the previous log messages with any new device request to https://github.com/make-all/tuya-local/issues/
>
> - Device matches create_fan_lightdimmable with quality of 101%. LOCAL DPS: {"updated_at": 1785616118.081446, "20": false, "21": "white", "23": 1000, "60": false, "62": 1, "63": "forward", "64": 0}
> - Device matches create_fan_lightdimmable with quality of 101%. LOCAL DPS: {"updated_at": 1785616243.061339, "20": false, "21": "white", "23": 1000, "60": false, "62": 1, "63": "forward", "64": 0}
> - Device matches create_fan_light with quality of 100%. LOCAL DPS: {"updated_at": 1785616323.9918284, "20": false, "21": "white", "23": 1000, "60": false, "62": 1, "63": "forward", "64": 0}
> -  Device matches create_fan_lightdimmable with quality of 101%. LOCAL DPS: {"updated_at": 1785617022.2760415, "20": false, "21": "white", "23": 1000, "60": false, "62": 1, "63": "reverse", "64": 0}
>
> - Partial cloud device spec: [{"id": 20, "name": "switch_led", "type": "Boolean", "format": "{}", "enumMap": {}}, {"id": 21, "name": "work_mode", "type": "Enum", "format": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}", "enumMap": {}}, {"id": 23, "name": "temp_value", "type": "Integer", "format": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}", "enumMap": {}}, {"id": 25, "name": "scene_data", "type": "String", "format": "{\"maxlen\":255}", "enumMap": {}}, {"id": 60, "name": "fan_switch", "type": "Boolean", "format": "{}", "enumMap": {}}, {"id": 62, "name": "fan_speed", "type": "Integer", "format": "{\"unit\":\"\",\"min\":1,\"max\":6,\"scale\":0,\"step\":1}", "enumMap": {}}, {"id": 63, "name": "fan_direction", "type": "Enum", "format": "{\"range\":[\"forward\",\"reverse\"]}", "enumMap": {}}, {"id": 64, "name": "fan_countdown_left", "type": "Integer", "format": "{\"unit\":\"min\",\"min\":0,\"max\":540,\"scale\":0,\"step\":1}", "enumMap": {}}, {"id": 66, "name": "fan_beep", "type": "Boolean", "format": "{}", "enumMap": {}}]
>
> Adding Ceiling Fan device with product id p8z27dfdwc4riyp9

## Query Things Data Model
```
{
  "result": {
    "model": "{\"modelId\":\"f08l5s\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":20,\"accessMode\":\"rw\",\"code\":\"switch_led\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power\",\"attribute\":\"1667\"},\"name\":\"灯开关\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":21,\"accessMode\":\"rw\",\"code\":\"work_mode\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"attribute\":\"1664\"},\"name\":\"灯模式\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}},{\"abilityId\":23,\"accessMode\":\"rw\",\"code\":\"temp_value\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_half\",\"attribute\":\"1664\"},\"name\":\"冷暖值\",\"typeSpec\":{\"type\":\"value\",\"max\":1000,\"min\":0,\"scale\":0,\"step\":1}},{\"abilityId\":25,\"accessMode\":\"rw\",\"code\":\"scene_data\",\"description\":\"用于切换、编辑场景\",\"extensions\":{\"iconName\":\"icon-shoucang\",\"attribute\":\"1664\"},\"name\":\"场景\",\"typeSpec\":{\"type\":\"string\",\"maxlen\":255}},{\"abilityId\":60,\"accessMode\":\"rw\",\"code\":\"fan_switch\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"1664\"},\"name\":\"风扇开关\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":62,\"accessMode\":\"rw\",\"code\":\"fan_speed\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-FanSpeed\",\"attribute\":\"1664\"},\"name\":\"风速\",\"typeSpec\":{\"type\":\"value\",\"max\":6,\"min\":1,\"scale\":0,\"step\":1,\"unit\":\"\"}},{\"abilityId\":63,\"accessMode\":\"rw\",\"code\":\"fan_direction\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"attribute\":\"1664\"},\"name\":\"风向\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"forward\",\"reverse\"]}},{\"abilityId\":64,\"accessMode\":\"rw\",\"code\":\"fan_countdown_left\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time3\",\"attribute\":\"1664\"},\"name\":\"风扇倒计时\",\"typeSpec\":{\"type\":\"value\",\"max\":540,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"min\"}},{\"abilityId\":66,\"accessMode\":\"rw\",\"code\":\"fan_beep\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_voice\",\"attribute\":\"1152\"},\"name\":\"蜂鸣器\",\"typeSpec\":{\"type\":\"bool\"}}]}]}"
  },
  "success": true,
  "t": 1785616910961,
  "tid": "6c43282a8de911f1ac26fa101bc7a5bb"
}
```

**Comment by make-all** [comment]
Device matches create_fan_lightdimmable with quality of 101%. LOCAL DPS: {"updated_at": 1785616118.081446, "20": false, "21": "white", "23": 1000, "60": false, "62": 1, "63": "forward", "64": 0}

**Comment by make-all** [comment]
There is no fan beep in that dp list, only light (20 - 23) and fan (60-63), fan timer (64)
