### ISSUE TITLE
Tesla aircon false temperature value

### ISSUE THREAD

**Issue by halmaizsolt92** [make-all/tuya-local#1793]
**Describe the bug**
I have 2 Tesla Air cons, it works with Tuya/SmartLife.
First I added it to Tuya integration and it worked well.
When I added it to Tuya Local, it worked well, except for setting the temperature.
When I set it to any value, it shows it, but after some secs, it sets back to -5.6 °C.
When I switch off the aircon, temp stays the same minus value.
However, room temperature is displayed correctly every time.
I tried to disable the Tuya integration, but it didn't help.

[tuya_local-b35c1c860077bd842019dfb3aff0e16a-Háló klíma-20e91bf0966598838b2182973c5b2595.json](https://github.com/make-all/tuya-local/files/14835225/tuya_local-b35c1c860077bd842019dfb3aff0e16a-Halo.klima-20e91bf0966598838b2182973c5b2595.json)

![tuya_local](https://github.com/make-all/tuya-local/assets/160393889/e186a875-994a-4798-a64a-a1189841d826)

![tuya_local2](https://github.com/make-all/tuya-local/assets/160393889/8d8a58d1-7729-4682-988a-c74ff9d3a7d3)

**Comment by make-all** [comment]
Based on the diagnostics, you have selected the Daizuki config, which is for a Us market device.  There is an almost identical Fisher Summer config, which should match a Celsius variant.

**Comment by halmaizsolt92** [comment]
Very very thank you!

It works well now.

I just had to remove it and add again, I could select the Fisher integration.

By default, Daizuki was highlighted and for the first time I just pushed next.
