### ISSUE TITLE
Kogan 1500W Panel Heater not working

### ISSUE THREAD

**Issue by xbmcnut** [make-all/tuya-local#18]
Hi there. Thanks for making this add-on. I was excited to stumble upon your repo after recently purchasing one of these heaters.

Quick question though. I've managed to extract the UUID and localKey from the Kogan SmarterHome app (Kogan SmarterHome_v2.0.1_apkpure.com.apk) using Bluestacks and BSTweaker but these do not seem to work in your add-on. Do I need to configure the heater in the official Tuya app for this to work?

With the UUID, localKey and IP configured, the add-ons seems to kill with WiFi on the heather as I get about 4 pings then it goes offline for a bit and the cycle continues. I've removed the integration and rebooted HA and now I get a consistent ping and the heater can again be reliably controlled from the Kogan app again.

**Comment by make-all** [comment]
If it is a new purchase, it may be a newer model with different dps assignments.  Does anything appear in the Home Assistant log?
You may need to set the log level to at least INFO for the tuya-local integration in order to see useful info with something like this in your configuration.yaml:

````YAML
logger:
  default: warning
  logs:
    custom_components.tuya_local: info
````

**Comment by xbmcnut** [comment]
Thanks. So it should work with the Kogan Smart Home app? I'll enable the logging and report back after the long weekend.

**Comment by make-all** [comment]
The integration will not work with the app.  You need to use one or the other.  Tuya devices only allow one connection at a time, and can become quite unstable if you try to control them with two at the same time.
Maybe that is what you are seeing with the device going offline after a few pings.

**Comment by make-all** [comment]
I realise my last comment may be misleading.  What I mean is that any app needs to be exited for Home Assistant to be able to connect to the device.   The Device ID and Local Key should work which ever app they come from, since you are communicating locally.

For the official Tuya integration, which uses the cloud, you need to be using an app that creates accounts in the same domain as the HA Tuya is using (I think it can be configured to use either us.tuya.com or eu.tuya.com, maybe also cn.tuya.com but some manufacturers use their own domain - Goldair I think does this, but I don't think Kogan does).

If you switch between apps and re-pair your device in the process, the local key will be changed, and you'll have to extract it again.

**Comment by xbmcnut** [comment]
Thanks for the clarification. I didn't have the Kogan app open when trying to connect so immediately thought I must need to be registered with the actual Tuya app. I'll have another go with the app force closed and logging enabled and report back.

**Comment by make-all** [comment]
There is another thread on issue #20 where another user seems to have a similar problem. In their case they previously had the heater running, and have two others that still run, but one has stopped working.  The software version is different than the other two heaters, and it is starting to look like a software update has changed the protocol somehow.

**Comment by make-all** [comment]
0.8.5 adds some Warning messages when setting up a new device that does not perfectly match any known config.  Previous log messages with useful info were at INFO level or below, which is not enabled by default in latest HA releases.

This message may provide some clues on what has changed in the new firmware so we can get it working again.

**Comment by make-all** [comment]
The current "main" branch has added a new Kogan Heater with different DPS layout.  

Your heater may have also been using the newer layout, so you might want to test the "main" branch.  You can do this by clicking the menu button on the Tuya Local integration in HACS, and selecting "Reinstall", and choosing "main" as the version from the bottom of the list.

**Comment by make-all** [comment]
As another similar issue has been closed by the new config, I've released it, so no special steps to install it, just update to 0.9.1 and restart.

**Comment by xbmcnut** [comment]
Thanks! Going to test tonight.

**Comment by xbmcnut** [comment]
Working now under 0.9.1. Thank you!
