### ISSUE TITLE
Diivoo WT03 can't turn on valve

### ISSUE THREAD

**Issue by tr1ckz** [make-all/tuya-local#1802]
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**
Diivoo WT03 single water timer not able to turn on valve, but can turn off.
This when I try it from HA
![image](https://github.com/make-all/tuya-local/assets/48994713/f7c989f0-35aa-4b6b-93de-6467c0bfff6e)
And this is what it looks like when I do it from either the app or the button on the actual device
![image](https://github.com/make-all/tuya-local/assets/48994713/44488f2d-4dc7-4875-8698-4c6360eb17a4)
It matches the ble_water_valve which I guess it might use the wrong trigger for turning on.

**Expected behavior**
Turn on the valve, from the looks, it seems like it should turn it to "manual" for on and "idle" for off

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"
[config_entry-tuya_local-9fbf5e54830e1734d6eac55776e5bd98.json](https://github.com/make-all/tuya-local/files/14895389/config_entry-tuya_local-9fbf5e54830e1734d6eac55776e5bd98.json)

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

**Comment by make-all** [comment]
There is nothing this integration can do about the behaviour of devices.

Perhaps though your connection settings are incorrect and you only have one way communication (incorrect device id can do this, and there are probably more possibilities with a hub involved).

**Comment by robertotucci** [comment]
> This form is for reporting bugs. If you have encountered a bug, you should generally have some log messages or device diagnostics to show something is going wrong. If your problem is more of a question or a request for help, then [Discussions](https://github.com/make-all/tuya-local/discussions) is probably a more suitable venue.
> 
> **Describe the bug** Diivoo WT03 single water timer not able to turn on valve, but can turn off. This when I try it from HA ![image](https://private-user-images.githubusercontent.com/48994713/320243264-f7c989f0-35aa-4b6b-93de-6467c0bfff6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MTEwNzgsIm5iZiI6MTcxMzkxMDc3OCwicGF0aCI6Ii80ODk5NDcxMy8zMjAyNDMyNjQtZjdjOTg5ZjAtMzVhYS00YjZiLTkzZGUtNjQ2N2MwYmZmZjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDIyMTkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMWM5NDI4N2M0ZDk5Y2Q2ZmNjNjVjMjNhNTljNzg0ZTFjMWU2ZjIzYWVjZTk3ODdiMjZlYmQ4YmZjMTM0MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tZ9KZP3_Kt_SKDtvD9k5U6qz3Op0Emyruoul33dMfPQ) And this is what it looks like when I do it from either the app or the button on the actual device ![image](https://private-user-images.githubusercontent.com/48994713/320243283-44488f2d-4dc7-4875-8698-4c6360eb17a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MTEwNzgsIm5iZiI6MTcxMzkxMDc3OCwicGF0aCI6Ii80ODk5NDcxMy8zMjAyNDMyODMtNDQ0ODhmMmQtNGRjNy00ODc1LTg2OTgtNGM2MzYwZWIxN2E0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDIyMTkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NmFkNGVkYmM2MDA0ZTlmZDg2YTVhMjNlZWE1ZDhmODc2YzgyZWE2OTVjNWYyMzc1NTM3ZDhiZTFmODNhZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GOeCjbxwU_5L2aw7YydlCI7Ne9gTnLo0wYF-B5bLVFQ) It matches the ble_water_valve which I guess it might use the wrong trigger for turning on.
> 
> **Expected behavior** Turn on the valve, from the looks, it seems like it should turn it to "manual" for on and "idle" for off
> 
> If the bug involves a device, then please include device diagnostics from Settings / Devices & Services / Tuya Local (your device) / "1 device" [config_entry-tuya_local-9fbf5e54830e1734d6eac55776e5bd98.json](https://github.com/make-all/tuya-local/files/14895389/config_entry-tuya_local-9fbf5e54830e1734d6eac55776e5bd98.json)
> 
> Please check if there are messages from Tuya Local in the Home Assistant log (Settings / System / Logs), and include those too.
> 
> If applicable, add screenshots to help explain your problem.

Hi!
I'm try to configure the same device "WT-03" but i'm not so lucky...could you please share your settings?? DPs, etc... 
Do you have the gateway?

Thanks!

**Comment by tr1ckz** [comment]
> > This form is for reporting bugs. If you have encountered a bug, you should generally have some log messages or device diagnostics to show something is going wrong. If your problem is more of a question or a request for help, then [Discussions](https://github.com/make-all/tuya-local/discussions) is probably a more suitable venue.
> > **Describe the bug** Diivoo WT03 single water timer not able to turn on valve, but can turn off. This when I try it from HA ![image](https://private-user-images.githubusercontent.com/48994713/320243264-f7c989f0-35aa-4b6b-93de-6467c0bfff6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MTEwNzgsIm5iZiI6MTcxMzkxMDc3OCwicGF0aCI6Ii80ODk5NDcxMy8zMjAyNDMyNjQtZjdjOTg5ZjAtMzVhYS00YjZiLTkzZGUtNjQ2N2MwYmZmZjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDIyMTkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMWM5NDI4N2M0ZDk5Y2Q2ZmNjNjVjMjNhNTljNzg0ZTFjMWU2ZjIzYWVjZTk3ODdiMjZlYmQ4YmZjMTM0MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tZ9KZP3_Kt_SKDtvD9k5U6qz3Op0Emyruoul33dMfPQ) And this is what it looks like when I do it from either the app or the button on the actual device ![image](https://private-user-images.githubusercontent.com/48994713/320243283-44488f2d-4dc7-4875-8698-4c6360eb17a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MTEwNzgsIm5iZiI6MTcxMzkxMDc3OCwicGF0aCI6Ii80ODk5NDcxMy8zMjAyNDMyODMtNDQ0ODhmMmQtNGRjNy00ODc1LTg2OTgtNGM2MzYwZWIxN2E0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDIyMTkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NmFkNGVkYmM2MDA0ZTlmZDg2YTVhMjNlZWE1ZDhmODc2YzgyZWE2OTVjNWYyMzc1NTM3ZDhiZTFmODNhZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GOeCjbxwU_5L2aw7YydlCI7Ne9gTnLo0wYF-B5bLVFQ) It matches the ble_water_valve which I guess it might use the wrong trigger for turning on.
> > **Expected behavior** Turn on the valve, from the looks, it seems like it should turn it to "manual" for on and "idle" for off
> > If the bug involves a device, then please include device diagnostics from Settings / Devices & Services / Tuya Local (your device) / "1 device" [config_entry-tuya_local-9fbf5e54830e1734d6eac55776e5bd98.json](https://github.com/make-all/tuya-local/files/14895389/config_entry-tuya_local-9fbf5e54830e1734d6eac55776e5bd98.json)
> > Please check if there are messages from Tuya Local in the Home Assistant log (Settings / System / Logs), and include those too.
> > If applicable, add screenshots to help explain your problem.
> 
> Hi! I'm trying to configure the same device "WT-03" but i'm not so lucky...could you please share your settings?? DPs, etc... Do you have the gateway?
> 
> Thanks!

It will only work with the gateway, also you won't be able to turn it on, even with official tuya integration you can't.
