### ISSUE TITLE
Request support for [TEKXDD Smart BLE Door Lock]

### ISSUE THREAD

**Issue by wlfc2031** [make-all/tuya-local#1803]
# Log Message

# Information about DPS mappings

```
{
"result": {
"properties": [
{
"code": "unlock_method_create",
"custom_name": "",
"dp_id": 1,
"time": 1690178103652
},
{
"code": "unlock_method_delete",
"custom_name": "",
"dp_id": 2,
"time": 1690178103652
},
{
"code": "unlock_method_modify",
"custom_name": "",
"dp_id": 3,
"time": 1690178103652
},
{
"code": "bluetooth_unlock",
"custom_name": "",
"dp_id": 6,
"time": 1690178103652
},
{
"code": "residual_electricity",
"custom_name": "",
"dp_id": 8,
"time": 1690255732530,
"value": 88
},
{
"code": "unlock_fingerprint",
"custom_name": "",
"dp_id": 12,
"time": 1690239837000,
"value": 100
},
{
"code": "unlock_password",
"custom_name": "",
"dp_id": 13,
"time": 1690178103652,
"value": 0
},
{
"code": "unlock_dynamic",
"custom_name": "",
"dp_id": 14,
"time": 1690178103652,
"value": 0
},
{
"code": "unlock_ble",
"custom_name": "",
"dp_id": 19,
"time": 1690178103652,
"value": 0
},
{
"code": "alarm_lock",
"custom_name": "",
"dp_id": 21,
"time": 1690243840000,
"value": "wrong_finger"
},
{
"code": "beep_volume",
"custom_name": "",
"dp_id": 31,
"time": 1690255732766,
"value": "high"
},
{
"code": "lock_motor_state",
"custom_name": "",
"dp_id": 47,
"time": 1690178103652,
"value": false
},
{
"code": "temporary_password_creat",
"custom_name": "",
"dp_id": 51,
"time": 1690178103652
},
{
"code": "temporary_password_delete",
"custom_name": "",
"dp_id": 52,
"time": 1690178103652
},
{
"code": "temporary_password_modify",
"custom_name": "",
"dp_id": 53,
"time": 1690178103652
},
{
"code": "synch_method",
"custom_name": "",
"dp_id": 54,
"time": 1690178103652
},
{
"code": "unlock_temporary",
"custom_name": "",
"dp_id": 55,
"time": 1690178103652,
"value": 0
},
{
"code": "remote_no_pd_setkey",
"custom_name": "",
"dp_id": 60,
"time": 1690178103652
},
{
"code": "remote_no_dp_key",
"custom_name": "",
"dp_id": 61,
"time": 1690178103652
},
{
"code": "unlock_phone_remote",
"custom_name": "",
"dp_id": 62,
"time": 1690178103652,
"value": 0
},
{
"code": "unlock_voice_remote",
"custom_name": "",
"dp_id": 63,
"time": 1690178103652,
"value": 0
},
{
"code": "password_offline_time",
"custom_name": "",
"dp_id": 64,
"time": 1690178137232,
"value": "1690178103"
},
{
"code": "unlock_offline_clear_single",
"custom_name": "",
"dp_id": 65,
"time": 1690178103652
},
{
"code": "unlock_offline_clear",
"custom_name": "",
"dp_id": 66,
"time": 1690178103652
},
{
"code": "unlock_offline_pd",
"custom_name": "",
"dp_id": 67,
"time": 1690178103652
}
]
}
```

# Product ID

okkyfgfs

# Information about how the device functions

Smart Door BLE Lock

**Comment by make-all** [comment]
Insufficient information

**Comment by wlfc2031** [comment]
{
  "result": {
    "model": "{\"modelId\":\"000004qzsr\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"unlock_method_create\",\"description\":\"【必选】App蓝牙近距离连接门锁后，进行开门方式的创建操作，支持指纹、密码、卡等方式的创建\",\"name\":\"添加开门方式\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"unlock_method_delete\",\"description\":\"【必选】App蓝牙近距离连接门锁后，进行开门方式的删除操作，支持指纹、密码、卡等方式的删除\",\"name\":\"删除开门方式\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":3,\"accessMode\":\"rw\",\"code\":\"unlock_method_modify\",\"description\":\"【必选】App蓝牙近距离连接门锁后，进行开门方式的修改操作，支持指纹、密码、卡等方式的修改\",\"name\":\"修改开门方式\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":6,\"accessMode\":\"rw\",\"code\":\"bluetooth_unlock\",\"description\":\"【手机蓝牙解锁必选之一】\\n【支持蓝牙配件不能选择该dp，需选择dp71，与70&71互斥，2选1】\",\"extensions\":{\"attribute\":\"512\"},\"name\":\"蓝牙解锁\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":8,\"accessMode\":\"ro\",\"code\":\"residual_electricity\",\"description\":\"【可选，但必须二选一】门锁上报电量百分比。剩余电量与电量状态，必须二选一   默认值为-1时不显示电量\",\"extensions\":{\"trigger\":\"direct\"},\"name\":\"剩余电量\",\"typeSpec\":{\"type\":\"value\",\"max\":100,\"min\":-1,\"scale\":0,\"step\":1}},{\"abilityId\":12,\"accessMode\":\"ro\",\"code\":\"unlock_fingerprint\",\"description\":\"【可选】指纹在门锁上录入，录入完成后由硬件分配id，发生指纹解锁后，门锁将上报该dp点。请用记录型上报\",\"extensions\":{\"trigger\":\"direct\"},\"name\":\"指纹解锁\",\"typeSpec\":{\"type\":\"value\",\"max\":999,\"min\":0,\"scale\":0,\"step\":1}},{\"abilityId\":13,\"accessMode\":\"ro\",\"code\":\"unlock_password\",\"description\":\"【可选】普通密码在门锁上录入，录入完成后由硬件分配id，发生普通密码解锁后，门锁将上报该dp点。普通密码指在门锁硬件上创建的密码，不包含通过app创建的临时密码。请用记录型上报\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"attribute\":\"1024\",\"trigger\":\"direct\"},\"name\":\"密码解锁\",\"typeSpec\":{\"type\":\"value\",\"max\":999,\"min\":0,\"scale\":0,\"step\":1}},{\"abilityId\":14,\"accessMode\":\"ro\",\"code\":\"unlock_dynamic\",\"description\":\"【可选】普通密码在门锁上录入，录入完成后由硬件分配id，发生普通密码解锁后，门锁将上报该dp点。普通密码指在门锁硬件上创建的密码，不包含通过app创建的临时密码。请用记录型上报\",\"extensions\":{\"iconName\":\"icon-shoushimima\",\"attribute\":\"1024\",\"trigger\":\"direct\"},\"name\":\"动态密码解锁\",\"typeSpec\":{\"type\":\"value\",\"max\":999,\"min\":0,\"scale\":0,\"step\":1}},{\"abilityId\":19,\"accessMode\":\"ro\",\"code\":\"unlock_ble\",\"description\":\"【必须】请用记录型上报成功上报：成员+蓝牙开门+时间（开门记录）\",\"extensions\":{\"trigger\":\"direct\"},\"name\":\"蓝牙解锁记录\",\"typeSpec\":{\"type\":\"value\",\"max\":999,\"min\":0,\"scale\":0,\"step\":1}},{\"abilityId\":21,\"accessMode\":\"ro\",\"code\":\"alarm_lock\",\"description\":\"【必选】0=指纹试错报警、1=密码试错报警、2=卡试错报警、3=人脸试错报警、4=假锁（锁舌卡住）、5=高温报警、6=超时未关门、7=电子锁舌未弹出、8=防撬报警 、9=钥匙插入、10=低电报警、11=电量耗尽报警、12=震动报警、13=布防报警。低电暂时保留使用单独的dp点的设计，如果使用了本dp点中的低电报警值，就不要使用11dp点\",\"extensions\":{\"iconName\":\"icon-dp_warming\",\"attribute\":\"1024\",\"trigger\":\"direct\"},\"name\":\"门锁告警\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"wrong_finger\",\"wrong_password\",\"low_battery\"]}},{\"abilityId\":31,\"accessMode\":\"rw\",\"code\":\"beep_volume\",\"description\":\"【可选】从0到9，表示从静音到最大音量。app设置后，如果硬件收到，需要将原设置值返回给服务器。如设置的是5，硬件设置成功返回5，设置失败，不返回\",\"extensions\":{\"iconName\":\"icon-sound\",\"attribute\":\"1280\",\"trigger\":\"direct\"},\"name\":\"导航音量\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"mute\",\"low\",\"normal\",\"high\"]}},{\"abilityId\":47,\"accessMode\":\"ro\",\"code\":\"lock_motor_state\",\"description\":\"【设备状态】用于上报设备离合开关的状态，即锁的开关状态。\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"attribute\":\"256\"},\"name\":\"关锁状态\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":51,\"accessMode\":\"rw\",\"code\":\"temporary_password_creat\",\"description\":\"【可选】当支持通过app向硬件上添加指定生效时间的临时密码，则选择该dp（创建、删除、修改临时密码的dp需要同步选择）\",\"extensions\":{\"iconName\":\"icon-dp_add\",\"attribute\":\"1024\"},\"name\":\"添加临时密码\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":52,\"accessMode\":\"rw\",\"code\":\"temporary_password_delete\",\"description\":\"管理员有临时密码删除入口，联网连蓝牙状态下，可删除临时密码\",\"extensions\":{\"iconName\":\"icon-dp_rabbish\",\"attribute\":\"1024\"},\"name\":\"删除临时密码\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":53,\"accessMode\":\"rw\",\"code\":\"temporary_password_modify\",\"description\":\"管理员有临时密码编辑入口，联网连蓝牙状态下，可编辑修改临时密码\",\"extensions\":{\"iconName\":\"icon-setting\",\"attribute\":\"1024\"},\"name\":\"修改临时密码\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":54,\"accessMode\":\"rw\",\"code\":\"synch_method\",\"description\":\"【具备本地电子解锁条件下 必选】当智能锁上存在物理解锁方式，包括不限于指纹、密码、卡等方式，并且可以在门锁硬件上对这些解锁方式进行操作时，需要选择该dp\\n下发同步指令，全量同步门锁下的所有开门方式（本地存储数据量较大时选用）\",\"extensions\":{\"iconName\":\"icon-dp_upload\",\"attribute\":\"1536\"},\"name\":\"同步解锁方式\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":55,\"accessMode\":\"ro\",\"code\":\"unlock_temporary\",\"description\":\"临时密码解锁记录上报\",\"extensions\":{\"iconName\":\"icon-shoushimima\",\"attribute\":\"1152\",\"trigger\":\"direct\"},\"name\":\"临时密码解锁\",\"typeSpec\":{\"type\":\"value\",\"max\":999,\"min\":0,\"scale\":0,\"step\":1}},{\"abilityId\":60,\"accessMode\":\"rw\",\"code\":\"remote_no_pd_setkey\",\"description\":\"【不支持配件，支持音箱开门选该dp，与70&73互斥】\\n配置远程网络加密解锁是否开启，包含密钥（次数、时效、内容）\",\"extensions\":{\"iconName\":\"icon-setting\",\"attribute\":\"1152\"},\"name\":\"配置新免密远程解锁\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":61,\"accessMode\":\"rw\",\"code\":\"remote_no_dp_key\",\"description\":\"远程网络解锁动作触发，下发和上报\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"attribute\":\"1152\"},\"name\":\"新免密远程开门-带密钥\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":62,\"accessMode\":\"ro\",\"code\":\"unlock_phone_remote\",\"description\":\"上报远程手机解锁的开门记录\",\"extensions\":{\"iconName\":\"icon-shouji\",\"attribute\":\"1152\",\"trigger\":\"direct\"},\"name\":\"远程解锁\",\"typeSpec\":{\"type\":\"value\",\"max\":999,\"min\":0,\"scale\":0,\"step\":1}},{\"abilityId\":63,\"accessMode\":\"ro\",\"code\":\"unlock_voice_remote\",\"description\":\"上报远程语音解锁的开门记录\",\"extensions\":{\"iconName\":\"icon-dp_mic\",\"attribute\":\"1280\",\"trigger\":\"direct\"},\"name\":\"远程语音解锁\",\"typeSpec\":{\"type\":\"value\",\"max\":999,\"min\":0,\"scale\":0,\"step\":1}},{\"abilityId\":64,\"accessMode\":\"rw\",\"code\":\"password_offline_time\",\"description\":\"离线密码时间戳下发，使用离线密码功能必选\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"attribute\":\"1152\",\"trigger\":\"direct\"},\"name\":\"离线密码T0时间下发\",\"typeSpec\":{\"type\":\"string\",\"maxlen\":255}},{\"abilityId\":65,\"accessMode\":\"ro\",\"code\":\"unlock_offline_clear_single\",\"description\":\"本地使用离线密码清除某条时间段性的离线密码后上报记录\",\"extensions\":{\"iconName\":\"icon-dp_upload\",\"attribute\":\"1152\"},\"name\":\"单条离线密码清空上报\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":66,\"accessMode\":\"ro\",\"code\":\"unlock_offline_clear\",\"description\":\"本地使用离线密码清空所有时间段的离线密码后上报记录\",\"extensions\":{\"iconName\":\"icon-dp_upload\",\"attribute\":\"1152\"},\"name\":\"离线密码清空上报\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":67,\"accessMode\":\"ro\",\"code\":\"unlock_offline_pd\",\"description\":\"本地使用离线密码解锁后上报记录\",\"extensions\":{\"iconName\":\"icon-dp_upload\",\"attribute\":\"1152\"},\"name\":\"离线密码解锁上报\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}}]}]}"
  },
  "success": true,
  "t": 1712619555433,
  "tid": "35cb4e34f60111eeb8a05ae3e4ec57c6"
}

**Comment by wlfc2031** [comment]
Does this help at all?

**Comment by make-all** [comment]
This helps with the values each dps accepts, but to have any chance of making a successful config, the local logs are also required. Locks even more so than other devices in general seem to limit what information they send locally compared with what is documented in the tuya cloud.

**Comment by wlfc2031** [comment]
Please ignore - new issue created with logs

**Comment by wlfc2031** [comment]
Hopefully this helps more: [1806](https://github.com/make-all/tuya-local/issues/1806)
