### ISSUE TITLE
Added support for Kolanki EV portable charger

### ISSUE THREAD

**Issue by liouma** [make-all/tuya-local#1817]
Hello, I created the yaml file adding support to the following EV charger:

https://fr.aliexpress.com/item/1005006312088262.html?spm=a2g0o.order_list.order_list_main.127.5af75e5btMvrmt&gatewayAdapt=glo2fra

This is a first time for me so I'm very happy. It's working fine with all sensors and settings available on tuya app.
[kolanky_ev_charger.yaml.txt](https://github.com/make-all/tuya-local/files/14944612/kolanky_ev_charger.yaml.txt)

**Comment by make-all** [comment]
Not a bug. Insufficient info for a new device report.
