### ISSUE TITLE
Heater does not show 'heating' state in HA history graph

### ISSUE THREAD

**Issue by jan-gerard** [make-all/tuya-local#1819]
Typical heaters show the heating state in HA history graphs. However, I get a white surface when the heater is on:
![image](https://github.com/make-all/tuya-local/assets/7569832/fc81ced7-a1b2-4260-bae4-1405d60c659e)

To Reproduce, create a heater using tuya-local, and look at the history graph.

I expect the surface below the temperature graph to be orange when heating, and blank when the heater is switched off.
![image](https://github.com/make-all/tuya-local/assets/7569832/c85c1289-8688-48eb-ae4f-69aabbd04491)

It's concerning a new device /homeassistant/custom_components/tuya_local/devices/eurom_sani_bathroom_towel_radiator.yaml (but that doesn't matter I suppose).

**Comment by make-all** [comment]
The device absolutely matters.  Many tuya climate devices do not provide the necessary feedback for hvac_action to be reported.

**Comment by jan-gerard** [comment]
> Many tuya climate devices do not provide the necessary feedback for hvac_action to be reported.

Which hvac_action values are needed? The device reports 'heating', 'drying', 'idle', and 'off'. Which seem the appropriate values to me. They are as such visible in HA, but apparently there is more to be reported to graphically show the heater state. I notice that removing the double quotes from the "off" string in the yaml file does the trick.

**Comment by make-all** [comment]
Removing the quotes is incorrect, as that would make the value `False` instead of `off`, which is invalid as an HvacAction value.
The values reported are correct apart from that, so it must be a frontend bug that the chart is not showing the action.
