### ISSUE TITLE
Add support for Tuya  MOES WIFI plugged Temp and Humidity sensors

### ISSUE THREAD

**Issue by poolMiniDomo** [make-all/tuya-local#182]
Hello,

looking for support for Temp and Humidity sensors. I bought this device to work locally: https://www.amazon.fr/MOES-Commutation-Intelligent-temp%C3%A9rature-t%C3%A9l%C3%A9commande/dp/B09TBBT1CD/ref=sr_1_4?__mk_fr_FR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=13OM3XJQP117T&keywords=MOES+WiFi+Smart+Temperature+Sensor&qid=1655097785&sprefix=moes+wifi+smart+temperature+sensor%2Caps%2C127&sr=8-4

"category": "wkcz",
"name": "Two-way temperature and humidity switch",
"product_id": "dlsdk5zvkuuhufpy",
"product_name": "Two-way temperature and humidity switch",

I need temperature in C° (switches don't interest me), there is 2 switch on device.
I am new to HA, but I believe that this sensor is not yet supported.

thanks in advance

**Comment by poolMiniDomo** [comment]
Update: tuya local detect this device as switch. The switch is the main switch witch turn on/off sensor. There are 2 others switch control by temperature in automatic mode.

![Screenshot_20220614-173519_Smart Life](https://user-images.githubusercontent.com/45268357/173618215-b20617ef-7e9b-4dc5-8e1a-456c1fa61baa.jpg)

**Comment by poolMiniDomo** [comment]
the message that shows up in the logs when I try adding this device in home assistant:
2022-06-14 17:26:10 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches simple_switch with quality of 5%. DPS: {'1': True, '2': False, '3': True, '4': 'manual', '6': 374, '8': False, '9': 0, '11': False, '12': 0, '18': 0, '20': 0, '21': 0, '22': 0, '24': '', '101': '', '102': '', '103': 0, '104': 0, '105': 'off', '106': 'mix', 'updated_at': 1655220355.797364}
2022-06-14 17:26:10 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/

Get device specification attributes return : 
{
  "code": 2009,
  "msg": "not support this device",
  "success": false,
  "t": 1655239576276,
  "tid": "09189020ec2311ec873a2aa367714e21"
}

**Comment by make-all** [comment]
You may need to change the server at the top of the screen when running the iot.tuya.com API calls, as if the server does not match the one your device is registered to, it gives errors like this.

Or, try other APIs to see if something at least gives the range of options for that "manual" setting, and gives some idea of what other features are in there.  Is there really a humidity sensor in there, it seems unlikely that humidity is all the way down at 0%, and if it is, that makes it indistinguishable from the other 0 values for timers and others.

**Comment by poolMiniDomo** [comment]
Thanks for your reply.

My device was registred in 'Central Europe Data Center'. when running the iot.tuya.com API calls, the data center is the same (list have only this one).
I'm not find Api witch have any information :(
This device is sold with external waterproof temperature sensor or temperature/humidity indoor sensor. I bought the waterproof, that's why humidity is 0%.
How I optain the config_flow data with command (I will do reverse)?   
I deduct '6' is temperature (in C° for me)

**Comment by make-all** [comment]
1. For "etat de redemarrage", there should be three possible states.  I think it maps to dp id 105, currently "off", and the three states should be "off", "on" and something like "keep", can you find out what value dp 105 has when selecting this third state?
2. Can you confirm that the two switches are dp 2 and 3?
3. Can you confirm which dp ids correspond to the two countdown timers, and the temperature calibration?

**Comment by make-all** [comment]
The app seems to know that the humidity sensor is not attached (automatique is greyed out for the second switch, and no humidity related options appear).  I guess one of the False values is telling this information, but I don't have any good idea besides the iot.tuya.com info or comparing with a second device with that sensor for working out which dp id it is.
