### ISSUE TITLE
Request support for [device description]

### ISSUE THREAD

**Issue by OsaedYahya** [make-all/tuya-local#1820]
# Information about DPS mappings
this is from TinyTuya

{
        "name": "Outdoor light",
        "id": "---",
        "key": "----",
        "mac": "----",
        "uuid": "----",
        "sn": "----",
        "category": "qjdcz",
        "product_name": "Smart scene light switch",
        "product_id": "cfgbqdd9upyrhtez",
        "biz_type": 18,
        "model": "YWL-qj01",
        "sub": false,
        "icon": "https://images.tuyaeu.com/smart/icon/ay1478601468737nHvdo/77be392a3f9653160c76e01c2de2f52f.jpg",
        "mapping": {
            "1": {
                "code": "switch_1",
                "type": "Boolean",
                "values": {}
            },
            "9": {
                "code": "countdown_1",
                "type": "Integer",
                "values": {
                    "unit": "s",
                    "min": 0,
                    "max": 86400,
                    "scale": 0,
                    "step": 1
                }
            },
            "27": {
                "code": "switch_led",
                "type": "Boolean",
                "values": {}
            },
            "28": {
                "code": "work_mode",
                "type": "Enum",
                "values": {
                    "range": [
                        "white",
                        "colour",
                        "scene",
                        "scene_1",
                        "scene_2",
                        "scene_3",
                        "scene_4"
                    ]
                }
            },
            "31": {
                "code": "colour_data",
                "type": "String",
                "values": "{\"maxlen\":255}"
            },
            "32": {
                "code": "scene_data",
                "type": "String",
                "values": "{\"maxlen\":255}"
            },
            "33": {
                "code": "flash_scene_1",
                "type": "String",
                "values": "{\"maxlen\":255}"
            },
            "34": {
                "code": "flash_scene_2",
                "type": "String",
                "values": "{\"maxlen\":255}"
            },
            "35": {
                "code": "flash_scene_3",
                "type": "String",
                "values": "{\"maxlen\":255}"
            },
            "36": {
                "code": "flash_scene_4",
                "type": "String",
                "values": "{\"maxlen\":255}"
            },
            "37": {
                "code": "countdown_led",
                "type": "Integer",
                "values": {
                    "unit": "s",
                    "min": 0,
                    "max": 86400,
                    "scale": 0,
                    "step": 1
                }
            }
        },
        "ip": "192.168.1.31",
        "version": "3.3"
    },
 

name: Smart scene light switch
primary_entity:
  entity: light
  dps:
    - id: 1
      type: boolean
      name: switch
secondary_entities:
  - entity: light
    name: Switch Light
    dps:
        - id: 27
          type: boolean
          name: switch
        - id: 28
          type: string
          name: color_mode
          optional: true
          mapping:
            - dps_val: white
              value: white
            - dps_val: colour
              value: hs
            - dps_val: scene
              value: scene
            - dps_val: scene_1
              value: scene_1
            - dps_val: scene_2
              value: scene_2
            - dps_val: scene_3
              value: scene_3
            - dps_val: scene_4
              value: scene_4
        - id: 31
          type: string
          name: color_data
          optional: true
  - entity: number
    translation_key: timer
    category: config
    dps:
              - id: 37
                type: integer
                name: value
                unit: min
                range:
                  min: 0
                  max: 86400
                mapping:
                  - scale: 60
                    step: 60  
  - entity: number
    translation_key: timer_2
    category: config
    dps:
              - id: 9
                type: integer
                name: value
                unit: min
                range:
                  min: 0
                  max: 86400
                mapping:
                  - scale: 60
                    step: 60
  - entity: select
    translation_key: select
    category: config
    options:
      - Select
      - Concentrate
      - Energize
      - Reading
      - Relax
      - 'OFF'
    dps:
              - id: 31
                type: string
                name: value

# Product ID
cfgbqdd9upyrhtez

# Information about how the device functions
This is a switch with rgb color embedded into the switch

from my configurations I can control both the switch and the (rgb switch) where I can turn it on or off and can control the color mode, How can I control the colors as an RGB slider? knowing that the "color_data" is NOT using this format
https://developer.tuya.com/en/docs/iot/product-function-definition?id=K9s9rhj576ypf#title-7-DP24%3A%20color

00ff0400796464

![image](https://github.com/make-all/tuya-local/assets/69788216/f792e095-400f-4445-a29d-5d563e10c81d)

**Comment by make-all** [comment]
Requests for new devices cannot be accepted without local logs.
