### ISSUE TITLE
Feature Request, Smart Kettle

### ISSUE THREAD

**Issue by Krispkiwi** [make-all/tuya-local#183]
Just checking with the Kogan Glass 1.7L Smart Kettle, It's pretty reliable for me. Is it at all possible to get the temperature the kettle is at?

**Comment by make-all** [comment]
If it is being detected as a Kogan Smart Kettle, you should have the current temperature already.  My guess is that yours was detected as a simple switch?  It seems there are issues with detection of this device, as #47 has never been closed.

**Comment by make-all** [comment]
If you re-add it (while switched on), and capture the log messages, I may be able to look at changing the config to detect it while on, with whatever information it is returning (it seems to return current temperature when off, so hopefully should do when on as well).

**Comment by Krispkiwi** [comment]
Just tried this, getting the Sorry, there is no support for this device error.

**Comment by Krispkiwi** [comment]
It appears it will only connect once the kettle has stopped heating up and then only detects it as a switch

**Comment by make-all** [comment]
I need the Home Assistant log messages from when it gets the "no support for this device" (most likely the same as the ones from #47) and when it detects it as simple switch (which were not provided for #47).  Just the two messages with dps listed is enough.

**Comment by Krispkiwi** [comment]
The no support error didn't pop up this time when re adding it. There was this error in the logs though Device matches simple_switch with quality of 50%. DPS: {'1': False, '5': 32, 'updated_at': 1655351620.613873}

The switch hasn't picked up any sensor other than on/off

**Comment by make-all** [comment]
The config for this device has been reduced to make it more compatible in 0.17.0.  It will still be necessary to turn the kettle on and let it boil first before adding the device.

**Comment by Krispkiwi** [comment]
> The config for this device has been reduced to make it more compatible in 0.17.0. It will still be necessary to turn the kettle on and let it boil first before adding the device.

I'm getting temperature values! Thanks mate.

**Comment by Krispkiwi** [comment]
Hey mate, just letting you know logs are showing a warning from time to time "Unrecognised HVAC Mode of None ignored"
