### ISSUE TITLE
Request support for [HTW-TD-080KOID (KOI DUO) - Electric water heater with wifi]

### ISSUE THREAD

**Issue by MerzkayaGnida** [make-all/tuya-local#1831]
# Log Message

Device matches desk_lamp with quality of 25%. DPS: {"updated_at": 1713199125.6721308, "1": true, "2": "jiheat", "9": 60, "10": 57, "12": 0, "13": "heating", "14": 85, "20": 0}

```
Please paste logs here
```

# Information about DPS mappings

Information about DPS mappings
"Query Things Data Model":

````
{
  "result": {
    "model": "{\"modelId\":\"dywwh4\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"mode\",\"description\":\"即热、智能ECO\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"模式\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"jiheat\",\"maneco\"]}},
{\"abilityId\":9,\"accessMode\":\"rw\",\"code\":\"temp_set\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"温度设置\",\"typeSpec\":{\"type\":\"value\",\"max\":80,\"min\":40,\"scale\":0,\"step\":10,\"unit\":\"℃\"}},
{\"abilityId\":10,\"accessMode\":\"ro\",\"code\":\"temp_current\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"当前温度\",\"typeSpec\":{\"type\":\"value\",\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"℃\"}},
{\"abilityId\":12,\"accessMode\":\"ro\",\"code\":\"power_consumption\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"耗电量\",\"typeSpec\":{\"type\":\"value\",\"max\":10000,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"kwh\"}},
{\"abilityId\":13,\"accessMode\":\"ro\",\"code\":\"work_state\",\"description\":\"待机、加热中、保温中、预约中\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"工作状态\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"standby\",\"heating\",\"warm\",\"yuyueing\"]}},
{\"abilityId\":14,\"accessMode\":\"ro\",\"code\":\"surplus_water\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"剩余热水量\",\"typeSpec\":{\"type\":\"value\",\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"%\"}},
{\"abilityId\":20,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"干烧故障、传感器故障、超温故障\",\"extensions\":{\"scope\":\"fault\",\"attribute\":\"128\"},\"name\":\"故障告警\",\"typeSpec\":{\"type\":\"bitmap\",\"label\":[\"E2\",\"E3\",\"E4\"],\"maxlen\":3}}]}]}"
  },
  "success": true,
  "t": 1713191288621,
  "tid": "615ced75fb3411ee83bd6a1108d921ac"
}
````

<details>
<summary>Information about DPS mappings</summary>
"Device Control / Query Properties"
{
  "result": {
    "properties": [
      {
        "code": "switch",
        "custom_name": "",
        "dp_id": 1,
        "time": 1713168180815,
        "value": true
      },
      {
        "code": "mode",
        "custom_name": "",
        "dp_id": 2,
        "time": 1713168179233,
        "value": "jiheat"
      },
      {
        "code": "temp_set",
        "custom_name": "",
        "dp_id": 9,
        "time": 1713168179814,
        "value": 60
      },
      {
        "code": "temp_current",
        "custom_name": "",
        "dp_id": 10,
        "time": 1713183657568,
        "value": 58
      },
      {
        "code": "power_consumption",
        "custom_name": "",
        "dp_id": 12,
        "time": 1713180739969,
        "value": 3
      },
      {
        "code": "work_state",
        "custom_name": "",
        "dp_id": 13,
        "time": 1713180739969,
        "value": "warm"
      },
      {
        "code": "surplus_water",
        "custom_name": "",
        "dp_id": 14,
        "time": 1713183657935,
        "value": 90
      },
      {
        "code": "fault",
        "custom_name": "",
        "dp_id": 20,
        "time": 1713168180864,
        "value": 0
      }
    ]
  },
  "success": true,
  "t": 1713187226062,
  "tid": "ebe89b81fb2a11eebfdcf20bbc22db8f"
}

and
"Get the specifications and properties of the device":
{
  "result": {
    "category": "rs",
    "functions": [
      {
        "code": "switch",
        "desc": "{}",
        "name": "开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "desc": "{\"unit\":\"℃\",\"min\":40,\"max\":80,\"scale\":0,\"step\":10}",
        "name": "温度设置",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":40,\"max\":80,\"scale\":0,\"step\":10}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "name": "开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "name": "温度设置",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":40,\"max\":80,\"scale\":0,\"step\":10}"
      },
      {
        "code": "temp_current",
        "name": "当前温度",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "power_consumption",
        "name": "耗电量",
        "type": "Integer",
        "values": "{\"unit\":\"kwh\",\"min\":0,\"max\":10000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "work_state",
        "name": "工作状态",
        "type": "Enum",
        "values": "{\"range\":[\"standby\",\"heating\",\"warm\"]}"
      },
      {
        "code": "surplus_water",
        "name": "剩余水量",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "fault",
        "name": "故障告警",
        "type": "bitmap",
        "values": "{\"label\":[\"E2\",\"E3\",\"E4\"]}"
      }
    ]
  },
  "success": true,
  "t": 1713187964445,
  "tid": "a40545fffb2c11eea56dde7960427246"
</details>

# Product ID

    "product_id": "7lkpskrohoygvb8y",
    "product_name": "Double tank electric water heater",

# Information about how the device functions
https://htwspain.com/es/agua-caliente/termos-electricos/koi-duo/

Just a water heater 
(in addition to the standard functions of on/off and setting the set temperature, 
there is a certain smart mode, the meaning of which is some kind of intelligent learning, 
but access to it from the control or application is only on/off)

**Comment by MerzkayaGnida** [comment]
I would like to request that a feature be added to manually set the device to the disabled state.

**Comment by make-all** [comment]
HA already has this feature, there is no need to add another way of doing the same thing

**Comment by MerzkayaGnida** [comment]
The fact is that the services water_heater.turn_off and
water_heater.turn_on either generate an error (if applied to device_id):

service: water_heater.turn_off
data: {}
target:
  device_id: 6238fba73542780d63c80783853099b4

 *water_heater.turn_off. extra keys not allowed @ data['device_id']. Got
None*

or pretend that the service has worked, but does not physically change the
state of the device in any way (if applied to entity_id):
call service

service: water_heater.turn_off    (ore .turn_on)
target:
  entity_id: water_heater.htw_tl
data: {}

visually indicates success, but the device does not change state.

service: water_heater.set_away_mode
data:
  away_mode: false
target:
  entity_id: water_heater.htw_tl

results in an error:

*water_heater.set_away_mode. Unknown error*

In this case, the change in target temperature occurs successfully:

service: water_heater.set_temperature
data:
  temperature: 50
target:
  entity_id: water_heater.htw_tl


In the previous release (2024.5.2), you could manually configure all data
 In the previous release, you could manually configure all the data (dps
id=1) and enable/disable it worked perfectly.

сб, 1 июн. 2024 г. в 18:35, Jason Rumney ***@***.***>:

**Comment by make-all** [comment]
You can find the list of available services for water heaters here:

https://www.home-assistant.io/integrations/water_heater/#services

**Comment by jjprz** [comment]
Hi @MerzkayaGnida, what features can you currently use in Home Assistant? I’m thinking of buying this water heater and would like to know which functions I can use with Local Tuya.

**Comment by MerzkayaGnida** [comment]
Hi!
The standard temperature setting has a step of 10 degrees (40-50-60-70-80).
In HA (local-tuya) you can set a step of 1 degree. You can turn it on or
off, switch to smart mode (I did not use it, I do not know the details).
And, of course, information about the temperature and settings. There is no
energy consumption monitoring. "Not thick", but that's probably all.

вт, 28 янв. 2025 г. в 19:46, jjprz ***@***.***>:

**Comment by jjprz** [comment]
Awesome, I understand there’s a climate type entity. With that and a smart plug that measures energy, what more could you ask for? Haha, thanks so much!

**Comment by MerzkayaGnida** [comment]
Of the minuses - you can't influence the heating directly. Only by changing
the target temperature. By the way, "out of the box" the temperature is
also maintained in 10 degree increments. That is, set the target 50 - it
will heat up to 50 and turn off the heating, and turn on only when it cools
down to 40. I keep a smaller range by changing the target temperature. It
makes a sound with any manipulations - it doesn't bother me, but I couldn't
find a way to turn it off. Good luck!

вт, 28 янв. 2025 г. в 20:13, jjprz ***@***.***>:

**Comment by jjprz** [comment]
That behavior is used by all water heaters: they have a resistor that heats to the maximum and turns on and off according to the thermostat, with a margin of a few degrees to avoid constantly switching on and off.
The noise doesn’t bother me because it will be in a storage room.
So, I don’t have an issue with the drawbacks, but thanks for mentioning them.

**Comment by jjprz** [comment]
Hello. I just installed the water heater. I don't have the on-off option. I can change the target temperature, choose between eco and boost, see the remaining hot water, check the status, monitor energy consumption, and check for errors, but I can't turn it on or off. Any ideas?

**Comment by make-all** [comment]
Maybe I misunderstood the user manual, but the function of "on-off" is to switch between "standby" and "working" state. In standby state, the power is still on, and the anti-freeze protection will still operate. Therefore I mapped that to "away" and left the heater without an off switch.

**Comment by Anycubic** [comment]
@make-all I have two of this devices. Actually I have only "Performance" and "Eco" functions. Changing to "Eco" enables the "Smart" function which is not a standby mode, the heater will behave as it say in a "smart" mode but it will always be in a sort of heating mode. I can't really turn it off in any way, I can only simulate it by lowering the target temperature to lowest value. Could you please consider adding the "on-off" switch?
Thank you

**Comment by make-all** [comment]
I cannot add new features to devices that they did not already have. As described above, I have mapped the control you probably mean to "away", since according to the manual the standby mode still activates anti-frost protection.

**Comment by Anycubic** [comment]
Unfortunately it's not an "away" function but "smart" function. Sorry for my stupid question, but the original Tuya integration does have a "on-off" switch, why are you saying that this device doesn't have such a function?

**Comment by make-all** [comment]
Are you saying that the function this integration maps to away, and the default Tuya integration maps to on-off is actually "Smart"?

**Comment by jjprz** [comment]
I changed DPS 1 and 2 in the koiduo_water_heater.yaml file, and now it works perfectly. You have the option to turn it on and off using either the normal or eco (smart) mode:

```
dps:
  - id: 1
    name: operation_mode
    type: boolean
    mapping:
      - dps_val: false
        value: "off"
      - dps_val: true
        constraint: work_mode
        conditions:
          - dps_val: jiheat
            value: performance
          - dps_val: maneco
            value: eco
  - id: 2
    type: string
    name: work_mode
    hidden: true
```

**Comment by Anycubic** [comment]
@jjprz thank you I'll give it a try
