### ISSUE TITLE
Inventor EVA ION PRO WI-FI Dehumidifier Not Recognised

### ISSUE THREAD

**Issue by GadgetUK** [make-all/tuya-local#1839]
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**
Inventor EVA ION PRO WI-FI Dehumidifier Not Recognised despite device being supported. 
Device is identified as feit_dimmer

**To Reproduce*
Device never gets detected correctly.

**Expected behavior**
Should be idenfied as Inventor EVA ION PRO WI-FI Dehumidifier

**Additional context**

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

Please check if there are messages from Tuya Local in the Home

Device matches feit_dimmer with quality of 30%. DPS: {"updated_at": 1713538532.774442, "1": true, "2": 65, "4": "low", "5": "manual", "6": 59, "7": 18, "10": false, "19": 0, "101": false, "103": false}

<img width="1023" alt="Screenshot 2024-04-19 at 16 04 21" src="https://github.com/make-all/tuya-local/assets/1688999/7f527f5c-7bff-4c14-99fe-1df78e09a41e">
<img width="1568" alt="Screenshot 2024-04-19 at 16 02 49" src="https://github.com/make-all/tuya-local/assets/1688999/7df80b83-197d-47b6-abb4-00aca793eaf7">

**Comment by GadgetUK** [comment]
Redownloaded the latest release. Still being detected as a feit_dimmer.

Device matches feit_dimmer with quality of 30%. DPS: {"updated_at": 1713602448.1895847, "1": true, "2": 45, "4": "high", "5": "manual", "6": 64, "7": 17, "10": true, "19": 4, "101": true, "103": false}

Happy to provide more diagnostics if needed.

**Comment by make-all** [comment]
The fix for this is not released

**Comment by GadgetUK** [comment]
Ok. Sorry didn't understand the release / testing process.

Replaced the yaml. file with the new one from the repo, and bingo works as expected.

Many Thanks.
