### ISSUE TITLE
Warning at HA startup on Divoo Device

### ISSUE THREAD

**Issue by legantois** [make-all/tuya-local#1842]
**Describe the bug**
At each HA Reboot i receive the following warning from HA
2024-04-20 14:10:10.484 WARNING (MainThread) [custom_components.tuya_local.helpers.config] The use of switch for Dual water timer is deprecated and should be replaced by valve.

**To Reproduce**
device is a Divoo WiFi Sprinkler Timer 2 Zone, Diivoo Smart Water Timer For Garden Hose

https://www.diivoosmart.com/collections/water-timer-1/products/wifi-sprinkler-timer-2-zone-diivoo-smart-water-timer-for-garden-hose

**Expected behavior**

**Additional context**
Device diagnostic file
[tuya_local-6bb40b9fd8fbff83e45b33396312fd39-Dual water timer-0aae708fa9492bd8d5466ab81ab5fac4.json](https://github.com/make-all/tuya-local/files/15048149/tuya_local-6bb40b9fd8fbff83e45b33396312fd39-Dual.water.timer-0aae708fa9492bd8d5466ab81ab5fac4.json)

**Comment by make-all** [comment]
You should disable the deprecated entity once all your automations etc have been updated to use the valve. The message will then go away.

**Comment by legantois** [comment]
I updated all automations, actions...

I disabled the switch entities -> did not work
I removed the device and reinstalled it, disabled entities -> did not work


I still have as warning at each reboot: 
2024-05-28 11:24:32.093 WARNING (MainThread) [custom_components.tuya_local.helpers.config] The use of switch for Dual water timer is deprecated and should be replaced by valve.
2024-05-28 11:24:32.093 WARNING (MainThread) [custom_components.tuya_local.helpers.config] The use of switch for Dual water timer is deprecated and should be replaced by valve.

could it be possible to modify the configuration of this device so that when i reinstall it the switch entity is not created anymore ?

Many thanks for your help

**Comment by make-all** [comment]
You are right, my previous comment was incorrect.  The current location where that message is output is while parsing the config, before any filtering by the entity registry is done. I have made a change to move it to only output when the entity is added to hass, which I think will only get called for enabled entities.
