### ISSUE TITLE
Smartplug T34-Smart Plug+ product_id: "m4jtkjc43ltrilru"

### ISSUE THREAD

**Issue by BertBH** [make-all/tuya-local#1848]
Today I received some new Smart Plugs. In Smart Life it was no problem to install them, they are also already integrated in Tuya Standard integration.

In Tuya Local it's impossible to integrate them. Perhaps there is a need for another yaml file ?

Some data I got from the Tuya Developers Site

"category": "tdq",
"model": "",
"name": "T34-Smart Plug+",
"product_id": "m4jtkjc43ltrilru",
"product_name": "T34-Smart Plug+",

{
  "result": {
    "properties": [
      {
        "code": "switch_1",
        "custom_name": "",
        "dp_id": 1,
        "time": 1713887347826,
        "value": true
      },
      {
        "code": "countdown_1",
        "custom_name": "",
        "dp_id": 9,
        "time": 1713871536486,
        "value": 0
      },
      {
        "code": "add_ele",
        "custom_name": "",
        "dp_id": 20,
        "time": 1713900389000,
        "value": 74
      },
      {
        "code": "cur_current",
        "custom_name": "",
        "dp_id": 21,
        "time": 1713900851644,
        "value": 684
      },
      {
        "code": "cur_power",
        "custom_name": "",
        "dp_id": 22,
        "time": 1713900851644,
        "value": 1471
      },
      {
        "code": "cur_voltage",
        "custom_name": "",
        "dp_id": 23,
        "time": 1713900851644,
        "value": 2273
      },
      {
        "code": "test_bit",
        "custom_name": "",
        "dp_id": 24,
        "time": 1713871538205,
        "value": 1
      },
      {
        "code": "fault",
        "custom_name": "",
        "dp_id": 29,
        "time": 1713871536518,
        "value": 0
      },
      {
        "code": "relay_status",
        "custom_name": "",
        "dp_id": 38,
        "time": 1713871536486,
        "value": "memory"
      },
      {
        "code": "random_time",
        "custom_name": "",
        "dp_id": 42,
        "time": 1713871538205,
        "value": ""
      },
      {
        "code": "cycle_time",
        "custom_name": "",
        "dp_id": 43,
        "time": 1713871538205,
        "value": ""
      },
      {
        "code": "switch_inching",
        "custom_name": "",
        "dp_id": 44,
        "time": 1713871538205,
        "value": "AAAC"
      }
    ]
  },
  "success": true,
  "t": 1713901889513,
  "tid": "e07f5bdd01aa11efa95c2ed630a352ef"
}

**Comment by make-all** [comment]
There is insufficient info to categorise this as an issue. It may be better as a discussion if you just want an answer to a question, but even then a response is unlikely without local logs.

**Comment by valselt** [comment]
did you find the solution to this problem?
