### ISSUE TITLE
No climate entity created for Hombli TRV

### ISSUE THREAD

**Issue by MarkPaxton** [make-all/tuya-local#1850]
**Describe the bug**
I just updated to the latest release 2024.3.2. I noticed the climate entities no longer were provided for my Hombli TRVs. The secondary entities are working as expected.

If I remove the device and re-add it, only 9 entities are created, not including the climate entity.

Please help!

**To Reproduce**
Get and configure a Hombli TRV. Add it to HA. Note there's no 'climate' entity for it

**Expected behavior**
The primary climate  entity should be present.
 

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"
Preexisting device:

[tuya_local-9c75467585768332fe17c087a58b3dde-Workshop Thermostat-f07a583d837948c81d04072bded23fc5.json.txt](https://github.com/make-all/tuya-local/files/15100408/tuya_local-9c75467585768332fe17c087a58b3dde-Workshop.Thermostat-f07a583d837948c81d04072bded23fc5.json.txt)

Newly added device:
[tuya_local-3f261895b21e0e331f6b1132f2d92061-Bathroom Radiator-dd77c25fe08cf5e7306dcb389e7e4331.json.txt](https://github.com/make-all/tuya-local/files/15100429/tuya_local-3f261895b21e0e331f6b1132f2d92061-Bathroom.Radiator-dd77c25fe08cf5e7306dcb389e7e4331.json.txt)

**Comment by make-all** [comment]
The log may show some reason why HA has decided the climate entity is unavailable.  From the returned data, it seems like it should be all OK.

```
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "climate.workshop_thermostat",
>>>            "state": "unavailable",
            "attributes": {
              "restored": true,
              "hvac_modes": [
                "off",
                "heat"
              ],
              "min_temp": 5.0,
              "max_temp": 30.0,
              "target_temp_step": 0.5,
              "preset_modes": [
                "away",
                "home"
              ],
              "supported_features": 17
            },
            "last_changed": "2024-04-24T21:00:39.078013+00:00",
            "last_updated": "2024-04-24T21:00:39.078013+00:00"
          }
```

**Comment by MarkPaxton** [comment]
I've updated to the latest HA docker image (seems I was using an older/non official version I started using when it was running on rasberry pi). That seems to have solved it!

**Comment by make-all** [comment]
If you are not installing through HACS, then the minimum HA version would not be enforced, and I guess that may have been the cause (probably due to the translation key that was added, which required HA 2024.2 or later)
