### ISSUE TITLE
Detected that custom integration 'tuya_local' sets "minor_version" directly to update a config entry.

### ISSUE THREAD

**Issue by robinhood-code** [make-all/tuya-local#1854]
```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:188
First occurred: 11:06:46 AM (2 occurrences)
Last logged: 11:06:54 AM

Detected that custom integration 'tuya_local' sets "minor_version" directly to update a config entry. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to use async_update_entry instead at custom_components/tuya_local/__init__.py, line 448: entry.minor_version = 3, please create a bug report at https://github.com/make-all/tuya-local/issues
```

**Comment by RenierM26** [comment]
Hi There,

I noticed that after the last release, the config entry version get's bumped. It looks like the first device that gets processed, adds the "data" entries to "Options".

I edited the /homeassistant/.storage/core.config_entries, found the 1st tuya_local device and cleared the content under "options": {}.

Fixed the issue for me.

***Be very careful when editing this file. You can brake home assistant if you make a mistake.***

**Comment by Joao-Sousa-71** [comment]
@RenierM26 , I have the same message and in the core.config_entries have the following:

`{
        "entry_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "version": 13,
        "minor_version": 3,
        "domain": "tuya_local",
        "title": "Dual water timer WT05 (Rega Horta e Vasos)",
        "data": {
          "device_id": "yyyyyyyyyyyyyyyyyy",
          "host": "192.168.1.207",
          "local_key": "zzzzzzzzzzzzzzzzzzz",
          "protocol_version": 3.4,
          "poll_only": false,
          "device_cid": "wwwwwwwwwwww",
          "type": "diivoo_wt05"
        },
        "options": {},
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "user",
        "unique_id": "wwwwwwwwwwww",
        "disabled_by": null
      }`

From your comment I didn't understood what to delete. Can you please clarify?

**Comment by make-all** [comment]
Don't. It is unrelated, and will erase part of your config.

**Comment by make-all** [comment]
This is a deprecation warning, it means that Home Assistant has changed its way of doing things, and the old way will be removed in future (September according to the message).  Nothing needs to be fixed urgently, as the old method is still working for now.

The actual fix will need to be made in code, following the information here: https://developers.home-assistant.io/blog/2024/02/12/async_update_entry after additional investigation into exactly how to use the new function that was provided without proper documentation or examples.

**Comment by Joao-Sousa-71** [comment]
> This is a deprecation warning, it means that Home Assistant has changed its way of doing things, and the old way will be removed in future (September according to the message). Nothing needs to be fixed urgently, as the old method is still working for now.
> 
> The actual fix will need to be made in code, following the information here: https://developers.home-assistant.io/blog/2024/02/12/async_update_entry after additional investigation into exactly how to use the new function that was provided without proper documentation or examples.

@make-all thank you for your support. Just to let you know that the message has disapeared after another HA restart 👍 .
Not sure if will return but I'll keep the group posted. Thank you again.

**Comment by make-all** [comment]
Yes, since the code that triggers it is in migration code, it will only run once after the update. So it will disappear for now for you and anyone whose config has already been migrated with the entity naming changes in 2024.4.0
