### ISSUE TITLE
Cover window no status (status window= unkown)

### ISSUE THREAD

**Issue by oomichalekoo** [make-all/tuya-local#1864]
"model": "ZC34T-03-3A",
    "name": "Smart Windows and doors 2
    "product_name": "人工智能门窗",

{
  "result": {
    "category": "mc",
    "functions": [
      {
        "code": "control",
        "desc": "{\"range\":[\"open\",\"stop\",\"close\"]}",
        "name": "设备控制",
        "type": "Enum",
        "values": "{\"range\":[\"open\",\"stop\",\"close\"]}"
      }
    ],
    "status": [
      {
        "code": "control",
        "name": "设备控制",
        "type": "Enum",
        "values": "{\"range\":[\"open\",\"stop\",\"close\"]}

{
  "result": [
    {
      "channel": 0,
      "control_type": 0,
      "current_version": "3.1.4",
      "dev_type": 0,
      "last_upgrade_time": 0,
      "timeout": 0,
      "type": 0,
      "type_desc": "Moduł główny",
      "upgrade_status": 0
    },
    {
      "channel": 9,
      "control_type": 0,
      "current_version": "1.0.0",
      "dev_type": 0,
      "last_upgrade_time": 0,
      "timeout": 0,
      "type": 9,
      "type_desc": "Moduł MCU",
      "upgrade_status": 0
![Screenshot_20240430-223242](https://github.com/make-all/tuya-local/assets/74293198/d5074333-afc5-42a4-a6c6-c8a66ab2f7ed)

Bug is no state windows is always unkown and next bug is binary sensor motor fail should be OK

**Comment by oomichalekoo** [comment]
Lock ,wind and rain sensor work

**Comment by oomichalekoo** [comment]
"github-project-automation bot added this to Tuya Local 17 minutes ago" i dont understand how bot can add this ?

**Comment by make-all** [comment]
The problem is not clearly described, and there is no local log or diagnostic information.

**Comment by oomichalekoo** [comment]
śr., 1 maj 2024, 04:14 użytkownik Jason Rumney ***@***.***>
napisał:

> The problem is not clearly described, and there is no local log or
> diagnostic information.
>
Ten błąd pochodzi z niestandardowej integracji.

Rejestrator: custom_components.tuya_local.config_flow
Źródło: custom_components/tuya_local/config_flow.py:97
integracja: Tuya Local (dokumentacja, Problemy)
Pierwsze zdarzenie: 07:04:51 (1 zdarzenia)
Ostatnio zalogowany: 07:04:51

Device matches ZC34T-03-3A_swing_arm_opener with quality of 100%. DPS:
{"updated_at": 1714539890.4542875, "101": "stop", "105": "motor_fault",
"107": "on", "108": "off"}

**Comment by oomichalekoo** [comment]
Ten błąd pochodzi z niestandardowej integracji.

Rejestrator: custom_components.tuya_local.config_flow
Źródło: custom_components/tuya_local/config_flow.py:97
integracja: Tuya Local (dokumentacja, Problemy)
Pierwsze zdarzenie: 07:04:51 (1 zdarzenia)
Ostatnio zalogowany: 07:04:51

Device matches ZC34T-03-3A_swing_arm_opener with quality of 100%. DPS: {"updated_at": 1714539890.4542875, "101": "stop", "105": "motor_fault", "107": "on", "108": "off"}

![Screenshot_20240501-070527](https://github.com/make-all/tuya-local/assets/74293198/3e135c67-0fb4-4b30-8e65-40ae37a62698)
![Screenshot_20240501-070453](https://github.com/make-all/tuya-local/assets/74293198/8ae14932-dee7-4f59-96bc-dd8c9a056935)

**Comment by oomichalekoo** [comment]
State is unknow

**Comment by oomichalekoo** [comment]
Maybe this help from local tuya
[
![Screenshot_20240501-070453](https://github.com/make-all/tuya-local/assets/74293198/ba40898b-0c78-4ea1-b166-c30aba3fcaf0)

**Comment by oomichalekoo** [comment]
![Screenshot_20240501-071339](https://github.com/make-all/tuya-local/assets/74293198/8ba461d0-3b8b-4ff0-933c-3da7238ee4a8)

**Comment by oomichalekoo** [comment]
![Screenshot_20240501-072140](https://github.com/make-all/tuya-local/assets/74293198/6b9dfb32-f21a-412b-aebb-9740291542b2)

**Comment by make-all** [comment]
Unknown is correct, as this device is not providing any feedback that would allow determining whether it is open or closed. If we try to guess based on other things, one of the controls will be disabled, which becomes a problem when that guess is wrong.

**Comment by oomichalekoo** [comment]
In other component local-tuya status ok

pon., 24 lut 2025, 10:17 użytkownik Gameplay ***@***.***>
napisał:
