### ISSUE TITLE
Request support for Remote Control ZBRC10WT

### ISSUE THREAD

**Issue by sveos** [make-all/tuya-local#1867]
# Log Message

```
Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:97
integration: Tuya Local ([documentation](https://github.com/make-all/tuya-local), [issues](https://github.com/make-all/tuya-local/issues))
First occurred: 10:14:42 PM (1 occurrences)
Last logged: 10:14:42 PM
Device matches None with quality of 0%. DPS: {"updated_at": 1713903265.314957, "3": 75, "27": "arm", "29": "sos"}








2024-04-23 22:14:25.315 DEBUG (SyncWorker_18) [custom_components.tuya_local.device] Test refreshed device state: {"dps": {"3": 75, "27": "arm", "29": "sos"}, "cid": "bc33acfffe5220a4", "device": "Non-JSON: (Device( 'bf7ca3836fc5310a1arjtg', address=None, local_key='', dev_type='default', connection_timeout=5, version=3.3, persist=False, cid='bc33acfffe5220a4', parent='bf7ca3836fc5310a1arjtg', children={} ))"}
```

# Information about DPS mappings

```
Query Zigbee devices under the gateway
Device_id: bf65cbc99a621d7646rbqo
    {
      "active_time": 1713300052,
      "category": "sos",
      "icon": "smart/icon/ay1513237774906SMBA3/497f02df5cd9517b42622ef10f38663e.png",
      "id": "bf7ca3836fc5310a1arjtg",
      "name": "6 Remote Control",
      "node_id": "bc33acfffe5220a4",
      "online": true,
      "owner_id": "181853912",
      "product_id": "fsiepnrh",
      "update_time": 1713300052
    },
  ],
  "success": true,
  "t": 1713905321169,
  "tid": "ddde55d101b211efa95c2ed630a352ef"
}




DP: {"3":"Battery","26":"B","27":"1","28":"A","29":"0"}
```

# Product ID
   "product_id": "fsiepnrh",

# Information about how the device functions
https://nedis.com/en-us/product/smart-home/control/remote-controls/550735173/smartlife-remote-control-zigbee-30-number-of-buttons-4-android-ios-white

“[Brand: Nedis](https://nedis.com/en-us/search?filterBrand=Nedis)
Vendor Part Number: ZBRC10WT
EAN number: 5412810330997
- Control any Nedis SmartLife device by connecting this remote control to your Nedis ZigBee gateway.
- 4 buttons which can be programmed
- Battery included with lifetime of 1 year (average use)
- Instant response, no noticeable delay
- Option to set different programs for different periods
“
“Connect this remote control with SmartLife through a Zigbee gateway (WIFIZBxxx) to have full control over your entire Smart Home without even touching your phone.
Each button can be programmed to control any number of Nedis SmartLife products, not only switch them on/off, but also to set a predefined brightness or even to start a full scenario or enable or disable an automation. Each button can even be programmed to act differently depending on the time of day or day in the week.
So whether you want to use this remote to control your alarm, your smart bulb or your Air conditioner, as long as it is controllable within the Nedis SmartLife application, you can control it with this remote control.”

**Comment by make-all** [comment]
The information is a bit vague, but it seems like the buttons can be programmed to generate certain strings when pressed, which could be included with the event info. I assume the battery is a percentage.

**Comment by sveos** [comment]
Hi @make-all Jason,

Thank you for your comment. The buttons are running sn Automation in e.g. Smart home app. Yes the battery is in percentage.
Pls let me know If I shall deliver any more info.

Best regards Sven 
![Screenshot_20240501_210952_Smart Life](https://github.com/make-all/tuya-local/assets/160712684/589043d3-3258-4d30-a0b4-86683d9d7002)
