### ISSUE TITLE
After each HA reboot all devices start offline

### ISSUE THREAD

**Issue by sambarlick** [make-all/tuya-local#1869]
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**
After each Home Assistant reboot all devices are offline and require manually refreshing.
**To Reproduce**
Steps to reproduce the behavior including the device the issue was observed with:
All of my devices are offline when HA starts.
**Expected behavior**
All devices to available when HA starts.
**Additional context**
Problem started with HA 2024.5beta
If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"
[error_log.txt](https://github.com/make-all/tuya-local/files/15177513/error_log.txt)

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

**Comment by garry0garry** [comment]
HA 2024.5.0
tompd_63lw_breaker - offline

**Comment by make-all** [comment]
Issue may not be solved by this change, see #1871
