### ISSUE TITLE
Add New Device (Dehumidifier-D030) 

### ISSUE THREAD

**Issue by KaportsevIA** [make-all/tuya-local#188]
Add new Device HUYNDAI PEW83/84

`
{
  "result": {
    "active_time": 1641845113,
    "biz_type": 0,
    "category": "cs",
    "create_time": 1641554697,
    "icon": "smart/icon/ay15105372588696Qo9c/d07e57e4353c13e0eb9d98bcb4b23908.png",
    "id": "XXXXXXXXX",
    "ip": "XXX.XXX.XXX.XXX",
    "lat": "XXX",
    "local_key": "XXXXXXXXXXXX",
    "lon": "XXX",
    "model": "D030（24小时）",
    "name": "Осушитель Сахара 20",
    "online": true,
    "owner_id": "XXXXXXX",
    "product_id": "r6gik8xajfg0lv1y",
    "product_name": "Dehumidifier-D030 ",
    "status": [
      {
        "code": "switch",
        "value": false
      },
      {
        "code": "dehumidify_set_value",
        "value": 50
      },
      {
        "code": "fan_speed_enum",
        "value": "high"
      },
      {
        "code": "humidity_indoor",
        "value": 73
      },
      {
        "code": "temp_indoor",
        "value": 25
      },
      {
        "code": "sleep",
        "value": false
      },
      {
        "code": "child_lock",
        "value": false
      },
      {
        "code": "fault",
        "value": 0
      }
    ],
    "sub": false,
    "time_zone": "+03:00",
    "uid": "XXXXXXX",
    "update_time": 1649578582,
    "uuid": "XXXXXXX"
  },
  "success": true,
  "t": 1656658677015,
  "tid": "2308b9caf90b11ecbf6a7eeb5c0b2a19"
}

-
![Снимок экрана 2022-07-01 095633](https://user-images.githubusercontent.com/98884453/176841384-0f2afb9e-14c1-4c66-af99-5eb88c240045.png)

**Comment by make-all** [comment]
Is the first set of info from iot.tuya.com?  If you have access there, the most useful information is from the Cloud / API Explorer, Section "Device Control" (second to last category in left hand list), "Get Device Specification Attribute" (last function under Device Control).

This function will include both dp_id and range information (for the fields that are available through the cloud API).  Since there may also be local only fields not listed in the cloud API docs, the warning message from HA logs when you try to add the device is also useful.

**Comment by make-all** [comment]
Thanks, that gives the info I need.  Have you customized the logging in HA to only show errors?  Tuya local emits a warning message containing all the DPS for a device whenever you try to add one and an exact match is not found.  If it is detecting as a simple switch, I would expect such an error.  I am talking about the logs in Settings / System / Logs.

**Comment by KaportsevIA** [comment]
Add complete successfully. On weekend will be working check.
Respect
![Снимок экрана 2022-07-01 175048](https://user-images.githubusercontent.com/98884453/176918223-2affa2d8-f360-4d91-a4d4-0b33745f1fa2.png)
.

**Comment by KaportsevIA** [comment]
Everything works. Except for the fan. But I couldn't beat him in another integration. The fan has only two modes - Low and High speed. In the native Tuya Smart app - there is no mode turned off. And when switching modes via local integrations, the fan turns off completely. I.e., according to the logic of the dehumidifier, either the fan turns off together with the dehumidifier only when the percentage of humidity reaches the set threshold, or turns on the last setting (Low/High) when the humidity is higher than the set one.

**Comment by make-all** [comment]
Off will turn off the whole dehumidifier, it is connected to the same switch, but the fan should be working - when set to 50%, it should be on low, and 100% on high.  Thresholds are probably <25% = Off, 25-75% = low, >75% = high, but you should see the speed snap to 50 or 100 after you set it.
