### ISSUE TITLE
Arlec wall plugs not available 

### ISSUE THREAD

**Issue by jochi82** [make-all/tuya-local#1889]
**Describe the bug**
Since the latest HACS fix all my Arlec wall plugs show failed to set up.
Trying to configure them again brings Sorry, there is no support for this device message.

Logger: custom_components.tuya_local
Source: custom_components/tuya_local/__init__.py:481
integration: Tuya Local (documentation, issues)
First occurred: 7:38:10 AM (1 occurrences)
Last logged: 7:38:10 AM

Configuration file for smartplugv2 not found

Re-adding the smart plug identify it as Compter electric meter

**Comment by make-all** [comment]
HA 2024.5 seems to have exposed a lot of issues in many integrations. There may be one in HACS, as this is the second issue in the past few days where files are missing from this integration after an upgrade to the latest version.

**Comment by make-all** [comment]
Anyway, if files are missing, as the error message suggests, then this is an error that is happening outside of this integration.
