### ISSUE TITLE
Tuya devices (presence sensors) became unavailable after HA restart

### ISSUE THREAD

**Issue by Motya-HA** [make-all/tuya-local#1893]
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**
Tuya presence sensors became unavailable after HA restart. 
After every device is reloaded in Tuya local integration, they become operational again

**To Reproduce**
Restart HA

**Expected behavior**
Tuya local devices should become unavailable after HA restart.

**Additional context**

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.5.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.2",
    "docker": true,
    "arch": "aarch64",
    "timezone": "America/Los_Angeles",
    "os_name": "Linux",
    "os_version": "6.6.25-haos",
    "supervisor": "2024.04.4",
    "host_os": "Home Assistant OS 12.2",
    "docker_version": "25.0.5",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "ha_carrier": {
      "documentation": "https://github.com/dahlb/ha_carrier",
      "version": "1.21.5",
      "requirements": [
        "carrier-api==1.12.0"
      ]
    },
    "tuya_local": {
      "documentation": "https://github.com/make-all/tuya-local",
      "version": "2024.4.0",
      "requirements": [
        "tinytuya==1.13.2"
      ]
    },
    "presence_simulation": {
      "documentation": "https://github.com/slashback100/presence_simulation",
      "version": "4.5",
      "requirements": []
    },
    "smartlife": {
      "documentation": "https://www.home-assistant.io/integrations/smartlife",
      "version": "0.1.0",
      "requirements": [
        "tuya-device-sharing-sdk==0.2.0"
      ]
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "alarmo": {
      "documentation": "https://github.com/nielsfaber/alarmo",
      "version": "v1.10.0",
      "requirements": []
    },
    "schlage": {
      "documentation": "https://github.com/mcnutter1/homeasssitant-schlage",
      "version": "1.0",
      "requirements": []
 ),
    "alexa_media": {
      "documentation": "https://github.com/alandtse/alexa_media_player/wiki",
      "version": "4.9.2",
      "requirements": [
        "alexapy==1.27.10",
        "packaging>=20.3",
        "wrapt>=1.14.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya_local",
    "name": "Tuya Local",
    "codeowners": [
      "@make-all"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/make-all/tuya-local",
    "integration_type": "device",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/make-all/tuya-local/issues",
    "requirements": [
      "tinytuya==1.13.2"
    ],
    "version": "2024.4.0",
    "is_built_in": false
  },
  "data": {
    "name": "Entry Presence Sensor",
    "type": "zym201_presence_sensor",
    "device_id": "**REDACTED**",
    "device_cid": "",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": 3.3,
    "tinytuya_version": "1.13.2",
    "api_version_set": 3.3,
    "api_version_used": 3.3,
    "api_working": true,
    "status": {},
    "cached_state": {
      "updated_at": 1715107238.1516948,
      "1": "none",
      "4": 250,
      "9": 0,
      "101": "nobody",
      "102": 20,
      "104": 35
    },
    "pending_state": {},
    "connected": true,
    "force_dps": [],
    "home_assistant": {
      "name": "Entry Presence Sensor",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "occupancy",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "binary_sensor.entry_presence_sensor_occupancy",
            "state": "off",
            "attributes": {
              "device_class": "occupancy",
              "friendly_name": "Entry Presence Sensor Occupancy"
            },
            "last_changed": "2024-05-07T16:44:28.054301+00:00",
            "last_reported": "2024-05-07T16:44:28.534666+00:00",
            "last_updated": "2024-05-07T16:44:28.054301+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "enum",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "sensor.entry_presence_sensor_presence_state",
            "state": "None",
            "attributes": {
              "options": [
                "None",
                "Still",
                "Moving"
              ],
              "device_class": "enum",
              "icon": "mdi:motion-sensor-off",
              "friendly_name": "Entry Presence Sensor Presence state"
            },
            "last_changed": "2024-05-07T16:44:27.936965+00:00",
            "last_reported": "2024-05-07T16:44:28.535194+00:00",
            "last_updated": "2024-05-07T16:44:27.936965+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "distance",
          "icon": null,
          "unit_of_measurement": "ft",
          "state": {
            "entity_id": "sensor.entry_presence_sensor_target_distance",
            "state": "0.0",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "ft",
              "device_class": "distance",
              "icon": "mdi:tape-measure",
              "friendly_name": "Entry Presence Sensor Target distance"
            },
            "last_changed": "2024-05-07T16:44:28.535714+00:00",
            "last_reported": "2024-05-07T16:44:28.535714+00:00",
            "last_updated": "2024-05-07T16:44:28.535714+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "illuminance",
          "icon": null,
          "unit_of_measurement": "lx",
          "state": {
            "entity_id": "sensor.entry_presence_sensor_illuminance",
            "state": "35",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "lx",
              "device_class": "illuminance",
              "friendly_name": "Entry Presence Sensor Illuminance"
            },
            "last_changed": "2024-05-07T18:40:06.548732+00:00",
            "last_reported": "2024-05-07T18:40:06.548732+00:00",
            "last_updated": "2024-05-07T18:40:06.548732+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "number.entry_presence_sensor_sensitivity",
            "state": "unknown",
            "attributes": {
              "min": 1.0,
              "max": 10.0,
              "step": 1.0,
              "mode": "auto",
              "icon": "mdi:human-greeting-proximity",
              "friendly_name": "Entry Presence Sensor Sensitivity"
            },
            "last_changed": "2024-05-07T14:17:47.325121+00:00",
            "last_reported": "2024-05-07T14:17:47.325121+00:00",
            "last_updated": "2024-05-07T14:17:47.325121+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": "m",
          "state": {
            "entity_id": "number.entry_presence_sensor_maximum_detection_distance",
            "state": "2.5",
            "attributes": {
              "min": 1.5,
              "max": 5.5,
              "step": 0.01,
              "mode": "auto",
              "unit_of_measurement": "m",
              "icon": "mdi:arrow-collapse-right",
              "friendly_name": "Entry Presence Sensor Maximum detection distance"
            },
            "last_changed": "2024-05-07T14:17:47.325943+00:00",
            "last_reported": "2024-05-07T14:17:47.325943+00:00",
            "last_updated": "2024-05-07T14:17:47.325943+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": "s",
          "state": {
            "entity_id": "number.entry_presence_sensor_fading_time",
            "state": "2.0",
            "attributes": {
              "min": 0.5,
              "max": 150.0,
              "step": 0.5,
              "mode": "auto",
              "unit_of_measurement": "s",
              "icon": "mdi:timer-sand-complete",
              "friendly_name": "Entry Presence Sensor Fading time"
            },
            "last_changed": "2024-05-07T14:17:47.326426+00:00",
            "last_reported": "2024-05-07T14:17:47.326426+00:00",
            "last_updated": "2024-05-07T14:17:47.326426+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "number.entry_presence_sensor_static_sensitivity",
            "state": "unknown",
            "attributes": {
              "min": 1.0,
              "max": 10.0,
              "step": 1.0,
              "mode": "auto",
              "icon": "mdi:human-greeting-proximity",
              "friendly_name": "Entry Presence Sensor Static sensitivity"
            },
            "last_changed": "2024-05-07T14:17:47.326807+00:00",
            "last_reported": "2024-05-07T14:17:47.326807+00:00",
            "last_updated": "2024-05-07T14:17:47.326807+00:00"
          }
        }
      ]
    }
  }
}

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

2024-05-07 07:15:34.622 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.12/asyncio/base_events.py:1973: RuntimeWarning: coroutine 'TuyaLocalDevice.receive_loop' was never awaited

**Comment by make-all** [comment]
The diagnostics show you are using an old version of the integration.
