### ISSUE TITLE
Request support for WIFIDS20WT Smoke detector

### ISSUE THREAD

**Issue by pimhofstee** [make-all/tuya-local#1894]
# Log Message

```
2024-05-07 22:41:25.531 WARNING (SyncWorker_23) [custom_components.tuya_local.device] Test protocol error 901: Network Error: Unable to Connect
```

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"0000048vgk\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"ro\",\"code\":\"smoke_sensor_state\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-yanwu\",\"attribute\":\"128\"},\"name\":\"烟雾检测状态\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"alarm\",\"normal\"]}},{\"abilityId\":11,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-baojing\",\"attribute\":\"1152\"},\"name\":\"故障告警\",\"typeSpec\":{\"type\":\"bitmap\",\"label\":[\"fault\"],\"maxlen\":1}},{\"abilityId\":14,\"accessMode\":\"ro\",\"code\":\"battery_state\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_battery\",\"attribute\":\"128\"},\"name\":\"电池电量状态\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"low\",\"middle\",\"high\"]}}]}]}"
  },
  "success": true,
  "t": 1715123701294,
  "tid": "a119b5580cc711ef9d60feae420aa81f"
}
```

{
  "result": {
    "category": "ywbj",
    "status": [
      {
        "code": "smoke_sensor_state",
        "name": "烟雾检测状态",
        "type": "Enum",
        "values": "{\"range\":[\"alarm\",\"normal\"]}"
      },
      {
        "code": "fault",
        "name": "故障告警",
        "type": "Bitmap",
        "values": "{\"label\":[\"fault\"],\"maxlen\":1}"
      },
      {
        "code": "battery_state",
        "name": "电池电量状态",
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"middle\",\"high\"]}"
      }
    ]
  },
  "success": true,
  "t": 1715123759261,
  "tid": "c386ecb20cc711ef97d9aeb02fd8bd34"
}

# Product ID

  "product_id": "inwnovped8h5aoaw",
  "product_name": "Smart Smoke Detector WIFIDS20WT",

# Information about how the device functions

Battery powered smoke sensor. Goes offline very quickly to save power. Reset button on top.

https://github.com/arendst/Tasmota/discussions/19653
https://nedis.nl/WIFIDS20WT

**Comment by make-all** [comment]
Battery powered devices cannot be supported locally without a hub.
