### ISSUE TITLE
All devices were working, now all entities show Unavailable

### ISSUE THREAD

**Issue by rknobbe** [make-all/tuya-local#1896]
I'm using Tuya Local 2024.4.0. I have 4 devices, all of which were set up using the SmartLife app and added to Tuya Local from the developer portal using the instructions here.  In the last week or so, all of these devices now show up in HomeAssistant as Unavailable. However all still show up in the SmartLife app properly.  Devices include an mmwave presence detector, a smart bulb, a smart power strip, and a low voltage patio lighting controller.

I've attached the json diagnostic logs from 2 of the devices (the MMWave presence detector and the patio lighting controller).  I've turned on debug logging for the Tuya Local integration.

[tuya_local-c47cdd7ada0228ce9a329e177a2dbcc6-mmWave presence sensor-3793336ccfb01d00897c054ee3dee788.json](https://github.com/make-all/tuya-local/files/15251318/tuya_local-c47cdd7ada0228ce9a329e177a2dbcc6-mmWave.presence.sensor-3793336ccfb01d00897c054ee3dee788.json)
[tuya_local-60a7bfda90ccd7a8155f7a50bb3dee61-Planter-f951b7b7072b3ac60370ebdc331f683a.json](https://github.com/make-all/tuya-local/files/15251317/tuya_local-60a7bfda90ccd7a8155f7a50bb3dee61-Planter-f951b7b7072b3ac60370ebdc331f683a.json)

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

Logger: homeassistant.util.loop
Source: util/loop.py:99
First occurred: May 6, 2024 at 1:25:52 PM (3 occurrences)
Last logged: May 6, 2024 at 1:25:54 PM

Detected blocking call to sleep inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/device.py, line 77: self._api = tinytuya.Device(dev_id, address, local_key) (offender: /usr/local/lib/python3.12/site-packages/tinytuya/core.py, line 944: time.sleep(0.1)), please create a bug report at https://github.com/make-all/tuya-local/issues

This error originated from a custom integration.

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:554
integration: Tuya Local (documentation, issues)
First occurred: May 6, 2024 at 1:25:57 PM (4 occurrences)
Last logged: May 6, 2024 at 1:26:09 PM

Failed to refresh device state for Office LED.
Failed to refresh device state for Planter.
Failed to refresh device state for mmWave presence sensor.
Failed to refresh device state for Genio Smart Power Board 2Gnd.

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:190
First occurred: May 6, 2024 at 1:25:50 PM (18 occurrences)
Last logged: May 6, 2024 at 1:26:16 PM

Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'tuya_local' calls async_write_ha_state from a thread at custom_components/tuya_local/device.py, line 423: entity.async_write_ha_state(), please report it to the author of the 'tuya_local' custom integration
Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 642: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'tuya_local' calls async_create_task from a thread at custom_components/tuya_local/device.py, line 147: self._refresh_task = self._hass.async_create_task(self.receive_loop()), please report it to the author of the 'tuya_local' custom integration

**Comment by make-all** [comment]
You are reporting problems with an outdated version of tuya-local.  Please upgrade first.
