### ISSUE TITLE
Request support for dual temp regulator

### ISSUE THREAD

**Issue by SmartLifeAbbecourt** [make-all/tuya-local#1902]
Hello,

I have special device Product Category : rs.

Clearly, it's dual thermostat with one channel able to be control with temperature difference between sensor channel 1 and 2.

It's is possible to have integration for it?

When I try to add it, it's found but I can not found any corresponding device, entities are not matching with any on list.

Below json to control it:

[
  {
    "code": "Power",
    "value": false
  },
  {
    "code": "temp_set",
    "value": 569
  },
  {
    "code": "T1RUN",
    "value": -40
  },
  {
    "code": "T2_UP_LIMIT",
    "value": 15
  },
  {
    "code": "T2_down_limit",
    "value": 8
  },
  {
    "code": "SWITCH2",
    "value": false
  },
  {
    "code": "UpAlarm",
    "value": 120
  },
  {
    "code": "DownAlarm",
    "value": 80
  },
  {
    "code": "Alarm",
    "value": false
  },
  {
    "code": "CH2MODE",
    "value": "DIFF2"
  },
  {
    "code": "ADJUST1",
    "value": 0
  },
  {
    "code": "ADJUST2",
    "value": 0
  },
  {
    "code": "CH1_RealTemp",
    "value": 190
  },
  {
    "code": "CH2_RealTemp",
    "value": 161
  }
]

below data from iot tuya:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/PDenis/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/PDenis/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Code | Type | Values
-- | -- | --
Power | Boolean | "{true,false}"

temp_set | Integer | {
"unit": "℃",
"min": -400,
"max": 1400,
"scale": 1,
"step": 1
}
 
temp_current | Integer | {
"unit": "℃",
"min": -400,
"max": 1400,
"scale": 1,
"step": 1
}
 
T1RUN | Integer | {
"unit": "℃",
"min": -400,
"max": 1400,
"scale": 1,
"step": 1
}
 
TEMP2 | Integer | {
"unit": "℃",
"min": -400,
"max": 1400,
"scale": 1,
"step": 1
}
 
T2_UP_LIMIT | Integer | {
"unit": "℃",
"min": -400,
"max": 1400,
"scale": 1,
"step": 1
}
 
T2_down_limit | Integer | {
"unit": "℃",
"min": -400,
"max": 1400,
"scale": 1,
"step": 1
}
 
SWITCH2 | Boolean | "{true,false}"

UpAlarm | Integer | {
"unit": "℃",
"min": -400,
"max": 1400,
"scale": 1,
"step": 1
}
 
DownAlarm | Integer | {
"unit": "℃",
"min": -400,
"max": 1400,
"scale": 1,
"step": 1
}
 
Alarm | Boolean | "{true,false}"

T1STATUS | Enum | {
"range": [
"NORMAL",
"OPEN",
"SHORT",
"UP",
"DOWN"
]
}
 
T2STATUS | Enum | {
"range": [
"NORMAL",
"OPEN",
"SHORT",
"UP",
"DOWN"
]
}
 
CH2MODE | Enum | {
"range": [
"HOT2",
"COLD2",
"ALARM2",
"DIFF2"
]
}
 
CH1MODE | Enum | {
"range": [
"HOT1",
"COLD2"
]
}
 
ADJUST1 | Integer | {
"unit": "℃",
"min": -150,
"max": 150,
"scale": 1,
"step": 1
}
 
ADJUST2 | Integer | {
"unit": "℃",
"min": -150,
"max": 150,
"scale": 1,
"step": 1
}
 
DIFFTEMP | Integer | {
"unit": "℃",
"min": -1600,
"max": 2000,
"scale": 1,
"step": 1
}
 
CH1_RealTemp | Integer | {
"unit": "℃",
"min": -400,
"max": 1400,
"scale": 1,
"step": 1
}
 
CH2_RealTemp | Integer | {
"unit": " ℃",
"min": -400,
"max": 1400,
"scale": 1,
"step": 1
}
 

</body>

</html>

**Comment by make-all** [comment]
The log message when it is found but not matched to any existing config is essential information
