### ISSUE TITLE
Temperature off by a factor of 10 with some Entities

### ISSUE THREAD

**Issue by Mrsash2020** [make-all/tuya-local#1907]
https://www.aliexpress.com/item/1005005372714992.html?spm=a2g0o.productlist.main.29.6be04f0fOEHZE4&algo_pvid=0c8a2f78-29f0-43b5-ba0b-7cb4a7a3162e&algo_exp_id=0c8a2f78-29f0-43b5-ba0b-7cb4a7a3162e-14&pdp_npi=4%40dis%21AUD%2178.84%2118.36%21%21%21371.02%2186.42%21%402101e5c517154395539983527e484c%2112000032789022863%21sea%21AU%210%21AB&curPageLogUid=HSDlkxo9sW1e&utparam-url=scene%3Asearch%7Cquery_from%3A

Ok so brought this device to monitor my Aquarium which works perfectly in tuya app. It also has temp and humidity high and low alarms to be setup. So I try to maintain the temp of the Aquarium around 30 deg C for tropical setup. In the tuya app I am able to set the temp high to 34 and low to 26 for alarms. 

In HA I was able to get the current temp which is around 28.3 deg C fine but the limits have to setup in multiples of 10, so I need to somehow divide it by 10 else the alarms go off in the tuya app because setting it up as 26 and 34, sets it up in tuya as 2.6 and 3.4 etc. See pic

No bug report really because nothing is actually erroring out.

**Expected behavior**

**Additional context**
I added this device with 3.4 in config as 3.3 did not work. Not sure if that is related at all.

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

![20240512_011140](https://github.com/make-all/tuya-local/assets/62192773/772a24ae-882c-486a-b0c9-2da41c957978)
![Screenshot_20240512_011055_Tuya Smart](https://github.com/make-all/tuya-local/assets/62192773/6025af0e-a0c6-486c-b111-49d8f7a6f976)

**Comment by make-all** [comment]
You seem to have a variant of a supported device with different temperature scale, but there is no log or diagnostics attached to your report that would show which device config you are using.

**Comment by Mrsash2020** [comment]
I will attach it. Not sure if I should be removing any info from it.
[config_entry-tuya_local-15ed4e2d7f83f3533423d2788fe947b7.json](https://github.com/make-all/tuya-local/files/15285095/config_entry-tuya_local-15ed4e2d7f83f3533423d2788fe947b7.json)

**Comment by Mrsash2020** [comment]
Do I need to add any more info? I do note the temp is showing correctly but the limits for the alarms are off by a factor of 10.

thanks

**Comment by make-all** [comment]
Are you trying the latest development version, or still on the last release?

**Comment by Mrsash2020** [comment]
Latest release, which also has the issue that I have to reload all devices since they become unresponsive after reboot

**Comment by make-all** [comment]
I think that is not even the latest release then, but the April release, before a series of hotfixes were attempted following the HA 2024.5 release which caused the above problem

**Comment by Mrsash2020** [comment]
ok I heard about it but have nothing in the way of updates. I update to latest usually

**Comment by make-all** [comment]
If you installed via HACS, then it should take care of prompting you when there is an update (but if you pressed "Ignore" at any stage, it may have stopped prompting).
If you installed tuya-local manually, you will need to check for updates yourself.  The latest now is [2024.5.2](https://github.com/make-all/tuya-local/releases)

**Comment by Mrsash2020** [comment]
Nope never hit ignore. Ho do I install this one? Sorry consider me Noob

**Comment by Mrsash2020** [comment]
Sorry may I ask if there is any update? I am now using the latest version but am thinking you were wanting me to test a beta version? Sorry dont know what the term is.

**Comment by Mrsash2020** [comment]
I was wondering why mine wasn't showing. I had to again go to hacs for the update to show. Curious when was it released? 

BTW thank you so much for fixing this.
