### ISSUE TITLE
Request support for [Water Timer Via WG01 WiFi BLE gateway]

### ISSUE THREAD

**Issue by tomarigr** [make-all/tuya-local#1909]
HA fails spectacularly to add this device and creates no logs about DPS.

This is for Water Timer: "category": "sfkzq"
{
  "result": {
    "properties": [
      {
        "code": "switch",
        "custom_name": "",
        "dp_id": 1,
        "time": 1715456963850,
        "value": false
      },
      {
        "code": "fault",
        "custom_name": "",
        "dp_id": 4,
        "time": 1715430827385,
        "value": 0
      },
      {
        "code": "battery_percentage",
        "custom_name": "",
        "dp_id": 7,
        "time": 1715430827385,
        "value": 100
      },
      {
        "code": "time_use",
        "custom_name": "",
        "dp_id": 9,
        "time": 1715456963850,
        "value": 1498
      },
      {
        "code": "weather_delay",
        "custom_name": "",
        "dp_id": 10,
        "time": 1715430827385,
        "value": "cancel"
      },
      {
        "code": "countdown",
        "custom_name": "",
        "dp_id": 11,
        "time": 1715456963850,
        "value": 0
      },
      {
        "code": "work_state",
        "custom_name": "",
        "dp_id": 12,
        "time": 1715456963850,
        "value": "idle"
      },
      {
        "code": "smart_weather",
        "custom_name": "",
        "dp_id": 13,
        "time": 1715430250897,
        "value": "sunny"
      },
      {
        "code": "switch_weather",
        "custom_name": "",
        "dp_id": 14,
        "time": 1715430827385,
        "value": false
      },
      {
        "code": "use_time_one",
        "custom_name": "",
        "dp_id": 15,
        "time": 1715456963000,
        "value": 600
      },
      {
        "code": "cycle_timing",
        "custom_name": "",
        "dp_id": 16,
        "time": 1715496806455,
        "value": "AA=="
      },
      {
        "code": "timer",
        "custom_name": "",
        "dp_id": 17,
        "time": 1715496806555,
        "value": "AA=="
      }
    ]
  },
  "success": true,
  "t": 1715499980467,
  "tid": "b8f4e34c103311ef9d60feae420aa81f"
}

{
  "result": {
    "model": "{\"modelId\":\"00000208kg\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power\",\"attribute\":\"640\"},\"name\":\"阀门开关\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":4,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"故障上报\",\"typeSpec\":{\"type\":\"bitmap\",\"label\":[\"low_battery\",\"fault\",\"lack_water\",\"sensor_fault\",\"motor_fault\"],\"maxlen\":5}},{\"abilityId\":7,\"accessMode\":\"ro\",\"code\":\"battery_percentage\",\"description\":\"\",\"extensions\":{\"attribute\":\"192\"},\"name\":\"电池电量\",\"typeSpec\":{\"type\":\"value\",\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"%\"}},{\"abilityId\":9,\"accessMode\":\"rw\",\"code\":\"time_use\",\"description\":\"\",\"extensions\":{\"attribute\":\"640\"},\"name\":\"累计使用时间\",\"typeSpec\":{\"type\":\"value\",\"max\":2592000,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"s\"}},{\"abilityId\":10,\"accessMode\":\"rw\",\"code\":\"weather_delay\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-shidu\",\"attribute\":\"640\"},\"name\":\"天气延时\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"cancel\",\"24h\",\"48h\",\"72h\"]}},{\"abilityId\":11,\"accessMode\":\"rw\",\"code\":\"countdown\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-timer1\",\"attribute\":\"640\"},\"name\":\"灌溉时间\",\"typeSpec\":{\"type\":\"value\",\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"s\"}},{\"abilityId\":12,\"accessMode\":\"ro\",\"code\":\"work_state\",\"description\":\"\",\"extensions\":{\"attribute\":\"640\"},\"name\":\"工作状态\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"auto\",\"manual\",\"idle\"]}},{\"abilityId\":13,\"accessMode\":\"rw\",\"code\":\"smart_weather\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"智能天气\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"sunny\",\"cloudy\",\"rainy\",\"snowy\"]}},{\"abilityId\":14,\"accessMode\":\"rw\",\"code\":\"switch_weather\",\"description\":\"\",\"extensions\":{\"attribute\":\"640\"},\"name\":\"智能天气\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":15,\"accessMode\":\"ro\",\"code\":\"use_time_one\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"单次使用时间\",\"typeSpec\":{\"type\":\"value\",\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"s\"}},{\"abilityId\":16,\"accessMode\":\"rw\",\"code\":\"cycle_timing\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"循环定时\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":17,\"accessMode\":\"rw\",\"code\":\"timer\",\"description\":\"可按要求自定义时间完成阀门开启/关闭、以及灌溉时间，可自定义多组，支持周循环、奇偶日、隔天循环定时。\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"定时\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}}]}]}"
  },
  "success": true,
  "t": 1715500401347,
  "tid": "b3c74b35103411ef9a8e62f092a4528b"
}

  "category": "sfkzq",
  "model": "SOP10",
  "name": "Water Timer",
  "product_id": "nxquc5lb",
  "product_name": "一出一水阀（网关+BLE)",
  
  
  This is for WG01: "category": "cz",
  
  {
  "result": {
    "model": "{\"modelId\":\"000003352e\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":38,\"accessMode\":\"rw\",\"code\":\"relay_status\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_battery\",\"attribute\":\"736\"},\"name\":\"上电状态设置\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"off\",\"on\",\"memory\"]}}]}]}"
  },
  "success": true,
  "t": 1715503806650,
  "tid": "a17fa8f6103c11ef9a8e62f092a4528b"
}

That's the only DPs reported:

{
  "result": {
    "properties": [
      {
        "code": "relay_status",
        "custom_name": "",
        "dp_id": 38,
        "time": 1715459251658,
        "value": "off"
      }
    ]
  },
  "success": true,
  "t": 1715503977633,
  "tid": "07753254103d11efa19236780218d147"
}

  "model": "WG01",
      "name": "Wi-Fi hub",
      "product_id": "yncyws7tu1q4cpsz",
      "product_name": "水阀网关",

**Comment by tomarigr** [comment]
Not planning to support this @make-all ?

**Comment by make-all** [comment]
It is not possible without logs

**Comment by tomarigr** [comment]
What logs do you need? How can I retrieve them? Happy to try stuff if needed.

**Comment by tomarigr** [comment]
Hi @make-all I found the problem! the UUID must be used as "sub-device ID" when setting up the device in tuya-local.

Steps:  
1) find the sub-device **UUID**  not the device_id from iot.tuya.com Query Device Details:
{
  "result": [
    {
...
      "category": "sfkzq",
      "create_time": 1715430250,
...
      "id": "DOESN'T_MATTER_USED_ONLY_FOR_CLOUD",
.....
      "model": "SOP10",
      "name": "Water Timer",
      "product_id": "nxquc5lb",
      "product_name": "一出一水阀（网关+BLE)",
      "sub": true,
      **"uuid": "THIS_IS_WHAT_YOU_NEED"**
    }
    
It works perfectly fine now! You are the best, I wish this was documented somewhere as I spent 2 days trying other stuff.

**Comment by make-all** [comment]
I didn't write the hub/subdevice support myself, so I may be misunderstanding it. My understanding is that the hub id should be used as the device id, and the cid is a separate id that only sub devices have, listed somewhere else in the device details.  Maybe the uuid for some sub-devices matches the cid, just as the device id matches the uuid for some (but not all) standalone devices.

**Comment by tomarigr** [comment]
no need to explain, I hope this makes it easier for other people to find the solution now. Perhaps an addition to the documentation encouraging people to try other ids would help too. I found out the hard way by playing with TinyTuya and desperately trying other stuff. 

Nevertheless, you just saved my roses garden as I am prepping for long summer holidays and didn't want to rely on the Chinese cloud to make sure it will keep them watered or not flood them. 

Thanks again for this great integration.
