### ISSUE TITLE
actually_start makes non-thread-safe calls to async_listen_once

### ISSUE THREAD

**Issue by bdraco** [make-all/tuya-local#1917]
https://github.com/make-all/tuya-local/blob/d0e1465574258e53d1519d67c5731a0abd224f8c/custom_components/tuya_local/device.py#L141

Because `actually_start` is not decorated with `@callback` Home Assistant will run it in the executor instead of the event loop. 
https://developers.home-assistant.io/docs/asyncio_categorizing_functions#the-callback-function

It looks like the intent was to have this function run in the event loop.  

If you decorate it with `@callback` you can safely call `async_create_task` in that function since it will run in the event loop

You may want to consider switching to `entry.async_create_background_task` (example: https://github.com/home-assistant/core/blob/b84829f70fcd8dfb73cbd9829cf962fc029f0d8e/homeassistant/components/homekit_controller/connection.py#L352)  since the task will automatically be cancelled when the config entry is unloaded.
https://github.com/home-assistant/core/blob/b84829f70fcd8dfb73cbd9829cf962fc029f0d8e/homeassistant/config_entries.py#L1133

**Comment by bdraco** [comment]
https://deploy-preview-2171--developers-home-assistant.netlify.app/docs/asyncio_thread_safety#ensuring-code-is-run-in-the-correct-thread might be helpful as well

**Comment by make-all** [comment]
> You may want to consider switching to entry.async_create_background_task

That is something I have considered recently, but the code is called from the `async_added_to_hass` callback, which does not get passed the entry.  Is there are generic way to get the entry when you are not in the `async_setup_entry` phase of setup?

**Comment by bdraco** [comment]
You'll have the pass the config entry to the entity when you create the object.

You can still use `hass.async_create_background_task` https://github.com/home-assistant/core/blob/2590db1b6dc253e4d80b3fada5b051512be1b21a/homeassistant/core.py#L843 in the mean time if you don't want to refactor. If you use that one instead of `entry.async_create_background_task`, you'll need to wrap it make sure the task is cancelled yourself when the entry is unloaded or the entity is removed.
