### ISSUE TITLE
Symbolic link loop

### ISSUE THREAD

**Issue by balronu** [make-all/tuya-local#1923]
Unable to parse /config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/custom_components/tuya_local/devices/awow_th213_thermostat.yaml: [Errno 40] Symbolic link loop:

**Comment by make-all** [comment]
I don't know what you have done to your installation, but it is not the integration that is causing this
