### ISSUE TITLE
Request support for PLD_DS01 - Tuya Bluetooth Smart Lock

### ISSUE THREAD

**Issue by FreemanJD** [make-all/tuya-local#1927]
# Log Message

```
Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:97
integration: Tuya Local ([documentation](https://github.com/make-all/tuya-local), [issues](https://github.com/make-all/tuya-local/issues))
First occurred: 3:45:02 PM (1 occurrences)
Last logged: 3:45:02 PM

Device matches None with quality of 0%. DPS: {"updated_at": 1715924699.7095335, "18": true, "28": "english", "31": "low", "33": false, "40": "closed", "46": true, "47": false, "48": "anticlockwise", "62": 256}
```

# Information about DPS mappings

{
  "result": {
    "properties": [
      {
        "code": "unlock_method_create",
        "custom_name": "",
        "dp_id": 1,
        "time": 1695941514682,
        "value": "Av8AAjMAAA=="
      },
      {
        "code": "unlock_method_delete",
        "custom_name": "",
        "dp_id": 2,
        "time": 1695450541756,
        "value": "AwABAWkB/w=="
      },
      {
        "code": "unlock_method_modify",
        "custom_name": "",
        "dp_id": 3,
        "time": 1695900992898
      },
      {
        "code": "bluetooth_unlock",
        "custom_name": "",
        "dp_id": 6,
        "time": 1697673846370,
        "value": "AQE="
      },
      {
        "code": "battery_state",
        "custom_name": "",
        "dp_id": 9,
        "time": 1695900992898,
        "value": "high"
      },
      {
        "code": "unlock_fingerprint",
        "custom_name": "",
        "dp_id": 12,
        "time": 1715815384000,
        "value": 100
      },
      {
        "code": "unlock_password",
        "custom_name": "",
        "dp_id": 13,
        "time": 1694392371000,
        "value": 0
      },
      {
        "code": "unlock_dynamic",
        "custom_name": "",
        "dp_id": 14,
        "time": 1693739541349,
        "value": 0
      },
      {
        "code": "unlock_card",
        "custom_name": "",
        "dp_id": 15,
        "time": 1707969563000,
        "value": 50
      },
      {
        "code": "unlock_key",
        "custom_name": "",
        "dp_id": 16,
        "time": 1693739541349,
        "value": 0
      },
      {
        "code": "open_inside",
        "custom_name": "",
        "dp_id": 18,
        "time": 1715900209000,
        "value": true
      },
      {
        "code": "unlock_ble",
        "custom_name": "",
        "dp_id": 19,
        "time": 1697673839000,
        "value": 1
      },
      {
        "code": "alarm_lock",
        "custom_name": "",
        "dp_id": 21,
        "time": 1715763861000,
        "value": "wrong_finger"
      },
      {
        "code": "language",
        "custom_name": "",
        "dp_id": 28,
        "time": 1715924612112,
        "value": "english"
      },
      {
        "code": "beep_volume",
        "custom_name": "",
        "dp_id": 31,
        "time": 1715924611986,
        "value": "low"
      },
      {
        "code": "reverse_lock",
        "custom_name": "",
        "dp_id": 32,
        "time": 1709077029872,
        "value": false
      },
      {
        "code": "automatic_lock",
        "custom_name": "",
        "dp_id": 33,
        "time": 1715924612191,
        "value": false
      },
      {
        "code": "auto_lock_time",
        "custom_name": "",
        "dp_id": 36,
        "time": 1715858257026,
        "value": 5
      },
      {
        "code": "closed_opened",
        "custom_name": "",
        "dp_id": 40,
        "time": 1715924611170,
        "value": "closed"
      },
      {
        "code": "manual_lock",
        "custom_name": "",
        "dp_id": 46,
        "time": 1715924610552,
        "value": true
      },
      {
        "code": "lock_motor_state",
        "custom_name": "",
        "dp_id": 47,
        "time": 1715924611168,
        "value": false
      },
      {
        "code": "lock_motor_direction",
        "custom_name": "",
        "dp_id": 48,
        "time": 1715924611723,
        "value": "anticlockwise"
      },
      {
        "code": "temporary_password_creat",
        "custom_name": "",
        "dp_id": 51,
        "time": 1695900992898
      },
      {
        "code": "temporary_password_delete",
        "custom_name": "",
        "dp_id": 52,
        "time": 1695900992898
      },
      {
        "code": "temporary_password_modify",
        "custom_name": "",
        "dp_id": 53,
        "time": 1695900992898
      },
      {
        "code": "synch_method",
        "custom_name": "",
        "dp_id": 54,
        "time": 1700374192276,
        "value": "AQE="
      },
      {
        "code": "unlock_temporary",
        "custom_name": "",
        "dp_id": 55,
        "time": 1693739541349,
        "value": 0
      },
      {
        "code": "remote_no_pd_setkey",
        "custom_name": "",
        "dp_id": 60,
        "time": 1715490088896,
        "value": "AAAB"
      },
      {
        "code": "remote_no_dp_key",
        "custom_name": "",
        "dp_id": 61,
        "time": 1715924035779,
        "value": "AAAB"
      },
      {
        "code": "unlock_phone_remote",
        "custom_name": "",
        "dp_id": 62,
        "time": 1715924030000,
        "value": 256
      },
      {
        "code": "unlock_voice_remote",
        "custom_name": "",
        "dp_id": 63,
        "time": 1715490082000,
        "value": 256
      },
      {
        "code": "password_offline_time",
        "custom_name": "",
        "dp_id": 64,
        "time": 1696158967042,
        "value": "1695900992"
      },
      {
        "code": "unlock_offline_clear_single",
        "custom_name": "",
        "dp_id": 65,
        "time": 1695900992898
      },
      {
        "code": "unlock_offline_clear",
        "custom_name": "",
        "dp_id": 66,
        "time": 1695900992898
      },
      {
        "code": "unlock_offline_pd",
        "custom_name": "",
        "dp_id": 67,
        "time": 1695900992898
      },
      {
        "code": "special_function",
        "custom_name": "",
        "dp_id": 68,
        "time": 1697673832302,
        "value": "function1"
      }
    ]
  },
  "success": true,
  "t": 1715925228647,
  "tid": "d48ecbed141111efbd94f222f50bf0b8"
}

# Product ID
      "model": "PLD_DS01",
      "name": "Smart Lock",
      "product_id": "omdezogp",
      "product_name": "Smart Lock",
      "catagory": "ms"
      "sub": true,

If support could be added for basic function of lock (lock/unlock, battery level) for my Tuya Bluetooth Lock that would be amazing. If you need anything further please let me know. Lock - (https://www.aliexpress.com/item/1005006585240792.html?spm=a2g0o.productlist.main.21.47f35ec2p3AdgJ&algo_pvid=fe19b443-aaed-400c-a8f9-249d96e05876&algo_exp_id=fe19b443-aaed-400c-a8f9-249d96e05876-10&pdp_npi=4%40dis%21AUD%21232.43%2163.85%21%21%211104.17%21303.32%21%402101d69a17159255370851823eeb97%2112000037734357591%21sea%21AU%210%21AB&curPageLogUid=Fq3Qh9QCTnLS&utparam-url=scene%3Asearch%7Cquery_from%3A)

**Comment by make-all** [comment]
There is not really enough info above to make a config.  Ranges (for integer dps) and valid values (for enum dps) are missing.

**Comment by FreemanJD** [comment]
Ok. That’s a shame. Is this something I could get for you ?

if not that’s fine just close the issue. I managed to get the lock integrated to home assistant (although I wish it was local and not dependant on two different cloud services ).

**Comment by make-all** [comment]
If you have access to the iot.tuya.com site, you can get the info from the QueryThingsDataModel API call, as suggested in the new issue template.  But if you don't have that access, it is more difficult. It would be nice to call from the integration itself now that we have cloud API support built in, but the tinytuya library does not expose that function in its cloud support.
