### ISSUE TITLE
Add New Device (Smart PowerStrip with USB ES-01)

### ISSUE THREAD

**Issue by KaportsevIA** [make-all/tuya-local#194]
Please Add New Device. Config YAML-file testing and full working.
All DPs Correct, timer's work.
[smart_strip_es01.yaml.txt](https://github.com/make-all/tuya-local/files/9089934/smart_strip_es01.yaml.txt)
![Снимок экрана 2022-07-12 085915](https://user-images.githubusercontent.com/98884453/178419568-baea79d2-9786-4ea3-9953-13ceb841e6dd.png)
![Снимок экрана 2022-07-12 085931](https://user-images.githubusercontent.com/98884453/178419572-69f5faf5-bb8c-42c7-b3c4-2522255681ea.png)
![Снимок экрана 2022-07-12 090003](https://user-images.githubusercontent.com/98884453/178419589-0898f814-5f62-41ea-aa79-880b5c61d40a.png)

Based on Woox R4028 PowerStrip.

**Comment by make-all** [comment]
This is included in the 0.18.0 release

**Comment by KaportsevIA** [comment]
Error:

Logger: custom_components.tuya_local
Source: custom_components/tuya_local/__init__.py:151
Integration: Tuya Local ([documentation](https://github.com/make-all/tuya-local), [issues](https://github.com/make-all/tuya-local/issues))
First occurred: 20:30:05 (2 occurrences)
Last logged: 20:37:26

Configuration file for smart_strip_es01 not found.

**Comment by make-all** [comment]
Sorry, you will need to delete and re add the device, since the name of the config file has changed.

**Comment by KaportsevIA** [comment]
Thanks. Confirmed - All Work - OK!!!
