### ISSUE TITLE
Request support for simple_shutoff_timer

### ISSUE THREAD

**Issue by Zylazy** [make-all/tuya-local#1979]
(https://www.aliexpress.com/item/33021320104.html?spm=a2g0o.order_list.order_list_main.59.b5351802px3oK1)

name: Simple shutoff with timer
products:
  - id: gbm9ata1zrzaez4a
    name: Water and Gas shutoff
primary_entity:
  entity: switch
  dps:
    - id: 1
      name: switch
      type: boolean
secondary_entities:
  - entity: number
    category: config
    name: Timer
    icon: "mdi:timer"
    dps:
      - id: 9
        name: value
        type: integer
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60

**Comment by Zylazy** [comment]
I have added this device locally to my tuya_local config and tested it since February without any issue.

**Comment by make-all** [comment]
This is already a match for simple_switch_timerv2, there is no need for another config just because of the naming.

**Comment by Zylazy** [comment]
I understand. Ok
But would you please add this to the products section in the simple_switch_timerv2.yaml ?

id: gbm9ata1zrzaez4a
name: Water and Gas shutoff
