### ISSUE TITLE
Possibility of Request for Orion Grid Connect Outdoor Siren?

### ISSUE THREAD

**Issue by jamiergrs** [make-all/tuya-local#198]
I'm wondering if it is possible to get support for the Orion grid connect outdoor siren, specifically ability to change the alarm_state. If you connect this device through the official tuya integration you only get ability to change volume and alarm time. Adding through this integration gives a device not supported message. 

Happy to provide any information / details as required

**Comment by make-all** [comment]
It may be possible, but I will need more information about the device.  Best is to send the local dps mapping which is output to the Home Assistant log as a warning message when you try to add it, and information from iot.tuya.com developer portal about the device attributes, specifically the info under Cloud / API_ Explorer / Device Control / the last "Get Device Specification Attribute" listed. Also, while you are in there, the product_id which you can get from General Devices Management / Get Device Information - but a lot of the information under there is private (local key, device id, latitude, longitude) so don't post it all.

**Comment by make-all** [comment]
Hi, that is not the correct Device Specificaton Atrribute, you need to use the last one listed under "Device Control", as that is the only function in the entire API that lists the dp_id field needed for local protocol use.

**Comment by make-all** [comment]
It looks like HomeAssistant has support for a siren platform, which supports setting volume, tone and duration.  So I guess that is where the limitation of the official cloud-based tuya integration support is coming from.

I don't currently have siren support, but it looks quite simple to add.  As this integration supports multiple entities per device, adding the alarm state to this will be a matter of adding a select entity (also sensors for the battery, charge state and tamper alarm - or is the tamper alarm another setting in the Tuya app?)

**Comment by make-all** [comment]
Actually it looks like the alarm state could be emulated as tones.  Maybe that would be better as it keeps everything in the standard alarm entity, so might work better in the UI.

**Comment by jamiergrs** [comment]
I think keeping it all together in the alarm entity would work better in the UI. 

As for the tamper alarm, that is simply a state in the app that is either true or false based on whether someone has opened the cover on the siren

**Comment by make-all** [comment]
This was released in the latest version. But I am not sure if I understood the way this device works correctly, so please feed back on how it is working compared to the Tuya app.

**Comment by zerocritical** [comment]
Hi,
Just got my hands on one of these sirens. It gets added to HA , battery, Charging status and Tamper Detection shows correctly but it doesnt trigger the alarm from HA. Please let me know what information you need, I can work with you to resolve the issue.
![image](https://user-images.githubusercontent.com/55267791/190295897-10a385a8-81b4-4dba-b62e-018f7863e295.png)

**Comment by zerocritical** [comment]
My guess is, 

to turn on, tone should be set to one of these - sound (for sound only), light (For light only) or sound+light (for both sound and light)

to turn off, tone should be set to normal

**Comment by make-all** [comment]
You should be able to test that, as the tone is exposed in the siren entity.  Unless there is a specific siren card, you may need to call a service from the developer console to test.

**Comment by make-all** [comment]
My interpretation of the available controls when writing the config was that the siren could only be triggered by a hardware input, which is supposed to connect to the alarm controller, and the settings available via the network were just for configuration.  But if the Tuya app is able to trigger the siren then there must be some way, and the presence of "normal" in the tone settings did raise some questions in my mind.

**Comment by zerocritical** [comment]
Yes, can trigger siren from the app. Here are the screenshots from the app:

when triggered:
![image](https://user-images.githubusercontent.com/55267791/190300744-0a1349d9-7323-4e40-8e00-fcf14e655721.png)


when disabled:
![image](https://user-images.githubusercontent.com/55267791/190300799-8a55ffd9-da3d-4bd7-af3d-566189257224.png)

**Comment by zerocritical** [comment]
The selling point of this siren is that it can be triggered using an event from another Tuya device.. like a door contact sensor. So it allows to trigger remotely from the app.

**Comment by make-all** [comment]
So to test, you should be able to go into Developer Tools, on the Services tab, and run the siren.turn_on service with a tone argument ("sound", "light" or "sound+light").  If that works, to turn it off, you may need to run the turn_on service again with a tone argument of "normal" rather than using the turn_off service.

**Comment by zerocritical** [comment]
Brilliant! It works!!

I was trying to trigger from services before but without specifying the tone! with tone, it works perfectly to trigger and disable. :)

**Comment by zerocritical** [comment]
By any chance would you be able to add sensors to edit volume and duration? Like this:

![image](https://user-images.githubusercontent.com/55267791/190304063-7492e5df-f93b-4f3d-9e90-5e342d25cdf5.png)

**Comment by make-all** [comment]
`volume` and `duration` are also set as parameters when calling the siren.turn_on service.  
The Home Assistant interface to [sirens ](https://www.home-assistant.io/integrations/siren/) only has the three services turn_on, turn_off and toggle, and nothing else.  I added the current settings as extra attributes so you can read them back, but that is not part of the standard interface.   Volume has a range between 0.0 and 1.0 per the HA interface, which will snap to the nearest value from 0.0=mute, 0.33=low, 0.67=middle, 1.0=high.  Duration has the same 1 - 10 range as the Tuya docs, which I think is in minutes.

In response to this report, I now know how to make this siren work, so in the next release, "normal" will disappear from the available tones list, and be replaced with a working turn_off.  turn_on without a tone argument and the toggle service will select sound by default.

**Comment by make-all** [comment]
The siren should now fully function in 0.19.0, including the turn_off and toggle service calls, and turn_on with or without arguments..

**Comment by make-all** [comment]
Note that 0.19.0 and 0.19.1 had some issues that might make it difficult to judge whether this is working correctly.  And I found a further problem after 0.19.2 which probably stops the turn_off command from functioning, so if you want to check it, please use the main development branch (can be installed from HACS by selecting "Redownload" from the tuya-local details page, main should be at the bottom of the list of versions available - it will nag you to upgrade after that, but you can ignore it until a later version than 0.19.2 is available).
