### ISSUE TITLE
Kettle Device Type Missing

### ISSUE THREAD

**Issue by voidnet-stack** [make-all/tuya-local#1985]
When adding my Weekett KE4071TF I don't see a matching device type. 
Maybe I'm doing something wrong? Not sure. It is supposedly supported and I've correctly followed the guidance to extract the devices local key so I'm at a loss as to how to resolve.

![image](https://github.com/make-all/tuya-local/assets/74432661/3ad72918-220c-4600-9d65-0f6bd6af33a8)

![image](https://github.com/make-all/tuya-local/assets/74432661/02b0970e-8eb1-418c-a361-6b4a1cdfd236)

**Comment by make-all** [comment]
This is not a Q&A discussion forum, including logs in your bug report is the bare minimum for the report to be useful.
