### ISSUE TITLE
Bresser Smart 7-in-1 weather station .. device not supported

### ISSUE THREAD

**Issue by hklages** [make-all/tuya-local#199]
Hi. I tried to add a Bresser weather station but got the message, that the device is not supported. 
Looking at your device list, there is a file "bresser_weather_station.yaml" what exactly looks like the device I want to add. 
The device id I did look up from the tuya developer account, the host and local key by installing the other local tuya integration and getting it from there. 

How does the matching works - with name, id? category? 

Here is the data from my "Bresser Smart 7-in-1 weather station": 

![bresser](https://user-images.githubusercontent.com/17273119/179389461-83dcc9ba-9538-475a-8104-f960849d8865.jpg)

**Comment by hklages** [comment]
we can close this. I use the other local tuya integration and add the entities I need.

**Comment by make-all** [comment]
The matching works by the dp ids returned by the device.  I understand that this device has a lot of optional sensors, so the current configuration is matching exactly the options that the original user who configured this had.  Probably it will take a few iterations to mark the options so that it will work with all possible combinations.

**Comment by myhomeiot** [comment]
@make-all Please add Bresser Smart 7-in-1 weather station into list of supported devices.

In Tuya it's lists as `Smart 7-in-1 weather station`, at Bresser web site it's called as [`BRESSER 7-in-1 ClimateConnect Tuya Smart Home Weather Centre`](https://www.bresser.de/en/Weather-Time/BRESSER-7-in-1-ClimateConnect-Tuya-Smart-Home-Weather-Centre.html) but actually it's only the base station (indoor module with display) which support Tuya protocol, the weather station itself (outdoor module) work with indoor module by RF 868 MHz and can be used with another indoor modules or even alone with [rtl_433](https://github.com/merbanan/rtl_433) and any compatible RTL-SDR hardware.
