### ISSUE TITLE
Configuration file for essentials_purifier not found

### ISSUE THREAD

**Issue by N1c093** [make-all/tuya-local#1990]
**Describe the bug**
Since the latest update I get the following error inside the log file: `2024-06-07 21:51:43.119 ERROR (MainThread) [custom_components.tuya_local] Configuration file for essentials_purifier not found ` Therefore I can't use my purifier with tuya-local anymore. I'm using this device :https://wesmartify.de/en/products/essentials-luftreiniger-viren-filterung-bis-zu-99-95-luftwascher-fur-allergiker-reinigt-raume-bis-zu-60-m2-lufterfrischer-mit-steuerung-per-app-farbe-weiss-mit-hepa13-filter

**To Reproduce**

- Have the purifier configured with an old version of  tuya-local
- Update tuya-local to the newest version
- See error in log

**Expected behavior**

- Device should be working with tuya-local

**Additional context**

I already tried to remove my tuya-local configuration. When I try to setup the device again, I get the following Error in the gui: "No unregistered devices could be found for the account."

**Comment by make-all** [comment]
There have been a few reports lately indicating missing files from the installation like this. I suspect maybe a bug in HACS where out is promoting to reboot too early, or just not completing the install for some reason. But the file is still there so it is not a bug in the integration.

**Comment by N1c093** [comment]
Thank you for your reply. I just copied the files manually and everything is running fine.
