### ISSUE TITLE
owon_pct513_thermostat does not work properly in Fahrenheit

### ISSUE THREAD

**Issue by r-t-s** [make-all/tuya-local#1996]
**Describe the bug**
The owon_pct513 thermostat does not work properly in US Units.
This probably ONLY worked in US Units in 2024.3.3. A change was made since then to support Metric.
It looks like the mappings to change the scale and step are not working as expected.

**To Reproduce**
Configure Home Assistant and thermostat with Metric units. Everything works as expected.
Configure Home Assistant and thermostat with US units. Initial display of thermostat reading is OK.
But can't change the setting because it is trying to scale the value between (approximately) 0 and 1.

**Expected behavior**
Should be able to set thermostat between 41 and 90 degF.

**Additional context**

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

Diagnostics from "Released" owon...yaml file:
[tuya_local-a983993ba13b031046de86a827d1517a-Bunk Room-c1f89c7b26cdbdd96016dc6ddb44ceef (2).json](https://github.com/user-attachments/files/15774727/tuya_local-a983993ba13b031046de86a827d1517a-Bunk.Room-c1f89c7b26cdbdd96016dc6ddb44ceef.2.json)

You can see from the diagnostic file the improper min and max values as well as the wrong step.

With my modified owon...yaml file: 
[owon_pct513_thermostat.yaml.txt](https://github.com/user-attachments/files/15774901/owon_pct513_thermostat.yaml.txt)

Diagnostics using MY attached owon...yaml file:
[tuya_local-a983993ba13b031046de86a827d1517a-Bunk Room-c1f89c7b26cdbdd96016dc6ddb44ceef (3).json](https://github.com/user-attachments/files/15775180/tuya_local-a983993ba13b031046de86a827d1517a-Bunk.Room-c1f89c7b26cdbdd96016dc6ddb44ceef.3.json)

The ramining problem is that the step is still 1/2 degF, in degF units it should be a step of 1 degF.
But the temperature is truncated to nearest 1 degF ... so it still works properly. But the user thinks they can specify 1/2 degF setting.

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.
Logs is as expected considering the incorrect min, max,  and step:

```
File "/config/custom_components/tuya_local/helpers/device_config.py", line 939, in get_values_to_set
raise ValueError(f"{self.name} ({value}) must be between {mn} and {mx}")
ValueError: temp_f (0.5) must be between 41.0 and 90.0
```

![OwonSetting](https://github.com/make-all/tuya-local/assets/11230849/14809d34-7493-44d4-ac78-8215978ef426)

**Comment by make-all** [comment]
I think commit 4e378216c3 should fix this

**Comment by r-t-s** [comment]
I tried this file with 2024.6.0 
The degF works. 
When I change to degC if I change the setpoint on HA, or change the mode, it does not work.
It looks like having a mapping inside a condition that sets step and scale is not working.
See the diagnostic file:
    
[tuya_local-a983993ba13b031046de86a827d1517a-Bunk Room-c1f89c7b26cdbdd96016dc6ddb44ceef (4).json](https://github.com/user-attachments/files/15780770/tuya_local-a983993ba13b031046de86a827d1517a-Bunk.Room-c1f89c7b26cdbdd96016dc6ddb44ceef.4.json)

On an unrelated issue I submitted a request to Tuya development:
   [Cloud Free Support](https://www.tuyaos.com/viewtopic.php?t=3332)
If that is something you support and can use your voice ... please pass it on.

**Comment by make-all** [comment]
Thank you for testing both cases here.

**Comment by make-all** [comment]
The scale and step needed to be directly in the condition.  owon was the only config with them nested like this, I seem to recall going through the configs some time ago fixing this problem, so probably this one was missed or was introduced later.
