### ISSUE TITLE
Brand New Install Error in log

### ISSUE THREAD

**Issue by botts7** [make-all/tuya-local#2]
Brand New Install Error in log

Any Ideas?

Error while setting up tuya_local platform for climate

  File "/config/custom_components/tuya_local/climate.py", line 62, in async_setup_entry

  File "/config/custom_components/tuya_local/climate.py", line 50, in async_setup_platform

**Comment by make-all** [comment]
What device are you trying to set up here?

**Comment by botts7** [comment]
A Kogan power monitoring plug. ???

**Comment by make-all** [comment]
You'll need to untick "Include device as a climate entity" for that, and tick "Include device as a switch entity" at the bottom.  the errors are coming from the climate entity because the device does not support it.

**Comment by botts7** [comment]
Thankyou. I was trying to set it up using yaml. The Integration worked. Just not getting the power monitoring. Will disconnect overnight and see how we go in the morning as per your suggestion.

Thanks Again!

**Comment by botts7** [comment]
I have the newer model Kogan Power monitor. I needed to change DP's as follows and is reporting all attributes now.

Model: KASPEMHUSBA

```yaml
from homeassistant.components.switch import ATTR_CURRENT_POWER_W

ATTR_SWITCH = "switch"
ATTR_TIMER = "timer"
ATTR_CURRENT_A = "current_a"
ATTR_VOLTAGE_V = "voltage_v"

PROPERTY_TO_DPS_ID = {
    ATTR_SWITCH: "1",
    ATTR_TIMER: "2",
    ATTR_CURRENT_A: "18",
    ATTR_CURRENT_POWER_W: "19",
    ATTR_VOLTAGE_V: "20",
}
```

**Comment by make-all** [comment]
Thanks for the info.  I see the string "USB" embedded in the model number, does this plug come with USB as well?  Could it be separately switchable?  Do you have the full list of DPS reported by the device?

**Comment by make-all** [comment]
I think the new version I released today should support this device out of the box.

**Comment by botts7** [comment]
> Thanks for the info. I see the string "USB" embedded in the model number, does this plug come with USB as well? Could it be separately switchable? Do you have the full list of DPS reported by the device?
> 
read out when off and no load
```yaml
'1' : false,
'9' : 0,
'18' : 0,
'19' : 0,
'20' : 2261,
'21' : 1,
'22' : 590,
'23' : 27459,
'24' : 15242,
'25' : 1368
```

read out when on and with load

```yaml
'1' : ftrue,
'9' : 0,
'18' : 5094,
'19' : 11198,
'20' : 2257,
'21' : 1,
'22' : 590,
'23' : 27459,
'24' : 15242,
'25' : 1368
```

**Comment by botts7** [comment]
> The other way to overcome the delays is to flash alternate firmware (Tasmota, ESPHome etc), where you can use your own MQTT server or direct connection to Home Assistant. But I don't know if the new devices are still ESP8266 devices, as Tuya seem to be switching some products to Realtek lately.

Yes they can be flashed, all mine run tasmota via tuya convert.  My old man has some and wants to keep them stock so I am doing this to set them up for him.
