### ISSUE TITLE
Kogan heater stopped working with tuya local

### ISSUE THREAD

**Issue by tsmanz** [make-all/tuya-local#20]
Thanks so much for the integration I have been using it for quite a while now for my 3 Kogan 2000W heaters with no problems up until now. One of the heaters is slightly older than the others and for some reason tuya local can no longer control it. The heater is still fully controllable via the Tuya Smart app and I can connect it to HA using the included Tuya integration but would much prefer tuya local. The product ID of the heater that stopped working with tuya local is "ynjanlglr4qa6dxf" if that helps. Please let me know if you need any additional info.

**Comment by make-all** [comment]
Did you re-pair it with the app?  The keys change every time the device is paired.  Otherwise it is a bit strange that one heater is affected but the other two are not.  I don't think a software update would have reconfigured the heater to be incompatible, but it may be possible I guess.  If anything is showing up in the Tuya logs it might shed some light on what the problem is if the problem is on the HA side. Otherwise it is likely the heater is not connecting at all, which would point to an incorrect key.

**Comment by make-all** [comment]
The productId helps with an idea I have to better identify devices in future, but unfortunately the Tuya developer portal just returns "Unauthorized" if I try to look up details for a product that isn't paired to my own account, so it doesn't help me get any further information about the device.

**Comment by make-all** [comment]
I also notice that if my heaters (not just Kogan, the Goldair one too) are unplugged for a while, Home Assistant needs restarting to pick it up again.  I think there might be some logic to stop polling devices when they have gone for an extended period.  Was your heater unplugged?  Have you tried restarting HA?

**Comment by tsmanz** [comment]
Thanks for your response, prior to the heater becomg unresponsive it had been working flawlessly for some time and hadn't been unplugged or turned off for weeks. Previously when it had been unplugged or turned off it reconnected no problem.

So far I've tried:
Unplugging the heater for 5 minutes.
Rebooting HA several times.
Uninstalling the integration completely from HACS and rebooting before reinstalling and adding the heater back.
Adding the heater with a different name.
Checking the key and ID are still the same via the tuya it dev portal (nothing has changed).
All of the above in various combinations.

I was able to added the newer heaters back with no issues so it seem to be specific to this version of the heater.

If it helps the heater current update details are:
Main Module: V3.1.2
MCU Module: V1.0.0

If there is any specific info I can give you that would I let me know.

I haven't tried removing the heater from the tuya smart app yet. I'll give that a go tomorrow to get a new key to see if it helps.

**Comment by make-all** [comment]
This is a more recent Main Module version than mine, which is V2.2.3 and says no updates are available, but mine is a 1500W model, and may be a generation older I guess.  Are the other two on the same software version?  If not, it is a possibility that they changed the dps mappings in an update for this heater (not something I would want to do to already shipped devices though).  But you say your other heaters are newer, it is unlikely they would change on an older model but leave the newer ones alone.

**Comment by make-all** [comment]
Possible relationshp here with #18

**Comment by tsmanz** [comment]
Mine also says no updates are available and I have automatic updates turned off. The other newer heaters are both V2.2.6 with no updates available either. I can add the problem heater using the "heater" option and climate entity in tuya local which gives me the ability to turn in on and off via HA but that doesn't give temperature control. When I change it to kogan_heater I noticed the temperature is in negative numbers and changes in HA don't turn the heater on or off or adjust temp.

**Comment by make-all** [comment]
So it seems the DPS assignments are different.  Can you see anything mentioning DPS in the HomeAssistant log?  Negative temperatures are a bit strange though, I have never seen any device return negative numbers, and I wonder what it is actually reporting that is negative.

**Comment by tsmanz** [comment]
Looks like I spoke too soon regarding the newer heaters still working, all heaters have stopped responding with the oldest one showing as unavailable. Have tried uninstalling, re-pairing rebooting etc with no luck. At this stage I think I might cut my losses since the HA tuya integration is working. Might come back to it when I have more time to fiddle with the setup.

**Comment by make-all** [comment]
Another user has reported the DPS layout of a newer model of Kogan heater, which is rearranged from the older layout. It is possible that your heaters have received a firmware upgrade that swapped to the new layout.

You can test this out in the "main" branch by selecting "Reinstall" from the menu of the Tuya Local integration in HACS.  On the reinstall menu, select "main" as the version to install from the bottom of the list.

The next release will have this config, so you can also wait until then, but I will be busy over the next week, so may not be able to make a release soon.

**Comment by tsmanz** [comment]
Wow thanks so much for following up, I reinstalled using "main" as you suggested and everything is working perfectly for all heaters. Absolute legend, cheers!
