### ISSUE TITLE
Vacuum E30 more functions possible?

### ISSUE THREAD

**Issue by SvenMartin81** [make-all/tuya-local#200]
Hello together:

I have read this thread and I was very happy to see this because I am using the vacuum and had no Idear to integrate this into Homeassistant without cloud. 
https://github.com/make-all/tuya-local/issues/124

But I would like to work a little bit on it....
1) is there any possibility to get the manual function?
2) to change the "mode"? 
3) or to get the movement to see? 

This is possible in the tuya smart live app.

**Comment by SvenMartin81** [comment]
in the actual version is in the "kyvol_e30_vacuum.yaml" a mistake: it has to be "**mdi:**arrow-expand-all" and it is written "mdi-arrow-expand-all"

  - entity: sensor
    name: Edge Brush
    category: diagnostic
    icon: "mdi-arrow-expand-all"
    dps:
      - id: 7
        type: integer
        name: sensor
        unit: "%"

**Comment by make-all** [comment]
For 1 and 2, you can use the Vacuum Send Command service to send any of the manual directions or modes to the vacuum.  If you use a custom card such as https://github.com/denysdovhan/vacuum-card for the vacuum, it will automatically add some of the commands to the card.  Currently the map is not available, on my Lefant vacuum, I notice that the clean_record is actually an id (starting with the date stamp) which I guess can be used with the cloud service somehow to get an image, but I don't know exactly how.  There is also some other attributes that change during operation, I have figured out that one of them has  range of 0 - 359 and seems to indicate the direction, and I guess the other might be indicating distance somehow but currently the poll rate is too slow to pick up all the changes and probably only the cloud has access to the data pushed by the vacuum at correct timing to turn this into a map.

Thank you for pointing out the error in the icon name. I will fix that.

**Comment by SvenMartin81** [comment]
perfect. I did not think about this option....So I will try with the vacuum send command....do you have a sample config?

**Comment by make-all** [comment]
There are no params for any of the commands, so just entity_id and command need to be given.

Supported commands for E30 are standby, random, smart, wall_follow, mop, clean_spot, left_spiral, right_spiral, bow, left_bow, right_bow, partial_bow, return_to_base, single, zone, pose, point, part, pick_zone, forward, reverse, left, right, stop

**Comment by SvenMartin81** [comment]
do you know which kind of errors can be?....there is nothing in the List of the DP's written....

**Comment by make-all** [comment]
No, the error attribute is not mentioned in the docs at iot.tuya.com for this model.
It is possible that the values are the same as Lefant, but even for that, the config is based on an assumption that the list from iot.tuya.com is in order, matching the bits from lowest bit first.

**Comment by SvenMartin81** [comment]
Ok, I will try some faules. The First I had already. „Left_wheel“

**Comment by SvenMartin81** [comment]
Hey....i saw in your E30 file alle the faults:
        - dps_val: 1
          value: edge_sweep
        - dps_val: 2
          value: middle_sweep
        - dps_val: 4
          value: left_wheel
        - dps_val: 8
          value: right_wheel
        - dps_val: 16
          value: garbage_box
        - dps_val: 32
          value: land_check
        - dps_val: 64
          value: collision

**Comment by make-all** [comment]
If you have any way of checking them, it might be useful to get some feedback on whether the mapping of errors is correct.
