### ISSUE TITLE
fault vacuum

### ISSUE THREAD

**Issue by SvenMartin81** [make-all/tuya-local#201]
hi,
after I updated the tuyalocal integration, yesterday, I got this fault, today: What could this be?

Logger: homeassistant.config_entries
Source: custom_components/tuya_local/helpers/device_config.py:105
Integration: Tuya Local (documentation, issues)
First occurred: 07:28:13 (1 occurrences)
Last logged: 07:28:13

Error setting up entry Kevin-Chantal for tuya_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tuya_local/__init__.py", line 155, in async_setup_entry
    e = device_conf.primary_entity
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 105, in primary_entity
    return TuyaEntityConfig(self, self._config["primary_entity"], primary=True)
KeyError: 'primary_entity'

**Comment by make-all** [comment]
Kevin-Chantal is not coming from this integration.  If it is a change you made to the name of one of your devices, I think `-` should not be used in ids, it should be changed to an underscore `_`.
Or if it is a custom config you have made locally, based on the message I would say it is missing a `primary_entity`, but possibly also just the naming problem.

**Comment by SvenMartin81** [comment]
this is the name of my vacuum...i installed your tuyalocal 0.17.1 and all is fine....
