### ISSUE TITLE
New device - Universal Remote Control

### ISSUE THREAD

**Issue by Der-Nax** [make-all/tuya-local#203]
I added new device:

`name: Universal Remote Control
products:
  - id: whs3cty93fzrqkpt
primary_entity:
  entity: sensor
  dps:
    - id: 101
      name: sensor
      type: integer
      unit: C
      range:
        min: 0
        max: 80
      mapping:
        - scale: 10
secondary_entities:
  - entity: sensor
    class: humidity
    name: Humidity
    dps:
      - id: 102
        type: integer
        name: sensor
        unit: "%"
        class: measurement
        readonly: true`

**Comment by Der-Nax** [comment]
[smartuniversalremoutecontrol.zip](https://github.com/make-all/tuya-local/files/9144765/smartuniversalremoutecontrol.zip)

**Comment by Der-Nax** [comment]
Please add it in a new release.

There is additional functionality - subdevice. Do you have plans to support subdevices?

Information about subdevice:
{
  "result": {
    "active_time": xxx,
    "category": "infrared_ac",
    "category_name": "Infrared air conditioner",
    "create_time": xxx,
    "gateway_id": "xxx",
    "icon": "smart/icon/001453365846342fhj9e/11c62df7bd89c10f43d3e5ee8d13b4f4.png",
    "id": "xxx",
    "ip": "",
    "lat": "xxx",
    "local_key": "xxx",
    "lon": "xxx",
    "model": "",
    "name": "XXX",
    "node_id": "xxx",
    "online": true,
    "owner_id": "xxx",
    "product_id": "qzktzhehinzsz2je",
    "product_name": "Air Conditioning",
    "sub": true,
    "time_zone": "xx",
    "update_time": xxx,
    "uuid": "xxx"
  },
  "success": true,
  "t": XXX,
  "tid": "XXX"
}

{
  "result": {
    "category": "infrared_ac",
    "functions": [
      {
        "code": "F",
        "type": "ENUM",
        "values": "{\"min\":0,\"max\":3,\"scale\":0,\"step\":1,\"type\":\"Integer\"}"
      },
      {
        "code": "M",
        "type": "ENUM",
        "values": "{\"min\":0,\"max\":4,\"scale\":0,\"step\":1,\"type\":\"Integer\"}"
      },
      {
        "code": "PowerOff",
        "type": "STRING",
        "values": "PowerOff"
      },
      {
        "code": "PowerOn",
        "type": "STRING",
        "values": "PowerOn"
      },
      {
        "code": "T",
        "type": "ENUM",
        "values": "{\"min\":16,\"max\":30,\"scale\":0,\"step\":1,\"type\":\"Integer\"}"
      }
    ],
    "status": [
      {
        "code": "wind",
        "type": "ENUM",
        "values": "{\"min\":0,\"max\":3,\"scale\":0,\"step\":1,\"type\":\"Integer\"}"
      },
      {
        "code": "mode",
        "type": "ENUM",
        "values": "{\"min\":0,\"max\":4,\"scale\":0,\"step\":1,\"type\":\"Integer\"}"
      },
      {
        "code": "power",
        "type": "BOOLEAN",
        "values": "{}"
      },
      {
        "code": "temp",
        "type": "ENUM",
        "values": "{\"min\":16,\"max\":30,\"scale\":0,\"step\":1,\"type\":\"Integer\"}"
      }
    ]
  },
  "success": true,
  "t": XXX,
  "tid": "XXX"
}

**Comment by make-all** [comment]
Currently subdevices are not handled by the underlying tinytuya library, but when they are I would like to add support (as requested previously in #70, and required for #170 as well as this device).  However I think IR blasters are different in that they do not return any data, only allow commands to be sent, so further changes are also needed to enable that, since current support assumes a simple mapping to data points that can always be read, and some can be also set (previously rejected in #120 as it deviates too much from the current feature set, but maybe one day...).

**Comment by Der-Nax** [comment]
Could you add basik device in next realese? It work as temperature and humidity sensor.

**Comment by make-all** [comment]
This is exactly what the commit above is for - just the two sensors.

**Comment by Der-Nax** [comment]
I updated integration. But device was not working. I will need to add my files to device folder.
I have not time to undestand the problem. Sorry.
Could you please provide name of file which you add? I'll try to check.

**Comment by make-all** [comment]
Although this issue contains tuya portal info for a sub device, local info is missing, so this issue will be closed when the general subdevice support is added without implementing that specific device.

**Comment by stijnb1234** [comment]
@make-all How to know which codes / commands to send (what to use for the command field)?

**Comment by make-all** [comment]
You can use the `remote.learn_command` service to learn the commands and they will be filed against a subdevice and command name that you specify. The send command will then use the same  details.  Otherwise you need to send raw codes prefixed with b64: but the way Tuya represents their codes is different than broadlink and others, so you'll need a Tuya specific source for those codes.

**Comment by christianzappa** [comment]
@make-all I have managed to work out how to learn and I can see the codes in the file outputted in .storage but how do I now send these! Sorry for the dumb question, I'm a noob to IR part of HA.

**Comment by make-all** [comment]
Use the `remote.send_command` service with the same device and command that you recorded the remote code against.

**Comment by christianzappa** [comment]
> Use the `remote.send_command` service with the same device and command that you recorded the remote code against.

Gotcha. I worked it out in the end.

By my device is a S06Pro WR3E, seems to be working nicely

**Comment by ricrdv** [comment]
Hi @make-all 

Just found this, I'm kinda new to HASS and all, Can you give me a quick overview on how to get this going?

**Comment by Onepamopa** [comment]
S06Pro - are sub-devices supported?
I've setup TV and STB in the tuya app, and when I'm trying to add the device - I can select them, but cannot add them for some reason?

<img width="488" height="497" alt="Image" src="https://github.com/user-attachments/assets/9c2bd9ab-f3ca-41b1-85d9-ac338976754c" />

<img width="593" height="421" alt="Image" src="https://github.com/user-attachments/assets/b3de9551-428a-460b-8d05-72e99e93b7bd" />

<img width="597" height="729" alt="Image" src="https://github.com/user-attachments/assets/ec6c5f15-1973-49a1-a2ae-5536544f6227" />

With poll only - same thing.
With version: 3.1, 3.2, 3.22, 3.4, 3.5, auto - same thing.

I added the remote itself (without sub-device node id) as ir_remote_sensors (there were also s11_rfir_remote / basic_rf_remote) - it's the only one that gave me the temp and humidity sensors.

**Comment by make-all** [comment]
IR subdevices seem to be cloud only. They appear in the cloud config flow, but as you observed, since they are not real devices they cannot be "connected" to locally. The only way to use an IR hub locally is as a remote entity, and using any sensors it has directly.
