### ISSUE TITLE
Door Lock is read-only however "Lockdown" will lock but not unlock

### ISSUE THREAD

**Issue by vulcan4d** [make-all/tuya-local#2059]
**Describe the bug**
1. HA entity under "Controls" shows the current status of the lock (lock or unlock) however when pressing the button you get the following error: "Failed to call service lock/lock. lock is read only"
2. Another HA entity exists under "Configuration" called "Lockdown" which too has an unlock or lock option.  If you press it, the door lock will actually work however it will ONLY lock regardless if the status says lock or unlocked.

**To Reproduce**
Simply pressing the button for the entity "Door Lock" and "Lockdown"

**Expected behavior**
The door would lock or unlock properly

**Additional context**
1. Door Lock is made by SMONET
2. Uses the TUYA Wifi/BLE BT03 gateway 
3. Used the auto-detect settings from the Smart Life app or setting it up manually getting information from the Tuya Developer Platform
4. Smark Lock Product ID is g7rboh0x and Gateway is yy2bmcoh (according to the Tuya Developer Platform)

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"
[tuya_local-ed64eefa7f9328b0bf4e9868c6058ace-Door lock-ae93909733a30e29e58e481f9da8c4df.json](https://github.com/user-attachments/files/16006862/tuya_local-ed64eefa7f9328b0bf4e9868c6058ace-Door.lock-ae93909733a30e29e58e481f9da8c4df.json)

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.
[home-assistant_2024-06-27T02-04-28.793Z.log](https://github.com/user-attachments/files/16006911/home-assistant_2024-06-27T02-04-28.793Z.log)

![HA screenshot](https://github.com/make-all/tuya-local/assets/25832698/dc6706ee-49a4-461e-bb36-0eb0d3dfa83b)

**Comment by make-all** [comment]
It is normal for security locks to not have a simple remote unlock method.  Current config is according to the documentation received.  Lockdown appears to be for manually forcing a lockdown, but "unlocking" the lockdown is not expected to unlock the lock, just to stop forcing it to remain locked.  The dp used to indicate the status of the lock is actually read-only, so cannot be used to unlock either.

**Comment by s0ftice** [comment]
I successfully got this working.

My Tuya door lock, a BLE sub-device, was detected by Tuya Local as a "Gainsborough Liberty Smart Entrance Lock" (among several options, this was the closest match), even though it’s from a different vendor and model. Fortunately, most entities were correctly populated.

To investigate the device’s properties, I accessed Tuya IoT Platform → Device Control → Query Properties and looked up the device_id. I found the code `bluetooth_unlock` associated with `dp_id`: 6. Using Device Debugging, I managed to remotely unlock the door by sending the same string (masked as xxxx below) found in the logs via the JSON_EDITOR under Control Device with DP Instruction:

```
[
  {
    "code": "bluetooth_unlock",
    "value": "xxxx"
  }
]
```

To integrate this with Home Assistant (HA) via Tuya Local, I manually added an entry in `devices/gainsboroughliberty_entrance_lock.yaml`:

```
  - entity: lock
    name: Magic
    icon: "mdi:lock"
    dps:
      - id: 6
        type: string 
        name: lock
        mapping:
          - dps_val: "xxxx"
            value: true

```

This setup works well. I have now blocked my Tuya BLE/Wi-Fi Gateway from accessing the Internet, as I only want remote unlocks triggered through Home Assistant. Additionally, I disabled "Remote Unlock" in the Tuya Smart App.

However, modifying `gainsboroughliberty_entrance_lock.yaml` is not a long-term solution, as it won’t survive future updates. My next step is to write a proper device YAML for my specific lock and submit a PR.

**Comment by barban-dev** [comment]
> I successfully got this working.
[,,,]
> To investigate the device’s properties, I accessed Tuya IoT Platform → Device Control → Query Properties and looked up the device_id. I found the code `bluetooth_unlock` associated with `dp_id`: 6. Using Device Debugging, I managed to remotely unlock the door by sending the same string (masked as xxxx below) found in the logs via the JSON_EDITOR under Control Device with DP Instruction:

Owner of MOES R2 Smart Lock here (Product Category: jtmspro) . I can confirm that the key to remote unlock the device can be found via device debugging on Tuya IoT platform. In my case, this is the key to use with `dp_id`:61 ("remote_no_dp_key"),

**Comment by titeet** [comment]
> I successfully got this working.
> 
> My Tuya door lock, a BLE sub-device, was detected by Tuya Local as a "Gainsborough Liberty Smart Entrance Lock" (among several options, this was the closest match), even though it’s from a different vendor and model. Fortunately, most entities were correctly populated.
> 
> To investigate the device’s properties, I accessed Tuya IoT Platform → Device Control → Query Properties and looked up the device_id. I found the code `bluetooth_unlock` associated with `dp_id`: 6. Using Device Debugging, I managed to remotely unlock the door by sending the same string (masked as xxxx below) found in the logs via the JSON_EDITOR under Control Device with DP Instruction:
> 
> ```
> [
>   {
>     "code": "bluetooth_unlock",
>     "value": "xxxx"
>   }
> ]
> ```
> 
> To integrate this with Home Assistant (HA) via Tuya Local, I manually added an entry in `devices/gainsboroughliberty_entrance_lock.yaml` and simply reloaded the integration:
> 
> ```
>   - entity: lock
>     name: Magic
>     icon: "mdi:lock"
>     dps:
>       - id: 6
>         type: string 
>         name: lock
>         mapping:
>           - dps_val: "xxxx"
>             value: true
> ```
> 
> This setup works well. I have now blocked my Tuya BLE/Wi-Fi Gateway from accessing the Internet, as I only want remote unlocks triggered through Home Assistant. Additionally, I disabled "Remote Unlock" in the Tuya Smart App. EDIT: turned out blocking Internet Access for the gateway prevents Tuya Local from triggering unlocks. This should not be the case and I will further investigate.
> 
> However, modifying `gainsboroughliberty_entrance_lock.yaml` is not a long-term solution, as it won’t survive future updates. My next step is to write a proper device YAML for my specific lock and submit a PR.

Hi,

Can you help me to control my wifi tuya smart lock, in home assistant showing controllable but i can't unlock or lock unless someone ring the bell. 

Is there a way to unlock without ring the bell

**Comment by make-all** [comment]
DUplicate of #1921
