### ISSUE TITLE
New device - 4 socket powerstrip

### ISSUE THREAD

**Issue by vnkorol** [make-all/tuya-local#206]
{
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "switch_1",
        "desc": "{}",
        "name": "开关1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_2",
        "desc": "{}",
        "name": "开关2",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_3",
        "desc": "{}",
        "name": "开关3",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_4",
        "desc": "{}",
        "name": "开关4",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "relay_status",
        "desc": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}",
        "name": "上电状态",
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "name": "开关1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_2",
        "name": "开关2",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_3",
        "name": "开关3",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_4",
        "name": "开关4",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "relay_status",
        "name": "上电状态",
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "add_ele",
        "name": "增加电量",
        "type": "Integer",
        "values": "{\"unit\":\"度\",\"min\":0,\"max\":50000,\"scale\":3,\"step\":100}"
      },
      {
        "code": "cur_current",
        "name": "当前电流",
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_power",
        "name": "当前功率",
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":0,\"max\":50000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_voltage",
        "name": "当前电压",
        "type": "Integer",
        "values": "{\"unit\":\"V\",\"min\":0,\"max\":2500,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1658393356236,
  "tid": "007048b808d211edbc333a18cbe6d689"
}

**Comment by make-all** [comment]
Please find the API call in iot.tuya.com that reports dp_id. It is the last function in the second to last category. I don't have it in front of me now, so I can't remember the exact names 
Also, or if you can't find that, this might be enough on its own, there should be a message in the Home Assistant log when you try to add the device telling the actual data returned from the device. Sometimes the iot.tuya.com info is wrong, and almost always it is missing something, so this is always useful.

**Comment by vnkorol** [comment]
is it?

{
  "result": {
    "active_time": 1658391464,
    "category": "cz",
    "category_name": "Socket",
    "create_time": 1658391464,
    "gateway_id": "",
    "icon": "smart/icon/1531222310rcqusncie3f_0.png",
    "id": "23322207807d3a2ddd97",
    "ip": "178.35.152.63",
    "lat": "50.9775",
    "local_key": "=deleted=",
    "lon": "44.7802",
    "model": "WP30",
    "name": "Детская удлиннитель",
    "online": true,
    "owner_id": "28174593",
    "product_id": "7hBwPPNdDP1xHrWv",
    "product_name": "Power Monitoring Strip",
    "sub": false,
    "time_zone": "+03:00",
    "update_time": 1658391504,
    "uuid": "23322207807d3a2ddd97"
  },
  "success": true,
  "t": 1658396117264,
  "tid": "6e24a04e08d811eda4f3322e56e3d437"
}

**Comment by OmegaKill** [comment]
It should be there:
![image](https://user-images.githubusercontent.com/17964130/180213997-0fc89523-cfe9-4069-90be-aba55ea2ee88.png)

**Comment by make-all** [comment]
The highlighted one is correct, but the output is usually more like the first output you gave, with additional dp_id fields reported.  The second set of data is useful for the product_id, but contains quite a lot else that is specific to your device and potentially useful to hackers and stalkers, I think that normally comes from one of the functions under General Devices Management (but there is so much duplication in the tuya cloud api that it could be accessible from elsewhere also).

**Comment by vnkorol** [comment]
I have tried all of menus, but dp_id was found nowhere :(

**Comment by make-all** [comment]
OK. If you can get the HomeAssistant log message from when you try to add the device, probably I can match the above up with what is being returned.  Powerstrips are usually quite simple - there will be booleans corresponding to the switches, the same number of integers corresponding to timers for each switch, and if it supports power monitoring, 3 or 4 integers corresponding to current, voltage, power and maybe energy.

**Comment by vnkorol** [comment]
I've connected device as simple switch.

2022-07-21 18:27:02 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches qoto_03_sprinkler with quality of 42%. DPS: {'1': False, '2': False, '3': False, '4': False, '102': 0, '103': 0, '104': 2240, '105': 1, '106': 1709, '107': 34620, '108': 101000, '109': 205, 'updated_at': 1658417221.9443605}
2022-07-21 18:27:02 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/

**Comment by vnkorol** [comment]
And if it will be usesul, such powerstrip i've set up at local tuya integration:
DP 1-4 - SWITCH1-4
DP 104 - voltage scaling 0.1
DP 102 - current scalling 0.001
DP 103 - power scalling 0.1

**Comment by make-all** [comment]
Available in 0.18.1

**Comment by vnkorol** [comment]
Thank you very much! It works perfectly!
