### ISSUE TITLE
New Device - A/C

### ISSUE THREAD

**Issue by OmegaKill** [make-all/tuya-local#207]
{
  "result": {
    "category": "kt",
    "functions": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "dp_id": 5,
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"cold\",\"hot\",\"wet\",\"wind\"]}"
      },
      {
        "code": "temp_set",
        "dp_id": 6,
        "type": "Integer",
        "values": "{\"min\":13,\"scale\":0,\"unit\":\"℃\",\"max\":32,\"step\":1}"
      },
      {
        "code": "windspeed",
        "dp_id": 8,
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\"]}"
      },
      {
        "code": "c_f",
        "type": "Enum",
        "values": "{\"range\":[\"C\",\"F\"]}"
      },
      {
        "code": "temp_set_f",
        "dp_id": 18,
        "type": "Integer",
        "values": "{\"min\":55,\"scale\":0,\"unit\":\"℉\",\"max\":90,\"step\":1}\t"
      }
    ],
    "status": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "dp_id": 5,
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"cold\",\"hot\",\"wet\",\"wind\"]}"
      },
      {
        "code": "temp_set",
        "dp_id": 6,
        "type": "Integer",
        "values": "{\"min\":13,\"scale\":0,\"unit\":\"℃\",\"max\":32,\"step\":1}"
      },
      {
        "code": "windspeed",
        "dp_id": 8,
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\"]}"
      },
      {
        "code": "c_f",
        "dp_id": 10,
        "type": "Enum",
        "values": "{\"range\":[\"C\",\"F\"]}"
      },
      {
        "code": "temp_set_f",
        "dp_id": 18,
        "type": "Integer",
        "values": "{\"min\":55,\"scale\":0,\"unit\":\"℉\",\"max\":90,\"step\":1}\t"
      }
    ]
  },
  "success": true,
  "t": 1658406587154,
  "tid": "ceaf884008f011eda4f3322e56e3d437"

Home Assistant wrote the following in the logs:

Device matches kogan_glass_1_7l_kettle with quality of 17%. DPS: {'1': False, '4': 0, '5': '4', '6': 24, '8': '0', '10': False, '13': 0, '14': 0, '15': 0, '16': True, '17': False, '19': False, 'updated_at': 1658406144.9907923}

but its not a kettle.

If you need anything else please tell me.

Thanks

**Comment by make-all** [comment]
Some information about brand and model would help users to identify it when setting up.

**Comment by OmegaKill** [comment]
The Device is called BE COOL BC14KL2101F
It's 14.000 BTU / 1.65kW
[https://www.hornbach.at/mvc/article/article-detail/articleCode/10394240](url)
The site is in german

**Comment by make-all** [comment]
Available in 0.18.1

**Comment by OmegaKill** [comment]
I tried it just now and it works like a charm.
Thank you very much!

**Comment by OmegaKill** [comment]
So i tried it and in response but some functions are seemingly mapped wrong.

Drying in HomeAssistant is cooling on the machine
Cooling is Fan only
heating is drying
fan only is fan only that works

**Comment by make-all** [comment]
Remapped modes are released in 0.18.2

**Comment by OmegaKill** [comment]
I tested it and everything seems to work now as expected
Thanks
