### ISSUE TITLE
Tuya WiFi TM616EGWT Intelligent curtain motor offline from Homeassistant

### ISSUE THREAD

**Issue by wqrwefdgfv** [make-all/tuya-local#2073]
Home Assistant Core 2024.6.4
Supervisor 2024.06.2
Operating System 12.4
UI 20240610.1
Tuya Local 2024.6.0

Tuya WiFi TM616EGWT Intelligent curtain motor goes offline from Home Assistant. 
Rebooting the integration or Home Assistant does not help. 
Same time on native android app Tuya Smart all is ok. Motor is online on app. 
Only a power reset helps to connect to Home Assistant.
I try even other integration and forks but problem the same - after some time motor becames offline from Home Assistant.

**Comment by make-all** [comment]
If other integrations are the same, then it is unlikely to be a bug in this integration.
