### ISSUE TITLE
All devices integration stopped

### ISSUE THREAD

**Issue by sumakos** [make-all/tuya-local#2074]
All devices integration stopped, I checked logs and I see the next information.

LOG:
source file: custom_components/tuya_local/device.py:80

ERROR:
<class 'RuntimeError'>: Caught blocking call to sleep with args (0.1,) inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/device.py, line 77: self._api = tinytuya.Device(dev_id, address, local_key). (offender: /usr/local/lib/python3.12/site-packages/tinytuya/core.py, line 944: time.sleep(0.1)), please create a bug report at https://github.com/make-all/tuya-local/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#sleep while initialising device bfce5f97ac29f4e6f6frso

I checked the configuration and everything seems good.

**Comment by make-all** [comment]
Seems to be a duplicate of old issue #1869.  The line numbers from your log do not align with the current source, so I assume you are using an old version with current HA.
