### ISSUE TITLE
Gainsborough Liberty Smart Entrance Lock: error "Failed to call service lock/unlock. lock is read only"

### ISSUE THREAD

**Issue by grantleyring** [make-all/tuya-local#2085]
Lock/Unlock switch fails to operate the lock, with the message returned as: "Failed to call service lock/unlock. lock is read only"

**Describe the bug**
From Home Assistent devices and services screeen using the Tuya Local Integration, the lock/unlock entity does not operate the lock.

**To Reproduce**
Steps to reproduce the behavior including the device the issue was observed with:
Click the lock/unlock entity on tuya local integration - error appears  "Failed to call service lock/unlock. lock is read only"

**Expected behavior**

when operating the lock/unlock entity the lock should operate

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

[tuya_local-1b8a3eb3fd98245c29bf4a84816b35ca-Side Door Lock-80c6a23ad5e31f5001e8c95ca04e76de.json](https://github.com/user-attachments/files/16119395/tuya_local-1b8a3eb3fd98245c29bf4a84816b35ca-Side.Door.Lock-80c6a23ad5e31f5001e8c95ca04e76de.json)

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 22:35:20 (1 occurrences)
Last logged: 22:35:20

Detected blocking call to open with args ('/config/custom_components/tuya_local/devices/gainsboroughliberty_entrance_lock.yaml',) inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/helpers/device_config.py, line 101: self._config = load_yaml(filename) (offender: /usr/src/homeassistant/homeassistant/util/yaml/loader.py, line 226: with open(fname, encoding="utf-8") as conf_file:), please create a bug report at https://github.com/make-all/tuya-local/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request resp = await request_handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle resp = await handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware response = await handler(request) File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle result = await handler(request, **request.match_info) File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin return await func(self, request, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 262, in post return await super().post(request) File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper return await method(view, request, data, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 77, in post return await self._post_impl(request, data) File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl result = await self._flow_mgr.async_init( File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 343, in async_init result = await self._async_handle_step(flow, flow.init_step, data) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 518, in _async_handle_step result: _FlowResultT = await getattr(flow, method)(user_input) File "/config/custom_components/tuya_local/config_flow.py", line 548, in async_step_init return await self.async_step_user(user_input) File "/config/custom_components/tuya_local/config_flow.py", line 581, in async_step_user cfg = get_config(config[CONF_TYPE]) File "/config/custom_components/tuya_local/helpers/device_config.py", line 998, in get_config return TuyaDeviceConfig(fname) File "/config/custom_components/tuya_local/helpers/device_config.py", line 101, in __init__ self._config = load_yaml(filename)

**Comment by make-all** [comment]
The dp was marked as read only in the info from Tuya,

I don't think this lock is designed to be remotely unlocked as simply as a switch.

**Comment by grantleyring** [comment]
Hi Jason,
Thanks for responding so quickly.
The work around I have been using (a bit dodgy) is using google home SDK to lock and unlock (via HA script), so it must be able to be done remotely if it supports google?

or is there a better solution?
Regards,
Grant.

**Comment by make-all** [comment]
Based on the info from #1536, all the controls that could be understood from their description were implemented, but some descriptions did not match the dp name, so there may be some misunderstanding. If that is the case, then maybe one of the other switches or locks attached to the device will work as a remote lock/unlock.  On some other devices the "Auto lock" functions like that.

**Comment by grantleyring** [comment]
Nope tried all the entities, although maybe it needs the password (as per
google sdk) but no password facility is available in the entity list?
