### ISSUE TITLE
Use of switch for Garden irrigation system is deprecated

### ISSUE THREAD

**Issue by millercentral** [make-all/tuya-local#2088]
**Describe the bug**
HA 2024.7.1 is reporting a log error for my RainPoint Irrigation Valve connected though Tuya-Local. The error is:

```
This error originated from a custom integration.

Logger: custom_components.tuya_local.helpers.mixin
Source: custom_components/tuya_local/helpers/mixin.py:113
integration: Tuya Local (documentation, issues)
First occurred: 4:21:00 PM (2 occurrences)
Last logged: 4:21:00 PM

The use of switch for Garden irrigation system is deprecated and should be replaced by valve.
```

**To Reproduce**
Use a Tuya Irrigation valve with Tuya Local integration with Home Assistant 2024.7

**Expected behavior**
No error message would appear

**Additional context**
[config_entry-tuya_local-e7b8ed95fb0918f6c9f35269e86f453d.json](https://github.com/user-attachments/files/16121527/config_entry-tuya_local-e7b8ed95fb0918f6c9f35269e86f453d.json)

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

**Comment by make-all** [comment]
This is not a bug. The deprecation is to give users time to adapt to using valves instead.

**Comment by millercentral** [comment]
Sorry, not positive I understand - the integration created the switch entity. Should that entity just be disabled/removed? I do also see a valve entity (sorry, I hadn't noticed that before).

**Comment by make-all** [comment]
You can disable the switch entity (if you install a fresh device, it should be disabled by default).
