### ISSUE TITLE
Unable to select the right type for Door/Window On/Off Sensor

### ISSUE THREAD

**Issue by EdSpatariu** [make-all/tuya-local#2095]
Hello experts,

Adding Tuya device Door Window Sensor (with battery) is not possible. 

Extract from Tuya cloud:
    "id": "bf13f646271522693cei49",
    "model": "",
    "name": "Contact Sensor 2",
    "product_id": "raacclhbugvi0qzr",
    "product_name": "WiFi门磁",
    "uuid": "103f00e869efe486"
    
    
Smart life or manual wizard, the device is being seen as a light bulb, vacuum cleaner, or simple contact sensor (image and debug logs attached - ignore local_tuya integration, that will be removed after migrating all sensors to this integration).
[home-assistant_tuya_local_2024-07-09T11-10-04.930Z.log](https://github.com/user-attachments/files/16142676/home-assistant_tuya_local_2024-07-09T11-10-04.930Z.log)
![image](https://github.com/make-all/tuya-local/assets/134559937/509f856e-5861-4e7c-9f27-a19518350777)

A couple of our ago, the same type of sensor, after few fails and retry attempts, finally was found as "nedis_open_close_sensor" or similar, that was what I was expected (sort of) as the device has battery, and make sense to monitor battery level, isn't it? Don't ask me what I did to finally appear device type "nedis_open_close_sensor" when adding the device.

How can I select device type from the list of available devices if the integration is not presenting the whole list???

Thank you.

**Comment by make-all** [comment]
Battery powered devices without hubs are out of scope for this integration, as they cannot work reliably without the cloud acting as a hub.
