### ISSUE TITLE
Request support for Fey123-Chargeur EV

### ISSUE THREAD

**Issue by juliiod** [make-all/tuya-local#2102]
Hello,
My Feyree charger is not recognized as a goodcell_ev_charger during integration. Can you help me ?

# Log Message
# Information about DPS mappings

Cette erreur provient d'une intégration personnalisée

Enregistreur: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:483
intégration: Tuya Local (documentation, problèmes)
S'est produit pour la première fois: 09:36:02 (1 occurrences)
Dernier enregistrement: 09:36:02

Device matches loratap_zigbee_six_switch with quality of 5%. DPS: {"updated_at": 1720683338.448093, "10": 0, "101": "no_connet", "102": 2377, "103": 0, "104": 0, "105": 0, "106": 0, "107": 0, "109": 0, "110": 376, "112": 0, "113": "Max32A", "115": 32, "118": 0, "119": 0, "120": "00:00:00", "121": "T:00H", "122": "D:00H", "123": false, "124": "WaitOperation", "125": 32, "126": 32}

# Product ID

Here is the Feyree charger  details :

https://fr.aliexpress.com/item/1005006103220114.html?spm=a2g0o.order_list.order_list_main.35.21ef5e5bEAzKwl&gatewayAdapt=glo2fra

**Comment by juliiod** [comment]
That's working ! thx !

**Comment by Nri-31** [comment]
Hello, i've the same problem with the same device. Can you help me ?
