### ISSUE TITLE
Remove Grid connect/arlec GPO/switch “master” dependency

### ISSUE THREAD

**Issue by JanekSMC** [make-all/tuya-local#212]
Hi, you guys are absolutely changing my world! It’s fantastic having local support for easily accessible products in AU (yay Bunnings!!!)

Is there a chance we could remove the master switch dependency on the grid connect series of GPOs and switches?  I change it in the config, but every update it changes back (obviously). 

It seems to me the master switch is only of use to switch off all outlets. You cannot have master on and outlets off, and as such when both/all outlets are off, master defaults to off, and inhibits the individual switch entities. 

This requires me to switch in the master, then select the switch I need on. This is different to the behaviour of the Tuya app which I can select any switch, and master can turn them all off. 

I hope this makes sense.

**Comment by make-all** [comment]
The override behaviour of the master switch was removed in the previous release.  It should now be possible to turn on individual switches when the master is off (whether the master automatically turns on will be down to device behaviour, there may be some delay if it does),

**Comment by JanekSMC** [comment]
My goodness! You are amazing. I never ever expected it to be done so quickly!!! It’ll be nice not to manually edit the master lockout every update!

I’m sos sorry I haven’t checked in before now, I keep getting caught up with my toddlers and all my “fun” stuff gets put on the back burner for ages. 

Honestly, Thankyou. I wish you knew just how appreciative I am.
