### ISSUE TITLE
add sensors to curtain motor

### ISSUE THREAD

**Issue by vnkorol** [make-all/tuya-local#213]
"product_id": "3r8gc33pnqsxfe1g",
    "product_name": "Blinds Controller",

To visualize position and check status of curtain, please add two sensors:
DP 2 - sensor position set -  unit '%'
DP 3 - sensor position get - unit '%'

**Comment by make-all** [comment]
Which configuration is this modification for?

**Comment by vnkorol** [comment]
1. when I send command to open at 50% I would like to check real position
2. At lovelace ganel it is more useful to show "get_position" instead of "current_position" from attributes. AFAIK in attributes there is set_position value.

**Comment by vnkorol** [comment]
To configuration of curtain controller. dp_id 2 and 3.

{
  "result": {
    "category": "cl",
    "functions": [
      {
        "code": "control",
        "dp_id": 1,
        "type": "Enum",
        "values": "{\"range\":[\"open\",\"stop\",\"close\"]}"
      },
      {
        "code": "percent_control",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "control_back",
        "dp_id": 5,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown",
        "dp_id": 8,
        "type": "Enum",
        "values": "{\"range\":[\"cancel\",\"1\",\"2\",\"3\",\"4\"]}"
      }
    ],
    "status": [
      {
        "code": "control",
        "dp_id": 1,
        "type": "Enum",
        "values": "{\"range\":[\"open\",\"stop\",\"close\"]}"
      },
      {
        "code": "percent_control",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "percent_state",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "control_back",
        "dp_id": 5,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_state",
        "dp_id": 7,
        "type": "Enum",
        "values": "{\"range\":[\"opening\",\"closing\"]}"
      },
      {
        "code": "countdown",
        "dp_id": 8,
        "type": "Enum",
        "values": "{\"range\":[\"cancel\",\"1\",\"2\",\"3\",\"4\"]}"
      },
      {
        "code": "countdown_left",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "time_total",
        "dp_id": 11,
        "type": "Integer",
        "values": "{\"unit\":\"ms\",\"min\":0,\"max\":120000,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1658807343754,
  "tid": "e435cb7d0c9511ed83de62023b21e71a"
}

**Comment by make-all** [comment]
This appears to be a completely new device, not a minor addition to an existing config.  Can you please give some details about the device (brand, model etc) to help with naming the config file.

**Comment by vnkorol** [comment]
AVATTO Wifi Smart Roller Blinds Motor
https://aliexpress.ru/item/4001045079168.html?gatewayAdapt=glo2rus&sku_id=10000015722279481&spm=a2g0o.order_list.0.0.69d6a396zYfORX

**Comment by vnkorol** [comment]
Now I waiting for release, right?

**Comment by make-all** [comment]
Or you can try it right away by selecting "Redownload" from the HACS page for this integration, and select "main" as the version to download.  It will pop up a notification that 0.8.1 is available to upgrade to, but you can ignore that until 0.8.2 comes out.

**Comment by vnkorol** [comment]
Device is detected correctly.
![image](https://user-images.githubusercontent.com/78999484/182834685-c11d38f0-d135-42ca-a578-f7c3f11def2e.png)

But there is no sensors - position_get (dp_id 3) and position_set (dp_id 2)
![image](https://user-images.githubusercontent.com/78999484/182835225-dbf0334f-1290-4fa0-98fd-5f567c02cff0.png)

**Comment by make-all** [comment]
These are not separate sensors, they are part of the main cover entity.

**Comment by vnkorol** [comment]
It works correctly! Thanks. DP_ID 3 i can get from current_position attribute. Thanks!
