### ISSUE TITLE
Request support for Petoneer Fresco Mini

### ISSUE THREAD

**Issue by Geek-MD** [make-all/tuya-local#2161]
### Log message

```text
Este error se originó en una integración personalizada.

Registrador: custom_components.tuya_local.config_flow
Fuente: custom_components/tuya_local/config_flow.py:483
integración: Tuya Local (documentación, problemas)
Ocurrió por primera vez: 21:04:57 (1 ocurrencias)
Último inicio de sesión: 21:04:57

Device matches tuya_smart_zigbee_door_sensor with quality of 20%. DPS: {"updated_at": 1722215065.5648248, "101": true, "102": 1, "104": 8604, "105": 8098, "108": 1}
```

### DPS information

```text
{
  "result": {
    "properties": [
      {
        "code": "power",
        "custom_name": "",
        "dp_id": 101,
        "name": "",
        "time": 1721705863336,
        "type": "bool",
        "value": true
      },
      {
        "code": "bright_value",
        "custom_name": "",
        "dp_id": 102,
        "name": "",
        "time": 1721699351551,
        "type": "value",
        "value": 1
      },
      {
        "code": "filter_alarm",
        "custom_name": "",
        "dp_id": 104,
        "name": "",
        "time": 1721873688107,
        "type": "value",
        "value": 2915
      },
      {
        "code": "pump_alarm",
        "custom_name": "",
        "dp_id": 105,
        "name": "",
        "time": 1721873706569,
        "type": "value",
        "value": 2732
      },
      {
        "code": "water_level",
        "custom_name": "",
        "dp_id": 108,
        "name": "",
        "time": 1721705986195,
        "type": "value",
        "value": 1
      }
    ]
  },
  "success": true,
  "t": 1721873734831,
  "tid": "c697bae44a2b11efb1b9c6346d654c82"
}
```

### Product ID

88055404e868e7583c52

### Product Name

Petoneer Fresco Mini

### Information about how the device functions

I managed to get the on/off switch and the light switch to work. Water level, filter alarm and pump alarma functionality is still missing. Here's a partial yaml code.

name: Pet fountain
products:
  - id: 88055404e868e7583c52
    name: Petoneer Fresco Mini
primary_entity:
  entity: switch
  name: Power
  class: switch
  icon: "mdi:water-pump"
  dps:
    - id: 101
      type: boolean
      name: switch
secondary_entities:
  - entity: light
    name: Light indicator
    translation_key: indicator
    category: config
    dps:
      - id: 102
        type: integer
        name: switch

**Comment by make-all** [comment]
I need the log message from trying to add the device without your custom changes, not the log message after you unsuccessfully created a broken config.

**Comment by Geek-MD** [comment]
> I need the log message from trying to add the device without your custom changes, not the log message after you unsuccessfully created a broken config.

I understand. I'll do what you need. Give me some time.

**Comment by Geek-MD** [comment]
You mean:

`
Este error se originó en una integración personalizada.

Registrador: custom_components.tuya_local.config_flow
Fuente: custom_components/tuya_local/config_flow.py:483
integración: Tuya Local (documentación, problemas)
Ocurrió por primera vez: 21:04:57 (1 ocurrencias)
Último inicio de sesión: 21:04:57

Device matches tuya_smart_zigbee_door_sensor with quality of 20%. DPS: {"updated_at": 1722215065.5648248, "101": true, "102": 1, "104": 8604, "105": 8098, "108": 1}`

**Comment by make-all** [comment]
Yes, thank you

**Comment by make-all** [comment]
Looking at the dps info you have provided, it is also missing range and possible value info, as well as any scale factors or steps for the numeric values that can be set.

**Comment by Geek-MD** [comment]
> Looking at the dps info you have provided, it is also missing range and possible value info, as well as any scale factors or steps for the numeric values that can be set.

Ranges:

code: power
  type:	Boolean,
  values: {
    true,
    false
  }

code: bright_value.
  type:	Integer,
  values: {
    "unit": "",
    "min": 0,
    "max": 1,
    "scale": 0,
    "step": 1
  }

code: filter_alarm
  type:	Integer,
  values: {
    "unit": "",
    "min": 0,
    "max": 43200,
    "scale": 0,
    "step": 1
  }

code: pump_alarm
  type:	Integer,
  values: {
    "unit": "",
    "min": 0,
    "max": 86400,
    "scale": 0,
    "step": 1
  }

> Also, the supplied product id seems to be in the format of a device id (unique to your specific device). Can you check either tuya portal (same functions that return local key) or tinytuya scan details for the product id?

You're right, I've written Device ID instead of Product ID.
PID is "uoihz7w5myinwrdx".

Thanks in advance
