### ISSUE TITLE
Fix Support for Modern Flames Orion Traditional Fireplace

### ISSUE THREAD

**Issue by rentzg** [make-all/tuya-local#2163]
**Describe the bug**
The existing device, modernflames_orion_fireplace.yaml, is missing the main on / off functionality that exists in the modern flames & tuya app directly. 

None of the entities brought into Home Assistant with this device template control the main on / off functionality that just controls the fire light visual of this device (there are separate controls for the built in heater and flame light visualization). This is id 1. It is incorrectly mapped to an HVAC control and should be a simple boolean.

**Expected behavior**
You should be able to use a switch in home assistant to control the on/off of the fire visual. This is the main On/Off in the Modern Flames app.

**Additional context**
To fix, I simply modified the device yaml (modernflames_orion_fireplace.yaml) and under "secondary_entities:" added a new entity as follows:

  - entity: switch
    name: Fire Visual On / Off
    icon: "mdi:power"
    category: config
    dps:
      - id: 1
        type: boolean
        name: switch

This works to control the fire visual as expected.

**Comment by make-all** [comment]
hvac_mode is the correct mapping for a climate entity.
