### ISSUE TITLE
Request support for Princess 350000 Smart Tower Fan

### ISSUE THREAD

**Issue by Gerlowski** [make-all/tuya-local#2167]
### Log message

```text
ejestrator: custom_components.tuya_local.config_flow
Źródło: custom_components/tuya_local/config_flow.py:483
integracja: Tuya Local (dokumentacja, Problemy)
Pierwsze zdarzenie: 19:26:25 (3 zdarzenia)
Ostatnio zalogowany: 19:42:00

    Device matches anko_fan with quality of 100%. DPS: {"updated_at": 1722360380.7927969, "1": false, "2": "sleep", "3": "3", "4": "auto", "6": "0"}
    Device matches anko_fan with quality of 100%. DPS: {"updated_at": 1722361012.2827163, "1": true, "2": "normal", "3": "1", "4": "off", "6": "0"}
    Device matches anko_fan with quality of 100%. DPS: {"updated_at": 1722361316.5532422, "1": true, "2": "normal", "3": "1", "4": "off", "6": "0"}
```

### DPS information

```text
{
  "result": {
    "properties": [
      {
        "code": "switch",
        "custom_name": "",
        "dp_id": 1,
        "time": 1722362779202,
        "type": "bool",
        "value": true
      },
      {
        "code": "mode",
        "custom_name": "",
        "dp_id": 2,
        "time": 1722361493870,
        "type": "enum",
        "value": "normal"
      },
      {
        "code": "fan_speed",
        "custom_name": "",
        "dp_id": 3,
        "time": 1722362575886,
        "type": "enum",
        "value": "1"
      },
      {
        "code": "fan_horizontal",
        "custom_name": "",
        "dp_id": 4,
        "time": 1722362268579,
        "type": "enum",
        "value": "off"
      },
      {
        "code": "countdown",
        "custom_name": "",
        "dp_id": 6,
        "time": 1722361471778,
        "type": "enum",
        "value": "0"
      }
    ]
  },
  "success": true,
  "t": 1722363295842,
  "tid": "9fb3c8ca4e9f11ef95c58686fd767712"
}
```

### Product ID

bknpvtphln5e07oj

### Product Name

Princess 350000 Smart Tower Fan

### Information about how the device functions

The fan can be controlled:
- enable/disable (true,false)
- mode (normal, natural, sleep)
- speed (1-3)
- rotation/oscillating (off,on)
- countdown(1-8 hour)

Product URL: [https://www.princesshome.eu/en-gb/princess-products/fans/princess-350000-smart-tower-fan-01.350000.01.001](https://www.princesshome.eu/en-gb/princess-products/fans/princess-350000-smart-tower-fan-01.350000.01.001)

**Comment by make-all** [comment]
The dps info is missing range / possible value, and scale details. Is there any other info you can provide, preferably QueryThigsDataModel results.

**Comment by make-all** [comment]
Without further info showing differences with the anko fan that is a 100% match already, there is no further action possible.

**Comment by Gerlowski** [comment]
Thank you for your reply. I wanted to clarify that almost everything is working correctly with my fan, except for the speed control. The issue is specifically with how the speeds are handled: unlike the Anko fan, which uses percentage-based control, my fan has three distinct speed settings—low, medium, and high. The percentage-based control doesn't map correctly to these settings, making it difficult to adjust the fan speed properly. I would greatly appreciate any help in resolving this issue.

Thank you for your support!
![obraz](https://github.com/user-attachments/assets/65cadde8-7c39-4c68-86d5-268f0b80a037)

![Screenshot_20240902_192744_Tuya Smart](https://github.com/user-attachments/assets/96b9a3f1-1321-4b71-a4a0-b218bd7ff9f8)
