### ISSUE TITLE
Ble Solar Light not an option?

### ISSUE THREAD

**Issue by Krispkiwi** [make-all/tuya-local#2183]
Hey mate,

I'm running into an issue with the latest versions of the integration. When trying to add them with protocol 3.4 as I'd previously done, it no longer shows up as an option.

<img width="391" alt="image" src="https://github.com/user-attachments/assets/ff8ca724-9e7b-4986-a57e-9bac3b32d639">

**Comment by make-all** [comment]
You should have left this as a discussion. As it is, there is not enough info to consider this a bug.
