### ISSUE TITLE
Air Purifier is added as a switch and not a fan type entity in HA

### ISSUE THREAD

**Issue by 4rianton** [make-all/tuya-local#2188]
**Describe the bug**
An air purifier should ideally be shown as a fan just like the Tuya cloud integration but it is exposed as a switch instead. This makes it pretty hard to meaningfully expose the purifier with any additional options using homekit bridge. One also loses the ability to have fancier cards for this entity in HA dashboards. 

**To Reproduce**
Add the purifier, notice that it's exposed as a switch instead of a fan. 

**Expected behavior**
Ideally, it should be exposed as a fan device type

How the integration looks like with purifier exposed as a switch (how this integration handles it):
 
<img width="554" alt="Screenshot 2024-08-08 at 15 23 34" src="https://github.com/user-attachments/assets/aa9e8a69-57d8-4448-9ffb-d912bb41432b">

<img width="651" alt="Screenshot 2024-08-08 at 15 05 57" src="https://github.com/user-attachments/assets/5f9a7649-87ab-444c-aad4-87ddbb14e6b3">

![IMG_9232](https://github.com/user-attachments/assets/0a8beced-daa9-49e2-8b4d-834ffd6cb0a7)

How the integration looks like with purifier exposed as a fan (like how Tuya default integration does it):

<img width="545" alt="Screenshot 2024-08-08 at 15 19 32" src="https://github.com/user-attachments/assets/935ce373-5aca-4a37-9888-17ae826db1ab">

<img width="537" alt="Screenshot 2024-08-08 at 15 23 09" src="https://github.com/user-attachments/assets/a0c46799-7bc7-4a36-a3a3-89e1e2a09a6d">

![IMG_9231](https://github.com/user-attachments/assets/081d954a-7726-424a-b99f-3632595413c1)

Please let me know if you need any more specific information.

**Comment by make-all** [comment]
There are insufficient details here to understand what your bug is.

**Comment by make-all** [comment]
Unlike the 22 other purifiers supported by this integration, the Essentials purifier does not appear to offer any control beyond the power switch. Since there is no speed control, or presets, using a fan just to control the power switch does not make sense.

**Comment by 4rianton** [comment]
Thanks a lot for taking care of this @make-all
