### ISSUE TITLE
New device - Inkbird ISV-100W Cooker

### ISSUE THREAD

**Issue by Condorello** [make-all/tuya-local#219]
Hi, i'm trying to add a souse vide cooker by Inkbird but i get this error:

`2022-08-10 18:53:16.228 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches None with quality of 0%. DPS: {'101': False, '102': 'stop', '103': 0, '104': 297, '105': 0, '106': 0, '107': 3, '108': True, '109': 0, '110': 0, 'updated_at': 1660150395.6375916}`

And here the debug from IOT platform:

`instruction set:

switch
Boolean	
"{true,false}"

cook_temperature	Integer	
{
  "unit": "℃",
  "min": 0,
  "max": 960,
  "scale": 1,
  "step": 1
}

cook_time	Integer	
{
  "unit": "min",
  "min": 0,
  "max": 5999,
  "scale": 0,
  "step": 1
}

cloud_recipe_number	Integer	
{
  "unit": "",
  "min": 0,
  "max": 1000,
  "scale": 0,
  "step": 1
}

temp_unit_convert	Enum	
{
  "range": [
    "c",
    "f"
  ]
  
  
status set:
temp_current	Integer	
{
  "unit": "℃",
  "min": 0,
  "max": 1000,
  "scale": 1,
  "step": 1
}
cook_time	Integer	
{
  "unit": "min",
  "min": 0,
  "max": 5999,
  "scale": 0,
  "step": 1
}
remain_time	Integer	
{
  "unit": "min",
  "min": 0,
  "max": 5999,
  "scale": 0,
  "step": 1
}
cloud_recipe_number	Integer	
{
  "unit": "",
  "min": 0,
  "max": 1000,
  "scale": 0,
  "step": 1
}

status	Enum	
{
  "range": [
    "standby",
    "cooking",
    "done"
  ]
}

temp_unit_convert	Enum	
{
  "range": [
    "c",
    "f"
  ]
}

fault	Bitmap	
{
  "label": [
    "0",
    "1",
    "2"
  ]`

This should be the main idx references:

101
switch

102
status

103
cook_temperature

104
temp_current

105
cook_time",

106
remaining_time

107
fault

108
temp_unit_convert

Any possibility to integrate? Thanks in advance

**Comment by make-all** [comment]
Can you check the actual values for 102 (status)?  The iot.tuya.com list says possible values are standby, cooking, done but the current value is "stop", so the documentation at iot.tuya.com seems to be wrong. 108 seems to be wrong as well, as it is boolean vs the docs that say "c" or "f", but that is more obvious.

You might also be able to discover what 109 and 110 are (maybe with Chinese labels, but I can translate those) from the iot.tuya.com device debugger (there is now a link in the README.md to some instructions from zigbee2mqtt project for doing this).

**Comment by Condorello** [comment]
Hi, thanks for your help, i'm trying to debugging:

102 status are correct: standby, cooking (when target temp is reached and stays in this state until remain cooking time became zero), done (after cooking  remain time is runned out).

108 in the debugger appear a "f", while in the app i can clearly see the temerature in celsius...

109 is in chinese, translated to "local recipe"  but probably it should be "cloud recipe" as in the official app is possible to  browse a predefined recipe database which correspond to a certain cooking time-duration.

110 is translated to "temperature correction", which is a setting which can be used for fix eventually a difference between the measured temperature of the water and the effective one.

**Comment by make-all** [comment]
Thanks, but the value returned locally in the log was clearly "stop".  I assume this maps to either standby or done in the cloud API, but not sure which one, and if that is different than the cloud value, the other two possibly are as well.

**Comment by Condorello** [comment]
Mmmm you are right, sorry!

now that is running (cooking) 102 state is "working"

**Comment by make-all** [comment]
Thanks, let me know when you can capture the local value for "done" as well, and we'll be ready to start creating the config.

**Comment by Condorello** [comment]
> Thanks, let me know when you can capture the local value for "done" as well, and we'll be ready to start creating the config.

at cooking finished the status change to "complete"

**Comment by Condorello** [comment]
Thanks for your work. The device is discovered, remaing time and set time is working fine. Cesius/Farenheit selector is correct according to tuya cloud specifics, but is working in counter way in human sense, so probably is better to invert the labels. The main problem is the temperature set and current temperature values. HAVC template i think works only as comma values (40,0   51,5   68,5   72,0 etc.), while tuya cloud (so the device) works with integer values (400   515   685   720 etc.). So the sent temp values is too low, under the minimum expected.

**Comment by make-all** [comment]
The C and F setting was swapped, and the device support is now released in 0.19.0.  Please let me know if there is still an issue.

**Comment by baylanger** [comment]
Does this PR support most Inkbird sous-vide cookers?

I have in my amazon cart since 2 weeks the ISV-200W.  Aside from the temperature range that differs between the 2 models, I believe they are pretty much identical. Many brand with sous-vide cookers, w/ wifi/bluetooth seem to use a ESP module.

**Comment by make-all** [comment]
You won't know until you (or someone) tries it.  Local protocol level detail is not publicly available, so we don't know if the ESP modules for these two models have the same or different firmware.

**Comment by baylanger** [comment]
🤔 Am I looking for a project this weekend or not? 🤔  After writing this I ended up amazon, lol thank you to push me there again.  fyi for those perhaps interested, there's currently a 35% coupon off.  It is expected to be delivered next Monday in the US.

I'm currently away, might take ~2 weeks before I get back and have time.  Will be back here whenever I have time,

**Comment by make-all** [comment]
For the temperature issue, the scale factor of 10 is already set in the config.  Unfortunately 0.19.0 and 0.19.1 had general issues with the underlying tuya library, but you should be able to check it in 0.19.2 now.

**Comment by Condorello** [comment]
Sorry for the delay in my answer. I'll check it out asap and let you know. Thanks :)
