### ISSUE TITLE
Smart Energy Monitor stopped working on HA update to 2024.8

### ISSUE THREAD

**Issue by kap-Gun** [make-all/tuya-local#2202]
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**
Smart Energy Monitor (GR2PW) is an energy monitor coming in three variants. Non-Smart, Wifi-only and Wifi with switch.
I have the Wifi-Only version which feeds all energy monitoring data to HA.
I have only the above device and 4 Tuya plugs through tuya-local, of which only the energy monitor failed after HA update.

**To Reproduce**
Steps to reproduce the behavior including the device the issue was observed with:
Update HA to 2024.8

**Expected behavior**
Device to be active through tuya-local

**Additional context**
Device IP can be pinged and data can be accessed through the Tuya App.

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"
[tuya_local-e060a808abc1a42194cfc977ffdfda74-House_Energy_meter-4afd4976db76ee652f37895ee869df35.json](https://github.com/user-attachments/files/16600062/tuya_local-e060a808abc1a42194cfc977ffdfda74-House_Energy_meter-4afd4976db76ee652f37895ee869df35.json)

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.
[home-assistant_2024-08-13T13-10-47.425Z.log](https://github.com/user-attachments/files/16600090/home-assistant_2024-08-13T13-10-47.425Z.log)

![image](https://github.com/user-attachments/assets/9cddbd43-4b65-4bc0-9386-b09b2ca47944)

![image](https://github.com/user-attachments/assets/1350d50d-7b35-4a63-a5c9-f8e5db93c140)

![image](https://github.com/user-attachments/assets/e5e1ea98-a731-4b35-9d09-334f52ee7a40)

**Comment by make-all** [comment]
From the DEBUG messages in the log, the root cause of the connection failures seems to be this exception from tinytuya:
```
2024-08-12 15:52:01.520 DEBUG (MainThread) [custom_components.tuya_local.device] Retrying after exception <class 'AttributeError'> Check device key or version (2/3)
```

**Comment by kap-Gun** [comment]
There is a clue about the likely cause in the message Check device key or version

Normally, the only change was the HA update.
I did check the device key first thing and it did not change.
The version was 3.4 when it was working and I did try to add it again using other versions and auto but to no avail.

**Comment by kap-Gun** [comment]
Device working again after several reset.
