### ISSUE TITLE
tuya rcrcbo power metter error

### ISSUE THREAD

**Issue by vpaulos** [make-all/tuya-local#2214]
Hi!

Sensor, that shows total energy consumtion (take units from device in Kwh). shows error in measurement. (7.64 KWH)

![image](https://github.com/user-attachments/assets/e7251b5b-ec82-4f23-b384-0a853a7ef868)

and right units is 76.43 KWH

![image](https://github.com/user-attachments/assets/f13f9b3e-e95a-4c6f-93f0-ea8d258dfc15)

CAn you please fix it?

Diagnostic file:

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.7.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.2",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Moscow",
    "os_name": "Linux",
    "os_version": "6.6.38-haos",
    "supervisor": "2024.06.2",
    "host_os": "Home Assistant OS 12.4",
    "docker_version": "26.1.4",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "smart_thermostat": {
      "documentation": "https://github.com/jethome-ru/hassio-component-smart-thermostat",
      "version": "v0.1.0",
      "requirements": [
        "simple-pid==1.0.1"
      ]
    },
    "lkcomu_interrao": {
      "documentation": "https://github.com/alryaz/hass-lkcomu-interrao",
      "version": "2022.05.03",
      "requirements": [
        "python-dateutil==2.8.1",
        "fake_useragent==0.1.11",
        "inter-rao-energosbyt-python==0.0.23"
      ]
    },
    "tuya_local": {
      "documentation": "https://github.com/make-all/tuya-local",
      "version": "2024.7.1",
      "requirements": [
        "tinytuya==1.15.1",
        "tuya-device-sharing-sdk>=0.1.9,<=0.2.99"
      ]
    },
    "dreame_vacuum": {
      "documentation": "https://github.com/Tasshack/dreame-vacuum",
      "version": "v1.0.4",
      "requirements": [
        "pillow",
        "numpy",
        "pybase64",
        "requests",
        "pycryptodome",
        "python-miio",
        "py-mini-racer",
        "tzlocal",
        "paho-mqtt"
      ]
    },
    "localtuya": {
      "documentation": "https://github.com/rospogrigio/localtuya/",
      "version": "5.2.1",
      "requirements": []
    },
    "moscow_pgu": {
      "documentation": "https://github.com/alryaz/hass-moscow-pgu",
      "version": "0.3.1",
      "requirements": []
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "ble_monitor": {
      "documentation": "https://github.com/custom-components/ble_monitor",
      "version": "12.14.0",
      "requirements": [
        "pycryptodomex>=3.19.1",
        "janus>=1.0.0",
        "aioblescan>=0.2.14",
        "btsocket>=0.2.0",
        "pyric>=0.1.6.3"
      ]
    },
    "sonoff": {
      "documentation": "https://github.com/AlexxIT/SonoffLAN",
      "version": "3.7.3",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "miio2": {
      "documentation": "https://github.com/KrzysztofHajdamowicz/home-assistant-vacuum-styj02ym",
      "version": "2022.3.3",
      "requirements": [
        "construct==2.10.56",
        "python-miio==0.5.12"
      ]
    },
    "tns_energo": {
      "documentation": "https://github.com/alryaz/hass-tns-energo",
      "version": "0.1.1",
      "requirements": [
        "tns-energo-api==0.0.5"
      ]
    },
    "midea_ac": {
      "documentation": "https://github.com/mill1000/midea-ac-py",
      "version": "2024.8.0",
      "requirements": [
        "msmart-ng>=2024.8.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya_local",
    "name": "Tuya Local",
    "codeowners": [
      "make-all"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/make-all/tuya-local",
    "integration_type": "device",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/make-all/tuya-local/issues",
    "requirements": [
      "tinytuya==1.15.1",
      "tuya-device-sharing-sdk>=0.1.9,<=0.2.99"
    ],
    "version": "2024.7.1",
    "is_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 0.00013920300000336283
    },
    "bd91bf38bf652e3a58730e6024f38732": {
      "wait_import_platforms": -3.1919823099999576,
      "config_entry_setup": 19.87845100300001
    },
    "fda2c2a0011d4a5fb7dfadb05ee0853b": {
      "wait_import_platforms": -3.1973582419999502,
      "config_entry_setup": 19.87855970999999
    },
    "8ba223301c2ea1e7af4b1193aba36edf": {
      "wait_import_platforms": -3.2078765300000214,
      "wait_base_component": -0.004130185000008169,
      "config_entry_setup": 21.52329503200002
    },
    "0e34be7fb30c8cb23285f6eaec1e2d0e": {
      "wait_import_platforms": -3.5898808619999727,
      "config_entry_setup": 20.47111214900002
    },
    "dcc013e384c2ee87c7cbe045774670e8": {
      "wait_import_platforms": -3.6063775570000303,
      "config_entry_setup": 20.481010826999977
    },
    "dbe95cbbcd695bbe4ad25621c9aec2fe": {
      "wait_import_platforms": -3.622531682999977,
      "config_entry_setup": 20.472705968000014
    },
    "f59f5e4b8cf88d3343b3cd70a83e9b81": {
      "wait_import_platforms": -3.6319371359999764,
      "config_entry_setup": 20.472066577999954
    },
    "805cb19d18cb5c09b76255044d233223": {
      "wait_import_platforms": -3.627537716000006,
      "config_entry_setup": 20.375327432000006
    },
    "2c81e6a111a3352516e22c3c92bc2b59": {
      "wait_import_platforms": -3.705155590000004,
      "config_entry_setup": 20.33019990599996
    },
    "0d6fca50036e8c3f5a65e8588c7ec696": {
      "wait_import_platforms": -3.7067000359999724,
      "config_entry_setup": 20.33152185800003
    },
    "f722d16ff68e0291aa8dc8e2b48e2f81": {
      "wait_import_platforms": -3.7353900670000257,
      "config_entry_setup": 21.572133323000003
    },
    "f3eb72f0568de5a411cf08b489aa855f": {
      "wait_import_platforms": -3.8447319530000073,
      "config_entry_setup": 21.573193739999965
    },
    "bd75205ddabe6b0bf92cf2eadcf39d19": {
      "wait_import_platforms": -3.998998216000018,
      "config_entry_setup": 21.634235450000006
    },
    "5860bca97259f70cf8462699119ecb08": {
      "wait_import_platforms": -4.176521653000009,
      "config_entry_setup": 21.605056950999995
    },
    "4d11ac12102e7375d9a2b80adecc59cb": {
      "wait_import_platforms": -4.465381476999994,
      "config_entry_setup": 21.749439945000006
    },
    "99777e97aef54442840ec8cf190768a5": {
      "wait_import_platforms": -4.504584442999999,
      "config_entry_setup": 21.793860773999995
    },
    "1bfb694463bc3461c014f94b030c3d04": {
      "wait_import_platforms": -4.735815838999997,
      "config_entry_setup": 21.841943157000003
    },
    "b0e0504c6d6214f456daf36f1c791f2f": {
      "wait_import_platforms": -4.8737155900000175,
      "config_entry_setup": 22.004151033000028
    },
    "1c313da58a337217767226c09bfb0406": {
      "wait_import_platforms": -5.086866511000039,
      "config_entry_setup": 22.001062241
    },
    "272fad71ddf1a657d611e20de27fa54e": {
      "wait_import_platforms": -5.241772548999961,
      "config_entry_setup": 22.009542179999983
    },
    "52d6b28695da868bf4604baf80442a06": {
      "wait_import_platforms": -5.5778770189999705,
      "config_entry_setup": 21.958769992999976
    },
    "582d088c5683f27232ff2ece232a7466": {
      "wait_import_platforms": -5.645371394999984,
      "config_entry_setup": 22.010586572999955
    },
    "ec6e7dc178cec8bdab23a5eb15c75ae4": {
      "wait_import_platforms": -5.780220027000041,
      "config_entry_setup": 21.981054632999985
    },
    "51fafeb87e00f8550aaa1590072e9aaa": {
      "wait_import_platforms": -7.7554836420000015,
      "config_entry_setup": 21.97417926600002
    },
    "364d7087b23046535f77965e03a955ab": {
      "wait_import_platforms": -7.85124353599997,
      "config_entry_setup": 22.58678399600001
    },
    "4f37978dd51a75c02f55be6687b51967": {
      "wait_import_platforms": -7.957489683000006,
      "config_entry_setup": 22.586721501
    },
    "4620bcbdb3118a5759ff89c6af42c881": {
      "wait_import_platforms": -8.07518606100001,
      "config_entry_setup": 22.577454766000017
    },
    "735b476f1bd76d3fae71391574e2319f": {
      "wait_import_platforms": -8.320256652000012,
      "config_entry_setup": 22.67596165399999
    },
    "760a6d926b3a32e88dc1075ad051789c": {
      "wait_import_platforms": -8.404447301999994,
      "config_entry_setup": 22.71419266600003
    },
    "e67fc85cbd4d0626f7c5a4d177bcb412": {
      "wait_import_platforms": -8.650694063000003,
      "config_entry_setup": 22.677577477
    },
    "c978892e3b6b418202cc34fffe398eaf": {
      "wait_import_platforms": -9.082380435999994,
      "config_entry_setup": 22.68529276800001
    },
    "0fcd18c480567eab8f76bef5908a31ce": {
      "wait_import_platforms": -9.289129120999974,
      "config_entry_setup": 22.667916042
    },
    "b64ca38e3721b8f21e12bce48147964c": {
      "wait_import_platforms": -9.367570862999969,
      "config_entry_setup": 22.660533209999983
    },
    "3f90c05d01dac23bddc8c2122f98711f": {
      "wait_import_platforms": -9.379570526000009,
      "config_entry_setup": 22.660383300999968
    },
    "41ddabd25173acd42df108b003a43567": {
      "wait_import_platforms": -9.513500115,
      "config_entry_setup": 22.63864305499999
    },
    "d95b4a4e887900c71d82af8376d92f74": {
      "wait_import_platforms": -9.604958594000038,
      "config_entry_setup": 22.658132173000013
    },
    "76e6c6c650ab79f8f88edb87ec728a85": {
      "wait_import_platforms": -9.847496019999994,
      "config_entry_setup": 22.724849233000043
    },
    "23c1aaabc7a1985ba998f1f2af608fbd": {
      "wait_import_platforms": -9.98854693300001,
      "config_entry_setup": 22.756318257000032
    },
    "e535e6d3e8ad785b870b757899db67ec": {
      "wait_import_platforms": -10.103460694999967,
      "config_entry_setup": 22.826036020000004
    },
    "000984f716c6af2f7a004a831d4f38e5": {
      "wait_import_platforms": -10.358511372999999,
      "config_entry_setup": 20.805755444
    }
  },
  "data": {
    "name": "t.int.rcbo",
    "type": "wdyk_3phase_energymonitor",
    "device_id": "**REDACTED**",
    "device_cid": "",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": 3.3,
    "tinytuya_version": "1.15.1",
    "api_version_set": 3.3,
    "api_version_used": 3.3,
    "api_working": true,
    "status": {},
    "cached_state": {
      "updated_at": 1723799654.678387,
      "1": true,
      "9": 0,
      "26": 0,
      "38": "2",
      "40": true,
      "104": 0,
      "105": 37,
      "107": 0,
      "114": 7644,
      "115": "463100000001        ",
      "117": false,
      "118": 0,
      "101": "CVMJAwkT",
      "102": "AAETAAAAAADu",
      "103": "AAKCAAFcAAAAAAEm"
    },
    "pending_state": {},
    "connected": true,
    "force_dps": [
      101,
      101,
      101,
      102,
      102,
      102,
      103,
      103,
      103,
      103
    ],
    "home_assistant": {
      "name": "t.int.rcbo",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "lock.t_int_rcbo_blokirovka_ot_detei",
            "state": "locked",
            "attributes": {
              "friendly_name": "t.int.rcbo \u0411\u043b\u043e\u043a\u0438\u0440\u043e\u0432\u043a\u0430 \u043e\u0442 \u0434\u0435\u0442\u0435\u0439",
              "supported_features": 0
            },
            "last_changed": "2024-08-16T09:06:18.644143+00:00",
            "last_reported": "2024-08-16T09:14:14.680315+00:00",
            "last_updated": "2024-08-16T09:06:18.644143+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "voltage",
          "icon": null,
          "unit_of_measurement": "V",
          "state": {
            "entity_id": "sensor.t_int_rcbo_voltage_a",
            "state": "238.7",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "V",
              "device_class": "voltage",
              "friendly_name": "t.int.rcbo Voltage A"
            },
            "last_changed": "2024-08-16T09:14:14.126883+00:00",
            "last_reported": "2024-08-16T09:14:14.681729+00:00",
            "last_updated": "2024-08-16T09:14:14.126883+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "voltage",
          "icon": null,
          "unit_of_measurement": "V",
          "state": {
            "entity_id": "sensor.t_int_rcbo_voltage_b",
            "state": "230.7",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "V",
              "device_class": "voltage",
              "friendly_name": "t.int.rcbo Voltage B"
            },
            "last_changed": "2024-08-16T09:14:14.128274+00:00",
            "last_reported": "2024-08-16T09:14:14.682722+00:00",
            "last_updated": "2024-08-16T09:14:14.128274+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "voltage",
          "icon": null,
          "unit_of_measurement": "V",
          "state": {
            "entity_id": "sensor.t_int_rcbo_voltage_c",
            "state": "232.3",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "V",
              "device_class": "voltage",
              "friendly_name": "t.int.rcbo Voltage C"
            },
            "last_changed": "2024-08-16T09:14:14.129672+00:00",
            "last_reported": "2024-08-16T09:14:14.683820+00:00",
            "last_updated": "2024-08-16T09:14:14.129672+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "current",
          "icon": null,
          "unit_of_measurement": "A",
          "state": {
            "entity_id": "sensor.t_int_rcbo_current_a",
            "state": "0.275",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "A",
              "device_class": "current",
              "friendly_name": "t.int.rcbo Current A"
            },
            "last_changed": "2024-08-16T09:14:14.267861+00:00",
            "last_reported": "2024-08-16T09:14:14.685016+00:00",
            "last_updated": "2024-08-16T09:14:14.267861+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "current",
          "icon": null,
          "unit_of_measurement": "A",
          "state": {
            "entity_id": "sensor.t_int_rcbo_current_b",
            "state": "0.0",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "A",
              "device_class": "current",
              "friendly_name": "t.int.rcbo Current B"
            },
            "last_changed": "2024-08-16T09:06:28.886505+00:00",
            "last_reported": "2024-08-16T09:14:14.685934+00:00",
            "last_updated": "2024-08-16T09:06:28.886505+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "current",
          "icon": null,
          "unit_of_measurement": "A",
          "state": {
            "entity_id": "sensor.t_int_rcbo_current_c",
            "state": "0.238",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "A",
              "device_class": "current",
              "friendly_name": "t.int.rcbo Current C"
            },
            "last_changed": "2024-08-16T09:14:14.270739+00:00",
            "last_reported": "2024-08-16T09:14:14.686826+00:00",
            "last_updated": "2024-08-16T09:14:14.270739+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "power",
          "icon": null,
          "unit_of_measurement": "kW",
          "state": {
            "entity_id": "sensor.t_int_rcbo_total_power",
            "state": "0.0642",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "kW",
              "device_class": "power",
              "friendly_name": "t.int.rcbo Total power"
            },
            "last_changed": "2024-08-16T09:14:14.687787+00:00",
            "last_reported": "2024-08-16T09:14:14.687787+00:00",
            "last_updated": "2024-08-16T09:14:14.687787+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "power",
          "icon": null,
          "unit_of_measurement": "kW",
          "state": {
            "entity_id": "sensor.t_int_rcbo_power_a",
            "state": "0.0348",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "kW",
              "device_class": "power",
              "friendly_name": "t.int.rcbo Power A"
            },
            "last_changed": "2024-08-16T09:14:14.689330+00:00",
            "last_reported": "2024-08-16T09:14:14.689330+00:00",
            "last_updated": "2024-08-16T09:14:14.689330+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "power",
          "icon": null,
          "unit_of_measurement": "kW",
          "state": {
            "entity_id": "sensor.t_int_rcbo_power_b",
            "state": "0.0",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "kW",
              "device_class": "power",
              "friendly_name": "t.int.rcbo Power B"
            },
            "last_changed": "2024-08-16T09:06:29.326092+00:00",
            "last_reported": "2024-08-16T09:14:14.690863+00:00",
            "last_updated": "2024-08-16T09:06:29.326092+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "power",
          "icon": null,
          "unit_of_measurement": "kW",
          "state": {
            "entity_id": "sensor.t_int_rcbo_power_c",
            "state": "0.0294",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "kW",
              "device_class": "power",
              "friendly_name": "t.int.rcbo Power C"
            },
            "last_changed": "2024-08-16T09:14:14.691904+00:00",
            "last_reported": "2024-08-16T09:14:14.691904+00:00",
            "last_updated": "2024-08-16T09:14:14.691904+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "current",
          "icon": null,
          "unit_of_measurement": "mA",
          "state": {
            "entity_id": "sensor.t_int_rcbo_leakage_current",
            "state": "0",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "mA",
              "device_class": "current",
              "friendly_name": "t.int.rcbo Leakage current"
            },
            "last_changed": "2024-08-16T09:06:18.657237+00:00",
            "last_reported": "2024-08-16T09:14:14.693055+00:00",
            "last_updated": "2024-08-16T09:06:18.657237+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "temperature",
          "icon": null,
          "unit_of_measurement": "\u00b0C",
          "state": {
            "entity_id": "sensor.t_int_rcbo_temperatura",
            "state": "37",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "\u00b0C",
              "device_class": "temperature",
              "friendly_name": "t.int.rcbo \u0422\u0435\u043c\u043f\u0435\u0440\u0430\u0442\u0443\u0440\u0430"
            },
            "last_changed": "2024-08-16T09:06:18.658334+00:00",
            "last_reported": "2024-08-16T09:14:14.696420+00:00",
            "last_updated": "2024-08-16T09:06:18.658334+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": "kWh",
          "state": {
            "entity_id": "sensor.t_int_rcbo_remaining_energy",
            "state": "0.0",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "kWh",
              "friendly_name": "t.int.rcbo Remaining energy"
            },
            "last_changed": "2024-08-16T09:06:18.659440+00:00",
            "last_reported": "2024-08-16T09:14:14.697378+00:00",
            "last_updated": "2024-08-16T09:06:18.659440+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "energy",
          "icon": null,
          "unit_of_measurement": "kWh",
          "state": {
            "entity_id": "sensor.t_int_rcbo_energiia",
            "state": "7.644",
            "attributes": {
              "state_class": "total_increasing",
              "unit_of_measurement": "kWh",
              "device_class": "energy",
              "friendly_name": "t.int.rcbo \u042d\u043d\u0435\u0440\u0433\u0438\u044f"
            },
            "last_changed": "2024-08-16T09:06:18.665038+00:00",
            "last_reported": "2024-08-16T09:14:14.698058+00:00",
            "last_updated": "2024-08-16T09:06:18.665038+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "problem",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "binary_sensor.t_int_rcbo_problema",
            "state": "off",
            "attributes": {
              "device_class": "problem",
              "friendly_name": "t.int.rcbo \u041f\u0440\u043e\u0431\u043b\u0435\u043c\u0430"
            },
            "last_changed": "2024-08-16T09:06:18.666404+00:00",
            "last_reported": "2024-08-16T09:14:14.698577+00:00",
            "last_updated": "2024-08-16T09:06:18.666404+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "lock",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "binary_sensor.t_int_rcbo_locking",
            "state": "off",
            "attributes": {
              "device_class": "lock",
              "friendly_name": "t.int.rcbo Locking"
            },
            "last_changed": "2024-08-16T09:06:18.667534+00:00",
            "last_reported": "2024-08-16T09:14:14.698934+00:00",
            "last_updated": "2024-08-16T09:06:18.667534+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.t_int_rcbo",
            "state": "on",
            "attributes": {
              "fault_code": 0,
              "serial_number": "463100000001        ",
              "RkWh": 0,
              "friendly_name": "t.int.rcbo"
            },
            "last_changed": "2024-08-16T09:06:18.677923+00:00",
            "last_reported": "2024-08-16T09:14:14.700065+00:00",
            "last_updated": "2024-08-16T09:06:18.677923+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": "min",
          "state": {
            "entity_id": "number.t_int_rcbo_taimer",
            "state": "0.0",
            "attributes": {
              "min": 0.0,
              "max": 1440.0,
              "step": 1.0,
              "mode": "auto",
              "unit_of_measurement": "min",
              "friendly_name": "t.int.rcbo \u0422\u0430\u0439\u043c\u0435\u0440"
            },
            "last_changed": "2024-08-16T09:06:18.679401+00:00",
            "last_reported": "2024-08-16T09:14:14.700973+00:00",
            "last_updated": "2024-08-16T09:06:18.679401+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "select.t_int_rcbo_initial_state",
            "state": "Last state",
            "attributes": {
              "options": [
                "Off",
                "On",
                "Last state"
              ],
              "icon": "mdi:toggle-switch",
              "friendly_name": "t.int.rcbo Initial state"
            },
            "last_changed": "2024-08-16T09:06:18.680660+00:00",
            "last_reported": "2024-08-16T09:14:14.701639+00:00",
            "last_updated": "2024-08-16T09:06:18.680660+00:00"
          }
        }
      ]
    }
  }
}

**Comment by make-all** [comment]
OK, it seems no scale info was provided in #550 originally, so I assumed Wh the same as some other smartplugs.
