### ISSUE TITLE
[New device request] Fairland Full Inverter Pool Heat Pump

### ISSUE THREAD

**Issue by VoyteckPL** [make-all/tuya-local#222]
Hi,
The heat pump for 15-30m3 pools - Fairland Inverter Plus 6,5kW IPHCR15

https://sklepbasenowy.pl/produkt/fairland-iphcr15/

All options work. Please add this to integration:

[https://pastebin.com/kss3N846](url)

**Comment by make-all** [comment]
This config is almost identical to the GardenPAC config except hvac_action is changed to hvac_mode.  Actually it is a bit strange that the pool heatpumps supported so far have read-only status that can indicate heating or cooling modes, but only an on/off switch, no way to explicitly control the heating or cooling state.  I suspect that all the madimack/gardenpac/fairland heatpumps are actually controllable through dp 105, just that users until now have only been interested in using them to heat.

**Comment by VoyteckPL** [comment]
It says 105 is read only but you can change it without a problem. This config I provided works 100%.All options are working.

**Comment by make-all** [comment]
Included in 0.19.0 release

**Comment by VoyteckPL** [comment]
Please fix:
    - id: 106
      name: temperature
      type: integer
      mapping:
        - constraint: temperature_unit
          conditions:
            - dps_val: false
              range:
                min: 60
                max: 115
      range:
        min: 12
        max: 45

min should be 12 (now it is 16) and it is not possible to set temp in range 12-16.
