### ISSUE TITLE
Add additional items for tuya power meter

### ISSUE THREAD

**Issue by Eckart0** [make-all/tuya-local#223]
Hi,
I use tuya-local for energy monitoring, but I cannot integrate the data into the HA Energy Monitor. 

Tuya local only reads the values for voltage, current and current_consumption from the electricity meter. 

However, the device also offers the values for kWh total and kWh today.

Couldn't these also be taken over - and preferably mapped in a sensor in such a way that it can be transferred to the HA energy monitor without further translation?

Greetings, Eckart

**Comment by make-all** [comment]
They could potentially be used directly by the Energy monitor instead of setting up an Integration sensor.  Until now, all the devices that provide a Wh reading have reset the counter automatically after submitting to the cloud, so they mostly just read 0 locally unless you catch it as it updates to 1 and the cloud submission is in progress.  But if it has a "today" reading, or a total that does not reset, that should be usable.

**Comment by make-all** [comment]
To do anything though, I need to know which device this is, and what the DPs are for the extra sensors.

**Comment by Eckart0** [comment]
Hi Jason,

 

I have not yet come to terms with this answer. Tuya-local only offers three fields in the configuration menu: Current, Current Consumption and Voltage. I cannot enter more than that.

 

I cannot enter the other values of the electricity meter - Wh total and today - and they do not appear in the sensor's attributes either. 

 

Have I overlooked something?

 

Greetings, Eckart

 



 

Von: Jason Rumney ***@***.***> 
Gesendet: Samstag, 20. August 2022 16:15
An: make-all/tuya-local ***@***.***>
Cc: Eckart0 ***@***.***>; Author ***@***.***>
Betreff: Re: [make-all/tuya-local] Add additional items for tuya power meter (Issue #223)

 

They could potentially be used directly by the Energy monitor instead of setting up an Integration sensor. Until now, all the devices that provide a Wh reading have reset the counter automatically after submitting to the cloud, so they mostly just read 0 locally unless you catch it as it updates to 1 and the cloud submission is in progress. But if it has a "today" reading, or a total that does not reset, that should be usable.

**Comment by Eckart0** [comment]
I am sending you the datasheet of the power meter - it is a standard Tuya power meter for DIN rail - and the list of DPs offered in your configuration dialogue. I will try to comment on the DPs; it will be of little use like this.
Anyway, the Tuya Cloud offers Wh today and Wh total. If you could add these Itmems to the configuration dialogue, then you can assign the DPs manually, just like the three previous ones.
Greetings, Eckart


Translated with www.DeepL.com/Translator (free version)

<img width="480" alt="20220820 20_43_34-Einstellungen – Home Assistant" src="https://user-images.githubusercontent.com/29716849/185761836-423fc514-aa4b-43d5-a0db-eb70c770cc1f.png">

[Pool Stromzähler Tuya WiFi TO-Q-SY1-Manual.pdf](https://github.com/make-all/tuya-local/files/9387845/Pool.Stromzahler.Tuya.WiFi.TO-Q-SY1-Manual.pdf)

**Comment by make-all** [comment]
The screenshot seems to be from another integration, not this one.
But if the scrollbar is hiding a 42 (string value) then I think this should match the smartplugv2_energyv2 config.

**Comment by Eckart0** [comment]
Hello,
Ashes on my head and sorry for this stupid mistake: With your integration, everything works wonderfully. 
I had installed "localtuya" - there are all the problems described - and not "tuyalocal".
Many greetings, Eckart
