### ISSUE TITLE
Unable to connect Tera W01 / Misidentified as Waterleak sensor

### ISSUE THREAD

**Issue by Thomas-Wimmer** [make-all/tuya-local#2236]
**Describe the bug**
Trying to add Tera W01 EV charger results in "Unable to connect" with Tuya protcol version 3.3 and 3.2.
With protocol 3.4, it was misidentified as a "zigbee_waterleak_sensor".

**To Reproduce**
Hmm, trying to add my Tera W01 EV charger? Don't know from your side...

**Expected behavior**
Well, adding the EV charger as an EV charger.

**Additional context**

```
2024-08-22 19:44:36.060 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches zigbee_waterleak_sensor with quality of 7%. DPS: {"updated_at": 1724348669.7100224, "3": "charger_free", "4": 16, "9": 0, "10": 0, "13": "controlpi_12v", "18": false, "23": "B4_V1.0.0", "24": 28, "101": 83, "103": 0, "104": 0, "105": false, "106": 0, "109": "temC"}

```

Followed the guide to open a Tuya developer account, added my devices (I have a Tuya smart plug named "DSL" and the aforementioned Tera EV charger. Both are visible in the developer account, and adding the smart plug worked.
Both Tuya devices are in their own IoT WIFI network, so discovery does not work, supplying the IP address manuelly does work with the smart plug, and it seems to work (?) for the EV charger.

If the bug involves a device, then please include device diagnostics from
Logfile attached. I treid my best to sanitize it (removing all the non-tuya stuff), may have missed something.

Please check if there are messages from Tuya Local in the Home
Added as screenshot (8.png)

See the screenshots.
[home-assistant_tuya_local_2024-08-22T18-20-33.912Z - Kopie.log](https://github.com/user-attachments/files/16732035/home-assistant_tuya_local_2024-08-22T18-20-33.912Z.-.Kopie.log)
![1](https://github.com/user-attachments/assets/8e260244-0bd0-40aa-a2f5-9a2d2fc26e1f)
![2](https://github.com/user-attachments/assets/a2c3e1f8-879c-4ff4-a00c-febee36651ff)
![3](https://github.com/user-attachments/assets/b7abf274-cee7-4d2d-9381-064f7398c197)
![4](https://github.com/user-attachments/assets/c5b568d4-9197-4e69-bc0d-04b0dd69aba9)
![5a](https://github.com/user-attachments/assets/56815160-21e7-47bc-b69d-557cdc9defe2)
![5b](https://github.com/user-attachments/assets/40df22ab-1e74-476f-a628-ac23e9fea0f2)
![6](https://github.com/user-attachments/assets/49f7665f-639d-4a59-9e55-ac3bc948496a)
![7](https://github.com/user-attachments/assets/9a9768c2-af9f-4b74-837c-912e4cc261e3)
![8](https://github.com/user-attachments/assets/2567857b-2ac9-45ef-a2f9-be2a6f1c4403)

**Comment by Thomas-Wimmer** [comment]
![9](https://github.com/user-attachments/assets/f4439619-94ac-4b2f-b113-2ba84705c78f)

**Comment by mat1990dj** [comment]
Hello, I have another charger that is being identified as a waterleak sensor,
`Device matches zigbee_waterleak_sensor with quality of 14%. DPS: {"updated_at": 1724776719.0935721, "3": "charger_free", "4": 32, "9": 0, "10": 0, "14": "charge_now", "18": true, "23": "V1"}`

Device details:
`{
  "result": {
    "category": "qccdz",
    "functions": [
      {
        "code": "charge_cur_set",
        "dp_id": 4,
        "type": "Integer",
        "values": "{\"unit\":\"A\",\"min\":6,\"max\":48,\"scale\":0,\"step\":1}"
      },
      {
        "code": "work_mode",
        "dp_id": 14,
        "type": "Enum",
        "values": "{\"range\":[\"charge_now\",\"charge_pct\",\"charge_energy\",\"charge_schedule\"]}"
      },
      {
        "code": "switch",
        "dp_id": 18,
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "lang_config": {},
    "status": [
      {
        "code": "work_state",
        "dp_id": 3,
        "type": "Enum",
        "values": "{\"range\":[\"charger_free\",\"charger_insert\",\"charger_free_fault\",\"charger_wait\",\"charger_charging\",\"charger_pause\",\"charger_end\",\"charger_fault\"]}"
      },
      {
        "code": "charge_cur_set",
        "dp_id": 4,
        "type": "Integer",
        "values": "{\"unit\":\"A\",\"min\":6,\"max\":48,\"scale\":0,\"step\":1}"
      },
      {
        "code": "power_total",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"kW\",\"min\":0,\"max\":99999999,\"scale\":3,\"step\":1}"
      },
      {
        "code": "work_mode",
        "dp_id": 14,
        "type": "Enum",
        "values": "{\"range\":[\"charge_now\",\"charge_pct\",\"charge_energy\",\"charge_schedule\"]}"
      },
      {
        "code": "switch",
        "dp_id": 18,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "charge_energy_once",
        "dp_id": 25,
        "type": "Integer",
        "values": "{\"unit\":\"kW·h\",\"min\":1,\"max\":999999,\"scale\":2,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1724777647627,
  "tid": "f9834231649411ef9454ee2b227aae0d"
}`

**Comment by mat1990dj** [comment]
so DPs:
{"3":"Work State",
"4":"Charge Current Set",
"6":"Phase A",
"7":"Phase B",
"8":"Phase C"
,"9":"Total power",
"10":"Fault"
,"14":"Work Mode",
"18":"Switch",
"19":"Schedule charging"
,"23":"System version",
"25":"Once Charge Energy"}
