### ISSUE TITLE
Error after upgrading Home Assistant from 2024.5.4 to 2024.8.3

### ISSUE THREAD

**Issue by stueri** [make-all/tuya-local#2246]
After the Home Assistant upgrade from 2024.5.4 to 2024.8.3 I get an error about a call tot sleep (see log below)

The Tuya Local integration now shows a connection problem on the 2 devices in use: 
W'Eau pool heatpump & Fairland InverterPlus Pool Heatpump. 

Rolling back to previous version 2024.5.4 fixes the issue. Tried 2x. Problem persists

Error message (sorry; in Dutch): 

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.tuya_local.device
Bron: custom_components/tuya_local/device.py:80
integratie: Tuya Local (documentatie, problemen)
Eerst voorgekomen: 14:35:57 (8 gebeurtenissen)
Laatst gelogd: 14:36:54

<class 'RuntimeError'>: Caught blocking call to sleep with args (0.1,) inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/device.py, line 77: self._api = tinytuya.Device(dev_id, address, local_key). (offender: /usr/local/lib/python3.12/site-packages/tinytuya/core.py, line 944: time.sleep(0.1)), please create a bug report at https://github.com/make-all/tuya-local/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#sleep while initialising device 20230712a4e57c1a0f33
<class 'RuntimeError'>: Caught blocking call to sleep with args (0.1,) inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/device.py, line 77: self._api = tinytuya.Device(dev_id, address, local_key). (offender: /usr/local/lib/python3.12/site-packages/tinytuya/core.py, line 944: time.sleep(0.1)), please create a bug report at https://github.com/make-all/tuya-local/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#sleep while initialising device 24074082ecfabc6ae06d

**Comment by make-all** [comment]
Before reporting such a bug, please make sure you are using the latest version of tuya-local
