### ISSUE TITLE
Error when adding device "Unable to connect"

### ISSUE THREAD

**Issue by roja45** [make-all/tuya-local#225]
Hello,

I get the error in the screenshot when I try to add a device, details are correct.  

Version: 0.18.2

Error:
![Screenshot 2022-08-28 121819](https://user-images.githubusercontent.com/19314911/187221240-38ba26d0-a3bc-437c-abf0-beb451566a14.png)

Log: 
![image](https://user-images.githubusercontent.com/19314911/187227044-c0563bd1-8e1f-4ee0-9635-3170009c3373.png)

Thanks

**Comment by make-all** [comment]
Do you have a Tuya app open?  Tuya devices generally only support local control by one source at a time.

**Comment by roja45** [comment]
Hello,
I wasn't aware of that, I have them connected to the local tuya integration that I am trying to replace, since that project seems abandoned.
I was using it to get the IP address of the device, as I am not sure how else to identify which ip address is for which device (since I have about 20 of them).

I will try disconnecting them.

Thanks

**Comment by make-all** [comment]
rospogrigio/localtuya released 4.0.2 6 hours ago, you may be looking at an abandoned fork, that one seems to be the most popular and active fork of localtuya.

**Comment by make-all** [comment]
I'm going to assume that the connection issue was solved or you found the maintained localtuya fork and are using that.

**Comment by kevvar** [comment]
> Do you have a Tuya app open? Tuya devices generally only support local control by one source at a time.

This situation applies if I have The devices conected to Alexa? So, do I have to disconect from Alexa, google, etc, to pair my devices on tuya local?

**Comment by make-all** [comment]
I think Alexa and Google integration should be via the Tuya cloud, not local connection, but if you still have connection issues and that is all that is left, then it might still be worth trying.  Connection of Alexa and Google via Home Assistant is also an option, so you would not be losing any functionality.

**Comment by met67** [comment]
> Hello, I wasn't aware of that, I have them connected to the local tuya integration that I am trying to replace, since that project seems abandoned. I was using it to get the IP address of the device, as I am not sure how else to identify which ip address is for which device (since I have about 20 of them).
> 
> I will try disconnecting them.
> 
> Thanks

@make-all maybe you could mention in the README that you can't use this integrantion and [rospogrigio/localtuya](https://github.com/rospogrigio/localtuya/) at the same time for the same device...

**Comment by Allu95** [comment]
> Hello, I wasn't aware of that, I have them connected to the local tuya integration that I am trying to replace, since that project seems abandoned. I was using it to get the IP address of the device, as I am not sure how else to identify which ip address is for which device (since I have about 20 of them).
> 
> I will try disconnecting them.
> 
> Thanks

Hi, did you solve the problem? I had local tuya integration before and now I am unable to connect to the device.
