### ISSUE TITLE
Request support for Cecofry 5500 connected

### ISSUE THREAD

**Issue by ap20132022** [make-all/tuya-local#2261]
### Log message

```text
Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:483
integration: tuya_local (documentation, issues)
First occurred: 9:12:12 PM (4 occurrences)
Last logged: 9:24:13 PM

Device matches None with quality of 0%. DPS: {"updated_at": 1725045124.1720564, "2": false, "3": "pizza", "5": "standby", "6": 180, "9": 10, "10": 10, "13": false}
Device matches None with quality of 0%. DPS: {"updated_at": 1725045539.0235984, "2": false, "3": "pizza", "5": "standby", "6": 180, "9": 10, "10": 10, "13": false}
Device matches None with quality of 0%. DPS: {"updated_at": 1725045604.9008543, "2": false, "3": "pizza", "5": "standby", "6": 180, "9": 10, "10": 10, "13": false}
Device matches None with quality of 0%. DPS: {"updated_at": 1725045848.5533803, "2": false, "3": "pizza", "5": "standby", "6": 180, "9": 10, "10": 10, "13": false}
```

### DPS information

```text
{
"result": {
"model": "{"modelId":"000004f7hd","services":[{"actions":[],"code":"","description":"","events":[],"name":"默认服务","properties":[
{"abilityId":1,"accessMode":"rw","code":"switch","description":"","extensions":{"iconName":"icon-dp_power2","attribute":"1152"},"name":"开关","typeSpec":{"type":"bool"}},
{"abilityId":2,"accessMode":"rw","code":"start","description":"","extensions":{"iconName":"icon-dp_play","attribute":"1152"},"name":"启动","typeSpec":{"type":"bool"}},
{"abilityId":3,"accessMode":"rw","code":"mode","description":"可增减枚举值，修改后需到App面板-编辑重新上传图标样式。","extensions":{"iconName":"icon-dp_mode","attribute":"1152"},"name":"烹饪模式","typeSpec":{"type":"enum","range":["pizza","fries","chicken","shrimp","fish","chicken_drumsticks","vegetables","desserts","none"]}},
{"abilityId":5,"accessMode":"ro","code":"status","description":"待机 烹饪中 烹饪完成 锅抽出 步骤1完成 步骤2完成...","extensions":{"iconName":"icon-zhuangtai","attribute":"1152","trigger":"direct"},"name":"工作状态","typeSpec":{"type":"enum","range":["standby","cooking","done","door_open","1_done","2_done","3_done","4_done","5_done","6_done","7_done","8_done","9_done","10_done"]}},
{"abilityId":6,"accessMode":"rw","code":"cook_temperature","description":"","extensions":{"iconName":"icon-dp_temp","attribute":"1152"},"name":"烹饪温度","typeSpec":{"type":"value","max":200,"min":80,"scale":0,"step":5,"unit":"℃"}},
{"abilityId":9,"accessMode":"rw","code":"cook_time","description":"","extensions":{"iconName":"icon-dp_time3","attribute":"1152"},"name":"烹饪时间","typeSpec":{"type":"value","max":60,"min":1,"scale":0,"step":1,"unit":"min"}},
{"abilityId":10,"accessMode":"ro","code":"remain_time","description":"","extensions":{"iconName":"icon-dp_time2","attribute":"1152"},"name":"剩余时间","typeSpec":{"type":"value","max":360,"min":0,"scale":0,"step":1,"unit":"min"}},
{"abilityId":11,"accessMode":"rw","code":"multistep","description":"01 -- 当前步骤 /第二步 \n\n00 -- 步骤1 \n03 -- dp 点的个数 (时间，模式，温度) cookArgs 的长度\n03 -- dpId\n0004 -- dpValue\n03 -- dpId\n0004 -- dpValue\n03 -- dpId\n0004 -- dpValue\n00 -- 是否执行完成(00：未开始执行的 01：执行已完成 02：执行到一半跳过的)\n00 -- 步骤动作(等待加料(00) 下一步 (01))\n\n0100030300040300040300040000","extensions":{"iconName":"icon-dp_direction","attribute":"1152"},"name":"多步骤执行","typeSpec":{"type":"raw","maxlen":128}},
{"abilityId":12,"accessMode":"ro","code":"fault","description":"","extensions":{"iconName":"icon-baojing","scope":"fault","attribute":"1152"},"name":"故障告警","typeSpec":{"type":"bitmap","label":["ntc_fault"],"maxlen":1}},
{"abilityId":13,"accessMode":"rw","code":"pause","description":"","extensions":{"iconName":"icon-dp_pause","attribute":"1152"},"name":"暂停/继续","typeSpec":{"type":"bool"}},
{"abilityId":22,"accessMode":"rw","code":"cloud_recipe_id","description":"无需云食谱功能则不用选择，根据实际需要选择使用；\n设备收到后回复即可","extensions":{"iconName":"icon-dp_cloud"},"name":"云食谱ID","typeSpec":{"type":"raw","maxlen":128}},
{"abilityId":23,"accessMode":"rw","code":"cooking_history_id","description":"根据实际需要选择使用，设备主动上报食谱id，App生成一条烹饪记录","extensions":{"iconName":"icon-dp_cloud"},"name":"烹饪历史ID","typeSpec":{"type":"raw","maxlen":128}},
{"abilityId":101,"accessMode":"ro","code":"device_version","description":"","name":"设备版本","typeSpec":{"type":"string","maxlen":255}}]}]}"
},
"success": true,
"t": 1725093405104,
"tid": "27a07ea4677411ef88b02ac421ecbce6"
}
```

### Product ID

<details><summary>xxwvfk9qrn56r4n6</summary>

```text
"model": "Cecofry 5500 Connected",
    "name": "Cecofry 5500 Connected",
    "product_id": "xxwvfk9qrn56r4n6",
    "product_name": "Cecofry 5500 Connected",
    "sub": false,
    "time_zone": "+02:00",
    "update_time": 1725042169,
    "uuid": "e52be3d9a47e3c6b"
  },
  "success": true,
  "t": 1725044777125,
  "tid": "ef1169a0670211efb77736033862a1ba"
```

</details>

### Product Name

Cecofry 5500 Connected

### Information about how the device functions

Airfryer 
https://www.amazon.de/dp/B0BQ1QJJPH?ref=ppx_yo2ov_dt_b_fed_asin_title&th=1

**Comment by make-all** [comment]
I'm not sure where you got the device info that you have included, but it does not contain any dps info. Maybe in the same location you can find more info that lists the dps with their names and numeric ids, as well as range and scale info for numeric ones, and list of possible values for enums such as "pizza" and "standby".

**Comment by ap20132022** [comment]
> I'm not sure where you got the device info that you have included, but it does not contain any dps info. Maybe in the same location you can find more info that lists the dps with their names and numeric ids, as well as range and scale info for numeric ones, and list of possible values for enums such as "pizza" and "standby".

Oh sorry for my last post. 
Here are the information from "query things data model":
{
  "result": {
    "model": "{\"modelId\":\"000004f7hd\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"1152\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"start\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_play\",\"attribute\":\"1152\"},\"name\":\"启动\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":3,\"accessMode\":\"rw\",\"code\":\"mode\",\"description\":\"可增减枚举值，修改后需到App面板-编辑重新上传图标样式。\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"attribute\":\"1152\"},\"name\":\"烹饪模式\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"pizza\",\"fries\",\"chicken\",\"shrimp\",\"fish\",\"chicken_drumsticks\",\"vegetables\",\"desserts\",\"none\"]}},{\"abilityId\":5,\"accessMode\":\"ro\",\"code\":\"status\",\"description\":\"待机 烹饪中 烹饪完成  锅抽出  步骤1完成 步骤2完成...\",\"extensions\":{\"iconName\":\"icon-zhuangtai\",\"attribute\":\"1152\",\"trigger\":\"direct\"},\"name\":\"工作状态\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"standby\",\"cooking\",\"done\",\"door_open\",\"1_done\",\"2_done\",\"3_done\",\"4_done\",\"5_done\",\"6_done\",\"7_done\",\"8_done\",\"9_done\",\"10_done\"]}},{\"abilityId\":6,\"accessMode\":\"rw\",\"code\":\"cook_temperature\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_temp\",\"attribute\":\"1152\"},\"name\":\"烹饪温度\",\"typeSpec\":{\"type\":\"value\",\"max\":200,\"min\":80,\"scale\":0,\"step\":5,\"unit\":\"℃\"}},{\"abilityId\":9,\"accessMode\":\"rw\",\"code\":\"cook_time\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time3\",\"attribute\":\"1152\"},\"name\":\"烹饪时间\",\"typeSpec\":{\"type\":\"value\",\"max\":60,\"min\":1,\"scale\":0,\"step\":1,\"unit\":\"min\"}},{\"abilityId\":10,\"accessMode\":\"ro\",\"code\":\"remain_time\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"attribute\":\"1152\"},\"name\":\"剩余时间\",\"typeSpec\":{\"type\":\"value\",\"max\":360,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"min\"}},{\"abilityId\":11,\"accessMode\":\"rw\",\"code\":\"multistep\",\"description\":\"01  -- 当前步骤 /第二步 \\n\\n00  -- 步骤1 \\n03   -- dp 点的个数 (时间，模式，温度) cookArgs 的长度\\n03  -- dpId\\n0004  -- dpValue\\n03  -- dpId\\n0004  -- dpValue\\n03  -- dpId\\n0004  -- dpValue\\n00 -- 是否执行完成(00：未开始执行的  01：执行已完成  02：执行到一半跳过的)\\n00 -- 步骤动作(等待加料(00) 下一步 (01))\\n\\n0100030300040300040300040000\",\"extensions\":{\"iconName\":\"icon-dp_direction\",\"attribute\":\"1152\"},\"name\":\"多步骤执行\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":12,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-baojing\",\"scope\":\"fault\",\"attribute\":\"1152\"},\"name\":\"故障告警\",\"typeSpec\":{\"type\":\"bitmap\",\"label\":[\"ntc_fault\"],\"maxlen\":1}},{\"abilityId\":13,\"accessMode\":\"rw\",\"code\":\"pause\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_pause\",\"attribute\":\"1152\"},\"name\":\"暂停/继续\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":22,\"accessMode\":\"rw\",\"code\":\"cloud_recipe_id\",\"description\":\"无需云食谱功能则不用选择，根据实际需要选择使用；\\n设备收到后回复即可\",\"extensions\":{\"iconName\":\"icon-dp_cloud\"},\"name\":\"云食谱ID\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":23,\"accessMode\":\"rw\",\"code\":\"cooking_history_id\",\"description\":\"根据实际需要选择使用，设备主动上报食谱id，App生成一条烹饪记录\",\"extensions\":{\"iconName\":\"icon-dp_cloud\"},\"name\":\"烹饪历史ID\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":101,\"accessMode\":\"ro\",\"code\":\"device_version\",\"description\":\"\",\"name\":\"设备版本\",\"typeSpec\":{\"type\":\"string\",\"maxlen\":255}}]}]}"
  },
  "success": true,
  "t": 1725093405104,
  "tid": "27a07ea4677411ef88b02ac421ecbce6"
}

**Comment by ap20132022** [comment]
Under "Device Debugging" I got: 

`Code	Type	Values
switch	Boolean	
"{true,false}"
start	Boolean	
"{true,false}"
mode	Enum	
{
  "range": [
    "shrimp",
    "fish"
  ]
}
cook_temperature	Integer	
{
  "unit": "℃",
  "min": 80,
  "max": 200,
  "scale": 0,
  "step": 5
}
cook_time	Integer	
{
  "unit": "min",
  "min": 1,
  "max": 60,
  "scale": 0,
  "step": 1
}
multistep	Raw	
{}
pause	Boolean	
"{true,false}"`
![Bildschirmfoto vom 2024-08-31 10-43-31](https://github.com/user-attachments/assets/2967e7ed-9ba6-47a0-8b44-efb42ecb4bc8)

**Comment by ap20132022** [comment]
it works now. Thank you very much @make-all 
Firstly I got problem with connecting. It showed always "unknown error".
After a while, I reinstall the add-on, connect it over app. And I can see and control everything
![image](https://github.com/user-attachments/assets/26bcebf5-b4e6-470d-8df6-2988f2d6207a)
