### ISSUE TITLE
Integration Setup Help

### ISSUE THREAD

**Issue by Merril-r** [make-all/tuya-local#227]
Hi All,

What am I doing wrong?

I added this repository and restarted HA. I can see the repository under HACS.

When I click on the repository and then click on the add repository link I get the error below:

Error
This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.

I can click on OK Then It ask me to enter the device id, local and Ip address.

When I click on submit. This error pops up.

Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect.

**Comment by make-all** [comment]
see #229
