### ISSUE TITLE
5 of 15 TUYA smart plugs reported "Migration Error" when changing from HA 2023.8.1 to HA 2024.8.3

### ISSUE THREAD

**Issue by Lutier2017** [make-all/tuya-local#2272]
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**
I have about 15 TUYA smart plugs.
In HA 2023.8.1 all plugs were working fine.
In HA 2024.8.3, 5 plugs are reporting "Migration Error".

**To Reproduce**
Issue can be reproduced any time HA re-start.

**Expected behavior**
It is expected that the referred 5 plugs should connect to HA ain the same way as all others..

**Additional context**
Logger: homeassistant.config_entries
Source: config_entries.py:943
First occurred: 23:11:32 (5 occurrences)
Last logged: 23:11:32

Error migrating entry lTSP-1-TR3 for tuya_local
Error migrating entry lTSP-3-AG for tuya_local
Error migrating entry lTSP-2-AS for tuya_local
Error migrating entry lTSP-1-TR2 for tuya_local
Error migrating entry lTSP-1-TR for tuya_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 943, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/__init__.py", line 418, in async_migrate_entry
    await async_migrate_entries(hass, entry.entry_id, update_unique_id13_2)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1627, in async_migrate_entries
    ent_reg.async_update_entity(entry.entity_id, **updates)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1170, in async_update_entity
    return self._async_update_entity(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1109, in _async_update_entity
    raise ValueError(
ValueError: Unique id 'ebab22410ed32cc2343gdy-binary_sensor_problem' is already in use by 'binary_sensor.ltsp_1_tr3_problem'

![image](https://github.com/user-attachments/assets/581531bc-280f-4d76-b473-3d7a5aa9d3f5)

**Comment by make-all** [comment]
It appears you have duplicate entities somehow. You will need to remove those devices and re-add them to clear up the device registry.

I can't really support upgrading issues from arbitrary ancient versions like this, so I won't look any further into it.

**Comment by Lutier2017** [comment]
Hi @make-all (Jason),
Thanks for your advice.
Now all my TUYA plugs are working.
