### ISSUE TITLE
Device Not Recognized: Aubess Smart Socket 20A/EM

### ISSUE THREAD

**Issue by mehdichaouch** [make-all/tuya-local#2273]
Hello @make-all,

First, thank you for this excellent integration — kudos to you and all the contributors!

After extensive research on Tuya, including reading forum posts and watching videos like [this one](https://youtu.be/R_8uypFHKTs), I decided to manually add my Aubess Smart Socket 20A/EM device. Using the information from the previous video, I mapped out the DPS configurations on paper.

However, I paused to continue searching using the `Product ID: 2iepauebcvo74ujc`. This led me to issue #294, where I discovered the `custom_components/tuya_local/devices/smartplugv2_energyv3.yaml` file. I was thrilled to see that my switch was supported — but unfortunately, it wasn't working as expected.

When I `Add a new device` I get this, super !
![image](https://github.com/user-attachments/assets/45a558c5-98a9-41c7-89fc-e5dba03b24fb)

Configuration continue with:
![image](https://github.com/user-attachments/assets/465befbf-2fa6-4b39-8fb4-caaaf67d8bc1)

It detect correctly the platform:
![image](https://github.com/user-attachments/assets/41d98adc-df86-45d5-be7b-0abd88f7764f)

Then I have to configure all the DPS one by one, setting the `Friendly name`
![image](https://github.com/user-attachments/assets/51637b5a-fe74-4470-a50a-aab96b49fe47)

Set the platform of the DPS:
![image](https://github.com/user-attachments/assets/71850691-ef11-4950-b857-2ded7d81f6ea)

If I select `Do not add any more entities`, the process ends with only one action, switch. Otherwise, I can continue by adding a new DPS, which I did. For the demonstration, I added DPS 18 for _current_.
![image](https://github.com/user-attachments/assets/38772e54-adba-4813-9ae3-5a8638380577)

The selection of entity type is not correct by default, it should be set with [this](https://github.com/make-all/tuya-local/blob/main/custom_components/tuya_local/devices/smartplugv2_energyv3.yaml#L69) as a sensor:
![image](https://github.com/user-attachments/assets/e9677382-6889-42e2-ac9b-26c43a445583)

Then if I open the device I have this, which is not good:
![image](https://github.com/user-attachments/assets/60e58fbd-5ee4-46f7-a23d-5a4c9e86fea6)

I tested the `Tuya integration`, at the end I had this (sorry it's in French):
![image](https://github.com/user-attachments/assets/73288760-528d-4048-ab3c-e37cce5a5620)

I see that Tuya Local offers more control over the device, but it requires manual configuration for everything, due to a bug (I suppose).

As a developer, I'm familiar with coding and would like to help get this integration working.
What steps should I take?

Best,

**Comment by make-all** [comment]
Incorrect venue for bug report for localtuya integration.

**Comment by mehdichaouch** [comment]
So fastest bug ever solved!

I understand my mistake I made a confusion between `tuya-local` and `localtuya` :man_facepalming:.


Maybe a notice in [bug report](https://github.com/make-all/tuya-local/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) template would avoid this ;)  

All is ok now :
![image](https://github.com/user-attachments/assets/0f769a37-c6c7-4928-989e-3e897a85209a)
