### ISSUE TITLE
incorrect relay operation logic TY-12Z

### ISSUE THREAD

**Issue by kuroxtyan** [make-all/tuya-local#2274]
Hello! When adding a device, only 8 relays out of 12 are available!
[config_entry-tuya_local-01J6RCF696EFVAH12QYX1CPJ0X.json](https://github.com/user-attachments/files/16887289/config_entry-tuya_local-01J6RCF696EFVAH12QYX1CPJ0X.json)

**Comment by kuroxtyan** [comment]
Device is TY-12Z relay
![S7f201fa91b7846dbada6d6aeab2dfa714 jpg_640x640](https://github.com/user-attachments/assets/4d97e5e3-7918-4a3d-a642-e40a3ad0bb40)

**Comment by make-all** [comment]
Not a bug. You are using a config for an 8 switch device.

**Comment by kuroxtyan** [comment]
> Not a bug. You are using a config for an 8 switch device.

Okay, that's right, but the system didn't offer a config for 12 switch device.
