### ISSUE TITLE
`Invalid handler specified` when adding integration 

### ISSUE THREAD

**Issue by Niek** [make-all/tuya-local#2279]
I see the following error when trying to add the integration:

![Screenshot_20240905-232016](https://github.com/user-attachments/assets/8072032c-76b4-4cc0-a9ad-20b61b52279d)

Latest git commit, running HA 2024.9.0.

**Comment by make-all** [comment]
There is no evidence that this message comes from this integration in your report, and as it is unreproducible, I can only close it.

**Comment by Niek** [comment]
Thanks, it turned out to be an issue with the custom components name. I used `tuya-local` instead of `tuya_local`. In case someone else experiences this error: check the directory name.
