### ISSUE TITLE
Request support for Loeffen LFIM6000 icecube maker

### ISSUE THREAD

**Issue by ekalle-swe** [make-all/tuya-local#2281]
### Log message

```text
Device matches desk_lamp with quality of 60%. DPS: {"updated_at": 1725618970.1236706, "1": false, "2": "big", "3": 0, "101": false, "102": false}
```

### DPS information

```text
{
  "result": {
    "model": "{\"modelId\":\"dxohpk\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"1024\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"mode\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"attribute\":\"1024\"},\"name\":\"模式\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"big\",\"small\"]}},
{\"abilityId\":3,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"E1缺水E2满冰，E3开盖\",\"extensions\":{\"iconName\":\"icon-baojing\",\"scope\":\"fault\",\"attribute\":\"1024\"},\"name\":\"故障告警\",\"typeSpec\":{\"type\":\"bitmap\",\"label\":[\"e1\",\"e2\",\"e3\"],\"maxlen\":3}},
{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"UV\",\"description\":\"\",\"name\":\"UV\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":102,\"accessMode\":\"rw\",\"code\":\"qingxie\",\"description\":\"\",\"name\":\"清洗模式\",\"typeSpec\":{\"type\":\"bool\"}}]}]}"
  },
  "success": true,
  "t": 1725612729221,
  "tid": "4ced9c0d6c2d11efbc016e7818a0f8a2"
}
```

### Product ID

2y44i6euwk9eeiz8

### Product Name

Loeffen LFIM6000

### Information about how the device functions

tried to add this as a standard switch device but can't get it to work properly and to bild a def file for it is beyond me.
Ice cube maker has these control switches for manual control and it looks like they are all reachable + error sensor 
Power switch
Switch to select cube size Large/Small
UV light switch
Cleaning mode switch

**Comment by ekalle-swe** [comment]
@make-all 
"awaiting confirmation"?
Is there something I should do?
Sorry, new to this. GitHub is for me a rather alien place.

**Comment by make-all** [comment]
It is just a tag to keep track of whether the completed issue is tested or not, to give others an idea of the maturity of the solution. Whether you want to test before it is released or not is up to you.

**Comment by ekalle-swe** [comment]
> It is just a tag to keep track of whether the completed issue is tested or not, to give others an idea of the maturity of the solution. Whether you want to test before it is released or not is up to you.

I'm really really surprised, in a positive way, of this process.
It was a huge hurdle, for a non developer, to be able fill in the form. Took me an hour to find the right info on tuya IoT and another hour to figure out what warning level log that was requested.
After that I thought "why should they even bother with my request? Surely not a common enough device to be interesting to support and if anything ever will happen, it's probly a yearlong process" and here I am, just 2 days later, with a ready integration!!
I'm truly impressed!!

**Comment by make-all** [comment]
A month ago, the pipeline was approaching two months, but over the past few weeks I've managed to completely clear the backlog of requests ready with full information, so was able to get to this within 2 days. Consider yourself lucky. 

I do try to encourage reports to include the full info, even though it can be difficult for newcomers to find all the info, because it does make adding devices easy. For those requests without all the info, there will be a lot of back and forward testing needed, and a lot of guesswork, so those take a back seat to the requests that make my work easy, and over the past year, usage has grown to the point where I can only keep up with the high quality requests.

**Comment by ekalle-swe** [comment]
Not the last "request for support" from me.
Have some more devices, I got from my wife for Xmas, fathers day, birthday that she assumed should work, as it said "smart" on the box 🤣

**Comment by ekalle-swe** [comment]
Have imported file and reconnected the device. It picked up the correct integration and all basic functionality works. Trying it out through my automations and will come back with final confirmation.

**Comment by ekalle-swe** [comment]
Sorry to say, but 
Service switch.turn_off will only toggle the switch and so will switch.turn_on.
So it you run switch.turn_on 3 times in a row, the device will turn on, turn off, turn on.

**Comment by make-all** [comment]
This is odd. Is it new behaviour of HA 2024.9, or behaviour of the device?

**Comment by ekalle-swe** [comment]
Just tested service switch.turn_off several times on other switches e.g. smart power sockets and it does not toggle. They will stay off.
