### ISSUE TITLE
Request support for Cleverio AP100 Air Purifier

### ISSUE THREAD

**Issue by ekalle-swe** [make-all/tuya-local#2284]
### Log message

```text
Device matches kesser_infrared_heater with quality of 33%. DPS: {"updated_at": 1725870397.5351033, "1": false, "4": "2", "5": 59, "8": true, "19": "cancle", "22": "1"}
```

### DPS information

```text
{
  "result": {
    "model": "{\"modelId\":\"0000004jt6\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"1\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":4,\"accessMode\":\"rw\",\"code\":\"speed\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-a_fan_low\",\"attribute\":\"4\"},\"name\":\"风速\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"1\",\"2\",\"3\",\"4\"]}},
{\"abilityId\":5,\"accessMode\":\"ro\",\"code\":\"filter\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_wet2\"},\"name\":\"滤芯使用率\",\"typeSpec\":{\"type\":\"value\",\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"％\"}},
{\"abilityId\":8,\"accessMode\":\"rw\",\"code\":\"light\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_light\"},\"name\":\"灯光\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":19,\"accessMode\":\"rw\",\"code\":\"countdown\",\"description\":\"取消/1/2/4/8H\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"attribute\":\"4\"},\"name\":\"倒计时\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"cancle\",\"1\",\"2\",\"3\",\"4\"]}},
{\"abilityId\":22,\"accessMode\":\"ro\",\"code\":\"air_quality\",\"description\":\"\",\"name\":\"空气质量\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"1\",\"2\",\"3\",\"4\"]}}]}]}"
  },
  "success": true,
  "t": 1725869388032,
  "tid": "e18131586e8211efbc016e7818a0f8a2"
}
```

### Product ID

6bspwvsqhl4vuanj

### Product Name

Cleverio Air Purifier AP100

### Information about how the device functions

A air purifier that's strangely enough got identified as a "kesser_infrared_heater" by TuyaLocal

Basic functionality
Power switch	on/off
Fan speed	1-4	
Background light	Switch on/off (colour can be selected on buttons but Tuya off integration did not support that	
Duration timer 1-4	
Filter life left % 0-100
Child lock

Link to pdf manual https://manuals.plus/cleverio/ap100-air-purifier-manual-2.pdf

**Comment by ekalle-swe** [comment]
Tnx, mate!
Works brilliantly.

Btw.
Can I remove the things I've added here from SmartTuya/Tuya IoT or are you still dependent on the cloud to some extent?
![Screenshot_20240912_085753](https://github.com/user-attachments/assets/a60602c1-56ed-4e49-a7aa-e8f352c9e188)

**Comment by make-all** [comment]
It depends what you mean by "remove".
There is no dependency on the built in cloud tuya integration in HA, so you can remove any device you had set up in HA from there.
But the local connection is dependent on the local key remaining constant, so you cannot unpair the device from the Tuya app.

**Comment by ekalle-swe** [comment]
Understood! 

Tnx, mate!

**Comment by ekalle-swe** [comment]
Just noticed.
If you look at my screenshot before and after light was added, you see that the unit (%) has gone missing in the new config.
Not important right now but should maybe be fixed before release.

**Comment by make-all** [comment]
Strange. The unit is still there in the config file.

**Comment by ekalle-swe** [comment]
I know!
Had to check and recheck so I cut&pasted it correctly and it's there and looks ok in my local file as well.
![Screenshot_20240912_135601](https://github.com/user-attachments/assets/bd5c8425-0391-4adb-8668-f37da5f95dfb)

**Comment by ekalle-swe** [comment]
Btw, I can now confirm this one as well.
Must have been cache problems.
It's working fine now!
