### ISSUE TITLE
A device works on one instance of HA but not on another

### ISSUE THREAD

**Issue by kohend** [make-all/tuya-local#2286]
**Describe the bug**
Adding a plug with power measurement option gives an unknown error on one HA instance (core with python installed via pyenv) and works on another (core docker container) 

**To Reproduce**
Added a device (tried manually given info and auto detected via app), the logs indicate a 100% match top a device, but I get an unknown device error (smartplugv2_energyv2)

**Expected behavior**
The device is successfully added

**Additional context**
It may be related to the fact the failed test is running on a Celron from 2007, I saw a blocking warning before
I'm a Python developer, if given context and some information on the area of the code I should look at, I may be able to try to fix it myself.
Non working instance is running 2024.8.3 and tuya_local from 24 hours ago, working one is running 2024.7.2 and tuya-local from today.

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"
[tuya_local-01J7C5XVKPQMXP8B768YYB486X-Energy monitoring smartplug-334c36de0b73a71b5525d38619447c0f.json](https://github.com/user-attachments/files/16936264/tuya_local-01J7C5XVKPQMXP8B768YYB486X-Energy.monitoring.smartplug-334c36de0b73a71b5525d38619447c0f.json)

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.
[tuya_local.log](https://github.com/user-attachments/files/16936283/tuya_local.log)

**Comment by make-all** [comment]
Bug reports can only be accepted for releases, or current HEAD. 

It is quite likely there was a bug 24 hours ago, as there are a few commits which failed CI tests in the recent history.

**Comment by kohend** [comment]
Thanks, 2024.9.0 works!
