### ISSUE TITLE
WiFi smart online 8 in 1 tester (bf096784fbb3ffe198prtk) - No pH

### ISSUE THREAD

**Issue by demsarinic** [make-all/tuya-local#2294]
Device don't get the pH-Sensor.
On Tuya Developer Platform and in the Smartlife-App the value is shown.

[tuya_local-01J7EMJDH2CB7KF7VBNDBB4J87-Whirlpool Wasserwerte-01f9f5582bb652c5beb31bdc06e3fccd.json](https://github.com/user-attachments/files/16958873/tuya_local-01J7EMJDH2CB7KF7VBNDBB4J87-Whirlpool.Wasserwerte-01f9f5582bb652c5beb31bdc06e3fccd.json)

![Screenshot 2024-09-11 081848](https://github.com/user-attachments/assets/6caf1df1-118e-4b5c-a525-6b0d0ba86dcc)
![Screenshot 2024-09-11 083129](https://github.com/user-attachments/assets/b1399ee9-b3ea-4a72-9c53-3018e19fda78)

THANKS

**Comment by make-all** [comment]
pH should be in the range (acid) 0 - 14 (alkaline). These devices use a value of 15 to indicate no valid reading, which is what your device is sending. It may show in the Tuya app as 15, but this integration translates it to "None" to better reflect the actual condition.

**Comment by demsarinic** [comment]
Thank you!!!
