### ISSUE TITLE
[New device request] NHZS-WA2通断器 101,104 新模块

### ISSUE THREAD

**Issue by Shagrat2** [make-all/tuya-local#230]
DIY WiFi Smart Light Switch Universal Breaker Timer Wireless Remote Control

https://aliexpress.ru/item/32912809006.html?spm=a2g2w.orderdetails.0.0.136b4aa6BBF7uy&sku_id=65951849037

```
{
  "result": {
    "category": "kg",
    "functions": [
      {
        "code": "switch_1",
        "desc": "{}",
        "name": "开关1",
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "name": "开关1",
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },
  "success": true,
}
```

```
[
  {
    "code": "switch_1",
    "value": true
  }
]
```
Please add this to integration

**Comment by make-all** [comment]
Hi, this looks like it should be supported already by the simple_switch configuration.

But there is no local protocol information above, so I may be mistaken.  If it is not working, please follow the instructions in README.md to get the information from Home Assistant log and Tuya IoT portal.  It is important to choose the correct function in API Explorer of Tuya portal, as others do not return local information.

**Comment by Shagrat2** [comment]
Sorry everything works great. 
An obsolete device key was written in notepad
