### ISSUE TITLE
Vacuum Smart 700 - Can't start cleaning

### ISSUE THREAD

**Issue by cvroque** [make-all/tuya-local#2302]
**Describe the bug**
When I use HA to start cleaning the integration won't change the current command, so the vacuum doesn't start.

**To Reproduce**
After having the the vacuum added, here is the status when it's charging:
![image](https://github.com/user-attachments/assets/aaf6aaa9-4cf6-4bc2-9d93-8cb8b424ca98)
And here it is after I press 'Start Cleaning':
![image](https://github.com/user-attachments/assets/86742b40-4a20-4fbe-a274-a4e638e52c00)
'Activate' changed to true, while the 'Command' remained the same.

**Expected behavior**
I expect the command (DP3) to change to 'Smart'. 

**Additional context**
This used to work about 3 months ago, but in the meantime I sent my vacuum for repairs and now that it came back with the updated integration this behavior has appeared.
This is also an issue in the default HA integration, but there I'm able to manually change the command while it is not available with this integration.

Diagnostic: [tuya_local-01J7GMRHP2K3S3K9E74S4BD34M-Robotnik-47ca15c70833a3db47d47ad5bab6c958.json](https://github.com/user-attachments/files/16993122/tuya_local-01J7GMRHP2K3S3K9E74S4BD34M-Robotnik-47ca15c70833a3db47d47ad5bab6c958.json)

Logs: 
[home-assistant_tuya_local_2024-09-13T11-20-00.176Z.log](https://github.com/user-attachments/files/16993180/home-assistant_tuya_local_2024-09-13T11-20-00.176Z.log)

Thanks in advance!

**Comment by cvroque** [comment]
I suspect this is related but I'm not sure on how to fix this:
https://github.com/make-all/tuya-local/commit/a7820d8d922aec3694dca4ccc1729801db9c5ce2

**Comment by make-all** [comment]
There isn't really any standard way for vacuums to work, so I don't know exactly what needs to be done here. It is not normal to automatically send the smart command when toggling on, and I don't think that can be done easily.

**Comment by cvroque** [comment]
Thanks for the reply! 
Would it be acceptable to expose an select entity for this vacuum model with the command?
![image](https://github.com/user-attachments/assets/5ea31b51-64b5-498e-a9c7-af412726392c)
 If you're okay with that, I can open the PR.
Then I should be able to circumvent this issue in the same manner as the default cloud integration.

**Comment by make-all** [comment]
A better option would be to add a button to your UI that performs the sequence of actions needed to actually start a clean. The vacuum.send_command action is still available as a service, even if the command is not exposed in the default UI.

**Comment by make-all** [comment]
Nothing changed in the config for more than 1 year, so I suspect that when your vacuum was away for repairs, it was given a firmware upgrade that changed its behaviour.

**Comment by cvroque** [comment]
> A better option would be to add a button to your UI that performs the sequence of actions needed to actually start a clean. The vacuum.send_command action is still available as a service, even if the command is not exposed in the default UI.

Thanks for mentioning the send_command service, with this there's no need for new entities. That is enough to fix my issue, thanks a lot!

And yeah, this model works nice but it's a lemon in terms of software.
