### ISSUE TITLE
Request support for Könighaus M1000 Infrared heating

### ISSUE THREAD

**Issue by hermann1514** [make-all/tuya-local#2327]
### Log message

```text
2024-09-23 08:27:19.798 WARNING (MainThread) [custom_components.tuya_local.device] Infrarot Heizung  receive loop has terminated
2024-09-23 08:27:19.799 INFO (MainThread) [custom_components.tuya_local.device] Deleting device: bffd13b3ead6151905ayc1
2024-09-23 08:27:19.800 INFO (SyncWorker_21) [custom_components.tuya_local.device] Creating device: bffd13b3ead6151905ayc1
2024-09-23 08:27:19.802 INFO (MainThread) [homeassistant.components.climate] Setting up tuya_local.climate
2024-09-23 08:27:19.804 INFO (MainThread) [custom_components.tuya_local.device] Setting protocol version for Infrarot Heizung to 3.4
```

### DPS information

```text
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.9.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.4",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "6.6.46-haos",
    "supervisor": "2024.09.1",
    "host_os": "Home Assistant OS 13.1",
    "docker_version": "26.1.4",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "dwd": {
      "documentation": "https://github.com/hg1337/homeassistant-dwd#readme",
      "version": "2024.9.0",
      "requirements": [
        "defusedxml==0.7.1"
      ]
    },
    "ws980wifi": {
      "documentation": "https://github.com/patschbo/ws980wifi/",
      "version": "0.1.9",
      "requirements": []
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "2.0.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "mbapi2020": {
      "documentation": "https://github.com/ReneNulschDE/mbapi2020",
      "version": "v0.18.1",
      "requirements": [
        "protobuf>=3.19.1"
      ]
    },
    "nodered": {
      "documentation": "https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/custom_integration/",
      "version": "4.1.0",
      "requirements": []
    },
    "openmediavault": {
      "documentation": "https://github.com/tomaae/homeassistant-openmediavault",
      "version": "0.0.0",
      "requirements": []
    },
    "scheduler": {
      "documentation": "https://github.com/nielsfaber/scheduler-component",
      "version": "v0.0.0",
      "requirements": []
    },
    "remote_homeassistant": {
      "documentation": "https://github.com/custom-components/remote_homeassistant",
      "version": "4.2",
      "requirements": []
    },
    "ytube_music_player": {
      "documentation": "https://github.com/KoljaWindeler/ytube_music_player",
      "version": "20240810.01",
      "requirements": [
        "ytmusicapi==1.8.0",
        "pytube==15.0.0",
        "integrationhelper==0.2.2"
      ]
    },
    "miele": {
      "documentation": "https://github.com/astrandb/miele",
      "version": "2024.9.0b1",
      "requirements": [
        "flatdict==4.0.1",
        "pymiele==0.1.7"
      ]
    },
    "volkswagencarnet": {
      "documentation": "https://github.com/robinostlund/homeassistant-volkswagencarnet",
      "version": "v5.0.3",
      "requirements": [
        "pytz",
        "volkswagencarnet==5.0.2"
      ]
    },
    "mass": {
      "documentation": "https://music-assistant.io",
      "version": "2024.9.1",
      "requirements": [
        "music-assistant==2.2.4"
      ]
    },
    "tuya_local": {
      "documentation": "https://github.com/make-all/tuya-local",
      "version": "2024.9.0",
      "requirements": [
        "tinytuya==1.15.1",
        "tuya-device-sharing-sdk>=0.1.9,<=0.2.99"
      ]
    },
    "homematicip_local": {
      "documentation": "https://github.com/danielperna84/custom_homematic",
      "version": "1.65.0",
      "requirements": [
        "hahomematic==2024.8.13"
      ]
    },
    "better_thermostat": {
      "documentation": "https://github.com/KartoffelToby/better_thermostat",
      "version": "1.6.0",
      "requirements": []
    },
    "powercalc": {
      "documentation": "https://docs.powercalc.nl",
      "version": "v1.14.8",
      "requirements": [
        "numpy>=1.21.1"
      ]
    },
    "watchman": {
      "documentation": "https://github.com/dummylabs/thewatchman",
      "version": "0.6.3",
      "requirements": [
        "prettytable==3.10.0"
      ]
    },
    "fontawesome": {
      "documentation": "https://github.com/thomasloven/hass-fontawesome",
      "version": "2.2.1",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "tuya_local",
    "name": "Tuya Local",
    "codeowners": [
      "make-all"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/make-all/tuya-local",
    "integration_type": "device",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/make-all/tuya-local/issues",
    "requirements": [
      "tinytuya==1.15.1",
      "tuya-device-sharing-sdk>=0.1.9,<=0.2.99"
    ],
    "version": "2024.9.0",
    "is_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 1.3242010027170181e-05
    },
    "01J8EQRGJ6PH1XDDMRR5PEA5G7": {
      "wait_import_platforms": -1.0919765690341592,
      "config_entry_setup": 1.1432723687030375
    }
  },
  "data": {
    "name": "Infrarot Heizung",
    "type": "hama_radiator_controller",
    "device_id": "**REDACTED**",
    "device_cid": "",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": 3.4,
    "tinytuya_version": "1.15.1",
    "api_version_set": 3.4,
    "api_version_used": 3.4,
    "api_working": true,
    "status": {},
    "cached_state": {
      "updated_at": 1727072465.9750304,
      "1": false,
      "2": "manual",
      "3": "manual",
      "16": 225,
      "24": 175,
      "101": false,
      "102": 180,
      "103": 220,
      "104": 50,
      "106": "online",
      "108": "heat",
      "111": 240,
      "112": 180,
      "113": 220,
      "114": 180,
      "115": 400,
      "116": 180,
      "117": 240,
      "118": false,
      "120": true
    },
    "pending_state": {},
    "connected": true,
    "force_dps": [],
    "home_assistant": {
      "name": "Infrarot Heizung",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "climate.infrarot_heizung",
            "state": "off",
            "attributes": {
              "hvac_modes": [
                "heat",
                "off"
              ],
              "min_temp": 5.0,
              "max_temp": 30.0,
              "target_temp_step": 0.5,
              "current_temperature": 18.0,
              "temperature": 22.0,
              "friendly_name": "Infrarot Heizung",
              "supported_features": 385
            },
            "last_changed": "2024-09-23T06:19:02.265958+00:00",
            "last_reported": "2024-09-23T06:19:02.265958+00:00",
            "last_updated": "2024-09-23T06:19:02.265958+00:00"
          }
        }
      ]
    }
  }
}
```

### Product ID

rufjdpbdogijhq89

### Product Name

Könighaus M1000 / in Cloud Name: W Modem

### Information about how the device functions

Only the Climate Entity is made available, which is then also not available.
The device can otherwise measure and set the temperature.
Switching on and off is available in the app, as are various programme modes, but these are not provided in HA.

**Comment by make-all** [comment]
There is insufficient information here to make any change

**Comment by hermann1514** [comment]
Which Infos do you need?

**Comment by hermann1514** [comment]
{
  "result": {
    "properties": [
      {
        "code": "switch",
        "custom_name": "",
        "dp_id": 1,
        "time": 1727072725720,
        "type": "bool",
        "value": false
      },
      {
        "code": "mode",
        "custom_name": "",
        "dp_id": 2,
        "time": 1726943080227,
        "type": "enum",
        "value": "manual"
      },
      {
        "code": "work_state",
        "custom_name": "",
        "dp_id": 3,
        "time": 1726943080223,
        "type": "enum",
        "value": "manual"
      },
      {
        "code": "temp_set",
        "custom_name": "",
        "dp_id": 16,
        "time": 1726949331980,
        "type": "value",
        "value": 225
      },
      {
        "code": "temp_current",
        "custom_name": "",
        "dp_id": 24,
        "time": 1727073661143,
        "type": "value",
        "value": 177
      },
      {
        "code": "week_program_5",
        "custom_name": "",
        "dp_id": 72,
        "time": 1726842557278,
        "type": "raw",
        "value": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
      },
      {
        "code": "relay_status",
        "custom_name": "",
        "dp_id": 101,
        "time": 1727072726449,
        "type": "bool",
        "value": false
      },
      {
        "code": "eco_mode_temp_heat",
        "custom_name": "",
        "dp_id": 102,
        "time": 1726842557324,
        "type": "value",
        "value": 180
      },
      {
        "code": "comfort_mode_temp_heat",
        "custom_name": "",
        "dp_id": 103,
        "time": 1726842557332,
        "type": "value",
        "value": 220
      },
      {
        "code": "holiday_mode_temp_heat",
        "custom_name": "",
        "dp_id": 104,
        "time": 1726842557335,
        "type": "value",
        "value": 50
      },
      {
        "code": "unpair_rf_thermostat",
        "custom_name": "",
        "dp_id": 105,
        "time": 1726840413540,
        "type": "bool",
        "value": false
      },
      {
        "code": "rf_thermostat_pair_status",
        "custom_name": "",
        "dp_id": 106,
        "time": 1726937175174,
        "type": "enum",
        "value": "online"
      },
      {
        "code": "clear_program_mode",
        "custom_name": "",
        "dp_id": 107,
        "time": 1726840413540,
        "type": "bool",
        "value": false
      },
      {
        "code": "heating_mode",
        "custom_name": "",
        "dp_id": 108,
        "time": 1726842557342,
        "type": "enum",
        "value": "heat"
      },
      {
        "code": "set_mode_settings_default",
        "custom_name": "",
        "dp_id": 109,
        "time": 1726840413540,
        "type": "bool",
        "value": false
      },
      {
        "code": "set_location_inside",
        "custom_name": "",
        "dp_id": 110,
        "time": 1726840413540,
        "type": "bool",
        "value": false
      },
      {
        "code": "location_inside_temp_heat",
        "custom_name": "",
        "dp_id": 111,
        "time": 1726842557345,
        "type": "value",
        "value": 240
      },
      {
        "code": "locationoutside_temp_heat",
        "custom_name": "",
        "dp_id": 112,
        "time": 1726842557347,
        "type": "value",
        "value": 180
      },
      {
        "code": "eco_mode_temp_cool",
        "custom_name": "",
        "dp_id": 113,
        "time": 1726842559382,
        "type": "value",
        "value": 220
      },
      {
        "code": "comfort_mode_temp_cool",
        "custom_name": "",
        "dp_id": 114,
        "time": 1726842557395,
        "type": "value",
        "value": 180
      },
      {
        "code": "holiday_mode_temp_cool",
        "custom_name": "",
        "dp_id": 115,
        "time": 1726842557397,
        "type": "value",
        "value": 400
      },
      {
        "code": "location_inside_temp_cool",
        "custom_name": "",
        "dp_id": 116,
        "time": 1726842557401,
        "type": "value",
        "value": 180
      },
      {
        "code": "locationoutside_temp_cool",
        "custom_name": "",
        "dp_id": 117,
        "time": 1726842557410,
        "type": "value",
        "value": 240
      },
      {
        "code": "window_open_status",
        "custom_name": "",
        "dp_id": 118,
        "time": 1726842590017,
        "type": "bool",
        "value": false
      },
      {
        "code": "rf_message",
        "custom_name": "",
        "dp_id": 119,
        "time": 1727074422239,
        "type": "raw",
        "value": "+/02ANIAsQUFAAC7AAA="
      },
      {
        "code": "user_mode_switch_status",
        "custom_name": "",
        "dp_id": 120,
        "time": 1726842557412,
        "type": "bool",
        "value": true
      }
    ]
  },
  "success": true,
  "t": 1727074590039,
  "tid": "f5e03a23797811efbc016e7818a0f8a2"
}
