### ISSUE TITLE
Unexpected Payload From Device

### ISSUE THREAD

**Issue by sshaikh** [make-all/tuya-local#2329]
**Describe the bug**

I'm trying to (re) add a Tuya smart socket that was previously working with TL but which I removed to test with the native app. As it needed a reset, a new local key (and device id?) have been ascertained already via development portal. The socket otherwise works fine in the Tuya app. Three other identical sockets still work (although they were not removed in the same way). The device is a Nooie PU13 UK smart socket.

**To Reproduce**
Try adding the device via both cloud and manual flows, using all types of protocol (restarting HA each time to avoid the "Device Key" error. The cloud flow detects the socket (as the only one not already added) but fails after populating the manual form.

**Expected behavior**
For the socket to be added.

**Additional context**
```
This error originated from a custom integration.

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:451
integration: Tuya Local (documentation, issues)
First occurred: 20:58:41 (1 occurrences)
Last logged: 20:58:41

Test protocol error 904: Unexpected Payload from Device
```

Interestingly the cloud flow populates the incorrect IP address. I'm not sure if this is related.

**Comment by make-all** [comment]
If the cloud flow populates an IP address, it is not incorrect.

**Comment by sshaikh** [comment]
Seems my static IPs were incorrect. No bug.
