### ISSUE TITLE
Unable to add C16 thermostat

### ISSUE THREAD

**Issue by PsychoMnts** [make-all/tuya-local#233]
I'm trying to add the C16 thermostat, but it reports "Sorry, there is no support for this device".
Log:

Device matches None with quality of 0%. DPS: {'2': 170, '3': 'Smart', '4': 0, '5': 245, '6': 350, '7': False, '8': 200, '9': False, '10': False, '11': False, '12': '5_1_1', '14': '0', '15': 0, '17': 0, '21': False, '22': 0, '23': 4, '24': 'Standby', 'updated_at': 1663097383.9795818}

**Comment by PsychoMnts** [comment]
I removed entity id number 26 and I was able to add the device.

**Comment by make-all** [comment]
OK, I will mark that one as optional.

**Comment by make-all** [comment]
DP 26 is now optional in 0.19.0, so your device should match now.
