### ISSUE TITLE
product_id: a1er7lposf6ctd0b unknown error occurred when attempting to add device

### ISSUE THREAD

**Issue by Gizmodious** [make-all/tuya-local#2330]
**Describe the bug**
	"Unknown error occurred" while trying to add a device. This is a wifi door sensor
	Model D06
	'product_id': 'a1er7lposf6ctd0b'
	https://www.amazon.com/gp/product/B0CG5HB1B6
	Attempting to add via cloud data pull; it finds the device id and key

**To Reproduce**
	At first I thought it was an issue with getting the IP address. Issue occurred while manually typing the IP address.
	Able to have Tuya Local find the IP address if playing with the contact in real time while its searching for the node.
	Not an IP issue

**Expected behavior**
	Turned on debugging and sorted through the logs. There seem to be some programming issues, so I figured id share.

**Additional context**
	Here are going to be some santized'ish sections of the log that appear to be related to tuya-local

	2024-09-23 14:48:42.125 DEBUG (MainThread) [custom_components.tuya_local.config_flow] Found: {'ip': 'XX.XX.XX.226', 'version': '3.4', 'id': 'SANITIZED', 'product_id': 'a1er7lposf6ctd0b', 'data': {'ip': 'XX.XX.XX.226', 'gwId': 'SANITIZED', 'active': 2, 'encrypt': True, 'productKey': 'SANITIZED', 'version': '3.4', 'token': True, 'wf_cfg': True, 'name': '', 'key': '', 'mac': '', 'id': 'eb73a3fe1eaace162fh56w', 'ability': 0, 'dev_type': 'default', 'origin': 'broadcast'}}

	Tuya Local Debug attached as text file
	Tuya Cloud Device Diagnostic is attached as text file

	I am able to successfully load and use Meso wall switches 2 & 3 Buttons with Tuya Local

**If the bug involves a device, then please include device diagnostics from
	unable to add the contact sensor to get to this stage where it is loaded in home assistant. i can provided the Tuya (cloud) version if that helps?

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.
	these logs are provided in an attached text file.

	please let me know if there are any tests or other datapoints you would like provided.

[tuya local debug mode while failure occured.txt](https://github.com/user-attachments/files/17105173/tuya.local.debug.mode.while.failure.occured.txt)
[Device Diagnostic of Tuya Cloud that failed to add to Tuya Local.txt](https://github.com/user-attachments/files/17105175/Device.Diagnostic.of.Tuya.Cloud.that.failed.to.add.to.Tuya.Local.txt)
![unknown error occured](https://github.com/user-attachments/assets/9ed2d32d-5ea4-4575-b864-f74db72e86b7)

**Comment by make-all** [comment]
Battery powered WiFi devices cannot be supported locally.

**Comment by Gizmodious** [comment]
That’s a pain. But I understand. Thanks for the great app/plugin for HA
