### ISSUE TITLE
[custom_components.tuya_local.device] Failed to fetch device status for Floodlight Veranda

### ISSUE THREAD

**Issue by geedsen** [make-all/tuya-local#2331]
**Describe the bug**
Log file is flooding with the above messages, thousands of them, causing HA to crash every now and then.
![image](https://github.com/user-attachments/assets/8f7aaf99-b289-4262-a05d-edf89184f704)

**To Reproduce**
No idea, how to reproduce. I did see others reporting this and it was mentioned that it may be a problem with either the wifi or wrong protocol version. 

**Expected behavior**
Errors should not be there, devices should work.

**Additional context**
All the devices dont work from tuya-local, but do work from regular Tuya in HA.  The protocols used for the devices are the ones Tuya-local suggested when the devices were added.

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

![image](https://github.com/user-attachments/assets/9aab4961-4348-46a6-8fb7-b1d2873fa5ee)

**Comment by make-all** [comment]
There is not enough detail given to diagnose what your problem might be.  You apparently got these devices set up once, but now they are failing. The debug log may show more details about the exact error that is preventing them from working.

**Comment by geedsen** [comment]
But still the errors occur, while the ip's are fixed now. The deviced do work though from HA. It is just that the log flooding with these errors is annoying.

**Comment by geedsen** [comment]
One more thing, One of the devices in tuya-local  was not working from tuya-local bur was working with the HA integeration. I removed and added again. No problem there. But soon the errors started appearing in the logs again. Abd the device logs show this: 
![image](https://github.com/user-attachments/assets/a4974253-4086-4bb7-9a68-be8c6f6d5f0d)
But the same device in Tuya: 
![image](https://github.com/user-attachments/assets/0d1f8c62-39d4-4927-be07-9a8a512c991f)

**Comment by geedsen** [comment]
I was hoping for some more support. Trying my best to provide you with more information. I have a diagnostig log, but don't know how to get it to you. Posting it here does not look like a good option. Also I have questions, like when you add a device, you need to give the ip, does that mean the ip should remain static?   I thought maybe we cannot have the dvices in both Tuya and Tuya-Local. So I removed one from the Tuya app, it was automatically removed from HA, but the device in Tuya-Local went offline with that as well, and does not come back. Is that to be expected?
