### ISSUE TITLE
Small bug in Silvercrest/lidl air fryer #2298

### ISSUE THREAD

**Issue by ekalle-swe** [make-all/tuya-local#2343]
Sorry I didn't catch this when I confirmed it as working.
The timer has 2 phases, that is both updated in "cooking time" and "time remaining"
1st is the selected cooking time that counts down to zero
2nd a cooling time is added when cooking time reaches zero. This is always 60s

The bug is only a unit mismatch, as 60min is added to time remaining and cooking time instead of 60 seconds.

Don't know if this is even fixable.

**Comment by make-all** [comment]
The integration does not add anything, it just displays the timers that are available.  If you can point specifically to which entity has the wrong units, it may help me understand what is wrong.

**Comment by ekalle-swe** [comment]
The sensor.xxx_airfryer_cooling_countdown
Is correctly in seconds.
It goes to 60s after the cooking phase reaches 0 and that is correct but to sensor.xx_airfryer_time_remaining and number.xxx_airfryer_cooking_time are in the same process added 60min

**Comment by make-all** [comment]
In that case, it seems to be the device itself that is sending the incorrect info.
