### ISSUE TITLE
[New device] Support for iHunt Air Purifier Smart 50m3/h

### ISSUE THREAD

**Issue by robex2005** [make-all/tuya-local#2344]
### Log message

```text
Full config file provided
```

### DPS information

```text
{
  "result": {
    "category": "kj",
    "functions": [
      {
        "code": "switch",
        "desc": "{}",
        "name": "开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_speed_enum",
        "desc": "{\"range\":[\"sleep\",\"low\",\"mid\",\"high\"]}",
        "name": "风速模式",
        "type": "Enum",
        "values": "{\"range\":[\"sleep\",\"low\",\"mid\",\"high\"]}"
      },
      {
        "code": "anion",
        "desc": "{}",
        "name": "净离子",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "filter_reset",
        "desc": "{}",
        "name": "滤芯复位",
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "name": "开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_speed_enum",
        "name": "风速模式",
        "type": "Enum",
        "values": "{\"range\":[\"sleep\",\"low\",\"mid\",\"high\"]}"
      },
      {
        "code": "filter",
        "name": "滤芯使用率",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "anion",
        "name": "净离子",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "filter_reset",
        "name": "滤芯复位",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "runtime_total",
        "name": "累计工作时间",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":5256000,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1727523853889,
  "tid": "fbf50ccb7d8e11efbc016e7818a0f8a2"
}
```

### Product ID

qjlhoysvavudtp3d

### Product Name

iHunt Air Purifier Smart 50m3/h

### Information about how the device functions

Below full working config file:

name: iHunt Air Purifier 50
products:
  - id: qjlhoysvavudtp3d
primary_entity:
  entity: switch
  icon: "mdi:air-purifier"
  dps:
    - id: 1
      name: switch
      type: boolean
secondary_entities:
  - entity: sensor
    name: Filter
    category: diagnostic
    icon: "mdi:air-filter"
    dps:
      - id: 5
        type: integer
        name: sensor
        unit: "%"
  - entity: switch
    name: Ionizer
    icon: "mdi:atom-variant"
    category: config
    dps:
      - id: 6
        type: boolean
        name: switch
        mapping:
          - dps_val: true
          - dps_val: false
  - entity: sensor
    name: Runtime total left
    category: diagnostic
    icon: "mdi:air-filter"
    dps:
      - id: 17
        name: sensor
        type: integer
        unit: min
  - entity: button
    name: Filter reset
    category: diagnostic
    class: restart
    dps:
      - id: 11
        type: boolean
        name: button
  - entity: select
    name: Fan Speed
    icon: "mdi:fan"
    category: config
    dps:
      - id: 4
        type: string
        name: option
        mapping:
          - dps_val: sleep
            value: Sleep
          - dps_val: low
            value: Low
          - dps_val: mid
            value: Middle
          - dps_val: high
            value: High

**Comment by robex2005** [comment]
Attached full config (renamed to txt)
[ihunt_air_purifier_50.txt](https://github.com/user-attachments/files/17174279/ihunt_air_purifier_50.txt)

**Comment by make-all** [comment]
Log message is not optional
