### ISSUE TITLE
du4l-wc-01 wifi pet feeder not supported anymore

### ISSUE THREAD

**Issue by Psytoshgen** [make-all/tuya-local#2358]
It was perfectly worked some time ago, but when I try to add it again its shows as unsupported.

here some info for it

      "active_time": 1716031743,
            "biz_type": 18,
            "category": "cwwsq",
            "create_time": 1716031743,
            "icon": "smart/icon/ay1542957114075QsKU3/975ea0ff658b940c9f13de156d0db747.jpg",
            "id": "bfaae484a4cece31d8otqg",
            "ip": "",
            "lat": "",
            "local_key": "ezu@/qjB@]]6amD+",
            "lon": "",
            "model": "",
            "name": "\u043a\u043e\u0440\u043c\u0443\u0448\u043a\u0430",
            "online": true,
            "owner_id": "",
            "product_id": "jh5urzefyklulxfb",
            "product_name": "WiFi Feeder",
            "status": [
                {
                    "code": "meal_plan",
                    "value": "fwUUCgF/EgAKAQ=="
                },
                {
                    "code": "manual_feed",
                    "value": 4
                },
                {
                    "code": "feed_state",
                    "value": "standby"
                },
                {
                    "code": "factory_reset",
                    "value": false
                },
                {
                    "code": "fault",
                    "value": 0
                },
                {
                    "code": "feed_report",
                    "value": 10
                }
            ],
            "sub": false,
            "time_zone": "",
            "uid": "eu1644506280630aE7yE",
            "update_time": 1725919661,
            "uuid": "f81a2a1db93d161a",
            "mapping": {
                "1": {
                    "code": "meal_plan",
                    "type": "Raw",
                    "values": {}
                },
                "3": {
                    "code": "manual_feed",
                    "type": "Integer",
                    "values": {
                        "min": 1,
                        "max": 12,
                        "scale": 0,
                        "step": 1
                    }
                },
                "4": {
                    "code": "feed_state",
                    "type": "Enum",
                    "values": {
                        "range": [
                            "standby",
                            "no_food",
                            "error_ir",
                            "feed_timeout",
                            "feeding"
                        ]
                    }
                },
                "9": {
                    "code": "factory_reset",
                    "type": "Boolean",
                    "values": {}
                },
                "14": {
                    "code": "fault",
                    "type": "Bitmap",
                    "values": {
                        "label": [
                            "no_food",
                            "error_ir",
                            "feed_timeout",
                            "battery_low"
                        ],
                        "maxlen": 4
                    }
                },
                "15": {
                    "code": "feed_report",
                    "type": "Integer",
                    "values": {
                        "min": 0,
                        "max": 12,
                        "scale": 0,
                        "step": 1
                    }
                }
            }
        },
[
    {
        "name": "\u043a\u043e\u0440\u043c\u0443\u0448\u043a\u0430",
        "id": "bfaae484a4cece31d8otqg",
        "key": "",
        "mac": "",
        "uuid": "f81a2a1db93d161a",
        "sn": "10010877900FA1",
        "category": "cwwsq",
        "product_name": "WiFi Feeder",
        "product_id": "jh5urzefyklulxfb",
        "biz_type": 18,
        "model": "",
        "sub": false,
        "icon": "https://images.tuyaeu.com/smart/icon/ay1542957114075QsKU3/975ea0ff658b940c9f13de156d0db747.jpg",
        "mapping": {
            "1": {
                "code": "meal_plan",
                "type": "Raw",
                "values": {}
            },
            "3": {
                "code": "manual_feed",
                "type": "Integer",
                "values": {
                    "min": 1,
                    "max": 12,
                    "scale": 0,
                    "step": 1
                }
            },
            "4": {
                "code": "feed_state",
                "type": "Enum",
                "values": {
                    "range": [
                        "standby",
                        "no_food",
                        "error_ir",
                        "feed_timeout",
                        "feeding"
                    ]
                }
            },
            "9": {
                "code": "factory_reset",
                "type": "Boolean",
                "values": {}
            },
            "14": {
                "code": "fault",
                "type": "Bitmap",
                "values": {
                    "label": [
                        "no_food",
                        "error_ir",
                        "feed_timeout",
                        "battery_low"
                    ],
                    "maxlen": 4
                }
            },
            "15": {
                "code": "feed_report",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 12,
                    "scale": 0,
                    "step": 1
                }
            }
        },
        "ip": "",
        "version": "3.3"
    },

**Comment by make-all** [comment]
No log supplied, and I don't see this in the list of supported devices, so there should be no expectation leading to consider this a bug.
