### ISSUE TITLE
Request support for Pet Feeder

### ISSUE THREAD

**Issue by Whininie** [make-all/tuya-local#2370]
### Log message

```text
Device matches None with quality of 0%. DPS: {"updated_at": 1727908514.2293947, "105": 1}
```

### DPS information

```text
{
  "result": {
    "model": "{\"modelId\":\"0000006t9z\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"other\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power\"},\"name\":\"其他\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"number\",\"description\":\"每次喂食份数\",\"name\":\"喂食份数\",\"typeSpec\":{\"type\":\"value\",\"max\":10,\"min\":1,\"scale\":0,\"step\":1,\"unit\":\"份\"}},
{\"abilityId\":102,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"份数不足时，提醒；如果是自动喂食，则设备在执行完上次份数时会计算一下剩余份数，若不足20份（下次可喂食的最大值），则上报至App,通知用户份数不足；若手动喂食，则在每次下发时，根据下发的份数计算是否满足该份数，若少于该下发份数，则上报至App E1.发生堵粮事件的时候，单片机上报堵粮故障,故障值为 E2。当设备发生故障，硬件损坏时，单片机上报设备异常故障，故障值为E3。\",\"extensions\":{\"scope\":\"fault\"},\"name\":\"故障告警\",\"typeSpec\":{\"type\":\"bitmap\",\"label\":[\"E1\",\"E2\",\"E3\"],\"maxlen\":3}},
{\"abilityId\":103,\"accessMode\":\"ro\",\"code\":\"feed_error\",\"description\":\"发生堵粮事件的时候，单片机上报堵粮故障,故障值为 1\\n当设备发生故障，硬件损坏时，单片机上报设备异常故障，故障值为2 \",\"extensions\":{\"scope\":\"fault\"},\"name\":\"喂食故障\",\"typeSpec\":{\"type\":\"bitmap\",\"label\":[\"1\",\"2\"],\"maxlen\":2}},
{\"abilityId\":104,\"accessMode\":\"rw\",\"code\":\"FEED_INFO\",\"description\":\"发送喂食计划，在单片机存储，在断网阶段也可以进行自动喂食计划\",\"name\":\"喂食计划\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
{\"abilityId\":105,\"accessMode\":\"ro\",\"code\":\"sumfed\",\"description\":\"\",\"extensions\":{\"trigger\":\"direct\"},\"name\":\"喂食统计\",\"typeSpec\":{\"type\":\"value\",\"max\":10,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"份\"}}]}]}"
  }
```

<details>

```text
{"1":"其他","101":"喂食份数","102":"Fault","103":"喂食故障","104":"喂食计划","105":"喂食统计"}
```

</details>

### Product ID

0355061098f4abbbe50c

### Product Name

TY-AF3W

### Information about how the device functions

the fun part is: i have 2 identical devices on the outside, but i think some other firmware
1 of the 2 is working with product code: **TYB3-AF3W_L** this device: **TY-AF3W** is not supported.
I know in the past I used: **TheAgentK/tuya-mqtt**  and it was working with DPS: 101 to manually feed.

**Comment by Whininie** [comment]
Is there anything I have to do or give?

**Comment by make-all** [comment]
This needs proper info on the DPS, including type, range, valid values and description to be actionable.

**Comment by Whininie** [comment]
I dont know where to get this information.. Can you help me? Or is it better to buy a new one

**Comment by make-all** [comment]
You need a developer account on iot.tuya.com really, to get sufficient information about devices to implement them locally.  Once you have signed up there, the API Explorer, Device Control section has a function "Query Things Data Model" that provides complete information about the device's local dps attributes (the format is not great, but if you paste it between ` ``` ` tags, I can clean it up to be more readable (basically adding a newline before each dp entry).

**Comment by Whininie** [comment]
{
  "result": {
    "model": "{\"modelId\":\"0000006t9z\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"other\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power\"},\"name\":\"其他\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"number\",\"description\":\"每次喂食份数\",\"name\":\"喂食份数\",\"typeSpec\":{\"type\":\"value\",\"max\":10,\"min\":1,\"scale\":0,\"step\":1,\"unit\":\"份\"}},{\"abilityId\":102,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"份数不足时，提醒；如果是自动喂食，则设备在执行完上次份数时会计算一下剩余份数，若不足20份（下次可喂食的最大值），则上报至App,通知用户份数不足；若手动喂食，则在每次下发时，根据下发的份数计算是否满足该份数，若少于该下发份数，则上报至App E1.发生堵粮事件的时候，单片机上报堵粮故障,故障值为 E2。当设备发生故障，硬件损坏时，单片机上报设备异常故障，故障值为E3。\",\"extensions\":{\"scope\":\"fault\"},\"name\":\"故障告警\",\"typeSpec\":{\"type\":\"bitmap\",\"label\":[\"E1\",\"E2\",\"E3\"],\"maxlen\":3}},{\"abilityId\":103,\"accessMode\":\"ro\",\"code\":\"feed_error\",\"description\":\"发生堵粮事件的时候，单片机上报堵粮故障,故障值为 1\\n当设备发生故障，硬件损坏时，单片机上报设备异常故障，故障值为2 \",\"extensions\":{\"scope\":\"fault\"},\"name\":\"喂食故障\",\"typeSpec\":{\"type\":\"bitmap\",\"label\":[\"1\",\"2\"],\"maxlen\":2}},{\"abilityId\":104,\"accessMode\":\"rw\",\"code\":\"FEED_INFO\",\"description\":\"发送喂食计划，在单片机存储，在断网阶段也可以进行自动喂食计划\",\"name\":\"喂食计划\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":105,\"accessMode\":\"ro\",\"code\":\"sumfed\",\"description\":\"\",\"extensions\":{\"trigger\":\"direct\"},\"name\":\"喂食统计\",\"typeSpec\":{\"type\":\"value\",\"max\":10,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"份\"}}]}]}"
  },
  "success": true,
  "t": 1731614357416,
  "tid": "ee15d0aaa2c211ef9520ae18e4d9fbe2"
