### ISSUE TITLE
Migration error 

### ISSUE THREAD

**Issue by Patbonamy** [make-all/tuya-local#2380]
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**
Error when updated 2.8.0 to 2.9.1 all my device cannot be configured.

Log :
Enregistreur: homeassistant.config_entries
Source: config_entries.py:933
S'est produit pour la première fois: 08:46:44 (12 occurrences)
Dernier enregistrement: 08:46:44

Error migrating entry SW10tl for tuya_local
Error migrating entry SW2tl for tuya_local
Error migrating entry SW8tl for tuya_local
Error migrating entry SW13tl for tuya_local
Error migrating entry SW6tl for tuya_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 933, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/__init__.py", line 649, in async_migrate_entry
    await async_migrate_entries(hass, entry.entry_id, update_unique_id13_6)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1630, in async_migrate_entries
    ent_reg.async_update_entity(entry.entity_id, **updates)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1173, in async_update_entity
    return self._async_update_entity(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1112, in _async_update_entity
    raise ValueError(
ValueError: Unique id 'None-select_initial_state' is already in use by 'select.sw3tl_chaudiere_power_on_state'

**To Reproduce**
Steps to reproduce the behavior including the device the issue was observed with: update 2.8.0 to 2 .9.1

**Expected behavior**

**Additional context**
Home Assistant latest on prmox virtual environment 

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

I revert to 2.8.0 all is working

**Comment by Patbonamy** [comment]
Duplicated unique_id

**Comment by flequi19** [comment]
I have the same problem and I don't know how to remove duplicate keys. They don't appear on your local account. Could you help me?

**Comment by Patbonamy** [comment]
> I have the same problem and I don't know how to remove duplicate keys. They don't appear on your local account. Could you help me?

Hello flequi19,
Sorry I don't remember how I do that,
I think I uninstall and reinstall the whole integration.
Have a good day
