### ISSUE TITLE
Air Conditioner Recognized as Switch

### ISSUE THREAD

**Issue by Aptul9** [make-all/tuya-local#239]
Hi, I recently tried setting up my air conditioner to use locally. The problem is that it gets recognized as a switch after I provide all the details. I have a Sendo air conditioner, I will attach all the device information below:

> {
>   "result": {
>     "category": "kt",
>     "functions": [
>       {
>         "code": "switch",
>         "desc": "{}",
>         "name": "开关",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "temp_set",
>         "desc": "{\"unit\":\"℃/F\",\"min\":160,\"max\":900,\"scale\":1,\"step\":10}",
>         "name": "设置温度",
>         "type": "Integer",
>         "values": "{\"unit\":\"℃/F\",\"min\":160,\"max\":900,\"scale\":1,\"step\":10}"
>       },
>       {
>         "code": "mode",
>         "desc": "{\"range\":[\"cold\",\"hot\",\"wet\",\"wind\",\"auto\"]}",
>         "name": "工作模式",
>         "type": "Enum",
>         "values": "{\"range\":[\"cold\",\"hot\",\"wet\",\"wind\",\"auto\"]}"
>       },
>       {
>         "code": "mode_eco",
>         "desc": "{}",
>         "name": "ECO模式",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "heat",
>         "desc": "{}",
>         "name": "辅热",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "light",
>         "desc": "{}",
>         "name": "灯光",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "lock",
>         "desc": "{}",
>         "name": "童锁",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "switch_horizontal",
>         "desc": "{}",
>         "name": "左右摆风开关",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "sleep",
>         "desc": "{}",
>         "name": "睡眠功能",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "health",
>         "desc": "{}",
>         "name": "健康",
>         "type": "Boolean",
>         "values": "{}"
>       }
>     ],
>     "status": [
>       {
>         "code": "switch",
>         "name": "开关",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "temp_set",
>         "name": "设置温度",
>         "type": "Integer",
>         "values": "{\"unit\":\"℃/F\",\"min\":160,\"max\":900,\"scale\":1,\"step\":10}"
>       },
>       {
>         "code": "temp_current",
>         "name": "当前温度",
>         "type": "Integer",
>         "values": "{\"unit\":\"℃/F\",\"min\":-300,\"max\":1760,\"scale\":1,\"step\":10}"
>       },
>       {
>         "code": "mode",
>         "name": "工作模式",
>         "type": "Enum",
>         "values": "{\"range\":[\"cold\",\"hot\",\"wet\",\"wind\",\"auto\"]}"
>       },
>       {
>         "code": "mode_eco",
>         "name": "ECO模式",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "heat",
>         "name": "辅热",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "light",
>         "name": "灯光",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "lock",
>         "name": "童锁",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "power_consumption",
>         "name": "耗电量",
>         "type": "Integer",
>         "values": "{\"unit\":\"kW·h\",\"min\":0,\"max\":255,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "switch_horizontal",
>         "name": "左右摆风开关",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "sleep",
>         "name": "睡眠功能",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "health",
>         "name": "健康",
>         "type": "Boolean",
>         "values": "{}"
>       }
>     ]
>   },
>   "success": true,
>   "t": ---,
>   "tid": "---"
> }

**Comment by make-all** [comment]
This information is missing the local protocol indexes.  Please see the README.md for hints on how to gather more information that includes these.

**Comment by Aptul9** [comment]
Hi, sorry, I have read the entire README file, but I am not sure what information you are looking for, I think it might be the Tuya protocol itself (3.1 or 3.3), but I wasn't able to find where to find it exactly, but the device Wi-Fi module is recent, there is a label which says it was created in 2022, so I think it might be 3.3

**Comment by make-all** [comment]
https://github.com/make-all/tuya-local#device-support

**Comment by Aptul9** [comment]
> {
>   "result": {
>     "category": "kt",
>     "functions": [
>       {
>         "code": "switch",
>         "dp_id": 1,
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "temp_set",
>         "dp_id": 2,
>         "type": "Integer",
>         "values": "{\"unit\":\"℃/F\",\"min\":160,\"max\":900,\"scale\":1,\"step\":10}"
>       },
>       {
>         "code": "mode",
>         "dp_id": 4,
>         "type": "Enum",
>         "values": "{\"range\":[\"cold\",\"hot\",\"wet\",\"wind\",\"auto\"]}"
>       },
>       {
>         "code": "mode_eco",
>         "dp_id": 8,
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "heat",
>         "dp_id": 12,
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "light",
>         "dp_id": 13,
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "lock",
>         "dp_id": 14,
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "switch_horizontal",
>         "dp_id": 33,
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "sleep",
>         "dp_id": 102,
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "health",
>         "dp_id": 106,
>         "type": "Boolean",
>         "values": "{}"
>       }
>     ],
>     "status": [
>       {
>         "code": "switch",
>         "dp_id": 1,
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "temp_set",
>         "dp_id": 2,
>         "type": "Integer",
>         "values": "{\"unit\":\"℃/F\",\"min\":160,\"max\":900,\"scale\":1,\"step\":10}"
>       },
>       {
>         "code": "temp_current",
>         "dp_id": 3,
>         "type": "Integer",
>         "values": "{\"unit\":\"℃/F\",\"min\":-300,\"max\":1760,\"scale\":1,\"step\":10}"
>       },
>       {
>         "code": "mode",
>         "dp_id": 4,
>         "type": "Enum",
>         "values": "{\"range\":[\"cold\",\"hot\",\"wet\",\"wind\",\"auto\"]}"
>       },
>       {
>         "code": "mode_eco",
>         "dp_id": 8,
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "heat",
>         "dp_id": 12,
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "light",
>         "dp_id": 13,
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "lock",
>         "dp_id": 14,
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "power_consumption",
>         "dp_id": 28,
>         "type": "Integer",
>         "values": "{\"unit\":\"kW·h\",\"min\":0,\"max\":255,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "switch_horizontal",
>         "dp_id": 33,
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "sleep",
>         "dp_id": 102,
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "health",
>         "dp_id": 106,
>         "type": "Boolean",
>         "values": "{}"
>       }
>     ]
>   },
>   "success": true,
>   "t": 1664118156288,
>   "tid": "172c4ac63ce311edb872ca0f69d78a9e"
> }

**Comment by make-all** [comment]
Thanks, that should be enough info to make an initial config.

**Comment by Aptul9** [comment]
Ok, thank you for the support, are you gonna include it in the next
release?

Il dom 25 set 2022, 23:48 Jason Rumney ***@***.***> ha
scritto:

**Comment by make-all** [comment]
Probably this can be supported by the next release.  Can you let me know the brand name and/or model number?  It is a bit confusing to use generic names like just "air conditioner", as Tuya devices are generally not compatible with other similar devices, so the config is unlikely to work for other brands.

**Comment by Aptul9** [comment]
Hi, as you can see from the previous comment the brand is called Sendo, they have a few models, but I got the opportunity to get in touch with them and they have confirmed to me that the Wi-Fi module is the same for all of them, so it should be working fine in every model.

**Comment by make-all** [comment]
This should be working in the latest release.

**Comment by Aptul9** [comment]
yes, it works like a charm, thank you!
