### ISSUE TITLE
Request support for Owon PCT321-W-TY Energy Meter

### ISSUE THREAD

**Issue by cperrier** [make-all/tuya-local#2394]
### Log message

```text
No more log available. I can work to get some, which basically remove the device that I manually added after tweaking the pc321zty_energy_meter.yaml file, but that's, IMHO, a lot of work for basically nothing as the point of this report is suggesting to add a new id to an existing device file
```

### DPS information

```text
Same than PC321-Z-TY...
```

### Product ID

bf59e113277b0d93fe9ddp

### Product Name

PC321-W-TY(Bi-Directional)

### Information about how the device functions

This issue is indeed about adding the correct is and name to the existing pct321zty_energy_meter.yaml file so that the Wifi version of this device is also support.

It resumes to this, indeed  

--- pc321ty_energy_meter.yaml
+++ pc321wty_energy_meter.yaml
@@ -1,9 +1,7 @@
-name: Power clamp meter
+name: Power clamp meter custom
 products:
-  - id: r64livttuufctble
-    name: PC321-TY
-  - id: 9rjjf6rdkca9woju
-    name: PC321-TY 80A
+  - id: bf59e113277b0d93fe9ddp
+    name: PC321-W-TY(Bi-Directional) 80A
 primary_entity:
   entity: sensor
   class: energy

I don't know if this is a dirty hack or not but, well, it works for me. It would indeed help me a lot when Tuya Local is updated so that I don't have to re-add my hacked YAML file manually before restarting HA....:-)

Thanks a lot for this great work, anyway !

**Comment by make-all** [comment]
This is your device id, not the product id. There is no meaning to add the id of your individual device to the config file that is shared with everyone.

**Comment by cperrier** [comment]
Well, that's right. I could probably find the Product ID, assuming I find my way in the giant nightmare that is the tuya.com developer platform. Bull, well the issue is closed, therefore I assume there is no point I try to contribute further. Seems to me that back in the days I was contributing to one of the major free software projects (I leave up to the readers to find which one, it's easy to find), I wasn't that quick at closing bug reports, even those that were not as precise as I would have expected. But, well, that was 15 years ago, other times, other ways to do things.

I guess I'll continue to hack my YAML files by hand and voilà...;-)

**Comment by make-all** [comment]
75% of users never come back with info, so I find it easier to track what requests are pending by closing issues quickly if there is no action to be taken based on the report and reopen if users come back with more info.

There is no need to get offended by this workflow, it is not a personal attack on you, just a way to keep the work queue manageable.

**Comment by cperrier** [comment]
Well, OK, I may understand this (still, from the POV of the person who tried to be helpful with his/her own skills, it probably sounds a bit rude). Sorry for being a bit harsh. I'm not part of these 75% users, you couldn't know, but I struggled myself enough with bug reports in the past to understand the reaction.

So, I certainly can try to find this productID information for my product. It seems to me that while I was struggling to get my device recognized I found a quite detailed way to find one's way on the Tuya Developer Platform (I have an account there, I can see my devices, etc.... but as this "world" is a bit unknown for me, I can't really find a way to navigate with the Tuya API (mentioned in devices/README.md, which I tried to read though it's a bit of black magic for me). And, well, this dev. platform is really scary

I know that I found "somewhere" a bit more detailed explanations about how to navigate there, but I can't find them anymore. Was it in Tuya Local documentation or somewhere else, I don't even remember....:-)

**Comment by make-all** [comment]
The product id is available from cloud or local discovery broadcasts.

For the cloud, iot.tuya.com Cloud / API Explorer allows you to run API commands. The "Query Device Details" command under Device Management is one of the commands that returns the product id.

For local discovery broadcasts, you can gather the info by installing tinytuya and running `python -m tinytuya scan`

**Comment by cperrier** [comment]
OK, I think I managed to get the required info, finally...
```
{
  "result": [
    {
      "active_time": 1726589638,
      "bind_space_id": "196407439",
      "category": "zndb",
      "create_time": 1726589638,
      "custom_name": "Mesure conso CE",
      "icon": "smart/icon/ay1515026431018saCFs/22a786d9e0619bdcb43260f65b7915a4.png",
      "id": "bf59e113277b0d93fe9ddp",
      "ip": "82.66.233.241",
      "is_online": true,
      "lat": "49.23",
      "local_key": "(STf4N6vdHm=sL=#",
      "lon": "1.34",
      "model": "",
      "name": "PC321-W-TY(Bi-Directional)",
      "product_id": "gqmmtjclqb7reg5p",
      "product_name": "PC321-W-TY(Bi-Directional)",
      "sub": false,
      "time_zone": "+02:00",
      "update_time": 1726589863,
      "uuid": "fa0497096a4f623f"
    }
  ],
  "success": true,
  "t": 1731419232933,
  "tid": "9ed20a8fa0fc11ef8851a6e2b97567ba"
}
```

**Comment by cperrier** [comment]
Not sure I can reopen the issue myself, so leaving it up to you.....

**Comment by cperrier** [comment]
Everything is working as expected as of 2024.11.3 (and .4). I just had to remove and re-add my device manually after the upgrade.

Thanks a lot! Hopefully, I'll know what to do the next time I come up with a new device for which I would like support for. Thanks for your work on Tuya Local.

**Comment by atiweb** [comment]
Hi everyone! 👋

I wanted to share that I got the **PC321-W-TY** (Tuya/OWON WiFi Energy Meter) working with Home Assistant, but using **LocalTuya** instead of Tuya Local.

I've created a detailed documentation repository based on my actual working configuration:

🔗 **https://github.com/atiweb/PC321-W-TY**

**What's included:**
- Complete DPS mapping with verified scaling factors
- All 18 sensors configured (voltage, current, power, energy per phase + totals)
- Bidirectional measurement working (grid import/export for solar systems)
- Template sensors for Energy Dashboard
- Protocol version **3.5** required

This setup has been running reliably for several months.

**Key DPS IDs for reference:**
| Measurement | Phase A | Phase B | Total |
|-------------|---------|---------|-------|
| Voltage | 101 | 111 | - |
| Current | 102 | 112 | 132 |
| Power | 103 | 113 | 133 |
| Energy Import | 106 | 116 | 131 |
| Energy Export | 107 | 117 | 139 |

While I understand Tuya Local uses YAML definitions, perhaps this information could help create a proper device definition for the PC321-W-TY? The DPS structure and scaling factors in my repo are verified working.

Hope this helps the community! 🙌
