### ISSUE TITLE
IR Remote Control T&H Sensor add as T&H only

### ISSUE THREAD

**Issue by tamerhamdyelsayed** [make-all/tuya-local#2417]
### Description

"product_id": "21ikckanjh9n5tzt" not shows as gateway
added as temp & hum sensor not as IR Remote Control T&H Sensor 

### Steps to reproduce

"product_id": "21ikckanjh9n5tzt" not shows as gateway
added as temp & hum sensor not as IR Remote Control T&H Sens

### Expected behaviour

to be added as gateway IR

### Additional context

"product_id": "21ikckanjh9n5tzt" not shows as gateway
added as temp & hum sensor not as IR Remote Control T&H Sens

### Confirmation

- [X] I am sure this is a bug, or improvement that is well enough described that it can be implemented
- [X] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [X] This is not requesting addition of a new device

**Comment by make-all** [comment]
There is no "gateway" entity type, so this is not a bug.

**Comment by tamerhamdyelsayed** [comment]
hi

this device when added as it shows as temp & hum sensor only 
 not as IR Remote Control T&H 
and not show as gateway for other devices to add them as sub

  "model": "WL-IRT",
    "name": "IR Remote Control T&H Sensor",
    "product_id": "21ikckanjh9n5tzt",
    "product_name": "万能遥控+温湿度",
    "sub": false,
