### ISSUE TITLE
Request support for <Infrared RF remote control>

### ISSUE THREAD

**Issue by tamerhamdyelsayed** [make-all/tuya-local#2418]
### Log message

```text
"name": "Infrared RF remote control",
    "product_id": "nwpvjlq7qacvnqf3",
```

### DPS information

```text
"model": "",
    "name": "Infrared RF remote control",
    "product_id": "nwpvjlq7qacvnqf3",
    "product_name": "S11+( IR+RF遥控器Pro)",
    "sub": false,
    "time_zone": "+03:00",
    "update_time": 1729351866,
```

### Product ID

"product_id": "nwpvjlq7qacvnqf3",

### Product Name

"product_name": "S11+( IR+RF遥控器Pro)",

**Comment by make-all** [comment]
There is no log and no local dps info in this report. I cannot do anything with this info.

**Comment by make-all** [comment]
Additionally, this device is already supported since 2024.10.0

**Comment by make-all** [comment]
The log is under Settings / System / Log in Home Assistant.
The DPS info needs a Tuya Developer account to gather.

But as my last comment says, there should be no need, as this device is already supported, which also seems to be confirmed by your "S11+( IR+RF , is shows up as a device".
