### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by Lars6503** [make-all/tuya-local#242]
When trying to install I get that there is no integration to download, try using latest Ha. But I am on the latest Ha.
And I can't find any manual download or clone.
How should I do?

**Comment by make-all** [comment]
Sorry, your question is not clear enough for me to understand the steps you are following and where it might be going wrong.

**Comment by Lars6503** [comment]
Hi Jason.

I tried using the link, "Add integration", to install, and when it opens my HA it says:
"Error
This integration doesn't support Configuration through userinterface. If you followed this link from Home-Assistant webplace, be sure to use the latest version of Home Assistant." 

This is a translation from the actual Swedish text I get. 

I can't see anywhere I can download the package for a manual installation? 

Cheers, 
Lars 


Jason Rumney ***@***.***> skrev: (1 oktober 2022 12:42:02 CEST)
>Sorry, your question is not clear enough for me to understand the steps
>you are following and where it might be going wrong.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/make-all/tuya-local/issues/242#issuecomment-1264322808
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

-This is not the (an)droid you're looking for.

**Comment by make-all** [comment]
That link only works after the integration is installed.  It is for adding a device.

I don't have the capacity to support everyone's preferred installation method sorry. If you do not use HACS, then you should be familiar with installing custom components using whatever method you choose, the release links do contain downloadable source, though you generally only need part of it.

**Comment by Lars6503** [comment]
Got everything installed, but the filebrowser doesn't start.
It is ok, I understand that you don't have the time to support.
Cheers,
Lars 

Jason Rumney ***@***.***> skrev: (11 oktober 2022 11:47:22 CEST)
>That link only works after the integration is installed.  It is for
>adding a device.
>
>I don't have the capacity to support everyone's preferred installation
>method sorry. If you do not use HACS, then you should be familiar with
>installing custom components using whatever method you choose, the
>release links do contain downloadable source, though you generally only
>need part of it.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/make-all/tuya-local/issues/242#issuecomment-1274424011
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

-This is not the (an)droid you're looking for.

**Comment by make-all** [comment]
I presume by "filebrowser" you mean the config window for adding the integration?

If you press the "Add Integration" button on the Settings / Devices page, can you find the tuya-local integration and start from there?

**Comment by Lars6503** [comment]
Got the integration to start now. Made some changes and rebuilt it and restarted and it is now up and running.
Now I'm working on getting it to see my NAS.
Thanks for the work you've put in.
Cheers. 

Jason Rumney ***@***.***> skrev: (16 oktober 2022 07:58:51 CEST)
>I presume by "filebrowser" you mean the config window for adding the
>integration?
>
>If you press the "Add Integration" button on the Settings / Devices
>page, can you find the tuya-local integration and start from there?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/make-all/tuya-local/issues/242#issuecomment-1279898833
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

-This is not the (an)droid you're looking for.
