### ISSUE TITLE
Cannot add any device (Greyed out entitities)

### ISSUE THREAD

**Issue by pacorola** [make-all/tuya-local#2431]
### Description

When adding a device, at first it seems successful, but then I can only see entities with no device. All of them greyed out.

Upon restarting Home Assistant, I can now see a device, but neither the device nor the entities are usable (all of them "disconnected"). Funnily enough, the device history does record changes live and knows wether the entity has been turned on or off.
![Captura de pantalla 2024-10-24 134117](https://github.com/user-attachments/assets/b7ec35a5-8c29-454a-bf5c-0ba4e65e016b)

### Steps to reproduce

1. Add device

### Expected behaviour

The added device should work. 

### Additional context

All devices are correctly identified by setup, and some are even old, previously connected devices, that still cannot be configured.

### Confirmation

- [X] I am sure this is a bug, or improvement that is well enough described that it can be implemented
- [X] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [X] This is not requesting addition of a new device

**Comment by make-all** [comment]
No actionable information in this report. Clearly if the steps were as simple as you suggest, we would all be seeing the same behaviour.
