### ISSUE TITLE
[Feature Request] Stateless Buttons

### ISSUE THREAD

**Issue by illuzn** [make-all/tuya-local#244]
Hello,

I have a Tuya gate controller that bizarrely uses a stateless button to control itself.

Essentially, *DPS 148* acts as this stateless button and if any get or set request is sent for this DPS then it will open/ close my gate.

The issue is implementing this as say a switch, when the status is attempted to be updated then it triggers the button.

**Comment by make-all** [comment]
What other dps are available on this device?  If nothing is available for reading, there is no way of detecting such a device currently.

Asy this integration does not perform get requests for specific dps, just a general update request with no dps, it shouldn't trigger the button on read.  Just that a switch with None as its current state probably will show up as unavailable in the UI.
