### ISSUE TITLE
Cannot add WGH-ML-001 Tuya Doorbell

### ISSUE THREAD

**Issue by rglszl** [make-all/tuya-local#2440]
### Description

I have a Tuya Doorbell that I have previously integrated to Home Assistant. In the recent version(s) I get an error message when I try to add it. The error message: "Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect."

It sometimes recognize the device, but the device type is not correct. Sometimes I can choose from "co2_sensor", "dimmable_light" or "aroma_diffuser", which are not correct. The list of possible device types is not always the same, but doorbell or alarm or anything like that does not come up.

<img width="487" alt="image" src="https://github.com/user-attachments/assets/4df55226-9aa1-44e1-bbf9-cf888ad49d44">

In the Tuya Smart app it is added and I get notifications on the doorbell button press, so the device itself is working. The IP address is correct, because it has a static IP with DHCP and it has been working before.
This same doorbell has been working already in Home Assistant with the Tuya Local integration, so one of the updates might caused this issue.

### Steps to reproduce

1. Add the Tuya Local integration to HA
2. Log in with QR code scan to Tuya Cloud
3. Select from discovered devices on network
4. Click on Submit

### Expected behaviour

The device should be recognized as a doorbell.

### Confirmation

- [x] I am sure this is a bug, or improvement that is well enough described that it can be implemented
- [X] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [X] This is not requesting addition of a new device

**Comment by rglszl** [comment]
I got this debug log:
<img width="1187" alt="image" src="https://github.com/user-attachments/assets/46e223d2-284e-4689-99f6-dd3fc77fd9a9">

**Comment by make-all** [comment]
This device is not listed as a supported device, so there is no expectation that any particular config will match.

**Comment by rglszl** [comment]
I think in issue #504 the support has been added and the device was working for me before an update.
