### ISSUE TITLE
Add Support Smart Temperature Controller WiFi 

### ISSUE THREAD

**Issue by QaDoPL** [make-all/tuya-local#2454]
### Log message

```text
Rejestrator: custom_components.tuya_local.config_flow
Źródło: custom_components/tuya_local/config_flow.py:485
integracja: Tuya Local (dokumentacja, Problemy)
Pierwsze zdarzenie: 14:16:26 (4 zdarzenia)
Ostatnio zalogowany: 15:05:34

    Device matches simple_dual_switch_timer_v2 with quality of 25%. DPS: {"updated_at": 1730726179.897683, "1": true, "2": false, "3": true, "4": "cold", "5": "c", "6": 244, "7": 830, "8": true, "9": 830, "10": 98, "11": false, "12": 160, "13": false, "16": 0, "18": 90, "19": 0}
    Device matches simple_dual_switch_timer_v2 with quality of 25%. DPS: {"updated_at": 1730726240.2121406, "1": true, "2": false, "3": true, "4": "cold", "5": "c", "6": 244, "7": 830, "8": true, "9": 830, "10": 98, "11": false, "12": 160, "13": false, "16": 0, "18": 90, "19": 0}
    Device matches simple_dual_switch_timer_v2 with quality of 25%. DPS: {"updated_at": 1730726275.545615, "1": true, "2": false, "3": true, "4": "cold", "5": "c", "6": 242, "7": 830, "8": true, "9": 830, "10": 98, "11": false, "12": 160, "13": false, "16": 0, "18": 90, "19": 0}
    Device matches simple_dual_switch_timer_v2 with quality of 25%. DPS: {"updated_at": 1730729128.8143003, "1": true, "2": false, "3": true, "4": "cold", "5": "c", "6": 238, "7": 830, "8": true, "9": 830, "10": 98, "11": false, "12": 160, "13": false, "16": 0, "18": 90, "19": 0}
```

### Product ID

bf893cffb7aa6213b3wqcr

### Product Name

温控插座 - Smart Temperature Controller

### DPS information

```text
{"1":"Switch All","2":"Switch 1","3":"Switch 2","4":"Mode","5":"Transition temperature","6":"Current Temperature","7":"Upper Temperature","8":"高温报警开关","9":"Upper Alarm Temp","10":"Lower Temperature","11":"低温报警开关","12":"Lower Alarm Temp","13":"制冷延时开关","14":"Cold Delay","16":"Countdown 1","18":"Temperature calibration","19":"fault"}
```

### Information about how the device functions

Device is not supported, all from list, are incorrect in functions.
There is option see actual temperature from sensor and steering 2 power output switch.
Device can run something for preheating and cooling.
Quite simple but nice. I'm using it for controlling central heating pumps

Product Name
温控插座
Device ID
bf893cffb7aa6213b3wqcr
Product Category
wkcz

[config_entry-tuya_local-01JBVQY1TH2HRJRPV43K2JGCN0.json](https://github.com/user-attachments/files/17619191/config_entry-tuya_local-01JBVQY1TH2HRJRPV43K2JGCN0.json)
![Tsmart](https://github.com/user-attachments/assets/da1cd276-ac06-42e0-a8f1-837bedec2cf5)

**Comment by make-all** [comment]
There are some issues here:
- the dps info is not sufficient, it is only pairing names and ids. Information about type, range, list of possible values if fixed, whether it is read-write, read-only or write-only is also needed.
- you have given device id instead of product id.  The product id is now logged alongside the dps log in 2024.11.0, so you can get it from there.
