### ISSUE TITLE
Request support for Novostella Flood Lights

### ISSUE THREAD

**Issue by broyuken** [make-all/tuya-local#2455]
### Log message

```text
I do not see anything in my logs when I add the device, even tried tail -f on the homeassitant.log file
```

### Product ID

61320166e0980611a9b7

### Product Name

Novostella 2 Pack 20W Smart LED Flood Lights, RGBCW, 2700K-6500K, 2000LM, WiFi Outdoor Dimmable Color Changing Stage Light, IP66 Waterproof, Multicolor Wall Washer Light, Work with Alexa

### DPS information

```text
{
  "result": {
    "model": "{\"modelId\":\"0000003wke\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":20,\"accessMode\":\"rw\",\"code\":\"switch_led\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_powe\",\"attribute\":\"3\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":21,\"accessMode\":\"rw\",\"code\":\"work_mode\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_mode\"},\"name\":\"模式\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}},{\"abilityId\":22,\"accessMode\":\"rw\",\"code\":\"bright_value\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-liangdu1\",\"attribute\":\"2\"},\"name\":\"白光亮度\",\"typeSpec\":{\"type\":\"value\",\"max\":1000,\"min\":10,\"scale\":0,\"step\":1}},{\"abilityId\":23,\"accessMode\":\"rw\",\"code\":\"temp_value\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_half\",\"attribute\":\"2\"},\"name\":\"白光色温\",\"typeSpec\":{\"type\":\"value\",\"max\":1000,\"min\":0,\"scale\":0,\"step\":1}},{\"abilityId\":24,\"accessMode\":\"rw\",\"code\":\"colour_data\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-yanse\"},\"name\":\"彩光颜色\",\"typeSpec\":{\"type\":\"string\",\"maxlen\":255}},{\"abilityId\":25,\"accessMode\":\"rw\",\"code\":\"scene_data\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-shoucang\"},\"name\":\"情景\",\"typeSpec\":{\"type\":\"string\",\"maxlen\":255}},{\"abilityId\":26,\"accessMode\":\"rw\",\"code\":\"countdown\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-a_nav_timer\",\"attribute\":\"2\"},\"name\":\"倒计时\",\"typeSpec\":{\"type\":\"value\",\"max\":86400,\"min\":0,\"scale\":0,\"step\":1}},{\"abilityId\":28,\"accessMode\":\"rw\",\"code\":\"control_data\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_box2\"},\"name\":\"调节\",\"typeSpec\":{\"type\":\"string\",\"maxlen\":255}}]}]}"
  },
  "success": true,
  "t": 1730733076925,
  "tid": "09fdea459abf11efbc0aea59c918e957"
}
```

### Information about how the device functions

This is an RGBCW outdoor floodlight. It has been tuya-convert patched and you can't open it up without breaking the glass on the front. 
https://templates.blakadder.com/novostella_UT88835.html

**Comment by broyuken** [comment]
I would do a pull request here, but this device doesn't get far enough in the process to work. 
![image](https://github.com/user-attachments/assets/6eaff03e-cd8b-4a12-9b05-36534a353ff6)

I've set the local key, device id and ip address and tried all the protocol versions. This device also did not automatically find the ip address, I had to manually add it in. Other devices work just fine.

**Comment by make-all** [comment]
If you are unable to get the device connected to gather logs, there is no point in requesting a new device.

**Comment by broyuken** [comment]
Can I open this as a trouble issue then? This device works fine in local tuya, but it can’t find it in tuya local.

**Comment by make-all** [comment]
No, connection issues should be discussed in #522 after going through all the other things there. It is unlikely that you can collect enough info to make a bug report against this integration, as the problem is either external (eg localtuya or mobile app is already connected to that device), or in the underlying library.
