### ISSUE TITLE
Nashone mts700wb thermostat contineously "on"

### ISSUE THREAD

**Issue by GroenZoom** [make-all/tuya-local#246]

**Comment by GroenZoom** [comment]
When the Nashone thermostat is switched off from the service or scheduler it is still showed as on in HA history.
![Image1](https://user-images.githubusercontent.com/50486182/195999831-3a8ab89c-c3c5-4364-a7ce-11ecc1c5d319.jpg)
I am using HA 2022.10.3 and current git-hub latest tuya-local. I seems to me that something is wrong in the device code.
regards
Martin

**Comment by make-all** [comment]
On issue #101, where the information for this device originally came from, the device has a "work_state" attribute, which maps to hvac_action in HA.  The problem is the Tuya portal docs only mention "manual" as a possible value for this, so when the value is manual, the hvac_mode will be followed, but any other value will be passed through as-is, which probably causes an error in the HA log rather than a state change if the value is not matching one of HA's recognized hvac_action values.

Have a look in the log, and also the attributes of the entity on the Developer Tools / States page, and see if you can find what other values hvac_action is taking when it is not reporting the expected values.

**Comment by GroenZoom** [comment]
Hallo Jason;

Thanks for your prompt reaction and suggestion.
I will explore and come back to you if anything comes up.

Regards
Martin

Van: Jason Rumney
Verzonden: zondag 16 oktober 2022 02:49
Aan: make-all/tuya-local
CC: GroenZoom; Author
Onderwerp: Re: [make-all/tuya-local] Nashone mts700wb thermostat contineously"on" (Issue #246)

On issue #101, where the information for this device originally came from, the device has a "work_state" attribute, which maps to hvac_action in HA. The problem is the Tuya portal docs only mention "manual" as a possible value for this, so when the value is manual, the hvac_mode will be followed, but any other value will be passed through as-is, which probably causes an error in the HA log rather than a state change if the value is not matching one of HA's recognized hvac_action values.
Have a look in the log, and also the attributes of the entity on the Developer Tools / States page, and see if you can find what other values hvac_action is taking when it is not reporting the expected values.

**Comment by GroenZoom** [comment]
Hallo Jason;
Thank for your prompt respons.
Attached the warning from the HA log and the output of Tuya-IOT get device specification attributes.
The thermostat is working OK and de-/activated in scheduler but always showing heating(off) and on in its history graph.
I am not sure what and where to change in order to solve this.
regards
Martin
[Get device specification attribute.txt](https://github.com/make-all/tuya-local/files/9794810/Get.device.specification.attribute.txt)

**Comment by make-all** [comment]
As expected, the log message shows that an unexpected value was returned from the `work_state` dp of the tuya device.

    Unrecognised HVAC Action **normal_temp_set** ignored

As with the original report on #101, the `work_state` is documented with only the value "manual".

      {
        "code": "work_state",
        "dp_id": 3,
        "type": "Enum",
        "values": "{\"range\":[\"manual\"]}"
      },

**Comment by GroenZoom** [comment]
Bizar, climate.turn_on is working ok but climate.turn_off is not. Work around possibly through climate.set_temperature with arbitrairy new temperatuur setpoint and mode off.  Still unclear how to solve this is scheduler, scripting seems large overkill.
bw
Martin

**Comment by GroenZoom** [comment]
Do I understand correctly that _"Unrecognised HVAC Action normal_temp_set ignored"means that TuyaLocal has sent an unknown command to the Tuya device which answers ???? inrecognised. Can i change that in the TuyaLocal device specs?

**Comment by make-all** [comment]
No, your understanding is the other way around.

normal_temp_set is not one of the recognised values for "work_mode", so tuya-local does not know what to do with it.

**Comment by GroenZoom** [comment]
Following scripts work but to switch on and off , however need to set target temperature simultaneously.
Can I adapt nashone_mts700wb_thermostat.yaml to avoid cumbersome script programming through scheduler?
Bye
Martin
radiator_badkamer_uit_script:
  sequence:
    - service: climate.set_temperature
      data:
        hvac_mode: "off"
        temperature: 12
      target:
        device_id: d8122227889cc7f94682b508e7af59e4
    
radiator_badkamer_23_script:
  sequence:
    - service: climate.set_temperature
      data:
        hvac_mode: heat
        temperature: 23
      target:
        device_id: d8122227889cc7f94682b508e7af59e4

**Comment by make-all** [comment]
Yes, that is correct.  Until you can figure out all the values returned by work_state and their meanings, I think the best temporary fix will be to rename the attribute from hvac_action to work_state so that Home Assistant doesn't expect anything specific from that.  The state will then just follow hvac_mode, which means you will only know the switch state, not the actual operation state, but the latter is not working now anyway.

**Comment by GroenZoom** [comment]
OK, Thanks for your much appreciated  support.
I will continue on this path, are you interested if it yields any progress?
So far Tuya IoT shows that the standard_status_set for work_state only contains "manual"
Bye
Martin

**Comment by make-all** [comment]
Yes, if you can figure out what it really does, then I am interested in making it work better.  It should be easier to monitor once the config change to rename it has gone through.

**Comment by GroenZoom** [comment]
OK, one last question: where do i change the attributes name as you suggested?

**Comment by make-all** [comment]
I forgot to tag this issue on the change https://github.com/make-all/tuya-local/commit/6509d53e85b2b6c2854f2938b2182aad94d883c3

**Comment by GroenZoom** [comment]
Tnx, 100% clear now.
I'll report back

**Comment by GroenZoom** [comment]
Jason:
The suggested mod in nashone_mts700wb_thermostat.yaml works fine.
The thermostat can now be set to off and on while the on/off state is correctly displayed in HA history.
Thanks for your support and advice.
regards
Martin
