### ISSUE TITLE
New Device: Stadler Form Roger

### ISSUE THREAD

**Issue by dilorenzo1987** [make-all/tuya-local#247]
Hi

I made the following definition for the Stadler Form Roger Air Purifier (see Attached):
https://www.stadlerform.com/de-ch/luftreiniger/roger-schwarz-r-017

Can you include it in the next release?

Thank you 
[stadler_form_roger.zip](https://github.com/make-all/tuya-local/files/9794352/stadler_form_roger.zip)

**Comment by dilorenzo1987** [comment]
Hi

Thank you for including the device.
But I noticed you changed the mappings and they are unfortunately not correct.

ID 4 is really just about the different speed levels (1-5) despite the strange names (Auto is in fact Speed 5 and not Auto Mode).

Auto Mode is solely controlled by ID 101.

Please check my initial supplied config again.

Regards

**Comment by make-all** [comment]
OK, I have changed them to speeds on a scale of 0-100 which should work better with voice assistants, as you'll be able to say things like "turn the fan down".

**Comment by make-all** [comment]
Closing as no feedback received since the last change 3 weeks ago or the previous release
