### ISSUE TITLE
Beca BHT-009: Test protocol error 901: Network Error: Unable to Connect

### ISSUE THREAD

**Issue by AndySuhl** [make-all/tuya-local#2470]
### Log message

```text
WARNING (SyncWorker_50) [custom_components.tuya_local.device] Test protocol error 901: Network Error: Unable to Connect
```

### Product ID

14bmxdarlb4ravgd

### Product Name

Beca BHT-009

### DPS information

```text
model:
009 采暖
```

### Information about how the device functions

I have 2 Thermostates from Beca with Smart Knob
BECA BHT-009GB Thermostat for electic heating
BECA BHT-009GA Thermostat for water heating

both i have connected with tuya via cloud and everythink is o.k.
I can´t connect them with tuya local.

Please help

**Comment by AndySuhl** [comment]
sorry, Fehlermeldung auf deutsch.
beim Einbinden über tuya local:
Mit diesen Angaben kann keine Verbindung zu Ihrem Gerät hergestellt werden. Es könnte sich um ein intermittierendes Problem handeln, oder die Angaben sind falsch.

**Comment by Bsector** [comment]
Hello, I have the same problem of connection failure with other devices.
They even connect via the Tuya app and local tuya, but Tuya-Local does not connect in any way.
