### ISSUE TITLE
Invalid hex color: #NaNNaNNaN

### ISSUE THREAD

**Issue by Ben00793** [make-all/tuya-local#2471]
### Description

Hi. after entering my user id for the cloud assisted setup, the qr does not appear on my screen.
Please help!

Thank you!
![image](https://github.com/user-attachments/assets/12f7f3c1-faa8-42a4-91e4-64144f81ef61)

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [ ] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
I just confirmed that the QR code is still working in HA 2024.11.0, so it is not a change made in HA that this integration needs to adapt to.

Perhaps it is something else in your local installation causing this, such as a custom theme, in which case it needs to be reported there (or to HA if the theme author determines the problem to be in HA)

**Comment by sh4gan** [comment]
![Image](https://github.com/user-attachments/assets/b9c0f4eb-10b1-4b2d-9ec4-559c45cff8cc)

Looks like the issue still exist. Home Assistant deployed at Docker and this is first integration which wasn't want to connect.
