### ISSUE TITLE
Zemismart Smart Curtain Rail

### ISSUE THREAD

**Issue by Fannangir** [make-all/tuya-local#249]
I have added Zemismart Curtain into the integration, it has detected the type automatically.
The control (arrows) and the position control works, but it does not provide feedback of the position bar, if moved using the arrows.
I have looked into dpids in tuya cloud platform, it uses dpid 1 for basic control, dpid 2 for position control, dpid 3 for current position.
Does the integration implement dpid 3 to read current curtain position?

Information from cloud platform:
{
  "result": {
    "category": "cl",
    "functions": [
      {
        "code": "control",
        "dp_id": 1,
        "type": "Enum",
        "values": "{\"range\":[\"open\",\"stop\",\"close\"]}"
      },
      {
        "code": "percent_control",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "control_back",
        "dp_id": 5,
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "control",
        "dp_id": 1,
        "type": "Enum",
        "values": "{\"range\":[\"open\",\"stop\",\"close\"]}"
      },
      {
        "code": "percent_control",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "percent_state",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "control_back",
        "dp_id": 5,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_state",
        "dp_id": 7,
        "type": "Enum",
        "values": "{\"range\":[\"opening\",\"closing\"]}"
      }
    ]
  },

**Comment by make-all** [comment]
There is no specific support for this device.  I think it has detected the simple blinds controller, which is missing dp id 3.

**Comment by Fannangir** [comment]
OK, understood.
Is there a chance you could add it please?

**Comment by Fannangir** [comment]
@make-all, could you please look into it?
The issue is that I loose synchronization between the actual position when I pull the curtain, to its state in HomeKit.
When I pull the curtain by hand, it moves all the way, and the synchronization lost.
Thanks.

**Comment by make-all** [comment]
For update speed, see #176
