### ISSUE TITLE
Tonepie cat litter box

### ISSUE THREAD

**Issue by med06053** [make-all/tuya-local#2493]
### Description

The app works ok with my cat litter box, which is a copy of tonepie, but when trying to calibrate the litter surface it always ends up the same independently of setting the value from 0 to 6.
Is it an app or software problem?

### Steps to reproduce

After the automatic cleanup, the litter always leans to the left, even if I set the value to 6, to make it lean to the right.

### Expected behaviour

The litter should lean to the left if the value is set closer to 0, or to the right if the value is set closer to 6.

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [ ] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
This is not tonepie clone manufacturer support.
