### ISSUE TITLE
Greenwind dehumidifier

### ISSUE THREAD

**Issue by rodrigoGA** [make-all/tuya-local#25]
When adding a new device the only type it shows is simple_switch

![Captura de pantalla de 2021-07-07 00-44-06](https://user-images.githubusercontent.com/2334523/124697007-7bf7fe00-debc-11eb-9089-3bf47934624f.png)

**Comment by make-all** [comment]
What device are you trying to add?  Only matching types are listed (simple switch matches most devices, as all it needs is just a boolean dps 1).

**Comment by rodrigoGA** [comment]
I am trying to add a dehumidifier. How do you recognize the type of device?

**Comment by make-all** [comment]
The type is recognized from the dps that the device returns.  Unfortunately there is no standard for this, and different device manufacturers map the features onto the Tuya module differently even for the same device type. 

If you look in the Home Assistant log, you might see a message about the dps that are being returned by your device.  Otherwise, you can use a command line tool like tuya-cli to show the dps.  With a bit of experimenting, changing settings on the device's panel and checking the dps again, you should be able to get a good idea what most of them are for.

With this information, and some identifying information about the brand and model of the dehumidifier, I can make a new config file for it, so it will be recognized.

**Comment by make-all** [comment]
0.8.5 adds support for an ElectriQ dehumidifier, so you might like to try configuring your device again.

It also adds some Warning messages in the HA log now if you configure a device that is not fully supported. So you should see some log messages that you can paste in as a reply if the ElectriQ dehumidifier is also not a match for yours.

**Comment by rodrigoGA** [comment]
Thank you very much for the quick answer.
Unfortunately it didn't work with the new version, it still recognizes it as switch

The log
```
2021-07-09 10:33:07 WARNING (MainThread) [homeassistant.components.http.forwarded] A request from a reverse proxy was received from 172.24.0.3, but your HTTP integration is not set-up for reverse proxies; This request will be blocked in Home Assistant 2021.7 unless you configure your HTTP integration to allow this header


2021-07-09 10:33:08 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches simple_switch with quality of 20%. DPS: {'1': False, '5': '3', '6': 50, '15': 0, '18': 70, 'updated_at': 1625837587.9881139}


2021-07-09 10:33:08 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/
```

**Comment by make-all** [comment]
It looks like the DPS will map to the following functions:
1: Power
5: Preset Mode (converted to a numeric value)
6: Target Humidity
15: Error code, or timer
18: Current Humidity

For preset modes, what are the available presets, and can you do some experimenting with how they map to the dps 5 values?
And can you confirm if the device gives warnings like tank full through the app, in which case 15 will definitely be an error code.  For dehumidifiers, tank full is normally the main error code, it may have the same code when you remove the tank, or it might use a different code for those two cases.  If you can find out what codes it uses, they can be converted to more friendly messages.

Also, what is the brand and/or model of the dehumidifier so it can be identified in the config file naming?

**Comment by rodrigoGA** [comment]
> For preset modes, what are the available presets, and can you do some experimenting with how they map to the dps 5 values?

How to discover the presets? Currently I can only configure it as a switch

> And can you confirm if the device gives warnings like tank full through the app, in which case 15 will definitely be an error code. For dehumidifiers, tank full is normally the main error code, it may have the same code when you remove the tank, or it might use a different code for those two cases. If you can find out what codes it uses, they can be converted to more friendly messages.

How do I discover the codes that the app uses? Should i use a proxy? like charlesproxy


> Also, what is the brand and/or model of the dehumidifier so it can be identified in the config file naming?
The dehumidifier brand is [greenwind](https://greenwind.online/sitio/ )

This is the configuration json from tuya webpage

```
{
  "result": {
    "active_time": 1625624783,
    "biz_type": 0,
    "category": "kt",
    "create_time": 1625619702,
    "icon": "smart/icon/1493368623_0.png",
    "id": ...,
    "ip": ...,
    "lat": "",
    "local_key":  ...,
    "lon": "",
    "name": "Dehumidifier",
    "online": true,
    "owner_id":  ...,
    "product_id": "3ZXJDubQ13lNTaLT",
    "product_name": "Dehumidifier",
    "status": [
      {
        "code": "switch",
        "value": false
      }
    ],
    "sub": false,
    "time_zone":  ....,
    "uid": ...,
    "update_time": 1625624806,
    "uuid": ....
  },
  "success": true,
  "t": 1625625355741
}

```

**Comment by make-all** [comment]
For discovery of more information about the protocol, you can use a command-line tuya client like tuya-cli (nodejs) or tinytuya (python) to query the DPS after changing settings on the control panel or in the official app.

Or, I can add a basic config based on the information above, and you will be able to observe (but not change) the preset mode so you can see how it matches up with the device's presets.

As an example, for other devices these are the presets that are available:

Goldair Dehumidifier: Normal, Low, High, Dry Clothes
Kogan Dehumidifier: Low, Medium, High, Dry Clothes
ElectriQ Dehumidifier: Auto, Low, High, Fan-Only
Eanons Humidifier: Sleep, Auto, Normal
