### ISSUE TITLE
Electricity sensor LSC Smart Power Plug (bfd34f0cf7f8dc33401uyr)

### ISSUE THREAD

**Issue by cob94440** [make-all/tuya-local#2508]
### Description

Device seems to work except energy sensor. it has Wh instead of kWh And it was like 1 wh intstead of 1.33 kWh

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [ ] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
This is how most Tuya smartplugs report energy usage, you are better off using an integration helper with the power sensor unless you have a rare smartplug that acts more like a proper energy meter.
