### ISSUE TITLE
PZIOT-E01 integration 

### ISSUE THREAD

**Issue by KazaiTg** [make-all/tuya-local#2511]
### Description

Tuya local has integration with this device but problem start when you have more than one of thoses
In tuya developer plattform the only visible difference from obvious one's  is name of device ( not name in the APP ) 

First device has this values on the cloud "Get device information" in cloud APP Explorer has this two similar properties :
      "model": "PZIOT-E01",
      "name": "PZIOT-E01",

And second added device has this:
      "model": "PZIOT-E01",
      "name": "PZIOT-E01 2",

And integration WON'T work manualy or automaticaly by Tuya SmartApp  way
Device is visible but the integration is telling that KEY or ID or something is wrong and cant connect

If you need more information i can provide them

Please fix integration with this device I have 8 of them  and only first is adding correctly 

Thanks

### Steps to reproduce

Add second device PZIOT-E01 in TUYA SMART  and try add that device in tuya local in HA

### Expected behaviour

Fix problem and unload more than one device of this model:  PZIOT-E01

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [ ] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
Sorry it isn't clear from your description what exactly is going wrong.

Please expands the steps to reproduce in detail, and add the log messages that are coming from tuya-local when the bug is observed.

**Comment by KazaiTg** [comment]
ONLY first device ( model PZIOT-E01 ) can be added to tuya local integration
When you try to add more PZIOT-E01 devices you can't do it 
![image](https://github.com/user-attachments/assets/c5ac325f-5690-49e9-aaa5-a513a0a7f814)
All inputs are filled with valid data and device is reachable in network but you can't add second , third devece and so on.
You can only add one device of this type. After that you will have error:
"Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect."
Same configuration for all devices beside adreses ids local keys

**Comment by KazaiTg** [comment]
Devices are connected to WIFI and visible in TUYA SMART and responding without problem, PING from windows command line has communication with devices.
In TuyaLocal when i choose Cloud option with ID from TuyaSmart  devices are listed and can be selected. After selecting device Tuya local get same details for device ( same I put on manual config ), On page "CONFIGURE YOUT TUYA DEVICES"  local key IP device ID  are the same for manual or cloud and stil when I click SUBMNIT i cant add them all have same error.

**Comment by make-all** [comment]
Without log messages, it is impossible to move further

**Comment by KazaiTg** [comment]
Please close this issue

The problem is somewhere else and concerns integration problems that do not always communicate with devices in the LAN that has more subnet classes and a lot of devices.

The integration cannot download information from the device even though the machine on which the home assistant is located can PING the device.

Sometimes you can try and try and the device does not want to be added to the integration, then you ping the device and try again to add the device to the integration and suddenly it starts working, the device is detected by Tuya Local and works correctly.
The devices have a permanently assigned static IP from DHCP.

This is communication problem and I can add more than one device of same type.

Thank You.
