### ISSUE TITLE
Tesvor S6 is not a vacuum

### ISSUE THREAD

**Issue by Braniff** [make-all/tuya-local#2519]
### Description

The device is since january supported but I can't add it to home assistant. I checked the productid in the yaml file "custom_components/tuya_local/devices/tesvor_s6_vacuum.yaml" and it is the same as my tesvor s6 sends.

### Steps to reproduce

1. Add new device
2. Login by qr code
3. Select device
4. Check id, IP and etc and click send

### Expected behaviour

The device should be a "Tesvor S6", but it is an "inkbird_ipt2ch_thermostat".

### Additional context

![image](https://github.com/user-attachments/assets/743e0a19-582b-4182-bb3e-7f6d9e244bc7)

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [X] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
There is nothing that can be done with this info.

Where are the logs?

**Comment by make-all** [comment]
Yes, that

**Comment by Nefesar** [comment]
II have the same problem
