### ISSUE TITLE
Double Gang Light Switch 6912HA no longer working after version 2024.11.1

### ISSUE THREAD

**Issue by BeHappy2021** [make-all/tuya-local#2535]
### Description

I have the touch light switch Double Gang Light Switch 6912HA. It has been working fine up until version 2024.11.1. I updated to version 2024.11.2 last week and I could no longer connect to the device. I deleted it and could not re-add it. I could get through all of the configuration (using either the local method or cloud) and it would fail at the final stage saying it couldn't connect 'might be an intermittent issue'. 

I checked all the details were correct (ID, key, protocol version) and I still could not connect to the device.

I rolled back to version 2024.11.1 and the device is connected and working properly again.

None of my other Tuya devices are affected by this issue.

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [X] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
Lately there have been issues of updates not downloading completely, I think HACS is prompting to restart HA too quickly. So you could try the update again. There is not a general problem with 2024.11.2, as others are using it without such problems.

**Comment by BeHappy2021** [comment]
Thanks for the quick response. I'll give the update a go tomorrow and get info from the logs if it doesn't work. It is weird that all the other devices are working, it is just this one that is failing to connect with 2024.11.2. I removed the device from Smart Life and did a full reset while trying.

I see there is a core update today so I'll do both tomorrow and see how it goes.

**Comment by BeHappy2021** [comment]
I've done the core update, then updated to the latest version of Tuya Local and everything appears to be working. I'll keep on checking and it all still good tomorrow I'll close this.

**Comment by BeHappy2021** [comment]
All still working so I'll close this. Thanks for being responsive with this.
