### ISSUE TITLE
How to calculate heating power consumption with Hysen thermostat based on time when heating is on

### ISSUE THREAD

**Issue by karnas99** [make-all/tuya-local#254]
Sorry for re-opening it thread it this way. But I would like to ask for advise. I am using this integration for HY08WE-4 and it works really grate. However I would like to calculate power consumption based on time when thermostat is heating, I can see entity thermostat which have three measurement - current temperature, target temperature and heating. Heating is showing when the heating is on. However I don't know how to extract this state. I believe it is field 101, but in DB it look weird.

Ideally would it be possible to implement this? I know W consumption of floor heating so I just need to calculate with the time when the it heating.

Thanks in advance.
![2](https://user-images.githubusercontent.com/65977799/198238254-1bb8725d-9cd7-4499-ab3e-2c0585f10429.PNG)
![1](https://user-images.githubusercontent.com/65977799/198238303-eb3cd97a-becd-4464-994c-cf40e07573df.PNG)

_Originally posted by @karnas99 in https://github.com/make-all/tuya-local/issues/104#issuecomment-1293201193_

**Comment by make-all** [comment]
The "heating" state is coming from the hvac_action attribute of the climate entity.  You would need to make a template sensor that conditionally sets the value to the power consumption of the heater or 0 depending on whether the value of hvac_action is "heating", or "idle" or "off".

If you have access to iot.tuya.com, you could also help to figure out what unknown_101 and the other unknown dps are by following the instructions from https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html for finding the datapoints in the debugger (start from step 7 if you already have an iot.tuya.com account, and ignore anything that talks about the Zigbee hub and sub devices).

**Comment by make-all** [comment]
It is possible that one of the unknown attributes gives a better format of the information you want.

**Comment by karnas99** [comment]
Hi,

thanks for reply. I will check some guide how to create sensor in HA. 
I have access to the iot tuya. However I don't know in which DP you are interested in. There are common things like power, mode, lock, heat etc. The last 4 are in chinnese.
![3](https://user-images.githubusercontent.com/65977799/198279308-3943d6b0-950d-446f-86be-99369f023fe0.PNG)

**Comment by karnas99** [comment]
OK so,
 there are following DP's

Power
Set Temperature
Current temp
Mode 
Lock
Fault
°C°F
Heat 
Ext temperature
Days of holiday
Settemp of holiday
Hightemp_Protect
LowTemp_Protect
Display Exttemp
Temp Calibration
Int Sensor Deadzone
Ext Sensor Deadzone
HighTemp Protection
LowTemp Protection
Max Temperature Limit
Min Temperature Limit
Temperature Sensor
Device State On Power
ProgramMode Type
Chineese 1
Chineese 2
Chineese 3
Chineese 4

There are also many event types - all logs I can find are for EVENT_TYPE_REPORT.
Here is the combination of heat and EVENT_TYPE_REPORT.

Then there is the output from debbug console. Is the Status Code: 200 what you are looking for?

General
Request URL: https://eu.iot.tuya.com/micro-app/cloud/api/v10/device/log/list
Request Method: POST
Status Code: 200 
Remote Address: 170.127.0.247:8080
Referrer Policy: strict-origin-when-cross-origin

Response Headers
cache-control: no-store
content-encoding: gzip
content-type: application/json; charset=utf-8
date: Thu, 27 Oct 2022 12:42:49 GMT
server: Tuya-Sec
set-cookie: csrf-token=jUJxZytH-1zw_KQutzmN9WsxXb_q_Il4eyq0; path=/; secure
set-cookie: csrf-token.sig=YjUXGqLAtfim-NIOlPucAIfT9KE; path=/; secure
set-cookie: s-sid=s:9bce6ff8-f515-4a40-ba33-ee616f1a52fc.4CvCOZ/YTnq8DUJuf/Nw3i3YXBBDfO5W0LBm5P2e0Tg; path=/; expires=Thu, 27 Oct 2022 18:42:49 GMT; httponly
set-cookie: fast-sid=4T6yC9DmXNf4koGByDjhaPpFYd-SqebN; path=/; expires=Mon, 31 Oct 2022 12:42:49 GMT; secure; httponly
strict-transport-security: max-age=31536000
vary: Accept-Encoding
x-b3-parentspanid: c9b246aa7e6a1110
x-b3-sampled: 1
x-b3-spanid: df3b48bb45f9f735
x-b3-traceid: a4574be9329cde16
x-content-type-options: nosniff
x-envoy-upstream-service-time: 213
x-fast-id: a4574be9329cde16
x-frame-options: *.tuya-inc.com
x-via: 1.1 fr
x-xss-protection: 1; mode=block
:authority: eu.iot.tuya.com
:method: POST
:path: /micro-app/cloud/api/v10/device/log/list
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
cache-control: no-cache
content-length: 286
content-type: application/json; charset=UTF-8
cookie: gTyPlatLang=en; notice_preferences=1:; notice_gdpr_prefs=0,1:; _tpmGuid=TY-42a21ac06f1d7346; tz=2; d41d8cd98f00b204e9800998ecf8427e=%5B%5D; region=EU; locale=en; fast-sid=4T6yC9DmXNf4koGByDjhaPpFYd-SqebN; _tpmSid=a7e08c872b724db48a0871a00376aff9f179a596b44689e554854b471509a088; projectCode=p1665744443160j9d8xx; _tpmSeqId=seq_id_4799a58a3f72ab4a; s-sid=s:9bce6ff8-f515-4a40-ba33-ee616f1a52fc.4CvCOZ/YTnq8DUJuf/Nw3i3YXBBDfO5W0LBm5P2e0Tg; 9e1c07d97bdbc7681a6f4ec2d55a8fb9=%5B%22smart_menu_cloud_develop_api_group%22%2C%22smart_menu_developer_platform_home%22%2C%22smart_menu_cloud_develop_api_explorer%22%5D; csrf-token=j46uOHa6-EMhdulosf_QkzWqAU1mdEs04o0E; csrf-token.sig=wOZ08xRi_dV_GRX7AXyeWceOV24
csrf-token: 42rFGsre-r5rE8Tw31aUq19NaDkZzslpHaOM
origin: https://eu.iot.tuya.com
pragma: no-cache
referer: https://eu.iot.tuya.com/cloud/device/detail/?id=p1665744443160j9d8xx&sourceId=eu1574179453335PL27v&sourceType=4&region=EU&deviceKey=deviceLogs&deviceId=78007030483fda4bf77f
sec-ch-ua: "Chromium";v="106", "Google Chrome";v="106", "Not;A=Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
x-requested-with: XMLHttpRequest
![5](https://user-images.githubusercontent.com/65977799/198288929-876dfb1f-70cb-475b-ba4d-3b10256f7cad.PNG)

**Comment by make-all** [comment]
These are the ones that will be interesting:
- Fault
- °C°F
- Display Exttemp
- Int Sensor Deadzone
- Ext Sensor Deadzone
- Chinese 1 (Programming - weekday parameter 1)
- Chinese 2
- Chinese 3
- Chinese 4

If the only difference between the Chinese language labels is the number on the end, then the translation is complete, but if they differ in other characters, see if you can copy the text, or if not send a screenshot of the dropdown showing all 4.
These are likely to be write-only, as there are only 5 slots for unknowns based on the data we have from the device.

For each of these, after selecting them in the dropdown, press the Search button.  A new "list" request should show up, the value of interest is in the Request payload, and labelled "code", as per the screenshot at https://www.zigbee2mqtt.io/assets/img/10_dev_tools.5d449195.png

**Comment by karnas99** [comment]
Here you go. There are two types of Chinese with numbering 1 and 2.

Fault
{startRowId: "", pageNo: 1, pageSize: 10, code: "12", type: "EVENT_TYPE_REPORT",…}
code
: 
"12"
deviceId
: 
"78007030483fda4bf77f"
endTime
: 
1666873548302
pageNo
: 
1
pageSize
: 
10
pageStartRow
: 
""
projectCode
: 
"p1665744443160j9d8xx"
region
: 
"EU"
sourceId
: 
"eu1574179453335PL27v"
sourceType
: 
"4"
startRowId
: 
""
startTime
: 
1666355148301
type
: 
"EVENT_TYPE_REPORT"

*****

°C°F
{startRowId: "", pageNo: 1, pageSize: 10, code: "101", type: "EVENT_TYPE_REPORT",…}
code
: 
"101"
deviceId
: 
"78007030483fda4bf77f"
endTime
: 
1666873548302
pageNo
: 
1
pageSize
: 
10
pageStartRow
: 
""
projectCode
: 
"p1665744443160j9d8xx"
region
: 
"EU"
sourceId
: 
"eu1574179453335PL27v"
sourceType
: 
"4"
startRowId
: 
""
startTime
: 
1666355148301
type
: 
"EVENT_TYPE_REPORT"

*****

Display Exttemp
code
: 
"108"
deviceId
: 
"78007030483fda4bf77f"
endTime
: 
1666873548302
pageNo
: 
1
pageSize
: 
10
pageStartRow
: 
""
projectCode
: 
"p1665744443160j9d8xx"
region
: 
"EU"
sourceId
: 
"eu1574179453335PL27v"
sourceType
: 
"4"
startRowId
: 
""
startTime
: 
1666355148301
type
: 
"EVENT_TYPE_REPORT"

******

Int Sensor Deadzone
code
: 
"110"
deviceId
: 
"78007030483fda4bf77f"
endTime
: 
1666873548302
pageNo
: 
1
pageSize
: 
10
pageStartRow
: 
""
projectCode
: 
"p1665744443160j9d8xx"
region
: 
"EU"
sourceId
: 
"eu1574179453335PL27v"
sourceType
: 
"4"
startRowId
: 
""
startTime
: 
1666355148301
type
: 
"EVENT_TYPE_REPORT"

*****

Ext Sensor Deadzone

code
: 
"111"
deviceId
: 
"78007030483fda4bf77f"
endTime
: 
1666873548302
pageNo
: 
1
pageSize
: 
10
pageStartRow
: 
""
projectCode
: 
"p1665744443160j9d8xx"
region
: 
"EU"
sourceId
: 
"eu1574179453335PL27v"
sourceType
: 
"4"
startRowId
: 
""
startTime
: 
1666355148301
type
: 
"EVENT_TYPE_REPORT"

********

Chineese 1

code
: 
"119"
deviceId
: 
"78007030483fda4bf77f"
endTime
: 
1666873548302
pageNo
: 
1
pageSize
: 
10
pageStartRow
: 
""
projectCode
: 
"p1665744443160j9d8xx"
region
: 
"EU"
sourceId
: 
"eu1574179453335PL27v"
sourceType
: 
"4"
startRowId
: 
""
startTime
: 
1666355148301
type
: 
"EVENT_TYPE_REPORT"

********

Chineese 2

code
: 
"120"
deviceId
: 
"78007030483fda4bf77f"
endTime
: 
1666873548302
pageNo
: 
1
pageSize
: 
10
pageStartRow
: 
""
projectCode
: 
"p1665744443160j9d8xx"
region
: 
"EU"
sourceId
: 
"eu1574179453335PL27v"
sourceType
: 
"4"
startRowId
: 
""
startTime
: 
1666355148301
type
: 
"EVENT_TYPE_REPORT"

**********

Chineese1

code
: 
"121"
deviceId
: 
"78007030483fda4bf77f"
endTime
: 
1666873548302
pageNo
: 
1
pageSize
: 
10
pageStartRow
: 
""
projectCode
: 
"p1665744443160j9d8xx"
region
: 
"EU"
sourceId
: 
"eu1574179453335PL27v"
sourceType
: 
"4"
startRowId
: 
""
startTime
: 
1666355148301
type
: 
"EVENT_TYPE_REPORT"

********

Chineese2

code
: 
"122"
deviceId
: 
"78007030483fda4bf77f"
endTime
: 
1666873548302
pageNo
: 
1
pageSize
: 
10
pageStartRow
: 
""
projectCode
: 
"p1665744443160j9d8xx"
region
: 
"EU"
sourceId
: 
"eu1574179453335PL27v"
sourceType
: 
"4"
startRowId
: 
""
startTime
: 
1666355148301
type
: 
"EVENT_TYPE_REPORT"
![ch1](https://user-images.githubusercontent.com/65977799/198296897-f2ece729-defe-4173-a812-6dcc8067ab15.PNG)
![ch1 2](https://user-images.githubusercontent.com/65977799/198296916-3bb6757d-b3b7-4713-a310-99209f3084d3.PNG)

**Comment by make-all** [comment]
I may have misinterpreted the meaning of this.  I thought it could be used for configuring the temperature that is displayed on the control panel, but maybe it is just reporting which temperature is displayed, and there is internal logic in the device that determines which to display.

**Comment by karnas99** [comment]
There is now such setting in the tuya app. 
Btw do you think it would be possible to integrate power consumption directly into integration? I would of course pay a coffee :-D

![68271](https://user-images.githubusercontent.com/65977799/198984152-07e9c8bb-3647-4dbb-9fad-fe7a3f88562e.jpg)
![60523](https://user-images.githubusercontent.com/65977799/198984173-64921533-2425-466e-bce1-081de015918c.jpg)

**Comment by make-all** [comment]
Sorry, but there is no information returned by the device that could directly be used for power consumption, and doing complex calculations is beyond the scope of this integration.

I suggest using a template sensor to get an instantaneous power reading (I think these still need to be defined in configuration.yaml, and an integration helper (available from the UI) to integrate over time into a kWh reading.

From https://www.home-assistant.io/integrations/template/, I would use something like the below (assuming 2000W when the heater is on - adjust as needed).

```yaml
template:
  - sensor:
      - name: Hysen Power
        unit_of_measurement: W
        state: >
          {% if state_attr('climate.hysen_thermostat', 'hvac_action') == 'heating' %}
          2000
          {% else %}
          0
          {% endif %}
```

**Comment by karnas99** [comment]
Thanks for the idea, it is showing something. I will play with it

**Comment by karnas99** [comment]
sorry for offtopic but can you please advise me with the calculation template you send is working well but I am struggling to get kWh.

I am using following:

# Power consumption
```
template:
  - sensor:
      - name: Big Bathroom heating consumption
        unit_of_measurement: W
        state: >
          {% if is_state_attr('climate.big_bathroom_thermostat', 'hvac_action', 'heating') %}
          750
          {% else %}
          0
          {% endif %}
                   
sensor:
  - platform: integration
    source: sensor.big_bathroom_heating_consumption
    name: big_bathroom_energy_spend
    unit_prefix: k
    
utility_meter:
  big_bathroom_consumption_daily:
    source: sensor.big_bathroom_energy_spend
    cycle: daily
```
however the consumption is wrong 

 You can see on the screen that consumption should be around 1kWh while big_bathroom_energy_spend is saying 8kWh.

Could you advise how to correct?

![1 (1)](https://user-images.githubusercontent.com/65977799/200584313-6701c858-4dd9-4960-b8e7-2076bebf0560.PNG)

**Comment by make-all** [comment]
It looks to be off by a factor of 10.  Maybe a bug in the Riemann sum integral integration, as the data coming out of this integration appears correct.
