### ISSUE TITLE
Ir-panel not responding to climate entity

### ISSUE THREAD

**Issue by Pherax** [make-all/tuya-local#2549]
### Description

I have succesfully added a IR-panel to home assistant via the Local tuya integration. But it will not respond to any setting via HA. I can control it via the Tuya app or via the remote.

After integration I got a nice climate entity so I added it to Home assistant. Now when i set any settings they just revert to what they where. When i do a change of setting via the remote or via the Tuya app I do see the updates in Homa Assistant.

device: byecold IR-panel  [https://www.amazon.de/-/en/dp/B0DF1PKDFP?ref=ppx_yo2ov_dt_b_fed_asin_title&th=1](url)

### Steps to reproduce

Switch on/off heat. Change temperature

### Expected behaviour

The device should follow the target setpoints.
[config_entry-tuya_local-01JBM6Z6G7WKXAGBM7PGHAGYBD.json](https://github.com/user-attachments/files/17898950/config_entry-tuya_local-01JBM6Z6G7WKXAGBM7PGHAGYBD.json)

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [X] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [X] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
This cannot be considered a bug, as this device is not supported and you are using another device's config with the expectation that it might work (but there are no guarantees that it will).

**Comment by Pherax** [comment]
Thanks for your comment, ill make a new device request.
