### ISSUE TITLE
11.3 - Weird RGBW Light Behavior

### ISSUE THREAD

**Issue by rac146** [make-all/tuya-local#2552]
I haven't had any issues with this automation until I upgraded to 11.3. A downgrade to 11.2 fixes whatever is happening. Not 100% sure but it might have something to do with the color names.

I have 17 lights in a light group called "Pot Lights". A simple automation will set the group to color name "blue" and brightness 50%. This has been working fine for a very long time, until 11.3 - now when I run the automation the RGBW lights just seem to go white. Really odd.  Just some light debugging here:

- If I take out the brightness % setting and the lights are initially off, it will set to blue correctly. 
- If the lights are set to white and I try to set to blue, nothing happens, they stay white.
- If I individually change a lights color (initially off or white), it will change properly
- If I change the group color wheel (initially off or white), it will change properly

** type of light is `rgbcw_lightbulb`

If I downgrade to 11.2 this problem goes away, and I can set a color name + brightness at the same time and the group works properly.

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [ ] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
I confirmed the issue. It is not due to the color name changes, but the brightness changes in 2024.11.3.
