### ISSUE TITLE
Failed to perform the action lock/unlock. lock is read only

### ISSUE THREAD

**Issue by FillHK** [make-all/tuya-local#2559]
### Description

Failed to perform the action lock/unlock. lock is read-only

`      "active_time": 1730753495,
      "bind_space_id": "196708031",
      "category": "jtmspro",
      "create_time": 1730753495,
      "custom_name": "",
      "icon": "smart/icon/ay1566269753407dl25G/5768fe0def75e0f7678c56d0c547757c.png",
      "id": "eb6f5febe09c14200eahqf",
      "ip": "",
      "is_online": true,
      "lat": "33.0551",
      "local_key": "xxx",
      "lon": "-97.0482",
      "model": "EL605A锐尔朗",
      "name": "KNOB LOCK",
      "product_id": "2hmqh0ty",
      "product_name": "KNOB LOCK",
      "sub": true,
      "time_zone": "-05:00",
      "update_time": 1732557092,
      "uuid": "6dd985327ee9c567"`

### Steps to reproduce

Devices have been added, and a lot of information was detected.

### Additional context

![image](https://github.com/user-attachments/assets/80b1fa9f-6b1e-44af-a2c3-26ad1201c3ed)

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [ ] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
There is nothing that can be done about this device limitation, especially without logs and not knowing which device we are talking about.
