### ISSUE TITLE
YSG BS01 lock does not respond to lock/unlock

### ISSUE THREAD

**Issue by dinamik1488** [make-all/tuya-local#2562]
### Description

The lock is on protocol 3.4 like YSG BS01 ble lock, but does not respond to gloss/unlock.

### Additional context

        "name": "bluetooth smart lock 3",
        "id": "xxxxxxxxxxxxxxx",
        "key": "xxxxxxxxxxxx",
        "mac": "xxxxxxxxxxx",
        "uuid": "xxxxxxxxxxxx",
        "category": "ms",
        "product_name": "bluetooth smart lock",
        "product_id": "isk2p555",
        "biz_type": 18,
        "model": "YSG_BS01",
        "sub": true,
        "icon": "https://images.tuyaeu.com/smart/icon/ay15724370520156puq6/0f960463f74a122aaf132f654d7622ed.png",
        "node_id": "d2b7e17bf98c6186",
        "mapping": {
            "1": {
                "code": "unlock_method_create",
                "type": "Raw",
                "values": {}
            },
            "2": {
                "code": "unlock_method_delete",
                "type": "Raw",
                "values": {}
            },
            "3": {
                "code": "unlock_method_modify",
                "type": "Raw",
                "values": {}
            },
            "8": {
                "code": "residual_electricity",
                "type": "Integer",
                "values": {
                    "min": -1,
                    "max": 100,
                    "scale": 0,
                    "step": 1
                }
            },
            "12": {
                "code": "unlock_fingerprint",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "13": {
                "code": "unlock_password",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "14": {
                "code": "unlock_dynamic",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "19": {
                "code": "unlock_ble",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "21": {
                "code": "alarm_lock",
                "type": "Enum",
                "values": {
                    "range": [
                        "wrong_finger",
                        "wrong_password",
                        "low_battery"
                    ]
                }
            },
            "28": {
                "code": "language",
                "type": "Enum",
                "values": {
                    "range": [
                        "chinese_simplified",
                        "english"
                    ]
                }
            },
            "31": {
                "code": "beep_volume",
                "type": "Enum",
                "values": {
                    "range": [
                        "mute",
                        "low",
                        "normal",
                        "high"
                    ]
                }
            },
            "47": {
                "code": "lock_motor_state",
                "type": "Boolean",
                "values": {}
            },
            "51": {
                "code": "temporary_password_creat",
                "type": "Raw",
                "values": {}
            },
            "52": {
                "code": "temporary_password_delete",
                "type": "Raw",
                "values": {}
            },
            "53": {
                "code": "temporary_password_modify",
                "type": "Raw",
                "values": {}
            },
            "54": {
                "code": "synch_method",
                "type": "Raw",
                "values": {}
            },
            "55": {
                "code": "unlock_temporary",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "60": {
                "code": "remote_no_pd_setkey",
                "type": "Raw",
                "values": {}
            },
            "61": {
                "code": "remote_no_dp_key",
                "type": "Raw",
                "values": {}
            },
            "62": {
                "code": "unlock_phone_remote",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "63": {
                "code": "unlock_voice_remote",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "64": {
                "code": "password_offline_time",
                "type": "String",
                "values": "{}"
            },
            "65": {
                "code": "unlock_offline_clear_single",
                "type": "Raw",
                "values": {}
            },
            "66": {
                "code": "unlock_offline_clear",
                "type": "Raw",
                "values": {}
            },
            "67": {
                "code": "unlock_offline_pd",
                "type": "Raw",
                "values": {}
            }
        },
        "parent": ""
    },

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [ ] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
Like most Tuya locks, this lock supports remote unlocking via the `remote_no_pd_setkey` and `remote_no_dp_key` dps.

`remote_no_pd_setkey` can only be used during the pairing process to set the key for remote unlocking. So whichever app is used for pairing the lock to the Tuya cloud holds the only key for remotely unlocking the lock using `remote_no_dp_key`.

Therefore this integration is unable to unlock any secure Tuya lock remotely, it can only report on the unlock methods that have been used.

**Comment by barban-dev** [comment]
> So whichever app is used for pairing the lock to the Tuya cloud holds the only key for remotely unlocking the lock using `remote_no_dp_key`.

You can find the key to remote unlock the device on Tuya IoT Cloud by looking on the device log.
