### ISSUE TITLE
New device request: "Catit Pet Feeder"

### ISSUE THREAD

**Issue by sindrebroch** [make-all/tuya-local#257]
Hi. I would love if the Catit Pet Feeder could get supported in the integration.
https://catit.co.uk/shop/catit-pixi-smart-feeder/

I doesn't seem to expose too much information in the tuya cloud, but here is a paylod:
```
{"result":{"devId":"<devId>","functions":[
{"code":"meal_plan","valueRange":"{}","valueType":"Raw","name":"喂食计划"},
{"code":"manual_feed","valueRange":"{\"min\":1,\"max\":12,\"scale\":0,\"step\":1}","valueType":"Integer","name":"手动喂食"},
{"code":"factory_reset","valueRange":"{true,false}","valueType":"Boolean","name":"恢复出厂设置"}],
"isOnline":true,"pid":"rlm2m69n0xzcvjpq","devName":" Pixi Smart Feeder","productName":"Pixi Smart Feeder (MCU)", "status":[
{"code":"meal_plan","valueRange":"{}","valueType":"Raw","name":"喂食计划"},
{"code":"manual_feed","valueRange":"{\"min\":1,\"max\":12,\"scale\":0,\"step\":1}","valueType":"Integer","name":"手动喂食"},
{"code":"factory_reset","valueRange":"{true,false}","valueType":"Boolean","name":"恢复出厂设置"},
{"code":"feed_report","valueRange":"{\"min\":0,\"max\":12,\"scale\":0,\"step\":1}","valueType":"Integer","name":"喂食结果上报"}],
"productCategory":"Pet Feeder"},"t":1666974645990,"success":true,"status":"ok"}
```

I tried adding it to the integration, and found this in the logs:
```
Test refreshed device state: {"devId": "<devId>", "dps": {"14": 1, "101": 1, "102": true, "103": false, "104": " ", "updated_at": 1666974030.715839}}
```

Thanks! And great job with the integration.

**Comment by make-all** [comment]
Are you able to get the information from the tuya cloud that contains dpId entries?  Or use the device debugger in the tuya developer portal on the device to capture this as documented in https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html (section 7 onwards)

**Comment by make-all** [comment]
Support was added a couple of versions ago, but is most likely not properly working, as I am not sure I properly understand how this device works.

**Comment by make-all** [comment]
Closing due to no feedback after a month.  The device will remain marked as experimental, as I am not confident that I have guessed correctly as to how the device operates.
