### ISSUE TITLE
Request support for Aeratron Ceiling Fan

### ISSUE THREAD

**Issue by doertli** [make-all/tuya-local#2574]
### Log message

```text
This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:393
integration: Tuya Local (documentation, issues)
First occurred: 11:00:30 AM (1 occurrences)
Last logged: 11:00:30 AM

Device matches mellerware_citymove_vacuum with quality of 60%. DPS: {"updated_at": 1732924805.2377574, "1": false, "15": false, "16": 0, "101": "0", "102": "TimeOff"}
```

### Product ID

iarwcyttkv1kvent

### Product Name

Aeratron AE3+

### DPS information

```
{ "result": { "model": "{\"modelId\":\"0000039kr8\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":3,\"accessMode\":\"rw\",\"code\":\"fan_speed\",\"description\":\"\",\"name\":\"speed\",\"typeSpec\":{\"type\":\"value\",\"max\":100,\"min\":1,\"scale\":0,\"step\":1,\"unit\":\"\"}},
{\"abilityId\":8,\"accessMode\":\"rw\",\"code\":\"fan_direction\",\"description\":\"\",\"name\":\"direction\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"forward\",\"reverse\"]}},
{\"abilityId\":15,\"accessMode\":\"rw\",\"code\":\"light\",\"description\":\"\",\"extensions\":{\"attribute\":\"16\"},\"name\":\"灯光\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":16,\"accessMode\":\"rw\",\"code\":\"bright_value\",\"description\":\"\",\"name\":\"灯光亮度\",\"typeSpec\":{\"type\":\"value\",\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"\"}},
{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"fan\",\"description\":\"\",\"name\":\"Fan\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"Breeze\"]}},
{\"abilityId\":102,\"accessMode\":\"rw\",\"code\":\"Time\",\"description\":\"\",\"name\":\"Timing\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"TimeOff\",\"1H\",\"2H\",\"3H\",\"4H\",\"5H\",\"6H\",\"7H\",\"8H\",\"9H\",\"10H\",\"11H\",\"12H\"]}},
{\"abilityId\":103,\"accessMode\":\"rw\",\"code\":\"FAN_value\",\"description\":\"\",\"name\":\"FAN_value\",\"typeSpec\":{\"type\":\"value\",\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"\"}}]}]}" }, "success": true, "t": 1733737784715, "tid": "eb5b7231b61211efbb1feeec0f1e308d" }
```

<details>

```text
Product name that appears in Tuya is "SYB-SYC"

primary_entity:
  entity: fan
  dps:
    - id: 1
      type: boolean
      name: Switch
    - id: 3
      name: Speed
      type: integer
      range:
        min: 1
        max: 6
    - id: 8
      name: Direction
      type: string
```

</details>

### Information about how the device functions

https://en.aeratron.io/products/ae3-series

I imagine the whole family of Aeratron fan models are the same (given a standard 'optional wifi control unit' has to be ordered for any of them to be wifi compatible, and it's the same wifi controller unit for all), so may not want to make it specific to Aeratron's "AE3+" model

**Comment by make-all** [comment]
The dps log does not match with the config you have provided instead of DPS information. Are you able to log in to platform.tuya.com to collect more detailed info?

**Comment by doertli** [comment]
Ah! Just ran the script and then exportcodes(). This is the export results:
{"1":"Switch","3":"Speed","8":"Direction Fan","15":"Light","16":"Brightness","101":"FAN","102":"Timer","103":"FAN_value"}

Is there anything else I can provide? (Tuya now seems to require a subscription for some of the other introspections).

**Comment by make-all** [comment]
You should be able to get to Cloud / API Explorer with the basic Free subscription, and get the QueryThingsDataModel result (under Device Control, I think).  That is the one highlighted in the New Device template as being most useful. I don't know where you found this script with "exportcodes()", but the info it is returning is not enough to make a config with.

**Comment by doertli** [comment]
Thanks! Found it. But still needs subscription (see screenshot). I've asked for my trial to be extended.
<img width="1643" alt="Screenshot 2024-12-09 at 8 36 45 pm" src="https://github.com/user-attachments/assets/75dd9690-d22f-44ac-ac82-904dbf8aba7d">

However, looks like it conforms to the generic fan profile, with dps values 1 (switch), 3 (speed: 1 to 6), 8 (direction: forward/reverse) 

The script + exportcodes() instructions are per this link: https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html (from your readme).
