### ISSUE TITLE
Integration disappeared following upgrade to 0.20.1

### ISSUE THREAD

**Issue by Fannangir** [make-all/tuya-local#259]
Hi,
After updating from 0.20.0 to 0.20.1, the integration has disappeared from Integrations page.
The devices are still working.
Home Assistant 2022.10.5.
Could it be related to the change of the manifest to 2022.11.XX support?
Reinstalled 0.20.0 back, the integration appeared back in the integrations page.
Thanks.

**Comment by skorpionwap** [comment]
I also have problems with this update.  I can't even install the previous version...The download is not loading.  It remains pending.  The devices work but no longer appear in the devices menu.

**Comment by make-all** [comment]
It looks like you are right, that HA 2022.11 change is not backwards compatible, my testing was insufficient and overlooked the integrations page.  Strange that there is no log message about it.

**Comment by Berserkir-Wolf** [comment]
Updating to 0.20.2 brought the Tuya Local entry in my integrations list back.

**Comment by Fannangir** [comment]
Solved by 0.20.2 update.
Thank you very much.
