### ISSUE TITLE
The use of sensor for mmWave presence sensor is deprecated and should be replaced by binary_sensors

### ISSUE THREAD

**Issue by felipecrs** [make-all/tuya-local#2595]
### Description

I received this in my Home Assistant logs:

```
This error originated from a custom integration.

Logger: custom_components.tuya_local.helpers.config
Source: custom_components/tuya_local/helpers/config.py:34
integration: Tuya Local (documentation, issues)
First occurred: 1:15:14 PM (1 occurrences)
Last logged: 1:15:14 PM

The use of sensor for mmWave presence sensor is deprecated and should be replaced by binary_sensors (motion and occupancy).
```

To be honest I don't know why. May you know? As far as I can tell, there's already a motion and occupancy binary sensor.

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [ ] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
Because it was released with an incorrect entity type. Deprecation gives users time to update their automations etc without suddenly breaking their config.

**Comment by felipecrs** [comment]
Oh, got it. It's just a warning to myself then. Thank you very much.
