### ISSUE TITLE
Missing heating state visual

### ISSUE THREAD

**Issue by DrFate09** [make-all/tuya-local#2598]
### Description

I previously worked with you to add my smart heater to the plugin and it has been working great since then. 

I have noticed one small missing visual state when using it in on HA Dashboard when compared to other climate devices. 

In the provided screenshot, my Nest thermostat (top) has a red background visual to indicate that it heating, with the status "heating". My Tuya smart heater (bottom) only has the status "heat" with no heating visual. 

Is there possibly a missing attribute that HA needs or does HA need the status "heating" rather than "heat"? Thinking out loud here haha. 

It might be the same for the cooling status.

![Screenshot_20241202-142552](https://github.com/user-attachments/assets/d9304c7a-1dc3-4bfb-9527-04ba0ca1dec1)

### Confirmation

- [ ] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [ ] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
If the device does not provide the information, it cannot be shown.
