### ISSUE TITLE
Kesser "Glas IR Heater" incorrect min. Temp

### ISSUE THREAD

**Issue by LotharWoman** [make-all/tuya-local#2599]
### Description

The heater is correctly recognized with all entities. However, the recognized value for the minimum temperature of 10°C is incorrect. The heater can be turned down to a temperature of 5°C.

### Additional context

 "pending_state": {},
    "connected": true,
    "force_dps": [],
    "home_assistant": {
      "name": "Kesser IR-Heater",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "climate.kesser_ir_heater",
            "state": "heat",
            "attributes": {
              "hvac_modes": [
                "heat",
                "off"
              ],
              "min_temp": 10,   **_should be 5°C_**
              "max_temp": 30,
              "target_temp_step": 1.0,
              "current_temperature": 16,
              "temperature": 23,
              "hvac_action": "heating",
              "friendly_name": "Kesser IR-Heater",
              "supported_features": 385
            },
            "last_changed": "2024-12-02T23:14:15.459019+00:00",
            "last_reported": "2024-12-02T23:14:15.459019+00:00",
            "last_updated": "2024-12-02T23:14:15.459019+00:00"
          }
        }

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [X] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [X] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by LotharWoman** [comment]
Hello @make-all,

I just downloaded tuy-local new from Github and reinstalled it. I can't notice any change. "min_temp": 10, is still recognized, but not 5
[config_entry-tuya_local-01JE62GRAA8VQEBH8R3QY5JEVY.json](https://github.com/user-attachments/files/17991757/config_entry-tuya_local-01JE62GRAA8VQEBH8R3QY5JEVY.json)
°C.

**Comment by make-all** [comment]
No change has been made.

**Comment by LotharWoman** [comment]
Hello @make-all,
i solved the problem for myself. I adjusted the file "kesser_infrared_wall_heater.yaml" in the folder "\config\custom_components\tuya_local\devices".
But i think the solution probably cannot be adopted as the original device is a 400w wall heater and it may not support 5°C?
My heater is a Kesser glass IR heater with 600w.
