### ISSUE TITLE
Updateinterval "universal remote control"

### ISSUE THREAD

**Issue by LotharWoman** [make-all/tuya-local#2608]
### Description

Hello,
with the device "universal remote control" (ir_remote_sensors.yaml) the data comes very incomplete. The device cannot handle queries that are too frequent.
 When setting up the integration "Local Tuya" from (https://github.com/xZetsubou/hass-localtuya/) there is the option to specify an update interval. (see screenshot) From 60 seconds onwards, the data is delivered without gaps.
Is it possible to integrate a configuration point for the interval in tuya-local?
Can this possibly be added manually in the ir_remote_sensors.yaml?

### Expected behaviour

The device should update entities ID 101,102 only >60sec.

### Additional context

![grafik](https://github.com/user-attachments/assets/c1e715ef-8144-4e4e-af49-66495a9e55bf)

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [ ] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
I don't want to complicate the config like localtuya does with lots of config options for broken devices. If your device doesn't work at reasonable speeds, you are better off buying a new one.
