### ISSUE TITLE
Local controll thermostat not working

### ISSUE THREAD

**Issue by ckegels** [make-all/tuya-local#262]
hi, i am sure this is the wrong place so please point me in the right direction if so.

first off amazing work on this, couldnt get my thermostat to work with local tuya.

so the issue i have is that when i block this device from the internet and i block dns for it too, the device will not respond after about 20 min so the first 20min without internet it is fine and works after that the valve wont open anymore and the set temperature keeps reseting.

any idea what could be causing this?

**Comment by make-all** [comment]
No, I don't have any insight into the internal firmware of devices. It is quite common for devices to stop responding after a long period online, but 20 minutes is the shortest I've seen.

**Comment by ckegels** [comment]
you mean long period offline because the issue only comes when i disconnect it from the internet, local control will work but then just stop working for no reason

**Comment by ckegels** [comment]
i block the device from internet and block dns port 53, am i missing something?

**Comment by make-all** [comment]
Sorry, I am not able to help any further with this, it is an issue with your device, not with this integration.
