### ISSUE TITLE
Getting error while trying to add device

### ISSUE THREAD

**Issue by zer0isdoing** [make-all/tuya-local#2637]
### Description

I followed the steps to get Device ID and Local Key and I am already using static IP for my devices. And I doubled checked that these IDs are correct or not but while trying to add my first device I am getting this error: "Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect.". I googled that and solution was defining IP address while adding device but like I said I am already using static IP address. These devices I am trying to add is not Tuya branded however they are added via Tuya app and obviously I can see them in the Tuya IOT. 

I have only Tuya cloud integration(which was disabled to test if it was causing the issue, which was not).
And I have Tuya Local. HA is working in VM in Proxmox.

I've got this log from home assistant:
This error originated from a custom integration.

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:475
integration: Tuya Local (documentation, issues)
First occurred: 3:44:28 PM (14 occurrences)
Last logged: 4:08:09 PM

Test protocol error 901: Network Error: Unable to Connect

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [ ] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [X] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
Connection issues have too many external causes for this to be considered a bug with so little evidence.

See discussion #522
