### ISSUE TITLE
Request support for LSC Smart Wall Dimmer

### ISSUE THREAD

**Issue by croskam** [make-all/tuya-local#2646]
### Log message

```text
This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:299
integration: Tuya Local (documentation, issues)
First occurred: December 14, 2024 at 22:34:41 (2 occurrences)
Last logged: 09:58:06

Could not find device: bf91aXXXX49342e118XXXX
```

### Product ID

sz9fil14ndvneelz

### Product Name

LSC Smart Wall Dimmer ('wall dimmer' in iot.tuya.com)

### DPS information

```text
{
  "result": {
    "active_time": 1734182533,
    "biz_type": 0,
    "category": "tgkg",
    "create_time": 1734180003,
    "icon": "smart/icon/ay1541056239985fDGjj/6fe41f0dda204d30fb997c336b8b2bd5.png",
    "id": "bf91af0d249342e118XXX",
    "ip": "77.173.146.12",
    "lat": "0",
    "local_key": "<S4@v|t*/Y8g|9-f",
    "lon": "0",
    "model": "5226000300",
    "name": "Bar light",
    "online": true,
    "owner_id": "211195504",
    "product_id": "sz9fil14ndvneelz",
    "product_name": "Wall Dimmer",
    "status": [
      {
        "code": "switch_led_1",
        "value": true
      },
      {
        "code": "bright_value_1",
        "value": 324
      },
      {
        "code": "brightness_min_1",
        "value": 324
      },
      {
        "code": "countdown_1",
        "value": 0
      }
    ],
    "sub": false,
    "time_zone": "+01:00",
    "uid": "eu1731017645776pwh0I",
    "update_time": 1734204117,
    "uuid": "d5d033a4ac58711b"
  },
  "success": true,
  "t": 1734261494120,
  "tid": "467e102abad611efbc549ae2a79b4875"
}
```

### Information about how the device functions

After adding this device to the Tuya Smart app, and adding this device through the 'Smart Life cloud-assisted device setup', it returns the page to select the new device correctly. 
I select the correct device without a gateway.
The next page informs me about obtaining the ip addres. When clicking next, the page shows me the device_id, local_key, protocol (3.3) but is missing the IP Address. 
When I enter the IP addres manually, the error 'Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect.'  shows up and adding the device is not possible.
Other LSC devices have been added flawlessly.

Also I found these 4 lines in homeassistant.log:
2024-12-15 10:14:22.917 WARNING (MainThread) [custom_components.tuya_local.config_flow] Connection test failed with <class 'Exception'> network error:(-9999999) sign invalid
2024-12-15 10:14:22.918 WARNING (MainThread) [custom_components.tuya_local.config_flow] Re-authentication is required.
2024-12-15 10:17:25.239 WARNING (MainThread) [custom_components.tuya_local.config_flow] Could not find device: bf91aXXXX49342e118XXXX
2024-12-15 10:18:32.230 WARNING (SyncWorker_12) [custom_components.tuya_local.device] Test protocol error 901: Network Error: Unable to Connect

Thanks for your support!

**Comment by make-all** [comment]
The statement "other LSC devices have been added flawlessly" suggests that this is not a new device request, so closing.

**Comment by croskam** [comment]
Hi there,
I mentioned 'other LSC devices have been added flawlessly' to emphasize that integrating LSC (tuya) devices is possible with my homeassistant setup and that this problem specifically appeared with this new device. This new devide just can't recover the ip address, although it is visible on the network and entering the actual ip address does not resolve the issue. I am not sure why it cannot acccess the device on the actual ip address.
Please reopen this issue, as I could not find anything related to this device, and it seems not to be supported by tuya local yet.

**Comment by make-all** [comment]
There is no information to justify reopening this. Connection problems can have many external causes, and can only be considered a bug with firm evidence.

**Comment by croskam** [comment]
Ok, thank you for the response! I hope someday I will find the cause. IF it could find the local ip address, would it still work withour having an specific listing in your custom_components/device ? Or does it specifically need a yaml file?

For example: LSC_SMART_Connect_RGB-CCT_Bulb is mentioned and working perfectly! Not sure if I can add devices, even without having a specific ernty in your devices files
