### ISSUE TITLE
Integration not working due to No DPS returned from device 

### ISSUE THREAD

**Issue by mrgionsi** [make-all/tuya-local#2649]
### Description

Trying to add beacon RGBCW as sub-devices via Gateway:
https://it.aliexpress.com/item/1005006535865050.html
`
 "product_name": "Beacon RGBCW",
    "product_id": "ctmqpnjk",
`
When try to integrate it response comes :
Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect.
In the logs: 
`
2024-12-15 14:46:07.453 ERROR (MainThread) [custom_components.tuya_local.device] Failed to refresh device state for Test.
`

I can see from other integration LocalTuya no DPS are returned.

Light bulb is write_only, if can help.

### Steps to reproduce

1. Login with App
2. Add subdevice

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [ ] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
Write only lightbulbs cannot be supported. We need to know the bulb's state to be able to change it.
