### ISSUE TITLE
Cannot add climate device

### ISSUE THREAD

**Issue by whaak58** [make-all/tuya-local#2656]
### Description

I add a new device in tuya-local. If I a step for end I have to choose a device type. But there is now climate device! I can choose from 13 devices. The first one is basic_ir_remote, the last one zigbee_waterleak_sensor. What can I do to get a climate device?

### Steps to reproduce

Add a tuya-device and all will working fine, without the last step, choose the device type.

### Expected behaviour

To choose a climate device

### Additional context

![image](https://github.com/user-attachments/assets/3ae8f721-5847-4296-8c37-edcdd97d3dfb)

### Confirmation

- [ ] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [ ] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [ ] This is not requesting addition of a new device.

**Comment by make-all** [comment]
Device not identified
