### ISSUE TITLE
A1 Max smart lock

### ISSUE THREAD

**Issue by Marcosangalli030164** [make-all/tuya-local#2664]
### Description

When I try to unlock the lock, the lock don't open. However when i try to lock, the lock works without problems

### Steps to reproduce

1.Push the unlock button

### Expected behaviour

Open the lock

### Additional context

[tuya_local-01JFC7DW35H83EH424751G2A6G-Door lock-83df467aa249b29e5dbe57b36b118d57.json](https://github.com/user-attachments/files/18176457/tuya_local-01JFC7DW35H83EH424751G2A6G-Door.lock-83df467aa249b29e5dbe57b36b118d57.json)
![smart lock](https://github.com/user-attachments/assets/004bb781-227b-4332-b496-43329884d57f)

Thank you

### Confirmation

- [ ] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [X] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [X] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
This is normal for any security focused lock. Only the app that it was paired with has the remote unlocking key.

**Comment by Marcosangalli030164** [comment]
with the Alexa skill you can open the door after creating a voice password 
In the smart life app, remote control is included in the options
smart lock is connected with gateway 

thanks for the work

![Screenshot_2024-12-18-09-09-47-541_com tuya smartlife (1)](https://github.com/user-attachments/assets/03a70780-146c-41a9-b607-6da0c10f34a7)
