### ISSUE TITLE
Smart Kettle Climate Warning

### ISSUE THREAD

**Issue by Krispkiwi** [make-all/tuya-local#267]
Hey Mate,

Just letting you know the Smart Kettle Climate integration is triggering a warning in the logs 
"Unrecognised HVAC Mode of None ignored"

**Comment by make-all** [comment]
It is known that this device sometimes fails to report its switch state.  If you can dowload the device diagnostics from the Settings / Devices / (tuya kettle) page, it might help understand why (is the protocol version unusual perhaps)

**Comment by make-all** [comment]
The new 0.21.0 (2022.12.0) release may help with this, as it will no longer forget the previous state of the switch if the device decides to stop reporting it.

**Comment by Krispkiwi** [comment]
Hey mate, sadly it does still show up. I went to look for the diagnostics but couldn't find them on the Tuya website after they've switched the layout and name options for everything.

**Comment by make-all** [comment]
The diagnostics should be in Home Assistant.

**Comment by Krispkiwi** [comment]
Ah, I understand what you mean now. I've restarted my home assistant about half an hour ago and haven't seen the error yet. I'll send it through as soon as It pops up.

**Comment by Krispkiwi** [comment]
Just proving a quick update not to leave you hanging, I've taken a look at the logs the past day or so and haven't seen the error so It doesn't appear to be happening all the time or at least not as frequently

**Comment by make-all** [comment]
Thanks, I still think there is improvement that can be done, so I will leave this open.

**Comment by Krispkiwi** [comment]
Just noticed it in the log "Unrecognised HVAC Mode of None ignored"

Diagnostics says this:

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.12.8",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Pacific/Auckland",
    "os_name": "Linux",
    "os_version": "5.15.76-v8",
    "supervisor": "2022.12.1",
    "host_os": "Home Assistant OS 9.4",
    "docker_version": "20.10.19",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "watchman": {
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    },
    "tuya_local": {
      "version": "0.21.0",
      "requirements": [
        "pycryptodome~=3.16.0",
        "tinytuya==1.9.1"
      ]
    },
    "spotcast": {
      "version": "v3.6.30",
      "requirements": [
        "spotify_token==1.0.0"
      ]
    },
    "multiscrape": {
      "version": "6.5.0",
      "requirements": [
        "lxml==4.9.1",
        "beautifulsoup4==4.11.1"
      ]
    },
    "hass_agent": {
      "version": "2022.11.9",
      "requirements": []
    },
    "niwa_tides": {
      "version": "1.1.2",
      "requirements": []
    },
    "bhyve": {
      "version": "3.0.0",
      "requirements": []
    },
    "smartir": {
      "version": "1.17.6",
      "requirements": [
        "aiofiles==0.6.0"
      ]
    },
    "steam_wishlist": {
      "version": "2.2.3",
      "requirements": []
    },
    "localtuya": {
      "version": "4.1.1",
      "requirements": []
    },
    "wyzeapi": {
      "version": "0.1.15",
      "requirements": [
        "wyzeapy==0.5.14"
      ]
    },
    "browser_mod": {
      "version": "2.1.2",
      "requirements": []
    },
    "fullykiosk": {
      "version": "1.1.0",
      "requirements": [
        "python-fullykiosk==0.0.11"
      ]
    },
    "hacs": {
      "version": "1.29.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "unifigateway": {
      "version": "0.3.3",
      "requirements": [
        "pyunifi==2.21"
      ]
    },
    "plex_recently_added": {
      "version": "0.3.8",
      "requirements": []
    },
    "garbage_collection": {
      "version": "4.10.2",
      "requirements": [
        "python-dateutil>=2.8.2"
      ]
    },
    "holidays": {
      "version": "1.9.1",
      "requirements": [
        "python-dateutil>=2.8.2",
        "holidays>=0.14.2"
      ]
    },
    "alexa_media": {
      "version": "4.3.2",
      "requirements": [
        "alexapy==1.26.4",
        "packaging>=20.3",
        "wrapt>=1.12.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya_local",
    "iot_class": "local_polling",
    "integration_type": "device",
    "name": "Tuya Local",
    "version": "0.21.0",
    "documentation": "https://github.com/make-all/tuya-local",
    "issue_tracker": "https://github.com/make-all/tuya-local/issues",
    "dependencies": [],
    "codeowners": [
      "@make-all"
    ],
    "requirements": [
      "pycryptodome~=3.16.0",
      "tinytuya==1.9.1"
    ],
    "config_flow": true,
    "is_built_in": false
  },
  "data": {
    "name": "Kitchen Kettle",
    "type": "kogan_glass_1_7l_kettle",
    "device_id": "**REDACTED**",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "api_version": 3.3,
    "status": {},
    "cached_state": {
      "updated_at": 1671685925.689364,
      "5": 23
    },
    "pending_state": {},
    "home_assistant": {
      "name": "Kitchen Kettle",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "climate.kitchen_kettle",
            "state": "unknown",
            "attributes": {
              "hvac_modes": [
                "off",
                "heat"
              ],
              "min_temp": null,
              "max_temp": null,
              "target_temp_step": 1,
              "current_temperature": 23,
              "friendly_name": "Kitchen Kettle",
              "supported_features": 0
            },
            "last_changed": "2022-12-22T03:07:02.456185+00:00",
            "last_updated": "2022-12-22T05:11:02.618841+00:00"
          }
        }
      ]
    }
  }
}

**Comment by make-all** [comment]
This is the same as the observation by the original reporter: only temperature is reported sometimes.

```
"cached_state": {
"updated_at": 1671685925.689364,
"5": 23
},
```

It is possible that using protocol version 3.2 may improve this (or it may not work at all, the main difference between 3.3 and 3.2 seems to be the way status is polled for).  2022.12.1 does introduce the possibility to set the protocol version to something other than "auto" (and this can be configured without removing and re-adding devices).

**Comment by make-all** [comment]
Same as #502
