### ISSUE TITLE
module 'tinytuya' has no attribute 'Device' while initialising device <my_device_id>

### ISSUE THREAD

**Issue by EduardMan** [make-all/tuya-local#2671]
### Description

Get an error when I try to add new device manually.
"Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect."

![2024-12-20_22-36-21](https://github.com/user-attachments/assets/50995267-f65d-4ae8-8068-4c5ec62f620c)

logs in HA:
Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:96
integration: tuya_local ([documentation](https://github.com/make-all/tuya-local), [issues](https://github.com/make-all/tuya-local/issues))
First occurred: 22:30:45 (13 occurrences)
Last logged: 22:34:25

**<class 'AttributeError'>: module 'tinytuya' has no attribute 'Device' while initialising device <my_device_id>**

HA Core: 2024.12.5
Supervisor: 2024.12.0
Operating System: 14.1
Frontend: 20241127.8

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [x] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [x] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
This seems to be a problem with your installation, and is not a bug in the integration.
