### ISSUE TITLE
QRCode for assisted configuration does not work for Konyks APP

### ISSUE THREAD

**Issue by acommuni** [make-all/tuya-local#2677]
### Description

When using Assisted configuration, I enter the user code from Konyks App but the QRCode is not recognized by Konyks App (Its a duplicated APP of Smart Life)

### Steps to reproduce

1/ Choose Assisted configuration
2/ Enter user code from Konyks App
3/ Scan QRCode

### Expected behaviour

Assisted configuration works for Konyks Appa

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [ ] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
As with the standard Tuya integration, it is probably necessary to use the Tuya branded apps (SmartLife, Tuya Smart) to pair your devices.
