### ISSUE TITLE
Nejdou mazat zarizeni

### ISSUE THREAD

**Issue by MichalUngr23** [make-all/tuya-local#2679]
### Description

Chci smazat zarizeni ktere jsme musel prihlasit na jinou sit a kdyz dám smazat zarizeni se neodebere ani po restartu HA

### Steps to reproduce

Udelat aby slo zařízeni odebrat 

### Confirmation

- [ ] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [ ] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
Probably a duplicate of #2578, but if not, there is insufficient information to investigate here.
