### ISSUE TITLE
New Device request "AGL Ultra Magic" - Lock with contact door status

### ISSUE THREAD

**Issue by raphaeleduardo42** [make-all/tuya-local#268]
Brand: AGL
Model: Ultra Magic
Country availability: Brazil

I've tried to retrieve as much important options as I could. From what I gather some share the same information, like the 3 and 124.
This model have a alarm when the door keeps opened for a defined time lenght, maybe this can be setted as well.

**https://www.aglbrasil.com/ultra-magic**

It has other models that share the same configuration, but with little differences how it behaves. Some with RFID options.

Thanks in advance.

`{'1': False, '3': False, '5': 0, '101': 1, '102': 1, '103': 'Silencioso', '104': True, '105': True, '107': True, '108': True, '109': True, '110': 0, '111': False, '112': True, '113': True, '114': 'Selecionar', '115': 3, '116': True, '117': '2', '120': False, '121': False, '122': False, '123': False, '124': False, '125': False, '126': False, '127': False, '128': False, '129': False, 'updated_at': 1667941093.3233285}`

```
{
  "result": {
    "category": "ckmkzq",
    "functions": [
      {
        "code": "switch_1",
        "desc": "{}",
        "name": "车库门开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_alarm",
        "desc": "{\"unit\":\"\",\"min\":-1,\"max\":2000,\"scale\":0,\"step\":1}",
        "name": "推送告警延时倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":-1,\"max\":2000,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "name": "车库门开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "doorcontact_state",
        "name": "门磁状态",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_alarm",
        "name": "推送告警延时倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":-1,\"max\":2000,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1667947492526,
  "tid": "f5685c9b5fb611ed8475060dd053b58c"
}
```

Opener: 1
Door contact open: 124
Door contact: 3
Time lenght for lock after closing: 102 (number from 1 to 5)
Auto close option: 107 (bolean)
Time lenght for auto-close: 115 (number from 1 to 1200)
Bip sound on opening: 103
* Silencioso (Mute)
* Baixo (Low)
* Médio (Medium)
* Alto (High)

**Comment by make-all** [comment]
This is a start, but I don't know if the unlocking will be as simple as setting dp 1 (it seems a bit insecure if it is).  If you see the link in the README.md that points to zigbee2mqtt documentation for tuya devices, it has a way to find out the names at least of other dps that are not listed by the api explorer method.  The names may be in Chinese but you should still be able to copy and paste them from the developer tools window.

**Comment by raphaeleduardo42** [comment]
I've retrieve all DP available by the Z2M method, they are:

128	Erro Backup128
1	Opener
129	Abertura por Chave
130 Function1back
3	Door contact
131	Function2back
132 Function3back
5	Quantidade de tags gravadas
101	Gravar Tag
102 Fechar após, trancar
103 Volume bip ao abrir & fechar
104 Abertura por botoeira
105	Abertura por interfone
106 Alarme porta aberta
107 Fechamento automático
108 Inter-travamento (gaiola)
109 Abertura por tag & chaveiro
110 Apagar tag & ultima tag adicionada
111 alarm
112 Notificação porta aberta
113 Notificação porta fechada
114 Back up (requer pen drive AGL)
115 Tempo para fechamento automático
116 Ligado na energia
117 Gate Contact
118 Deslize direita para abrir
119 Deslize esquerda para fechar
120 Notifica interfone
121 Notifica botoeira
122 Notifica celular
123 Controles Apagados
124 Door Contact Open
125 Disparo_Alarme_Porta
126 Backup Salvo
127 Backup Recuperado

After anallize the fuction behavior of the device with Node-Red, the messages sended on app command to open/close are in the 118/119.

Also, the device appeared in the tuya official integration, as a cover entity. But it can't be controlled there, the statuses seens to work.

**Comment by make-all** [comment]
118 and 119 are missing from the logged data.  I suspect they are "write only" registers, which are not currently supported well by this integration.  But for future possible support, are you able to capture the data type for those?  Probably they will be listed in the same debug interface if there have been recent commands using them.  Since they are intended for app use, they may also be cloud only, but it is probably worth trying local versions since we can get the corresponding code number.

It does look like for intercom and pushbutton use, the lock supports a request/reply type protocol where the door can be opened by a simple binary switch within some time of the request, so at least I think that method of opening can be supported.

**Comment by make-all** [comment]
Closing due to lack of feedback

**Comment by raphaeleduardo42** [comment]
Hello @make-all I had some adversities using this device by wifi control, and then I opt to hardwire a esphome attached to it. Real sorry for the late response.
Recently it got my attention again and I have a working behavior. I would like to share it.

The device has two sensors, one that shows if the door is open, and other that exposes the lock state of the motor.
Open and Close actions are controlled by two different DPs that reacts to a `true` value. I got it working using a button entity. 
Some other configurations are also working

After some trying I didn't managed to expose it as a Lock or Cover (Garage Door) directly, but it's working using an external template that it's shared bellow.

`name: AGL Ultra Magic Lock
products:
  - id: xrqkoapmq1rwjvms
    name: Ultra Magic
primary_entity:
  entity: button
  name: Open
  icon: mdi:lock-open-outline
  dps:
    - id: 118
      type: boolean
      name: button
secondary_entities:
  - entity: button
    name: Close
    icon: mdi:lock-outline
    dps:
      - id: 119
        type: boolean
        name: button


## Sensors
  - entity: binary_sensor
    name: Door Contact
    class: door
    dps:
      - id: 3
        type: boolean
        name: sensor

        mapping:
          - dps_val: true
            value: false
          - dps_val: false
            value: true
  - entity: binary_sensor
    name: Gate Contact
    class: lock
    dps:
      - id: 117
        type: string
        name: sensor

        mapping:
          - dps_val: "1"
            value: true
          - dps_val: "2"
            value: false

## Configuration Options ##
  - entity: select
    category: config
    name: Beep
    icon: "mdi:volume-high"
    dps:
      - id: 103
        name: option
        type: string

        mapping:
          - dps_val: Silensioso
            value: Mute
          - dps_val: Baixo
            value: Low
          - dps_val: Médio
            value: Medium
          - dps_val: Alto
            value: High
  - entity: switch
    category: config
    name: Allow Intercom Unlock
    icon: "mdi:doorbell"
    dps:
      - id: 105
        name: switch
        type: boolean

  - entity: switch
    category: config
    name: Allow Inside Button Unlock
    icon: "mdi:gesture-tap-button"
    dps:
      - id: 104
        name: switch
        type: boolean

  - entity: switch
    category: config
    name: Allow IC Card Unlock
    icon: "mdi:nfc-variant"
    dps:
      - id: 109
        name: switch
        type: boolean

  - entity: switch
    category: config
    name: Enable Interlock
    icon: "mdi:lock-pattern"
    dps:
      - id: 108
        name: switch
        type: boolean

  - entity: switch
    category: config
    name: Auto lock after closed
    icon: "mdi:lock-check-outline"
    dps:
      - id: 107
        name: switch
        type: boolean

  - entity: number
    category: config
    name: Lock timeout
    icon: "mdi:lock-clock"
    dps:
      - id: 102
        name: value
        type: integer

        range:
          min: 1
          max: 5
        unit: s
  - entity: number
    category: config
    icon: "mdi:clock-end"
    name: Auto Lock timeout
    dps:
      - id: 115
        name: value
        type: integer
        range:
          min: 1
          max: 1200
          unit: s
  - entity: number
    category: config
    icon: "mdi:alarm"
    name: Open Alarm time
    mode: box
    dps:
      - id: 106
        name: value
        type: integer
        range:
          min: 0
          max: 100
          unit: s`

`cover:
  - platform: template
    covers:
      portao:
        device_class: garage
        friendly_name: "Portão"
        unique_id: portao
        value_template: >
          {% if is_state('binary_sensor.agl_ultra_magic_lock_gate_contact', 'off') and is_state('binary_sensor.agl_ultra_magic_lock_door_contact', 'off') %}
          closed
          {% else %}
          open
          {% endif %}
        open_cover:
          service: button.press
          entity_id: button.agl_ultra_magic_lock_open
        close_cover:
          service: button.press
          entity_id: button.agl_ultra_magic_lock_close`
