### ISSUE TITLE
Vine tj550 thermostat cant see if fan is running

### ISSUE THREAD

**Issue by joshuamns** [make-all/tuya-local#2682]
### Description

the tuya local is unable to use the fan as an automation. it shows "heating" or "cooling" when it is working, but there is no entity to use from it. just if the whole thermostat is on or off.

### Steps to reproduce

set thermostat to higher than current temp

### Expected behaviour

entity should show "fan on" but instead it doesnt. (tuya app does let me)

### Confirmation

- [ ] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [X] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
It seems you need to review the Home Assistant documentation to see how to do whatever it is that you are trying to do within Home Assistant. Don't expect it to work exactly as the Tuya app does, that is not the goal of Home Assistant or this integration.

**Comment by joshuamns** [comment]
I just know the device has the ability to show if the fan is running or not, it would have just been nice to be able to turn on other fans when my furnace is running without using additional thermostats or tuya(online). I'll just have to find one of the thermostats you already have supported that does do that

Yahoo Mail: Search, Organize, Conquer 
 
  On Sun, Dec 22, 2024 at 8:43 PM, Jason ***@***.***> wrote:   


It seems you need to review the Home Assistant documentation to see how to do whatever it is that you are trying to do within Home Assistant. Don't expect it to work exactly as the Tuya app does, that is not the goal of Home Assistant or this integration.

**Comment by make-all** [comment]
You said *'it shows "heating" or "cooling" when it is working'*, if that is the information you need to trigger off, then why not use that?

**Comment by joshuamns** [comment]
It's physically shows it on tuya local (like on the display) but it does not give you any sort of entity or any actual state change to run anything off of. It just SHOWS it's working lol. That's why I was hoping it would be something super simple 😅. I can see the state changing, but it's not giving me an actual entity that changes if you follow what I mean

Yahoo Mail: Search, Organize, Conquer 
 
  On Sun, Dec 22, 2024 at 8:54 PM, Jason ***@***.***> wrote:   


You said 'it shows "heating" or "cooling" when it is working', if that is the information you need to trigger off, then why not use that?

**Comment by joshuamns** [comment]
![17349190598057116047062359371145](https://github.com/user-attachments/assets/e6005b81-1c68-426d-99ca-87fa83a60369)
It shows heating, but on the actual entity or log book, there isn't a state change on anything.

**Comment by joshuamns** [comment]
![17349191552144037372283984814636](https://github.com/user-attachments/assets/6b959f35-78d4-45aa-915c-ce2d51f57c8f)
"HVAC mode changed" is just if you set it to heat, or AC, or Off. But not what the furnace is actively doing.

**Comment by make-all** [comment]
You need to use the Entity triggers, not the Device triggers. Device triggers are just limited to the major ones as decided by Home Assistant, entity triggers give you access to all the attributes, including the hvac_action which you see in the UI.

**Comment by joshuamns** [comment]
Yup....I'm a moron 😅 sorry for bothering you.

Yahoo Mail: Search, Organize, Conquer 
 
  On Sun, Dec 22, 2024 at 10:04 PM, Jason ***@***.***> wrote:   


You need to use the Entity triggers, not the Device triggers. Device triggers are just limited to the major ones as decided by Home Assistant, entity triggers give you access to all the attributes, including the hvac_action which you see in the UI.
