### ISSUE TITLE
Error connecting the Nedis WIFISA10CWT air quality monitor 

### ISSUE THREAD

**Issue by PeterDemuynck** [make-all/tuya-local#2688]
### Description

I was able to integrate the device into the Tuya Smart app, closed the app.
Then with the latest version of HA.
Tuya Local - add device, but I get a final error. 

### Steps to reproduce

1. Add device through the Smart Tuya App.  Works Okay.
2. Ha: Devices and services
3. Add Device
4. Smart Life cloud-assisted device setup.
5. Enter code if asked
6. List is correctly generated: "choose the device to add"
7. Choose Gateway: none
8. Locate the device IP address (20 sec) - next
9. Configure local tuya  is presented, with all parameters filled in   (also the local IP address) 
10. Submit - then error:  "Unable to connect to your device with those details. - It could be an intermittend issue, or they may be incorrect".

So something made sure that it was not possible to integrated, even after several attempts. 
![Bug Smartlife](https://github.com/user-attachments/assets/23ab97b8-fd9e-4b00-8929-189eb971feec)

### Additional context

This error originated from a custom integration.

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:484
integration: Tuya Local (documentation, issues)
First occurred: 12:36:42 PM (17 occurrences)
Last logged: 2:04:41 PM

Test protocol error 904: Unexpected Payload from Device
Test protocol error 901: Network Error: Unable to Connect
Test protocol error 900: Invalid JSON Response from Device

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [ ] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [X] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
See discussion #522 for issues with initial connection
