### ISSUE TITLE
Failed to refresh device state for Test.

### ISSUE THREAD

**Issue by DroneSkull** [make-all/tuya-local#2689]
### Description

This error originated from a custom integration.

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:555
integration: Tuya Local (documentation, issues)
First occurred: 15:33:36 (1 occurrences)
Last logged: 15:33:36

Failed to refresh device state for Test.

### Steps to reproduce

When I try to add any device to Tuya Local:
I add the right details (Device ID, Local Key, IP address) And press submit. After that I get this error mess.

### Expected behaviour

I just want to add my Tuya device to Tuya Local.

### Additional context

This error originated from a custom integration.

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:555
integration: Tuya Local (documentation, issues)
First occurred: 15:33:36 (1 occurrences)
Last logged: 15:33:36

Failed to refresh device state for Test.

### Confirmation

- [ ] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [ ] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
There are many external factors that affect whether you can connect to a device or not, you cannot jump straight to assuming a bug without some evidence.

See discussion #522 for tips on solving connection issues.
