### ISSUE TITLE
Clamp meter "Energy" sensor problem

### ISSUE THREAD

**Issue by dolzhanskiyoa** [make-all/tuya-local#2691]
### Description

Device is recognized as pj1103_clamp_meter. On the box I see model CT-1103
1. Cannot use Energy entity in Energy dashboard (no needed attributes)
2. Energy entity is stuck on 0.1 kWh. Doesn't grow. Voltage, Current and Power entities are changing and show correct data
[tuya_local-01JFZDHWA4YGY58841Q3RB97K0-PJ-1103 clamp power meter-d8c9ffdef18736ca62d4491f77a4686c.json](https://github.com/user-attachments/files/18246898/tuya_local-01JFZDHWA4YGY58841Q3RB97K0-PJ-1103.clamp.power.meter-d8c9ffdef18736ca62d4491f77a4686c.json)

### Steps to reproduce

Entities in Devices pane. Nothing to reproduce

### Expected behaviour

1 - Can add Energy entity to Energy dashboard (device_class must be energy. state_class must be total or total_increasing.)
2 - Entity Energy grows while energy is used and shows the total use of enegry

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [X] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [X] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
The behaviour of the device you note in 2 is the reason for 1.

Use an integration helper on the power sensor to track energy usage.
