### ISSUE TITLE
Tuya app Closes when scanning QR code

### ISSUE THREAD

**Issue by awptechnologies** [make-all/tuya-local#2695]
### Description

No matter what i do after i put my user code in and scan qr code with tuya app. Tuya app on phone immediately crashes. Keep in mind i have already added 21 devices using the exact same procedure.

### Steps to reproduce

1. Go to tuya local.
2. Add device
3. input user code
4. scan qr code.

### Expected behaviour

I expect the tuya app to scan qr code and add devices i have synced to app.

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [ ] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
I am not responsible for the Tuya app.
