### ISSUE TITLE
Support for Poolex Silverline Heatpump

### ISSUE THREAD

**Issue by thomas-fr** [make-all/tuya-local#27]
Hi

Not really an issue (sorry, not familiar with Github, but it was the only way to share files) : I wanted to share a configuration file for supporting Poolex Silverline FI heatpumps.
Might work as well for other models from Poolex, which is a quite famous swimming-pool heatpumps manufacturer in France.

[Poolex_Silverline_FI_Heatpump.txt](https://github.com/make-all/tuya-local/files/6791863/Poolex_Silverline_FI_Heatpump.txt)

Thanks for this nice add-on and for your great work,
Thomas

**Comment by make-all** [comment]
This has been added in 0.8.6.
