### ISSUE TITLE
New device request "ME80 Thermostat"

### ISSUE THREAD

**Issue by griszamen** [make-all/tuya-local#270]
Hi, thank you for making such a useful repository! I integrated Rotenso air conditioner (by Tuya) as device 'starlight_heatpump'. Every feature is working fine. Thanks a lot!

But now i try to connect ME80 Tuya WiFi Smart 4.3" LCD Touch Color Screen Thermostat. It is detected only as 'simple switch'. Brand name is unknown.
https://www.banggood.com/ME80-Tuya-WiFi-Smart-4_3-inch-LCD-Touch-Color-Screen-Thermostat-Heating-Temperature-Controller-Works-with-Alexa-Google-Home-p-1894168.html

From Home Assistant logs i detected some datapoints:
'1': True, -  true-on, false-off
'2': 'auto', -  mode: auto/manual
'16': 21,  - target temperature
'19': 30,  - upper temperature limit
'23': 'c',  - temperature scale switch c/f
'24': 25, - current temperature temperatura
'26': 5,  - lower temperature limit
'27': 1,  - temperature calibration
'36': 'close',  - close- not heating, open-heating
'40': False, -  child lock (true - on, false - off)
'43': 'in', - sensor selection (in/out)
'45': 0,  - ???
'101': 0,  - ???
'103': False, -  true/false-antifreeze
'104': 'weekend', -  programming mode (options to chose: off, double break, single break, no day off - mode names taken from Tuya Smart Home app,  week days to program 5+2, 6+1, 7)
'106': 1,  - temperature difference start

There are datapoints i get from Tuya IOT platform:
1 switch
2 mode
16 target temperature
17 target temperature F
18 set temperature upper limit F
19 set temperature upper limit
20 set lower temperature limit F
23 temperature scale switch
24 current temperature
26 set lower temperature limit
27 temperature calibration
29 current temperature F
36 state of valve
101 floor temperature
102 floor temperature F
39 restore factory settings
103 antifreeze
40 child lock
104 programming mode
105 temperature calibration F
106 temperature difference start
107 temperature difference start F
43 sensor selection
108 reservation
45 fault alarm

Other info  from Tuya site:
Get the specifications and properties of the device:

> {
>   "result": {
>     "category": "wk",
>     "functions": [
>       {
>         "code": "switch",
>         "desc": "{}",
>         "name": "开关",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "mode",
>         "desc": "{\"range\":[\"auto\",\"manual\"]}",
>         "name": "工作模式",
>         "type": "Enum",
>         "values": "{\"range\":[\"auto\",\"manual\"]}"
>       },
>       {
>         "code": "temp_set",
>         "desc": "{\"unit\":\"℃\",\"min\":5,\"max\":99,\"scale\":0,\"step\":1}",
>         "name": "温度设置",
>         "type": "Integer",
>         "values": "{\"unit\":\"℃\",\"min\":5,\"max\":99,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "temp_set_f",
>         "desc": "{\"unit\":\"℉\",\"min\":32,\"max\":210,\"scale\":0,\"step\":1}",
>         "name": "目标温度_F",
>         "type": "Integer",
>         "values": "{\"unit\":\"℉\",\"min\":32,\"max\":210,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "upper_temp_f",
>         "desc": "{\"unit\":\"℉\",\"min\":86,\"max\":203,\"scale\":0,\"step\":1}",
>         "name": "设置温度上限_F",
>         "type": "Integer",
>         "values": "{\"unit\":\"℉\",\"min\":86,\"max\":203,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "upper_temp",
>         "desc": "{\"unit\":\"℃\",\"min\":30,\"max\":95,\"scale\":0,\"step\":1}",
>         "name": "设置温度上限",
>         "type": "Integer",
>         "values": "{\"unit\":\"℃\",\"min\":30,\"max\":95,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "lower_temp_f",
>         "desc": "{\"unit\":\"℉\",\"min\":41,\"max\":68,\"scale\":0,\"step\":1}",
>         "name": "设置温度下限_F",
>         "type": "Integer",
>         "values": "{\"unit\":\"℉\",\"min\":41,\"max\":68,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "temp_unit_convert",
>         "desc": "{\"range\":[\"c\",\"f\"]}",
>         "name": "温标切换设置",
>         "type": "Enum",
>         "values": "{\"range\":[\"c\",\"f\"]}"
>       },
>       {
>         "code": "lower_temp",
>         "desc": "{\"unit\":\"℃\",\"min\":5,\"max\":20,\"scale\":0,\"step\":1}",
>         "name": "设置温度下限",
>         "type": "Integer",
>         "values": "{\"unit\":\"℃\",\"min\":5,\"max\":20,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "temp_correction",
>         "desc": "{\"unit\":\"°C\",\"min\":-9,\"max\":9,\"scale\":0,\"step\":1}",
>         "name": "温度校准",
>         "type": "Integer",
>         "values": "{\"unit\":\"°C\",\"min\":-9,\"max\":9,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "factory_reset",
>         "desc": "{}",
>         "name": "恢复出厂设置",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "child_lock",
>         "desc": "{}",
>         "name": "童锁",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "sensor_choose",
>         "desc": "{\"range\":[\"in\",\"out\"]}",
>         "name": "传感器选择",
>         "type": "Enum",
>         "values": "{\"range\":[\"in\",\"out\"]}"
>       }
>     ],
>     "status": [
>       {
>         "code": "switch",
>         "name": "开关",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "mode",
>         "name": "工作模式",
>         "type": "Enum",
>         "values": "{\"range\":[\"auto\",\"manual\"]}"
>       },
>       {
>         "code": "temp_set",
>         "name": "温度设置",
>         "type": "Integer",
>         "values": "{\"unit\":\"℃\",\"min\":5,\"max\":99,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "temp_set_f",
>         "name": "目标温度_F",
>         "type": "Integer",
>         "values": "{\"unit\":\"℉\",\"min\":32,\"max\":210,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "upper_temp_f",
>         "name": "设置温度上限_F",
>         "type": "Integer",
>         "values": "{\"unit\":\"℉\",\"min\":86,\"max\":203,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "upper_temp",
>         "name": "设置温度上限",
>         "type": "Integer",
>         "values": "{\"unit\":\"℃\",\"min\":30,\"max\":95,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "lower_temp_f",
>         "name": "设置温度下限_F",
>         "type": "Integer",
>         "values": "{\"unit\":\"℉\",\"min\":41,\"max\":68,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "temp_unit_convert",
>         "name": "温标切换设置",
>         "type": "Enum",
>         "values": "{\"range\":[\"c\",\"f\"]}"
>       },
>       {
>         "code": "temp_current",
>         "name": "当前温度",
>         "type": "Integer",
>         "values": "{\"unit\":\"℃\",\"min\":0,\"max\":99,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "lower_temp",
>         "name": "设置温度下限",
>         "type": "Integer",
>         "values": "{\"unit\":\"℃\",\"min\":5,\"max\":20,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "temp_correction",
>         "name": "温度校准",
>         "type": "Integer",
>         "values": "{\"unit\":\"°C\",\"min\":-9,\"max\":9,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "temp_current_f",
>         "name": "当前温度_F",
>         "type": "Integer",
>         "values": "{\"unit\":\"℉\",\"min\":32,\"max\":210,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "valve_state",
>         "name": "阀门状态",
>         "type": "Enum",
>         "values": "{\"range\":[\"open\",\"close\"]}"
>       },
>       {
>         "code": "factory_reset",
>         "name": "恢复出厂设置",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "child_lock",
>         "name": "童锁",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "sensor_choose",
>         "name": "传感器选择",
>         "type": "Enum",
>         "values": "{\"range\":[\"in\",\"out\"]}"
>       },
>       {
>         "code": "fault",
>         "name": "故障告警",
>         "type": "Bitmap",
>         "values": "{\"label\":[\"e1\",\"e2\",\"e3\"]}"
>       }
>     ]
>   },
>   "success": true,
>   "t": 1668094962219,
>   "tid": "5033ac6c610e11ed803932ed7f2eb8a3"
> }

Get the instruction set of the device

> {
>   "result": {
>     "category": "wk",
>     "functions": [
>       {
>         "code": "switch",
>         "desc": "switch",
>         "name": "switch",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "mode",
>         "desc": "mode",
>         "name": "mode",
>         "type": "Enum",
>         "values": "{\"range\":[\"auto\",\"manual\"]}"
>       },
>       {
>         "code": "temp_set",
>         "desc": "temp set",
>         "name": "temp set",
>         "type": "Integer",
>         "values": "{\"unit\":\"℃\",\"min\":5,\"max\":99,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "temp_set_f",
>         "desc": "temp set f",
>         "name": "temp set f",
>         "type": "Integer",
>         "values": "{\"unit\":\"℉\",\"min\":32,\"max\":210,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "upper_temp_f",
>         "desc": "upper temp f",
>         "name": "upper temp f",
>         "type": "Integer",
>         "values": "{\"unit\":\"℉\",\"min\":86,\"max\":203,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "upper_temp",
>         "desc": "upper temp",
>         "name": "upper temp",
>         "type": "Integer",
>         "values": "{\"unit\":\"℃\",\"min\":30,\"max\":95,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "lower_temp_f",
>         "desc": "lower temp f",
>         "name": "lower temp f",
>         "type": "Integer",
>         "values": "{\"unit\":\"℉\",\"min\":41,\"max\":68,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "temp_unit_convert",
>         "desc": "temp unit convert",
>         "name": "temp unit convert",
>         "type": "Enum",
>         "values": "{\"range\":[\"c\",\"f\"]}"
>       },
>       {
>         "code": "lower_temp",
>         "desc": "lower temp",
>         "name": "lower temp",
>         "type": "Integer",
>         "values": "{\"unit\":\"℃\",\"min\":5,\"max\":20,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "temp_correction",
>         "desc": "temp correction",
>         "name": "temp correction",
>         "type": "Integer",
>         "values": "{\"unit\":\"°C\",\"min\":-9,\"max\":9,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "factory_reset",
>         "desc": "factory reset",
>         "name": "factory reset",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "child_lock",
>         "desc": "child lock",
>         "name": "child lock",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "sensor_choose",
>         "desc": "sensor choose",
>         "name": "sensor choose",
>         "type": "Enum",
>         "values": "{\"range\":[\"in\",\"out\"]}"
>       }
>     ]
>   },
>   "success": true,
>   "t": 1668095155535,
>   "tid": "c374a4c6610e11ed803932ed7f2eb8a3"
> }

Get Device Specification

> {
>   "result": {
>     "category": "wk",
>     "functions": [
>       {
>         "code": "switch",
>         "lang_config": {
>           "false": "Off",
>           "true": "on"
>         },
>         "name": "Switch",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "mode",
>         "lang_config": {
>           "auto": "Auto",
>           "manual": "Manual"
>         },
>         "name": "Mode",
>         "type": "Enum",
>         "values": "{\"range\":[\"auto\",\"manual\"]}"
>       },
>       {
>         "code": "temp_set",
>         "lang_config": {
>           "unit": "°C"
>         },
>         "name": "Target temperature",
>         "type": "Integer",
>         "values": "{\"unit\":\"℃\",\"min\":5,\"max\":99,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "temp_set_f",
>         "lang_config": {
>           "unit": "°F"
>         },
>         "name": "Target temperature_F",
>         "type": "Integer",
>         "values": "{\"unit\":\"℉\",\"min\":32,\"max\":210,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "upper_temp_f",
>         "lang_config": {
>           "unit": "℉"
>         },
>         "name": "Set temperature upper limit_F",
>         "type": "Integer",
>         "values": "{\"unit\":\"℉\",\"min\":86,\"max\":203,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "upper_temp",
>         "lang_config": {
>           "unit": "℃"
>         },
>         "name": "Set the upper temperature limit",
>         "type": "Integer",
>         "values": "{\"unit\":\"℃\",\"min\":30,\"max\":95,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "lower_temp_f",
>         "lang_config": {
>           "unit": "℉"
>         },
>         "name": "Set lower temperature limit -℉",
>         "type": "Integer",
>         "values": "{\"unit\":\"℉\",\"min\":41,\"max\":68,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "temp_unit_convert",
>         "lang_config": {
>           "c": "℃",
>           "f": "℉"
>         },
>         "name": "Temperature scale switch",
>         "type": "Enum",
>         "values": "{\"range\":[\"c\",\"f\"]}"
>       },
>       {
>         "code": "lower_temp",
>         "lang_config": {
>           "unit": "°C"
>         },
>         "name": "Set lower temperature limit",
>         "type": "Integer",
>         "values": "{\"unit\":\"℃\",\"min\":5,\"max\":20,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "temp_correction",
>         "lang_config": {
>           "unit": "°C"
>         },
>         "name": "Temperature calibration",
>         "type": "Integer",
>         "values": "{\"unit\":\"°C\",\"min\":-9,\"max\":9,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "factory_reset",
>         "lang_config": {
>           "false": "cancel",
>           "true": "ok"
>         },
>         "name": "Restore factory settings",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "child_lock",
>         "lang_config": {
>           "false": "OFF",
>           "true": "ON"
>         },
>         "name": "child lock",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "sensor_choose",
>         "lang_config": {
>           "in": "built-in",
>           "out": "External"
>         },
>         "name": "Sensor selection",
>         "type": "Enum",
>         "values": "{\"range\":[\"in\",\"out\"]}"
>       }
>     ],
>     "status": [
>       {
>         "code": "switch",
>         "lang_config": {
>           "false": "Off",
>           "true": "on"
>         },
>         "name": "Switch",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "mode",
>         "lang_config": {
>           "auto": "Auto",
>           "manual": "Manual"
>         },
>         "name": "Mode",
>         "type": "Enum",
>         "values": "{\"range\":[\"auto\",\"manual\"]}"
>       },
>       {
>         "code": "temp_set",
>         "lang_config": {
>           "unit": "°C"
>         },
>         "name": "Target temperature",
>         "type": "Integer",
>         "values": "{\"unit\":\"℃\",\"min\":5,\"max\":99,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "temp_set_f",
>         "lang_config": {
>           "unit": "°F"
>         },
>         "name": "Target temperature_F",
>         "type": "Integer",
>         "values": "{\"unit\":\"℉\",\"min\":32,\"max\":210,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "upper_temp_f",
>         "lang_config": {
>           "unit": "℉"
>         },
>         "name": "Set temperature upper limit_F",
>         "type": "Integer",
>         "values": "{\"unit\":\"℉\",\"min\":86,\"max\":203,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "upper_temp",
>         "lang_config": {
>           "unit": "℃"
>         },
>         "name": "Set the upper temperature limit",
>         "type": "Integer",
>         "values": "{\"unit\":\"℃\",\"min\":30,\"max\":95,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "lower_temp_f",
>         "lang_config": {
>           "unit": "℉"
>         },
>         "name": "Set lower temperature limit -℉",
>         "type": "Integer",
>         "values": "{\"unit\":\"℉\",\"min\":41,\"max\":68,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "temp_unit_convert",
>         "lang_config": {
>           "c": "℃",
>           "f": "℉"
>         },
>         "name": "Temperature scale switch",
>         "type": "Enum",
>         "values": "{\"range\":[\"c\",\"f\"]}"
>       },
>       {
>         "code": "temp_current",
>         "lang_config": {
>           "unit": "°C"
>         },
>         "name": "Current temperature",
>         "type": "Integer",
>         "values": "{\"unit\":\"℃\",\"min\":0,\"max\":99,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "lower_temp",
>         "lang_config": {
>           "unit": "°C"
>         },
>         "name": "Set lower temperature limit",
>         "type": "Integer",
>         "values": "{\"unit\":\"℃\",\"min\":5,\"max\":20,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "temp_correction",
>         "lang_config": {
>           "unit": "°C"
>         },
>         "name": "Temperature calibration",
>         "type": "Integer",
>         "values": "{\"unit\":\"°C\",\"min\":-9,\"max\":9,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "temp_current_f",
>         "lang_config": {
>           "unit": "°F"
>         },
>         "name": "Current temperature -℉",
>         "type": "Integer",
>         "values": "{\"unit\":\"℉\",\"min\":32,\"max\":210,\"scale\":0,\"step\":1}"
>       },
>       {
>         "code": "valve_state",
>         "lang_config": {
>           "close": "Close",
>           "open": "Open"
>         },
>         "name": "State of the valve",
>         "type": "Enum",
>         "values": "{\"range\":[\"open\",\"close\"]}"
>       },
>       {
>         "code": "factory_reset",
>         "lang_config": {
>           "false": "cancel",
>           "true": "ok"
>         },
>         "name": "Restore factory settings",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "child_lock",
>         "lang_config": {
>           "false": "OFF",
>           "true": "ON"
>         },
>         "name": "child lock",
>         "type": "Boolean",
>         "values": "{}"
>       },
>       {
>         "code": "sensor_choose",
>         "lang_config": {
>           "in": "built-in",
>           "out": "External"
>         },
>         "name": "Sensor selection",
>         "type": "Enum",
>         "values": "{\"range\":[\"in\",\"out\"]}"
>       },
>       {
>         "code": "fault",
>         "lang_config": {
>           "e1": "E1",
>           "e2": "E2",
>           "e3": "E3"
>         },
>         "name": "Fault alarm",
>         "type": "Bitmap",
>         "values": "{\"label\":[\"e1\",\"e2\",\"e3\"]}"
>       }
>     ]
>   },
>   "success": true,
>   "t": 1668095371854,
>   "tid": "445c2cc9610f11ed8c4b06bdf2add754"
> }

**Comment by griszamen** [comment]
Thanks a lot for integration!
I'm testing features, everything is working fine by now.

Some ranges of presets are different in Tuya app:
upper temperature limit: 30-95 (in app) versus 30-100 in integration;
lower teperature limit: should be 5-20 / is 0-100
temperature calibration -9+9  /0-100
temperature difference start: 1-5 /0-100
And there is in app third sensor preset: 'both' - not working in my case, i have ME80 model without external sensor connector, chosing this option cause 'error'.

**Comment by griszamen** [comment]
Hi there, i tested new settings and all features seems to be fine. Ranges are correct now.
But i have a question, look at this: 
there are my thermostat's entity in 'developer tools':
![image](https://user-images.githubusercontent.com/76266184/204606605-3741eb93-019b-4b19-84fe-5cd607fb53da.png)
an there are thermostat's popup window:
![image](https://user-images.githubusercontent.com/76266184/204608319-2ce5d182-4f34-4c92-8629-157eaefb97a9.png)

Hvac_mode 'heat' causes the same effect as preset_mode 'manual', auto is the same option in both modes, so it looks like  duplicated options in my opinion. Is the reason to exist two similar presets?

**Comment by make-all** [comment]
Purely because the preset_mode already existed in the previous version of the config, so when I linked it to hvac_mode in the last change I did not remove it, even though the hvac_mode fully covers the possibile presets.
