### ISSUE TITLE
Config flow could not be loaded: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by ProgInj** [make-all/tuya-local#2706]
### Description

After installing the integration and when trying to configure it, an error occurs.

Log from the journal:
2024-12-29 19:59:57.875 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration tuya_local: No module named 'tinytuya'

### Steps to reproduce

The system is set to HAOS.
The methods found to solve the problem are only through docker, but I don't have access to it because of this system.
Should I try to reinstall the system or is there some other way?

## System Information

version | core-2024.12.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.66-haos
arch | x86_64
timezone | Europe/Moscow
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4968
Installed Version | 2.0.1
Stage | running
Available Repositories | 1493
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.12.0
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 228.5 GB
disk_used | 5.6 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.1), Terminal & SSH (9.16.0), Zigbee2MQTT (1.42.0-2), Studio Code Server (5.17.3), Home Assistant Google Drive Backup (0.112.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 1
views | 0
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 22 декабря 2024 г. в 12:27
-- | --
current_recorder_run | 29 декабря 2024 г. в 19:59
estimated_db_size | 6.69 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [ ] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [X] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment]
Why are you reporting this as a bug in the integration?

The dependencies are declared in the manifest, it is a problem of whatever installation method you used or Home Assistant itself if the dependencies do not get installed.
