### ISSUE TITLE
Add hvac action attribute to automation trigger selector

### ISSUE THREAD

**Issue by kramttocs** [make-all/tuya-local#271]
For device ITC-308
The Dev tool page in HA shows the HVAC action attribute with the correct value (heating) but this attribute isn't available in the drop down to trigger an automation from it.

1. Go to automations
2. Select the climate entity
3. Expand the Attribute drop down.
4. Notice HVAC action isn't there

Thank you

**Comment by make-all** [comment]
This integration only provides the info in the format that Home Assistant expects it.  Issues in the automation UI are Home Assistant issues, not integration specific.

**Comment by kramttocs** [comment]
Thanks for the quick reply. My ecobee climate entity shows the HVAC action so is it possible there is some flag missing in the attribute definition for the integration? Will add screenshots shortly.

**Comment by kramttocs** [comment]
Ah, wait. I don't have this described correctly. Turns out one of my ITC-308 has that attribute and it DOES show in the trigger selection. My other ITC-308 doesn't (in Dev tools) and it therefore doesn't show in the trigger selection.

Initially I was looking at one in Dev tools and the other in Automations. Sorry.

So the new question is why dies one have it but the other not?
Worth noting that the one that does have it is heating and the one that doesn't is cooling right now?

**Comment by make-all** [comment]
Is there anything in the log?  Maybe it is returning an unrecognized value from the dp linked to hvac_action?
The config is set to translate '1' -> cooling, '2' -> idle, '3' -> heating, but it is possible that it also uses others (or that the mapping is incorrect).

**Comment by kramttocs** [comment]
Well, looks like it can be closed. I didn't check the log before touching the temp unfortunately. Now the attribute shows up for both heating and cooling. Will keep an eye on it though.
Again, thanks for the quick replies.

**Comment by kramttocs** [comment]
This error originated from a custom integration.

Logger: custom_components.tuya_local.generic.climate
Source: custom_components/tuya_local/generic/climate.py:261
Integration: Tuya Local (documentation, issues)
First occurred: 11:22:25 PM (10 occurrences)
Last logged: 11:31:25 PM

_Unrecognised HVAC Action 0 ignored

**Comment by kramttocs** [comment]
I think idle isn't mapped correctly (the state it should be in now). On my phone now but if more data is needed, can do some testing tomorrow on my desktop.

**Comment by make-all** [comment]
It could be that "0" is an additional state that means "off".  I assume the original reporter got those values from somewhere and they should be correct (but maybe incomplete).

Is it idle because of schedule now, or because of temperature?  I think "idle" in HA terms means because of temperature - so the heating/cooling is on, but because the temperature is within the desired range, it is not actively heating or cooling.  If idle because of schedule, maybe "off" is better.  Maybe you can check the other values for heating and cooling match what is in the config.

**Comment by kramttocs** [comment]
Thanks.
It's idle now because of temp. It's within the desired range.
This is just a theory but I wonder if the behavior changes if it goes from heating to idle vs from cooling to idle.
Maybe the idle is a different value depending upon which mode it 'came from'.

I can't recall how to get the DPs in the log (been too long). Do I need to set debug logging in the yaml file?

**Comment by kramttocs** [comment]
Nevermind :)
Found it in another issue report:

logger:
  default: warning
  logs;
    custom_components.tuya_local.device: debug

**Comment by make-all** [comment]
OK, the change I made yesterday would appear to be correct then.
