### ISSUE TITLE
Support bluetooth devices through a hub/bridge

### ISSUE THREAD

**Issue by felipecrs** [make-all/tuya-local#275]
I have some bluetooth bulbs which works through a bluetooth hub. The tuya-cli seems to recognize them:

```console
❯ tuya-cli wizard
[
  {
    name: 'Hub Bluetooth e ZigBee',
    id: 'eb41b8f336925ed5eczxwg',
    key: '<hidden>',
    subDevices: [
      {
        name: 'Luz do corredorzinho',
        id: 'eb4ea98uq24mj6d7',
        cid: 'dc234dc5aea1'
      }
    ]
  }
]
```

Adding the hub itself to Tuya Local doesn't work:

![image](https://user-images.githubusercontent.com/29582865/202258259-d0880fe4-f72a-42c5-be67-af543396aaed.png)

And using any combination of id/sub-id/cid/key does not seem to work either.

**Comment by felipecrs** [comment]
Adding the hub itself to Tuya Local:

![image](https://user-images.githubusercontent.com/29582865/202258259-d0880fe4-f72a-42c5-be67-af543396aaed.png)

**Comment by make-all** [comment]
This will not be possible until the upstream library adds subdevice support, which it currently lacks.

**Comment by make-all** [comment]
It looks like the support has been added to tinytuya (after the 1.8.0 release was cut, so not yet released), so it will become possible to work on this issue soon.

**Comment by tony-robson** [comment]
Interested in this functionality too, looks like v1.9.0 of tinytuya has been released now with support for gateways also. Happy to participate in any testing, I'm currently using a Bluetooth gateway with some lights and sensors.

**Comment by felipecrs** [comment]
@tony-robson out of curiosity, are your lights RGB?

**Comment by make-all** [comment]
Progress on the underlying sub-device support is being tracked on issue #70.

**Comment by tony-robson** [comment]
> @tony-robson out of curiosity, are your lights RGB?

I have both kinds, mostly RGB but also some Warm White too.

@make-all Thanks, I'll keep an eye on that issue then.

**Comment by felipecrs** [comment]
> mostly RGB

When I use the official Tuya HA integration, it doesn't allow me to change colors. Only the white temperature. Have you observed the same as well? My hope is that the same issue won't occur with Tuya Local.

**Comment by tony-robson** [comment]
> > mostly RGB
> 
> When I use the official Tuya HA integration, it doesn't allow me to change colors. Only the white temperature. Have you observed the same as well? My hope is that the same issue won't occur with Tuya Local.

I haven't tested extensively with the Official Tuya Integration, instead I've been using a [fork of localtuya](https://github.com/leeyuentuen/localtuya) that has *limited* Gateway Support. The problem I have had using that integration though could be similar to yours, I found unless I manually initialized the DP values of the sub devices (read: RGB Lights) using tinytuya/tuya-cli each time the Gateway was restarted then those functions wouldn't work In the integration. 

I suspect this could be due to the Gateway clearing the values for all sub devices each time it is reset, so when the integration was polling a DP it was getting an undefined return causing issues with the integrations logic. More info in an issue i submitted [here](https://github.com/leeyuentuen/localtuya/issues/23).

Hope that helps some.

**Comment by felipecrs** [comment]
Awesome. Thank you!

**Comment by felipecrs** [comment]
I'm attempting to connect this device but I'm running into https://github.com/make-all/tuya-local/discussions/1425.

I'm just pinging this issue wondering if anyone involved here that had such device was able to make it work.

**Comment by pergolafabio** [comment]
hey @felipecrs , seems i also purchased a cat feeder, unaware it was bluetooth
so i have an BT gateway now in order too ..

is this now working correctly ?

**Comment by felipecrs** [comment]
Nah, all my BLE bulbs burned out already.

Do yourself a favor and ditch your Tuya BT gateway, use this instead: https://github.com/ha-tuya-ble/ha_tuya_ble.

Otherwise, if Tuya Local doesn't have the feature you need, you should raise it. Else, try this [localtuya fork](https://github.com/xZetsubou/hass-localtuya).

**Comment by pergolafabio** [comment]
ok, will have a look at that integration, but i still need a bluetooth device / hub / gateway to talk to my petfeeder ?

**Comment by felipecrs** [comment]
https://github.com/ha-tuya-ble/ha_tuya_ble is for connecting it directly to Home Assistant through the BT radio of your Home Assistant server.

If you need to extend the range, then you can use an [ESPHome Bluetooth Proxy](https://esphome.io/components/bluetooth_proxy/), which works transparently. It's awesome.

**Comment by pergolafabio** [comment]
ah, but i'm running HA on my synology as a virtual , so dont have BT hardware on my HA instance
so i need to hub anyway

**Comment by felipecrs** [comment]
Got it.

BTW if you have some ESP32 lingering around you can easily flash ESPHome BT Proxy on it.

To use with your Tuya BT Gateway, try Tuya Local. If it doesn't work out of the box, it's likely that your device is not supported yet. You can then raise it as a feature request.

**Comment by pergolafabio** [comment]
Yeah, already created some PR's before to add new devices, I'm aware, a good maintainer here!!

Gonna wait now for my 5€ hub I ordered on Ali

**Comment by felipecrs** [comment]
Well, it's hard to argue over 5€. But I'd have bought an ESP32-S3 with that money instead. It's far more useful.

https://aliexpress.com/item/1005005051294262.html

**Comment by make-all** [comment]
The Bluetooth hub should work OK with a single device connected. I have one and it works fine with one or two devices, but becomes unstable with more. There is a Moes branded hub that others have reported works with larger numbers of devices. I'm not sure if ha-tuya-ble will support your pet feeder, but for devices it does support, it is definitely a better option, as it gets the devices out of the Tuya ecosystem (same as using Zigbee device with ZHA or Z2MQTT instead of a Tuya hub),

**Comment by pergolafabio** [comment]
Ok. Let me first try the official hub, will be delivered next week, I will only connect max 2 feeders to it, for me it's only important to open the flaps ,  but it must be at the same time, let's hope I can send the command and the hun can handle 2 BLE connections...
My end goal is to open the 2 feeders, so I can drop food in those from.another wifi feeder that I already have ;-)

**Comment by make-all** [comment]
You'll have trouble getting them exactly synchronised through a single Bluetooth hub, see #1323, which has some videos showing light behaviours (the latest one at the bottom is indicative of the current state). You might be able to create a scene in Tuya to trigger through the cloud integration that synchronizes better if the performance through this integration is not acceptable.
The user on #1323 has a lot of lights, so you may not notice much delay with only 2 devices, but I just want to manage your expectations here.

**Comment by pergolafabio** [comment]
Ok. Thnx for feedback, let's wait untill it arrives, maybe I can use the scene indeed

**Comment by pergolafabio** [comment]
I was looking st scenes...
Do I need to create a "tap to run " scene. Is that scene then exposed to your integration somehow??

Or do I need to create a state change scene: like, when state on device A changes then do something on device B

**Comment by felipecrs** [comment]
I think you should use the official Tuya integration for scenes.

**Comment by pergolafabio** [comment]
Ok. Will do some testing when hubs arrive. Also ordered  that "moes" version now
