### ISSUE TITLE
New Device request - Aubess Smart Switch/EM

### ISSUE THREAD

**Issue by filipole** [make-all/tuya-local#277]
Hello
can you possibly add support for the following Smart Switch:
Aubess Smart Switch/EM (https://www.aliexpress.com/item/1005004685338010.html)
It is detected as simple or simple timer switch without power monitoring
Device_id for the reference:
bf1ebdc2dc0ac0d76dhfev

Sorry, can't see how I can list all the dp_ids, but the ones which I am looking for are:

cur_current: 21
cur_power: 22
cur_voltage: 23

{
  "result": {
    "category": "tdq",
    "functions": [
      {
        "code": "switch_1",
        "desc": "{}",
        "name": "开关1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "name": "开关1倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "desc": "{\"range\":[\"0\",\"1\",\"2\"]}",
        "name": "上电状态设置",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\"]}"
      },
      {
        "code": "random_time",
        "desc": "{\"maxlen\":255}",
        "name": "随机定时",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "cycle_time",
        "desc": "{\"maxlen\":255}",
        "name": "循环定时",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "switch_inching",
        "desc": "{\"maxlen\":255}",
        "name": "点动开关",
        "type": "String",
        "values": "{\"maxlen\":255}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "name": "开关1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "name": "开关1倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "add_ele",
        "name": "增加电量",
        "type": "Integer",
        "values": "{\"unit\":\"kW·h\",\"min\":0,\"max\":50000,\"scale\":3,\"step\":100}"
      },
      {
        "code": "cur_current",
        "name": "当前电流",
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_power",
        "name": "当前功率",
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":0,\"max\":50000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "cur_voltage",
        "name": "当前电压",
        "type": "Integer",
        "values": "{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "test_bit",
        "name": "产测结果位",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":5,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "name": "上电状态设置",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\"]}"
      },
      {
        "code": "random_time",
        "name": "随机定时",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "cycle_time",
        "name": "循环定时",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "switch_inching",
        "name": "点动开关",
        "type": "String",
        "values": "{\"maxlen\":255}"
      }
    ]
  },
  "success": true,
  "t": 1668701525219,
  "tid": "93f4db55669211ed81ea8ec426404b74"
}

Thank you and let me know if any other information is needed

**Comment by make-all** [comment]
The data you have provided seems to come from the API Explorer on iot.tuya.com.  There is one specific API call which does return dp_id attributes along with the descriptions of each function and status datapoint.  There are instructions in the README.md for locating the correct API call, and also a link to another method of linking dp ids with named attributes.

**Comment by filipole** [comment]
{
  "result": {
    "category": "tdq",
    "functions": [
      {
        "code": "switch_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "dp_id": 38,
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\"]}"
      },
      {
        "code": "random_time",
        "dp_id": 42,
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "cycle_time",
        "dp_id": 43,
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "switch_inching",
        "dp_id": 44,
        "type": "String",
        "values": "{\"maxlen\":255}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "add_ele",
        "dp_id": 20,
        "type": "Integer",
        "values": "{\"unit\":\"kW·h\",\"min\":0,\"max\":50000,\"scale\":3,\"step\":100}"
      },
      {
        "code": "cur_current",
        "dp_id": 21,
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_power",
        "dp_id": 22,
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":0,\"max\":50000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "cur_voltage",
        "dp_id": 23,
        "type": "Integer",
        "values": "{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "test_bit",
        "dp_id": 24,
        "type": "Integer",
        "values": "{\"min\":0,\"max\":5,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "dp_id": 38,
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\"]}"
      },
      {
        "code": "random_time",
        "dp_id": 42,
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "cycle_time",
        "dp_id": 43,
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "switch_inching",
        "dp_id": 44,
        "type": "String",
        "values": "{\"maxlen\":255}"
      }
    ]
  },
  "success": true,
  "t": 1669048117482,
  "tid": "8d0701fc69b911ed806f32ed7f2eb8a3"
}

**Comment by Edkiygluk** [comment]
Hello)
Sorry, my english is bad)))))
Speed of reaction Aubess Smart Switch/EM is very slow =(
Cloud integration is faster than local integration.

**Comment by make-all** [comment]
If you are talking about the time taken to reflect changes made from outside Home Assistant, then cloud will always be faster than local, since the device immediately reports state changes to the cloud, while for local we need to poll it at a rate that does not overload the firmware on the device.  Changes made from Home Assistant should be quick, except if you make multiple changes in quick succession, they will be rate limited, again to avoid overloading the device and crashing it.

**Comment by Edkiygluk** [comment]
Thank you)
I meant exactly this.

**Comment by make-all** [comment]
There is another issue open for the speed, #176 so I will close this one as complete.
