### ISSUE TITLE
All included devices "DEVICES.md" should be selectable when including a new device.

### ISSUE THREAD

**Issue by Tommy032017** [make-all/tuya-local#278]
As described in the manual: Stage Two
_

> The second stage of configuration is to select which device you are connecting. The list of devices offered will be limited to devices which appear to be at least a partial match to the data returned by the device.
> type
>     (string) (Optional) The type of Tuya device. Select from the available options.
> If you pick the wrong type, you will need to delete the device and set it up again.

_
" 
**There should be also an option to list and select any of the programmed devices.**

![Bildschirmfoto vom 2022-11-17 20-25-03](https://user-images.githubusercontent.com/26543724/202541460-ccd63aa8-b257-433c-bb5d-fd341d9bd0a6.png)

This could help to include a similar or cloned device, which will not be selectable by proposed and matching devices.

**Comment by make-all** [comment]
No, that won't help to allow you to select an incompatible device.

**Comment by Tommy032017** [comment]
Thank you, I will submit all information about a new device, which maybe could be added by you.
Thanks for your great project!
