### ISSUE TITLE
New device request: RYRA Temperature electric quantity controller (Switch)

### ISSUE THREAD

**Issue by catdogmaus** [make-all/tuya-local#281]
Would be great, if you could add this device. Thank you in advance.

Brand name, model:
RYRA Temperature electric quantity controller
TYTE-D1

Image search gives several different brands and models for the same device
Let me know when I can add some useful information

[new device HA log DP .txt](https://github.com/make-all/tuya-local/files/10047895/new.device.HA.log.DP.txt)
[Tinituya inf dumps.txt](https://github.com/make-all/tuya-local/files/10047896/Tinituya.inf.dumps.txt)
![907361209-590293804](https://user-images.githubusercontent.com/116189627/202870581-a8a23640-2ef6-43fe-9f10-336260359e7d.jpg)

**Comment by make-all** [comment]
If you can log into iot.tuya.com, and use the APIExplorer to collect information on the DPS, it will show also ranges for some of those values, as well as indicate whether they are read-only or settable.

**Comment by catdogmaus** [comment]
Could you please clarify, by DP information you mean the use of Chrome developer tools DP extraction method or simply some IoT own standard data set. I have really just basic knowledge about T IoT platform.
Meanwhile I add some screens from app. That will also give probably some additional information.

![Screenshot_20221120-005531_Smart_Life](https://user-images.githubusercontent.com/116189627/202915276-5a6b2933-3e41-4b8d-bad1-82e9d952af65.png)
![Screenshot_20221120-005546_Smart_Life](https://user-images.githubusercontent.com/116189627/202915278-f98e6b35-56a1-4e43-9f51-123e6ed25dc6.png)
![Screenshot_20221120-005629_Smart_Life](https://user-images.githubusercontent.com/116189627/202915281-185cdfff-e339-4985-99f4-81fc5250bdb5.png)
![Screenshot_20221120-005714_Smart_Life](https://user-images.githubusercontent.com/116189627/202915284-df957c42-4eac-49ae-bb55-ae7c857f1221.png)
![Screenshot_20221120-005734_Smart_Life](https://user-images.githubusercontent.com/116189627/202915286-f52e5518-7985-44d1-869e-b2ccae0cd94c.png)
![Screenshot_20221120-005749_Smart_Life](https://user-images.githubusercontent.com/116189627/202915287-9c90f751-12a8-4598-87cf-8968b6e901cb.png)
![Screenshot_20221120-010000_Smart_Life](https://user-images.githubusercontent.com/116189627/202915288-78964e3b-1449-4154-82e8-3fa8c3cdf548.png)

**Comment by make-all** [comment]
Cloud / API Explorer on iot.tuya.com gives the most detailed info, but does not always list all dps.
So best is to look under "Smart Home Device System" / "Device Control" the last "Get Device Specification Attribute" function, check the Data Center at the top, and enter your device id (it must be a device linked to your account, or you will get nothing back), then copy the response in here.  Check which dp_id are listed against the HA log info above, and if any are missing, you can go looking in the Device Debugger for additional attributes and identify their code using the web debug window.

**Comment by make-all** [comment]
The API Explorer info should return data like this, giving the dp_id and range of values, which are missing from your tinytuya info (which must be using a different API call to get its info).

```
      {
        "code": "countdown_1",
        "dp_id": 11,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
```

**Comment by catdogmaus** [comment]
I think here should be all dp information as Tuya shows them
[T IoT Debugging Result.txt](https://github.com/make-all/tuya-local/files/10071571/T.IoT.Debugging.Result.txt)
