### ISSUE TITLE
New device request: Light Motion Sensors request(DET100HA / DET102HA)

### ISSUE THREAD

**Issue by isarib01** [make-all/tuya-local#282]
Hi,

I seem to have a fair bit of light sensors which are not yet supported, there are two different models and wondering if anyone has some fixes to the below.  Many thanks.

***************************************************************
Sensor Model 1 - Deta 360 Motion Sensor, Grid Connect(DET102HA).
{
  "result": {
    "active_time": 1666953679,
    "category": "pir",
    "category_name": "Motion Detector",
    "create_time": 1664431066,
    "gateway_id": "",
    "icon": "smart/icon/ay1536534747810ekKBj/33e050831a2f667fcae9bff8aa5ec73b.png",
    "id": "67506371e868e784b0d7",
    "ip": "1234567890",
    "lat": "1234567890",
    "local_key": "1234567890",
    "lon": "115.9807",
    "model": "Starlux DET102HA",
    "name": "Garage Light",
    "online": true,
    "owner_id": "65067975",
    "product_id": "oapo5mmfbcr2y7ox",
    "product_name": "DET102HA",
    "sub": false,
    "time_zone": "+08:00",
    "update_time": 1666953686,
    "uuid": "1234567890"
  },
  "success": true,
  "t": 1669133304844,
  "tid": "e4a17bd36a7f11edadcaa64798946735"
}

{
  "result": {
    "category": "pir",
    "functions": [],
    "status": [
      {
        "code": "pir",
        "lang_config": {
          "none": "",
          "pir": ""
        },
        "name": "人体感应状态",
        "type": "Enum",
        "values": "{\"range\":[\"pir\",\"none\"]}"
      }
    ]
  },
  "success": true,
  "t": 1669134803744,
  "tid": "620c535f6a8311edadcaa64798946735"
}

***************************************************************
Sensor Model 2 - Deta Light Motion Sensor, Grid Connect(DET100HA).

{
  "result": {
    "active_time": 1666953283,
    "category": "pir",
    "category_name": "Motion Detector",
    "create_time": 1659200434,
    "gateway_id": "",
    "icon": "smart/icon/ay1558866774161DZ6MV/1566282712ae29041f3ee.png",
    "id": "58607270e868e782f909",
    "ip": "58.167.237.241",
    "lat": "1234567890",
    "local_key": "1234567890",
    "lon": "1234567890",
    "model": "Starlux DET100HA",
    "name": "Driveway Light Sensor",
    "online": true,
    "owner_id": "65067975",
    "product_id": "8mrw54ape8opgl69",
    "product_name": "DET100HA",
    "sub": false,
    "time_zone": "+08:00",
    "update_time": 1666953289,
    "uuid": "1234567890"
  },
  "success": true,
  "t": 1669133402629,
  "tid": "1ef042506a8011edadcaa64798946735"
}

{
  "result": {
    "category": "pir",
    "functions": [],
    "status": []
  },
  "success": true,
  "t": 1669134902067,
  "tid": "9c9746eb6a8311edadcaa64798946735"
}

***************************************************************

**Comment by make-all** [comment]
How are these powered?  If they are battery powered they are unlikely to work locally, as they will be in deep sleep most of the time.

**Comment by isarib01** [comment]
Hi,

Thanks for the reply.

These are both live powered, and not battery.  They are hardwired into my light circuits.  Presently connected to Tuya/Tuya IoT, but would like them to be local.

https://www.bunnings.com.au/deta-grid-connect-smart-compact-pir-sensor_p0129567
https://www.bunnings.com.au/deta-grid-connect-smart-360-degree-pir-sensor_p0129568

**Comment by make-all** [comment]
OK, can you capture the local data for these two also?  You should see something in the log of Home Assistant if you start the process of adding them with this integration.  You can cancel out of adding them once the list of options for device type come up (or no matching device is reported).  If it is not clear which is the sensor, I may need to you collect more info for the first device from the tuya portal, for the second, it does not look like the portal has any info so maybe need to do some experimenting, or use the debugger method.

**Comment by isarib01** [comment]
> OK, can you capture the local data for these two also? You should see something in the log of Home Assistant if you start the process of adding them with this integration. You can cancel out of adding them once the list of options for device type come up (or no matching device is reported). If it is not clear which is the sensor, I may need to you collect more info for the first device from the tuya portal, for the second, it does not look like the portal has any info so maybe need to do some experimenting, or use the debugger method.

The strange thing is, I dont see anything in the HA Logbook whilst trying to add the devices into the integration....

**Comment by isarib01** [comment]
Here is the log for Sensor Model 2 - Deta Light Motion Sensor, Grid Connect(DET100HA).

This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:35
Integration: Tuya Local (documentation, issues)
First occurred: 1:18:16 PM (4 occurrences)
Last logged: 1:21:39 PM

Device matches None with quality of 0%. DPS: {'101': 'mode_auto', '102': False, '103': 0, '104': 249, '105': 374, '106': False, 'updated_at': 1669180696.7623637}
Report this to https://github.com/make-all/tuya-local/issues/
Device matches None with quality of 0%. DPS: {'101': 'mode_auto', '102': False, '103': 2, '104': 160, '105': 981, '106': False, 'updated_at': 1669180899.0558958}

Full Log:


2022-11-23 13:21:39.284 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches None with quality of 0%. DPS: {'101': 'mode_auto', '102': False, '103': 2, '104': 160, '105': 981, '106': False, 'updated_at': 1669180899.0558958}
2022-11-23 13:21:39.285 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/

**Comment by make-all** [comment]
The sensors look to be the same at the protocol level, so a single config should cover both.  There still isn't really enough info to implement anything though - the portal info you posted first just mentions a single dp "pir" with possible values "none" and "pir", but what we see in the local protocol does not match.  I guess the pir is one of the booleans, either 102 or 106.  101 seems to be the mode - mode_auto would mean fully automatic, and I guess there are other values for overrides, either a mode_manual, or separate on and off values.  The numeric values 103, 104, 105 will be configuring the time and sensitivity.

If you use the debug method described in the zigbee2mqtt link in the README.md, you can probably find which dp maps to which function.  The ranges will need to come from the manual, or from the mobile app.

**Comment by isarib01** [comment]
Thanks for the reply, 

if it helps, here is the settings at the gui level of the devices.  I guess the booleans 102/101/106 etc represent these modes, sesitivity, lux perhaps?

![image](https://user-images.githubusercontent.com/73514261/204308196-a7f5a6c4-143f-46c4-bb5a-a1d5c7207c80.png)

**Comment by make-all** [comment]
I can't actually tell from these screen shots what the ranges are for the various settings and which setting corresponds to which dp id in the local data.  I also can't find a manual and only limited info on the webpage: that the duration range is 10s - 15min.  On another (non-smart) Deta PIR, I can also find that the light level range is 3-2000 lux, and the duration matches (10s +/- 3s to 15min +/- 2min) so probably similar.
I've made a preliminary config, but the guesses I've made for ranges and which setting is which may be wrong.  I also made another guess that dp 102 is the master switch, and 106 is the PIR detection value.  The cloud protocol info does hint that that should be available, but it is also possible that the extra boolean is some other sort of detection, such as tamper detection.

**Comment by isarib01** [comment]
Hi!,

Thanks for your reply, it must be difficult for you to work off thin air...  Much appreciate it.

I found this link which may/may not be helpfull.  I too would think the NON-Smart version of the Deta PIR would have the same functions.  They do sell the Non Smart version, and all the settings in the screenshot above is very much what a typical Non Smart PIR would have.

https://www.geekzone.co.nz/forums.asp?forumid=73&topicid=299111

**Comment by make-all** [comment]
You can try the device in the latest release.

**Comment by make-all** [comment]
Assuming this is working OK, as no feedback received since the release.

**Comment by isarib01** [comment]
Hi, 

Sorry I haven't had a chance to test it, currently abroad at the moment. I shall update it and update you in a few weeks.

Cheers

**Comment by isarib01** [comment]
Hello,

I'm back from my travels and trying to figure HOW to update the tuya local(excuse my stupidity).  My current version of Home Assistant is Home Assistant 2022.10.5/Frontend 20221010.0 - latest, and the update button of Home Assistant claims there is no updates pending...

In HACS, and Tuya Local Repo, there is also no Update button.

Appreciate any guidance.

**Comment by make-all** [comment]
The current version requires HA 2022.11, due to new Unit enums added  to Home Assistant.  So you will need to figure out why HA is not updating first.

**Comment by isarib01** [comment]
Hello,

I have managed to update my HA container, and pulled the latest release of tuya local.  I have also tested the entities you have created for the two mentioned models of deta Motion Sensors range and they detect/work great! 

I will do more testing and move the remaining 5 devices to tuya local to eliminate the cloud.

Thank you very much

**Comment by isarib01** [comment]
I have one question though, what is "Auto Reset"?  Is it merely just a toggle Enable/Disable the Sensor?

![image](https://user-images.githubusercontent.com/73514261/215344128-d454ba87-257f-4219-9a7a-ba88d0e9e80e.png)


![image](https://user-images.githubusercontent.com/73514261/215344065-af0a9640-da0e-4409-a65b-d38ad2ff1b85.png)

**Comment by make-all** [comment]
I can't comment on the functionality of the device. The information about what the different DPS are came from #356 about the Arlec branded device which appears to be the same.

**Comment by isarib01** [comment]
> I can't comment on the functionality of the device. The information about what the different DPS are came from #356 about the Arlec branded device which appears to be the same.

Just tried the "Auto Reset", what this does is just puts the light in the ON mode and counts down timer to turn off in 1hr.  I checked and compared the behaviours what each of the functionality did against the official Tuya or vendor app. 

So in hind sight, the entity Auto Reset should be called Sensor Off/Auto/On/On(Auto Reset).

That should be the only bit missing and is probably the most critical function of it.

Hope that makes sense.
Cheers

**Comment by cg6** [comment]
Hi, I've setup a DET100HA. It mostly works - thanks for your effort on this project.
The one issue is the on-off-auto as an effect is clunky. When the relay is off effect isn't shown, so it isn't easy to see if it is set to manual off, or if it is auto. Also if it is set to manual off and you want to change to auto, it requires first turning on then changing the effect to Auto.

Is it possible to add an "Auto" switch with the following logic:

101_State | 102_State| Auto_Sw_State | Auto_Sw Change Effect
---------- | ---------- | ---------------- | --------------------------
0             | N/A         | off                    | 101 set to 1 
2             | N/A         | off                    | 101 set to 1
1             | 0             | on                     | 101 set to 0
1             | 1             | on                     | 101 set to 2

This should in use make it feel like the Auto switch is purely affecting the auto function. The existing light entity should stay exactly like it is (show state, or change state and switch to manual if toggled).

I suspect the Tuya functions are the same as this Arlec unit https://templates.blakadder.com/arlec_MAL315HA.html
The product came in a DETA box but the Tuya app sees it as ARLEC.

<html>
<body>
<h2 id="tuya-dpid-list" style="box-sizing: border-box; font-weight: 300; letter-spacing: -0.1rem; margin-bottom: 2rem; margin-top: 0px; font-size: 3.6rem; line-height: 1.25; color: rgb(51, 51, 51); font-family: Roboto, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Tuya dpID list for Arlec Smart Security Light (MAL315HA)</h2>

dpID | Data Type | Function
-- | -- | --
101 | enum | Mode: 0=Off, 1=Auto, 2=Manual
102 | binary | relay status
103 | integer | Sensitivity (e.g.: 0 most sensitive, 3 misses a close wave, 5 quite coarse)
104 | integer | Light duration in seconds (e.g.: 10)
105 | integer | Light level adjustment (e.g.: 0 trigger any time, 500 blocked by torch, 4000 blocked by indoor light)
106 | binary | Send 1 while in manual mode to activate one hour countdown to revert to auto


</body>
</html>

**Comment by make-all** [comment]
Sorry it is not feasible to represent "auto" as a switch, as the underlying dp is tri-state.
I was only able to make on and off work from the switch because the device provides a read-only dp for the relay state, which could be overridden.

**Comment by cg6** [comment]
I'll look into it more. It might be more than a UI issue. When setting up automations I noticed the 'effect' attribute doesn't exist when the light is off.

**Comment by make-all** [comment]
Sorry, I just tried it here, and it looks like even extracting the attribute HA shows it as "--" when the light is off, even though we are able to read it from the actual device.

**Comment by cg6** [comment]
![image](https://user-images.githubusercontent.com/977146/216293851-dfc92189-546f-4a7f-a3ef-fc206ab75986.png)

![image](https://user-images.githubusercontent.com/977146/216294029-256f7ade-160d-4188-8e2e-d90f471ed520.png)

No luck - doesn't exist when off.

Can you show the state of id 101 as a sensor?

**Comment by cg6** [comment]
A secondary_entities of type 'select' and off-on-auto mapping to 101 should be enough.

**Comment by cg6** [comment]
> I don't have a motion light for testing here, but I do have one that has "scene" and "music" implemented as effects, and if I send effect: "scene" in the light.turn_on when the light is off, the light turns on as a side effect, but since dp 102 is read-only for the motion light, maybe it will work there without the light turning on.


The auto effect is tied to dp 101, you can't send an 'auto' to dp 102. 

I see in light.py you've already needed to custom handle the motion lights. I think in this case using effect is not working well. 

If 101 was moved to a select as I posted above;  Can light.py check for a mode entity in self._config.secondary_entities, instead of checking for `"off" in self._effect_dps.values(self._device)` ?

**Comment by make-all** [comment]
Yes, the id can be duplicated in multiple entities.  A select entity is the easy option, but the UI isn't great.  If I can get two switches (on/off and manual/auto) working, I think it would make for a better UI, so I'll still look at whether I can make it work..

Re 101/102, yes, I know that.  But 102 is tied to the "switch" on the light entity, so it can't actually turn the light on. It needs 101 set to "on" to turn on, but we are setting it to "auto" within the same command so hopefully that is enough to stop the light being turned on by side effect.

**Comment by cg6** [comment]
I tested latest main and that works perfect thanks. The "Auto mode" switch is a good solution.
I particularly like that the switch always matches the auto state, and turning off Auto mode keeps the current light state.
