### ISSUE TITLE
Smart MCB Switch stopped working after Tuya updated Its MCU

### ISSUE THREAD

**Issue by plandregan** [make-all/tuya-local#295]
This switch was working fine, on and off, then attributes for voltage, current and power.
SY1 WiFi switch with metering

Tuya then updated it to MCU 1.0.9 and now it says unavailable. If I edit the switch, i can see the device IP, local key etc Protocol version 3.3. 
Yet once added, the switch remains unavailable. 

Details from IoT developer page
    "owner_id": "56262698",
    "model": "AT-Q-SY1-JWT",
    "product_id": "jdj6ccklup7btq3a",
    "product_name": "WiFi Din Rail Switch with metering",

Is there anything else from the Debug I can off to assist getting this back on, before Tuya update the rest of my switches

**Comment by make-all** [comment]
Either the local key has changed, or the dps mapping has changed.  The cloud info above does not help with that - I need either the local log or the "Get Device Specification Attributes" results that contains dp_id as described in the README.md.

**Comment by plandregan** [comment]
Many thanks for responding

The DP IDs look to be the same. Here are them in full, for the Good 1st and Bad 2nd
Good Device
bf4b1e9712f61f9f70d***

{
  "result": {
    "category": "dlq",
    "functions": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "dp_id": 38,
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "light_mode",
        "dp_id": 40,
        "type": "Enum",
        "values": "{\"range\":[\"relay\",\"pos\",\"none\",\"on\"]}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "add_ele",
        "dp_id": 17,
        "type": "Integer",
        "values": "{\"min\":0,\"max\":50000,\"scale\":3,\"step\":100}"
      },
      {
        "code": "cur_current",
        "dp_id": 18,
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":100000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_power",
        "dp_id": 19,
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":0,\"max\":99999,\"scale\":1,\"step\":1}"
      },
      {
        "code": "cur_voltage",
        "dp_id": 20,
        "type": "Integer",
        "values": "{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "test_bit",
        "dp_id": 21,
        "type": "Integer",
        "values": "{\"min\":0,\"max\":5,\"scale\":0,\"step\":1}"
      },
      {
        "code": "voltage_coe",
        "dp_id": 22,
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "electric_coe",
        "dp_id": 23,
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "power_coe",
        "dp_id": 24,
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "electricity_coe",
        "dp_id": 25,
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "fault",
        "dp_id": 26,
        "type": "Bitmap",
        "values": "{\"label\":[\"ov_cr\",\"ov_vol\",\"ov_pwr\",\"ls_cr\",\"ls_vol\",\"ls_pow\"]}"
      },
      {
        "code": "relay_status",
        "dp_id": 38,
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "light_mode",
        "dp_id": 40,
        "type": "Enum",
        "values": "{\"range\":[\"relay\",\"pos\",\"none\",\"on\"]}"
      },
      {
        "code": "child_lock",
        "dp_id": 41,
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1669709582313,
  "tid": "a4cea2546fbd11edb831be74e8817213"
}

Bad Device
bf3ce4e995cefbadbe0***

ResponseCopy
{
  "result": {
    "category": "dlq",
    "functions": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "dp_id": 38,
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "light_mode",
        "dp_id": 40,
        "type": "Enum",
        "values": "{\"range\":[\"relay\",\"pos\",\"none\",\"on\"]}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "add_ele",
        "dp_id": 17,
        "type": "Integer",
        "values": "{\"min\":0,\"max\":50000,\"scale\":3,\"step\":100}"
      },
      {
        "code": "cur_current",
        "dp_id": 18,
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":100000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_power",
        "dp_id": 19,
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":0,\"max\":99999,\"scale\":1,\"step\":1}"
      },
      {
        "code": "cur_voltage",
        "dp_id": 20,
        "type": "Integer",
        "values": "{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "test_bit",
        "dp_id": 21,
        "type": "Integer",
        "values": "{\"min\":0,\"max\":5,\"scale\":0,\"step\":1}"
      },
      {
        "code": "voltage_coe",
        "dp_id": 22,
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "electric_coe",
        "dp_id": 23,
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "power_coe",
        "dp_id": 24,
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "electricity_coe",
        "dp_id": 25,
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "fault",
        "dp_id": 26,
        "type": "Bitmap",
        "values": "{\"label\":[\"ov_cr\",\"ov_vol\",\"ov_pwr\",\"ls_cr\",\"ls_vol\",\"ls_pow\"]}"
      },
      {
        "code": "relay_status",
        "dp_id": 38,
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "light_mode",
        "dp_id": 40,
        "type": "Enum",
        "values": "{\"range\":[\"relay\",\"pos\",\"none\",\"on\"]}"
      },
      {
        "code": "child_lock",
        "dp_id": 41,
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1669709392977,
  "tid": "33e93d7f6fbd11edb831be74e8817213"
}

**Comment by make-all** [comment]
Since the dps did not change, then something else must have.  Did you remove and try to re-add the device yet?  Or check the IP address and update that in the config.

**Comment by plandregan** [comment]
No, the IP is the same, the local key is the same. If I re-add it, it adds fine, then shows as unavailable in the list. 
Attached are some logs and debug
[home-assistant.log](https://github.com/make-all/tuya-local/files/10114330/home-assistant.log)
[config_entry-localtuya-727b7c4d7c99c7f50fad85f17eb9c262.json.txt](https://github.com/make-all/tuya-local/files/10114332/config_entry-localtuya-727b7c4d7c99c7f50fad85f17eb9c262.json.txt)

**Comment by make-all** [comment]
Those logs and configuration are for a different integration.
