### ISSUE TITLE
Adding X-Sense smoke detector

### ISSUE THREAD

**Issue by Kulturnilpferd** [make-all/tuya-local#297]
Hey there,
I have a problem by adding an X-Sense smoke detector. Due the nature of these thing (and batery saving) it goes out if it has the connection to the cloud. When I use a mac filter to deny that thingy the internet access I can connect to it and have enough time to do so. But sadly even with my config the sensor wouldn't be detected, just endless searching in the dialog... Is there anything I can do that it would be recognized?

**Comment by Kulturnilpferd** [comment]
Now waiting a bit i got these error:
[custom_components.tuya_local.device] Failed to refresh device state for Test.

**Comment by make-all** [comment]
Battery powered devices essentially need the cloud to operate.

**Comment by Kulturnilpferd** [comment]
So you can get it to be online for a few minutes connected to the wlan if you cut of the internet. Maybe there is a chance that it can be synced, just need to "hear" if these thing goes on or do an alarm. Even the Silence mode is only triggered from the mobile phone, if there is an alarm it just shuts off the alarm on the phone. Doesn't know how to realize if you give me some hint how I could debug it better I would be very interested to get these things local online without a cloud. Also ordered on black friday some battery powered wlan temp sensors, I doubt they sadly will also have this "offline" behavior.

**Comment by Kulturnilpferd** [comment]
Maybe have some chance to flash it with tuya-convert... doesn't want to open it up to flash some custom firmware on it :D

**Comment by Kulturnilpferd** [comment]
So have tried to flash the TYWE3S insite this thing. I can't get it any further (incl. soldering it out and connect pins directly). Discovered that they soldered AND glued it to the main circuit board. Due its not working and firuring over 24h out what some dickhead somke alarm developer has developed to make it harder to get into this incopatible pile of shit esp i throw this fuck in the garbage. 33€ and 24h of lifetime lost >.< Next time I search either for a bigger hammer or compatible products...

**Comment by make-all** [comment]
Note that your battery life will be measured in days or even hours unless you specifically customize your firmware to have the same behaviour of dropping offline for long periods between updates.
