### ISSUE TITLE
Add new device - Aubess diy smart switch

### ISSUE THREAD

**Issue by vnkorol** [make-all/tuya-local#299]
https://aliexpress.ru/item/1005004478098241.html

{
  "result": {
    "category": "tdq",
    "functions": [
      {
        "code": "switch_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "dp_id": 38,
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\"]}"
      },
      {
        "code": "random_time",
        "dp_id": 42,
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "cycle_time",
        "dp_id": 43,
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "switch_inching",
        "dp_id": 44,
        "type": "String",
        "values": "{\"maxlen\":255}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "dp_id": 38,
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\"]}"
      },
      {
        "code": "random_time",
        "dp_id": 42,
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "cycle_time",
        "dp_id": 43,
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "switch_inching",
        "dp_id": 44,
        "type": "String",
        "values": "{\"maxlen\":255}"
      }
    ]
  },
  "success": true,
  "t": 1669916307076,
  "tid": "f65a0a05719e11edac99da3a06eee480"

**Comment by vnkorol** [comment]
I am sorry, it was old version installed at my system :( all works great.

**Comment by make-all** [comment]
I was going to suggest that this should mostly work with one of the existing devices.
