### ISSUE TITLE
Power Monitoring Does not default / update to 0 when off

### ISSUE THREAD

**Issue by botts7** [make-all/tuya-local#3]
Kogan Smart Plug - shows previous values when device is in off state?

**Comment by make-all** [comment]
The power monitoring reports what the device reports, regardless of whether the switch is off or on.  I find mine fluctuate between 0.9 and 1.4W for a while after turning off before going to zero.  I presume this usage is from the Wi-Fi module itself maintaining an active state for a while before entering low power mode.

However the new firmware may have different behaviour. If you are able to confirm the reported dps with tuyacli or by enabling debug logging in the HomeAssistant config, we can rule out the possibility that the device stops reporting power consumption completely when off, which may indeed cause HomeAssistant to keep reporting the old values.

**Comment by botts7** [comment]
I can confirm that there is a 10 minute delay after removing a load before home assistant updates to 0 for amps and watts

**Comment by botts7** [comment]
The Tuya App reports the change straight away. Also of note, if I open the tuya app and check power usage the device goes unavailable in home assistant. An when I kill the tuya app the attributes then update in home assistant and I dont have to wait the  10 mins for an update? Any ideas?

**Comment by make-all** [comment]
I guess the tuya app is sending some command to trigger the update right away. But without documentation of the command protocol, it is not something that we can easily figure out.  I intend to switch the underlying tuya library to the maintained tuyaface library in future, which may help with issues like this.

**Comment by make-all** [comment]
Please check with 0.2.0.  It is using a newer underlying tuya library, which may handle this situation better.

**Comment by make-all** [comment]
Closed due to no feedback
