### ISSUE TITLE
Add Support for Kogan Smart Dehumidifier 

### ISSUE THREAD

**Issue by b3nnyk22** [make-all/tuya-local#30]
Hello 

Was wondering if it would be possible to add support for the following smart dehumidifier: 

https://www.kogan.com/au/buy/kogan-smarterhome-smart-7l-desiccant-dehumidifier/?utm_source=google&utm_medium=product_listing_ads&gclid=Cj0KCQjwraqHBhDsARIsAKuGZeGvh80L-kiwAqezFm2FI3ZHfOJzyLT-BHJcDvfYW_gQYscddFcDWfUaAleBEALw_wcB

I've mapped the DPs as following: 

1 - value: true/false (power)

2 - value: low/middle/high/quickdry (fan) 

3 - value: numeric (humidity sensor) 

8 - value: true/false (swing)

11 - value: 0/1 (tank full indicator)

12 - value: 0, 1, 2, 3 (countdown timer select)

13 - value: 0, 120, 240, 480 (countdown timer minutes)

101: value: 0 - 80 (humidity set point)

Cheers! :)

**Comment by make-all** [comment]
This should be working now in 0.8.7. 

If it is not showing in HACS yet, you can force a check by clicking the menu button on the Tuya Local integration within HACS and selecting "Update Information".

**Comment by b3nnyk22** [comment]
Hey mate.

Thanks for getting this done so quickly. 

I've tested this. Everything seems to work but there seems to be a slight digression with the fan settings. 

Setting the unit mode from the Humidifier entity works for Low, High and Dry Clothes as expected but setting it to medium seems to put the unit into "Dry Clothes" mode. 

Setting the fan speed from the Fan entity gives the following result: 

0, 33 = Low 
67 = Dry Clothes 
100 = High 

When using the fan slider these are the only speeds you can select. 

Not sure why this is happening. Let me know if there's anyway I can help you with this. 

Cheers!

**Comment by make-all** [comment]
I see the issue. I put medium, as per the Home Assistant naming, the list above has middle so it needs to be translated.  Strange that it defaults to Dry Clothes mode.  It was intentional that you could not select Dry Clothes from the fan slider, as it isn't really another speed for the fan, just a combination of High speed with more aggressive dehumidification I think.  The manual also separated it out from the fan speeds.

**Comment by b3nnyk22** [comment]
Also, when using the device in HomeKit it's reporting its "Current Relative Humidity" as 0 when it is in fact 54%.

 When looking at the entity in developer tools I can see it's reporting "current_humidity" correctly at 54% but "humidity" is 0% which is what I assume HomeKit is reading. Is there anyway to change this so the correct Humidity shows up in HomeKit? 

Cheers.

**Comment by b3nnyk22** [comment]
Sorry that's my bad. I see now that "humidity" is the actual set point humidity. 

I've done a similar thing with my Sensibo in my living to report the humidity from that into HomeKit. It is annoying though that the dehumidifier will report 0% as a default as there's no way to hide this in HomeKit. 

Thanks mate.

**Comment by make-all** [comment]
It's not actually mentioned in the documentation at all. The documentation mentions linked_battery_sensor, linked_doorbell_sensor and linked_motion_sensor, but you would only find out about linked_humidity_sensor if you read the source code of the homekit integration.  But that seems to be the only way to get current humidity reported for a humidifier or dehumidifier.

**Comment by make-all** [comment]
I think with 0.8.8, the fan speed should be working correctly now.

**Comment by b3nnyk22** [comment]
I didn't even realise you could link entities until re-reading the documentation. That's neat! Will give that a shot. 

Just tested 0.8.8 and it's working perfectly! Thanks so much for your work.

**Comment by make-all** [comment]
Thanks for checking and confirming.
