### ISSUE TITLE
Add new device - GNCC Smart Socket 16A

### ISSUE THREAD

**Issue by SvenMartin81** [make-all/tuya-local#300]
Hello!
Is it possible to add new device configuretion for GNCC Smart Socket 16A.
attached are the some usefull informations for this device.

{
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "switch_1",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Switch 1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "lang_config": {
          "unit": "s"
        },
        "name": "Countdown 1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "lang_config": {
          "last": "Remember last status",
          "power_off": "OFF",
          "power_on": "On"
        },
        "name": "Relay Status",
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "cycle_time",
        "lang_config": {
          "unit": "s"
        },
        "name": "cycle time",
        "type": "String",
        "values": "{}"
      },
      {
        "code": "random_time",
        "lang_config": {
          "unit": "s"
        },
        "name": "random time",
        "type": "String",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Switch 1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "lang_config": {
          "unit": "s"
        },
        "name": "Countdown 1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "add_ele",
        "lang_config": {
          "unit": "W"
        },
        "name": "Add Electricity",
        "type": "Integer",
        "values": "{\"unit\":\"kW·h\",\"min\":0,\"max\":50000,\"scale\":3,\"step\":100}"
      },
      {
        "code": "cur_current",
        "lang_config": {
          "unit": "mA"
        },
        "name": "Current",
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_power",
        "lang_config": {
          "unit": "W"
        },
        "name": "Power",
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":0,\"max\":80000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "cur_voltage",
        "lang_config": {
          "unit": "V"
        },
        "name": "Voltage",
        "type": "Integer",
        "values": "{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "relay_status",
        "lang_config": {
          "last": "Remember last status",
          "power_off": "OFF",
          "power_on": "On"
        },
        "name": "Relay Status",
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "cycle_time",
        "lang_config": {
          "unit": "s"
        },
        "name": "cycle time",
        "type": "String",
        "values": "{}"
      },
      {
        "code": "random_time",
        "lang_config": {
          "unit": "s"
        },
        "name": "random time",
        "type": "String",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": xxxx,
  "tid": "xxxx"
}

**Comment by make-all** [comment]
This looks like a basic switch, what exactly is not working with the existing configurations?

If a new config is needed to support this device, I will need local protocol information, not just the cloud protocol documentation.  Please see the README.md for more detailed information about what is needed.

**Comment by SvenMartin81** [comment]
Hi, I was able to integrate the socket but I cannot switch....means there is no reaction on the socket....

**Comment by make-all** [comment]
Do you have the mobile app open while doing your test?  You need to either close it or ensure the device it is running on is not on the local network.

**Comment by SvenMartin81** [comment]
I tried this Morning Without the Tuya smart app. It is Not possible. The socket is in my local network „online“. 
By using the Tuya Smart App I can switch.

**Comment by make-all** [comment]
Please download the diagnostics from Settings / Devices & Services / Tuya local - <YOUR DEVICE> / 1 device/ Download Diagnostics and post them here.  This will be a start of making sense of what is happening on the local protocol level.

Also, if there are any log messages appearing from this integration, please include the details.

**Comment by SvenMartin81** [comment]
no. I do not have the mobile app open....the device is running, means the lamp on the switch on the plug is on.

**Comment by SvenMartin81** [comment]
I just saw, by switching on the socket that the home assistant is switching the switch...but by using the switch in HA the socket is not switching.

**Comment by SvenMartin81** [comment]
if I switch in HA....it takes some time....30sec or something...and the switch goes back to its status on the hardware

**Comment by SvenMartin81** [comment]
hi, thanks for working on this issue but the last update brought no better result. I cannot switch from HA.... 

Info: the current power and voltage is shown up 

mwans for me partly it is running but the mainpart. the switching is not possible

**Comment by make-all** [comment]
In the latest version, you can try manually setting the protocol version (if it was half working with v3.3, I think 3.2 may also be an option, which might help make the rest working).

**Comment by SvenMartin81** [comment]
hi, I send the sockets back to amazon....and bought some with Zigbee. so I think we can close this issue, becuase I don't know how this is running next.
