### ISSUE TITLE
Device is detected as switch

### ISSUE THREAD

**Issue by Fannangir** [make-all/tuya-local#31]
Hi,
Tried both 0.8.8 and main.
Both detect my AC device as a switch.
Product category is: kt
This is the info I have managed to see in the device debug under tuya development platform:

switch | Boolean | "{true,false}"
temp_set | Integer | {   "min": 16,   "unit": "℃",   "scale": 0,   "max": 32,   "step": 1 }
mode | Enum | {   "range": [     "auto",     "cold",     "hot",     "wet",     "wind",     "eco"   ] }
fan_speed_enum | Enum | {   "range": [     "auto",     "low",     "middle",     "high"   ] }

I have found a homebridge plugin for my AC, which actually works great.
Maybe it could help with the required information, found in the following link:
https://github.com/nitaybz/homebridge-tadiran-ac

Thanks.

**Comment by make-all** [comment]
There is some information in the code of that repository, but it would also be useful to see the Warnings that appear in the HomeAssistant log when you try to add the device.

**Comment by Fannangir** [comment]
This is what I see prior I accept the basic switch configuration:

Device matches simple_switch with quality of 8%. DPS: {'1': True, '2': 25, '3': 250, '4': 'cooling', '5': 'low', '101': 0, '102': 260, '103': 225, '104': 'low', '105': 'stop', '106': -300, '107': False, '108': False, 'updated_at': 1626713690.985591}

Is this the information you have asked for?

**Comment by make-all** [comment]
Yes, that is the full info the air conditioner is returning.  I added a config based on the link you gave yesterday, but number '104' does not seem to match that, being a string rather than a boolean.

**Comment by make-all** [comment]
If you Reinstall (no need to uninstall, just select "Reinstall" from the menu for tuya local in HACS), the "main" version, you may see some progress now.

The config for Homebridge has some support for swing mode, but it does not seem to match. You should be able to experiment with the buttons on the IR remote, and check in HA Developer Tools what effect it has on the States of the climate entity once it is added.

**Comment by Fannangir** [comment]
You are awesome.
It works.
I have tested all the modes, these work OK.
I have tested temperature, works OK.
This is the info I see in the developer tools (off mode):
![image](https://user-images.githubusercontent.com/30548574/126374252-232aafc3-01df-4eb3-ba7c-832e9e1a4a5b.png)

This is the info I see when the unit cools:
![image](https://user-images.githubusercontent.com/30548574/126374774-57f5ffa6-f890-44d4-a803-ba2b21a8493d.png)

As for swing, my AC is a central unit, it does not support this mode.
And this is what I see when I press the swing button (the button which should move the vents, although it does nothing in my unit)
![image](https://user-images.githubusercontent.com/30548574/126375078-dee2974d-4c1d-44f8-af68-cef1d903f655.png)

As for the climate generated entity, I miss the temperature reading.
Is it something that you can fix (please refer to the snapshot below)?
I guess the issue is due to dual row of current_temperature (one reads null, the other the correct temperature).
![image](https://user-images.githubusercontent.com/30548574/126373975-9c395392-6d9a-4038-9ff7-6dd5b00b0679.png)

Thanks again for the great work.

**Comment by make-all** [comment]
There is a typo in the current_temperature config (it is missing the a).  Due to the differences with that homebridge config for swing mode, I guess there are going to be several versions of this brand's units. Do you have a model number / name that I can use to make it clear which unit this config is for?

**Comment by Fannangir** [comment]
Sure, there are many models by Tadiran (manufacturer’s name).
This specific model is Wind 65/3P.
I guess this config will be identical for the whole Wind series.

**Comment by Fannangir** [comment]
Works like a charm.
Temp. is displayed as well (incl. homekit on my iOS).

Thank you very much.
