### ISSUE TITLE
New Device: INOW+ WiFi heating element

### ISSUE THREAD

**Issue by Paul-C-S** [make-all/tuya-local#312]
I've got a few of these elements that you fit into towel radiators.  I've made a YAML file that works but has a few issues,

There is an odd thing that when the device is first turned on you get these are the details from TUYA-CLI and the TUYA developer website:

tuya-cli get ***
{ dps: { '1': true, '2': 70, '3': 71, '4': 'smart', '7': false } }

From TUYA developer:

Standard Instruction Set

switch	Boolean	
"{true,false}"
temp_set	Integer	
{
  "unit": "℃",
  "min": 15,
  "max": 70,
  "scale": 0,
  "step": 5
}
mode	Enum	
{
  "range": [
    "smart"
  ]
}
lock	Boolean	
"{true,false}"
countdown_set	Enum	
{
  "range": [
    "2h",
    "4h"
  ]
}

Standard Status Set

switch	Boolean	
"{true,false}"
temp_set	Integer	
{
  "unit": "℃",
  "min": 15,
  "max": 70,
  "scale": 0,
  "step": 5
}
temp_current	Integer	
{
  "unit": "℃",
  "min": -20,
  "max": 90,
  "scale": 0,
  "step": 1
}
mode	Enum	
{
  "range": [
    "smart"
  ]
}
lock	Boolean	
"{true,false}"
countdown_set	Enum	
{
  "range": [
    "2h",
    "4h"
  ]
}

However, there is also an option called 'Boost' on the TUYA app which turns on the radiator for 1 or 2hrs and only when you select this you ID19 (a bug I guess?)

{
  dps: { '1': true, '2': 70, '3': 71, '4': 'smart', '7': false, '19': '2h' }
}

From TUYA developer:

Standard Instruction Set

switch	Boolean	
"{true,false}"
temp_set	Integer	
{
  "unit": "℃",
  "min": 15,
  "max": 70,
  "scale": 0,
  "step": 5
}
mode	Enum	
{
  "range": [
    "smart"
  ]
}
lock	Boolean	
"{true,false}"
countdown_set	Enum	
{
  "range": [
    "2h",
    "4h"
  ]
}

Standard Status Set

switch	Boolean	
"{true,false}"
temp_set	Integer	
{
  "unit": "℃",
  "min": 15,
  "max": 70,
  "scale": 0,
  "step": 5
}
temp_current	Integer	
{
  "unit": "℃",
  "min": -20,
  "max": 90,
  "scale": 0,
  "step": 1
}
mode	Enum	
{
  "range": [
    "smart"
  ]
}
lock	Boolean	
"{true,false}"
countdown_set	Enum	
{
  "range": [
    "2h",
    "4h"
  ]
}

I don't need to use the countdown boost (ID19) because that's easy to automate with Home Assistant so I'm currently working with this YAML file which excludes it so that the device is recognised without having to use the app and turn the feature on:

name: inow heater element
primary_entity:
  entity: climate
  dps:
    - id: 1
      type: boolean
      name: hvac_mode
      mapping:
        - dps_val: true
          value: heat
        - dps_val: false
          value: "off"
    - id: 2
      type: integer
      name: temperature
      range:
        min: 15
        max: 70
      mapping:
         - scale: 1
           step: 5
           constraint: temperature_unit
           conditions:
            - dps_val: false
              step: 5
              range:
                min: 15
                max: 70
    - id: 3
      type: integer
      name: current_temperature
      mapping:
        - scale: 1
    - id: 4
      type: string
      name: preset_mode
      mapping:
        - dps_val: "smart"
          value: comfort
        - dps_val: "antifreezing"
          value: Anti-Freeze

secondary_entities:
  - entity: lock
    name: Child lock
    category: config
    dps:
      - id: 7
        type: boolean
        name: lock
        mapping:
          - dps_val: true
            icon: "mdi:hand-back-right-off"
          - dps_val: false
            icon: "mdi:hand-back-right"

That's excluding this ID:

    - id: 19
      type: string
      name: timer
      mapping:
        - dps_val: "0h"
          value: "off"
        - dps_val: "1h"
          value: comfort
        - dps_val: "2h"
          value: comfort

If you improve this in any way, please do!

Thanks, Paul :)

**Comment by make-all** [comment]
Remove the constraint and conditions for temperature_unit, as there is no temperature unit dp.
You can include dp19 as an optional attribute on the primary_entity for reading, but it will not be possible to set it.

**Comment by Paul-C-S** [comment]
Thank you!

This is my new YAML file:

name: inow heater element
primary_entity:
  entity: climate
  dps:
    - id: 1
      type: boolean
      name: hvac_mode
      mapping:
        - dps_val: true
          value: heat
        - dps_val: false
          value: "off"
    - id: 2
      type: integer
      name: temperature
      range:
        min: 15
        max: 70
      mapping:
         - scale: 1
           step: 5
    - id: 3
      type: integer
      name: current_temperature
      mapping:
        - scale: 1
    - id: 4
      type: string
      name: preset_mode
      mapping:
        - dps_val: "smart"
          value: comfort
        - dps_val: "antifreezing"
          value: Anti-Freeze
    - id: 19
      optional: true
      type: string
      name: timer
      mapping:
        - dps_val: "0h"
          value: "off"
        - dps_val: "1h"
          value: comfort
        - dps_val: "2h"
          value: comfort

secondary_entities:
  - entity: lock
    name: Child lock
    category: config
    dps:
      - id: 7
        type: boolean
        name: lock
        mapping:
          - dps_val: true
            icon: "mdi:hand-back-right-off"
          - dps_val: false
            icon: "mdi:hand-back-right"

**Comment by Paul-C-S** [comment]
That works great for me - thank you!
