### ISSUE TITLE
Moes thermostat BW-WIFI

### ISSUE THREAD

**Issue by bartoszx** [make-all/tuya-local#314]
Hello
Can you add following device 
Device matches garage_door_opener with quality of 10%. DPS: {'updated_at': 1671123225.0320082, '1': True, '2': 50, '3': 180, '6': False, '12': 0, '101': False, '102': False, '103': 0, '104': 14, '105': 20, '106': True, '107': True, '108': False, '109': -10, '110': 15, '113': 7, '114': 35, '115': 5, '117': 'keep', '118': '2days'}

**Comment by make-all** [comment]
I need more information on the meaning of those dps and ranges etc.

**Comment by make-all** [comment]
Closing as nothing can be done without the information requested more than one month ago.
