### ISSUE TITLE
Easy way to test device configs

### ISSUE THREAD

**Issue by and7ey** [make-all/tuya-local#317]
Could you please find a way to test new device configs (yaml files) without HA restart? 
It takes a lot of time to test new devices now.

**Comment by make-all** [comment]
You can run `pytest tests/test_device_config.py`, which will perform some basic checks on the device config files prior to deployment.

**Comment by and7ey** [comment]
Thanks. I wanted to test something more than what [test_device_config.py](https://github.com/make-all/tuya-local/blob/main/tests/test_device_config.py) does:
- new effects added
- color modes added/deleted
- new data points added
- etc.

**Comment by and7ey** [comment]
Just in case somebody will be looking for some solution. I use the following approach currently:
1. Modify the yaml
2. Delete the device/integration
3. Add the integration again (so, you'll have to input device id, ip and local key again :( )
4. Now the device will work with updated yaml
So, no need to restart HA

**Comment by and7ey** [comment]
`YAML configuration reloading` you mean? Or, where should I find that `Reload` option?

**Comment by make-all** [comment]
On the Settings / Devices tab, if you select the device inside the Tuya Local box, then in the menu there is a "Reload" item.  This appears to load the new yaml when I tried it just now.

**Comment by make-all** [comment]
As the Reload is working, I think this issue is taken care of already by Home Assistant's generic device support.

**Comment by and7ey** [comment]
Thanks! It works, but looks like doesn't cover all scenario. For ex., I remove some mappings, then the list is updated.
But when I tried to change entity type from hex to string, I received the following error

```
2023-01-08 14:15:36.453 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Fairy lights for select
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
result = await component.async_setup_entry(hass, self)
File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 62, in async_setup_entry
return await component.async_setup_entry(entry)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 166, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
```
