### ISSUE TITLE
c16 state is always the same, request to change to another attribute

### ISSUE THREAD

**Issue by SamJongenelen** [make-all/tuya-local#319]
Hey,

I've got a great working c16 in Homeassistant :) I now have a device `state` question or request.

The c16 is for me only ever used in `hvac_mode`  'heat', as is is the floor heater in my bathroom. 
Currently in HA, the `state` of the device is always the 'operation'.  So it is always heat, which shows as following in the UI: 
![image](https://user-images.githubusercontent.com/3382443/209319546-cfb75e8b-81bf-4702-aefc-38d627828d0f.png)

I would love the `hvac_action` to be mapped as the state, it now switches nice from 'idle' to 'heating' :). 
Templating `Climate` is a bit hard, hence the question here. 

![image](https://user-images.githubusercontent.com/3382443/209318899-3e5380d0-8b35-451a-b8b7-3678994a1e16.png)

**Comment by make-all** [comment]
HA maps the state to hvac_mode for climate devices.  It is not something that is up to this integration to change.

**Comment by SamJongenelen** [comment]
Related Mushroom issue :) 
https://github.com/piitaya/lovelace-mushroom/issues/629
