### ISSUE TITLE
Kyvol E30 vacuum not avalible since last update

### ISSUE THREAD

**Issue by SvenMartin81** [make-all/tuya-local#322]
hi,
i cannot connect to my vaccum since the last update form the integration. I tried to configure the vacuum new but it does not run and it cannot find the vacuum (the protocol is on auto, or all version from 1-4). After testing some things, e remembered that i deleted the vaccuum in the cloud....and that was the reason..... After I added the vacuum again and changed the uuid and the local key.... everything is running fine.

but why can't I delete the device in the cloud.? I thought that Tuya local is a cloudfree soloution.  

what do you think ?

**Comment by make-all** [comment]
I cannot influence or explain how Tuya devices interact with the cloud.

I have made no claims that it is possible to remove your devices from the Tuya cloud by using this integration, in fact I have explicitly stated that using this device does not stop your devices from reporting to the cloud.  If you don't want devices that report to the cloud, then Tuya devices are not really a viable solution.
