### ISSUE TITLE
Device mismatches

### ISSUE THREAD

**Issue by jsstv01** [make-all/tuya-local#323]
Device matches simple_switch_timerv2 with quality of 17%. DPS: {'updated_at': 1672073378.6609213, '1': True, '9': 0, '21': 40, '22': 20, '23': 2507, '24': 2, '29': 0, '38': 'on', '42': '', '43': '', '44': '', '47': 'flip'}

Actual Device - Aubess energy monitor switch

I have 5 devices and 3 were detected correctly and having issue with remaining 2 devices.
Thanks for your guidance.

**Comment by make-all** [comment]
This doesn't seem to be reporting the energy monitoring attributes, only the calibration for it, which is weird.  There is also another attribute that unexpectedly is coming through as an empty string instead of a boolean true/false.

**Comment by jsstv01** [comment]
Ironically, it worked after couple of hours of usage of device.
