### ISSUE TITLE
groups

### ISSUE THREAD

**Issue by sujitvasanth** [make-all/tuya-local#324]
Hi have 6x Calex GU10 wifi bulbs. using protocol 3.4 so rospogrigio/localtuya/ doesnt work at present (supports<=3.3) but make-all/tuya-local does work. Thanks for the great software!

Please note that in the docs the integration link does not work for newer versions of home assistant that block the non-standard link - you need to go into HACS and manually search repositories integration for make-all/tuya-local - maybe helpful to add this to the docs as I had almost given up trying to add to HACS.

With regard to the gu10 lights used locally. They are detected and turn on and off fine individually and if I manually turn them all on as fast as I can this works fine
But when using an automation with all 6 either with a delay of 250 ms or all together things work erratically (some don't turn off/on at all or they turn off at different times over about a minute). Cycling through the lights twice in the automation does seem to work but I think this throws up errors at the tuya server causing the lights to become unavailable (just my guess). I then have to unpair and pair my lights using the android Smartlife app which re-generates the local key. then I update the keys in your app and it works again.

Please can you have a  feature to handle groups better? and also to deal with the refractory time for sending multiple messages? Why should it matter when I try to control multiple entities simultaneously?
and how come the cloud based tuya server overcomes this?

**Comment by make-all** [comment]
Groups are a Home Assistant feature, and nothing to do with this integration.
