### ISSUE TITLE
AlecoAir D16 not detected correctly

### ISSUE THREAD

**Issue by culdaraul** [make-all/tuya-local#328]
Hello there.
I've tried today to setup my Alecoair D16 dehumidifier - known to be supported but seems that I do have some issues. Is there something wrong (maybe a newer FW on my unit) which makes the identification not working?

![image](https://user-images.githubusercontent.com/8573177/210113757-a8258a6a-3bb3-40d5-969a-f9c3cc08c98c.png)

![image](https://user-images.githubusercontent.com/8573177/210113578-0209049f-e0a9-4b4e-8344-74a5197a3f11.png)

I'm running 2022.12.8 on my VM server. Any help would be appreciated.

**Comment by make-all** [comment]
It seems to be using a completely different command/data mapping than the AlecoAir D16 that was submitted previously.
Please go through the steps in the README.md file regarding finding info for new devices.

**Comment by make-all** [comment]
OK, that is useful information, as it gives us something obvious to differentiate the two configurations.  But I still need more info about the dps values to make a config.  With just the list from the log they are nothing but a list of random numbers and booleans.

**Comment by masterminds84** [comment]
> OK, that is useful information, as it gives us something obvious to differentiate the two configurations. But I still need more info about the dps values to make a config. With just the list from the log they are nothing but a list of random numbers and booleans.

I am newbie in the Home Assistant. I will help you with the DPS values, but please tell me, how can I do this values get. The purify is in the Tuya IOT platform, and the Tuya Smart app can controll it now.
Thank you your answer.

**Comment by make-all** [comment]
There are details here https://github.com/make-all/tuya-local#device-support

**Comment by masterminds84** [comment]
There are the values:

```
Power - 1
Mode - 2
Humidity - 3
Set Humidity - 4
Anion - 5
Inside Drying - 101
Wind Speed - 6
Water Pump - 102
Child Lock - 7
Swing - 8
Fault - 11
Countdown - 12
Remaining Time - 13
```

**Comment by make-all** [comment]
If you can post the functions and status info from any of the API Explorer functions that list the above (don't worry about finding the one with dps, because you already posted them, as long as it has the names), that will contain ranges and indicate which are read-only and which writable.

**Comment by masterminds84** [comment]
I found only just this, but I know, that the Set Humidity values is: 30-35-40-45-50-55-60-65-70-75-80. 

`{
  "result": {
    "category": "cs",
    "functions": [
      {
        "code": "anion",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Anion",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "swing",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Swing",
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "anion",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Anion",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "swing",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Swing",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fault",
        "lang_config": {
          "e1": "",
          "e2": ""
        },
        "name": "Fault",
        "type": "Bitmap",
        "values": "{\"label\":[\"E1\",\"E2\"]}"
      },
      {
        "code": "countdown_left",
        "lang_config": {
          "unit": "min"
        },
        "name": "Remaining Time",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":1440,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1673857209878,
  "tid": "976cdc6c957611edb15f72681cb52e7c"
}`

**Comment by Liionboy** [comment]
Same problem for AlecoAir D12 Dehumidifier:

![Screenshot from 2023-01-16 11-01-43](https://user-images.githubusercontent.com/87735636/212638933-3bcf97a2-e786-4512-ae4c-9bd8d51689a3.png)

**Comment by make-all** [comment]
There seems to be very little info in the portal then.  As well as the humidity range given above, the list of modes (both the values from the protocol, and the UI/meaning if it isn't obvious from the dps values), the list of fan speeds, and if you know what water pump and inside drying do, whether they are settings or indicators.  Also if you can identify any of the values of Fault (tank full/missing is probably the main one which would be useful for automations eg to notify so if the dehumidifier is away out of sight and hearing you know to go and check on it).

**Comment by Liionboy** [comment]
so after all is not suported right? I can give you this if help with something:

{
  "result": {
    "active_time": 1675843604,
    "biz_type": 0,
    "category": "cs",
    "create_time": 1675843604,
    "icon": "smart/icon/ay1571897408473s5wkc/0d45b3b80458368688a1df8cead4cda6.png",


    "lat": "45.0622",

    "lon": "24.9386",
    "model": "HOME",
    "name": "Dezumidificator Home",
    "online": true,

    "product_id": "hp1sjssyokokbrsg",
    "product_name": "D12/D16 HOME",
    "status": [
      {
        "code": "anion",
        "value": false
      },
      {
        "code": "swing",
        "value": false
      },
      {
        "code": "fault",
        "value": 0
      },
      {
        "code": "countdown_left",
        "value": 0
      }
    ],
    "sub": false,
    "time_zone": "+02:00",
    "uid": "eu1639342404951Qjbek",
    "update_time": 1675843619,
    "uuid": "ec9ab96095cf59b6"
  },
  "success": true,
  "t": 1675878189037,
  "tid": "0cea0dbaa7d811edbe05a63cfb33a057"
}

This is from D16 i have two of then one is D12 and one is D16

**Comment by make-all** [comment]
There is still a lot of information needed, which you can only find from experimentation, either adding the device to HA as whatever non-matching device is offered then downloading diagnostics, changing settings from the control panel or Tuya app and downloading diagnostics again until you capture all the possibilities, or using some other tool like tuyacli (nodejs based) or tinytuya (Python based) to monitor the local dps (this will be faster but requires setting up a development environment and familiarising with one of those tools).

Here is the information we have:

| DP | Values (from HA log) | Function (from iot portal) | Values (from HA portal) | Status |
|---|---|---|---|
| 1 | True | Power | boolean | OK |
| 2 | '0' | Mode | enum: ('0': ?, ...) | Need option mapping |
| 3 | 53 | Humidity | int | OK |
| 4 | 50 | Set Humidity | int | Need range |
| 5 | False | Anion | boolean | OK |
| 6 | '1' | Wind Speed | enum: ('1': ?, ...) | Need option mapping |
| 7 | False | Child Lock | boolean | OK|
| 8 | - | Swing | boolean | OK |
| 11 | 0 | Fault | bitfield | Value for tank full would be useful |
| 12 | '0' | Countdown |  enum: ('0': off, ...?) |
| 13 | 0 | Remaining Time | int | units s, or min? |
| 101| False | Inside Drying | boolean | OK |
| 102 | - | Water Pump | ? | ignore? |

**Comment by make-all** [comment]
I think with PR #386, enough information is available now.

**Comment by Liionboy** [comment]
> There is still a lot of information needed, which you can only find from experimentation, either adding the device to HA as whatever non-matching device is offered then downloading diagnostics, changing settings from the control panel or Tuya app and downloading diagnostics again until you capture all the possibilities, or using some other tool like tuyacli (nodejs based) or tinytuya (Python based) to monitor the local dps (this will be faster but requires setting up a development environment and familiarising with one of those tools).
> 
> Here is the information we have:
> 
> DP	Values (from HA log)	Function (from iot portal)	Values (from HA portal)	Status
> 1	True	Power	boolean	OK
> 2	'0'	Mode	enum: ('0': Auto, '1': Continuous)	
> 3	53	Humidity	int	OK
> 4	50	Set Humidity	int	30%;35%;40%;45%;50%;55%;60%;65%;70%;75%;80% range
> 5	False	Anion	boolean	OK
> 6	'1'	Wind Speed	enum: ('0': High, '1': Low)	
> 7	False	Child Lock	boolean	OK
> 8		Swing	boolean	OK
> 11	0	Fault	bitfield	('8':Ok, '0': Full )
> 12	'0'	Countdown	enum: ('0': off, 1 hour to 24 hour set time si 60 min)	
![image](https://user-images.githubusercontent.com/87735636/218329666-b4098e75-c90d-49d6-b2b0-98a33d478f1e.png)

> 13	0	Remaining Time	int	units  min
> 101	False	Inside Drying	boolean	OK
> 102		Water Pump	?	ignore?


I hope will help you this settings
