### ISSUE TITLE
missing protocol versions

### ISSUE THREAD

**Issue by Santanachia** [make-all/tuya-local#332]
[documentation](https://github.com/make-all/tuya-local#protocol_version) says I have a choice of `3.1|3.2|3.3|3.4`, unfortunately the only choice i have is 3.1 and 3.3

![image](https://user-images.githubusercontent.com/4628507/210220104-0c36d81f-ed8f-4e4f-b450-2fb6208803f8.png)

**Comment by make-all** [comment]
This is not the configuration dialog for this integration.

**Comment by Santanachia** [comment]
it's probably because I already have [LocalTuya](https://github.com/rospogrigio/localtuya/) integration. What can I do to make it work at the same time? In the `manifest.json` file there are different `domain` and `name`, shouldn't this be treated as a different integration?
![image](https://user-images.githubusercontent.com/4628507/210227460-341d97e2-fd42-4eed-882f-098488aaf6b7.png)
