### ISSUE TITLE
Device never connects

### ISSUE THREAD

**Issue by jjlauer** [make-all/tuya-local#339]
Tried out the integration today and I'm unable to ever get any of my devices to connect or be added.  Using tinytua, its able to scan my network and easily find all my devices.  I'm very familiar with the Tuya cloud, local keys, etc. and I've got a complete list of device ids, local keys, and their associated IP address.

The integration just keeps "spinning" when I try to add any of them, until it eventually times out after a long, long time.  I turned on debug logging for home assistant, but the logs don't tell me much of anything.  The only thing I see is that it tries to refresh the device state, then spits out something an "retrying after exception 'dps'".

Looking for assistance -- is there a better way to debug this?  I have no idea what the integration is actually trying to do under the hood, but tinytua works great for me locally with my devices, so I'm stumped why this integration doesn't seem to connect.

The only odd thing about my setup is all my tuya devices on their own subnet.  I can easily ping the devices and get to that subnet from home assistant, but again I'm not entirely sure what this integration is trying to do when it connects.

**Comment by make-all** [comment]
Does tinytuya work great for you from the same device or VM that is running Home Assistant, or is it from a different PC?

It looks like a networking routing issue to me, with the long delay being a timeout trying to connect to the given IP address.

**Comment by jjlauer** [comment]
tinytua works great from a different device that's setup on the same network as home assistant.  On my linux workstation (not homeassistant), I have my physical ethernet hooked up to my lan network 10.16.0.x.  If i run tinytua scan on this machine, it will obviously only scan 10.16.0.x.  If i enable wifi on this machine and hook up my machine to my IoT wifi net 10.16.4.x, the tinytua is able to successfully scan both networks and it returns the list of my tuya devices.

However, even if i turn off wifi, once i know the IP addresses of my tuya devices, my firewall allows all traffic from 10.16.0.x <-> 10.16.4.x networks and I can communicate with my tuya devices.

If i open up the terminal on homeassistant, I have tried a few different configurations.  Home assistant has a physical ethernet connection to 10.16.0.x.  I can ping all my tuya devices successfully this way.  But this integration won't connect to any of them.  I have also tried enabling the wifi to connect to my IoT wifi network (10.16.4.x) as a 2nd active ethernet connection (similar to what i did on my worksation example above), and that also fails to connect.

I'm happy to try and figure out what's going on further, I'm just not sure how I turn on ALL debugging output.  When a device is being added, does it try to do a scan underneath similiar to tinytua's "scan" or does it skip that and try to establish a tcp/ip connection directly with the device?

**Comment by make-all** [comment]
This integration does not use the scan feature of tinytuya, it just makes connections using the details you supply in the first config dialog when adding a device.  In the case of "auto" protocol setting, it will try in the order of 3.3, 3.1, 3.2, 3.4.

**Comment by jjlauer** [comment]
Any idea what "retrying after exception 'dps'" could mean?  Is it possible my GE Jasco switches simply aren't supported and I should focus on that?  Tinytua's simple "switch" device works on them, but maybe that's actually the issue rather than network connectivity?

**Comment by make-all** [comment]
I think you will get that exception when the decryption fails, either due to wrong protocol version, or local key.  The 'dps' will be the message from the exception, probably it would help to log the exception type as well.  Or maybe the latest version already logs more useful info.

**Comment by make-all** [comment]
Are the switches connected via a hub, or directly on WiFi?

**Comment by jjlauer** [comment]
They are all connected directly on wifi.  I just did a tinytuya status command, with debugging turned on.  Here's what it spit out:

```
DEBUG:TinyTuya [1.9.1]

DEBUG:status() entry (dev_type is default)
DEBUG:building command 10 payload=b'{"gwId":"REDACTED","devId":"REDACTED","uid":"REDACTED","t":"1673710269"}'
DEBUG:sending payload
DEBUG:payload encrypted=b'000055aa000000010000000a00000088787652a23659a57a845d5e622dfb50cd40334be5e67f07c0230d39b288eb3fd1845875d0a53ee4c0affae879429caa8c91f1f2b3134f9beff36c0a8591b19eadc064192adcd0e95ecf4d745f9b8cb30340334be5e67f07c0230d39b288eb3fd1a4e98a0a90993aead494fb8d96800f7ab3608b75498746ea92f7907d53c92e2b68cc8bc00000aa55'
DEBUG:received data=b'000055aa000000010000000a0000008c00000000614a890f37bdc660c0097206a8c29124dfae684d966c90296a572ff49abe21a7989159d2db7111b2b67696f0468165a74b4ab689b2068a0c4b388533e549b79f93061d73c8d6ced4c3d3885ef23d5a044d612c60637e10babbf68cf8653e0d6d684c9299faa10f7afb832b2b5eadd773b095612cce1761425fee8ed441bfdfc80ea3fdb50000aa55'
DEBUG:received message=TuyaMessage(seqno=1, cmd=10, retcode=0, payload=b'aJ\x89\x0f7\xbd\xc6`\xc0\tr\x06\xa8\xc2\x91$\xdf\xaehM\x96l\x90)jW/\xf4\x9a\xbe!\xa7\x98\x91Y\xd2\xdbq\x11\xb2\xb6v\x96\xf0F\x81e\xa7KJ\xb6\x89\xb2\x06\x8a\x0cK8\x853\xe5I\xb7\x9f\x93\x06\x1ds\xc8\xd6\xce\xd4\xc3\xd3\x88^\xf2=Z\x04Ma,`c~\x10\xba\xbb\xf6\x8c\xf8e>\rmhL\x92\x99\xfa\xa1\x0fz\xfb\x83++^\xad\xd7s\xb0\x95a,\xce\x17aB_\xee\x8e\xd4A\xbf\xdf\xc8', crc=245628341, crc_good=True)
DEBUG:raw unpacked message = TuyaMessage(seqno=1, cmd=10, retcode=0, payload=b'aJ\x89\x0f7\xbd\xc6`\xc0\tr\x06\xa8\xc2\x91$\xdf\xaehM\x96l\x90)jW/\xf4\x9a\xbe!\xa7\x98\x91Y\xd2\xdbq\x11\xb2\xb6v\x96\xf0F\x81e\xa7KJ\xb6\x89\xb2\x06\x8a\x0cK8\x853\xe5I\xb7\x9f\x93\x06\x1ds\xc8\xd6\xce\xd4\xc3\xd3\x88^\xf2=Z\x04Ma,`c~\x10\xba\xbb\xf6\x8c\xf8e>\rmhL\x92\x99\xfa\xa1\x0fz\xfb\x83++^\xad\xd7s\xb0\x95a,\xce\x17aB_\xee\x8e\xd4A\xbf\xdf\xc8', crc=245628341, crc_good=True)
DEBUG:decode payload=b'aJ\x89\x0f7\xbd\xc6`\xc0\tr\x06\xa8\xc2\x91$\xdf\xaehM\x96l\x90)jW/\xf4\x9a\xbe!\xa7\x98\x91Y\xd2\xdbq\x11\xb2\xb6v\x96\xf0F\x81e\xa7KJ\xb6\x89\xb2\x06\x8a\x0cK8\x853\xe5I\xb7\x9f\x93\x06\x1ds\xc8\xd6\xce\xd4\xc3\xd3\x88^\xf2=Z\x04Ma,`c~\x10\xba\xbb\xf6\x8c\xf8e>\rmhL\x92\x99\xfa\xa1\x0fz\xfb\x83++^\xad\xd7s\xb0\x95a,\xce\x17aB_\xee\x8e\xd4A\xbf\xdf\xc8'
DEBUG:decrypting=b'aJ\x89\x0f7\xbd\xc6`\xc0\tr\x06\xa8\xc2\x91$\xdf\xaehM\x96l\x90)jW/\xf4\x9a\xbe!\xa7\x98\x91Y\xd2\xdbq\x11\xb2\xb6v\x96\xf0F\x81e\xa7KJ\xb6\x89\xb2\x06\x8a\x0cK8\x853\xe5I\xb7\x9f\x93\x06\x1ds\xc8\xd6\xce\xd4\xc3\xd3\x88^\xf2=Z\x04Ma,`c~\x10\xba\xbb\xf6\x8c\xf8e>\rmhL\x92\x99\xfa\xa1\x0fz\xfb\x83++^\xad\xd7s\xb0\x95a,\xce\x17aB_\xee\x8e\xd4A\xbf\xdf\xc8'
DEBUG:decrypted 3.x payload='{"dps":{"1":false,"2":1000,"3":10,"4":"led","5":1000,"6":0,"14":"memory","21":"relay","106":"dimmer","107":"3way_switch"}}'
DEBUG:payload type = <class 'str'>
DEBUG:decoded results='{"dps":{"1":false,"2":1000,"3":10,"4":"led","5":1000,"6":0,"14":"memory","21":"relay","106":"dimmer","107":"3way_switch"}}'
DEBUG:status() received data={'dps': {'1': False, '2': 1000, '3': 10, '4': 'led', '5': 1000, '6': 0, '14': 'memory', '21': 'relay', '106': 'dimmer', '107': '3way_switch'}}
DEBUG:bulb type set to A
DEBUG:status() entry (dev_type is default)
DEBUG:building command 10 payload=b'{"gwId":"ebabd7c06e79a505a7wyqx","devId":"ebabd7c06e79a505a7wyqx","uid":"ebabd7c06e79a505a7wyqx","t":"1673710270"}'
DEBUG:sending payload
DEBUG:payload encrypted=b'000055aa000000020000000a00000088787652a23659a57a845d5e622dfb50cd40334be5e67f07c0230d39b288eb3fd1845875d0a53ee4c0affae879429caa8c91f1f2b3134f9beff36c0a8591b19eadc064192adcd0e95ecf4d745f9b8cb30340334be5e67f07c0230d39b288eb3fd1a797378d16e43a1680951b7378329bf7b3608b75498746ea92f7907d53c92e2be7f933df0000aa55'
DEBUG:received data=b'000055aa000000020000000a0000008c00000000614a890f37bdc660c0097206a8c29124dfae684d966c90296a572ff49abe21a7989159d2db7111b2b67696f0468165a74b4ab689b2068a0c4b388533e549b79f93061d73c8d6ced4c3d3885ef23d5a044d612c60637e10babbf68cf8653e0d6d684c9299faa10f7afb832b2b5eadd773b095612cce1761425fee8ed441bfdfc8d4752d680000aa55'
DEBUG:received message=TuyaMessage(seqno=2, cmd=10, retcode=0, payload=b'aJ\x89\x0f7\xbd\xc6`\xc0\tr\x06\xa8\xc2\x91$\xdf\xaehM\x96l\x90)jW/\xf4\x9a\xbe!\xa7\x98\x91Y\xd2\xdbq\x11\xb2\xb6v\x96\xf0F\x81e\xa7KJ\xb6\x89\xb2\x06\x8a\x0cK8\x853\xe5I\xb7\x9f\x93\x06\x1ds\xc8\xd6\xce\xd4\xc3\xd3\x88^\xf2=Z\x04Ma,`c~\x10\xba\xbb\xf6\x8c\xf8e>\rmhL\x92\x99\xfa\xa1\x0fz\xfb\x83++^\xad\xd7s\xb0\x95a,\xce\x17aB_\xee\x8e\xd4A\xbf\xdf\xc8', crc=3564449128, crc_good=True)
DEBUG:raw unpacked message = TuyaMessage(seqno=2, cmd=10, retcode=0, payload=b'aJ\x89\x0f7\xbd\xc6`\xc0\tr\x06\xa8\xc2\x91$\xdf\xaehM\x96l\x90)jW/\xf4\x9a\xbe!\xa7\x98\x91Y\xd2\xdbq\x11\xb2\xb6v\x96\xf0F\x81e\xa7KJ\xb6\x89\xb2\x06\x8a\x0cK8\x853\xe5I\xb7\x9f\x93\x06\x1ds\xc8\xd6\xce\xd4\xc3\xd3\x88^\xf2=Z\x04Ma,`c~\x10\xba\xbb\xf6\x8c\xf8e>\rmhL\x92\x99\xfa\xa1\x0fz\xfb\x83++^\xad\xd7s\xb0\x95a,\xce\x17aB_\xee\x8e\xd4A\xbf\xdf\xc8', crc=3564449128, crc_good=True)
DEBUG:decode payload=b'aJ\x89\x0f7\xbd\xc6`\xc0\tr\x06\xa8\xc2\x91$\xdf\xaehM\x96l\x90)jW/\xf4\x9a\xbe!\xa7\x98\x91Y\xd2\xdbq\x11\xb2\xb6v\x96\xf0F\x81e\xa7KJ\xb6\x89\xb2\x06\x8a\x0cK8\x853\xe5I\xb7\x9f\x93\x06\x1ds\xc8\xd6\xce\xd4\xc3\xd3\x88^\xf2=Z\x04Ma,`c~\x10\xba\xbb\xf6\x8c\xf8e>\rmhL\x92\x99\xfa\xa1\x0fz\xfb\x83++^\xad\xd7s\xb0\x95a,\xce\x17aB_\xee\x8e\xd4A\xbf\xdf\xc8'
DEBUG:decrypting=b'aJ\x89\x0f7\xbd\xc6`\xc0\tr\x06\xa8\xc2\x91$\xdf\xaehM\x96l\x90)jW/\xf4\x9a\xbe!\xa7\x98\x91Y\xd2\xdbq\x11\xb2\xb6v\x96\xf0F\x81e\xa7KJ\xb6\x89\xb2\x06\x8a\x0cK8\x853\xe5I\xb7\x9f\x93\x06\x1ds\xc8\xd6\xce\xd4\xc3\xd3\x88^\xf2=Z\x04Ma,`c~\x10\xba\xbb\xf6\x8c\xf8e>\rmhL\x92\x99\xfa\xa1\x0fz\xfb\x83++^\xad\xd7s\xb0\x95a,\xce\x17aB_\xee\x8e\xd4A\xbf\xdf\xc8'
DEBUG:decrypted 3.x payload='{"dps":{"1":false,"2":1000,"3":10,"4":"led","5":1000,"6":0,"14":"memory","21":"relay","106":"dimmer","107":"3way_switch"}}'
DEBUG:payload type = <class 'str'>
DEBUG:decoded results='{"dps":{"1":false,"2":1000,"3":10,"4":"led","5":1000,"6":0,"14":"memory","21":"relay","106":"dimmer","107":"3way_switch"}}'
DEBUG:status() received data={'dps': {'1': False, '2': 1000, '3': 10, '4': 'led', '5': 1000, '6': 0, '14': 'memory', '21': 'relay', '106': 'dimmer', '107': '3way_switch'}}
```

**Comment by make-all** [comment]
You could try setting the following in your home assistant configuration.yaml to compare the same status request when triggered from this integration:

logger:
  default: warning
  logs:
     tinytuya: debug

**Comment by jjlauer** [comment]
Boom! Turning on tinytua debugging immediately pinpointed the issue.  It really was a socket connect issue.  For some reason having home assistant on both the physical lan, plus wifi caused the connection failure.  I disabled wifi and it immediately connected to the device.

These are dimmer switches -- I can give it a try adding official support for them, but they work as on/off switches at least now!

**Comment by make-all** [comment]
I am glad the connection issue is solved. Please open a new issue with the device details when you have collected enough information to configure it as a light with dimmer.
