### ISSUE TITLE
Tuya Local is causing server to crash.

### ISSUE THREAD

**Issue by samuelfurman** [make-all/tuya-local#344]
When this integration fully loads up, the CPU % slowly begins to rise, as more and more smart devices establish a connection with the HA server, CPU keeps rising until 100%. And eventually HAN crashes and then once it reboots it behaves normally for 5-10 mins and then once again CPU spikes and it crashes. []()

**Comment by samuelfurman** [comment]
I'm running HAOS on an 11th generation Intel Nuc with 32GB RAM, and a 10GBps network link.

**Comment by make-all** [comment]
I'm running on a rPi4 with 1GB RAM, and not seeing such issues.  How many devices do you have that your server is filling up 32GB of RAM and crashing within 10 minutes?  Is there anything unusual about your network configuration that might be causing reconnections to pile up without closing properly?

**Comment by samuelfurman** [comment]
> I'm running on a rPi4 with 1GB RAM, and not seeing such issues.  How many devices do you have that your server is filling up 32GB of RAM and crashing within 10 minutes?  Is there anything unusual about your network configuration that might be causing reconnections to pile up without closing properly?

Nothing unusual about the network, around 80 TUYA recessed RGBWC smart WiFi lights.

**Comment by make-all** [comment]
Please check the log for messages from tuya-local.
