### ISSUE TITLE
goldair_gpcv_heater Doesn’t work since last actualization.

### ISSUE THREAD

**Issue by Carlos-HA** [make-all/tuya-local#346]
Hello, I’ve got 4 goldair_gpcv_heater that I was switch on/off depending on my solar energy instalation. Yesterday I updated local tuya and now I can’t operate any of four climate.

I don’t know if it could be any problem I created by updating local tuya.

Thanks for your support,
Carlos.

**Comment by make-all** [comment]
Please check the log for log messages.  If you have messages from localtuya, you are in the wrong place.  If they are in fact from tuya-local, then please post them here.

**Comment by Carlos-HA** [comment]
Hello, sorry is tuya-local.

Thanks.
Carlos.

Este error se originó a partir de una integración personalizada.

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:152 
Integration: Tuya Local (documentation, issues) 
First occurred: 16 de enero de 2023, 17:01:49 (1457477 occurrences) 
Last logged: 08:02:09

radiador planta alta Goldair GPCV Heater error reading: Unexpected Payload from Device
radiador planta baja Goldair GPCV Heater error reading: Unexpected Payload from Device
radiador entrada Goldair GPCV Heater error reading: Unexpected Payload from Device
radiador baño Marga Goldair GPCV Heater error reading: Unexpected Payload from Device

**Comment by make-all** [comment]
Are your devices all set to "auto" protocol?  I suspect what is happening is that the receive connection is made before the protocol is determined, and is not rotating though the protocol versions because of the different error handling than the previous polled connection.  Does it help to explicitly set the protocol as appropriate (my guess is 3.1, since 3.3 is the first it would try)?

**Comment by Carlos-HA** [comment]
I’ve tried by setting 3.1 protocol but It doesn’t work for any of four climate devices. I get this message when trying.
“Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect.”

(I’ve got two other devices than haven’t been afected on actualization ( beca bht-6000 and kogan glass panel )).

Thnak you.

**Comment by make-all** [comment]
3.1 was just a suggestion.  If you try 3.3 or one of the other options, do any of them work? (I think some of them may cause the dialog to hang, in which case you may need to close the browser window, open another and go back in to change to something else).

**Comment by Carlos-HA** [comment]
I’ve tried every protocol number for every climate and they all send the same message:  “Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect.”

(I’ve tried also with beca bht-6000 and kogan glass panel but they both send the same message “Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect.”… but they still are working.

Thanks.

**Comment by make-all** [comment]
It seems that once a persistent connection is started, the protocol cannot be changed.

I have released 2023.1.2 based on my investigation into how my protocol version 3.1 device is working when set to "auto" protocol detection.

**Comment by Carlos-HA** [comment]
I’ve installed 2023.1.2 release and it works again. Thanks!
