### ISSUE TITLE
Thermostat Beca BHT-6000

### ISSUE THREAD

**Issue by gabrymed** [make-all/tuya-local#347]
After last Tuya Local update, if i call service to change temperature target i have this error:
Termostato BHT-6000 error reading: Unexpected Payload from Device
I read all the values correctly but i can't change temperature.
What's the problem?

**Comment by Bubi504** [comment]
Same bug here:
Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:152
Integration: Tuya Local ([documentation](https://github.com/make-all/tuya-local), [issues](https://github.com/make-all/tuya-local/issues))
First occurred: 07:14:32 (8222 occurrences)
Last logged: 07:24:40

Háló termosztát error reading: Unexpected Payload from Device
Nappali termosztát error reading: Unexpected Payload from Device

**Comment by make-all** [comment]
Is your device set to use "auto" protocol?  Does it work if you set it to the appropriate protocol version (maybe 3.1, since 3.3 is default)

**Comment by Bubi504** [comment]
Cannot change the protocol version, it's just floods ha's log with the error above.

**Comment by lucaxxaa** [comment]
I have two bht-002 with two different firmware. One is right other after last tuya local update, not speak with ha

**Comment by make-all** [comment]
There appears to be an issue with 3.1 protocol devices that were set to auto when the update was done.  I have one 3.1 device, but I am unable to change the protocol to auto due to the same bug.

**Comment by make-all** [comment]
I have released 2023.1.2 based on my investigation into how my protocol version 3.1 device is working when set to "auto" protocol detection.

**Comment by gabrymed** [comment]
With  release 2023.1.2 , my BHT-6000 it started working fine again.
Thanks Jason for your support
