### ISSUE TITLE
"permission deny" when querying the api for the local_key

### ISSUE THREAD

**Issue by bolisaf** [make-all/tuya-local#348]
followed the instructions to get the local_key of my Tuya Smart switch, but I keep on getting a "permission deny" returned by the API:

{
  "code": 1106,
  "msg": "permission deny",
  "success": false,
  "t": 1673905416350,
  "tid": "d4c70c4695e611edb15f72681cb52e7c"
}

I found this in the Tuya help, but I must admit that I don't understand half of what it says:
https://support.tuya.com/en/help/_detail/K9g77zlgd4xmb
https://support.tuya.com/en/help/_detail/K9kui9wvuwc93

**Comment by make-all** [comment]
This integration does not contain any cloud API features.  I think you must be using something else here.

**Comment by bolisaf** [comment]
from your instructions:

Finding your device ID and local key

The easiest way to find your local key is with the Tuya Developer portal. If you have previously configured the built in Tuya cloud integration, or localtuya, you probably already have a developer account with the Tuya app linked. Note that you need to use Tuya's own branded "Tuya Smart" or "SmartLife" apps to access devices through the developer portal. For most devices, your device will work identically with those apps as it does with your manufacturer's branded app, but there are a few devices where that is not the case and you will need to decide whether you are willing to potentially lose access to some functionality (such as mapping for some vacuum cleaners).

If you log on to your Developer Portal account, under Cloud you should be able to get a list of your devices, which contains the "Device ID". If you don't see them, check your server is set correctly at the top of the page. Make a note of the Device IDs for all your devices, then select Cloud on the side bar again and go to the API Explorer.

**Under General Device Capabilities / General Devices Management, select the "Get Device Information" function, and enter your Device ID. In the results you should see your local_key.**
