### ISSUE TITLE
Request for support new device (humidifier Kyvol EA200)

### ISSUE THREAD

**Issue by Pokemowka25** [make-all/tuya-local#354]
Hello!
Thanks for very good project!
Could you add new humidifier to support?

Device: Himidifier
Model: Kyvol EA200(Wi-Fi) 

Device Specification:
{
  "result": {
    "category": "jsq",
    "functions": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "level",
        "type": "Enum",
        "values": "{\"range\":[\"level_1\",\"level_2\",\"level_3\",\"level_4\",\"level_5\",\"level_6\",\"level_7\",\"level_8\",\"level_9\",\"level_10\",\"level_11\",\"level_12\",\"level_13\",\"level_14\",\"level_15\",\"level_16\",\"level_17\",\"level_18\",\"level_19\",\"level_20\"]}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fault",
        "type": "Bitmap",
        "values": "{\"label\":[\"lack_water\"],\"maxlen\":1}"
      },
      {
        "code": "level",
        "type": "Enum",
        "values": "{\"range\":[\"level_1\",\"level_2\",\"level_3\",\"level_4\",\"level_5\",\"level_6\",\"level_7\",\"level_8\",\"level_9\",\"level_10\",\"level_11\",\"level_12\",\"level_13\",\"level_14\",\"level_15\",\"level_16\",\"level_17\",\"level_18\",\"level_19\",\"level_20\"]}"
      }
    ]
  },

**Comment by make-all** [comment]
Unfortunately there is not enough detail in the info above to add local protocol support.  Where you got that info from, there are some other functions which return slightly different info. One near the end of the list (last function in second-last subcategory in last group of functions) is the one that has the info we need (see the README.md for details).  And since the API Explorer is only showing two dps which seem to be defining just a fan, the local dps list from the HA log message you get when trying to add the unsupported device will also confirm whether other info is potentially available to be able to simulate a humidifier device as well as a fan.

**Comment by Pokemowka25** [comment]
I got this information from tuya api explorer.
This device is ultrasonic humidifier. Like [this](https://www.amazon.com/LEVOIT-Humidifiers-Ultrasonic-Classic-200S/dp/B08KXW1KRJ/ref=sr_1_1?crid=2HGEZIHNHCU0A&keywords=ultrasonic+humidifier+wifi&qid=1674297178&sprefix=ultrasonic+humidifier+wifi%2Caps%2C182&sr=8-1)
**Get device specification attribute:**
{
  "result": {
    "category": "jsq",
    "functions": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "level",
        "dp_id": 23,
        "type": "Enum",
        "values": "{\"range\":[\"level_1\",\"level_2\",\"level_3\",\"level_4\",\"level_5\",\"level_6\",\"level_7\",\"level_8\",\"level_9\",\"level_10\",\"level_11\",\"level_12\",\"level_13\",\"level_14\",\"level_15\",\"level_16\",\"level_17\",\"level_18\",\"level_19\",\"level_20\"]}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fault",
        "dp_id": 22,
        "type": "Bitmap",
        "values": "{\"label\":[\"lack_water\"],\"maxlen\":1}"
      },
      {
        "code": "level",
        "dp_id": 23,
        "type": "Enum",
        "values": "{\"range\":[\"level_1\",\"level_2\",\"level_3\",\"level_4\",\"level_5\",\"level_6\",\"level_7\",\"level_8\",\"level_9\",\"level_10\",\"level_11\",\"level_12\",\"level_13\",\"level_14\",\"level_15\",\"level_16\",\"level_17\",\"level_18\",\"level_19\",\"level_20\"]}"
      }
    ]
  },

As i understand, DP 1 is On/Off, DP 23 is Spray speed, DP 22 is Low water message
