### ISSUE TITLE
Request for support new device (thermostat Salcar T9W)

### ISSUE THREAD

**Issue by TheExenth** [make-all/tuya-local#359]
Hi i was wondering if this is enough information to add support for this device.

Device Link: [Salcar T9W](https://www.amazon.de/SALCAR-Heizungsthermostat-Heizk%C3%B6rperthermostat-Programmierbar-Wandthermostat/dp/B0BD7BV6FH)

Tuya IoT API Explorer Info:
```
{
  "result": {
    "category": "wk",
    "functions": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "dp_id": 2,
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"manual\"]}"
      },
      {
        "code": "frost",
        "dp_id": 10,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "dp_id": 16,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":50,\"max\":10000,\"scale\":1,\"step\":5}"
      },
      {
        "code": "upper_temp",
        "dp_id": 19,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":50,\"max\":10000,\"scale\":1,\"step\":10}"
      },
      {
        "code": "temp_unit_convert",
        "dp_id": 23,
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "lower_temp",
        "dp_id": 26,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":50,\"max\":10000,\"scale\":1,\"step\":10}"
      },
      {
        "code": "work_days",
        "dp_id": 31,
        "type": "Enum",
        "values": "{\"range\":[\"5_2\",\"6_1\",\"7\"]}"
      },
      {
        "code": "child_lock",
        "dp_id": 40,
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "dp_id": 2,
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"manual\"]}"
      },
      {
        "code": "frost",
        "dp_id": 10,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "dp_id": 16,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":50,\"max\":10000,\"scale\":1,\"step\":5}"
      },
      {
        "code": "upper_temp",
        "dp_id": 19,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":50,\"max\":10000,\"scale\":1,\"step\":10}"
      },
      {
        "code": "temp_unit_convert",
        "dp_id": 23,
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "temp_current",
        "dp_id": 24,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-300,\"max\":10000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "lower_temp",
        "dp_id": 26,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":50,\"max\":10000,\"scale\":1,\"step\":10}"
      },
      {
        "code": "work_days",
        "dp_id": 31,
        "type": "Enum",
        "values": "{\"range\":[\"5_2\",\"6_1\",\"7\"]}"
      },
      {
        "code": "valve_state",
        "dp_id": 36,
        "type": "Enum",
        "values": "{\"range\":[\"close\",\"open\"]}"
      },
      {
        "code": "child_lock",
        "dp_id": 40,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fault",
        "dp_id": 45,
        "type": "Bitmap",
        "values": "{\"label\":[\"e1\",\"e2\",\"e3\"]}"
      }
    ]
  },
  "success": true,
  "t": 1674667333975,
  "tid": "cf105c149cd411ed89e112b09600735b"
}
```

**Comment by TheExenth** [comment]
I have also found this device which looks identical:

[Tellur TSH02](https://www.tellur.com/product/smart-wifi-ambient-thermostat-tsh02/) 

[User Manual](https://www.tellur.com/wp-content/uploads/2022/11/TLl331431-EN.pdf)

**Comment by TheExenth** [comment]
Thanks for the quick inclusion. I updated to the newest version via HACS, but i cant add the device. 

I always get the Error "Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect."

In the Home Assistant logs it just says: "2023-01-26 15:59:00.055 ERROR (MainThread) [custom_components.tuya_local.device] Failed to refresh device state for Test."

**Comment by make-all** [comment]
Usual reasons for that error:
1. Device was re-paired with the mobile app, causing the local key to change.
2. Device does not have a static IP allocated by the router, and is no longer at the IP configured.
3. HA is connected to 2 networks, and is confused about how to route to your device.
4. Mobile app is open, and blocking connections.
5. Device is using protocol 3.2 or 3.4, and may not be working well with auto protocol detection.
6. Device is using protocol 3.5, which is not yet supported.

**Comment by TheExenth** [comment]
Thanks for the tipps, at this point i think it may be the protocol beeing v3.5
Since i checked all the other points multiple times.

Any plans when we can expect support? I saw that tinytuya recently started supporting it.

**Comment by TheExenth** [comment]
Just a quick Update. I ran tinytuya myself to see what it would find and indeed this devices Protocol Version is 3.5. See [Screenshot](https://i.imgur.com/nkCOwsJ.jpeg)

**Comment by make-all** [comment]
Closnig, as the support for both this device and protocol version 3.5 were already released in the previous release.

**Comment by make-all** [comment]
A correction to the config based on my tests for #460.  This may have been preventing the device from initialising previously (though the log messages were not showing it getting that far).

**Comment by kellerman** [comment]
Hello. I recently purchased T9W thermostat and nothing is broadcasting over UDP. The tinytuya script mentioned in the post above also doesn't find any devices.
When adding the device to Tuya app, I get some UDP broadcasts and some weird BOOTP traffic, not locally, but to tuya's servers. After that, no broadcast at all.
Maybe the later devices somehow doesn't broadcast anymore? I could only ICMP ping the device, but couldn't see any open ports.

**Comment by make-all** [comment]
The different protocol versions broadcast on different ports.  The latest tinytuya library should support latest protocols as well.
Some devices also do not broadcast once they are connected locally.
None of this is relevant to this integration though, as we do not use the broadcasts currently.

**Comment by kellerman** [comment]
> The different protocol versions broadcast on different ports.  The latest tinytuya library should support latest protocols as well.
> Some devices also do not broadcast once they are connected locally.
> None of this is relevant to this integration though, as we do not use the broadcasts currently.

Thanks for reply. I might try using a different AP for WiFi connection and then see if there is any broadcast. I could not see any broadcast from my thermostats IP address on any ports.
Also I can't seem to add the thermostat by entering all the data manually. Maybe there is some newer firmware, that is just incompatible?

**Comment by kellerman** [comment]
Here is my device info from Tuya developer portal.
`{
  "result": [
    {
      "active_time": 1692484071,
      "category": "wk",
      "create_time": 1692484071,
      "custom_name": "",
      "icon": "smart/icon/ay1547209623516pqlXf/7a9d8dfea8b9b93aa706696ef9549e01.png",
      "id": "bffc7a40ae1b2eb4aabyms",
      "ip": "212.93.115.xxx",
      "is_online": true,
      "lat": "56.xx",
      "local_key": "&7S#*0XK=349[mbs",
      "lon": "25.xx",
      "model": "T9W 2.0, R9BW 2.0",
      "name": "Floor Heating",
      "product_id": "eaacu1av8nz9qdva",
      "product_name": "采暖温控v2",
      "sub": false,
      "time_zone": "+03:00",
      "update_time": 1692484073,
      "uuid": "f8dcec28886dac9d"
    }
  ],
  "success": true,
  "t": 1692485265757,
  "tid": "6a0490e33ee211ee9a70760d0d3c40d3"
}
`
Maybe this 2.0 version is new revision? I'm willing to help if this is a device yet to support.

**Comment by jonathh21** [comment]
I'm here, after searching for my device 'eaacu1av8nz9qdva'.

Although this device is 'supported' it doesn't work well.

It has duplicated HVAC modes and quickly and irrecoverably gets out of sync with the device when you toggle between off and on.

Telling you it is on when it is off and vice versa.

Also the upper temperature is a balmy 500 degrees C which is a little warm for me, I've set a maximum of 25 in tuya but this is never reflected.

**Comment by make-all** [comment]
I suspect you are using a different integration than this one. The upper temperature advertised by the device itself is 1000 degrees (C or F depending on device setting), which is reflected in this config. So an upper temperature of 500 must be coming from somewhere else.  If the device is reporting the maximum set by the Tuya app, it is used by this config, but if the device is not reporting it (there are no logs above), there will be no way to use it.

**Comment by jonathh21** [comment]
Ah yes, sorry.

**Comment by divadiow** [comment]
curious to know if anyone ever dumped the Tuya factory firmware from this device
