### ISSUE TITLE
Following Update to last release 0.9.0 AC Unavailable

### ISSUE THREAD

**Issue by Fannangir** [make-all/tuya-local#36]
Hi,
I have just updated to the last revision (0.9.0) from revision 0.8.9, my AC became unavailable.
My AC model is Tadiran Wind 65/3P.
Is there any change that might cause the issue?
Is there any log that I can provide?

Thanks.

**Comment by make-all** [comment]
The config file was renamed from tadiran_heatpump.yaml to tadiran_wind_heatpump.yaml, but there should be a link in there so that previously configurations will continue working.

Maybe there is an issue with that. Are there any messages in the log?

**Comment by Fannangir** [comment]
I can’t see any message in the log, like everything is OK.
Should I enable some special logging?

**Comment by make-all** [comment]
Have a look in Developer tools at what entities you have available. The config renaming may have had a side effect of making it appear to Home Assistant to be a different device, so it created a new one alongside your existing entities.

**Comment by Fannangir** [comment]
It didn’t create a new entity.
Got it to work.
I had to re-configure the integration.
Simply pressed configure, it says the integration is being installed…
It has detected the key and the IP automatically (as was previously entered).
The entity is working correctly (with the same name).

I guess some change has made it to require a reconfigure.

**Comment by make-all** [comment]
Good news that it works after a reconfigure, but I can't find why that might be. I'll keep this in mind if anyone else reports the same problem.
