### ISSUE TITLE
Support for new device doorcam

### ISSUE THREAD

**Issue by x5500** [make-all/tuya-local#371]
Hello!
I've tried to add control new device (Doorcam/Intercom) and found out that protocol is not supported, but Local-Tuya using tytuya works correct.
[debug_log.txt](https://github.com/make-all/tuya-local/files/10568176/debug_log.txt)

2023-02-02 12:45:32.433 DEBUG (MainThread) [custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.168.77', 'gwId': 'bf71b225dc6dd70835wlbt', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': 'h3bhzu9m0ig80rdu', 'version': '3.3', 'token': True}

The difference i've noticed between this device and curtain (now supported by tuya-local) is using "'token" in protocol.

category: "sp"
category_name: "Smart Camera"
icon: "smart/icon/ay15507223992875xh7c/8c8b547693dedc057cf1dd9d3237f58c.png"
model: "863XX"
name: "DoorCAM"
product_id: "h3bhzu9m0ig80rdu"
product_name: "SmartDoorBell-IPBox"

Tuya cloud export data:
[DoorBell_export.txt](https://github.com/make-all/tuya-local/files/10568222/DoorBell_export.txt)

I wrote a simple config for it. Just as first step to add to HA and do basic control.
[doorcam.yaml.txt](https://github.com/make-all/tuya-local/files/10568640/doorcam.yaml.txt)

**Comment by make-all** [comment]
I am not sure what the token: True means, but if it is handled by localtuya, then it should be easy for the tinytuya developers to handle as well.

The bigger issue for this device is that there is no camera support in this integration, and isn't likely to be for some time, as I am not sure it is possible without cloud support (like vacuum cleaner mapping features).

**Comment by x5500** [comment]
I don't think that camera would be a big deal. I didn't researched it yet - need some time. However, there are some other features that are to be useful for local use. These are intercom status, door open commands, camera and motion sensor screenshots (raw image), flash memory status (free/used), doorbell signal (incoming call).

**Comment by make-all** [comment]
Based on the log, I wonder if the reason tuya-local cannot connect to your device is that localtuya is already connected?
The other possibility is that it is returning no state, so there is nothing to recognize as in #365

**Comment by ochayone** [comment]
> Hello! I've tried to add control new device (Doorcam/Intercom) and found out that protocol is not supported, but Local-Tuya using tytuya works correct. [debug_log.txt](https://github.com/make-all/tuya-local/files/10568176/debug_log.txt)
> 
> 2023-02-02 12:45:32.433 DEBUG (MainThread) [custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.168.77', 'gwId': 'bf71b225dc6dd70835wlbt', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': 'h3bhzu9m0ig80rdu', 'version': '3.3', 'token': True}
> 
> The difference i've noticed between this device and curtain (now supported by tuya-local) is using "'token" in protocol.
> 
> category: "sp" category_name: "Smart Camera" icon: "smart/icon/ay15507223992875xh7c/8c8b547693dedc057cf1dd9d3237f58c.png" model: "863XX" name: "DoorCAM" product_id: "h3bhzu9m0ig80rdu" product_name: "SmartDoorBell-IPBox"
> 
> Tuya cloud export data: [DoorBell_export.txt](https://github.com/make-all/tuya-local/files/10568222/DoorBell_export.txt)
> 
> I wrote a simple config for it. Just as first step to add to HA and do basic control. [doorcam.yaml.txt](https://github.com/make-all/tuya-local/files/10568640/doorcam.yaml.txt)

@x5500 
Where should the doorcam.yaml file be uploaded to in order to make the intercom/IP Box work and/or show up in HA?
Were you able to make the video/snapshot work as well?
I've tried multiple times (both locally and through cloud) to make my IP box work but was not successful so far :-(
Any recommendation/guidance would be very much appreciated.

**Comment by make-all** [comment]
The config for this issue is already included in the latest release.  If your device is not compatible, please file an issue with the HA logs from when you try to add the device, so we can see what the difference is.

**Comment by ochayone** [comment]
@make-all thank you very much for the prompt response (and for this awesome integration)

Well... sorry for being such a noob but where do I grab those logs from? the logs available through setting>system>logs say nothing about tuya-local.
anyway I also tried tinytuya and polling my local devices ends up w/ no response:
Polling local devices...
    [Intercom                 ] 192.168.0.109      - No Response

the product details per tinytuya are:

"name": "Intercom",
        "id": "bfa25c4610034c38c4jq6o",
        "key": "87ff2f936b439d83",
        "mac": "ef:f6:40:d5:4b:59",
        "uuid": "bkdz7d33eff640d54b59",
        "category": "sp",
        "product_name": "IP Bell",
        "product_id": "zwtjdst90jovtgsn",
        "biz_type": 18,
        "model": "",
        "sub": false,
        "icon": "https://images.tuyaeu.com/smart/icon/ay1565761798595HD4IR/1657503861d3ae38734f4.png"

**Comment by make-all** [comment]
> anyway I also tried tinytuya and polling my local devices ends up w/ no response

That will be an issue.  Are you sure the IP address, id and localkey are correct, and that there is no other integration or apps running that has already taken the local connection to the device?

**Comment by scherbet** [comment]
> #365

Hello!
I have same device and cant connect it to localtuya.

Localtuya error:
Connection to device succeeded but no datapoints found, please try again. Create a new issue and include debug logs if problem persists.

HA log:
homeassistant.util.loop
util/loop.py:99

Detected blocking call to import_module inside the event loop by custom integration 'localtuya' at custom_components/localtuya/config_flow.py, line 200: return import_module("." + platform, integration_module).flow_schema(dps_strings) (offender: /config/custom_components/localtuya/config_flow.py, line 200: return import_module("." + platform, integration_module).flow_schema(dps_strings)), please create a bug report at https://github.com/rospogrigio/localtuya/issues

Device Information (from iot tuya):
Product Name
IP Bell
Device ID
bf6a1ddb6aab3cd129b27b
Product Category
sp
Device Status
Online
Activated At
2023-02-04 15:28:35
