### ISSUE TITLE
inventor_atmosphere xl_dehumidifier mod enhancement 

### ISSUE THREAD

**Issue by samios88** [make-all/tuya-local#385]
hello again.
I have an inventor_atmosphere xl_dehumidifier i was able to modify the existing yaml file in order to have a seperate power button and an Oscillate button named swing in order to have the option when in both dehumidifier and air purifier it also makes it easier at least for me for the automations i will post bellow the modified yaml file and the iot cloud dps. One thing i found when is that in the fan entity when i put the slider in the middle it stops. Is it possible to put presets instead such us high medium low?
Thank you in advance please let me know if i can help

**Comment by samios88** [comment]
`name: Inventor Atomsphere XL dehumidifier
primary_entity:
  entity: humidifier
  class: dehumidifier
  dps:
    - id: 110
      type: string
      name: switch
      mapping:
        - dps_val: "air_purifier"
          value: false
        - dps_val: "dehumi_air"
          value: true
          constraint: main_switch
          conditions:
            - dps_val: false
              invalid: true
    - id: 1
      name: main_switch
      type: boolean
      mapping:
        - dps_val: false
          icon: "mdi:air-humidifier-off"
          icon_priority: 1
        - dps_val: true
          icon: "mdi:air-humidifier"
          icon_priority: 3
    - id: 3
      type: string
      name: humidity
      range:
        min: 0
        max: 80
      mapping:
        - dps_val: "CO"
          value: 0
        - dps_val: "40"
          value: 40
        - dps_val: "45"
          value: 45
        - dps_val: "50"
          value: 50
        - dps_val: "55"
          value: 55
        - dps_val: "60"
          value: 60
        - dps_val: "65"
          value: 65
        - dps_val: "70"
          value: 70
        - dps_val: "75"
          value: 75
        - dps_val: "80"
          value: 80
    - id: 5
      type: string
      name: mode
      mapping:
        - dps_val: auto
          value: Auto
        - dps_val: manual
          value: Manual
        - dps_val: drying
          value: Clothes
        - dps_val: night
          value: Sleep
    - id: 19
      type: bitfield
      name: error_code
# The following do not have descriptions in iot.tuya.com, the names
# though can be obtained from the debugger.  But functionality needs
# to be confirmed before making them separate entities
    - id: 105
      type: string
      name: air_purifier
secondary_entities:
  - entity: fan
    dps:
      - id: 1
        type: boolean
        name: switch
      - id: 4
        name: speed
        type: string
        mapping:
          - dps_val: low
            value: 50
            constraint: dehumid_mode
            conditions:
              - dps_val: air_purifier
                value_redirect: fan_speed_purifier
          - dps_val: high
            value: 100
            constraint: dehumid_mode
            conditions:
              - dps_val: air_purifier
                value_redirect: fan_speed_purifier
      - id: 8
        name: oscillate
        type: boolean
      - id: 110
        type: string
        name: dehumid_mode
        hidden: false
      - id: 112
        type: string
        name: fan_speed_purifier
        hidden: false
        mapping:
          - dps_val: low
            value: 33
          - dps_val: middle
            value: 66
          - dps_val: high
            value: 100
  - entity: sensor
    class: humidity
    name: Room humidity
    dps:
      - id: 6
        type: integer
        name: sensor
        unit: "%"
        class: measurement
  - entity: sensor
    class: temperature
    name: Room temperature
    dps:
      - id: 7
        type: integer
        name: sensor
        unit: C
        class: measurement
  - entity: switch
    category: config
    name: Ionizer
    icon: "mdi:creation"
    dps:
      - id: 10
        name: switch
        type: boolean
  - entity: switch
    category: config
    name: swing
    icon: "mdi:heat-wave"
    dps:
      - id: 8
        name: switch
        type: boolean
  - entity: switch
    category: config
    name: power
    icon: "mdi:power"
    dps:
      - id: 1
        name: switch
        type: boolean
  - entity: switch
    category: config
    name: UV sterilization
    icon: "mdi:solar-power"
    dps:
      - id: 13
        name: switch
        type: boolean
  - entity: sensor
    class: pm25
    name: PM2.5
    dps:
      - id: 15
        type: integer
        name: sensor
        unit: ugm3
  - entity: lock
    name: Child lock
    category: config
    dps:
      - id: 16
        type: boolean
        name: lock
        mapping:
          - dps_val: true
            icon: "mdi:hand-back-right-off"
          - dps_val: false
            icon: "mdi:hand-back-right"
  - entity: select
    name: Timer
    category: config
    icon: "mdi:timer"
    dps:
      - id: 17
        type: string
        name: option
        mapping:
          - dps_val: "None"
            value: "Off"
          - dps_val: 1h
            value: 1 hour
          - dps_val: 2h
            value: 2 hours
          - dps_val: 3h
            value: 3 hours
          - dps_val: 4h
            value: 4 hours
          - dps_val: 5h
            value: 5 hours
          - dps_val: 6h
            value: 6 hours
          - dps_val: 7h
            value: 7 hours
          - dps_val: 8h
            value: 8 hours
          - dps_val: 9h
            value: 9 hours
  - entity: sensor
    name: Timer
    category: diagnostic
    icon: "mdi:timer"
    dps:
      - id: 18
        type: integer
        name: sensor
        unit: min
  - entity: binary_sensor
    class: cold
    name: Defrost
    category: diagnostic
    dps:
      - id: 19
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 32
            value: true
          - value: false
  - entity: binary_sensor
    class: problem
    name: Tank full or missing
    category: diagnostic
    dps:
      - id: 19
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 64
            value: true
          - value: false
  - entity: binary_sensor
    class: problem
    name: Error
    category: diagnostic
    # Several errors are bundled here since they are actual faults and the
    # recommended action is turn off for 10 minutes for all and get it serviced
    # if the error persists.
    dps:
      - id: 19
        type: bitfield
        name: sensor
        mapping:
          # C1: Defrost sensor error
          - dps_val: 1
            value: true
          # C1: Humidity/temperature sensor failure
          - dps_val: 2
            value: true
          # C2: Possible refridgerant leakage (sensor temps too close)
          - dps_val: 4
            value: true
          # 000: not described
          - dps_val: 8
            value: true
          # 999: not described
          - dps_val: 16
            value: true
          # no error / P1/P2/Replace_Hepa (covered by individual sensors)
          - value: false
  - entity: binary_sensor
    class: problem
    name: HEPA filter replacement
    category: diagnostic
    dps:
      - id: 19
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 128
            value: true
          - value: false
  - entity: binary_sensor
    class: problem
    name: High humidity
    category: diagnostic
    dps:
      - id: 106
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - value: true
  - entity: binary_sensor
    class: problem
    name: Low humidity
    category: diagnostic
    dps:
      - id: 107
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - value: true
  - entity: select
    category: config
    name: Purifier mode
    icon: "mdi:cog"
    dps:
      - id: 105
        type: string
        name: option
        mapping:
        - dps_val: auto
          value: Auto
        - dps_val: manual
          value: Manual
        - dps_val: night
          value: Sleep
  - entity: select
    category: config
    name: Lighting
    icon: "mdi:lightbulb"
    dps:
      - id: 111
        type: string
        name: option
        mapping:
          - dps_val: "1"
            value: Display only
          - dps_val: "2"
            value: "Off"
          - dps_val: "3"
            value: "On"
  - entity: sensor
    category: diagnostic
    name: Air quality
    icon: "mdi:weather-dust"
    dps:
      - id: 108
        type: string
        name: sensor
`

**Comment by samios88** [comment]
`{
  "result": [
    {
      "category": "cs",
      "devices": [
        "bfb56d5ee83f535b4fbhv4"
      ],
      "functions": [
        {
          "code": "switch",
          "desc": "switch",
          "name": "switch",
          "type": "Boolean",
          "values": "{}"
        },
        {
          "code": "dehumidify_set_enum",
          "desc": "dehumidify set enum",
          "name": "dehumidify set enum",
          "type": "Enum",
          "values": "{\"range\":[\"CO\",\"40\",\"45\",\"50\",\"55\",\"60\",\"65\",\"70\",\"75\",\"80\"]}"
        },
        {
          "code": "fan_speed_enum",
          "desc": "fan speed enum",
          "name": "fan speed enum",
          "type": "Enum",
          "values": "{\"range\":[\"low\",\"high\"]}"
        },
        {
          "code": "mode",
          "desc": "mode",
          "name": "mode",
          "type": "Enum",
          "values": "{\"range\":[\"manual\",\"drying\",\"night\",\"auto\"]}"
        },
        {
          "code": "swing",
          "desc": "swing",
          "name": "swing",
          "type": "Boolean",
          "values": "{}"
        },
        {
          "code": "anion",
          "desc": "anion",
          "name": "anion",
          "type": "Boolean",
          "values": "{}"
        },
        {
          "code": "uv",
          "desc": "uv",
          "name": "uv",
          "type": "Boolean",
          "values": "{}"
        },
        {
          "code": "child_lock",
          "desc": "child lock",
          "name": "child lock",
          "type": "Boolean",
          "values": "{}"
        },
        {
          "code": "countdown_set",
          "desc": "countdown set",
          "name": "countdown set",
          "type": "Enum",
          "values": "{\"range\":[\"1h\",\"2h\",\"3h\",\"4h\",\"5h\",\"6h\",\"7h\",\"8h\",\"9h\",\"None\"]}"
        },
        {
          "code": "Air_purify_mode",
          "desc": "Air purify mode",
          "name": "Air purify mode",
          "type": "Enum",
          "values": "{\"range\":[\"manual\",\"night\",\"auto\"]}"
        },
        {
          "code": "Air_purify_switch",
          "desc": "Air purify switch",
          "name": "Air purify switch",
          "type": "Enum",
          "values": "{\"range\":[\"dehumi_air\",\"air_purifier\"]}"
        },
        {
          "code": "Light_level",
          "desc": "Light level",
          "name": "Light level",
          "type": "Enum",
          "values": "{\"range\":[\"1\",\"2\",\"3\"]}"
        },
        {
          "code": "Air_purify_fan_speed",
          "desc": "Air purify fan speed",
          "name": "Air purify fan speed",
          "type": "Enum",
          "values": "{\"range\":[\"low\",\"middle\",\"high\"]}"
        }
      ],
      "product_id": "td5l0upccfhkjwrw"
    }
  ],
  "success": true,
  "t": 1676065117564,
  "tid": "47040663a98b11ed9a310aeeb3bc8fba"
}`

**Comment by samios88** [comment]
{
  "result": [
    {
      "category": "cs",
      "devices": [
        "bfb56d5ee83f535b4fbhv4"
      ],
      "functions": [
        {
          "code": "switch",
          "desc": "switch",
          "name": "switch",
          "type": "Boolean",
          "values": "{}"
        },
        {
          "code": "dehumidify_set_enum",
          "desc": "dehumidify set enum",
          "name": "dehumidify set enum",
          "type": "Enum",
          "values": "{\"range\":[\"CO\",\"40\",\"45\",\"50\",\"55\",\"60\",\"65\",\"70\",\"75\",\"80\"]}"
        },
        {
          "code": "fan_speed_enum",
          "desc": "fan speed enum",
          "name": "fan speed enum",
          "type": "Enum",
          "values": "{\"range\":[\"low\",\"high\"]}"
        },
        {
          "code": "mode",
          "desc": "mode",
          "name": "mode",
          "type": "Enum",
          "values": "{\"range\":[\"manual\",\"drying\",\"night\",\"auto\"]}"
        },
        {
          "code": "swing",
          "desc": "swing",
          "name": "swing",
          "type": "Boolean",
          "values": "{}"
        },
        {
          "code": "anion",
          "desc": "anion",
          "name": "anion",
          "type": "Boolean",
          "values": "{}"
        },
        {
          "code": "uv",
          "desc": "uv",
          "name": "uv",
          "type": "Boolean",
          "values": "{}"
        },
        {
          "code": "child_lock",
          "desc": "child lock",
          "name": "child lock",
          "type": "Boolean",
          "values": "{}"
        },
        {
          "code": "countdown_set",
          "desc": "countdown set",
          "name": "countdown set",
          "type": "Enum",
          "values": "{\"range\":[\"1h\",\"2h\",\"3h\",\"4h\",\"5h\",\"6h\",\"7h\",\"8h\",\"9h\",\"None\"]}"
        },
        {
          "code": "Air_purify_mode",
          "desc": "Air purify mode",
          "name": "Air purify mode",
          "type": "Enum",
          "values": "{\"range\":[\"manual\",\"night\",\"auto\"]}"
        },
        {
          "code": "Air_purify_switch",
          "desc": "Air purify switch",
          "name": "Air purify switch",
          "type": "Enum",
          "values": "{\"range\":[\"dehumi_air\",\"air_purifier\"]}"
        },
        {
          "code": "Light_level",
          "desc": "Light level",
          "name": "Light level",
          "type": "Enum",
          "values": "{\"range\":[\"1\",\"2\",\"3\"]}"
        },
        {
          "code": "Air_purify_fan_speed",
          "desc": "Air purify fan speed",
          "name": "Air purify fan speed",
          "type": "Enum",
          "values": "{\"range\":[\"low\",\"middle\",\"high\"]}"
        }
      ],
      "product_id": "td5l0upccfhkjwrw"
    }
  ],
  "success": true,
  "t": 1676065117564,
  "tid": "47040663a98b11ed9a310aeeb3bc8fba"
}

**Comment by samios88** [comment]
manual:
https://ac.inv-static.com/uploads/dehumidifiers/ATMOSPHERE_XL/Atmosphere_XL_UM_v10_0620.pdf

**Comment by make-all** [comment]
This device is already supported
