### ISSUE TITLE
Request support for TOMPD-63LW Breaker

### ISSUE THREAD

**Issue by garry0garry** [make-all/tuya-local#388]
TOMPD-63LW Breaker

# Log Message

```
      "dps_strings": [
        "1 (value: 0)",
        "9 (value: 0)",
        "11 (value: False)",
        "13 (value: 0)",
        "15 (value: 0)",
        "16 (value: True)",
        "19 (value: 1234)"

```
# Information about DPS mappings

```
{
  "result": {
    "category": "dlq",
    "functions": [
      {
        "code": "switch_prepayment",
        "dp_id": 11,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "energy_reset",
        "dp_id": 12,
        "type": "Enum",
        "values": "{\"range\":[\"empty\"]}"
      },
      {
        "code": "charge_energy",
        "dp_id": 14,
        "type": "Integer",
        "values": "{\"unit\":\"kW·h\",\"min\":0,\"max\":99999,\"scale\":1,\"step\":1}"
      },
      {
        "code": "switch",
        "dp_id": 16,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "alarm_set_1",
        "dp_id": 17,
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "alarm_set_2",
        "dp_id": 18,
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "leakagecurr_test",
        "dp_id": 21,
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "total_forward_energy",
        "dp_id": 1,
        "type": "Integer",
        "values": "{\"unit\":\"kW·h\",\"min\":0,\"max\":99999999,\"scale\":2,\"step\":1}"
      },
      {
        "code": "phase_a",
        "dp_id": 6,
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "fault",
        "dp_id": 9,
        "type": "Bitmap",
        "values": "{\"label\":[\"short_circuit_alarm\",\"surge_alarm\",\"overload_alarm\",\"leakagecurr_alarm\",\"temp_dif_fault\",\"fire_alarm\",\"high_power_alarm\",\"self_test_alarm\",\"ov_cr\",\"unbalance_alarm\",\"ov_vol\",\"undervoltage_alarm\",\"miss_phase_alarm\",\"outage_alarm\",\"magnetism_alarm\",\"credit_alarm\",\"no_balance_alarm\"]}"
      },
      {
        "code": "switch_prepayment",
        "dp_id": 11,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "energy_reset",
        "dp_id": 12,
        "type": "Enum",
        "values": "{\"range\":[\"empty\"]}"
      },
      {
        "code": "balance_energy",
        "dp_id": 13,
        "type": "Integer",
        "values": "{\"unit\":\"kW·h\",\"min\":0,\"max\":999999,\"scale\":1,\"step\":1}"
      },
      {
        "code": "charge_energy",
        "dp_id": 14,
        "type": "Integer",
        "values": "{\"unit\":\"kW·h\",\"min\":0,\"max\":99999,\"scale\":1,\"step\":1}"
      },
      {
        "code": "leakage_current",
        "dp_id": 15,
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch",
        "dp_id": 16,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "alarm_set_1",
        "dp_id": 17,
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "alarm_set_2",
        "dp_id": 18,
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "breaker_number",
        "dp_id": 19,
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "leakagecurr_test",
        "dp_id": 21,
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1676111968259,
  "tid": "5c2c6eb3a9f811edbe05a63cfb33a057"
}

```

# Product ID
```
    "product_id": "rrmpzckqm5pfd642",
    "model": "",
    "name": "Breaker",
    "online": true,
    "owner_id": "44613254",
    "product_name": "Breaker",

```
# Information about how the device functions

https://aliexpress.ru/item/1005004774173382.html

    1. Remote control ON/OFF at anytime from anywhere by phone.
    2. Review current ,voltage, leakage current, total kWh on phone
    3. Timer function in smartlife TUYA app
    4. Can set over voltage/under voltage/over current /leakage current in app or can set these by manual
    5. Undervoltage protection 140V-210V (adjustable) (default: 170V)
    6. Over voltage proteciton225V-295V (adjustable) (default: 265)
    7. Over current protection1A-63A (adjustable) (default: 40A)
    8. Reconnect time (delay on time): 1s-500s (default: 30s)
    9. Voltage/current/kW calibration: -9.9%-9.9%
    10. Action time: 1-30s (detault 1s)
    11. power consumption less than 2W

![photo_2023-02-11_13-49-13](https://user-images.githubusercontent.com/95581374/218254439-21495543-597a-460d-b34c-39fafeb8ae3d.jpg)
![photo_2023-02-11_13-48-20 (3)](https://user-images.githubusercontent.com/95581374/218254441-9fd48443-ba6e-48d0-94d3-383dab33d36b.jpg)
![photo_2023-02-11_13-48-20 (2)](https://user-images.githubusercontent.com/95581374/218254442-10bf3fc9-2ba7-4e2d-9e6f-6497f42c7c19.jpg)
![photo_2023-02-11_13-48-20](https://user-images.githubusercontent.com/95581374/218254443-8d80a0a4-02e0-4d2e-94d5-234ed44e85f1.jpg)

**Comment by garry0garry** [comment]
How can I install this [patch](https://github.com/make-all/tuya-local/commit/7b70f2ed558e33fdf9ea27f84f0b3ca344002765)? Need to install the master version?

**Comment by make-all** [comment]
The 2023.2.1 release has this.

**Comment by garry0garry** [comment]
Home Assistant v2023.2.4
Log Message:
```
 "dps_strings": [
        "1 (value: 0)",
        "9 (value: 0)",
        "11 (value: False)",
        "13 (value: 0)",
        "15 (value: 0)",
        "16 (value: True)",
        "19 (value: 1234)"

```If the release has it, then why is there no data in the log? Did I have to prescribe the TOMPD-63LW Breaker in some special way? Tell me the instructions, please.

**Comment by make-all** [comment]
I mean the tuya-local release 2023.2.1, not Home Assistant.

**Comment by garry0garry** [comment]
Sorry, I'm confused. I thought I was writing for
https://github.com/rospogrigio/localtuya
but wrote to
https://github.com/make-all/tuya-local

Can I install your integration side by side with another one?

**Comment by make-all** [comment]
Not for the same device, and if you have localtuya installed, the "Auto" setting for IP address will not work in tuya-local, as the discovery port is already claimed by localtuya.

**Comment by garry0garry** [comment]
Thank you! While included one device in different integrations in parallel.

Do I understand correctly that
```
status: {
       "16": true
```
equals
`"entity_id": "switch.circuit_breaker_energy_meter"`
?

Is there a difference in the protocols
`  "api_version_set": 3.2` 
and 3.3 for this device? Visually, it works the same on both 3.2 and 3.3.

[tuya_local-04af1652d2a1f1a20788ab10b185eea3-Circuit breaker energy meter-1968c6386062d92c6a9db7affea88ffb.json.txt](https://github.com/make-all/tuya-local/files/10745194/tuya_local-04af1652d2a1f1a20788ab10b185eea3-Circuit.breaker.energy.meter-1968c6386062d92c6a9db7affea88ffb.json.txt)

**Comment by garry0garry** [comment]
3.3
[tuya_local-04af1652d2a1f1a20788ab10b185eea3-Circuit breaker energy meter-1968c6386062d92c6a9db7affea88ffb.json(1).txt](https://github.com/make-all/tuya-local/files/10745281/tuya_local-04af1652d2a1f1a20788ab10b185eea3-Circuit.breaker.energy.meter-1968c6386062d92c6a9db7affea88ffb.json.1.txt)

**Comment by make-all** [comment]
3.2 is a variation of 3.3, more like a beta version I think, as it is not very widely deployed.  The differences are minor, if it works with both, chose 3.3, as that is the more common one.  Actual 3.2 devices do not fully work when set to 3.3

**Comment by garry0garry** [comment]
Stable error after restarting Home Assistant:

```
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:503
Integration: Sensor (documentation, issues)
First occurred: 9:10:37 AM (2 occurrences)
Last logged: 9:10:37 AM

Entity sensor.circuit_breaker_energy_meter_balance_energy (<class 'custom_components.tuya_local.sensor.TuyaLocalSensor'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; expected None or one of 'total', 'total_increasing'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.circuit_breaker_energy_meter_energy (<class 'custom_components.tuya_local.sensor.TuyaLocalSensor'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; expected None or one of 'total', 'total_increasing'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
```

![изображение](https://user-images.githubusercontent.com/95581374/219283435-51ba0cc8-3f04-474f-b8d8-078b31d9ab6c.png)

**Comment by make-all** [comment]
Support added in 2023.2.3

**Comment by garry0garry** [comment]
`State Class: ''`

![изображение](https://user-images.githubusercontent.com/95581374/223825068-586215c2-5e22-4b6f-a572-1c67104ba0e5.png)

**Comment by make-all** [comment]
I can't see the full message, the full entity name and there is no explanation of the conditions that cause this message to come out.

**Comment by garry0garry** [comment]
This message is not in the log. Message in /developer-tools/statistics: `"The state class '' of this entity is not supported."` and `"Unsupported state class"`

Entity:
```
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": "kWh",
          "state": {
            "entity_id": "sensor.circuit_breaker_energy_meter_balance_energy",
            "state": "0.0",
            "attributes": {
              "unit_of_measurement": "kWh",
              "friendly_name": "Circuit breaker energy meter Balance energy"
            },
            "last_changed": "2023-03-08T19:19:34.450479+00:00",
            "last_updated": "2023-03-08T19:19:34.450479+00:00"
          }
        },
```

**Comment by garry0garry** [comment]
As far as I understand it is about 
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by make-all** [comment]
Right, and in there it gives descriptions of only measurement, total and total_increasing state classes.  This is a total remaining, which doesn't really fit into any of those, so it is not tagged with a state class.  As far as I can tell from the HA developer documentation, this is correct.

**Comment by garry0garry** [comment]
Why does a similar sensor have a tate_class?

```
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "energy",
          "icon": null,
          "unit_of_measurement": "kWh",
          "state": {
            "entity_id": "sensor.circuit_breaker_energy_meter_energy",
            "state": "557.32",
            "attributes": {
              "state_class": "total_increasing",
              "unit_of_measurement": "kWh",
              "device_class": "energy",
              "friendly_name": "Circuit breaker energy meter Energy"
            },
            "last_changed": "2023-03-09T05:46:38.532148+00:00",
            "last_updated": "2023-03-09T05:46:38.532148+00:00"
          }
        }

```

**Comment by make-all** [comment]
That is an energy meter, which counts the energy consumed.

The one the message is about, sensor.circuit_breaker_energy_meter_balance_energy, is a balance tracker for remaining credit on a prepaid meter.

**Comment by make-all** [comment]
It looks like a new device class has been added for such sensors, presumably for HA 2023.4.  Once that is added, it will be easier to see what other integrations using it do for state_class (particularly the built in ones).

https://github.com/home-assistant/core/pull/88310

**Comment by garry0garry** [comment]
Sorry, I did not understand. There are two sensors:

circuit_breaker_energy_meter_energy
unit_of_measurement: "kWh"
**state_class: "total_increasing"**
**device_class: "energy"**

circuit_breaker_energy_meter_balance_energy
unit_of_measurement: "kWh"
**state_class: not specified**
**device_class: not specified**

Why do they have different attributes?

**Comment by make-all** [comment]
One question on this device:  is the energy reset button working?

On issue #577 a similar device (same brand and amp rating) is requested.  The only difference between the data captured in the log and the config for this device is the energy reset (dp 12 from the "Information on DPS mappings" above) is being returned from the device as a boolean value (false).

In the logs posted to this issue, we never captured dp 12, so it was just an assumption that it will be a string based on the "Information on DPS mappings" from iot.tuya.com, which specifies it as Enum with possible value "empty".

It is quite common for iot.tuya.com information to not match the local protocol, so if you can test that button - if it is not working, likely this device and the #577 device are identical, and that button needs to be changed to a boolean.

**Comment by garry0garry** [comment]
How to enable debug information? I will run tests and send logs.

**Comment by garry0garry** [comment]
configuration.yaml
```
logger:
  default: warning
  logs:
    homeassistant.core: warning
    custom_components.tuya-local: debug
```
    
Does not output debug information.

**Comment by make-all** [comment]
You need to use an underscore.  But I don't expect to see anything in the logs, as Tuya devices don't really reject anything at the protocol level, just silently fail (some will go offline for a few seconds, probably crashing and watchdogging due to bad input). So I just want to know whether that energy reset button is resetting anything.

If it is ever returning data for dp 12, you should be able to see that in the diagnostics file: Settings / Devices & Services / Integrations - Tuya Local [TOMPD device] / 1 device / Download Diagnostics.

**Comment by garry0garry** [comment]
Before energy reset button:
[tuya_local-04af1652d2a1f1a20788ab10b185eea3-Circuit breaker energy meter-1968c6386062d92c6a9db7affea88ffb.json(5).txt](https://github.com/make-all/tuya-local/files/11118491/tuya_local-04af1652d2a1f1a20788ab10b185eea3-Circuit.breaker.energy.meter-1968c6386062d92c6a9db7affea88ffb.json.5.txt)


After:
[tuya_local-04af1652d2a1f1a20788ab10b185eea3-Circuit breaker energy meter-1968c6386062d92c6a9db7affea88ffb.json(6).txt](https://github.com/make-all/tuya-local/files/11118492/tuya_local-04af1652d2a1f1a20788ab10b185eea3-Circuit.breaker.energy.meter-1968c6386062d92c6a9db7affea88ffb.json.6.txt)

**Comment by make-all** [comment]
There doesn't seem to be any effect.  I will try changing the type of the button to boolean and remove the mapping then, so it sends true rather than "empty".

**Comment by garry0garry** [comment]
Is it possible to display volts and amps?

**Comment by nao982** [comment]
Could someone advice how to add volts and amps display in home assistant ?

**Comment by make-all** [comment]
With this device, you can't.  It does not provide volts and amps in the local protocol.

**Comment by garry0garry** [comment]
0V and 580A

![изображение](https://github.com/make-all/tuya-local/assets/95581374/b005aeed-10a5-477f-b4b6-73e0641ad1f5)

[tuya_local-04af1652d2a1f1a20788ab10b185eea3-Circuit breaker energy meter-1968c6386062d92c6a9db7affea88ffb.json(8).txt](https://github.com/make-all/tuya-local/files/11761618/tuya_local-04af1652d2a1f1a20788ab10b185eea3-Circuit.breaker.energy.meter-1968c6386062d92c6a9db7affea88ffb.json.8.txt)

[home-assistant_tuya_local_2023-06-15T19-05-13.221Z.log](https://github.com/make-all/tuya-local/files/11761715/home-assistant_tuya_local_2023-06-15T19-05-13.221Z.log)

**Comment by make-all** [comment]
It seems the phase_a decoding was just copied from another device without checking.  Both #577 and your diagnostic data show 8 byte data, but the decoding is based on an 11 byte field.  I will update it accordingly.

**Comment by marsic-84** [comment]
> 0V and 580A
> 
> ![изображение](https://user-images.githubusercontent.com/95581374/246209908-b005aeed-10a5-477f-b4b6-73e0641ad1f5.png)
> 
> [tuya_local-04af1652d2a1f1a20788ab10b185eea3-Circuit breaker energy meter-1968c6386062d92c6a9db7affea88ffb.json(8).txt](https://github.com/make-all/tuya-local/files/11761618/tuya_local-04af1652d2a1f1a20788ab10b185eea3-Circuit.breaker.energy.meter-1968c6386062d92c6a9db7affea88ffb.json.8.txt)
> 
> [home-assistant_tuya_local_2023-06-15T19-05-13.221Z.log](https://github.com/make-all/tuya-local/files/11761715/home-assistant_tuya_local_2023-06-15T19-05-13.221Z.log)

Hi. Is your device updating voltage, current, power and total power without internet connection to tuya server, just in LAN ?
Because mine do not do it even in Tuya Smart App((

**Comment by screem20056** [comment]
Hi, i really like this integration for the high level of customization it gives to tuya even the official integration does not.
In this device, there is a possibility to turn on and off some features like the earth leakage, which i really wanted to control as a switch from home assistant 
Regards

**Comment by RuStyC0der** [comment]
Hi there, I am kinda newbie in smart home topic and I want to ask for some help) I set up TOMPD-63LW  with this integration and it works like charm but after approximately 40s after connection breaker stops sending updates to HA, i mean voltage, current, etc.
Is there any problem on my side? 

Also it would be great to have ability to set parameters like delays or other protection values.

**Comment by garry0garry** [comment]
@RuStyC0der 
I suggest you first study the logs on the router, then enable debugging in HA
```
logger:
  default: warning
  logs:
    custom_components.tuya_local: debug
```
and reboot HA.

**Comment by RuStyC0der** [comment]
Hi, what kind of router do you mean, my wifi router?
My friend also have this issue with same device. 
Are you have same device and not have this issue?

**Comment by garry0garry** [comment]
Yes, I suggest analyzing the wifi router logs.
That's right, I have the same device and don't have this problem.

I think having router logs and integration will help to understand the problem.

**Comment by RuStyC0der** [comment]
did some additional tests, energy sensor and ability control switch is preserved but sensors in diagnostic section are freezed. When i press "Refresh sensors" they unfreeze for another 10 seconds or so and then again became static.

@garry0garry  do you have the same behavior of your breaker?

![image](https://github.com/user-attachments/assets/a264d687-993f-4b21-a621-3cfcbc398607)

**Comment by garry0garry** [comment]
I don't have any sensor freeze.
![изображение](https://github.com/user-attachments/assets/f2087b8b-678b-4955-9bea-c20304db8f9b)

**Comment by make-all** [comment]
This is the device behaviour, and is the reason why the "Refresh Sensors" button is needed.  I'm not sure why only some people are seeing this, but the intention is that you would set up an automation to call Refresh Sensors at whatever interval you need for tracking granularity.

**Comment by RuStyC0der** [comment]
@make-all  Hi, thanks for your reply. I did know about this but thought of it as workaround, and wanted to confirm it is normal behavior, not some bug from my device)

@garry0garry  So did you also set up automation?

sorry for being kinda noisy I`m newbie in this field and just wanna make sure I`m not making something wrong)

**Comment by garry0garry** [comment]
@RuStyC0der 
I don't use "Refresh Sensors". I see the sensor automatically updating every two minutes. In my scenario, this is enough. 

For accurate diagnostics, I use PZEM and set the data collection to every three seconds.

**Comment by RuStyC0der** [comment]
I`m confused now @make-all, do you have any guesses in this?

The only guess I can assume that @garry0garry  may also use some tuya cloud application or platform which triggers updates as soon as when I open app it starts to send data

![image](https://github.com/user-attachments/assets/5701c383-0f99-4671-b1ad-c77b176e283c)

**Comment by garry0garry** [comment]
No logs - no attempt to give an answer.

**Comment by garry0garry** [comment]
@make-all Please add the device type to "Device info".
  "data": {
    "name": "Circuit breaker energy meter",
    "type": "tompd_63lw_breaker",
![изображение](https://github.com/user-attachments/assets/dc620ca3-8534-4af6-a8bb-2d5cc7f637a4)

**Comment by RuStyC0der** [comment]
@garry0garry  sure, I will check and provide you debug data and network traffic dump data a little bit later, thanks for helping)

**Comment by garry0garry** [comment]
"installation_type": "Home Assistant Container", "version": "2024.12.2"
"name": "Tuya Local", "version": "2024.12.0"

`power_factor` and `frequency` are always unknown:

```
          "original_device_class": "power_factor",
          "icon": null,
          "unit_of_measurement": "%",
          "state": {
            "entity_id": "sensor.avtomat_na_septike_koeffitsient_moshchnosti",
            "state": "unknown",

          "original_device_class": "frequency",
          "icon": null,
          "unit_of_measurement": "Hz",
          "state": {
            "entity_id": "sensor.avtomat_na_septike_chastota",
            "state": "unknown",

```
P.S. It's a pity that they renamed the English entity_id of the sensors into transcription :-(

**Comment by garry0garry** [comment]
Please add the device type to "Device info". https://github.com/make-all/tuya-local/issues/388#issuecomment-2459827757
