### ISSUE TITLE
Instruction to add Kogan Dehumidifer

### ISSUE THREAD

**Issue by advertisingfree** [make-all/tuya-local#39]
Is there a step by step on how to add kogan dehumidifer? I can add it as a switch to turn on and off, not sure how to add the rest such as fan speed or humidifier numeric sensor.

**Comment by advertisingfree** [comment]
I have added switch to turn on, off and sensor to see current stats. However, still not sure how to control fan speed or timer.

**Comment by make-all** [comment]
This integration does not support sensors yet, so I am not sure you have added it from this integration, maybe from another integration?

**Comment by advertisingfree** [comment]
Sorry, I was using a different integration.
