### ISSUE TITLE
Configuration wizard wont loadup

### ISSUE THREAD

**Issue by Bluezzz** [make-all/tuya-local#391]
I'm trying to configurate my integration but every try the "Configuration wizard" wont load, waited about half an hour and still nothing happend

1. Go to https://github.com/make-all/tuya-local
2. Click on "Add Integration"
3. "Configuration wizard" wont load

Happed with:
 - RP3
 - Windows 11
 - Chrome

Screenshots

![Screenshot 2023-02-11 200148](https://user-images.githubusercontent.com/25132339/218273873-fd020c54-706a-482c-8f66-192b5197b881.png)
![Screenshot 2023-02-11 195007](https://user-images.githubusercontent.com/25132339/218273472-77e4b266-453d-4569-8a76-72805cb38abf.png)

**Comment by make-all** [comment]
- Have you installed the integration first?
- Did you restart Home Assistant after installing the integration?
- Do other "My Homeassistant" links work correctly?

The link is just a shortcut to "Settings" / "Devices and Services" / "+ Add Integration" / "Tuya Local", so you should still be able to add devices if you cannot get the "My Homeassistant" link to work with your installation.
