### ISSUE TITLE
Request support for [Elivco Smart Plug 20A, CB2S-16DL, LSPA9]

### ISSUE THREAD

**Issue by YuriiMaiboroda** [make-all/tuya-local#392]
My socket (Elivco Smart Plug 20A, CB2S-16DL, LSPA9) is different from smartplugv2_energyv3 in a few small ways and very different from smartplugv2. Because of which I cannot use all the socket functions through HA.

I set up a few experiments and found out how scheduled timers are encoded into a string (described in detail below).

# Log Message

```json
{
    "1": true,
    "9": 0,
    "18": 0,
    "19": 0,
    "20": 2434,
    "21": 1,
    "22": 591,
    "23": 26025,
    "24": 14705,
    "25": 2830,
    "26": 0,
    "38": "off",
    "39": false,
    "40": "pos",
    "41": false,
    "42": "AH8AAAB4AAoAFA==",
    "43": "AH8AHgA8",
    "44": "AA4Q"
}
```

# Information about DPS mappings

The settings are almost the same as in `smartplugv2_energyv3.yaml`

<details>
<summary>Specification received via API:</summary>

```json
{
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "switch_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "dp_id": 38,
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "overcharge_switch",
        "dp_id": 39,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "light_mode",
        "dp_id": 40,
        "type": "Enum",
        "values": "{\"range\":[\"relay\",\"pos\",\"none\"]}"
      },
      {
        "code": "child_lock",
        "dp_id": 41,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "cycle_time",
        "dp_id": 42,
        "type": "String",
        "values": "{}"
      },
      {
        "code": "random_time",
        "dp_id": 43,
        "type": "String",
        "values": "{}"
      },
      {
        "code": "switch_inching",
        "dp_id": 44,
        "type": "String",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "add_ele",
        "dp_id": 17,
        "type": "Integer",
        "values": "{\"min\":0,\"max\":50000,\"scale\":3,\"step\":100}"
      },
      {
        "code": "cur_current",
        "dp_id": 18,
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_power",
        "dp_id": 19,
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":0,\"max\":80000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "cur_voltage",
        "dp_id": 20,
        "type": "Integer",
        "values": "{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "relay_status",
        "dp_id": 38,
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "overcharge_switch",
        "dp_id": 39,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "light_mode",
        "dp_id": 40,
        "type": "Enum",
        "values": "{\"range\":[\"relay\",\"pos\",\"none\"]}"
      },
      {
        "code": "child_lock",
        "dp_id": 41,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "cycle_time",
        "dp_id": 42,
        "type": "String",
        "values": "{}"
      },
      {
        "code": "random_time",
        "dp_id": 43,
        "type": "String",
        "values": "{}"
      },
      {
        "code": "switch_inching",
        "dp_id": 44,
        "type": "String",
        "values": "{}"
      }
    ]
  }
}
```
</details>
But it has mistakes:

- I have never seen "dp 17" (add_ele) in the log.
- "dp 38" (relay_status) says `power_off, power_on, last'`, when it actually sends `on, off, memory`.
- "dp 9" (countdown_1) specifies scale 0 instead of 1.
- "dp 18" (cur_current) specifies scale 0 instead of 10.

Differences from `smartplugv2_energyv3.yaml`:
- dp 9 is in seconds with scale 1 (realy 0) and step 1, not minutes with scale 60 and step 60
- dp 42 is not just string but base64 (сan be an empty string if no schedules are specified)
 Array of settings for cycling
  - 1 byte - boolean (1 or 0) - enabled or not
  - 1 byte - a set of bits indicating which days the setting should work (for example, 00000001 - Monday, 01000000 - Sunday, 01111111 - all days of the week)
  - 2 bytes - int, start time in minutes from midnight
  - 2 bytes - int, end time in minutes from midnight
  - 2 bytes - int, duration of on periods in minutes
  - 2 bytes - int, duration of off periods in minutes
  
  Example: "AH8AAAB4AAoAFAAAAHgA8AAeADw=" -> [0, 127, 0, 0, 0, 120, 0, 10, 0, 20, 0, 0, 0, 120, 0, 240, 0, 30, 0, 60] -> [false, 0b01111111, 0, 120, 10, 20], [false, 0b000000, 120, 240, 30, 60] 
    <details><summary>Screenshot of the circulate menu</summary>

    ![img](https://user-images.githubusercontent.com/47284191/218271749-05200a29-ee49-4830-b1a2-c6c809f850c0.jpg)
    </details>
    1. disabled, repeats every day, starts at 00:00, ends at 02:00, on periods are 10 minutes, off periods are 20 minutes 
    <details><summary>Screenshot of the first circulate</summary>
    
      ![photo_3_2023-02-11_19-18-45](https://user-images.githubusercontent.com/47284191/218271789-8fec08e2-110b-4dc6-b272-5cf43b72f73d.jpg) 
    </details>
    3. disabled, not repeating, starts at 02:00, ends at 04:00, on periods are 30 minutes, off periods are 60 minutes
    <details><summary>Screenshot of the second circulate</summary>
    
      ![photo_2_2023-02-11_19-18-45](https://user-images.githubusercontent.com/47284191/218271777-f50c8d96-131c-4694-8bae-815c75d2843b.jpg)
    </details>

- dp 43 is not just string but base64 (сan be an empty string if no schedules are specified)
 Array of settings for random
  - 1 byte - boolean (1 or 0) - enabled or not
  - 1 byte - a set of bits indicating which days the setting should work (for example, 00000001 - Sunday, 01000000 - Saturday, 01111111 - all days of the week)
  - 2 bytes - int, start time in minutes from midnight
  - 2 bytes - int, end time in minutes from midnight

  Example: "AH8AHgA8AQEAPAB4" -> [0, 127, 0, 30, 0, 60, 1, 1, 0, 60, 0, 120] -> [false, 0b00000000, 30, 60], [true, 0b00000001, 60, 120] 
    <details><summary>Screenshot of the Random menu</summary>

    ![photo_1_2023-02-11_19-33-34](https://user-images.githubusercontent.com/47284191/218272473-744d05c6-05df-4d0e-ab1c-d24c3a65dbff.jpg)
    </details>
    1. disabled, repeats every day, starts at 00:30, ends at 01:00
    <details><summary>Screenshot of the first random</summary>
    
    ![photo_3_2023-02-11_19-33-34](https://user-images.githubusercontent.com/47284191/218272534-0a89b868-86ba-4137-9ef3-9293ba4b4b4f.jpg)
    </details>
    3. enabled, repeating every Sunday, starts at 01:00, ends at 02:00
    <details><summary>Screenshot of the second random</summary>
    
    ![photo_2_2023-02-11_19-33-34](https://user-images.githubusercontent.com/47284191/218272591-66bbec13-975f-42b6-85c8-02ae38942b97.jpg)
    </details>

- dp 44 is not boolean but base64 (can be an empty string if it has never been enabled before)
  Inching (auto-off)
  - 1 byte - boolean (1 or 0) - enabled or not
  - 2 bytes - int, duration before automatic switch-off in seconds

  Example: "AA4Q" -> [0, 14, 16] -> [false, 3600]
    disabled, power off after 1 hour
    <details><summary>Screenshot of the Inching menu</summary>

    ![photo_1_2023-02-11_19-40-23](https://user-images.githubusercontent.com/47284191/218272934-6f1825f1-65f1-400f-be68-b2c3263a3844.jpg)
    </details>

# Product ID

```json
{
    "category": "cz",
    "category_name": "Socket",
    "model": "CB2S-16DL",
    "product_id": "wrz6vzch8htux2zp",
    "product_name": "Wifi Plug",
}
```

# Information about how the device functions

### Circulate
The mode of automatic switching on and off of the socket in the specified period of time, for the specified durations.
For example, every Sunday, from 10 am to 10 pm, repeatedly turn on for 10 minutes and turn off for 20 minutes.

- Maximum number of items - 10
- Durations should not be less than 1 minute, more than 24 hours or the total duration of the schedule (if the schedule starts at 00:00 and ends at 03:00, then the total duration of switching on and off cannot be more than 3 hours).
- If the days of repetitions are not specified, then the schedule works only once and after that it is disabled.

### Random
The mode of automatic switching on and off of the socket in the specified period of time, for random durations.
For example, every Sunday, from 10 am to 10 pm, turn on and off for a random duration.

- Maximum number of items - 10
- Durations should not be less than 1 minute, more than 24 hours or the total duration of the schedule (if the schedule starts at 00:00 and ends at 03:00, then the total duration of switching on and off cannot be more than 3 hours).
- If the days of repetitions are not specified, then the schedule works only once and after that it is disabled.

### Inching
Automatic shutdown after a specified time after switching on.

**Comment by make-all** [comment]
Regarding the specification mistakes:

- I have never seen "dp 17" (add_ele) in the log.
It may be a cloud only dp - generally these add_ele attributes are not useful locally, as they mostly only return 0 or 1, and clear back to 0 after sending the update to the cloud.  It is a shame, because the units of kWh would eliminate the need to set up an additional integration helper to get energy usage based on power history.

- "dp 38" (relay_status) says power_off, power_on, last', when it actually sends on, off, memory.
It's not unusual for the local enum values to be different from the cloud ones documented.

- "dp 9" (countdown_1) specifies scale 0 instead of 1.
This is the way Tuya defines their scale (decimal place shifts).  I defined mine before iot.tuya.com existed, through reverse engineering the protocol, so my definition (a divisor) differs from theirs.

- "dp 18" (cur_current) specifies scale 0 instead of 10.
It is normal for current to be in mA without any scaling.  Are you sure there is a scale of 10 there?  Normally voltage and power will have a scale of 10 to be able to represent 0.1V and 0.1W, but current is in mA.  A quick check would be to multiple your voltage by the current to see if the power is in the right ballpark (for AC, it is not exactly P=VI due to inductive or capacitive loads causing phase shifting, but it should be close).


Regarding differences from smartplugv2_energyv3.yaml:

- dp 9 is in seconds with scale 1 (realy 0) and step 1, not minutes with scale 60 and step 60
This is not a difference, just a design choice to avoid fielding issues about the timer precision being off by some seconds.  Since we can't guarantee accuracy to the exact second and updates for the UI previously came only every 20s (now around 5s), I chose to scale to minutes.  I didn't think there was a use case for sub minute timers, but maybe there is for inching cases.

- dp 42, 43, 44 is not just string but base64
These multi-value bundles are too complex to support, so I didn't try to decode them further.  I have only done this for RGB lights, where there is a standard encoding that maps directly onto HA functionality.

---

I think the only substantial differences between this and smartplugv2_energyv3 is the incompatible type of dp 44 and the missing dp 17.  If you can confirm the scale of dp 18, that may also be different, but I suspect not based on the iot.tuya.com doc matching the smartplugv2_energyv3 scale and 90% of other plugs also matching that.

**Comment by YuriiMaiboroda** [comment]
You're right. For 18, the scale should be 1, not 10.
What about Overcharge switch (39)? Regular boolean switch.

**Comment by YuriiMaiboroda** [comment]
I looked at issue #294. There, too, there is a Boolean 39 and 44 is a string, not a Boolean. That is, exactly the same data is sent there as mine, but 17 is additionally sent.
In some similar issues (#277, #299? #323), 44 is also a string, not a boolean.
Perhaps when adding smartplugv2_energyv3 44 was boolean by mistake and instead of adding a new device file, you need to fix the existing one?

**Comment by make-all** [comment]
Yes, I think you are right, fixing the existing one is the better option.  I seem to have been thrown by the naming as "switch_inching" into creating it as a switch, and then probably copied across multiple similar but not quite identical configs.

**Comment by YuriiMaiboroda** [comment]
Device detected successfully
![image](https://user-images.githubusercontent.com/47284191/218499908-f9e20a4c-477d-4a3c-afd5-854f12256481.png)
Even some kind of energy is displayed somehow. It didn't exist before. Perhaps this is due to the addition of calibration data in the right places.
![image](https://user-images.githubusercontent.com/47284191/218500539-1e0a6bb4-5317-4c6b-9201-ec5951d48919.png)

**Comment by YuriiMaiboroda** [comment]
Checked the log. The device did start sending dp 17 with the amount of kW*h. The application indicates 3.03, the device sends 3. I don’t know why it didn’t send before.
Well, it's good that it started to send. :)

**Comment by YuriiMaiboroda** [comment]
For dp 17, the total_increasing class is specified, but there the value is reset when data is sent to the server, which is why a warning appears in the log.
```
Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:382
Integration: Сенсор (documentation, issues)
First occurred: 08:35:10 (1 occurrences)
Last logged: 08:35:10

Entity sensor.plug_0_energy from integration tuya_local has state class total_increasing, but its state is not strictly increasing. Triggered by state 22 (23.0) with last_updated set to 2023-02-14T06:32:54.503182+00:00. Please report it to the custom integration author.
```

**Comment by make-all** [comment]
I'm confused about this state class. I thought it meant that Home Assistant would ignore resets to zero and keep adding for its long term statistics.  If it is just reporting errors because the device is resetting to zero, I don't really see the point of it.

**Comment by YuriiMaiboroda** [comment]
From [documentation](https://developers.home-assistant.io/docs/core/entity/sensor/#state-class-total_increasing)
> There is some tolerance, a decrease between state changes of < 10% will not trigger a new meter cycle.
Most likely at that time the new value was slightly less than the old one.

Since add_ele is not a value that is strictly increasing (each new message is approximately how much energy has been used since the previous message), then the class `total_increase` does not fit this entity. Since, if 50 was transmitted first, and then 55, then HA will consider this a change by 5, and will not add 55.

<details><summary>screenshot of add_ele chart (sorry not english)</summary>

![Screenshot_20230215_015932_Chrome](https://user-images.githubusercontent.com/47284191/218890608-5d624bb2-bb3d-4945-9a3f-18a0a9f46192.jpg)

</details>

**Comment by make-all** [comment]
I was going by [different documentation](https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes)

<html>
<body>


total_increasing | Similar to total, with the restriction that the state represents a monotonically increasing positive total which periodically restarts counting from 0, e.g. a daily amount of consumed gas, weekly water consumption or lifetime energy consumption. Statistics of the accumulated growth of the sensor's value since it was first added is updated every 5 minutes. A decreasing value is interpreted as the start of a new meter cycle or the replacement of the meter.
-- | --



</body>
</html>

**Comment by YuriiMaiboroda** [comment]
Below there are examples of using total_increase

Example of state class total_increasing:
|t|state|sum|
|-|--------|--------|
|2021-08-01T13:00:00|1000|0|
|2021-08-01T14:00:00|1010|10|
|2021-08-01T15:00:00|0|10|
|2021-08-01T16:00:00|5|15|

Example of state class total_increasing where the sensor does not reset to 0:
|t|state|sum|
|---|---|---|
|2021-08-01T13:00:00|1000|0|
|2021-08-01T14:00:001010|10|
|2021-08-01T15:00:00|5|15|
|2021-08-01T16:00:00|10|20|

As written - it works almost like a normal total, but when the value decreases, it considers it not a subtraction, but a start from 0 or ignores if the value has become a little less. This behavior is not appropriate for add_ele.

**Comment by make-all** [comment]
Why is it not appropriate for add_ele?  That seems exactly what we want from add_ele.  When it resets to 0, we want the sum to keep counting.

**Comment by YuriiMaiboroda** [comment]
Because it will behave like this:
|state|sum|
|---|---|
|500|500|
|400|900|
|450|950|

And it should be like this:
|state|sum|
|---|---|
|500|500|
|400|900|
|450|1350|

**Comment by make-all** [comment]
I don't see any suitable state class that would do that then.

To be honest, I haven't ever seen add_ele not reset to 0, but I guess you are testing under high loads, or your device has a low update frequency for add_ele.

**Comment by YuriiMaiboroda** [comment]
I manually summed the values of each point (every half an hour) for February 14 and got about 2709Wh. The Tuya Smart app indicates that 2.72Wh was used on February 14th. The values are very similar.

![plug_0_energy_2023-02-14 (Small)](https://user-images.githubusercontent.com/47284191/218905610-41490dce-60c4-4a93-a4db-4355ac2074e5.png)

**Comment by MayborodaYuriy** [comment]
I found that in cases where the device sends deltas, I need to use the [Utility Meter](https://www.home-assistant.io/integrations/utility_meter/).

**Comment by make-all** [comment]
My plan is to remove the energy and total_increasing markers from all devices except dedicated energy meters (which seem to function as expected).

It may be possible for them to work correctly if marked with "total" and "last_reset" instead, but there seems to be variation in the exact working of "add_ele" attributes of Tuya devices, so it cannot be guaranteed that all devices will work with that, and "last_reset" support would involve tracking update times for individual dps separately which is not currently done, and marking somehow which dps provide reset readings on every update.

**Comment by YuriiMaiboroda** [comment]
There are no more warnings about invalid values.
It is still possible to try to add a device to the energy panel (because the unit of change is kW), but this will not work (because the "energy" class has been removed).
![image](https://user-images.githubusercontent.com/47284191/219426274-69ac56dd-6ac0-40da-bafe-28f14659ae18.png)
The Riemann Integral by Power helper seems to be working fine (except #420).

I think it works as expected now. Task can be closed.

**Comment by rleongcs** [comment]
> There are no more warnings about invalid values. It is still possible to try to add a device to the energy panel (because the unit of change is kW), but this will not work (because the "energy" class has been removed). ![image](https://user-images.githubusercontent.com/47284191/219426274-69ac56dd-6ac0-40da-bafe-28f14659ae18.png) The Riemann Integral by Power helper seems to be working fine (except #420).
> 
> I think it works as expected now. Task can be closed.

Hi...I think I am having a similar issue as @YuriiMaiboroda that I can't seems to be able to add my Energy Smart Plug to the energy panel even though it has all the details as shown below.

![image](https://user-images.githubusercontent.com/61628312/219959417-6c52bf76-8404-4f02-b939-50757f3e5fb3.png)

How do I go about setting it up so I can have it in the energy panel?

**Comment by YuriiMaiboroda** [comment]
@rleongcs 
You need to create a [Riemann integral](https://www.home-assistant.io/integrations/integration/).
Select Power as the sensor.

**Comment by rleongcs** [comment]
@YuriiMaiboroda I managed to setup the "Riemann sum integral sensor" helper and got a sensor as below. Unfortunately it is still not appearing in the energy panel. Not sure what I did wrong?

![image](https://user-images.githubusercontent.com/61628312/220037797-6bdbdae2-b642-4a5a-813d-0f241a6097e5.png)

**Comment by YuriiMaiboroda** [comment]
> @YuriiMaiboroda I managed to setup the "Riemann sum integral sensor" helper and got a sensor as below. Unfortunately it is still not appearing in the energy panel. Not sure what I did wrong?
> 
> ![image](https://user-images.githubusercontent.com/61628312/220037797-6bdbdae2-b642-4a5a-813d-0f241a6097e5.png)

@rleongcs I don't know. Maybe you just need to wait a bit.
> After setting up a new device, it can take up to 2 hours for new data to arrive in your energy dashboard

I have the same integral settings
![Screenshot_20230220_093752_Chrome](https://user-images.githubusercontent.com/47284191/220042999-f00c1a7d-10f6-44d5-b37b-bd4dc229b1bd.jpg)
And the integral is in the list of devices that can be added to the electricity panel
![Screenshot_20230220_093958_Chrome](https://user-images.githubusercontent.com/47284191/220043003-f09fc90e-b05f-497a-9d95-5d00de2c6a3d.jpg)

**Comment by rleongcs** [comment]
@YuriiMaiboroda I guess I will wait a while and see or experiment more. Thanks a lot.
