### ISSUE TITLE
Request support for [Wifi Digital Meter PJ-1103 Power Meter]

### ISSUE THREAD

**Issue by Casadomoticap** [make-all/tuya-local#395]
Hi! This issue is related to: https://github.com/make-all/tuya-local/issues/336 because this new device should be supported but with the version 2023.2.0 it is still appearing the message "not supported" when I try to configure it. 

The Wifi digital meter is the model PJ-1103 (from official Tuya integration log): https://es.aliexpress.com/item/1005004845740618.html?spm=a2g0o.productlist.main.1.22e64b33CJcBNI&algo_pvid=0d067b7d-d10d-482f-95cd-652272528a10&algo_exp_id=0d067b7d-d10d-482f-95cd-652272528a10-0&pdp_ext_f=%7B%22sku_id%22%3A%2212000030723786342%22%7D&pdp_npi=3%40dis%21EUR%2151.11%2122.49%21%21%21%21%21%402100b1a616762247804122139d06f8%2112000030723786342%21sea%21ES%21843820519&curPageLogUid=OMfwKYABRD8M

# Log Message

"Sorry, the device is not supported"

# Information about DPS mappings

Description - DP ID - Example - Unit

Add Ele - 17 - 0.16kW·h - Kw/h
Cur Current - 18 - 2937mA - mA
CUR Power - 19 - 618.60W - W
Max Standby power - 51 -
Cur Voltage - 20 - 227.40V - V
Max Power - 52 -
Test Bit - 21 -
Voltage Coe - 22 -
Electric Coe - 23 -
Power Coe - 24 -
Electricity Coe - 25 -
Fault - 26 -

# Product ID

 "product_id": "djfep9s6s3b2qk89"

# Information about how the device functions

**Comment by make-all** [comment]
I guess from the output above that the Max standby power is not being reported by your device, but was required by the config.  I have marked this optional and also added some other attributes from your list that were missing from the config as optional attributes.

**Comment by make-all** [comment]
Did you redownload the tuya_local integration from "main" branch?  As this is still unreleased, you will need to do that to test it now.  If you use HACS, there is a Redownload menu item on the right side of the Tuya Local listing in HACS.   If you choose that, there is a version selection, which has some recent versions, and "main" at the bottom of the list.  After selecting "main", wait for the list to become active again after it has downloaded the info for the update, then press the download button.

**Comment by Casadomoticap** [comment]
You'r right, I follow you'r steps in HACS and now it is working :) 
You'r the best! Thank you a lot. 

One more question, so in the next release it will be solved right? So I will can update the version in the future.

**Comment by make-all** [comment]
Yes, HACS will keep prompting you to upgrade, since now you are not on the "latest release", but as long as it is offering 2023.2.0, please ignore it.  Once I release 2022.2.1, which I plan to do tonight, after clearing the backlog of requests it will be supported.

**Comment by Casadomoticap** [comment]
Nice @make-all :) 

One more think that maybe helps you to clearing backlog, I have this Alerts in LOGs about this project: 

**1- Error about this clamp_power_meter_energy:**

Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:677
Integration: Sensor (documentation, issues)
First occurred: 11:09:59 (1 occurrences)
Last logged: 11:09:59

Entity sensor.clamp_power_meter_energy (<class 'custom_components.tuya_local.sensor.TuyaLocalSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('energy') it is using; expected one of ['Wh', 'MJ', 'MWh', 'kWh', 'GJ']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author. 


**2- Error handling request**
Este error se originó a partir de una integración personalizada.

Logger: aiohttp.server
Source: custom_components/tuya_local/device.py:69
Integration: Tuya Local (documentation, issues)
First occurred: 11:12:52 (1 occurrences)
Last logged: 11:12:52

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 145, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 253, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/tuya_local/config_flow.py", line 41, in async_step_user
    self.device = await async_test_connection(user_input, self.hass)
  File "/config/custom_components/tuya_local/config_flow.py", line 175, in async_test_connection
    device = TuyaLocalDevice(
  File "/config/custom_components/tuya_local/device.py", line 69, in __init__
    self._api = tinytuya.Device(dev_id, address, local_key)
  File "/usr/local/lib/python3.10/site-packages/tinytuya/core.py", line 732, in __init__
    raise Exception("Unable to find device on network (specify IP address)")
Exception: Unable to find device on network (specify IP address)


**3- blocking call**

Logger: homeassistant.util.async_
Source: util/async_.py:182
First occurred: 11:09:29 (2 occurrences)
Last logged: 11:09:54

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 69: self._api = tinytuya.Device(dev_id, address, local_key)


**4- Duplicate key unit**

Logger: homeassistant.util.yaml.loader
Source: util/yaml/loader.py:164
First occurred: 11:09:34 (1 occurrences)
Last logged: 11:09:34

YAML file /config/custom_components/tuya_local/devices/hdmi_sync_light.yaml contains duplicate key "unit". Check lines 101 and 106


I hope to help you :)

**Comment by make-all** [comment]
1. I will fix in the next release.
2. Seems to be a problem with the Auto address detection not working for that device, or your network.  Maybe I can catch it and provide a more informative message I guess.
3. Known issue with Auto address detection, since this is in the tinytuya library, and they have rejected making the library async, there is not much I can do for now.
4. Will check this and fix in the next release.

**Comment by Casadomoticap** [comment]
Great, Thank you a lot! :)

**Comment by Casadomoticap** [comment]
The main issue of this is solved, the device Wifi Digital Meter PJ-1103 Power Meter is working :) 

You can close the issue if you don't need the other bugs information. Thank you a lot

**Comment by make-all** [comment]
Thanks.  I'm leaving it open for now to track the three issues that I have fixes for (1, 2, 4)

**Comment by GregTB1** [comment]
Hello everyone, I have a problem with Tuya Smart Energy Meter. It is a socket model S1WP. Works like a charm with Smart Life, google Home and alexa for the socket On/OFF. 
In Localtuya, it is a little tricky. I can see the switch state on or off but the button is not effectively turning on the current. Ans after a day, all the localtuya sensors are unavailable. I need to understand what is this f****g Chinese socket ? Do you manage to turn ON/OFF locally more than 24 hours ?
Thans for your help !

**Comment by semkyskov** [comment]
Is it possible to add device_class for _energy?

**Comment by make-all** [comment]
There is no suitable sensor to add that class to.  The add_ele dp from Tuya devices does not act as expected, so is not suitable for use as an energy sensor.  Instead, use an Integration helper on the power sensor to calculate energy usage.  Others have also reported success using the Utility meter integration with the energy sensor, but I don't have much knowledge of that, and different devices act differently, so it may not be suitable for all devices.

**Comment by nthulke** [comment]
Did anyone have luck adding this as an engery meter? I have one attached to my old solar invenrtor and I want to add it to my dashboard.

**Comment by make-all** [comment]
See the comment above yours.

**Comment by Den612** [comment]
Добрый день, подключил PJ-1103 все работало ровно неделю, но вчера все отвалилось . В самом приложении tuya- работает. Манипуляции с разными версиями tuya local и версиями протокола не помогают. В данный момент установлена Home Assistant 2023.9.2 Supervisor 2023.09.0.dev0102 и Tuya Local 2023.9.0. подскажите как возможно исправить данную проблему? Спасибо!

**Comment by semkyskov** [comment]
> Добрый день, подключил PJ-1103 все работало ровно неделю, но вчера все отвалилось . В самом приложении tuya- работает. Манипуляции с разными версиями tuya local и версиями протокола не помогают. В данный момент установлена Home Assistant 2023.9.2 Supervisor 2023.09.0.dev0102 и Tuya Local 2023.9.0. подскажите как возможно исправить данную проблему? Спасибо!

Удали полностью и подключи снова.

**Comment by Reibeiro2017** [comment]
![dual meter](https://github.com/make-all/tuya-local/assets/109174594/aa6fd97c-7bcf-4ef7-bc7d-51195b7bf480)
how to know the sensors?
Current (mA)
Energy (kWh)
Power (w)
Voltage (V)

**Comment by JalimRabava** [comment]
Yes, using Tuya Local (not  the local tuya) as a custom repository in Hacs. It needs the protocol 3.5 that is available only on Tuya Local.
