### ISSUE TITLE
Request support for Skyfan DC Tuya Wifi Module

### ISSUE THREAD

**Issue by ruaandeysel** [make-all/tuya-local#396]
It would be awesome to get support for the Skyfan DC Fans Tuya Wifi Module

# Information about DPS mappings

<google-sheets-html-origin style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">

DPID | Description | Example
-- | -- | --
1 | Power | ON or OFF
2 | Mode | NORMAL, NATURE or SLEEP
3 | Fan Speed | 1,2,3,4 or 5
22 | Timer | 1 Hour
8 | Direction | FORWARD or REVERSE

</google-sheets-html-origin>

# Product ID

vzj97d3m05yjhchn

Let me know if you need any other info.

**Comment by make-all** [comment]
Please provide the log messages that show the original data format at the protocol level.

**Comment by ruaandeysel** [comment]
Hello, is this what you are looking for?

Code | Type | Values
-- | -- | --
switch | Boolean | "{true,false}"
fan_speed_percent | Integer | {   "min": "1",   "max": "5",   "scale": "0",   "step": "1" }
mode | Enum | {   "range": [     "nature",     "sleep",     "smart"   ] }
fan_direction | Enum | {   "range": [     "forward",     "reverse"   ] }
countdown_set | Enum | {   "range": [     "cancel",     "1h",     "2h",     "3h",     "4h",     "5h",     "6h",     "7h",     "8h",     "9h",     "10h",     "11h",     "12h"   ] }

Were do I find the log messages that show the original data format at the protocol level?

**Comment by make-all** [comment]
In the Home Assistant log (Settings / System / Log), after you attempt to add the device and there is not an exact match.

**Comment by ruaandeysel** [comment]
@make-all I found this

{
  "result": {
    "category": "fs",
    "functions": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_speed_percent",
        "type": "Integer",
        "values": "{\"min\":\"1\",\"max\":\"5\",\"scale\":\"0\",\"step\":\"1\"}"
      },
      {
        "code": "mode",
        "type": "Enum",
        "values": "{\"range\":[\"nature\",\"sleep\",\"smart\"]}"
      },
      {
        "code": "fan_direction",
        "type": "Enum",
        "values": "{\"range\":[\"forward\",\"reverse\"]}"
      },
      {
        "code": "countdown_set",
        "type": "Enum",
        "values": "{\"range\":[\"cancel\",\"1h\",\"2h\",\"3h\",\"4h\",\"5h\",\"6h\",\"7h\",\"8h\",\"9h\",\"10h\",\"11h\",\"12h\"]}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_speed_percent",
        "type": "Integer",
        "values": "{\"min\":\"1\",\"max\":\"5\",\"scale\":\"0\",\"step\":\"1\"}"
      },
      {
        "code": "mode",
        "type": "Enum",
        "values": "{\"range\":[\"nature\",\"sleep\",\"smart\"]}"
      },
      {
        "code": "fan_direction",
        "type": "Enum",
        "values": "{\"range\":[\"forward\",\"reverse\"]}"
      },
      {
        "code": "countdown_set",
        "type": "Enum",
        "values": "{\"range\":[\"cancel\",\"1h\",\"2h\",\"3h\",\"4h\",\"5h\",\"6h\",\"7h\",\"8h\",\"9h\",\"10h\",\"11h\",\"12h\"]}"
      }
    ]
  },
  "success": true,
  "t": 1676269943263,
  "tid": "2ca37033ab6811ed9a310aeeb3bc8fba"
}

**Comment by make-all** [comment]
These look more likely than the original uppercase values.  But sometimes at the protocol level, the "nature", "sleep", "smart" will get replace by "0", "1", "2", so I also want to double check those.

**Comment by ruaandeysel** [comment]
> In the Home Assistant log (Settings / System / Log), after you attempt to add the device and there is not an exact match.

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/tuya_local/device.py:69 
Integration: Tuya Local (documentation, issues) 
First occurred: 4:36:50 PM (1 occurrences) 
Last logged: 4:36:50 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 145, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 253, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/tuya_local/config_flow.py", line 41, in async_step_user
    self.device = await async_test_connection(user_input, self.hass)
  File "/config/custom_components/tuya_local/config_flow.py", line 175, in async_test_connection
    device = TuyaLocalDevice(
  File "/config/custom_components/tuya_local/device.py", line 69, in __init__
    self._api = tinytuya.Device(dev_id, address, local_key)
  File "/usr/local/lib/python3.10/site-packages/tinytuya/core.py", line 727, in __init__
    bcast_data = find_device(dev_id)
  File "/usr/local/lib/python3.10/site-packages/tinytuya/core.py", line 524, in find_device
    client.bind(("", UDPPORT))
OSError: [Errno 98] Address in use

**Comment by make-all** [comment]
This error seems to occur when you have localtuya installed, and set your IP address to Auto.  The "Auto" ip address setting requires access to the tuya discovery port, but localtuya has already claimed it.

If you set your IP address explicitly, it should get past that and output a message with the DPS values received from the device when it cannot find an exact match.

**Comment by ruaandeysel** [comment]
> This error seems to occur when you have localtuya installed, and set your IP address to Auto. The "Auto" ip address setting requires access to the tuya discovery port, but localtuya has already claimed it.
> 
> If you set your IP address explicitly, it should get past that and output a message with the DPS values received from the device when it cannot find an exact match.

I tried to explicitly set IP address of the Tuya device and getting this

This error originated from a custom integration.

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:291 
Integration: tuya_local (documentation, issues) 
First occurred: 4:41:04 PM (1 occurrences) 
Last logged: 4:41:04 PM

Failed to refresh device state for Test.

**Comment by make-all** [comment]
I've made a config based on the information available, there is a good chance that it will work, but if it doesn't when you eventually sort out the connection issue to your device (which may be one of the other config settings, or perhaps the protocol version is not being detected correctly, and needs to be set manually if you know it -  if it is 3.4, then there appears to be a bug in the underlying library that makes communication intermittent, quite likely affecting 3.5 as well), then I will need to local log messages to debug the issue then.

**Comment by ruaandeysel** [comment]
> I've made a config based on the information available, there is a good chance that it will work, but if it doesn't when you eventually sort out the connection issue to your device (which may be one of the other config settings, or perhaps the protocol version is not being detected correctly, and needs to be set manually if you know it - if it is 3.4, then there appears to be a bug in the underlying library that makes communication intermittent, quite likely affecting 3.5 as well), then I will need to local log messages to debug the issue then.

Thank you. It's working without issues. 

I had to remove local tuya integration completely as it caused auto discovery of devices on network to fail.
