### ISSUE TITLE
AlecoAir D12 Home is not detelcted

### ISSUE THREAD

**Issue by romicaiarca** [make-all/tuya-local#397]
**Describe the bug**
AlecoAir D12 Home is not detelcted properly.

**To Reproduce**
Try to add new device setting: Device id = dehumidifier_id, IP address = dehumidifier_ip_address, local key = dehumidifier_local_key and protocol=auto.

Here is the error that I can see:
```
Device matches garage_door_opener with quality of 18%. DPS: {'updated_at': 1676254822.5699, '1': False, '2': '1', '3': 68, '4': 30, '5': False, '6': '1', '7': True, '11': 0, '12': '0', '13': 0, '101': False}
Report this to https://github.com/make-all/tuya-local/issues/
```

```
Logger: homeassistant
Source: custom_components/localtuya/discovery.py:67
Integration: LocalTuya ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 4:20:21 AM (2 occurrences)
Last logged: 4:20:26 AM

Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/config/custom_components/localtuya/discovery.py", line 65, in datagram_received
    data = decrypt_udp(data)
  File "/config/custom_components/localtuya/discovery.py", line 30, in decrypt_udp
    return _unpad(decryptor.update(message) + decryptor.finalize()).decode()
  File "/usr/local/lib/python3.10/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 186, in finalize
    data = self._ctx.finalize()
  File "/usr/local/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 222, in finalize
    raise ValueError(
ValueError: The length of the provided data is not a multiple of the block length.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 1027, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/config/custom_components/localtuya/discovery.py", line 67, in datagram_received
    data = data.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 10: invalid start byte
```

**Expected behavior**
To detect alecoair d12 home as option

**Screenshots**

<img width="396" alt="Screenshot 2023-02-13 at 04 23 01" src="https://user-images.githubusercontent.com/1266110/218356429-1bfccfc6-933c-46be-96d6-14db6933b3dd.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome 
 - Version 110.0.5481.77 (Official Build) (x86_64)

**Additional context**

**Comment by make-all** [comment]
I have already made some changes to the config, including fixing some inconsistencies around dps 5 and 6 in the original config.

Please try updating to latest main version.

**Comment by romicaiarca** [comment]
> I have already made some changes to the config, including fixing some inconsistencies around dps 5 and 6 in the original config.
> 
> Please try updating to latest main version.

I've made some changes on my version so everything works fine for my hardware (all functions as they are in reality) in https://github.com/make-all/tuya-local/pull/398

Also I've tested your code from main and I've described int this comm all issues that I've noticed: https://github.com/make-all/tuya-local/pull/398#issuecomment-1427295911
