### ISSUE TITLE
Request for new device - Fanco Eco Silent Deluxe Ceiling Fan with LED Light CFFCESD3LWHSMRABS

### ISSUE THREAD

**Issue by dezinc57** [make-all/tuya-local#399]
Requesting device support for Fanco Eco Silent Deluxe DC Smart Ceiling Fan with LED Light

Fan switch is currently discoverable in Tuya Local as simple_switch only

# **Information about DPS mappings**

{
  "result": {
    "category": "fs",
    "functions": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_speed_percent",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"min\":\"1\",\"max\":\"6\",\"scale\":\"0\",\"step\":\"1\"}"
      },
      {
        "code": "light",
        "dp_id": 15,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "bright_value",
        "dp_id": 16,
        "type": "Integer",
        "values": "{\"min\":\"10\",\"max\":\"1000\",\"scale\":\"0\",\"step\":\"1\"}"
      },
      {
        "code": "temp_value",
        "dp_id": 17,
        "type": "Integer",
        "values": "{\"min\":\"0\",\"max\":\"1000\",\"scale\":\"0\",\"step\":\"1\"}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_speed_percent",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"min\":\"1\",\"max\":\"6\",\"scale\":\"0\",\"step\":\"1\"}"
      },
      {
        "code": "light",
        "dp_id": 15,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "bright_value",
        "dp_id": 16,
        "type": "Integer",
        "values": "{\"min\":\"10\",\"max\":\"1000\",\"scale\":\"0\",\"step\":\"1\"}"
      },
      {
        "code": "temp_value",
        "dp_id": 17,
        "type": "Integer",
        "values": "{\"min\":\"0\",\"max\":\"1000\",\"scale\":\"0\",\"step\":\"1\"}"
      }
    ]
  },
  "success": true,
  "t": 1676261554171,
  "tid": "a4586334ab5411ed9a310aeeb3bc8fba"
}

# Product ID

{
  "result": {
    "category": "fs",
    "category_name": "Fan",
    "model": "MZ-DCFAN",
    "product_id": "agyqzsfpafsvkrl9",
    "product_name": "DC吊扇",
  },

# Information about how the device functions

Fan has On/Off, 6 speeds, timer, forward & reverse
LED Light has On/Off, dimmable brightness, color temp selection

Product link: https://www.fanco.com.au/product/eco-silent-deluxe-dc-abs-blades-ceiling-fan-smart-remote-with-cct-led-white-52/

Manual link: https://www.fanco.com.au/wp-content/uploads/manuals/esd-manual.pdf

Smart App guide: https://www.fanco.com.au/wp-content/uploads/manuals/fanco-smart-ceiling-fan-manual.pdf

**Comment by make-all** [comment]
The info above seems incomplete:

> Fan has On/Off, 6 speeds, timer, forward & reverse

The above info contains only on/off and 6 speeds.  No forward/reverse or timer function.

**Comment by make-all** [comment]
Anyway, I have implemented a preliminary version without forward/reverse or timer support as a first step.

**Comment by dezinc57** [comment]
Just removed and re added the device, no error - just discovered as simple switch, with this log message:

Device matches simple_switch with quality of 11%. DPS: {'updated_at': 1676177547.4074905, '1': False, '2': 'normal', '3': 2, '8': 'forward', '15': False, '16': 1000, '17': 220, '22': '0', '24': 0}
Does this help ?
May be the case that the other functions are only supported by the remote ???

**Comment by make-all** [comment]
Yes that helps.  Did you update the tuya_local integration to use "main" (Redownload from the HACS menu, then select "main" and wait for the select box to reactivate before pressing Download)?  The DPS list looks like it should match the config I made, though it is not a complete match, due to the dps for the other functions, plus some more

2: "normal" - not sure, probably related to the fan
8: "forward" - this will be the "forward"/"reverse" function
22: "0" - not sure.  It might be related to the timer, as some timers have a separate set and remaining dp
24: 0 - should be the timer, but as above, it might be necessary to set it through dp 22.

If I can see the interface for the timer, I can probably tell what type of timer it is, and therefore whether dp 22 is the timer, or something else.

**Comment by make-all** [comment]
The manual provides some answers

"normal" and "natural" wind modes
timer is a fixed list of "Cancel", "1H", "2H", "3H", "4H", which suggests that dp 22 is for setting the timer, and dp 24 will just be feeding back the remaining time.

**Comment by dezinc57** [comment]
Thankyou, 
Updated the tuya_local integration and added device.
Have Fan On/Off and Speed
Have Light On/Off, brightness and color temp - however actual color temp on device is reveresed to that of the slider display in HA

**Comment by dezinc57** [comment]
Updated tuya-local to 2023.2.1, can confirm device entities work correctly.
Thankyou for adding this device.
