### ISSUE TITLE
dimmer.

### ISSUE THREAD

**Issue by Securond** [make-all/tuya-local#4]
Hi, Can I add another device? Dimmer for Led strip.
Standard Function Set:
Code                 | Type      | Values

switch_led         | Boolean | {true,false}
work_mode       | Enum     | {"range":["white","colour","scene","music"]}
bright_value_v2 | Integer  | {"min":10,"scale":0,"unit":"","max":1000,"step":1}
scene_data_v2   | Json       | {}
countdown_1    | Integer   | {"unit":"","min":0,"max":86400,"scale":0,"step":1}
control_data     | Json        | {}
 
Standard State Set:
Code	                Type	Values

switch_led	        Boolean	{true,false}
work_mode	        Enum	{"range":["white","colour","scene","music"]}
bright_value_v2	Integer	{"min":10,"scale":0,"unit":"","max":1000,"step":1}
scene_data_v2 	Json	{}
countdown_1	        Integer	{"unit":"","min":0,"max":86400,"scale":0,"step":1}
control_data	        Json	        {}
   
I would appreciate your help.

**Comment by make-all** [comment]
I'm currently working on making it easier to add new devices as yaml file configurations.
One essential piece of information missing from your analysis is the dps id.

**Comment by Securond** [comment]
> dps id.

dps id ? There is a Device ID:, Product ID, owner_id, uid. Where can I view "dps id"?

**Comment by make-all** [comment]
I don't know where you are looking, but the schema has it as "id", and in the protocol it is "dps".

**Comment by Securond** [comment]
This is the result of the request -  {{url}}/v1. 0/devices/{{device_id}} :

{
    "result": {
        "active_time": 1600188918,
        "biz_type": 0,
        "category": "dj",
        "create_time": 1599980072,
        "icon": "smart/icon/ay1511658812948sYzut/128eca53fe9f9498bfa4e852b5f397e4.png",
        "id": "50006075a4cf12e6d8b7",
        "ip": "XXX.XXX.XXX.XXX",
        "local_key": "XXXXXXXXXXXXX",
        "name": "Light",
        "online": true,
        "owner_id": "8422602",
        "product_id": "b3rzqnxq8w8dfmlc",
        "product_name": "AM-WIFI-WW",
        "status": [
            {
                "code": "scene_data_v2",
                "value": ""
            },
            {
                "code": "countdown_1",
                "value": 0
            },
            {
                "code": "switch_led",
                "value": false
            },
            {
                "code": "work_mode",
                "value": "white"
            },
            {
                "code": "control_data",
                "value": ""
            },
            {
                "code": "bright_value_v2",
                "value": 1000
            }
        ],
        "sub": false,
        "time_zone": "+03:00",
        "uid": "eu15765748060481yeIL",
        "update_time": 1600190749,
        "uuid": "50006075a4cf12e6d8b7"
    },
    "success": true,

**Comment by make-all** [comment]
You seem to be using the tuya web service interface.
This component is for direct communication with tuya devices.
The web interface is used by the built in tuya component (at https://github.com/home-assistant/core)

**Comment by Securond** [comment]
Yes, I use the web interface, because my device is not supported by "local taya", so I wrote to You. I apologize if I explain it poorly, I translate it from Russian.

**Comment by make-all** [comment]
So the dps id, which is needed for mapping those fields in the web ui onto the actual device, can be found by either:
1. Looking in the phone filesystem for the app's data directory, and finding the schema for the device in there.
2. Using tuya-cli to query the device for its status.
3. If the device is using protocol version 3.1, you can eavesdrop on the first message the device sends when the app is opened. (in protocol version 3.1 the first message is unencrypted, but in version 3.3 the first message is encrypted, so you will need tuya-cli to decrypt it)

**Comment by Securond** [comment]
Thank you, I will learn how to use "tuya-cli" and send you the necessary "dps".

**Comment by Securond** [comment]
dps: { '20': false, '21': 'white', '22': 1000, '26': 0 }

**Comment by Securond** [comment]
Hi, is there any news on dimmer?

**Comment by make-all** [comment]
I am in the middle of a refactor to make adding new devices easier, and not a lot of time to spend, so it could be some time before I add any new devices.

**Comment by Securond** [comment]
it turned out to add a dimmer through the localtuya-homeassistant integration
https://github.com/rospogrigio/localtuya-homeassistant/
