### ISSUE TITLE
Request support for Ebac 4000 Series Dehumifiers

### ISSUE THREAD

**Issue by Clam58** [make-all/tuya-local#402]
# Log Message

I’ve attached the yaml file I’ve used to set up this device in HA using your 2023.2.0 version, but I had to change its extension to .txt as it wouldn’t accept .yaml. 

The user manual for this device (4000 series) can be found [here](https://www.ebac.com/support/user-manuals)

# Information about DPS mappings

DPID | Description | Example | unit
-- | -- | -- | --
1 | Device switch | On | binary
2 | Dehumidify Set Value | 50% | %
4 | Speed (Fan) | Low, High | List
5 | Mode | Smart | List
6 | Humidity | 43% | %
7 | Temperature | 15C | C
9 | Defrost | Off (not implemented) | binary
13 | UV | Off (not implemented) | binary
17 | Countdown | Continuous,4h | List
18 | Time Left | 0min, 239min | min
19 | Fault | 0 (probably not implemented) | E1-E4
20 | Filter Reset | On (set Filter Life back to 100%) | binary
23 | Filter Life | 50% | %
27 | Runtime | 0min (never changes from 0, probably not implemented) | min
28 | Reset Runtime | On but see above | binary
30 | Bright Value | Reported LED display brightness either 2 (night)or 5(normal). Can’t be set. | %
101 | Night | On (dims display and sets fan to low) | binary
102 | Bucket | BUCKET_Full,BUCKET_OK | enum
103 | Fan State | On (can’t be set but does change to reflect whether fan is on or not.) | binary

Structures from Tuya iot
{
  "result": {
    "category": "cs",
    "functions": [
      {
        "code": "switch",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "dehumidify_set_value",
        "lang_config": {
          "unit": "%"
        },
        "name": "Dehumidify Set Value\t",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":35,\"max\":80,\"scale\":0,\"step\":5}"
      },
      {
        "code": "fan_speed_enum",
        "lang_config": {
          "high": "High",
          "low": "Low"
        },
        "name": "Speed",
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"high\"]}"
      },
      {
        "code": "mode",
        "lang_config": {
          "boost": "",
          "dehumidify": "Smart",
          "drying": "Drying",
          "manual": "Target"
        },
        "name": "Mode",
        "type": "Enum",
        "values": "{\"range\":[\"dehumidify\",\"drying\",\"boost\",\"manual\"]}"
      },
      {
        "code": "defrost",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Defrost",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "uv",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "UV",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_set",
        "lang_config": {
          "1h": "1h",
          "2h": "2h",
          "3h": "3h",
          "4h": "4h",
          "5h": "5h",
          "6h": "6h",
          "7h": "7h",
          "8h": "8h",
          "cancel": "Continuous"
        },
        "name": "Countdown",
        "type": "Enum",
        "values": "{\"range\":[\"cancel\",\"1h\",\"2h\",\"3h\",\"4h\",\"5h\",\"6h\",\"7h\",\"8h\"]}"
      },
      {
        "code": "filter_reset",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Filter Reset",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "runtime_total_reset",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Reset(Runtime)",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "bright_value",
        "lang_config": {
          "unit": "%"
        },
        "name": "Bright Value",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":10}"
      },
      {
        "code": "night1",
        "lang_config": {
          "false": "",
          "true": ""
        },
        "name": "Night",
        "type": "Boolean",
        "values": "{}"
      }

My yaml file:
     
[ebac_dj4000_dehumidifier.txt](https://github.com/make-all/tuya-local/files/10722389/ebac_dj4000_dehumidifier.txt)

**Comment by Clam58** [comment]
Device is found correctly in 2023.2.2 and functions as I’d expect.
Thanks for adding this in so quickly, much appreciated.

I do have a query about the use of icons for the various dehumidifier modes. I selected mdi equivalents to match the icons used by the ebac app e.g.

    - id: 5
      name: mode
      type: string
      mapping:
        - dps_val: dehumidify
          value: Smart
          icon: "mdi:alpha-s-circle-outline"
          icon_priority: 1
        - dps_val: drying
          value: Laundry
          icon: "mdi:tshirt-crew-outline"
          icon_priority: 3
        - dps_val: manual
          value: Target
          icon: "mdi:bullseye"
          icon_priority: 3
        - dps_val: boost
          value: Boost
          icon: "mdi:rocket-launch-outline"
          icon_priority: 3
          
But I notice you changed  this, is this to meet HA guidelines or other standard? I found it useful to have these as they change with the mode, and I don’t see an easy way to replicate this behaviour in the ui.

Thanks

**Comment by make-all** [comment]
It is to meet HA guidelines.  Dynamic icons seemed like a good idea when I started this, but I have since become aware that they interfere with HA's theming support.
