### ISSUE TITLE
Request support for Czajnik Setti+ KT950W

### ISSUE THREAD

**Issue by spitfire** [make-all/tuya-local#403]
# Log Message

`2023-02-13 14:35:16.681 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches bwt_heatpump with quality of 29%. DPS: {'updated_at': 1676295315.7473915, '1': False, '2': 27, '3': 80, '4': '40', '5': '104', '6': '40', '7': '104', '8': 40, '9': 104, '10': 40, '11': 104, '12': 'c', '13': False, '14': 30, '15': 'standby', '16': 'temp_setting', '19': 0}`

# Information about DPS mappings

```
{
  "result": {
    "category": "bh",
    "functions": [
      {
        "code": "start",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_setting_quick_c",
        "type": "Enum",
        "values": "{\"range\":[\"85\"]}"
      },
      {
        "code": "temp_setting_quick_f",
        "type": "Enum",
        "values": "{\"range\":[\"185\"]}"
      },
      {
        "code": "temp_boiling_quick_c",
        "type": "Enum",
        "values": "{\"range\":[\"85\",\"100\"]}"
      },
      {
        "code": "temp_boiling_quick_f",
        "type": "Enum",
        "values": "{\"range\":[\"185\",\"212\"]}"
      },
      {
        "code": "temp_set",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_set_f",
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":32,\"max\":212,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_boiling_c",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_boiling_f",
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":32,\"max\":212,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_unit_convert",
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "warm",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "warm_time",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":360,\"scale\":0,\"step\":1}"
      },
      {
        "code": "work_type",
        "type": "Enum",
        "values": "{\"range\":[\"setting_quick\",\"boiling_quick\",\"temp_setting\",\"temp_boiling\"]}"
      }
    ],
    "status": [
      {
        "code": "start",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_current",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_current_f",
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":32,\"max\":212,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_setting_quick_c",
        "type": "Enum",
        "values": "{\"range\":[\"85\"]}"
      },
      {
        "code": "temp_setting_quick_f",
        "type": "Enum",
        "values": "{\"range\":[\"185\"]}"
      },
      {
        "code": "temp_boiling_quick_c",
        "type": "Enum",
        "values": "{\"range\":[\"85\",\"100\"]}"
      },
      {
        "code": "temp_boiling_quick_f",
        "type": "Enum",
        "values": "{\"range\":[\"185\",\"212\"]}"
      },
      {
        "code": "temp_set",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_set_f",
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":32,\"max\":212,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_boiling_c",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_boiling_f",
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":32,\"max\":212,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_unit_convert",
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "warm",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "warm_time",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":360,\"scale\":0,\"step\":1}"
      },
      {
        "code": "status",
        "type": "Enum",
        "values": "{\"range\":[\"standby\",\"heating\",\"cooling\",\"warm\",\"heating_temp\",\"boiling_temp\",\"reserve_1\",\"reserve_2\",\"reserve_3\"]}"
      },
      {
        "code": "work_type",
        "type": "Enum",
        "values": "{\"range\":[\"setting_quick\",\"boiling_quick\",\"temp_setting\",\"temp_boiling\"]}"
      }
    ]
  },
  "success": true,
  "t": 1676295572422,
  "tid": "d8cc1a4baba311ed9de742b33a3cd862"
}
```
# Product ID

```
{
  "result": {
    "active_time": 1669111637,
    "category": "bh",
    "category_name": "Smart Kettle",
    "create_time": 1669111637,
    "gateway_id": "",
    "icon": "smart/icon/ay1578885126041ps8K2/eecc96a059fba5b5df4c68387371c91b.png",
    "id": "bf33b66314f3c0e062vtnt",
    "ip": "redacted",
    "lat": "redacted",
    "local_key": "redacted",
    "lon": "redacted",
    "model": "D2818EWB",
    "name": "Czajnik Setti+ KT950W",
    "online": true,
    "owner_id": "71836261",
    "product_id": "rsygyyeiyarl4urt",
    "product_name": "Smart kettle Setti+ KT950W",
    "sub": false,
    "time_zone": "+01:00",
    "update_time": 1669394914,
    "uuid": "d1139a23a90a643e"
  },
  "success": true,
  "t": 1676295824080,
  "tid": "6eccb786aba411edbe05a63cfb33a057"
}
```

# Information about how the device functions

https://setti.pl/produkty/kuchnia/czajniki/czajnik-kt950w-smart-sterowanie-smartfonem-regulacja-temperatury-zimna-obudowa

A 1,7l kettle which besides just boiling water allows to set a specific temperature to warm up to and lets the user hold temperature for a specified amount of time. has DPs displaying temperature in both Celsius and Fahrenheit, since it is a product distributed in Poland it should default to Celsius.

**Comment by spitfire** [comment]
For whatever reason after updating integration to the latest version double checked that /config/custom_components/tuya_local/devices/setti_czajnik_kettle.yaml is in there) and restarting HA the set up of the kettle doesn't proceed properly. It doesn't suggest the preset you've created (instead it proposes to use BWT_heatpump as before), and it's not even on the list of possible templates to assign to this device.

**Comment by make-all** [comment]
Please check the log message again.
We had similar problems with the Kogan kettle, it appears to send different dps depending on what state it is in.

**Comment by spitfire** [comment]
```
2023-02-16 09:45:26.276 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 69: self._api = tinytuya.Device(dev_id, address, local_key)
2023-02-16 09:45:28.095 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches bwt_heatpump with quality of 29%. DPS: {'updated_at': 1676537126.4945655, '1': False, '2': 26, '3': 78, '4': '40', '5': '104', '6': '40', '7': '104', '8': 40, '9': 104, '10': 40, '11': 104, '12': 'c', '13': False, '14': 30, '15': 'standby', '16': 'temp_setting', '19': 0}
2023-02-16 09:45:28.098 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/
```

**Comment by spitfire** [comment]
With the file from the last commit the kettle is properly recognized now, thanks!
Is there a way to add a separate toggle to start boiling water (you know, the most common feature of a kettle;)) ?

**Comment by make-all** [comment]
I would suggest adding buttons in the UI.  There isn't really a "turn on", because the device has so many "on" modes (Boil, Quick Boil, Warm, Quick Warm), so the "off" was mapped to mode along with them.

**Comment by YuriiMaiboroda** [comment]
"Czajnik" is Polish for "Kettle".  It seems to me that there is an unnecessary tautology in the name of the configuration file :).

**Comment by make-all** [comment]
Unfortunately it was released in the last release, so is more difficult to change now.

**Comment by make-all** [comment]
The turn_on and turn_off services for the water_heater platform should now be implemented in 2023.2.4 (it was accidentally checked in along with another change so missed in the release notes), so it should now be possible to add actions to buttons or an input_boolean to get the simple UI you want (the turn_on will just use whatever mode the kettle is in).

**Comment by bdkacz** [comment]
Hi. I have  Setti+ KT950W and have problem. After integration with HA  the kettle "by itself" from time to time makes sounds, such as it normally emits when it receives a command from the application. It looks like HA sends some command to it from time to time

**Comment by make-all** [comment]
The integration does not send commands without being told to do so by Home Assistant.  However, there have been devices that reboot, perhaps due to internal memory leaks in the local protocol handling code, and I suspect that may be what is happening here.  On a smart switch that I have here, the problem went away when this integration switched from polling to persistent connections, but your device may be the other way around, and may work better with polling.

**Comment by bdkacz** [comment]
The self-reboot theory makes sense. The household members say that since the integration, the kettle does not boil the water - it runs for a while, then stops (probably a restart) and they had to press the switch again, heated it up a bit again, stop (restart) etc.

**Comment by bdkacz** [comment]
> The integration does not send commands without being told to do so by Home Assistant. However, there have been devices that reboot, perhaps due to internal memory leaks in the local protocol handling code, and I suspect that may be what is happening here. On a smart switch that I have here, the problem went away when this integration switched from polling to persistent connections, but your device may be the other way around, and may work better with polling.

How can I switch from persistent to pooling ?

**Comment by make-all** [comment]
If you go into Settings / Devices and select your device in the Tuya Local panel on the integrations page, you should get an "Options" button.  In there is a checkbox to select polling.
