### ISSUE TITLE
Got error " Got message type 16 for unknown listener " when accessing power sensor device

### ISSUE THREAD

**Issue by christopheBfr** [make-all/tuya-local#404]
I have installed a Tuya power meter using local tuya. It works fine since several days.
This morning, I notice errors in the home assistant logs and the entity sensor disapeared from the home assistant dashboard.
Errors in the logs repeated several times:

> 2023-02-13 12:03:04.436 ERROR (MainThread) [custom_components.localtuya.pytuya] [bfe...cto] Got message type 16 for unknown listener 6646: TuyaMessage(seqno=6646, cmd=16, retcode=0, payload=b'\x9c\xa7y\x9d\x1a}]\xce\xd5\xe8<C\xc2e\x8bm\xba\x913~\x81"\x05\xbe+\x7f\x86\xea@b\xbd\xce!\x8e\x1a\x88\xb4\xab=\x18\xe5\x04\x90#e\xec\x8f9\xb1\x04\xf2\xc7!\xcb4k\xdd\xf9\x1e\\\x95\x861\x7f', crc=b'G6*\x1f\xc0\xa5\xc3\xf9\xd3\x98\xe1\t\xd7tv\xff\xd7\x81\xe2\xbc\xfb\x85\xd5St\xf5y3\xd8\x84\xc3e', crc_good=True)

I'm using the version 3.4 of the local tuya protocol   (the only version compatible with my device).

On my network, the sensor is far from the wifi router, but stays reachable with a medium wifi quality link... (perhaps it is a part of the problem ?)

**To Reproduce**
I don't know how to reproduce (perhaps having a poor wifi link quality can helps to have the faulty beahviour ?)

**Expected behavior**
The error message can be more explicited (converting the hex code to human  readable error ?) to help in debuging ?

**Additional context**
Here the configuration in my home assistant for local tuya  (local tuya => export as json):

> {
>   "home_assistant": {
>     "installation_type": "Home Assistant Container",
>     "version": "2023.1.4",
>     "dev": false,
>     "hassio": false,
>     "virtualenv": false,
>     "python_version": "3.10.7",
>     "docker": true,
>     "arch": "armv7l",
>     "timezone": "Europe/Paris",
>     "os_name": "Linux",
>     "os_version": "5.10.103-v7+",
>     "run_as_root": true
>   },
>   "custom_components": {
>     "hacs": {
>       "version": "1.30.1",
>       "requirements": [
>         "aiogithubapi>=22.10.1"
>       ]
>     },
>     "tahoma": {
>       "version": "2.14.0",
>       "requirements": [
>         "pyoverkiz==1.5.6"
>       ]
>     },
>     "localtuya": {
>       "version": "5.0.0",
>       "requirements": []
>     },
>     "tapo": {
>       "version": "1.5.1",
>       "requirements": [
>         "plugp100==2.5.1"
>       ]
>     }
>   },
>   "integration_manifest": {
>     "domain": "localtuya",
>     "name": "LocalTuya integration",
>     "version": "5.0.0",
>     "documentation": "https://github.com/rospogrigio/localtuya/",
>     "dependencies": [],
>     "codeowners": [
>       "@rospogrigio",
>       "@postlund"
>     ],
>     "issue_tracker": "https://github.com/rospogrigio/localtuya/issues",
>     "requirements": [],
>     "config_flow": true,
>     "iot_class": "local_push",
>     "is_built_in": false
>   },
>   "data": {
>     "device_config": {
>       "friendly_name": "compteur",
>       "host": "192.168.1.65",
>       "local_key": "<<<MY SECRET>>>",
>       "protocol_version": "3.4",
>       "enable_debug": false,
>       "manual_dps_strings": "19",
>       "entities": [
>         {
>           "friendly_name": "currentPower",
>           "unit_of_measurement": "W",
>           "device_class": "power",
>           "scaling": 0.1,
>           "id": 19,
>           "platform": "sensor"
>         }
>       ],
>       "device_id": "<<<MY SECRET>>>",
>       "dps_strings": [
>         "17 (value: 136)",
>         "18 (value: 0)",
>         "19 (value: 0)",
>         "20 (value: 0)"
>       ],
>       "product_key": "<<<MY SECRET>>>"
>     }
>   }
> }

If the bug involves a device, then please include device diagnostics from
The device is working properly ( data normally posted to Tuya site ). The device measurements are well published.

Please check if there are messages from Tuya Local in the Home Assistant log:
Log provided:
2023-

> 02-13 12:03:04.436 ERROR (MainThread) [custom_components.localtuya.pytuya] [bfe...cto] Got message type 16 for unknown listener 6646: TuyaMessage(seqno=6646, cmd=16, retcode=0, payload=b'\x9c\xa7y\x9d\x1a}]\xce\xd5\xe8<C\xc2e\x8bm\xba\x913~\x81"\x05\xbe+\x7f\x86\xea@b\xbd\xce!\x8e\x1a\x88\xb4\xab=\x18\xe5\x04\x90#e\xec\x8f9\xb1\x04\xf2\xc7!\xcb4k\xdd\xf9\x1e\\\x95\x861\x7f', crc=b'G6*\x1f\xc0\xa5\xc3\xf9\xd3\x98\xe1\t\xd7tv\xff\xd7\x81\xe2\xbc\xfb\x85\xd5St\xf5y3\xd8\x84\xc3e', crc_good=

True)

No screenshot usefull.. But when the problem occurs, the power sensor disapeared from the Home Assistant dashboard (entity not found error). I get the sensor back when edidting the local tuya device and validate all the steps to "rebuild" the device creation in HA.
(perhaps it can be good to have a parameter "device availabilty" and/or "device last update time" to monitor the device availability and define "automation" to alert when the parameter is no more available nor refreshed ? But the local tuya component must not remove the sensor without "configuration" changes from the user.

Many thank for your help

**Comment by make-all** [comment]
Log indicates a different integration is being used
