### ISSUE TITLE
Thousands of socket errors in the log (not critical)

### ISSUE THREAD

**Issue by YuriiMaiboroda** [make-all/tuya-local#405]
**Describe the bug**
After updating the plugin, hundreds of errors per second began to be displayed in the log. It didn't affect functionality, though.

```
Logger: homeassistant
Source: /data/data/com.termux/files/home/hass/lib/python3.11/site-packages/homeassistant/runner.py:100
First occurred: 17:25:34 (30693 occurrences)
Last logged: 17:28:17

Error doing job: Exception in callback BaseSelectorEventLoop._accept_connection(<aiohttp.web_... 0x758da24450>, <socket.socke...40000, 0, 25)>, None, <Server socke...00, 0, 25)>,)>, 128, None, None)
Error doing job: Exception in callback BaseSelectorEventLoop._accept_connection(<aiohttp.web_... 0x758da24f10>, <socket.socke....241', 40000)>, None, <Server socke...1', 40000)>,)>, 128, None, None)
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/selector_events.py", line 165, in _accept_connection
    conn, addr = sock.accept()
                 ^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/socket.py", line 294, in accept
    fd, addr = self._accept()
               ^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument

```

**To Reproduce**
- Remove added device
- Update the plugin from version 2023.2.0 to version 2023.2.1.
- restart the server
- Start adding the device again
- Specify id, key, ip and protocol
- There are tens of thousands of error messages in the log

**Expected behavior**
There shouldn't be so many socket error messages.

**Additional context**
Restarting the server fixed the issue.

I was unable to reproduce the problem
I tried:
- removed the device
- rolled back the plugin to the previous version
- restarted the server
- added device
- changed switch position
- repeated the steps from **To Reproduce**
- no problems in the log

Device: Elivco CB2S-16DL

Since errors began to be written when a device was connected using a socket through this plugin, I am writing about the error here.
But since I couldn’t reproduce it, it’s more like a message that this happens than a request to fix something.

**Comment by make-all** [comment]
There is nothing in that log that indicates that the errors are coming from this integration.  In fact the error is happening when accepting an incoming connection, but all the connections made by this integration are outgoing, so it is more likely to be the connections from your browser to HA itself that are triggering the error.
