### ISSUE TITLE
Request support for AOFO ZLD-44EU-W

### ISSUE THREAD

**Issue by rafazundt** [make-all/tuya-local#411]
# Log Message

- Device matches tellur_usb_power_strip with quality of 80%. DPS: {'updated_at': 1676388481.911221, '1': True, '2': True, '3': True, '4': True, '7': True, '101': 0, '102': 0, '103': 0, '104': 0, '105': 0}

# Information about DPS mappings

{
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "switch_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_2",
        "dp_id": 2,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_3",
        "dp_id": 3,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_4",
        "dp_id": 4,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 101,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_2",
        "dp_id": 102,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_3",
        "dp_id": 103,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_4",
        "dp_id": 104,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_usb1",
        "dp_id": 7,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_usb1",
        "dp_id": 105,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_2",
        "dp_id": 2,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_3",
        "dp_id": 3,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_4",
        "dp_id": 4,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 101,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_2",
        "dp_id": 102,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_3",
        "dp_id": 103,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_4",
        "dp_id": 104,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_usb1",
        "dp_id": 7,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_usb1",
        "dp_id": 105,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1676392166208,
  "tid": "bf2cc615ac8411ed838e2a0aa76353ad"
}

# Product ID

brand: AOFO
product_model: ZLD-44EU-W
product_name: Smart Power Strip
product_id: D7Hl3AxFbHDS98iO

# Information about how the device functions

4 power switch + 1 switch for 4 usb ports
https://www.blitzwolfeurope.com/spd/RSH-ZLD-44EU-W/RSH-ZLD-44-EU-W-SMART-WiFi-USB-charger-distributor (different brand, however the same model)

**Comment by make-all** [comment]
It looks like you have some kind of lightbulb there as well from the log?  I'm guessing lightbulb because the dps start at 20 and include "colour"

**Comment by rafazundt** [comment]
ooops sorry about that, I copy paste more than I should.
the second log was about a LED Strip.
