### ISSUE TITLE
New error with latest version (Climate)

### ISSUE THREAD

**Issue by davidt94** [make-all/tuya-local#416]
**Describe the bug**

Error after installing latest version, climate error occurs and device wont load. When dropping back to version 2023.2.0 error goes away and device works as normal.

**To Reproduce**
Steps to reproduce the behavior including the device the issue was observed with:

**Expected behavior**

**Additional context**

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

Logger: homeassistant.components.climate
Source: custom_components/tuya_local/climate.py:137
Integration: Climate (documentation, issues)
First occurred: 12:32:43 PM (2 occurrences)
Last logged: 12:32:44 PM

Error adding entities for domain climate with platform tuya_local
Error while setting up tuya_local platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 629, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 264, in capability_attributes
    self.hass, self.min_temp, self.temperature_unit, self.precision
  File "/config/custom_components/tuya_local/climate.py", line 137, in precision
    self._current_temperature_dps.scale(self._device),
AttributeError: 'NoneType' object has no attribute 'scale'

If you need anymore info please let me know.

**Comment by davidt94** [comment]
The last changes made to climate.py seems to be the cause of the issue. Reverting climate.py to previous version fixes the error. I am assuming this is because the heater I have does not have 'current_temperature_dps'.

**Comment by make-all** [comment]
Thanks, that will be exactly the problem.  The newly added code does not account for the fact that both temperature and current_temperature dps may be missing from some devices.

**Comment by davidt94** [comment]
Thanks Jason. Confirmed to be working with the changes you have made above. Really appreciate it!
