### ISSUE TITLE
Request support for Zemmi smart abalon curtain rail motor BCM700D

### ISSUE THREAD

**Issue by robertvanroosmalen** [make-all/tuya-local#418]
Hi,

Thanks for providing the tuyalocal integration. It works for my smart plugs and it is very intuitve when configuring.
I have 5 Wifi curtain motors also sold as Zemmi smart and Abalon. Model: BCM700D WiFi, product ID XS76BY5Q1uKO6gjC
When adding the device I receive a not supported error message from the integration.

Model: BCM700D WiFi, 
product ID XS76BY5Q1uKO6gjC

Link to the device:
https://www.amazon.nl/Motorized-Curtains-compatible-Smartphone-Electric/dp/B09HCGB1M7/ref=asc_df_B09HCGB1M7/?tag=nlshogostdde-21&linkCode=df0&hvadid=494655232972&hvpos=&hvnetw=g&hvrand=15666103754480162956&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9064627&hvtargid=pla-1435775979529&psc=1

They work with local tuya but it is cumbersome to set up and to modify when making mistakes.

# Log Message

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:44
Integration: Tuya Local (documentation, issues)
First occurred: 13 februari 2023 om 14:32:35 (8 occurrences)
Last logged: 19:31:07

Device matches None with quality of 0%. DPS: {'updated_at': 1676295154.7038064, '101': 0, '102': 'STOP', '103': True}
Report this to https://github.com/make-all/tuya-local/issues/
Device matches None with quality of 0%. DPS: {'updated_at': 1676295892.9182327, '101': 51, '102': 'STOP', '103': True}
Device matches None with quality of 0%. DPS: {'updated_at': 1676296356.4694378, '101': 51, '102': 'STOP', '103': True}
Device matches None with quality of 0%. DPS: {'updated_at': 1676485866.4851806, '101': 89, '102': 'STOP', '103': True}
-->

# Information about DPS mappings

If you have an iot.tuya.com account, please go to "Cloud" -> "API Explorer".  Under "Smart Home Device System"/"Device Control", select the last "Get Device Specification Attribute" function, check the server is set correctly, and enter your device ID.  Please post the output here.

{
  "result": {
    "category": "cl",
    "functions": [
      {
        "code": "mach_operate",
        "type": "Enum",
        "values": "{\"range\":[\"ZZ\",\"FZ\",\"STOP\"]}"
      },
      {
        "code": "opposite",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "position",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "opposite",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mach_operate",
        "type": "Enum",
        "values": "{\"range\":[\"ZZ\",\"FZ\",\"STOP\"]}"
      },
      {
        "code": "position",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1676487296014,
  "tid": "3cf1f86bad6211ed954a4e3668f00a74"

Output from tuya iot device debug:

DP ID              Code            Values
Reverse             103            on, off (lowercase)
Position             101            0-100 (%)
Curtain control  102            ON, OFF, PAUZE (upper case)

# Product ID

{
  "result": {
    "active_time": 1621683005,
    "category": "cl",
    "category_name": "Curtain",
    "create_time": 1621683005,
    "gateway_id": "",
    "icon": "smart/product_icon/cl.png",
    "id": "556307468caab5ea0979",
    "ip": "",
    "lat": "51.6245",
    "local_key": "",
    "lon": "5.1799",
    "model": "BCM700D WiFi",
    "name": "Gordijn eethoek zijkant",
    "online": true,
    "owner_id": "",
    "product_id": "XS76BY5Q1uKO6gjC",
    "product_name": "Curtain",
    "sub": false,
    "time_zone": "+01:00",
    "update_time": 1652118776,
    "uuid": "556307468caab5ea0979"
  },
  "success": true,
  "t": 1676487506493,
  "tid": "ba6ba189ad6211ed954a4e3668f00a74"

Although this information is optional and not required, it will be used in future to identify matching devices.
-->

# Information about how the device functions

With the Tuya cloud integration three entities are created:

Reverse, as a switch under configuration, reverses the normal open and close operation i.e. when the motor is mounted on the other side of the curtain rail.
Control opens, stops or closes the curtain
Position is a slide base from 0 to 100
--
If there is a manual or other explanation available online, please link to it (even if not in English)
Otherwise if it is not obvious what all the functions do, please give a brief description.
-->
https://www.abalontracks.com/wp-content/uploads/2022/09/TechnicalSpecifications.pdf

**Comment by make-all** [comment]
Hi, it isn't obvious to me which command is open, and which is close out of "FZ" and "ZZ".  I'm guessing these are abbreviations of a transliteration from Chinese or something.

**Comment by robertvanroosmalen** [comment]
Hello,

That was my problem also. I was looking for a way to modify the current zemismart.yml
I think it's FZ and ZZ and that the tuya iot platform and the tuya app only displays this to on and off.

This is what i've setup using local tuya:

![image](https://user-images.githubusercontent.com/70897113/219288315-6bd8ede3-add7-4402-8971-5ba61f182c8e.png)

**Comment by make-all** [comment]
OK, assuming the order is the same, I will assign FF to open and ZZ to close then.  If it is wrong, they can always be swapped later.

**Comment by make-all** [comment]
Support added in 2023.2.3

**Comment by robertvanroosmalen** [comment]
I'm not so familiar with pull requests but I've made some changes to the provided abalon_bcm700d_curtain.yaml in version 2023.2.3. It now works fine opening and closing, and added the curtain device class.


name: Curtain rail motor
product:
  - id: XS76BY5Q1uKO6gjC
    name: Abalon BCM700D
primary_entity:
  entity: cover
  class: curtain
  dps:
    - id: 101
      name: position
      type: integer
      range:
        min: 0
        max: 100
    - id: 102
      name: control
      type: string
      mapping:
        - dps_val: ZZ
          value: open
        - dps_val: FZ
          value: close
        - dps_val: STOP
          value: stop
secondary_entities:
  - entity: switch
    name: Reverse
    category: config
    icon: "mdi:arrow-u-down-left"
    dps:
      - id: 103
        type: boolean
        name: switch

**Comment by robertvanroosmalen** [comment]
It was discovered fine with the previous release. I'll do an upgrade later today.
Try powercycling the curtainmotor. I remember doing this once and also shut down the (old) local tuya integration since it uses the same network ports for discovering devices as I understood.
