### ISSUE TITLE
update interval energy

### ISSUE THREAD

**Issue by milandzuris** [make-all/tuya-local#420]
My Plugs not updating energy sensors how fix it?

**Comment by make-all** [comment]
I cannot change the behaviour of devices.  The add_ele (energy) attributes of Tuya devices are useless.  Some send 0 constantly, then 1 briefly when there is an increment.  Others send nothing for half an hour, then that half hour's usage once (blink and you miss it in both cases).  They are really intended for cloud use.

It is better to set up an Integration helper in Home Assistant calculating energy use from the power sensor.

**Comment by milandzuris** [comment]
@make-all local-tuya have settings for scan interval and working good, every 10 seconds state (energy) upodated

**Comment by milandzuris** [comment]
![image](https://user-images.githubusercontent.com/42905545/219204500-1d999416-111b-4465-a2ae-f90c3362869a.png)

**Comment by make-all** [comment]
I think this is the same issue as raised in the latest comment of #377 
The solution is to use the updateDps() API function, but it seems to get into black magic at that point, as there isn't any real guidance of when this is needed, and what parameters are safe to pass (apparently devices can misbehave if certain dps are passed in)

**Comment by MayborodaYuriy** [comment]
There is no filter on the values ​​18, 19, 20. These are the default values ​​used when generating the payload (`generate_payload(tinytuya.UPDATEDPS`).

In the [example](https://github.com/jasonacox/tinytuya/blob/d7e621f1ccfb993eb1edb8e9ff044b748dc7a55b/examples/getstatus.py) of getting device status, it is also recommended for outlets to call the DPS update.

**Comment by make-all** [comment]
localtuya never calls that function with any parameters, so they effectively have a filter.

**Comment by MayborodaYuriy** [comment]
Indeed, localtuya has a filter. 
```py
# DPS that are known to be safe to use with update_dps (0x12) command
UPDATE_DPS_WHITELIST = [18, 19, 20]  # Socket (Wi-Fi)
```
And, unlike tinytuya, the function without parameters - updates all known dp included in the white list. Therefore, the locale does not call this function with parameters. Tinytuya has a different behavior - a function called without parameters updates only dp 1. Therefore, you need to either specify a specific set of dp, or use the payload generation with default 18,19,20

**Comment by milandzuris** [comment]
so there is no way to fix it?

**Comment by make-all** [comment]
It can be fixed, but will take some effort, so will need to wait until I have some time.  I need to think about how to specify when to use it and which dps to request update for.  Probably they need to be explicitly marked in the config.  My smartplugs do not need this, and neither did the previous ones I owned of another brand, so I always assumed it was a rare thing to need it.

**Comment by YuriiMaiboroda** [comment]
I made a call to updatedps for all known dp_ids.
```
[tinytuya.core] building command 18 payload=b'{"dpId":[1,9,17,18,19,20,21,22,23,24,25,26,38,39,40,41,42,43,44]}'
```
This really made it possible to update the values of the main three parameters more often every 5–10 seconds. 
```
[tinytuya.core] decoded results='{"dps":{"20":2421,"18":1050,"19":1812},"t":1676550235}'  
```
But sometimes it comes less (probably, if for this value it remained the same). 17, as expected, does not come. My understanding is that this is because it is rarely updated on the device.
```
[tinytuya.core] decoded results='{"dps":{"18":1005,"19":1801},"t":1676550274}'  
```

**Comment by milandzuris** [comment]
> 

thx, i need it this update interval for energy sensor, i have many automations when drop (W) Power e.g. Washing Machine TTS.

**Comment by milandzuris** [comment]
> I made a call to updatedps for all known dp_ids.
> 
> ```
> [tinytuya.core] building command 18 payload=b'{"dpId":[1,9,17,18,19,20,21,22,23,24,25,26,38,39,40,41,42,43,44]}'
> ```
> 
> This really made it possible to update the values of the main three parameters more often every 5–10 seconds.
> 
> ```
> [tinytuya.core] decoded results='{"dps":{"20":2421,"18":1050,"19":1812},"t":1676550235}'  
> ```
> 
> But sometimes it comes less (probably, if for this value it remained the same). 17, as expected, does not come. My understanding is that this is because it is rarely updated on the device.
> 
> ```
> [tinytuya.core] decoded results='{"dps":{"18":1005,"19":1801},"t":1676550274}'  
> ```
I can add it to HA?

**Comment by YuriiMaiboroda** [comment]
> I can add it to HA?

I added before the line `if now - last_cache > self._CACHE_TIMEOUT:` in the `async def async_receive(self):` function of the file `.homeassistant/custom_components/tuya_local/device.py` this call:
```py
self._api.updatedps([int(key) for key,v in self._get_cached_state().items() if key.isdigit()], True)
```
or
```py
self._api.send(self._api.generate_payload(tinytuya.UPDATEDPS, [17, 18, 19, 20]))
```
After that, my data in HA began to be updated regularly.
Power:
![image](https://user-images.githubusercontent.com/47284191/219418816-b4bbbdac-7ff4-41b9-99a7-8315616a41c5.png)
Riemann integral by power:
![image](https://user-images.githubusercontent.com/47284191/219418786-9956ad44-b3f0-4294-be7d-f9976a00eeac.png)

But this is NOT the right place for this call. I chose it just to test how it works. When this call is here, a warning is printed to the log:
```
Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py
```

Also, after that, the server restarts for a long time (waits until tinituya finishes performing long operations with the socket) and tinituya often writes to the log that it has to make 4 repeated requests to get a response (1-2 requests were enough for it before the change).

I don't recommend using this solution on a permanent basis. It is better to wait until the author studies this problem and finds a suitable place for such a call.

**Comment by YuriiMaiboroda** [comment]
I changed the call to updatedps a bit. Now, it seems to me that it works more stable: [tuya-local-dpsupdate.patch](https://github.com/make-all/tuya-local/files/10760586/tuya-local-dpsupdate.patch)
But once again I repeat - this can be used for tests, but I do not recommend using it on a permanent basis.

**Comment by milandzuris** [comment]
> I changed the call to updatedps a bit. Now, it seems to me that it works more stable: [tuya-local-dpsupdate.patch](https://github.com/make-all/tuya-local/files/10760586/tuya-local-dpsupdate.patch) But once again I repeat - this can be used for tests, but I do not recommend using it on a permanent basis.

u copy code from local tuya? or tinytuya?

**Comment by YuriiMaiboroda** [comment]
> > I changed the call to updatedps a bit. Now, it seems to me that it works more stable: [tuya-local-dpsupdate.patch](https://github.com/make-all/tuya-local/files/10760586/tuya-local-dpsupdate.patch) But once again I repeat - this can be used for tests, but I do not recommend using it on a permanent basis.
> 
> u copy code from local tuya? or tinytuya?

This is a modification of the tuya-local code using the tinituya command.
I didn't use localtuya here.

**Comment by make-all** [comment]
What might work is to just change the call to self._api.status() in async_receive() to self._api.updatedps()

But this will not be suitable for all devices, so only for testing if you primarily use smart switches that require this workaround.

**Comment by YuriiMaiboroda** [comment]
I confirm. With such a call, as well as `self._CACHE_TIMEOUT = 5`, it works fine.
```py
if now - last_cache > self._CACHE_TIMEOUT:
    poll = await self._retry_on_failed_connection(
        # lambda: self._api.status(),
        lambda: self._api.updatedps([int(key) for key,v in self._get_cached_state().items() if key.isdigit()]),
        f"Failed to refresh device state for {self.name}",
    )
```
If `_CACHE_TIMEOUT` is not changed, the values will be updated every 2 minutes.
Calling `updatedps()` with no arguments didn't work for me.

**Comment by milandzuris** [comment]
> I confirm. With such a call, as well as `self._CACHE_TIMEOUT = 5`, it works fine.
> 
> ```python
> if now - last_cache > self._CACHE_TIMEOUT:
>     poll = await self._retry_on_failed_connection(
>         # lambda: self._api.status(),
>         lambda: self._api.updatedps([int(key) for key,v in self._get_cached_state().items() if key.isdigit()]),
>         f"Failed to refresh device state for {self.name}",
>     )
> ```
> 
> If `_CACHE_TIMEOUT` is not changed, the values will be updated every 2 minutes. Calling `updatedps()` with no arguments didn't work for me.

Can you please send me the entire file for update interval, i need update interval for every 10 seconds, thx.

**Comment by YuriiMaiboroda** [comment]
@milandzuris [device.txt](https://github.com/make-all/tuya-local/files/10771848/device.txt)
I changed the file extension to upload the file to GitHub. Originally, the file extension is `.py`

**Comment by milandzuris** [comment]
> @milandzuris [device.txt](https://github.com/make-all/tuya-local/files/10771848/device.txt) I changed the file extension to upload the file to GitHub. Originally, the file extension is `.py`

im in local-tuya docs read this, how change in device.py interval to only 10 seconds, thanks.
![image](https://user-images.githubusercontent.com/42905545/219819625-873d006c-5400-46ac-a3b5-514ff5efaee1.png)

**Comment by milandzuris** [comment]
Im downloaded Main (Master) and nothing changed same every 2 minutes updating sensor state, for stability is good every 10 seconds updating no less.

**Comment by YuriiMaiboroda** [comment]
@milandzuris In the last commit, there is an option to add a `force` field, but it is not added anywhere. Since this is a new feature that hasn't been tested enough yet.
You can manually change the cache expiration time, change the value of the `_CACHE_TIMEOUT` field in the device.py, and also put the `force: true` field in the device configuration file (perhaps smartplugv2_energyv3.yaml) to those entities whose values should be updated (usually 18, 19, 20)
But do it at your own risk.

**Comment by YuriiMaiboroda** [comment]
Maybe move the DPS update use flag and its frequency to the user interface, to the device configuration (like in localtuya)? So that users can optionally reduce the polling interval if they need it. And if the device itself updates the data and responds in a status request, then calling the update dps may be redundant. And so users will have the opportunity to configure a polling in case they are not satisfied with the standard behavior.

**Comment by make-all** [comment]
I don't want a complex configuration aimed at technical users.  That is the niche that localtuya fills already.  I prefer to have a simpler configuration that fills general needs.  If you need a more frequent update than 1 minute, you should probably buy different smartplugs or reflash with custom firmware to be frank.

**Comment by YuriiMaiboroda** [comment]
That is, @milandzuris is it better to switch to using the localtuya instead of tuya-local if he needs to update the data every 10 seconds? It's easier than flashing the device.

**Comment by milandzuris** [comment]
> That is, @milandzuris is it better to switch to using the localtuya instead of tuya-local if he needs to update the data every 10 seconds? It's easier than flashing the device.

i like it more tuya local have many more sensor and switches for control my device and local tuya have only switch (on off) and thats all.

**Comment by milandzuris** [comment]
> Maybe move the DPS update use flag and its frequency to the user interface, to the device configuration (like in localtuya)? So that users can optionally reduce the polling interval if they need it. And if the device itself updates the data and responds in a status request, then calling the update dps may be redundant. And so users will have the opportunity to configure a polling in case they are not satisfied with the standard behavior.

this would be the best

**Comment by milandzuris** [comment]
After new update 2.3 stop updating, every 30 minutes. @make-all 
![image](https://user-images.githubusercontent.com/42905545/219956936-2d6585ee-0c36-4411-ae0a-d652b4e9af5e.png)

**Comment by make-all** [comment]
Upgrading to 2023.2.3 via HACS will overwrite any local changes you have. As stated in the release notes, the feature is currently in beta, and no configs are using it out of the box.  I did get it to the stage where it does not make my smartplugs perform any worse, but none of mine actually need the feature so I cannot test if it makes any improvement.

**Comment by YuriiMaiboroda** [comment]
After the update, I turned on the forced update for 17, 18, 20. It works exactly as expected - every half a minute there are requests for a dps update or a status in turn. That is, the energy values are updated once a minute.
It's certainly not refreshing every 5–10 seconds, but much better than before.

**Comment by Reconos87** [comment]
How can i turn on the forced update, for testing purpose? I have 2 Ledvance Smart+ switch that only updates whenever i open the app and goes to the electric tab :)

**Comment by YuriiMaiboroda** [comment]
> How can i turn on the forced update, for testing purpose? I have 2 Ledvance Smart+ switch that only updates whenever i open the app and goes to the electric tab :)

https://github.com/make-all/tuya-local/issues/420#issuecomment-1435765676

**Comment by milandzuris** [comment]
> @milandzurisV poslednom commite je možnosť pridať pole `force`, ale nikde sa nepridáva. Keďže ide o novú funkciu, ktorá ešte nebola dostatočne otestovaná. Môžete manuálne zmeniť čas vypršania platnosti vyrovnávacej pamäte, zmeniť hodnotu poľa `_CACHE_TIMEOUT`v súbore device.py a tiež vložiť `force: true`pole do konfiguračného súboru zariadenia (možno smartplugv2_energyv3.yaml) do tých entít, ktorých hodnoty by sa mali aktualizovať (zvyčajne 18, 19 , 20) Robíte to však na vlastné riziko.

This you mean?, i only want update interval for smartplugv2_energyv3.yaml, no for every device, same need change code in device.py or no?, thx.
![image](https://user-images.githubusercontent.com/42905545/220135736-6619c511-438b-4c73-a698-5924dc769d32.png)

**Comment by YuriiMaiboroda** [comment]
@milandzuris  `force: true` must be specified not for the whole entity, but for a specific dp.
```yaml
- entity: sensor
    category: diagnostic
    class: current
    name: Current
    dps:
      - id: 18
        name: sensor
        type: integer
        class: measurement
        unit: mA
        force: true
      - id: 23
        type: integer
        name: calibration
  - entity: sensor
    category: diagnostic
    class: power
    name: Power
    dps:
      - id: 19
        name: sensor
        type: integer
        class: measurement
        unit: W
        mapping:
          - scale: 10
        force: true
      - id: 24
        type: integer
        name: calibration
  - entity: sensor
    category: diagnostic
    class: voltage
    name: Voltage
    dps:
      - id: 20
        name: sensor
        type: integer
        class: measurement
        unit: V
        mapping:
          - scale: 10
        force: true
      - id: 22
        type: integer
        name: calibration
```

Then `updatedps()` will be called only for the specified dps and only for devices for which the type `smartplugv2_energyv3.yaml` was selected.

In the code, you need to make changes only if you are not satisfied with polling once a minute. If you need the device to be polled more often, then you need to reduce the cache expiration time to the one you need (for example, set to 5 seconds so that the data is updated every 10)

**Comment by milandzuris** [comment]
> cache expiration time

I added now force: true to (DPS) only where im need update, and when i need every 10 seconds update this dps need other change? or only force, I'm a bit confused already.

**Comment by YuriiMaiboroda** [comment]
> > cache expiration time
> 
> I added now force: true to (DPS) only where im need update, and when i need every 10 seconds update this dps need other change? or only force, I'm a bit confused already.

1. Change `smartplugv2_energyv3.yaml` to enable forced update for the some dps
2. In device.py change the value of the constant `_CACHE_TIMEOUT` to 5 (it is 10/2)
3. Reboot the server

**Comment by milandzuris** [comment]
> > > cache expiration time
> > 
> > 
> > I added now force: true to (DPS) only where im need update, and when i need every 10 seconds update this dps need other change? or only force, I'm a bit confused already.
> 
> 1. Change `smartplugv2_energyv3.yaml` to enable forced update for the some dps
> 2. In device.py change the value of the constant `_CACHE_TIMEOUT` to 5 (it is 10/2)
> 3. Reboot the server

now working, im changed same other smartplugv2_energyv.yaml and smartplugv2_energyv2.yaml to force and updating every 12-25 seconds

**Comment by Reconos87** [comment]
> > > cache expiration time
> > 
> > 
> > I added now force: true to (DPS) only where im need update, and when i need every 10 seconds update this dps need other change? or only force, I'm a bit confused already.
> 
> 1. Change `smartplugv2_energyv3.yaml` to enable forced update for the some dps
> 2. In device.py change the value of the constant `_CACHE_TIMEOUT` to 5 (it is 10/2)
> 3. Reboot the server

Thanks!
Power and voltage is now updating at a random, short, interval. But current doesn't seem to change :)

**Comment by milandzuris** [comment]
> > > > cache expiration time
> > > 
> > > 
> > > I added now force: true to (DPS) only where im need update, and when i need every 10 seconds update this dps need other change? or only force, I'm a bit confused already.
> > 
> > 
> > 
> > 1. Change `smartplugv2_energyv3.yaml` to enable forced update for the some dps
> > 2. In device.py change the value of the constant `_CACHE_TIMEOUT` to 5 (it is 10/2)
> > 3. Reboot the server
> 
> Thanks! Power and voltage is now updating at a random, short, interval. But current doesn't seem to change :)

Add to this Folders force: true
![image](https://user-images.githubusercontent.com/42905545/220162916-8a9177d6-f87c-4c5f-be2e-9a76de827c8b.png)

**Comment by Reconos87** [comment]
> > > > > cache expiration time
> > > > 
> > > > 
> > > > I added now force: true to (DPS) only where im need update, and when i need every 10 seconds update this dps need other change? or only force, I'm a bit confused already.
> > > 
> > > 
> > > 
> > > 1. Change `smartplugv2_energyv3.yaml` to enable forced update for the some dps
> > > 2. In device.py change the value of the constant `_CACHE_TIMEOUT` to 5 (it is 10/2)
> > > 3. Reboot the server
> > 
> > 
> > Thanks! Power and voltage is now updating at a random, short, interval. But current doesn't seem to change :)
> 
> Add to this Folders force: true ![image](https://user-images.githubusercontent.com/42905545/220162916-8a9177d6-f87c-4c5f-be2e-9a76de827c8b.png)

Did that :) Still, current not updating. And the Power seems to be living on its own now. Almost 2 minutes between some updates, 10 seconds between others. but hey, it's updating! 👍

**Comment by Reconos87** [comment]
> > > > > cache expiration time
> > > > 
> > > > 
> > > > I added now force: true to (DPS) only where im need update, and when i need every 10 seconds update this dps need other change? or only force, I'm a bit confused already.
> > > 
> > > 
> > > 
> > > 1. Change `smartplugv2_energyv3.yaml` to enable forced update for the some dps
> > > 2. In device.py change the value of the constant `_CACHE_TIMEOUT` to 5 (it is 10/2)
> > > 3. Reboot the server
> > 
> > 
> > Thanks! Power and voltage is now updating at a random, short, interval. But current doesn't seem to change :)
> 
> Add to this Folders force: true ![image](https://user-images.githubusercontent.com/42905545/220162916-8a9177d6-f87c-4c5f-be2e-9a76de827c8b.png)

Seems that current doesn't change when there is no change in the current :) So my bad!

**Comment by milandzuris** [comment]
> > > > > > cache expiration time
> > > > > 
> > > > > 
> > > > > I added now force: true to (DPS) only where im need update, and when i need every 10 seconds update this dps need other change? or only force, I'm a bit confused already.
> > > > 
> > > > 
> > > > 
> > > > 1. Change `smartplugv2_energyv3.yaml` to enable forced update for the some dps
> > > > 2. In device.py change the value of the constant `_CACHE_TIMEOUT` to 5 (it is 10/2)
> > > > 3. Reboot the server
> > > 
> > > 
> > > Thanks! Power and voltage is now updating at a random, short, interval. But current doesn't seem to change :)
> > 
> > 
> > Add to this Folders force: true ![image](https://user-images.githubusercontent.com/42905545/220162916-8a9177d6-f87c-4c5f-be2e-9a76de827c8b.png)
> 
> Seems that current doesn't change when there is no change in the current :) So my bad!

or try to see if it changes in app

**Comment by milandzuris** [comment]
One of my Plug every 10 minutes is unavailable (smartplugv2) @make-all 
![image](https://user-images.githubusercontent.com/42905545/220182289-9a5919fc-cc4e-431f-a8f7-84c639b8ab2f.png)
[tuya_local-e5fdef66f95efa2783014a0c848a2c52-Washing Machine-320f65d922dc8af83e91cd8d9a5a2d96.json.txt](https://github.com/make-all/tuya-local/files/10787193/tuya_local-e5fdef66f95efa2783014a0c848a2c52-Washing.Machine-320f65d922dc8af83e91cd8d9a5a2d96.json.txt)

**Comment by make-all** [comment]
This is the kind of problem I would expect from decreasing CACHE_TIMEOUT. Your smartplug is being overloaded and rebooting periodically.  You can see from the history graph that it wasn't happening before 18:00, which I assume is when you made changes to your device.py and config files.

**Comment by milandzuris** [comment]
> This is the kind of problem I would expect from decreasing CACHE_TIMEOUT. Your smartplug is being overloaded and rebooting periodically. You can see from the history graph that it wasn't happening before 18:00, which I assume is when you made changes to your device.py and config files.

yes, but on local-tuya have same 10sec update interval and don't do this @make-all

**Comment by make-all** [comment]
It is not my goal to replace localtuya.  The released version will not be setting CACHE_TIMEOUT lower than 30s, which seems stable.

**Comment by YuriiMaiboroda** [comment]
As far as I understand, the status call is needed to get information about all dps.
If I'm not mistaken, usually the devices themselves inform the server that something has changed. Except, for example, the electrical parameters of plugs - for them, it is sometimes necessary to send an updatedps.

I think that if the definition of device unavailability is improved - when the socket connection is broken, then the status can be requested once - when the connection is restored. And with a permanent connection, call updatedps and listen to what the device sends itself.

If this can be done, then the frequency of data updates can be reduced to once every 30 seconds, instead of once a minute as it is now.

**Comment by CodingGhost** [comment]
so... is there a way to make it update more often? localtuya doesnt update at all for me and tuya-local only about every 70 secs

**Comment by milandzuris** [comment]
> so... is there a way to make it update more often? localtuya doesnt update at all for me and tuya-local only about every 70 secs

this problem in local tuya only on 3.4 protocol, im waiting for update or try tuya local for 3.4 protocol

**Comment by milandzuris** [comment]
local tuya updating every 2minutes +-

**Comment by CodingGhost** [comment]
I am using tuya-local atm for the affected devices, its better but also inconsistent. does that mean there is still ongoing troubleshooting on this issue? is there an open issue for that?

**Comment by milandzuris** [comment]
@CodingGhost https://github.com/rospogrigio/localtuya/issues/1425

**Comment by MayborodaYuriy** [comment]
> so... is there a way to make it update more often? localtuya doesnt update at all for me and tuya-local only about every 70 secs

It was said above that the frequency can be increased by editing the source files.
https://github.com/make-all/tuya-local/issues/420#issuecomment-1437218634

**Comment by CodingGhost** [comment]
> 

but then it was said that it causes reboots and overloads the device...

**Comment by MayborodaYuriy** [comment]
> > 
> 
> but then it was said that it causes reboots and overloads the device...

Yes, if the frequency is too high, it may not work correctly. Here you need to look for a balance - which is the most frequent with the fewest failures. I have almost no problems with an interval of 10 seconds. But it very much depends on the model.

I did not find another way to increase the frequency.

You can, of course, take an unnecessary smartphone or run an emulator on your computer, install the Tuya application on it and open in this application information about the electricity of the outlet. Then you can get data with greater frequency. But I'm also not sure about the stability of this option during long-term work.

**Comment by CodingGhost** [comment]
well, still that isnt a good solution I think. If I understand correctly that causes all devices to have the faster Interval, and the tuya app is also not an option. what would be nice I think, is if there was an option to set interval per device like in localtuya(also broken currently tho)

**Comment by vleeuwenmenno** [comment]
Has this issue been closed without proper fix? 

I am struggling with this issue at the moment myself. Once the tuya app is open in a meter it is fast but when it's not open in the app it only updates very infrequently. Can I increase the poll rate or force a poll? I use this in combination with Node-RED so if I can force it from there somehow that would work for me too.

**Comment by make-all** [comment]
Are you using the smartplugv2_polled_power configuration?

**Comment by vleeuwenmenno** [comment]
Can I only see this when adding the devices or can I see this back somewhere in a config? I don't think I am using that. Something smartplugv2 but not sure what was after that.

**Comment by make-all** [comment]
The config file can only be changed by removing your device and setting it up again.  This is due to the fact that different configs define different entities, so it would mess the entity registry up to change on the fly.

**Comment by vleeuwenmenno** [comment]
Alright so I just reset a single socket, hope it's the proper one. I left all of them default, which was `smartplugv2_energy`. 

I also happen to have done a network reboot yesterday after I left the comment here. And I applied the `_CACHE_TIMEOUT` to 5 to all those energy files to be sure and some of the sockets seem to be updating every 5-20s while others appear to still be stuck for minutes before updating again. Is it correct they don't update if it's at 0W? Because some of my sockets only have power draw at specific times of the day.

Either way, I'll just let everything run like this and see over a couple of days if most of them maintain a reasonable polling rate. As I also use this to estimate a rough energy expense number, I want this as accurate as possible of course 😅
