### ISSUE TITLE
Slow homeassistant restart when devices are unavailable

### ISSUE THREAD

**Issue by pretoriano80** [make-all/tuya-local#424]
**Describe the bug**
I'm using tuya-local with AlecoAir D14 PURIFY dehumidifier ,but when i restart homeassistant and the dehumidifier is not available (powered off) ,the starting process will hang for about 5 minutes  (until bootstrap timeout is reached ).

This happens ONLY if the dehumidifier is not available.

**To Reproduce**
Power OFF the dehumidifier and restart Homeassistant 

**Expected behavior**
tuya-local should not block the starting process even if a device/entity is not available

**Additional context**
Before opening this ticket i tried various scenarios ,to make sure that's not caused by a misconfiguration in my system .This is what i tried :  
- Removing and re-configure the device
- Unistall tuya-local and re-install 

Diagnostics
`{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2023.2.3",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Bucharest",
    "os_name": "Linux",
    "os_version": "6.1.10",
    "run_as_root": true
  },
  "custom_components": {
    "alarmo": {
      "version": "v1.9.7",
      "requirements": []
    },
    "hacs": {
      "version": "1.30.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "tuya_local": {
      "version": "2022.2.2",
      "requirements": [
        "pycryptodome~=3.17",
        "tinytuya==1.10.2"
      ]
    },
    "adaptive_lighting": {
      "version": "1.4.1",
      "requirements": []
    },
    "alexa_media": {
      "version": "4.6.0",
      "requirements": [
        "alexapy==1.26.4",
        "packaging>=20.3",
        "wrapt>=1.12.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya_local",
    "iot_class": "local_push",
    "integration_type": "device",
    "name": "Tuya Local",
    "version": "2022.2.2",
    "documentation": "https://github.com/make-all/tuya-local",
    "issue_tracker": "https://github.com/make-all/tuya-local/issues",
    "dependencies": [],
    "codeowners": [
      "@make-all"
    ],
    "requirements": [
      "pycryptodome~=3.17",
      "tinytuya==1.10.2"
    ],
    "config_flow": true,
    "is_built_in": false
  },
  "data": {
    "name": "dezumidificator",
    "type": "alecoair_d16_dehumidifier",
    "device_id": "**REDACTED**",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": 3.2,
    "api_version_set": 3.2,
    "api_version_used": 3.2,
    "api_working": false,
    "status": {},
    "cached_state": {
      "updated_at": 0
    },
    "pending_state": {},
    "connected": true,
    "home_assistant": {
      "name": "dezumidificator",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "problem",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "binary_sensor.dezumidificator_tank",
            "state": "unavailable",
            "attributes": {
              "device_class": "problem",
              "friendly_name": "dezumidificator Tank"
            },
            "last_changed": "2023-02-16T10:31:21.184825+00:00",
            "last_updated": "2023-02-16T10:31:21.184825+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "lock.dezumidificator_child_lock",
            "state": "unavailable",
            "attributes": {
              "friendly_name": "dezumidificator Child lock",
              "supported_features": 0
            },
            "last_changed": "2023-02-16T10:31:27.081458+00:00",
            "last_updated": "2023-02-16T10:31:27.081458+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "switch",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.dezumidificator_ionizer",
            "state": "unavailable",
            "attributes": {
              "device_class": "switch",
              "icon": "mdi:creation",
              "friendly_name": "dezumidificator Ionizer"
            },
            "last_changed": "2023-02-16T10:31:21.189802+00:00",
            "last_updated": "2023-02-16T10:31:21.189802+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "dehumidifier",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "humidifier.dezumidificator",
            "state": "unavailable",
            "attributes": {
              "min_humidity": 25,
              "max_humidity": 80,
              "available_modes": [
                "Sleep",
                "Purify",
                "Dry clothes",
                "Manual"
              ],
              "device_class": "dehumidifier",
              "friendly_name": "dezumidificator",
              "supported_features": 1
            },
            "last_changed": "2023-02-16T10:31:27.083179+00:00",
            "last_updated": "2023-02-16T10:31:27.083179+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "humidity",
          "icon": null,
          "unit_of_measurement": "%",
          "state": {
            "entity_id": "sensor.dezumidificator_current_humidity",
            "state": "unavailable",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "%",
              "device_class": "humidity",
              "friendly_name": "dezumidificator Current humidity"
            },
            "last_changed": "2023-02-16T10:31:21.190840+00:00",
            "last_updated": "2023-02-16T10:31:21.190840+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "fan.dezumidificator",
            "state": "unavailable",
            "attributes": {
              "preset_modes": [],
              "friendly_name": "dezumidificator",
              "supported_features": 1
            },
            "last_changed": "2023-02-16T10:31:27.080634+00:00",
            "last_updated": "2023-02-16T10:31:27.080634+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "select.dezumidificator_timer",
            "state": "unavailable",
            "attributes": {
              "options": [
                "9 hours",
                "5 hours",
                "20 hours",
                "6 hours",
                "24 hours",
                "1 hour",
                "7 hours",
                "8 hours",
                "3 hours",
                "16 hours",
                "23 hours",
                "12 hours",
                "14 hours",
                "22 hours",
                "4 hours",
                "13 hours",
                "Off",
                "11 hours",
                "19 hours",
                "2 hours",
                "17 hours",
                "10 hours",
                "21 hours",
                "18 hours",
                "15 hours"
              ],
              "icon": "mdi:timer",
              "friendly_name": "dezumidificator Timer"
            },
            "last_changed": "2023-02-16T10:31:27.079793+00:00",
            "last_updated": "2023-02-16T10:31:27.079793+00:00"
          }
        }
      ]
    }
  }
}`

Homeassistant system logs 
`2023-02-16 12:31:36.322 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.dezumidificator_tank is taking over 10 seconds
2023-02-16 12:36:35.388 WARNING (MainThread) [homeassistant.bootstrap] Setup timed out for bootstrap - moving forward`

Notes:
This time "binary_sensor.dezumidificator_tank" is showing in logs,but it's not always the same,the entity may change (i.e. switch.dezumidificator_ionizer ).

Don't mind the device showing as AlecoAir D16 in the diagnostics ,that's the profile i used this time ,but the issue persists with both the D16 PURIFY and  D14 PURIFY profiles .

The device internet access and DNS requests are blocked .

**Comment by make-all** [comment]
Probably this should be a Home Assistant bug.  Tuya Local has finished starting by this point, but Home Assistant assumes that any activity that begins during the startup phase needs to finish before startup can switch to the next phase.  There doesn't seem to be any way to signal to Home Assistant that we are done starting and to not wait for any hung connections, other than not opening any connections to devices until after startup is finished, which in worst case can be 15 minutes after a reboot if another integration is delaying startup.

**Comment by pretoriano80** [comment]
Hmm... i wonder why this isn't happening with other integrations when the device is unavailable .
Fir example i also have esphome integration with 2 devices which are not available ,but there's no issues with that.

However ,i don't know if HA devs will take it seriously if we report this with a custom integration involved .

**Comment by make-all** [comment]
The commit above should speed it up substantially, I think even with the protocol version set to "auto" it should now fail after 1m15s seconds in theory, instead of 6m15s.  With the protocol version set correctly, you can bring it down to 15s (with the previous code, it should have been 75s with the protocol set).

**Comment by pretoriano80** [comment]
Yep,tested and the speed improved a lot.
Also,no more bootstrap timeout error .
Thank you for the quick fix!

**Comment by YuriiMaiboroda** [comment]
Is it possible to listen to some kind of HA event that it is shout downing or restarting and interrupting the work of tinituya?

**Comment by make-all** [comment]
This is done already.

**Comment by YuriiMaiboroda** [comment]
If I understand correctly, now at the HA stopping work, we wait until the cycle is completed. In particular, wait until tinituya has finished making repeated requests.
From `device.py`
```py
def actually_start(self, event=None):
  ...
  self._refresh_task = self._hass.async_create_task(self.receive_loop())

...

async def async_stop(self, event=None):
  ...
  if self._refresh_task:
    await self._refresh_task
```

`async_create_task` returns an object of type `asyncio.Task`
From `homeassistant/core.py`
```py
def async_create_task(self, target: Coroutine[Any, Any, _R]) -> asyncio.Task[_R]:
```

The Python [documentation](https://docs.python.org/3/library/asyncio-task.html#asyncio.Task.cancel) has recommendations for stopping tasks ahead of time:
```py
async def main():
    # Create a "cancel_me" Task
    task = asyncio.create_task(cancel_me())

    # Wait for 1 second
    await asyncio.sleep(1)

    task.cancel()
    try:
        await task
    except asyncio.CancelledError:
        print("main(): cancel_me is cancelled now")
```
Maybe it's worth adding the cancellation of the task, so as not to wait for it to finish?

**Comment by make-all** [comment]
I don't think it is necessary.  The message is not an urgent shutdown, it is a gradeful one. Tinytuya's default socket timeout is 5 seconds, and now we have set it to only try once if the connections are failing.

I am not sure what hanging up a connection mid stream will do to the devices, they seem to be coded fairly poorly and hangup/crash/toggle switches randomly on all sorts of unexpected input.

I am also not sure that the HA async task functions provide access to all the features of asyncio.task, but probably there is a cancel method there somewhere for cases where it really is needed.
.

**Comment by pretoriano80** [comment]
@make-all i still have an issue with this device ,but probably it's not related to this bug (i will open another report after more testing ).

Basically ,if the device it's unavailable and i proceed with a Power ON (from the mains) ,tuya-local will not update the entities's status for a quite some time and some are not updated at all (i.e.  the tank entity it's stuck on "problem").

I will enable the debug logging and see if i can get something useful .

**Comment by YuriiMaiboroda** [comment]
> @make-all i still have an issue with this device ,but probably it's not related to this bug (i will open another report after more testing ).
> 
> Basically ,if the device it's unavailable and i proceed with a Power ON (from the mains) ,tuya-local will not update the entities's status for a quite some time and some are not updated at all (i.e. the tank entity it's stuck on "problem").
> 
> I will enable the debug logging and see if i can get something useful .

I think it's related to #377

**Comment by pretoriano80** [comment]
Thx,will keep an eye on that report while testing with this dehumidifier .
IIRC it was working fine with older versions ,from a year or so,but i don't recall when all this started to happen (i noticed this issue months ago,but i thought that there's something wrong with my configuration ).

**Comment by make-all** [comment]
self._running is not set until after initial startup, so blocking retries on that will prevent protocol version discovery on the first connection during startup.  Instead I put in a condition on `self._hass.is_shutting_down.`

**Comment by pretoriano80** [comment]
@make-all  i've did a clean test ,by removing the device completely and re-added AlecoAir D14 dehumidifier again ,with all parameters set manually .
Everything works as expected here ,a complete restart of HA when the device is unavailable it's around 30 seconds .
Also,when the device is powered on,so the device became available ,all the entities are updated correctly .

Thanks again!
