### ISSUE TITLE
Request support for BVF CP1 Smart Heater

### ISSUE THREAD

**Issue by saotthon** [make-all/tuya-local#425]
# Log Message

# Information about DPS mappings

    "category": "wk",
    "functions": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "dp_id": 2,
        "type": "Enum",
        "values": "{\"range\":[\"hot\",\"eco\",\"cold\",\"auto\"]}"
      },
      {
        "code": "light",
        "dp_id": 6,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "sound",
        "dp_id": 7,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "window_check",
        "dp_id": 8,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "dp_id": 16,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":5,\"max\":45,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_correction",
        "dp_id": 27,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-9,\"max\":9,\"scale\":0,\"step\":1}"
      },
      {
        "code": "child_lock",
        "dp_id": 40,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown",
        "dp_id": 41,
        "type": "Enum",
        "values": "{\"range\":[\"cancel\",\"1h\",\"2h\",\"3h\",\"4h\",\"5h\",\"6h\",\"7h\",\"8h\",\"9h\",\"10h\",\"11h\",\"12h\",\"13h\",\"14h\",\"15h\",\"16h\",\"17h\",\"18h\",\"19h\",\"20h\",\"21h\",\"22h\",\"23h\",\"24h\"]}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "dp_id": 2,
        "type": "Enum",
        "values": "{\"range\":[\"hot\",\"eco\",\"cold\",\"auto\"]}"
      },
      {
        "code": "light",
        "dp_id": 6,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "sound",
        "dp_id": 7,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "window_check",
        "dp_id": 8,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "dp_id": 16,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":5,\"max\":45,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_current",
        "dp_id": 24,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":50,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_correction",
        "dp_id": 27,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-9,\"max\":9,\"scale\":0,\"step\":1}"
      },
      {
        "code": "child_lock",
        "dp_id": 40,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown",
        "dp_id": 41,
        "type": "Enum",
        "values": "{\"range\":[\"cancel\",\"1h\",\"2h\",\"3h\",\"4h\",\"5h\",\"6h\",\"7h\",\"8h\",\"9h\",\"10h\",\"11h\",\"12h\",\"13h\",\"14h\",\"15h\",\"16h\",\"17h\",\"18h\",\"19h\",\"20h\",\"21h\",\"22h\",\"23h\",\"24h\"]}"
      }
    ]

# Product ID

    "biz_type": 0,
    "category": "wk",
    "icon": "smart/icon/ay1515733470982l5jsJ/176d5e4bd40af07887ec61d20b1c216b.png",
    "model": "",
    "product_id": "t2htqaryl4gymeuv",
    "product_name": "CP-1 heater",

# Information about how the device functions

User manual, has english content from page 10:
https://www.bvfheating.hu/files/futopanelek/bvf_cp1_hasznalati_utmutato.pdf

**Comment by make-all** [comment]
Support added in 2023.2.3
