### ISSUE TITLE
Please add support for the Electriq CD12PW

### ISSUE THREAD

**Issue by Swiftnesses** [make-all/tuya-local#43]
Good day,

Is it possible to add support for this model, I have a feeling it's largely the same as existing models?

I found this: https://templates.blakadder.com/electriq_CD12PW.html

**Comment by make-all** [comment]
The information at that link is about the protocol between the ESP8266 and another microcontroller.  Although it is likely to be similar to the Tuya level protocol, it is quite common to have mapping of string values at Tuya protocol level to integers at the internal protocol level.  So some logs from attempting to configure the device would be useful.  

You may also find if you configure it that it is a close enough match to one of the other ElectriQ CDPRO models to work with an existing configuration.

**Comment by make-all** [comment]
This looks similar enough to the CD25PRO that it should get detected as that and partially function.  There are some difference in the number and labelling of presets though that might limit the compatibility a bit.  But I'll need further details on the actual lpreset names observed in the logs to make a custom config that works fully for this device.

**Comment by make-all** [comment]
This is now in 0.11.3, if there are any issues with it, or you find additional info, please open a new issue.
