### ISSUE TITLE
Request support for Hiper IoT DL221, DL331

### ISSUE THREAD

**Issue by igor070784** [make-all/tuya-local#430]
# Log Message
Device matches garage_door_opener with quality of 40%. DPS: {'updated_at': 1676637238.192053, '1': True, '2': 'Breathe', '3': 255, '4': 112, '101': False}

# Information about DPS mappings
{
  "result": {
    "category": "dj",
    "functions": [
      {
        "code": "switch_led",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "bright_value",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"min\":25,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}"
      },
      {
        "code": "temp_value",
        "dp_id": 4,
        "type": "Integer",
        "values": "{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch_led",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "bright_value",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"min\":25,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}"
      },
      {
        "code": "temp_value",
        "dp_id": 4,
        "type": "Integer",
        "values": "{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1676638054440,
  "tid": "3ffc06fbaec111ed838e2a0aa76353ad"
}

 "Debug Device" 
switch_led | Boolean | "{true,false}"
-- | -- | --
bright_value | Integer | {   "min": 25,   "scale": 0,   "unit": "",   "max": 255,   "step": 1 }
temp_value | Integer | {   "min": 0,   "scale": 0,   "unit": "",   "max": 255,   "step": 1 }
# Product ID
eab4q4by3mgeg6ip

# Information about how the device functions
https://hiper-power.com/ru/catalog/umnyy-dom/osveshchenie/svetilniki/umnyy-svetilnik-hiper-iot-dl221/

**Comment by make-all** [comment]
Sorry, this device seems to be specific to the Russian market.  I will not be working on this until your country's leadership stops sending young Russian men to die in a futile war of aggression against its neighbour.

**Comment by make-all** [comment]
This device actually appears to be basically the same as the Setti+ desk lamp, which is supported for a while now, so a specific config for this will not be needed.
