### ISSUE TITLE
Request support for [Flooding Detector, Flood sensor SQ400A]

### ISSUE THREAD

**Issue by hronek** [make-all/tuya-local#433]
DPS: 
{
  "result": {
    "category": "sj",
    "functions": [],
    "status": [
      {
        "code": "watersensor_state",
        "dp_id": 1,
        "type": "Enum",
        "values": "{\"range\":[\"alarm\",\"normal\"]}"
      },
      {
        "code": "battery_percentage",
        "dp_id": 4,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1676720812292,
  "tid": "ef84a130af8111ed954a4e3668f00a74"
}

{
  "result": {
    "active_time": 1675277905,
    "category": "sj",
    "category_name": "Flooding Detector",
    "create_time": 1675277905,
    "gateway_id": "",
    "icon": "smart/icon/ay1537847617560vAgbw/4544fbc115e72a5f3b9e9f290a68d6e0.jpg",
    "id": "bf4d7289100e56b1fdq04c",
    "ip": "178.255.168.68",
    "lat": "49.3146",
    "local_key": "MY_KEY",
    "lon": "14.1428",
    "model": "SQ400A",
    "name": "Flood sensor",
    "online": true,
    "owner_id": "80342840",
    "product_id": "ewqu5gfbaod635ge",
    "product_name": "Flood sensor",
    "sub": false,
    "time_zone": "+01:00",
    "update_time": 1675277909,
    "uuid": "fcdd58b51209481e"
  },
  "success": true,
  "t": 1676721093732,
  "tid": "97441ddaaf8211ed8a3392fe1232b0cc"
}

**Comment by make-all** [comment]
As this is a battery powered device, there is very low chance that this can work with this integration.

Please try to add it, and add the Home Assistant log messages from that attempt (only those from tuya-local) as a comment.

**Comment by hronek** [comment]
It's bateerypowered device, you can close the issue.
