### ISSUE TITLE
Initial state Support (Power on behavior, relay_status) mini通断器

### ISSUE THREAD

**Issue by milandzuris** [make-all/tuya-local#436]
#Log Message
Clear

#Product
mini通断器

#Product ID
45gg9a0jfyzj1z1d

#Attributes Specification
{
  "result": {
    "category": "tdq",
    "functions": [
      {
        "code": "switch_1",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Switch 1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "lang_config": {
          "unit": "s"
        },
        "name": "Countdown 1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "lang_config": {
          "0": "OFF",
          "1": "ON",
          "2": "Remember last status"
        },
        "name": "Relay status",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\"]}"
      },
      {
        "code": "random_time",
        "lang_config": {
          "unit": "s"
        },
        "name": "Random time",
        "type": "String",
        "values": "{\"maxlen\":255}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Switch 1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "lang_config": {
          "unit": "s"
        },
        "name": "Countdown 1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "lang_config": {
          "0": "OFF",
          "1": "ON",
          "2": "Remember last status"
        },
        "name": "Relay status",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\"]}"
      },
      {
        "code": "random_time",
        "lang_config": {
          "unit": "s"
        },
        "name": "Random time",
        "type": "String",
        "values": "{\"maxlen\":255}"
      }
    ]
  },
  "success": true,
  "t": 1676741084621,
  "tid": "22b2fab8afb111ed838e2a0aa76353ad"
}

**Comment by make-all** [comment]
If this has the standard layout, it should match smartplugv2_energy after the latest changes which made a number of dps optional to maximise compatibility.

If not, this report is missing logs and information linking the cloud datapoints to local protocol indexes, I suggest following the instructions on the new device template fully.
