### ISSUE TITLE
Initial state Support (Power on behavior, relay_status) Smart Socket iqTech

### ISSUE THREAD

**Issue by milandzuris** [make-all/tuya-local#437]
#Log Message
Clear

#Product
Smart Socket iqTech

#Product ID
ivmoqnslqglt6bid

#Attributes Specification
{
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "switch_1",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Switch 1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "lang_config": {
          "unit": "s"
        },
        "name": "Countdown 1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "lang_config": {
          "last": "Remember last status",
          "power_off": "OFF",
          "power_on": "On"
        },
        "name": "relay status",
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "cycle_time",
        "lang_config": {
          "unit": "s"
        },
        "name": "cycle time",
        "type": "String",
        "values": "{}"
      },
      {
        "code": "random_time",
        "lang_config": {
          "unit": "s"
        },
        "name": "random time",
        "type": "String",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Switch 1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "lang_config": {
          "unit": "s"
        },
        "name": "Countdown 1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "add_ele",
        "lang_config": {
          "unit": "W"
        },
        "name": "Add Electricity",
        "type": "Integer",
        "values": "{\"unit\":\"kW·h\",\"min\":0,\"max\":50000,\"scale\":3,\"step\":100}"
      },
      {
        "code": "cur_current",
        "lang_config": {
          "unit": "mA"
        },
        "name": "Current",
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_power",
        "lang_config": {
          "unit": "W"
        },
        "name": "Power",
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":0,\"max\":80000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "cur_voltage",
        "lang_config": {
          "unit": "V"
        },
        "name": "Voltage",
        "type": "Integer",
        "values": "{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "relay_status",
        "lang_config": {
          "last": "Remember last status",
          "power_off": "OFF",
          "power_on": "On"
        },
        "name": "relay status",
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "cycle_time",
        "lang_config": {
          "unit": "s"
        },
        "name": "cycle time",
        "type": "String",
        "values": "{}"
      },
      {
        "code": "random_time",
        "lang_config": {
          "unit": "s"
        },
        "name": "random time",
        "type": "String",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1676741814508,
  "tid": "d5cdf4d6afb211ed838e2a0aa76353ad"
}

**Comment by make-all** [comment]
If this has the standard layout, it should match smartplugv2_energy after the latest changes which made a number of dps optional to maximise compatibility.

If not, this report is missing logs and information linking the cloud datapoints to local protocol indexes, I suggest following the instructions on the new device template fully.
