### ISSUE TITLE
IPS Pro pool - Power kw sensor

### ISSUE THREAD

**Issue by itchyNZL** [make-all/tuya-local#440]
**Describe the bug**
Sorry, not a bug or a new device so somewhere in the middle. The pool heater displays a kW when running, so I was trying to get this displayed. The pool heater gets added in nicely using Tuya-local and adds in as an IPS Pro Pool. It brings in the thermostat items nicely and brings in water flow, and power as a %*. I then tried the Local Tuya which enable me to find all the data points, but none were defined so I tried to adjust settings to figure out what was what. This is what I gathered and the values that were there;

1	True/False			Power
2	Smart/Silence/Turbo	Fan
102	29				Temp Current
103	True				?
104	65				% Power
105	Warm
106	28				Temp Setting
107	18				Temp Min
108	40				Temp Max
115	0				?
116	0				?
142	889				kw
143	True				?

There are four data points there that I was unsure of, one will be water flow, not sure about the others though.

I thought I could add just the power sensor from Local Tuya and keep the rest from Tuya Local which worked for a bit, but then a lamp failed. My issue seems to be that I can't have two integrations accessing the same device otherwise errors occur, something in Local Tuya, the Tuya local start to fail and won't work until I remove Local Tuya.

*I did try setting up conversions for the power, but it wasn't accurate, so I kept digging for another solution.

This is the device if that helps;
https://www.aquaclear.co.nz/products/aquax-pool-heat-pump/

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

Here are the diagnostics, which match the notes I found above. 142 is the power but it doesn't make a sensor for it

  "data": {
    "name": "Pool Heat Pump",
    "type": "ips_pro_heatpump",
    "device_id": "**REDACTED**",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": "auto",
    "api_version_set": 3.3,
    "api_version_used": 3.3,
    "api_working": true,
    "status": {},
    "cached_state": {
      "updated_at": 1676790981.6951501,
      "1": false,
      "2": "smart",
      "102": 28,
      "103": true,
      "104": 0,
      "105": "warm",
      "106": 28,
      "107": 18,
      "108": 40,
      "115": 0,
      "116": 0,
      "142": 0,
      "143": true

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

Thanks in advance

**Comment by make-all** [comment]
I don't think that is 889kW unless this is a commercial heatpump for a multi-pool swimming complex or something.
889W maybe?

**Comment by make-all** [comment]
I've added these as optional attributes on the IPS Pro config, as I suspect the devices are the same (often the tuya iot portal does not list dps above a certain range, which may be why they were missing from the original config, or maybe they are not present on the IPS Pro, in which case having them optional will still match that)

The 4 "unidentified" ones will be 103=Temperature unit (true=C, false=F), 115=pump error (0= no error, 4=water flow protection), 116=some other error (no specific values identified), 143 is still unidentified, but if you have iot.tuya.com access, you may be able to find the missing function in the DPS dropdown at top left of the Device Debugger page.

**Comment by make-all** [comment]
Support added in 2023.2.3
