### ISSUE TITLE
Request support for [X-sense WI-FI Smoke Alarm]

### ISSUE THREAD

**Issue by Casadomoticap** [make-all/tuya-local#441]
Hi, I would like to add support to this new device for Wifi Smoke Alarm:

The product is: https://www.amazon.es/X-Sense-reemplazable-inteligente-autocomprobaci%C3%B3n-XS01-WT/dp/B08PF5J5CS/ref=sr_1_5?__mk_es_ES=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=4VXL6Q3QWI35&keywords=x-sense+wi-fi+smoke+alarma&qid=1676809541&sprefix=x-sense+wi-fi+smoke+alarm%2Caps%2C397&sr=8-5

# Log Message

# Information about DPS mappings

**Description - DP ID - Example -> From Cloud**

Silence - 16 -
Smoke detection status - 1
Self-Check results - 9
Fault Warning - 11
Battery Status - 14 - High

**Get Device Specification Attribute -> From API Explorer**

{
  "result": {
    "category": "ywbj",
    "functions": [
      {
        "code": "muffling",
        "dp_id": 16,
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "smoke_sensor_status",
        "dp_id": 1,
        "type": "Enum",
        "values": "{\"range\":[\"alarm\",\"normal\"]}"
      },
      {
        "code": "battery_state",
        "dp_id": 14,
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"high\"]}"
      },
      {
        "code": "muffling",
        "dp_id": 16,
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1676810672940,
  "tid": "28a2bdaeb05311edaee5be2f74bef187"
}

# Product ID

"product_id": "skivkhveqwmqw4gs",

# Information about how the device functions

Is a Smoke Alarm, if the alarm detected smoke, it will advice you by Tuya integration and make sound. 

Thank you a lot :) Nice and perfect project

**Comment by make-all** [comment]
<html>
<body>


Fuente de alimentación | Funciona con batería
-- | --



</body>
</html>

If I am not mistaken, the above means it runs off batteries.  Most likely it will not be possible to use this device locally, due to power management leaving it offline most of the time, and only coming on to send status updates to the cloud.]

If you cannot gather the log messages, then I think it is pointless trying to add support.

**Comment by Casadomoticap** [comment]
Yes, it is a battery. So I will close the issue 

Thank you.
