### ISSUE TITLE
Request support for LoraTap RF + WiFi Curtain Switch

### ISSUE THREAD

**Issue by elninosi** [make-all/tuya-local#446]
It would be awesome to add support for Tuya LoraTap curtain switch as no other integration currently supports it.

# Log Message
2023-02-20 16:13:14.133 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches None with quality of 0%. DPS: {'updated_at': 1676905993.3373048, '1': '3'}

# Information about DPS mappings
DP ID Code Values:
DPID: 1 (Status)

Status can be either:
- Pause
- turn off
- turn on

# Product ID

{
  "result": {
    "active_time": 1633185941,
    "category": "clkg",
    "category_name": "Curtain Switch",
    "create_time": 1633185941,
    "gateway_id": "",
    "icon": "smart/icon/15524566468s3d5rsnldv_0.png",
    "id": "4433632370039f89db10",
    "ip": "92.37.33.253",
    "lat": "45.5755",
    "local_key": "90d9da336ff194bf",
    "lon": "15.1878",
    "model": "SC500W-V1",
    "name": "Blinds",
    "online": true,
    "owner_id": "30083290",
    "product_id": "tuh2eatk4hsq336s",
    "product_name": "Curtain Switch",
    "sub": false,
    "time_zone": "+01:00",
    "update_time": 1676668512,
    "uuid": "4433632370039f89db10"
  },
  "success": true,
  "t": 1676907983515,
  "tid": "ba3bd212b13511ed954a4e3668f00a74"
}

# Information about how the device functions
Device is curtain switch and it functions as switch for curtain motor. You can either open, close or pause the switch.

Please let me know if anything else is needed. Thank you.

**Comment by make-all** [comment]
Please fill in the information from the new device template.
In particular, the local protocol information is completely missing from this request, there is no log provided, and the possible values for the dp are not precisely defined.

**Comment by elninosi** [comment]
Hi @make-all,
thanks for quick reply. I updated some info above. Can you guide me how to identify local protocol info and get more details for  DPS?

**Comment by elninosi** [comment]
Confirming that it works.

**Comment by make-all** [comment]
The config was migrated to use a cover entity rather than buttons/switches on March 5 after changes were made to the cover entity that allow a simple device like this to work as a cover.  If you are upgrading directly from 2023.2.4, you may find that your previous entities are no longer available and there is a new cover entity that you need to use instead.

**Comment by elninosi** [comment]
I tried to re-add it but it can't be added. 
![slika](https://user-images.githubusercontent.com/11082452/236251827-487e778e-84a0-4545-98bf-ceccd9d8675f.png)

**Comment by make-all** [comment]
If you restart Home Assistant?  Is there anything in the Home Assistant log?

**Comment by elninosi** [comment]
Here is the snippet from the log:

> 2023-05-08 21:41:16.664 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 66: self._api = tinytuya.Device(dev_id, address, local_key)
> 2023-05-08 21:41:21.295 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 66: self._api = tinytuya.Device(dev_id, address, local_key)
> 2023-05-08 21:41:22.477 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 66: self._api = tinytuya.Device(dev_id, address, local_key)
> 2023-05-08 21:41:27.340 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 66: self._api = tinytuya.Device(dev_id, address, local_key)
> 2023-05-08 21:41:29.384 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 66: self._api = tinytuya.Device(dev_id, address, local_key)
> 2023-05-08 21:41:47.490 ERROR (MainThread) [custom_components.tuya_local.device] <class 'Exception'>: Unable to find device on network (specify IP address) while initialising device 4433632370039f89db10
> 2023-05-08 21:41:47.491 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Simple curtain switch for tuya_local
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
>     result = await component.async_setup_entry(hass, self)
>   File "/config/custom_components/tuya_local/__init__.py", line 236, in async_setup_entry
>     setup_device(hass, config)
>   File "/config/custom_components/tuya_local/device.py", line 575, in setup_device
>     device = TuyaLocalDevice(
>   File "/config/custom_components/tuya_local/device.py", line 74, in __init__
>     raise e
>   File "/config/custom_components/tuya_local/device.py", line 66, in __init__
>     self._api = tinytuya.Device(dev_id, address, local_key)
>   File "/usr/local/lib/python3.10/site-packages/tinytuya/core.py", line 789, in __init__
>     raise Exception("Unable to find device on network (specify IP address)")
> Exception: Unable to find device on network (specify IP address)

**Comment by make-all** [comment]
The message indicates that it is the auto IP address detection that is failing.  Did you try to set the IP address for the device in your configuration instead of leaving it to auto detect?

**Comment by elninosi** [comment]
Yes, I did, same thing happens. Weird.
