### ISSUE TITLE
Gosund SP112 Smart Plug

### ISSUE THREAD

**Issue by pvillanyi** [make-all/tuya-local#448]
# Product ID: zmql6aexy8ua5rox

# Information about how the device functions

name: Gosund SP112 smart plug + USB
product:
  - id: zmql6aexy8ua5rox
    name: Gosund SP112
primary_entity:
  entity: switch
  class: outlet
  name: Outlet
  dps:
    - id: 1
      type: boolean
      name: switch
secondary_entities:
  - entity: switch
    name: USB switch
    class: switch
    dps:
      - id: 7
        type: boolean
        name: switch
  - entity: number
    name: Timer 1
    category: config
    icon: "mdi:timer"
    dps:
      - id: 9
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: number
    name: USB Timer
    category: config
    icon: "mdi:timer"
    dps:
      - id: 15
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: sensor
    name: Current
    class: current
    category: diagnostic
    dps:
      - id: 18
        type: integer
        name: sensor
        unit: mA
        class: measurement
  - entity: sensor
    name: Power
    class: power
    category: diagnostic
    dps:
      - id: 19
        type: integer
        name: sensor
        unit: W
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    name: Voltage
    class: voltage
    category: diagnostic
    dps:
      - id: 20
        type: integer
        name: sensor
        unit: V
        class: measurement
        mapping:
          - scale: 10
  - entity: select
    category: config
    name: Initial state
    icon: "mdi:toggle-switch"
    dps:
      - id: 38
        type: string
        name: option
        mapping:
          - dps_val: "power_on"
            value: "On"
          - dps_val: "power_off"
            value: "Off"
          - dps_val: last
            value: "Last State"
  - entity: select
    name: Light mode
    category: config
    icon: "mdi:lightbulb"
    dps:
      - id: 39
        type: string
        name: option
        mapping:
          - dps_val: relay
            value: State
          - dps_val: pos
            value: Position
          - dps_val: none
            value: "Off"
          - dps_val: "on"
            value: "On"

**Comment by pvillanyi** [comment]
It's working good for me.
I hope it can help others also

**Comment by pietjanssen** [comment]
Hey @pvillanyi. Thank you for this information! I was searching the internet for hours until I found this.
I have a question, though. How do I use this information for local-tuya? I'm having trouble using the UI to configure my wallplugs.

**Comment by pvillanyi** [comment]
Hi Boris,

its a device file for tuya local. For local tuya you have to pair the IDs with the functions. You can use my config as a guide.
________________________________
Feladó: Boris van Norren ***@***.***>
Elküldve: 2023. március 4., szombat 13:31
Címzett: make-all/tuya-local ***@***.***>
Másolatot kap: pvillanyi ***@***.***>; Mention ***@***.***>
Tárgy: Re: [make-all/tuya-local] Gosund SP112 Smart Plug (Issue #448)


Hey @pvillanyi<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpvillanyi&data=05%7C01%7C%7Ceddeb76e5c464795bba108db1cac6372%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638135298947815509%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BRC%2B2VqZ4bLS1Z8ojcvnExpBNC8XooRn19xKmMq6qC4%3D&reserved=0>. Thank you for this information! I was searching the internet for hours until I found this.
I have a question, though. How do I use this information for local-tuya? I'm having trouble using the UI to configure my wallplugs.

**Comment by hwinkel** [comment]
how can i select the template while addding a new device?

**Comment by hwinkel** [comment]
i have the following SP112 which seems to have a different Product_ID

```
{
  "result": {
    "active_time": 1635606589,
    "category": "pc",
    "category_name": "Power Strip",
    "create_time": 1635606589,
    "gateway_id": "",
    "icon": "smart/icon/ay1517974017716dABhC/a1672287759828e0c7f9ae5dfebae887.png",
    "id": "",
    "ip": "",
    "lat": "",
    "local_key": "",
    "lon": "",
    "model": "SP112硬件优化，0937，中性",
    "name": "Gosund SP112-01",
    "online": true,
    "owner_id": "37367224",
    "product_id": "zo7k5xd87yciwk6p",
    "product_name": "Smart Socket",
    "sub": false,
    "time_zone": "+01:00",
    "update_time": 1674917317,
    "uuid": "205284415002912a691b"
  },
  "success": true,
  "t": 1678225125285,
  "tid": "6fea1005bd3011edb7fdc2ad824e71c9"
}
```
