### ISSUE TITLE
Request to support another thermostat 

### ISSUE THREAD

**Issue by Uaeguy** [make-all/tuya-local#45]
Hello, Thanks again for supporting these devices, I came with new Thermostat. 

While trying to add the thermostat it shows as switch only.

 The thermostat is from a company called saswell [here is a link of the product](https://www.saswell.com/google-home-smart-thermostat-google-home-compatible-thermostat-t29utw-7-wifi-ty_p102.html)

[and another link for the manual ](https://fccid.io/2AOIFT29UTW/User-Manual/User-Manual-4656091)

The below is what I can read from the device

```
{
  "result": {
    "active_time": 1633009656,
    "biz_type": 18,
    "category": "wk",
    "create_time": 1633008214,
    "icon": "smart/icon/ay1537509218624daaHb/1568701541ef9f14aff8e.jpg",
    "id": "quoted for security",
    "ip": "quoted for security",
    "lat": "quoted for security",
    "local_key": "quoted for security",
    "lon": "quoted for security",
    "model": "T29UTW-7-WIFI(TY)",
    "name": "Room Thermostat",
    "online": true,
    "owner_id": "quoted for security",
    "product_id": "q2cf9qt8zl2qyqhz",
    "product_name": "T29UTW",
    "status": [
      {
        "code": "switch",
        "value": true
      },
      {
        "code": "mode",
        "value": "cold"
      },
      {
        "code": "c_f",
        "value": "C"
      },
      {
        "code": "temp_set",
        "value": 23
      },
      {
        "code": "temp_current",
        "value": 23
      },
      {
        "code": "temp_set_f",
        "value": 74
      },
      {
        "code": "temp_current_f",
        "value": 81
      }
    ],
    "sub": false,
    "time_zone": "+00:00",
    "uid": "quoted for security",
    "update_time": quoted for security,
    "uuid": "quoted for security"
  },
  "success": true,
  "t": .....
}
```

Edit:

I added the DPS from HA while detecting it as simple switch and what I think it will be
```
Device matches simple_switch with quality of 7%. DPS: {
'1': True, #True the thermostat is on position False is off position 
'2': 240,  #set tempreture 24.0 (exact reading on the panel)
'3': 241,  #currunt tempreture 24.1 (exact reading on the panel)
'4': 'cold',  #mode cold / off (it can be heat as well) it changes from cold to off when the thermostat in off position
'5': 'auto',  #fan auto or on
'19': 'c',  # Celsius or Fahrenheit
'101': False, 
'102': False, 
'103': 'cold',  #mode it doesn't change when it is in off position
'112': '1', 
'113': 0, 
'114': 24, #set temp in C
'115': 24,  #current temp in C
'116': 75,  #set temp in F
'117': 81,  # current temp in F
'updated_at': 1633013846.2673612
}
```

I can find out the others if I played with the configuration of the device if needed

Thanks again :)

**Comment by Uaeguy** [comment]
`Device matches simple_switch with quality of 7%. DPS: {'1': True, '2': 240, '3': 241, '4': 'cold', '5': 'auto', '19': 'c', '101': False, '102': False, '103': 'cold', '112': '1', '113': 0, '114': 24, '115': 24, '116': 75, '117': 81, 'updated_at': 1633013846.2673612}
`

DPS in Home Assistant Sorry forgot about it

**Comment by make-all** [comment]
From the manual, one of 101 or 102 should be the child lock, the other may be an aux_heat setting.
112 may be related to the program settings, or the configuration of the thermostat, and 113 an error code (covering the other indicators on the panel, such as UV lamp replacement indicator).

**Comment by Uaeguy** [comment]
I have checked for the remaining dps and found the below, 

Also I want to note that once I have added the new thermostat the old one went missing from HA I don't know why I will try restarting HA and reconnecting it. 

DPS: {
'1': False, #true is on false is off
'2': 240, # set temp
'3': 275, # current temp
'4': 'off', # mode off or cold
'5': 'auto', # fan auto or on
'19': 'c',  #c or F
'101': False, #True = away mode (it sets the temp to 28 C)
'102': False, #True = activate 7 day program / False if you don't want to use it
'103': 'cold', # mode cold (related to the 7 days program)
'112': '1', 
'113': 0, 
'114': 24, # set temp "c"
'115': 27, # current temp "c"
'116': 75, # set temp "f"
'117': 81, # current temp "f"
'updated_at': 1633111820.2566292}

**Comment by make-all** [comment]
You can try the change I just pushed on 'main' (not released yet).  I haven't yet made the changes from your last comment, but it looks like they can be accommodated as presets.

**Comment by make-all** [comment]
Release 0.11.0 has preliminary support (with the away/program settings still reported as unknown)

**Comment by Uaeguy** [comment]
Hello,

I got it reporting the correct temps, but I cant control anything with HA

**Comment by Uaeguy** [comment]
I found out the below, Mode can be _cold hot_ or _off_

to enable the thermostat switch on it should (turn the switch to on "true" and change mode to cold at the same time)

Mode: 
type: Enum
```
{
  "range": [
    "cold",
    "hot"
  ]
}
```

as for setting the temp, it can only read the temp_set_f, I have tired setting the temp with temp_set (which is the c unit) it will not accept it for some reason.

**Comment by make-all** [comment]
Only one method of setting the temperature can be provided.  Previously dps 2 was used (in 0.11.0 that is the case), but in main, I have changed it to dps 114/116 depending on the setting of dps 19 (c = 114, f = 116).

But it may be that there is still some problem with the scaling, or with the C/F conditions in the 0.11.0 version, so if it is still not working in main, I could try simplifying the temperature set conditions.  Like the Beka thermostat, we may end up needing to use different configs for the C and F settings so the conditions can be removed.

**Comment by Uaeguy** [comment]
I have tried the main as well, I can't control the thermostat, If you need me to do anything else I'm ready.

I just want to share the info I have in Tuya developer page if that can help
_Standard Instruction Set tap_
![image](https://user-images.githubusercontent.com/36298972/135750502-f766d516-664a-466f-93c6-8c0e820ab6fc.png)


_Standard Status Set tap_

![image](https://user-images.githubusercontent.com/36298972/135750472-365f5d7c-bdcd-47e2-881a-d7a94fa2396f.png)

**Comment by Uaeguy** [comment]
Still I can't control the thermostat, when trying to control it via HA, it shows idle.

**Comment by make-all** [comment]
For DPS 1, is it turning off the full system, or just the display?  I notice that quite a few thermostats use DPS 1 for the display on/off, and don't actually have a way to turn them off remotely.  If it is full system, then it needs to be linked to hvac_mode.

**Comment by make-all** [comment]
0.11.3 should have the changes raised in the last comment.  If you have any suggestions for further improvement, please open a new issue.
