### ISSUE TITLE
Request support for Smart Curtain Controller FS-03W (unbranded)

### ISSUE THREAD

**Issue by rafazundt** [make-all/tuya-local#452]
# Log Message

- Device matches qs_c01_curtain with quality of 67%. DPS: {'updated_at': 1677073122.0887997, '1': 'stop', '2': 0, '7': True, '8': 'forward', '10': 10, '14': 'relay'}

# Information about DPS mappings

{
  "result": {
    "category": "clkg",
    "functions": [
      {
        "code": "control",
        "dp_id": 1,
        "type": "Enum",
        "values": "{\"range\":[\"open\",\"stop\",\"close\"]}"
      },
      {
        "code": "percent_control",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_calibration",
        "dp_id": 3,
        "type": "Enum",
        "values": "{\"range\":[\"start\",\"end\"]}"
      },
      {
        "code": "switch_backlight",
        "dp_id": 7,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "control_back_mode",
        "dp_id": 8,
        "type": "Enum",
        "values": "{\"range\":[\"forward\",\"back\"]}"
      },
      {
        "code": "light_mode",
        "dp_id": 14,
        "type": "Enum",
        "values": "{\"range\":[\"relay\",\"pos\",\"none\"]}"
      }
    ],
    "status": [
      {
        "code": "control",
        "dp_id": 1,
        "type": "Enum",
        "values": "{\"range\":[\"open\",\"stop\",\"close\"]}"
      },
      {
        "code": "percent_control",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_calibration",
        "dp_id": 3,
        "type": "Enum",
        "values": "{\"range\":[\"start\",\"end\"]}"
      },
      {
        "code": "switch_backlight",
        "dp_id": 7,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "control_back_mode",
        "dp_id": 8,
        "type": "Enum",
        "values": "{\"range\":[\"forward\",\"back\"]}"
      },
      {
        "code": "light_mode",
        "dp_id": 14,
        "type": "Enum",
        "values": "{\"range\":[\"relay\",\"pos\",\"none\"]}"
      }
    ]
  },

# Product ID

category: "clkg"
category_name: "Curtain Switch"
product_id: "5rr5k8fzjcogubkt"
product_name: "Curtain switch"
model: FS-03W

# Information about how the device functions

Smart Curtain Controller with the following features: 
  - Schedule
  - Indicator Status
  - Backlight Switch
  - Motor Steering Switch
  - Accurate Calibration
  - Quick Calibration

ref: https://aliexpress.com/item/1005005005003123.html

**Comment by make-all** [comment]
qs_c01_curtain seems to cover the basic functionality of the curtain.  Missing from that is backlight control, which I think I can basically understand, and calibration, which is not clear to me so I'm not sure how to support it (especially breaking it down to quick and accurate calibration).
