### ISSUE TITLE
Request support for AUBESS Power Monitor Switch 16A

### ISSUE THREAD

**Issue by rafazundt** [make-all/tuya-local#454]
# Log Message

I am currently getting no log message because the device doesn't pass the configuration step. 

When I am adding the device I just keep getting the "Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect." message.

- Device is online
- ID and local_key are both correct
- IP is also correct
- There is no other app/service/tool connected to the same device
- "Poll only" option is also not working.

UPDATE: Log message when I add the device using protocol:3.4 /simple_switch_timerv2

Device matches simple_switch_timerv2 with quality of 17%. DPS: {'updated_at': 1677146475.6250558, '1': False, '9': 0, '21': 0, '22': 0, '23': 2249, '24': 2, '29': 0, '38': 'off', '42': '', '43': '', '44': '', '47': 'flip'}

# Information about DPS mappings

{
  "result": {
    "category": "tdq",
    "functions": [
      {
        "code": "switch_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "dp_id": 38,
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\"]}"
      },
      {
        "code": "random_time",
        "dp_id": 42,
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "cycle_time",
        "dp_id": 43,
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "switch_inching",
        "dp_id": 44,
        "type": "String",
        "values": "{\"maxlen\":255}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "add_ele",
        "dp_id": 20,
        "type": "Integer",
        "values": "{\"unit\":\"kW·h\",\"min\":0,\"max\":50000,\"scale\":3,\"step\":100}"
      },
      {
        "code": "cur_current",
        "dp_id": 21,
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_power",
        "dp_id": 22,
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":0,\"max\":50000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "cur_voltage",
        "dp_id": 23,
        "type": "Integer",
        "values": "{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "test_bit",
        "dp_id": 24,
        "type": "Integer",
        "values": "{\"min\":0,\"max\":5,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "dp_id": 38,
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\"]}"
      },
      {
        "code": "random_time",
        "dp_id": 42,
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "cycle_time",
        "dp_id": 43,
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "switch_inching",
        "dp_id": 44,
        "type": "String",
        "values": "{\"maxlen\":255}"
      }
    ]
  },

# Product ID

"category": "tdq",
"category_name": "Breaker",
"product_id": "labfkgzm2ikdcpdp",
"product_name": "Aubess Smart Switch/EM",
"model": "Aubess Smart Switch/EM"

# Information about how the device functions

Power Monitor Switch 16A with the following features:
- Timer
- Power monitoring: Current(mA) / Power(W) / Voltage(V) / Total(KWh) / Today(KWh)
- Relay Status: ON / OFF / Remember last status
- Switch type settings:
  rocker switch - flip to change state
  rocker switch - state synchronous
  reset switch

REF: https://www.aubess.net/products/aubess-wifi-mini-smart-switch16a-with-power-monitor-supporte-amazon-alexa-google-home-yandex-alice

**Comment by rafazundt** [comment]
FYI if I switch from protocol:auto to protocol:3.4 it gets identified as a simple_switch / simple_switch_timerv2

**Comment by make-all** [comment]
You should be getting a log message now that you've identified that the protocol version needs to be explicitly set.

**Comment by make-all** [comment]
Based on the config values given above, this should be a 100% match for aubess_1gang_switch.

So I need to see the log messages to figure out why it is not matching.

**Comment by rafazundt** [comment]
Updated the log message as requested

**Comment by make-all** [comment]
It just seems to be missing the energy reading, which seems to be a common issue with Tuya plugs (energy only reported infrequently).
