### ISSUE TITLE
Request support for [Blinds Controller] Wifi chain motor 

### ISSUE THREAD

**Issue by mrulke** [make-all/tuya-local#456]
# Log Message

# Information about DPS mappings

Here are the DPs from both get attribute and Debug
`{
    "result": {
      "category": "cl",
      "functions": [
        {
          "code": "control",
          "dp_id": 1,
          "type": "Enum",
          "values": "{\"range\":[\"open\",\"stop\",\"close\"]}"
        },
        {
          "code": "percent_control",
          "dp_id": 2,
          "type": "Integer",
          "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
        },
        {
          "code": "control_back",
          "dp_id": 5,
          "type": "Boolean",
          "values": "{}"
        },
        {
          "code": "countdown",
          "dp_id": 8,
          "type": "Enum",
          "values": "{\"range\":[\"cancel\",\"1\",\"2\",\"3\",\"4\"]}"
        }
      ],
      "status": [
        {
          "code": "control",
          "dp_id": 1,
          "type": "Enum",
          "values": "{\"range\":[\"open\",\"stop\",\"close\"]}"
        },
        {
          "code": "percent_control",
          "dp_id": 2,
          "type": "Integer",
          "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
        },
        {
          "code": "percent_state",
          "dp_id": 3,
          "type": "Integer",
          "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
        },
        {
          "code": "control_back",
          "dp_id": 5,
          "type": "Boolean",
          "values": "{}"
        },
        {
          "code": "work_state",
          "dp_id": 7,
          "type": "Enum",
          "values": "{\"range\":[\"opening\",\"closing\"]}"
        },
        {
          "code": "countdown",
          "dp_id": 8,
          "type": "Enum",
          "values": "{\"range\":[\"cancel\",\"1\",\"2\",\"3\",\"4\"]}"
        },
        {
          "code": "countdown_left",
          "dp_id": 9,
          "type": "Integer",
          "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
        },
        {
          "code": "time_total",
          "dp_id": 11,
          "type": "Integer",
          "values": "{\"unit\":\"ms\",\"min\":0,\"max\":120000,\"scale\":0,\"step\":1}"
        }
      ]
    }

{
"Control": {
    "code": "1",
    "startTime": 1676886844031,
    "endTime": 1677059644032,
    "projectCode": "p1628395652128ugchy4",
    "sourceId": "eu1597471042376AF0FX",
    "sourceType": "4",
    "deviceId": "50548253e8db848d94a5",
    "region": "EU"
            },
"Percent Control": 
{
    "code": "2",
    "startTime": 1676887792389,
    "endTime": 1677060592390,
    "projectCode": "p1628395652128ugchy4",
    "sourceId": "eu1597471042376AF0FX",
    "sourceType": "4",
    "deviceId": "50548253e8db848d94a5",
    "region": "EU"
},
"Percent State":
{
    "code": "3",
    "startTime": 1676887895752,
    "endTime": 1677060695753,
    "projectCode": "p1628395652128ugchy4",
    "sourceId": "eu1597471042376AF0FX",
    "sourceType": "4",
    "deviceId": "50548253e8db848d94a5",
    "region": "EU"
},
"Motor Direction":
{
    "code": "5",
    "startTime": 1676887916314,
    "endTime": 1677060716315,
    "projectCode": "p1628395652128ugchy4",
    "sourceId": "eu1597471042376AF0FX",
    "sourceType": "4",
    "deviceId": "50548253e8db848d94a5",
    "region": "EU"
},
"Work State":
{
    "startRowId": "",
    "code": "7",
    "startTime": 1676888287339,
    "endTime": 1677061087339,
    "projectCode": "p1628395652128ugchy4",
    "sourceId": "eu1597471042376AF0FX",
    "sourceType": "4",
    "deviceId": "50548253e8db848d94a5",
    "region": "EU"
},
"Count Down":
{
    "code": "8",
    "startTime": 1676887965430,
    "endTime": 1677060765431,
    "projectCode": "p1628395652128ugchy4",
    "sourceId": "eu1597471042376AF0FX",
    "sourceType": "4",
    "deviceId": "50548253e8db848d94a5",
    "region": "EU"
},
"Left Time":
{
    "code": "9",
    "startTime": 1676887991551,
    "endTime": 1677060791552,
    "projectCode": "p1628395652128ugchy4",
    "sourceId": "eu1597471042376AF0FX",
    "sourceType": "4",
    "deviceId": "50548253e8db848d94a5",
    "region": "EU"
},
"Fault":
{
    "code": "10",
    "startTime": 1676888011890,
    "endTime": 1677060811891,
    "projectCode": "p1628395652128ugchy4",
    "sourceId": "eu1597471042376AF0FX",
    "sourceType": "4",
    "deviceId": "50548253e8db848d94a5",
    "region": "EU"
}

}`

  "category": "cl",
  "product_name": "Blinds Controller",
  "product_id": "3r8gc33pnqsxfe1g",
  "biz_type": 0,
  "model": "CCB-11",
  "sub": false,
  "icon": "https://images.tuyaeu.com/smart/program_category_icon/cl.png"

Here is a link to the product.
[html
](https://www.aliexpress.com/item/4000782412838.html)
Its a wifi/RF chain controller.
has button for up down and stop. you can set limits. and motor direction

**Comment by make-all** [comment]
This device is a 100% match for Avatto blinds controller, which is the same type of device.  Why can that config not be used?

**Comment by mrulke** [comment]
when i use that they dont work not sure why

**Comment by mrulke** [comment]
Thanks, Heaps. ill test on during the week
