### ISSUE TITLE
[IMPROVEMENT] Get keys easier with NodeRED

### ISSUE THREAD

**Issue by formatBCE** [make-all/tuya-local#458]
Finally published my NodeRED flow to easily get local keys and device IDs for all connected Tuya devices. I don't use it anymore (re-flashed or sold all Tuya devices), but don't want this to die somewhere with next flows cleanup.

https://github.com/formatBCE/Tuya-Get-Keys-NodeRED

Hopefully, someone will fond this useful.

**Comment by make-all** [comment]
Sorry, this appears to be a single long line script in a markup I am not familiar with which makes it difficult to review for recommendation to my users.

**Comment by formatBCE** [comment]
Ok.
It's NodeRED flow, which is pretty clear, when imported to NodeRED.
But whatever. Anyways, thanks for your job and quick response.
