### ISSUE TITLE
Create service to reload integration

### ISSUE THREAD

**Issue by davefx** [make-all/tuya-local#459]
**Describe the bug**
I have a light bulb that eventually doesn't become active after turning it on, unless I reload its integration, or reboot the whole Home Assistant.

**To Reproduce**
I turn on the wall switch and the bulb turns on. However, the corresponding device in Home Assistant keeps as "not available" for minutes, unless I reload its corresponding Tuya Local device.

**Expected behavior**
I'd like to have a service that allows me to program an automation that reloads the integration for this device if it has not become available a minute after the corresponding wall switch has been switched on.

**Comment by make-all** [comment]
This service already exists: [homeassistant.reload_config_entry](https://www.home-assistant.io/integrations/homeassistant/#service-homeassistantreload_config_entry).
