### ISSUE TITLE
Request support Tellur Thermostat TSH02

### ISSUE THREAD

**Issue by boekerolli** [make-all/tuya-local#460]
Hi All,
can you please add the support for the following device?
Thanks a lot and best regards,
Olli

********************************************************************************************
{
  "result": {
    "category": "wk",
    "functions": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "dp_id": 2,
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"manual\"]}"
      },
      {
        "code": "frost",
        "dp_id": 10,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "dp_id": 16,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":50,\"max\":10000,\"scale\":1,\"step\":5}"
      },
      {
        "code": "upper_temp",
        "dp_id": 19,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":50,\"max\":10000,\"scale\":1,\"step\":10}"
      },
      {
        "code": "temp_unit_convert",
        "dp_id": 23,
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "lower_temp",
        "dp_id": 26,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":50,\"max\":10000,\"scale\":1,\"step\":10}"
      },
      {
        "code": "work_days",
        "dp_id": 31,
        "type": "Enum",
        "values": "{\"range\":[\"5_2\",\"6_1\",\"7\"]}"
      },
      {
        "code": "child_lock",
        "dp_id": 40,
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "dp_id": 2,
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"manual\"]}"
      },
      {
        "code": "frost",
        "dp_id": 10,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "dp_id": 16,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":50,\"max\":10000,\"scale\":1,\"step\":5}"
      },
      {
        "code": "upper_temp",
        "dp_id": 19,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":50,\"max\":10000,\"scale\":1,\"step\":10}"
      },
      {
        "code": "temp_unit_convert",
        "dp_id": 23,
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "temp_current",
        "dp_id": 24,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-300,\"max\":10000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "lower_temp",
        "dp_id": 26,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":50,\"max\":10000,\"scale\":1,\"step\":10}"
      },
      {
        "code": "work_days",
        "dp_id": 31,
        "type": "Enum",
        "values": "{\"range\":[\"5_2\",\"6_1\",\"7\"]}"
      },
      {
        "code": "valve_state",
        "dp_id": 36,
        "type": "Enum",
        "values": "{\"range\":[\"close\",\"open\"]}"
      },
      {
        "code": "child_lock",
        "dp_id": 40,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fault",
        "dp_id": 45,
        "type": "Bitmap",
        "values": "{\"label\":[\"e1\",\"e2\",\"e3\"]}"
      }
    ]
  },
  "success": true,
  "t": 1677231880702,
  "tid": "dc0791deb42711ed8000aaf8d5ec8256"
}

**Comment by make-all** [comment]
If possible, can you please include the log message from HA log.

Otherwise it can take some back and forward to get the values right.  In particular, dp 23 temp_unit_convert is often a boolean in the local protocol even though it is documented as a "c"/"f" enum. And other enums can often use numeric values in the local protocol instead of the strings documented in the cloud API.

**Comment by make-all** [comment]
As specified above, the device should be an exact match for salcar_t9w_thermostat.

**Comment by boekerolli** [comment]
Hi,
No chance to get it integrated... everytime the same error message....
<Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect.>
Do you have idea? 
Thanks a lot and best regards
Olli

**Comment by make-all** [comment]
1. one or more of the details is incorrect.
2. Home Assistant is not able to route to the network where your device is.
3. you have another local connection to the device already (mobile app, localtuya, ...)

**Comment by boekerolli** [comment]
Hi All,
Hmmmmm, got  the device id and local key from iot.tuya.com and the fixed IP from the router.
I have no local_tuya or tuya integration running in HA and the tuya app is not open on my mobile.....
Seems I have a network issue....
Is there any possilbility to get / trace the network information from HA?
Thanks again and best regards,
Olli

**Comment by make-all** [comment]
You can try enabling debug log output for tinytuya:

```yaml
logger:
  default: warning
  logs:
    tinytuya: debug
```

This should give more information about what is happening at the network level (whether it is no response, no route to host, actively rejected connection, connected but data cannot be decrypted etc)

**Comment by boekerolli** [comment]
Sorry for the delay..... :-( 
I think there is the tinytuya missing in my installation.
I´m running HA in a VM on a Synology Host.......
If I try to add the tinytuya repository https://github.com/jasonacox/tinytuya in HACS I´m getting this error:
<Integration jasonacox/tinytuya> Repository structure for v1.10.3 is not compliant
confused..... as I´m new to HA.... .

**Comment by make-all** [comment]
tinytuya is not an HA integration, so it can't be installed via HACS.

I don't know about VM installs, but on HAOS when tuya-local is installed via HACS, the dependencies are automatically installed as well.  Maybe you need to install tinytuya and pycryptodome as a python library in your VM.  `pip install -r requirements.txt` from inside the tuya-local directory might work depending on whether HA on VM uses a virtual environment or not.  But in general if your environment is not standard, you are going to have to figure out things like this on your own (but the same should apply to other third party integrations as well)

**Comment by boekerolli** [comment]
Got one step closer yesterday....
pip is missing?!? installed it, but after a restart of HA it´s lost again.
I will investigate further and keep you informed..

**Comment by boekerolli** [comment]
It´s the restart of the VM.... After upgrading python and installation of pip3 and tinytuya all changes are lost after a restart of the VM.
Now trying to find out how to keep the updates after a restart of the VM.
Has maybe anyone an idea? THX Olli

**Comment by Freddyjb67** [comment]
I also have a Tellur TSH02.
 dont' recognize either. iot.tuya says these writ:
{
  "result": {
    "category": "wk",
    "functions": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "dp_id": 2,
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"manual\"]}"
      },
      {
        "code": "frost",
        "dp_id": 10,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "dp_id": 16,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":50,\"max\":10000,\"scale\":1,\"step\":5}"
      },
      {
        "code": "upper_temp",
        "dp_id": 19,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":50,\"max\":10000,\"scale\":1,\"step\":10}"
      },
      {
        "code": "temp_unit_convert",
        "dp_id": 23,
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "lower_temp",
        "dp_id": 26,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":50,\"max\":10000,\"scale\":1,\"step\":10}"
      },
      {
        "code": "work_days",
        "dp_id": 31,
        "type": "Enum",
        "values": "{\"range\":[\"5_2\",\"6_1\",\"7\"]}"
      },
      {
        "code": "child_lock",
        "dp_id": 40,
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "dp_id": 2,
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"manual\"]}"
      },
      {
        "code": "frost",
        "dp_id": 10,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "dp_id": 16,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":50,\"max\":10000,\"scale\":1,\"step\":5}"
      },
      {
        "code": "upper_temp",
        "dp_id": 19,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":50,\"max\":10000,\"scale\":1,\"step\":10}"
      },
      {
        "code": "temp_unit_convert",
        "dp_id": 23,
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "temp_current",
        "dp_id": 24,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-300,\"max\":10000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "lower_temp",
        "dp_id": 26,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":50,\"max\":10000,\"scale\":1,\"step\":10}"
      },
      {
        "code": "work_days",
        "dp_id": 31,
        "type": "Enum",
        "values": "{\"range\":[\"5_2\",\"6_1\",\"7\"]}"
      },
      {
        "code": "valve_state",
        "dp_id": 36,
        "type": "Enum",
        "values": "{\"range\":[\"close\",\"open\"]}"
      },
      {
        "code": "child_lock",
        "dp_id": 40,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fault",
        "dp_id": 45,
        "type": "Bitmap",
        "values": "{\"label\":[\"e1\",\"e2\",\"e3\"]}"
      }
    ]
  },
  "success": true,
  "t": 1677678360777,
  "tid": "66bd88e8b83711edb803d6013968de13"
}

**Comment by kassyo87** [comment]
Hello. this is old, but maybe someone could help me. I specifically bought the tsh02 because the other salcar clone was unable to connect (the intermittent problem). Now, the tsh does connect but at the final stage of integration it asks me about what type best describes my device and it gives me options for a pet feeder, an ir remote, but no thermostat.

**Comment by kassyo87** [comment]
this is what i have from the log "Not match for Salcar T9W thermostat, missing required DPs: [{'1': 'bool'}, {'2': 'str'}, {'16': 'int'}, {'19': 'int'}, {'23': 'str'}, {'24': 'int'}, {'26': 'int'}, {'36': 'str'}, {'10': 'bool'}, {'19': 'int'}, {'23': 'str'}, {'23': 'str'}, {'26': 'int'}, {'23': 'str'}, {'31': 'str'}, {'40': 'bool'}, {'45': 'int'}, {'45': 'int'}, {'45': 'int'}]"
