### ISSUE TITLE
Request support for wifi electric bathroom heater

### ISSUE THREAD

**Issue by karolzamosc** [make-all/tuya-local#463]
Device is a smart wifi heater with touch panel that allows to switch device on, off, change temperature. Digital screen shows actual temperature and indicates working status

![grzalka-elektryczna-rumba-400w-biala](https://user-images.githubusercontent.com/61420368/221275926-47c96ee6-eb87-490e-9138-19049f400a72.jpg)

Device ID: bfbe530fc448c2d675lmpt

Datapoints:
1. Set temperature - code: 16
2. Switch - code: 1
3. Mode - code: 2
4. Current temperature - code: 24
5. Child lock - code: 40
6. Temperature correction - code: 27
7. Week program - code: 110

switch | Boolean | "{true,false}"

mode | Enum | {   "range": [     "hot",     "eco",     "cold",     "auto"   ] }

temp_set | Integer | {   "unit": "℃",   "min": 150,   "max": 700,   "scale": 1,   "step": 5 }

temp_current | Integer | {   "unit": "℃",   "min": 0,   "max": 1000,   "scale": 1,   "step": 5 }

temp_correction | Integer | {   "unit": "℃",   "min": -5,   "max": 5,   "scale": 0,   "step": 1 }

child_lock | Boolean | "{true,false}"

**Comment by make-all** [comment]
Brand: Rumba?
