### ISSUE TITLE
tuya smart curtain (i guess it is bcm700d

### ISSUE THREAD

**Issue by denveronly** [make-all/tuya-local#472]
When i try to add in to homeassistant integration the device  - i get device not supported
here is the log from tuya api

```
{
  "result": {
    "active_time": 1596730944,
    "biz_type": 0,
    "category": "cl",
    "create_time": 1589651523,
    "icon": "smart/icon/1524640833egsjpb7nrnnczo9gn5xez5mi_0.png",
    "id": "myididontsay",


    "local_key": "mykeyidontsay",

    "model": "",
    "name": "Dining room curtain",
    "online": true,

    "product_id": "spjpuwf1u2dc7tlt",
    "product_name": "SmartCurtain",
    "status": [
      {
        "code": "control",
        "value": "open"
      },
      {
        "code": "percent_state",
        "value": 100
      },
      {
        "code": "control_back",
        "value": false
      },
      {
        "code": "percent_control",
        "value": 100
      }
    ],
    "sub": false,
    "time_zone": "+02:00",
    "uid": "myididontsay",
    "update_time": 1677362149,
    "uuid": "myididontsay"
  },
  "success": true,
  "t": 1677433121451,
  "tid": "mytididontsay"
}

```

Here is the device specification attributes

```

{
  "result": {
    "category": "cl",
    "functions": [
      {
        "code": "control",
        "type": "Enum",
        "values": "{\"range\":[\"open\",\"stop\",\"close\"]}"
      },
      {
        "code": "percent_control",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "control_back",
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "control",
        "type": "Enum",
        "values": "{\"range\":[\"open\",\"stop\",\"close\"]}"
      },
      {
        "code": "percent_control",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}\t"
      },
      {
        "code": "control_back",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "percent_state",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":1,\"step\":1}\t"
      }
    ]
  },
  "success": true,
  "t": 1677487086677,
  "tid": "0e9f6245b67a11edad0316dc0085482e"
}
```

homeassistant gives this in logs

```
2023-02-27 10:44:05.782 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 65: self._api = tinytuya.Device(dev_id, address, local_key)
2023-02-27 10:44:05.883 INFO (MainThread) [custom_components.tuya_local.device] Setting protocol version for Test to 3.3
2023-02-27 10:44:06.532 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches None with quality of 0%. DPS: {"updated_at": 1677487446.1278815, "101": "open", "102": 0, "103": false, "104": 0}
2023-02-27 10:44:06.533 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/
```

some of the code i changed, cos i dont want it to be exposed, if needed i will tell what it is.
in tuya cloud HA integration the device works, as well in Tuya cloud app

**Comment by make-all** [comment]
As per the instructions on the new device form, I am closing this, as it is not providing any local protocol information that would be needed to make it work locally.

Please feel welcome to file a new issue again, and follow the instructions on the issue template carefully to get the information that is required.

**Comment by make-all** [comment]
The info you blanked is OK, I would also consider blanking lat, lon, ip and owner_id, really only product_id, product_name and sometimes model are interesting from the header.  But the information about status and commands needs to be from the specific API Explorer function mentioned in the template, which contains dp_id, and also please include the message from the Home Assistant log.

**Comment by denveronly** [comment]
i will edit and try to provide the needed info, sorry

**Comment by denveronly** [comment]
> The info you blanked is OK, I would also consider blanking lat, lon, ip and owner_id, really only product_id, product_name and sometimes model are interesting from the header. But the information about status and commands needs to be from the specific API Explorer function mentioned in the template, which contains dp_id, and also please include the message from the Home Assistant log.

is this okay ?

**Comment by make-all** [comment]
I guess this is NOT bcm700d, as that curtain is already supported and not compatible with this one.  Any identifying information you have (webpage, model info on a label on the device, etc) would help to identify it.

**Comment by denveronly** [comment]
Well it looks similar but i guess it is some clone
I brought it on Ali
![5B4B84EA-844C-41F1-AAC4-E38B6D7537FD](https://user-images.githubusercontent.com/66441516/222913478-d74af728-8a50-4de8-8db1-f061b3f43b92.jpeg)
![2CAEFBB7-1FE5-4805-B1A4-31D1EC40A697](https://user-images.githubusercontent.com/66441516/222913489-3f22b775-9f85-48a0-855c-4cdd31910029.jpeg)

here is the link i brought advertising it
I cant look in to description because the item is unavailable now
In the tuya app i dont have any model just that ID with lots of numbers
![38AF5A50-88EB-4A33-B3C1-783B8154DDF9](https://user-images.githubusercontent.com/66441516/222913740-0ab4b81a-c377-4c14-9105-fc585c5c54eb.png)

**Comment by make-all** [comment]
There's a reference there to Dooya, which is a manufacturer of curtain motors and controllers, and DC2700, which is the model number for one of their RF 433MHz remote controls https://www.alibaba.com/product-detail/Dooya-DC2700-433mhz-Single-Channel-Wireless_1600325681755.html, so I guess this device is compatible with that.  Is there a separate hub, or is the WiFi in the curtain motor unit?

**Comment by denveronly** [comment]
It is surely a wifi unit. 100%
433 mhz is used to connect a remote control

Сб, 4 марта 2023 г. в 17:38, Jason Rumney ***@***.***>:

**Comment by make-all** [comment]
OK, so the DC2700 is just the compatible RF controller, not related to the model of the device itself.  I'll just go with Dooya curtain for the name then.

**Comment by denveronly** [comment]
> OK, so the DC2700 is just the compatible RF controller, not related to the model of the device itself. I'll just go with Dooya curtain for the name then.

Sound awesome!

**Comment by denveronly** [comment]
i tried to connect my curtain providing the exact IP not auto.
and trying to sweep through all protocols.
all of them gave me nothing and protocol 3.3 gave me this

```
2023-03-05 14:26:13.156 INFO (MainThread) [custom_components.tuya_local.device] Setting protocol version for Test to 3.3
2023-03-05 14:26:13.718 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches None with quality of 0%. DPS: {"updated_at": 1678019173.241188, "101": "open", "102": 0, "103": false, "104": 0}
2023-03-05 14:26:13.720 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/
```
<img width="320" alt="Screenshot 2023-03-05 at 14 23 40" src="https://user-images.githubusercontent.com/66441516/222960421-5e0a02c1-40d8-46ac-9f87-7dae3732196d.png">

**Comment by denveronly** [comment]
all working. confirmed
you are a code-boss!
