### ISSUE TITLE
Request support for [Asakuki Diffuser]

### ISSUE THREAD

**Issue by launchm** [make-all/tuya-local#473]
# Log Message

```
This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:45 
Integration: Tuya Local (documentation, issues) 
First occurred: 6:23:23 pm (2 occurrences) 
Last logged: 6:23:23 pm

Device matches simple_switch with quality of 10%. DPS: {"updated_at": 1677435801.5472379, "1": false, "11": false, "12": 0, "13": "0", "14": 0, "103": "off", "108": "014a023b00ff", "109": "colour", "110": "1", "111": 1}
Report this to https://github.com/make-all/tuya-local/issues/

```

# Information about DPS mappings

```
{
  "result": {
    "category": "jsq",
    "functions": [
      {
        "code": "switch_led",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_spray",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "type": "Enum",
        "values": "{\"range\":[\"small\",\"large\"]}"
      },
      {
        "code": "colour_data_hsv",
        "type": "Json",
        "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      },
      {
        "code": "work_mode",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"colourful1\"]}"
      },
      {
        "code": "moodlighting",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\"]}"
      },
      {
        "code": "bright_value",
        "type": "Integer",
        "values": "{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch_led",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_spray",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "type": "Enum",
        "values": "{\"range\":[\"small\",\"large\"]}"
      },
      {
        "code": "colour_data_hsv",
        "type": "Json",
        "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      },
      {
        "code": "work_mode",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"colourful1\"]}"
      },
      {
        "code": "moodlighting",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\"]}"
      },
      {
        "code": "bright_value",
        "type": "Integer",
        "values": "{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1677410569133,
  "tid": "e69e5166b5c711edad0316dc0085482e"
}
```

# Product ID
"product_id": "6ASdNwe9IdaewQEl",
"product_name": "Aromatherapy machine",

Aromatherapy Machine which has a spray getting and LED lights which can be set to a specific colour or a rolling gradient. The device also has a night light mode, and the spray level can be weak, strong or off. I have got a link to the product, but mine is an older model without the timing button on it

https://asakuki.com/en-uk/products/asakuki-700ml-smart-wifi-essential-oil?variant=40740815634641

**Comment by make-all** [comment]
The log has 10 values, but the iot docs only have 7.  Can you go back to API Explorer, and use the last "Get Device Specification Attribute" function listed under the  "Smart Home Device System" / "Device Control" section?  This will contain dp_id values so we don't have to guess which 7 correspond to the documented ones.

**Comment by make-all** [comment]
Normally the documentation is listed in order of lowest to highest dp_id, though there have been one or two exceptions. So if I had to guess, I would say 12, 14, 103 are the undocumented ones, due to the type not matching in the expected order.  The only deviation from the cloud API docs is that the "mode" seems to use "0" and presumably "1" instead of "small" and "large" for the local protocol.  And of course colourhsv is hex encoded, not json, but that is expected based on other rgb light devices.

**Comment by launchm** [comment]
Would I need to run the installation process again, and send across the logs?

**Comment by launchm** [comment]
"code": "colour_data_hsv",
      "value": "{\"h\":123.0,\"s\":100.0,\"v\":255.0}"


![60FB145D-F968-4A96-9419-ADE22EDE8912](https://user-images.githubusercontent.com/2204760/221553499-cb8811b8-ef5a-4ca0-85fd-15cadbaf0bd3.png)
![A3BE38EA-5625-4EA4-B261-E51035E5989C](https://user-images.githubusercontent.com/2204760/221553520-13620025-37fb-45dd-89fb-6b5d3c38f660.jpeg)

**Comment by make-all** [comment]
Interesting, the h is 123, but the position on the wheel is about 330 degrees, which matches the 014a at the start of dp 108 in the log message.  Did you change the colour at all since capturing that log?

**Comment by launchm** [comment]
I used the IOT API to get the colour data once I set it on the phone.

**Comment by launchm** [comment]
RED 

"code": "colour_data_hsv",
        "value": "{\"h\":348.0,\"s\":100.0,\"v\":255.0}"

purple:
"code": "colour_data_hsv",
      "value": "{\"h\":291.0,\"s\":100.0,\"v\":255.0}"

Blue:
        "code": "colour_data_hsv",
        "value": "{\"h\":227.0,\"s\":100.0,\"v\":255.0}"

yellow
        "code": "colour_data_hsv",
        "value": "{\"h\":46.0,\"s\":100.0,\"v\":255.0}"

**Comment by make-all** [comment]
The cloud values are not what is of interest. RGB to HSV transformation is standard.  But those do seem to show that s is on a scale of 0 - 100.0 (probably in increments of 0.1) while v is on a scale of 0-255.  This matches my suspicion.

What I was really interested in is matching up a colour (or hsv data) to the value of dp 108 from the log.

**Comment by launchm** [comment]
Had to wait as it would not let me try add the device once the colour is changed or device is switched on

Green:
Device matches simple_switch with quality of 10%. DPS: {"updated_at": 1677435801.5472379, "1": false, "11": false, "12": 0, "13": "0", "14": 0, "103": "off", "108": "014a023b00ff", "109": "colour", "110": "1", "111": 1}


Red:
Device matches simple_switch with quality of 10%. DPS: {"updated_at": 1677507572.3959386, "1": true, "11": true, "12": 0, "13": "0", "14": 0, "103": "small", "108": "ff000d016464ff", "109": "colour", "110": "2", "111": 255}


Blue:
Device matches simple_switch with quality of 10%. DPS: {"updated_at": 1677507821.93708, "1": true, "11": true, "12": 0, "13": "0", "14": 0, "103": "small", "108": "003cff00e164ff", "109": "colour", "110": "2", "111": 255}

**Comment by make-all** [comment]
Thanks.  It looks like this is the 7 byte rgbhhsv format, except they strip the leading 0 from h when it is < 256, which makes it a real pain to parse.

**Comment by launchm** [comment]
does this mean that it is not an easy one to do, and if so, would it still be considered?

**Comment by make-all** [comment]
Probably not for a one off buggy device.  If other devices have this strange format I might consider it.
