### ISSUE TITLE
Request support for Moes Smart Infrared AC Controller - Model SD16Pro

### ISSUE THREAD

**Issue by bparten** [make-all/tuya-local#478]
# Information about DPS mappings

Note: This device has a Main and Sub Device:

MAIN Device:
---------------
{
  "result": {
    "category": "hwktwkq"
  },
  "success": true,
  "t": 1677551725289,
  "tid": "8e41efaab71011ed83008ee81be32eee"
}

SUB Device (i.e. Mini-Split AC System):
-----------------------------------------
{
  "result": {
    "category": "infrared_ac",
    "functions": [
      {
        "code": "F",
        "desc": "{\"min\":0,\"max\":3,\"scale\":0,\"step\":1,\"type\":\"Integer\"}",
        "name": "fan speed",
        "type": "ENUM",
        "values": "{\"min\":0,\"max\":3,\"scale\":0,\"step\":1,\"type\":\"Integer\"}"
      },
      {
        "code": "M",
        "desc": "{\"min\":0,\"max\":4,\"scale\":0,\"step\":1,\"type\":\"Integer\"}",
        "name": "mode",
        "type": "ENUM",
        "values": "{\"min\":0,\"max\":4,\"scale\":0,\"step\":1,\"type\":\"Integer\"}"
      },
      {
        "code": "PowerOff",
        "desc": "PowerOff",
        "name": "PowerOff",
        "type": "STRING",
        "values": "PowerOff"
      },
      {
        "code": "PowerOn",
        "desc": "PowerOn",
        "name": "PowerOn",
        "type": "STRING",
        "values": "PowerOn"
      },
      {
        "code": "T",
        "desc": "{\"min\":16,\"max\":30,\"scale\":0,\"step\":1,\"type\":\"Integer\"}",
        "name": "temperature",
        "type": "ENUM",
        "values": "{\"min\":16,\"max\":30,\"scale\":0,\"step\":1,\"type\":\"Integer\"}"
      }
    ],
    "status": [
      {
        "code": "wind",
        "type": "ENUM",
        "values": "{\"min\":0,\"max\":3,\"scale\":0,\"step\":1,\"type\":\"Integer\"}"
      },
      {
        "code": "mode",
        "type": "ENUM",
        "values": "{\"min\":0,\"max\":4,\"scale\":0,\"step\":1,\"type\":\"Integer\"}"
      },
      {
        "code": "power",
        "type": "BOOLEAN",
        "values": "{}"
      },
      {
        "code": "temp",
        "type": "ENUM",
        "values": "{\"min\":16,\"max\":30,\"scale\":0,\"step\":1,\"type\":\"Integer\"}"
      }
    ]
  },
  "success": true,
  "t": 1677551806610,
  "tid": "bebdf286b71011ed83008ee81be32eee"
}

DPS Examples (Both Main and Sub Device Report These)
--------------------------------------------------------------
{
  '1': true,              <---  True: A/C Unit On,  False: A/C Unit Off
  '2': 233,              <---  Measured Temperature (i.e. 23.3C)
  '3': 21,                <---  Temperature Set Point (C)
  '4': 'cold',            <---  A/C System Modes:  'cold', 'warm', 'auto', 'air', 'dehumidify'
  '5': 'auto',           <---  Fan Speeds:  'auto', 'low', 'middle', 'high'
  '9': 26,                <---  ?? (No Change Observed)
  '10': 20,              <---  ?? (No Change Observed)
  '11': 'f',               <---  Temp Units
  '12': 30,              <---  Humidity %
  '15': 'scene_1',   <---  ?? (No Change Observed)
  '16': 'done',       <---  ?? (No Change Observed)
  '18': 962,           <---  ?? (No Change Observed)
}

Protocol Version 3.3

# Product ID

"hwktwkq"

# Information about how the device functions

When connecting this Moes Controller to the Tuya Smart App, you go though an extra step to load the correct Infrared codes for the particular A/C unit you are trying to control.

"MoesGo Wifi Smart Air Conditioner Controller"
Model #:  S16Pro
https://www.amazon.com/gp/product/B0B8S3DW7D

**Comment by make-all** [comment]
I've just bought a similar IR controller myself (actually the same device with sensors supported by ir_remote_sensors.yaml).  I think the way forward with these devices is to implement ir_send and ir_learn commands the same way that the broadlink integration works.

The problem with IR remotes (and zigbee hubs) is that there is no limit to the devices that can be added (including non-Tuya devices), so configuration file proliferation will be a problem if we implement them using the subdevices exposed.

**Comment by make-all** [comment]
As with the ir_remote_sensors.yaml device, I think for now this can be added with just the built in sensor support, and extended to ir remote functionality when I can figure out the protocol for ir_send and ir_learn.  My understanding from the other device is that the tuya cloud integration works for remote commands, but does not support the sensors, so this will complement that nicely.

**Comment by tsktech** [comment]
+1 following, have a similar device

**Comment by phoenixmarines** [comment]
@bparten Did you manage to get your Moes IR remote to send the IR signal to the air conditioner. So far I can only change settings and get the display to update but the IR signal is not sent?

**Comment by joeldickson** [comment]
I've got the same problem above, is there something with the subdevice that you mentioned that needs to be configured to fix this?
