### ISSUE TITLE
Failed to refresh device state

### ISSUE THREAD

**Issue by Krispkiwi** [make-all/tuya-local#483]
Hey mate, I'm noticing a issue with my Tuya smart plugs with this integration lately. They keep dropping offline with a "Failed to refresh device state " error in the logs despite my unifi stats on them showing a consistently good experience.

It's happened with numerous plugs in different rooms. 

Logs show:
"Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:174
Integration: Tuya Local ([documentation](https://github.com/make-all/tuya-local), [issues](https://github.com/make-all/tuya-local/issues))
First occurred: 12:48:59 PM (6 occurrences)
Last logged: 1:10:43 PM

Failed to refresh device state for Electric Blanket Right
Failed to refresh device state for Electric Blanket Left
Failed to refresh device state for Computer Monitor Right"

**Comment by make-all** [comment]
smartplugv1?

**Comment by Krispkiwi** [comment]
> smartplugv1?

Smartplugv2 for all of them.

**Comment by make-all** [comment]
I may need to revert the changes to poll for power/current/voltage then. Stability is more important than working around shortcomings with specific Tuya devices.

**Comment by Krispkiwi** [comment]
> I may need to revert the changes to poll for power/current/voltage then. Stability is more important than working around shortcomings with specific Tuya devices. Until now, there were only reports of problems with smartplugv1 (#477), so I thought I could get away with only reverting it there.

I just changed back to 2.0, haven't had any warnings yet so far so it may be the changes made. It's only been 15 min or so but i normally would have got them by now.

**Comment by Krispkiwi** [comment]
Testing v2.3 and that appears to be fine as well.

**Comment by blavak68** [comment]
I have the same problem

all my smart plugs are version Smartplugv2

After downgrade from 2.4 to 2.3 everything looks fine

**Comment by Krispkiwi** [comment]
> I have the same problem
> 
> all my smart plugs are version Smartplugv2
> 
> After downgrade from 2.4 to 2.3 everything looks fine

I just noticed 2.3 appears to have the issue with my kettle as well so I'm sitting on 2.0 atm all seems fine

**Comment by Krispkiwi** [comment]
I just want to double check I understand correctly before doing this, are we just adding custom_components/tuya_local/devices/smartplugv2_polled_power.yaml and leaving the rest the same or are we removing something as well

**Comment by make-all** [comment]
The change reverts smartplugv2.yaml to 2023.2.3 and earlier version and adds a new config smartplugv2_polled_power.yaml which is the 2023.2.4 version of smartplugv2.yaml.

**Comment by Krispkiwi** [comment]
> The change reverts smartplugv2.yaml to 2023.2.3 and earlier version and adds a new config smartplugv2_polled_power.yaml which is the 2023.2.4 version of smartplugv2.yaml.

Pretty sure I've done it wrong, I couldn't see a download link when clicking through on the commit so I ended up copying the new v2 yaml over top then adding the polled_power.yaml getting errors though.

**Comment by blavak68** [comment]
who i find the file DEVICE.md ?

**Comment by make-all** [comment]
You don't have to edit anything, just update to the main branch.

**Comment by blavak68** [comment]
I'm now on version 2.3, is it enough to upgrade to 2.4?

**Comment by make-all** [comment]
No, 2023.2.4 is the version that has the problem.

**Comment by Krispkiwi** [comment]
> I'm now on version 2.3, is it enough to upgrade to 2.4?

https://imgur.com/a/qJGLI6S This

**Comment by blavak68** [comment]
It probably doesn't belong here, but what are DPs used for calibration (21, 22...) or how to use them?

**Comment by Krispkiwi** [comment]
On the main branch I'm also getting "Failed to refresh device state for Kitchen Kettle" for the Kogan kettle

**Comment by blavak68** [comment]
> You don't have to edit anything, just update to the main branch.

for me smartplug are on the main branch  OK

**Comment by make-all** [comment]
Calibration discussion: #467
Summary is that nobody is sure what the values mean, or whether it is possible to change them after the device has left the factory.
