### ISSUE TITLE
Request support for Blitzwolf BW-LT11 LED Strip

### ISSUE THREAD

**Issue by sortilego** [make-all/tuya-local#487]
Greetings, 

It would be much appreciated to get working theese LED strips.

Product Name: BW-LT11 - 灯带控制器 - 东莞汇唐
Device ID: 04017065a4e57ca6f16c
Product Category: dj

Instruction sets attached.

[standard_status_set.txt](https://github.com/make-all/tuya-local/files/10882117/standard_status_set.txt)
[standard_instruction_set.txt](https://github.com/make-all/tuya-local/files/10882118/standard_instruction_set.txt)

https://www.blitzwolfeurope.com/Smart-LED-Light-Strip-BlitzWolf-BW-LT11-Smart-LED

Any extra info needed just ask, and I get anything.

Thanks

**Comment by make-all** [comment]
Please fill out the New Device template instead of bypassing the issue templates.
