### ISSUE TITLE
WiFi Wireless-Relay Switch Module - New Device

### ISSUE THREAD

**Issue by wardend01** [make-all/tuya-local#488]
Would be nice to have the following new device added:  [1-Channel WiFi Wireless-Relay Switch Module - Smart Momentary Inching Controller,DC 7-32V DIY Remote Control Garage Door,Compatible with Alexa Echo Go](https://www.amazon.com/gp/product/B08JCTWZXJ/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1)

Comes in a 1 Channel, 2 Channel and 4 Channel version.

![51kXISEUipL _SY90_](https://user-images.githubusercontent.com/92233082/222808085-7cd3a5a6-6809-4570-8ded-bf74d629e68e.jpg)

**Comment by make-all** [comment]
Insufficient nformation

**Comment by cataseven** [comment]
Device Information
Product Name: 1-433
Product Category: tdq


Code | Type | Values
-- | -- | --
switch_1 | Boolean | "{true,false}"
countdown_1 | Integer | {   "unit": "s",   "min": 0,   "max": 86400,   "scale": 0,   "step": 1 }
relay_status | Enum | {   "range": [     "0",     "1",     "2"   ] }
random_time | String | {   "maxlen": 255 }
cycle_time | String | {   "maxlen": 255 }
switch_inching | String | {   "maxlen": 255 }

Payloads:
switch_1 --- code: 1
countdown_1 --- code: 9
relay_status ---- code: 38
random_time ---- code: 42
cycle_time ---- code: 43
switch_inching ---- code: 44  (If closed: value looks AAABH///f///f///f///f///f///f///f///f1//f0//f1//f1//Y1//f0//f0//f///f///f///f//Qf///f//Yf///f//2U123Y567c9ABCDEF and if open: AQABH///f///f///f///f///f///f///f///f1//f0//f1//f1//Y1//f0//f0//f///f///f///f//Qf///f//Yf///f//2U123Y567c9ABCDEF)
