### ISSUE TITLE
WiFi Wireless-Relay Switch Module - New Device

### ISSUE THREAD

**Issue by cataseven** [make-all/tuya-local#495]
Device Information
Product Name: 1-433
Product Category: tdq

Code | Type | Values
-- | -- | --
switch_1 | Boolean | "{true,false}"
countdown_1 | Integer | {   "unit": "s",   "min": 0,   "max": 86400,   "scale": 0,   "step": 1 }
relay_status | Enum | {   "range": [     "0",     "1",     "2"   ] }
random_time | String | {   "maxlen": 255 }
cycle_time | String | {   "maxlen": 255 }
switch_inching | String | {   "maxlen": 255 }

Payloads:
switch_1 --- code: 1
countdown_1 --- code: 9
relay_status ---- code: 38
random_time ---- code: 42
cycle_time ---- code: 43
switch_inching ---- code: 44  (If closed: value looks AAABH///f///f///f///f///f///f///f///f1//f0//f1//f1//Y1//f0//f0//f///f///f///f//Qf///f//Yf///f//2U123Y567c9ABCDEF and if open: AQABH///f///f///f///f///f///f///f///f1//f0//f1//f1//Y1//f0//f0//f///f///f///f//Qf///f//Yf///f//2U123Y567c9ABCDEF)

_Originally posted by @cataseven in https://github.com/make-all/tuya-local/issues/488#issuecomment-1454841937_

**Comment by make-all** [comment]
This is already covered by `simple_switch_timerv2`.

**Comment by cataseven** [comment]
Inching mode doesnt work properly. My device is set to 1 seconds. When I trigger via Tuya Local, switch state is shown different on different integration. On locaş tuya it shown On for 1 second but on Tuya Local it remains 40 seconds (even it is not actually On because I also check official app state at the same time) ıt shows On even it is off

**Comment by make-all** [comment]
Inching mode is a complex undocumented field, and is not supported.
