### ISSUE TITLE
Request support for Gosund Smart Plug (Energy Monitoring)

### ISSUE THREAD

**Issue by pnm1977** [make-all/tuya-local#497]
### Please add support for Gosund Smart Plug (Energy Monitoring).
**I have 2 types and the DP_ID list is different for both on the Tuya IoT Platform so will add them separately below.**

### Device Type 1 
Product ID - **UP111-C 16A Mini Smart Plug**

{
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "switch_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "add_ele",
        "dp_id": 17,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":50000,\"scale\":3,\"step\":100}"
      },
      {
        "code": "cur_current",
        "dp_id": 18,
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_power",
        "dp_id": 19,
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":0,\"max\":50000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "cur_voltage",
        "dp_id": 20,
        "type": "Integer",
        "values": "{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1677966708507,
  "tid": "c389a598bad611edb7fdc2ad824e71c9"
}

### Device Type 2
Product ID - **UP111_RTL**

{
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "switch_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "dp_id": 38,
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "light_mode",
        "dp_id": 39,
        "type": "Enum",
        "values": "{\"range\":[\"relay\",\"pos\",\"none\"]}"
      },
      {
        "code": "child_lock",
        "dp_id": 40,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "cycle_time",
        "dp_id": 41,
        "type": "String",
        "values": "{}"
      },
      {
        "code": "random_time",
        "dp_id": 42,
        "type": "String",
        "values": "{}"
      },
      {
        "code": "switch_inching",
        "dp_id": 43,
        "type": "String",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "add_ele",
        "dp_id": 17,
        "type": "Integer",
        "values": "{\"unit\":\"kwh\",\"min\":0,\"max\":50000,\"scale\":3,\"step\":100}"
      },
      {
        "code": "cur_current",
        "dp_id": 18,
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":80000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_power",
        "dp_id": 19,
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":0,\"max\":200000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "cur_voltage",
        "dp_id": 20,
        "type": "Integer",
        "values": "{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "relay_status",
        "dp_id": 38,
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "light_mode",
        "dp_id": 39,
        "type": "Enum",
        "values": "{\"range\":[\"relay\",\"pos\",\"none\"]}"
      },
      {
        "code": "child_lock",
        "dp_id": 40,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "cycle_time",
        "dp_id": 41,
        "type": "String",
        "values": "{}"
      },
      {
        "code": "random_time",
        "dp_id": 42,
        "type": "String",
        "values": "{}"
      },
      {
        "code": "switch_inching",
        "dp_id": 43,
        "type": "String",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1677967374793,
  "tid": "50a763debad811ed9f7936041e250963"
}

**Comment by make-all** [comment]
First one is covered by `smartplugv2`

**Comment by pnm1977** [comment]
> First one is covered by `smartplugv2`

Confirmed. I couldn't connect but now tried with specific IP address instead of "Auto" and it's working. Thanks.
