### ISSUE TITLE
Tuya heater preset modes and set temperature not working

### ISSUE THREAD

**Issue by awaismun** [make-all/tuya-local#5]
Hi,

First of all thanks for this setup for Tuya devices. 

I have couple of Tuya heater which I have now set up in HA with Local Tuya. The climate.turn_on and climate.turn_off are working absolutely fine.

Following services are not working:

climate.set_preset_mode - The heaters I have does have the Comfort, Eco and Antifreeze modes.
climate.set_temperature - This is something I was able to do through the Tuya webbased integration in HA.

The heaters are set up as "heaters" in the device setup without choosing a specific model from the list.

The attributes in HA and a picture of my Tuya heater is attached.

![attributes](https://user-images.githubusercontent.com/56998062/94710452-2c8e0b80-0347-11eb-82f1-9cc4dc1f34c9.png)

![heater](https://user-images.githubusercontent.com/56998062/94710698-6e1eb680-0347-11eb-8956-f40fc7b9046d.png)

**Comment by make-all** [comment]
The functionality listed seems similar to Goldair GPPH heaters, but the protocol is obviously not compatible, or the heater would be detected and function correctly.  There seems to be no standard for the dps mappings, so if you can capture them using tuya-cli or by eavesdropping the communication with the app, or by finding the device schema on your phone's filesystem, then I will look at adding this device when I have finished my current refactoring work.

**Comment by awaismun** [comment]
Thanks for your reply.

I am not very technical, but would love to do this.

Which tuya-cli commands should I use to get what we need? Would like this method since I am up and running already on tuya-cli.

**Comment by awaismun** [comment]
I tried it out with this:

tuya-cli get --id xxxxx --key xxxxx --ip 192.168.1.7 --all

This is not returning anything. Absolutely nothing. 

Then I tried only this:
tuya-cli get --id xxxxx --key xxxxx --all

Response: Error: find() timed out. Is the device powered on and the ID or IP correct?

Then I tried PING 192.168.1.7 and got response from the device. 

Last I tried this: 

tuya-cli get --id xxxxxx --key xxxxx --ip 192.168.1.7 ----protocol-version 3.3

Response: true

What am I missing and why am I not getting the correct response?

**Comment by make-all** [comment]
Here's what works for me:
```
tuya-cli get --id XXXXX --key XXXXX -a

{ devId: 'XXXXX',
  dps: { '1': false, '2': 0, '4': 0, '5': 0, '6': '2401' } }
```

**Comment by awaismun** [comment]
Its not working for me. After waiting for almost 1 hour I get this error:

(node:13772) UnhandledPromiseRejectionWarning: Error: Error from socket
    at Socket.<anonymous> (C:\Users\munawa\AppData\Roaming\npm\node_modules\@tuyapi\cli\node_modules\tuyapi\index.js:351:30)
    at Socket.emit (events.js:315:20)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:418:5)
    at onwrite (_stream_writable.js:445:5)
    at internal/streams/destroy.js:50:7
    at Socket._destroy (net.js:679:5)
    at Socket.destroy (internal/streams/destroy.js:38:8)
    at afterWriteDispatched (internal/stream_base_commons.js:154:17)
    at writeGeneric (internal/stream_base_commons.js:145:3)
(node:13772) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:13772) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by awaismun** [comment]
I got it to work!

Here is the dps. Will be thankful if you can add support for it when you have time :)

{
  devId: xxxxxx,
  dps: { '1': true, '2': 22, '3': 24, '4': 'low', '12': 0 }
}

Looks like this:
1: ON/OFF
2: Target temp
3: Current temp
4: Preset mode (low/high/af(For antifreze)
12: Not sure

**Comment by awaismun** [comment]
Hi @make-all!

Thanks for your help so far. When will you be able to add this device? I am using HA to automate the heater ON/OFF bit for some reason the target temp is automatically set to 20. 

I am not able to set a temperature with HA using set_temperature.

Thanks in advance.

**Comment by make-all** [comment]
Support added in new release.

**Comment by awaismun** [comment]
Just updated to mewer versions but not getting any new option to select Andersson device?

**Comment by make-all** [comment]
I forgot to adjust the list for manual configuration.  But setting it to Auto should work.

**Comment by awaismun** [comment]
Yes, it did work with auto now. Thanks. Working good!

**Comment by make-all** [comment]
The manual config is also there - under gsh_heater.
