### ISSUE TITLE
BHT-6000 BECA thermostat

### ISSUE THREAD

**Issue by antoweb** [make-all/tuya-local#50]
I have a BHT-6000 but in stage two, after insered id and key, from device type i have only switch.

**Comment by antoweb** [comment]
Yes you are true. All values are divided by 2

**Comment by antoweb** [comment]
To be precise desired temperaure and current temperature values are divided by 2

**Comment by antoweb** [comment]
Any news?

**Comment by make-all** [comment]
Do you have it configured in localtuya as well, or the app running on your phone? Riya devices are limited to one local connection.

**Comment by antoweb** [comment]
I tried but I'm sure those two attributes always remain fixed

**Comment by antoweb** [comment]
> Hi! I changed my cell phone and can't find the Beca BHT 6000 app anymore on google play. any other place or way? (I already wrote to Beca company without answer). thank you!

Beca is tuya Smart or Smart Life app is the same
