### ISSUE TITLE
climate: Unrecognised HVAC Mode of None ignored

### ISSUE THREAD

**Issue by Krispkiwi** [make-all/tuya-local#502]
Hey mate, got 2 more showing up with this bug, is there a quick way i can transfer the fixes over? The Kogan kettle and lightbulbs are doing it as well https://imgur.com/a/tEjYNOF

**Comment by make-all** [comment]
There is nothing to transfer, only smartplugs were changed to use the upatedps forced polling.

If you enable debug logging on custom_components.tuya_local.device and tinytuya you might be able to spot what is causing the problem.

In config/configuration.yaml:

```yaml
logger:
    default: warning
    custom_components.tuya_local.device: debug
    tinytuya: debug

**Comment by make-all** [comment]
It was never addressed, it is a known misbehavior of this device that it often fails to return anything other than the current temperature.  What was addressed is that the previous known value is now kept if it goes into this state once HA is up and running (as long as the kettle does not go offline completely).  But it still shows up if the kettle is in this state when HA starts, or if the kettle goes offline for a long period and comes back in this state.
