### ISSUE TITLE
Request support for Heat Storm 6000 watt Infrared Electric Garage Heater

### ISSUE THREAD

**Issue by A-J-O** [make-all/tuya-local#510]
First time doing this so hopefully everything is correct.
Managed to butcher together some sort of working yaml  

# Log Message
 "data": {
    "name": "HeatStorm Garage heater",
    "type": "heatstorm_garage_heater",
    "device_id": "**REDACTED**",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": "auto",
    "api_version_set": 3.3,
    "api_version_used": 3.3,
    "api_working": true,
    "status": {},
    "cached_state": {
      "updated_at": 1678225991.7319975,
      "1": true,
      "2": 18,
      "3": 19,
      "4": "Auto",
      "5": "10",
      "7": true,
      "13": 0,
      "19": "c",
      "20": 64,
      "21": 66
    },
    "pending_state": {},
    "connected": true,

```
Please paste logs here
```

# Information about DPS mappings

```
{
  "result": {
    "category": "qn",
    "functions": [
      {
        "code": "switch",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "lang_config": {
          "unit": "°C"
        },
        "name": "Set Temperature",
        "type": "Integer",
        "values": "{\"unit\":\"°C\",\"min\":4,\"max\":37,\"scale\":0,\"step\":1}"
      },
      {
        "code": "mode",
        "lang_config": {
          "auto": "",
          "high": "",
          "low": ""
        },
        "name": "Mode",
        "type": "Enum",
        "values": "{\"range\":[\"Auto\",\"Low\",\"High\"]}"
      },
      {
        "code": "level",
        "lang_config": {
          "10": "10%",
          "50": "50%",
          "100": "100%",
          "off": ""
        },
        "name": "Brightness",
        "type": "Enum",
        "values": "{\"range\":[\"Off\",\"10\",\"50\",\"100\"]}"
      },
      {
        "code": "child_lock",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Child Lock",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "week_program1",
        "lang_config": {
          "unit": ""
        },
        "name": "Week Program（freestyle）",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "temp_unit_convert",
        "lang_config": {
          "c": "°C",
          "f": "℉"
        },
        "name": "Temperature Scale",
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "temp_set_f",
        "lang_config": {
          "unit": "℉"
        },
        "name": "Set Temperature ",
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":40,\"max\":99,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_current_f",
        "lang_config": {
          "unit": "℉"
        },
        "name": "Current Temperature",
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":16,\"max\":99,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "lang_config": {
          "unit": "°C"
        },
        "name": "Set Temperature",
        "type": "Integer",
        "values": "{\"unit\":\"°C\",\"min\":4,\"max\":37,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_current",
        "lang_config": {
          "unit": "°C"
        },
        "name": "Current Temperature",
        "type": "Integer",
        "values": "{\"unit\":\"°C\",\"min\":-9,\"max\":37,\"scale\":0,\"step\":1}"
      },
      {
        "code": "mode",
        "lang_config": {
          "auto": "",
          "high": "",
          "low": ""
        },
        "name": "Mode",
        "type": "Enum",
        "values": "{\"range\":[\"Auto\",\"Low\",\"High\"]}"
      },
      {
        "code": "level",
        "lang_config": {
          "10": "10%",
          "50": "50%",
          "100": "100%",
          "off": ""
        },
        "name": "Brightness",
        "type": "Enum",
        "values": "{\"range\":[\"Off\",\"10\",\"50\",\"100\"]}"
      },
      {
        "code": "child_lock",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Child Lock",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fault",
        "lang_config": {
          "fault1": "Temp sensor fault",
          "fault2": "Tilt over ",
          "fault3": "Over-Voltage",
          "fault4": ""
        },
        "name": "Fault Alarm",
        "type": "Bitmap",
        "values": "{\"label\":[\"fault1\",\"fault2\",\"fault3\",\"fault4\"],\"maxlen\":4}"
      },
      {
        "code": "week_program1",
        "lang_config": {
          "unit": ""
        },
        "name": "Week Program（freestyle）",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "temp_unit_convert",
        "lang_config": {
          "c": "°C",
          "f": "℉"
        },
        "name": "Temperature Scale",
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "temp_set_f",
        "lang_config": {
          "unit": "℉"
        },
        "name": "Set Temperature ",
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":40,\"max\":99,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_current_f",
        "lang_config": {
          "unit": "℉"
        },
        "name": "Current Temperature",
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":16,\"max\":99,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1678230854001,
  "tid": "c676d308bd3d11ed8e091e9ebf08afbf"
```

# Product ID
product:
  - id: wta6rb1zqwayghxv

# Information about how the device functions

Manual [https://cdn.shopify.com/s/files/1/1873/7325/files/HS_6000_GC_manual_2020_V2.pdf?v=1611599756](url)

**Semi working .yaml** 
name: HeatStorm Garage heater
product:
  - id: wta6rb1zqwayghxv
primary_entity:
  entity: climate
  dps:
    - id: 1
      type: boolean
      name: hvac_mode
      mapping:
        - dps_val: false
          value: "off"
          icon: "mdi:fire-off"
        - dps_val: true
          value: heat
          icon: "mdi:fire"
    - id: 2
      type: integer
      name: temperature
      range:
        min: 4
        max: 37
    - id: 3
      type: integer
      name: current_temperature
    - id: 4
      type: string
      name: preset_mode
      mapping:
        - dps_val: auto
          value: Auto
        - dps_val: low
          value: Low
        - dps_val: high
          value: High

**Comment by A-J-O** [comment]
The display brightness is not working properly. The units display is only capable of the preset values of off, 10% , 50% and 100% 
HA is using a slider for the brightness value. 
The native tuya integration gives a drop-down selection of 0,10,50,100 but incorrectly reports this as temperature 

The child lock is also being reported incorrectly. It is reporting locked when it is really unlocked and vice versa.
All other functions are working properly.  
Thank You

**Comment by make-all** [comment]
The slider should snap to the closest allowed value. Does it not do this? Slider is the native HA UI for brightness. The config does define just 0, 10, 50 and 100 as allowed values.

**Comment by make-all** [comment]
I noticed that snapping to the nearest valid value is not actually implemented for the generic case.  I think for the devices that used that before, the values were evenly spaced, and "step" was set, to get the snapping.  So I have implemented a general case snap to nearest mapping for numeric values, which does not require evenly spaced numbers.  This probably fixes at least one other device (which the user has been quiet about, probably because they submitted the config themselves and are putting up with the UI not working for brightness).  I also inverted the child lock.

**Comment by A-J-O** [comment]
I replaced custom_components/tuya_local/devices/heatstorm_hs6000gc_heater.yaml and custom_components/tuya_local/helpers/device_config.py
Not sure what to do with tests/mixins/light.py or if I even need to.
The child lock works/reports as expected 
The brightness is not.
Moving the switch or the slider results in:  
 Failed to call service light/turn_off.type str doesn't define_round_method

**Comment by make-all** [comment]
The files under tests are not installed to HA.  But if you are using HACS, I would recommend using the "Redownload" function there and selecting "main" as the version to install, instead of replacing individual files.

**Comment by A-J-O** [comment]
If I redownload and select "main" the version I end up with is 01e1cb0
This results in the device becoming unavailable and the following warnings and errors being generated in HA 


2023-03-12 12:03:55.259 WARNING (MainThread) [homeassistant.helpers.entity] Update of select.heatstorm_heavy_duty_heater_temperature_unit is taking over 10 seconds
2023-03-12 12:06:27.737 ERROR (MainThread) [custom_components.tuya_local.device] Failed to refresh device state for Heatstorm heavy duty heater.
2023-03-12 12:07:49.246 ERROR (MainThread) [custom_components.tuya_local.device] Heatstorm heavy duty heater receive loop terminated by exception 'TuyaLocalSelect' object has no attribute 'dps'
Traceback (most recent call last):
  File "/config/custom_components/tuya_local/device.py", line 197, in receive_loop
    for dp in entity.dps():
AttributeError: 'TuyaLocalSelect' object has no attribute 'dps'

If I then redownload 2023.3.0 and manually add heatstorm_hs6000gc_heater.yaml the device becomes available. 
The switch for the brightness will turn off the display but will not turn it back on 
the slider will turn the display on only if slid all the way to 100%

If I replace Device_config.py  
The switch will turn off the display but will not turn it back on. 
The slider will turn the display back on and will snap at 10%, 50%, at 100% all levels function

**Comment by make-all** [comment]
Thanks for reporting these. I have fixed the exception being thrown from recently added code to allow dps to trigger automations if they are only ever sent with a single value.

For the light switch, I need to look at the logic and see if I can make that work as well.

**Comment by jeffd1845** [comment]
I am trying to add this heater to a working Tuya Local installation and am not presented with an option to select this as a heater.  

I  see: 1) neptun_smart_waterleak 2) mypin_6l_videopetfeeder 3) s11_rfir_remote or 4) basic_ir_remote as device type options.  

Has something changed with this integration?  I have the latest 2023 version of the heater, including an external thermostat.

**Comment by make-all** [comment]
Seeing those options indicates that you are getting no data from your device (but also no errors). The protocol may need to be set to something else (3.2 or 3.4 seem to be the ones that get misdetected without errors)

**Comment by jeffd1845** [comment]
I tried all available protocol versions with the same results.  I also deleted and re-added another device to tuya local to make sure it was not a firewall or vlan routing issue (tuya devices are on a dedicated vlan). 

One note is that the Product ID shows as **onpvep0lp6wtg2us** in the Tuya Home Assistant dashboard, not as **wta6rb1zqwayghxv** in the notes above.

**Comment by make-all** [comment]
It seems you may have an incompatible model / firmware version.

It is better to make a new device request I think.
