### ISSUE TITLE
Request support for Etersky Aroma Diffuser

### ISSUE THREAD

**Issue by Kannix2005** [make-all/tuya-local#511]
# Log Message

```
Device matches kogan_glass_1_7l_kettle with quality of 25%. DPS: {"updated_at": 1678271284.8826845, "1": true, "2": false, "3": "large", "4": "cancel", "5": 0, "7": false, "9": "white", "11": 1}
Report this to https://github.com/make-all/tuya-local/issues/
Device matches kogan_glass_1_7l_kettle with quality of 25%. DPS: {"updated_at": 1678272300.899988, "1": true, "2": false, "3": "large", "4": "cancel", "5": 0, "7": false, "9": "white", "11": 0}
```

# Information about DPS mappings

```
{
  "code": 2009,
  "msg": "not support this device",
  "success": false,
  "t": 1678272447989,
  "tid": "9e76632dbd9e11edb803d6013968de13"
}

DP Ids from debug:
Power 1
Spray 2
Mode 3
Spray Timer 4
Spray Timer 5
Light 7
Brightness 8
LED Mode 9
Color 10
Fault 11
```

# Product ID

rvajlvjh4qoj1lkn

# Information about how the device functions

The diffusion function is important. The night-light not so much. Currently simple switch does not work. See
https://www.amazon.de/gp/product/B0B56BT1MX/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

**Comment by make-all** [comment]
I have made an initial configuration, but there is no information about some of those dps, so I have made some guesses based on other similar devices.
1. Only two modes (large and small)?
2. The color format has a high likelihood to be incorrect.
3. The brightness range may be incorrect.
4. Power is a master switch, and spray and light each have their own switches?

**Comment by make-all** [comment]
1. I mean "Mode 3", which in the log has a value "large".  I made the config with "large" and "small", which was what another diffuser had.
