### ISSUE TITLE
Bug with Wifi Digital Meter PJ-1103 Power Meter

### ISSUE THREAD

**Issue by Casadomoticap** [make-all/tuya-local#512]
Hi mate, I found that every time that I restart HA, I have this error in the LOGs.
But in the other hand the device also works. That has me confused 

**Describe the bug:**

 Este error se originó a partir de una integración personalizada.

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:184
Integration: Tuya Local (documentation, issues)
First occurred: 20:23:16 (1 occurrences)
Last logged: 20:23:16

Failed to refresh device state for Clamp power meter

**To Reproduce:**
If you have integrated the clamp power meter, restart HA, go to the LOGs and you will see the error failed to refresh state

**Expected behavior:**
No have a failed to refresh device every time that I restart HA. 

**Additional context:**
I don't know what means this error. Maybe you know what is it and can help me to solve it :) 

Thank you

**Comment by make-all** [comment]
It means Home Assistant was not able to get the device status the first time it connected.  As long as it is recovering, this is not a problem and should be expected occasionally.  This may be more likely if your protocol version is set to "auto", so if you know what version it is using (you can find out by downloading the device diagnostics and looking there) it might help to set it to that version.
