### ISSUE TITLE
Request support for Kettle SILVERCREST® Czajnik elektryczny Lidl Smart Home, 1,7 l

### ISSUE THREAD

**Issue by spitfire** [make-all/tuya-local#516]
# Log Message
```
Device matches mirabella_genio_usb with quality of 29%. DPS: {"updated_at": 1678366588.621065, "1": false, "2": 28, "8": 100, "15": "0", "16": "5", "103": false, "104": 5}
Report this to https://github.com/make-all/tuya-local/issues/
```

# Information about DPS mappings
```

  "result": {
    "category": "bh",
    "functions": [
      {
        "code": "start",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":40,\"max\":100,\"scale\":0,\"step\":5}"
      },
      {
        "code": "warm",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "warm_time",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":120,\"scale\":0,\"step\":30}"
      }
    ],
    "status": [
      {
        "code": "start",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_current",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_set",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":40,\"max\":100,\"scale\":0,\"step\":5}"
      },
      {
        "code": "warm",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "warm_time",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":120,\"scale\":0,\"step\":30}"
      },
      {
        "code": "countdown_left",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":120,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1678367912262,
  "tid": "e3924341be7c11edbcdaea52450d735d"
}
```

# Product ID
```
{
  "result": {
    "active_time": 1678365193,
    "category": "bh",
    "category_name": "Smart Kettle",
    "create_time": 1678365193,
    "gateway_id": "",
    "icon": "smart/icon/ay1559701439060fw6BY/9e933381fabaa1b6b0718d93bb56f322.png",
    "id": "bf7d0e935a0fad92ca0cem",
    "ip": "redacted",
    "lat": "redacted",
    "local_key": "redacted",
    "lon": "redacted",
    "model": "WK0828RT",
    "name": "Czajnik",
    "online": true,
    "owner_id": "71836261",
    "product_id": "il4ofqon04yai1xe",
    "product_name": "Water Kettle",
    "sub": false,
    "time_zone": "+01:00",
    "update_time": 1678365898,
    "uuid": "06f9dabd0bb25fc2"
  },
  "success": true,
  "t": 1678368090626,
  "tid": "4dea6263be7d11edafb1d6e7dc4fd226"
}
```

# Information about how the device functions
It's a smart kettle
SILVERCREST® Czajnik elektryczny Lidl Smart Home, 1,7 l
https://www.lidl.pl/p/silvercrest-czajnik-elektryczny-lidl-smart-home-1-7-l/p100358081

**Comment by make-all** [comment]
Sorry, the Information about DPS mappings does not seem to match up with the Log data.  Can you look again in the iot.tuya.com API explorer for the "Get Device Specification Attribute" function under "Smart Home Device System" / "Device Control" that contains dp_id mappings.
Log has Boolean, Integer, Integer, Enum, Enum, Boolean, Integer
Info has one fewer: Boolean, Integer, Integer, Boolean, _Integer, Integer

Probably the first three match up, but beyond that is a bit confused.

**Comment by spitfire** [comment]
Looks about the same.

```
{
  "result": {
    "category": "bh",
    "functions": [
      {
        "code": "start",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "dp_id": 8,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":40,\"max\":100,\"scale\":0,\"step\":5}"
      },
      {
        "code": "warm",
        "dp_id": 13,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "warm_time",
        "dp_id": 14,
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":120,\"scale\":0,\"step\":30}"
      }
    ],
    "status": [
      {
        "code": "start",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_current",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_set",
        "dp_id": 8,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":40,\"max\":100,\"scale\":0,\"step\":5}"
      },
      {
        "code": "warm",
        "dp_id": 13,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "warm_time",
        "dp_id": 14,
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":120,\"scale\":0,\"step\":30}"
      },
      {
        "code": "countdown_left",
        "dp_id": 18,
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":120,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1678454239541,
  "tid": "e2a1112abf4511edafb1d6e7dc4fd226"
}
```

```
Device matches mirabella_genio_usb with quality of 29%. DPS: {"updated_at": 1678454427.0493417, "1": false, "2": 35, "8": 100, "15": "0", "16": "5", "103": false, "104": 5}
Report this to https://github.com/make-all/tuya-local/issues/
```

**Comment by spitfire** [comment]
The device is not getting identified correctly:

```
Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:46
Integration: Tuya Local ([documentation](https://github.com/make-all/tuya-local), [issues](https://github.com/make-all/tuya-local/issues))
First occurred: 01:03:24 (2 occurrences)
Last logged: 01:03:24

Device matches mirabella_genio_usb with quality of 29%. DPS: {"updated_at": 1679184202.0086718, "1": false, "2": 23, "8": 98, "15": "0", "16": "2", "103": false, "104": 5}
Report this to https://github.com/make-all/tuya-local/issues/
```

it is being matched to


```
mirabella_genio_usb

simple_lightbulb

simple_switch
```

**Comment by make-all** [comment]
It was the warm_time setting from above.  It is not appearing in the logs, so needs to be optional.

**Comment by spitfire** [comment]
Seems to be working now. Any chance for regular switches to turn the boiling on (aside from what it is now)?

**Comment by make-all** [comment]
The water_heater platform does support turn_on and turn_off services, so you should be able to attach an input helper to it to make those service calls, or even just call the turn_on service call directly from a button in the UI.

**Comment by spitfire** [comment]
When I try to use the "Boil" work mode it just beeps a few times and nothing happens. Doing it from Smart Life app works fine.

**Comment by make-all** [comment]
I am not sure, but this might be due to the default on mode of Boil preventing the explicit Boil from being set properly.  I fixed this in the config by removing the default (which will only be needed if the dp "13" is not reported when dp "1" is on, and even then "Boil" was just a guess for that imaginary scenario).

If that does not fix it, try setting to warm first, then boil after that.

**Comment by spitfire** [comment]
Running the Keep_Warm work mode alone lets the water boil, maybe the modes are switched?

**Comment by make-all** [comment]
Yes, probably that is it.  It was just a boolean called "warm", so I assumed that true was "keep warm".  Maybe it is inverted.

**Comment by spitfire** [comment]
It makes sense, cause I was trying to issue that command with 100 degrees, and kettle definitely doesn't support keeping water boiling :) Can you invert them?

**Comment by capitar06** [comment]
Hi,

Since a restart of the device I'm having the same issue. When tryting to start heating water, the LED turns on, but heating doesnt start. When I stop the process the LEDs turn of and I hear 3 beeps, letting me know the process has stopped. When heating water from Smart life, it starts no problem and I can stop it from Home assistant, I also see the water temp rise.

What was the fix for this issue? I've added the device via Tuya cloud and Local Tuya, but both platforms creates this issue.
Thanks in advance! :)

**Comment by capitar06** [comment]
> It was fixed in the pre-defined config for all the problems encountered so far. You aren't actually specific about which "same issue" you are facing, and without log info there isn't a lot that can be done.

Thanks for the quick response! I was checking for logging but couldn't really find it. Also in config/custom_components/localtuya/ I don't see the /devices folder. Could you let me know on how I can collect the appropriate logging for you?
Thanks!

**Comment by make-all** [comment]
This is not the localtuya integration.

**Comment by capitar06** [comment]
> This is not the localtuya integration.

Ok. I have this issue on Tuya local and Tuya Cloud. Would you like me to create a separate issue for this case? 
Please also let me know what kind of logging you need of the device. For testing purposes I have the devices connected to home assistant with Local Tuya and Cloud Tuya.

**Comment by make-all** [comment]
I think it is best if you create a new issue, as it is still not clear to me what your issue is, and this task is already closed, so not tracked beyond the notifications that a new comment was posted.
