### ISSUE TITLE
Please add this video intercom

### ISSUE THREAD

**Issue by ChapayTv** [make-all/tuya-local#519]
Please add this video intercom, if possible, it would be nice to see the object "pressing a button on the call panel" and "motion detector". in the cloud tuya there is no such possibility.

{
"result": {
"category": "sp",
"functions": [
{
"code": "basic_indicator",
"dp_id": 101,
"type": "Boolean",
"values": "{}"
},
{
"code": "basic_flip",
"dp_id": 103,
"type": "Boolean",
"values": "{}"
},
{
"code": "basic_osd",
"dp_id": 104,
"type": "Boolean",
"values": "{}"
},
{
"code": "motion_sensitivity",
"dp_id": 106,
"type": "Enum",
"values": "{"range":["0","1","2"]}"
},
{
"code": "basic_nightvision",
"dp_id": 108,
"type": "Enum",
"values": "{"range":["0","1","2"]}"
},
{
"code": "sd_format",
"dp_id": 111,
"type": "Boolean",
"values": "{}"
},
{
"code": "record_switch",
"dp_id": 150,
"type": "Boolean",
"values": "{}"
},
{
"code": "record_mode",
"dp_id": 151,
"type": "Enum",
"values": "{"range":["1","2"]}"
},
{
"code": "device_restart",
"dp_id": 162,
"type": "Boolean",
"values": "{}"
}
],
"status": [
{
"code": "basic_indicator",
"dp_id": 101,
"type": "Boolean",
"values": "{}"
},
{
"code": "basic_flip",
"dp_id": 103,
"type": "Boolean",
"values": "{}"
},
{
"code": "basic_osd",
"dp_id": 104,
"type": "Boolean",
"values": "{}"
},
{
"code": "motion_sensitivity",
"dp_id": 106,
"type": "Enum",
"values": "{"range":["0","1","2"]}"
},
{
"code": "basic_nightvision",
"dp_id": 108,
"type": "Enum",
"values": "{"range":["0","1","2"]}"
},
{
"code": "sd_storge",
"dp_id": 109,
"type": "String",
"values": "{"maxlen":255}"
},
{
"code": "sd_status",
"dp_id": 110,
"type": "Integer",
"values": "{"unit":"","min":1,"max":5,"scale":1,"step":1}"
},
{
"code": "sd_format",
"dp_id": 111,
"type": "Boolean",
"values": "{}"
},
{
"code": "movement_detect_pic",
"dp_id": 115,
"type": "Raw",
"values": "{}"
},
{
"code": "sd_format_state",
"dp_id": 117,
"type": "Integer",
"values": "{"unit":"","min":-20000,"max":20000,"scale":1,"step":1}"
},
{
"code": "doorbell_active",
"dp_id": 136,
"type": "String",
"values": "{"maxlen":255}"
},
{
"code": "record_switch",
"dp_id": 150,
"type": "Boolean",
"values": "{}"
},
{
"code": "record_mode",
"dp_id": 151,
"type": "Enum",
"values": "{"range":["1","2"]}"
},
{
"code": "doorbell_pic",
"dp_id": 154,
"type": "Raw",
"values": "{}"
},
{
"code": "device_restart",
"dp_id": 162,
"type": "Boolean",
"values": "{}"
}
]
},
"success": true,
"t": 1678434872883,
"tid": "cb393012bf1811eda9e9d694da825c81"
}

"product_id": "h3bhzu9m0ig80rdu",
"name": "SmartDoorBell-IPBox",

**Comment by make-all** [comment]
This appears to be the same device as #371
But without a log, I am unable to tell why it is not being detected.

**Comment by ChapayTv** [comment]
I'll post the log a little later

**Comment by make-all** [comment]
Closing due to no feedback for a month
