### ISSUE TITLE
Multiple switch device

### ISSUE THREAD

**Issue by darek-margas** [make-all/tuya-local#52]
Hi,
I spent most of Sunday trying to make double outlet working and found there is no way to add anything what has multiple entity of the same type. So, if there is 4 button light switch or two button (in fact 3 with virtual master) outlet it won't work at all.

**Comment by make-all** [comment]
This is a known limitation, which I intend to fix in future.  I think such devices should be easy to configure in  the [localtuya](https://github.com/rospogrigio/localtuya/) integration (similarly named but with different origins and approach).

**Comment by darek-margas** [comment]
Once this is in release, I'll make a few more configs for multiswitches.

**Comment by ThomasADavis** [comment]
I also have this one, which is 4 switches, called 'Geeni EXTEND Multi-Port Wall Tap WW119'

```
switch_1	Boolean	 "{true,false}"
switch_2	Boolean	 "{true,false}"
switch_3	Boolean	 "{true,false}"
switch_4	Boolean	 "{true,false}"
countdown_1	Integer	
  {
    "unit": "s",
    "min": 0,
    "max": 86400,
    "scale": 0,
    "step": 1
  }
countdown_2	Integer	
  {
    "unit": "s",
    "min": 0,
    "max": 86400,
    "scale": 0,
    "step": 1
  }
countdown_3	Integer	
  {
    "unit": "s",
    "min": 0,
    "max": 86400,
    "scale": 0,
    "step": 1
}
countdown_4	Integer	
{
    "unit": "s",
    "min": 0,
    "max": 86400,
    "scale": 0,
    "step": 1
}
```

**Comment by darek-margas** [comment]
I tried to make it work by adding to translations the below in two sections. Seems similar to others, say a child lock:
                    "switch_wall_switch_1": "Include Wall switch 1 as a switch entity",
                    "switch_wall_switch_2": "Include Wall switch 2 as a switch entity",

However, it does not show anyway. Anywhere else missing?

**Comment by make-all** [comment]
Sometimes you need to force a refresh of the front end with a Shift-Refresh immediately after changes like this.

**Comment by make-all** [comment]
Take a look at the 3 most recent commits I made.  I renamed the outlets to "Outlet 1" and "Outlet 2" for both Grid Connect double outlets, so the number of translations doesn't grow unnecessarily.  So probably we're headed for another merge/rebase conflict again.

I think the GitHub UI is too basic to handle this nicely. I always use TortoiseGit or the command line for merging and rebasing.  I think the "use theirs" and "use ours" options during merge are better to use than adding extra commits deleting and recreating the conflicting files.

I'm a bit surprised that changes before your most recent merge caused conflicts when rebasing, I would have expected the merge point to set a common start point, so my knowlegde of git is also not perfect...  At some point when things have gotten too far out of step, it might be best to rename your branch to main_old, and start over with a fresh main branch based on upstream.

**Comment by darek-margas** [comment]
I think for outlets "left" and right" is a lot more descriptive as it instantly shows what is connected to which.

**Comment by make-all** [comment]
Entities can be renamed in the UI. I am more concerned with the maintenance of the translations, as different switches are going to be left/right or top/bottom, or for more than two they are going to end up numbered anyway.  Fewer distinct strings to maintain is easier, especially if users start contributing translations for other languages.
