### ISSUE TITLE
Klarta Humea humidifier beeping periodically

### ISSUE THREAD

**Issue by AdamB2023** [make-all/tuya-local#520]
Please add support for Klarta Humea humidifier.

# Log Message
```
Device matches abalon_bcm700d_curtain with quality of 30%. DPS: {"updated_at": 1678471840.9699385, "10": true, "101": "1", "102": "cancel", "103": false, "104": false, "105": "0", "106": "2", "107": "0", "108": "0", "109": 47}
```

# Information about DPS mappings
```
{
  "result": {
    "category": "jsq",
    "functions": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "sleep",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "level",
        "type": "Enum",
        "values": "{\"range\":[\"level_1\",\"level_2\",\"level_3\",\"level_4\",\"level_5\",\"level_6\",\"level_7\",\"level_8\",\"level_9\"]}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "sleep",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "humidity_current",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "level",
        "type": "Enum",
        "values": "{\"range\":[\"level_1\",\"level_2\",\"level_3\",\"level_4\",\"level_5\",\"level_6\",\"level_7\",\"level_8\",\"level_9\"]}"
      }
    ]
  },
  "success": true,
  "t": 1678472564190,
  "tid": "8cff5f56bf7011edafb1d6e7dc4fd226"
}
```

# Product ID
 ```
"product_id": "i8cej9chgwebzrmp"
```

# Information about how the device functions
https://klarta.pl/pdf/INSTRUKCJA_KLARTA_HUMEA_WIFI.pdf

10 Power
101 Water Level
102 Night Light
103 Sleep Mode
104 Auto Mode
105 Humidity Setting
106 Moisture output level
107 Filter
108 Countdown Timer
109 Current Humidity

**Comment by make-all** [comment]
2.  It looks like number entities default to 0-100 if no range is given.  Is it 1-4, or 1-9 as documented in your original request? 
```
  {
      "code": "level",
      "type": "Enum",
      "values": "{\"range\":[\"level_1\",\"level_2\",\"level_3\",\"level_4\",\"level_5\",\"level_6\",\"level_7\",\"level_8\",\"level_9\"]}"
  }
```

**Comment by make-all** [comment]
1. was fixed yesterday (only numeric values are valid for humidity, so I used 35)
2. fixed now
3. I need more details on this - what are "signals", something you are seeing in a log somewhere?

**Comment by make-all** [comment]
It seems the device may be rebooting for some reason.  Can you add the following to config/configuration.yaml so we can see the debug log of the last message that was sent before the reboot.

```yaml
logger:
    default: warning
    logs:
      custom_components.tuya_local.device: debug
```

**Comment by make-all** [comment]
The snippet above only increases the log level in the existing Home Assistant log, it does not create additional log files.

The Home Assistant log can be accessed through Settings/System/Logs.

**Comment by make-all** [comment]
Sorry, unless you can find the protocol level debug log messages, not much more can be done here.

**Comment by make-all** [comment]
As I wrote above, the Home Asssistant logs can be accessed at Settings/System/Logs in the HA interface.  At the bottom there should be a button to load the full logs.

**Comment by make-all** [comment]
Please confirm if the new tinytuya library version in 2023.5.1 fixes the issue.

**Comment by make-all** [comment]
This log looks like it was taken with the previous version, as the protocol version is being rotated immediately after the 3 failures.

Does the "Yes" at the start of your message indicate that the problem was fixed after trying the new version?

**Comment by make-all** [comment]
Is this issue still current on the latest version of the tuya-local integration?
The comment above seems to be about HA versions, not tuya-local versions.

Also, are you using HACS, or installing manually?  If installing manually, you will need to make sure tinytuya is also updated.

**Comment by make-all** [comment]
Auto should be available as a mode in the humidifier entity.
