### ISSUE TITLE
 New Device Request: for Smart Curtain Switch with OPEN/STOP/CLOSE BUTTONS (unbranded) 

### ISSUE THREAD

**Issue by theshop35** [make-all/tuya-local#523]
# Log Message

```
This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:45
Integration: Tuya Local (documentation, issues)
First occurred: 1:06:16 PM (2 occurrences)
Last logged: 1:06:16 PM

Device matches None with quality of 0%. DPS: {"updated_at": 1678520174.3120847, "2": "2", "101": "03"}
Report this to https://github.com/make-all/tuya-local/issues/
```

# Information about DPS mappings

```
Device Specification Attribute
{
  "result": {
    "category": "cl",
    "functions": [
      {
        "code": "control",
        "dp_id": 101,
        "type": "Enum",
        "values": "{\"range\":[\"open\",\"stop\",\"close\",\"continue\"]}"
      }
    ],
    "status": [
      {
        "code": "control",
        "dp_id": 101,
        "type": "Enum",
        "values": "{\"range\":[\"open\",\"stop\",\"close\",\"continue\"]}"
      }
    ]
  },
  "success": true,
  "t": 1678531610145,
  "tid": "072585e7bffa11edbcdaea52450d735d"
}```

<!--
DP ID : STATUS (OPEN,STOP,CLOSE) -CODE :2
DP ID : POWER(OPEN,STOP,CLOSE)  -CODE :101

Code | Type | Values

control | Enum | {   "range": [     "open",     "stop",     "close",     "continue"   ]


![Curtain Switch Panel](https://user-images.githubusercontent.com/79641326/224484235-9940cda6-c8e2-4e7a-a4b5-a25220417111.jpg)

# Product ID

<!--
"category": "cl",
    "category_name": "Curtain",
    "id": "0088250084f3ebecee37",
    "model": "CcSmartCurtain1",
    "name": "Smart Curtain",
    "product_id": "dy1jPRPGVR9G7PWY",
    "product_name": "Smart Curtain1",
    "sub": false,
    "uuid": "0088250084f3ebecee37"
-->


# Information about how the device functions
<!-- Its a three button WIFI Switch with OPEN/STOP/CLOSE BUTTONS
-->

**Comment by make-all** [comment]
Both these dp seem to be using cryptic codes instead of the obvious "open", "close", "stop" strings.  To add support, it will need some more investigation to figure out what each value corresponds to.

**Comment by theshop35** [comment]
> Both these dp seem to be using cryptic codes instead of the obvious "open", "close", "stop" strings. To add support, it will need some more investigation to figure out what each value corresponds to.


any addition info required from my side?

**Comment by make-all** [comment]
Yes, what the actual values used for OPEN, STOP and CLOSE actually are.  In the logs, there are "2" for status and "03" for control, but it isn't clear what those mean.

Probably it is easier to start with a config that surfaces these as sensors, and observe while playing around from the control panel or with the Tuya app via a mobile connection with WiFi switched off (as opening the Tuya app with WiFi on may prevent other local connections from working).

save to custom_components/tuya_local/devices/test.yaml:
```
name: Information gathering
primary_entity:
  entity: sensor
  name: status
  dps:
    - id: 2
      type: string
      name: sensor
secondary_entities:
  - entity: sensor
    name: control
    dps:
      - id: 101
        type: string
        name: sensor
```

**Comment by theshop35** [comment]
> Yes, what the actual values used for OPEN, STOP and CLOSE actually are. In the logs, there are "2" for status and "03" for control, but it isn't clear what those mean.
> 
> Probably it is easier to start with a config that surfaces these as sensors, and observe while playing around from the control panel or with the Tuya app via a mobile connection with WiFi switched off (as opening the Tuya app with WiFi on may prevent other local connections from working).
> 
> save to custom_components/tuya_local/devices/test.yaml:
> 
> ```
> name: Information gathering
> primary_entity:
>   entity: sensor
>   name: status
>   dps:
>     - id: 2
>       type: string
>       name: sensor
> secondary_entities:
>   - entity: sensor
>     name: control
>     dps:
>       - id: 101
>         type: string
>         name: sensor
> ```

This is what i found by pressing on TUYA app.

Attributes:
OPEN- RAW state :02
STOP- RAW state :01
CLOSE- RAW STATE :03


![Uploading Screenshot_20230319-122317_Smart Life.png…
![Screenshot_20230319-122322_Smart Life](https://user-images.githubusercontent.com/79641326/226159217-e3dafe41-d1e8-4c21-94b9-3c9ffa24215a.png)
![Screenshot_20230319-122327_Smart Life](https://user-images.githubusercontent.com/79641326/226159218-58466ed9-cd3d-43a1-947b-cb4b4687269d.png)
]()

thankyou for your time

**Comment by theshop35** [comment]
hi today i changed instruction set  the from standard to DP instructions on Tuya IOT platform site

results 
Get Device Specification Attribute

{
  "result": {
    "category": "cl",
    "functions": [
      {
        "code": "Power",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "dp_id": 101,
        "type": "Enum",
        "values": "{\"range\":[\"01\",\"02\",\"03\"]}"
      }
    ],
    "status": [
      {
        "code": "Power",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "status",
        "dp_id": 2,
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\"]}"
      },
      {
        "code": "mode",
        "dp_id": 101,
        "type": "Enum",
        "values": "{\"range\":[\"01\",\"02\",\"03\"]}"
      }
    ]
  },
  "success": true,
  "t": 1679309003474,
  "tid": "09a97e84c70c11eda717d63f1fabdb28"
}




Get the specifications and properties of the device:

{
  "result": {
    "category": "cl",
    "functions": [
      {
        "code": "Power",
        "desc": "{}",
        "name": "开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "desc": "{\"range\":[\"01\",\"02\",\"03\"]}",
        "name": "开关",
        "type": "Enum",
        "values": "{\"range\":[\"01\",\"02\",\"03\"]}"
      }
    ],
    "status": [
      {
        "code": "Power",
        "name": "开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "status",
        "name": "窗帘",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\"]}"
      },
      {
        "code": "mode",
        "name": "开关",
        "type": "Enum",
        "values": "{\"range\":[\"01\",\"02\",\"03\"]}"
      }
    ]
  },
  "success": true,
  "t": 1679309120751,
  "tid": "4f96127dc70c11eda717d63f1fabdb28"
}
