### ISSUE TITLE
Request support for Double switch

### ISSUE THREAD

**Issue by alexreddy78** [make-all/tuya-local#524]
Dear Developer,

Kindly ask you to add below mentioned device to integration, in possible

This form is for reporting a new device.
-->

# Log Message

N/A
Please paste logs here
N/A

# Information about DPS mappings

{
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "switch_1",
        "desc": "{}",
        "name": "开关1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_2",
        "desc": "{}",
        "name": "开关2",
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "name": "开关1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_2",
        "name": "开关2",
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1678541657378,
  "tid": "6bc050a9c01111edafb1d6e7dc4fd226"

Refards 

Alex
-->

**Comment by make-all** [comment]
No information about local protocol provided.
