### ISSUE TITLE
Request support for Sirena/Alarm

### ISSUE THREAD

**Issue by alexreddy78** [make-all/tuya-local#525]
Dear Developer,

Kindly ask you to add below mentioned device to integration, in possible

This form is for reporting a new device.
-->

# Log Message

N/A
Please paste logs here
N/A

# Information about DPS mappings

"result": {
    "category": "sgbj",
    "functions": [
      {
        "code": "Alarmtype",
        "desc": "{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\"]}",
        "name": "声音类型",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\"]}"
      },
      {
        "code": "AlarmPeriod",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":60,\"scale\":0,\"step\":1}",
        "name": "报警时长",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":60,\"scale\":0,\"step\":1}"
      },
      {
        "code": "AlarmSwitch",
        "desc": "{}",
        "name": "报警开关",
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "Alarmtype",
        "name": "声音类型",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\"]}"
      },
      {
        "code": "BatteryStatus",
        "name": "电量状态",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\"]}"
      },
      {
        "code": "AlarmSwitch",
        "name": "报警开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "AlarmPeriod",
        "name": "报警时长",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":60,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1678542430524,
  "tid": "389ae335c01311edafb1d6e7dc4fd226"

Refards 

Alex
-->

**Comment by make-all** [comment]
No information about local protocol provided.
