### ISSUE TITLE
Better `/devices` folder structuring

### ISSUE THREAD

**Issue by yarosman** [make-all/tuya-local#530]
It would be great to split `/devices` folders to subfolders which depends on device category.  
It will allow users to find similar products easily for supporting new device

**Comment by make-all** [comment]
It adds extra complexity to loading of configs, and the benefit is not much I think

**Comment by yarosman** [comment]
"bug" was added automatically

**Comment by yarosman** [comment]
> It adds extra complexity to loading of configs, and the benefit is not much I think.
> 
> Certainly this is not a bug.

in the future you will get folder with hundred of files and it will be very hard to find what you want
