### ISSUE TITLE
Request support for [Proscenic A8]

### ISSUE THREAD

**Issue by kajapa** [make-all/tuya-local#533]
Hi! 
I would like to ask for adding support to air purifier Proscenic A8. I even tried adding configuration of that device but sadly config did not appear in set up process. You can find my config in txt file below. Thank you in advance!
[proscenic_a8.txt](https://github.com/make-all/tuya-local/files/10951515/proscenic_a8.txt)

# Information about DPS mappings

```
{
  "result": {
    "product_id": "jiiagi6aamtgbffk",
    "product_name": "A8",
    "status": [
      {
        "code": "switch",
        "value": false
      },
      {
        "code": "pm25",
        "value": 0
      },
      {
        "code": "fan_speed_enum",
        "value": "mid"
      },
      {
        "code": "filter",
        "value": 99
      },
      {
        "code": "lock",
        "value": false
      },
      {
        "code": "light",
        "value": true
      },
      {
        "code": "filter_reset",
        "value": false
      },
      {
        "code": "filter_days",
        "value": 1999
      },
      {
        "code": "total_time",
        "value": 21
      },
      {
        "code": "total_pm",
        "value": 0
      },
      {
        "code": "air_quality",
        "value": "great"
      },
      {
        "code": "fault",
        "value": 0
      }
    ],
    "sub": false,
    "time_zone": "+01:00",
    "uid": "eu1627645011200BWh0n",
    "update_time": 1678635404,
    "uuid": "1615185624a160286666"
  },
  "success": true,
  "t": 1678640288330,
  "tid": "106189f5c0f711ed904372ab8eab5dd5"
}
```

# Product ID

```
"product_id": "jiiagi6aamtgbffk",
"product_name": "A8"
```

# Information about how the device functions

This is link to aforementioned airpurifier:
https://www.gshopper.com/pl/product/detail/3000015659

**Comment by make-all** [comment]
No local protocol information in the report, I cannot do anything with this.

**Comment by kajapa** [comment]
@make-all Log Message has been added. Please let me know if I can add any more informations.

**Comment by kajapa** [comment]
@make-all Could you explain what should I do to make my yaml file appear in set up process of device?
