### ISSUE TITLE
Request support for Selecting template manually (override)

### ISSUE THREAD

**Issue by thewolf-oz** [make-all/tuya-local#534]
I've noticed there are a number of templates mentioned that look to match the products I'm trying to setup, however the wrong template is suggested to me. It would be great to be able to have an option to override the presented options and force a particular template

In some cases, the presented options may work (mostly), however it looks like there are existing devices that should just work

In this example, I'd have thought this would align to arlec_fan.yaml however it only gives me a simple switch as an option
![image](https://user-images.githubusercontent.com/86336633/224651891-f03319b6-f831-4a2a-a789-cbdaef302af5.png)
![image](https://user-images.githubusercontent.com/86336633/224651998-4c4ce26c-3d21-4a2c-98e0-b1fdb8e9f5a6.png)

I have a few more examples, such as a simple smart globe that only has diming detecting as RGB or colour selectable, and no option to select simple_lightbulb.yaml

**Comment by make-all** [comment]
No, it wouldn't be great. It would be confusing, as the configs that are not offered are definitely not compatible with your device.
