### ISSUE TITLE
Request support for Arlec 75cm Grid Connect 19 Speed Smart Industrial Pedestal Fan

### ISSUE THREAD

**Issue by thewolf-oz** [make-all/tuya-local#543]
# Log Message

```
Please paste logs here
```

# Information about DPS mappings

```
{
  "result": {
    "category": "fs",
    "functions": [
      {
        "code": "switch",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_speed_percent",
        "lang_config": {
          "unit": "Level"
        },
        "name": "Speed",
        "type": "Integer",
        "values": "{\"min\":1,\"max\":19,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_horizontal",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Swing",
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_speed_percent",
        "lang_config": {
          "unit": "Level"
        },
        "name": "Speed",
        "type": "Integer",
        "values": "{\"min\":1,\"max\":19,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_horizontal",
        "lang_config": {
          "false": "OFF",
          "true": "ON"
        },
        "name": "Swing",
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1678964638675,
  "tid": "402c094cc3ea11eda717d63f1fabdb28"
}
```

# Product ID

0waab4clioc3qaks

# Information about how the device functions

19 speed industrial fan with oscillate/swing control. On/Off and natural/sleep/normal options (for varying speed, quiet or normal operation) and countdown timer
Original link no longer available... this is the closest I could find: (mine is on a stand and is not wall mount like this, but the fan unit is the same)
https://i.ebayimg.com/00/s/MTYwMFgxNjAw/z/VtMAAOSw4q1gIjfR/$_58.JPG
https://files.ozbargain.com.au/upload/174968/86494/img_20210126_142443.jpg

This is the replacement product... it has a similar description but only has 6 speeds: https://www.bunnings.com.au/arlec-75cm-grid-connect-smart-industrial-pedestal-fan_p0274518

**Comment by make-all** [comment]
While a good amount of info is available, none of it includes  the dp ids for the local protocol.  At least a log message, and/or the specific API explorer data mentioned in the README is required.

**Comment by thewolf-oz** [comment]
Sorry, having some issues with this device and missed it when submitting a few for support. I get a blank box and no logs when adding this device

Following another guide with explicit instructions on gathering the DPs: (https://github.com/dulfer/localtuya-device-datapoints)
1 - Switch
2 - Mode
3 - Speed
5 - Swing (Oscillate)
22 - Timer Stop
24 - Fault Alarm

**Comment by make-all** [comment]
Without the log, I cannot see what type of timer the device is using, but if it is a "cancel", "1h",... enum type rather than 0, 60, ... numeric type, then this device should work with the Stirling FS140DC fan config, with just the fault alarm not configured in there (this could be added as an optional attribute if it indeed matches).

But if you cannot get the connection in the first place, it is possible that this device is using Tuya's commercial platform, which may differ from the domestic one at the local protocol level.

**Comment by thewolf-oz** [comment]
I'll try the Stirling fan, though it doesn't go as high for speed (15, rather than 19, not that I have it full speed often)... I just checked the logs in Tuya IOT and it doesn't appear to record the "h". Cancelling sets it back to 0

One of the annoying things with this fan is it requires the remote to put it into pairing mode... one of the reasons it's my only IOT device not on my new IOT network as the fan isn't responding to the remote. I'm not 100% sure if this is why it is not connecting even when specifying the IP

As far as the commercial platform are concerned, the fan is sold through Bunnings (who own the "Grid Connect" brand), they are one of the largest hardware chains in Australia (like Home Depot/Canadian Tire") the Smart Life/Tuya app and native integration work fine with it (I haven't tried Local Tuya as I prefer the idea of this integration and having device profiles rather than setting up each device through the GUI one at a time)

![image](https://user-images.githubusercontent.com/86336633/226083872-5411588d-9da6-4b49-9b0c-aaae0f773920.png)

**Comment by thewolf-oz** [comment]
Also, the hours are in whole numbers only according to the app
![503F0EF0-A6B4-4AFA-926C-420939F5DCD5](https://user-images.githubusercontent.com/86336633/226090662-34b55ebc-5299-4324-857d-21293c5b2a5e.png)

**Comment by make-all** [comment]
Based on those reports, it looks like the timer is numeric, so would not be a match anyway, and like you say, the number of speeds is different so it will need a new config.

**Comment by thewolf-oz** [comment]
Thanks for working on this and the other requests... I need to sort my wifi issue out before I can fully test this one
