### ISSUE TITLE
Request support for Motion Sensor -T -W8

### ISSUE THREAD

**Issue by souza252** [make-all/tuya-local#545]
Generic motion sensor: https://www.amazon.com/dp/B08T6ZSST1
AKA: NEO Coolcam Smart PIR Motion With Temperature Humidity Sensor Wifi USB Charge

Unable to retrieve logs. Tried the dump script and got not reply.

INFO:localtuya:localtuya version 1.0.0
INFO:localtuya:Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
INFO:localtuya:Using pytuya version '10.0.0'
INFO:localtuya:TIMEOUT: No response from device after 2 attempts.

Pings are inconsistent, device sleeps a lot to save power.

64 bytes from 192.168.0.220: icmp_seq=523 ttl=255 time=20.3 ms
64 bytes from 192.168.0.220: icmp_seq=524 ttl=255 time=2020 ms
64 bytes from 192.168.0.220: icmp_seq=525 ttl=255 time=1007 ms
64 bytes from 192.168.0.220: icmp_seq=526 ttl=255 time=5.36 ms
64 bytes from 192.168.0.220: icmp_seq=527 ttl=255 time=8011 ms
64 bytes from 192.168.0.220: icmp_seq=528 ttl=255 time=7011 ms
64 bytes from 192.168.0.220: icmp_seq=529 ttl=255 time=5987 ms
64 bytes from 192.168.0.220: icmp_seq=530 ttl=255 time=4964 ms
64 bytes from 192.168.0.220: icmp_seq=535 ttl=255 time=593 ms
64 bytes from 192.168.0.220: icmp_seq=536 ttl=255 time=1872 ms

```
No logs found
```

# Information about DPS mappings

```
{
  "result": {
    "category": "pir",
    "functions": [],
    "status": [
      {
        "code": "pir",
        "dp_id": 1,
        "type": "Enum",
        "values": "{\"range\":[\"pir\",\"none\"]}"
      },
      {
        "code": "battery_percentage",
        "dp_id": 4,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temper_alarm",
        "dp_id": 5,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_current",
        "dp_id": 7,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-100,\"max\":1250,\"scale\":1,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1678995932977,
  "tid": "1d1a406bc43311eda2c5dae7169ea2b8"
}
```

"product_id": "vtdhft75lhnreqk8"

Very simple binary PIR motion sensor, with added temperature and humidity.

**Comment by make-all** [comment]
> device sleeps a lot to save power.

Unfortunately that is a dealbreaker when it comes to local use.
