### ISSUE TITLE
Request support for Chanfok Smart Ceiling fan

### ISSUE THREAD

**Issue by dhuddle** [make-all/tuya-local#546]
# Log Message

```
Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:45
Integration: Tuya Local (documentation, issues)
First occurred: March 16, 2023 at 5:00:25 PM (8 occurrences)
Last logged: 9:24:36 AM

Device matches None with quality of 0%. DPS: {"updated_at": 1679011224.935124, "20": false, "22": 701, "23": 0, "60": false, "61": "fresh", "62": 1, "63": "forward", "66": true, "101": false}
Report this to https://github.com/make-all/tuya-local/issues/
Device matches None with quality of 0%. DPS: {"updated_at": 1679013805.0010648, "20": false, "22": 701, "23": 0, "60": false, "61": "fresh", "62": 1, "63": "forward", "66": true, "101": false}
Device matches simple_dual_switch_timer_v2 with quality of 50%. DPS: {"updated_at": 1679015771.2989616, "1": true, "2": false, "3": false, "9": 0, "10": 0, "11": 0, "38": "memory", "42": ""}
Device matches None with quality of 0%. DPS: {"updated_at": 1679070274.7955856, "20": false, "22": 701, "23": 0, "60": true, "61": "fresh", "62": 1, "63": "forward", "66": true, "101": false}
```
# Information about DPS mappings

```
{
  "result": {
    "category": "fsd",
    "functions": [
      {
        "code": "switch_led",
        "dp_id": 20,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "dp_id": 21,
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"
      },
      {
        "code": "bright_value",
        "dp_id": 22,
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_value",
        "dp_id": 23,
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "control_data",
        "dp_id": 28,
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "fan_switch",
        "dp_id": 60,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_mode",
        "dp_id": 61,
        "type": "Enum",
        "values": "{\"range\":[\"fresh\",\"nature\"]}"
      },
      {
        "code": "fan_speed",
        "dp_id": 62,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":1,\"max\":6,\"scale\":0,\"step\":1}"
      },
      {
        "code": "fan_direction",
        "dp_id": 63,
        "type": "Enum",
        "values": "{\"range\":[\"forward\",\"reverse\"]}"
      },
      {
        "code": "fan_beep",
        "dp_id": 66,
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch_led",
        "dp_id": 20,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "dp_id": 21,
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"
      },
      {
        "code": "bright_value",
        "dp_id": 22,
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_value",
        "dp_id": 23,
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "fan_switch",
        "dp_id": 60,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_mode",
        "dp_id": 61,
        "type": "Enum",
        "values": "{\"range\":[\"fresh\",\"nature\"]}"
      },
      {
        "code": "fan_speed",
        "dp_id": 62,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":1,\"max\":6,\"scale\":0,\"step\":1}"
      },
      {
        "code": "fan_direction",
        "dp_id": 63,
        "type": "Enum",
        "values": "{\"range\":[\"forward\",\"reverse\"]}"
      },
      {
        "code": "fan_beep",
        "dp_id": 66,
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1679069458422,
  "tid": "4da2bd49c4de11edacf08ac5d669b858"
}
```

# Product ID

```
{
  "result": {
    "active_time": 1678771225,
    "category": "fsd",
    "category_name": "Ceiling Fan",
    "create_time": 1678771225,
    "gateway_id": "",
    "icon": "smart/icon/bay1615016736420i3z2/bbbd1445b5868093fce11ffb168e9b1d.png",
    "id": "bf4db9a34dbf40f520znek",
    "ip": 
    "lat": 
    "local_key": 
    "lon": 
    "model": "",
    "name": "smart fan",
    "online": true,
    "owner_id": 
    "product_id": "tvtzgei8bgaezsvi",
    "product_name": "smart fan",
    "sub": false,
    "time_zone": "-07:00",
    "update_time": 1678928297,
    "uuid": "01d4d83f2be93ff9"
  },
  "success": true,
  "t": 1679069997565,
  "tid": "8f10e06cc4df11edacf08ac5d669b858"
}
```

# Information about how the device functions

This is a request for integration of the Chanfok Smart fan ([Amazon](https://www.amazon.com/gp/product/B0BF8VXNQY/)). It has what looks to be a generic smart fan controller. This fan contains a LED light (non-RGB) and a 6 speed, 2 direction fan w/ timer function.

**Comment by dhuddle** [comment]
In the "devices" tab in my project, it shows this product as "JST-DC-WYfen"

**Comment by dhuddle** [comment]
Great news!
![image](https://user-images.githubusercontent.com/73569754/226195270-4835f292-9941-4756-8f5b-167486a32004.png)
and:
![image](https://user-images.githubusercontent.com/73569754/226195352-e3a5173c-125f-44d9-a670-6b768adb365d.png)

![image](https://user-images.githubusercontent.com/73569754/226195421-2ca870ca-3f20-43a3-852d-a5984adbb930.png)

**Great** work! Thank you so much! I'm able to turn on, off light, the fan, change fan direction, change color temp (it is non RGB, so just cool to warm white), and turn on/off the beep! there's one attribute as "unknown" (101) under "fan" but I don't know what that could be (timer? but that is not a requirement for me.

This seems to pass all my tests!

Thanks again! there are a ton of similar fan on Amazon - the only difference I can see (same fan controller) is that some have RGB lighting. This hopefully will be generic enough to get most of them online!

**Comment by make-all** [comment]
The unknown 101 was a Boolean, so I don't think it is the timer. A bit of a mystery to me, as there was no mention of any other feature on the webpage except timer, but that would require an integer or enum type

**Comment by dhuddle** [comment]
![image](https://user-images.githubusercontent.com/73569754/226222609-a1874681-92e1-4b93-8a57-81aac9e1f3a0.png)

Actually - one issue I just noticed. The color temperature control in home assistant seems to be inverted. (6500k is actually 2000k etc.) For example, when I have it selected as per the image, the light changes to cool white.

**Comment by make-all** [comment]
Actually, that seems to be standard for Tuya, the generic rgbcw_lightbulb also is inverted - I think because HA used to follow Phillips Hue convention and use mireds (they now allow either mireds or K, but this integrations implementation predates that, so we use mireds while Tuya seem to use a scale where 0 = 2000K and 1000 = 6500K).

**Comment by Blackduke77** [comment]
Hi Does this enable the fan to be detected or do I need to do some mapping etc. I just purchased this device but a firned who uses this integration informed me that this integration does not detect the fan etc and he has completed some manual mappings.

**Comment by make-all** [comment]
If you have the same fan, it should be detected. But different models will have different dps. Also the device can report different subsets of dps in different states such as light on/off, fan on/off, and since there has only been one user so far reporting this device, we may not have captured all the possibilities.

**Comment by Blackduke77** [comment]
Thanks, what do you need from us to get this fan added. We have manually specified the values and seems to work

**Comment by make-all** [comment]
Sorry, I do not understand what you mean by "We have manually specified the values".   If it is working after you enter the connection details, then it is obviously already supported. There are no other values to specify, unless you are in fact using  localtuya, which does have a manual dps mapping step as far as I understand.

**Comment by vincedarley** [comment]
I've just installed and connected a Chanfok fan, tested/configured it in the Tuya Smart app, and have now moved on to home assistant.  It is discovered just fine by tuya-local, but then not correctly recognised (the list of device-types I am offered is really just LED lights, not fans).

```
2025-06-26 14:10:44.733 WARNING (MainThread) [custom_components.tuya_local.config_flow] Adding Chanfok Ceiling Fan device with product id yos17rcreaqlpi5i
2025-06-26 14:10:44.795 WARNING (MainThread) [custom_components.tuya_local.config_flow] Cloud device spec:
[{"id": 20, "name": "switch_led", "type": "Boolean", "format": "{}", "enumMap": {}}, {"id": 21, "name": "work_mode", "type": "Enum", "format": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}", "enumMap": {}}, {"id": 22, "name": "bright_value", "type": "Integer", "format": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}", "enumMap": {}}, {"id": 23, "name": "temp_value", "type": "Integer", "format": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}", "enumMap": {}}, {"id": 53, "name": "switch_night_light", "type": "Boolean", "format": "{}", "enumMap": {}}]
2025-06-26 14:10:44.795 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches marpou_ceiling_lamp_ledlight with quality of 40%. DPS: {"updated_at": 1750943442.8344378, "20": true, "21": "white", "22": 495, "23": 1000, "53": false, "101": false, "104": "forward", "105": 1, "106": "fresh", "107": false}
2025-06-26 14:10:44.795 WARNING (MainThread) [custom_components.tuya_local.config_flow] Include the previous log messages with any new device request to https://github.com/make-all/tuya-local/issues/

```

Above are the relevant log lines.  Weirdly I don't see anything in the above lines about the fan control (the Tuya app shows controls both for the fan and the light).  Any suggestion how to proceed?
