### ISSUE TITLE
Request support for Kogan SmarterHome bidet

### ISSUE THREAD

**Issue by kytro** [make-all/tuya-local#559]
# Log Message

```
Device matches None with quality of 0%. DPS: {"updated_at": 1679344727.3146813, "45": true, "50": "dry", "52": "level_3", "55": "pos_3", "60": "level_3", "62": true, "64": false, "65": false}
```

# Information about DPS mappings

```
{
  "result": {
    "category": "mt",
    "functions": [
      {
        "code": "switch",
        "lang_config": {
          "false": "Stop",
          "true": ""
        },
        "name": "Switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "seated",
        "lang_config": {
          "false": "",
          "true": ""
        },
        "name": "Seated",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "lang_config": {
          "child": "",
          "normal": ""
        },
        "name": "Mode",
        "type": "Enum",
        "values": "{\"range\":[\"normal\",\"child\"]}"
      },
      {
        "code": "deodorization",
        "lang_config": {
          "false": "",
          "true": ""
        },
        "name": "Deodorization",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "light",
        "lang_config": {
          "false": "",
          "true": ""
        },
        "name": "Light",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "economize",
        "lang_config": {
          "false": "",
          "true": ""
        },
        "name": "Energy Saving",
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "lang_config": {
          "false": "Stop",
          "true": ""
        },
        "name": "Switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "seated",
        "lang_config": {
          "false": "",
          "true": ""
        },
        "name": "Seated",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "lang_config": {
          "child": "",
          "normal": ""
        },
        "name": "Mode",
        "type": "Enum",
        "values": "{\"range\":[\"normal\",\"child\"]}"
      },
      {
        "code": "deodorization",
        "lang_config": {
          "false": "",
          "true": ""
        },
        "name": "Deodorization",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "light",
        "lang_config": {
          "false": "",
          "true": ""
        },
        "name": "Light",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "economize",
        "lang_config": {
          "false": "",
          "true": ""
        },
        "name": "Energy Saving",
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1679345315790,
  "tid": "956b2d08c76011edbae0c235483784fc"
}
```

Light: 64
Energy Saving: 65
Fault: 68
产品型号: 101
固件版本: 102
环境温度: 103
主机状态: 104
Switch: 45
Seated: 46
Mode: 50
Water Temp: 52
Water Temp: 53
清洗水压: 54
Position: 55
Clean Time: 56
Wind Temp: 57
烘干时间: 59
Seat Warmer: 60
Seat Temp: 61
Deodorization: 62

# Product ID

"product_id": "7cuimqtezvgbaeun"

# Information about how the device functions

https://www.kogan.com/au/buy/kogan-smarterhome-smart-antibacterial-wash-dry-electric-bidet-toilet-seat/

**Comment by kytro** [comment]
Currently, the Seated value is missing. This could be used as a presence sensor. I tried to add it myself, but I couldn't correctly map it as a binary sensor.

**Comment by make-all** [comment]
Seated (dp 46) did not appear in your log message.  Unless it is only sent when true so we need an optional do with default of false?
It also wasn't clear whether it is a binary_sensor for presence as expected, or a switch that controls something, as it was listed under both functions and status in the iot.tuya.com device info.

**Comment by subexx** [comment]
Hi, I have this device. I can see it under the custom_components/devices but when i try to add it to HA it says device is not supported. Any idea how i can fix it?

**Comment by make-all** [comment]
The log message will show why it is not recognised.

**Comment by subexx** [comment]
> The log message will show why it is not recognised.

These are the logs

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:49
Integration: Tuya Local ([documentation](https://github.com/make-all/tuya-local), [issues](https://github.com/make-all/tuya-local/issues))
First occurred: 8:27:38 AM (10 occurrences)
Last logged: 10:22:45 AM

Report this to https://github.com/make-all/tuya-local/issues/
Device matches None with quality of 0%. DPS: {"updated_at": 1690670232.7587736, "45": true, "46": false, "50": "normal", "52": "level_3", "60": "level_3", "62": true, "64": false, "65": false}
Device matches None with quality of 0%. DPS: {"updated_at": 1690670698.0428252, "45": true, "46": false, "50": "normal", "52": "level_3", "60": "level_3", "62": true, "64": false, "65": false}
Device matches None with quality of 0%. DPS: {"updated_at": 1690670839.1567247, "45": true, "50": "dry", "52": "level_3", "54": "level_3", "57": "level_2", "60": "level_3", "62": true, "64": false, "65": false}
Device matches None with quality of 0%. DPS: {"updated_at": 1690676564.448356, "45": true, "50": "dry", "52": "level_3", "54": "level_3", "57": "level_2", "60": "level_3", "62": true, "64": false, "65": false}

Logger: homeassistant.util.async_
Source: util/async_.py:166
First occurred: 8:27:37 AM (5 occurrences)
Last logged: 10:22:42 AM

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 76: self._api = tinytuya.Device(dev_id, address, local_key)

**Comment by subexx** [comment]
Thank you. You are a legend.

**Comment by OkhammahkO** [comment]
I've got a ESPHome project working for this here if anyone's interested....

https://community.home-assistant.io/t/esphome-your-kogan-smart-dunny/656881
