### ISSUE TITLE
Request support for LSC SMART Connect Sirene

### ISSUE THREAD

**Issue by xtronets** [make-all/tuya-local#560]
{
  "result": {
    "category": "sgbj",
    "functions": [
      {
        "code": "alarm_volume",
        "desc": "alarm volume",
        "name": "alarm volume",
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"middle\",\"high\",\"mute\"]}"
      },
      {
        "code": "alarm_time",
        "desc": "alarm time",
        "name": "alarm time",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":1,\"max\":30,\"scale\":0,\"step\":1}"
      },
      {
        "code": "alarm_switch",
        "desc": "alarm switch",
        "name": "alarm switch",
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1679379607464,
  "tid": "6cf0d54ec7b011edbae0c235483784fc"
}

**Comment by make-all** [comment]
Sorry, with no local protocol info, there is nothing that can be done here.
