### ISSUE TITLE
"Ledkia fan and light controller" fan Speed error

### ISSUE THREAD

**Issue by bedtiming** [make-all/tuya-local#561]
Hi, I have problem with Ledkia fan and light controller device.

**Describe the bug**
When I set fan Speed to "1"  (Speed can be set from 1 to 6) the speed does not change and the following error appears:
ValueError: speed (16) must be between 16.666666666666668 and 100.0

Other speeds work as expected.

Can you help me?

**Comment by make-all** [comment]
In latest main, I have allowed the speed to go down to 0, to avoid this floating point rounding error.  I think that Home Assistant will change the 0 into a turn off command, so it might work like that.
