### ISSUE TITLE
Request support for MOES 002 thermostat- showing incorrect temperature

### ISSUE THREAD

**Issue by jone9618** [make-all/tuya-local#569]
# Log Message

```
From diagnostic:

  "integration_manifest": {
    "domain": "tuya_local",
    "name": "Tuya Local",
    "codeowners": [
      "@make-all"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/make-all/tuya-local",
    "integration_type": "device",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/make-all/tuya-local/issues",
    "requirements": [
      "pycryptodome~=3.17",
      "tinytuya==1.12.0"
    ],
    "version": "2022.3.1",
    "is_built_in": false
  },
  "data": {
    "name": "53B thermostat",
    "type": "moes_bht002_thermostat_c",
    "device_id": "**REDACTED**",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": "auto",
    "api_version_set": 3.3,
    "api_version_used": 3.3,
    "api_working": true,
    "status": {},
    "cached_state": {
      "updated_at": 1679767822.4444249,
      "1": false,
      "2": 26,
      "3": 45,
      "4": "1",
      "5": false,
      "6": false,
      "102": 0,
      "104": true
    },
    "pending_state": {
      "6": {
        "value": false,
        "updated_at": 1679767822.162346,
        "sent": true
      }
    },
    "connected": true,
    "force_dps": [],
    "home_assistant": {
      "name": "53B thermostat",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "climate.53b_thermostat_2",
            "state": "off",
            "attributes": {
              "hvac_modes": [
                "heat",
                "off",
                "auto"
              ],
              "min_temp": 5.0,
              "max_temp": 35.0,
              "target_temp_step": 0.5,
              "preset_modes": [
                "comfort",
                "eco"
              ],
              "current_temperature": 22.5,
              "temperature": 13.0,
              "preset_mode": "comfort",
              "unknown_104": true,
              "friendly_name": "53B thermostat",
              "supported_features": 17
            },
            "last_changed": "2023-03-25T17:57:58.442004+00:00",
            "last_updated": "2023-03-25T17:57:58.442004+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "lock.53b_thermostat_child_lock",
            "state": "unlocked",
            "attributes": {
              "icon": "mdi:hand-back-right",
              "friendly_name": "53B thermostat Child lock",
              "supported_features": 0
            },
            "last_changed": "2023-03-25T18:10:22.329284+00:00",
            "last_updated": "2023-03-25T18:10:22.329284+00:00"
          }
        }
```

# Information about DPS mappings

```
{
  "result": {
    "category": "wk",
    "functions": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "child_lock",
        "dp_id": 6,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":10,\"max\":70,\"scale\":1,\"step\":5}"
      },
      {
        "code": "eco",
        "dp_id": 5,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "upper_temp",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":5}"
      }
    ],
    "status": [
      {
        "code": "eco",
        "dp_id": 5,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":10,\"max\":70,\"scale\":1,\"step\":5}"
      },
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "child_lock",
        "dp_id": 6,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "upper_temp",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":5}"
      }
    ]
  },
  "success": true,
  "t": 1679767382402,
  "tid": "48b0fcf3cb3711ed868e92fe0d59ba81"
}
```

# Product ID

    "product_id": "IAYz2WK1th0cMLmL",

# Information about how the device functions

Thermostat is reporting temperature and setpoints twice what they really are.  The Tuya App reports tempoeratures correctly, as does the device itself.  This is a problem for the core HA Tuya integration as well - when I was using that I had to put a fudge in place to make it useable.  There is endless chatter on the HA forum about why this is.

**Comment by make-all** [comment]
There seem to be many different clones of the BHT-002 thermometer.   Is this actually a MOES branded one, or something else? Based on the information you have given, it seems you are saying the current_temperature of 22.5 and the set temperature of 13 are both double what they should be.  This would mean the actual values are 11.25 and 6.5?

But based on the documentation in "Information about DPS mappings", there shouldn't be a current temperature, instead dp 3 should be an unscaled maximum temperature (45), and dp 2 set temperature should be scaled by 10 with a step of 5 (0.5 after scaling), making the current setting 2.6 actually an out of range and invalid stepping.

What makes the most sense to me though, looking at those values is that the 22.5 current temperature is probably correct, but the set temperature should be unscaled, at 26, and not scaled to 13 (or 6.5 or 2.6 depending on which information is to be believed).

**Comment by make-all** [comment]
The thermostat is also identified in the diagnostics as `climate.53b_thermostat_2`. The _2 at the end suggests that there is already a `climate.53b_thermostat` configured.  Are you perhaps still looking at the Tuya cloud integration provided entity?

**Comment by jone9618** [comment]
> There seem to be many different clones of the BHT-002 thermometer. Is this actually a MOES branded one, or something else? Based on the information you have given, it seems you are saying the current_temperature of 22.5 and the set temperature of 13 are both double what they should be. This would mean the actual values are 11.25 and 6.5?
> 
> But based on the documentation in "Information about DPS mappings", there shouldn't be a current temperature, instead dp 3 should be an unscaled maximum temperature (45), and dp 2 set temperature should be scaled by 10 with a step of 5 (0.5 after scaling), making the current setting 2.6 actually an out of range and invalid stepping.
> 
> What makes the most sense to me though, looking at those values is that the 22.5 current temperature is probably correct, but the set temperature should be unscaled, at 26, and not scaled to 13 (or 6.5 or 2.6 depending on which information is to be believed).

Hi.  Thanks for getting back to me.  The thermometer is MOES branded (from Amazon). 

The actual temperatures are half what the readings show.  So when I look at the thermostat screen, or at the Tuya App (or for that matter the readings from another thermometer in that room) the actual temperature is half what is coming back from the integration.  Same applies to the setpoint temperature.

There is a lot of chatter about this sort of problem and some of the other Tuya integrations.  For example at https://github.com/home-assistant/core/issues/30609

Trawling through this one https://github.com/home-assistant/core/issues/66853 there is a response from the Home Assistant team which indicates that some of these thermostat have not been implemented in accordance with the specification.  The post is long, and gets a bit fraught.  This was after the bundled cloud Tuya integration was updated. The prior version had a hack to allow users to insert the appropriate scaling factors (mine looks like it is half, but there are reports of other multiplication factors on the forums).

What would be useful is if there were a way to recreate the option to insert the factors as part of the config flow process within the integration to be able to support these thermostats.

To deal with this scaling problem when using the bundled Tuya cloud integration I set up my own workaround, where I used a series of template sensors to create a parallel thermostat which presented the corrected numbers.  The reference to climate.53b_thermostat_2 in the diagnostic is to the thermostat that I created using the template sensors.

I can revert to my template workaround if necessary, but looking at the activity on the forums I'm sure I won't be the only one with this issue.

"

**Comment by defaultbad** [comment]
I also had issues with a this moes thermostat when using the cloud (mine was reporting a quarter of the real temperature)
since trying tuya local it is displaying the correct temperature. I would suggest re installing your thermostat with uuid and local keys and name it something else, I feel its still pulling from your previously created entity

 "integration_manifest": {
    "domain": "tuya_local",
    "name": "Tuya Local",
    "codeowners": [
      "@make-all"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/make-all/tuya-local",
    "integration_type": "device",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/make-all/tuya-local/issues",
    "requirements": [
      "pycryptodome~=3.17",
      "tinytuya==1.12.0"
    ],
    "version": "2022.3.1",
    "is_built_in": false
  },
  "data": {
    "name": "BHT-002 thermostat C",
    "type": "moes_bht002_thermostat_c",
    "device_id": "**REDACTED**",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": "auto",
    "api_version_set": 3.3,
    "api_version_used": 3.3,
    "api_working": true,
    "status": {},
    "cached_state": {
      "updated_at": 1679866282.1463618,
      "1": false,
      "2": 40,
      "3": 32,
      "4": "1",
      "5": false,
      "6": false,
      "103": "0",
      "104": false
    },
    "pending_state": {},
    "connected": true,
    "force_dps": [],
    "home_assistant": {
      "name": "BHT-002 thermostat C",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "lock.bht_002_thermostat_c_child_lock",
            "state": "unlocked",
            "attributes": {
              "icon": "mdi:hand-back-right",
              "friendly_name": "BHT-002 thermostat C Child lock",
              "supported_features": 0
            },
            "last_changed": "2023-03-26T19:33:38.318884+00:00",
            "last_updated": "2023-03-26T19:33:38.318884+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "climate.bht_002_thermostat_c",
            "state": "off",
            "attributes": {
              "hvac_modes": [
                "heat",
                "off",
                "auto"
              ],
              "min_temp": 5.0,
              "max_temp": 35.0,
              "target_temp_step": 0.5,
              "preset_modes": [
                "comfort",
                "eco"
              ],
              "current_temperature": 16.0,
              "temperature": 20.0,
              "preset_mode": "comfort",
              "unknown_104": false,
              "friendly_name": "BHT-002 thermostat C",
              "supported_features": 17
            },
            "last_changed": "2023-03-26T20:28:33.187388+00:00",
            "last_updated": "2023-03-26T21:06:14.467519+00:00"
          }

**Comment by make-all** [comment]
`climate.53b_thermostat_2` is under this integration in the diagnostics provided, so it is the climate entity provided by this integration.  If those temperatures are correct, then this integration is correct for your thermometer.

**Comment by jone9618** [comment]
Thanks for looking at this.  I have uninstalled and reinstalled, and given the reinstalled device a new name.  Unfortunately the problem persists - actual temperature and setpoint temperature out y a factor of 2.  Having said that it is manageable - just not ideal. 
Given that this reporting of incorrect temperatures seems to be a widespread feature of these devices, I'm sure others will report the problem in future.  For now I will revert to my workaround.
