### ISSUE TITLE
Request support for Tadiran Wind Inverter 40A Air Condition

### ISSUE THREAD

**Issue by yuvalhal** [make-all/tuya-local#574]
# Log Message

**```
Device matches ir_remote_sensors with quality of 7%. DPS: {"updated_at": 1679859470.3162622, "1": false, "2": 16, "3": 215, "4": "cooling", "5": "middle", "101": 210, "102": 205, "103": 205, "104": 3, "105": "Off", "106": false, "107": "Off", "108": "Off", "109": 0, "110": -550, "111": 150, "112": 155, "113": 155, "114": 160, "115": 165, "116": 0, "117": 0, "118": 219, "119": 350, "122": 0, "123": 0, "124": 0}
Report this to https://github.com/make-all/tuya-local/issues/
Device matches ir_remote_sensors with quality of 7%. DPS: {"updated_at": 1679860343.1570776, "1": false, "2": 16, "3": 215, "4": "cooling", "5": "middle", "101": 210, "102": 205, "103": 205, "104": 3, "105": "Off", "106": false, "107": "Off", "108": "Off", "109": 0, "110": -550, "111": 150, "112": 155, "113": 155, "114": 160, "115": 165, "116": 0, "117": 0, "118": 218, "119": 350, "122": 0, "123": 0, "124": 0}
Device matches ir_remote_sensors with quality of 7%. DPS: {"updated_at": 1679898243.947122, "1": false, "2": 16, "3": 215, "4": "cooling", "5": "middle", "101": 215, "102": 215, "103": 215, "104": 3, "105": "Off", "106": false, "107": "Off", "108": "Off", "109": 0, "110": -550, "111": 170, "112": 170, "113": 175, "114": 360, "115": 310, "116": 0, "117": 0, "118": 219, "119": 350, "122": 0, "123": 0, "124": 0}
Device matches ir_remote_sensors with quality of 7%. DPS: {"updated_at": 1679898970.3603175, "1": false, "2": 16, "3": 205, "4": "cooling", "5": "middle", "101": 165, "102": 160, "103": 165, "104": 3, "105": "Off", "106": false, "107": "Off", "108": "Off", "109": 0, "110": 230, "111": 175, "112": 170, "113": 175, "114": 290, "115": 195, "116": 0, "117": 0, "118": 219, "119": 350, "122": 0, "123": 0, "124": 0}
```**

# Information about DPS mappings

<!--
If you have an iot.tuya.com account, please go to "Cloud" -> "API
Explorer".  Under "Smart Home Device System"/"Device Control", select
the last "Get Device Specification Attribute" function, check the
server is set correctly, and enter your device ID.
-->
**{
  "result": {
    "category": "kt",
    "functions": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "type": "Integer",
        "values": "{\"min\":16,\"unit\":\"℃\",\"scale\":0,\"max\":32,\"step\":1}"
      },
      {
        "code": "fan_speed_enum",
        "type": "Enum",
        "values": "{\"range\":[\"sleep\",\"health\",\"natural\",\"strong\",\"auto\",\"low\",\"middle\",\"high\",\"mute\"]}"
      },
      {
        "code": "mode",
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"cold\",\"hot\",\"wet\",\"wind\"]}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "type": "Integer",
        "values": "{\"min\":16,\"unit\":\"℃\",\"scale\":0,\"max\":32,\"step\":1}"
      },
      {
        "code": "temp_current",
        "type": "Integer",
        "values": "{\"min\":-2000,\"scale\":0,\"unit\":\"℃\",\"max\":2000,\"step\":1}"
      },
      {
        "code": "fan_speed_enum",
        "type": "Enum",
        "values": "{\"range\":[\"sleep\",\"health\",\"natural\",\"strong\",\"auto\",\"low\",\"middle\",\"high\",\"mute\"]}"
      },
      {
        "code": "mode",
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"cold\",\"hot\",\"wet\",\"wind\"]}"
      }
    ]
  },
  "success": true,
  "t": 1679901468169,
  "tid": "7a260a80cc6f11ed9963de456539a11f"
}**



DP ID: Switch
code: 1
DP ID: Temp Set
Code: 2
DP ID: Temp Current
Code: 3
DP ID: Mode
Code: 4
DP ID: Fan Speed Command
Code: 5
DP ID: IDU COIL IN (TH4)
Code: 101
DP ID:  IDU COIL MID (TH3)
Code: 102
DP ID:  IDU COIL MID (TH2)
Code: 103
DP ID:  IDU Rev
Code: 104
DP ID:  IDU Fan Speed FB
Code: 105
DP ID:  Inverter Type
Code: 106
DP ID:  ODU MODE
Code: 107
DP ID:  ODU FAN SPEED
Code: 108
DP ID:  COMP.FREQUENCY
Code: 109
DP ID:  IGBT Temp
Code: 110
DP ID:  AMBIENT Temp (TH5)
Code: 111
DP ID:  ODU COIL OUT(TH4)
Code: 112
DP ID:  ODU COIL IN(TH3)
Code: 113
DP ID:  DISCHARGE Temp(TH2)
Code: 114
DP ID:  SUCTION Temp(TH1)
Code: 115
DP ID:  COMP.CURRENT
Code: 116
DP ID:  COMP.POWER
Code: 117
DP ID:  AC INPUT VOLTAGE
Code: 118
DP ID:  EEV OPEN Steps
Code: 119
DP ID:  FOUR_WAY
Code: 122
DP ID:  IDU Error Code
Code: 123
DP ID:  ODU Error Code
Code: 124



# Product ID pdwzhqdjh6ppnjpb

**Comment by make-all** [comment]
This seems compatible with the existing Tadiran 65/3P model for the basic climate controls.  The diagnostic values are different, so I needed to remove most of those (which were unknowns in the previous config), just leaving a few which I labelled as above.
