### ISSUE TITLE
Request support for TOMZN 63A

### ISSUE THREAD

**Issue by rdaguerre** [make-all/tuya-local#577]
STANDARD STATUS SET

total_forward_energy | Integer | {   "unit": "kW·h",   "min": 0,   "max": 99999999,   "scale": 2,   "step": 1 }
-- | -- | --
phase_a | Raw | {}
phase_b | Raw | {}
phase_c | Raw | {}
fault | Bitmap | {   "label": [     "short_circuit_alarm",     "surge_alarm",     "overload_alarm",     "leakagecurr_alarm",     "temp_dif_fault",     "fire_alarm",     "high_power_alarm",     "self_test_alarm",     "ov_cr",     "unbalance_alarm",     "ov_vol",     "undervoltage_alarm",     "miss_phase_alarm",     "outage_alarm",     "magnetism_alarm",     "credit_alarm",     "no_balance_alarm"   ] }
switch_prepayment | Boolean | "{true,false}"
energy_reset | Enum | {   "range": [     "empty"   ] }
balance_energy | Integer | {   "unit": "kW·h",   "min": 0,   "max": 99999999,   "scale": 2,   "step": 1 }
charge_energy | Integer | {   "unit": "kW·h",   "min": 0,   "max": 999999,   "scale": 2,   "step": 1 }
leakage_current | Integer | {   "unit": "mA",   "min": 0,   "max": 1000,   "scale": 0,   "step": 1 }
switch | Boolean | "{true,false}"
alarm_set_1 | Raw | {}
alarm_set_2 | Raw | {}
breaker_number | String | {   "maxlen": 255 }
leakagecurr_test | Boolean | "{true,false}"
temp_current | Integer | {   "unit": "℃",   "min": -400,   "max": 1250,   "scale": 1,   "step": 1 }

STANDARD INSTRUCTION SET

switch_prepayment | Boolean | "{true,false}"
-- | -- | --
energy_reset | Enum | {   "range": [     "empty"   ] }
charge_energy | Integer | {   "unit": "kW·h",   "min": 0,   "max": 999999,   "scale": 2,   "step": 1 }
switch | Boolean | "{true,false}"
alarm_set_1 | Raw | {}
alarm_set_2 | Raw | {}
leakagecurr_test | Boolean | "{true,false}"

register error HA
-------------

Device matches None with quality of 0%. DPS: {"updated_at": 1680145622.8155146, "1": 0, "9": 0, "11": false, "12": false, "13": 0, "15": 4, "16": true, "19": "\u0007", "21": true, "102": 261}

    {
        "category": "dlq",
        "sub": false,
        "uuid": "d029d6f90e12bdc9",
        "biz_type": 18,
        "product_name": "WIFI\u667a\u80fd\u65ad\u8def\u5668",
        "mac": "1c:90:ff:4f:38:ec",
        "product_id": "psjg8ldomxnelfp5",
        "sn": "JX20221206202204",
        "key": "f71a29xxxxxxxx",
        "model": "WIFI-1",
        "icon": "https://images.tuyaus.com/smart/icon/ay15736160944174WdWY/40ab25c21ec2ed44988a0d3b5358580a.png",
        "id": "eb7a12fb1bc7cxxxxxxx",
        "name": "Breaker"
    },

DP Important

switch: 16
phaseA: 6
leakage: 15

i think is equal to name: TOMPD-63LW

example 
2023-03-30 01:07:08 | Report | Phase A | CPQAFEkAAuk= | device itself |  
2023-03-30 01:06:26 | Report | Phase A | CPwAFGEAAu4= | device itself |  
2023-03-30 01:06:05 | Report | Phase A | CPkAFGoAAu8= | device itself |  
2023-03-30 01:05:44 | Report | Phase A | CQgAFIwAAvg= | device itself |  
2023-03-30 01:05:24 | Report | Phase A | CQMAFFgAAuo= | device itself |  
2023-03-30 01:05:03 | Report | Phase A | CP4AFFsAAuo= | device itself |  
2023-03-30 01:04:42 | Report | Phase A | CQIAFG8AAvU= | device itself |  
2023-03-30 01:04:21 | Report | Phase A | CQQAFGkAAu4= | device itself |  
2023-03-30 01:04:00 | Report | Phase A | CPYAE8IAA2g= | device itself |  
2023-03-30 01:03:39 | Report | Phase A | CPgAE5gAA2A= | device itself

<br class="Apple-interchange-newline">
</body>
</html>
https://www.aliexpress.us/item/3256805033122565.html?gps-id=pcStoreJustForYou&scm=1007.23125.137358.0&scm_id=1007.23125.137358.0&scm-url=1007.23125.137358.0&pvid=9e1b4c1c-2ab8-42b2-838c-25336d4379db&_t=gps-id%3ApcStoreJustForYou%2Cscm-url%3A1007.23125.137358.0%2Cpvid%3A9e1b4c1c-2ab8-42b2-838c-25336d4379db%2Ctpp_buckets%3A668%232846%238109%231935&pdp_ext_f=%7B%22sku_id%22%3A%2212000032233705628%22%2C%22sceneId%22%3A%2213125%22%7D&pdp_npi=3%40dis%21USD%2126.3%2121.04%21%21%21%21%21%402101f6b116801482388882827eaa3e%2112000032233705628%21rec%21US%21741547476&spm=a2g0o.store_pc_home.smartJustForYou_2004763636096.1&gatewayAdapt=glo2usa&_randl_shipto=US

thanks for all
great work. excuse me for my english

**Comment by rdaguerre** [comment]
hi, thanks. all 8 sensor work ok. alarms will be good
im install pyscript and make this .py  for extract V,A,W.

@state_trigger('sensor.breaker_meter_phase_a')
def base64_decode_breaker_meter():
    #!/usr/bin/env python3
    import base64
    import sys

    # Decoding value from datapoint 6 which is base64-based (manually activated)
    value_phase_a = state.get('sensor.breaker_meter_phase_a')
    value_decoded = base64.b64decode(value_phase_a)

    # Calculating Voltage from base64-decoded value
    value_voltage = round(int.from_bytes(value_decoded[0:2], byteorder='big')*0.1, 1)
    state.set('sensor.breaker_meter_voltage_py', value_voltage, {"unit_of_measurement": "V"})

    # Calculating Current from base64-decoded value
    value_current = round(int.from_bytes(value_decoded[3:5], byteorder='big')*0.001, 2)
    state.set('sensor.breaker_meter_current_py', value_current, {"unit_of_measurement": "A" })

    # Calculating Power from base64-decoded value
    value_power = round(int.from_bytes(value_decoded[6:8], byteorder='big'), 3)
    state.set('sensor.breaker_meter_power_py', value_power, {"unit_of_measurement": "W"})


thanks for you work. best regards

Ronnie

**Comment by make-all** [comment]
Since these phase_a/b/c encoded fields seem to be common across a number of energy meter devices, it may be worthwhile to check if the encoding is common and add some special code to handle breaking it out to multiple attributes or sensors.

**Comment by make-all** [comment]
I'm not sure why you are seeing undecoded values.  I updated the tests for this device to use the value above, and get 224.0V, 4000mA, 821.0W as the output.

This is not yet released though, so maybe your method of updating is incomplete. Or if you are testing a different device than TOMZN 63A/TOMPD 63LW, then there may be an error in the config for that device that is causing this.

**Comment by make-all** [comment]
Please raise a new issue with more details about the device used and any log messages if you see the encoded values in the 2023.4.1 release.

**Comment by rdaguerre** [comment]
Hi, i update today HA and make a error . I have a 64A version. 
thanks 

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:46
Integration: Tuya Local (documentation, issues)
First occurred: 19:41:12 (2 occurrences)
Last logged: 19:41:12

Device matches tompd_63lw_breaker with quality of 89%. DPS: {"updated_at": 1682116872.2232325, "1": 18392, "9": 0, "11": false, "12": false, "13": 0, "15": 3, "16": true, "19": "\u0007", "102": 224}
Report this to https://github.com/make-all/tuya-local/issues/

---------------------

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/helpers/device_config.py:387
Integration: Tuya Local (documentation, issues)
First occurred: 19:38:10 (3 occurrences)
Last logged: 19:41:33

Breaker Meter receive loop terminated by exception argument should be a bytes-like object or ASCII string, not 'NoneType'
Breaker Power receive loop terminated by exception argument should be a bytes-like object or ASCII string, not 'NoneType'
Traceback (most recent call last):
  File "/config/custom_components/tuya_local/device.py", line 200, in receive_loop
    entity.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 721, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 568, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 632, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 470, in state
    value = self.native_value
  File "/config/custom_components/tuya_local/sensor.py", line 72, in native_value
    return self._sensor_dps.get_value(self._device)
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 363, in get_value
    bytevalue = self.decoded_value(device)
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 387, in decoded_value
    return b64decode(v)
  File "/usr/local/lib/python3.10/base64.py", line 80, in b64decode
    s = _bytes_from_decode_data(s)
  File "/usr/local/lib/python3.10/base64.py", line 45, in _bytes_from_decode_data
    raise TypeError("argument should be a bytes-like object or ASCII "
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'

**Comment by make-all** [comment]
This has already been reported as #631, and should be fixed in the main branch.

**Comment by sippe2** [comment]
Hi @make-all,

I have a TOMZN 63A Circuit Breaker (TOMPD-63LW). The device is recognized correctly, but the values do not update unless the phone application is open. As soon as I open the phone application and select this device, the values start updating in Tuya-local. However, when I close the phone application value updating stops. What could be causing this and is it possible to fix it somehow?

**Comment by make-all** [comment]
There is a Refresh sensors button available to force the device to update. The app is doing something similar.

**Comment by sippe2** [comment]
Thank you for the superfast answer. So the idea is create an automation to push the button every minute?

**Comment by make-all** [comment]
However frequently you need the data. I am not sure why the device acts like this. Does it perhaps run off a battery when switched off, so has a reason to avoid a few mW of drain sending things over WiFi constantly?

**Comment by sippe2** [comment]
It seems to me that the device does not have any kind of battery. At least I didn’t find one when I ripped one apart a few months ago. I think this behavior is unreasonable or perhaps the purpose is to reduce the amount of data being transferred. Might be the manufacturer has assumed that data only needs to be sent when the phone application is active. I would understand this if the device ran on a battery but in fact it receives power continuously from the phase it’s connected to.

I have domestic water heater behind the contactor and of course it would be nice to collect data on its operation to calculate the cost of heating water as well as to monitor consumption and the need for water heating in general. Do I need it? Well... In general no but I like to see what is going on.

`
alias: Slap the sleepy TOMZN
description: ""
triggers:
  - trigger: time_pattern
    minutes: /1
actions:
  - target:
      entity_id: button.circuit_breaker_63a_refresh_sensors
    action: button.press
    data: {}
mode: single
`
