### ISSUE TITLE
Arlec 2200W Grid Connect Smart Convection Panel Heater

### ISSUE THREAD

**Issue by Silvrav** [make-all/tuya-local#578]
# Log Message

```
Please paste logs here
```

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/HANNES~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/HANNES~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

DP ID | Code | example
-- | -- | --
switch | 1 | OFF
Set   Temperature | 2 | 20'C
Current   Temperature | 3 | 17'C
Countdown | 19 | 1h
Mode | 4 | eco, comfort,   anti-frost
childlock | 7 | OFF

</body>

</html>

```
{
  "result": {
    "category": "qn",
    "functions": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":5,\"max\":50,\"scale\":0,\"step\":1}"
      },
      {
        "code": "lock",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_set",
        "type": "Enum",
        "values": "{\"range\":[\"cancel\",\"1h\",\"2h\",\"3h\",\"4h\",\"5h\",\"6h\"]}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":5,\"max\":50,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_current",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-20,\"max\":50,\"scale\":0,\"step\":1}"
      },
      {
        "code": "lock",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_set",
        "type": "Enum",
        "values": "{\"range\":[\"cancel\",\"1h\",\"2h\",\"3h\",\"4h\",\"5h\",\"6h\"]}"
      }
    ]
  },
  "success": true,
  "t": 1680219654698,
  "tid": "5013f798cf5411ed9c106a2c61a2ec08"
}
```

"product_id": "zf4japp0z9hihzsz"

This device is a grid connect Arlec 2200W White Grid Connect Smart Convection Panel Heater model number PEH225HA
Details
On/off switch
Temperature adjustments stepped in 1 degree celsius 
temp range 5°C- 50°C
3 modes, eco, comfort and anti frost.
anti frost sets the temp to 5'C
eco runs the unit at half power (1100w)
comfort runs the unit at full power (2200w)
Adjustable 1-24 hr timer 

https://www.bunnings.co.nz/arlec-2200w-white-grid-connect-smart-convection-panel-heater_p0163657?store=9532&gclid=CjwKCAjw5pShBhB_EiwAvmnNV7xuSYsEve9jV6hu_tT9EAwaP_yjL4StfqxU81SBfZwtrEOO-uJYfBoCfqwQAvD_BwE&gclsrc=aw.ds

**Comment by Silvrav** [comment]
Note: I currently use the device with the inow heater profile and this seems to work except that it misses the timer function, mode functions and it steps it in 5'C intervals and not 1'C intervals

**Comment by thewolf-oz** [comment]
I have a similar Arlec Panel Heater, though it's 2400W. I've tested this file with it and submitted a PR. The DP IDs appear different to yours: https://github.com/thewolf-oz/tuya-local/blob/main/custom_components/tuya_local/devices/arlec_panel_heater.yaml

I've adapted mine to the DP IDs you've supplied if the above doesn't work for you. If the above doesn't work and the below does I can make a PR: https://github.com/thewolf-oz/tuya-local/blob/main/custom_components/tuya_local/devices/arlec_panel_heater_v2.yaml

**Comment by Silvrav** [comment]
> I have a similar Arlec Panel Heater, though it's 2400W. I've tested this file with it and submitted a PR. The DP IDs appear different to yours: https://github.com/thewolf-oz/tuya-local/blob/main/custom_components/tuya_local/devices/arlec_panel_heater.yaml
> 
> I've adapted mine to the DP IDs you've supplied if the above doesn't work for you. If the above doesn't work and the below does I can make a PR: https://github.com/thewolf-oz/tuya-local/blob/main/custom_components/tuya_local/devices/arlec_panel_heater_v2.yaml

Thank you. I have created the yaml and placed it in the appropriate location but when I add the device under integrations I do not get the YAML as an option. Restarted the HA after uploading the file but no luck. 

I only have the following as options from the menu:
<html>
<body>
<div ccp_infra_version='3' ccp_infra_timestamp='1680556105849' ccp_infra_user_hash='60761419' ccp_infra_copy_id='46712f97-ef3a-4c9e-bd0a-dc1f8ccab56d' data-ccp-timestamp='1680556105849'><html><head><meta name=ProgId content=Excel.Sheet><meta name=Generator content="Microsoft Excel 15"><style>table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
td
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	text-align:general;
	vertical-align:bottom;
	border:none;
	white-space:nowrap;
	mso-rotate:0;}
</style></head><body link="#0563C1" vlink="#954F72">

Eurom_saniwallheat2000_heater
--
Eurom_walldesignheat2000_heater
inow_heater_element
mirabella_geio_usb
netmostat_n1_thermostat
simple_lightbulb
simple_switch

</body></html></div>
</body>
</html>

**Comment by thewolf-oz** [comment]
Which file(s) did you save? I think yours should be the v2 file

**Comment by Silvrav** [comment]
> Which file(s) did you save? I think yours should be the v2 file

I tried both.

**Comment by Silvrav** [comment]
Thank you very much! Can confirm its working

**Comment by contactnat** [comment]
> Thank you very much! Can confirm its working

Hi, do the presets work for you? I have the same heater but changing the preset via ha does nothing. However if I use the tuya app they work, and ha shows the correct state too.

**Comment by make-all** [comment]
That is probably because there was no information on the presets, and I had to guess at the values for the config.

If you download the diagnostics for the device with the preset set at each setting, it will show what the local protocol values are so the config can be fixed.

**Comment by contactnat** [comment]
try these, I changed the presets using the tuya app then downloaded the diagnostics through the local tuya integration, let me know if I should have done it differently?

[tuya_local-antifrost.txt](https://github.com/make-all/tuya-local/files/11458866/tuya_local-antifrost.txt)
[tuya_local-comfort.txt](https://github.com/make-all/tuya-local/files/11458867/tuya_local-comfort.txt)
[tuya_local-eco.txt](https://github.com/make-all/tuya-local/files/11458868/tuya_local-eco.txt)

**Comment by contactnat** [comment]
> That is probably because there was no information on the presets, and I had to guess at the values for the config.
> 
> If you download the diagnostics for the device with the preset set at each setting, it will show what the local protocol values are so the config can be fixed.

I updated my file as per your changes and can confirm it now works! Thanks heaps

**Comment by Silvrav** [comment]
Thanks! sorry only got back from holiday today. I added the new file but now I get a zombie state from my heater - it flashes 00 all the time and I can issue a command from HA and the tuya smart app, but after 3 seconds it goes off again and just flashes 00

**Comment by make-all** [comment]
I don't know what you mean by "I added the new file".  You should upgrade the whole integration to the latest version.
