### ISSUE TITLE
I got "Unable to connect to your device with this details" when trying to connect with my Socket 

### ISSUE THREAD

**Issue by VCTGomes** [make-all/tuya-local#595]
**Describe the bug**
All info is right, but I can't connect my Socket to Tuya Local. I got the "Unable to connect to your device with this details" message and I can't connect!

**To Reproduce**
Trying to connect first time.

**Additional context**

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

**Comment by make-all** [comment]
Please see #522 for possible causes of connection issues.
