### ISSUE TITLE
Request support for Arkifi double wall socket with 2 USB

### ISSUE THREAD

**Issue by MiloRoNu** [make-all/tuya-local#596]
# Log Message

Este error se originó en una integración personalizada.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:46 
Integration: Tuya Local (documentation, issues) 
First occurred: 20:06:31 (2 occurrences) 
Last logged: 20:06:31

Device matches arlec_pb88uha_s2_switch with quality of 77%. DPS: {"updated_at": 1680912390.618807, "1": true, "2": false, "3": false, "4": false, "9": 0, "10": 0, "11": 0, "12": 0, "38": "on", "41": false, "42": "", "43": "", "44": ""}
Report this to https://github.com/make-all/tuya-local/issues/

# Information about DPS mappings

{
  "result": {
    "category": "pc",
    "functions": [
      {
        "code": "switch_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_2",
        "dp_id": 2,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_3",
        "dp_id": 3,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_4",
        "dp_id": 4,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_2",
        "dp_id": 10,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_3",
        "dp_id": 11,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_4",
        "dp_id": 12,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "dp_id": 38,
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "child_lock",
        "dp_id": 41,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "cycle_time",
        "dp_id": 42,
        "type": "String",
        "values": "{}"
      },
      {
        "code": "random_time",
        "dp_id": 43,
        "type": "String",
        "values": "{}"
      },
      {
        "code": "switch_inching",
        "dp_id": 44,
        "type": "String",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_2",
        "dp_id": 2,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_3",
        "dp_id": 3,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_4",
        "dp_id": 4,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_2",
        "dp_id": 10,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_3",
        "dp_id": 11,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_4",
        "dp_id": 12,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "dp_id": 38,
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      },
      {
        "code": "child_lock",
        "dp_id": 41,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "cycle_time",
        "dp_id": 42,
        "type": "String",
        "values": "{}"
      },
      {
        "code": "random_time",
        "dp_id": 43,
        "type": "String",
        "values": "{}"
      },
      {
        "code": "switch_inching",
        "dp_id": 44,
        "type": "String",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1680912846551,
  "tid": "468c4d1ad5a211edaa23c686e2b37de2"
}

# Product ID

product_id: o8z3fcmpcoxwpwz3

# Information about how the device functions

This is the data sheet of the product. It’s in Spanish, since it’s a device made for Chile.
https://drive.google.com/file/d/158MaoJxEVRGWpYw_wLOanp5glvS1e2pv/view

**Comment by make-all** [comment]
There isn't really enough info in your report to know why the arlec_pb88uha_s2_switch config (for a 4 switch device with independant timers) is not sufficient.

**Comment by make-all** [comment]
Assuming arlec_pb88uha_s2 covers this, as the config matches and no feedback received.
