### ISSUE TITLE
DOOR SENSOR

### ISSUE THREAD

**Issue by RudiEter** [make-all/tuya-local#598]
I managed  add the door sensor to the integration. 
Integration recognize door sensor as switch an work good.

The problem is when the sensor goes to sleep and the state of the switch is unavailable not OPEN or CLOSE.
How would i make the sensor to keep the last state?

**Comment by make-all** [comment]
Battery powered devices that are not stable on the network are not supported.

**Comment by RudiEter** [comment]
thankyou

V V pon., 10. apr. 2023 ob 00:40 je oseba Jason Rumney <
***@***.***> napisala:
