### ISSUE TITLE
Heaters automatically turn on to heat after Home Assistant restart

### ISSUE THREAD

**Issue by awaismun** [make-all/tuya-local#6]
I am noticing an issue with the heaters. When I restart Home Assistant for some reason, the heater are automatically set to "heat". Is it possible to restore them to the previous state?

**Comment by make-all** [comment]
I don't think Home Assistant changes any state when it restarts, but it can trigger automations to run.  The latest 0.106 release has increased the information in Logbook which might help in debugging what is happening, for example, when I turned all my heaters off and restarted just now, they initially remained off, but after Home Assistant fiinshed starting, came on, and I see the following message in Logbook:

Heaters on when cold has been triggered by numeric state of sensor.people_tracker

**Comment by make-all** [comment]
Since you seem to have been using a heater for which support was only just added in issue #5, maybe you can retest after updating to the new version, to see if this issue is still present. It may have been caused by the wrong heater type causing wrong initialization sequence to your heater.

**Comment by make-all** [comment]
Please check with 0.2.0, which is updated to use a newer Tuya library.

**Comment by make-all** [comment]
Closed due to no feedback

**Comment by awaismun** [comment]
@make-all Sorry for late reply. It didnt make any difference. The devices are still on unavailable after power outage.

**Comment by make-all** [comment]
This sounds different than the originally reported behaviour, so perhaps a new issue explaining the current symptoms is warranted.
