### ISSUE TITLE
Request support for Out and Out Original Zora - Convector Panel Heater 2000W With Wifi - Deluxe

### ISSUE THREAD

**Issue by mwkchan** [make-all/tuya-local#603]
# Information about DPS mappings

{
  "result": {
    "category": "qn",
    "functions": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"°C\",\"min\":1,\"max\":35,\"scale\":0,\"step\":1}"
      },
      {
        "code": "mode",
        "dp_id": 4,
        "type": "Enum",
        "values": "{\"range\":[\"eco\"]}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"°C\",\"min\":1,\"max\":35,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_current",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"unit\":\"°C\",\"min\":0,\"max\":80,\"scale\":0,\"step\":1}"
      },
      {
        "code": "mode",
        "dp_id": 4,
        "type": "Enum",
        "values": "{\"range\":[\"eco\"]}"
      },
      {
        "code": "countdown_left",
        "dp_id": 12,
        "type": "Integer",
        "values": "{\"unit\":\"m\",\"min\":0,\"max\":1440,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1681079867539,
  "tid": "26e5f0fad72711ed93dec2bd506f6b85"
}

**Comment by make-all** [comment]
There doesn't appear to be a major difference between this and the anderson_gsh_heater.
Modes are different, but since this one only lists "eco" as a valid mode, a meaningful config for that cannot be made without further info.
