### ISSUE TITLE
Request Support for Smart Ape Solar Light

### ISSUE THREAD

**Issue by Krispkiwi** [make-all/tuya-local#605]
Hey Mate, I was wondering if it's at all possible to get these solar lights working locally, they connect to the Tuya bluetooth gateway and can generate a local key, however they don't have an IP address showing since they're a bluetooth device. I can get them through the normal tuya integration but local control is definitely preferred. 

https://www.mightyape.co.nz/product/smart-ape-solar-garden-light/35164419

Here's what's showing under device specifications. If I'm fetching the wrong data please let me know

https://pastebin.com/sWMnT7m4

**Comment by make-all** [comment]
Not yet. @LesTR had a branch with work in progress to support gateways and subdevices, but I don't know what state it is in currently.

My preference actually would be to support Tuya Bluetooth LE devices directly as Bluetooth devices, and Zigbee gateways as zigbee devices, probably through different integrations.  In the case of Bluetooth hubs, I think only Tuya devices can connect which does limit the scope, but Zigbee gateways can support non-Tuya devices pairing also, so I am worried that this integration will get overloaded with requests to support Philips Hue, Ikea and other non-Tuya subdevices once we get gateway support.

**Comment by make-all** [comment]
The device details do not have any local dp ids, so unless you can find more info, this will be considered closed by the general inclusion of subdevice support in the next release.  You can open a new issue if the work in that release is enough for you to capture logs showing the dp ids

**Comment by Krispkiwi** [comment]
Just attempted this, the Bluetooth gateway wouldn't connect so couldn't get test the sub devices, no worries.

**Comment by Krispkiwi** [comment]
Hey mate, an update on this, I've just got one of these lights connected via 3.4 using the local node however I'm missing a lot of the light config, It's a fully RGB so the lamp option given that only shows warm and white doesn't quite fulfill all the functionality of the light.

What would you need to bring this in?

**Comment by make-all** [comment]
If it is not detected as one of the RGB lights already, then the dps layout must be non-standard, and I would need the log or device diagnostics from Home Assistant to check what layout it is using.

**Comment by Krispkiwi** [comment]
[config_entry-tuya_local-29799b8d4d844ae1dee892f1fb11c3ec.json.txt](https://github.com/make-all/tuya-local/files/12213960/config_entry-tuya_local-29799b8d4d844ae1dee892f1fb11c3ec.json.txt)


Here you go
<img width="192" alt="2023-07-31 22_15_15-Settings – Home Assistant" src="https://github.com/make-all/tuya-local/assets/72541572/17067c44-5c5d-4e56-8143-63a63be8f511">

Here's the diagnostics and the options that come up in total for 3.4 for the solar light.

**Comment by make-all** [comment]
IOT portal info (without dp ids: Query Things Data Model results would be better):
```
{
  "result": {
    "category": "gyd",
    "functions": [
      {
        "code": "switch_led",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"
      },
      {
        "code": "bright_value",
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_value",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "colour_data",
        "type": "Json",
        "values": "{}"
      },
      {
        "code": "scene_data",
        "type": "Json",
        "values": "{}"
      },
      {
        "code": "countdown",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "music_data",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "device_mode",
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"manual\"]}"
      },
      {
        "code": "cds",
        "type": "Enum",
        "values": "{\"range\":[\"2000lux\",\"300lux\",\"50lux\",\"10lux\",\"5lux\"]}"
      },
      {
        "code": "pir_sensitivity",
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"middle\",\"high\"]}"
      },
      {
        "code": "pir_delay",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":5,\"max\":3600,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_pir",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "standby_time",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":1,\"max\":480,\"scale\":0,\"step\":1}"
      },
      {
        "code": "standby_bright",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch_led",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"
      },
      {
        "code": "bright_value",
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_value",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "colour_data",
        "type": "Json",
        "values": "{}"
      },
      {
        "code": "scene_data",
        "type": "Json",
        "values": "{}"
      },
      {
        "code": "countdown",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "device_mode",
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"manual\"]}"
      },
      {
        "code": "pir_state",
        "type": "Enum",
        "values": "{\"range\":[\"pir\",\"none\"]}"
      },
      {
        "code": "cds",
        "type": "Enum",
        "values": "{\"range\":[\"2000lux\",\"300lux\",\"50lux\",\"10lux\",\"5lux\"]}"
      },
      {
        "code": "pir_sensitivity",
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"middle\",\"high\"]}"
      },
      {
        "code": "pir_delay",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":5,\"max\":3600,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_pir",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "standby_time",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":1,\"max\":480,\"scale\":0,\"step\":1}"
      },
      {
        "code": "standby_bright",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1681186039359,
  "tid": "5a4210b5d81e11ed8ee74e84e26a469d"
}
```

DPS from diagnostics:

```
    "cached_state": {
      "updated_at": 1690798550.230404,
      "1": true,
      "2": "colour",
      "3": 255,
      "4": 12,
      "5": "010803E703E8",
      "6": "05464601000003e803e800000000464601007803e803e80000000046460100f003e803e800000000464601003d03e803e80000000046460100ae03e803e800000000464601011303e803e800000000",
      "7": 0,
      "51": "manual",
      "56": true,
      "60": false,
      "62": "high"
    },
```

**Comment by Krispkiwi** [comment]
[query things.txt](https://github.com/make-all/tuya-local/files/12214887/query.things.txt)
Couldn't see anything with DP ID in the query but this is what I get with query things in data model under device control.

**Comment by make-all** [comment]
I don't know why Tuya can't be consistent with their naming, they call them abilityId under that documentation:
```
{"abilityId":1,"accessMode":"rw","code":"switch_led","description":"","name":"开关","typeSpec":{"type":"bool","typeDefaultValue":false}},
{"abilityId":2,"accessMode":"rw","code":"work_mode","description":"","name":"模式","typeSpec":{"range":["white","colour","scene","music"],"type":"enum","typeDefaultValue":"white"}},
{"abilityId":3,"accessMode":"rw","code":"bright_value","description":"","name":"亮度值","typeSpec":{"max":1000,"min":10,"scale":0,"step":1,"type":"value","typeDefaultValue":10}},
{"abilityId":4,"accessMode":"rw","code":"temp_value","description":"","name":"冷暖值","typeSpec":{"max":1000,"min":0,"scale":0,"step":1,"type":"value","typeDefaultValue":0}},
{"abilityId":5,"accessMode":"rw","code":"colour_data","description":"","name":"彩光","typeSpec":{"maxlen":255,"type":"string","typeDefaultValue":""}},
{"abilityId":6,"accessMode":"rw","code":"scene_data","description":"","name":"场景","typeSpec":{"maxlen":255,"type":"string","typeDefaultValue":""}},
{"abilityId":7,"accessMode":"rw","code":"countdown","description":"","name":"倒计时","typeSpec":{"max":86400,"min":0,"scale":0,"step":1,"type":"value","typeDefaultValue":0}},
{"abilityId":8,"accessMode":"rw","code":"music_data","description":"","name":"音乐灯","typeSpec":{"maxlen":255,"type":"string","typeDefaultValue":""}},
{"abilityId":51,"accessMode":"rw","code":"device_mode","description":"","name":"设备模式","typeSpec":{"range":["auto","manual"],"type":"enum","typeDefaultValue":"auto"}},
{"abilityId":52,"accessMode":"rw","code":"pir_state","description":"","name":"感应状态","typeSpec":{"range":["pir","none"],"type":"enum","typeDefaultValue":"pir"}},
{"abilityId":53,"accessMode":"rw","code":"cds","description":"","name":"光敏参数","typeSpec":{"range":["2000lux","300lux","50lux","10lux","5lux"],"type":"enum","typeDefaultValue":"2000lux"}},
{"abilityId":54,"accessMode":"rw","code":"pir_sensitivity","description":"","name":"灵敏度","typeSpec":{"range":["low","middle","high"],"type":"enum","typeDefaultValue":"low"}},
{"abilityId":55,"accessMode":"rw","code":"pir_delay","description":"","name":"感应延时","typeSpec":{"max":3600,"min":5,"scale":0,"step":1,"type":"value","typeDefaultValue":5,"unit":"s"}},
{"abilityId":56,"accessMode":"rw","code":"switch_pir","description":"","name":"感应开关","typeSpec":{"type":"bool","typeDefaultValue":false}},
{"abilityId":58,"accessMode":"rw","code":"standby_time","description":"","extensions":{"attribute":"512"},"name":"伴亮延时","typeSpec":{"max":480,"min":1,"scale":0,"step":1,"type":"value","typeDefaultValue":1,"unit":"min"}},
{"abilityId":59,"accessMode":"rw","code":"standby_bright","description":"","extensions":{"attribute":"512"},"name":"伴亮亮度值","typeSpec":{"max":1000,"min":0,"scale":0,"step":1,"type":"value","typeDefaultValue":0}},
{"abilityId":60,"accessMode":"rw","code":"sensorgroup_sync","description":"","name":"组内感应同步","typeSpec":{"type":"bool","typeDefaultValue":false}},
{"abilityId":61,"accessMode":"rw","code":"standby_on","description":"","extensions":{"attribute":"512"},"name":"微亮常开","typeSpec":{"type":"bool","typeDefaultValue":false}},
{"abilityId":62,"accessMode":"rw","code":"battery_state","description":"","extensions":{"attribute":"512"},"name":"电池电量","typeSpec":{"range":["low","middle","high"],"type":"enum","typeDefaultValue":"low"}}
```

**Comment by Krispkiwi** [comment]
Just double checking, is there any more data you'd like? I'm not well versed in reading the data myself so I just want to make sure I'm not leaving you hanging on anything.

**Comment by make-all** [comment]
I think only productId from one of the API Explorer functions.

**Comment by Krispkiwi** [comment]
Can confirm it works. I was expecting just the colour but you brought all the sensors in, brilliant.

**Comment by Krispkiwi** [comment]
I did have one weird thing happen, It detected one solar light, i went to add another and the solar light action didn't appear, after a cache refresh it did on another attempt, just in case you get any reports on that.

**Comment by IkusasaNZ** [comment]
> Hey Mate, I was wondering if it's at all possible to get these solar lights working locally, they connect to the Tuya bluetooth gateway and can generate a local key, however they don't have an IP address showing since they're a bluetooth device. I can get them through the normal tuya integration but local control is definitely preferred.
> 
> https://www.mightyape.co.nz/product/smart-ape-solar-garden-light/35164419
> 
> Here's what's showing under device specifications. If I'm fetching the wrong data please let me know
> 
> https://pastebin.com/sWMnT7m4

@Krispkiwi , how did you go about getting the local key, when I try all I get is the following:

"local_key": "",

and that is for all my Mighty Ape solar lights.

**Comment by Krispkiwi** [comment]
> > Hey Mate, I was wondering if it's at all possible to get these solar lights working locally, they connect to the Tuya bluetooth gateway and can generate a local key, however they don't have an IP address showing since they're a bluetooth device. I can get them through the normal tuya integration but local control is definitely preferred.
> > https://www.mightyape.co.nz/product/smart-ape-solar-garden-light/35164419
> > Here's what's showing under device specifications. If I'm fetching the wrong data please let me know
> > https://pastebin.com/sWMnT7m4
> 
> @Krispkiwi , how did you go about getting the local key, when I try all I get is the following:
> 
> "local_key": "",
> 
> and that is for all my Mighty Ape solar lights.

Use the local key and I'd from your Bluetooth hub then using tiny tuya you can find the I'd you need to pair

**Comment by IkusasaNZ** [comment]
> > > Hey Mate, I was wondering if it's at all possible to get these solar lights working locally, they connect to the Tuya bluetooth gateway and can generate a local key, however they don't have an IP address showing since they're a bluetooth device. I can get them through the normal tuya integration but local control is definitely preferred.
> > > https://www.mightyape.co.nz/product/smart-ape-solar-garden-light/35164419
> > > Here's what's showing under device specifications. If I'm fetching the wrong data please let me know
> > > https://pastebin.com/sWMnT7m4
> > 
> > 
> > @Krispkiwi , how did you go about getting the local key, when I try all I get is the following:
> > "local_key": "",
> > and that is for all my Mighty Ape solar lights.
> 
> Use the local key and I'd from your Bluetooth hub then using tiny tuya you can find the I'd you need to pair

Thanks @Krispkiwi , will  give that a go.
