### ISSUE TITLE
Request support for Loratap Smart Garage Door Opener

### ISSUE THREAD

**Issue by matteozamu** [make-all/tuya-local#607]
# Log Message

```
This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:46
Integration: Tuya Local (documentation, issues)
First occurred: 10:06:13 (2 occurrences)
Last logged: 10:06:13

Device matches None with quality of 0%. DPS: {"updated_at": 1681200372.005937, "7": 0, "101": false, "102": 20, "103": 0}
Report this to https://github.com/make-all/tuya-local/issues/
```

# Information about DPS mappings

```
{
  "result": {
    "category": "kg",
    "functions": [
      {
        "code": "switch_1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1681200633159,
  "tid": "54d33ef4d84011ed99d6ea1895c2a2b1"
}
```

# Product ID
```
"product_id": "kksjmhr9nhjudvzo",
"product_name": "Smart Garage Door Opener",
```

# Information about how the device functions

I believe these are the correct values to indicate the state of the garage door:
switch_1 status: indicates if the garage door is closed (true) or open (false)

This is the link to the device page of the vendor:
https://www.loratap.com/products/gdc100w

After digging on the Tuya IoT website, I've seen that there are 5 DP:
<img width="183" alt="image" src="https://user-images.githubusercontent.com/51788939/231103446-87d47ee5-e877-469a-9fcc-edcf7e9f5f5d.png">

I've tried to provide as many details as possible, let me know if other information is needed.
Thank you!

**Comment by make-all** [comment]
The Chinese names read "Magnetic switch" and "Travel time setting".  I guess "magnetic switch is maybe a fully closed or open detection, which is missing from the log as there is only one boolean listed.
It isn't clear though which of the integer values is which (two countdowns and a travel time setting).  Maybe you can narrow it down using the steps 2 or 3 [here](https://github.com/make-all/tuya-local#device-support).

**Comment by matteozamu** [comment]
门磁开关 (Magnetic switch) is the closed or open detection and it is the 101 DPS in the log above.

The other three DPS are timers and by looking in the SmartLife app:
- 7 should be "Countdown"
- 102 (行程时间设置 - Travel time setting) is used for the opening/closing animation in the app (in this case 20 seconds)
- 103 I guess is "Timer"

**Comment by make-all** [comment]
So there is no dp for switch_1, to actually control the door?

**Comment by matteozamu** [comment]
I was wrong about the DPS 7. This is an example of a configuration I found online by a guy who is using LocalTuya.  It should work like this, I hope

`"entities": [
        {
          "id": 7,
          "friendly_name": "Switch",
          "platform": "switch"
        },
        {
          "id": 101,
          "friendly_name": "Status",
          "state_on": "True",
          "state_off": "False",
          "device_class": "garage_door",
          "platform": "binary_sensor"
        }
      ]`

**Comment by make-all** [comment]
No, it won't work like that, dp 7 is not a boolean, it can't be the switch.  Try using the method described [here](https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html#_8-find-your-data-point) to get the  code for the "Switch" option in that dropdown you screenshotted above.

**Comment by matteozamu** [comment]
Following that method, I was able to get this: 
It now appears a "new" DP:    "dpId": 1   that refers to the switch.
```
[
    {
        "dpName": "Switch",
        "dpId": 1
    },
    {
        "dpName": "门磁开关",
        "dpId": 101
    },
    {
        "dpName": "行程时间设置",
        "dpId": 102
    },
    {
        "dpName": "Countdown",
        "dpId": 7
    },
    {
        "dpName": "Countdown",
        "dpId": 103
    }
]
```

and this is specific for the Switch option:

```
{
    "startRowId": "",
    "pageNo": 1,
    "pageSize": 10,
    "code": "1",
    "startTime": 1681570695794,
    "endTime": 1681743495794,
    "projectCode": "xxx",
    "sourceId": "xxx",
    "sourceType": "4",
    "deviceId": "xxx",
    "pageStartRow": "",
    "region": "EU"
}
```
