### ISSUE TITLE
New version bht-6000 error migration

### ISSUE THREAD

**Issue by antoweb** [make-all/tuya-local#61]
Logger: homeassistant.config_entries
Source: custom_components/tuya_local/__init__.py:132
Integration: Tuya Local (documentation, issues)
First occurred: 23:39:01 (1 occurrences)
Last logged: 23:39:01

Error migrating entry termostato for tuya_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 519, in async_migrate
    result = await component.async_migrate_entry(hass, self)  # type: ignore
  File "/config/custom_components/tuya_local/__init__.py", line 132, in async_migrate_entry
    newopts[e.config_id] = opts[e.entity]
KeyError: 'light'

**Comment by make-all** [comment]
Did you previously have it configured with the light disabled?
I think it means the light is missing from the config. Maybe I also edited the config to add the light in the same release.

**Comment by make-all** [comment]
I think this issue with the migration should be fixed in 0.12.1
