### ISSUE TITLE
Request support for Nedis Smart Air Conditioner 9000 BTU

### ISSUE THREAD

**Issue by JuhaFIN1** [make-all/tuya-local#610]
Included Diagnostic File attachment from Tuya, hope there is all data?

[tuya-0d5d0b9f0647fde776463d8b4299777b-Smart Air Conditioner 9000 BTU-1f5b792573686c3957f25d40c289900d.json (1).txt](https://github.com/make-all/tuya-local/files/11207592/tuya-0d5d0b9f0647fde776463d8b4299777b-Smart.Air.Conditioner.9000.BTU-1f5b792573686c3957f25d40c289900d.json.1.txt)

DIAGNOSTIC:

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.4.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.10",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Helsinki",
    "os_name": "Linux",
    "os_version": "6.1.22",
    "supervisor": "2023.04.0",
    "host_os": "Home Assistant OS 10.0.rc3",
    "docker_version": "23.0.2",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "weatherbit": {
      "version": "1.0.19",
      "requirements": [
        "pyweatherbitdata==1.0.15"
      ]
    },
    "xiaomi_miio_fan": {
      "version": "2022.8.0.0",
      "requirements": [
        "construct==2.10.56",
        "python-miio>=0.5.12"
      ]
    },
    "localtuya": {
      "version": "5.0.0",
      "requirements": []
    },
    "watchman": {
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    },
    "iphonedetect": {
      "version": "1.4.0",
      "requirements": []
    },
    "alexa_media": {
      "version": "4.6.2",
      "requirements": [
        "alexapy==1.26.5",
        "packaging>=20.3",
        "wrapt>=1.12.1"
      ]
    },
    "ble_monitor": {
      "version": "11.9.0-beta",
      "requirements": [
        "pycryptodomex>=3.14.1",
        "janus>=1.0.0",
        "aioblescan>=0.2.14",
        "btsocket>=0.2.0",
        "pyric>=0.1.6.3"
      ]
    },
    "samsungtv_smart": {
      "version": "0.11.6",
      "requirements": [
        "websocket-client!=1.4.0,>=0.58.0",
        "wakeonlan>=2.0.0",
        "aiofiles>=0.8.0",
        "casttube>=0.2.1"
      ]
    },
    "trakt_tv": {
      "version": "0.8.1",
      "requirements": []
    },
    "nicehash": {
      "version": "0.0.4",
      "requirements": []
    },
    "edge_tts": {
      "version": "0.0.1",
      "requirements": [
        "edge-tts==6.1.3"
      ]
    },
    "xiaomi_cloud_map_extractor": {
      "version": "v2.2.0",
      "requirements": [
        "pillow",
        "pybase64",
        "python-miio",
        "requests",
        "pycryptodome"
      ]
    },
    "icloud3": {
      "version": "2.4.6",
      "requirements": []
    },
    "ember_mug": {
      "version": "0.6.0",
      "requirements": [
        "python-ember-mug==0.6.0"
      ]
    },
    "bmw_connected_drive": {
      "version": "2023.3.12",
      "requirements": [
        "bimmer_connected==0.13.0"
      ]
    },
    "delonghi_primadonna": {
      "version": "1.3.3",
      "requirements": []
    },
    "plex_recently_added": {
      "version": "0.3.8",
      "requirements": []
    },
    "browser_mod": {
      "version": "2.2.1",
      "requirements": []
    },
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "trakt": {
      "version": "2.0.3",
      "requirements": [
        "trakt==2.14.0"
      ]
    },
    "alarmo": {
      "version": "v1.9.8",
      "requirements": []
    },
    "yahoofinance": {
      "version": "1.1.11",
      "requirements": []
    },
    "nordpool": {
      "version": "0.0.13",
      "requirements": [
        "nordpool>=0.2",
        "backoff"
      ]
    },
    "fontawesome": {
      "version": "2.1.5",
      "requirements": []
    },
    "philips_airpurifier_coap": {
      "version": "0.10.8",
      "requirements": [
        "aioairctrl==0.2.4"
      ]
    },
    "mass": {
      "version": "2023.2.1",
      "requirements": [
        "music-assistant==1.8.7.4"
      ]
    },
    "fullykiosk": {
      "version": "1.1.0",
      "requirements": [
        "python-fullykiosk==0.0.11"
      ]
    },
    "xiaomi_miot": {
      "version": "0.7.7",
      "requirements": [
        "construct==2.10.56",
        "python-miio>=0.5.6",
        "micloud>=0.3"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya",
    "name": "Tuya",
    "codeowners": [
      "@Tuya",
      "@zlinoliver",
      "@frenck"
    ],
    "config_flow": true,
    "dependencies": [
      "ffmpeg"
    ],
    "dhcp": [
      {
        "macaddress": "105A17*"
      },
      {
        "macaddress": "10D561*"
      },
      {
        "macaddress": "1869D8*"
      },
      {
        "macaddress": "381F8D*"
      },
      {
        "macaddress": "508A06*"
      },
      {
        "macaddress": "68572D*"
      },
      {
        "macaddress": "708976*"
      },
      {
        "macaddress": "7CF666*"
      },
      {
        "macaddress": "84E342*"
      },
      {
        "macaddress": "D4A651*"
      },
      {
        "macaddress": "D81F12*"
      }
    ],
    "documentation": "https://www.home-assistant.io/integrations/tuya",
    "integration_type": "hub",
    "iot_class": "cloud_push",
    "loggers": [
      "tuya_iot"
    ],
    "requirements": [
      "tuya-iot-py-sdk==0.6.6"
    ],
    "is_built_in": true
  },
  "data": {
    "endpoint": "https://openapi.tuyaeu.com",
    "auth_type": 0,
    "country_code": "358",
    "app_type": "tuyaSmart",
    "mqtt_connected": true,
    "disabled_by": null,
    "disabled_polling": false,
    "name": "Smart Air Conditioner 9000 BTU",
    "model": "WIFIACMB3WT9",
    "category": "kt",
    "product_id": "z8xltnkqigeumr1f",
    "product_name": "Smart Air Conditioner 9000 BTU",
    "online": true,
    "sub": false,
    "time_zone": "+02:00",
    "active_time": "2022-08-24T08:04:32+00:00",
    "create_time": "2022-08-24T08:04:32+00:00",
    "update_time": "2023-04-12T04:48:52+00:00",
    "function": {
      "fan_speed_enum": {
        "type": "Enum",
        "value": {
          "range": [
            "low",
            "mid",
            "high",
            "auto"
          ]
        }
      },
      "mode": {
        "type": "Enum",
        "value": {
          "range": [
            "cold",
            "hot",
            "wet",
            "wind"
          ]
        }
      },
      "temp_set": {
        "type": "Integer",
        "value": {
          "min": 16,
          "unit": "\u2103",
          "scale": 0,
          "max": 31,
          "type": "value",
          "step": 1
        }
      },
      "switch": {
        "type": "Boolean",
        "value": ""
      }
    },
    "status_range": {
      "temp_current": {
        "type": "Integer",
        "value": {
          "min": -20,
          "scale": 0,
          "unit": "\u2103",
          "max": 100,
          "step": 1
        }
      },
      "fan_speed_enum": {
        "type": "Enum",
        "value": {
          "range": [
            "low",
            "mid",
            "high",
            "auto"
          ]
        }
      },
      "mode": {
        "type": "Enum",
        "value": {
          "range": [
            "cold",
            "hot",
            "wet",
            "wind"
          ]
        }
      },
      "temp_set": {
        "type": "Integer",
        "value": {
          "min": 16,
          "unit": "\u2103",
          "scale": 0,
          "max": 31,
          "type": "value",
          "step": 1
        }
      },
      "switch": {
        "type": "Boolean",
        "value": {}
      }
    },
    "status": {
      "switch": false,
      "temp_set": 22,
      "temp_current": 25,
      "mode": "cold",
      "fan_speed_enum": "low"
    },
    "home_assistant": {
      "name": "Smart Air Conditioner 9000 BTU",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "climate.smart_air_conditioner_9000_btu",
            "state": "off",
            "attributes": {
              "hvac_modes": [
                "off",
                "cool",
                "heat",
                "dry",
                "fan_only"
              ],
              "min_temp": 16.0,
              "max_temp": 31.0,
              "target_temp_step": 1.0,
              "fan_modes": [
                "low",
                "mid",
                "high",
                "auto"
              ],
              "current_temperature": 25.0,
              "temperature": 22.0,
              "fan_mode": "low",
              "friendly_name": "Smart Air Conditioner 9000 BTU",
              "supported_features": 9
            },
            "last_changed": "2023-04-12T05:43:03.283706+00:00",
            "last_updated": "2023-04-12T05:43:03.283706+00:00"
          }
        }
      ]
    }
  }
}

**Comment by make-all** [comment]
No local data

**Comment by JuhaFIN1** [comment]
> No local data

And this means what?

**Comment by make-all** [comment]
It means you have provided only cloud data, which is not sufficient to provide local support.
The issue template contains instructions on what is required when filing a request for New Device support.
