### ISSUE TITLE
Request support for Light Strip "3-bit Wifi large board light with controller PCBA (color R, G, B)"

### ISSUE THREAD

**Issue by aletsweb** [make-all/tuya-local#623]
# Log Message

```
Please paste logs here
```

# Information about DPS mappings

```
{
  "result": {
    "category": "dd",
    "functions": [
      {
        "code": "switch_led",
        "dp_id": 20,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "dp_id": 21,
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"
      },
      {
        "code": "colour_data",
        "dp_id": 24,
        "type": "Json",
        "values": "{\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}"
      },
      {
        "code": "scene_data",
        "dp_id": 25,
        "type": "Json",
        "values": "{\"scene_num\":{\"min\":1,\"scale\":0,\"max\":8,\"step\":1},\"scene_units\": {\"unit_change_mode\":{\"range\":[\"static\",\"jump\",\"gradient\"]},\"unit_switch_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"unit_gradient_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"bright\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"temperature\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}}"
      },
      {
        "code": "countdown",
        "dp_id": 26,
        "type": "Integer",
        "values": "{\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "music_data",
        "dp_id": 27,
        "type": "Json",
        "values": "{\"change_mode\":{\"range\":[\"direct\",\"gradient\"]}, \"bright\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"temperature\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      },
      {
        "code": "control_data",
        "dp_id": 28,
        "type": "Json",
        "values": "{\"change_mode\":{\"range\":[\"direct\",\"gradient\"]}, \"bright\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"temperature\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      }
    ],
    "status": [
      {
        "code": "switch_led",
        "dp_id": 20,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "dp_id": 21,
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"
      },
      {
        "code": "colour_data",
        "dp_id": 24,
        "type": "Json",
        "values": "{\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}"
      },
      {
        "code": "scene_data",
        "dp_id": 25,
        "type": "Json",
        "values": "{\"scene_num\":{\"min\":1,\"scale\":0,\"max\":8,\"step\":1},\"scene_units\": {\"unit_change_mode\":{\"range\":[\"static\",\"jump\",\"gradient\"]},\"unit_switch_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"unit_gradient_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"bright\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"temperature\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}}"
      },
      {
        "code": "countdown",
        "dp_id": 26,
        "type": "Integer",
        "values": "{\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1681882572857,
  "tid": "1890fa68de7411eda4083a3fb6a8c6de"
}
```

# Product ID

 "product_id": "j2itrg2vktyh6vuz"

# Information about how the device functions

<html>
<body>

switch_led | Boolean | "{true,false}"
-- | -- | --
work_mode | Enum | {   "range": [     "white",     "colour",     "scene",     "music"   ] }
colour_data | Json | {   "h": {     "min": 0,     "scale": 0,     "unit": "",     "max": 360,     "step": 1   },   "s": {     "min": 0,     "scale": 0,     "unit": "",     "max": 1000,     "step": 1   },   "v": {     "min": 0,     "scale": 0,     "unit": "",     "max": 1000,     "step": 1   } }
scene_data | Json | {   "scene_num": {     "min": 1,     "scale": 0,     "max": 8,     "step": 1   },   "scene_units": {     "unit_change_mode": {       "range": [         "static",         "jump",         "gradient"       ]     },     "unit_switch_duration": {       "min": 0,       "scale": 0,       "max": 100,       "step": 1     },     "unit_gradient_duration": {       "min": 0,       "scale": 0,       "max": 100,       "step": 1     },     "bright": {       "min": 0,       "scale": 0,       "max": 1000,       "step": 1     },     "temperature": {       "min": 0,       "scale": 0,       "max": 1000,       "step": 1     },     "h": {       "min": 0,       "scale": 0,       "unit": "",       "max": 360,       "step": 1     },     "s": {       "min": 0,       "scale": 0,       "unit": "",       "max": 1000,       "step": 1     },     "v": {       "min": 0,       "scale": 0,       "unit": "",       "max": 1000,       "step": 1     }   } }
countdown | Integer | {   "min": 0,   "max": 86400,   "scale": 0,   "step": 1 }
music_data | Json | {   "change_mode": {     "range": [       "direct",       "gradient"     ]   },   "bright": {     "min": 0,     "scale": 0,     "unit": "",     "max": 1000,     "step": 1   },   "temperature": {     "min": 0,     "scale": 0,     "unit": "",     "max": 1000,     "step": 1   },   "h": {     "min": 0,     "scale": 0,     "unit": "",     "max": 360,     "step": 1   },   "s": {     "min": 0,     "scale": 0,     "unit": "",     "max": 255,     "step": 1   },   "v": {     "min": 0,     "scale": 0,     "unit": "",     "max": 255,     "step": 1   } }
control_data | Json | {   "change_mode": {     "range": [       "direct",       "gradient"     ]   },   "bright": {     "min": 0,     "scale": 0,     "unit": "",     "max": 1000,     "step": 1   },   "temperature": {     "min": 0,     "scale": 0,     "unit": "",     "max": 1000,     "step": 1   },   "h": {     "min": 0,     "scale": 0,     "unit": "",     "max": 360,     "step": 1   },   "s": {     "min": 0,     "scale": 0,     "unit": "",     "max": 255,     "step": 1   },   "v": {     "min": 0,     "scale": 0,     "unit": "",     "max": 255,     "step": 1   } }

</body>
</html>

**Comment by make-all** [comment]
Looks like a standard rgbcw_lightbulb layout.

**Comment by aletsweb** [comment]
> Looks like a standard rgbcw_lightbulb layout.

Yeah so it seems, but when i tried the "rgbcw_lightbulb layout" it's only the color mode that works, the white mode doesn't work.
