### ISSUE TITLE
Request support for wifi illuminance sensor

### ISSUE THREAD

**Issue by robertrebor** [make-all/tuya-local#626]
# Log Message

```
Please paste logs here
```

# Information about DPS mappings

```
{
  "result": {
    "category": "ldcg",
    "functions": [],
    "status": [
      {
        "code": "bright_state",
        "dp_id": 1,
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"middle\",\"high\"]}"
      },
      {
        "code": "bright_value",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"lux\",\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1681935634192,
  "tid": "a38a42cfdeef11ed9e48762a04b19869"
}
```

# Product ID

8181077094b97e16d467

# Information about how the device functions

**Comment by make-all** [comment]
Is this battery powered?  If you are not able to get logs, it does not seem worth spending time trying to support, as there is a high likelihood that it simply will not work due to being offline most of the time to conserve battery, and only waking to report to the Tuya cloud.

**Comment by robertrebor** [comment]
@make-all  thank you for adding my illuminance sensor to your integration. both IDs from sensor working without problem :)
