### ISSUE TITLE
Request support for Smart WiFi Aroma Diffuser

### ISSUE THREAD

**Issue by aurelmarius** [make-all/tuya-local#627]
Name: Smart 400ML WiFi Aromatherapy Machine
Product_id: "6ASdNwe9IdaewQEl",
Name: "Aromatherapy machine",

DPs:

"result": {
    "category": "jsq",
    "functions": [
      {
        "code": "switch_led",
        "dp_id": 11,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_spray",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "dp_id": 103,
        "type": "Enum",
        "values": "{\"range\":[\"small\",\"large\"]}"
      },
      {
        "code": "colour_data_hsv",
        "dp_id": 108,
        "type": "Json",
        "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      },
      {
        "code": "work_mode",
        "dp_id": 109,
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"colourful1\"]}"
      },
      {
        "code": "moodlighting",
        "dp_id": 110,
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\"]}"
      },
      {
        "code": "bright_value",
        "dp_id": 111,
        "type": "Integer",
        "values": "{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch_led",
        "dp_id": 11,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_spray",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "dp_id": 103,
        "type": "Enum",
        "values": "{\"range\":[\"small\",\"large\"]}"
      },
      {
        "code": "colour_data_hsv",
        "dp_id": 108,
        "type": "Json",
        "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      },
      {
        "code": "work_mode",
        "dp_id": 109,
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"colourful1\"]}"
      },
      {
        "code": "moodlighting",
        "dp_id": 110,
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\"]}"
      },
      {
        "code": "bright_value",
        "dp_id": 111,
        "type": "Integer",
        "values": "{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}"
      }
    ]
  },

  "result": {
    "category": "jsq",
    "functions": [
      {
        "code": "switch_led",
        "desc": "switch led",
        "name": "switch led",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_spray",
        "desc": "switch spray",
        "name": "switch spray",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "desc": "mode",
        "name": "mode",
        "type": "Enum",
        "values": "{\"range\":[\"small\",\"large\"]}"
      },
      {
        "code": "colour_data_hsv",
        "desc": "colour data hsv",
        "name": "colour data hsv",
        "type": "Json",
        "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      },
      {
        "code": "work_mode",
        "desc": "work mode",
        "name": "work mode",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"colourful1\"]}"
      },
      {
        "code": "moodlighting",
        "desc": "moodlighting",
        "name": "moodlighting",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\"]}"
      },
      {
        "code": "bright_value",
        "desc": "bright value",
        "name": "bright value",
        "type": "Integer",
        "values": "{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}"
      }
    ]
  },

**Comment by make-all** [comment]
Does this have a brand name, or a web link where I can see more info?

**Comment by aurelmarius** [comment]
> Does this have a brand name, or a web link where I can see more info?

This is the product. Thanks.

TUYA Ultrasonic Humidifier Electric Aroma Air Diffuser 400ML  Wood Grain Air Humidifier Essential Oil Aromatherapy Mist Maker

https://a.aliexpress.com/_mM5Q7n6

**Comment by make-all** [comment]
Thanks, it seems to be a Ditua DT-1522YN

**Comment by aurelmarius** [comment]
Thanks for the device integration but it seems that only the fan entity is created, the light one doesn't appear.
![image](https://user-images.githubusercontent.com/7074653/236673189-13e7509d-6483-4a5f-a623-11efddc7d0a1.png)
