### ISSUE TITLE
Request support for  Blitzwolf BW-SS5 WIFI Smart  1 or 2 gang  Switch

### ISSUE THREAD

**Issue by bdkacz** [make-all/tuya-local#633]
Hi

Can You add support for this device https://www.blitzwolf.com/BW-SS5-WIFI-Smart-Switch-2300W-Voice-Control-p-1645429.html ?

When  I try to add it I get "Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect." 

For 2 gang device used  DP's are :

 "dps_strings": [
        "1 (value: False)",
        "2 (value: False)",
        "9 (value: 0)",
        "10 (value: 0)"
      ],

and it's  "product_id" is  "7c35xxu0foeqpdka"

Where 1 and 2 is states of each  switch and 9 nad 10 is described in tuya cloud as  as countdown 1 and countdown 2

For 1 gang device it use  DP number 1 (switch state)  and 7 (countdown)

and "product_id": is "grgpt93aw565ihkg",

Additional info for both models:

  "protocol_version": "3.3",
      "model": "BW-SS5"

**Comment by make-all** [comment]
This should be already supported as "simple_dual_switch_timer_v2".

See #522 for sorting out the connection issues.

**Comment by bdkacz** [comment]
Hi.

The one gang version  works fine, just need to enter also IP manualny when adding. 

But with 2 gang version I have problem - after enter all data it redirects me to empty page (where normalny is a list of  possibile devices) and it's all what I can do
