### ISSUE TITLE
Not able to add the second device

### ISSUE THREAD

**Issue by ceinmart** [make-all/tuya-local#637]
I just installed the Tuya local and beginning to setup my tuya devices. 
Tuya Local Version 2023.4.1.
HA version 2023.4.1

The first device I setup it easily and without any issues. 
The second device became impossible... just doesn't work.

For the first device, they ask for ID, IP, Key , Protocol... 
For the second device, they ask for key , IP and protocol... is not the same form. 
I fill with the data of the second device , they give a message "Options save successfully" and do nothing. 
At HA logs show nothing. 
I activated the debug mode and tried to add it again. 
Looking at the log (attached) I see it found the same switch already added (Interruptor Area Gourmet).. 
Even if I changed the IP, and key... 
(language in Portuguese)

Screen to add the first device
![image](https://user-images.githubusercontent.com/7062410/233811037-83fa53bf-2d30-4970-a2da-8d8f009912a1.png)

Screen to add the second device
![image](https://user-images.githubusercontent.com/7062410/233811041-d1fdc9f9-4636-44fc-94ec-d94ccaeedb1e.png)

After click on "Enviar" (send) for the second device, they give this message . 
![image](https://user-images.githubusercontent.com/7062410/233811043-1741da18-94b7-4142-b1fd-ed72de6240c3.png)

I'm stuck with only one device and I have 24 devices more to add ... 
![image](https://user-images.githubusercontent.com/7062410/233811352-d45a885c-0514-454d-b3cb-adb2ebc3e56a.png)

**To Reproduce**
Just include one device ,then add the second one. 

**Expected behavior**
Add the second device...

Have no way to add device diagnostics since they never were added effectivily.
The second device is exactly the same type/hardware of the first added, so , isn't anything related to incompatible device. 

The key I retrieved using the tinytuya utility.

_Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too._
No messages.. 

[home-assistant_tuya_local_2023-04-22T23-12-21.774Z.log](https://github.com/make-all/tuya-local/files/11302516/home-assistant_tuya_local_2023-04-22T23-12-21.774Z.log)

**Comment by make-all** [comment]
It seems you are reconfiguring the first device instead of adding the second device.  To add the second device, you need to use the + button on the integrations screen again.

**Comment by ceinmart** [comment]
ouch!!! 
Yes, you're right. 
Was a misconception on my part. 
Thank you!!!
