### ISSUE TITLE
Moes BHT-002

### ISSUE THREAD

**Issue by Skro11-ru** [make-all/tuya-local#64]
Hi. I try to connect moes BHT-002 (climate) but it gives me 2 incomprehensible device types (mirabella_genio_usb
and simple_switch ) instead of climate. Help why and what to do?
device details
{
  "result": {
    "active_time": 1635254299,
    "biz_type": 0,
    "category": "wk",
    "create_time": 1583321813,
    "icon": "smart/icon/15264583415nnlzwfs1qd2wqz6i937op3nmi_0.png",
    "id": "xxxxxx",
    "ip": "xxxxxxxx",
    "lat": "xxxxxx",
    "local_key": "xxxxx",
    "lon": "xxxxx",
    "model": "",
    "name": "Thermostat",
    "online": true,
    "owner_id": "xxxxx",
    "product_id": "xxxxx",
    "product_name": "thermostat",
    "status": [
      {
        "code": "switch",
        "value": true
      },
      {
        "code": "temp_set",
        "value": 50
      },
      {
        "code": "upper_temp",
        "value": 50
      },
      {
        "code": "eco",
        "value": false
      },
      {
        "code": "child_lock",
        "value": false
      }
    ],
    "sub": false,
    "time_zone": "+07:00",
    "uid": "xxxxxxxx",
    "update_time": 1635254311,
    "uuid": "xxxxxxxx"
  },
  "success": true,
  "t": xxxxx
}

**Comment by make-all** [comment]
Support is added in 0.13.0
