### ISSUE TITLE
INOW heating element controls room temperature, not water temperature

### ISSUE THREAD

**Issue by pdw-mb** [make-all/tuya-local#643]
**Describe the bug**
The INOW heating element has two different temperature sensors and target temperatures: room and water.

Room operates on a scale of 7C to 30C, water temperature is 30C to 70C.

The tuya-local implementation is currently setup to control room temperature, but has a scale of 15C-70C.  Trying to set the temperature to anything beyond 30C doesn't work (the change is ignored).  The temperature set through HA doesn't have any effect if the device isn't in "comfort" or "eco" mode.

**To Reproduce**

The temperature scale in HA is 15-70, but trying to set the temperature of the device through home assistant to something higher than 30 gets ignored, because this is out-of-range for the room temperature scale.  After a short pause, the temperature control reverts to its previous setting.

**Expected behavior**

The device should present two separate temperature controls for room temperature and water temperature.

**Additional context**

tuya-local is using IDs 2 and 3 for target temp and current temp respectively:

https://github.com/make-all/tuya-local/blob/main/custom_components/tuya_local/devices/inow_heater_element.yaml#L21

These appear to be the room temp IDs.  target and current water temp appear to be 102 and 101.

If I edit my yaml to include the following in place of 2 and 3:

```
    - id: 102
      type: integer
      name: temperature
      range:
        min: 30
        max: 70
      mapping:
        - step: 5
    - id: 101
      type: integer
      name: current_temperature
```

I can now control water temperature (which is what I want to do) but I lose the ability to set room temperature.

As far as I can tell, which temperatures are used is set by the value of ID 4:

* `comfort` or `eco` => room temperature (2 and 3)
* `water_temp` => water temperature (101 and 102)
* `antifreezin` => target room temperature has a fixed value of 7 and cannot be updated.

[tuya_local-2608272a32c5c8273ba6bc1aab93d492-Bathroom Towel Rail-eb128f31f8f7448759a2c710d558d4ff.json.txt](https://github.com/make-all/tuya-local/files/11309849/tuya_local-2608272a32c5c8273ba6bc1aab93d492-Bathroom.Towel.Rail-eb128f31f8f7448759a2c710d558d4ff.json.txt)

**Comment by make-all** [comment]
I think you may have a different device than that reported in #312.  There was no water heater on that device.

**Comment by pdw-mb** [comment]
The device on #312 is a water heater, I think it's just a different version that doesn't have a room temperature sensor, so you can only control it by specifying target water temperature.  [This is what I've got](https://ukradiators.com/inowplus-anthracite-heating-element-300w-thermostatic-wifi.html).

I'm happy to submit a PR to add support for this thing, but I'm not sure how best to do it in HA.  Should the second heating controls be exposed as a second `climate` entity under `secondary_entities` ?  Is there any way to capture the logic between which mode the device is in and which setting takes effect?
