### ISSUE TITLE
Garage door opener behaves strangely after update

### ISSUE THREAD

**Issue by Bluhme1** [make-all/tuya-local#650]
After upgrading to Operating System 10.1 my garage door opener closes the garage door a few seconds after opening the door.
No problems in error logs.

Running Tuya Local 2023.4.1 and Home Assistant 2023.4.6 (supervisor 2023.4.1, operating system 10.1)

Cannot give more details, sorry

**Comment by make-all** [comment]
There may be an issue with HAOS 10, as they appear to have unpublished it.  My update.home_assistant_operating_system_update says: `installed_version: '10.0', latest_version: '9.5'`

**Comment by Bluhme1** [comment]
Solved with ver. 2023.4.2. Thank you
