### ISSUE TITLE
Devices going into "unavailable" state

### ISSUE THREAD

**Issue by elninosi** [make-all/tuya-local#653]
I noticed that my Tuya devices go into "unavailable" state. After reloading, integration is restored for some period.

Diagnostic for device that goes to unavailable state most often:

```
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.4.6",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.10",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Vienna",
    "os_name": "Linux",
    "os_version": "6.1.24",
    "supervisor": "2023.04.1",
    "host_os": "Home Assistant OS 10.0",
    "docker_version": "23.0.3",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "alarmo": {
      "version": "v1.9.9",
      "requirements": []
    },
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "multiscrape": {
      "version": "6.5.0",
      "requirements": [
        "lxml==4.9.1",
        "beautifulsoup4==4.11.1"
      ]
    },
    "panasonic_cc": {
      "version": "1.0.32",
      "requirements": []
    },
    "powercalc": {
      "version": "v1.5.1",
      "requirements": [
        "numpy>=1.21.1"
      ]
    },
    "tuya_local": {
      "version": "2022.4.1",
      "requirements": [
        "pycryptodome~=3.17",
        "tinytuya==1.12.4"
      ]
    },
    "webrtc": {
      "version": "v3.1.0",
      "requirements": []
    },
    "roborock": {
      "version": "0.1.2",
      "requirements": [
        "python-roborock==0.1.7"
      ]
    },
    "browser_mod": {
      "version": "2.2.1",
      "requirements": []
    },
    "scheduler": {
      "version": "v0.0.0",
      "requirements": []
    },
    "watchman": {
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya_local",
    "name": "Tuya Local",
    "codeowners": [
      "@make-all"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/make-all/tuya-local",
    "integration_type": "device",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/make-all/tuya-local/issues",
    "requirements": [
      "pycryptodome~=3.17",
      "tinytuya==1.12.4"
    ],
    "version": "2022.4.1",
    "is_built_in": false
  },
  "data": {
    "name": "Beok TOL47 Main thermostat",
    "type": "beok_tol47_thermostat",
    "device_id": "**REDACTED**",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": "auto",
    "api_version_set": 3.3,
    "api_version_used": 3.3,
    "api_working": true,
    "status": {},
    "cached_state": {
      "updated_at": 1682549760.0076742,
      "1": false,
      "2": 150,
      "3": 217,
      "4": "cold",
      "5": "0",
      "8": false,
      "13": true,
      "16": 0,
      "20": -18,
      "21": 30,
      "25": "1",
      "26": false,
      "31": false,
      "41": "1",
      "42": "1",
      "101": false,
      "105": 5,
      "107": 5
    },
    "pending_state": {},
    "connected": true,
    "force_dps": [],
    "home_assistant": {
      "name": "Beok TOL47 Main thermostat",
      "name_by_user": "Main Thermostat",
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "climate.main_thermostat",
            "state": "off",
            "attributes": {
              "hvac_modes": [
                "auto",
                "off",
                "heat"
              ],
              "min_temp": 5.0,
              "max_temp": 95.0,
              "target_temp_step": 0.5,
              "preset_modes": [
                "Program",
                "Temporary",
                "Manual"
              ],
              "current_temperature": 21.7,
              "temperature": 15.0,
              "hvac_action": "off",
              "preset_mode": "Manual",
              "fault_code": 0,
              "icon": "mdi:radiator-off",
              "friendly_name": "Main Thermostat",
              "supported_features": 17
            },
            "last_changed": "2023-04-26T09:56:54.371840+00:00",
            "last_updated": "2023-04-26T09:56:54.371840+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": "switch",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.main_thermostat_anti_frost",
            "state": "off",
            "attributes": {
              "device_class": "switch",
              "icon": "mdi:snowflake-melt",
              "friendly_name": "Main Thermostat Anti-frost"
            },
            "last_changed": "2023-04-26T09:56:54.370657+00:00",
            "last_updated": "2023-04-26T09:56:54.370657+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "select.main_thermostat_backlight_brightness",
            "state": "Low",
            "attributes": {
              "options": [
                "High",
                "Low",
                "None",
                "Middle"
              ],
              "icon": "mdi:lightbulb-on-40",
              "friendly_name": "Main Thermostat Backlight brightness"
            },
            "last_changed": "2023-04-26T09:56:54.372413+00:00",
            "last_updated": "2023-04-26T09:56:54.372413+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": "\u00b0C",
          "state": {
            "entity_id": "number.main_thermostat_calibration_offset",
            "state": "-1.8",
            "attributes": {
              "min": -9.0,
              "max": 9.0,
              "step": 0.1,
              "mode": "auto",
              "unit_of_measurement": "\u00b0C",
              "icon": "mdi:arrow-collapse-up",
              "friendly_name": "Main Thermostat Calibration offset"
            },
            "last_changed": "2023-04-26T09:56:54.372816+00:00",
            "last_updated": "2023-04-26T09:56:54.372816+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "lock.main_thermostat_child_lock",
            "state": "unlocked",
            "attributes": {
              "icon": "mdi:hand-back-right",
              "friendly_name": "Main Thermostat Child lock",
              "supported_features": 0
            },
            "last_changed": "2023-04-26T09:56:54.371102+00:00",
            "last_updated": "2023-04-26T09:56:54.371102+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": "temperature",
          "icon": null,
          "unit_of_measurement": "\u00b0C",
          "state": {
            "entity_id": "number.main_thermostat_external_sensor_temperature_limit",
            "state": "5",
            "attributes": {
              "min": 5,
              "max": 60,
              "step": 1.0,
              "mode": "auto",
              "unit_of_measurement": "\u00b0C",
              "device_class": "temperature",
              "icon": "mdi:arrow-collapse-up",
              "friendly_name": "Main Thermostat External sensor temperature limit"
            },
            "last_changed": "2023-04-26T09:56:54.373413+00:00",
            "last_updated": "2023-04-26T09:56:54.373413+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "problem",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "binary_sensor.main_thermostat_fault_alarm",
            "state": "off",
            "attributes": {
              "device_class": "problem",
              "friendly_name": "Main Thermostat Fault alarm"
            },
            "last_changed": "2023-04-26T09:56:54.370950+00:00",
            "last_updated": "2023-04-26T09:56:54.370950+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": "temperature",
          "icon": null,
          "unit_of_measurement": "\u00b0C",
          "state": {
            "entity_id": "number.main_thermostat_high_temperature_limit",
            "state": "30",
            "attributes": {
              "min": 15,
              "max": 95,
              "step": 1.0,
              "mode": "auto",
              "unit_of_measurement": "\u00b0C",
              "device_class": "temperature",
              "icon": "mdi:thermometer-chevron-up",
              "friendly_name": "Main Thermostat High temperature limit"
            },
            "last_changed": "2023-04-26T09:56:54.373007+00:00",
            "last_updated": "2023-04-26T09:56:54.373007+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": "switch",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.main_thermostat_output_main_reverse",
            "state": "off",
            "attributes": {
              "device_class": "switch",
              "icon": "mdi:swap-horizontal",
              "friendly_name": "Main Thermostat Output main reverse"
            },
            "last_changed": "2023-04-26T09:56:54.370792+00:00",
            "last_updated": "2023-04-26T09:56:54.370792+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "select.main_thermostat_schedule",
            "state": "Weekday+Weekend",
            "attributes": {
              "options": [
                "Weekday+Weekend",
                "Mon-Sat+Sun",
                "Daily"
              ],
              "icon": "mdi:calendar-clock",
              "friendly_name": "Main Thermostat Schedule"
            },
            "last_changed": "2023-04-26T09:56:54.372593+00:00",
            "last_updated": "2023-04-26T09:56:54.372593+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "select.main_thermostat_sensor_selection",
            "state": "Internal",
            "attributes": {
              "options": [
                "Both",
                "External",
                "Internal"
              ],
              "icon": "mdi:home-thermometer",
              "friendly_name": "Main Thermostat Sensor selection"
            },
            "last_changed": "2023-04-26T09:56:54.372069+00:00",
            "last_updated": "2023-04-26T09:56:54.372069+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": "switch",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.main_thermostat_sound",
            "state": "on",
            "attributes": {
              "device_class": "switch",
              "icon": "mdi:music-note",
              "friendly_name": "Main Thermostat Sound"
            },
            "last_changed": "2023-04-26T09:56:54.370347+00:00",
            "last_updated": "2023-04-26T09:56:54.370347+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": "\u00b0C",
          "state": {
            "entity_id": "number.main_thermostat_temperature_control_switch_difference",
            "state": "0.5",
            "attributes": {
              "min": 0.5,
              "max": 9.5,
              "step": 0.1,
              "mode": "auto",
              "unit_of_measurement": "\u00b0C",
              "icon": "mdi:thermometer-plus",
              "friendly_name": "Main Thermostat Temperature control switch difference"
            },
            "last_changed": "2023-04-26T09:56:54.373224+00:00",
            "last_updated": "2023-04-26T09:56:54.373224+00:00"
          }
        }
      ]
    }
  }
}
```

**Comment by fldc** [comment]
Same here, started some time ago.

**Comment by Nikolay-Ch** [comment]
I have six smart plugs, all of them have now state "unavailable".
State periodically return to normal but after some time go to unavailable

Cloud tuya integration works normally...

**Comment by Drummingman** [comment]
I also have the same issue

**Comment by tm1981** [comment]
i also have the same issue, the device randomly changes status to unknown and then to unavailable, restarting temporally fix the issue

**Comment by make-all** [comment]
I think there may be a limit in the number of threads Home Assistant is letting an integration start.  Because the underlying tinytuya library is not async, this integration starts a thread per device to receive updates asynchronously from the device.

**Comment by bezigebever** [comment]
@make-all I only have 1 device, the pool heatpump. 
Can we activate any additional logging ?

**Comment by adamkoch** [comment]
I see this as well, it only started happening recently (last few days), likely related to upgrading tuya-local to latest.

I only have a single pool heater connected and HA shows it as offline - using the Tuya app (Cloud) to change the pool heater state makes the entity in HA come online again but then shortly after it will go offline again.

**Comment by chrisghu** [comment]
I have the same issue with just one pool heat pump. @adamkoch  which version you have used before (which was stable for you)? I have switched from local tuya to tuya local due to the device is supported out of the box but if it is not working reliable it will not be that useful. Is there any idea what we can try to log? I'm experiencing this behavior just after a while. The wifi connection to the pump is not the best so my guess is, that is has something to do with a reconnect of the pump. Perhaps the loss of connection is bringing the integration somehow to the limit?

**Comment by make-all** [comment]
If your protocol version is set to auto, you will get faster recovery times after a network disconnection if you set the protocol version to the version actually used by your device.  If you don't know what that is, download Diagnostics for the device when it is working, and the version detected will be in the diagnostics file.

**Comment by adamkoch** [comment]
> I have the same issue with just one pool heat pump. @adamkoch which version you have used before (which was stable for you)?

It may have been a red herring. I had never seen the device go "unavailable" for 1+ years and then I upgraded to the latest version and it went unavailable constantly all day. However, for whatever reason, it seems to be stable again today and no longer going offline. I will report back in case I see more issues going forward.

**Comment by peregrines2** [comment]
Same problem here. Tonight all my 16 devices went unavailable  :(
Only restarting HA did bring them back to live :(

**Comment by bezigebever** [comment]
> If your protocol version is set to auto, you will get faster recovery times after a network disconnection if you set the protocol version to the version actually used by your device. If you don't know what that is, download Diagnostics for the device when it is working, and the version detected will be in the diagnostics file.

I've tried to set protocol to version 3.3 and this is much more stable. I still sometimes get an unavailable state, but it comes back very quick...

**Comment by ceinmart** [comment]
I'm new to HA and started to use tuya-local a few weeks ago and already "became" with this behave, which is very annoying, my automation fails constantly. 
However, my devices are set with protocol = auto. 
Changing to the correct protocol and crossing my fingers to reduce this behavior.

**Comment by Krispkiwi** [comment]
I noticed this as well, restarting home assistant seems to fix it until it happens again after a period of time.

**Comment by ceinmart** [comment]
@make-all  , just a note. 

I'm trying since yesterday to change thru the interface the protocol version of my devices. 
They are working and available, however, when I go to the configuration and change the protocol from "auto" to the correct version they give an error that aren't able to connect, the problem should be interment... 
I restarted my HA, my S.O. and the problem persists... 
To force the protocol I was forced to shutdown my HA and change manually the core.config_entries file.

**Comment by georgef333** [comment]
Same issue here,
Slowly, all my devices becomes "unavailable",
I might corelate this behavior with the upgrade of HA to 2023.5

**Comment by chrisghu** [comment]
@georgef333 I have the issue for home assistant 2023.4.6 as well. Before 2023.4 I have not used the integration so I cannot say to much.

**Comment by fldc** [comment]
The workaround is as @make-all suggested, figure out the protocol and configure it directly, haven't had a device going unavailable in over a week.

**Comment by Krispkiwi** [comment]
> The workaround is as @make-all suggested, figure out the protocol and configure it directly, haven't had a device going unavailable in over a week.

Can confirm my devices aren't going offline with this

**Comment by georgef333** [comment]
Confirm working after updating tinytuya to 1.12.7,
Thanks!

**Comment by antoweb** [comment]
> Confirm working after updating tinytuya to 1.12.7, Thanks!

Hallo how to uodate tintuya? Whats tintuya?

**Comment by make-all** [comment]
If you use HACS, tinytuya is automatically updated to match the version specified in the manifest when you upgrade to the latest version of this integration.

If you install manually, you should understand how to also install the dependency libraries.

**Comment by make-all** [comment]
The logger documentation is here: https://www.home-assistant.io/integrations/logger/
Tuya local is under `custom_components.tuya_local`, for communication issues, probably just enabling debug on `custom_components.tuya_local.device` is enough.  The low level communication is handled by `tinytuya`, and you should be able to enable debug logging for that also if you cannot spot anything at the tuya-local level.

**Comment by TheS1ngularity** [comment]
Hi, I am also having this issue, some of my ceiling lights are going unavailable very often.

Can this be cause by not selecting the correct device type by any chance?

**Comment by claudioquevedo** [comment]
Hi, I am also having this issue, some of my NovaDigital plug are going unavailable very often.

**Comment by ceinmart** [comment]
A long time ago I had issues like these. 
Consider the solution was a sum of : 

- The some fix did here on tuya-local 
- I review all my DHCP fixed IPs for all devices
- I review all my wifi environment (changes my router to a really good router, tplink deco)
- Any suspect for disconecting , first thing , monitor the network of the device with a simple ping.

For a long time, I have no issues like that anymore.

**Comment by TheCodeingPadawan** [comment]
I'd like to give some insight in this as I also came across this problem. I read that Tuya devices go offline if they get too many requests too frequently, and one source even suggested that you shouldn't set your Tuya devices to update more than once every 10 seconds, Otherwise they can freeze and restart. I also noticed on my router that when the plugs went unavailable, The host name changed from Tuya Smart Inc to wlan0. This pointed towards the Tuya devices chips restarting.

Following this, I disabled HA ability to poll the devices for each plug.

This fixed the issue completely. All my smart plugs now report their sensor readings every minute. This is not ideal and I would like a more frequent update rate, But it seems that this is handled on the plug side of things now as home assistant can't poll the devices without them randomly going unavailable. I know the device can at least poll every 5 seconds, as when I open the smart life app, select a plug, and go to electricity, It has an update rate of five seconds.

I find it odd, however, that some people say that this only started happening for them after updating Tuya local. Maybe a bug was introduced where it is sending too many requests, It updated to batch messages which some devices don't like, or it updated to a more frequent polling rate... 

Frankly though, HA has very poor support for manually setting polling rates in the GUI without writing scripts yourself, Despite this probably being quite a common requirement for sensors.

Device: Antela WiFi Smart Plug.
Model: F1s302-UK
"protocol_version": 3.4,
"tinytuya_version": "1.15.1",
"api_version_set": 3.4,
"api_version_used": 3.4,
"api_working": true,

**Comment by Vesa62** [comment]
Thanks!

Need to check this.

**Comment by make-all** [comment]
Devices going unavailable is either due to device bugs causing a reboot, which as you observe can be reduced by using the default push connection instead of enabling polling, or it can be due to unstable WiFi network, as the modules used do not have the best antennas, and are 2.4GHz only, so affected by nearby Bluetooth, Zigbee and other networks in addition to WiFi on the same congested band, and microwave ovens.

**Comment by TheCodeingPadawan** [comment]
> Thanks!
> 
> Need to check this.

Just to add to this. The one minute polling was something to do with Tuya Local. It is configured to poll once every minute as a form of rate limiting. I managed to successfully reconfigure TL to pole once every 10 seconds without issue, as long as you disable HA ability to poll the device as well. 

My current guess is that if Home Assistant is set to poll the device, because Tuya Local does its own separate polling, You can have a scenario where both HA and TL Are sending requests to the device too close together, causing the device to crash. If you just let Tuya Local handle all the polling, The devices remain stable.

You may also want to wait a bit for the devices to pull a Tuya Firmware update If you don't plan to flash them OTA. I noticed the plugs I bought were unstable for about five minutes, until they rebooted after updating, and then became fully stable. It might be asking too much of the onboard chip to handle pulling down its first update, while also at the same time frequently respond to polling requests. 

There's also a possibility the update fix the crash condition.

**Comment by make-all** [comment]
The default is to use a persistent connection to the device and let it push updates. Does your device really need polling enabled?

**Comment by TheCodeingPadawan** [comment]
> The default is to use a persistent connection to the device and let it push updates. Does your device really need polling enabled?

If I want higher resolution data, yes. 

By default, the plugs I have don't push readings very frequently. I also found that my plugs are capable of W/h reporting based on its own Internal higher resolution data, But by default through the normal Tuya integration, It does not push to expose this Locally. You have to poll the device via Tuya Local to get that data out.

You have to bear in mind the Monetization model for these devices is for you to pay for accurate monitoring statistics. It's not always going to be a given that these devices will push all that data locally, and in a timely manner. Polling, however, makes the device hand over its most up to date readings when requested, and the more frequent the better. This lets you compile your own stats, without having to pay the cloud service for accurate statistics.

10 seconds between each reading I feel is good enough for "live" monitoring, and is a high enough resolution for an accurate approximation of power usage. I know the device internally takes readings every five seconds by watching how frequently it updates in the app, and I would imagine it would be sending them 5 second data points to Tuya for usage tracking calculations. 

Sure, The 5 second resolution would be more accurate, but it's not £45 a year more accurate.
