### ISSUE TITLE
Switch reverts to ON when device is offline

### ISSUE THREAD

**Issue by nickdos** [make-all/tuya-local#66]
I successfully added a smart fan (Sterling FS1-40WIFI pedestal DC fan sold by Aldi) using this custom integration and the only entity that was added, was a simple switch. This was fine for my uses as I could turn the fan on and off using that entity. 

The issue I'm seeing is if the fan is unplugged, the switch entity shows it being ON. Manually toggling it OFF results in it staying OFF for a while but it eventually reverts to ON again (not sure why). If I look at the device in the Tuya app, it shows it as being offline.

**Comment by make-all** [comment]
Since you've added this as a switch, not a fan, I've changed the title to better reflect the actual issue.

**Comment by nickdos** [comment]
I'd be happy to try and get my fan working properly, similar to the [Lexe model](https://github.com/make-all/tuya-local/issues/34).  My fan has very similar specs - 15 speeds, oscillator, 3 modes (normal, sleep and natural), etc. 

I think I need to get the DPs list first. I've hit Python missing deps (`No module named 'cryptography'`)  when trying to run the `test.py` command from the `tuyadebug.tgz` bundle (despite installing both Python 2 and 3 versions). I have got `tuya-cli` working but can't see how to get it to output DP IDs... Any pointers?

**Comment by make-all** [comment]
I think the following should work.

`tuya-cli get --id DEVICEID --key LOCALKEY -a`

You may need to add `--protocol-version 3.3` and maybe `--ip IPADDRESS`

Alternatively, when you add the device to the tuya-local integration as a Simple Switch, there should be a Warning message in the HA logs saying it is not a 100% match, and listing the DPs received then. But tuya-cli is more convenient for experimenting with different settings to try to figure out what each DP means.

**Comment by nickdos** [comment]
OFF:
```{ '1': false, '2': 'normal', '3': 5, '5': false, '22': 'cancel' }```
ON:
```{ '1': true, '2': 'normal', '3': 9, '5': false, '22': 'cancel' }```
`1` is on/off
`2` is mode
`3` is speed
not sure of others

**Comment by make-all** [comment]
This issue should be fixed in 0.13.0.  I was using STATE_UNAVAILABLE as a return value to indicate an offline device, but that is converted to True by the code that expects a boolean return value. Instead I have changed to None, which should get interpreted as False by any code blindly using it, while still providing a distinction between an actual False for code that cares.
