### ISSUE TITLE
Hydrotherm X8 Heat Pump Hot Water Wrong Temperature 

### ISSUE THREAD

**Issue by curik8** [make-all/tuya-local#663]
Hi! Big thanks for your tuya local integration! Finally got my Hydrotherm X8 hot water system connected locally to Hass. However I noticed that the temperature will only show up to 50 deg instead of 70 deg. Is there a way to fix this issue, say by modifying the instruction set on Tuya's dev platform?

{
  "result": {
    "category": "qn",
    "functions": [
      {
        "code": "switch",
        "desc": "{}",
        "name": "开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "desc": "{\"unit\":\"℃\",\"min\":15,\"max\":75,\"scale\":0,\"step\":1}",
        "name": "目标温度",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":15,\"max\":75,\"scale\":0,\"step\":1}"
      },
      {
        "code": "mode",
        "desc": "{\"range\":[\"STANDARD\",\"ECO\",\"HYBRID\",\"HYBRID1\",\"ELEMENT\"]}",
        "name": "工作模式",
        "type": "Enum",
        "values": "{\"range\":[\"STANDARD\",\"ECO\",\"HYBRID\",\"HYBRID1\",\"ELEMENT\"]}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "name": "开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "name": "目标温度",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":15,\"max\":75,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_current",
        "name": "当前温度",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-20,\"**max\":50,**\"scale\":0,\"step\":1}"
      },
      {
        "code": "mode",
        "name": "工作模式",
        "type": "Enum",
        "values": "{\"range\":[\"STANDARD\",\"ECO\",\"HYBRID\",\"HYBRID1\",\"ELEMENT\"]}"
      },
      {
        "code": "fault",
        "name": "故障告警",
        "type": "Bitmap",
        "values": "{\"label\":[\"fault_bit0\",\"fault_bit1\",\"fault_bit2\",\"fault_bit3\",\"fault_bit4\",\"fault_bit5\",\"fault_bit6\",\"fault_bit7\",\"fault_bit8\",\"fault_bit9\",\"fault_bit10\",\"fault_bit11\",\"fault_bit12\",\"fault_bit13\",\"fault_bit14\",\"fault_bit15\",\"fault_bit16\",\"fault_bit17\",\"fault_bit18\",\"fault_bit19\",\"fault_bit20\",\"fault_bit21\",\"fault_bit22\",\"fault_bit23\",\"fault_bit24\",\"fault_bit25\",\"fault_bit26\",\"fault_bit27\",\"fault_bit28\",\"fault_bit29\"],\"maxlen\":30}"
      }
    ]
  },
  "success": true,
  "t": 1682831128969,
  "tid": "a0124b4de71411ed9b43a28304c1a187"
}

**Comment by make-all** [comment]
Based on the comments on #251, this is not a bug in the integration, the devices really are reporting a current temperature of 50.
