### ISSUE TITLE
Pioneer Diamante Ultra Mini-Split is read-only, cannot be controlled

### ISSUE THREAD

**Issue by curiouscrusher** [make-all/tuya-local#664]
# Log Message

```
No logs or errors for tuya-local in HA are present
```

# Information about DPS mappings

```
{
  "result": {
    "category": "kt",
    "functions": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":160,\"max\":880,\"scale\":1,\"step\":5}"
      },
      {
        "code": "mode",
        "type": "Enum",
        "values": "{\"range\":[\"cold\",\"hot\",\"wet\",\"wind\",\"auto\"]}"
      },
      {
        "code": "temp_set_f",
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":61,\"max\":88,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":160,\"max\":880,\"scale\":1,\"step\":5}"
      },
      {
        "code": "temp_current",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-20,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "mode",
        "type": "Enum",
        "values": "{\"range\":[\"cold\",\"hot\",\"wet\",\"wind\",\"auto\"]}"
      },
      {
        "code": "humidity_current",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_set_f",
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":61,\"max\":88,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1682871310634,
  "tid": "2e36f016e77211ed9e189607f7cda52d"
}
```

# Product ID

```
product_id: ibmmirhhq62mmf1g
```

# Information about how the device functions

The device is a [Pioneer Diamante Ultra 12K BTU Mini-Split AC Unit](https://www.pioneerminisplit.com/collections/wyt/products/pioneer-diamante-ultra-12-000-btu-230v-ductless-mini-split-inverter-wifi-enabled-air-conditioner-heat-pump-full-set-with-16-ft-kit?_pos=7&_fid=53e4e979b&_ss=c)

Currently the device sets up without issue and all values from the unit are _read_ by tuya-local, however no updates can be made via the integration. If you attempt to change a setting via tuya-local in Home Assistant it will show up in the logbook and then after ~30 seconds it will show a change back to the previous setting. 

No errors appear in the Home Assistant log, it just seems like nothing is happening when you attempt to change settings on the unit via tuya-local.

I'll be happy to provide any additional info needed to help with troubleshooting, I filled out the details here as best as possible. Would love to see this device working via the integration as I've come across numerous requests for it's functionality while troubleshooting the connection to HA.

# Screenshots

_Device settings all appear correctly with relevant settings showing the correct values_
<img width="1252" alt="Screen Shot 2023-04-30 at 11 24 22 AM" src="https://user-images.githubusercontent.com/4745854/235364407-5f9eb5a2-6499-404d-8e90-202f7f939720.png">

_Device card shows all values properly and updates whenever settings are changed via infrared remote or Smart Life Tuya App._
<img width="569" alt="Screen Shot 2023-04-30 at 11 24 04 AM" src="https://user-images.githubusercontent.com/4745854/235364409-a05440e5-69c2-41cd-bf76-9aba67903949.png">

**Comment by make-all** [comment]
This looks the same as #338.  There are a number of suggestions in the comments and other linked issues which are now closed.  None of them worked for that user, so there is no guarantee they will help here.  From memory, an incorrect local key can cause this on protocol version 3.1 devices, as on those the key is only used for sending commands, the device gives its state data in the clear.

**Comment by make-all** [comment]
Assumed fixed due to no feedback
