### ISSUE TITLE
Stirling FAN support request

### ISSUE THREAD

**Issue by nickdos** [make-all/tuya-local#67]
Make: Sterling
Model: FS1-40DCWIFI 
Info: https://stirlingappliances.com.au/stirling_products/fan-pesdestal-dc-motor-fs1-40dc/

| DPs | Function | values |
| --- | ---------- | ------ |
| 1 | power |  `true`\|`false` |
| 2 | mode |  `normal`\|`nature`\|`sleep` |
| 3 | speed |  `1-15` |
| 5 | oscillator (rotation) |  `true`\|`false` |
| 22 | sleep function |  `false`\|`0_5`\|`1_0`\|`2_0` etc. |

**Comment by make-all** [comment]
The values reported for dps 22 seem to use "cancel" rather than false.  Is that correct?

**Comment by EthanBezz** [comment]
> The values reported for dps 22 seem to use "cancel" rather than false. Is that correct?

I'm not OP but I also own this exact fan and yes, that is correct. dps 22 will report "cancel" when there is no sleep timer set.

The fan can set a sleep timer for up to 10 hours and with half hour intervals, so from `0_5` to `10_0`

**Comment by nickdos** [comment]
Yes, "cancel" is correct. That was a copy and paste error on my part, apologies.

**Comment by make-all** [comment]
Support is added in 0.13.0 based on the information above.

**Comment by nickdos** [comment]
Just tried this and although it imports a device, there are no entities created.

I deleted the old device and imported from scratch. The first odd thing was an option that had no "label" next to it:

<img width="510" alt="image" src="https://user-images.githubusercontent.com/532845/140631140-d01de9cf-5ce1-494f-896b-864518fd2533.png">

The integration appears as:

<img width="296" alt="image" src="https://user-images.githubusercontent.com/532845/140631153-7973bf47-4946-47fb-b984-8a4003655e86.png">

Note, no entities shown. Same viewing the detailed version:

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/532845/140631171-1217111e-c1e3-48a9-ad0c-26e3030f1b6d.png">

Found the following errors in my logs:

```
Logger: homeassistant.components.fan
Source: custom_components/tuya_local/helpers/mixin.py:49 
Integration: Fan (documentation, issues) 
First occurred: 2:13:43 PM (2 occurrences) 
Last logged: 2:13:43 PM

Error adding entities for domain fan with platform tuya_local
Error while setting up tuya_local platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 523, in _async_add_entity
    entity_category=entity.entity_category,
  File "/config/custom_components/tuya_local/helpers/mixin.py", line 49, in entity_category
    return self._config.entity_category
AttributeError: 'TuyaEntityConfig' object has no attribute 'entity_category'
```

**Comment by make-all** [comment]
Did you restart Home Assistant after the install?

It seems like it is using some old copies of the files.  Latest version of TuyaEntityConfig does have that attribute.

**Comment by nickdos** [comment]
Thanks for the suggestions. I did the HA `2021.11.1` upgrade after installing the update from HACS (2 birds with 1 stone, I thought as restart is required). HACS was not showing the usual message about requiring a restart when I checked just now. 

Just did a manual restart now and entities have appeared now and all functions are working 🎉.
