### ISSUE TITLE
Cannot add Tuya curtains / loonas_curtain

### ISSUE THREAD

**Issue by Andrius-Al** [make-all/tuya-local#671]
**Describe the bug**
Cannot add Tuya curtains (device is loonas_curtain), after entering all details Im getting "Sorry, there is no support for this device."

**To Reproduce**
Install tuya-local later version from repository.
Add integration, and in configuration page enter correct details:
 - device_id: [my device ID from iot.tuya]
 - device IP: [my local IP of curtain motor that is pingable]
 - local key: [device's key from iot.tuya]

**Expected behavior**
Device recognized and added into HA

**Additional context**
A) device details from iot.tuya. Note that product_id matches loonas_curtain 
{
  "result": {
    "active_time": 1680357196,
    "category": "cl",
    "category_name": "Curtain",
    "create_time": 1680357196,
    "gateway_id": "",
    "icon": "smart/icon/ay1513046654908xshtz/c7188920b20c257c673caa7a8d059808.png",
    "id": [HIDDEN],
    "ip": "[HIDDEN]",
    "lat": "54.6100",
    "local_key": "[HIDDEN]",
    "lon": "24.9200",
    "model": "",
    "name": "curtains",
    "online": true,
    "owner_id": "152641179",
    "product_id": "wraaecjqfiirj8go",
    "product_name": "Curtain Motor",
    "sub": false,
    "time_zone": "+03:00",
    "update_time": 1680537104,
    "uuid": "[HIDDEN]"
  },
B) DPS IDs in iot.tuya also mathes ones in yaml file

Control = 1
Curtain Position Setting = 2
Current Curtain Position = 3
Motion Direction = 5
Fault = 12

Assistant log (Settings / System / Logs):
Device matches None with quality of 0%. DPS: {"updated_at": 1683145132.0017009, "2": 0, "3": 100, "5": "forward"}

![image](https://user-images.githubusercontent.com/114024821/236041824-f807eef7-011c-420b-9499-4e8de1cfc8a6.png)
![image](https://user-images.githubusercontent.com/114024821/236042323-ad1625b7-ec62-4ab3-a8db-06c6e625d72f.png)

**Comment by make-all** [comment]
It appears from the log that the "control" dp needs to be optional.

**Comment by Andrius-Al** [comment]
Worked:
![image](https://user-images.githubusercontent.com/114024821/236122980-4ceb128d-c4ab-4c5b-8706-a183ba9b2cda.png)
