### ISSUE TITLE
neo_coolcam_Siren_NAS-AB02W

### ISSUE THREAD

**Issue by epajfl00** [make-all/tuya-local#673]
### Log Message
None

### Information about DPS mappings
{
  "result": {
    "category": "wsdcg",
    "functions": [
      {
        "code": "switch",
        "dp_id": 104,
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "va_temperature",
        "dp_id": 105,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-200,\"max\":500,\"scale\":1,\"step\":1}"
      },
      {
        "code": "va_humidity",
        "dp_id": 106,
        "type": "Integer",
        "values": "{\"unit\":\"%RH\",\"min\":1,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch",
        "dp_id": 104,
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1681712333048,
  "tid": "b9bdf30edce711edb8e99ee79c9add90"

### Product ID
016458803c6105eb73a8

### Information about how the device functions:
This is a Tuya siren with temperature and humidity sensor. 
Runs on USB and two CR123A batteries as backup.

    dpId 101 - power type (1 - battery high; 2 - medium; 3 - low; 4 - usb port)
    dpId 102 - alarm type chime sound (0-17)
        0 - doorbell
        1 - fur elise
        2 - big ben
        3 - ring ring
        4 - lone ranger
        5 - turkish march
        6 - high pitched
        7 - red alert
        8 - crickets
        9 - beep
        10 - dog bark
        11 - police siren
        12 - grandfather clock
        13 - phone ring
        14 - fire truck
        15 - clock chime
        16 - alarm clock
        17 - school bell
    dpId 103 - alarm duration time (in seconds)
    dpId 104 - alarm control
    dpId 105 - temp in C (divide by 10)
    dpId 106 - humidity
    dpId 107 - minimum temperature to trigger alarm
    dpId 108 - maximum temperature to trigger alarm
    dpId 109 - minimum humidity to trigger alarm
    dpId 110 - maximum humidity to trigger alarm
    dpId 112 - unit change (on = C, off = F) - does not affect dpid 105 values
    dpId 113 - temperature alarm control (0 = off, 1 = on)
    dpId 114 - humidity alarm control (0 = off, 1 = on)
    dpId 116 - alarm volume (0 = high, 1 = medium, 2 = low)

Also see, 
https://templates.blakadder.com/neo_coolcam_NAS-AB02W.html
Blakadder flashed this item with Tasmota.
Other details for interest
https://www.aliexpress.com/item/33042023659.html

**Comment by epajfl00** [comment]
Hi Jason,
Thanks for this device addition, much appreciated.
I've updated to the latest release 2023.6.1 to test the device, looks good.
However, the controls are not fully functional, the switch turns on a tone for about for 1 sec audibly, 
even-though the timer is 60 sec. 
There are no controls to select the tone, duration, or volume.
Can you please re-look at this again, thanks.
![image](https://github.com/make-all/tuya-local/assets/86779948/27c2d152-c399-48f6-9365-75d38a38e36e)

Also, see diagnostic report, this may help.

[tuya_local-9eae520c694af062a3b722f82799d406-Neo Coolcam siren-f4fa2d39c5c7f3794a5c9fe709da30a6.json.txt](https://github.com/make-all/tuya-local/files/11827454/tuya_local-9eae520c694af062a3b722f82799d406-Neo.Coolcam.siren-f4fa2d39c5c7f3794a5c9fe709da30a6.json.txt)

**Comment by make-all** [comment]
See the siren documentation here: https://www.home-assistant.io/integrations/siren/

**Comment by epajfl00** [comment]
Hi Jason,
I do understand that the siren call services can be used, but I don't understand why we can't have both in the device UI and the call services for automation. Via the Tuya App obviously you can control the volume, tone and duration, even via LocalTuya you can do this and still have call service capability. So both is the preferred way.

Anyway, I've tried the call service to turn on siren with the three parameters (see below), however, can not set the tone to use (not mapped), changing the volume makes no difference (0-1) to the level, changing the duration still only produces about 1 sec on tone, regardless of actual setting value.

![image](https://github.com/make-all/tuya-local/assets/86779948/4cb9cbe3-311e-4eb6-94ae-4e733f66888d)

**Comment by epajfl00** [comment]
Hi,
Just noticed this too,
The temperature threshold values, both lower and higher setting, show 1.5 and 3.0, instead of 15 and 30, 
so need a multiplier of x10.
Why is the humidity threshold setting different to the temperature threshold, one uses a line to set and the other uses an input box, is it possible to have the same method to set for both?


![image](https://github.com/make-all/tuya-local/assets/86779948/1ceea06c-4b4c-4312-9ad4-3d34929acd24)

**Comment by make-all** [comment]
Because the Tuya documentation provided was very limited, and no logs were provided, the ranges for some of the fields may be incorrect as they had to be guessed based on others.  I will remove the scaling from the high/low temperature thresholds, as they are apparently not scaled the same as the temperature sensor as assumed.

If you have issues with the limited siren UI, then the HA frontend project is the place to suggest improvements.  This project does not determine the UI, only implements entities.

Number entities can be set to have either representation, but have some logic to pick a default depending on the range of values selectable.

**Comment by epajfl00** [comment]
Thanks, I've done some tinkering with the code and have it almost fully working.
The values set in the app are now updated in HA states values (see pic below).
Even the call service now works (see pic below), I can set the duration and the tone (manually, I was expecting a menu to select from) to use and that works great. 
However, the volume level of 0.3, 0.7 or 1 do not seen to change anything, what ever level is on the app is the level that is used. So something is not quite right for the tone level. 
Any ideas?

Also when using the switch to turn on alarm for the Tuyalocal siren device, I still only get a single tone for less than a sec and the tone state is shown as "none", so that is part of the problem, instead of using the app tone setting or even the last used tone
So "none" is also part of a problem, otherwise what is the point the switch.

The YAML file that I modified/fixed is attached.
Also fixed the Temperature alarm settings that I reported previously.

[neo_coolcam_siren_v2.txt](https://github.com/make-all/tuya-local/files/11859011/neo_coolcam_siren_v2.txt)

![image](https://github.com/make-all/tuya-local/assets/86779948/2d889cc0-0e69-4dc5-bb99-f20db0bb3a31)
![image](https://github.com/make-all/tuya-local/assets/86779948/757343e0-f8f2-4b34-9ca4-19e71cf730b8)

**Comment by epajfl00** [comment]
I was just visiting the TUYA development site for API Explorer, and see that usual way to get dpid's is gone, but another way is available (even though messy looking) with "Device Control - Query Things Data Model". 
The function seems to provide more information, so thought to provide it since it may help further.
I see that Enum is used, rather than String or Integer. Is there a reason, other than HA expects Integer or String for the Siren controls.

[Siren DC-QTDM.txt](https://github.com/make-all/tuya-local/files/11878342/Siren.DC-QTDM.txt)

**Comment by epajfl00** [comment]
Letting you know that the change you made to Siren.py fixed the tone level sending through the service call, excellent and thanks.
Even thought the device siren switch still does a momentary tone only, so not sure if anything can be done here.

Since I had more information now from "Device Control - Query Things Data Model", I took the opportunity to 
add an extra option to dp:101 (added "0" to reflect battery at full charge ie. 100%)
Also added dp:115 Alarm status (0 - 4)
How can word value options be used instead of just numbers, I've tried, but didn't work, 0 = "xyz", 1 = "abc", etcc... more meaningful ??

See my latest change to YAML file
[neo_coolcam_siren_v2.txt](https://github.com/make-all/tuya-local/files/11902098/neo_coolcam_siren_v2.txt)

A curiosity question, what controls the order of entities on the TUYAlocal device page?
Obviously, the YAML order is not used.

**Comment by make-all** [comment]
Thank you, I will take a look at these changes when I get time.  For the word options, you just need to use words instead of numbers, but the sensor must either be of class enum or no class (if you do not know all the values - enum will throw an error if it gets an unknown value, all other device classes expect numeric values), and the dp not be marked as class: measurement or any other state class.

**Comment by epajfl00** [comment]
Thanks for the information requested.
I've tried class: enum for dp: 115, and that worked well, however, I tried the same for dp: 101, but that did not work, not sure if this was because dp: 101 is used twice, once as a sensor and the second as a binary sensor.

Concerning the listing order, yes you are right, alphabetically, I've added numbers in front and can now control the order.
![image](https://github.com/make-all/tuya-local/assets/86779948/83bff156-b881-4f28-9b74-3b2415412306)

Anyway, attached is the updated file again.
[neo_coolcam_siren_v2.txt](https://github.com/make-all/tuya-local/files/11914357/neo_coolcam_siren_v2.txt)

**Comment by epajfl00** [comment]
Is there anything you can do in the Siren.py or yaml file to set default value?
according to your readme.md, the DEFAULT option is available and is used especially for a Siren entity, as follows;

**Default set to true allows an attribute to be set as the default value. This is used by some entities when an argument is not provided to a service call but the attribute is required to be set to function correctly. An example is the siren entity which uses the tone attribute to turn on and off the siren, but when turn_on is called without any argument, it needs to pick a default tone to use to turn on the siren.**

I've tried various ways to use "Default" for the primary entity values for switch, tone, level, and duration, but nothing seems to work, totally ignored. Maybe I'm not using it correctly, how and where in the YAML should it be used, can you provide an example, so I can try again?

When siren switch is "on" defaults are not set, but do have values, however, tone = none. 
![image](https://github.com/make-all/tuya-local/assets/86779948/6092ff36-7124-43d2-89d8-5c63b2e112a3)
When siren switch is "off" defaults are not set, but do have values, however, tone=null. 
![image](https://github.com/make-all/tuya-local/assets/86779948/d92674b6-5a09-435a-b4a0-df4813a6027e)

**Comment by make-all** [comment]
If you want the device to retain the previously set values, I think it is better to not set any defaults, as the defaults would override whatever was previously set.

**Comment by epajfl00** [comment]
Hi Jason,
No, I'm not expecting to have the previously set value to be used. As is done in TUYA, each "dp-id" has a default value set, so that if no parameter value is set, the function still works, at least this how I understand it. If the service call is used, then the specific wanted values will be used.

As documented, the siren entity uses the tone attribute to turn on and off the siren, but when turn_on is called without any argument, it needs to pick a default tone to use, to turn on the siren, otherwise it will be none or null as shown.

Does the default parameter actually work for siren? Has it been used in any yaml file?
How and where should it be used, so I can try it? I have tried, but nothing has worked so far.
For example, can you show for these id:103 and id:116 where and the syntax of default to use? 
    - id: 103
      type: integer
      name: duration
      unit: s
      range:
        min: 0
        max: 1800
    - id: 116
      type: string
      name: volume_level
      mapping:
        - dps_val: "0"
          value: 1.0
        - dps_val: "1"
          value: 0.7
        - dps_val: "2"
          value: 0.3

**Comment by make-all** [comment]
This device has a separate turn on/off dp for the siren, so does not need the tone to be sent to turn on/off.  Since the device is reporting its previous tone/volume/duration I would expect those to be used if there is none sent with the turn on command.

**Comment by epajfl00** [comment]
Hi Jason,
Using the call service of turn_on, works fine, uses all 3 chosen parameters.
I would still like to have the device switch working to use default parameters or even the last used would be fine.
I managed to work out how to use the default option, by looking at the orion_outdoor_siren.yaml.
I've tried to use it in the same manner, but nothing, no effect at all. So I'm still not sure if default works at all.

I've changed dp-id:101 to use class: enum, with added text.
I've also changed the names of the thresholds, so correct grouping will occur.
attached file:
[neo_coolcam_siren.txt](https://github.com/make-all/tuya-local/files/12024263/neo_coolcam_siren.txt)

**Comment by epajfl00** [comment]
Hi,
I see that you have closed this, without at least incorporating the changes I provided. This means that every time you provide an update, I have to override your file with mine, this seems pointless, can you incorporate the changes provided, thanks.
[neo_coolcam_siren.txt](https://github.com/make-all/tuya-local/files/12208492/neo_coolcam_siren.txt)

Also, I've recently noticed that there is a bug with the Temperature unit, changing from C to F has no effect on the temperature values nor the units used.
![image](https://github.com/make-all/tuya-local/assets/86779948/c47c5f42-586c-4bac-a7cc-08657152e271)
Is there anything to fix this, for me personally, It is not important, since I only use C, but for someone else it may be an issue.

**Comment by make-all** [comment]
There are no significant changes in your config, other than naming, changing the battery sensor from battery class to enum class, and unnecessarily marking one of the tones as default.  The temperature units are already marked as "Temperature display units" in the installed config, to make it clearer that they do not affect the values reported by the device as the original report noted.
