### ISSUE TITLE
Arlec SmartPlug with In Socket Power Monitoring (PC191HA)

### ISSUE THREAD

**Issue by epajfl00** [make-all/tuya-local#674]
### Log Message
None

Information about DPS mappings

{
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "switch_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "dp_id": 38,
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "add_ele",
        "dp_id": 17,
        "type": "Integer",
        "values": "{\"unit\":\"kW·h\",\"min\":0,\"max\":50000,\"scale\":3,\"step\":100}"
      },
      {
        "code": "cur_current",
        "dp_id": 18,
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_power",
        "dp_id": 19,
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":0,\"max\":80000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "cur_voltage",
        "dp_id": 20,
        "type": "Integer",
        "values": "{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "relay_status",
        "dp_id": 38,
        "type": "Enum",
        "values": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}"
      }
    ]
  },
  "success": true,
  "t": 1681711795129,
  "tid": "791c16ecdce611edb8e99ee79c9add90"
}

### Product ID
bf819f3f0e0f958b17ufid

### Information about how the device functions: 
Arlec SmartPlug with In Socket Power Monitoring (PC191HA)
Other dpid's that are available

dpid 21		Test Bit
dpid 22		Voltage coe
dpid 23		Current coe
dpid 24		Power coe
dpid 25		Electricity coe
dpid 26		Fault

**Comment by make-all** [comment]
Config smartplugv2_energy already exists with this dps layout.

**Comment by epajfl00** [comment]
smartplugv2_energy contains extra dpid, that PH191HA does not have, such as,
id 46, 41, 42
Do extras matter, or just ignored?

**Comment by make-all** [comment]
If they are marked as optional, they are just ignored

**Comment by epajfl00** [comment]
How do you know if they are optional?
especially if dpid 41 and 42 are listed as part of the primary entity, but not required.
I'm just wanting to understand, thanks.

**Comment by make-all** [comment]
They are optional because not all devices have them.
