### ISSUE TITLE
Request Support for Minco Heat MH-1823D

### ISSUE THREAD

**Issue by pascaltippelt** [make-all/tuya-local#68]
Hi!

I would really like to use my Minco Heat MH-1823D in Home Assistant. The MH-1823D is a thermostat for electric floor heating.

The following dps are available:

```
tuya-cli get --id CENSORED --key CENSORED --full
{ dps:
   { '1': true,
     '2': 'program',
     '3': 'stop',
     '5': false,
     '9': true,
     '12': false,
     '18': 'out',
     '19': 'c',
     '22': 18,
     '23': 64,
     '32': 1,
     '33': 205,
     '35': 0,
     '37': 689,
     '39': '7',
     '45': 0,
     '101': 200,
     '102': 680,
     '103': 0,
     '104': 2,
     '105': 'no_power',
     '106': 35,
     '107': 95 } }
```

Some are already decoded, wich should be enough for a basic support:

```
1   --> ???
2   --> ???
3   --> state of the heating (start / stop) + set the heating
5   --> ???
9   --> frost-blocker (true/false)
12  -->
18  --> use internal or external sensor (in/out)
19  --> temperature unit (c/f)
22  --> target temperature
23  -->
32  -->
33  --> current sensor temperature (*0.1) eg 211 is 21.1 °C
35  -->
37  -->
39  -->
45  -->
101 -->
102 -->
103 -->
104 --> temperature hysteresis
105 -->
106 --> maximal temperature
107 -->
```

If you need anything else, please ask.

Best regards

Pascal

**Comment by make-all** [comment]
I have made some guesses at some of the other values.

```
1   --> power
2   --> (program/manual)???
3   --> state of the heating (start / stop) + set the heating
5   --> 
9   --> frost-blocker (true/false)
12  -->
18  --> use internal or external sensor (in/out)
19  --> temperature unit (c/f)
22  --> target temperature C
23  --> target temperature F
32  -->
33  --> current internal??? sensor temperature C (*0.1) eg 211 is 21.1 °C
35  -->
37  --> current internal??? sensor temperature F (*0.1)
39  --> schedule (7/6_1/5_2)???
45  -->
101 --> current external??? sensor temperature C (*0.1)
102 --> current external??? sensor temperature F (*0.1)
103 -->
104 --> temperature hysteresis
105 -->
106 --> maximum temperature C
107 --> maximum temperature F
```

What do you mean "+ set the heating" on dp 2?  Can this also be set, not just read to indicate the current state?
If you set it, does dp 2 change from 'program' to something else like 'manual' or 'override'?

The webpage mentions a child lock, and it shows in the Tuya App screenshot so must be one of the false values, I think (dp 5 or 12).

**Comment by make-all** [comment]
I think dp 2 may be similar to a feature on Beca BHP-6000 thermostat, which has values for Schedule (program), Temporary Hold, Permanent Hold and Holiday Hold.  The Aliexpress page selling this model also mentions a Holiday feature, so it may be the same 4 modes, I think.

**Comment by pascaltippelt** [comment]
I tinkered a bit around and could verify some of your guesses and added some new information. Hope this helps.

```
1   --> power --> correct
2   --> (program/manual) --> correct
3   --> state of the heating (start / stop) + set the heating --> correct
5   --> 
9   --> frost-blocker (true/false) --> correct.
12  -->
18  --> use internal or external sensor (in/out) --> correct
19  --> temperature unit (c/f) --> correct
22  --> target temperature C --> correct
23  --> target temperature F --> NOT CORRECT. Did not figure out what it is.
32  -->
33  --> current internal sensor temperature C (*0.1) eg 211 is 21.1 °C -->correct
35  --> Internal sensor calibration (-9 ... +9)
37  --> current internal sensor temperature F (*0.1) --> correct
39  --> schedule (7/6_1/5_2) --> correct
45  --> 
101 --> current external sensor temperature C (*0.1) --> correct
102 --> current external sensor temperature F (*0.1) --> correct
103 --> External sensor calibration (-9 ... +9)
104 --> temperature hysteresis --> correct
105 -->
106 --> maximum temperature C --> correct
107 --> maximum temperature F --> correct

```

**Comment by make-all** [comment]
23 definitely seemed to convert to the target temperature in F in the first set of values you sent.  But I guess they could swap when the units are set to f so that the temperature is always set through dp 22?

**Comment by pascaltippelt** [comment]
This time it's 20°C and 64. But 20°C is 68°F.
```
{
  dps: {
    '1': true,
    '2': 'holiday',
    '3': 'stop',
    '5': false,
    '9': true,
    '12': false,
    '18': 'out',
    '19': 'c',
    '22': 20,
    '23': 64,
    '32': 1,
    '33': 193,
    '35': 0,
    '37': 667,
    '39': '7',
    '45': 0,
    '101': 194,
    '102': 669,
    '103': 0,
    '104': 2,
    '105': 'no_power',
    '106': 35,
    '107': 95
  }
}
```

**Comment by make-all** [comment]
OK, I'll switch that to an unknown, and try to handle C/F switching on dp 22 instead.

**Comment by pascaltippelt** [comment]
Give me a second, I set the device to F and recheck!

**Comment by pascaltippelt** [comment]
Funny, now it fits... Maybe the F value is not always updated.

```
{
  dps: {
    '1': true,
    '2': 'holiday',
    '3': 'stop',
    '5': false,
    '9': true,
    '12': false,
    '18': 'out',
    '19': 'f',
    '22': 20,
    '23': 68,
    '32': 1,
    '33': 193,
    '35': 0,
    '37': 667,
    '39': '7',
    '45': 0,
    '101': 193,
    '102': 667,
    '103': 0,
    '104': 2,
    '105': 'no_power',
    '106': 20,
    '107': 95
  }
}
```

**Comment by make-all** [comment]
Either dp 5 or 12 should be a child lock.  I think there is a way to activate the child lock from the panel which you could use to check.

**Comment by pascaltippelt** [comment]
5 is **true** if _locked_ and **false** if _unlocked_

I did not find anything that changes 7 until now...

**Comment by pascaltippelt** [comment]
I can confirm the detection and it is working fine.

I have a questing tho: My setup is in german. Where does the "program"-String come from?
![grafik](https://user-images.githubusercontent.com/2066297/141681672-3210d7b1-2e5b-4c91-a381-040248fc91e5.png)

Is that provided by you or home assistant? The correct translation would be "Programm".

**Comment by make-all** [comment]
The preset modes are from the device config, I used the same names as the Tuya protocol.  I do not think HA translates them even if I use the predefined ones from the climate component.

**Comment by pascaltippelt** [comment]
Thank you, now I understand.

As my thermostat works very well now, I have to thank you for your work. I really appreciate your engagement.
