### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by make-all** [make-all/tuya-local#682]
Home Assistant has added the ability for integrations to provide device specific translations, for use in the main HA UI.  Previously only the config flow dialogs were translated.

https://developers.home-assistant.io/blog/2023/03/27/entity_name_translations

- multiple devices should share translation_key to minimise translations needed
- where possible, translation keys from HA standard components should be referenced so that translations are inherited from a much larger pool of translators.

Currently we have translations for Bulgarian, English, Spanish, Hungarian, Italian, Brazilian Portuguese and Ukrainian.  When more translations are available, the original contributors of these translations should be given a heads up so they can provide the new translations before a release if possible.

**Comment by ssorgatem** [comment]
How do we go about providing a new translation?
I can do it for Catalan

**Comment by make-all** [comment]
The translation files are in custom_components/tuya_local/translations, named with the ISO 2-letter language code, and optional variant suffix (as in case of pt-BR).  The "master" file will be en.json, but if you prefer to start with es.json, you can do that and just cross-check at the end to see if anything was missed.

Currently only the config dialogs are translated, but that will change as this issue is worked on.
