### ISSUE TITLE
HCT-611 WiFi Water Timer 

### ISSUE THREAD

**Issue by spanzetta** [make-all/tuya-local#685]
I tried to configure my water timer that you just added as supported with 2023.5.0 ( #638) but is not detected..
What can be wrong?
Can you guide me to provide any relevant logs that can be usefully for you to understand why it doesn't work?
Thanks

![immagine](https://user-images.githubusercontent.com/49818743/236693589-4e63a1d9-f347-4840-9513-1bee28dfa598.png)

**Comment by make-all** [comment]
See discussion #522

**Comment by spanzetta** [comment]
Hi, since there are many different case discussed there.. is there a way to "identify" exactly the issue by seeing at logs?
If you guide me how to collect the right log for you.. I will do..
I don't want to go by temptatives..
Thanks

> See discussion #522

**Comment by spanzetta** [comment]
@make-all 
Any suggestions?
