### ISSUE TITLE
ASIP-0622 Smart Indoor Planter

### ISSUE THREAD

**Issue by epajfl00** [make-all/tuya-local#687]
### Log Message
None

### Information about DPS mappings

{
  "result": {
    "category": "sz",
    "functions": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "pump",
        "dp_id": 2,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "light",
        "dp_id": 3,
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "pump",
        "dp_id": 2,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "light",
        "dp_id": 3,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_current",
        "dp_id": 6,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-30,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "humidity_current",
        "dp_id": 7,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1681712191187,
  "tid": "652c6ce4dce711eda5263aeadf44bc9a"
### Product ID
bfec529288fa08ae833zsz

### Information about how the device functions: 
ASIP-0622 Smart Indoor Planter
Attached is the user manual for the device.
[asip0622.pdf](https://github.com/make-all/tuya-local/files/11418382/asip0622.pdf)

There are many other dpid's see below;
### Data that I used for LocalTuya:
"bfec529288fa08ae833zsz": {
  "friendly_name": "ASIP-0622 Smart Indoor Planter",
  "host": "192.168.0.xxx",
  "local_key": "xxxxxxxxxxxxxxx",
  "protocol_version": "3.3",
  "entities": [
    {
      "friendly_name": "Power Switch",
      "restore_on_reconnect": false,
      "id": 1,
      "platform": "switch"
    },
    {
      "friendly_name": "Water Pump",
      "restore_on_reconnect": false,
      "id": 2,
      "platform": "switch"
    },
    {
      "friendly_name": "Power Indicator Green LED ",
      "restore_on_reconnect": false,
      "id": 3,
      "platform": "switch"
    },
    {
      "friendly_name": "Grow LED Light",
      "restore_on_reconnect": false,
      "id": 123,
      "platform": "switch"
    },
    {
      "friendly_name": "Current Fertility",
      "unit_of_measurement": "us/cm",
      "device_class": "aqi",
      "id": 102,
      "platform": "sensor"
    },
    {
      "friendly_name": "Current Illumination",
      "unit_of_measurement": "Lux",
      "device_class": "illuminance",
      "id": 108,
      "platform": "sensor"
    },
    {
      "friendly_name": "Water counter",
      "min_value": 1.0,
      "max_value": 10.0,
      "step_size": 1.0,
      "restore_on_reconnect": false,
      "id": 104,
      "platform": "number"
    },
    {
      "friendly_name": "Current Temperature",
      "unit_of_measurement": "C",
      "device_class": "temperature",
      "id": 6,
      "platform": "sensor"
    },
    {
      "friendly_name": "Current Humidity",
      "unit_of_measurement": "%",
      "device_class": "humidity",
      "id": 7,
      "platform": "sensor"
    },
    {
      "friendly_name": "Lighting Mode",
      "select_options": "0;1",
      "select_options_friendly": "Automatic;Manual",
      "restore_on_reconnect": false,
      "id": 122,
      "platform": "select"
    },
    {
      "friendly_name": "Planted Date",
      "unit_of_measurement": "Date",
      "device_class": "date",
      "id": 114,
      "platform": "sensor"
    },
    {
      "friendly_name": "Today's Date",
      "unit_of_measurement": "Date",
      "device_class": "date",
      "id": 109,
      "platform": "sensor"
    },
    {
      "friendly_name": "Plant Type",
      "device_class": "power",
      "id": 105,
      "platform": "sensor"
    },
    {
      "friendly_name": "Total Daily Light Level",
      "unit_of_measurement": "Lux",
      "device_class": "illuminance",
      "id": 10,
      "platform": "sensor"
    },
    {
      "friendly_name": "No Alarm and Watering at Night",
      "restore_on_reconnect": false,
      "id": 116,
      "platform": "switch"
    },
    {
      "friendly_name": "Temperature Range",
      "min_value": 10.0,
      "max_value": 30.0,
      "step_size": 1.0,
      "restore_on_reconnect": false,
      "id": 117,
      "platform": "number"
    },
    {
      "friendly_name": "Illumination Range",
      "min_value": 1.0,
      "max_value": 8000.0,
      "step_size": 1.0,
      "restore_on_reconnect": false,
      "id": 119,
      "platform": "number"
    },
    {
      "friendly_name": "Fertility Range",
      "min_value": 1.0,
      "max_value": 2000.0,
      "step_size": 1.0,
      "restore_on_reconnect": false,
      "id": 120,
      "platform": "number"
    },
    {
      "friendly_name": "Humidity Range",
      "min_value": 45.0,
      "max_value": 75.0,
      "step_size": 1.0,
      "restore_on_reconnect": false,
      "id": 118,
      "platform": "number"
    },
    {
      "friendly_name": "Watering Mode",
      "select_options": "0;1",
      "select_options_friendly": "Automatic;Manual",
      "restore_on_reconnect": false,
      "id": 101,
      "platform": "select"
    },
    {
      "friendly_name": "Watering Statistics",
      "device_class": "frequency",
      "id": 112,
      "platform": "sensor"
    },
    {
      "friendly_name": "Sufficient Water Available",
      "device_class": "duration",
      "id": 103,
      "platform": "sensor"
    },
    {
      "friendly_name": "Required Plant Lighting",
      "unit_of_measurement": "Lux",
      "device_class": "illuminance",
      "id": 121,
      "platform": "sensor"
    },
    {
      "friendly_name": "Harvest Statistics",
      "device_class": "duration",
      "id": 113,
      "platform": "sensor"
    },
    {
      "friendly_name": "Love Value ??",
      "device_class": "duration",
      "id": 111,
      "platform": "sensor"
    },
    {
      "friendly_name": "Matrix ??",
      "device_class": "duration",
      "id": 110,
      "platform": "sensor"
    }
  ],
  "scan_interval": 30,
  "model": "ASIP-0622 Smart Indoor Planter",
  "device_id": "bfec529288fa08ae833zsz",
  "dps_strings": [
    "1 (value: True)",
    "2 (value: False)",
    "3 (value: True)",
    "6 (value: 19)",
    "7 (value: 50)",
    "10 (value: 1024)",
    "101 (value: 0)",
    "102 (value: 689)",
    "103 (value: 55)",
    "104 (value: 1)",
    "105 (value: 95)",
    "108 (value: 26)",
    "109 (value: 1660126755)",    this is a unix planted date, can it be convered to regular format date?
    "110 (value: 80)",
    "111 (value: 919)",
    "112 (value: 22)",
    "113 (value: 1)",
    "114 (value: 1660098275)",    this is a unix current date, can it be converted to regular format date?
    "116 (value: False)",
    "117 (value: 10,30)",
    "118 (value: 45,75)",
    "119 (value: 1,8000)",
    "120 (value: 0,2000)",
    "121 (value: 11016)",
    "122 (value: 0)",
    "123 (value: False)"
  ],

**Comment by epajfl00** [comment]
Hi,
I've been able to extract other info from the Tuya app, such as the plant types and associated growing conditions, hope this can help further.
[plant matrix.xlsx](https://github.com/make-all/tuya-local/files/11432047/plant.matrix.xlsx)
eg. "105 (value: 95)", 95 corresponds to basil, this plant type dpid ranges from 1 to 132

I can also supply all the plant and app icon's (png pictures that the app uses) there are lots of them if you want them.

**Comment by make-all** [comment]
pngs can't be used, so no point to submit them.

**Comment by epajfl00** [comment]
I was just visiting the TUYA development site for API Explorer, and see that usual way to get dpid's is gone, but another way is available (even though messy looking) with "Device Control - Query Things Data Model". 
The function seems to provide more information, so thought to provide it since it may help further.
All the possible options are provided here, including default values to use.

[Planter DC-QTDM.txt](https://github.com/make-all/tuya-local/files/11878402/Planter.DC-QTDM.txt)

**Comment by make-all** [comment]
Thanks, I actually updated the README for the API Explorer rearrangement last week after someone else pointed out the same thing.
