### ISSUE TITLE
Colored lights lost their color state

### ISSUE THREAD

**Issue by Nikolay-Ch** [make-all/tuya-local#688]
I have 4 smart-bulbs. After upgrade to 2023.4.1 release my bulbs change its mode (white/RGB).

***How to reproduce bug***
I turn it on RGB-mode, then I turn-on-off some times. Bulbs change its mode to warm-white mode.
I have both integration in HA - cloud and local... Cloud integration works normally when I disable local integration.

**Comment by make-all** [comment]
Can you attach your device's diagnostics file?
Settings / Devices & Services / Tuya Local [your device] / 1 device / Download Diagnostics

**Comment by xgustavoh** [comment]
I had the same problem, using a `Smart Bulb RGBCW7` in `version=3.2`.
In my case the bulb always reset to the status it was when Home Assistant was configured.

I noticed that whenever the `status()` function was executed, the bulb suffered a "reset".

After seeing the code, I noticed that the `self.dps_cache` was equal to the value that the bulb was getting after the "reset".

---

Adding this code in `def detect_available_dps(self):` solved my problem.
```python
data["dps"] = {k: None for k in data["dps"]}
```


---

```python
def detect_available_dps(self):
    """Return which datapoints are supported by the device."""
    # device22 devices need a sort of bruteforce querying in order to detect the
    # list of available dps experience shows that the dps available are usually
    # in the ranges [1-25] and [100-110] need to split the bruteforcing in
    # different steps due to request payload limitation (max. length = 255)
    self.dps_cache = {}
    ranges = [(2, 11), (11, 21), (21, 31), (100, 111)]

    for dps_range in ranges:
        # dps 1 must always be sent, otherwise it might fail in case no dps is found
        # in the requested range
        self.dps_to_request = {"1": None}
        self.add_dps_to_request(range(*dps_range))
        try:
            data = self.status()
        except Exception as ex:
            log.exception("Failed to get status: %s", ex)
            raise
        if data is not None and "dps" in data:
            data["dps"] = {k: None for k in data["dps"]}
            self.dps_cache.update(data["dps"])

        if self.dev_type == "default":
            self.dps_to_request = self.dps_cache
            return self.dps_cache
    log.debug("Detected dps: %s", self.dps_cache)
    self.dps_to_request = self.dps_cache
    return self.dps_cache
```

**Comment by make-all** [comment]
Tuya local does not use the detect_available_dps() function.  I did try once, as it seemed like it might work better during the initial device discovery process, but had issues with it, perhaps related to what you are reporting here.

**Comment by xgustavoh** [comment]
tuyalocal uses it indirectly, when the `set_version` function is called with version `3.2` this part of the code is executed:

```python
if version == 3.2: # 3.2 behaves like 3.3 with device22
     self.dev_type="device22"
     if self.dps_to_request == {}:
         self.detect_available_dps()
````

--

Note: I'm still debugging the problem, I just downloaded the code from tuya-local... maybe I'm saying something wrong!
