### ISSUE TITLE
Atomi Smart Fan Unavailable

### ISSUE THREAD

**Issue by mattbruman** [make-all/tuya-local#694]
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**
Atomi Smart Fan is showing as unavailable. I added it using the info from tinyTuya

**To Reproduce**
Steps to reproduce the behavior including the device the issue was observed with:

**Expected behavior**
Being able to control the fan

**Additional context**
[Add any other context about the problem here.](https://github.com/make-all/tuya-local/issues/668)

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

  "integration_manifest": {
    "domain": "tuya_local",
    "name": "Tuya Local",
    "codeowners": [
      "@make-all"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/make-all/tuya-local",
    "integration_type": "device",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/make-all/tuya-local/issues",
    "requirements": [
      "pycryptodome~=3.17",
      "tinytuya==1.12.6"
    ],
    "version": "2022.5.0",
    "is_built_in": false
  },
  "data": {
    "name": "Luke Ceiling Fan",
    "type": "atomi_ceiling_fan",
    "device_id": "**REDACTED**",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": "auto",
    "api_version_set": 3.3,
    "api_version_used": 3.3,
    "api_working": true,
    "status": {},
    "cached_state": {
      "updated_at": 1683570627.4999158
    },
    "pending_state": {},
    "connected": false,
    "force_dps": [],
    "home_assistant": {
      "name": "Luke Ceiling Fan",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "fan.luke_ceiling_fan",
            "state": "unavailable",
            "attributes": {
              "preset_modes": [
                "Natural",
                "Fresh"
              ],
              "friendly_name": "Luke Ceiling Fan",
              "supported_features": 9
            },
            "last_changed": "2023-05-08T18:30:27.337717+00:00",
            "last_updated": "2023-05-08T18:30:27.337717+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": "min",
          "state": {
            "entity_id": "number.luke_ceiling_fan_light_timer",
            "state": "unavailable",
            "attributes": {
              "min": 0.0,
              "max": 1440.0,
              "step": 1.0,
              "mode": "auto",
              "unit_of_measurement": "min",
              "icon": "mdi:timer",
              "friendly_name": "Luke Ceiling Fan Light timer"
            },
            "last_changed": "2023-05-08T18:30:27.338030+00:00",
            "last_updated": "2023-05-08T18:30:27.338030+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": "switch",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.luke_ceiling_fan_do_not_disturb",
            "state": "unavailable",
            "attributes": {
              "device_class": "switch",
              "friendly_name": "Luke Ceiling Fan Do not disturb"
            },
            "last_changed": "2023-05-08T18:30:27.337250+00:00",
            "last_updated": "2023-05-08T18:30:27.337250+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "light.luke_ceiling_fan_light",
            "state": "unavailable",
            "attributes": {
              "min_color_temp_kelvin": 2000,
              "max_color_temp_kelvin": 6535,
              "min_mireds": 153,
              "max_mireds": 500,
              "supported_color_modes": [
                "color_temp"
              ],
              "friendly_name": "Luke Ceiling Fan Light",
              "supported_features": 0
            },
            "last_changed": "2023-05-08T18:30:27.336759+00:00",
            "last_updated": "2023-05-08T18:30:27.336759+00:00"

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

This error originated from a custom integration.

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:199
Integration: Tuya Local (documentation, issues)
First occurred: 2:40:25 PM (9 occurrences)
Last logged: 2:41:23 PM

Failed to refresh device state for Luke Ceiling Fan

**Comment by make-all** [comment]
This isn't really a bug.  Your device seems to be offline.  If you are turning off mains power to it, this will happen.

**Comment by mattbruman** [comment]
Its not offline, its working with the main tuya integration. Screenshot from exact same time. The local version is unavailable but the tuya one is online and I can control it.

![Screenshot 2023-05-09 105405](https://github.com/make-all/tuya-local/assets/43623584/e7d0ff4f-ef0d-481f-9fa8-2d091d480b99)
![Screenshot 2023-05-09 105421](https://github.com/make-all/tuya-local/assets/43623584/75741662-9866-43c0-a908-a27246fd3b87)

**Comment by make-all** [comment]
See #522
