### ISSUE TITLE
Request support for Emmeti Zona Smart Thermostat now Unisenza in UK

### ISSUE THREAD

**Issue by kanthamohan** [make-all/tuya-local#700]
# Log Message

```
* Device matches awow_th213v2_thermostat with quality of 57%. DPS: {"updated_at": 1683746326.6845183, "1": true, "2": 230, "3": 251, "4": "4", "6": false, "12": 0, "101": 0, "102": "0", "103": 0, "104": 1, "105": false, "107": "Apr 2 2022", "108": true, "109": false, "110": false, "111": 0, "112": 235, "113": false, "114": 5, "115": 150, "116": "0"}
* Report this to https://github.com/make-all/tuya-local/issues/
```

# Information about DPS mappings

```
{
  "result": {
    "category": "wk",
    "functions": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":50,\"max\":350,\"scale\":1,\"step\":5}"
      },
      {
        "code": "child_lock",
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":50,\"max\":350,\"scale\":1,\"step\":5}"
      },
      {
        "code": "temp_current",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":1000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "child_lock",
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1683750687992,
  "tid": "a3be385aef7111edb8e6f637b158923e"
}
```

DP.                                 ID 
Power         	                1
Set Temp                       2
Current temp                3
Mode                             4
Out Temp                      101
Lock                               6
Sensor Type                  102
Temp Calibration ADJ  103
Swing                             104
Load                               105
ProgramData                 106
MakeDate                      107
Error                               12 
Optimum                        108
Geofence                       109
Boost Switch                 110
Boost Time                    111
Boost Temperature       112
Holiday Switch              113
Holiday Day                   114
Holiday Temperature    115
ProgramMode               116

# Product ID

{
  "result": {
    "active_time": 1671035276,
    "category": "wk",
    "category_name": "Thermostat",
    "create_time": 1611849531,
    "gateway_id": "",
    "icon": "smart/icon/1541563621slyggh2zc3_0.jpg",
    "id": "206100464c11ae127a5b",
    "ip": "xx.xx.xx.xx",
    "lat": "51.xxxx",
    "local_key": "xxxxxxxxxxxxxxxxxxxxx",
    "lon": "-0.7xxxx",
    "model": "Smart Thermostat",
    "name": "Kitchen",
    "online": true,
    "owner_id": "xxxxxxxx",
    "product_id": "snflej6i7rpqnmhv",
    "product_name": "Smart Thermostat",
    "sub": false,
    "time_zone": "+00:00",
    "update_time": 1683741614,
    "uuid": "206100464c11ae127a5b"
  },
  "success": true,
  "t": 1683751093402,
  "tid": "9592c3a6ef7211edb63796ce6b547e6f"
}

# Information about how the device functions

Product Name:  Previously Known as  Emmeti Zona Smart Thermostat  (Company seems to have name changed to Unisenza) 
Region:  UK (Note temperature in Celcius only)
Product Operation Guide : 
Function:  It sends a control signal (using an MCU I believe)  to the central heading system (Boiler) to turn on the specific zone linked to the thermostat.   The Thermostat has an internal temp sensor that  will determine when the boiler is turned on/off based on the 7 day programming and the preset modes all accessible through the touch screen panel.  More details in the linked Operations Manual

https://emmeti.co.uk/wp-content/uploads/33464-Zona-Instruction-BookInternalHR.pdf
[33464-Zona-Instruction-BookInternalHR.pdf](https://github.com/make-all/tuya-local/files/11445808/33464-Zona-Instruction-BookInternalHR.pdf)

Has its own app, which seems to a copy of the Tuya app with some branding. I use it with the Tuya app and not the OEM app.

**Comment by make-all** [comment]
There are a few fields that need more information:
- dp 4 (mode) - what are the mappings? The log message has a numeric string (value "4"), expect cool, heat, dry, fan_only, auto
- dp 102 (sensor type) - what are the mappings? The log message has a numeric string (value "0"), expect something like internal, external, both
- dp 104 (swing) - is it really swing? I would expect either an off/on boolean switch, or a string value (off, horizontal, vertical, both) not a numeric value
- dp 105 (load) - what does this do?

**Comment by make-all** [comment]
Closing, as unable to gather enough information to make a config.

**Comment by KanthamohanJ** [comment]
Can we reopen this ? Apologies for the delay but attahced is a device config for this Thermostat that works well.  The config will  have answers to the previous open questions. 

[Emmeti_thermostat_custom.txt](https://github.com/user-attachments/files/18609262/Emmeti_thermostat_custom.txt)
