### ISSUE TITLE
Classic America window AC isnt able to be configured with Local Tuya

### ISSUE THREAD

**Issue by TheJoe1990** [make-all/tuya-local#707]
Part number: TWC-12CRD1/L0U-CA

With the official Tuya integration it seems to double convert from C to F.  

I have configured the AC in Local Tuya and I manage to get the current temp and the target temp reported to HA correctly, but I cannot change the target temp.  When I look under Dev Tools I see this:

hvac_modes: null
min_temp: 7
max_temp: 35
target_temp_step: 0.5
friendly_name: test
supported_features: 1
current_temperature: 68
temperature: 73
raw_state: true

The min and max temps catch my attention as being pretty far from reality.  Any suggestions or help?

**Comment by make-all** [comment]
Wrong project
