### ISSUE TITLE
door opener sensor

### ISSUE THREAD

**Issue by fischrobi** [make-all/tuya-local#708]
# Log Message

```
Please paste logs here
```

# Information about DPS mappings

```
{
  "result": {
    "category": "mcs",
    "functions": [],
    "status": [
      {
        "code": "doorcontact_state",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "battery_percentage",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1683897719304,
  "tid": "f9718ebff0c711edb63796ce6b547e6f"
}
```

# Product ID

    "product_id": "0mjj67aaztcfmc3i",
    "product_name": "WIFI Door ",

# Information about how the device functions

**Comment by make-all** [comment]
As there are no logs, I assume you were not able to connect the device.  In that case it is unlikely to work, and it would be a waste of my time to spend time on supporting it.
