### ISSUE TITLE
door opening sensor

### ISSUE THREAD

**Issue by fischrobi** [make-all/tuya-local#711]
```
2023-05-12 23:42:20.739 ERROR (MainThread) [custom_components.tuya_local.device] <class 'Exception'>: Unable to find device on network (specify IP address) while initialising device bf52af08e8b8ad906babm9
2023-05-12 23:42:20.747 WARNING (MainThread) [custom_components.tuya_local.config_flow] Connection test failed with <class 'Exception'> Unable to find device on network (specify IP address)
```

# Information about DPS mappings

```
{
  "result": {
    "category": "mcs",
    "functions": [],
    "status": [
      {
        "code": "doorcontact_state",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "battery_percentage",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1683927886820,
  "tid": "36b3b923f10e11edb63796ce6b547e6f"
}
```

# Product ID

    "product_id": "0mjj67aaztcfmc3i",
    "product_name": "WIFI Door ",

# Information about how the device functions

https://www.aliexpress.com/item/1005004320221657.html?spm=a2g0o.productlist.main.9.676c12ab6TR6xK&algo_pvid=eb8ce717-4f6b-4f52-b2d5-5e9027a275cb&aem_p4p_detail=2023051214480910532273910091220005485613&algo_exp_id=eb8ce717-4f6b-4f52-b2d5-5e9027a275cb-4&pdp_npi=3%40dis%21HUF%215732.37%212866.19%21%21%21%21%21%40211be54b16839280896148866d07ff%2112000028742793442%21sea%21HU%210&curPageLogUid=uLUOyqCsGVC5&ad_pvid=2023051214480910532273910091220005485613_5&ad_pvid=2023051214480910532273910091220005485613_5

**Comment by LinkXX92** [comment]
Same problem here

**Comment by make-all** [comment]
Did either of you read the error message, and try specifying the IP address as it says?

**Comment by LinkXX92** [comment]
I dont have any error in logs
Only this
![1](https://github.com/make-all/tuya-local/assets/88990325/a9dd7a71-3223-49b4-84ff-5ffd7b663702)

If in IP i write AUTO i have error in logs

**Comment by make-all** [comment]
It is very likely that this device is battery powered, and therefore not consistently on the network.  Such a device can only really work with the cloud, as it only wakes up when it has events to send, which it sends directly to the cloud.
