### ISSUE TITLE
Thermostat bht-600 goes unavailable after some hours powered off

### ISSUE THREAD

**Issue by antoweb** [make-all/tuya-local#713]
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**
After last update thermostat bht-6000 goes offline (unavailable) after some hours that is powered offi have to turn on manually than return online

**To Reproduce**
Steps to reproduce the behavior including the device the issue was observed with:

- Turn off Thermostat
- Wait some hours
- Check status is offline
- TUrn on manually Thermostat
- Status retunr online

**Expected behavior**

**Additional context**

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

[tuya_local-9a61ee850f6868b39d3f4c5bf8d8ea0f-termostato-943f166c7e915bc1dde4ab39d0fe730d.json.txt](https://github.com/make-all/tuya-local/files/11471345/tuya_local-9a61ee850f6868b39d3f4c5bf8d8ea0f-termostato-943f166c7e915bc1dde4ab39d0fe730d.json.txt)

attached diagnostic data

**Comment by make-all** [comment]
Seems like the same issue as #653
