### ISSUE TITLE
benexmart_blind_motor no longer reporting position as of version 2023.5.0

### ISSUE THREAD

**Issue by davidt94** [make-all/tuya-local#715]
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**
Curtains no longer reporting position back to home assistant.

**To Reproduce**
Updating to 2023.5.0

**Expected behavior**
Curtains report back position to HA

**Additional context**

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.5.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.11",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "6.1.21-v8",
    "supervisor": "2023.04.1",
    "host_os": "Home Assistant OS 10.1",
    "docker_version": "23.0.3",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hikvision_next": {
      "version": "1.0.3",
      "requirements": [
        "xmltodict==0.13.0",
        "hikvisionapi==0.3.2",
        "requests-toolbelt==0.10.1"
      ]
    },
    "tuya_local": {
      "version": "2022.5.1",
      "requirements": [
        "pycryptodome~=3.17",
        "tinytuya==1.12.7"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya_local",
    "name": "Tuya Local",
    "codeowners": [
      "@make-all"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/make-all/tuya-local",
    "integration_type": "device",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/make-all/tuya-local/issues",
    "requirements": [
      "pycryptodome~=3.17",
      "tinytuya==1.12.7"
    ],
    "version": "2022.5.1",
    "is_built_in": false
  },
  "data": {
    "name": "Curtain Left",
    "type": "benexmart_blind_motor",
    "device_id": "**REDACTED**",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": "auto",
    "api_version_set": 3.3,
    "api_version_used": 3.3,
    "api_working": true,
    "status": {},
    "cached_state": {
      "updated_at": 1684159030.5036194,
      "1": "stop",
      "2": 0,
      "5": true
    },
    "pending_state": {},
    "connected": true,
    "force_dps": [],
    "home_assistant": {
      "name": "Curtain Left",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": "switch",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.left_curtain_reversed",
            "state": "on",
            "attributes": {
              "device_class": "switch",
              "icon": "mdi:arrow-u-down-left",
              "friendly_name": "Curtain Left Reversed"
            },
            "last_changed": "2023-05-15T13:54:02.509559+00:00",
            "last_updated": "2023-05-15T13:54:02.509559+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": "curtain",
          "original_device_class": "blind",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "cover.left_curtain",
            "state": "unknown",
            "attributes": {
              "current_position": 0,
              "device_class": "curtain",
              "friendly_name": "Left Curtain",
              "supported_features": 15
            },
            "last_changed": "2023-05-15T13:54:02.508878+00:00",
            "last_updated": "2023-05-15T13:54:02.508878+00:00"
          }
        }
      ]
    }
  }

<img width="716" alt="Screenshot 2023-05-15 at 15 04 28" src="https://github.com/make-all/tuya-local/assets/57048835/23c95973-5e7d-4676-bb04-3fff0d8064fb">

**Comment by tavicu** [comment]
Same thing for "simple blinds", now it reports unknown.

I tried adding the device again but same thing.
![image](https://github.com/make-all/tuya-local/assets/172068/57dde4cc-4729-47d7-adcb-8fbe53741dbf)
![image](https://github.com/make-all/tuya-local/assets/172068/9f2d9743-7379-4a41-9828-e833fb692ea5)

**Comment by xZetsubou** [comment]
> Same thing for "simple blinds", now it reports unknown.
> 
> I tried adding the device again but same thing

Out of curious, You can try this it might fix your issues: [cover.py](https://github.com/xZetsubou/tuya-local/blob/fix-cover-actions/custom_components/tuya_local/cover.py) I had issues with cover states before and this fixed it for me.

**Comment by davidt94** [comment]
@xZetsubou Looks to be working great with that cover.py and the commit that referenced this issue.

**Comment by tavicu** [comment]
@make-all any update on this?
<img width="629" alt="image" src="https://github.com/make-all/tuya-local/assets/172068/28574987-127b-4dec-a4ad-4d3c5749220b">

**Comment by make-all** [comment]
There is no way to know if the position is reliable, on many devices it reportedly isn't.  So position is only reported for devices that have separate position setting and position reporting dps.
The Unknown is correct when all Tuya devices are considered.

**Comment by make-all** [comment]
This is no status.  I have no control over what is displayed by the Home Assistant front end.

**Comment by tavicu** [comment]
@make-all the change will not fix the problem. Even if you mapped `current_position` to the `position` dp the current_status function will return None if the value is not < 5 or > 95 (https://github.com/tavicu/tuya-local/blob/main/custom_components/tuya_local/cover.py#L124-L129)

Unless I'm missing something.
