### ISSUE TITLE
Poolex Heater - No decimals

### ISSUE THREAD

**Issue by nakedfoot** [make-all/tuya-local#717]
Hello,

I got a Poolex Jetline Premium Fi working quite well with Tuya-Local,
But it only displays integer, no decimals on climate card.

On the screen of my Heater, decimals are good, not in HomeAssistant (temp: 24 on HA, 24.9 on my heater).

Is it a JSON issue ? or my config is bad ?

Thx.

**Comment by make-all** [comment]
This is not a bug. HA can only display what the heater is supplying.
