### ISSUE TITLE
New device: Eurom Soleil 601

### ISSUE THREAD

**Issue by maartendamen** [make-all/tuya-local#73]
Can you please add support for this device? The product page is here: https://eurom.nl/en/product/permanent-heating/infrared-heaters-permanent/mon-soleil-601-wifi/ There are also larger and smaller models I guess they all work the same way.

Right now the device is detected as follows:

Device matches mirabella_genio_usb with quality of 40%. DPS: {'1': False, '2': 21, '3': 20, '6': False, '13': 0, 'updated_at': 1637071127.705068}

In the Tuya app I can control On/Off, Eco mode (which is basically 16 degress setpoint) and the temperature.
Maybe some code from the other Tuya devices is re-usable? I will be glad to help add support for this device, just let me know if you need more information.

**Comment by make-all** [comment]
Which is current temperature, and which is set temperature out of 21 and 20?
Does it have a timer?  The last 0 could be either a timer or a fault code I think.

**Comment by maartendamen** [comment]
Thanks for the reply. I did some testing this evening and I believe the id's are as follows:

1 = On/off
2 = Setpoint
3 = Temperature
6 = Eco mode
13 = Error code

The device has a timer but this has no effect on id 13 when I change it.
Based on the above I created the following yaml file (eurom_601_heater.yaml):

`name: Eurom Mon Soleil 601 Heater
legacy_type: eurom_heater
primary_entity:
  entity: climate
  dps:
    - id: 1
      type: boolean
      mapping:
        - dps_val: false
          value: "off"
          icon: "mdi:radiator-disabled"
          icon_priority: 1
        - dps_val: true
          value: "heat"
          icon: "mdi:radiator"
          icon_priority: 3
      name: hvac_mode
    - id: 2
      type: integer
      range:
        min: 15
        max: 35
      name: temperature
    - id: 3
      type: integer
      readonly: true
      name: current_temperature
    - id: 6
      type: boolean
      mapping:
        - dps_val: false
          value: "off"
        - dps_val: true
          value: "on"
      name: eco_mode
    - id: 13
      type: bitfield
      mapping:
        - dps_val: 0
          value: "OK"
      readonly: true
      name: error
secondary_entities:
  - entity: binary_sensor
    name: Error
    category: diagnostic
    class: problem
    dps:
      - id: 13
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - value: true
`
The device is working and it is properly detected.
Any feedback on the device configuration file?

**Comment by maartendamen** [comment]
I can confirm everything is working with the new version.
Thanks a lot for the quick support!
