### ISSUE TITLE
Poolex Q line adds as domestic water heater with different commands

### ISSUE THREAD

**Issue by paqpaqpaq** [make-all/tuya-local#731]
My Poolex Q-line heatpump is discovered as "hydrotherm_dynamic_x8_water_heater", which is a domestic water heater.
current and set temperatures are there, but the possible mode settings are all wrong.

<img width="416" alt="Scherm­afbeelding 2023-05-21 om 23 09 02" src="https://github.com/make-all/tuya-local/assets/34166264/4d520331-3c01-43df-bcb0-f5868970c963">

**Comment by make-all** [comment]
There is no info to diagnose your issue.  Please do not bypass the templates next time

**Comment by paqpaqpaq** [comment]
Sorry there was no template when simply creating a new topic.
Anyway, maybe you can re-open?

Device information:
`{
  "result": {
    "active_time": 1653480668,
    "category": "qn",
    "category_name": "Heater",
    "create_time": 1653480668,
    "gateway_id": "",
    "icon": "smart/icon/ay1540350271847tyMSF/66dc330a70e71ab0bc8cc0540b3c5ec6.png",
    "id": "xxx",
    "ip": "82.170.211.80",
    "lat": "50.9900",
    "local_key": "xxx",
    "lon": "5.7700",
    "model": "XK-LED03",
    "name": "Poolex Q-7",
    "online": true,
    "owner_id": "13225696",
    "product_id": "qhrpnqjhakrn3jvv",
    "product_name": "Pool Heat Pump",
    "sub": false,
    "time_zone": "+02:00",
    "update_time": 1684699928,
    "uuid": "xxx"
  },
  "success": true,
  "t": 1684703634050,
  "tid": "xxx"
}`

Properties:
`curl  --request GET "https://openapi.tuyaeu.com/v1.0/iot-03/devices/xxx/specification" --header "sign_method: HMAC-SHA256" --header "client_id: 5t7demxaas6i7km0fo7a" --header "t: 1684738478351" --header "mode: cors" --header "Content-Type: application/json" --header "sign: 13E22B38A5D7478168F292AD69A3AA9F9A93384A3E7D6A0C36561FD7DDF541F9" --header "access_token: xxx" `

`{
  "result": {
    "category": "qn",
    "functions": [
      {
        "code": "switch",
        "desc": "{}",
        "name": "开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "desc": "{\"unit\":\"℃\",\"min\":5,\"max\":80,\"scale\":0,\"step\":1}",
        "name": "设置温度",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":5,\"max\":80,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_unit_convert",
        "desc": "{\"range\":[\"c\",\"f\"]}",
        "name": "温标切换",
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "temp_set_f",
        "desc": "{\"unit\":\"℉\",\"min\":41,\"max\":176,\"scale\":0,\"step\":1}",
        "name": "设置温度F",
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":41,\"max\":176,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "name": "开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "name": "目标温度C",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":5,\"max\":80,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_current",
        "name": "当前温度C",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-30,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "work_state",
        "name": "工作状态",
        "type": "Enum",
        "values": "{\"range\":[\"heating\"]}"
      },
      {
        "code": "temp_unit_convert",
        "name": "温标切换",
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "temp_set_f",
        "name": "设置温度F",
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":41,\"max\":176,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_current_f",
        "name": "当前温度F",
        "type": "Integer",
        "values": "{\"unit\":\"℉\",\"min\":-22,\"max\":212,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1684738478430,
  "tid": "xxx"
}`

and the instruction:
`curl  --request GET "https://openapi.tuyaeu.com/v1.0/iot-03/devices/{   "result": {     "category": "qn",     "functions": [       {         "code": "switch",         "desc": "{}",         "name": "开关",         "type": "Boolean",         "values": "{}"       },       {         "code": "temp_set",         "desc": "{/"unit/":/"℃/",/"min/":5,/"max/":80,/"scale/":0,/"step/":1}",         "name": "设置温度",         "type": "Integer",         "values": "{/"unit/":/"℃/",/"min/":5,/"max/":80,/"scale/":0,/"step/":1}"       },       {         "code": "temp_unit_convert",         "desc": "{/"range/":[/"c/",/"f/"]}",         "name": "温标切换",         "type": "Enum",         "values": "{/"range/":[/"c/",/"f/"]}"       },       {         "code": "temp_set_f",         "desc": "{/"unit/":/"℉/",/"min/":41,/"max/":176,/"scale/":0,/"step/":1}",         "name": "设置温度F",         "type": "Integer",         "values": "{/"unit/":/"℉/",/"min/":41,/"max/":176,/"scale/":0,/"step/":1}"       }     ],     "status": [       {         "code": "switch",         "name": "开关",         "type": "Boolean",         "values": "{}"       },       {         "code": "temp_set",         "name": "目标温度C",         "type": "Integer",         "values": "{/"unit/":/"℃/",/"min/":5,/"max/":80,/"scale/":0,/"step/":1}"       },       {         "code": "temp_current",         "name": "当前温度C",         "type": "Integer",         "values": "{/"unit/":/"℃/",/"min/":-30,/"max/":100,/"scale/":0,/"step/":1}"       },       {         "code": "work_state",         "name": "工作状态",         "type": "Enum",         "values": "{/"range/":[/"heating/"]}"       },       {         "code": "temp_unit_convert",         "name": "温标切换",         "type": "Enum",         "values": "{/"range/":[/"c/",/"f/"]}"       },       {         "code": "temp_set_f",         "name": "设置温度F",         "type": "Integer",         "values": "{/"unit/":/"℉/",/"min/":41,/"max/":176,/"scale/":0,/"step/":1}"       },       {         "code": "temp_current_f",         "name": "当前温度F",         "type": "Integer",         "values": "{/"unit/":/"℉/",/"min/":-22,/"max/":212,/"scale/":0,/"step/":1}"       }     ]   },   "success": true,   "t": 1684738478430,   "tid": "xxx" }/functions" --header "sign_method: HMAC-SHA256" --header "client_id: 5t7demxaas6i7km0fo7a" --header "t: 1684738573258" --header "mode: cors" --header "Content-Type: application/json" --header "sign: AAE232B148F8EF576D770D6DA8AB6B07DC74BFFBF7DEC0FD973743B824F3EECE" --header "access_token: xxx" `

**Comment by WilcoE** [comment]
Have the same issue
Is more information needed?
