### ISSUE TITLE
Request support for YINMIK Water Quality Tester ( WF-3188 )

### ISSUE THREAD

**Issue by dakoller** [make-all/tuya-local#732]
# Log Message

```
Please paste logs here
```

# Information about DPS mappings

```
  "data": {
    "endpoint": "https://openapi.tuyaeu.com",
    "auth_type": 0,
    "country_code": "49",
    "app_type": "tuyaSmart",
    "mqtt_connected": true,
    "disabled_by": null,
    "disabled_polling": false,
    "name": "WaterQuality2",
    "model": "WF-3188",
    "category": "szjcy",
    "product_id": "u5xgcpcngk3pfxb4",
    "product_name": "YINMIK Water Quality Tester",
    "online": true,
    "sub": false,
    "time_zone": "+02:00",
    "active_time": "2023-05-06T10:42:36+00:00",
    "create_time": "2023-04-07T12:12:38+00:00",
    "update_time": "2023-05-06T10:42:36+00:00",
    "function": {
      "phbuffer": {
        "type": "Enum",
        "value": {
          "range": [
            "AsiaStandard",
            "EUStandard"
          ]
        }
      },
      "holdreading": {
        "type": "Boolean",
        "value": {}
      },
      "backlight": {
        "type": "Boolean",
        "value": {}
      },
      "ectempcompenabled": {
        "type": "Boolean",
        "value": {}
      },
      "ectempcomfactor": {
        "type": "Integer",
        "value": {
          "unit": "%/\u2103",
          "min": 0,
          "max": 30,
          "scale": 1,
          "step": 1
        }
      },
      "buzzerwarning": {
        "type": "Boolean",
        "value": {}
      },
      "phmaxlimit": {
        "type": "Integer",
        "value": {
          "unit": "",
          "min": 0,
          "max": 1400,
          "scale": 2,
          "step": 1
        }
      },
      "phminlimit": {
        "type": "Integer",
        "value": {
          "unit": "",
          "min": 0,
          "max": 1400,
          "scale": 2,
          "step": 1
        }
      },
      "ecmaxlimit": {
        "type": "Integer",
        "value": {
          "unit": "mS/cm",
          "min": 0,
          "max": 200000,
          "scale": 3,
          "step": 1
        }
      },
      "ecminlimit": {
        "type": "Integer",
        "value": {
          "unit": "mS/cm",
          "min": 0,
          "max": 200000,
          "scale": 3,
          "step": 1
        }
      },
      "orpmaxlimit": {
        "type": "Integer",
        "value": {
          "unit": "mV",
          "min": -1200,
          "max": 1200,
          "scale": 0,
          "step": 1
        }
      },
      "orpminlimit": {
        "type": "Integer",
        "value": {
          "unit": "mV",
          "min": -1200,
          "max": 1200,
          "scale": 0,
          "step": 1
        }
      },
      "humiditymaxlimit": {
        "type": "Integer",
        "value": {
          "unit": "%",
          "min": 0,
          "max": 100,
          "scale": 0,
          "step": 1
        }
      },
      "humidityminlimit": {
        "type": "Integer",
        "value": {
          "unit": "%",
          "min": 0,
          "max": 100,
          "scale": 0,
          "step": 1
        }
      }
    },
    "status_range": {
      "tds_in": {
        "type": "Integer",
        "value": {
          "unit": "ppm",
          "min": 0,
          "max": 9999,
          "scale": 0,
          "step": 1
        }
      },
      "temp_current": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": 0,
          "max": 800,
          "scale": 1,
          "step": 1
        }
      },
      "battery_percentage": {
        "type": "Integer",
        "value": {
          "unit": "%",
          "min": 0,
          "max": 100,
          "scale": 0,
          "step": 1
        }
      },
      "ph": {
        "type": "Integer",
        "value": {
          "min": 0,
          "max": 1400,
          "scale": 2,
          "step": 1
        }
      },
      "conductivity_value": {
        "type": "Integer",
        "value": {
          "unit": "mS/cm",
          "min": 0,
          "max": 200000,
          "scale": 3,
          "step": 1
        }
      },
      "orp_value": {
        "type": "Integer",
        "value": {
          "unit": "mV",
          "min": -1200,
          "max": 1200,
          "scale": 0,
          "step": 1
        }
      },
      "phbuffer": {
        "type": "Enum",
        "value": {
          "range": [
            "AsiaStandard",
            "EUStandard"
          ]
        }
      },
      "holdreading": {
        "type": "Boolean",
        "value": {}
      },
      "backlight": {
        "type": "Boolean",
        "value": {}
      },
      "ectempcompenabled": {
        "type": "Boolean",
        "value": {}
      },
      "ectempcomfactor": {
        "type": "Integer",
        "value": {
          "unit": "%/\u2103",
          "min": 0,
          "max": 30,
          "scale": 1,
          "step": 1
        }
      },
      "buzzerwarning": {
        "type": "Boolean",
        "value": {}
      },
      "phmaxlimit": {
        "type": "Integer",
        "value": {
          "unit": "",
          "min": 0,
          "max": 1400,
          "scale": 2,
          "step": 1
        }
      },
      "phminlimit": {
        "type": "Integer",
        "value": {
          "unit": "",
          "min": 0,
          "max": 1400,
          "scale": 2,
          "step": 1
        }
      },
      "ecmaxlimit": {
        "type": "Integer",
        "value": {
          "unit": "mS/cm",
          "min": 0,
          "max": 200000,
          "scale": 3,
          "step": 1
        }
      },
      "ecminlimit": {
        "type": "Integer",
        "value": {
          "unit": "mS/cm",
          "min": 0,
          "max": 200000,
          "scale": 3,
          "step": 1
        }
      },
      "orpmaxlimit": {
        "type": "Integer",
        "value": {
          "unit": "mV",
          "min": -1200,
          "max": 1200,
          "scale": 0,
          "step": 1
        }
      },
      "orpminlimit": {
        "type": "Integer",
        "value": {
          "unit": "mV",
          "min": -1200,
          "max": 1200,
          "scale": 0,
          "step": 1
        }
      },
      "eccf": {
        "type": "Integer",
        "value": {
          "unit": "",
          "min": 0,
          "max": 20000,
          "scale": 1,
          "step": 1
        }
      },
      "humidity": {
        "type": "Integer",
        "value": {
          "unit": "%",
          "min": 0,
          "max": 100,
          "scale": 0,
          "step": 1
        }
      },
      "humiditymaxlimit": {
        "type": "Integer",
        "value": {
          "unit": "%",
          "min": 0,
          "max": 100,
          "scale": 0,
          "step": 1
        }
      },
      "humidityminlimit": {
        "type": "Integer",
        "value": {
          "unit": "%",
          "min": 0,
          "max": 100,
          "scale": 0,
          "step": 1
        }
      }
    },
    "status": {
      "tds_in": 0,
      "temp_current": 186,
      "battery_percentage": 0,
      "ph": 678,
      "conductivity_value": 648,
      "orp_value": 369,
      "phbuffer": "AsiaStandard",
      "holdreading": false,
      "backlight": false,
      "ectempcompenabled": true,
      "ectempcomfactor": 0,
      "buzzerwarning": true,
      "phmaxlimit": 1400,
      "phminlimit": 0,
      "ecmaxlimit": 200000,
      "ecminlimit": 0,
      "orpmaxlimit": 1200,
      "orpminlimit": -1200,
      "eccf": 64,
      "humidity": 59,
      "humiditymaxlimit": 100,
      "humidityminlimit": 0
    },
    "home_assistant": {
      "name": "WaterQuality2",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": []
    }
  }
}
```

`{
  "result": {
    "category": "szjcy",
    "functions": [
      {
        "code": "phbuffer",
        "desc": "{\"range\":[\"AsiaStandard\",\"EUStandard\"]}",
        "name": "pHBuffer",
        "type": "Enum",
        "values": "{\"range\":[\"AsiaStandard\",\"EUStandard\"]}"
      },
      {
        "code": "holdreading",
        "desc": "{}",
        "name": "HoldReading",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "backlight",
        "desc": "{}",
        "name": "BackLight",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "ectempcompenabled",
        "desc": "{}",
        "name": "EcTempCompEnabled",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "ectempcomfactor",
        "desc": "{\"unit\":\"%/℃\",\"min\":0,\"max\":30,\"scale\":1,\"step\":1}",
        "name": "EcTempCompFactor",
        "type": "Integer",
        "values": "{\"unit\":\"%/℃\",\"min\":0,\"max\":30,\"scale\":1,\"step\":1}"
      },
      {
        "code": "buzzerwarning",
        "desc": "{}",
        "name": "BuzzerWarning",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "phmaxlimit",
        "desc": "{\"unit\":\"\",\"min\":0,\"max\":1400,\"scale\":2,\"step\":1}",
        "name": "pHMaxLimit",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":1400,\"scale\":2,\"step\":1}"
      },
      {
        "code": "phminlimit",
        "desc": "{\"unit\":\"\",\"min\":0,\"max\":1400,\"scale\":2,\"step\":1}",
        "name": "pHMinLimit",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":1400,\"scale\":2,\"step\":1}"
      },
      {
        "code": "ecmaxlimit",
        "desc": "{\"unit\":\"mS/cm\",\"min\":0,\"max\":200000,\"scale\":3,\"step\":1}",
        "name": "EC最大值",
        "type": "Integer",
        "values": "{\"unit\":\"mS/cm\",\"min\":0,\"max\":200000,\"scale\":3,\"step\":1}"
      },
      {
        "code": "ecminlimit",
        "desc": "{\"unit\":\"mS/cm\",\"min\":0,\"max\":200000,\"scale\":3,\"step\":1}",
        "name": "EC最小值",
        "type": "Integer",
        "values": "{\"unit\":\"mS/cm\",\"min\":0,\"max\":200000,\"scale\":3,\"step\":1}"
      },
      {
        "code": "orpmaxlimit",
        "desc": "{\"unit\":\"mV\",\"min\":-1200,\"max\":1200,\"scale\":0,\"step\":1}",
        "name": "OrpMaxLimit",
        "type": "Integer",
        "values": "{\"unit\":\"mV\",\"min\":-1200,\"max\":1200,\"scale\":0,\"step\":1}"
      },
      {
        "code": "orpminlimit",
        "desc": "{\"unit\":\"mV\",\"min\":-1200,\"max\":1200,\"scale\":0,\"step\":1}",
        "name": "OrpMinLimit",
        "type": "Integer",
        "values": "{\"unit\":\"mV\",\"min\":-1200,\"max\":1200,\"scale\":0,\"step\":1}"
      },
      {
        "code": "humiditymaxlimit",
        "desc": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}",
        "name": "HumidityMaxLimit",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "humidityminlimit",
        "desc": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}",
        "name": "HumidityMinLimit",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "tds_in",
        "name": "TDS",
        "type": "Integer",
        "values": "{\"unit\":\"ppm\",\"min\":0,\"max\":9999,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_current",
        "name": "Temprt",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":800,\"scale\":1,\"step\":1}"
      },
      {
        "code": "battery_percentage",
        "name": "BatteryValue",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "ph",
        "name": "PH值",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":1400,\"scale\":2,\"step\":1}"
      },
      {
        "code": "conductivity_value",
        "name": "EC",
        "type": "Integer",
        "values": "{\"unit\":\"mS/cm\",\"min\":0,\"max\":200000,\"scale\":3,\"step\":1}"
      },
      {
        "code": "orp_value",
        "name": "ORP",
        "type": "Integer",
        "values": "{\"unit\":\"mV\",\"min\":-1200,\"max\":1200,\"scale\":0,\"step\":1}"
      },
      {
        "code": "phbuffer",
        "name": "pHBuffer",
        "type": "Enum",
        "values": "{\"range\":[\"AsiaStandard\",\"EUStandard\"]}"
      },
      {
        "code": "holdreading",
        "name": "HoldReading",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "backlight",
        "name": "BackLight",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "ectempcompenabled",
        "name": "EcTempCompEnabled",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "ectempcomfactor",
        "name": "EcTempCompFactor",
        "type": "Integer",
        "values": "{\"unit\":\"%/℃\",\"min\":0,\"max\":30,\"scale\":1,\"step\":1}"
      },
      {
        "code": "buzzerwarning",
        "name": "BuzzerWarning",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "phmaxlimit",
        "name": "pHMaxLimit",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":1400,\"scale\":2,\"step\":1}"
      },
      {
        "code": "phminlimit",
        "name": "pHMinLimit",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":1400,\"scale\":2,\"step\":1}"
      },
      {
        "code": "ecmaxlimit",
        "name": "EC最大值",
        "type": "Integer",
        "values": "{\"unit\":\"mS/cm\",\"min\":0,\"max\":200000,\"scale\":3,\"step\":1}"
      },
      {
        "code": "ecminlimit",
        "name": "EC最小值",
        "type": "Integer",
        "values": "{\"unit\":\"mS/cm\",\"min\":0,\"max\":200000,\"scale\":3,\"step\":1}"
      },
      {
        "code": "orpmaxlimit",
        "name": "OrpMaxLimit",
        "type": "Integer",
        "values": "{\"unit\":\"mV\",\"min\":-1200,\"max\":1200,\"scale\":0,\"step\":1}"
      },
      {
        "code": "orpminlimit",
        "name": "OrpMinLimit",
        "type": "Integer",
        "values": "{\"unit\":\"mV\",\"min\":-1200,\"max\":1200,\"scale\":0,\"step\":1}"
      },
      {
        "code": "eccf",
        "name": "CF",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":20000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "humidity",
        "name": "Humidity",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "humiditymaxlimit",
        "name": "HumidityMaxLimit",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "humidityminlimit",
        "name": "HumidityMinLimit",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1684767508932,
  "tid": "1c723755f8b111ed86f16a7eaa158d6d"
}`

# Product ID

# Information about how the device functions

**Comment by make-all** [comment]
Sorry I cannot make a config with just information from the cloud API
