### ISSUE TITLE
Request support for Quinetic dimming controller

### ISSUE THREAD

**Issue by MoondewCoUK** [make-all/tuya-local#738]
# Log Message

```
Please paste logs here
```

# Information about DPS mappings

```
{
  "result": {
    "category": "tgq",
    "functions": [
      {
        "code": "switch_led_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "bright_value_1",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "brightness_min_1",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      }
    ],
    "lang_config": {},
    "status": [
      {
        "code": "switch_led_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "bright_value_1",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "brightness_min_1",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1685043752418,
  "tid": "4a6c1069fb3411eda4908a3120fb3e2a"
}
```

# Product ID

"product_id": "azt4dppefleigvb0",

# Information about how the device functions

https://www.quinetic.co.uk/products/wifi-receiver/
Dimming capable controller which works either with tuya or a proprietary 433Mhz pulse.
Adding as a Simple lightbulb works, but the dimming is incorrect.
Needs the following to map brightness correctly
        min: 10
        max: 1000
      mapping:
        - scale: 3.92

**Comment by make-all** [comment]
This seems the same as the recently added feit dimmer submitted as PR#752

**Comment by MoondewCoUK** [comment]
Good evening
I updated to the current version, removed and added this device as a feit dimmer but now I am unable to turn on the device.
If i use the smart life app, I can turn it on, then home assistant can adjust the brightness, or turn it off.
However if home assistant is told to turn this on, the UI changes to on, then shortly after changes to off

**Comment by MoondewCoUK** [comment]
It works if I remove the lines from the Feit yaml
       mapping:
        - dps_val: null
          value: false

**Comment by make-all** [comment]
Thanks for the info, I think this problem was fixed earlier in this development cycle.
