### ISSUE TITLE
Device : Heater NEDIS 

### ISSUE THREAD

**Issue by TeddyLafrite** [make-all/tuya-local#74]
Hi

Thanks for your wonderful work :)

I have a NEDIS heater : https://nedis.com/en-us/product/home-living/climate/heaters/550711594/smartlife-convection-heater-wi-fi-suitable-for-bathroom-glass-panel-2000-w-2-heat-settings-led-display-15-35-0c-adjustable-thermostat-white?_ga=undefined

Here you can find journal :

Cette erreur provient d'une intégration personnalisée

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:73
Integration: Tuya Local (documentation, issues)
First occurred: 22:36:11 (1 occurrences)
Last logged: 22:36:11

Device matches poolex_silverline_heatpump with quality of 62%. DPS: {'1': True, '2': 25, '3': 25, '4': '1', '7': False, '11': '0', '13': 0, '101': False, 'updated_at': 1637098568.809125}

2 = set temp
3 = actual temp

I really need 5 functions :
- ECO mode
- COMFORT mode
- OFF
- Actual temp
- Set temp

Thanks a lot :)

**Comment by TeddyLafrite** [comment]
Actually working : 
- Set temp
- Current temp
- Off
- Eco mode (heat)

So only Comfort mode is missing

**Comment by make-all** [comment]
Are you able to find out the values for dps 4 for Comfort and Eco modes?
Are there other features such as a Child Lock, Timer, or anything else?

**Comment by TeddyLafrite** [comment]
Tanks for your reply
I will try tomorrow
There are some others features (timer, Child lock, timer prog)

**Comment by make-all** [comment]
OK, One of the False values (7 or 101) will be the child lock in that case (it didn't show on the screenshot on the webpage).
The daily scheduling is likely cloud based, and is handled by Home Assistant Automations.  If it is device based, it relies on a complex long hexidecimal string, probably in dps 11 which is too hard to work with, so I've skipped it in the devices I've identified as supporting it so far.

**Comment by TeddyLafrite** [comment]
Hi

I test for DPS 4 : 
1 = Eco
2 = Comfort

I just delete device, active comfort mode, and proceed to integration

Device matches poolex_silverline_heatpump with quality of 62%. DPS: {'1': **True**, '2': 22, '3': 20, '4': '**1**', '7': False, '11': '0', '13': 0, '101': False, 'updated_at': 1637171189.0292742}
= Device active on Eco

Device matches poolex_silverline_heatpump with quality of 62%. DPS: {'1': **False**, '2': 22, '3': 21, '4': '**1**', '7': False, '11': '0', '13': 0, '101': False, 'updated_at': 1637171299.1233184}
= Device off

Device matches poolex_silverline_heatpump with quality of 62%. DPS: {'1': **True**, '2': 23, '3': 22, '4': '**2**', '7': False, '11': '0', '13': 0, '101': False, 'updated_at': 1637171431.7162051}
= Device active on Comfort

**Comment by TeddyLafrite** [comment]
Modifications done :

      mapping:
        - dps_val: "1"
          value: "Eco"
        - dps_val: "2"
          value: "Confort"
        - dps_val: "3"
          value: "Hors gel"
👍
