### ISSUE TITLE
Eurom Heater is recognized as mirabella_genio_usb

### ISSUE THREAD

**Issue by mvroosmalen1970** [make-all/tuya-local#75]
Hi
My Heater is not correctly recognized:
This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:73
Integration: Tuya Local (documentation, issues)
First occurred: 8:34:20 PM (1 occurrences)
Last logged: 8:34:20 PM

Device matches mirabella_genio_usb with quality of 40%. DPS: {'1': False, '2': 21, '3': 19, '4': 'off', '7': False, 'updated_at': 1637350453.9208913}

Any help is appreciated

**Comment by make-all** [comment]
Which model Eurom heater is this?

**Comment by mvroosmalen1970** [comment]
Sani-Wall-Heat 2000 Wifi with swing function

https://eurom.nl/product/verwarming/badkamerkachels/sani-wall-heat-2000-wifi/

**Comment by make-all** [comment]
I made a guess at the values for dps 4 being "off", "low" and "high" based on the manual saying that the mode can be switched between fan only, half and full heating, combined with the known value of "off" above.  Another guess is that dps 7 controls the swing function (otherwise, there are no other dps left, so the swing would not be controllable if it is not that).

**Comment by mvroosmalen1970** [comment]
The device is recognized. temperature is functional. The on/off, swing and power doesn;t seem to match with values expected as I get status:
off - fan
- auto
- 50_perc
- 100_perc
no clue how to resolve this or what info could be helpful for you?

**Comment by make-all** [comment]
I'm not sure what is going on with the swing, but it may just be a side effect of the presets being incorrect.

**Comment by mvroosmalen1970** [comment]
Everything seems to function :-). Thanks!!! Would be nice to improve the 
<img width="251" alt="Capture" src="https://user-images.githubusercontent.com/36565907/142840804-91c83499-00fc-4d27-976c-9746954cae95.PNG">
with swing function and that you can click in the icon starting/stopping the swing.  Maybe this is for future improvements

Good work.

**Comment by make-all** [comment]
Thanks for confirming.  The UI is a general Home Assistant UI, so any enhancement reqests should go there.  I think though that will not want to clutter it with the full functionality of climate devices, and will suggest adding a row of buttons below to control additional functionality.
