### ISSUE TITLE
Request support for EMS Heatpump water heater

### ISSUE THREAD

**Issue by nk00li** [make-all/tuya-local#751]
# Log Message

```
Please paste logs here
```

# Information about DPS mappings

```
Please paste the output here.
```
{
  "result": {
    "category": "rs",
    "functions": [
      {
        "code": "Power",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":10,\"max\":70,\"scale\":0,\"step\":1}"
      },
      {
        "code": "mode",
        "dp_id": 4,
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"mix\",\"electric\"]}"
      }
    ],
    "status": [
      {
        "code": "Power",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":10,\"max\":70,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_current",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":-10,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "mode",
        "dp_id": 4,
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"mix\",\"electric\"]}"
      },
      {
        "code": "fault",
        "dp_id": 9,
        "type": "Bitmap",
        "values": "{\"label\":[\"P01\",\"P02\",\"P03\",\"P04\",\"P05\",\"P06\",\"E01\",\"E02\",\"E03\",\"PA\",\"E08\",\"EA8\",\"EA9\",\"CS\"],\"maxlen\":14}"
      }
    ]
  },
  "success": true,
  "t": 1687261538138,
  "tid": "f9b767c10f5f11eea68636790d793901"
}

# Product ID

nqlqesmkrje7vdhm

# Information about how the device functions

[EMS Thermal 200L Operation Manual.pdf](https://github.com/make-all/tuya-local/files/11760383/EMS.Thermal.200L.Operation.Manual.pdf)

**Comment by nk00li** [comment]
[EMS Thermal 200L Operation Manual.pdf](https://github.com/make-all/tuya-local/files/11721127/EMS.Thermal.200L.Operation.Manual.pdf)

**Comment by make-all** [comment]
There is insufficient information about the modes.  The manual indicates that it supports heatpump, heatpump+element and element modes.  But this documentation only lists one: "auto".

**Comment by nk00li** [comment]
Not sure what happened when I pasted the DPI data above initially. I have done a fresh query from Tuya "Get Device Specification Attribute" and overwrote why I initially submitted, it shows the 3 supported modes on DPID 4.
The supported modes are

1. Auto (Heatpump)
2. Mix
3. Electric
