### ISSUE TITLE
Reopen  HCT-611 WiFi Water Timer #685 

### ISSUE THREAD

**Issue by spanzetta** [make-all/tuya-local#754]
https://github.com/make-all/tuya-local/issues/685

@make-all 
Can you pls help me?

As I wrote in the mentioned ticket (now closed).. since there are many completely different case discussed there (See discussion https://github.com/make-all/tuya-local/discussions/522).. is there a way to "identify" exactly the issue by seeing at logs?

If you guide me how to collect the right log for you.. I will do..

I don't want to go by attempts.. and I would like to have it working..

Thanks in advance

**Comment by make-all** [comment]
The information is all there in #522

**Comment by spanzetta** [comment]
So there is no way to understand the problem by seeing at logs?
I can't believe that..
