### ISSUE TITLE
Tuya presence sensor ZY-M100 not recognised, although already supported

### ISSUE THREAD

**Issue by awatrin** [make-all/tuya-local#755]
I'm trying to add a Tuya ZY-M100 sensor, but the only options presented are: illumanance_sensor, ir_remote_sensors, loratap_curtain_switch and pir_sensor.

Below are the Home Assistant log:

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:49
Integration: Tuya Local (documentation, issues)
First occurred: 1 de junho de 2023 às 17:29:19 (14 occurrences)
Last logged: 11:20:22

Device matches illumanance_sensor with quality of 20%. DPS: {"updated_at": 1685651606.5790794, "1": "presence", "2": 7, "3": 60, "4": 600, "6": "check_success", "9": 87, "101": 1, "102": 100, "103": " ", "104": 83}
Device matches illumanance_sensor with quality of 20%. DPS: {"updated_at": 1685652159.16564, "1": "presence", "2": 7, "3": 60, "4": 600, "6": "check_success", "9": 86, "101": 1, "102": 100, "103": " ", "104": 90}
Device matches illumanance_sensor with quality of 20%. DPS: {"updated_at": 1685652477.2035055, "1": "presence", "2": 9, "3": 60, "4": 600, "6": "check_success", "9": 87, "101": 1, "102": 100, "103": " ", "104": 95}
Report this to https://github.com/make-all/tuya-local/issues/
Device matches illumanance_sensor with quality of 20%. DPS: {"updated_at": 1685715621.3664322, "1": "presence", "2": 8, "3": 0, "4": 950, "6": "check_success", "9": 97, "101": 0, "102": 100, "103": " ", "104": 273}

And the "Get Device Specification Attribute" from Tuya:

{
  "result": {
    "category": "hps",
    "functions": [
      {
        "code": "sensitivity",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"min\":0,\"max\":9,\"scale\":0,\"step\":1}"
      },
      {
        "code": "near_detection",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"unit\":\"M\",\"min\":0,\"max\":1000,\"scale\":2,\"step\":10}"
      },
      {
        "code": "far_detection",
        "dp_id": 4,
        "type": "Integer",
        "values": "{\"unit\":\"M\",\"min\":0,\"max\":1000,\"scale\":2,\"step\":10}"
      }
    ],
    "status": [
      {
        "code": "presence_state",
        "dp_id": 1,
        "type": "Enum",
        "values": "{\"range\":[\"none\",\"presence\"]}"
      },
      {
        "code": "sensitivity",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"min\":0,\"max\":9,\"scale\":0,\"step\":1}"
      },
      {
        "code": "near_detection",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"unit\":\"M\",\"min\":0,\"max\":1000,\"scale\":2,\"step\":10}"
      },
      {
        "code": "far_detection",
        "dp_id": 4,
        "type": "Integer",
        "values": "{\"unit\":\"M\",\"min\":0,\"max\":1000,\"scale\":2,\"step\":10}"
      },
      {
        "code": "checking_result",
        "dp_id": 6,
        "type": "Enum",
        "values": "{\"range\":[\"checking\",\"check_success\",\"check_failure\",\"others\",\"comm_fault\",\"radar_fault\"]}"
      },
      {
        "code": "target_dis_closest",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"M\",\"min\":0,\"max\":1000,\"scale\":2,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1685715882442,
  "tid": "3720f56b015111ee9066bad4ffc8096c"
}

**Comment by make-all** [comment]
I think the issue is fixed, but if it is not (in "main" as not yet released), then more logs might help.
