### ISSUE TITLE
Devices no more available

### ISSUE THREAD

**Issue by lorenzomartini1** [make-all/tuya-local#756]
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**
Some lightbulbs always "not available" since few days

**To Reproduce**
idk

**Expected behavior**

**Additional context**

Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:202
Integration: Tuya Local (documentation, issues)
First occurred: 19:23:49 (91 occurrences)
Last logged: 19:30:37

Failed to fetch device status for Luce Scrivania
Failed to fetch device status for Luce Ambiente 2
Failed to fetch device status for Lampada Salotto 2
Failed to fetch device status for Luce Ambiente 1
Failed to fetch device status for Lucina Corridoio Su

Logger: homeassistant.util.async_
Source: util/async_.py:182
First occurred: 19:27:00 (1 occurrences)
Last logged: 19:27:00

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 78: self._api = tinytuya.Device(dev_id, address, local_key)

When trying to add device again (removed) it gives me: "Impossibile connettersi al dispositivo. Può trattarsi di un problema temporaneo, oppure le informazioni fornite potrebbero non essere corrette."

**Comment by make-all** [comment]
Take a look at the possible causes and solutions in #522
