### ISSUE TITLE
Cleverio Air Purifier

### ISSUE THREAD

**Issue by mrjatko** [make-all/tuya-local#760]
# Log Message

```
Please paste logs here
```

# Information about DPS mappings

```
Please paste the output here.
```
{
  "result": {
    "active_time": 1682958026,
    "biz_type": 0,
    "category": "kj",
    "create_time": 1681757368,
    "icon": "smart/icon/ay1541396207188PFb5m/9ce399b9a35bcd2d8383ffe9d0671462.png",
    "id": "56825362483fda389a7b",
    "ip": "92.34.79.248",
    "lat": "59.2833",
    "local_key": "8fb6496315fedbea",
    "lon": "15.2302",
    "model": "47007 AP1211",
    "name": "Cleverio Air Purifier",
    "online": true,
    "owner_id": "154974557",
    "product_id": "6bspwvsqhl4vuanj",
    "product_name": "Cleverio Air Purifier",
    "status": [
      {
        "code": "switch",
        "value": true
      },
      {
        "code": "speed",
        "value": "2"
      },
      {
        "code": "filter",
        "value": 78
      },
      {
        "code": "light",
        "value": true
      },
      {
        "code": "countdown_set",
        "value": "cancle"
      }
    ],
    "sub": false,
    "time_zone": "+01:00",
    "uid": "eu16829576971237FOwE",
    "update_time": 1685025509,
    "uuid": "56825362483fda389a7b"
  },
  "success": true,
  "t": 1685631221609,
  "tid": "194be8cc008c11eeac8032ebdb7f4f6c"
}

# Product ID
6bspwvsqhl4vuanj

# Information about how the device functions

I think its the same as Breville Smart Air Plus

**Comment by mrjatko** [comment]
https://expo.tuya.com/product/901250

**Comment by make-all** [comment]
As there are no logs, and the documentation you have supplied is for the cloud API (no dpId given for the status datapoints, no list of which datapoints are functions), there is not enough information to add a config.

**Comment by mrjatko** [comment]
"result": {
    "category": "kj",
    "functions": [
      {
        "code": "switch",
        "desc": "{}",
        "name": "开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "speed",
        "desc": "{\"range\":[\"1\",\"2\",\"3\",\"4\"]}",
        "name": "风速档位",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\",\"4\"]}"
      },
      {
        "code": "light",
        "desc": "{}",
        "name": "灯光",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown",
        "desc": "{\"range\":[\"1\",\"2\",\"3\",\"4\"]}",
        "name": "倒计时设置",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\",\"4\"]}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "name": "开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "speed",
        "name": "风速档位",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\",\"4\"]}"
      },
      {
        "code": "filter",
        "name": "滤芯使用率",
        "type": "Integer",
        "values": "{\"unit\":\"％\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "light",
        "name": "灯光",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_set",
        "name": "倒计时设置",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\",\"4\"]}"
      }
    ]
  },
  "success": true,
  "t": 1685845737227,
  "tid": "8e93b988027f11eebfbfa24bf1d21c99"
}
----------------------------------------------------------------------------------------------------------------------------
{
  "result": {
    "category": "kj",
    "functions": [
      {
        "code": "switch",
        "desc": "switch",
        "name": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "speed",
        "desc": "speed",
        "name": "speed",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\",\"4\"]}"
      },
      {
        "code": "light",
        "desc": "light",
        "name": "light",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown",
        "desc": "countdown",
        "name": "countdown",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\",\"4\"]}"
      }
    ]
  },
  "success": true,
  "t": 1685845921592,
  "tid": "fc81d89d027f11eea4908a3120fb3e2a"
}
I vill tray to find the log

**Comment by make-all** [comment]
Sorry, there is still no local protocol details in the information you have supplied, so nothing can be done here.
