### ISSUE TITLE
Tuya Bluetooth Gateway

### ISSUE THREAD

**Issue by kde1806** [make-all/tuya-local#764]
<!--
Hi 
I like to get support for the Tuya Bluetooth Gateway because my Flower Care Sensors are connected via bluetooth to the Gateway. 

Tuya IoT Info # Gateway
{
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "relay_status",
        "desc": "{\"range\":[\"off\",\"on\",\"memory\"]}",
        "name": "上电状态设置",
        "type": "Enum",
        "values": "{\"range\":[\"off\",\"on\",\"memory\"]}"
      }
    ],
    "status": [
      {
        "code": "relay_status",
        "name": "上电状态设置",
        "type": "Enum",
        "values": "{\"range\":[\"off\",\"on\",\"memory\"]}"
      }
    ]
  },
  "success": true,
  "t": 1685966470702,
  "tid": "a960f824039811eeac8032ebdb7f4f6c"
}

Tuya IoT Info # Flower Care Sensor
{
  "result": {
    "category": "zwjcy",
    "functions": [
      {
        "code": "temp_unit_convert",
        "desc": "{\"range\":[\"c\",\"f\"]}",
        "name": "温标切换",
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      }
    ],
    "status": [
      {
        "code": "humidity",
        "name": "湿度",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_current",
        "name": "温度",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":1400,\"scale\":1,\"step\":1}"
      },
      {
        "code": "temp_unit_convert",
        "name": "温标切换",
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "battery_state",
        "name": "电池电量状态",
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"middle\",\"high\"]}"
      },
      {
        "code": "battery_percentage",
        "name": "电池电量",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1685966652979,
  "tid": "1606f1be039911eeac8032ebdb7f4f6c"
}

**Comment by kde1806** [comment]
Hi 

I like to add support for my FLower Care sensors which are connected via Tuya Bluetooth Gateway.
The Gateway not supported yet.

Any help

Tuya IoT Info  Gateway
{
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "relay_status",
        "desc": "{\"range\":[\"off\",\"on\",\"memory\"]}",
        "name": "上电状态设置",
        "type": "Enum",
        "values": "{\"range\":[\"off\",\"on\",\"memory\"]}"
      }
    ],
    "status": [
      {
        "code": "relay_status",
        "name": "上电状态设置",
        "type": "Enum",
        "values": "{\"range\":[\"off\",\"on\",\"memory\"]}"
      }
    ]
  },
  "success": true,
  "t": 1685966860827,
  "tid": "91e7a544039911eea795ce4cada2c678"
}



Tuya IoT Info  Flower Care Sensor
{
  "result": {
    "category": "zwjcy",
    "functions": [
      {
        "code": "temp_unit_convert",
        "desc": "{\"range\":[\"c\",\"f\"]}",
        "name": "温标切换",
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      }
    ],
    "status": [
      {
        "code": "humidity",
        "name": "湿度",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_current",
        "name": "温度",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":1400,\"scale\":1,\"step\":1}"
      },
      {
        "code": "temp_unit_convert",
        "name": "温标切换",
        "type": "Enum",
        "values": "{\"range\":[\"c\",\"f\"]}"
      },
      {
        "code": "battery_state",
        "name": "电池电量状态",
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"middle\",\"high\"]}"
      },
      {
        "code": "battery_percentage",
        "name": "电池电量",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1685966652979,
  "tid": "1606f1be039911eeac8032ebdb7f4f6c"
}

**Comment by kde1806** [comment]
Hi in the end of the day yes I only like to get the support for the sensors. What kind of information you need?

**Comment by make-all** [comment]
All the information listed in the New Device template that you should be presented when opening a new request.

**Comment by make-all** [comment]
It is not possible to support this device without local protocol information
