### ISSUE TITLE
"HCT-611 WiFi Water Timer" not detected properly

### ISSUE THREAD

**Issue by spanzetta** [make-all/tuya-local#771]
See logs below..
The device is not detected as Water Timer (there is a specific config file named "ble_hct611_watertimer.yaml") but as "ASC wifi circuit breaker"

I also noticed that even if I installed 2023.5.2.. in the log I read 2022.5.2.. 
Do you know why?

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.5.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.11",
    "docker": true,
    "arch": "armv7l",
    "timezone": "Europe/Rome",
    "os_name": "Linux",
    "os_version": "6.1.21-v7",
    "supervisor": "2023.04.1",
    "host_os": "Home Assistant OS 10.2",
    "docker_version": "23.0.6",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "ezviz_plug": {
      "version": "1.0.0",
      "requirements": []
    },
    "sonoff": {
      "version": "3.5.1",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "tuya_local": {
      "version": "2022.5.2",
      "requirements": [
        "pycryptodome~=3.17",
        "tinytuya==1.12.7"
      ]
    },
    "midea_dehumidifier": {
      "version": "2.0.2",
      "requirements": [
        "midea-python-client==1.0.2"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya_local",
    "name": "Tuya Local",
    "codeowners": [
      "@make-all"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/make-all/tuya-local",
    "integration_type": "device",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/make-all/tuya-local/issues",
    "requirements": [
      "pycryptodome~=3.17",
      "tinytuya==1.12.7"
    ],
    "version": "2022.5.2",
    "is_built_in": false
  },
  "data": {
    "name": "Irrigatore",
    "type": "asc_wifi_circuit_breaker",
    "device_id": "**REDACTED**",
    "device_cid": "**REDACTED**",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": 3.3,
    "api_version_set": 3.3,
    "api_version_used": 3.3,
    "api_working": true,
    "status": {},
    "cached_state": {
      "updated_at": 1686057348.059441,
      "1": false,
      "7": 5,
      "8": "high",
      "13": "cloudy",
      "14": false,
      "110": false
    },
    "pending_state": {},
    "connected": true,
    "force_dps": [],
    "home_assistant": {
      "name": "Irrigatore",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "current",
          "icon": null,
          "unit_of_measurement": "A",
          "state": {
            "entity_id": "sensor.irrigatore_current",
            "state": "unknown",
            "attributes": {
              "unit_of_measurement": "A",
              "device_class": "current",
              "friendly_name": "Irrigatore Current"
            },
            "last_changed": "2023-06-06T13:14:45.291566+00:00",
            "last_updated": "2023-06-06T13:14:45.291566+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "voltage",
          "icon": null,
          "unit_of_measurement": "V",
          "state": {
            "entity_id": "sensor.irrigatore_voltage",
            "state": "unknown",
            "attributes": {
              "unit_of_measurement": "V",
              "device_class": "voltage",
              "friendly_name": "Irrigatore Voltage"
            },
            "last_changed": "2023-06-06T13:14:45.293919+00:00",
            "last_updated": "2023-06-06T13:14:45.293919+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "power",
          "icon": null,
          "unit_of_measurement": "W",
          "state": {
            "entity_id": "sensor.irrigatore_power",
            "state": "unknown",
            "attributes": {
              "unit_of_measurement": "W",
              "device_class": "power",
              "friendly_name": "Irrigatore Power"
            },
            "last_changed": "2023-06-06T13:14:45.295940+00:00",
            "last_updated": "2023-06-06T13:14:45.295940+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": "min",
          "state": {
            "entity_id": "number.irrigatore_countdown",
            "state": "0.0833333333333333",
            "attributes": {
              "min": 0.0,
              "max": 1440.0,
              "step": 1.0,
              "mode": "auto",
              "unit_of_measurement": "min",
              "icon": "mdi:timer",
              "friendly_name": "Irrigatore Countdown"
            },
            "last_changed": "2023-06-06T13:14:45.302271+00:00",
            "last_updated": "2023-06-06T13:14:45.302271+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "switch",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.irrigatore",
            "state": "off",
            "attributes": {
              "device_class": "switch",
              "friendly_name": "Irrigatore"
            },
            "last_changed": "2023-06-06T13:14:45.303648+00:00",
            "last_updated": "2023-06-06T13:14:45.303648+00:00"
          }
        }
      ]
    }
  }
}

**Comment by make-all** [comment]
The logs show dps 10 (weather_delay), 11 (countdown), 12 (work_state) are missing from the local status messages. 

Additional dps 14 and 110 are present, but the function is unknown.  You may be able to find a name for these in the Device Debugger on iot.tuya.com (see https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html for more details about this).

**Comment by spanzetta** [comment]
What about version reported?
_"tuya_local": {
"version": "2022.5.2",_
Shouldn't be 2023.5.2 ??

**Comment by spanzetta** [comment]
See details about 110 (Google Translate = Switch records)
Below is 14 (Smart Weather switch)
Do you know now how to modify the config file? 
Thanks

![image](https://github.com/make-all/tuya-local/assets/49818743/f6ec9830-9589-47c2-be47-7bcfacc47662)
![image](https://github.com/make-all/tuya-local/assets/49818743/4cf8a1d2-59a4-47f3-9c7c-0d19162fc18a)

**Comment by make-all** [comment]
I'm not sure what that does, but since this integration does not use the cloud API, I don't think it will be affected (but the standard tuya integration and mobile app may be affected).

**Comment by spanzetta** [comment]
Many thanks!

Do you think that you can enable support also for the **Timer Programs** (up to 8) as "read only"?

Their pids are 
101 Program P1
102 Program P2
........
107 Program P7
108 Program P8

(but not sure if they are available without changing mode - see my previous post about "Standard instructions" vs "DP instructions")

Thanks again

**Comment by spanzetta** [comment]
Another thing.. do you think you can enable support also for the **Gateway** (as readonly data to be shown in HA)?

These are some details I read on Tuya cloud
_I was mainly interested to read the RSI signal level (usefull to know) that I can read in SmartLife app.. but cannot find here (continue to search)_

Request URLCopy
curl --request GET "https://openapi.tuyaeu.com/v1.0/devices/bfc857c6b09c82e72a2aeg" --header "sign_method: HMAC-SHA256" --header "client_id: jwk9e4nr5v37vtgf3qqv" --header "t: 1686130890133" --header "mode: cors" --header "Content-Type: application/json" --header "sign: 04CA86079DDAC40DED662B509EFE2B2D2CDB68BDF330FE23E1A4DCB513BDAA6B" --header "access_token: 76242f4913be0272d36a04ff787189cf"
ResponseCopy
{
  "result": {
    "active_time": 1681484089,
    "biz_type": 18,
    "category": "wg2",
    "create_time": 1681484089,
    "icon": "smart/icon/bay1588755969426Gamy/b9a281989e5d134cd4e41a3549c51fbb.jpg",
    "id": "bfc857c6b09c82e72a2aeg",
    "ip": "80.116.52.20",
    "lat": "45.6013",
    "local_key": "4e163d9cfcbd16df",
    "lon": "9.4193",
    "model": "HCG-001",
    "name": "BT Gateway",
    "online": true,
    "owner_id": "37640186",
    "product_id": "oqjyih6d",
    "product_name": "Bluetooth Gateway",
    "status": [],
    "sub": true,
    "time_zone": "+02:00",
    "uid": "eu1631964264000CXOhB",
    "update_time": 1686117596,
    "uuid": "4ecd3a79fde51796"
  },
  "success": true,
  "t": 1686130890323,
  "tid": "7b10f99f051711eeac8032ebdb7f4f6c"
}

**Comment by spanzetta** [comment]
Urrah!!
With the updated config file (manually copied from githun to my HA) it now detects it properly..
And I see the most important data (still have to test if it works really on the device.. but I assume yes!)

Really really happy!!!

See below!

![image](https://github.com/make-all/tuya-local/assets/49818743/2d95fc11-2c4d-4acc-b323-4727bdcedd61)

![image](https://github.com/make-all/tuya-local/assets/49818743/99b7cee0-d102-436c-8cd1-5ac1c85b3238)

**Comment by spanzetta** [comment]
All comands are reported (into logs) as "device itself"

Still have to understand how the Timer (Countdown) is suppsed to work ..

![image](https://github.com/make-all/tuya-local/assets/49818743/e47b18ad-699c-4b04-b31b-7fb464969b0f)

**Comment by spanzetta** [comment]
And "weather delay" apparently doesn't work

**Comment by make-all** [comment]
I forgot to tag this issue, but I added the newly discovered dps.

For the hub itself, you will need to make a report with local logs, the same as with this device.  The cid will be blank.

But I am not sure whether the current implementation is able to support the hub and subdevice at the same time.   Subdevice support is quite recent, and not all bugs are yet found and fixed.  When I tried it some time ago, a hub that was already configured in HA was not able to configure any subdevices, as they appeared as duplicates to HA.  One fix was submitted since then, and maybe it fixes that, but I have not had time to try again.

**Comment by make-all** [comment]
The timer is configured to allow setting and showing 1 minute resolution. Typically the Tuya mobile app will only allow setting timers in 1 hour or 30 minute increments, so this is still more precision than you get from that.  Allowing 1 second precision would be misleading, because we cannot guarantee the timing that accurately, and the device does not report every second ticking down, so would just lead to bug reports that are limitations of the technology.
Based on the diagnostics, your timer has 2 seconds left.  I wonder if this device is not reporting 0 values, and that was the last update it gave before the timer expired.   I would expect the timer to turn the valve off when it expires (or maybe it will toggle on if the timer started with the valve off).

The program attributes can be seen in the diagnostics output, they are set as attributes on the main switch, so you should be able to see them in the Developer Tools, and read them as attributes in automations etc.  Since the format is unknown, I did not think they were useful to break out into separate entities.

**Comment by spanzetta** [comment]
I confirm that Programs are visible as attributes of the switch

![Screenshot_20230608_065336_Home Assistant](https://github.com/make-all/tuya-local/assets/49818743/cb2f3b4f-a3ee-4da0-8561-e8d1fa8d3013)

**Comment by spanzetta** [comment]
I think I found the way to interpreter the Program if is SET but ON or OFF and not SET

Maybe you can improve this functionality to show, as attributes, these word instead of the code?

Program 1 - fwcAALR = ON - AAcAALR = OFF
Program 2 - fw8AALR = ON - AA8AALR/ = OFF
Program 3 - fxUAALR = ON - ABUAALR/ = OFF
Program X - AA==		Not set

Am I asking too much? ;-)

Thanks anyway...

**Comment by fcrozat** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/16671 contains some info on those attributes. It would be better to completely reverse engineering this part of the protocol, but this is non trivial.

Moreover, it is unclear if it relies on Tuya cloud or not.

**Comment by spanzetta** [comment]
> Moreover, it is unclear if it relies on Tuya cloud or not.

I can tell you that when I change the value from the Smartlife app .. I can read in the Cloud logs the changes.. (and as device itself I think it refers to HA that reads those data)

Here we are talking about "just" showing if the Program is ON/OFF/Not Set

Thanks

![image](https://github.com/make-all/tuya-local/assets/49818743/46bf5989-a573-4b5d-9ef5-9b6ecfa1eb3b)

**Comment by spanzetta** [comment]
> For the hub itself, you will need to make a report with local logs, the same as with this device. The cid will be blank.
> 
> But I am not sure whether the current implementation is able to support the hub and subdevice at the same time. Subdevice support is quite recent, and not all bugs are yet found and fixed. When I tried it some time ago, a hub that was already configured in HA was not able to configure any subdevices, as they appeared as duplicates to HA. One fix was submitted since then, and maybe it fixes that, but I have not had time to try again.

I tried to add the Gateway in order to be able to collect logs .. but it fails..

I am using the following data:
- DeviceID of the Gateway (that's sure)
- IP Address (it's the same of when I configured the Valve as sub-device.. )
- LocalKey of the Gateway (that's sure)
- Subdevice = empty
- I get as result "cannot connect.... " (tried also wit "Poll only")
:-(
Any hints ?

**Comment by make-all** [comment]
It depends on the exact error message, but as I wrote above "I am not sure whether the current implementation is able to support the hub and subdevice at the same time."

**Comment by make-all** [comment]
OK, based on that log, it was able to connect to the hub, so the conflict between subdevices and hub seems to be fixed.

The problem is that the hub is not returning any data.  So there is nothing to match against, and nothing that could be displayed in HA if it was implemented.  That signal strength must be cloud only.

**Comment by spanzetta** [comment]
ok clear..

What about the possibility to show ON/OFF/not SET (for Program) based on my list above?

Thanks

**Comment by make-all** [comment]
I think the not SET is easy enough to pull out, as it is a single value (corresponding to a single null character if you decode that base64 data).  But the distinction between on and off is not so easy to make without understanding the actual format of the binary data.

**Comment by spanzetta** [comment]
Hi agree that decoding it is not easy.. but I was not talking about showing the "program data" (eg all day from 7:00 to 8:00 etc) but simply.. ON, OFF based on the difference between the "know" data ..
Anyway.. I managed myself by creating template sensors that shows them (I always use the same 3 programs).. and it works fine.. See screenshots below (it matches the Smartlife app Program settings in realtime.. it's amazing!)

As recap about the sensors created so far for this device:

1) Main switch - IT WORKS fine.. that's the important one as gives the possibility to create automations/notifications ecc ... very good!
2) Battery level - IT WORKS
3) Smart Weather switch - Apparently it works (still to know what it should do) even if sometimes I set it ON.. and then after a while I see it OFF - WHen it works I can verify on Tuya Cloud that it's set on..
4) Smart Weather - I think it should be a "read only" value.. while currently it's a drop down list (so it seems you can change the value.. but it has no sense to change it)..
5) Weather Delay - Apparently IT DOESN'T work.. but also here it's not clear what it should do/what it does (well.. I know what it should do: it should skip the next Program cycle based on the delay that you set).. But I reserve to more testing with it
6) Counter/Timer: it doesn't work at all..

That's all for now

Thanks again for all of your effort to make this device working with HA 

![image](https://github.com/make-all/tuya-local/assets/49818743/d2d7782c-6aa7-421e-9464-e3ab12d17d8c)

![image](https://github.com/make-all/tuya-local/assets/49818743/931bc6cc-9aee-46ea-917d-724229ac00bd)

**Comment by make-all** [comment]
I suggest to read the link from @fcrozat above.  It had some information about some of the specific pre-conditions for some of the dps to work as expected.

I don't think the "smart weather" forecast is coming from the device itself, and therefore is not read-only (it was listed under "functions" in the portal information).  Probably the cloud is driving it, and you can basically ignore it for local use, but I_ suspect if the device was blocked from accessing the cloud, then setting those would probably work as expected, and it is only that it is fighting against the cloud that is causing it to appear not to work now.

**Comment by spanzetta** [comment]
At this point I can close the ticket..
I am very satisfied about the obtained result..
Thanks a lot again

**Comment by make-all** [comment]
I prefer to leave them open with the unreleased tag until the release is actually made.  But thanks for confirming.

**Comment by spanzetta** [comment]
Ok..

**Comment by spanzetta** [comment]
Tonight the integration stopped working.. this morning I updated it to latest version just released but the device continues to be unavailable.. no idea why (Smartlife see it online)
Will have to understand what did happen

**Comment by make-all** [comment]
Maybe this is normal for devices connected via hubs.  The hub does not have any data until it is triggered by something trying to connect to the device.  This is probably useful information for the connection problems thread.
