### ISSUE TITLE
Request support for teckin smart plug sp21

### ISSUE THREAD

**Issue by xXMuffinmanXx** [make-all/tuya-local#772]
```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:46
Integration: Tuya Local (documentation, issues)
First occurred: 15:02:34 (2 occurrences)
Last logged: 15:06:11

Connection test failed with <class 'Exception'> Unable to find device on network (specify IP address)

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:81
Integration: Tuya Local (documentation, issues)
First occurred: 15:02:34 (2 occurrences)
Last logged: 15:06:10

<class 'Exception'>: Unable to find device on network (specify IP address) while initialising device 30737286b4e62d5b7120
```

```
{
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "switch_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 11,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ],
    "lang_config": {},
    "status": [
      {
        "code": "switch_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 11,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1686143689760,
  "tid": "4829d8ff053511eea4908a3120fb3e2a"
}
```

{
  "result": {
    "active_time": 1686069572,
    "category": "cz",
    "category_name": "Socket",
    "create_time": 1572711572,
    "gateway_id": "",
    "icon": "smart/icon/152956414744qw5qx565_0.jpg",
    "id": "30737286b4e62d5b7120",
    "ip": "87.165.231.51",
    "lat": "48.4810",
    "local_key": 
    "lon": "9.2077",
    "model": "SP21/SE131",
    "name": "Nachttischlampe",
    "online": true,
    "owner_id": "32290276",
    "product_id": "r15JnoGqWPM4PPtl",
    "product_name": "smart socket",
    "sub": false,
    "time_zone": "+01:00",
    "update_time": 1686069576,
    "uuid": "30737286b4e62d5b7120"
  },
  "success": true,
  "t": 1686136982640,
  "tid": "aa623d7a052511eea4908a3120fb3e2a"
}

# Information about how the device functions

https://manuals.plus/m/a893623c62b42beec2d77297e993db4e1259c04bcc7635218636b90f75ddfc86_optim.pdf

**Comment by make-all** [comment]
The config file simple_switch_timer already covers this device.  But you'll have to sort out your connection issues first.
