### ISSUE TITLE
I've created Air Humidifier WetAir WAW-H1210LW yaml

### ISSUE THREAD

**Issue by bob-tm** [make-all/tuya-local#78]
"dps":{
	"1":true,		// Main switch
	"5":true,		// Led 
	"8":true,		// Sound (beeps on commands)
	"13":50,		// humidity_set (zero for non "AUTO" mode)
	"14":57,		// humidity_current
	"22":0,		// unknown 
	"24":"AUTO",	// { "AUTO", "MIDDLE", "HIGH", "SLEEP" }	
	"25":true,		// Anion
	"29":false,        // Child lock
	"101":"Have_water" // {"No_water", "Have_water", "Full_water"}
}

I have created and attached yaml (github do not support yaml attachments, please rename txt to yaml :)  file. Everything works fine for me.

I'm not shure how to name pid 101 field. I place it under humidifier and named "error" (like in other humidifier yaml).  But "water_status" has more sense. 

Please add it to release with or without modifications. 
 
[wetair_waw_h1210lw_humidifier.txt](https://github.com/make-all/tuya-local/files/7591058/wetair_waw_h1210lw_humidifier.txt)

**Comment by bob-tm** [comment]
I found a problem while adding second my WetAir Humidifier.
I add integration, put ip, local_key and device_id. 
First humidifier was detected with two options {"switch", "WetAir WAW-H1210LW"}
But second one always detected as "switch" with some messages in log:

2021-11-23 23:35:18 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches simple_switch with quality of 11%. DPS: {'1': True, '5': True, '8': True, '13': 55, '14': 52, '22': 0, '24': 'AUTO', '25': False, '101': 'Full_water', 'updated_at': 1637703314.7812483}
2021-11-23 23:35:18 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/

How I can fix this?

**Comment by make-all** [comment]
It seems the child lock is missing on this second one (or many it is only reported in a certain state).

I haven't yet introduced a way to mark things as optional, but maybe this is one of those cases.  Unless the model is slightly different and the features of this one are actually missing the child lock, in which case, two configs for the different models is probably best.

**Comment by bob-tm** [comment]
toggle child-lock and second device is detected. tnx! 

There are a lot of devices. Always something will be going wrong :)
Sometimes manual yaml assign will be the best solution!

**Comment by bob-tm** [comment]
Updated version. 
Added separate sensor for Current Humidity.
[wetair_waw_h1210lw_humidifier.yaml.txt](https://github.com/make-all/tuya-local/files/7595115/wetair_waw_h1210lw_humidifier.yaml.txt)

**Comment by bob-tm** [comment]
everything ok
