### ISSUE TITLE
Request support for [Nedis/Tuya Air Conditioner]

### ISSUE THREAD

**Issue by Xpl0jd** [make-all/tuya-local#781]
# Log Message

```
Device not yet added to HA since not supported.
```

# Information about DPS mappings

```
Output as in Response or Request, this is the Response, please clarify in Template.
{
  "code": 28841002,
  "msg": "No permissions. Your subscription to cloud development plan has expired.",
  "success": false,
  "t": 1686403449551,
  "tid": "1513c78c079211eeac8032ebdb7f4f6c"
}
```

# Product ID
 "product_id": "vrredpnf22yayvhi",

# Information about how the device functions

Air Conditioner Functions
Turn ON/OFF
Measure real time Temp
Set target temp for AC
Change between 3 Modes, "Cool, Dry, Fan"
Set fan speed "low, medium, high"
Activate Automatic swing function for change airflow direction

I understand i give very bad and crappy information since im new to the whole Smart Home scene and still trying to learn.
I can also show or give more info here or via Discord if i know what im going to look for.

Here is the device sold in Sweden
https://www.webhallen.com/se/product/306482-Nedis-Barbar-luftkonditionering-AC-12-000-BTU-WIFI-Energiklass-A-Fjarrkontroll-Timerfunk

This is the Company homepage of the device.
https://nedis.co.uk/en-gb/product/home-living/climate/air-conditioners/550681737/mobile-air-conditioner-12000-btu-100-m3-3-speed-remote-control-shut-off-timer-white

**Comment by make-all** [comment]
Without local protocol information there is nothing to be done here.
Please refile after you get your tuya account reactivated so you can get access to your local key and API explorer for pulling down the device instruction set (preferably the using the API command that returns dpId as documented in the README.md and new device template)
