### ISSUE TITLE
Adding Weau Invertor, unable to connect

### ISSUE THREAD

**Issue by pergolafabio** [make-all/tuya-local#786]
**Describe the bug**
Hi, i already use LocalTuya, but seems Weau was not supported, so want to try this tuyalocal instead, but i have issues adding the device? see screenshot below

The local key / device ID are correct, also the IP, since it works in localtuya, but only the swith is there discovered
i want to use then full climate options

Not sure how to download diagnostics, since i'm unable to add the device?

![image](https://github.com/make-all/tuya-local/assets/43251136/1beb5b15-b3dd-4e0c-afc3-b460cfb1c7e9)

**Comment by make-all** [comment]
See #522 for resolving connection issues.

**Comment by pergolafabio** [comment]
Ah, maybe the connection was indeed in use by localtuya,  gonna try again later, thnx

**Comment by pergolafabio** [comment]
hmm, tried everything, removed the device from localtuya
restarted HA, rebooted eve my router AP to make sure that all connections are dropped, but still receive same error
if i add with localtuya after, then it just works
