### ISSUE TITLE
missing "repository.json"

### ISSUE THREAD

**Issue by Saentist** [make-all/tuya-local#8]
To be added as repo in home assistence need to have in root  **repository.json** with following  content:

```
{
    "name": "tuya-local add-on",
    "url": "https://github.com/make-all/tuya-local",
    "maintainer": "Jason Rumney <your@mail.addres>"
}
```

**Comment by make-all** [comment]
This is not an add-on.  Add-on's are separate docker containers that run separate applications from Home Assistant.

This is a custom component.  The easiest way to manage custom components is using the HACS custom component from https://hacs.xyz/
