### ISSUE TITLE
Request for suport for Smart-Star-Projector

### ISSUE THREAD

**Issue by SergioFuchs** [make-all/tuya-local#804]
I think is the same as Smart Galaxy Projector https://github.com/make-all/tuya-local/issues/770

But when I added to HA is missing the laser part of the new device

Thanks 

curl --request GET "https://openapi.tuyaus.com/v1.1/iot-03/devices/ebfb24f700379d6945oqc9" --header "sign_method: HMAC-SHA256" --header "client_id: 3xade3v4bi6ba8yhyjj4" --header "t: 1686861133486" --header "mode: cors" --header "Content-Type: application/json" --header "sign: D52DC0516532F3C4DD49D7314768BBBB45A648F0ADF6C4EEB4ED0443B6B658C5" --header "access_token: 4c727adaadef28f296af46fecfae1c77"

{
  "result": {
    "category": "dj",
    "functions": [
      {
        "code": "switch_led",
        "dp_id": 20,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "dp_id": 21,
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"
      },
      {
        "code": "bright_value_v2",
        "dp_id": 22,
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "colour_data_v2",
        "dp_id": 24,
        "type": "Json",
        "values": "{\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}"
      },
      {
        "code": "scene_data_v2",
        "dp_id": 25,
        "type": "Json",
        "values": "{\"scene_num\":{\"min\":1,\"scale\":0,\"max\":8,\"step\":1},\"scene_units\": {\"unit_change_mode\":{\"range\":[\"static\",\"jump\",\"gradient\"]},\"unit_switch_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"unit_gradient_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"bright\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"temperature\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}}"
      },
      {
        "code": "countdown_1",
        "dp_id": 26,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch_led",
        "dp_id": 20,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "dp_id": 21,
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"
      },
      {
        "code": "bright_value_v2",
        "dp_id": 22,
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "colour_data_v2",
        "dp_id": 24,
        "type": "Json",
        "values": "{\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}"
      },
      {
        "code": "scene_data_v2",
        "dp_id": 25,
        "type": "Json",
        "values": "{\"scene_num\":{\"min\":1,\"scale\":0,\"max\":8,\"step\":1},\"scene_units\": {\"unit_change_mode\":{\"range\":[\"static\",\"jump\",\"gradient\"]},\"unit_switch_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"unit_gradient_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"bright\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"temperature\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}}"
      },
      {
        "code": "countdown_1",
        "dp_id": 26,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1686862163181,
  "tid": "1bb580a50bbe11eebfceda94faf43880"
}

**Comment by make-all** [comment]
The information above is just a standard RGBW lightbulb, there are no datapoints for a laser.

**Comment by SergioFuchs** [comment]
This is the device, the basic version, there's no dpi for the laser but it shows on smartlife app

https://pt.aliexpress.com/item/1005002135993671.html?spm=a2g0o.order_list.order_list_main.12.21efcaa4LZtAps&gatewayAdapt=glo2bra


{
  "result": {
    "active_time": 1682643773,
    "category": "dj",
    "category_name": "Light Source",
    "create_time": 1638997592,
    "gateway_id": "",
    "icon": "smart/icon/ay149682747096840kwW/56df5e11d53922816403db387309e9fc.png",
    "id": "ebfb24f700379d6945oqc9",
    "ip": "138.94.180.215",
    "lat": "-27.6543",
    "local_key": "057b6ae5cbbf5e01",
    "lon": "-54.2860",
    "model": "SK20",
    "name": "Projetor Tuya",
    "online": true,
    "owner_id": "41145990",
    "product_id": "cw7kinnselbesfp9",
    "product_name": "Smart-Star-Projector ",
    "sub": false,
    "time_zone": "-03:00",
    "update_time": 1686862147,
    "uuid": "1505865d062a4641"
  },
  "success": true,
  "t": 1686874176870,
  "tid": "1467c8240bda11ee9d71220dd637f8d3"
}
