### ISSUE TITLE
Request support for wifi smart energy meter

### ISSUE THREAD

**Issue by robertrebor** [make-all/tuya-local#809]
# Log Message

```
Please paste logs here
```

# Information about DPS mappings

```
{
  "result": {
    "category": "zndb",
    "functions": [
      {
        "code": "forward_energy_total",
        "dp_id": 1,
        "type": "Integer",
        "values": "{\"unit\":\"kW·h\",\"min\":0,\"max\":99999999,\"scale\":2,\"step\":1}"
      },
      {
        "code": "reverse_energy_total",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"kW·h\",\"min\":0,\"max\":99999999,\"scale\":2,\"step\":1}"
      },
      {
        "code": "energy_month",
        "dp_id": 3,
        "type": "Json",
        "values": "{}"
      },
      {
        "code": "energy_daily",
        "dp_id": 4,
        "type": "Json",
        "values": "{}"
      },
      {
        "code": "frozen_time_set",
        "dp_id": 11,
        "type": "Json",
        "values": "{}"
      },
      {
        "code": "switch",
        "dp_id": 16,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "alarm_set_2",
        "dp_id": 17,
        "type": "Json",
        "values": "{}"
      },
      {
        "code": "event_clear",
        "dp_id": 20,
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "lang_config": {},
    "status": [
      {
        "code": "forward_energy_total",
        "dp_id": 1,
        "type": "Integer",
        "values": "{\"unit\":\"kW·h\",\"min\":0,\"max\":99999999,\"scale\":2,\"step\":1}"
      },
      {
        "code": "reverse_energy_total",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"kW·h\",\"min\":0,\"max\":99999999,\"scale\":2,\"step\":1}"
      },
      {
        "code": "energy_month",
        "dp_id": 3,
        "type": "Json",
        "values": "{}"
      },
      {
        "code": "energy_daily",
        "dp_id": 4,
        "type": "Json",
        "values": "{}"
      },
      {
        "code": "phase_a",
        "dp_id": 6,
        "type": "Json",
        "values": "{}"
      },
      {
        "code": "fault",
        "dp_id": 10,
        "type": "Bitmap",
        "values": "{\"label\":[\"ov_cr\",\"unbalance_alarm\",\"ov_vol\",\"undervoltage_alarm\",\"miss_phase_alarm\",\"outage_alarm\",\"magnetism_alarm\",\"terminal_alarm\",\"cover_alarm\",\"credit_alarm\",\"no_balance_alarm\",\"battery_alarm\",\"meter_hardware_alarm\"]}"
      },
      {
        "code": "frozen_time_set",
        "dp_id": 11,
        "type": "Json",
        "values": "{}"
      },
      {
        "code": "switch",
        "dp_id": 16,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "alarm_set_2",
        "dp_id": 17,
        "type": "Json",
        "values": "{}"
      },
      {
        "code": "meter_id",
        "dp_id": 18,
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "event_clear",
        "dp_id": 20,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "forward_energy_t1",
        "dp_id": 21,
        "type": "Integer",
        "values": "{\"unit\":\"kW·h\",\"min\":0,\"max\":99999999,\"scale\":2,\"step\":1}"
      },
      {
        "code": "forward_energy_t2",
        "dp_id": 22,
        "type": "Integer",
        "values": "{\"unit\":\"kW·h\",\"min\":0,\"max\":99999999,\"scale\":2,\"step\":1}"
      },
      {
        "code": "forward_energy_t3",
        "dp_id": 23,
        "type": "Integer",
        "values": "{\"unit\":\"kW·h\",\"min\":0,\"max\":99999999,\"scale\":2,\"step\":1}"
      },
      {
        "code": "forward_energy_t4",
        "dp_id": 24,
        "type": "Integer",
        "values": "{\"unit\":\"kW·h\",\"min\":0,\"max\":99999999,\"scale\":2,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1686916732218,
  "tid": "2961a3fc0c3d11eebfbfa24bf1d21c99"
}
```

# Product ID

bfb42a9c2610c8e5edy8um

# Information about how the device functions
Additional information to standard status set:
https://developer.tuya.com/en/docs/iot/1?id=Ka8mx9cl5zolg

**Comment by make-all** [comment]
Log messages are needed to confirm the local dps format matches the cloud docs.

Also, the product id appears to be a different format than usual, are you sure it came from the product_id field of the device details.

**Comment by robertrebor** [comment]
@make-all  I am sorry for my long inactivity.  Provided Device ID is correct ( I am sending screenshot from IoT tuya ) 
<img width="315" alt="image" src="https://github.com/make-all/tuya-local/assets/114231763/09ae8c77-044c-4d2e-9480-86dddd525354">


I don't understand what you mean "Log messages are needed to confirm the local dps format matches the cloud docs." and how can I send it to you.

**Comment by make-all** [comment]
This is the device id, which is unique to your particular device.  For the config, it is the product id that is needed, which in the iot..tuya.com site is found in the results of some of the API Explorer functions that get information about the device (usually the same functions that tell you the local key).

For the logs, the Home Assistant log is under Settings / System / Logs.  You should get a message there when you try to add tthe device using the device id above, local key, and IP address, and either get a list of not really matching devices to choose from, or a message saying no devices match.

**Comment by robertrebor** [comment]
@make-all  thank you for prompt answer. from IoT I am sending picture, I hope that product ID correspond with the device ID: opdhepy0p7eyeurz, or not?
<img width="509" alt="image" src="https://github.com/make-all/tuya-local/assets/114231763/19cc0882-95f8-4b78-bae8-b62a1423fbff">
When I tried to add smart meter I get this message:
<img width="300" alt="image" src="https://github.com/make-all/tuya-local/assets/114231763/ac82e1d0-0200-4d4f-ade2-66b3384bbf03">

this is what i get in logs:
2023-10-17 15:40:30.351 ERROR (MainThread) [custom_components.tuya_local.device] <class 'OSError'>: [Errno 98] Address in use while initialising device opdhepy0p7eyeurz
2023-10-17 15:40:30.359 WARNING (MainThread) [custom_components.tuya_local.config_flow] Connection test failed with <class 'OSError'> [Errno 98] Address in use
