### ISSUE TITLE
BHT-002 with external sensor

### ISSUE THREAD

**Issue by floxboy** [make-all/tuya-local#81]
is it possible to add an external temperature sensor for the thermostat BHT-002?
while researching the integration Tuya local, I found that it will be returned in parameter 102
if I can help you, then I am ready

**Comment by make-all** [comment]
It is already supported. The config without external sensor was actually made later when it was discovered some devices didn't work with the existing config.

**Comment by make-all** [comment]
If your device is not working with the existing config with external sensor, then please report the log messages from the time you try to add it, as they will contain info about the dps returned by the device, so I can compare with the existing configs to see if yours is missing something else to explain why it does not match the config.

**Comment by floxboy** [comment]
Yes. I chose for MOES BHT-002  the template  beca_bht002_thermostat_c and an external temperature sensor appeared
it works!
thanks!
