### ISSUE TITLE
Receive loop has terminated

### ISSUE THREAD

**Issue by itn3rd77** [make-all/tuya-local#817]
**Describe the bug**
After a certain amount of time one of my Tuya devices stops responding to commands. The device seems to be blocked by something as even operating the device itself via buttons e.g. increase fan speed doesn't work anymore. What still works is turning the device off/on via integration and on the device itself. After on/off cycle the device operates again for some time until the error shows up again.

The only thing I see and seems to cause the problem is the message regarding the device: ```Receive loop has terminated````

I only have two Tuya devices and only the second aka last one added has this problem.

**To Reproduce**
Just have to wait a certain amount of time.

**Expected behavior**
Device works normaly ;-)

**Additional context**
```
Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:225
Integration: Tuya Local (documentation, issues)
First occurred: 18. Juni 2023 um 14:00:01 (36 occurrences)
Last logged: 07:30:02

Luftbefeuchter Schlafzimmer receive loop has terminated
```

[tuya_local-d7a63504204d3bc0f83926aac762ec14-Luftbefeuchter Schlafzimmer-03c430ed559d2c772d44d98d45550cb1.json.txt](https://github.com/make-all/tuya-local/files/11785032/tuya_local-d7a63504204d3bc0f83926aac762ec14-Luftbefeuchter.Schlafzimmer-03c430ed559d2c772d44d98d45550cb1.json.txt)

**Comment by itn3rd77** [comment]
Hi,

I can try that but I doubt it is an incorrect mapping. The two Tuya devices I own are the devices from my PR #743. One is a Stadler Form Karl and the other a Stadler Form Karl big. Both device have exact the same hardware Buttons and according to Tuya Cloud  have the same definitions. I triggered every control or configuration handle in Home ASsistant and the device reacts exactly the same as if I would use the buttons on the device itself (without an error happening). The error just happens out of nowhere when I leave the device untouched.

**Comment by TTLucian** [comment]
Same for me. I have a Fairland pool heater and the behaviour is exactly as described in op.

**Comment by make-all** [comment]
This issue needs debug logs to proceed further

**Comment by make-all** [comment]
I have investigated, and the only things that can cause the receive loop to be terminated are an HA shutdown and the integration being reloaded.  The latter may be happening for some other reason, but I need the debug log to see what it might be/

I do see this message when enabling debug logging for the integration, as it is automatically reloaded with the new log settings then, but the connection is re-established and this doesn't cause any lasting effect in that case.

**Comment by escoand** [comment]
I've the same problem with different Tuya devices. I've created an automation reloading the config entry. But this is happening only now an than. Is there maybe a way to automatically recover in this case?
