### ISSUE TITLE
Request support for Smart power strip pro 4 outlet + USB

### ISSUE THREAD

**Issue by 007Nexus** [make-all/tuya-local#819]
# Information about DPS mappings

{
  "result": {
    "category": "pc",
    "functions": [
      {
        "code": "switch_1",
        "desc": "{}",
        "name": "开关1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_2",
        "desc": "{}",
        "name": "开关2",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_3",
        "desc": "{}",
        "name": "开关3",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_4",
        "desc": "{}",
        "name": "开关4",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_usb1",
        "desc": "{}",
        "name": "USB1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "name": "开关1倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_2",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "name": "开关2倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_3",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "name": "开关3倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_4",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "name": "开关4倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_usb1",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "name": "USB1倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "name": "开关1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_2",
        "name": "开关2",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_3",
        "name": "开关3",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_4",
        "name": "开关4",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_usb1",
        "name": "USB1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "name": "开关1倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_2",
        "name": "开关2倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_3",
        "name": "开关3倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_4",
        "name": "开关4倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_usb1",
        "name": "USB1倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1687209009591,
  "tid": "ac38606f0ee511ee927c56f414dcf3dd"
}

# Product ID

{
  "code": 1106,
  "msg": "permission deny",
  "success": false,
  "t": 1687209513787,
  "tid": "d8ccdb330ee611ee927c56f414dcf3dd"
}

# Information about how the device functions

https://www.aliexpress.com/item/1005001849380500.html?spm=a2g0o.productlist.main.83.10d5359afJRi7W&algo_pvid=0f77ea24-8f85-4727-9944-1e6db7d996d0&algo_exp_id=0f77ea24-8f85-4727-9944-1e6db7d996d0-41&pdp_npi=3%40dis%21EUR%2154.65%2133.58%21%21%21%21%21%402100ba4716872097169057746d074c%2112000017846971033%21sea%21NL%210&curPageLogUid=UoPHSrKqipin

**Comment by make-all** [comment]
With no log or local dps information, it is not possible to add support. But a similar device was just added in PR#860, so if the existing quad socket + USB configs do not match, there is a possibility that the new one may.
