### ISSUE TITLE
Request support for Royal Clima RCB 150

### ISSUE THREAD

**Issue by tariya-garker** [make-all/tuya-local#825]
# Log Message

```
Device matches desk_lamp with quality of 25%. DPS: {"updated_at": 1682250681.1077883, "1": true, "2": "Recirculation", "3": 0, "5": false, "11": 99, "12": "1", "13": false, "16": "cancel", "22": 29, "42": false, "101": "cancel", "102": 20}
```

# Information about DPS mappings

```
{
  "result": {
    "properties": [
      {
        "code": "switch",
        "custom_name": "",
        "dp_id": 1,
        "time": 1687197937588,
        "value": true
      },
      {
        "code": "mode",
        "custom_name": "",
        "dp_id": 2,
        "time": 1687016151049,
        "value": "Air_Supply"
      },
      {
        "code": "pm25",
        "custom_name": "",
        "dp_id": 3,
        "time": 1687366429570,
        "value": 0
      },
      {
        "code": "anion",
        "custom_name": "",
        "dp_id": 5,
        "time": 1687010124748,
        "value": false
      },
      {
        "code": "filter_life",
        "custom_name": "",
        "dp_id": 11,
        "time": 1687203405381,
        "value": 87
      },
      {
        "code": "fan_speed_enum",
        "custom_name": "",
        "dp_id": 12,
        "time": 1687346649286,
        "value": "1"
      },
      {
        "code": "filter_reset",
        "custom_name": "",
        "dp_id": 13,
        "time": 1687010124752,
        "value": false
      },
      {
        "code": "countdown_set",
        "custom_name": "",
        "dp_id": 16,
        "time": 1687010124753,
        "value": "cancel"
      },
      {
        "code": "temp_outdoor",
        "custom_name": "",
        "dp_id": 22,
        "time": 1687366095170,
        "value": 21
      },
      {
        "code": "heat",
        "custom_name": "",
        "dp_id": 42,
        "time": 1687010126991,
        "value": false
      },
      {
        "code": "countup_set",
        "custom_name": "",
        "dp_id": 101,
        "time": 1687010124795,
        "value": "cancel"
      },
      {
        "code": "Temperature_set",
        "custom_name": "",
        "dp_id": 102,
        "time": 1687010124804,
        "value": 20
      }
    ]
  },
  "success": true,
  "t": 1687370463454,
  "tid": "96435b26105d11ee9b65f25b5112df17"
}
```

# Product ID

      "product_id": "qcgxajmb0sdg608j",
      "product_name": "Royal Clima RCB 150",

# Information about how the device functions

This is a Fresh Air System with a heater and a sensor of pm 2.5. For the heater there is a power tuning line to which temperature to heat the incoming air. 6 speeds and 6 work programs (air supply, recycling, sleep, auto, eco, anti-condensate). there is also an inlet air temperature sensor
![2023-06-21 20-58-54](https://github.com/make-all/tuya-local/assets/117899721/882e361e-d014-4c78-a115-fec4c2423d93)
![2023-06-21 20-59-05](https://github.com/make-all/tuya-local/assets/117899721/56b23ff0-ce29-49c0-8e22-3f2ba59e04cf)
![2023-06-21 20-59-17](https://github.com/make-all/tuya-local/assets/117899721/4afb1bc0-52e0-41ca-8d80-e7b8cf14f9b9)

**Comment by make-all** [comment]
The range and possible enum value information is missing.  Tuya changed their portal around in the last couple of days, and I didn't realise that the first function I found that returns the dp id no longer returns the range info.  But there is another function at the bottom of that section that does seem to return everything needed for the dps, just labelled differently and not formatted nicely.

**Comment by tariya-garker** [comment]
tell me more precisely what the snag is? I don’t understand all this very well, but I want to help than possible

**Comment by make-all** [comment]
For example, for mode we have the following info:
```
  {
        "code": "mode",
        "custom_name": "",
        "dp_id": 2,
        "time": 1687016151049,
        "value": "Air_Supply"
      },
```

This seems to be the info from "Query Device Parameters" in the API Explorer.
It shows the dp id is 2, and the current value is "Air_Supply".  But we also need to know what other values it can take.

Another function a few lines further down is "Query Things Data Model".  That function seems to return a lot more information about the possible values, not just the current values.

**Comment by tariya-garker** [comment]
Do I understand correctly that I should look at these items by changing the settings in SmartLife?

**Comment by make-all** [comment]
You shouldn't need to change the values if you use the "Query Things Data Model" function.  But that is another way of discovering the info, though a little more difficult for numeric values with a wide range.

**Comment by tariya-garker** [comment]
went into the Query Things Data Model section, that's what you got there

> {
>   "result": {
>     "model": "{\"modelId\":\"000003x3i0\",
> 	\"services\":[{\"actions\":[],
> 	\"code\":\"\",\"description\":\"\",
> 	\"events\":[],\"name\":\"默认服务\",
> 	\"properties\":[{\"abilityId\":1,
> 	\"accessMode\":\"rw\",
> 	\"code\":\"switch\",
> 	\"description\":\"\",
> 	\"extensions\":{\"iconName\":\"icon-dp_power2\"},
> 	\"name\":\"Power\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
> 	{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"mode\",\"description\":\"\",
> 	\"extensions\":{\"iconName\":\"icon-dp_mode\"},
> 	\"name\":\"Mode\",
> 	\"typeSpec\":{\"range\":[\"Air_Supply\",
> 	\"Recirculation\",
> 	\"Sleep\",
> 	\"Auto\",
> 	\"Eco\",
> 	\"Anti_Condensation\"],
> 	\"type\":\"enum\",
> 	\"typeDefaultValue\":\"Air_Supply\"}},
> 	{\"abilityId\":3,
> 	\"accessMode\":\"ro\",
> 	\"code\":\"pm25\",
> 	\"description\":\"\",
> 	\"extensions\":{\"iconName\":\"icon-pm\"},
> 	\"name\":\"PM2.5\",
> 	\"typeSpec\":{\"max\":999,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"ug/m³\"}},
> 	{\"abilityId\":5,\"accessMode\":\"rw\",\"code\":\"anion\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-function_eh\"},\"name\":\"Anion\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
> 	{\"abilityId\":11,\"accessMode\":\"ro\",\"code\":\"filter_life\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_heart\"},\"name\":\"Filter _life\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%\"}},
> 	{\"abilityId\":12,\"accessMode\":\"rw\",\"code\":\"fan_speed_enum\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-FanSpeed\"},\"name\":\"Fan_speed\",\"typeSpec\":{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\"],\"type\":\"enum\",\"typeDefaultValue\":\"1\"}},
> 	{\"abilityId\":13,\"accessMode\":\"rw\",\"code\":\"filter_reset\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_filter\"},\"name\":\"filter_reset\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
> 	{\"abilityId\":16,\"accessMode\":\"rw\",\"code\":\"countdown_set\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\"},\"name\":\"Timer_on\",\"typeSpec\":{\"range\":[\"cancel\",\"1h\",\"2h\",\"3h\",\"4h\",\"5h\",\"6h\",\"7h\",\"8h\",\"9h\",\"10h\",\"11h\",\"12h\"],\"type\":\"enum\",\"typeDefaultValue\":\"cancel\"}},
> 	{\"abilityId\":22,\"accessMode\":\"ro\",\"code\":\"temp_outdoor\",\"description\":\"\",\"name\":\"temp_outdoor\",\"typeSpec\":{\"max\":50,\"min\":-50,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-50,\"unit\":\"℃\"}},
> 	{\"abilityId\":42,\"accessMode\":\"rw\",\"code\":\"heat\",\"description\":\"\",\"name\":\"Heat_up\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
> 	{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"countup_set\",\"description\":\"\",\"name\":\"Timer_off\",\"typeSpec\":{\"range\":[\"cancel\",\"1h\",\"2h\",\"3h\",\"4h\",\"5h\",\"6h\",\"7h\",\"8h\",\"9h\",\"10h\",\"11h\",\"12h\"],\"type\":\"enum\",\"typeDefaultValue\":\"cancel\"}},
> 	{\"abilityId\":102,\"accessMode\":\"rw\",\"code\":\"Temperature_set\",\"description\":\"\",\"name\":\"Temperature_set\",\"typeSpec\":{\"max\":30,\"min\":10,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":10,\"unit\":\"℃\"}}]}]}"
>   },
>   "success": true,
>   "t": 1687446239971,
>   "tid": "04934259110e11eea68636790d793901"
> }

**Comment by eses19** [comment]
Hello.
2 devices added successfully. Their parameters:
     "product_id": "qcgxajmb0sdg608j",
     "product_name": "Royal Clima RCB 150",
2 others - not identified correctly. Their parameters:
     "product_id": "wcp2nfeclky0ybwi",
     "product_name": "Royal Clima RCB 150",

Please add support for this product_id too.

**Comment by make-all** [comment]
This isn't how it works. If the devices are different they can't just be added with a product id, the logs are needed to determine what is different about them.

**Comment by eses19** [comment]
Query Things Data Model for 2 device with (ANOTHER) "product_id": "wcp2nfeclky0ybwi" 
 "result": {
    "model": "{\"modelId\":\"000001y8px\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\"},\"name\":\"Power\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"mode\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_mode\"},\"name\":\"Mode\",\"typeSpec\":{\"range\":[\"Air_Supply\",\"Recirculation\",\"Sleep\",\"Auto\",\"Eco\",\"Anti_Condensation\"],\"type\":\"enum\",\"typeDefaultValue\":\"Air_Supply\"}},{\"abilityId\":3,\"accessMode\":\"ro\",\"code\":\"pm25\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-pm\"},\"name\":\"PM2.5\",\"typeSpec\":{\"max\":999,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"ug/m³\"}},{\"abilityId\":5,\"accessMode\":\"rw\",\"code\":\"anion\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-function_eh\"},\"name\":\"Anion\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":11,\"accessMode\":\"ro\",\"code\":\"filter_life\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_heart\"},\"name\":\"Filter _life\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%\"}},{\"abilityId\":12,\"accessMode\":\"rw\",\"code\":\"fan_speed_enum\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-FanSpeed\"},\"name\":\"Fan_speed\",\"typeSpec\":{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\"],\"type\":\"enum\",\"typeDefaultValue\":\"1\"}},{\"abilityId\":13,\"accessMode\":\"rw\",\"code\":\"filter_reset\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_filter\"},\"name\":\"filter_reset\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":16,\"accessMode\":\"rw\",\"code\":\"countdown_set\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\"},\"name\":\"Timer_on\",\"typeSpec\":{\"range\":[\"cancel\",\"1h\",\"2h\",\"3h\",\"4h\",\"5h\",\"6h\",\"7h\",\"8h\",\"9h\",\"10h\",\"11h\",\"12h\"],\"type\":\"enum\",\"typeDefaultValue\":\"cancel\"}},{\"abilityId\":22,\"accessMode\":\"ro\",\"code\":\"temp_outdoor\",\"description\":\"\",\"name\":\"temp_outdoor\",\"typeSpec\":{\"max\":50,\"min\":-50,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-50,\"unit\":\"℃\"}},{\"abilityId\":42,\"accessMode\":\"rw\",\"code\":\"heat\",\"description\":\"\",\"name\":\"Heat_up\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"countup_set\",\"description\":\"\",\"name\":\"Timer_off\",\"typeSpec\":{\"range\":[\"cancel\",\"1h\",\"2h\",\"3h\",\"4h\",\"5h\",\"6h\",\"7h\",\"8h\",\"9h\",\"10h\",\"11h\",\"12h\"],\"type\":\"enum\",\"typeDefaultValue\":\"cancel\"}},{\"abilityId\":102,\"accessMode\":\"rw\",\"code\":\"Temperature_set\",\"description\":\"\",\"name\":\"Temperature_set\",\"typeSpec\":{\"max\":30,\"min\":10,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":10,\"unit\":\"℃\"}}]}]}"
  },
  "success": true,
  "t": 1705840771475,
  "tid": "1fbd6ab4b85a11eebe106ae4d2d5261a"
}

And this for 2 device with (OLD) "product_id": "qcgxajmb0sdg608j"
{
  "result": {
    "model": "{\"modelId\":\"000003x3i0\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\"},\"name\":\"Power\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"mode\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_mode\"},\"name\":\"Mode\",\"typeSpec\":{\"range\":[\"Air_Supply\",\"Recirculation\",\"Sleep\",\"Auto\",\"Eco\",\"Anti_Condensation\"],\"type\":\"enum\",\"typeDefaultValue\":\"Air_Supply\"}},{\"abilityId\":3,\"accessMode\":\"ro\",\"code\":\"pm25\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-pm\"},\"name\":\"PM2.5\",\"typeSpec\":{\"max\":999,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"ug/m³\"}},{\"abilityId\":5,\"accessMode\":\"rw\",\"code\":\"anion\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-function_eh\"},\"name\":\"Anion\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":11,\"accessMode\":\"ro\",\"code\":\"filter_life\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_heart\"},\"name\":\"Filter _life\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%\"}},{\"abilityId\":12,\"accessMode\":\"rw\",\"code\":\"fan_speed_enum\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-FanSpeed\"},\"name\":\"Fan_speed\",\"typeSpec\":{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\"],\"type\":\"enum\",\"typeDefaultValue\":\"1\"}},{\"abilityId\":13,\"accessMode\":\"rw\",\"code\":\"filter_reset\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_filter\"},\"name\":\"filter_reset\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":16,\"accessMode\":\"rw\",\"code\":\"countdown_set\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\"},\"name\":\"Timer_on\",\"typeSpec\":{\"range\":[\"cancel\",\"1h\",\"2h\",\"3h\",\"4h\",\"5h\",\"6h\",\"7h\",\"8h\",\"9h\",\"10h\",\"11h\",\"12h\"],\"type\":\"enum\",\"typeDefaultValue\":\"cancel\"}},{\"abilityId\":22,\"accessMode\":\"ro\",\"code\":\"temp_outdoor\",\"description\":\"\",\"name\":\"temp_outdoor\",\"typeSpec\":{\"max\":50,\"min\":-50,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-50,\"unit\":\"℃\"}},{\"abilityId\":42,\"accessMode\":\"rw\",\"code\":\"heat\",\"description\":\"\",\"name\":\"Heat_up\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"countup_set\",\"description\":\"\",\"name\":\"Timer_off\",\"typeSpec\":{\"range\":[\"cancel\",\"1h\",\"2h\",\"3h\",\"4h\",\"5h\",\"6h\",\"7h\",\"8h\",\"9h\",\"10h\",\"11h\",\"12h\"],\"type\":\"enum\",\"typeDefaultValue\":\"cancel\"}},{\"abilityId\":102,\"accessMode\":\"rw\",\"code\":\"Temperature_set\",\"description\":\"\",\"name\":\"Temperature_set\",\"typeSpec\":{\"max\":30,\"min\":10,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":10,\"unit\":\"℃\"}}]}]}"
  },
  "success": true,
  "t": 1705840510959,
  "tid": "846bc158b85911eea050fecb253acbfb"
}

**Comment by eses19** [comment]
Differences only in: modelId,  t,  tid ?

**Comment by eses19** [comment]
> This isn't how it works. If the devices are different they can't just be added with a product id, the logs are needed to determine what is different about them.

Hello.
@make-all , can you add "product_id": "wcp2nfeclky0ybwi"? Or are additional logs required?
