### ISSUE TITLE
Request support for CREATE Windcalm ceiling fan - using standard Tuya fsd

### ISSUE THREAD

**Issue by tobyt99** [make-all/tuya-local#827]
# Log Message

```
Please paste logs here
```

# Information about DPS mappings

```
{
  "result": {
    "properties": [
      {
        "code": "fan_switch",
        "custom_name": "",
        "dp_id": 60,
        "time": 1687389114271,
        "value": false
      },
      {
        "code": "fan_speed",
        "custom_name": "",
        "dp_id": 62,
        "time": 1683974324841,
        "value": 3
      },
      {
        "code": "fan_direction",
        "custom_name": "",
        "dp_id": 63,
        "time": 1687357654016,
        "value": "forward"
      },
      {
        "code": "fan_countdown_left",
        "custom_name": "",
        "dp_id": 64,
        "time": 1687357654093,
        "value": 0
      }
    ]
  },
  "success": true,
  "t": 1687389270012,
  "tid": "5fd8fd22108911ee927c56f414dcf3dd"
}
```

ifj19h1aa9xjmrci

Ceiling fan (no light):

* On/off
* fan speed
* fan direction
* timer

{
  "result": {
    "category": "fsd",
    "functions": [
      {
        "code": "fan_switch",
        "desc": "fan switch",
        "name": "fan switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_speed",
        "desc": "fan speed",
        "name": "fan speed",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":1,\"max\":6,\"scale\":0,\"step\":1}"
      },
      {
        "code": "fan_direction",
        "desc": "fan direction",
        "name": "fan direction",
        "type": "Enum",
        "values": "{\"range\":[\"forward\",\"reverse\"]}"
      },
      {
        "code": "countdown_left_fan",
        "desc": "countdown left fan",
        "name": "countdown left fan",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":540,\"scale\":0,\"step\":1}"
      }
    ]
  },

![IMG_4061](https://github.com/make-all/tuya-local/assets/10271406/bca01686-aeb5-40e2-bb04-c3a231102664)

**Comment by tobyt99** [comment]
Seems to be based on standard tuya fsd: [https://developer.tuya.com/en/docs/iot/ceiling-fan-light?id=Kaof8fwdfzz9y](https://developer.tuya.com/en/docs/iot/ceiling-fan-light?id=Kaof8fwdfzz9y)

**Comment by hanzwo** [comment]
If PR [839](https://github.com/make-all/tuya-local/pull/839) is approved, it should work for you 👌

**Comment by nicolasglg** [comment]
Hello,
I have added the exact same ceiling fan to my home assistant and I only have the ON / OFF switch exposed, absolutely no other settings either through official Tuya integration (recognized as : ifj19h1aa9xjmrci) or through Tuya Local integration. 

Any idea how I could access more settings ? 

Thank you so much for your help,
Best,
Nicolas.
