### ISSUE TITLE
Unable to connect, but works in Tuya Cloud

### ISSUE THREAD

**Issue by bilogic** [make-all/tuya-local#832]
1. I have a device integrated into my Home Assistant with Tuya Cloud, but wants to run in on Tuya Local
2. I used Tuya Cloud to ascertain that the device is in working condition after I kept getting the error below
3. My HA sits on a different subnet, but both can route to each other
4. Case in point, I have many tasmota devices on the 192.168.9.x subnet and they work fine with HA
5. Also checked that 192.168.9.140 is listening on port 6668
6. My point here being, I'm quite confident the network etc is all setup correctly (IP of the device is read off my router, credentials are read off iot.tuya.com)
7. However, I keep getting this
![image](https://github.com/make-all/tuya-local/assets/946010/d84ee575-0911-4910-99c8-7cfcd6c01a0e)
8. Can I get some logs, some where? HA `Log viewer` show nothing specific to this issue

Thank you!

**Comment by make-all** [comment]
Please see discussion #522, and familiarise yourself with the Home Assistant logs.
