### ISSUE TITLE
PJ-1103J does not show up in Home Assistant energy

### ISSUE THREAD

**Issue by bilogic** [make-all/tuya-local#833]
I managed to add `PJ-1103J clamp power meter` successfully, meaning I'm getting voltage, current etc in Home Assistant. 

However, I can't select it as a consumption sensor in Home Assistant energy dashboard.

I'm able to select my other tasmota devices as consumption sensors, so suspect it is the way tuya-local registered the clamp with Home Assistant.

Able to fix? Thank you!

**Comment by make-all** [comment]
This is due to the device behaviour, the energy sensor resets every hour, so is not usable on the energy dashboard.  Instead you should use an Reiman sum integral helper to calculate energy use from the power.
