### ISSUE TITLE
Request support for [Heat Pump - Model: ITS-4.5HDsuper]

### ISSUE THREAD

**Issue by nicopret1** [make-all/tuya-local#866]
# Log Message

```
This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:49
Integration: tuya_local (documentation, issues)
First occurred: 11:37:52 AM (2 occurrences)
Last logged: 11:37:52 AM

Device matches desk_lamp with quality of 9%. DPS: {"updated_at": 1688549872.3491309, "1": true, "2": "HEAT", "4": 53, "7": false, "14": 230, "15": 0, "17": "NO", "18": 64, "19": "High", "20": 12, "21": 48, "22": 52, "23": 10, "24": 69, "26": 15, "27": true, "28": false, "29": true, "30": false, "31": true, "32": false, "33": false, "40": 24, "41": 8, "101": 0, "102": 0, "103": 0, "104": 0, "105": false, "106": false, "107": false, "108": false, "109": false}
Report this to https://github.com/make-all/tuya-local/issues/
```

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"000004stwy\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"1152\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"mode\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"attribute\":\"1152\"},\"name\":\"模式\",\"typeSpec\":{\"range\":[\"COOL\",\"HEAT\"],\"type\":\"enum\",\"typeDefaultValue\":\"COOL\"}},
{\"abilityId\":4,\"accessMode\":\"rw\",\"code\":\"temp_set\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-set\",\"attribute\":\"1152\"},\"name\":\"温度设置\",\"typeSpec\":{\"max\":75,\"min\":15,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":15,\"unit\":\"℃\"}},
{\"abilityId\":7,\"accessMode\":\"rw\",\"code\":\"defrost\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-chushuang\",\"attribute\":\"1152\"},\"name\":\"正在除霜\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":14,\"accessMode\":\"ro\",\"code\":\"countdown_left\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"attribute\":\"1152\"},\"name\":\"电子膨胀阀\",\"typeSpec\":{\"max\":500,\"min\":-500,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-500,\"unit\":\"P\"}},
{\"abilityId\":15,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-baojing\",\"scope\":\"fault\",\"attribute\":\"1152\"},\"name\":\"故障告警\",\"typeSpec\":{\"label\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\"],\"maxlen\":30,\"type\":\"bitmap\",\"typeDefaultValue\":0}},
{\"abilityId\":17,\"accessMode\":\"ro\",\"code\":\"work_state\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-zhuangtai\",\"attribute\":\"1152\"},\"name\":\"相序模块\",\"typeSpec\":{\"range\":[\"normal\",\"ERR\",\"NO\"],\"type\":\"enum\",\"typeDefaultValue\":\"normal\"}},
{\"abilityId\":18,\"accessMode\":\"ro\",\"code\":\"power_consumption\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_battery\",\"attribute\":\"1152\"},\"name\":\"今日电量\",\"typeSpec\":{\"max\":100000,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"kW·h\"}},
{\"abilityId\":19,\"accessMode\":\"ro\",\"code\":\"flow\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-setting\",\"attribute\":\"1152\"},\"name\":\"风机状态\",\"typeSpec\":{\"range\":[\"OFF\",\"LOW\",\"High\"],\"type\":\"enum\",\"typeDefaultValue\":\"OFF\"}},
{\"abilityId\":20,\"accessMode\":\"ro\",\"code\":\"compressor_strength\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-a_mode_turbo\",\"attribute\":\"1152\"},\"name\":\"回气温度\",\"typeSpec\":{\"max\":140,\"min\":-50,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-50,\"unit\":\"℃\"}},
{\"abilityId\":21,\"accessMode\":\"ro\",\"code\":\"temp_top\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-wendu2\"},\"name\":\"进水温度\",\"typeSpec\":{\"max\":150,\"min\":-50,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-50,\"unit\":\"℃\"}},
{\"abilityId\":22,\"accessMode\":\"ro\",\"code\":\"temp_bottom\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-wendu2\"},\"name\":\"出水温度\",\"typeSpec\":{\"max\":150,\"min\":-50,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-50,\"unit\":\"℃\"}},
{\"abilityId\":23,\"accessMode\":\"ro\",\"code\":\"coiler_temp\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-wendu2\"},\"name\":\"盘管温度\",\"typeSpec\":{\"max\":150,\"min\":-50,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-50,\"unit\":\"℃\"}},
{\"abilityId\":24,\"accessMode\":\"ro\",\"code\":\"venting_temp\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-wendu2\"},\"name\":\"排气温度\",\"typeSpec\":{\"max\":150,\"min\":-50,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-50,\"unit\":\"℃\"}},
{\"abilityId\":26,\"accessMode\":\"ro\",\"code\":\"around_temp\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-wendu2\"},\"name\":\"环境温度\",\"typeSpec\":{\"max\":150,\"min\":-50,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-50,\"unit\":\"℃\"}},
{\"abilityId\":27,\"accessMode\":\"ro\",\"code\":\"compressor_state\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-zhuangtai\",\"attribute\":\"1152\"},\"name\":\"压缩机状态\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":28,\"accessMode\":\"ro\",\"code\":\"four_valve_state\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-zhuangtai\",\"attribute\":\"1152\"},\"name\":\"四通阀状态\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":29,\"accessMode\":\"ro\",\"code\":\"draught_fan_state\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-zhuangtai\",\"attribute\":\"1152\"},\"name\":\"低压开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":30,\"accessMode\":\"ro\",\"code\":\"pump_state\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-zhuangtai\",\"attribute\":\"1152\"},\"name\":\"氟循环/水循环\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":31,\"accessMode\":\"ro\",\"code\":\"backwater\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power\"},\"name\":\"水泵状态\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":32,\"accessMode\":\"ro\",\"code\":\"ele_heating_state\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-zhuangtai\",\"attribute\":\"1152\"},\"name\":\"电热状态\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":33,\"accessMode\":\"ro\",\"code\":\"defrost_state\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-zhuangtai\",\"attribute\":\"1152\"},\"name\":\"高压开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":40,\"accessMode\":\"ro\",\"code\":\"effluent_temp_f\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-wendu2\",\"attribute\":\"1152\"},\"name\":\"机组工装号\",\"typeSpec\":{\"max\":10000,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"\"}},
{\"abilityId\":41,\"accessMode\":\"ro\",\"code\":\"coiler_temp_f\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-wendu2\",\"attribute\":\"1152\"},\"name\":\"除霜前压机运行时间\",\"typeSpec\":{\"max\":10000,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"min\"}},
{\"abilityId\":101,\"accessMode\":\"ro\",\"code\":\"cur_current\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_0\",\"attribute\":\"4096\"},\"name\":\"电流\",\"typeSpec\":{\"max\":2000000,\"min\":0,\"scale\":3,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"A\"}},
{\"abilityId\":102,\"accessMode\":\"ro\",\"code\":\"cur_voltage\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dianliang\",\"attribute\":\"4096\"},\"name\":\"电压\",\"typeSpec\":{\"max\":5000,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"V\"}},
{\"abilityId\":103,\"accessMode\":\"ro\",\"code\":\"cur_power\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-gaodiyin\",\"attribute\":\"4096\"},\"name\":\"功率\",\"typeSpec\":{\"max\":50000,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"W\"}},
{\"abilityId\":104,\"accessMode\":\"ro\",\"code\":\"electric_total\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dianliang\",\"attribute\":\"4096\"},\"name\":\"总电量\",\"typeSpec\":{\"max\":400000000,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"kW·h\"}},
{\"abilityId\":105,\"accessMode\":\"ro\",\"code\":\"lpress\",\"description\":\"\",\"name\":\"电量检测\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":106,\"accessMode\":\"ro\",\"code\":\"link\",\"description\":\"\",\"name\":\"联动开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":107,\"accessMode\":\"ro\",\"code\":\"flowswitch\",\"description\":\"\",\"name\":\"水流开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":108,\"accessMode\":\"ro\",\"code\":\"sw1\",\"description\":\"\",\"name\":\"拨码开关1\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":109,\"accessMode\":\"ro\",\"code\":\"sw2\",\"description\":\"\",\"name\":\"拨码开关2\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}}]}]}"
  },
  "success": true,
  "t": 1688553815928,
  "tid": "cb4af50d1b2011ee871736843e81b476"
}

output of export_codes() for dp_id from Google Chrome developer console:

{"1":"Power","2":"Mode","4":"Target temp","7":"Defrosting","14":"EEV Open","15":"Fault Warning","17":"Work State","18":"Today Electricity","19":"Water Flow","20":"Suction Temp.","21":"Inlet temp.","22":"Outlet temp.","23":"Coiler Temp.","24":"Exhaust Temp.","26":"Ambient Temp.","27":"Compressor state","28":"Four_valve state","29":"Low pressure switch","30":"Fluorine/Water","31":"Pump State","32":"Heating elemet state","33":"High pressure switch","40":"Unit Tooling Number","41":"Runing time before defrost","101":"Current","102":"Voltage","103":"Power","104":"Total Electricity","105":"Electronic ","106":"Linked switch","107":"Water flow switch","108":"SW1","109":"SW2"}

```

# Product ID

"product_id": "hqegspadimukzmll"

# Information about how the device functions

I've recently installed two ITS-4.5HDsuper heat pumps (https://itssolar.co.za/product/4-5kw-super-its-residential-heat-pump/ ) to heat water for my house. The devices are managed via Wi-Fi with the SmartLife app. I have also added both devices to the Tuya IOT platform and can see and also manage the devices from there. The Tuya Cloud integration in Home Assistant shows the devices as: Heat Pump (unsupported) with no entities. If I add the devices via the Tuya local service, I only have the option to add as them as device type: 
- desk_lamp, 
- ir_remote_sensors or 
- simple_switch.

**Comment by pabll0** [comment]
I have the same problem

**Comment by nicopret1** [comment]
Hi Jason, 

The YAML file for the ITS-4.5HDsuper heatpump water heater will be similar to the one for aquatech_x6_water_heater.yaml. The ITS seems to have more data points though. I have created a yaml file based on the available information and copied the file into my tuya-local\devices folder. However, if I try to add my device it is still not detected correctly and I still only get the desk_lamp, ir_remote_sensors or simple_switch options.

I'll gladly contribute to create/test the config required for the ITS device. I'm, however, still fairly new to HA and therefore have limited experience with it. I therefore wanted to first do some local tests and get the basics going before creating a pull request to formally contribute. I'm, however, clearly missing something. Can you give me some pointers what to check for my device to be correctly detected?

I've attached my first attempt for the its_heatpump.yaml herewith. Since I was unable to upload a .yaml, I renamed it .txt to be able to upload it.
[its_heatpump_yaml.txt](https://github.com/make-all/tuya-local/files/12035988/its_heatpump_yaml.txt)

Any pointers will be help or pointers will be greatly appreciated.

Thank you,

Nico

**Comment by nicopret1** [comment]
I've managed to get the integration running with the basic diagnostics. I reduced the number of parameters to those listed in the diagnostic log and also changed the names to match those in the log. Below some detail:

![Screenshot 2023-07-13 at 13 24 08](https://github.com/make-all/tuya-local/assets/130547447/9630a372-8315-4013-a45a-8a07afff38a6)

I'm still missing something since none of the entities currently defined under "primary_entity:" show up. Herewith my current YAML file: 
[ITS_4.5HDsuper_yaml.txt](https://github.com/make-all/tuya-local/files/12038841/ITS_4.5HDsuper_yaml.txt)

**Comment by tnarg-retrac** [comment]
Thanks @make-all 
I tested this but keep getting "Unknown Error Occurred" when trying to add this device.

This is the extent of the logs:
`2023-07-23 19:17:50.704 DEBUG (MainThread) [custom_components.tuya_local.device] Refreshing device state for Test
2023-07-23 19:17:50.704 INFO (MainThread) [custom_components.tuya_local.device] Setting protocol version for Test to 3.3
2023-07-23 19:17:50.759 DEBUG (SyncWorker_0) [custom_components.tuya_local.device] Test refreshed device state: {"dps": {"1": false, "2": "HEAT", "4": 55, "7": false, "14": 300, "15": 0, "17": "NO", "18": 53, "19": "OFF", "20": 15, "21": 39, "22": 16, "23": 11, "24": 15, "26": 11, "27": false, "28": false, "29": true, "30": false, "31": false, "32": false, "33": false, "40": 24, "41": 0, "101": 0, "102": 0, "103": 0, "104": 0, "105": false, "106": false, "107": false, "108": false, "109": false}}
2023-07-23 19:17:50.760 DEBUG (SyncWorker_0) [custom_components.tuya_local.device] new state (incl pending): {"updated_at": 1690132670.759641, "1": false, "2": "HEAT", "4": 55, "7": false, "14": 300, "15": 0, "17": "NO", "18": 53, "19": "OFF", "20": 15, "21": 39, "22": 16, "23": 11, "24": 15, "26": 11, "27": false, "28": false, "29": true, "30": false, "31": false, "32": false, "33": false, "40": 24, "41": 0, "101": 0, "102": 0, "103": 0, "104": 0, "105": false, "106": false, "107": false, "108": false, "109": false}`

I was expecing more with logging level set to debug. Any suggestions on where else to look?
Thanks for all the assistance!

**Comment by nicopret1** [comment]
> Thanks @make-all I tested this but keep getting "Unknown Error Occurred" when trying to add this device.
> 
> This is the extent of the logs: `2023-07-23 19:17:50.704 DEBUG (MainThread) [custom_components.tuya_local.device] Refreshing device state for Test 2023-07-23 19:17:50.704 INFO (MainThread) [custom_components.tuya_local.device] Setting protocol version for Test to 3.3 2023-07-23 19:17:50.759 DEBUG (SyncWorker_0) [custom_components.tuya_local.device] Test refreshed device state: {"dps": {"1": false, "2": "HEAT", "4": 55, "7": false, "14": 300, "15": 0, "17": "NO", "18": 53, "19": "OFF", "20": 15, "21": 39, "22": 16, "23": 11, "24": 15, "26": 11, "27": false, "28": false, "29": true, "30": false, "31": false, "32": false, "33": false, "40": 24, "41": 0, "101": 0, "102": 0, "103": 0, "104": 0, "105": false, "106": false, "107": false, "108": false, "109": false}} 2023-07-23 19:17:50.760 DEBUG (SyncWorker_0) [custom_components.tuya_local.device] new state (incl pending): {"updated_at": 1690132670.759641, "1": false, "2": "HEAT", "4": 55, "7": false, "14": 300, "15": 0, "17": "NO", "18": 53, "19": "OFF", "20": 15, "21": 39, "22": 16, "23": 11, "24": 15, "26": 11, "27": false, "28": false, "29": true, "30": false, "31": false, "32": false, "33": false, "40": 24, "41": 0, "101": 0, "102": 0, "103": 0, "104": 0, "105": false, "106": false, "107": false, "108": false, "109": false}`
> 
> I was expecing more with logging level set to debug. Any suggestions on where else to look? Thanks for all the assistance!

This file works for me - my ITS Heatpump (Model ITS-4.5HD Super) is detected and I can add my heat pumps. Make sure you reload YAML files in Developer Tools after you've added the file.

**Comment by tnarg-retrac** [comment]
Thanks @nicopret1 - there must be another issue with my setup as I have reloaded tha YAML files. The one you posted above gave me the same issue. I'll keep digging, but at least I know the file should work.

**Comment by tnarg-retrac** [comment]
I tried to debug but no joy. If I remove the its_45hd_heatpump.yaml file from the devices directory, I get back to the same process as you initially describe, with the device being found as

- desk_lamp,
- ir_remote_sensors or-
- simple_switch.
- 
As soon as I add the file back, Tuya Local seems to connect to it correctly to retrieve the dps, but then dies with no logging ("Unknown error occurred"). I have also added debug logging to custom_components.tuya_local.helpers.device_config as well as custom_components.tuya_local but I am not catching any errors. 

I have added other tuya components successfully so HA + TuyaLocal is working.

So I am out of idea. Any guidance would be appreciated.
Thanks

**Comment by pabll0** [comment]
Where can i found yaml file for this heat pump?

lun., 24 iul. 2023, 17:42 Nico Pretorius ***@***.***> a scris:

**Comment by make-all** [comment]
This is possibly due to a protocol mismatch. Try etting protocol 3.5 and 3.4 manually.

**Comment by tnarg-retrac** [comment]
> Where can i found yaml file for this heat pump? 

Look in this github repo for custom_components/tuya_local/devices/its_45hd_heatpump.yaml

**Comment by nicopret1** [comment]
Thank you for adding the support, it is highly appreciated and it is working well. Below find a summary of some minor changes I made to your file:

1. Changed current temperature id from 26 to 21. The best temperature sensor to use for the current water temperature is the "Inlet temperature" (ID=21) due to the location of the sensor. ID=26 is the "Ambient temperature"
2. Added Suction temperature as secondary sensor (ID=20)
3. Added Ambient temperature as secondary sensor (ID=26)
4. Renamed "Exhaust temperature" to "Vent temperature" (ID=24) 
5. Removed all electricity related sensors for Voltage, Current and Energy (i.e. ID's=18,101, 101, 104, 105,). The ITS heat pump currently do not have sensors for these aspects and all values are therefore=0.
6. Removed Chlorination (ID=30) since this type of heat pump is not a swimming pool heat pump. It is used as a water heater for the house (i.e geyser element alternative).

[its_45hd_heatpump_yaml.txt](https://github.com/make-all/tuya-local/files/12163817/its_45hd_heatpump_yaml.txt)

I have currently left Linkage sensor (ID=106), but I think you can also remove it since the value remains as "Disconnected" all the time.

Attached herewith find my current file.

**Comment by tnarg-retrac** [comment]
> This is possibly due to a protocol mismatch. Try setting protocol 3.5 and 3.4 manually.

Just to close the loop. An upgrade to 2023.7.0 resolved the "Unknown error occurred" issue when trying to add the device. 
Thanks

**Comment by nicopret1** [comment]
> @make-all Thank you for adding the support, it is highly appreciated and it is working well. Below find a summary of some minor changes I made to your file:
> 
> 1. Changed current temperature id from 26 to 21. The best temperature sensor to use for the current water temperature is the "Inlet temperature" (ID=21) due to the location of the sensor. ID=26 is the "Ambient temperature"
> 2. Added Suction temperature as secondary sensor (ID=20)
> 3. Added Ambient temperature as secondary sensor (ID=26)
> 4. Renamed "Exhaust temperature" to "Vent temperature" (ID=24)
> 5. Removed all electricity related sensors for Voltage, Current and Energy (i.e. ID's=18,101, 101, 104, 105,). The ITS heat pump currently do not have sensors for these aspects and all values are therefore=0.
> 6. Removed Chlorination (ID=30) since this type of heat pump is not a swimming pool heat pump. It is used as a water heater for the house (i.e geyser element alternative).
> 
> [its_45hd_heatpump_yaml.txt](https://github.com/make-all/tuya-local/files/12163817/its_45hd_heatpump_yaml.txt)
> 
> I have currently left Linkage sensor (ID=106), but I think you can also remove it since the value remains as "Disconnected" all the time.
> 
> Attached herewith find my current file.

I've updated my changes and also removed the Linkage sensor (ID=106) as listed above via a Github commit. I'm new to Github and hopefully I've followed the correct process to do so.

**Comment by nicopret1** [comment]
@make-all What will one need to be able to return the specific error code as per the below for Fault (ID=15)?
![image](https://github.com/make-all/tuya-local/assets/130547447/8fd2e75f-b314-49cf-b49c-96704f2dd686)
