### ISSUE TITLE
Inkbird IBBQ-4BW no target temps available

### ISSUE THREAD

**Issue by UniPer85** [make-all/tuya-local#874]
Hi there,

I've been able to add my IBBQ-4BW to this integration without any issues. The only problem seems to be that it doesn't recognize the target temperature which you can set for each probe. See the screenshot below:

![image](https://github.com/make-all/tuya-local/assets/81710808/41891fc6-f4f2-4b58-ad0b-d9f6db194c09)

It only reports the current temperature of each probe and its calibration correction value. Did I do something wrong here of forgot a step in the whole setup process?

**Comment by make-all** [comment]
There is no information in the logs that were submitted for the original request for this device for those values.  Without confirmation of the data type, scale and range, it is not possible to add.

**Comment by UniPer85** [comment]
How can I help adding this to the project? What do you need to get this working?
I've seen other Tuya local plugins who got this working so it should be possible...I'm willing to help proving information what so ever.

**Comment by make-all** [comment]
Device Diagnostics will show what dps are available.  If there is just one block of 4 not from the config it should be obvious what they are.  If there are more, then you'll also need to identify them.  I'll also need to know the ranges over which they can be adjusted.  I presume these are alarm thresholds?

**Comment by UniPer85** [comment]
It's some kind of alarm threshold indeed. Below screens shows someone using them in a dashboard (top left):
![image](https://github.com/make-all/tuya-local/assets/81710808/3bc89a16-f462-4c97-8b54-a7080c337928)
**Source**: https://community.home-assistant.io/t/cannot-get-tuya-integration-to-work/226356/39

If I go to the debug environment on my local Tuya, I can't find any related values for the target temp whatsoever.

**Comment by make-all** [comment]
The device diagnostics will show whether these are present in the local protocol.  You can download them from Settings / Devices on in the Device Info panel after selecting your device on the Decvices tab, or by clicking on "X devices" on the tuya-local panel on the Integrations tab.

**Comment by make-all** [comment]
No feedback for over a month.
