### ISSUE TITLE
WIFI Smoke alarm Cant Connect

### ISSUE THREAD

**Issue by Panda260** [make-all/tuya-local#879]
**Describe the bug**
When i try to add a New device from my Tuya account as the other devices the other Devices work like Some Simple Switches then i want to add my Wifi Smoke Alarm Devices wha i fount is that in the local key are some special character and in the otherdevices that i addedet not have and i geht the error while adding a new Wifi Smoke Alarm device "Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect."

**To Reproduce**
Try to add the [Wifi Smoke Alarm](https://de.aliexpress.com/item/1005004930330522.html?spm=a2g0o.productlist.main.1.26ab7914y2kvGz&algo_pvid=3ff9d1c6-6688-48cc-ba39-9b92a8ac267c&algo_exp_id=3ff9d1c6-6688-48cc-ba39-9b92a8ac267c-0&pdp_npi=3%40dis%21EUR%2123.69%217.82%21%21%2125.17%21%21%40211bda9b16885822792404959d0742%2112000031058266822%21sea%21DE%213099402541&curPageLogUid=hFlgB2jJ7nsB) with the Tuya Local 

**Expected behavior**
...That the Device can Connect to Home Assistant

**Additional context**

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:81
Integration: Tuya Local (documentation, issues)
First occurred: 20:46:33 (1 occurrences)
Last logged: 20:46:33

<class 'Exception'>: Unable to find device on network (specify IP address) while initialising device bfeaf00916aea4b987yev1

and i diddnt fount the device on the network but the app says that the device is online

**Comment by make-all** [comment]
This is a battery powered device.  It will require the cloud to work properly.  If you could connect it locally, it would cause the batteries to drain in hours instead of months.
