### ISSUE TITLE
Request support for YINMIK Water Quality Tester (WF-3188)

### ISSUE THREAD

**Issue by samgalagher** [make-all/tuya-local#880]
# Log Message

```
Pop up menu after adding device id/ip address/local key:
Choose the type of device
Choose the type that matches your device
Device type
co2_box
feit_dimmer

Log details:
This error originated from a custom integration.
Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:49
Integration: tuya_local (documentation, issues)
First occurred: 09:26:26 (2 occurrences)
Last logged: 09:26:27

Device matches co2_box with quality of 5%. DPS: {"updated_at": 1688977575.5371566, "2": 223, "7": 0, "10": 596, "11": 2152, "12": 378, "101": "AsiaStandard", "102": false, "103": true, "104": true, "106": true, "107": 650, "108": 539, "109": 200000, "110": 0, "111": 1200, "112": -1200, "113": 215, "114": 54, "115": 100}
Report this to https://github.com/make-all/tuya-local/issues/


```

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"0000047m9o\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"ro\",\"code\":\"tds_in\",\"description\":\"\",\"extensions\":{\"attribute\":\"1664\"},\"name\":\"TDS\",\"typeSpec\":{\"max\":9999,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"ppm\"}},
{\"abilityId\":2,\"accessMode\":\"ro\",\"code\":\"temp_current\",\"description\":\"\",\"extensions\":{\"attribute\":\"1152\"},\"name\":\"Temprt\",\"typeSpec\":{\"max\":800,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"℃\"}},
{\"abilityId\":7,\"accessMode\":\"ro\",\"code\":\"battery_percentage\",\"description\":\"\",\"extensions\":{\"attribute\":\"1664\"},\"name\":\"BatteryValue\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%\"}},
{\"abilityId\":10,\"accessMode\":\"ro\",\"code\":\"ph\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-p7\",\"attribute\":\"1152\"},\"name\":\"PH值\",\"typeSpec\":{\"max\":1400,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},
{\"abilityId\":11,\"accessMode\":\"ro\",\"code\":\"conductivity_value\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"attribute\":\"1152\"},\"name\":\"EC\",\"typeSpec\":{\"max\":200000,\"min\":0,\"scale\":3,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"mS/cm\"}},
{\"abilityId\":12,\"accessMode\":\"ro\",\"code\":\"orp_value\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-tongji\",\"attribute\":\"1024\"},\"name\":\"ORP\",\"typeSpec\":{\"max\":1200,\"min\":-1200,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-1200,\"unit\":\"mV\"}},
{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"phbuffer\",\"description\":\"\",\"name\":\"pHBuffer\",\"typeSpec\":{\"range\":[\"AsiaStandard\",\"EUStandard\"],\"type\":\"enum\",\"typeDefaultValue\":\"AsiaStandard\"}},
{\"abilityId\":102,\"accessMode\":\"rw\",\"code\":\"holdreading\",\"description\":\"\",\"name\":\"HoldReading\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":103,\"accessMode\":\"rw\",\"code\":\"backlight\",\"description\":\"\",\"name\":\"BackLight\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":104,\"accessMode\":\"rw\",\"code\":\"ectempcompenabled\",\"description\":\"\",\"name\":\"EcTempCompEnabled\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
\"abilityId\":105,\"accessMode\":\"rw\",\"code\":\"ectempcomfactor\",\"description\":\"\",\"name\":\"EcTempCompFactor\",\"typeSpec\":{\"max\":30,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%/℃\"}},
{\"abilityId\":106,\"accessMode\":\"rw\",\"code\":\"buzzerwarning\",\"description\":\"\",\"name\":\"BuzzerWarning\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":107,\"accessMode\":\"rw\",\"code\":\"phmaxlimit\",\"description\":\"\",\"name\":\"pHMaxLimit\",\"typeSpec\":{\"max\":1400,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"\"}},
{\"abilityId\":108,\"accessMode\":\"rw\",\"code\":\"phminlimit\",\"description\":\"\",\"name\":\"pHMinLimit\",\"typeSpec\":{\"max\":1400,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"\"}},
{\"abilityId\":109,\"accessMode\":\"rw\",\"code\":\"ecmaxlimit\",\"description\":\"\",\"name\":\"EC最大值\",\"typeSpec\":{\"max\":200000,\"min\":0,\"scale\":3,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"mS/cm\"}},
{\"abilityId\":110,\"accessMode\":\"rw\",\"code\":\"ecminlimit\",\"description\":\"\",\"name\":\"EC最小值\",\"typeSpec\":{\"max\":200000,\"min\":0,\"scale\":3,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"mS/cm\"}},
{\"abilityId\":111,\"accessMode\":\"rw\",\"code\":\"orpmaxlimit\",\"description\":\"\",\"name\":\"OrpMaxLimit\",\"typeSpec\":{\"max\":1200,\"min\":-1200,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-1200,\"unit\":\"mV\"}},
{\"abilityId\":112,\"accessMode\":\"rw\",\"code\":\"orpminlimit\",\"description\":\"\",\"name\":\"OrpMinLimit\",\"typeSpec\":{\"max\":1200,\"min\":-1200,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-1200,\"unit\":\"mV\"}},
{\"abilityId\":113,\"accessMode\":\"ro\",\"code\":\"eccf\",\"description\":\"\",\"name\":\"CF\",\"typeSpec\":{\"max\":20000,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"\"}},
{\"abilityId\":114,\"accessMode\":\"ro\",\"code\":\"humidity\",\"description\":\"\",\"name\":\"Humidity\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%\"}},
{\"abilityId\":115,\"accessMode\":\"rw\",\"code\":\"humiditymaxlimit\",\"description\":\"\",\"name\":\"HumidityMaxLimit\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%\"}},
{\"abilityId\":116,\"accessMode\":\"rw\",\"code\":\"humidityminlimit\",\"description\":\"\",\"name\":\"HumidityMinLimit\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%\"}}
]}]}"
  },
  "success": true,
  "t": 1688978239533,
  "tid": "fb729a1d1efc11ee97740a4306e7517e"
}
```

{
  "1": "TDS",
  "2": "Temperature",
  "7": "Battery percentage",
  "10": "pH",
  "11": "Conductivity Value",
  "12": "ORP",
  "101": "pH Buffer",
  "102": "Hold Reading",
  "103": "Back Light",
  "104": "EC temp. Comp.Enabled",
  "105": "EC Temp.Comp.Factor",
  "106": "Buzzer Warning",
  "107": "pH Max Limit",
  "108": "pH Min Limit",
  "109": "EC Max Limit",
  "110": "EC Min Limit",
  "111": "ORP Max Limit",
  "112": "ORP Min Limit",
  "113": "CF",
  "114": "Humidity",
  "115": "RH Max Limit",
  "116": "RH Min Limit"
}

# Product ID

{
  "result": [
    {
      "active_time": 1688945610,
      "category": "szjcy",
      "create_time": 1688078924,
      "custom_name": "PPM ORP PH Meter",
      "icon": "smart/icon/bay164497620449560Pe/3c680798e8af1b8ed29218a14427936d.jpg",
      "id": "bfd6863a573547e758h6fi",
      "ip": "[REDACTED]",
      "is_online": true,
      "lat": "[REDACTED]",
      "local_key": "[REDACTED]",
      "lon": "[REDACTED]",
      "model": "WF-3188",
      "name": "YINMIK Water Quality Tester",
      "product_id": "u5xgcpcngk3pfxb4",
      "product_name": "YINMIK水质检测仪",
      "sub": false,
      "time_zone": "+01:00",
      "update_time": 1688977486,
      "uuid": "25ffe6ea5ca30dd7"
    }
  ],
  "success": true,
  "t": 1688977549449,
  "tid": "60292dc61efb11ee871736843e81b476"
}

# Information about how the device functions

https://www.aliexpress.com/item/1005005622706921.html?spm=a2g0o.productlist.main.1.55f72717pj7ZIT&algo_pvid=b4707349-5781-4a78-9c38-552f6c8ee96d&algo_exp_id=b4707349-5781-4a78-9c38-552f6c8ee96d-0&pdp_npi=3%40dis%21GBP%2197.66%2141.02%21%21%21121.62%21%21%402102188b16889788849325738d0757%2112000033781387394%21sea%21UK%214119568503&curPageLogUid=FwiG1Kwhd0Xv

**Comment by samgalagher** [comment]
DPS | Name | Entity | Type | Example Value | Notes
-- | -- | -- | -- | -- | --
1 | TDS | Primary | Sensor | Calculated value. | EC x EC Temp.Comp.Factor
2 | Temperature | Primary | Sensor | 22.90℃ |  
7 | Battery percentage | Secondary | Sensor | N/A | 6v power supply
10 | pH | Primary | Sensor | 5.91 |  
11 | Conductivity Value | Primary | Sensor | 2.16mS/cm |  
12 | ORP | Primary | Sensor | 392mV |  
101 | pH Buffer | Secondary | Number | 6.86,4.00,9.18 | Calibration solution values
102 | Hold Reading | Secondary | Switch. Boolean | off | legacy from hand held meter
103 | Back Light | Secondary | Switch. Boolean | on | LCD
104 | EC temp. Comp.Enabled | Secondary | Switch. Boolean | on | Used to calulate TDS
105 | EC Temp.Comp.Factor | Secondary | Number | Value fixed. | Used to calulate TDS
106 | Buzzer Warning | Secondary | Switch. Boolean | off | When max/min limit reached
107 | pH Max Limit | Secondary | Number | 6.5 |  
108 | pH Min Limit | Secondary | Number | 5.5 |  
108 | EC Max Limit | Secondary | Number | 200.00mS/cm |  
110 | EC Min Limit | Secondary | Number | 0.00mS/cm |  
111 | ORP Max Limit | Secondary | Number | 1200mV |  
112 | ORP Min Limit | Secondary | Number | -1200mV |  
113 | CF | Primary | Sensor | 21.5 | CF=EC
114 | Humidity | Primary | Sensor | 53% |  
115 | RH Max Limit | Secondary | Number | 100% | RH = Humidity
116 | RH Min Limit | Secondary | Number | 20% | RH = Humidity

**Comment by samgalagher** [comment]
Correction to CF relationship to EC
113 | CF | Primary | Sensor | 21.5 | CF=10xEC
-- | -- | -- | -- | -- | --



</body>
</html>

**Comment by samgalagher** [comment]
The naming convention is not consistent across the physical device, app and DPS. I propose the following for the primary entities

EC TDS CF pH ORP Temperature Humidity

Updated table. Sorry for all the changes,  I will ensure I better consolidate comments moving forward 

1 | TDS | Primary | Sensor | Calculated value. | EC x EC Temp.Comp.Factor
-- | -- | -- | -- | -- | --
  |   |   |   |   | PPM on the  device.
  |   |   |   |   | PPM (Parts Per Million) is the
  |   |   |   |   | unit for TDS (Total Disolved Solids).
2 | Temperature | Primary | Sensor | 22.90℃ |  
7 | Battery percentage | Secondary | Sensor | N/A | 6v power supply
10 | pH | Primary | Sensor | 5.91 |  
11 | Conductivity Value | Primary | Sensor | 2.16mS/cm | Conductivity Value = EC
12 | ORP | Primary | Sensor | 392mV |  
101 | pH Buffer | Secondary | Number | 6.86,4.00,9.18 | Calibration solution values
102 | Hold Reading | Secondary | Switch. Boolean | off | legacy from hand held meter
103 | Back Light | Secondary | Switch. Boolean | on | LCD
104 | EC temp. Comp.Enabled | Secondary | Switch. Boolean | on | Used to calulate TDS
105 | EC Temp.Comp.Factor | Secondary | Number | Value fixed. | Used to calulate TDS
106 | Buzzer Warning | Secondary | Switch. Boolean | off | When max/min limit reached
107 | pH Max Limit | Secondary | Number | 6.5 |  
108 | pH Min Limit | Secondary | Number | 5.5 |  
108 | EC Max Limit | Secondary | Number | 200.00mS/cm |  
110 | EC Min Limit | Secondary | Number | 0.00mS/cm |  
111 | ORP Max Limit | Secondary | Number | 1200mV |  
112 | ORP Min Limit | Secondary | Number | -1200mV |  
113 | CF | Primary | Sensor | 21.5 | CF=10xEC
114 | Humidity | Primary | Sensor | 53% |  
115 | RH Max Limit | Secondary | Number | 100% | RH = Humidity
116 | RH Min Limit | Secondary | Number | 20% | RH = Humidity

**Comment by samgalagher** [comment]
This works for me and may save you some time.

1. Based on \config\custom_components\tuya_local\devices\phw218_waterquality_monitor.yaml
2. DPS 1: TDS and DPS 105: EC Temp.Comp.Factor excluded as they were not reported in the Home Assistant log.
3. It appears the device calculates TDS by multiplying EC by 1000 and dividing by 2. I am doing this in Home Assistant,

`name:  Water quality
products:
  - id: u5xgcpcngk3pfxb4
    name: WF-3188
primary_entity:
  entity: sensor
  name: Temperature
  class: temperature
  icon: "mdi:water-thermometer"
  dps:
    - id: 2
      type: integer
      name: sensor
      class: measurement
      mapping:
        - scale: 10
secondary_entities:
  - entity: sensor
    name: Battery 
    class: battery
    dps:
      - id: 7
        type: integer
        name: sensor
        class: measurement
        unit: "%"
  - entity: sensor
    name: pH
    icon: "mdi:ph"
    dps:
      - id: 10
        type: integer
        name: sensor
        class: measurement
        mapping:
          - scale: 100
          - dps_val: 1500
            value: null
  - entity: sensor
    name: Electrical conductivity
    icon: "mdi:omega"
    dps:
      - id: 11
        type: integer
        name: sensor
        class: measurement
        unit: µS/cm
  - entity: sensor
    name: Oxidation reduction potential
    icon: "mdi:virus-off"
    dps:
      - id: 12
        type: integer
        name: sensor
        class: measurement
        unit: mV
  - entity: text
    name: pH Buffer
    dps:
      - id: 101
        type: string
        name: text
  - entity: switch
    name: Hold Reading
    dps:
      - id: 102
        type: boolean
        name: switch
  - entity: switch
    name: Back Light
    dps:
      - id: 103
        type: boolean
        name: switch
  - entity: switch
    name: EC temp. Comp.Enabled
    dps:
      - id: 104
        type: boolean
        name: switch
  - entity: switch
    name: Buzzer Warning
    dps:
      - id: 106
        type: boolean
        name: switch
  - entity: number
    name: pH Max Limit
    category: config
    icon: "mdi:pH"
    dps:
      - id: 107
        type: integer
        name: value
        range:
          min: 0
          max: 1500
        mapping:
          - scale: 100
  - entity: number
    name: pH Min Limit
    category: config
    icon: "mdi:pH"
    dps:
      - id: 108
        type: integer
        name: value
        range:
          min: 0
          max: 1500
        mapping:
          - scale: 100        
  - entity: number
    name: EC Max Limit
    category: config
    icon: "mdi:omega"
    dps:
      - id: 109
        type: integer
        name: value
        unit: µS/cm
        range:
          min: 0
          max: 199999
  - entity: number
    name: EC Min Limit
    category: config
    icon: "mdi:omega"
    dps:
      - id: 110
        type: integer
        name: value
        unit: µS/cm
        range:
          min: 0
          max: 199999
  - entity: number
    name: ORP Max Limit
    category: config
    icon: "mdi:virus-off"
    dps:
      - id: 111
        type: integer
        name: value
        unit: mV
        range:
          min: -2000
          max: 2000
  - entity: number
    name: ORP Min Limit
    category: config
    icon: "mdi:virus-off"
    dps:
      - id: 112
        type: integer
        name: value
        unit: mV
        range:
          min: -2000
          max: 2000
  - entity: sensor
    name: CF
    dps:
      - id: 113
        type: integer
        name: sensor
        class: measurement
  - entity: sensor
    name: Humidity
    class: humidity
    dps:
      - id: 114
        type: integer
        name: sensor
        unit: "%"
        class: measurement
  - entity: number
    name: RH Max Limit
    category: config
    dps:
      - id: 115
        type: integer
        name: value
        unit: "%"
        range:
          min: 0
          max: 100
  - entity: number
    name: RH Min Limit
    category: config
    dps:
      - id: 116
        type: integer
        name: value
        unit: "%"
        range:
          min: 0
          max: 100

`

**Comment by samgalagher** [comment]
I tested this and it works on my device. Screen grabs included. 

![tuya_local_yinmik_waterquality_tester_settings](https://github.com/make-all/tuya-local/assets/96902552/77772d68-5fec-4278-883d-b034ca9c3836)
![tuya_local_yinmik_waterquality_tester_ui](https://github.com/make-all/tuya-local/assets/96902552/d7a8a98e-050b-40b9-91f8-ff700b28ea7a)
_

**Comment by tjlwhero** [comment]
Having same issue - 

Choose the type that matches your device
Device type
co2_box
feit_dimmer

Running version 2023.7.0

Logs below:

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:49
Integration: Tuya Local ([documentation](https://github.com/make-all/tuya-local), [issues](https://github.com/make-all/tuya-local/issues))
First occurred: 5:36:58 PM (2 occurrences)
Last logged: 5:36:58 PM

Device matches co2_box with quality of 6%. DPS: {"updated_at": 1690868216.3691285, "2": 160, "10": 669, "12": 148, "101": "AsiaStandard", "102": false, "103": false, "104": true, "106": true, "107": 1400, "108": 0, "109": 5000, "110": 0, "111": 1200, "112": -1200, "114": 53, "115": 100}
Report this to https://github.com/make-all/tuya-local/issues/

**Comment by tjlwhero** [comment]
Tested and it works. Thank you.

**Comment by denveronly** [comment]
im trying to integrate same device but i cant connect.
<img width="589" alt="Screenshot 2023-08-10 at 11 55 07" src="https://github.com/make-all/tuya-local/assets/66441516/d5e1aa0b-61f7-4de5-930c-bab3385f6f1b">

device id and local key are correct.
device is visible in my network
<img width="971" alt="Screenshot 2023-08-10 at 12 00 58" src="https://github.com/make-all/tuya-local/assets/66441516/f5b05abf-6125-4bd5-9f5c-6c2337a12902">


i tried to change the 
 \config\custom_components\tuya_local\devices\phw218_waterquality_monitor.yaml
with DPs list that is given in this topic and reboot HA
Tried auto IP and direct IP, auto protocol and all protocols manualy

**Comment by make-all** [comment]
For best results, you should use the protocol version and IP address from the scan result in the screenshot.  See #522 for some tips on resolving connection issues.

**Comment by Voltage-Studio** [comment]
Added! Thanks for this..

Will be SO much easier to keep tabs on my Aerospring tower garden and move into automatic dosing.

**Comment by Voltage-Studio** [comment]
> Hallo miteinander bin noch neuling in Sachen Yaml ;)
> 
> habe mir hier alles durchgelesen aber hab keine Lösung
> 
> Habe den [YINMIK Water Quality Tester habe über die Smart Life app hizugefügt aber das Gerät hat keine Entitäten???
> 
> Bitte um Hilfe Grüße Jürgen

Sie verwenden nicht die SmartLife-App, um es hinzuzufügen. Sie müssen ein benutzerdefiniertes Repository über diesen GitHub-Link hinzufügen (über HACS, das Sie installiert haben müssen).
Öffnen Sie anschließend HACS. Klicken Sie oben rechts auf die drei Punkte.
Wählen Sie „Benutzerdefinierte Repositorys“.
Fügen Sie die URL zum Repository hinzu (https://github.com/make-all/tuya-local).
Wählen Sie den richtigen Typ (Integration).
Klicken Sie auf „HINZUFÜGEN“.
Anschließend können Sie das Messgerät über diese Integration hinzufügen.

**Comment by dimasik233** [comment]
my YINMIK Water Quality Tester when the internet connection is lost, the pH, EC, and other sensors go to the unavailable status in home assistant. When the connection appears, the sensors are updated. What could be the reason, is it possible to configure a local update without the internet? Thank you very much in advance.
