### ISSUE TITLE
Device 'Unavailable', I have to keep deleting and re-adding devices.

### ISSUE THREAD

**Issue by baudneo** [make-all/tuya-local#887]
No logs as the devices cant be connected to as they are unavailable. Protocol version is set correctly, devices all have static DHCP and ARP mappings. Tuya dev account has IoT core active subscription. Tuya Android app and the cloud Tuya integration work without any issues whatsoever. Only this integration has this issue.

This issue has several discussions open with 0 solutions. I followed all recommended steps in the closed issue. Since multiple users are experiencing the same thing, I would classify this as a bug?

**Comment by make-all** [comment]
Connection issues are covered in discussion #522 
As there are many possibilities coming from your network environment and the devices themselves, this cannot be considered to be a bug without evidence from logs or other sources.
