### ISSUE TITLE
Unable to add device

### ISSUE THREAD

**Issue by GeraldPape** [make-all/tuya-local#890]
The following device cannot be added. I do have already 3 other devices from the same type and maker working, but this one refuses every attemp to get added.

**To Reproduce**
Steps to reproduce the behavior including the device the issue was observed with:
Add new device 

**Expected behavior**
A success message, and the device available in local tuya / HA

**Additional context**

```

{
  "result": [
    {
      "active_time": 1687089547,
      "category": "cz",
      "create_time": 1545471630,
      "custom_name": "Entfeuchter",
      "icon": "smart/icon/ay1519551146071pEnBd/241db20bdb08e5eecdc0eb228bdf94d1.png",
      "id": "0507507***********",
      "ip": "**.***.***.**",
      "is_online": true,
      "lat": "**.****",
      "local_key": "*********",
      "lon": "**.****",
      "model": "SP1-C Smart Socket-16A-AR(SP1-C)",
      "name": "Smart Socket 2",
      "product_id": "IGzCi97RpN2Lf9cu",
      "product_name": "SP1-C Smart Socket-16A-AR",
      "sub": false,
      "time_zone": "+01:00",
      "update_time": 1687583898,
      "uuid": "0507507*******"
    }
  ],
  "success": true,
  "t": 1689337209468,
  "tid": "c63b2a18224011ee871736843e81b476"

```
The local Key looks suspicious, compared to all other keys a saw until yet, it contains some special characters:
cCCCc:c^c7c*cc$<

I replaced the aSCII chars with c or C depending on case, leaving the speciual chars in.

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

Logging is incomplete. I only got one log entry, when I ommited the IP address, saying device not found and add IP address.  since than new tries WITH IP address, but no new entries in logfile.
![grafik](https://github.com/make-all/tuya-local/assets/72608781/016b90ce-897f-4446-ba5f-5d43493ac7f1)

![grafik](https://github.com/make-all/tuya-local/assets/72608781/016b90ce-897f-4446-ba5f-5d43493ac7f1)

**Comment by make-all** [comment]
If the local key format is different than your other devices, it is likely the protocol version is as well, so you could try protocol version 3.4 and 3.5, neither of which are reliably detected with the auto setting.  You could also try repairing the device to get a new local key allocated, in case the underlying tinytuya library has a problem with some punctuation characters in the local key handling.

**Comment by make-all** [comment]
There are a few possibilities for mishandling of those characters.  The browser is probably encoding them before sending to HA from that configuration screen, and HA may be passing them through without decoding them first.  This would be a bug in HA really, as integrations shouldn't need to be handling front end concerns like this.  There could be some string interpretation working under the hood somewhere in the integration or tinytuya library, or the device itself might be having problems with that local key (you wouldn't notice it from the app, as it will continue to use the cloud if the local protocol is not working).

Maybe some testing with the tinytuya command line or tuya-cli would shed more light on where the problem might be.

https://github.com/jasonacox/tinytuya
https://github.com/TuyaAPI/cli

**Comment by make-all** [comment]
As #1065 seems to have attracted more comments than this one, I'll leave that newer issue open and close this older one (even though duplicates normally should be the other way around).  If you have any further evidence of where the problem may be occuring, then please comment on #1065.

it still isn't 100% clear that there is a bug with the local key handling, but a few possibilities have now been eliminated on that issue.
