### ISSUE TITLE
Can't add my device

### ISSUE THREAD

**Issue by EvGeniyLell** [make-all/tuya-local#891]
I try add my device to Tuya local but I already have errors on add integration screen
<img width="200" alt="Screenshot 2023-07-14 at 17 52 29" src="https://github.com/make-all/tuya-local/assets/1710383/2be89aa6-bcc1-424a-961c-b0b578dc6b94">

I have the response from iot Tuya 
and use fields `id ` for uuid and `local_key` for local key
also I try use `uuid` field for uuid from the response
```
{
  "result": [
    {
      "active_time": 1689257135,
      "category": "sp",
      "create_time": 1689257135,
      "custom_name": "",
      "icon": "smart/icon/ay1539690257727HoKMt/c3b88c1b9aaa28ca80b4986861b73254.png",
      "id": "bf2***z7z",
      "ip": "46.***.31",
      "is_online": true,
      "lat": "48.5500",
      "local_key": ">s5p***@g",
      "lon": "35.0900",
      "model": "",
      "name": "AHD Monitor ",
      "product_id": "ixzur437dljmahij",
      "product_name": "AHD Monitor",
      "sub": false,
      "time_zone": "+03:00",
      "update_time": 1689259640,
      "uuid": "eag***213"
    }
  ],
  "success": true,
  "t": 1689***961537,
  "tid": "7ea***2c1"
}
```

**Comment by make-all** [comment]
You probably need to set the IP address and possibly the protocol version manually, the "auto" setting for both does not always work.  Auto IP address only works if you do not have localtuya installed, and your network setup is simple (no seperated subnets for devices).  Auto protocol detection only works reliably for 3.1 and 3.3 devices.

**Comment by make-all** [comment]
Other tips for solving connection issues are on discussion #522, and this issue does not indicate any actual bug, so I will close it.

**Comment by make-all** [comment]
The local key has a `>` sign in it, which may make this the same as bug #890 where the local_key has a `<` sign.  It isn't confirmed yet, but it is possible that Python is processing the string with special meaning given to those characters.  If this is the case, a workaround for now is probably to repair the device with the Tuya Smart app again, to get another key generated which will hopefully not trigger the bug again.

**Comment by EvGeniyLell** [comment]
I already did it
I receive new local key
set ip address for my AHD Monitor
try all protocol versions
<img width="643" alt="Screenshot 2023-07-17 at 14 19 06" src="https://github.com/make-all/tuya-local/assets/1710383/bd8cd3ad-095e-4d06-934a-77ebf2170ede">
but it doesn't  work

**Comment by EvGeniyLell** [comment]
any ideas for connecting / integrationing to Tuya AHD Monitor?
