### ISSUE TITLE
Request support for [AGSHOME Alarm System]

### ISSUE THREAD

**Issue by balu58** [make-all/tuya-local#907]
# Log Message

```
Please paste logs here
```

# Information about DPS mappings

```
Please paste the output here.
```
{
  "result": {
    "model": "{\"modelId\":\"000000271d\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"true\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-tcl_function_hs\",\"attribute\":\"4\"},\"name\":\"状态\",\"typeSpec\":{\"range\":[\"1\",\"2\",\"3\"],\"type\":\"enum\",\"typeDefaultValue\":\"1\"}},{\"abilityId\":103,\"accessMode\":\"rw\",\"code\":\"bj\",\"description\":\"\",\"name\":\"报警\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":104,\"accessMode\":\"rw\",\"code\":\"kg\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power\",\"attribute\":\"1\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":105,\"accessMode\":\"rw\",\"code\":\"bjsc\",\"description\":\"\",\"name\":\"报警时长\",\"typeSpec\":{\"max\":60,\"min\":1,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":1,\"unit\":\"分钟\"}},{\"abilityId\":106,\"accessMode\":\"rw\",\"code\":\"bjy\",\"description\":\"\",\"name\":\"报警音\",\"typeSpec\":{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\"],\"type\":\"enum\",\"typeDefaultValue\":\"1\"}},{\"abilityId\":107,\"accessMode\":\"rw\",\"code\":\"yl\",\"description\":\"\",\"name\":\"音量\",\"typeSpec\":{\"range\":[\"0\",\"25\",\"50\",\"100\"],\"type\":\"enum\",\"typeDefaultValue\":\"0\"}},{\"abilityId\":110,\"accessMode\":\"wr\",\"code\":\"xxpj\",\"description\":\"\",\"name\":\"学习配件\",\"typeSpec\":{\"range\":[\"1\",\"2\",\"3\"],\"type\":\"enum\",\"typeDefaultValue\":\"1\"}},{\"abilityId\":111,\"accessMode\":\"rw\",\"code\":\"ykqts\",\"description\":\"\",\"name\":\"遥控器提示\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":112,\"accessMode\":\"rw\",\"code\":\"cgqts\",\"description\":\"\",\"name\":\"传感器提示\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":113,\"accessMode\":\"rw\",\"code\":\"cmys\",\"description\":\"时间单位为秒\",\"name\":\"出门延时\",\"typeSpec\":{\"max\":600,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"s\"}},{\"abilityId\":114,\"accessMode\":\"rw\",\"code\":\"hjys\",\"description\":\"时间单位为秒\",\"name\":\"回家延时\",\"typeSpec\":{\"max\":600,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"s\"}},{\"abilityId\":115,\"accessMode\":\"rw\",\"code\":\"y1\",\"description\":\"\",\"name\":\"遥控器\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},{\"abilityId\":116,\"accessMode\":\"rw\",\"code\":\"pjts\",\"description\":\"\",\"name\":\"配件推送\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},{\"abilityId\":120,\"accessMode\":\"rw\",\"code\":\"c1\",\"description\":\"\",\"name\":\"传感器\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},{\"abilityId\":121,\"accessMode\":\"ro\",\"code\":\"pjls\",\"description\":\"\",\"name\":\"配件历史记录\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}}]}]}"
  },
  "success": true,
  "t": 1689671826455,
  "tid": "dd7fcefe254b11ee94e0a2e0adfc0b14"
}

# Product ID

# Information about how the device functions

**Comment by balu58** [comment]
Response when try adding device: "Sorry, there is no support for this device."

**Comment by balu58** [comment]
see log
[home-assistant_2023-07-18T11-36-57.518Z.log](https://github.com/make-all/tuya-local/files/12079941/home-assistant_2023-07-18T11-36-57.518Z.log)

**Comment by balu58** [comment]
Product store: 
https://www.amazon.de/gp/product/B0B38H2HTP/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&th=1&language=en_GB

**Comment by make-all** [comment]
The above log does not capture the log message from your attempt to add the device (where you got the "Sorry, there is no support for this device" message.  That log message is the one that is needed to check the data sent by the device.
