### ISSUE TITLE
base64 dp's limited to 255

### ISSUE THREAD

**Issue by blakadder** [make-all/tuya-local#915]
**Describe the bug**
I have a vacuum cleaner with base64 string that decodes into a json string but its longer than 255 and tuya-local throws an error

**To Reproduce**
Tuya robot vacuums map dpid use base64 encoded strings

**Expected behavior**
allow bigger sizes since they clearly exist

Coincidentally an option to decode base64 into json would be useful in these cases

**Comment by make-all** [comment]
From a quick check, there is no limit imposed by the integration, nor by the underlying library.  There is a comment in the underlying library that the tuya protocol limits payloads to 255 bytes, so the limitation is likely coming from that.

**Comment by blakadder** [comment]
Looks like it, no bug here then
