### ISSUE TITLE
Add "mode selection" for rumba_bathroom_heater

### ISSUE THREAD

**Issue by karolzamosc** [make-all/tuya-local#922]
Hi,

Is it possible to add a mode selection for a rumba_bathroom_heater?

![Screenshot_2023-07-25-09-39-39-768_com tuya smart](https://github.com/make-all/tuya-local/assets/61420368/f167e083-2673-4070-9111-75c4b3fb3148)

Regards,
Charles

**Comment by make-all** [comment]
I'm going to need more details than a screenshot.  If it is not mentioned in the iot.tuya.com documentation, then downloading the diagnostics for the device from Home Assistant for each preset selection should show the values, as would turning on debug logging for the integration and selecting each of the presets from the app and waiting 30s in between (remember what order you selected them in, in case the local protocol values are not related to the names).

**Comment by make-all** [comment]
After looking at the config, the modes were there, but the dp was named incorrectly.

**Comment by karolzamosc** [comment]
So it should works fine now?

**Comment by make-all** [comment]
Using "main" it should work fine now.

**Comment by karolzamosc** [comment]
Yes, now it is better but I think options "anti-freeze" and "program" has to be renamed because now they are present as "away" and "home"

**Comment by make-all** [comment]
Away is the correct standard pre-defined preset in HA for anti-freeze modes.  "Program" does not have a standard equivalent, but it is better to stay with standard presets which will have translations already provided within Home Assistant.

**Comment by karolzamosc** [comment]
Works great, thanks for a quick help 👍

**Comment by make-all** [comment]
Sorry, I prefer to leave issues open until they are released, and just remove the "awaiting confirmation" tag when they are confirmed.
