### ISSUE TITLE
Request support for Tuya smart blind chain motor model M515EGWT V2

### ISSUE THREAD

**Issue by mikekornikh** [make-all/tuya-local#924]
# Log Message

```
Please paste logs here
```

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"000002otuw\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"control\",\"description\":\"【必选项】用于控制电机的开启、暂停、关闭。该DP点枚举值参数不允许修改，不允许增减。\",\"extensions\":{\"iconName\":\"icon-dp_power2\"},\"name\":\"控制\",\"typeSpec\":{\"range\":[\"open\",\"stop\",\"close\"],\"type\":\"enum\",\"typeDefaultValue\":\"open\"}},
{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"percent_control\",\"description\":\"如果窗帘电机可以监控窗帘目前的所处位置，例如窗帘现在开了一半，也就是50%，那么可以通过该DP点进行窗帘位置的自定义控制。控制使用该DP点，如果选择了该DP点，必选选择“”开启百分比状态显示“”，该DP点数值范围值参数不允许修改，不允许增减。\",\"extensions\":{\"iconName\":\"icon-dp_power\"},\"name\":\"开启百分比控制\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%\"}},
{\"abilityId\":5,\"accessMode\":\"rw\",\"code\":\"control_back\",\"description\":\"用于设置电机转向，顺时针，或者逆时针，0代表顺时针，1代表顺时针\",\"extensions\":{\"iconName\":\"icon-dp_time2\"},\"name\":\"电机反向\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":7,\"accessMode\":\"ro\",\"code\":\"work_state\",\"description\":\"【必选项】用于显示电机的当前工作状态。该DP点枚举值参数不允许修改，不允许增减。如需要修改在APP面板中显示的内容，可以前往第四步的拓展中心，多语言管理修改代表值，新增的枚举值所代表的的内容也是在多语言中修改代表值。\",\"name\":\"工作状态\",\"typeSpec\":{\"range\":[\"opening\",\"closing\"],\"type\":\"enum\",\"typeDefaultValue\":\"opening\"}},
{\"abilityId\":12,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"【必选】设备上报故障值，该DP点枚举值可增减，但不可修改枚举值名称，例如可以删除motor_fault，可以增加其他值，未选则不展示该功能。 如需要修改在APP面板中显示的内容，可以前往第四步的拓展中心，多语言管理修改代表值，新增的枚举值所代表的的内容也是在多语言中修改代表值。\",\"name\":\"故障告警\",\"typeSpec\":{\"label\":[\"motor_fault\"],\"maxlen\":1,\"type\":\"bitmap\",\"typeDefaultValue\":0}},
{\"abilityId\":16,\"accessMode\":\"rw\",\"code\":\"border\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"设置限位\",\"typeSpec\":{\"range\":[\"up\",\"down\",\"up_delete\",\"down_delete\",\"remove_top_bottom\"],\"type\":\"enum\",\"typeDefaultValue\":\"up\"}},
{\"abilityId\":19,\"accessMode\":\"rw\",\"code\":\"position_best\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"最佳位置\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%\"}}]}]}"
  },
  "success": true,
  "t": 1690312804068,
  "tid": "41e69e652b2011ee804ade073cb82c5d"
}
```

# Product ID

"model": "M515EGWT V2",
    "name": "EGWT V2  2",
    "product_id": "t6ief6k56sapz1ey",
    "product_name": "M515EGWT V2",
    "sub": false,

# Information about how the device functions

This is a blind/curtain chain pulling motor that looks and functions the same as the "Avatto roller blind controller" model that is already supported by this integration.  I tried manually creating a device file for it in the tuya local config using the Avatto file as a template but had no luck adding it.
Here's a link to the product...
https://www.aliexpress.us/item/3256805419544011.html?spm=a2g0o.detail.0.0.171cR5v5R5v5HS&gps-id=pcDetailTopMoreOtherSeller&scm=1007.40050.281175.0&scm_id=1007.40050.281175.0&scm-url=1007.40050.281175.0&pvid=adb167b1-ca9d-4b2b-b283-3ad7543a4461&_t=gps-id:pcDetailTopMoreOtherSeller,scm-url:1007.40050.281175.0,pvid:adb167b1-ca9d-4b2b-b283-3ad7543a4461,tpp_buckets:668%232846%238107%231934&pdp_npi=3%40dis%21USD%2165.57%2131.19%21%21%21%21%21%40210324e516903131806121716e71a3%2112000033726272354%21rec%21US%212665310569

**Comment by make-all** [comment]
I need to see the log message when you try to add the device, which contains the raw dps sent by the device.
Without that, it is unlikely that any config I would create will work.

**Comment by RealMedman** [comment]
Is this what you need?`
2023-09-20 21:04:24.321 DEBUG (MainThread) [custom_components.localtuya.config_flow] Detected DPS: {'1': 'stop', '2': 100, '5': True, '7': 'opening', '16': 'down'}
2023-09-20 21:04:24.321 DEBUG (MainThread) [custom_components.localtuya.config_flow] Total DPS: {'1': 'stop', '2': 100, '5': True, '7': 'opening', '16': 'down'}
