### ISSUE TITLE
Request support for MoesGo Dimmer Switch

### ISSUE THREAD

**Issue by ScottWoolven5** [make-all/tuya-local#927]
# Log Message

This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:49
Integration: Tuya Local (documentation, issues)
First occurred: 15:22:23 (2 occurrences)
Last logged: 15:22:23

Device matches weau_pool_heatpump with quality of 83%. DPS: {"updated_at": 1690381338.1185477, "1": false, "2": 378, "3": 159, "4": "led", "6": 0, "26": true}
Report this to https://github.com/make-all/tuya-local/issues/

# Information about DPS mappings

{
  "result": {
    "model": "{\"modelId\":\"000002fviw\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch_led_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power\",\"attribute\":\"131\"},\"name\":\"开关1\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"bright_value_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_half\",\"attribute\":\"130\"},\"name\":\"亮度值1\",\"typeSpec\":{\"max\":1000,\"min\":10,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":10}},{\"abilityId\":3,\"accessMode\":\"rw\",\"code\":\"brightness_min_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-liangdu1\",\"attribute\":\"128\"},\"name\":\"最小亮度1\",\"typeSpec\":{\"max\":1000,\"min\":10,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":10}},{\"abilityId\":4,\"accessMode\":\"rw\",\"code\":\"led_type_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_box2\",\"attribute\":\"128\"},\"name\":\"光源类型1\",\"typeSpec\":{\"range\":[\"led\",\"incandescent\",\"halogen\"],\"type\":\"enum\",\"typeDefaultValue\":\"led\"}},{\"abilityId\":6,\"accessMode\":\"rw\",\"code\":\"countdown_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"attribute\":\"131\"},\"name\":\"倒计时1\",\"typeSpec\":{\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"s\"}},{\"abilityId\":14,\"accessMode\":\"rw\",\"code\":\"relay_status\",\"description\":\"\",\"extensions\":{\"iconName\":\"setting icon-setting\",\"attribute\":\"128\"},\"name\":\"上电状态记忆\",\"typeSpec\":{\"range\":[\"off\",\"on\",\"memory\"],\"type\":\"enum\",\"typeDefaultValue\":\"off\"}},{\"abilityId\":26,\"accessMode\":\"rw\",\"code\":\"switch_backlight\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"背光开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}}]}]}"
  },
  "success": true,
  "t": 1690381466304,
  "tid": "1fccc0ff2bc011ee871736843e81b476"
}

# Mapping from TinyTuya
"mapping": {
            "1": {
                "code": "switch_led_1",
                "type": "Boolean",
                "values": {}
            },
            "2": {
                "code": "bright_value_1",
                "type": "Integer",
                "values": {
                    "min": 10,
                    "max": 1000,
                    "scale": 0,
                    "step": 1
                }
            },
            "3": {
                "code": "brightness_min_1",
                "type": "Integer",
                "values": {
                    "min": 10,
                    "max": 1000,
                    "scale": 0,
                    "step": 1
                }
            },
            "4": {
                "code": "led_type_1",
                "type": "Enum",
                "values": {
                    "range": [
                        "led",
                        "incandescent",
                        "halogen"
                    ]
                }
            },
            "6": {
                "code": "countdown_1",
                "type": "Integer",
                "values": {
                    "unit": "s",
                    "min": 0,
                    "max": 86400,
                    "scale": 0,
                    "step": 1
                }
            },
            "14": {
                "code": "relay_status",
                "type": "Enum",
                "values": {
                    "range": [
                        "off",
                        "on",
                        "memory"
                    ]
                }
            },
            "26": {
                "code": "switch_backlight",
                "type": "Boolean",
                "values": {}
            }
        },

# Product ID
bf450789b46e8ff48f9n6r

# Information about how the device functions
MoesGo Dimmer Switch
https://www.amazon.co.uk/gp/product/B094Y1C6BS/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1

I've seen that Moes Dimmer Switch is on the list of compatible devices but I believe that my one has different DPS.

**Comment by ScottWoolven5** [comment]
I've tried adding my switch, it's detected with the correct name but unfortunately the device controls do not do anything. I see this message in the logs: 

`Logger: homeassistant.helpers.entity
Source: helpers/entity.py:375
First occurred: 21:47:11 (2 occurrences)
Last logged: 21:51:26

Entity None (<class 'custom_components.tuya_local.switch.TuyaLocalSwitch'>) is implicitly using device name by not setting its name. Instead, the name should be set to None, please report it to the custom integration author.
Entity None (<class 'custom_components.tuya_local.light.TuyaLocalLight'>) is implicitly using device name by not setting its name. Instead, the name should be set to None, please report it to the custom integration author.`

And also this error: 

`This error originated from a custom integration.

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:223
Integration: Tuya Local (documentation, issues)
First occurred: 21:53:45 (1 occurrences)
Last logged: 21:53:45

Lounge Dimmer Switch receive loop has terminated`

Let me know if I can provide any other logs or information.

**Comment by make-all** [comment]
Double check your device id is the device_id, not the uuid (if the two are different in iot.tuya.com listings, most devices are the same so various instructions refer to it as uuid, but that is wrong if they differ). 

Also if it is a protocol 3.1 device, the localkey may be incorrect. (other protocol versions will not work at all if the localkey is wrong, but 3.1 will work as receive only).

Receive loop terminating is probably just another symptom of the same communication problems that are preventing control from working.

**Comment by ScottWoolven5** [comment]
This was the issue, thanks! I was using the uuid as it's in brackets next to the Device ID in the configuration window.
