### ISSUE TITLE
"Wistar roller blinds no position sensor" not fully working with service cover.toggle after 2023.5.0

### ISSUE THREAD

**Issue by mihsu81** [make-all/tuya-local#934]
**Describe the bug**
 After the cover upgrade introduced in 2023.5.0 "Wistar roller blinds no position sensor" is not stopped by service cover.toggle.
After calling the service cover.toggle on the cover entity to open/close, calling again the service cover.toggle on the same cover entity while the cover is still in motion doesn't stop it. Before 2023.5.0 was possible to stop the cover while moving with cover.toggle. 

**To Reproduce**
Call the service cover.toggle on a cover entity of the type: "Wistar roller blinds no position sensor".

**Expected behavior**
The cover should stop if moving when the service call.cover is called.

**Additional context**
I'm currently on 2023.7.0

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"
[config_entry-tuya_local-3ec41129760708c24e7b4bc61de24ce6.json.txt](https://github.com/make-all/tuya-local/files/12187411/config_entry-tuya_local-3ec41129760708c24e7b4bc61de24ce6.json.txt)

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.
No messages

**Comment by make-all** [comment]
The known dps for the device do not provide sufficient information to determine if the cover is moving or stopped, so opening and closing states cannot be reliably determined.  But there are still several unknown dps for this device which might convey the needed information.

**Comment by mihsu81** [comment]
But wouldn't it be possible to use approximations like before 2023.5.0?
Even the Tuya application seems to make this assumption.

**Comment by make-all** [comment]
It is not safe to make assumptions, as this is not the only device that needs to be supported, and experience shows that the previous assumptions made that worked for this device prevent other devices from functioning.
If you can find more information on the behaviour of the unknown dps of this device, something might be able to be done, otherwise this will need to be closed.

**Comment by mihsu81** [comment]
I've checked again the dpids and couldn't find anything else related to the current position (most of them don't seem to change value) except 112 which is broken (stuck on 100).
I did notice that, by removing the below portion of code from _wistar_roller_blind_nopos.yaml_, I can use the service _cover.toggle_. The problem with this approach is that the state of the cover appears _Unknown_ when partially _open_/_closed_. And also when fully _open_/_closed_, after 30 seconds changes from _open_/_closed_ to _Unkwon_.
```
    - id: 102
      type: integer
      name: current_position
      range:
        min: 0
        max: 100
```

**Comment by make-all** [comment]
I don't see how toggle can work then if after 30s the state of the curtain becomes unknown.  It seems you are just trading a short term limitation for a long term one.

**Comment by mihsu81** [comment]
> I don't see how toggle can work then if after 30s the state of the curtain becomes unknown

I was as surprised as you are, but somehow that works.
Maybe there is something missing in the code which would allow full cover.toggle on my motor.

> It is not safe to make assumptions, as this is not the only device that needs to be supported, and experience shows that the previous assumptions made that worked for this device prevent other devices from functioning.

I didn't mean to apply the workaround to all devices. But would be great if you could make selectable the previous approach which was removed in 2023.5.0. It worked really well in my case and never encountered issues with it.
