### ISSUE TITLE
Exception in the logs when using Effects/Scene

### ISSUE THREAD

**Issue by new-kirte** [make-all/tuya-local#94]
Hi
I have a Tuya fairy lights string. The DPs dump is as follows:
INFO:localtuya:COMPLETE response from device bfb04939fb31c54646hamp [192.168.100.209].
INFO:localtuya:Detecting list of available DPS of device bfb04939fb31c54646hamp [192.168.100.209], protocol 3.3.
DEBUG:localtuya.pytuya:Sending command status (device type: type_0a)
DEBUG:localtuya.pytuya:paylod=b'{"gwId":"bfb04939fb31c54646hamp","devId":"bfb04939fb31c54646hamp"}'
DEBUG:localtuya.pytuya:DATA RECEIVED!
DEBUG:localtuya.pytuya:decode payload=b'l\x03`_\xd7\x1b-$\xf8\xc3\xd9\xd7\xec\xf9\xabK\x81m\x0e4`\xe3TO\x9b\xbb*\x81!x\x1f\xc6\x03JW\x06e\xcac[QI\x83\x16\xb0`"\x00?\xf4\xfdr\x15(e\xcey\xa4\xd8\x80\xf6\x07e\x00\x1b\xe8LY\xc4!\xdf\x8b\xcab18\xed2Jz\xc8KX\x92Y\xceQ>\xce\xe8\xc7\x1eyP$\x13{\xa1\xf0\xca\xfc\xe7\xe8\xf0?\xd5Q\'5\x1dn\xe8'
DEBUG:localtuya.pytuya:decrypted result='{"dps":{"20":true,"21":"scene","24":"00f003e803e8","25":"0303e8","26":0,"101":"12103e81000003e803e8"}}'
AVAILABLE DPS ARE [{'20': True, '21': 'scene', '24': '00f003e803e8', '25': '0303e8', '26': 0, '101': '12103e81000003e803e8'}]
INFO:localtuya:COMPLETE response from device bfb04939fb31c54646hamp [192.168.100.209].
INFO:localtuya:TIMEOUT: No response from device bfb04939fb31c54646hamp [192.168.100.209] after 2 attempts.

The string has 3 modes - music, colour, and scene.
Colour mode works well - the device changes DP 21 to word 'color' and DP 24 to the colour code.
Music mode and scene mode do not work.
Scene mode uses DP 25. It can be in the range from **01**03e8 to **21**03e8. To set a scene DP 21 need to be set to 'scene' and DP25 needs to be set to the 6-digit hex code.
Music mode uses DP 101. It has 4 values - '**1**2103e81000003e803e8', '**2**2103e81000003e803e8', '**3**2103e81000003e803e8', and '**4**2103e81000003e803e8'. be in the range from 0103e8 to 2103e8. To use music mode DP 21 need to be set to 'music' and DP101 needs to be set to the 20-digit hex code.

I have tried to define a light entity and map all DPs, but then I am getting a list of non-working effects: "Night", "Read", "Working", "Leisure", "Soft", "Colorful",  "Dazzling",  **"Music",   "Music"**, and "Custom".
The second Music effect turns up when I check the checkbox that device supports Music. 
None of the effects work as device uses its own DPs and codes for changing modes and scenes.

I coud not find an easy way to make scenes working without updating light.py:
```
SCENE_LIST_RGB_1000 = {
    "Night": "000e0d00002e03e802cc00000000",
    "Read": "010e0d000084000003e800000000",
    "Working": "020e0d00001403e803e800000000",
    "Leisure": "030e0d0000e80383031c00000000",
    "Soft": "04464602007803e803e800000000464602007803e8000a00000000",
    "Colorful": "05464601000003e803e800000000464601007803e803e80000000046460100f003e80"
    + "3e800000000464601003d03e803e80000000046460100ae03e803e800000000464601011303e803"
    + "e800000000",
    "Dazzling": "06464601000003e803e800000000464601007803e803e80000000046460100f003e80"
    + "3e800000000",
    "Music": "07464602000003e803e800000000464602007803e803e80000000046460200f003e803e8"
    + "00000000464602003d03e803e80000000046460200ae03e803e800000000464602011303e803e80"
    + "0000000",
}
```
or creating my own logic and adding it in:
```
SCENE_LIST_TUYA_FAIRY = {
    "Scene 01": "0103e8",..., "Scene 21":"2103e8" }
```

So I thought of creating a light template and use localtuya.set_dp service:
```
service: localtuya.set_dp
data:
  device_id: bfb04939fb31c54646hamp
  dp: 21
  value: 'scene'
```

However, every call to localtuya.set_dp (I tried to run a service from Developer Tools) generates an exception in the log:
Logger: homeassistant.util.logging
Source: util/logging.py:105
First occurred: 6:38:48 PM (2 occurrences)
Last logged: 6:40:41 PM

Exception in _update_handler when dispatching 'localtuya_bfb04939fb31c54646hamp': ({'20': True, '21': 'scene', '24': '00f003e803e8', '25': '1103e8', '26': 0, '101': '12103e81000003e803e8'},) Traceback (most recent call last): File "/config/custom_components/localtuya/common.py", line 239, in _update_handler self.status_updated() File "/config/custom_components/localtuya/light.py", line 414, in status_updated self._effect = self.__find_scene_by_scene_data( File "/config/custom_components/localtuya/light.py", line 275, in __find_scene_by_scene_data return next( File "/config/custom_components/localtuya/light.py", line 276, in <genexpr> (item for item in self._effect_list if self._scenes.get(item) == data), AttributeError: 'NoneType' object has no attribute 'get'

However, the service call works find. What is the best way to get custom device effects working?

**Comment by make-all** [comment]
The log above is for the localtuya integration, which is unrelated to this one. In fact, this one does not yet have any support for color lights, effects or scenes, so would be unsuited for your particular lights without putting in the effort to extend its capabilities.
