### ISSUE TITLE
Request support for [(one relay switch with 433 remote)]

### ISSUE THREAD

**Issue by epajfl00** [make-all/tuya-local#947]
"result": {
"model": "{
"modelId":"000004y2th",
"services":[{"actions":[],
"code":"",
"description":"",
"events":[],
"name":"Default Service",
"properties":[{

"abilityId":1,
"accessMode":"rw",
"code":"switch_1",
"description":"",
"extensions":{"iconName":"icon-dp_power",
"attribute":"646"},
"name":"Switch 1",
"typeSpec":{"type":"bool",
"typeDefaultValue":false}},{

"abilityId":9,
"accessMode":"rw",
"code":"countdown_1",
"description":"",
"extensions":{"iconName":"icon-dp_time2",
"attribute":"644"},
"name":"Switch 1 countdown",
"typeSpec":{"max":86400,
"min":0,
"scale":0,
"step":1,
"type":"value",
"typeDefaultValue":0,
"unit":"s"}},{

"abilityId":38,
"accessMode":"rw",
"code":"relay_status",
"description":"",
"extensions":{"iconName":"icon-zhuangtai",
"attribute":"736"},
"name":"Power-on status setting",
"typeSpec":{"range":["off","on","memory"],
"type":"enum",
"typeDefaultValue":"off"}},{

"abilityId":42,
"accessMode":"rw",
"code":"random_time",
"description":"During the set time range, the device switches on and off according to a certain random rule. The timing start switch is turned on, and the timing end switch is turned off. It is mainly used when the residents go out, simulating the scene where there are people at home, and has the effect of preventing theft.",
"extensions":{"iconName":"icon-a_nav_timer",
"attribute":"736"},
"name":"Random Timing",
"typeSpec":{"maxlen":255,
"type":"string",
"typeDefaultValue":""}},{

"abilityId":43,
"accessMode":"rw",
"code":"cycle_time",
"description":"In the set time range, repeat the opening/closing action, and the duration of opening and closing can be customized. The timing start switch is turned on, and the timing end switch is turned off. It is mainly used for cycle watering, feeding, lighting scene control, etc.",
"extensions":{"iconName":"icon-dp_loop",
"attribute":"736"},
"name":"Cycle Timing",
"typeSpec":{"maxlen":255,
"type":"string",
"typeDefaultValue":""}},{

"abilityId":44,
"accessMode":"rw",
"code":"switch_inching",
"description":"It is also called delay off. The user sets a duration. Each time the switch is turned on, it will be automatically turned off after a delay for a period of time to avoid frequent setting of countdown. Such as access control, garage door control and other scenarios that require pulse output signals.",
"extensions":{
"attribute":"736"},
"name":"Jog switch",
"typeSpec":{"maxlen":255,
"type":"string",
"typeDefaultValue":""}},{

"abilityId":47,
"accessMode":"rw",
"code":"switch_type",
"description":"respectively correspond to three external switch states: rocker switch flipping is valid, rocker switch fixed position is valid, self-reset switch is pressed and valid",
"extensions":{"iconName":"icon-dp_power2",
"attribute":"736"},
"name":"Switch type",
"typeSpec":{"range":["flip","sync","button"],
"type":"enum",
"typeDefaultValue":"flip"}},{

"abilityId":49,
"accessMode":"rw",
"code":"remote_add",
"description":"For adding 433 remote control, need to use 433 remote control and must select DP",
"extensions":{"iconName":"icon-dp_add",
"attribute":"224"},
"name":"Remote controller added",
"typeSpec":{"maxlen":128,
"type":"raw"}},{

"abilityId":50,
"accessMode":"rw",
"code":"remote_list",
"description":"For 433 remote control list management, DP is required to use 433 remote control",
"extensions":{"iconName":"icon-dp_list",
"attribute":"224"},
"name":"Remote Controller List",
"typeSpec":{"maxlen":128,
"type":"raw"}}]}]}"

-----------------------------------------------------------

  "result": {
    "active_time": 1690429672,
    "category": "tdq",
 
    "id": "bfab649367a583280dvytj",

    "model": "1-433",
    "name": "1-433",
    "product_id": "1aegphq4yfd50e6b",
    "product_name": "1-433",

    "uuid": "c510d1c9b2c2d497"
 
-------------------------------------------------------------

Summary:
1    Switch
9    Count Down
38  Power on Relay State
42  Random Time
43  Cycle Time
44  Inching
47  Switch Type
49  Add Remote
50  List Remote

-------------------------------------------------------------

I've started a yaml file, see attached, but not sure how to setup dpid 49 and 50. 
[one_relay_with_433.txt](https://github.com/make-all/tuya-local/files/12208513/one_relay_with_433.txt)

------------------------------------------------------------

![image](https://github.com/make-all/tuya-local/assets/86779948/3870f263-6335-4d67-ab1f-fc8493c33da8)

**Comment by make-all** [comment]
I think you will need to manage your remotes from the original app, as there is insufficient documentation on those dps.  They are basically the same as random_time and cycle_time dps, and should be treated the same as them.

**Comment by epajfl00** [comment]
Hi Jason,
Thanks for releasing this, I'm getting a strange result.
When the power on state is set to anything, say off for example, when the relay switch is activated the Power on State goes unknown and is then cleared in the setting. 
![image](https://github.com/make-all/tuya-local/assets/86779948/91026463-75a7-4bbc-ba66-7c38e7d65d18
Any idea why?

**Comment by make-all** [comment]
It is possible that the values are different for the local protocol that the `"range":["off","on","memory"]` reported for the cloud protocol.  You didn't send any logs with the report, so the local value is not confirmed to match the docs.

**Comment by make-all** [comment]
This is the opposite of usual documentation mismatch problems, the cloud API is using numeric strings for the enum types, but the local protocol is using descriptive words.

**Comment by epajfl00** [comment]
Yes, you are right!
That fixed the dp 38, thankyou.

There is another issue that I can't explain;
I'm using the inching function set in the TUYA app (since I can't set it in Tuyalocal), it is set to 1 sec.
So when I use the relay switch (dp:1), the switch goes on for 1 sec and I can hear the relay switching off, however on the control panel, the switch is shown to be still on, and finally shows off after 33 sec.
![image](https://github.com/make-all/tuya-local/assets/86779948/757571af-c633-4a88-862b-2b7d657d47df)

When using the app, it works fine and the control panel mirrors the on/off correctly.

Any explanation?

**Comment by make-all** [comment]
Originally this integration used polling for updates, so it was a while before state would reflect after sending a command.  To compensate, the integration contains logic to override the value in the UI with the value it just sent.  After 30s, it has surely reflected in the device's state, so at that point it drops the override.

Probably this should be revisited now that persistent connections are supported and we can get almost instant feedback from the device, as in cases like this where the device is making further changes on its own, the feature is doing more harm than good.

**Comment by epajfl00** [comment]
You are a champ!
It works fine now, on/off as expected. I used your updated device.py file. Thank-you!

Is there a way you can config the inching function (id 44), so I can understand what is required in future.
I've mapped out some of the values;
I believe the type is base64
      off = AAAB
  1 sec = AQAB
  2 sec = AQAC
  3 sec = AQAD
  4 sec = AQAE
  5 sec = AQAF
  6 sec = AQAG
30 sec = AQAe
     etc........

BTW, I made a mistake in the Product ID value in the yaml file, I used the Device ID by mistake.
Can you please fix this to "1aegphq4yfd50e6b"

**Comment by epajfl00** [comment]
Thank-you for the requested changes.
Just a minor snag with the inching function, HA gives an error when the inching duration is changed/set.
![image](https://github.com/make-all/tuya-local/assets/86779948/3aacae38-623d-4356-a21c-d01e71d97151)

Is there any other info I can provide to help?

**Comment by epajfl00** [comment]
Thank you for the quick fix in Device_config.py
Works great now.
