### ISSUE TITLE
tuya smart curtain 

### ISSUE THREAD

**Issue by vandanoob** [make-all/tuya-local#951]
@iphong  when I send  55 AA 00 06 00 08 02 02 00 04 00 00 00 32 47 this command ,curtain goes to 44% but it should goes  at 50% ,another issue is it does not report updated position .to get updated position I have to restart the curtain module every time after setting new position.

**Comment by make-all** [comment]
I think this is meant for another project, because that is not making sense to me.  I see an esphome curtain project under the repositories of the user you referenced.

**Comment by vandanoob** [comment]
@make-all understood but i don't have a idea that how to deal with this thing !
