### ISSUE TITLE
Request support for mini smart switch with power usage monitoring

### ISSUE THREAD

**Issue by b0120** [make-all/tuya-local#956]
Thanks for your hard work ;-)

# Information about DPS mappings

{
  "result": {
    "properties": [
      {
        "code": "switch_1",
        "custom_name": "",
        "dp_id": 1,
        "time": 1690853961341,
        "value": false
      },
      {
        "code": "countdown_1",
        "custom_name": "",
        "dp_id": 9,
        "time": 1690853961341,
        "value": 0
      },
      {
        "code": "add_ele",
        "custom_name": "",
        "dp_id": 20,
        "time": 1690850513622,
        "value": 0
      },
      {
        "code": "cur_current",
        "custom_name": "",
        "dp_id": 21,
        "time": 1690853961364,
        "value": 0
      },
      {
        "code": "cur_power",
        "custom_name": "",
        "dp_id": 22,
        "time": 1690853961364,
        "value": 0
      },
      {
        "code": "cur_voltage",
        "custom_name": "",
        "dp_id": 23,
        "time": 1690854040520,
        "value": 2439
      },
      {
        "code": "test_bit",
        "custom_name": "",
        "dp_id": 24,
        "time": 1690853962640,
        "value": 2
      },
      {
        "code": "fault",
        "custom_name": "",
        "dp_id": 29,
        "time": 1690853961373,
        "value": 0
      },
      {
        "code": "relay_status",
        "custom_name": "",
        "dp_id": 38,
        "time": 1690853961341,
        "value": "memory"
      },
      {
        "code": "random_time",
        "custom_name": "",
        "dp_id": 42,
        "time": 1690853962640,
        "value": ""
      },
      {
        "code": "cycle_time",
        "custom_name": "",
        "dp_id": 43,
        "time": 1690853962640,
        "value": ""
      },
      {
        "code": "switch_inching",
        "custom_name": "",
        "dp_id": 44,
        "time": 1690853962640,
        "value": "AAAC"
      },
      {
        "code": "switch_type",
        "custom_name": "",
        "dp_id": 47,
        "time": 1690853961341,
        "value": "flip"
      }
    ]
  },
  "success": true,
  "t": 1690854810380,
  "tid": "36d5f7d9300e11ee94e0a2e0adfc0b14"
}
```
Please paste the output here.
```

# Product ID

{
  "result": {
    "active_time": 1690850513,
    "category": "tdq",
    "create_time": 1690850513,
    "custom_name": "",
    "icon": "smart/icon/bay16250208517964yTO/a02f1a76ea3974d64759ea392689caf9.png",
    "id": "bf764c1bb8d62ca1b4qmbw",
    "ip": "203.91.226.68",
    "is_online": true,
    "lat": "-35.1000",
    "local_key": ",
    "lon": "150.6300",
    "model": "WBP-1G",
    "name": "WBP-1G",
    "product_id": "elntzzmug9aekvsa",
    "product_name": "WBP-1G",
    "sub": false,
    "time_zone": "+10:00",
    "update_time": 1690850518,
    "uuid": "8f0ffd36d5ae0d2b"
  },
  "success": true,
  "t": 1690854906680,
  "tid": "70483bca300e11ee8ac9ce4d0cb672c1"
}

# Information about how the device functions

mini smart switch with power usage monitoring

**Comment by make-all** [comment]
There is insufficient information here to create a new config.  The following look like close matches that might fit your needs:

- aubess_1gang_switch (missing switch_type and fault dps)
- relay_switch_remote (missing the power/current/voltage sensors, but has the switch_type setting, and also implements the inching function)

**Comment by BorisAbakumov** [comment]
hi. what information should I add to this topic in order to get support for TuYa Mini (WBP-1G)?

**Comment by make-all** [comment]
There is no point adding information to a closed issue, file a new device request with the information requested in the template if it is not already matching one of the existing configs.

**Comment by BorisAbakumov** [comment]
> Нет смысла добавлять информацию в закрытый вопрос. Отправьте новый запрос на устройство с информацией, указанной в шаблоне, если она не соответствует одной из существующих конфигураций.

I need to get this WBP-1G device, the description of which is mentioned in the first post of this topic. However, one of your messages says, "There is not enough information." What information needs to be updated?
