### ISSUE TITLE
Add Eurom Mon Soleil 300 Verre Wifi?

### ISSUE THREAD

**Issue by PaulJoosten** [make-all/tuya-local#96]
Hi all, is anyone working yet on this infrared heating panel: Eurom Mon Soleil 300 Verre Wifi

We've already successfully added a Eurom Mon Soleil Ceiling 600 Wi-Fi into my Lovelace and hoped this would be more of the same. 

I've managed to add both panels to the Tuya app on my smartphone but when I try to add the new one to HA using the tuya cli in Powershell method I get either a simple 'abort' message or a very weird error message: “ tuya-cli get --id <myid> --key <mykey> --all
���O�;o�����§U�p☺♂��o����3yC�”

My knowledge about HA programming is VERY limited but fortunately my son helps me when he can find the time. When answering, please assume I don't know anything and elaborate each and every step I should take. THANKS!!
Paul

**Comment by make-all** [comment]
It seems similar behaviour to the issue https://github.com/TuyaAPI/cli/issues/97

Double check your device key.

**Comment by PaulJoosten** [comment]
Thanks Jason, adding the --protocol-version 3.3 solved the weird error message. This is the result I now got:
"{
  devId: '126667338cce4edf6549',
  dps: { '1': false, '2': 6, '3': 11, '6': false, '13': 0 }
}"
By comparison, this is what I get for the Eurom Mon Soleil Ceiling 600 Wi-Fi:
"{
  devId: '47308087ecfabc5b9581',
  dps: { '1': true, '2': 15, '5': 20, '7': 0 }
}"
Now to find out what is shown. I deduct '1' shows if the device is on ('true') or off ('false); '2' shows the temperature setting, '3' resp. '5' shows the measured temperature but I wouldn't know what the other numbers show.

By comparing what I did for the 600w panel I found I could use the Tuya Local integration to also show the new 300W panel in my Lovelace. VERY VERY confusing to me having three different ways of integrating Tuya devices; via the TuyaCloud, Local Tuya and Tuyalocal. Persistant trial and error paid off but for a next item I wished there was a clear explanation which of these should be used and why.

Any further pointers will be greatly appreciated but at least I've made some good progress. THANKS!

**Comment by make-all** [comment]
```
devId: '126667338cce4edf6549',
dps: { '1': false, '2': 6, '3': 11, '6': false, '13': 0 }
}"
```
This appears to be the same as Eurom Mon Soleil 601 configuration, so I think you can use that.

```
By comparison, this is what I get for the Eurom Mon Soleil Ceiling 600 Wi-Fi:
"{
devId: '47308087ecfabc5b9581',
dps: { '1': true, '2': 15, '5': 20, '7': 0 }
}"
```

This is different that the currently supported Eurom Mon Soleil 600,  That has '6' as the last dps, not '7'.  Maybe there are two variants of this heater, so a new config will be needed for the new one.

**Comment by PaulJoosten** [comment]
Thanks again Jason. If you or someone else is looking at these heaters perhaps they can modify these configs as the panels can be set to wanted temperatures of below 15° using the Tuya app but in the Lovelace thermostat card they cannot. I use the 600 in the bathroom where this is no problem but the 300W is in my radio shack (ham radio man cave) which is situated in the unheated shed behind my house where I would like to set it to 5° when I'm not (about to go) operating. Or is there a way to adapt them myself? I have no idea where to find these configs on my system or what to change.

**Comment by make-all** [comment]
After reviewing the manuals, I see the Mon Soleil range all have a temperature range of 0-37, so I've modifed them to that.  I think the 15-35 was probably copy and paste from another heater that nobody picked up on before.

**Comment by make-all** [comment]
Interestingly, the manual for the 300 Verre is also for the 450 Verre and 720 Verre.
But the manual for the 601, as well as being also for the 350 and 720 is also for the 3 Verre models, confirming that using the same config is probably correct.

**Comment by PaulJoosten** [comment]
Thanks for your interest. Just out of curiosity, I tried to manually change the setting of my ceiling 600 panel on the wall plug unit that controls it. As expected, it too goes down to 0° but I was only able to go up to 30°, not 37°. As it's my bathroom and not some sauna I'd say that is more than sufficient. Dunno what that means for the config.

**Comment by make-all** [comment]
Is this the correct manual?
https://eurom.nl/wp-content/uploads/2020/07/361834-361841-361858-361865-361872-361889-Mon-Soleil-300-600-800-Ceiling-NE-DU-EN-FR-SV-CZ-SK-RO-versie-4.pdf

It seems to say 0-37.  What happens on the unit if you go past 30 in HA?  If it acts strangely, it is probably best to limit it.  But if it is actually capable of going up to 37 (I guess chosen because it is 100F), then other users might have a se case for that, so it will be better for the config to follow the device's capabilities.

**Comment by PaulJoosten** [comment]
It probably is, can't find mine just now. 

My bad, when I tried it again just now I was able to go all the way to 37 on the unit, up to 35 in HA (which is what it says in the old YAML).
