### ISSUE TITLE
Request support for Nutri Mini (8vwr6rfoaaxncjwj)

### ISSUE THREAD

**Issue by drewpo28** [make-all/tuya-local#960]
The strange situation with this device, few weeks ago I able to add as **Catit Pixi Smart Feeder** and all functions worked successfully.
Some days ago it stopped work and currently I unable to add with error 'Sorry, the device is unknown'.

# Log Message
Device matches None with quality of 0%. DPS: {"updated_at": 1691050319.0349264, "14": 1, "15": 1}
11:11:59 – (WARNING) Tuya Local (custom integration) - message first occurred at 11:11:59 and shows up 2 times

# Information about DPS mappings

{
    "modelId": "00000382y2",
    "services": [
        {
            "actions": [
            ],
            "code": "",
            "description": "",
            "events": [
            ],
            "name": "默认服务",
            "properties": [
                {
                    "abilityId": 1,
                    "accessMode": "rw",
                    "code": "meal_plan",
                    "description": "同步到设备端本地，即使设备离线，仍能正常喂食出粮，喂食计划最多支持10个\\nraw格式约定：按照“周期+时间+喂食份数+开关”来实现本地定时，具体如下\\n1，前7个比特位代表周一到周日，二进制转十六进制，占用一个字节，0代表未设置，1代表设置，如0000001，表示周日生效，转换为16进制就是01\\n2，时间按照小时分钟格式，占用2个字节，分钟和小时，十进制转16进制，如18：50，转为16进制为1232\\n3，喂食份数，占用1个字节，十进制转16进制，如12，转为16进制为0c\\n4，开关，占用1个字节，00表示关闭，01表示开启\\n上述举例，对于APP端时间下发的结果为0112320c01，表示周日，18：50，喂食12份，开启。",
                    "extensions": {
                        "attribute": "1120",
                        "iconName": "icon-dp_time3"
                    },
                    "name": "喂食计划",
                    "typeSpec": {
                        "maxlen": 128,
                        "type": "raw"
                    }
                },
                {
                    "abilityId": 2,
                    "accessMode": "rw",
                    "code": "quick_feed",
                    "description": "",
                    "extensions": {
                        "attribute": "1024",
                        "iconName": "icon-dp_1"
                    },
                    "name": "一键喂食",
                    "typeSpec": {
                        "type": "bool",
                        "typeDefaultValue": false
                    }
                },
                {
                    "abilityId": 3,
                    "accessMode": "rw",
                    "code": "manual_feed",
                    "description": "",
                    "extensions": {
                        "attribute": "1024",
                        "iconName": "icon-icon-test13"
                    },
                    "name": "手动喂食",
                    "typeSpec": {
                        "max": 12,
                        "min": 1,
                        "scale": 0,
                        "step": 1,
                        "type": "value",
                        "typeDefaultValue": 1
                    }
                },
                {
                    "abilityId": 9,
                    "accessMode": "rw",
                    "code": "factory_reset",
                    "description": "",
                    "extensions": {
                        "attribute": "1120",
                        "iconName": "icon-a_nav_mode"
                    },
                    "name": "恢复出厂设置",
                    "typeSpec": {
                        "type": "bool",
                        "typeDefaultValue": false
                    }
                },
                {
                    "abilityId": 14,
                    "accessMode": "ro",
                    "code": "fault",
                    "description": "1:正常 2：缺粮  4：堵粮",
                    "extensions": {
                        "attribute": "1024",
                        "iconName": "icon-dp_notice",
                        "scope": "fault"
                    },
                    "name": "故障告警",
                    "typeSpec": {
                        "label": [
                            "1",
                            "2",
                            "3"
                        ],
                        "maxlen": 3,
                        "type": "bitmap",
                        "typeDefaultValue": 0
                    }
                },
                {
                    "abilityId": 15,
                    "accessMode": "ro",
                    "code": "feed_report",
                    "description": "",
                    "extensions": {
                        "attribute": "1152",
                        "iconName": "icon-dp_upload",
                        "id": 15,
                        "trigger": "direct"
                    },
                    "name": "喂食结果上报",
                    "typeSpec": {
                        "max": 12,
                        "min": 0,
                        "scale": 0,
                        "step": 1,
                        "type": "value",
                        "typeDefaultValue": 0
                    }
                },
                {
                    "abilityId": 101,
                    "accessMode": "rw",
                    "code": "manual_weight",
                    "description": "",
                    "name": "快速出粮份数",
                    "typeSpec": {
                        "max": 12,
                        "min": 1,
                        "scale": 0,
                        "step": 1,
                        "type": "value",
                        "typeDefaultValue": 1,
                        "unit": "份"
                    }
                },
                {
                    "abilityId": 102,
                    "accessMode": "rw",
                    "code": "manual_enable",
                    "description": "手动出粮使能 TRUE按键出粮有效",
                    "name": "按键出粮",
                    "typeSpec": {
                        "type": "bool",
                        "typeDefaultValue": false
                    }
                },
                {
                    "abilityId": 103,
                    "accessMode": "rw",
                    "code": "voice_enable",
                    "description": "出粮音是否有效",
                    "name": "出粮音",
                    "typeSpec": {
                        "type": "bool",
                        "typeDefaultValue": false
                    }
                },
                {
                    "abilityId": 104,
                    "accessMode": "rw",
                    "code": "ipc_did",
                    "description": "关联摄像头id",
                    "name": "关联IPC",
                    "typeSpec": {
                        "maxlen": 255,
                        "type": "string",
                        "typeDefaultValue": ""
                    }
                },
                {
                    "abilityId": 105,
                    "accessMode": "ro",
                    "code": "power_mode",
                    "description": "0: 适配器供电 1：电池供电",
                    "name": "供电方式",
                    "typeSpec": {
                        "max": 1,
                        "min": 0,
                        "scale": 0,
                        "step": 1,
                        "type": "value",
                        "typeDefaultValue": 0,
                        "unit": ""
                    }
                },
                {
                    "abilityId": 106,
                    "accessMode": "rw",
                    "code": "express_feed",
                    "description": "用于alexa语音控制出粮指令",
                    "name": "ALEXA出粮",
                    "typeSpec": {
                        "max": 12,
                        "min": 0,
                        "scale": 0,
                        "step": 1,
                        "type": "value",
                        "typeDefaultValue": 0,
                        "unit": ""
                    }
                }
            ]
        }
    ]
}

# Product ID
8vwr6rfoaaxncjwj

**Comment by drewpo28** [comment]
brrrrrr, just try another time .... and added my feeder  ...

Device matches catit_pixi_smart_feeder with quality of 67%. DPS: {"updated_at": 1691061414.4737751, "3": 1, "14": 1, "15": 1}
14:16:55 – (WARNING) Tuya Local (custom integration) - message first occurred at 14:16:55 and shows up 2 times

**Comment by make-all** [comment]
A lot of more recent devices have become inconsistent about reporting their state.  To match Catit Pixi, your device needed dp 3 and one of 14 or 15 (I'm not sure which one without checking the config, but the match is reported as 67%).  It seems like your device only reports manual feed (dp 3) sometimes - maybe not until you've done a manual feed after turning on the power

**Comment by drewpo28** [comment]
@make-all, it looks you are right, I able add the device after manually did quick_feed action in IoT API Explorer.
what method used to check dps? because if I do Query Properties in IoT explorer then receive a full list of supported dps.
`
{
  "result": {
    "properties": [
      {
        "code": "meal_plan",
        "custom_name": "",
        "dp_id": 1,
        "time": 1690882894758,
        "value": "AA=="
      },
      {
        "code": "quick_feed",
        "custom_name": "",
        "dp_id": 2,
        "time": 1673014970089,
        "value": false
      },
      {
        "code": "manual_feed",
        "custom_name": "",
        "dp_id": 3,
        "time": 1691131359087,
        "value": 1
      },
      {
        "code": "factory_reset",
        "custom_name": "",
        "dp_id": 9,
        "time": 1673014970089,
        "value": false
      },
      {
        "code": "fault",
        "custom_name": "",
        "dp_id": 14,
        "time": 1691131359087,
        "value": 1
      },
      {
        "code": "feed_report",
        "custom_name": "",
        "dp_id": 15,
        "time": 1691083433666,
        "value": 1
      },
      {
        "code": "manual_weight",
        "custom_name": "",
        "dp_id": 101,
        "time": 1691083433974,
        "value": 1
      },
      {
        "code": "manual_enable",
        "custom_name": "",
        "dp_id": 102,
        "time": 1691083433974,
        "value": true
      },
      {
        "code": "voice_enable",
        "custom_name": "",
        "dp_id": 103,
        "time": 1691083433974,
        "value": true
      },
      {
        "code": "ipc_did",
        "custom_name": "",
        "dp_id": 104,
        "time": 1691083433974,
        "value": "��\u000f��\b���\t�rFO�\u0003\u0003��\u0004��\b�\u0001L GpG\u0019"
      },
      {
        "code": "power_mode",
        "custom_name": "",
        "dp_id": 105,
        "time": 1691083433974,
        "value": 0
      },
      {
        "code": "express_feed",
        "custom_name": "",
        "dp_id": 106,
        "time": 1673014970089,
        "value": 0
      }
    ]
  },
  "success": true,
  "t": 1691131364287,
  "tid": "1dceb4ae329211ee8ac9ce4d0cb672c1"
}`

**Comment by make-all** [comment]
The dps are queried from the device with a status request, not using one of the cloud API functions from API explorer.

**Comment by drewpo28** [comment]
@make-all, I see, thanks
