### ISSUE TITLE
eberg_cooly_c35hd doesn't get detected as this device, instead is detected as becool_heatpump and 2 others

### ISSUE THREAD

**Issue by Barley194** [make-all/tuya-local#974]
As in title, I've got the Eberg Cooly C35HD air conditioner, and when configuring, I can select type from 3 devices, but in this list the eberg_cooly_c35hd is missing. (The file is present in the custom_components\tuya_local\devices folder )

**To Reproduce**
Try to add Eberg Cooly C35HD air conditioner - the correct device type is not present to choose
**Expected behavior**
When adding  Eberg Cooly C35HD the correct device type is present to choose

I did a temporal workaround by copping settings from custom_components\tuya_local\devices\eberg_cooly_c35hd.yaml to custom_components\tuya_local\devices\becool_heatpump.yaml and using becool_heatpump as a type for this device. But any update to tuya local will override my local changes.

**Comment by make-all** [comment]
There is insufficient information here to act on.  It is quite common for manufacturers to make different versions of the same model which are not compatible with each other, and it is quite common for the same device to be sold under different brands, so entirely possible that your device is not the same as the eberg_cooly_c35hd that was already added, but is the same as one of the other devices.

**Comment by make-all** [comment]
After reviewing the two configs, the only substantial difference is in the mapping of the hvac_modes.
BeCool has the set_temp_f dp marked as optional, so I assume that would be the reason for the non-match of Eberg.  I have made that change for the Eberg config.

**Comment by Barley194** [comment]
I can confirm that this fixed the issue.
