### ISSUE TITLE
Request support for [Breville AirDynamic 3D]

### ISSUE THREAD

**Issue by Thunn-Der** [make-all/tuya-local#983]
# Log Message

```
Please paste logs here
```

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"000001uz7y\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"extensions\":{\"attribute\":\"1\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"mode\",\"description\":\"\",\"name\":\"工作模式\",\"typeSpec\":{\"range\":[\"NORMAL\",\"NATURAL_N1\",\"NATURAL_N2\",\"NATURAL_N3\",\"ECO\",\"TURBO\"],\"type\":\"enum\",\"typeDefaultValue\":\"NORMAL\"}},
{\"abilityId\":3,\"accessMode\":\"rw\",\"code\":\"fan_speed\",\"description\":\"\",\"name\":\"风速\",\"typeSpec\":{\"max\":8,\"min\":1,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":1,\"unit\":\"\"}},
{\"abilityId\":4,\"accessMode\":\"rw\",\"code\":\"switch_vertical\",\"description\":\"\",\"name\":\"上下摆风开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":5,\"accessMode\":\"rw\",\"code\":\"switch_horizontal\",\"description\":\"\",\"name\":\"左右摆风开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":21,\"accessMode\":\"ro\",\"code\":\"temp_current\",\"description\":\"\",\"name\":\"当前温度\",\"typeSpec\":{\"max\":50,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"℃\"}},
{\"abilityId\":22,\"accessMode\":\"rw\",\"code\":\"countdown_set\",\"description\":\"\",\"name\":\"倒计时\",\"typeSpec\":{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\"],\"type\":\"enum\",\"typeDefaultValue\":\"0\"}},
{\"abilityId\":23,\"accessMode\":\"ro\",\"code\":\"countdown_left\",\"description\":\"\",\"name\":\"倒计时剩余时间\",\"typeSpec\":{\"max\":720,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"min\"}},
{\"abilityId\":24,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"\",\"extensions\":{\"scope\":\"fault\"},\"name\":\"故障告警\",\"typeSpec\":{\"label\":[\"motor_fault\"],\"maxlen\":1,\"type\":\"bitmap\",\"typeDefaultValue\":0}}]}]}"
  },
  "success": true,
  "t": 1691918038499,
  "tid": "bc30ffeb39b911eeb3f09e6a0abc163a"
}

```

# Product ID

 "product_id": "wpkdomrtayuzuqvc",

# Information about how the device functions
{
  "result": [
    {
      "active_time": 1690283438,
      "category": "fs",
      "create_time": 1690283438,
      "custom_name": "Fan",
      "icon": "smart/icon/ay157353776524912KIV/a0fd27ae63eebc4ebc5717d8e2ebca0e.png",
      "id": "228001353c6105ee53ab",
      "ip": "xxxxxxxxxxxxxx",
      "is_online": true,
      "lat": "-xxxxxx",
      "local_key": "xxxxxxxxxx",
      "lon": "xxxxxxx",
      "model": "LPF308",
      "name": "the Breville AirDynamic 3D™ 2",
      "product_id": "wpkdomrtayuzuqvc",
      "product_name": "the Breville AirDynamic 3D™",
      "sub": false,
      "time_zone": "+10:00",
      "update_time": 1691741620,
      "uuid": "228001353c6105ee53ab"
    }
  ],
  "success": true,
  "t": 1691918121194,
  "tid": "ed82ae6039b911eeb3f09e6a0abc163a"
}

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:////Users/mitrober/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

<link rel=themeData
href="file:////Users/mitrober/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:////Users/mitrober/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-AU style='tab-interval:36.0pt;word-wrap:break-word'>

<p class=MsoNormal><span style='font-size:10.5pt;font-family:"Segoe UI",sans-serif;
color:#272E3B;background:#F7F8FA'>Brand: Breville<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:10.5pt;font-family:"Segoe UI",sans-serif;
color:#272E3B;background:#F7F8FA'>Model: Breville AirDynamic 3D™</span><o:p></o:p></p>

Code: | Description (PD ID) | Example | Unit | Notes
-- | -- | -- | -- | --
1 | Power | OFF | - |  
1 | Power | ON | - |  
2 | Mode | Normal | - | Normal Air mode
2 | Mode | Normal:1 | - | Natural Air mode 1
2 | Mode | Normal:2 | - | Natural Air mode 2
2 | Mode | Normal:3 | - | Natural Air mode 3
3 | Wind Speed Level | 1 | - | 1 –to– 8 (levels)
4 | Vertical Oscillation | OFF | - |  
4 | Vertical Oscillation | ON | - |  
5 | Horizontal Oscillation | OFF | - |  
5 | Horizontal Oscillation | ON | - |  
21 | Current Temperature | 20℃ | ℃ |  
22 | Countdown | 10h | hours | 0h,1h,2h,3h,4h,5h    12h
23 | Remaining Time | 720min | minutes | 60min,120min,180min    720min
24 | Fault Alarm | 0 | - |  
  |   |   |   |  

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

</body>

</html>

**Comment by make-all** [comment]
Needs logs from the device itself.  The information provided is contradictory, so the logs should help to clear up which (if any) information is the one to follow.

**Comment by Thunn-Der** [comment]
Hi,

I am happy to gather any logs for you (but I am not sure which logs you mean) 

I logged onto iot.tuya and collected more info just on the off chance this is the information you asked for. Please find attached info
[Breville AirDynamic 3D v2.docx](https://github.com/make-all/tuya-local/files/12567507/Breville.AirDynamic.3D.v2.docx)

I have tried to add the fan and found that the "Arlec industrial fan" works but is missing some functions like vertical oscillation etc.

Please see the lag from my home-assistant server. 

[tuya_local-d2dce0f106f4103556bf934c3fb5f1a0-Arlec industrial fan-8803182622cf8050cdd00f4d56a44a78.json.txt](https://github.com/make-all/tuya-local/files/12567511/tuya_local-d2dce0f106f4103556bf934c3fb5f1a0-Arlec.industrial.fan-8803182622cf8050cdd00f4d56a44a78.json.txt)

**Comment by make-all** [comment]
Thanks, the device diagnostics gave the information that was needed.
```
    "cached_state": {
      "updated_at": 1694320182.1855392,
      "1": false,
      "2": "NORMAL",
      "3": 1,
      "4": false,
      "5": false,
      "21": 19,
      "22": "0",
      "23": 0,
      "24": 0
    },
```
