### ISSUE TITLE
Migration Error with ebac DJ4000 and 2023.8.0

### ISSUE THREAD

**Issue by Jilas** [make-all/tuya-local#984]
**Describe the bug**
Within the TuyaLocal integration page, get a migration error for the device and all entities are unavailable. 

**To Reproduce**
Just updated to 2023.8.0 from 2023.7.0

**Additional context**
Extract from the logs provide this telling error.

2023-08-13 12:08:20.355 ERROR (MainThread) [homeassistant.config_entries] Error migrating entry EBAC DJ4000 for tuya_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 633, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/__init__.py", line 302, in async_migrate_entry
    await async_migrate_entries(hass, entry.entry_id, update_unique_id13)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1348, in async_migrate_entries
    updates = entry_callback(entry)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/__init__.py", line 288, in update_unique_id13
    if new_id.endsWith(new_suffix):
       ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'endsWith'
--------------

Hope this helps find what the migration issue is, tried rolling back, which seems ok?  After I did the roll back I noted it I had a second "humidifier.ebac" sensor.  The original was broken, while the new _2 version working fine.  Deleting the original and renaming the _2 restored everything prior to the update.

If you need any further info, please let me know, happy to test as much as needed.

Thanks for all your work on this, as it's so much easier than the alternatives.

**Comment by make-all** [comment]
Rolling back should be OK if the migration has failed, but it seems it had partially migrated so you got some broken entities on the rollback.

Anyway, I have fixed the basic typo that caused this, it seems my own devices are not diverse enough to test all the branches in the migration.

**Comment by Jilas** [comment]
> Rolling back should be OK if the migration has failed, but it seems it had partially migrated so you got some broken entities on the rollback.
> 
> Anyway, I have fixed the basic typo that caused this, it seems my own devices are not diverse enough to test all the branches in the migration.

Many thanks for the quick response.  And can't expect you to have every device.

So just applied the new version, no more failure. 

BUT and guessing this is related to the other changes, I have now totally lose my 'sensor.ebac_current_humidity' sensor.  

Rolling back now, I get that extra entity as before plus one for temperature.... But no humidity.

**Comment by make-all** [comment]
Humidifier entities should keep history too. Climate entities certainly do. It might be an issue if you want continuous history across the change though.

**Comment by Jilas** [comment]
> Humidifier entities should keep history too. Climate entities certainly do. It might be an issue if you want continuous history across the change though.

That was indeed part of the problem with the change, was losing the history, but thankfully quick enough with renaming, kept all the history and the template sensor just took over the old current humidity name and worked fine.


Hadn't actually thought about just throwing the entity straight in.  That might work later on (quick look, I do get target & current humidity plus when it's running).

Thanks for mentioning that.  Good idea long term.

**Comment by Clam58** [comment]
On upgrading to 2024.3.0 this error resurfaced

Log:

Error migrating entry EBAC DJ4000 dehumidifier for tuya_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 701, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/__init__.py", line 374, in async_migrate_entry
    await async_migrate_entries(hass, entry.entry_id, update_unique_id13_2)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1389, in async_migrate_entries
    updates = entry_callback(entry)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/__init__.py", line 359, in update_unique_id13_2
    new_suffix is None and new_id.contains(suffix)
                           ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'contains'

**Comment by make-all** [comment]
Thanks, I rushed out 2024.3.1 to fix this issue.  It may not help if the migration got marked as complete despite that error, in which case you'll have to clean up your old Tank entity manually.
