### ISSUE TITLE
avatto_curtain_light.yaml - supported device is not populated in the pick up list

### ISSUE THREAD

**Issue by NashHome** [make-all/tuya-local#987]
**Describe the bug**
During the new Tuya Local device configuration there is no option to pick up an appropriate device type - avatto_curtain_light.yaml
There are several not relevant device types appear (see screenshots in the links below)
https://prnt.sc/k74oi4lPlUYO
https://prnt.sc/fpqHsf3yMaoA

**To Reproduce**
Stage One - the configuration goes through with no problem. Filling up the device_id, local_key and the host IP.

At the Stage Two - https://github.com/make-all/tuya-local#stage-two
there is no proper device type (avatto_curtain_light.yaml)
Picking up different type (for instance avatto_curtain_switch) allows functionality as set in the relevant yaml file.

**Expected behavior**
avatto_curtain-light device type to be populated within the pick up list.

**Additional context**
The link below is the DP ID and Tuya functions summary:
https://prnt.sc/w8dKcv6LQHvW

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"
N/A

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.
--------------------------------------------------------------------------------------------------------------------------------------------
Log Details (WARNING)

This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:49
Integration: tuya_local (documentation, issues)
First occurred: 3:45:32 PM (2 occurrences)
Last logged: 3:45:32 PM

Device matches qs_c01_curtain with quality of 67%. DPS: {"updated_at": 1692017130.7970073, "1": "stop", "2": 100, "7": true, "8": "forward", "10": 15, "101": true}
Report this to https://github.com/make-all/tuya-local/issues/
--------------------------------------------------------------------------------------------------------------------------------------------
Query Device Details
Response
{
  "result": {
    "active_time": 1692002212,
    "category": "clkg",
    "create_time": 1680265100,
    "custom_name": "1B-Curtain+switch ",
    "icon": "smart/icon/ay1575861603878V3JkG/b46f29c2c8560823f6bcfa2fbc81e298.png",
    "id": "XXXXXXXXXXX",
    "ip": "XXXXXXXX",
    "is_online": true,
    "lat": "XXXX",
    "local_key": "XXXXXXXXX",
    "lon": "XXXX",
    "model": "涂鸦定制CB3S",
    "name": "Curtain Light switch ",
    "product_id": "v59tpvs4ubvjalhq",
    "product_name": "Smart Curtain + Light Switch",
    "sub": false,
    "time_zone": "+03:00",
    "update_time": 1692002212,
    "uuid": "XXXXXXXXX"
  },
  "success": true,
  "t": 1692017427927,
  "tid": "24e570523aa111eeb1a5226f85af9d81"
}

**Comment by make-all** [comment]
Your device is not reporting the light dp on 102.

**Comment by NashHome** [comment]
Hi @make-all,

Thanks for your check up on this.

See the link below with the fresh DP log data from the Tuya IoT:
https://prnt.sc/FdbprZIJDorZ

There might be some delay in a confirmation from the device. Can it be the reason for the issue you raised?

P.S. In the LocalTuya 102 DP is recognized and working.

**Comment by make-all** [comment]
It is a shame that the one dp that would distinguish this from plain curtains is sometimes missing, but It is possible to make that dp optional to cater to this.

**Comment by NashHome** [comment]
I replied in the Commit link.
Can you match the device according to the product ID?
products:
  - id: v59tpvs4ubvjalhq
or maybe to show the full list?

**Comment by make-all** [comment]
Currently, no, neither of those are viable options.

**Comment by NashHome** [comment]
Hey @make-all,

There is some progress.
The device type is available now and I set it up. However the device entities don't work at all.
When click on the entity, it goes on and after some period of time of less thank a minute goes back to the initial state with no action.
Some become unknown (see the logbook in the screenshot).

https://prnt.sc/XUiQchkVTbQ_

I tested the same device with LocalTuya - works fine.

Your plugin definitely allows better user experience, so I'd prefer to have it working. 

[tuya_local-d4b31f7c28e536657434f9874f878458-Avatto Curtain and Light-fa28d832349d78f23b24f1a50b664002.json (1).txt](https://github.com/make-all/tuya-local/files/12388526/tuya_local-d4b31f7c28e536657434f9874f878458-Avatto.Curtain.and.Light-fa28d832349d78f23b24f1a50b664002.json.1.txt)

Thank you for your great piece of work and the customer support!

**Comment by make-all** [comment]
Are you using the exact same device_id and local_key in localtuya and tuya-local?

Is the device still configured in localtuya when you attempt to use it in tuya-local?

**Comment by NashHome** [comment]
Hi,

**Are you using the exact same device_id and local_key in localtuya and tuya-local?**
YES

**Is the device still configured in localtuya when you attempt to use it in tuya-local?**
I tried the following:
1. Disabled the Localtuya and then set the tuya-local device
2. Uninstalled the Localtuya and then set the tuya-local device.

In both cases the tuya-local entities were successfully added in the HomeAssistant.
However triggering the entities through the HomeAssistant had no effect on the physical device.

See the video attached (The speed X4)

https://github.com/make-all/tuya-local/assets/124376491/2564b46f-141c-437f-9207-8050840fb8b1
