### ISSUE TITLE
Request support for Tuya key safe box

### ISSUE THREAD

**Issue by karolzamosc** [make-all/tuya-local#990]
Hi,

I want to ask before I buy it. I am searching for a key box for sharing keys to my customers. I found that this model is working with Tuya through ble-wifi gateway:

![Screenshot_2023-08-15-11-15-39-541_com alibaba aliexpresshd](https://github.com/make-all/tuya-local/assets/61420368/a55290af-d844-43c4-a552-63dccc91b23a)

@make-all can you fell me if it is possibile to add this key box to your integration?

Regards,
Charles

**Comment by make-all** [comment]
With this amount of information, I can only say no.
