### ISSUE TITLE
tompd_63lw_breaker, entity None is implicitly using device name by not setting its name

### ISSUE THREAD

**Issue by garry0garry** [make-all/tuya-local#992]
I don't understand what should I do?

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:375
First occurred: 9:33:56 AM (1 occurrences)
Last logged: 9:33:56 AM

Entity None (<class 'custom_components.tuya_local.switch.TuyaLocalSwitch'>) is implicitly using device name by not setting its name. Instead, the name should be set to None, please report it to the custom integration author.
```
[tuya_local-04af1652d2a1f1a20788ab10b185eea3-Circuit breaker energy meter-1968c6386062d92c6a9db7affea88ffb.json(9).txt](https://github.com/make-all/tuya-local/files/12347087/tuya_local-04af1652d2a1f1a20788ab10b185eea3-Circuit.breaker.energy.meter-1968c6386062d92c6a9db7affea88ffb.json.9.txt)

**Comment by make-all** [comment]
The string you put a question mark by is the "Manufacturer" reported by the device.  In the case of Tuya Local, the manufacturer is currently always reported as Tuya.

**Comment by garry0garry** [comment]
Are you planning to specify something like tompd_63lw_breaker as the model?

**Comment by make-all** [comment]
Long term. But currently it is not possible to distinguish different devices that share the same config.
