### ISSUE TITLE
Request support for [MOES Tuya WiFi RF Smart Ceiling Fan Light Lamp Wall Switch]

### ISSUE THREAD

**Issue by Levanterman** [make-all/tuya-local#993]
# Log Message

```
Device matches mirabella_genio_usb with quality of 40%. DPS: {"updated_at": 1692139683.8999696, "1": false, "2": 0, "4": 36, "5": false, "13": true}
Report this to https://github.com/make-all/tuya-local/issues/
Device matches mirabella_genio_usb with quality of 40%. DPS: {"updated_at": 1692139749.3000295, "1": false, "2": 0, "4": 36, "5": false, "13": true}
```

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"000002c7jp\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch_fan\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power\",\"attribute\":\"641\"},\"name\":\"风扇开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"countdown_fan\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"attribute\":\"128\"},\"name\":\"风扇倒计时\",\"typeSpec\":{\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"s\"}},
{\"abilityId\":4,\"accessMode\":\"rw\",\"code\":\"fan_speed\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-FanSpeed\",\"attribute\":\"128\"},\"name\":\"风速\",\"typeSpec\":{\"max\":100,\"min\":1,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":1,\"unit\":\"%\"}},
{\"abilityId\":5,\"accessMode\":\"rw\",\"code\":\"switch_led\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power\",\"attribute\":\"128\"},\"name\":\"风扇灯开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":11,\"accessMode\":\"rw\",\"code\":\"relay_status\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_circle\",\"attribute\":\"128\"},\"name\":\"上电状态设置\",\"typeSpec\":{\"range\":[\"off\",\"on\",\"memory\"],\"type\":\"enum\",\"typeDefaultValue\":\"off\"}},
{\"abilityId\":13,\"accessMode\":\"rw\",\"code\":\"switch_backlight\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_light\",\"attribute\":\"128\"},\"name\":\"背光开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}}]}]}"
  },
  "success": true,
  "t": 1692140829939,
  "tid": "763984ed3bc011ee8298eeefa7b3467e"
}
```

# Product ID

"model": "",
      "name": "Fan Light switch",
      "product_id": "66urzkokqdufersv",
      "product_name": "NHZS-风扇灯开关",
      "sub": false,

# Information about how the device functions

Tuya WiFi RF Smart Ceiling Fan Light Lamp Wall Switch
https://www.aliexpress.com/item/1005001524953476.html?spm=a2g0o.order_list.order_list_main.81.3d261802Evvwmt

**Comment by Levanterman** [comment]
Hi @make-all , I'll give this a go and do a pull request, but before I start, I wondered if it looked similar to any other fan switches ?
Also I have another Pull request I will submit for a ceiling fan controller.


Heres the Pretty for the above device

{
    "modelId": "000002c7jp",
    "services": [
        {
            "actions": [],
            "code": "",
            "description": "",
            "events": [],
            "name": "默认服务",
            "properties": [
                {
                    "abilityId": 1,
                    "accessMode": "rw",
                    "code": "switch_fan",
                    "description": "",
                    "extensions": {
                        "iconName": "icon-dp_power",
                        "attribute": "641"
                    },
                    "name": "风扇开关",
                    "typeSpec": {
                        "type": "bool",
                        "typeDefaultValue": false
                    }
                },
                {
                    "abilityId": 2,
                    "accessMode": "rw",
                    "code": "countdown_fan",
                    "description": "",
                    "extensions": {
                        "iconName": "icon-dp_time2",
                        "attribute": "128"
                    },
                    "name": "风扇倒计时",
                    "typeSpec": {
                        "max": 86400,
                        "min": 0,
                        "scale": 0,
                        "step": 1,
                        "type": "value",
                        "typeDefaultValue": 0,
                        "unit": "s"
                    }
                },
                {
                    "abilityId": 4,
                    "accessMode": "rw",
                    "code": "fan_speed",
                    "description": "",
                    "extensions": {
                        "iconName": "icon-FanSpeed",
                        "attribute": "128"
                    },
                    "name": "风速",
                    "typeSpec": {
                        "max": 100,
                        "min": 1,
                        "scale": 0,
                        "step": 1,
                        "type": "value",
                        "typeDefaultValue": 1,
                        "unit": "%"
                    }
                },
                {
                    "abilityId": 5,
                    "accessMode": "rw",
                    "code": "switch_led",
                    "description": "",
                    "extensions": {
                        "iconName": "icon-dp_power",
                        "attribute": "128"
                    },
                    "name": "风扇灯开关",
                    "typeSpec": {
                        "type": "bool",
                        "typeDefaultValue": false
                    }
                },
                {
                    "abilityId": 11,
                    "accessMode": "rw",
                    "code": "relay_status",
                    "description": "",
                    "extensions": {
                        "iconName": "icon-dp_circle",
                        "attribute": "128"
                    },
                    "name": "上电状态设置",
                    "typeSpec": {
                        "range": [
                            "off",
                            "on",
                            "memory"
                        ],
                        "type": "enum",
                        "typeDefaultValue": "off"
                    }
                },
                {
                    "abilityId": 13,
                    "accessMode": "rw",
                    "code": "switch_backlight",
                    "description": "",
                    "extensions": {
                        "iconName": "icon-dp_light",
                        "attribute": "128"
                    },
                    "name": "背光开关",
                    "typeSpec": {
                        "type": "bool",
                        "typeDefaultValue": false
                    }
                }
            ]
        }
    ]
}

**Comment by make-all** [comment]
Sorry, I just noticed your comment after making the config.  I think the main difference from existing fans is that this one has a 1-100 range for the fan speed, matching Home Assistant, which is quite unusual for Tuya fans.  Otherwise it is broadly similar to other fan/light combos.

**Comment by xDAVIDx93** [comment]
@Levanterman @make-all this is the exact same fan light switch I have 

Link to device request 
https://github.com/make-all/tuya-local/issues/3037

was this device compatible or not I can’t tell from the messages in here??

**Comment by make-all** [comment]
It appears from the product id to be the same device, so if you are able to resolve your connection problems, it should work.

**Comment by xDAVIDx93** [comment]
I’m not really sure what I’m doing wrong. I’m able to add normal Moes light switches via SmartLife cloud assisted device set up and as you can see in the links below, I can see/add the fan light switches, but when I go to connect it fails I have also tried the auto protocol version and poll only still no luck..

[https://ibb.co/tpJ7m6xH
https://ibb.co/b54ysQjf
https://ibb.co/gh5ShJw](url)

Any troubleshooting you could advise of I’d really love to get these working. I have 9 Moes fan lights which is in my home.

**Comment by xDAVIDx93** [comment]
Well, I’m not sure what changed, but I tried again to add them and now it works added under “yidi fan light switch” so if you wanted to add Moe’s house fan light switch is supported you could 👍👍

![Image](https://github.com/user-attachments/assets/813c613b-b629-467b-a669-8d9e12286337)
![Image](https://github.com/user-attachments/assets/701f5c73-5e69-4410-8c1a-61b302dc790e)
